apache/beam

.test-infra/jenkins/job_PreCommit_BeamSQL_ZetaSQL_Java11.groovy
.test-infra/jenkins/job_PreCommit_Java_Examples_Dataflow_Java11.groovy
.test-infra/jenkins/job_PreCommit_Java_PortabilityApi_Java11.groovy
.test-infra/jenkins/job_PreCommit_SQL_Java11.groovy

This works around kelloggm/checkerframework-gradle-plugin#117
The plugin bases its configuration in part on what JVM Gradle runs during
configuration, which is JRE8 currently. Specifically it sets -Xbootclasspath/p
seemingly because:
- the Gradle JVM used during configure is version 8
- the source level is 8
- Checker version is >= 3
Fix TBD but likely a minor change to the plugin.
Since checker is a source-level analysis we do not need to run it redundantly in Java 11 builds.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-eas …

Disable checker in Java 11 builds

---

sdks/go/pkg/beam/create_test.go

This PR adds missing tests for the beam.CreateList function.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-bea …

Improve beam CreateList test coverage

---

website/www/site/content/en/documentation/transforms/python/aggregation/latest.md
website/www/site/content/en/documentation/transforms/python/overview.md
website/www/site/layouts/partials/section-menu/en/documentation.html

Add `Latest` code snippets.
R: @aaltay
R: @rosetn
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/12394/documentation/transforms/python/aggregation/latest/index.html
Go | [![Build …

[BEAM-7390] Add latest code snippets

---

sdks/go/pkg/beam/create.go
sdks/go/pkg/beam/create_test.go

This PR allow to pass an empty list to the beam.CreateList function.
Please merge #12373 before this. …

Support creation of empty PCollection in beam CreateList

---

sdks/go/pkg/beam/transforms/stats/count.go
sdks/go/pkg/beam/transforms/stats/count_test.go

The documentation says
> CountElms counts the number of elements in a collection.
> It expects a PCollection<T> as input and returns a PCollection<int> of **one element** containing the count.
If the input is an empty PCollection<T> the output is empty as well.
This is probably an intended behaviour (Is the behaviour consistent across sdks?), and in case feel free to close this (but I feel that we should document it).
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci- …

Fix go count on an empty pcollection

---

sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/README.md
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/jest.config.js
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/package.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/kernel/KernelModel.test.ts
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/kernel/KernelCode.ts
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/kernel/KernelModel.ts
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/tsconfig.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/yarn.lock

1. Added a KernelModel module that handles messaging between the
frontend and the connected kernel. The model silently executes code in the kernel and handles IOPub responses from the kernel for information of the current interactive environment. UI components and other data models can use this module as a data model to communicate with the kernel. When instantiated, this model does not have to be a singleton.
2. Integrated jest test framework with typescript.
3. Advanced prettier to 1.19 so that it can parse typescript optional
chaining syntax.
4. The tests can be executed with `jlpm jest`. Test details see README.
5. Changes made by jlpm are:
jlpm add --dev jest @types/jest ts-jest identity-obj-proxy
jlpm upgrade prettier@^1.19.0 …

[BEAM-10545] KernelModel and jest tests

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/runtime/harness/harness.go
sdks/go/pkg/beam/core/runtime/harness/logging.go
sdks/go/pkg/beam/options/jobopts/options.go
sdks/go/pkg/beam/runners/universal/extworker/extworker.go
sdks/go/pkg/beam/runners/universal/extworker/extworker_test.go
sdks/go/pkg/beam/runners/universal/universal.go
sdks/go/pkg/beam/util/grpcx/dial.go

This allows loopback mode to be supported in the Go SDK. This is useful for validating pipelines against real portable runners such as Flink, Spark, and the Python Portable runner. 
This PR also fixes some smaller  bugs around logging, discovered through testing.
* Missing newlines when printing unsent log messages to the local machine.
* A small race condition when the control channel terminates prevented orderly shutdown of workers.
* Cleans up [BEAM-9982], and removes the redundant MustMarshal function from graphx.
* Increases the default GRPC recv limit to it's maximum. Testing indicates that this only leads to memory overage if the inputs are actually large, and unnecessarily restricts pipeline data.
Loopback mode allows for convenient testing of pipelines, such as avoiding needing …

[BEAM-10610][BEAM-9982] Support Loopback mode with universal runners in the Go SDK.

---

buildSrc/build.gradle
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

This PR:
- upgrades the Spotbugs plugin to the most recent that works with our version of Gradle [1]
- upgrades Spotbugs to the latest [2]
- inlines most of `spotbugs-filter.xml` to annotations on the code it is about [3]
Read footnotes if you care about why...
[1] In #12376 removing rawtypes created new Spotbugs null errors in the expansion service module. But checker is enabled there, so Spotbugs is irrelevant. So I went down a rabbit hole of trying to pass `omitVisitors` to disable the null-related checks via the Spotbugs gradle plugin. I upgraded the plugin to get it working.
[2] Just randomly in my attempt to get the above working, I also tried upgrading Spotbugs. It caught a bunch of new errors and seemed mostly useful to upgrade. So I decided to do it.
[3] I realized I don't need …

Upgrade spotbugs from 3.1.12 to 4.0.6, spotbugs gradle plugin from 2.0.0 to 3.0.0

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/ParDo_Load_Tests.json

The Grafana dashboard is currently missing Python load test metrics:
http://metrics.beam.apache.org/d/MOi-kf3Zk/pardo-load-tests?orgId=1&var-processingType=streaming&var-sdk=python
Before:
After:
Note that the latency metrics aren't yet populated in the backup InfluxDB I was using to create the dashboard. They were added recently. …

[BEAM-10602] Display Python streaming metrics in Grafana dashboard

---

sdks/python/apache_beam/runners/direct/evaluation_context.py
sdks/python/apache_beam/runners/direct/executor.py
sdks/python/apache_beam/runners/direct/test_stream_impl.py
sdks/python/apache_beam/runners/direct/transform_evaluator.py

Change-Id: I1b25694c2f8f52d5335da889610ae1871deb0917
PR 1/7
When the DirectRunner gets canceled, there is no signal to pass to the evaluation context to gracefully shut it down. The TestStreamImpl starts a long-lived GRPC thread that needs to be terminated when the runner shuts down.
Lang | SDK | Dataflow | Flink | Samza | Spark | …

[BEAM-10603] Gracefully stop the TestStream RPC if the job stops.

---

sdks/python/apache_beam/io/external/xlang_jdbcio_it_test.py

Jdbc cross-language python test is flaky due to testcontainer's boot failure. I added retries to starting the container as it is in testcontainer's java sdk for Postgres and ignore the exception if it was raised in stop() function in the test's tearDown.
--- | --- | --- | --- …

[BEAM-10591] Fix flaky xlang jdbc test

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/ParDo_Load_Tests.json

Somehow the latency results are missing from the python_streaming_pardo_6
table. It is better though to retrieve the latency metrics from the
python_streaming_pardo_5 table because it gives a better base line with
checkpointing disabled.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/be …

[BEAM-10602] Use python_streaming_pardo_5 table for latency results

---

website/www/site/content/en/documentation/transforms/python/aggregation/max.md
website/www/site/content/en/documentation/transforms/python/overview.md
website/www/site/layouts/partials/section-menu/en/documentation.html

Add `Max` code snippets.
R: @aaltay
R: @rosetn
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/12409/documentation/transforms/python/aggregation/max/index.html
Go | [![Build …

[BEAM-7390] Add max code snippets

---

website/www/site/content/en/documentation/transforms/python/aggregation/mean.md

Add `Mean` code snippets.
R: @aaltay
R: @rosetn
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/12437/documentation/transforms/python/aggregation/mean/index.html
Go | [![Build …

[BEAM-7390] Add mean code snippets

---

sdks/python/apache_beam/runners/interactive/background_caching_job.py
sdks/python/apache_beam/runners/interactive/background_caching_job_test.py
sdks/python/apache_beam/runners/interactive/interactive_environment.py
sdks/python/apache_beam/runners/interactive/interactive_environment_test.py
sdks/python/apache_beam/runners/interactive/messaging/interactive_environment_inspector.py
sdks/python/apache_beam/runners/interactive/options/capture_control.py

1. Completed the cleanup routine for all internal states held by the
current interactive environment.
2. Utilized the environment inspector to determine whether a pipeline is
out of scope: not assigned to variable and has no inspectable
PCollections.
3. Invoked the cleanup every time the user defined pipelines in watched
scope are refreshed. …

Interactive: clean up when pipeline is out of scope

---

sdks/python/apache_beam/runners/interactive/display/pcoll_visualization.py

The datatable now displays some info when there is no data and renders
datatable when data comes in for continuously updated visualization.
The problem was:
1. If the pcoll returns empty data for a streaming pipeline, it will cause
the header of the datatable to container only the index column. 
2. The original `update_display` approach cannot modify the HTML part
of the datatable. Later when updating, if data is not empty, new rows are
added but there are no columns to display those data. …

Fixed pcoll visualization in datatable

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaTest.java

Schema#indexOf uses String.format to prepare error message.
It causes performance issues if schema has options, because
Schema.Options#toString allocates TreeMap.
Use formatter built-in into Preconditions that is lazy, and
doesn't call Schema#toString unless needed.
--- | --- …

[BEAM-10631] Fix performance of Schema#indexOf

---

sdks/python/apache_beam/runners/portability/flink_runner.py
sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/flink_uber_jar_job_server.py
sdks/python/apache_beam/runners/portability/spark_runner.py
sdks/python/apache_beam/runners/portability/spark_runner_test.py
sdks/python/apache_beam/runners/portability/spark_uber_jar_job_server.py
sdks/python/apache_beam/utils/subprocess_server_test.py

When using the FlinkRunner with master, the job server needs to be build
first. Beam prints out instructions for that, e.g.
```
RuntimeError: /Users/max/Dev/beam/runners/flink/1.10/job-server/build/libs/beam-runners-flink-1.10-job-server-2.24.0-SNAPSHOT.jar not found. Please build the server with
cd /Users/max/Dev/beam; ./gradlew runners:flink:1.10:job-server:shadowJar
```
Note that the gradle path printed is not valid because it misses a colon before
"runners".
Internally, the Gradle path is used to resolve the jar locally or from Maven
Central. Gradle paths always start with a colon. We should stick to that format
although we can also parse Gradle paths which do not start with a colon.
In order for the Gradle path printed to be valid, we should prefix Gradle path
with colon.
Post-Commit …

[BEAM-10622] Prefix Gradle paths with a colon for user-facing output

---

sdks/python/apache_beam/runners/interactive/options/capture_limiters.py
sdks/python/apache_beam/runners/interactive/options/capture_limiters_test.py

Change-Id: I9f7030999f2ce38073ca72512c71794dbdbc301e
PR 2/7
This will allow for the cache to stop reading based on elements. Currently, the cache can only stop based on global configuration.
Go | [![Build …

[BEAM-10603] Add ElementLimiters which allows the cache to prematurely based on read elements.

---

runners/direct-java/src/main/java/org/apache/beam/runners/direct/DirectRunner.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/DirectRunnerTest.java

More direct runner updates to handle null (fixes a NullPointerException introduced by #11275)
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_Post …

[BEAM-10470] Handle null state from waitUntilFinish

---

sdks/python/apache_beam/utils/subprocess_server.py

AF_INET fails in IPv6-only environments:
```
../apache_beam/utils/subprocess_server.py", line 294, in find_free_port
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
File "<embedded stdlib>/socket.py", line 144, in __init__
_socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
``` …

[BEAM-10618] subprocess_server.py: Fallback to AF_INET6 family when finding free port

---

sdks/python/apache_beam/testing/test_stream_service.py
sdks/python/apache_beam/testing/test_stream_service_test.py

Fixed the start/stop logic so that a controller:
1. can only be started/stopped once;
2. can only be stopped when is started while never stopped before;
3. does not hang indefinitely but noop for redundant or invalid start/stop calls.
Go …

[BEAM-10637] fix: test stream service start/stop

---

sdks/python/apache_beam/utils/shared.py
sdks/python/apache_beam/utils/shared_test.py

This PR mirrors tensorflow/tfx-bsl#12 and adds a tag to the shared object utility.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark …

Migrate shared tag from tfx-bsl

---

sdks/go/pkg/beam/core/graph/coder/map.go
sdks/go/pkg/beam/core/graph/coder/map_test.go
sdks/go/pkg/beam/core/graph/coder/row.go
sdks/go/pkg/beam/core/graph/coder/row_test.go

Adds the Beam Schema map coding and container nil handling to the Go SDK, per https://github.com/apache/beam/pull/12426. 
While independent, this should probably not merge until that PR is finalized.
Go | [![Build …

[BEAM-7996] Add map & nil encoding to Go SDK.

---

sdks/go/pkg/beam/core/runtime/graphx/schema/schema.go
sdks/go/pkg/beam/core/runtime/graphx/schema/schema_test.go

Adds initial Schema to Go type conversions and vice versa.
In particular, handles the "easy" stuff: basic struct to Row conversion, Slices, and maps, basic field name conversions.
Doesn't implement struct+schema compatibility comparisons, which are necessary at pipeline construction time, however, this is more than sufficient to allow other immediately incoming code to unlock the row coder tests in standard_coders.yaml. …

[BEAM-9615] Add initial Schema to Go conversions.

---

website/www/site/content/en/contribute/release-guide.md

In the past, we have seen performance regressions in releases. We should make
sure that the release guide includes checking available performance
measurements. …

[BEAM-10630] Include data from load tests in the release process

---

sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/bigquery_tools_test.py

This enables to look for location in BigQueryWrapper for first available referenced table for the user. If you are querying authorised view, you may end up with permission error of accessing referenced table that is in authorised view and be unable to retrieve location, so you should look on next available table for You that you should have permission. …

[BEAM-10647] Fixes get_query_location bug in BigQueryWrapper

---

.github/workflows/build_wheels.yml
scripts/ci/ci_check_are_gcp_variables_set.sh

I want to propose a different approach for making GitHub Actions workflow runnable on the forks.
Some of the jobs requires GCP variables stored as secrets to perform operations like uploading wheels to GCS.
Currently these jobs are filtered based on the condition `github.repository_owner == 'apache'`.
I introduced shell script which checks are these variables are set and echos some information about them.
Later job filtering is based on the output returned by this check.
PR which introduced gating:
[Gate GH actions so it only runs in main/upstream repo](https://github.com/apache/beam/pull/12222)
Inspired by Apache Airflow ci workflow:
https://github.com/apache/airflow/blob/master/.github/workflows/ci.yml#L111
Depends on depends on https://github.com/apache/beam/pull/12405 …

GH-Actions workflow checks are GCP variables set [depends on BEAM-10599]

---

runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/ValidateRunnerXlangTest.java
sdks/python/apache_beam/transforms/validate_runner_xlang_test.py

Added documentation, to both the [java](https://github.com/apache/beam/blob/master/runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/ValidateRunnerXlangTest.java) and [python](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/transforms/validate_runner_xlang_test.py) equivalents, explaining the design of the test suite tasked with validating a cross-language runner. It is directly inspired from [Runner Validation Test Plan for Cross-language transforms](https://docs.google.com/document/d/1xQp0ElIV84b8OCVz8CD2hvbiWdR8w4BvWxPTZJZA6NA/edit?usp=sharing).
This pull request serves as a replacement for the [original](https://github.com/apache/beam/pull/12071) to correct for botched git workflows. It contains only the cherry picked latest and …

[BEAM-9932] Adding documentation to describe cross-language test pipelines

---

sdks/python/apache_beam/runners/interactive/cache_manager.py
sdks/python/apache_beam/runners/interactive/cache_manager_test.py
sdks/python/apache_beam/runners/interactive/caching/streaming_cache.py
sdks/python/apache_beam/runners/interactive/caching/streaming_cache_test.py
sdks/python/apache_beam/runners/interactive/options/capture_limiters.py
sdks/python/apache_beam/runners/interactive/options/capture_limiters_test.py
sdks/python/apache_beam/runners/interactive/testing/test_cache_manager.py

Change-Id: I093e1dc1f99c31b1e0bb868fc3bcfc507bd24c8d
PR 3/7
This builds on https://github.com/apache/beam/pull/12411 to utilize the ElementLimiters to stop reading from cache. This also adds the ability for caches to clear single PCollections.
--- | --- | --- | --- | --- | --- …

[BEAM-10603] Add ElementLimiters to all Cache Managers.

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/bigquery/BeamSqlUnparseContext.java
sdks/python/apache_beam/dataframe/expressions.py

R: @apilloud 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/la …

Fix precommit errors

---

sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/doctests_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

The report looks like this when run with `pytest -s`:
```
apache_beam/dataframe/pandas_doctests_test.py 829 total test cases.
722 will implement, 107 won't implement.
257 skipped.
69.0% (572/829) of all test cases pass or raise WontImplementError
.676 total test cases.
631 will implement, 45 won't implement.
265 skipped.
60.8% (411/676) of all test cases pass or raise WontImplementError
``` …

[BEAM-10619] Report ratio of implemented pandas tests

---

sdks/go/pkg/beam/core/runtime/harness/harness.go

Should be checking for nil-ness in the primary/residual elements.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild …

[BEAM-10289] Fixing bug in Go harness split response.

---

runners/flink/flink_runner.gradle
runners/spark/build.gradle

Tests were added as part of #11924 that fail on Spark and Flink.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ …

[BEAM-8460] Exclude category containing failing tests for spark/flink to restore green test signal.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOUtils.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSourceDescriptor.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOUtilsTest.java

This is the basic implementation of `ReadFromKafkaViaSDF`.
Supports included in this implementation:
- Initial restriction
- Progress and size
- Checkpoint
Future worker includes:
- Add `CommitOffsetTransform` and expand `ReadFromKafkaViaSDF` with it when `commitOffset()` is enabled: [BEAM-10123](https://issues.apache.org/jira/browse/BEAM-10123)
- Make it work with x-lang both for `KafkaIO.Read` when `useSDFTransform()` is enabled and using `ReadFromKafkaViaSDF` directly. 
- Provide a new API `withTopicPattern` for `KafkaIO.Read` . This can be done by adding another SDF which watches growth of topics.
Any other proposal of future works are welcomed : )
r: @aromanenko-dev(assuming you are interested in this : ) )
r: @lukecwik  …

[BEAM-9977] Implement ReadFromKafkaViaSDF 

---

sdks/java/extensions/sql/datacatalog/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datacatalog/BigQueryTableFactory.java
sdks/java/extensions/sql/datacatalog/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datacatalog/PubsubTableFactory.java

There are a couple of instances in the code where toLowerCase().equals() is used, when equalsIgnoreCase() would suffice. The latter is more concise + also doesn't involve the default Locale that's used with toLowerCase(), which might be problematic depending on the String being compared.

[BEAM-10668] Replace toLowerCase().equals() with equalsIgnoreCase

---

sdks/java/io/cassandra/src/test/java/org/apache/beam/sdk/io/cassandra/CassandraIOTest.java

[BEAM-10471] change the test condition for testEstimatedSizeBytes to greater than 0 to ensure that the dataset is a least split.

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamZetaSqlCalcRel.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/DateTimeUtils.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/SqlAnalyzer.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlBeamTranslationUtils.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlCalciteTranslationUtils.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/AggregateScanConverter.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/ExpressionConverter.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/SqlOperators.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlBeamTranslationUtilsTest.java

[Simplification] Type translation code refactor:
1. Move ZetaSQL => Calcite value translation logic from ExpressionConverter to ZetaSqlCalciteTranslationUtils
2. Move helper methods for ZetaSQL => Calcite time-related value translation from DateTimeUtils to ZetaSqlCalciteTranslationUtils
3. Rename methods in ZetaSqlCalciteTranslationUtils and ZetaSqlBeamTranslationUtils to be simpler; and inline excessive helper methods
r: @apilloud 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apac …

[BEAM-9179] Move value conversion logic out of ExpressionConverter

---

build.gradle
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/amazon-web-services/build.gradle
sdks/java/io/amazon-web-services2/build.gradle
sdks/java/io/kinesis/build.gradle
sdks/java/io/kinesis/src/main/java/org/apache/beam/sdk/io/kinesis/BasicKinesisProvider.java
sdks/java/io/kinesis/src/main/java/org/apache/beam/sdk/io/kinesis/KinesisIO.java
sdks/java/io/kinesis/src/test/java/org/apache/beam/sdk/io/kinesis/KinesisIOIT.java
sdks/java/io/kinesis/src/test/java/org/apache/beam/sdk/io/kinesis/KinesisTestOptions.java

I've done this by the way of writing cross-language integration tests.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompleted …

[BEAM-601] Run KinesisIOIT with localstack

---

sdks/java/extensions/sql/datacatalog/build.gradle
sdks/java/extensions/sql/datacatalog/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datacatalog/DataCatalogTableProvider.java
sdks/java/extensions/sql/datacatalog/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/datacatalog/DataCatalogBigQueryIT.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/BeamCalciteSchema.java

Fixing the nullability issues for sub-module sdks:java:extensions:sql:datacatalog
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/la …

[BEAM-10572] Eliminate nullability errors from :sdks:java:extensions:sql:datacatalog

---

sdks/python/apache_beam/io/external/xlang_kafkaio_it_test.py

Enable again when  BEAM-10663 is merged
R: @TheNeuralBit @boyuanzz 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https …

[BEAM-10663] Disable python kafka integration tests

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSourceDescriptor.java

[BEAM-10663] Workaround of AutoValueSchema doesn't work with SchemaFieldName

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py

Consider results from this analysis: https://docs.google.com/document/d/1s8VRkN4qKdgGkDOZQiwowmD3GVyVV9UskJQwTdKfRCE/edit#
This change helps increase EPS per worker from ~100 to >1000 per worker.
Also improves documentation and telemetry.
--- | --- | --- | --- | --- | --- | …

[BEAM-6064] Improvements to BQ streaming insert performance

---

model/pipeline/src/main/proto/external_transforms.proto
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/ValidateRunnerXlangTest.java
sdks/java/expansion-service/build.gradle
sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java
sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOExternalTest.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java
sdks/python/apache_beam/io/kafka.py
sdks/python/apache_beam/runners/portability/expansion_service_test.py
sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/transforms/external_test.py
sdks/python/apache_beam/transforms/external_test_py3.py
sdks/python/apache_beam/transforms/external_test_py37.py

- 16bc9bb: The bulk of the change. Changes external_transform.proto to encode a Schema and a Row, and modifies Java's ExpansionService, and Python's SchemaBasedPayloadBuilders, to use the new representation.
- 5ff29d8: Changes related to KafkaIO. Since KV is not supported in schemas, KafkaIO configuration types are changed to use `Map<String, String>` instead of `List<KV<String, String>>`. Also updates references to external_transform.proto in KafkaIOExternalTest.
- 0ef3701: Updates references to external_transform.proto in PubsubIOExternalTest.
- b8936db: Updates references to external_transform.proto in XVR test fixtures (Java and Python).
Some notes about the implementation:
- Since KV is not supported by Rows, I've updated the tests that used them in this context to use a Map instead. …

[BEAM-10571] Use schemas in ExternalConfigurationPayload

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/DateTimeUtils.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlBeamTranslationUtils.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlCalciteTranslationUtils.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlBeamTranslationUtilsTest.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlTimeFunctionsTest.java

Simplify getting/creating ZetaSQL values using the new API. Also improves performance because we can avoid unnecessary conversions.
r: @apilloud @ZijieSong946  …

[BEAM-10611] Simplification: Use new ZetaSQL API to get/create Values

---

.test-infra/jenkins/job_LoadTests_ParDo_Flink_Python.groovy
.test-infra/metrics/grafana/dashboards/perftests_metrics/ParDo_Load_Tests.json

This reverts the recent changes to the dashboards and adds a commit which adds a latency and checkpoint duration panel.
Also, it modifies the Flink streaming tests to write into the `_pardo_1` table. This way, the results will show up in the dashboard together with all the other Runners' data.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastComp …

[BEAM-10602] Fix load test metrics in Grafana dashboard

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOUtils.java
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/SqlTransformRunner.java

Fix some typos found during code import to Google codebase.
r: @aaltay @kennknowles 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/bad …

Fix some typos

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcTransformsRegistrar.java

Jdbc cross-language was broken after recent upgrades to cross-language. This PR fixes it.
I suppose it should be a blocker to the 2.24 release.
R: @chamikaramj  @TheNeuralBit @mxm 
Go | [![Build …

[BEAM-10684] Fix jdbc cross-language transform

---

sdks/python/apache_beam/runners/interactive/utils.py
sdks/python/apache_beam/runners/interactive/utils_test.py

Change-Id: I9a2fbf1532b3d22a612e7a09f4f1fb2b9635c40b
PR 4/7
Reading elements from cache can yield TestStreamFileRecords which can have many elements that exceeds the requested element count.
This also adds functionality to decode more types of elements (WindowedValueHolder and "Any").
Lang | SDK | Dataflow | Flink | Samza | Spark | …

[BEAM-10603] Add max count to utils.to_element_list

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlCalciteTranslationUtils.java

https://github.com/apache/beam/pull/12507 revealed a bug related to duplicate STRUCT field name. This PR fix it by following the same way that BigQuery handles unspecified or duplicate field name.
r: @apilloud 
cc: @youngoli (2.24 release manager, this is a fix for a previous PR)
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/bad …

Follow the same way that BigQuery handles unspecified or duplicate ZetaSQL STRUCT field name

---

.test-infra/jenkins/CommonJobProperties.groovy
sdks/python/setup.py
sdks/python/test-suites/tox/common.gradle
sdks/python/test-suites/tox/py38/build.gradle
sdks/python/tox.ini

This PR enables the generation of Python coverage reports during pre-commit in the `py38-cloud` Tox environment.
- The resultant reports are uploaded to `codecov.io`, as can be seen [here](https://codecov.io/gh/saavannanavati/beam/tree/7e9d684698adbe2654fb59a734553c4f1682c356/sdks/python/apache_beam).
- To work on the live testing infrastructure, an environment variable `CODECOV_TOKEN` must be defined on Jenkins with a value that can be found [here](https://codecov.io/gh/apache/beam/).
The full design document related to this PR can be found [here](https://docs.google.com/document/d/1K6zEJnDNvk7TkqDEPwoIa7NTj5KxtUIdq-TGewUgpmo/edit).
See the …

[BEAM-2762] Generate Python coverage reports during pre-commit

---

sdks/python/apache_beam/runners/interactive/background_caching_job.py
sdks/python/apache_beam/runners/interactive/background_caching_job_test.py

Change-Id: I52a4f36b09e6f6899d7c59756c9702ba983e083b
PR 5/7
The logic to stop reading from cache was incorrect and did not properly stop if the cache changed.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCom …

[BEAM-10603] Fix BCJ to stop caching when the cache signature has changed.

---

sdks/go/pkg/beam/core/runtime/harness/logging.go

Make the logging connection cleanly shut down when an EOF is received from the GRPC connection. EOF indicates that the connection was shutdown by the remote end, so we should similarly shut down on our end.
This is valuable in loop back mode where we see more of the worker side of logging.
Also, make the "emergency" local log to STDERR more legible vs simply printing the proto struct. …

[BEAM-10610] Clean logging cruft from loopback mode.

---

sdks/go/pkg/beam/core/runtime/harness/harness.go

Not much to elaborate on. This TransformID is technically required by the proto but wasn't used until now, but I ran into some problems when using it with the FnAPI runner, so I'm adding it.
Go | [![Build …

[BEAM-10289] Adding required transform ID to Go channel split.

---

sdks/python/apache_beam/runners/worker/bundle_processor.py
sdks/python/apache_beam/runners/worker/bundle_processor_test.py
sdks/python/apache_beam/transforms/timeutil.py

By default, the Python SDK adds a timer output timestamp equal to the current
timestamp of an element. This is problematic because:
1. We hold back the output watermark on the current element's timestamp for
every timer
2. It doesn't match the behavior in the Java SDK which defaults to using the
fire timestamp as the timer output timestamp (and adds a hold on it)
3. There is no way for the user to influence this behavior because there is no
user-facing API
We should use the fire timestamp as the default output timestamp.
Go | [![Build …

[BEAM-10676] Use the fire timestamp as the output timestamp for timers

---

runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/KeyedTimerData.java
runners/samza/src/test/java/org/apache/beam/runners/samza/runtime/KeyedTimerDataTest.java

`KeyedTimerDataCoder` doesn't actually encode the `outputTimestamp` separately, instead re-using the `timestamp` when decoding. This leads to occasional flakes when the two `new Instant()` instances created in the test are different.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_P …

[BEAM-10500] Make KeyedTimerDataCoder encode output timestamp

---

sdks/python/apache_beam/metrics/metric.py

by no requiring both namespace and name to be correct, when both of them are supplied, the filter does not filter out non-exact matches. So now when both name and namespaces are provided, True is only returned when both namespace and name are matched.
--- | --- | --- | --- | …

fix logic issue in metric name namespace filtering

---

sdks/python/apache_beam/io/gcp/bigquery_tools.py

Better error on BQ schema parse

---

sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/.eslintrc.js
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/.prettierrc.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/package.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/common/HtmlView.test.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/kernel/KernelModel.test.ts
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/common/HtmlView.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/tsconfig.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/yarn.lock

1. Added a HtmlView module to render given HTML and execute given
scripts from the provider model.
2. Integrated react framework to the jest testing framework and eslint.
3. Added line length limit (80) to eslint and prettier. Note prettier's
printWidth is not a hard limit as max-len rule. Sometimes, the code
needs to be written in a specific way to meet both eslint and
prettier. An example, long strings (if not url) should be broken into
suitable pieces.
4. The jlpm(yarn/npm) installations are:
jlpm add --dev react-dom @types/react-dom eslint-plugin-react
5. @types/react is resoluted to the version bundled with jupyter
apputils. …

[BEAM-10545] HtmlView module

---

sdks/python/apache_beam/runners/portability/artifact_service.py
sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/test-suites/portable/common.gradle

Context: https://issues.apache.org/jira/browse/BEAM-10702
Looks like the artifact service started with `--job_endpoint=embed` uses `FileSystems.open` to read the artifacts to be staged, which by default decompresses the artifacts if they are compressed. PIP packages are compressed as .tar.gz, so when the worker container retrieves the PIP packages to install, they see .tar.gz files whose contents is actually the underlying .tar file.
I would appreciate guidance for where to add tests for this.
* `artifact_service_test` uses an in-memory file reader fn that doesn't actually share the code being used in production. Should I change that?
* `worker_handlers_test` does not exist - there's `fn_runner_test.py` in that directory but I'm not sure how to test the artifact staging codepath via …

[BEAM-10702] Do not implicitly decompress artifacts

---

sdks/python/apache_beam/runners/interactive/interactive_environment.py
sdks/python/apache_beam/runners/interactive/interactive_environment_test.py

Change-Id: I271efeef53f99c8083a6d37b89085cddd63bf56a
The code in the InteractiveEnvironment was manipulating the _computed_pcollections set while iterating.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompl …

[BEAM-10695] Fix InteractiveEnvironment cannot evict PCollection

---

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/WindowDoFnOperatorTest.java

This seems to fix the issue in my pipeline. Not sure if this is the best solution, yet. This PR is for discussion.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apa …

[BEAM-10691] Use FlinkStateInternals#addWatermarkHoldUsage for timer output timestamp

---

sdks/go/gogradle.lock
sdks/go/pkg/beam/core/runtime/graphx/schema/schema.go
sdks/go/pkg/beam/core/runtime/graphx/schema/schema_test.go

* Add a schema.RegisterType method to preconvert user types to schema generated synthetic types, and be able to map them back to user types.
* Add an schema option to indicate that the top level schema should be interpreted as a proto.
* Add a field option to indicate whether a given int64 should actually be a go int.
* Same for maps, arrays, and slice types. …

[BEAM-9615] Map user types to Schema reps.

---

build.gradle
sdks/go/gogradle.lock

Update the dependencies one further since the precommit is apparently less stringent on build deps than the postcommit.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-bea …

Fix broken build.

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FnApiDoFnRunnerTest.java

This PR scales the progress when observing windows. 
r: @lukecwik 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuil …

[BEAM-10303] Scale progress with respect to windows observation.

---

CHANGES.md
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/SplittableParDo.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/SplittableParDoTest.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/DirectRunner.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/ImmutabilityEnforcementFactory.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/BoundedReadEvaluatorFactoryTest.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/DirectGraphVisitorTest.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/DirectRunnerTest.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/EvaluationContextTest.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/UnboundedReadEvaluatorFactoryTest.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/WatermarkManagerTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/Read.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/AvroIOTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TFRecordIOTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageQueryTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOExternalTest.java

[BEAM-10670] Make Read execute as a splittable DoFn by default for the Java DirectRunner.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java

cherry-pick https://github.com/apache/beam/pull/12577
(cherry picked from commit d2b2d9d992199b7f2a47c7650df6d91b02ae8eba)
Go | [![Build …

[BEAM-10698] Use unbounded wrapper for Kafka Read.

---

sdks/python/test-suites/tox/py2/build.gradle

Removing this specific target since it has been flaky.
Remainder work for removing Python 2.7 support is tracked
in https://issues.apache.org/jira/browse/BEAM-7372.
Go | [![Build …

[BEAM-10697] Remove testPy2Cython from precommit

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/AvroIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/AvroSink.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/ConstantAvroDestination.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/DynamicAvroDestinations.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/AvroIOTest.java

Similar to #11641 and #11479, this change allows configuring the IO to use custom DatumWriter implementations.
R: @iemejia @RyanSkraba 
- [] Update `CHANGES.md` with noteworthy changes.
Go | [![Build …

[BEAM-10523] Add support for custom DatumWriters to AvroIO.Write

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build_wheels.yml
.github/workflows/python_tests.yml
CI.md
README.md
scripts/ci/ci_check_are_gcp_variables_set.sh
sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/io/parquetio_test.py
sdks/python/apache_beam/runners/interactive/interactive_beam_test.py
sdks/python/apache_beam/runners/interactive/interactive_runner_test.py
sdks/python/apache_beam/runners/portability/portable_runner_test.py
sdks/python/apache_beam/runners/worker/log_handler_test.py
sdks/python/apache_beam/testing/datatype_inference_test.py
sdks/python/apache_beam/typehints/typecheck_test_py3.py
sdks/python/gen_protos.py
sdks/python/tox.ini

Workflow run with python tests
* `GCP_TESTING_BUCKET` -  beam-github-actions-tests
* `GCP_PROJECT_ID` -  apache-beam-testing
* `GCP_REGION` - us-central1
* Storage Admin (`roles/storage.admin`)
* Dataflow Admin (`roles/dataflow.admin`) …

[BEAM-10623] Add workflow to run Beam python tests on Linux/Windows/Mac platforms

---

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

To reduce teststream flakiness on dataflow runner. …

Bump up advanceProcessingTime duration in ParDoTest

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOReadIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadIT.java

Currently a lot of these tests take ~30 seconds on my machine which means that it is likely to flake since the timeout is on the same order of magnitude as the current test.
Go | [![Build …

[BEAM-10040, BEAM-6804] Increase wait times to reduce flakiness. 

---

sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/PubsubToBigqueryIT.java

Adding the use_deprecated_read experiment temporarily to fix SQL PostCommit, as SDF seems to break these tests.
R: @robinyqiu 
CC: @lukecwik  …

[BEAM-10752] add use_deprecated_read experiment for testSimpleInsert, testSimpleInsertFlat

---

sdks/go/pkg/beam/runners/dataflow/dataflowlib/messages.go
sdks/go/pkg/beam/runners/dataflow/dataflowlib/translate.go

This just means including the RestrictionEncoder. …

[BEAM-3301] Adding SDF Go Dataflow translation.

---

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystem.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/s3/S3FileSystem.java

A few small things I came across while working on the Azure filesystem.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComplete …

clarifying unclear comments in filesystems

---

CHANGES.md
sdks/python/apache_beam/runners/portability/artifact_service.py
sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/container/license_scripts/dep_urls_py.yaml
sdks/python/container/license_scripts/manual_licenses/enum34/LICENSE
sdks/python/test-suites/portable/common.gradle

Also adds a Julia set test on portable local runner, which uses a
setup.py and hence exercises the artifact staging codepath.
This is a squashed cherrypick of https://github.com/apache/beam/pull/12571 + a change to CHANGES.md.
I also added the LICENSE for enum34 to manual_licenses as the original repo is down. I took the license from somebody's backup: https://github.com/jamespharaoh/python-enum34
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCom …

[BEAM-10702, BEAM-10757] Cherrypick #12571: Do not implicitly decompress artifacts

---

.test-infra/jenkins/job_LoadTests_coGBK_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_coGBK_Python.groovy
sdks/python/apache_beam/testing/load_tests/co_group_by_key_test.py

Add CoGBK load test with streaming mode for Dataflow Python SDK.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ …

[BEAM-10674] Add Python CoGBK load test for streaming on Dataflow

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/DefaultFilenamePolicy.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/LocalFileSystem.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/LocalResourceId.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/DefaultFilenamePolicyTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/LocalFileSystemTest.java

`DefaultFilenamePolicy.ParamsCoder` used `StringUtf8Coder` for encoding/decoding `baseFilename` and therefore information whether `baseFilename resourceID` is file or directory was lost. Using  `ResourceIdCoder` instead fixes this issue.
Lang | SDK | Dataflow | Flink | Samza | Spark
--- | --- | --- | --- | --- | ---
Go | [![Build …

[BEAM-10292] DefaultFilenamePolicy.ParamsCoder is not able to decode directory on the local file system

---

sdks/python/apache_beam/runners/portability/portable_runner_test.py

The default pytest timeout is 600s. Once all portable runner tests are migrated to pytest, we can use the pytest timeout instead of portable_runner_test's bespoke implementation. See #12385.
R: @udim 
Go | [![Build …

[BEAM-9118] Increase portable_runner_test timeout.

---

sdks/go/pkg/beam/core/runtime/exec/datasource.go
sdks/go/pkg/beam/core/runtime/exec/datasource_test.go

[BEAM-10289] Fixing miscalculated SDF split fraction.

---

sdks/python/apache_beam/coders/row_coder.py
sdks/python/apache_beam/dataframe/convert.py
sdks/python/apache_beam/dataframe/schemas.py
sdks/python/apache_beam/dataframe/schemas_test.py
sdks/python/apache_beam/dataframe/transforms.py
sdks/python/apache_beam/dataframe/transforms_test.py
sdks/python/apache_beam/pvalue.py
sdks/python/apache_beam/typehints/schemas.py

Adds batching of schema'd PCollections into dataframes based on BatchElements transform.
Lang | SDK | Apex | Dataflow | Flink | Samza | Spark
Go | [![Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [![Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/ba …

[BEAM-9546] DataframeTransform can now consume a schema-aware PCollection

---

CHANGES.md
sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_test.py

A user reported failures in decoding fields with "REPEATED" mode while using `ReadFromBigQuery` transform with `use_json_exports` set to `True`.  
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ …

[BEAM-10524] JSON decoder for ReadFromBigQuery supports repeatable fields

---

website/www/site/content/en/blog/python-improved-annotations.md
website/www/site/content/en/blog/python-performance-runtime-type-checking.md
website/www/site/data/authors.yml

[BEAM-10777] Add two blog posts detailing changes to the type hints module of the Python SDK

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/transforms_test.py

This causes trouble with downstream operations. …

set_index is not index preserving

---

CHANGES.md
runners/spark/build.gradle
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/MultiDoFnFunction.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkProcessContext.java

[BEAM-9850] Key should be available in @OnTimer methods (Spark Runner)

---

.test-infra/jenkins/job_LoadTests_GBK_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Python_reiterate.groovy
sdks/python/apache_beam/testing/load_tests/group_by_key_test.py
sdks/python/apache_beam/testing/load_tests/load_test_metrics_utils.py

Add Python GBK Load Tests for streaming on Dataflow. Cases 1, 2, 4 and 5 are temporarily excluded because their execution time is too long. …

[BEAM-10675] Add Python GBK Load Tests for streaming on Dataflow 

---

learning/katas/go/common_transforms/aggregation/count/task.md

[BEAM-10771] Fix whitespace error causing whitespace lint to fail

---

sdks/python/apache_beam/testing/benchmarks/nexmark/nexmark_launcher.py
sdks/python/apache_beam/testing/benchmarks/nexmark/queries/query12.py

implemented query 12, which only runs in streaming mode currently
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild …

[BEAM-2855] implement query 12

---

.github/codecov.yml
.gitignore
sdks/python/.coveragerc
sdks/python/tox.ini

Also sets up Python code coverage status. …

[BEAM-10701] Add codecov config, fix paths hopefully

---

sdks/python/apache_beam/testing/benchmarks/nexmark/monitor.py
sdks/python/apache_beam/testing/benchmarks/nexmark/nexmark_launcher.py
sdks/python/apache_beam/testing/benchmarks/nexmark/nexmark_util.py

added beam-metric based performance monitoring
performance are logged to console after the query is done or canceled by nexmark suite
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)]( …

[BEAM-8258] basic metric feature for nexmark

---

sdks/python/apache_beam/dataframe/pandas_doctests_test.py

I noticed that a lot of useful pandas methods are hidden behind Series.dt and Series.str, and tested from separate modules. This PR adds some skipped tests for those modules.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | …

[BEAM-10720,BEAM-10721] Add skipped tests for Series.dt and Series.str methods

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/portability/python_urns.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py
sdks/python/apache_beam/runners/portability/portable_runner.py
sdks/python/apache_beam/transforms/environments.py

Adds `pack_combiners` graph optimization phases to the translations module. This allows  packs compatible CombinePerKey stages with a common input into a single stage. This improves performance for use cases of Beam that create thousands of Combine stages with a common input.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/i …

[BEAM-10409] Add combiner packing to graph optimizer phases

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryQuerySource.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryQuerySourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryTableSource.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryTableSourceDef.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java

Currently on read Avro GenericRecords are not supporting `LogicalType`'s; reading `DATE`, `TIME` fields will be read as STRING.
 
Supporting logical types should be doable by just enabling support on `JobConfigurationExtract`
```java
new JobConfigurationExtract()
.setSourceTable(table)
.setDestinationFormat("AVRO")
.setUseAvroLogicalTypes(useAvroLogicalTypes)
.setDestinationUris(ImmutableList.of(destinationUri));
``` …

[BEAM-10649] Add BigQuery Avro logical type support on read

---

sdks/python/apache_beam/runners/interactive/cache_manager.py
sdks/python/apache_beam/runners/interactive/cache_manager_test.py
sdks/python/apache_beam/runners/interactive/caching/streaming_cache.py
sdks/python/apache_beam/runners/interactive/caching/streaming_cache_test.py
sdks/python/apache_beam/runners/interactive/recording_manager.py
sdks/python/apache_beam/runners/interactive/testing/test_cache_manager.py

Change-Id: I3b9ff420817c78988a283bc7b046d85cc732a09b
These were previously added but I found a simple solution to just use limiters from reading from the cache.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastC …

[BEAM-10603] Remove unnecessary limiters and add a method to get the size of a PCollection on disk.

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/ParDo_Load_Tests.json

This fixes the labels for the latency and checkpoint panels. Instead of
displaying "$tag_metric" as the name, it now displays the metric name,
e.g. 'python_streaming_pardo_6.max'.
ibution quickly and easily:
Before:
After:
Also adjusts the titles of the two affected panels.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/ico …

[BEAM-10602] Fix display of latency and checkpoint duration metrics

---

sdks/python/apache_beam/runners/interactive/background_caching_job.py
sdks/python/apache_beam/runners/interactive/options/capture_control_test.py

Change-Id: I24eb5a94e1bdafa1833ede0d04c9e2b824417f87
The old logic didn't allow for the BCJ to terminate if cancelled without a trigger. This allows for the BCJ to be cancelled at any time.
Go | [![Build …

[BEAM-10603] Fix BCJ termination conditions.

---

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java

This will allow users to avoid list full directory trees for limited searches. …

Supporting delimiter for GcsUtil.listObjects

---

website/www/site/content/en/documentation/io/built-in/google-bigquery.md

Updating the BigQuery docs to use the new code snippets from #12118 
R: @rosetn 
R: @aaltay 
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/12559/documentation/io/built-in/google-bigquery/index.html
Go | [![Build …

[BEAM-7705] Update BigQuery docs with new code snippets

---

website/www/site/content/en/documentation/runtime/model.md

Add note about state and timers in the face of retry.

---

.test-infra/jenkins/CommonJobProperties.groovy

CC: @ibzib 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/last …

[BEAM-10841] Set SETUPTOOLS_USE_DISTUTILS=stdlib on jenkins

---

sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/pubsub/PubsubJsonIT.java

It looks like various fixes may have reduced the flakiness. I ran each 100s of times locally without a flake. I think we should try re-enabling. If we see any flakes over the next week or so we can ignore again.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/ …

[BEAM-5122][BEAM-7582] Re-enable ignored tests in PubsubJsonIT

---

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java

Cleanup timers per key lead to potentially unbounded state/checkpoint size growth with a global window in streaming mode.
Instead of timers, we can use the final watermark as the barrier to perform state cleanup.
Go | [![Build …

[BEAM-10760] Optimize state cleanup for global window in portable Flink runner

---

sdks/go/pkg/beam/runners/dataflow/dataflow.go

Use an image when set by the worker_harness_container_image flag.
The `image` variable stopped being consumed in https://github.com/apache/beam/commit/5f46b678e001d55621e5de719cf782160b1ba67d#diff-baacafffaacf38819d0a42b9d41d3174L228, which appears to have removed any ability to specific an image workers should use.
Lang | SDK | …

[BEAM-10773] Use the image flag before the default environment.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/options/StreamingDataflowWorkerOptions.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/GrpcWindmillServer.java

Add options, enabled by default, to control both grpc level channel
health checks as well as application health checks for streaming rpcs
sent to streaming engine. This allows for timely detection of channel
errors which otherwise were only noticed once the rpc deadline was
reached. Also add additional debugging information to the status page
and increased control over logging. …

[BEAM-10808] Health checks streaming rpcs to streaming engine backend

---

sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/package.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/inspector/InspectableList.test.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/inspector/InspectableListItem.test.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/inspector/InspectableView.test.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/inspector/InspectableViewModel.test.ts
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/inspector/Inspectables.test.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/inspector/InteractiveInspector.test.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/inspector/InspectableList.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/inspector/InspectableListItem.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/inspector/InspectableView.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/inspector/InspectableViewModel.ts
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/inspector/Inspectables.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/inspector/InteractiveInspector.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/style/index.css
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/tsconfig.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/yarn.lock

1. Added the InteractiveInspector component and its sub components. The
hierarchy can be found in the code documentation.
2. The component allows listing all user defined pipelines and
PCollections in the kernel of the current notebook session,
displaying pipeline graphs, and visualizing PCollection data.
Lang | SDK | Dataflow | …

[BEAM-10545] Added the inspector of PCollections and pipelines

---

sdks/python/apache_beam/runners/direct/test_stream_impl.py

Change-Id: I5fac037a7dcc141ff9d0ff8058fa3de993626c15
In the case that the kernel is interrupted we want to gracefully shutdown the grpc streaming request from the TestStream. Otherwsie, this throws an esoteric exception.
Go | [![Build …

[BEAM-10603] Gracefully shutdown the channel reader in the test_stream_impl

---

sdks/python/container/license_scripts/dep_urls_py.yaml

It seems after a recent upgrade to pbr (5.5.0) pip-licenses is unable to get its license.
R: @Hannah-Jiang 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark …

[BEAM-10567] Add LICENSE for pbr

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

This PR splits out the uncontroversial portions of #12705, the elementwise methods.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badg …

[BEAM-10720] Add implementation for elementwise str methods

---

sdks/java/io/elasticsearch-tests/elasticsearch-tests-2/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOIT.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-2/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-5/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOIT.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-5/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-6/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOIT.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-6/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOIT.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTestCommon.java
sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java

**What**
This change introduces a new builder function (`withIsDeleteFn`) with `ElasticsearchIO.Write` which can be used to effectively delete documents from the Elasticsearch index. Previously, ElasticsearchIO only supports upsert operations within an index but it is impossible to delete documents.
**Why**
By using the `withIsDeleteFn` function, the apache beam user can dynamically decide the bulk operation to be carried out for the document. Mostly, in streaming update environment, it might happen that some of the previously indexed document needs to be deleted based on some conditions but the current version of ElasticsearchIO doesn't support delete operation and hence many users end up writing empty document for those IDs. This might have a major memory space issue while …

[BEAM-5757] Add ElasticsearchIO: delete document support

---

sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
sdks/python/apache_beam/io/gcp/bigquery_test.py

…ingle name for all copies
* Fixing copy name issue: Single name for all copies
* Fix formatting
* fixup
* Addinga test case to verify multi-partitioned imports work.
* Fixing copy job name generation
--- | --- | --- …

[cherry-pick][BEAM-10853] Fixing copy name issue: Single name for all copies

---

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java

The previous fix a6f4a60edd3ed02839b5b37cdbb29ed137517fae only cleaned up the
state in the portable Flink Runner. This also adds the optimization to the
classic Flink Runner.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | …

[BEAM-10760] Generalize state cleanup optimization for global window

---

sdks/python/apache_beam/runners/interactive/options/capture_limiters.py
sdks/python/apache_beam/runners/interactive/options/capture_limiters_test.py
sdks/python/apache_beam/runners/interactive/pipeline_instrument.py
sdks/python/apache_beam/runners/interactive/recording_manager.py
sdks/python/apache_beam/runners/interactive/recording_manager_test.py

Change-Id: I414463dc40a58c1452b7f4a6e819b9e054e4cac8
This adds the ability to introspect into the RecordingManager to get the start time and size on cache for a recording or pipeline (RecordingManager). Also adds the "cancel" method to a recording. This allows to gracefully shutdown a recording if a kernel interrupt is caught.
Lang …

[BEAM-10603] Add describe and cancel to RecordingManager

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/pipeline_test.py

Currently, `PTransformOverride` only supports overriding `PTransform` s that have a single input. This change adds support for multiple main inputs and side inputs.
The change introduces a new method `PTransformOverride.get_replacement_inputs(self, applied_ptransform)` that can be overridden by end users. This method will be called to get the inputs for the replacement `PTransform.` The default implementation will return a tuple of all the main inputs in order, concatenated with the all the side inputs `PValue` s in order.
Go | [![Build …

[BEAM-10779] Support multiple main inputs and side inputs for PTransformOverride

---

README.md

R: @udim 
Do you think we should switch the coveralls badge over to the new codecov check? Coveralls looks incorrect and out of date. …

[BEAM-10701] Change coveralls badge to codecov

---

.gitignore
sdks/python/scripts/run_pytest.sh
sdks/python/tox.ini

- `run_pytest.sh` runs pytest twice. The second run was overwriting the
first's results.
- Simplified argument passing to run_pytest.sh.
- Use the default coverage.xml report (was generating both coverage.xml
and codecov.xml).
Go | …

[BEAM-10701] Fix Python coverage reporting

---

.test-infra/jenkins/job_LoadTests_ParDo_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Python.groovy
sdks/python/apache_beam/testing/load_tests/pardo_test.py

Added streaming tests cases for load tests for Python SDK. It required to parametrise tests and add condition to set specific source for Dataflow tests (Flink uses `StatefulLoadGenerator` and Dataflow `SyntheticSources`).
Go | [![Build …

[BEAM-10616] Added Python Pardo load tests for streaming on Dataflow

---

sdks/go/pkg/beam/coder.go

Per https://pkg.go.dev/mod/google.golang.org/protobuf there's a v2 variant of generated protocol buffer code for Go. As it stands, technically the v1 variants are now implemented in terms of v2, except that the base interface is now protoreflect.Message, rather than proto.MessageV. 
They are implemented differently, which prevents the existing beam code from "discovering" protocol buffer types on pipeline analysis. This PR resolves it.
Additionally, use the v2 marshaller/unmarshaller explicitly for user elements. …

[BEAM-10874] Support v2 Go protos.

---

sdks/python/apache_beam/transforms/stats.py
sdks/python/apache_beam/transforms/stats_test.py
sdks/python/container/base_image_requirements.txt
sdks/python/container/license_scripts/dep_urls_py.yaml
sdks/python/setup.py

Replace python built-in hash() function with hashlib.md5 (with an option for murmurhash), which is deterministic. Refactor test cases. 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon) …

[BEAM-10824] [BEAM-7654] Change hash function in ApproximateUniqueCombineFn

---

model/fn-execution/src/main/resources/org/apache/beam/model/fnexecution/v1/standard_coders.yaml
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/CommonCoderTest.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/SchemaTranslationTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/MicrosInstant.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/NanosType.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/SqlTypes.java
sdks/python/apache_beam/coders/row_coder.py
sdks/python/apache_beam/coders/row_coder_test.py
sdks/python/apache_beam/coders/standard_coders_test.py
sdks/python/apache_beam/typehints/schemas.py
sdks/python/apache_beam/typehints/schemas_test.py

This PR adds support for `beam:logical_type:micros_instant:v1` in Python and Java. It also adds logic for translating logical types which do not use the argument to portable Beam schemas.
In Python, `micros_instant:v1` is the default mapping for the microsecond-precision `beam.utils.timestamp.Timestamp` type when inferring a schema.
The change is tested via unit tests in Python and Java, as well as a new entry in `standard_coders_test.yaml`.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-b …

[BEAM-10009] Add beam:logical_type:micros_instant:v1

---

release/go-licenses/common.gradle

The Go language license dependencies are built when Pdocker-pull-licenses is specified, which is the default for Jenkins jobs but not interactive builds. This caused flakiness in Jenkins builds when there were concurrent build steps for the same SDK because the build used Docker and Docker can have only one running container with a given name.
This change:
1) adds a random number to the container name to avoid collisions
2) uses the cached output of the golang license generation, to speed up builds
R:apilloud …

[BEAM-10868] Fix build (docker run) concurrency issue when building golang license dependencies

---

sdks/python/apache_beam/dataframe/frames.py

[BEAM-9547] A couple trivial but common dataframe methods.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/extensions/sql/build.gradle
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/KafkaCSVTableIT.java

[BEAM-7523] Enable KafkaCSVTableIT using KafkaContainer

---

sdks/python/apache_beam/dataframe/doctests.py

Only track as WontImplement those tests that are actually raising WontImplement errors.
Also report summary on failure.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-bea …

[BEAM-9561] Improve WontImplement reporting.

---

runners/flink/flink_runner.gradle
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkStreamingTransformTranslators.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/SplittableDoFnOperator.java

I used the UnboundedSourceFunction as a guide to implementing the bundle finalization hook for the DoFnOperator.
Since checkpointing support is only supported when using shutdownSourcesAfterIdleMs so I added a new validates runner task that runs a subset of the tests that rely on bundle finalization.
I also added support for Impulse translation for non-portable streaming pipelines.
This is the base for swapping over non-portable Flink to use SDF instead of UnboundedSources.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier …

[BEAM-6868, BEAM-10670] Add support for bundle finalization to DoFnOperator for non-portable streaming pipelines.

---

runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/DefaultJobBundleFactoryTest.java

Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark …

[BEAM-10678] Split up assertion for clarity

---

model/pipeline/src/main/proto/beam_runner_api.proto
sdks/python/apache_beam/io/gcp/pubsub.py
sdks/python/apache_beam/io/gcp/pubsub_test.py

This is needed to allow runners to override portable definition of transforms. …

[BEAM-10861] Adds URNs and payloads to PubSub transforms to allow runner-native overrides

---

release/build.gradle
release/src/main/groovy/quickstart-java-twister2.groovy
release/src/main/scripts/run_rc_validation.sh
release/src/main/scripts/script.config
runners/twister2/build.gradle
runners/twister2/src/main/java/org/apache/beam/runners/twister2/Twister2PipelineResult.java
runners/twister2/src/main/java/org/apache/beam/runners/twister2/Twister2Runner.java
sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml

Adding changes to complete quickstart for Twister2 runner and adding runner maven archetypes
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostC …

[BEAM-10830] Twister2 quickstarts and the runner maven archetypes

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/EnvironmentsTest.java
sdks/python/apache_beam/transforms/environments.py
sdks/python/apache_beam/transforms/environments_test.py

[BEAM-10505][BEAM-10530] Add truncate capability.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/GroupIntoBatches.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/GroupIntoBatchesTest.java

Add an option in `GroupIntoBatches` interface to allow users to set a timeout for batching. This is useful when there can be incomplete batches, e.g., very few input elements or unbounded input in a global window that might arrive at arbitrary time intervals. …

[BEAM-10475] Add max buffering duration to GroupIntoBatches (Java)

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/RowUtils.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/AvroUtilsTest.java

This PR also adds a test that will fail permanently (rather than flake) without this bugfix, and updates documentation on LogicalType to clarify that it should not need to handle nulls.
R: @tysonjh 
CC: @reuvenlax 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Fli …

[BEAM-10252] Add null check on logical type override

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/pipeline_test.py
sdks/python/apache_beam/runners/dataflow/ptransform_overrides.py
sdks/python/apache_beam/runners/direct/direct_runner.py
sdks/python/apache_beam/runners/direct/sdf_direct_runner.py

`PTransformOverride.get_replacement_transform_for_applied_ptransform()` is a new method that replaces `PTransformOverride.get_replacement_transform()`. This new method provides access to the `AppliedPTransform` when constructing the replacement transform, whereas the old method only provides access to the `PTransform`.
- Introduces `PTransformOverride.get_replacement_transform_for_applied_ptransform(self, applied_ptransform)`. The user can override this to provide a replacement `PTransform` using the input `AppliedPTransform`.
- Provides a default implementation of this method that calls `PTransformOverride.get_replacement_transform()` for backwards compatibility.
- Deprecates `PTransformOverride.get_replacement_transform()`. …

[BEAM-10781] Add PTransformOverride.get_replacement_transform_for_applied_ptransform()

---

CHANGES.md
sdks/python/apache_beam/runners/interactive/display/pcoll_visualization.py
sdks/python/apache_beam/runners/interactive/display/pcoll_visualization_test.py
sdks/python/apache_beam/runners/interactive/interactive_beam.py
sdks/python/apache_beam/runners/interactive/interactive_beam_test.py
sdks/python/apache_beam/runners/interactive/interactive_runner_test.py
sdks/python/apache_beam/runners/interactive/messaging/interactive_environment_inspector.py
sdks/python/apache_beam/runners/interactive/messaging/interactive_environment_inspector_test.py

Change-Id: I660b98ac7cd562eb03aab6d15d829eae8726ebad
The following API changes the way that the Interactive Runner caches
data from unbounded sources. Previously, a user-configurable duration
would run a "Background Caching Job" that would cache all elements from
unbounded source. Then, the user pipeline would run by reading from
that cache after completion. Now, there is a long lived "Background
Recording Job". This replaces the caching job with a background pipeline
that records elements from the unbounded sources and most importantly
does not block user pipeline execution.
The following APIs have changed:
show(*pcolls, include_window_info=False, visualize_data=False) -->
show(*pcolls, n='inf', duration='inf', include_window_info=False, visualize_data=False)
The show() command was …

[BEAM-10603] Implement the new Large Source Recording API.

---

.github/workflows/java_tests.yml

This fixes the java wordcount direct runner test on windows by using the Gradle Github action.
Gradle Github action will use the `.bat` script on windows instead of the `gradlew` bash script.
The issue was that the previous test was running the test on windows using the `gradlew`
bash script instead of the `gradlew.bat` which is what should be used on Windows.
Github actions has msys installed which would mean that the `gradlew` bash script would
not parse the arguments as expected.
The quotes would be removed from the `pipelineOptionsString` which would mean it was invalid JSON.
See https://issues.apache.org/jira/browse/BEAM-10886 for more details. …

[BEAM-10886] Fix Java Wordcount Direct Runner (windows-latest)

---

sdks/python/apache_beam/runners/portability/stager.py
sdks/python/apache_beam/runners/portability/stager_test.py

The fix does the following: 
- It extracts and uses the filename when downloading a remote wheel file (http, https) specified in --sdk_location at the staging phase.
- It refactored the test_sdk_location_remote_wheel as the initial unittest didn't cover well the remote wheel case 
CC: @tvalentyn 
Fixes when the --sdk_location 
- [ x ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
- [ x ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically …

[BEAM-10705] Fixes a bug when passing whl files in --sdk_location from https locations

---

sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py
sdks/python/apache_beam/runners/portability/portable_runner.py

If multiple `KeyWithNone` stages share a common input, then all but one stages will be eliminated along with their output `PCollection`s. Transforms that originally read input from the output `PCollection` of the eliminated `KeyWithNone` stages will be remapped to read input from the output `PCollection` of the remaining `KeyWithNone` stage.
This allows `pack_combiners` to pack sibling `CombineGlobally` stages, rather than just `CombinePerKey` stages.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompl …

[BEAM-10641] Add eliminate_common_key_with_none graph optimizer

---

CHANGES.md
runners/jet/build.gradle
runners/jet/src/main/java/org/apache/beam/runners/jet/JetRunner.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/Read.java

[BEAM-10670] Update Jet to be opt-out for SplittableDoFn powering the Read transform.

---

sdks/python/apache_beam/transforms/combiners.py
sdks/python/apache_beam/transforms/combiners_test.py
sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/stats.py

#12802 seems to have broken `ValidateRunnerXlangTest.combinePerKey`. Rolling back to get tests green again.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark …

[BEAM-10907] Revert "Deprecate obsolete CombineFn.add_inputs. (#12802)"

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisClientThrottledException.java
sdks/java/io/kinesis/src/main/java/org/apache/beam/sdk/io/kinesis/KinesisClientThrottledException.java

`KinesisClientThrottledException` is a type of argument used in `RateLimitPolicy.onThrottle()`, which should be implemented by user in case of using custom `RateLimitPolicy`. So, it should be `public` as a part of user API.
R: @iemejia  …

[BEAM-10816] Make KinesisClientThrottledException public

---

sdks/python/apache_beam/runners/interactive/pipeline_instrument_test.py

Change-Id: I6a4bbd8c2f56d10e40a9f0dcb32b8bfa33549214
The tests are run in parallel causing the same environment to be cleaned
up in multiple threads. This keeps the same environment.
Go | [![Build …

[BEAM-10921] Fix flaky unit tests on Windows

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/PTransformMatchers.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/GroupIntoBatchesOverride.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/PropertyNames.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/GroupIntoBatches.java

To enable optimization for the transform `GroupIntoBatches`, add a new step property when translating stateful DoFns to inform the backend that the special transform allows shardable states.
Go | [![Build …

[BEAM-10703] Add a step property for shardable states during Dataflow graph translation (Java)

---

sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/doctests_test.py

Adds an additional option to doctest, `not_implemented_ok`, which works identically to `wont_implement_ok`, but allows `NotImplementedError` to be raised.
My goal is to minimize the number of skipped tests, so anything unsupported raises `WontImplementError` or `NotImplementedError`. `NotImplementedError`s should link to a jira so users can indicate interest in a feature and track it's support.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComple …

[BEAM-9547] Add not_implemented_ok

---

sdks/python/apache_beam/dataframe/pandas_doctests_test.py

We pass close to half of the the Loc tsts, but it's simpler to just skip them all until Loc supports `__setitem__`.
R: @ibzib
CC: @robertwb  …

[BEAM-9547] Add indexing tests

---

sdks/python/container/Dockerfile
sdks/python/container/license_scripts/pull_licenses_py.py

To help check the python dependency licenses, add python-licenses.csv to /opt/apache/beam/third_party_licenses/ that lists the name, url, and license type for the licenses found by pip-licenses in the pull_licenses_py.py script.
```
./gradlew -Pdocker-pull-licenses :sdks:python:container:py37:docker
docker run -it --entrypoint bash apache/beam_python3.7_sdk:2.25.0.dev 
84 /opt/apache/beam/third_party_licenses/python-licenses.csv
tenacity,https://raw.githubusercontent.com/jd/tenacity/master/LICENSE,Apache Software License
tensorboard,https://raw.githubusercontent.com/tensorflow/tensorboard/master/LICENSE,Apache Software License
tensorboard-plugin-wit,https://raw.githubusercontent.com/PAIR-code/what-if-tool/master/LICENSE,Apache 2.0 …
```

[BEAM-9136] Add CSV for python dependency license names, URLs and types

---

.test-infra/jenkins/job_PostCommit_Python_Chicago_Taxi_Example_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Python_Chicago_Taxi_Example_Flink.groovy

[BEAM-9154] Disable Chicago Taxi Example on Jenkins

---

sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java

TLDR  Let KafkaIO support the deserializer API with headers
References mailing list posts:
* Original https://lists.apache.org/thread.html/rdac09a286cab86c237cf17ed35cdc592b4079d116fc682a6f797d68b%40%3Cdev.beam.apache.org%3E
* Reply from Luke https://lists.apache.org/thread.html/rfde58381e9c34da7894b2dd5325c02944411539235f2668adea5bf24%40%3Cdev.beam.apache.org%3E
The reason for SpEL is because with kafka-clients API < 2.1.0 as dependency, compilation fails with:
```
required: String,byte[]
found: String,Headers,byte[]
reason: actual and formal argument lists differ in length
where T is a type-variable:
```
Because the headers default API only landed in 2.1.0 via https://github.com/apache/kafka/commit/f1f719211e5f28fe5163e65dba899b1da796a8e0#diff-a4f4aee88ce5091db576139f6c610ced
I opted …

[BEAM-10865] Support for Kafka deserialization API with headers (since Kafka API 2.1.0)

---

sdks/python/apache_beam/dataframe/pandas_doctests_test.py

Fix PreCommit breakage due to race between https://github.com/apache/beam/pull/12869 and https://github.com/apache/beam/pull/12856. …

Update indexing skips for pandas 1.x

---

CHANGES.md
sdks/python/apache_beam/examples/wordcount_dataframe.py
sdks/python/apache_beam/examples/wordcount_dataframe_test.py

Also add reference in release notes. …

Dataframe wordcount example.

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py

These have to be done before creating the pipeline proto for Dataflow to be able to correctly generate job requests from portable protos.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/ico …

[BEAM-10933] Adjust GBK type before creating the pipeline proto

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServices.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageQuerySource.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageSourceBase.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageStreamSource.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageTableSource.java
website/www/site/content/en/documentation/io/built-in/google-bigquery.md

This change removes the Experimental annotations for BigQuery storage API sources. The storage API is now GA, and the sources have been updated to use the GA API surface.
Go | [![Build …

[BEAM-10916] Remove experimental annotations for BQ storage API source

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java

- add a case for NUMERIC in fromTableFieldSchemaType so the default case doesn't trigger
- update unit tests with NUMERIC test, increase expected row field counts
Go | [![Build …

[BEAM-10532] convert NUMERIC field in TableSchema

---

sdks/python/apache_beam/runners/worker/data_plane_test.py

[BEAM-10768] Don't assert the order in which elements are received.

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

This PR reduces the number of skipped test cases in `pandas.core.frame` down to 36 (6.3%), and they are all due to issues with the test framework, not unimplemented functionality. The rest of the test cases raise wont implement (13.5%), raise not implemented (11.5%), or pass (68.7%).
- Series.memory_usage
- `Series.__contains__` - checks for a value in the entire index. Maybe this could be implemented as a deferred scalar?
- [`DataFrame.info`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html)
I'm pretty confident the following could be implemented at least partially:
- `DataFrame.__getitem__(DeferredBase)`
- [`DataFrame.apply`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html)
- …

[BEAM-9547] Raise NotImplementedError and WontImplementError throughout DeferredDataframe

---

CHANGES.md
sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/options/pipeline_options_validator_test.py
sdks/python/apache_beam/transforms/ptransform.py
sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/typehints/decorators.py
sdks/python/apache_beam/typehints/typed_pipeline_test.py
sdks/python/apache_beam/typehints/typed_pipeline_test_py3.py
sdks/python/conftest.py
website/www/site/content/en/documentation/sdks/python-type-safety.md

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [![Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [![Build …

[BEAM-4091] Pass type hints in ptransform_fn

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/TestPubsub.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/TestPubsubSignal.java

[BEAM-10716] TestPubsub/TestPubsubSignal clean up subscriptions

---

build.gradle
sdks/python/apache_beam/coders/row_coder.py
sdks/python/apache_beam/dataframe/convert.py
sdks/python/apache_beam/dataframe/convert_test.py
sdks/python/apache_beam/dataframe/io.py
sdks/python/apache_beam/dataframe/io_test.py
sdks/python/apache_beam/dataframe/schemas.py
sdks/python/apache_beam/dataframe/schemas_test.py
sdks/python/apache_beam/dataframe/transforms.py
sdks/python/apache_beam/dataframe/transforms_test.py
sdks/python/apache_beam/typehints/schemas.py
sdks/python/apache_beam/typehints/schemas_test.py

This PR adds the ability for `DataframeTransform` to produce element-wise PCollections, via a new `UnbatchPandas` transform. The original behavior is still available, with a `yield_dataframes=True` option.
In order to support this, the PR also adds more robust support for converting between native Python types and pandas/numpy dtypes. Note that pandas' catch-all `np.object` type is mapped to `typing.Any`. This PR also closes BEAM-10570 - it adds support for RowCoder to encode fields with arbitrary Python types using FastPrimitivesCoder.
Go | [![Build …

[BEAM-10814][BEAM-10570] DataframeTransform outputs elements

---

sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py

Implementation of [BEAM-10938](https://issues.apache.org/jira/browse/BEAM-10938)
Adds support for writing a footer to the `WriteToText` transform.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ …

[BEAM-10938] Adds support for writing a footer to Python WriteToText

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/io.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

This is a roll forward of #12858 (rolled back in #12910), but with an additional commit. It removes the ability for `_WriteToPandas.__ror__` to accept and convert a `DeferredBase` as this conflicts with the actual or operator on `DeferredDataFrame` and `DeferredSeries`.
R: @ibzib 
CC: @robertwb 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCo …

[BEAM-9547] Roll forward #12858

---

sdks/python/apache_beam/runners/portability/local_job_service_test.py
sdks/python/apache_beam/runners/portability/portable_runner.py

It looks like there may have been a regression to BEAM-8660 (https://github.com/apache/beam/pull/10108). This fixes the intended behavior of --artifact_endpoint to override the artifact endpoint reported by the jobserver.
Go | [![Build …

[BEAM-8660] Use PortableOptions.artifact_endpoint if provided over value reported from jobserver

---

.test-infra/jenkins/job_PostCommit_Python_Chicago_Taxi_Example_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Python_Chicago_Taxi_Example_Flink.groovy

In previous PR, cronJobBuilders were commented out, but cron jobs were still active. Changing PostCommitJobBuilder to PhraseTriggeringPostCommitBuilder to mitigate this behaviour.
Go | [![Build …

[BEAM-9154] Ensure Chicago Taxi Example is disabled on Jenkins

---

sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/bigquery_tools_test.py
sdks/python/apache_beam/utils/retry.py

Resolves [BEAM-10910](https://issues.apache.org/jira/browse/BEAM-10910) by raising a `ValueError` when the table name is invalid (too long or contains invalid characters).
Go | [![Build …

BEAM-10910: Validate the BigQuery table name before creating one

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/DropFields.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/transforms/DropFieldsTest.java

There was HashSet used for inserting fields that were supposed to be kept so the order of new schema was completely random.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci …

[BEAM-10960] Fix DropFields does not maintain the original fields order

---

.test-infra/jenkins/job_LoadTests_Combine_Flink_Python.groovy

The goal is to avoid situations where two Flink tests run at the same time on the same machine.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_Po …

Change when streaming Combine on Flink should be fired

---

sdks/go/pkg/beam/core/runtime/genx/genx.go
sdks/go/pkg/beam/core/runtime/genx/genx_test.go
sdks/go/pkg/beam/core/runtime/symbols.go
sdks/go/pkg/beam/core/runtime/types_test.go
sdks/go/pkg/beam/forward.go
sdks/go/pkg/beam/pardo_test.go
sdks/go/pkg/beam/transforms/stats/stats.shims.go
sdks/go/pkg/beam/transforms/top/top.go
sdks/go/pkg/beam/util/starcgenx/starcgenx.go
sdks/go/pkg/beam/util/starcgenx/starcgenx_test.go

Adds a beam.RegisterDoFn call for users to call on their DoFns instead of individually calling RegisterFunction and RegisterType for all parameter types, using reflection.
These registrations are important to ensure workers can process and lookup types and functions correctly. 
This PR also lets starcgen key off of RegisterDoFn in addition to the identifiers list. 
Only transforms/top has been adjusted to demonstrate, and a full go generate ./... pass run on the SDK to demonstrate that the code generator works in both modes simultaneously. In time, we'll remove the identifiers approach and require RegisterDoFn as the only way to hint to the code generator.
The extra changes are go fmt changes missed from other PRs and are benign.
TODO in later PRs:
* Make use of RegisterDoFn everywhere in …

[BEAM-9616] Add RegisterDoFn

---

sdks/python/apache_beam/runners/portability/sdk_container_builder.py

[BEAM-10975] Remove capture_output argument in sdk_container_builder

---

sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/worker/sdk_worker.py
sdks/python/apache_beam/runners/worker/sdk_worker_test.py

[BEAM-10959] Store a fixed amount of known process bundle instructions to prevent failures due to concurrency within a runner.

---

sdks/go/pkg/beam/core/runtime/harness/harness.go

Add a touch more state to prevent race conditions on the runner side.
Retains a list of the most recent N (currently 1000) process bundle instructions.
The flow is: 
Receive ProcessBundleRequest INST-> Add INST to inactive.
Start executing INST -> remove INST from inactive and add INST to active.
Finish executing INST -> remove INST from active, add INST to inactive
if inactive queue > N, then remove the oldest inst from inactive first.
if INST failed -> also add INST to failed.
Then for either Split or Progress requests:
INST is active -> return the appropriate populated response.
INST is failed -> return the cached error
INST is inactive -> return empty response.
https://issues.apache.org/jira/browse/BEAM-10976 is tracking handling Bundle Finalization which would require an additional …

[BEAM-10959] Go SDK: Store a fixed amount of known process bundle instructions to prevent failures due to concurrency within a runner.

---

runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java

`buildPipelineOptions` sets several fake fields for unit testing and therefore failed Dataflow ValidatesRunner tests.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam. …

Fix failed GroupIntoBatchesOverrideTest

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/AutoValueUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ByteBuddyUtils.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/AutoValueSchemaTest.java

[BEAM-10677] Fix @SchemaFieldName in AutoValueSchema

---

sdks/python/apache_beam/io/fileio.py

Remove experimental declarations from fileio.

---

sdks/python/apache_beam/testing/benchmarks/nexmark/nexmark_launcher.py

Add nexmark python query 10 to choices

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Context: https://issues.apache.org/jira/browse/BEAM-10985
This reverts commit 093bea6407f8879d5c9bd8e55b4c833718e956c9.
R: @udim 
cc: @runningcode @mxm 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompleted …

[BEAM-10985] Revert "Fix up-to-date checking mechanism on Tox Task."

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

I came across this while trying to launch the local job service for running Java ValidatesRunner against ULR.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.o …

[BEAM-10993][BEAM-7372][BEAM-8371][BEAM-9980] Set default Python version for virtualenv to 3.6, the minimum supported by Beam

---

runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/legacy-worker/build.gradle

Ran into issues with a logging client that needed a newer version of conscrypt and noticed the hardcoded dependency hadn't been updated in 2 years. 
R: @boyuanzz
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/last …

[BEAM-5748] Upgrade conscrypt to latest version

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_ULR_LOOPBACK.groovy
runners/portability/java/build.gradle

This just adds the additional gradle target. TODO: add continuous Jenkins runs. It looks like it takes long enough it has to be a postcommit.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge …

[BEAM-10435] Add LOOPBACK mode Java ValidatesRunner test suite for ULR

---

.test-infra/jenkins/job_PostCommit_Python_ValidatesRunner_Spark.groovy
.test-infra/jenkins/job_PreCommit_Python_ValidatesRunner_Flink.groovy
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/portable_runner_test.py
sdks/python/apache_beam/runners/portability/spark_runner_test.py
sdks/python/conftest.py
sdks/python/scripts/pytest_validates_runner.sh
sdks/python/scripts/run_tox.sh
sdks/python/test-suites/portable/common.gradle
sdks/python/tox.ini

The main goals of migrating to pytest are:
1. Get Junit structured test output (BEAM-10527).
2. Replace PortableRunnerTest's bespoke timeout mechanism with pytest's (BEAM-9011). ~This also implicitly raises the timeout for all these tests from 60s to 600s, which should reduce the likelihood of timeout flakes (BEAM-8912).~
I originally wanted to do this in incremental changes, but I gradually realized a complete overhaul of these tests' configuration was needed. The main challenge was that `flink_runner_test.py` expected to be run as `__main__`, which is impossible with pytest. I basically reworked everything except the tests themselves; the tests themselves are unchanged.
- I left worker configuration in Gradle because it changes the test dependencies. I moved optimization and streaming …

[BEAM-10527] Migrate Flink and Spark tests to pytest.

---

sdks/python/apache_beam/runners/portability/flink_uber_jar_job_server_test.py
sdks/python/apache_beam/runners/portability/spark_uber_jar_job_server_test.py

This doesn't address the root cause of this issue, which is that value provider arguments are still leaking into unrelated tests.
R: @udim @tvalentyn 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBu …

[BEAM-9026] Avoid side effects from positional value provider arguments.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py

[cherry-pick][BEAM-10950] Passing project properly in BQSource

---

CHANGES.md
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContext.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillTimerInternals.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

This reverts commit 88acc5267f759d81e9836a9db17b9e0ee521c785.
There is a bug in this commit that causes deleted timers to not clear their
watermark holds, resulting in stuck pipelines. See
https://issues.apache.org/jira/browse/BEAM-10991 …

[BEAM-10991] Revert "[BEAM-8543] Dataflow streaming timers are not strictly time ordered when set earlier mid-bundle (#11924)"

---

sdks/python/apache_beam/io/filesystemio.py

Replace deprecated `@abstractproperty` with `@abstractmethod` and `@property` since Python2 is no longer supported.
https://docs.python.org/3/library/abc.html#abc.abstractproperty
Go | [![Build …

[BEAM-10935] Replace @abstractproperty with @abstractmethod

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

Previously, `translations.optimize_pipeline()` failed on an empty pipeline because the `leaf_transform_stages()` returned no stages for an empty pipeline. This change makes `leaf_transform_stages()` return the root transform of an empty pipeline, and adds a test that calls `translations.optimize_pipeline()` on an empty pipeline. …

Fix translations.optimize_pipeline() failure on empty pipelines

---

sdks/python/apache_beam/io/filebasedsource.py
sdks/python/apache_beam/io/tfrecordio_test.py

Handle empty TFRecord file within a glob.
Same as #7777, but I actually narrowed down the cause and included a unit test this time!
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](ht …

[BEAM-10862] Handle empty tfrecord files within a glob

---

CHANGES.md

In reverting the fix for BEAM-8543 I also reverted the edit to CHANGES.md. Instead, CHANGES.md should have forward information about the known issues. This PR adds it. I have also added this to my cherry pick to the 2.25.0 branch.
Go | …

[BEAM-10991] Adjust CHANGES.md to indicate rollback of fix for BEAM-8543

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

[BEAM-9547] Implement dot method for dataframes.

---

sdks/python/apache_beam/io/gcp/big_query_query_to_table_it_test.py
sdks/python/apache_beam/io/gcp/tests/bigquery_matcher.py
sdks/python/apache_beam/io/gcp/tests/bigquery_matcher_test.py
sdks/python/apache_beam/testing/test_utils.py
sdks/python/apache_beam/utils/retry.py
sdks/python/apache_beam/utils/retry_test.py

- In short: streaming inserts are not immediately available after
InsertAll RPC is done. See bug for details.
- Added cumulative time limit option to retry mechanism. This may also
be useful for ITs where the matcher needs to wait for a streaming
pipeline to complete writing its output.
Lang | SDK | Dataflow | Flink | Samza | Spark …

[BEAM-7463] Fix BQ IT flake with streaming inserts

---

website/www/site/content/en/get-started/wordcount-example.md

As I was going through the [wordcount example](https://beam.apache.org/get-started/wordcount-example/) in the Get started tutorial, I've noticed two minor issues.
1) In the Python example of [adding timestamps to data](https://beam.apache.org/get-started/wordcount-example/#adding-timestamps-to-data), the `AddTimestampFn` is initialized with a single parameter, but the class actually takes two, as is visible in the later example, where the class is defined.
2) The [streaming wordcount example](https://beam.apache.org/get-started/wordcount-example/#reading-an-unbounded-dataset), uses deprecated methods `ReadStringsFromPubSub` and `WriteStringsToPubSub`. These are replaced by `ReadFromPubSub` and `WriteToPubSub`.  …

Minor fixes to the get-started/wordcount-example webpage.

---

sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/monitoring_infos_test.py

The PR addresses the encoding issue of Gauges by initializing them with 0.

[BEAM-10848] Initialize gauge to 0

---

CHANGES.md

[BEAM-10670] Improve messaging in CHANGES.md giving clearer instructions to users.

---

CHANGES.md

[BEAM-10670] Cherrypick #13015 to 2.25.0: "[BEAM-10670] Improve messaging in CHANGES.md giving clearer instructions to users."

---

sdks/java/testing/nexmark/src/main/resources/log4j.properties

Notice this while waiting for the Spark Nexmark run to finish on #13021
R: @lukecwik 
CC: @apilloud

[BEAM-11027] Avoid excessive logging of ZetaSQL on Nexmark run

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowWorkProgressUpdater.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/GroupingShuffleReader.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/common/worker/MapTaskExecutor.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/common/worker/NativeReader.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/common/worker/ReadOperation.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowWorkProgressUpdaterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/common/worker/MapTaskExecutorTest.java

On complete_work_status received (by the work progress updater thread), abort the corresponding map task executor thread.  This relies on Thread.interrupt() to unblock the worker thread if blocked and raise an exception -- the exception is actually ignored by the backend since the backend already decided to abort this thread.  Must also check the current thread for interrupts in the valuesiterator when it consumes a stream of values behind the same key, else control does not return to the runReadLoop() to check the interruption. …

[BEAM-11044] Add support for gracefully aborting workers.

---

sdks/python/apache_beam/examples/snippets/snippets_test.py
website/www/site/content/en/documentation/programming-guide.md
website/www/site/static/images/unwindowed-pipeline-bounded.svg
website/www/site/static/images/windowing-pipeline-bounded.svg
website/www/site/static/images/windowing-pipeline-unbounded.svg

While going through the programming guide, I found two small things that can be improved.
First is in the [Windowing with bounded PCollections](https://beam.apache.org/documentation/programming-guide/#windowing-bounded-collections) section. The description mentions reading using `TextIO` but the images display reading from a database table via Kafka IO.
I've updated both diagrams (there's also a slight change in the text) to better reflect the content in the section.
Here's the "unwindowed" before & after:
Here's the "windowing" before & after:
The second change is a minor one in the [Setting a trigger](https://beam.apache.org/documentation/programming-guide/#setting-a-trigger) section. The python example uses a code snippet from a test suite, but it is wrong with regards to the text - …

Minor programming guide improvements

---

runners/portability/java/build.gradle
sdks/python/apache_beam/runners/portability/local_job_service_main.py

There were two problems:
1. My gradle script did not fail when the job service failed to start up. I fixed that and confirmed.
2. The target for the various port/pid/stdout/stderr files were in the gradle output dir but it may not exist.
This PR fixes both.
For the second one, I modified the local job service to create the needed directories. I'm not sure if there is a preference here. The gradle script could also create the needed directory, but I think this change is probably more helpful overall. …

[BEAM-11031] Fix flaking in ULR ValidatesRunner suite

---

CHANGES.md
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunnerDebugger.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/SparkStructuredStreamingRunner.java
runners/spark/src/test/java/org/apache/beam/runners/spark/SparkRunnerDebuggerTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/streaming/ResumeFromCheckpointStreamingTest.java

Instructions to use the old implementation are in CHANGES.md, latest version was merged in https://github.com/apache/beam/pull/13015 for release 2.25
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBui …

[BEAM-10670] Make Spark by default execute Read.Bounded using SplittableDoFn.

---

.test-infra/jenkins/job_PostCommit_Java_PortableValidatesRunner_Flink_Streaming.groovy
runners/flink/job-server/flink_job_server.gradle
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperator.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/functions/FlinkExecutableStageFunctionTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/DefaultJobBundleFactory.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SingleEnvironmentInstanceJobBundleFactory.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/StageBundleFactory.java
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/SparkExecutableStageFunctionTest.java
sdks/python/apache_beam/runners/portability/flink_runner_test.py

This PR adds bundle finalization support to streaming portable Flink by hooking up with Flink checkpoint. 
I also looked into batch support but found out that Flink batch doesn't expose an API like checkpoint:
https://lists.apache.org/thread.html/r89c74f4020cd15d3c1a4b84ef78d7da4f67824e1b5e2210f4c5c1f40%40%3Cdev.flink.apache.org%3E.
For now, the streaming support is enough to support streaming SDF usage, which is also a major usage for x-lang.
r: @mxm 
cc: @lukecwik @ibzib 
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier …

[BEAM-11022] Support bundle finalization for portable Flink in streaming.

---

runners/spark/build.gradle

This passes now after some recent changes in core. A really minor improvement after reviewing the PR on SDF Bounded reads for Spark runner
R: @lukecwik

Enable SDF testPairWithIndexWindowedTimestampedBounded in Spark Structured Streaming runner

---

runners/spark/build.gradle

Seems we were excluding this set of tests even if they were passing for the Batch case.
R: @aromanenko-dev

Enable UsesStrictTimerOrdering ValidatesRunner tests on Spark Classic Runner

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow_streaming.groovy
runners/google-cloud-dataflow-java/build.gradle

DataflowRunner automatically detects bounded/unbounded collections and will run in batch mode if possible. This forces a run in streaming mode, since this is most of the important coverage.
Go | [![Build …

[BEAM-2146] Continuously test Dataflow ValidatesRunner forcing streaming

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py

In `pipeline_from_stages()`, only the transforms and their subtransforms that are included in the given stages are copied over to the output pipeline proto. This change similarly only copies over only PCollections that are produced by those transforms to the output pipeline proto. This prevents PCollections whose producers have been eliminated by optimization phases from being copied to the output pipeline proto, which would later cause an error in `Pipeline.from_runner_api()`.
Go | [![Build …

Delete unneeded PCollections in pipeline_from_stages()

---

sdks/python/apache_beam/runners/dataflow/dataflow_metrics.py
sdks/python/apache_beam/runners/dataflow/dataflow_metrics_test.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient.py

Currently, Dataflow metrics processor expects Dataflow internal step names generated for v1beta3 job description in metrics returned by Dataflow service.
But with portable job submission, Dataflow uses PTransform ID (in proto pipeline) as the internal step name. Hence metrics processor should be updated to handle this.
Lang | SDK | …

[BEAM-11033] Updates Dataflow Metrics processor for portable job submission

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow_streaming.groovy

The change copy/pasted from the batch VR job got rolled back between testing and merge.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit …

Remove stability history from Dataflow streaming VR job

---

runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/AggregatorCombiner.java

Accumulators can be mutated during merging by the combine fn so we must ensure that we use a unique instance of the accumulator per window. …

[BEAM-11050] Duplicate accumulator if it appears in multiple windows.

---

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/functions/FlinkExecutableStageFunction.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/functions/FlinkExecutableStageFunctionTest.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/StageBundleFactory.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/SparkExecutableStageFunctionTest.java
sdks/python/apache_beam/runners/portability/flink_runner_test.py

This PR added an unsupported BundleFinalizationHandler to portable Flink in batch mode. This will give users a more detailed error message like:
```
ERROR:root:java.lang.UnsupportedOperationException: Portable Flink runner doesn't support bundle finalization in batch mode. For more details, please refer to https://issues.apache.org/jira/browse/BEAM-11021.
```
when users try to use bundle finalization in batch.
r: @mxm 
cc: @lukecwik @ibzib 
Post-Commit Tests Status (on …

[BEAM-11021] Add unsupported BundleFinalizationHandler to portable batch Flink.

---

sdks/python/apache_beam/dataframe/frames.py

I've run into this enough times that I think it'll be valuable to have. (Pandas has such a class as well.)
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/ …

Introduce intermediate superclass for both Dataframe and Series.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/google-cloud-dataflow-java/worker/legacy-worker/build.gradle
sdks/java/maven-archetypes/examples/build.gradle
sdks/python/build.gradle

This adds relative path sensitivity to task inputs where necessary in order to enable the build cache to be shared across workspaces.
[More information on relative path sensitivity and relocatability.](https://guides.gradle.org/using-build-cache/#relocatability)
--- | --- | …

Add Relative Path Sensitivity

---

model/pipeline/src/main/proto/beam_runner_api.proto
sdks/python/apache_beam/io/gcp/pubsub_test.py
sdks/python/apache_beam/io/iobase.py

This seems to be the correct place for this encoding since we would not want to override the full expansion of ReadFromPubSub/WriteToPubSub transforms.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedB …

[BEAM-10861]Adds PubSub Runner API encoding to Read/Write transforms

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/dataframe/transforms_test.py

This PR adds implementations for the non-trivial operations in `pd.Series.str`:
- [`cat`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.cat.html) can accept another Series or DataFrame making it a zipping operation, or it may produce a scalar.
- [`repeat`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.repeat.html) can accept another Series making it a zipping operation.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache. …

[BEAM-10720] Finish implementing StringMethods (cat, repeat)

---

sdks/python/apache_beam/runners/portability/stager_test.py

For some reason pytest occasionally brings a zipimporter object into the main session. Below py3.8 these objects are unpicklable, causing test_with_main_session to flake. This PR skips the test under the flaky conditions for now.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostC …

[BEAM-10987] Skip test_with_main_session on windows

---

sdks/go/pkg/beam/core/runtime/exec/datasource.go
sdks/go/pkg/beam/core/runtime/exec/datasource_test.go
sdks/go/pkg/beam/core/runtime/exec/dynsplit_test.go
sdks/go/pkg/beam/core/runtime/exec/plan.go
sdks/go/pkg/beam/core/runtime/exec/sdf.go
sdks/go/pkg/beam/core/runtime/exec/sdf_test.go
sdks/go/pkg/beam/core/runtime/harness/harness.go
sdks/go/pkg/beam/io/rtrackers/offsetrange/offsetrange.go

Adjust Go SDF splitting and execution code so that splits take exploded windows into consideration and perform splits at window boundaries. Also required adjusting various split logic to accept multiple residuals and primaries from splits.
The changes to the splitting logic itself are in exec/sdf.go, and the tests are in the corresponding test file. The rest of the changes are mostly related to adjusting other code to handle the change from single primaries and restrictions to multiple primaries and restrictions, or just small bugfixes (like offsetrange.RTracker.GetProgress). …

[BEAM-11020] Adding multi-window splitting to Go SDF.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

[BEAM-8721] Update stax2-api to version 4.2.1

---

runners/google-cloud-dataflow-java/build.gradle

This disables the tests failing at https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/5/#showFailuresLink
They are unsupported features on Dataflow.
Confirmed that prior runs have the same failures: they are not flakes and there are not additional flakes.
Lang | SDK | Dataflow | Flink | Samza | …

[BEAM-2146] Disable unsupported categories for Dataflow streaming

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frames.py

Also implement divmod which uses this. …

[BEAM-9547] Allow wrapping multiple return values.

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frame_base_test.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

R: @robertwb 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/la …

[BEAM-9547] Add support for `DataFrame.assign`

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

When running on https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html
Before: 
```
250 total test cases:
0 skipped (0.0%)
4 won't implement (1.6%)
3 order-sensitive (75.0%)
1 Conversion to a non-deferred a numpy array. (25.0%)
26 not implemented (yet) (10.4%)
9 NameError following NotImplementedError (34.6%)
5 'index' is not yet supported (BEAM-9547) (19.2%)
5 GroupBy.agg currently only supports callable arguments (19.2%)
1 [Grouper(level=1, axis=0, sort=False), 'A'] (3.8%)
1 [Grouper(level='second', axis=0, sort=False), 'A'] (3.8%)
1 ['second', 'A'] (3.8%)
1 Traceback (most recent call last):\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 1329, in __run\n    compileflags, 1), test.globs)\n …
```

[BEAM-9547] Flesh out dataframe groupby (and related) implementation.

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java

[BEAM-11066] Fix java dataflow runner override factories ordering with streaming beam_fn_api 

---

runners/google-cloud-dataflow-java/build.gradle

These were removed from the exclusion list, at https://github.com/apache/beam/commit/c3114bf2410163cad72d08fb569f34cc034cca53#diff-8f2f682def71854816cc757228ece9384fcc753fd338a19dcf2a5b3ccca92185L150 without any clear reason. They are not supported, so they should remain in the unsupported list.
Lang | SDK | Dataflow | Flink | Samza …

Re-sickbay unsupported metrics on Dataflow

---

sdks/python/apache_beam/io/gcp/pubsub_test.py
sdks/python/apache_beam/io/iobase.py

This preserves the old behavior that might be expected by some runners.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComplete …

[BEAM-10861] Updates Pub/Sub runner API transformation to preserve None values

---

sdks/java/bom/build.gradle

beam-sdks-java-bom-2.25.0.pom is no longer signed during release after we upgrade to Gradle 6. This PR enables generatePomFileForMavenJavaPublication explicitly to make the signing step work again.
r: @kennknowles @tysonjh 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_ …

[BEAM-11068] Ensure beam-sdks-java-bom.pom is signed during release

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java

The logging of the key is controlled by the DataflowPipelineOption `hotKeyLoggingEnabled`. When true and a hot key is detected from Dataflow, the literal hot key content will be logged to Cloud Logging. Otherwise, the default message without a key will be displayed.
--- | --- …

[BEAM-10994] Adds ability to log literal hot key in Streaming Dataflow

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow_streaming.groovy

With the same title, they show up as one GitHub status.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- …

Make streaming and "auto" Dataflow ValidatesRunner jobs have different titles

---

runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/ProcessBundleDescriptors.java
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/ProcessBundleDescriptorsTest.java

We need to length-prefix the coder of the input pcollection for one executable stage especially when there is an SDF or a stateful DoFn, where:
- In SDF, the input coder is for encoding DelayedBundleApplication
- In one stateful DoFn, the input coder is for encoding the key for state request.
r: @lukecwik @mxm 
Lang | SDK | Dataflow …

[BEAM-10940] Lengthprefix any input coder for an ProcessBundleDescriptor.

---

buildSrc/build.gradle
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

This is a routine upgrade. The new checkerframework version has a "Called Methods" analysis that may help analyze our classes that have protocols like "must call method X before method Y".
Go | [![Build …

Upgrade checkerframework and gradle plugin

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Java build fails on my machine due to https://github.com/pypa/virtualenv/issues/1910. I suspect several other folks on my team may be affected.
The workaround https://github.com/pypa/virtualenv/issues/1643#issuecomment-665703259 does not work since python3.6 distutils package,  is no longer installable on my platform.
To workaround the issue, bumping up the version to the latest supported. We can readjust or discuss further if this causes any inconveniences.
Post-Commit …

Use a newer Python interpreter version as default.

---

sdks/python/setup.py

This PR removes all requirements that were conditioned on py3 vs. py2. Anything py2 only is now removed, anything py3 only is included unconditionally. …

[BEAM-7372] Remove py2 checks in setup.py

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/graph/QueryablePipeline.java

[BEAM-11107] Populate sideinput for SDF

---

.test-infra/metrics/build.gradle
website/build.gradle

[BEAM-11111] Fix website publish to use stable directory so that .git directory can be found.

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go

The panic is triggered at this line:
https://github.com/apache/beam/blob/v2.25.0-RC2/sdks/go/pkg/beam/core/runtime/graphx/translate.go#L126 …

[BEAM-11112] Fix nil pointer panic in `graphx.Marshal`

---

learning/katas/go/course-remote-info.yaml
learning/katas/go/windowing/adding_timestamp/lesson-info.yaml
learning/katas/go/windowing/adding_timestamp/lesson-remote-info.yaml
learning/katas/go/windowing/adding_timestamp/pardo/cmd/main.go
learning/katas/go/windowing/adding_timestamp/pardo/pkg/common/data.go
learning/katas/go/windowing/adding_timestamp/pardo/pkg/task/task.go
learning/katas/go/windowing/adding_timestamp/pardo/task-info.yaml
learning/katas/go/windowing/adding_timestamp/pardo/task-remote-info.yaml
learning/katas/go/windowing/adding_timestamp/pardo/task.md
learning/katas/go/windowing/adding_timestamp/pardo/test/task_test.go
learning/katas/go/windowing/fixed_time_window/lesson-remote-info.yaml

This pull requests adds a lesson on assigning PCollection timestamps to the Go SDK katas. I would like to request the following reviewer:
(R: @lostluck )
The [Stepik course](https://stepik.org/course/70387) has not yet been updated.
Go | …

[BEAM-9682] Add assign timestamp lesson to Go SDK katas

---

sdks/go/pkg/beam/io/filesystem/filesystem.go
sdks/go/pkg/beam/io/filesystem/gcs/gcs.go
sdks/go/pkg/beam/io/filesystem/local/local.go
sdks/go/pkg/beam/io/filesystem/memfs/memory.go
sdks/go/pkg/beam/io/filesystem/memfs/memory_test.go

Size returns the size of a file in bytes. GCS and local were tested manually. Also did some cleanup since I was getting linter errors about unused parameters.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCom …

[BEAM-11108] Add a Size method to all Go SDK filesystems.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java

I've seen some user reports that these messages are confusing. I think it would be helpful to log the exception simultaneously. …

[BEAM-11117] Clarify 'execution of work' messages

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

The query is somewhat complex to avoid reading data. On `bigquery-public-data.samples.github_nested` this consumed 0.02 seconds and 0 bytes shuffle, vs 'SELECT count(*)' consuming 1 second and 72 bytes shuffle.
Go | [![Build …

[BEAM-11114] BigQueryServicesImpl.isTableEmpty uses jobs.query API

---

runners/google-cloud-dataflow-java/build.gradle

OrderedListState tests fail on Dataflow runner v2. Excluding them for
now until the feature is supported.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/j …

[BEAM-11130] Exclude OrderedListState VR tests.

---

CHANGES.md
sdks/python/apache_beam/io/aws/clients/s3/boto3_client.py
sdks/python/apache_beam/io/aws/clients/s3/client_test.py
sdks/python/apache_beam/io/aws/s3filesystem.py
sdks/python/apache_beam/io/aws/s3filesystem_test.py
sdks/python/apache_beam/io/aws/s3io.py
sdks/python/apache_beam/io/aws/s3io_test.py
sdks/python/apache_beam/options/pipeline_options.py

I would like to be able to configure s3 compatible IO in order to be able to use alternative endpoints. https://github.com/apache/beam/pull/10560 began moving in this direction but has been stalled for a while. The main comment there was that pipeline options should be used for configuration. 
Some open questions that I have are:
* Is there a reason that a separate S3IO instance was created for every operation in the s3filesystem? If so I can save a reference to the pipeline options in the constructor and pass that in instead of saving the single S3IO.
* Are there any naming considerations for the S3Options? Should they begin with a naming prefix to differentiate from other options provided on the command line?
* Does it make sense to pass in tokens/keys through pipeline options? Should …

 BEAM-9094 Configure S3 client for IO to s3 compatible object stores

---

sdks/python/apache_beam/dataframe/convert.py
sdks/python/apache_beam/dataframe/convert_test.py
sdks/python/apache_beam/dataframe/schemas.py
sdks/python/apache_beam/dataframe/schemas_test.py

* Allow conversion of a PCollection of primitives (like ints) to a deferred Serries.
* Allow conversion of deferred scalars to singleton PCollections without specifying `yield_elements=pandas`.
Go | [![Build …

More flexible dataframe conversions.

---

sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/doctests_test.py

* Unset variables from failed assignments.
* Better parsing of multi-line examples.
* Strip ipython prompts.
* Track line numbers in test parsing.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ …

[BEAM-9561] Dataframe test infrastructure improvements.

---

sdks/python/apache_beam/runners/direct/direct_runner.py
sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py

The option was added for Java in https://github.com/apache/beam/pull/12726
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompl …

[BEAM-10475] Add max buffering duration option for GroupIntoBatches transform in Python

---

sdks/python/container/boot.go

delete conditions concerning Python 2.7 and 3.5 from boot.go …

[BEAM-7372][BEAM-8371][BEAM-9372] drop python 2.7 and 3.5 support from python container

---

sdks/go/examples/stringsplit/stringsplit.go
sdks/go/examples/wordcount/wordcount.go
sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/io/rtrackers/offsetrange/offsetrange.go
sdks/go/pkg/beam/io/rtrackers/offsetrange/offsetrange_test.go
sdks/go/pkg/beam/io/textio/sdf.go
sdks/go/pkg/beam/io/textio/sdf_test.go
sdks/go/pkg/beam/io/textio/textio.go

Pretty straightforward. Read and ReadSdf should be functionally identical, and likewise for ReadAll and ReadAllSdf.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.ap …

[BEAM-11108] Add a version of TextIO implemented via SDF.

---

sdks/python/apache_beam/transforms/core.py

Simple optimization for {CallableWrapperCombineFn, NoSideInputsCallableWrapperCombineFn}.extract_output that takes advantage of the corresponding (optional) compact behavior.
(Prepared by @katsiapis).
Go | [![Build …

Optimizes extract_output for 1 element accumulator case.

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow_V2.groovy

The suite is failing consistently with a timeout. One successful run
previously completed with 1 minute to spare (269min). Bumping by an
hour.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badg …

Increase Dataflow V2 validates runner timeout.

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/dataframe/transforms_test.py

This PR primarily adds support for `DataFrame.{drop,explode}`.
I also noticed an edge case affecting the generated proxy in `rename`, so I included a change in this PR to make `TransformTest.run_scenario` verify that the deferred DataFrame's proxy matches the shape of the expected output. This detected a couple of issues (the aforementioned rename issue, verified in a new test, as well as a problem in `str.repeat`).
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_Po …

[BEAM-9547] Implementation for drop, explode

---

sdks/python/apache_beam/runners/portability/flink_runner_test.py

Current py bundle finalization test is flaky on Flink since  Flink checkpointing may not happen right before the pipeline finishes. We can rewrite the test to use SDF initiated checkpoint to force bundle finalization happens. But it requires https://github.com/apache/beam/pull/13105 being checked in first. 
Lang | SDK | Dataflow | …

[BEAM-11070] Skip py bundle finalization test.

---

sdks/python/apache_beam/runners/dataflow/internal/names.py
sdks/python/apache_beam/runners/internal/names.py
sdks/python/apache_beam/runners/portability/stager.py
sdks/python/apache_beam/runners/portability/stager_test.py

This should solve [this Jira issue](https://issues.apache.org/jira/browse/BEAM-5939).
apache_beam/runners/dataflow/internal/names.py
apache_beam/runners/portability/stager.py
had same constants defined in both files, this pull request should resolve it.

[BEAM-5939] - Deduplicate constants

---

sdks/java/io/hadoop-format/build.gradle

beam_PerformanceTests_HadoopFormat is failing since ElasticSearch update. The problem was that there was no dependency for apache `commons-lang3` and `NoSuchMethodError: StringUtils.isNoneEmpty` was thrown.
Go | [![Build …

[BEAM-11160] Fix HadoopFormatIOIT

---

sdks/python/apache_beam/transforms/core.py

[BEAM-3736] Construct empty global combine values on workers when possible.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffset.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java

Changes include:
- Add `KafkaCommitOffset` transform, which expands to 
PCollection<KV<KafkaSourceDescriptor, KafkaRecord>> -> Map to KV<KafkaSourceDescriptor, (Long)offset> -> WindowInto(5 min FixWindow) -> Max.longsPerKey() -> CommitOffsetDoFn
- Change `ReadFromKafkaDoFn` to output KV<KafkaSourceDescriptor, KafkaRecord> instead of KafkaRecord only.
- Add commit offset expansion to KafkaIO.ReadSourceDescriptors:
ParDo(ReadFromKafkaDoFn) -->
Reshuffle() --> Map(output KafkaRecord) --> output
|
- -> KafkaCommitOffset
**Note** that this expansion is not supported when using x-lang on Dataflow.
r: @aromanenko-dev 
cc: @lukecwik  …

[BEAM-10123] Add Kafka Commit transform.

---

sdks/java/extensions/sql/build.gradle
sdks/java/io/clickhouse/build.gradle

[BEAM-5570] Update javacc dependency

---

runners/core-java/src/main/java/org/apache/beam/runners/core/ReduceFnRunner.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/AfterAllStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/AfterDelayFromFirstElementStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/AfterEachStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/AfterFirstStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/AfterPaneStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/AfterWatermarkStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/DefaultTriggerStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/ExecutableTriggerStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/NeverStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/OrFinallyStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/RepeatedlyStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/ReshuffleTriggerStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/TriggerStateMachine.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/TriggerStateMachineContextFactory.java
runners/core-java/src/main/java/org/apache/beam/runners/core/triggers/TriggerStateMachineRunner.java
runners/core-java/src/test/java/org/apache/beam/runners/core/triggers/ExecutableTriggerStateMachineTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/triggers/RepeatedlyStateMachineTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/triggers/StubTriggerStateMachine.java
runners/core-java/src/test/java/org/apache/beam/runners/core/triggers/TriggerStateMachineTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/triggers/TriggerStateMachineTester.java

is used for the state namespace.
Previously prefetching was fetching non-existent state, possibly adding
unnecessary fetches as well as neglecting to prefetch actual state used.
Another way to accomplish this would be to change the TriggerStateMachine
prefetch methods to take a TriggerContext instead of a raw state accessor.
This would allow for TriggerStateMachine to get the correct state for
subtriggers.  That seems more inline with how the nonprefetch methods work
however that is a public interface change. …

[BEAM-11144] Fix trigger prefetching so that the correct trigger index

---

runners/google-cloud-dataflow-java/build.gradle

Refactor how tests are excluded to use the category instead of a regex.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComplete …

[BEAM-11130] Exclude OrderedListState category for Dataflow V2.

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow_V2_Streaming.groovy
runners/google-cloud-dataflow-java/build.gradle

Add Dataflow Runner V2 VR streaming tests and refactor build.gradle for reuse.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastC …

Add Dataflow Runner V2 Java ValidatesRunner streaming test configuration.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/iobase.py
sdks/python/apache_beam/io/iobase_test.py
sdks/python/apache_beam/io/textio_test.py

This is valuable for BigQuery repeatedly firing side input. This PR is intended to be used here: https://github.com/apache/beam/pull/13170
This makes the SDF Bounded Source reader available to use. A small change in functionality:
- If no `source` is provided to the initial restriction in the constructor, then the element is expected to be a source, and it's added to the initial restriction at creation.
r: @boyuanzz  …

Implementing Python Bounded Source Reader DoFn

---

.test-infra/jenkins/job_PostCommit_Java_PortableValidatesRunner_Flink_Streaming.groovy
runners/flink/job-server/flink_job_server.gradle

[BEAM-11187] Exclude SDF test suite because it requires support of self-checkpoint.

---

sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/ptransform_test.py

Before this change, beam.Partition doesn't correctly pass PValue typed
side inputs to the downstream ParDo transform, which causes the Beam
pipeline fails if passing a Pvalue typed side input to beam.Partition
ptransform.
In this change, args and kwargs are rebuilt before being passed to the
downstream ParDo.
Lang | SDK | Dataflow | …

[BEAM-11164] Fixes bug in beam.Partition

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py

When performing the KeyWithNone elimination, the output PCollections of the original KeyWithNone transforms are deleted, and transforms that read from the deleted output PCollections are remapped to read from the remaining output PCollection. Originally, this remapping was only performed by leaf transforms in stages. This is incorrect because non-leaf transforms may also reference the deleted PCollections. This change fixes this by also applying the remapping to transforms in the context's components.
Go | [![Build …

[BEAM-10409] Remap all PCollections in KeyWithNone elimination

---

model/pipeline/src/main/proto/beam_runner_api.proto
sdks/python/apache_beam/io/gcp/pubsub.py
sdks/python/apache_beam/io/gcp/pubsub_test.py
sdks/python/apache_beam/io/iobase.py

[BEAM-10869] Remove unused PubSubSink with_attributes property

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test.py

This doesn't address BEAM-2717, but should fix the `NotImplementedError:
BEAM-2717` error message when using this class.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-be …

[BEAM-2717] Implement ProtoCoder.to_type_hint

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/transforms/combinefn_lifecycle_test.py

CombineFnVisitor is not working properly and triggers an exception for correct pipelines. It should be disabled until being fixed.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](htt …

[BEAM-3736] Disable CombineFnVisitor

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

Currently the parent of the fused stage is set to `None` if the two stages do not share a common parent. This sets it to the lowest common ancestor, if one exists.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | …

[BEAM-11196] Set parent of fused stages to the lowest common ancestor

---

CHANGES.md
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/transforms/core.py

Also add an additional assertion for CombinerFnVisitor's test.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) …

[BEAM-3736] Let users know that CombineFn.setup and teardown are not supported on Dataflow without Runner V2

---

model/pipeline/src/main/proto/beam_runner_api.proto

This adds the ToString URN to the list of well-known transforms. the ToString transform allows for Runners to translate a given element into a human-readable string. This is useful for debugging, creating tools, or features on the runner side that generalize across SDKs that require element introspection.
Design-doc:
https://docs.google.com/document/d/1v7iWj0LIum04mYwRM_Cvze915tATwmEzLrqj_uVBkCE/ …

[BEAM-11151] Adds the ToString well-known transform URN

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_read_internal.py
sdks/python/apache_beam/io/gcp/bigquery_test.py

This is an intermediate step for #13170 , along with #13154 .
This change is meant to be pure moving of utilities without changing the functionality. Internal symbols are moved to the interna file.
R: @chamikaramj 
Go | [![Build …

Refactoring BigQuery Read utilities into internal file

---

CHANGES.md
sdks/java/extensions/sql/datacatalog/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datacatalog/SchemaUtils.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java

Add support to 2 more new types: DATETIME and NUMERIC, similar to https://github.com/apache/beam/pull/12261
Also add the missing mapping for NUMERIC in SchemaUtils in Data Catalog.
r: @chamikaramj, @TheNeuralBit 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink …

Support read/write ZetaSQL DATETIME/NUMERIC types from/to BigQuery

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/google-cloud-platform/build.gradle
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubOptions.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/TestPubsub.java

The official GCP client has better tuned timeouts and retry configs for this application, using it should reduce flakiness. …

[BEAM-11159] Use GCP pubsub client for TestPubsub

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/TestPubsub.java

listSubscriptions used to remove the subscription that TestPubsub itself created, but I didn't port over this logic in https://github.com/apache/beam/pull/13273. This is very likely the cause of the SQL PostCommit failures.
The test is supposed to wait until the pipeline under test has created a subscription before moving on and publishing test data, but it is proceeding early because it's counting the subscription created by TestPubsub.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam. …

[BEAM-11159] listSubscriptions should remove TestPubsub's own sub

---

sdks/go/pkg/beam/io/synthetic/source.go
sdks/go/pkg/beam/io/synthetic/source_test.go

Add support for HotKeys and HotKeysFraction when generating Synthetic Source in Beam GO SDK

[BEAM-11075] Go SDK's synthetic source supports hot keys generation

---

build.gradle
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/spark/build.gradle
sdks/java/extensions/sorter/build.gradle
sdks/java/extensions/sql/build.gradle
sdks/java/io/hadoop-common/build.gradle
sdks/java/io/hadoop-file-system/build.gradle
sdks/java/io/hadoop-format/build.gradle
sdks/java/io/hcatalog/build.gradle
sdks/java/io/parquet/build.gradle

This PR:
- updates Hadoop dependencies from 2.8.5 to 2.10.1
- adds tests for Hadoop 2.8.5 compatibility in modules that have hadoop dependencies as 'provided'
For the tests I've taken the approach that is already used in KafkaIO.
I tried to add tests for Hadoop 2.7.7 but without success. I haven't verified if the problem comes from tests configuration or the IO itself but since this PR is to assure the compatibility with the previous version used in Beam (2.8.5) I'd like not to touch it. It could be worth to file a Jira to add tests for 2.7.7 version. …

[BEAM-8719 BEAM-8768 BEAM-8769 BEAM-8770 BEAM-8771] Update minor hadoop dependencies

---

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ViewTest.java

This is a regression test that would have detected an issue with a dataflow runner, triggered by the side input for a window not being ready initially and then never having a value when the window closed.
--- | --- | …

Add side input test verifies runner test where side input never becomes ready

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

Adds support for executing `eval` and `query` as element-wise methods. Restricts most kwargs to their defaults for simplicity, only parser, engine and truediv are still allowed to be changed.
This PR also includes a commit to pass `*args` through `maybe_inplace` as not having it breaks `eval`. 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCom …

[BEAM-9547] Add basic support for `DataFrame.{eval,query}`

---

sdks/go/examples/xlang/cogroup_by/cogroup_by.go
sdks/go/examples/xlang/combine/combine.go
sdks/go/examples/xlang/combine_globally/combine_globally.go
sdks/go/examples/xlang/flatten/flatten.go
sdks/go/examples/xlang/group_by/group_by.go
sdks/go/examples/xlang/multi_input_output/multi.go
sdks/go/examples/xlang/partition/partition.go
sdks/go/examples/xlang/transforms.go
sdks/go/examples/xlang/wordcount/wordcount.go
sdks/go/pkg/beam/core/graph/xlang.go
sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/runtime/xlangx/expand.go
sdks/go/pkg/beam/core/runtime/xlangx/translate.go
sdks/go/pkg/beam/xlang.go

Adds wrappers around each test xlang transform used in the examples, which show how xlang transforms are best implemented. Also adjusts the xlang fronte-end, specifically removing the misleadingly named Sink and Source versions of the methods, and adjusting the Input/Output tag naming to match and adding some helpers.
Note: Currently the CoGroupByKey, Partition, and MultiInputOutput examples are failing when run manually, however that seems unrelated to this PR. They fail identically if I run them in a clean repo. Still debugging that issue. …

[BEAM-11188] Add wrappers to Go Xlang examples, and adjust front-end.

---

runners/flink/flink_runner.gradle
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkExecutionEnvironments.java
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineOptions.java
runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkExecutionEnvironmentsTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkPipelineOptionsTest.java
website/www/site/layouts/shortcodes/flink_java_pipeline_options.html
website/www/site/layouts/shortcodes/flink_python_pipeline_options.html

We should make it easier to configure a Flink state backend. At the moment,
users have to either:
(A)  Configure the default state backend in their Flink cluster
(B1) Include the dependency in their Gradle/Maven
project (e.g. "org.apache.flink:flink-statebackend-rocksdb_2.11:$flink_version"
for RocksDB).
(B2) Set the state backend factory in the FlinkPipelineOptions. This only works
in Java due to the factory specification being in Java!
We can make it easier by simple adding pipeline options for the state backend
name and the checkpoint directory which will be enough for configuring the state
backend. We bundle the RocksDB state backend by default. …

[BEAM-9855] Provide an option to configure the Flink state backend

---

.test-infra/jenkins/CommonTestProperties.groovy
.test-infra/jenkins/LoadTestConfig.groovy
.test-infra/jenkins/LoadTestsBuilder.groovy
.test-infra/jenkins/PythonTestProperties.groovy
.test-infra/jenkins/job_LoadTests_Combine_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_Combine_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Python_reiterate.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Python.groovy
.test-infra/jenkins/job_LoadTests_Python_Smoke.groovy
.test-infra/jenkins/job_LoadTests_SideInput_Python.groovy
.test-infra/jenkins/job_LoadTests_coGBK_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_coGBK_Python.groovy
.test-infra/jenkins/job_PerformanceTests_BigQueryIO_Python.groovy
.test-infra/jenkins/job_PerformanceTests_PubsubIO_Python.groovy

Not to hardcode `python 3.7` in load test and performance test groovy files.
Following tests are affected.
```
beam_LoadTests_Python_CoGBK_Flink_Batch
beam_LoadTests_Python_Combine_Dataflow_Batch
beam_LoadTests_Python_Combine_Dataflow_Streaming
beam_LoadTests_Python_GBK_Flink_Batch
beam_LoadTests_Python_GBK_Dataflow_Batch
beam_LoadTests_Python_GBK_Dataflow_Streaming
beam_LoadTests_Python_GBK_reiterate_Dataflow_Batch
beam_LoadTests_Python_GBK_reiterate_Dataflow_Streaming
beam_LoadTests_Python_ParDo_Flink_Batch
beam_LoadTests_Python_ParDo_Flink_Streaming
beam_LoadTests_Python_ParDo_Dataflow_Batch
beam_LoadTests_Python_ParDo_Dataflow_Streming
beam_Python_LoadTests_Smoke
beam_LoadTests_Python_SideInput_Dataflow_Batch
beam_LoadTests_Python_CoGBK_Flink_Batch …
```

[BEAM-9980] Don't hardcode Python version in loadtests and make it switchable.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_test.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py

Allow ReadFromBigQuery to use a user pre-configured dataset for the temporary dataset.
Using a DatasetReference will also allow for cross project temporary dataset configuration.
There are some uses cases that require temporary datasets created when using beam.io.BigQuerySource to be in a different GCP project (e.g service account permissions, billing).
We could make the project where temporary datasets configurable, so that the temp dataset is created in a user specified project. Example:
```
pipeline = p | "Read from BQ source" >> beam.io.ReadFromBigQuery(
query=q,
use_standard_sql=True,
project='frankzhao-test-project',
temp_dataset=bigquery.DatasetReference(
projectId='bigquery-project', datasetId='bq_temp'))
```
This PR adds the temp_dataset option to allow user configuration of the …

[BEAM-9804] Allow user configuration of BigQuery temporary dataset

---

sdks/python/apache_beam/runners/dataflow/dataflow_metrics.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient.py

This is required to properly support runner v2 jobs that migrate from runner v1.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/las …

[BEAM-11033] Identify Dataflow metrics for portable job path based on step name.

---

runners/flink/job-server/flink_job_server.gradle
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkBatchPortablePipelineTranslator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkStreamingPortablePipelineTranslator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/functions/FlinkExecutableStageFunction.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/SdfByteBufferKeySelector.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/functions/FlinkExecutableStageFunctionTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/BundleCheckpointHandlers.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/DefaultJobBundleFactory.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SingleEnvironmentInstanceJobBundleFactory.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/StageBundleFactory.java
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/SparkExecutableStageFunctionTest.java
sdks/python/apache_beam/runners/portability/flink_runner_test.py

This PR added the sdf self-checkpoint support to portable Flink by using timer and state where
- In batch, we use `InMemoryTimerInternals` and `InMemoryStateInternals` to set the timer and persist residual elements.
- In streaming, we use `SdfFlinkTimerInternals` as the wrapper of `FlinkTimerInternals` and `SdfFlinkStateInternals` as the wrapper of `FlinkStateInternals` for one specific key.
For more design details, please refer to this [doc](https://docs.google.com/document/d/1372B7HYxtcUYjZOnOM7OBTfSJ4CyFg_gaPD_NUxWClo/edit?usp=sharing)
r: @robertwb @mxm 
cc: @ibzib @lukecwik …

[BEAM-10940] Add sdf initiated checkpoint support to portable Flink.

---

sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/pandas_docs_test.py

This significantly speeds up running the full suite. …

[BEAM-9561] Run pandas doctests in parallel.

---

release/src/main/scripts/build_release_candidate.sh

Specifically, this change checks whether a tag exists before calling the gradle release plugin, allowing the user to either delete the existing tag or skip creating the tag. Also avoids going into interactive commit messages with SVN, instead using commit messages built-in to the script.
Note that the original intention behind this change is to allow finer-grained skipping in the release candidate script to avoid problems if steps need to be repeated if a release candidate fails. For example, in the current implementation if a release candidate fails after creating a release candidate tag and that step gets run again, it'll cause an error due to trying to create an existing tag. I tried to read through the script to find other instances where repeating a step might be problematic, but I …

[BEAM-11074] build_release_candidate usability improvements.

---

sdks/python/setup.py

This helps fix the issues trying to install boto3. The incompatibility comes from these ranges:
```
* botocore==1.19.16
- urllib3 [required: >=1.25.4,<1.26, installed: 1.26.1]
- requests [required: >=2.24.0,<3.0.0, installed: 2.25.0]
- urllib3 [required: >=1.21.1,<1.27, installed: 1.26.1]
```
The error surfaces like this:
```
botocore 1.19.16 has requirement urllib3<1.26,>=1.25.4; python_version != "3.4", but you have urllib3 1.26.1.
```
Post-Commit Tests Status (on …

[BEAM-11255] Adding upper bound on urllib3 dependency

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FieldValueTypeInformation.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/JavaBeanSchema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/annotations/SchemaCaseFormat.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/annotations/SchemaFieldName.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/JavaBeanUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/POJOUtils.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/AutoValueSchemaTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/JavaBeanSchemaTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/JavaFieldSchemaTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/SchemaTestUtils.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/TestJavaBeans.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/TestPOJOs.java

Adds an `@SchemaCaseFormat` annotation that can be used to control the case format used in schema field names. For example:
```java
@DefaultSchema(JavaFieldSchema.class)
@SchemaCaseFormat(CaseFormat.LOWER_UNDERSCORE)
class MyClass {
public String user;
public int ageInYears;
@SchemaCaseFormat(CaseFormat.UPPER_CAMEL)
public boolean knowsJavascript;
}
```
Will produce a schema with fields "user", "age_in_years", and "KnowsJavascript".
I think the primary application of this will be using `lower_underscore` for schemas that will be used across languages (e.g. in LogicalType base types, and cross-language transform configuration objects), but I figured a general purpose solution based on [`CaseFormat`](https://guava.dev/releases/23.0/api/docs/com/google/common/base/CaseFormat.html) would be …

[BEAM-10989] Add @SchemaCaseFormat annotation

---

.test-infra/jenkins/PythonTestProperties.groovy
.test-infra/jenkins/job_PostCommit_CrossLanguageValidatesRunner_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_CrossLanguageValidatesRunner_Direct.groovy
.test-infra/jenkins/job_PostCommit_CrossLanguageValidatesRunner_Flink.groovy
.test-infra/jenkins/job_PostCommit_CrossLanguageValidatesRunner_Spark.groovy

Define Python versions for CrossLanguageValidatesRunner jobs as property.
affected jobs:
```
beam_PostCommit_XVR_Direct
beam_PostCommit_XVR_Flink
beam_PostCommit_XVR_Spark
```
Go | [![Build …

[BEAM-9980] do not hardcode Python version for cross language tests and make it switchable.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/maven-archetypes/examples/build.gradle
sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml

GCP libraries bom uses an incompatible version of guava. Add guava as a dependency management to override bom version
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam. …

[BEAM-11228] Add guava to dependency management in generated pom

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

#13202 introduces a bug where the algorithm that determines the parents of fused stage can create loops, because the lowest common ancestor algorithm considers a transform to be its own parent. Fusing a single transform A will result cause the fused stage's parent to be set to A. Fusing a transform A with a descendant B will also cause fused stage's parent to be set to A. To fix this, if the parent of the fused stage would be one of transforms to be fused, set the parent to the parent of that transform instead. …

[BEAM-11196] Ensure parent of fused stages is not one of its transforms

---

runners/spark/build.gradle
sdks/java/extensions/sorter/build.gradle
sdks/java/extensions/sql/build.gradle
sdks/java/io/hadoop-common/build.gradle
sdks/java/io/hadoop-file-system/build.gradle
sdks/java/io/hadoop-format/build.gradle
sdks/java/io/parquet/build.gradle

[BEAM-8615 BEAM-8569 BEAM-7937] Add hadoop 3 compatibility tests

---

sdks/java/io/google-cloud-platform/expansion-service/build.gradle
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/MutationUtils.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerConfig.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerTransformRegistrar.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/StructUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/MutationUtilsTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/StructUtilsTest.java
sdks/python/apache_beam/io/gcp/spanner.py
sdks/python/apache_beam/io/gcp/tests/xlang_spannerio_it_test.py
sdks/python/test-suites/portable/common.gradle
settings.gradle

What is left:
- transaction support (in the future I suppose)
- Is representing Mutation as Row ok? To discuss.
- There is a lot of duplication code in struct -> row and row -> struct translation. I would be grateful for some advice how (if possible in this case) to deal with it.
- SpannerWriteResult is replaced with PDone thus FailureMode must be FAIL_FAST
- To read from spanner Schema is needed to be added to the configuration. Schema can be constructed from Struct while running the pipeline, but idk how to pass the RowCoder to the pipeline otherwise. And it's to discuss whether validation of schemas equality is needed.
- I didn't generify Read and Write because there is ReadAll , Transaction etc and this way is much less complicated. ReadRows and WriteRows shouldn't be used outside …

[BEAM-10139][BEAM-10140] Add cross-language support for Java SpannerIO with python wrapper

---

runners/google-cloud-dataflow-java/build.gradle

The containers images were not being built properly for the tests and
this change moves the dependency into the created test task.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](htt …

Fix Java ValidatesRunner V2 task dependency.

---

runners/google-cloud-dataflow-java/build.gradle

Jenkins jobs were failing, rarely, when attempting to delete the container image because the container was not removed first. This is likely due to a race between shutting down the container and removing the container image. Since this is a test, it is safe to force remove the image and assume the container will be shutdown properly.
If there is actually a problem here with the containers not shutting down, it should manifest as a memory related exception on the Jenkins agent and be quite a spectacular failure (i.e. easy to notice). …

[BEAM-11263] Java cleanUpDockerImages now force removes container images.

---

sdks/python/apache_beam/dataframe/transforms.py
sdks/python/apache_beam/dataframe/transforms_test.py

* Concatenate small dataframe before shuffle.
* Omit shuffling of empty partitions.
- This requires some adjustment to use the proxy object
if *all* partitions from all workers are empty.
Projections, filterings, and aggregations are common operations that often greatly reduce the size of a dataframe, and can result in small output batches which have high relative overhead.
This is in reaction to looking at the number of (relatively tiny) elements in the dataflow ui.  …

Further dataframe batch consolidation.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

This is required to address null-pointer issue happening with 2.1.5 of gcsio. GCSIO 2.1.6 has a [fix](https://github.com/GoogleCloudDataproc/hadoop-connectors/pull/486).
Go | [![Build …

[BEAM-8889] Upgrade GCSIO to 2.1.6

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteTest.java

We shouldn't make an assertion about the number of times the writer slept, this is verifying the backoff policy which is an implementation detail. The test already verifies the total amount of time slept, which is more appropriate.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_Pos …

[BEAM-11262] Remove numSleeps assertion in SpannerIOWriteTest

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java

I haven't found evidence that this is the cause but I strongly suspect the cause of the NPE on this line:
https://github.com/apache/beam/blob/43e8b990b19d9ad3031b06e3c3dea508d0916d93/sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java#L162
is that the `Logger` corresponding to `"ConfiguredLogger"` has been GC'd. The javadoc for `Logger.getLogger` notes:
> Note: The LogManager may only retain a weak reference to the newly created Logger. It is important to understand that a previously created Logger with the given name may be garbage collected at any time if there is no strong reference to the Logger.
Once the client is closed the only reference to the logger is removed and there's the possibility it gets GC'd before we try to access it for the …

[BEAM-4136] Keep strong reference to loggers to avoid potential NPE

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

#13202 introduces a bug where the algorithm that determines the parents of fused stage can create loops, because the lowest common ancestor algorithm considers a transform to be its own parent. Fusing a single transform A will result cause the fused stage's parent to be set to A. Fusing a transform A with a descendant B will also cause fused stage's parent to be set to A. To fix this, if the parent of the fused stage would be one of transforms to be fused, set the parent to the parent of that transform instead.
This is a cherry pick of #13303. …

[BEAM-11196] Cherry-pick #13303 to the 2.26.0 release branch.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/GrpcVendoring_1_26_0.groovy

Following #12965, upgrading Conscrypt in the vendored gRPC to 2.5.1 because it's not shaded so having the same version on both sides would be clearer.
R: @justinwhite @lukecwik
Go | [![Build …

[BEAM-5748] Upgrade Conscrypt to 2.5.1 in GrpcVendoring_1_26_0

---

sdks/go/pkg/beam/runners/session/session.go

Unit tests were failing because Execute could no longer be used with RegisterRunner. This should fix that.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/ …

[BEAM-11207] Adding PipelineResult to session runner.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/testing/UsesTestStream.java

Before this change, batch-only runners would have to exclude both `UsesTestStream` and `UsesUnboundedPCollections`. This is a tiny usability improvement of the categories to make it easy to indicate a batch-only runner with a single exclusion.
--- | --- | --- | --- | --- | --- …

Make UsesTestStream extend UsesUnboundedPCollections for exclusion in batch-only runners

---

sdks/python/apache_beam/internal/metrics/metric.py
sdks/python/apache_beam/internal/metrics/metric_test.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/resource_identifiers.py
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/execution.py
sdks/python/apache_beam/metrics/metric.py
sdks/python/apache_beam/metrics/metricbase.py
sdks/python/apache_beam/metrics/monitoring_infos.py
sdks/python/apache_beam/metrics/monitoring_infos_test.py
sdks/python/apache_beam/runners/worker/sdk_worker.py
sdks/python/apache_beam/runners/worker/sdk_worker_test.py

[BEAM-11092] Add bigquery io request count metric, implementing HarnessMonitoringInfos and process_wide metrics
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache …

[BEAM-11092] Add bigquery io request count metric, implementing HarnessMonitoringInfos and process_wide metrics

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py

The size aggregator is not associative. We can lift it, but the post aggregation needs to be a sum.
This PR also adds an implementation for `count`, which is also post-aggregated with a sum.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) …

[BEAM-11303] Use sum as the post-agg for size

---

sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py
sdks/python/apache_beam/utils/sharded_key.py

The added variation of transform accepts the same parameters as the existing transform but output iterables with ShardedKey ,  See #13208 for changes for Java SDK.
Go | [![Build …

[BEAM-10475]Add WithShardedKey variation of GroupIntoBatches transform in Python SDK.

---

sdks/go/pkg/beam/core/runtime/graphx/xlang.go
sdks/go/pkg/beam/core/runtime/graphx/xlang_test.go

This is meant to be part of a larger change adding unit tests for the various pipeline transformations in graphx/xlang.go.
After how long it took to figure out how to implement this, and the realization that each other transformation is going to be similarly difficult and they're already somewhat tested by the xlang examples (and soon-to-be integration tests), I think I'd rather not implement the rest anymore. But I already implemented most of this test so I just finished it up and am sending it out in a PR. …

[BEAM-11188] Adding unit test for mergeExpandedWithPipeline

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py

Prior to this change `df[df.value > x].groupby(df.group).size()` produces sizes of the unfiltered dataset.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/ …

[BEAM-11304] groupby(Series).size() on a filtered dataframe is incorrect

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillTimerInternals.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WindmillTimerInternalsTest.java

Fix the decoding logic to avoid parsing error in output timestamp - the output timestamp encoding can contain a '+' which is used as the separator in the timer tag. 
Go | [![Build …

Fix Windmill timer tag output timestamp decoding

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

[BEAM-9547] Add support for Series.rename

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py

[release-2.26.0][BEAM-11303][BEAM-11304] Fix some incorrect result bugs with size aggregation

---

runners/flink/job-server/flink_job_server.gradle

I tried changing the taskmanager memory size, but couldn't get it to work.
R: @mxm 
cc: @tysonjh 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_ …

[BEAM-10974] Skip GroupByKeyTest.testLargeKeys10MB.

---

sdks/python/apache_beam/metrics/metric_test.py
sdks/python/apache_beam/metrics/metricbase.py

Restore original str() behaviour to MetricName, for user counter(namespace+name) style MetricNames

---

sdks/python/apache_beam/dataframe/frames.py

When doing a set_index for groupby(Series) we incorrectly indicate it preserves partitioning by index
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastC …

set_index does not preserve partitioning

---

runners/google-cloud-dataflow-java/build.gradle

r: @tysonjh
cc:  @kennknowles  …

Enable more runner v2 tests.

---

sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py

[BEAM-11070] Use self-checkpoint to enforce finalization happens.

---

.test-infra/jenkins/job_PostCommit_Java_Examples_Dataflow_V2_Java11.groovy
CHANGES.md
release/src/main/scripts/build_release_candidate.sh
release/src/main/scripts/publish_docker_images.sh
sdks/java/container/java11/build.gradle

- Fix java11 container task to actually output a java 11 container (whoops)
- Add ValidateRunner and Example postcommits against the container
- Add java11 container to release scripts
Go | [![Build …

[BEAM-8106] Add Java 11 container to release and Java 11+V2+Dataflow testing

---

CHANGES.md
sdks/python/apache_beam/io/mongodbio.py
sdks/python/apache_beam/io/mongodbio_it_test.py
sdks/python/apache_beam/io/mongodbio_test.py

This fixes issue BEAM-11266 allowing to use ReadFromMongoDB with MongoDB Atlas by optionally using `@bucketAuto` MongoDB aggregation instead of `splitVector`:
```
pipeline | ReadFromMongoDB(uri='mongodb+srv://user:pwd@cluster0.mongodb.net',
db='testdb',
coll='input',
bucket_auto=True)
```
This enhancement is based on the solution, provided by Susumu Asaga in this [comment](https://issues.apache.org/jira/browse/BEAM-4567?focusedCommentId=17152256&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17152256) to the issue BEAM-4567, related to Java MongoDB connector. …

[BEAM-11266] Python IO MongoDB: add bucket_auto aggregation option for bundling in Atlas.

---

sdks/python/apache_beam/examples/kafkataxi/README.md

`use_unified_worker` is also needed, otherwise the pipeline will use java runner.
r: @aaltay 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_Post …

Add use_unified_worker to pipeline options.

---

sdks/python/apache_beam/dataframe/expressions.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/dataframe/partitionings.py

This PR modifies `PartitioningSession` so it re-executes expressions with a variety of partitioned inputs, determined by the expression's `requires_partition_by` specification. It also verifies that the output for each type of partitioned input is partitioned consistent with the expression's `preserves_partition_by` specification.
This detected the issue fixed in https://github.com/apache/beam/pull/13398, and detected an additional issue with Series.agg's pre-aggregation, fixed in ac1e3a.
Go | [![Build …

[BEAM-11324] Add additional verification in PartitioningSession

---

sdks/python/apache_beam/dataframe/expressions.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/dataframe/partitionings.py

This cherrypicks 9054c7a8f3ca48b4ea75e5b01e18ca8e9f773354 and bd825f574e342cfa83fb09767c7d5a19a3accc55. The majority of the changes are in test code, the implementation changes are:
- Disallow grouping by Series
- Fix some incorrectly specified partitioning requirements
R: @robertwb 
R: @lostluck 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/last …

[release-2.26.0][BEAM-11324] Fix some partitioning errors that can lead to execution-time errors

---

.test-infra/jenkins/job_LoadTests_Combine_Flink_Go.groovy
sdks/go/test/load/build.gradle
sdks/go/test/load/combine/combine.go

This PR adds Combine load tests for Go SDK. …

Go SDK Combine load tests

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

[BEAM-11342] fix google3 import error

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/DefaultExpansionServiceClientFactory.java
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/ExpansionServiceClient.java
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/ExpansionServiceClientFactory.java
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/External.java

I found this inaccessibility issue while trying to use ExpansionService outside of the external transform. 
R: @ibzib

[BEAM-11343] Make ExpansionServiceClient accesible outside of core-construction-java

---

CHANGES.md
sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_read_internal.py
sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py
sdks/python/apache_beam/io/gcp/bigquery_test.py
sdks/python/apache_beam/io/iobase.py

This adds a DoFn to perform BigQuery exports and pass them downstream to be consumed.
Eventually, we'll move `ReadFromBigQuery` to use this as part of its implementation, but for now, we'll leave them separate.
r: @chamikaramj 
r: @tysonjh 
--- | --- | --- | --- | --- | --- | …

[BEAM-9650] Adding support for ReadAll from BigQuery transform

---

sdks/python/apache_beam/examples/snippets/snippets.py
sdks/python/apache_beam/runners/common.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/transforms/core.py

[BEAM-11354] Allow DoFn itself to be used as the restriction provider.

---

.test-infra/jenkins/PythonTestProperties.groovy

followup for https://github.com/apache/beam/pull/13393#discussion_r529135483 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCo …

[BEAM-9980] use ALL_SUPPORTED_VERSIONS for constant SUPPORTED_CONTAINER_TASKS for python

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

PR https://github.com/apache/beam/pull/13026 has broken Spark postcommit because of Kafka dependencies mismatch.
Starting with Kafka clients 2.5.0 Scala 2.11 is no longer supported. 
This PR reverts Kafka client to 2.4.1
Go | [![Build …

 [BEAM-11375] Downgrade Kafka clients dependency to fix spark postcommit 

---

runners/direct-java/build.gradle

r: @TobKed 
Manually tested direct runner on both windows 10 and ubuntu.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComplet …

[BEAM-11365] Direct Runner: Handle pipeline option string quotes under windows os

---

CHANGES.md
sdks/java/io/amazon-web-services2/build.gradle
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java

The original `AwsOptions` has a flat `region`, which is in conflict with the one in `DataflowPipelineOptions`
This PR renames the flag, matching the ver1 sdk (io.aws).
Go | [![Build …

[BEAM-11331] Change region flag to awsRegion in io.aws2

---

sdks/java/build-tools/beam-linkage-check.sh

This updates the beam linkage check script to be simpler to use and also removes incorrect assumptions. Now you just pass the refs you want to compare and that is that. A few minor fixes, too.
Go | [![Build …

[BEAM-11260][BEAM-11261] Remove inappropriate assumptions about repo from linkage check script

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Without this `./gradlew sdks:java:build-tools:checkstyleMain` fails with a FileNotFoundException when run with Java 11. It looks for suppression.xml in the daemon directory (see https://github.com/gradle/gradle/issues/8286).
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit …

Make checkstyle suppression filepath absolute

---

build.gradle
sdks/java/extensions/ml/build.gradle

Instead of running IT classes in the `:test` task, this PR runs them in a separate `:integrationTest` task, which is run by the Java PostCommit. …

[BEAM-11363] Create `:sdks:java:extensions:ml:integrationTest` target, run in Java PostCommit

---

sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/apache_beam/runners/portability/spark_runner_test.py

Found a couple of comments that contain wrong capitalization and a missing "=" sign.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go …

Fixed a couple of comments

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

Under some conditions, `translations.pipeline_from_stages()` after `translations.sort_stages()` could return a pipeline that was not topologically sorted due the construction of the tree of parents to subtransforms. This change ensures that the pipeline is topologically ordered by ensuring that when a transform is added to the pipeline, each of its ancestors become the last subtransform of its parent. …

[BEAM-11355] Fix topological ordering of pipeline_from_stages after sort_stages

---

runners/core-java/src/test/java/org/apache/beam/runners/core/SideInputHandlerTest.java

Encountered this while working on a somewhat larger change.
Some things are done in shared test setup that really should not be
- the setup is so trivial it doesn't save any mental space or code space
- the setup is relevant only for some test cases
- it actually mixes different windows in weird ways, seemingly to shoehorn all the test cases
into the same test setup
- the setup does not encapsulate anything meaningful; to understand a test case, it is necessary to read and remember the details of the setup.
These are inlined so each test is more independently readable and has no
irrelevant coupling. …

[BEAM-11392] SideInputHandlerTest: inline trivial test setup for clarity

---

sdks/python/apache_beam/runners/worker/bundle_processor.py

This adds the ToStringFn implementation to Python. This allows Runners to call the SDK to translate an element to a human-readable representation.
Design-doc:
https://docs.google.com/document/d/1v7iWj0LIum04mYwRM_Cvze915tATwmEzLrqj_uVBkCE/
--- | --- | --- | --- | --- | --- | …

[BEAM-11151] Adds the ToStringFn Bundle Processor to Python

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/PTransformTranslation.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/ToStringFnRunner.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/ToStringFnRunnerTest.java

This adds the ToString implementation to the Java SDK Harness.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) …

[BEAM-11151] Adds the ToStringFnRunner to Java

---

runners/flink/job-server/flink_job_server.gradle

Cherry picks https://github.com/apache/beam/pull/13218 into the release for BEAM-11273.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit …

[release-2.26.0][BEAM-11273][BEAM-10974] Skip GroupByKeyTest.testLargeKeys10MB.

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test_common.py
sdks/python/apache_beam/typehints/sharded_key_type.py
sdks/python/apache_beam/typehints/sharded_key_type_test.py

Implement `to_type_hint` and `from_type_hint` for `ShardedKeyCoder` and add a `TypeConstraint` for `ShardedKey` so during the runner API translation the corresponding coder can be added.
Go | [![Build …

[BEAM-10475] Add typehints for ShardedKeyCoder

---

dev-support/docker/Dockerfile
dev-support/docker/bashcolors.sh
dev-support/docker/beam_env_checks.sh
sdks/java/core/src/main/java/org/apache/beam/sdk/state/Timers.java
sdks/python/build-requirements.txt
start-build-env.sh
website/www/site/content/en/contribute/_index.md

This adds a docker based build environment intended for developers to have a predictable working environment with all needed tools present.
On a Linux machine (I ONLY tested this on my Ubuntu 20.04 laptop) just run the `start-build-env.sh` script to build and start a Docker based build setup that wraps around the current source tree beam copy.
This is based upon the initiative started by @omarismail94 #12837 and copies large parts from https://github.com/apache/hadoop 
As suggested by @TheNeuralBit in #12837 I was able to run `./gradlew :sdks:python:container:py37:docker` inside this docker setup which actually created a 2.39GB docker image `apache/beam_python3.7_sdk:2.27.0.dev`
TODO:  …

[BEAM-10891] Standardized developer build environment using Docker

---

build.gradle
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

This normalizes the sdk.properties file which has a build timestamp in it as well as the version and sdk version. For the purposes of the runtime classpath, these can be ignored so that tasks are not rerun if only the build timestamp is changed.
This should result in significantly higher cache hits as well as more up-to-date checks.
This also preserves timestamps for certain tasks for the same reason.
BEAM-11383
Read the [Gradle release notes](https://docs.gradle.org/6.6/release-notes.html#performance-improvements) for an explanation of runtime classpath normalization. Read the header "Improved cache hits with normalized runtime classpaths".
Below is an example of a task that would be avoided when the sdk.properties file does not change: …

[BEAM-11383] Add runtime normalization for file timestamps

---

sdks/java/core/src/main/java/org/apache/beam/sdk/annotations/Experimental.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/AvroIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Deduplicate.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicSequence.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Watch.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/ByteKeyRangeTracker.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/GrowableOffsetRangeTracker.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/HasDefaultTracker.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/HasDefaultWatermarkEstimator.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/ManualWatermarkEstimator.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/OffsetRangeTracker.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/RestrictionTracker.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/SplitResult.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/TimestampObservingWatermarkEstimator.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/WatermarkEstimator.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/WatermarkEstimators.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/package-info.java
sdks/java/io/hbase/src/main/java/org/apache/beam/sdk/io/hbase/HBaseIO.java
sdks/python/apache_beam/io/iobase.py

r: @kennknowles 
cc: @robertwb @aaltay @lukecwik  …

[BEAM-11132] Remove Experimental annotation from SDF related APIs.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py

This fix will prevent BQ-related tools from issuing unnecessary queries to verify table emptiness.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam …

Avoiding queries that check whether a BQ table is empty for streaming inserts

---

sdks/go/pkg/beam/runners/universal/runnerlib/execute.go

The 'err' object was being overridden by the output of newUniversalPipelineResult. As a result, the user was not able to catch any job errors.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badg …

[BEAM-11207] Return valid error on job failures

---

model/pipeline/src/main/proto/beam_runner_api.proto
sdks/python/apache_beam/portability/common_urns.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/runners/dataflow/internal/names.py
sdks/python/apache_beam/runners/dataflow/ptransform_overrides.py
sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py

This PR adds `GroupIntoTransform.WithShardedKey` to the runner api as a well-known composite transform and also adds the non-sharded version `GroupIntoBatches` as a component there of. This allows runners to recognize and choose the sharding approach for `GroupIntoTransform.WithShardedKey`.
This PR also adds a Dataflow override of `GroupIntoTransform.WithShardedKey` in Python for non-portable job submission, analogous to the Java implementation (#13208). For portable job submission, the changes will be done in the Dataflow service instead of in SDK. …

[BEAM-10703, BEAM-10475] Add GroupIntoBatches to runner API; add Dataflow override in Python SDK

---

runners/flink/1.10/src/test/java/org/apache/beam/runners/flink/streaming/StreamSources.java
runners/flink/1.12/build.gradle
runners/flink/1.12/job-server-container/build.gradle
runners/flink/1.12/job-server/build.gradle
runners/flink/1.12/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/AbstractStreamOperatorCompat.java
runners/flink/1.12/src/test/java/org/apache/beam/runners/flink/streaming/StreamSources.java
runners/flink/1.8/src/test/java/org/apache/beam/runners/flink/streaming/StreamSources.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkStreamingTransformTranslatorsTest.java
settings.gradle

https://issues.apache.org/jira/browse/BEAM-11419 …

[BEAM-11419] Add Flink 1.12 build target.

---

.test-infra/jenkins/job_LoadTests_GBK_Flink_Go.groovy
sdks/go/test/load/group_by_key/run.sh

Changes to fix Go SDK GBK Load test case.
- Skip GBK 7 test for now because it runs out of memory
- Fix typings in num_records for GBK_2, GBK_5, GBK_6
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBu …

[BEAM-11075] Fix go sdk gbk load test

---

sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/apache_beam/transforms/environments.py

As we introduce custom containers (mostly for Python), there are a couple of misleading or unclear log messages.
* PortableRunner currently attempts to pull the container and ignores errors, defaulting to local images. Logging added to make this path clearer.
* DockerEnvironment.default_docker_image can be called even if we don't use the default image - currently this outputs a message saying `Using default image "..."` which is very confusing. I edited to make sure it's clearer when we are using provided container image vs default container image. …

Better logging for Python Docker environment

---

sdks/go/pkg/beam/core/runtime/graphx/xlang.go
sdks/go/pkg/beam/runners/universal/runnerlib/compile.go
sdks/go/pkg/beam/testing/ptest/ptest.go

These issues were found and fixed while working on the ValidatesRunner framework, but are not directly related, so they're good candidates for a setup commit. The fixes:
1. Fixed an issue in graphx/xlang.go where the output PCollection of a composite containing an external transform wasn't being renamed properly, resulting in an error due to the composite containing a non-existent output. This was only caught when testing the Flink Runner, tests still passed with the Python Portable Runner.
2. Added a check to cross-compiling code to detect if the pipeline is being executed through go test, so an appropriate cross-compilation can be done for tests. This enables running pipelines from tests with portable runners.
3. Added a new helper function to ptest for convenience. …

[BEAM-11415] Setup and bugfixes for Go ValidatesRunner framework.

---

sdks/go/pkg/beam/runners/universal/universal.go
sdks/go/test/build.gradle
sdks/go/test/run_validatesrunner_tests.sh
sdks/go/test/validatesrunner/reshuffle_test.go
sdks/go/test/validatesrunner/validatesrunner.go
sdks/go/test/validatesrunner/validatesrunner_test.go
sdks/go/test/validatesrunner/xlang_test.go

This PR includes everything I've worked on in the Go ValidatesRunner framework so far, for initial review. Note that it includes the contents of PR #13502 as the first commit since it's a required for this code to work, but that should be reviewed in its own PR. This PR only covers the second commit.
This PR creates a new subdirectory, test/validatesrunner, that is intended to just contain a bunch of tests that run and validate lightweight pipelines. It also contains a script that handles starting job servers and expansion services, similar to run_integration_tests.sh, and one initially tested gradle build rule for running it with Flink. Running with the direct runner also works fine, with the command "go test validatesrunner/... --runner=direct". Currently, the script has only been …

[BEAM-11415] In-progress Go ValidatesRunner framework.

---

runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java

Fixes broken compile from https://github.com/apache/beam/pull/13521
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBui …

[BEAM-10402] Supress nullness and keyfor DoFnOperatorTest warnings.

---

sdks/java/io/thrift/src/main/java/org/apache/beam/sdk/io/thrift/ThriftCoder.java

The `ThriftCoder` class is currently only visible in the `thrift` package, to be used by `ThriftIO`, which is only meant to handle files.
However, this class can also be useful when consuming/producing thrift data from/to other sources/sinks, such as Kafka topics and alike.

[BEAM-11337] Make the ThriftCoder class visible from outside its package

---

website/www/site/content/en/documentation/io/built-in/snowflake.md

Fix for snowflake docs about writing from unbounded sources. 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) …

[BEAM-11439] Fix Snowflake streaming docs

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

R: @piotr-szuberski @aromanenko-dev

[BEAM-9196] Update testcontainers to 1.15.1

---

CHANGES.md
sdks/python/apache_beam/io/mongodbio.py
sdks/python/apache_beam/io/mongodbio_test.py

This enhances MongoDB connector to mask password in display_data as described in BEAM-11444.
Display data before this change:
```
"uri": mongodb+srv://top:secret@xyx456-pri.ab123.mongodb.net
"mongo_client_spec": {"username": "top", "password": "secret"}
```
Display data after this change:
```
"uri": mongodb+srv://top:******@xyx456-pri.ab123.mongodb.net
"mongo_client_spec": {"username": "top", "password": "******"}
``` …

[BEAM-11444] Python IO MongoDB: mask password in display_data uri and spec.

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

This improves the readability of the stage and transform names for transforms and stages resulting from the `translations.eliminate_common_key_with_none` and `translations.pack_combiners`. This also fixes an issue where the transform name was incorrectly set to the stage name.
For example, for `TranslationsTest.test_pack_combiners`, previously both the Pack transform and stage  were set to `(ref_AppliedPTransform_multiple-combines/mean-perkey/CombinePerKey(MeanCombineFn)_16)+(ref_AppliedPTransform_multiple-combines/count-perkey/CombinePerKey(CountCombineFn)_21)/Pack`. After this change, the Pack transform name is set to `multiple-combines/Packed[mean-perkey/CombinePerKey(MeanCombineFn), count-perkey/CombinePerKey(CountCombineFn)]/Pack` and the Pack stage name is set to …

[BEAM-11429] User-friendly names for packed combiners

---

start-build-env.sh

added support for mac-os, tested on mac-os 10.15.2, ubuntu 20.04
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ …

[Beam-11438] start-build-env.sh improve for macOS

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

Fixes a bug introduced by #13202 where the parent for a fused stage (or packed combiner) gets set to `None` if more than two stages are fused (or packed). This occurs because `_lowest_common_ancestor` uses the `subtransforms` field of the `PipelineContext`'s transforms to figure out parent-child relationships. However, a stage that is created by fusion or by another optimizer phase will not be present in the `PipelineContext`'s transforms. As a result, such a stage is passed to `_lowest_common_ancestor`, it will return `None`. This change fixes it by additionally using the `parent` field of the input stages.
This bug only affects runners that use `translations.pipeline_from_stages` with `partial=True`. …

[BEAM-11196] Fix `None` parent when fusing >2 stages

---

sdks/python/apache_beam/io/gcp/bigquery_read_internal.py
sdks/python/apache_beam/io/gcp/bigquery_test.py

A user reported problem with decoding repeated, non-record BigQuery fields (see jira ticket's description).
Now all cases (repeatable, record; repeatable, non-record; non-repeatable, record; non-repeatable, non-record) should be supported by the coder.
--- | --- | --- | --- | …

[BEAM-11230] Fix a bug with decoding repeated fields

---

runners/portability/java/build.gradle

https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR_PR/1/testReport/
r: @tysonjh 
cc: @kennknowles 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-bea …

[BEAM-10450][BEAM-10449][BEAM-10453][BEAM-10995] Enable more Java tests on Python FnRunner

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

When Dataflow runs portable python pipelines, such as all Python streaming pipelines and all pipelines on Runner V2, Dataflow service currently starts as many SDK containers as there are CPU cores on the VMs. 
This behavior was originally initiated by the SDK setting an experiment use_multiple_sdk_containers, and it was possible to disable this behavior  by supplying `--experiment=no_use_multiple_sdk_containers`. 
Dataflow service no longer needs SDK to supply these experiments, so we clean up this logic. 
Dataflow service may still recognize `--experiment=no_use_multiple_sdk_containers` for some time but it is NOT RECOMMENDED to use this knob: in the future Dataflow may have better algorithms for deciding how many SDK containers to start, and specifying this knob may interfere with these …

Do not add unnecessary experiment use_multiple_sdk_containers.

---

sdks/python/apache_beam/runners/portability/spark_runner_test.py

Skip dynamic timer test in portable spark test

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test_common.py
sdks/python/apache_beam/coders/typecoders.py
sdks/python/apache_beam/io/flink/flink_streaming_impulse_source_test.py
sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/pipeline_context.py
sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/environments.py
sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/transforms/ptransform.py
sdks/python/apache_beam/typehints/native_type_compatibility.py

Also cleans up multi-language pipelines related hooks in Python SDK that are not needed when we use portable job submission (hence directly generate Dataflow steps from the Runner API proto).
These hooks were mostly were added in PRs https://github.com/apache/beam/pull/8270 and https://github.com/apache/beam/pull/11185.
Lang | SDK | …

[BEAM-11360] Updates Dataflow Python multi-language pipelines to use portable job submission by default

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

Reverts apache/beam#13475
Reason: for streaming jobs new codepath using UW (https://github.com/apache/beam/blob/9f97585160fae644d9b4a7f0dca6558c82c29723/sdks/python/apache_beam/runners/dataflow/internal/apiclient.py#L276) is not yet triggered by default. 
So, at this time Dataflow first need to change the behavior to not require `use_multiple_sdk_containers` for streaming pipelines, or we need to use UW codepath for all streaming pipelines in Beam.

Revert "Do not add unnecessary experiment use_multiple_sdk_containers."

---

sdks/python/apache_beam/io/restriction_trackers.py
sdks/python/apache_beam/runners/common.py

[BEAM-11472] Support SDF on non-splitting runners such as legacy Dataflow.

---

sdks/python/apache_beam/transforms/core.py

Currently the DoFn.process docstring does not render well. This fixes it, and clarifies how the default params are used: …

Update DoFn docstring

---

sdks/python/apache_beam/io/concat_source.py
sdks/python/apache_beam/io/concat_source_test.py

Fix concat source fraction_consumed() in degenerate case.

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/TransformProcessingThreadTracker.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java

[BEAM-11474] Track transform processing thread in Java SDK harness and set log entry field

---

sdks/java/extensions/sql/udf/src/main/java/org/apache/beam/sdk/extensions/sql/udf/AggregateFn.java

[BEAM-10925] Create interface for SQL Java aggregate function.

---

sdks/java/io/xml/src/main/java/org/apache/beam/sdk/io/xml/XmlSource.java
sdks/java/io/xml/src/test/java/org/apache/beam/sdk/io/xml/XmlSourceTest.java

Fixing java.nio.BufferOverflowException in getFirstOccurenceOfRecordElement method of XMLReader …

[Beam-11002] Fixes BufferOverflowException in XMLReader

---

sdks/python/apache_beam/runners/portability/portable_runner.py

Adding combiner packing optimization for Portable Runner

---

website/www/site/content/en/contribute/_index.md
website/www/site/content/en/documentation/runtime/environments.md

This rewrites the container guide as we move to launch custom containers for Dataflow runner. There are two methods that should be highlighted - one is using the released Dockerhub images as a base image, and one is building from Beam source itself. 
--- | --- | --- | --- | …

Rewrite container docs for custom containers

---

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/KeyedPushedBackElementsHandler.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java

[BEAM-11481] emit output watermark on watermark hold change

---

sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/NexmarkLauncher.java
sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/NexmarkOptions.java

watermarks using commit time, allow specifying the
number of partitions instead of requiring launcher
to have access to kafka cluster, and removing
unneeded deserialization of keys.
--- | --- | --- | --- | --- | --- …

[BEAM-11391] Improve Nexmark Kafka support to track

---

sdks/python/apache_beam/runners/portability/portable_runner.py

[release-2.27.0][cherry-pick] Adding combiner packing optimization for Portable Runner

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/TestPubsub.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/TestPubsubSignal.java

As with TestPubsub (https://github.com/apache/beam/pull/13273), the official GCP client is a better choice for this application since it has better tuned timeout and retry policies.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | …

[BEAM-11159] Use official GCP client in TestPubSubSignal

---

CHANGES.md
sdks/python/apache_beam/transforms/core.py

Reverts apache/beam#13220
Context: https://github.com/apache/beam/pull/13220#issuecomment-750674335

[BEAM-11522] Revert "Optimizes extract_output for 1 element accumulator case."

---

sdks/python/apache_beam/examples/snippets/snippets.py
sdks/python/apache_beam/examples/snippets/snippets_test.py
sdks/python/apache_beam/examples/sql_taxi.py

WriteStringsToPubSub is a deprecated API, we shouldn't use it in any examples.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/ico …

[BEAM-11524] Remove usages of WriteStringsToPubSub in examples

---

sdks/python/apache_beam/transforms/core.py

This reverts commit 34e27ba1dd6ec8886d0df7e5fcd3600fd64db914 on 2.27.0 release branch.
See: https://github.com/apache/beam/pull/13220#issuecomment-750674335 for motivation.
Go | [![Build …

[BEAM-11522] Revert "Optimizes extract_output for 1 element accumulator case. (#13220)"

---

sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
sdks/python/apache_beam/io/gcp/bigquery_test.py

Should hopefully allow streaming pipelines to use FILE_LOADS on Dataflow.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComple …

[BEAM-11517] Fix test_file_loads on Dataflow

---

sdks/python/apache_beam/io/gcp/pubsub.py
sdks/python/apache_beam/io/gcp/pubsub_test.py
sdks/python/apache_beam/runners/direct/direct_runner.py

[BEAM-11524] Change WriteStringsToPubsub to use WriteToPubsub.

---

sdks/go/pkg/beam/core/graph/coder/map_test.go
sdks/go/pkg/beam/core/graph/coder/row.go
sdks/go/pkg/beam/core/graph/coder/row_decoder.go
sdks/go/pkg/beam/core/graph/coder/row_encoder.go
sdks/go/pkg/beam/core/graph/coder/row_test.go
sdks/go/pkg/beam/core/graph/coder/testutil/testutil.go
sdks/go/pkg/beam/core/graph/coder/testutil/testutil_test.go

Adds "custom schema coder" support. I believe Python and Java call these providers, but that's not exactly what's happening in the Go SDK. 
This PR adds the ability to register a factory function for schema coder functions for a given type. This enables overriding the default behavior for Go types in the schema coders with a custom one, for the type itself, or any matching interface.
To ensure users *can* write custom schema coders, a testing utility has been added to validate the factory functions, and ensure the coders encode to a valid schema equivalent type.
Benchmarks were added to demonstrate the umbrella helper coder functions, using a custom coder function, registering a custom coder function, and comparing to the equivalent we use for JSON encoding at present.
There are more …

[BEAM-9615] Custom Schema Coder Support

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/TestPubsubSignal.java

I had the subscription and topic arguments reversed in this call.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://c …

[BEAM-11537] Fix TestPubSubSignal.waitForStart

---

CHANGES.md
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FieldValueTypeInformation.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/JavaBeanSchemaTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/TestJavaBeans.java

I'm facing an exception telling me that my JavaBean contained a setter for a field that had a mismatching nullable attribute, although both getter and setter (parameters) are annotated with `@Nullable` (`org.apache.avro.reflect.Nullable`).
```java
@DefaultSchema(JavaBeanSchema.class)
public final class SampleBean {
@Nullable
private Float value;
public @Nullable Float getValue() {
return value;
}
public void setValue(@Nullable Float value) {
this.value = value;
}
}
```
The code responsible for determining if a setter's parameter is nullable looks wrong to me, since it ~~does check if the type (class) itself is annotated with `@Nullable` instead of checking the actual parameter's annotations.~~ only considers type annotations instead of looking at parameter annotations, too. Java …

[BEAM-11530] Annotated setter parameters handled wrong in schema creation

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py

[BEAM-11532] Fix edge case in merge where left_on and right_on contain equivalent column names

---

sdks/java/io/hadoop-common/src/main/java/org/apache/beam/sdk/io/hadoop/SerializableConfiguration.java
sdks/java/io/hadoop-common/src/test/java/org/apache/beam/sdk/io/hadoop/SerializableConfigurationTest.java
sdks/java/io/parquet/src/main/java/org/apache/beam/sdk/io/parquet/ParquetIO.java
sdks/java/io/parquet/src/test/java/org/apache/beam/sdk/io/parquet/ParquetIOTest.java

`ParquetIO.Sink` supports user provided Configuration flags. With increasing number of flags in AvroParquetReader options.
Making the configuration flags accessible to the user makes it more usable.
For example, enable reading INT96 data.
R:@iemejia can you help review.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit …

[BEAM-11527] Allow user defined Hadoop ReadSupport flags for ParquetReader

---

sdks/python/apache_beam/examples/snippets/snippets.py
sdks/python/apache_beam/examples/snippets/snippets_test.py
sdks/python/apache_beam/examples/sql_taxi.py
sdks/python/apache_beam/io/gcp/pubsub.py
sdks/python/apache_beam/io/gcp/pubsub_test.py
sdks/python/apache_beam/runners/direct/direct_runner.py
sdks/python/setup.py

This cherrypicks three PRs into the 2.27.0 branch. #13614 and #13615 for BEAM-11524, and #13623 (restrict pandas version to <1.2.0 for BEAM-11531).
R: @pabloem 
CC: @boyuanzz 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | …

[release-2.27.0][BEAM-11524] Fix WriteStringsToPubSub, remove usages in examples

---

CHANGES.md
sdks/java/io/hadoop-format/src/main/java/org/apache/beam/sdk/io/hadoop/format/HadoopFormatIO.java
sdks/java/io/hadoop-format/src/test/java/org/apache/beam/sdk/io/hadoop/format/HadoopFormatIOReadTest.java

[BEAM-11457] Add option to skip key-value clone

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/RowToPubsubMessage.java

[BEAM-8829] only drop event_timestamp when it exists

---

.test-infra/jenkins/job_PostCommit_Python_ValidatesRunner_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Python_ValidatesRunner_Dataflow_V2.groovy
sdks/python/test-suites/dataflow/build.gradle
sdks/python/test-suites/gradle.properties

Makes the Python versions in Dataflow VR suite configurable …

[BEAM-9980] do not hardcode Python version for dataflow validate runner tests and make it switchable

---

.github/workflows/build_wheels.yml

[BEAM-11569] Enabling wheels to be built using Apache-based workflow

---

build.gradle
sdks/java/core/build.gradle
sdks/java/core/src/main/resources/org/apache/beam/sdk/sdk.properties

This PR does two things.
1. It removes the timestamp from the sdk.properties file.
2. This doesn't ignore the `sdk.properties` anymore for the purposes of the runtime classpath. This means that the tests will rerun when the versions change.
This PR assumes that [there is no need for the timestamp in the sdk.properties](https://github.com/apache/beam/pull/13597#issuecomment-750423282). If there is such a need, the other option to resolve this issue is to wait until Gradle 6.8 is released which will have the ability to ignore specific properties [such as the timestamp](https://docs.gradle.org/6.8-rc-3/release-notes.html#more-cache-hits-for-tasks-with-runtime-classpaths) in the sdk.properties file.
See the discussion on [the PR](https://github.com/apache/beam/pull/13597) for more …

[BEAM-11512] Fix sdk.properties caching, remove timestamp

---

.github/workflows/cancel.yml

[BEAM-11569] Fixing cancel workflows

---

sdks/go/pkg/beam/runners/dataflow/dataflow.go
sdks/go/pkg/beam/runners/dataflow/dataflowlib/job.go

Add `disk_size_gb` flag for Go SDK. This allows users to modify the default requested disk size for Dataflow worker machines.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https:// …

[BEAM-11580] Add disk_size_gb flag for Go SDK.

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/transforms/util_test.py

Some internal tooling suggested these changes, since they will make any error message clearer.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastComplete …

Clarify some assertions

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/transforms/ptransform.py

This does not fully resolve BEAM-1833, but that cleanup will be best done once all runners are portable. 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/j …

[BEAM-1833] Give transforms more control over the names of their inputs and outputs.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java

Prior to BEAM2.20 with Cloud Spanner Library 1.06, the timeout for Cloud Spanner streaming read was 2 hours. This was changed to 1 hour with the library update in BEAM 2.20. Setting this value back to 2 hours.
R: @nielm  @chamikaramj 
Go …

[BEAM-11543] Increase Spanner streaming read timeout to 2 hours

---

sdks/python/test-suites/portable/common.gradle

The default reads from pipeline_options.py, which hasn't been updated from Flink 1.10 to 1.12 yet.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam …

[BEAM-11579] Specify flink_job_server_jar instead of using default.

---

sdks/go/pkg/beam/core/graph/coder/double_test.go

This PR adds a test to the standard double coder.  The test cases are modeled from that used in the [sdks/python/apache_beam/coders/coders_test_common.py#L189](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/coders/coders_test_common.py#L189).  I would like to request either @youngoli or @lostluck to review this PR. …

[BEAM-8493] Add test to standard double coder

---

sdks/java/container/build.gradle
sdks/java/container/common.gradle

Fixes https://issues.apache.org/jira/browse/BEAM-11586 by removing artifact for Java licenses. 
Verified manually by running `./gradlew :sdks:java:container:java8:docker --info` with `-Pdocker-pull-licenses` toggled on/off and inspecting the container built …

[BEAM-11586] Fix on-demand pulling of Java container licenses

---

runners/google-cloud-dataflow-java/build.gradle

Reverts apache/beam#13699. The new image causes performance regressions.

Revert "Update Dataflow worker harness container image version."

---

sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/transforms/external_test.py

According to Beam runner API proto if a spec is set then the URN is required: https://github.com/apache/beam/blob/master/model/pipeline/src/main/proto/beam_runner_api.proto#L1578
Currently, when external SDK does not set a spec, Python proto copying results in an empty spec being set in the final transform proto.
Lang | SDK | …

[BEAM-11614] Do not set empty specs in external transforms

---

model/pipeline/src/main/proto/beam_runner_api.proto

R: @chamikaramj 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark …

[BEAM-11614] Clarify Beam model for zero subtransform case

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

It incorrectly infers proxy and fails in pandas 1.2.0 which disallows calling transform on an empty DataFrame.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Sp …

[BEAM-11531] Remove transform implementation

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

Where possible, tests are replicated in frames_test.py
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apac …

[BEAM-11531] Skip some DataFrame tests that are broken in pandas 1.2.0

---

.github/workflows/build_wheels.yml
.github/workflows/cancel.yml
.gitmodules

Airflow repositories will be removed soon. Instead, this PR creates submodules for existing actions in the Beam repo, and uses them instead of relying on external repos.
r: @ibzib 
cc: @potiuk @ashb
Go | [![Build …

[BEAM-11569] Enabling wheels to be built using Beam-based submodules workflow

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go

[BEAM-11604](https://issues.apache.org/jira/browse/BEAM-11604)
I tried to the example streaming_wordcap/wordcap.go and panic occurred.
```
$ cd beam/sdks/go/examples/streaming_wordcap/wordcap.go
$ go run wordcap.go \
--project=MY_PROJECT\
--temp_location=gs://MY_BUKET/tmp\
--staging_location=gs://MY_BUKET/binaries\
--runner=dataflow
...
panic: runtime error: invalid memory address or nil pointer dereferencepanic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x15b85c3]
goroutine 1 [running]:github.com/apache/beam/sdks/go/pkg/beam/core/runtime/graphx.(*marshaller).addMultiEdge(0xc00079ba10, 0x1d16d9d, 0x8, 0xc00025a0a0, 0x2544dc0, 0xc0001f6c00, 0x2, 0x30, 0x2867560) …
```

[BEAM-11604] Fix translate.go to prevent panic

---

sdks/go/pkg/beam/runners/universal/universal.go

Change "enviroment" to "environment".

Fix typo in universal.go

---

sdks/go/pkg/beam/coder.go
sdks/go/pkg/beam/core/graph/coder/iterable.go
sdks/go/pkg/beam/core/graph/coder/registry_test.go
sdks/go/pkg/beam/core/graph/coder/row.go
sdks/go/pkg/beam/core/graph/coder/row_decoder.go
sdks/go/pkg/beam/core/graph/coder/row_encoder.go
sdks/go/pkg/beam/core/graph/coder/row_test.go
sdks/go/pkg/beam/core/runtime/genx/genx.go
sdks/go/pkg/beam/core/runtime/graphx/coder.go
sdks/go/pkg/beam/core/runtime/graphx/schema/logicaltypes.go
sdks/go/pkg/beam/core/runtime/graphx/schema/schema.go
sdks/go/pkg/beam/core/runtime/graphx/schema/schema_test.go
sdks/go/pkg/beam/encoding.go
sdks/go/pkg/beam/encoding_test.go
sdks/go/pkg/beam/example_schema_test.go
sdks/go/pkg/beam/forward.go
sdks/go/pkg/beam/schema.go
sdks/go/pkg/beam/transforms/top/top.go
sdks/go/pkg/beam/transforms/top/top_test.go

This PR does a few things, but is the last non "carefully migrate" or cleanup step for Schema support in the Go SDK.
1. Theres' a toggle to enable Schema support, the package var `beam.EnableSchemas`. This will have your pipelines use the schema infrastructure to encode types that don't have an alternate custom coder registered. It's currently off, to permit graceful migration, though once remaining details are sorted out, it will switch to being default on instead.
2. Adds a way to conveniently RegisterSchemaProviders which is a helper on the beam package. There's a bit of cleanup to be done around the usability experience around schemas, however, this one is probably going to stick, as it demonstrates the mechanism and includes an example of registering custom providers for given types. …

[BEAM-9615] Add Schema Logical Type Provider support

---

runners/core-java/build.gradle

Since enabling the strict dependencies on all Java modules is a large and critical change to be merged all at once. Therefore, task [[BEAM-10961](https://issues.apache.org/jira/browse/BEAM-10961)] is divided into sub-tasks and strict dependencies are enabled to each module separately which is comparatively easy to review and merge. …

[BEAM-10961] Enabled strict dependency on Core Java runner

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

For design details, please refer to the doc here: https://docs.google.com/document/d/1FU3GxVRetHPLVizP3Mdv6mP5tpjZ3fd99qNjUI5DT5k/edit#
Next step is to add support of starting reading from new added TopicPartitions.
r: @dpmills @aromanenko-dev 
--- | --- | --- | --- | --- | …

[BEAM-11325] ReadFromKafkaDoFn should stop reading when topic/partition is removed or marked as stopped

---

runners/samza/build.gradle
runners/samza/job-server/build.gradle

Since enabling the strict dependencies on all Java modules is a large and critical change to be merged all at once. Therefore, task [[BEAM-10961](https://issues.apache.org/jira/browse/BEAM-10961)] is divided into sub-tasks and strict dependencies are enabled to each module separately which is comparatively easy to review and merge. …

[BEAM-10961] Enabled strict dependencies on samza

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/SplitResult.java

Add nullable annotations to SplitResult.of (primary and residual can be null).
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastC …

[BEAM-10402] Add nullability annotations to SplitResult.of

---

runners/jet/build.gradle

Since enabling the strict dependencies on all Java modules is a large and critical change to be merged all at once. Therefore, task [[BEAM-10961](https://issues.apache.org/jira/browse/BEAM-10961)] is divided into sub-tasks and strict dependencies are enabled to each module separately which is comparatively easy to review and merge. …

[BEAM-10961] Enabled strict dependency on Jet Runner

---

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkExecutionEnvironments.java

I was surprised that [auto] does not seem to respect the user-provided
Flink configuration (BEAM-11612).
This PR makes [auto] respect the user-provided
Flink configuration when it creates a local stream environment.
For batch, simply modify the default Configuration.
The difference is because batch `ExecutionEnvironment` exposes its configuration publicly, while `StreamExecutionEnvironment` does not.
R: @mxm  …

[BEAM-11570] Disable classloader check for [auto] mode.

---

runners/direct-java/build.gradle

Since enabling the strict dependencies on all Java modules is a large and critical change to be merged all at once. Therefore, task [[BEAM-10961](https://issues.apache.org/jira/browse/BEAM-10961)] is divided into sub-tasks and strict dependencies are enabled to each module separately which is comparatively easy to review and merge. …

[BEAM-10961] Enabled strict dependency on Direct Java runner

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py

This PR also adds an `expect_error` option to `DeferredFrameTest._run_test`. When true, `_run_test` will verify that our implementation raises the same error as pandas. …

[BEAM-11542] Add support for projecting GroupBy objects

---

.test-infra/jenkins/CommonTestProperties.groovy
.test-infra/jenkins/job_PostCommit_CrossLanguageValidatesRunner_Flink.groovy
.test-infra/jenkins/job_PostCommit_Java_Nexmark_Flink.groovy
.test-infra/jenkins/job_PostCommit_Java_PortableValidatesRunner_Flink_Batch.groovy
.test-infra/jenkins/job_PostCommit_Java_PortableValidatesRunner_Flink_Streaming.groovy
.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Flink.groovy
.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Flink_Java11.groovy
.test-infra/jenkins/job_Publish_Docker_Snapshots.groovy

This PR does not include [Flink.groovy](https://github.com/apache/beam/blob/master/.test-infra/jenkins/Flink.groovy) and dependents.
Does anyone know why we do `import CommonJobProperties as commonJobProperties` instead of just `import CommonJobProperties`? …

[BEAM-9541] Jenkins tests use latest Flink version (1.12).

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/portability/sdk_container_builder.py
sdks/python/apache_beam/runners/portability/sdk_container_builder_test.py

The SdkContainerImageBuilder class currently only offers an option to build images locally or in google cloud build. I would like to be able to define my own subclass which I can use outside of GCP. There is an existing utility which allows this (BeamPlugin) and is used by filesystems to allow easy extension.
Existing functionality should be unchanged, however when another subclass is available, it should be able to be selected by specifying its module and class name, eg '--prebuild_sdk_container_engine=custom_beam_extension_package.submodule.CustomSdkContainerImageBuilder'
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips …

Allow extension of SdkContainerImageBuilder

---

runners/google-cloud-dataflow-java/build.gradle

This line was accidentally re-merged in #13211, after being deleted when different logic for container cleanup was added (https://github.com/apache/beam/blame/master/runners/google-cloud-dataflow-java/build.gradle#L280-L287).
Go | …

[BEAM-11678] Fix Java DataflowRunner test container cleanup

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/Publishers.java

Change the publisher used by the beam sink from the RoutingPublisher which uses a static set of partitions determined at startup to the PartitionCountWatchingPublisher which watches for changes in the partition count.
Go | [![Build …

[BEAM-10114] Allow Pub/Sub Lite Sink to support increasing partitions

---

sdks/python/apache_beam/transforms/combiners.py

Combiners have a label constructor argument which is not currently used correctly.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/l …

[BEAM-11272] Fix combiner label constructor arg

---

build.gradle
release/src/main/scripts/build_release_candidate.sh
sdks/java/container/build.gradle
sdks/python/container/build.gradle

instead of bash when building the release candidate.
Bash arrays make no sense and I've seen the ones in this file cause at least two bugs already.
Delegating to Gradle also lets as many of the tasks run in parallel as the OS allows.
Also use LOCAL_CLONE_DIR instead of LOCAL_PYTHON_STAGING_DIR for clarity, and rm it afterwards.
R: @emilymye  …

[BEAM-9541] Create a Gradle task to push all docker images, and use it

---

build.gradle
sdks/java/build-tools/beam-linkage-check.sh

Linkage Checker 1.5.4 has better handling for error reporting. This PR also addresses the following small enhancements:
- There is a minor typo in the shell script "ARTIFACT_LIST".
- When Gradle happens to fail to generate baseline files (in a baseline mode), it can skip the corresponding validate mode.
Example failure: Maven Central timeout: https://gist.github.com/suztomo/c4525d718af5b963245054d53abb5732#file-gistfile1-txt-L730
Post-Commit Tests Status (on master …

[BEAM-11640] Linkage Checker version upgrade to 1.5.4 (latest)

---

sdks/java/io/hadoop-format/build.gradle

Moved here from PR# 13688 per @ibzib's request.
R: @ibzib, please add other folks if needed.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostC …

[BEAM-10961] Enable strict dependency checking on sdks/java/io/hadoop-format

---

sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/dataframe/pandas_top_level_functions.py

Required to run some new test cases in pandas 1.2.0
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache. …

[BEAM-11531] Add pd.to_datetime, handle DeferredBase args in _defer_to_pandas

---

buildSrc/src/main/groovy/org/apache/beam/gradle/Repositories.groovy

This doesn't erase https://repo.spring.io/plugins-release because it is still used by Gradle plugins. 
https://github.com/apache/beam/blob/280107a48d83a2c72c70a19a881f5789200818dc/buildSrc/build.gradle#L26-L34
Go | [![Build …

[BEAM-11689] Add public.nexus.pentaho.org to offline repositories.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimator.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimatorTest.java

Since Numeric types were added to Spanner, it is possible to use BigDecimal values in Spanner mutations.
This PR adds this support in the MutationSizeEstimator. 
Support for writing these types was already added in #12818
-------------------------------------------------------------------------------------------------------------------
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBu …

[BEAM-11643] Add BigDecimal support for SpannerIO

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/runners/dataflow/ptransform_overrides.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py

Previously, combiner packing did not work in Dataflow because the optimizations were only applied to the `proto_pipeline` object and not the `pipeline` object. This fixes combiner packing, and also makes it disabled by default unless enabled using the `pre_optimize` option.
Cherry-pick of #13763.
Lang | SDK | Dataflow | Flink | …

[BEAM-11695] [cherry-pick] Combiner packing in Dataflow (#13763)

---

examples/java/src/main/java/org/apache/beam/examples/snippets/transforms/io/gcp/bigquery/BigQueryReadFromQueryWithBigQueryStorageAPI.java
website/www/site/content/en/documentation/io/built-in/google-bigquery.md

Jira [ticket](https://issues.apache.org/jira/browse/BEAM-7034) was resolved but the [docs](https://beam.apache.org/documentation/io/built-in/google-bigquery/#storage-api) haven't been updated accordingly with a snippet.
Go | [![Build …

[BEAM-7034] Add example snippet to read fromQuery using BQ Storage API.

---

runners/flink/job-server/flink_job_server.gradle
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperator.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/TimerReceiverFactory.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/translation/PipelineTranslatorUtils.java
sdks/python/apache_beam/runners/portability/flink_runner_test.py

[BEAM-10120] Add dynamic timer support to portable Flink

---

sdks/java/bom/build.gradle

Beam BOM incorrectly produces a Gradle module metadata with the variant library instead of platform. Temporarily disable the metadata generation so Gradle users can depend on Beam BOM as a platform
Verified that the snapshot no longer produces a module file and manually created a project that was able to use the new snapshot of Beam BOM as a platform …

[BEAM-11709] Disable Gradle module metadata generation for Beam BOM

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/JavaUdfLoader.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/ScalarFunctionImpl.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamCalcRel.java

Note that it is possible for one CalcFn to require multiple jars, so for
now it is the user's responsibility to ensure there are no conflicts.
This is no different from user-provided jars in the Java SDK.
This adds an optional jar path field to ScalarFunctionImpl. This field
will be populated in a later PR.
R: @amaliujia @apilloud  …

[BEAM-10925] Load user-provided jars in CalcFn.

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamJavaUdfCalcRule.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/SqlAnalyzer.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java

The rule isn't used yet because there are no `USER_DEFINED_JAVA_SCALAR_FUNCTIONS` yet.
Most of this code was originally written by @amaliujia.
R: @amaliujia @apilloud 
Go | [![Build …

[BEAM-10925] Add rule to replace Calc with BeamCalcRel for ZetaSQL UDFs.

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/SupportedZetaSqlBuiltinFunctions.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlDialectSpecTest.java

It does not pass internal compliance tests because nulls are not propagated correctly (this is not a flaw with BIT_XOR specifically, the problem seems to affect all ZetaSQL aggregations).
R: @amaliujia
cc: @sonam-vend @y1chi 
Go | …

[BEAM-10379] Remove BIT_XOR from ZetaSQL supported functions list.

---

runners/flink/flink_runner.gradle

[BEAM-11732] Revert flink-clients from runtime to compile configuration.

---

sdks/go/pkg/beam/core/runtime/pipelinex/clone.go

We need to copy Annotations field as well when doing a ShallowClonePTransform, otherwise we lose the Annotations. This is an issue when there multiple instances of the same DoFn with an annotation in the pipeline.
CREDITS=robertre@

[BEAM-11357] Copy Annotations when cloning PTransforms

---

sdks/python/apache_beam/examples/snippets/snippets_test.py
sdks/python/apache_beam/runners/direct/direct_runner.py
sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/apache_beam/runners/portability/local_job_service.py
sdks/python/apache_beam/runners/portability/portable_runner.py
sdks/python/apache_beam/runners/worker/sdk_worker_main.py

TLDR; Propagates pipeline options to the python DirectRunner when running in multi_processing mode.
When running a test pipeline with the DirectRunner, and with the direct_running_mode=multi_processing I found that pipeline options were not set as expected in the worker processes, causing the pipeline to fail. Specifically I required filesystem related options to be set in order to access a remote filesystem. It seems that the sdk_worker_main.py runner script expects the options to be populated into an environment variable (PIPELINE_OPTIONS) prior to running, which was not the case for the SubprocessSdkWorker.
It also seems that the sdk_worker_main.py needs to set the loaded pipeline options using the global `filesystems.FileSystems.set_options` which wasn't the case before. This seems …

[BEAM-11736] Propagate pipeline options to direct runner

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

Add an integration test using TestPipeline with packable combiners. Combiner packing will be triggered if and only if the TestPipeline runner enables it.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComplete …

[BEAM-11715] Add ValidatesRunner test for translations.pack_combiners

---

sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/portable_runner.py
sdks/python/apache_beam/runners/portability/portable_runner_test.py

An indentation error in portable_runner.py is causing optimizations to not run when pre_optimize is set to default or all. This was broken by #13573. Additionally, the existing 'all' optimizations branch is not working in PortableRunner due to `greedily_fuse_stages` and `partial=False`.
This change re-enables optimizations for 'default' and 'all'. It also disables `translations.pack_combiners` due to BEAM-11715, and adds an 'all_without_fusion' option that is used to run `PortableRunnerOptimizedWithoutFusion`. …

[BEAM-11700] Fix PortableRunner skipping optimizations

---

sdks/python/apache_beam/dataframe/schemas.py
sdks/python/apache_beam/dataframe/schemas_test.py
sdks/python/setup.py

All of the blocking changes have been merged. This PR removes restriction on pandas to allow upgrade to 1.2.0 and 1.2.1.
Unfortunately there was a new breakage in pandas 1.2.1 caused by https://github.com/pandas-dev/pandas/issues/39474. So this PR includes a couple of other changes:
- Skips affected test when run with 1.2.1
- Removes special handling for pandas 0.x, we already opted not to support it.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/las …

[BEAM-11531] Allow pandas <1.3.0

---

sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/portable_runner.py
sdks/python/apache_beam/runners/portability/portable_runner_test.py

An indentation error in portable_runner.py is causing optimizations to not run when pre_optimize is set to default or all. This was broken by #13573. Additionally, the existing 'all' optimizations branch is not working in PortableRunner due to `greedily_fuse_stages` and `partial=False`.
This change re-enables optimizations for 'default' and 'all'. It also disables `translations.pack_combiners` due to BEAM-11715, and adds an 'all_without_fusion' option that is used to run `PortableRunnerOptimizedWithoutFusion`.
Cherry-pick of #13824. …

[BEAM-11700] [cherry-pick] Fix PortableRunner skipping optimizations

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

Add an integration test using TestPipeline with packable combiners. Combiner packing will be triggered if and only if the TestPipeline runner enables it.
Cherry-pick of #13851.
Go | [![Build …

[BEAM-11715] [cherry-pick] Add ValidatesRunner test for translations.pack_combiners

---

sdks/python/apache_beam/runners/interactive/interactive_environment_test.py

Moved cleanup patch into each test method after each new_env() instance
creation to avoid cleanup invocation in new_env() call when there could be
race conditions in tests running on Jenkins.
Go | [![Build …

[BEAM-11476] Resolve flaky tests

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffset.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedSource.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java

When headers are not supported, there are no reflection calls remaining as this knowledge is computed once in the ConsumerSpEL singleton.
When headers are supported but the decoder does not implement the method to examine headers, there are no reflection calls based upon a cache keyed by decoder in the ConsumerSpeEL singleton.
When headers are supported and possibly used by the coder, a reflection-based expression is still evaluated for each deserialization.  I tried to enable expression compilation but was unable to get it working, I believe due to the generics as part of the Deserializer<T> object but I am not sure.  That is a possible performance improvement for the future for uses that require headers. …

[BEAM-11657] Reduce reflection calls when reading from Kafka

---

sdks/java/extensions/sql/udf-test-provider/src/main/java/org/apache/beam/sdk/extensions/sql/provider/UdfTestProvider.java
sdks/java/extensions/sql/zetasql/build.gradle
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/SqlAnalyzer.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLPlannerImpl.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/ExpressionConverter.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlJavaUdfTest.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlUdfTest.java

This completes the proof of concept. Note however that when UDFs and
built-in ZetaSQL operators are mixed, the program will crash without
warning.
R: @amaliujia @apilloud 
Go | [![Build …

[BEAM-10925] Enable user-defined Java scalar functions in ZetaSQL.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/GroupIntoBatches.java

Test failure introduced by #13805 which missed a change in the check on `maxBufferingDuration` - the parameter used to default to null but it now defaults to zero.
R: @boyuanzz @kennknowles 
Go | [![Build …

[BEAM-11746] Fix test flakiness: GroupIntoBatches.testInGlobalWindow

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/TopicPartitionCoder.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/WatchKafkaTopicPartitionDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/TopicPartitionCoderTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/WatchKafkaTopicPartitionDoFnTest.java

design doc: https://docs.google.com/document/d/1FU3GxVRetHPLVizP3Mdv6mP5tpjZ3fd99qNjUI5DT5k/edit#
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_ …

[BEAM-11325] Kafka Dynamic Read

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/runners/dataflow/ptransform_overrides.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

This reverts the use of `translations.pack_combiners` in DataflowRunner added in #13763, but preserves other changes (i.e. minor bug fix in `translations.pack_combiners`, disabling optimizations by default, and testing that `translations.pack_combiners` is disabled).
This reason for the revert is that `translations.pack_combiners` results in packed `CombinePerKey` transforms without subtransforms which is not accepted by Dataflow, and that `Pipeline.from_runner_api` will break cross-language pipelines …

[BEAM-11715] Partial revert of "Combiner packing in Dataflow" (#13763)

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/runners/dataflow/ptransform_overrides.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

This reverts the use of `translations.pack_combiners` in DataflowRunner added in #13763, but preserves other changes (i.e. minor bug fix in `translations.pack_combiners`, disabling optimizations by default, and testing that `translations.pack_combiners` is disabled).
This reason for the revert is that `translations.pack_combiners` results in packed CombinePerKey transforms without subtransforms which is not accepted by Dataflow, and that `Pipeline.from_runner_api` will break cross-language pipelines
Cherry-pick of #13884. …

[BEAM-11715] [cherry-pick] Partial revert of "Combiner packing in Dataflow" (#13763)

---

sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/portability/portable_runner.py

[BEAM-11723] [cherry-pick] Avoid eliminate_common_key_with_none without combiner packing

---

sdks/go/pkg/beam/core/graph/edge.go
sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/runtime/graphx/xlang.go
sdks/go/pkg/beam/external.go
sdks/go/pkg/beam/external_test.go
sdks/go/pkg/beam/util.go

Support user side direction of cross language or external transforms.
Often the runners have their own mechanism for interpretting a URN + Payload, but that payload may contain data to specify how to route the inputs and outputs. ExternalTagged permits users to provide local tags for the input PCollections and output PCollection types to assist with this routing.
Later changes may want to add variadic Options to External and ExternalTagged to support Artifact provisioning, and Environment setting, though preferablly without using the beam protos directly in the API. (Similarly for ParDo as well). …

[BEAM-9918] Support Tagged external PTransforms

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java

Python SDK caches bundle_processors per process_bundle_descriptor and shutdowns inactive bundle_processors every 1 mins since last access: https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/worker/sdk_worker.py#L557-L582.
Currently Java only use Map to cache BundleProcessor, which is not really a cache with proper evicting policy. …

[BEAM-11752] Using LoadingCache instead of Map to cache BundleProcessor

---

sdks/python/apache_beam/dataframe/expressions.py

Without this change, it's possible that an incorrectly specified expression can create a flaky test. Since we only keep the result from the last executed partitioning, it's possible to get a false positive if, say, Singleton partitioning was used last. This change ensures we always use the most challenging partitioning for the final result. 
Pre-Commit Tests Status (on master branch)
--- |Java | Python | Go | Website | Whitespace | Typescript
Non-portable | [![Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [![Build …

[BEAM-11324] Impose consistent ordering on partitionings used in PartitioningSession

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/mongodb/build.gradle

This PR implements a change suggested in PR# 13830. The mongo_java_driver created here will subsequently be used in that PR.
R: @ibzib  
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon …

[BEAM-10961] Make mongo-java-driver dependency a named variable

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/PipelineTranslation.java

This is documented as required in the proto, but not maintained by `PipelineTranslation` (despite being a topological traversal).
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](http …

[BEAM-11784] Maintain topological order of root transforms

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

[BEAM-11787] Removes new VR test that fails for Dataflow

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py

This fixes a breakage caused by #13884. Before #13884, when streaming was enabled, we never call `translations.optimize_pipeline` on `self.proto_pipeline`. After #13884, when streaming is enabled, we never call `translations.optimize_pipeline` on `self.proto_pipeline` with `phases=[]`. This breaks Dataflow Python streaming because calling `translations.optimize_pipeline` with `phases=[]` is not a no-opt.
This fix only calls `translations.optimize_pipeline` when the pipeline is not streaming and when phases is non-empty. …

[BEAM-11787] Do not call `translations.optimize_pipeline` in Dataflow Streaming

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

This cherry-picks https://github.com/apache/beam/pull/13957 …

[BEAM-11787] Removes VR test

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py

This cherry-picks https://github.com/apache/beam/pull/13951
* Do not call `translations.optimize_pipeline` in Dataflow Streaming
* Lint
Go | [![Build …

[BEAM-11787] Do not call `translations.optimize_pipeline` in Dataflow

---

sdks/go/build.gradle
sdks/go/test/run_integration_tests.sh

Resolve collision due to go:build building a collision with go:test:build
```
> Task :sdks:go:test:goPrepare
Found global GOPATH: /home/rebo/git.
go build github.com/apache/beam/sdks/go/test/integration/driver: mkdir ./build/bin/integration/: file exists
> Task :sdks:go:buildLinuxAmd64 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':sdks:go:buildLinuxAmd64'.
> Build failed due to return code 1 of: 
Command:
/home/rebo/.gradle/go/binary/1.12/go/bin/go build -o ./build/bin/integration/driver github.com/apache/beam/sdks/go/test/integration/driver
Env:
GOEXE=
GOPATH=/home/rebo/git
GOROOT=/home/rebo/.gradle/go/binary/1.12/go
GOOS=linux
GOARCH=amd64
```
Essentially, it's actually mkdir that fails, because it was already build in go:goTest, when …

[BEAM-11647] Fix go:goBuild gradle rules for build collision

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteGroupedRecordsToFiles.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/testing/FakeDatasetService.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java

Use GroupIntoBatches.WithShardedKey API to enable dynamic sharding when using FILE_LOADS for unbounded data. This is a follow-up change to #13496.
This PR 
- Wires `withAutoSharding` option in BigQueryIO builder to `BatchLoads`.
- Allows `numFileShards` to be 0 when performing streaming FILE_LOADS. 
Lang | SDK | Dataflow | Flink | …

[BEAM-11772] Integrate BigQuery sink file loads with GroupIntoBatches

---

sdks/python/apache_beam/runners/interactive/interactive_environment_test.py

1. Moved the cleanup mock for the flaky test down to the statement we
want to check instead of placing an assert_not_called before the
statement that we cannot guarantee in the testing environment.
2. The culprit statement could be the `set_cache_manager` when in the
testing environment, the global singleton ie.current_env() holds a
non empty cache manager for some reason while a new cache manager
set would trigger a cleanup.
3. Moved some of the set_cache_manager tests to use local
InteractiveEnvironment instance rather than the global one. …

[BEAM-11476] Resolve flakiness

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml
sdks/java/io/google-cloud-platform/build.gradle

This reverts #13765, as it breaks SpannerReadIT in Java PostCommit.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https:/ …

[BEAM-11805] Revert version updates from #13765

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriter.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java

At present, the `WriteRecords` transform for KafkaIO does not recognize the `partition` property defined on `ProducerRecord` instances consumed by the transform:
```
producer.send(
// The null property in the following constructor represents partition
new ProducerRecord<>(
topicName, null, timestampMillis, record.key(), record.value(), record.headers()),
new SendCallback());
```
Because of this limitation, in a scenario where a user may desire an explicitly defined partitioning strategy as opposed to round-robin, they would have to create their own custom `DoFn` that defines a KafkaProducer (preferably within a @StartBundle) similar to the following approach (in Kotlin):
```
private class ExampleProducerDoFn(...): DoFn<...>() {
private lateinit var producer: KafkaProducer<...> …
```

[BEAM-11806] Explicit Partition Support for KafkaIO.WriteRecords

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamJavaUdfCalcRule.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamZetaSqlCalcRule.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlJavaUdfTest.java

[BEAM-11747] Reject the mixed Java UDF and ZetaSQL builtin operator cases

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java

[BEAM-11811] [Dataflow Java] Don't allow numWorkers > maxNumWorkers.

---

sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/fn_api_runner/execution.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/spark_runner_test.py
sdks/python/apache_beam/runners/worker/bundle_processor.py

This reverts commit 625ee1f6e27636f26672e973ecbcecf19a8cb361.
The commit broke ValidateRunnerXlangTest.combineGloballyTest broken in beam_PostCommit_XVR_Direct
See test failure details here:
https://issues.apache.org/jira/browse/BEAM-11822?filter=-2
--- | --- | --- | --- | --- …

[BEAM-11822] Revert "[BEAM-2914] Add portable merging window support to Python. (#12995)"

---

build.gradle.kts

https://issues.apache.org/jira/browse/BEAM-11827
The `sdks/java/build-tools/beam-linkage-check.sh` is not working. It fails with "Failed to generate the baseline file. Check the build error above." ([full log](https://gist.github.com/suztomo/b5a33361ad83c5e5c9054b393ac496c1)).
It's because `./gradlew ... -PjavaLinkageWriteBaseline=build/linkagecheck/baseline-beam-sdks-java-io-google-cloud-platform.xml :checkJavaLinkage` task does not generate a file. 
Beam repository has migrated to the Gradle Kotlin DSL recently. The Kotlin Gradle DSL needs to add a spread operator when passing an array to "args" method. Otherwise the DSL passes a String argument from toString of the array (see the screenshot of the problem below; it shows the DSL passed an unexpected String to LinkageCheckerMain):
The …

[BEAM-11827] checkJavaLinkage task requires a spread operator for args

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml
sdks/java/io/google-cloud-platform/build.gradle
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java

This patch contains the workaround to replace the user-agent for spanner.
R: @TheNeuralBit  @nielm 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/bea …

[BEAM-11805] Replace user-agent for spanner

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java

This adds hooks to run the ZetaSQL Compliance tests (currently internal to Google) on individual calcs.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job …

[BEAM-10925] Support selecting Calc for ZetaSQL testing

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfig.java

It is difficult to write unit tests that use the bigtable emulator, because the cached channel pool is shared globally within a process.  This means multiple unit tests running concurrently against different emulator instances will all hit whichever test runs first.
This is admittedly a workaround to the behavior of the Bigtable client, ideally it would cache channel pools per-host, rather than globally. …

[BEAM-11801] Don't set useCachedDataPool if an emulator host is set

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlJavaUdfTest.java

This makes the filter for BeamCalcRel a passing set of operators.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild …

 [BEAM-11747] Make BeamCalcRel safe for ZetaSQL

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowWorkUnitClient.java

If a time correction happens, `endTime` can be before `startTime`, which cause `IllegalArgumentException` (the end instant must be greater than the start instant) in `DataflowWorkerUnitClient.reportWorkItemStatus`. 
Compute the elapsed time by `endTime.getMillis() - startTime.getMills()` which may be a negative value but I think it's ok because it's only logging purpose.
Post-Commit Tests Status (on master …

[BEAM-11832] Fix IllegalArgumentException in Interval

---

sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlJavaUdfTest.java

R: @amaliujia @apilloud 
cc: @kennknowles  …

[BEAM-11747] Disable BeamJavaUdfCalcRule by default.

---

sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py

1. Changed how Linux system exposes worker handler endpoints to
sibling Java docker containers when executing pielines with
SqlTransforms in containerized notebook environment.
2. Before the change, pipelines with external transforms cannot be
executed if the SDK is running inside a docker container.
3. Even after the change, the docker container running the SDK needs to
set up Java and Docker (DooD or DinD) for xlang support.
4. The change does not take effect if the SDK is not running in a
notebook(ipython) environment.
5. The change also works even if the notebook environment running the
SDK is not in a docker container. …

[BEAM-10708] Support SqlTransform in container

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

[BEAM-9547] Fill in some trivial compliance gaps

---

.test-infra/jenkins/job_LoadTests_FnApiRunner_Python.groovy

Restructuring the file to copy `job_LoadTests_Combine_Python.groovy`
The reason influxdb export was not working is that we were not adding additionalPipelineOptions to the job options, and thus the export did not include the InfluxDB instance.
See [sample run logs](https://ci-beam.apache.org/job/beam_Python_LoadTests_FnApiRunner_Microbenchmark/31/consoleFull) are missing influx_db_host:
```
00:00:27.176 [src] $ /home/jenkins/jenkins-slave/workspace/beam_Python_LoadTests_FnApiRunner_Microbenchmark/src/gradlew -PloadTest.mainClass=apache_beam.testing.load_tests.microbenchmarks_test -Prunner=DirectRunner -PwithDataflowWorkerJar=false "-PloadTest.args=--publish_to_big_query=true --influx_measurement=python_microbenchmarks --project=apache-beam-testing --metrics_dataset=load_test …
```

[BEAM-11791] Fixing FnApiRunner Microbenchmarks to export to influxDB

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/udaf/ArrayAgg.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/SupportedZetaSqlBuiltinFunctions.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/SqlOperatorMappingTable.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/SqlOperators.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlDialectSpecTest.java

[BEAM-11800] Support ARRAY_AGG fn for Zetasql dialect

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/HttpHealthcareApiClient.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOSearchIT.java

When the search result returned from FhirIO.Search is empty, the following exception occurs:
```
Caused by: java.lang.NullPointerException
at com.google.gson.JsonArray.addAll (JsonArray.java:117)
at org.apache.beam.sdk.io.gcp.healthcare.FhirIO$Search$SearchResourcesJsonString$SearchResourcesFn.searchResources (FhirIO.java:1695)
at org.apache.beam.sdk.io.gcp.healthcare.FhirIO$Search$SearchResourcesJsonString$SearchResourcesFn.processElement (FhirIO.java:1662)
```
Changed the first "addAll" to be within the "while hasNext" loop, and fixed "hasNext" to also check for null, as this causes:
```
Caused by: java.lang.NullPointerException
at org.apache.beam.sdk.io.gcp.healthcare.HttpHealthcareApiClient$FhirResourcePages$FhirResourcePagesIterator.hasNext(HttpHealthcareApiClient.java:964)
at …
```

Add null checks to FhirIO.Search for when the search results are empty.

---

website/build.gradle

Attempt to fix failures in https://ci-beam.apache.org/job/beam_PostCommit_Website_Publish/ by 'git stash' then 'git checkout asf-site' before grgit checkout of asf-site branch.
Go | [![Build …

[BEAM-11796] Fix website build

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

bump google-cloud-pubsub to 1.110.3, because we follwed dependencies in google_cloud_platform_libraries_bom sets version.
The current master branch depends on `16.3.0` (#13990)
https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/16.3.0/artifact_details.html
^ It depends on `com.google.cloud:google-cloud-pubsub:1.110.3`
Since this is newer than the current master(`1.108.6` ) , I think it's better to update
*Success*
https://gist.github.com/masahitojp/6a292e3d8ff5506383fca3a44805bafb …

[BEAM-11770] bump google-cloud-pubsub to 1.110.3(google_cloud_platform_libraries_bom )

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/WindowingStrategyTranslation.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/WindowingStrategyTranslationTest.java

Discovered this by running on a runner that:
1. Does not deserialize to the Java class and call `isNonMerging()` (which all the Java-based runners do)
2. Does not special-case the session window URN unless the NEEDS_MERGE bit is set.
Go …

[BEAM-11824] Set merge status in WindowingStrategyTranslation

---

sdks/java/io/azure/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/azure/

---

sdks/java/io/solr/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/solr

---

sdks/java/io/influxdb/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/influxdb

---

sdks/java/io/xml/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/xml

---

sdks/java/io/synthetic/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/synthetic

---

sdks/java/io/splunk/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/splunk

---

sdks/java/io/hcatalog/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/hcatalog

---

sdks/java/io/kafka/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/kafka

---

sdks/java/io/jdbc/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/jdbc

---

sdks/java/io/expansion-service/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/expansion-service

---

sdks/java/io/elasticsearch/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/elasticsearch

---

sdks/java/io/bigquery-io-perf-tests/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/bigquery-io-perf-tests

---

sdks/java/io/kinesis/build.gradle
sdks/java/io/kinesis/expansion-service/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/kinesis

---

sdks/java/io/tika/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/tika

---

sdks/java/io/contextualtextio/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/io/contextualtextio

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java

Adding a getSuccesses() method to the FhirIO.Write.Result - useful for the healthcare API users to know which bodies were successfully written to the store.
I also made the check for TupleTags consistent in FhirIO.Read.Result and FhirIO.Search.Result (using the PCollectionTuple .has() method) since the cast from TupleTagList -> java.util.Collection resulted in a ClassCastException for me. …

Returning successful writes in FhirIO.Write.Result

---

runners/google-cloud-dataflow-java/build.gradle
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

This is a regression test for the following: a side input is created once and consumed by two separate transforms.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apa …

Two side input test

---

sdks/python/apache_beam/testing/load_tests/microbenchmarks_test.py
sdks/python/apache_beam/tools/teststream_microbenchmark.py

Adding a microbenchmark for running a simple pipeline with TestStream and a few groupings in parallel.
r: @rohdesamuel 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-bea …

[BEAM-11791] Adding a microbenchmark for TestStream

---

website/www/site/content/en/contribute/attributes.md
website/www/site/content/en/contribute/become-a-committer.md
website/www/site/data/en/committer_traits.yaml
website/www/site/layouts/partials/section-menu/en/contribute.html

This PR re-applies the changes to the become a committer page that were reverted from the website revamp (#13871), with the comments addressed:
- Matches ordering between attributes section and attributes page
- Uses Beam mascot image for "Beam community practices"
- Makes minor copy adjustments (capitalization, spelling)
- Adds a "process" section with details about the information used to select committers
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit …

[BEAM-11344] Apply "Become a Committer" changes from Website Revamp

---

.test-infra/jenkins/job_PostRelease_NightlySnapshot.groovy
release/src/main/groovy/MobileGamingCommands.groovy
release/src/main/groovy/mobilegaming-java-dataflow.groovy
release/src/main/groovy/quickstart-java-dataflow.groovy
release/src/main/groovy/quickstart-java-direct.groovy
release/src/main/groovy/quickstart-java-flinklocal.groovy
release/src/main/groovy/quickstart-java-twister2.groovy

- Attempt to reduce 'Connection Reset' errors with mvn wagon flags.
- Fix shutdown process that fails when the job is not in state Running. …

[BEAM-11377] Fix retry & cleanup issues.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py
sdks/python/apache_beam/io/gcp/bigquery_test.py
sdks/python/apache_beam/transforms/util.py

This is a parity of Java changes (#13496 and #13859).
Use `GroupIntoBatches.WithShardedKey` API to group and batch write before streaming to BigQuery service. Currently batching is done best-effort upon bundle finalization.
This PR adds an option to `WriteToBigQuery` to toggle between the existing and new implementation for both streaming inserts and file loads. …

[BEAM-11408] Integrate Python BigQuery sink with GroupIntoBatches

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineJob.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/TestDataflowRunner.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/MonitoringUtil.java

We've seen a number of cases of "job terminate in state UNRECOGNIZED but did not return a failure reason". This will make it easy to notice what the unrecognized state is.
The risk is that it could create a lot of logging, but that should be limited to the polling in waiting for a job to finish. Whenever the Dataflow service creates a new state, it will be unrecognized by past SDKs, so this log line _will_ produce warnings for users of past SDKs in this scenario. …

Log a warning when Dataflow returns an unrecognized state

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PerSubscriptionPartitionSdf.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/PerSubscriptionPartitionSdfTest.java

This is currently not available in default dataflow and causes a hard error
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComp …

[BEAM-10114] Fix PerSubscriptionPartitionSdf to not rely on the presence of BundleFinalizer

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/AvroUtils.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/AvroUtilsTest.java

The left hand side of the comparison can be equal as well.
When registering multiple coders, it will produce a NPE when checking if the fromRowFunction is already registered:
```
[WARNING] 
java.lang.NullPointerException
at org.apache.beam.sdk.schemas.utils.AvroUtils$RowToGenericRecordFn.equals (AvroUtils.java:559)
at org.apache.beam.sdk.schemas.SchemaCoder.equals (SchemaCoder.java:208)
at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Objects.equal (Objects.java:52)
at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.HashBiMap.seekByKey (HashBiMap.java:224)
at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.HashBiMap.get (HashBiMap.java:254)
at org.apache.beam.runners.core.construction.SdkComponents.registerCoder (SdkComponents.java:265)
at …
```

[BEAM-11864] Use objects.equals instead of raw comparison

---

sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslNestedRowsTest.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlDialectSpecTest.java

This is a list of SQL tests which should pass, but fail.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- …

[BEAM-9378] Add ignored tests which fail in various ways when querying nested structures

---

sdks/java/build-tools/src/main/resources/beam/suppressions.xml
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamZetaSqlCatalog.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/SqlAnalyzer.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLPlannerImpl.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/ExpressionConverter.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/SqlOperators.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlJavaUdfTest.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlNativeUdfTest.java

This is mostly just a refactor. The catalog doesn't include user-defined
functions from the Calcite schema yet.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache …

[BEAM-11778] Create a wrapper for ZetaSQL catalog and refactor accordingly.

---

runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/InstanceBuilder.java

[BEAM-11870] Re-raise underlying exception for InvocationTargetException

---

sdks/java/io/parquet/src/main/java/org/apache/beam/sdk/io/parquet/ParquetIO.java
sdks/java/io/parquet/src/test/java/org/apache/beam/sdk/io/parquet/ParquetIOTest.java

Provide setCoder, withCoder methods in ParquetIO.Parse<T> and ParquetIO.ParseFiles<T> to provide explicit coder.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apach …

[BEAM-11861] Add methods to explicitly provide coder for ParquetIO's Parse and ParseFiles

---

sdks/java/extensions/sorter/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/extensions/sorter

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/extensions/ml/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/extensions/ml

---

sdks/java/extensions/protobuf/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/extensions/protobuf

---

sdks/java/extensions/join-library/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/extensions/join-library

---

sdks/java/extensions/jackson/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/extensions/jackson

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/MonitoringUtil.java

Since adding the warning log about unrecognized states, I've seen that PENDING is not recognized. I mapped it to RUNNING since that is closest.
Technically, both adding and removing enums could be a compatibility issue. It is an unfortunate API design. The `State` enum is both too detailed (having states that are not very generic) but also not detailed enough (not allowing runners to have runner-specific details because it is an enum not a type parameter).
So my approach is to just put a band-aid on it and map states to their closest Beam state. Eventually, if we care, we might design a better API and deprecate this one.
We could also just document something like "you have to have a `default` clause in your `switch` statements because we intend to add new enums". Probably most users are …

Recognize JOB_STATE_PENDING from Dataflow and map to RUNNING

---

sdks/java/extensions/euphoria/build.gradle
sdks/java/extensions/google-cloud-platform-core/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/extensions/google-cloud-platform-core

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_FnApiRunner_ubenchmarks.json

Updating charts for Python DirectRunner benchmarks.
Sample image - note how both series are shown in a single chart.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.a …

Attempting improvements on DirectRunner Python dash

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillStateInternals.java
sdks/java/testing/watermarks/src/main/java/org/apache/beam/sdk/testing/watermarks/WatermarkLatency.java
sdks/java/testing/watermarks/src/main/java/org/apache/beam/sdk/testing/watermarks/package-info.java

Two independently passing PRs were merged today, however due to an overlap between them the merges broke the build. This fixes the build.

Fix Beam breakage

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/Read.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/ReadTest.java

The watemark reported by reader in trySplit needs to be stored and reported after call to trySplit.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/bea …

[BEAM-11833] Fix reported watermark after restriction split in UnboundedSourceAsSDFRestrictionTracker

---

sdks/java/extensions/zetasketch/build.gradle

[BEAM-10961] enable strict dependency checking for sdks/java/extensions/zetasketch

---

runners/flink/1.10/job-server/build.gradle
runners/flink/1.11/job-server/build.gradle
runners/flink/1.12/job-server/build.gradle
runners/flink/1.8/job-server/build.gradle
runners/flink/1.9/job-server/build.gradle
runners/flink/job-server/flink_job_server.gradle

PR #13658 intended to enable strict dependency checking for everything under runners/flink, but it missed runners/flink/job-server.
It also seems to have introduced unnecessary changes to runners/flink/<version>/job-server/build.gradle files
This PR enables strict dependency checking for runners/flink/job-server (which effectively covers  runners/flink/<version>/job-server/). 
R: @ibzib …

[BEAM-10961] enable strict dependency checking for flink/job-server

---

sdks/python/apache_beam/io/jdbc.py

I have executed python jdbc in Dataflow runner, and it worked when i use runner_v2 options. please check it
https://github.com/apache/beam/blob/master/sdks/python/apache_beam/options/pipeline_options.py#L910
```
"--experiments=use_runner_v2",
```
>MVP, and FeatureCompletness nearly done for SDKs, Python ULR, and shared java runners library. Performance is good >and multi-language pipelines are supported. Currently, the Flink and Spark runners support portable pipeline execution, as >does Dataflow when using the Dataflow Runner v2. See the Portability support table for details
https://beam.apache.org/roadmap/portability/#status
```
from apache_beam.io.jdbc import ReadFromJdbc
from …
```

jdbc python supported Dataflow runner

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/EnvironmentsTest.java
sdks/python/apache_beam/transforms/environments.py
sdks/python/apache_beam/transforms/environments_test.py

This adds the TO_STRING capability in the Java and Python SDK environments. This allows runners to query the SDKs to see if it supports this primitive.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedB …

[BEAM-11151] Add the TO_STRING capability to Java and Python

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_FnApiRunner_ubenchmarks.json

This will show all charts together, and will show the metric names correctly.
Currently only two charts are shown together, and the metric names show up wrong.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCo …

Fix legend for Python Directrunner microbenchmarks

---

model/pipeline/src/main/proto/beam_runner_api.proto

Specify the time resolution for TestStreamPayload.

---

runners/google-cloud-dataflow-java/build.gradle
runners/portability/java/build.gradle

Fix typos for excluding testMergingCustomWindowsWithoutCustomWindowTypes

---

sdks/java/expansion-service/build.gradle
sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceTest.java

- Switch to checkerframework nullness annotations in ExpansionServiceTest
- Remove temp checkerframework testCompile …

[BEAM-10632] Checkerframework nullness cleanups

---

sdks/java/extensions/euphoria/build.gradle

This is the same change as PR #14083, which was merged successfully.
However, when PR #14084 was merged, one unintended effect was that the change from #14083 got reversed. This is potentially explained by the following: The change in #14083 had unintentionally moved into #14084 and one of the commits in #14084 was reversing that stray change. The merge commit for #14084 (b7125d0) in addition to the single file that was intended for #14084 also added this reversal commit.
R: @ibzib 
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-j …

[BEAM-10961] Enable strict dependency checking for sdks/java/extensions/euphoria (second attempt)

---

sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

Adds a new test method in pandas_doctests_test.py that runs the doctests from groupby objects.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastComplete …

[BEAM-9547] Add groupby doctests

---

sdks/python/container/piputil.go

Remove pip version check to avoid an extra request and unactionable warning.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

This change sets a hard deadline of 30s on calls to SplitReadStream in the BigQuery storage source. This will help to avoid cases where pipelines are killed due to high-latency calls on this path.
Go | [![Build …

[BEAM-11326] Add a deadline of 30s to SplitReadStream

---

model/pipeline/src/main/proto/beam_runner_api.proto

Add topic and subscription overridden field into pubsub proto.

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/runners/dataflow/ptransform_overrides.py

Remove the Dataflow experiment `--enable_streaming_auto_sharding` used to gate the runner determined sharding option provided by `GroupIntoBatches`. Now that we have options in sinks to opt in/out the feature, e.g., https://github.com/apache/beam/blob/2e9e9a8e2815458eee382bbef64facea05c90eca/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java#L2370, we don't need the experiment any more. 
Post-Commit Tests Status (on …

[BEAM-11772, BEAM-11408] Remove Dataflow experiment --enable_streaming_auto_sharding

---

runners/samza/src/main/java/org/apache/beam/runners/samza/translation/PViewToIdMapper.java

PValueBase.toString() now appends the hashcode to the end. This causes the PViewToIdMapper generates IDs with hashcode, which can be inconsistent in different Samza containers. And therefore causes runtime issues.
We should exclude the hashcode from the id. …

[BEAM-11748] Fix PViewToIdMapper in Samza runner

---

sdks/python/apache_beam/io/gcp/bigquery_file_loads.py

I encountered the following error that appears to be caused by #13839 
```
TypeError: Unable to deterministically encode '<TableReference
datasetId: 'my-dataset-id'
projectId: 'my-project-id'
tableId: 'my-table-id'>' of type '<class 'apache_beam.io.gcp.internal.clients.bigquery.bigquery_v2_messages.TableReference'>', please provide a type hint for the input of 'WriteToBigQuery/BigQueryBatchFileLoads/GroupFilesByTableDestinations' [while running 'WriteToBigQuery/BigQueryBatchFileLoads/IdentityWorkaround']
```
The outputs of `WriteRecordsToFile`, `WriteGroupedRecordsToFile`, and `TriggerLoadJobs` can contain `TableReference` which does not have a deterministic coder. The PR uses `bigquery_tools.get_hashable_destination` to create a string representation of `TableReference` so that it can be …

[BEAM-11884] Pass destination as str rather than TableReference within BigQueryBatchFileLoads

---

sdks/java/io/parquet/src/main/java/org/apache/beam/sdk/io/parquet/ParquetIO.java
sdks/java/io/parquet/src/test/java/org/apache/beam/sdk/io/parquet/ParquetIOTest.java

We should expose only Hadoop's Configuration as we do in other IOs. This also helps the Beam API to be compatible with the Parquet APIs. I introduced here a test that uses Parquet to do a filter predicates for example.
R: @aromanenko-dev 
CC: @TheNeuralBit for awareness

[BEAM-11913] Add support for Hadoop configuration on ParquetIO

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java

**Please** add a meaningful description for your change here. I would like to remove the PrettyPrint from the output. This decreases the size of the job definition:
```
With the PR:
-rw-r--r--  1 fdriesprong  wheel    45M Mar  1 22:27 /tmp/pubsub-to-bigquery.json
With 2.28.0:
-rw-r--r--  1 fdriesprong  wheel    47M Mar  1 22:30 /tmp/pubsub-to-bigquery.json
``` …

[BEAM-11904] Remove PrettyPrint from job definition

---

sdks/python/apache_beam/dataframe/frame_base.py

Add __repr__ and disallow __bool__ for DeferredScalar

---

sdks/python/apache_beam/portability/python_urns.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations_test.py

Depends on https://github.com/apache/beam/pull/14160
R: @yifanmai 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuil …

[BEAM-10409] Use annotations to control combiner packing.

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

This basically results multi-language pipelines using GCR images for external SDKs.
This update only works for released Beam versions. For unreleased Beam code SDK harness containers for external SDKs have to be manually overridden similar to today.
--- | --- | --- | --- | --- …

[BEAM-11613] Updates Dataflow pipelines to always use SDK Harness containers hosted in GCR

---

build.gradle.kts

For more info on the flake see BEAM-11918. This fix is pretty straightforward, it avoids any race conditions with the goTest task by executing it alone first before executing the other Precommit tasks in parallel.
Go | [![Build …

[BEAM-11647] Avoid flake by splitting Go Precommit into 2 phases

---

sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/dataframe/partitionings.py

This PR addresses an issue in doctests where the output expression wasn't being run through PartitioningSession. So expressions that should be impossible (e.g. `fillna(method='ffill')`) were being executed successfully. Most of the remaining changes are addressing the resulting compliance failures.
The final commit, 0947055, adds an ugly hack to make sure that frames with multiindexes evaluate equally, i.e.:
```
Series name  Row ID
s1           0         a
1         b
s2           0         c
1         d
dtype: object
```
Is converted into:
```
Series name  Row ID
s1           0         a
s1           1         b
s2           0         c
s2           1         d
dtype: object
```
This is required for some of the new test failures. …

[BEAM-11925] Ensure that output expression is partitioned in doctest framework

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java
sdks/python/apache_beam/io/gcp/bigquery_file_loads.py

Using user triggering frequency to limit `GroupIntoBatches` could introduce performance penalties as the triggering frequency could be set to a large value and we have to buffer all the data in the states (as `GroupIntoBatches` uses state/timer for batching). …

[BEAM-11772] Fix auto-sharding parameter for BigQuery sink with FILE LOADS

---

.test-infra/jenkins/job_PostRelease_NightlySnapshot.groovy

Previous 'fix' for retries broke credentials by executing on the
'ubuntu' tagged machine instead of 'beam'. This reverts that part of the
change.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/b …

[BEAM-11377] Fix credentials regression.

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/WindowMergingFnRunner.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/WindowMergingFnRunnerTest.java

…r to avoid accumulating unnecessary state
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job …

[BEAM-11952] Clean up merged window result in MergingViaWindowFnRunner to avoid accumulating unnecessary state

---

sdks/java/io/debezium/build.gradle

Enable strict dependency checking for sdks/java/io/debezium
R: @ibzib 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompleted …

[BEAM-10961] enable strict dependency checking for sdks/java/io/debezium

---

sdks/python/apache_beam/coders/stream.pyx
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/execution.py
sdks/python/apache_beam/runners/common.py
sdks/python/apache_beam/runners/worker/statesampler_fast.pyx
sdks/python/apache_beam/transforms/cy_dataflow_distribution_counter.pyx
sdks/python/apache_beam/transforms/stats.py
sdks/python/apache_beam/utils/counters.py
sdks/python/apache_beam/utils/windowed_value.py
sdks/python/setup.py

[BEAM-1251] Use Python 3 semantics in Cython-compiled modules.

---

sdks/python/apache_beam/runners/interactive/utils_test.py

1. Fixed the flaky test by explicitly assert_called_with rendered
HTML/Javascript strings.
2. The flakiness could be introduced from other display calls emitted
from the IPythonLogHandler though couldn't reproduce it locally.
To rule out the flakiness and since assertion at a lower level is
added, assertion around display is discarded. …

[BEAM-11797] Fixed the flaky test

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillStateReader.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WindmillStateReaderTest.java

from 8MB to 32MB.
This decreases the number of fetches for large bag by 4x. Such
page fetches are generally triggered by bag iteration and are
therefore block user processing. The latency overhead of performing
a fetch is less than the latency added by fetching additional data. …

[BEAM-11910] Increase the bag page limit for continuation pages

---

runners/spark/3/build.gradle
runners/spark/3/job-server/build.gradle
runners/spark/job-server/spark_job_server.gradle
runners/spark/spark_runner.gradle
sdks/python/test-suites/portable/common.gradle

Some minor details I forgot and I realized were not ok after double checking with the generated SNAPSHOTs
R: @ibzib

[BEAM-7092] Fix artifact names for Spark separated modules + upgrade to Spark 3.1.1

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

[BEAM-9547] Implement count() on deferred DataFrame, Series

---

sdks/python/apache_beam/dataframe/expressions.py
sdks/python/apache_beam/dataframe/expressions_test.py
sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py
sdks/python/apache_beam/dataframe/pandas_top_level_functions.py
sdks/python/apache_beam/dataframe/partitionings.py
sdks/python/apache_beam/dataframe/partitionings_test.py
sdks/python/apache_beam/dataframe/transforms.py

This modifies the ordering defined by is_subpartitioning_of from:
```
Nothing() < Index([i]) < Index([i, j]) < ... < Index() < Singleton()
```
to:
```
Singleton() < Index([i]) < Index([i, j]) < ... < Index() < Nothing()
```
Which is more logical, since `Singleton()` is equivalent to `Index([])`. The rest of the PR deals with the fallout from this change, which largely entails updating `preserves_partition_by` specs for computed expressions (e0aba2d), and updating the logic for fusing stages (29f41c0). It also includes a patch to have `Index.check` make a strong assertion about partioning, as discussed in BEAM-11324 (29f41c0), and removes the "difficulty" ordering key used in `PartitioningSession`, as this is now equivalent to the standard ordering.
Post-Commit Tests Status (on master …

[BEAM-11881] Fix partitioning ordering for DataFrames

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py
sdks/python/apache_beam/transforms/environments.py

Limits Dataflow GCR container image overriding to external Apache Beam container images
We want to prevent following cases.
* Overriding the container image set by pipeline SDK (which might be overridden for test environments).
* Overriding non-Apache Beam containers set by external transforms.
Lang | SDK | Dataflow | Flink | Samza …

[BEAM-11613] Limits Dataflow GCR container image overriding

---

release/src/main/scripts/build_release_candidate.sh

With 'non-interactive', svn commands fail without prompting for credentials, if credentials are not found in the environment.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https:// …

Removes non-interactive from SVN commands

---

runners/google-cloud-dataflow-java/build.gradle
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java

This cherrypicks both commits from #14208 to fix Dataflow V2 metrics for 2.29.0
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/last …

[BEAM-11967] Cherrypick #14208 to release 2.9.0 branch: Fix Dataflow V2 metrics

---

sdks/java/io/parquet/src/main/java/org/apache/beam/sdk/io/parquet/ParquetIO.java
sdks/java/io/parquet/src/test/java/org/apache/beam/sdk/io/parquet/ParquetIOTest.java

This adds the plumbing needed for setting row-group size in the underlying `ParquetWriter` of `ParquetIO.Sink`.
Go | [![Build …

[BEAM-11969] Adds an option for setting row-group size in ParquetIO

---

sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/pubsub/PubsubTableProviderIT.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/AddTimestampAttribute.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/NestedRowToMessage.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubMessage.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubMessageToRow.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaIOProvider.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/NestedRowToMessageTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubMessageToRowTest.java

Add pubsub handling of byte array payload schemas and ARRAY<ROW<VARCHAR key, VARCHAR value>> attributes schemas.
These enable pure-sql lossless copies to and from Pub/Sub Lite and kafka.
Go | [![Build …

[BEAM-11659] Add new schema types to Pub/Sub SQL

---

sdks/python/apache_beam/dataframe/transforms_test.py

Separated out from #13843.
`pd.testing.assert*` methods provide more detailed error messages, and also handles floating point equality checks. …

[BEAM-11628] Switch to pd.testing.assert* in transforms_test

---

sdks/python/apache_beam/utils/subprocess_server.py

Context at https://stackoverflow.com/questions/66682878/data-flow-flex-runner-fails-on-start/66683401#66683401
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache. …

Better error for missing java.

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Combine.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/View.java
sdks/java/core/src/test/java/org/apache/beam/sdk/testing/PCollectionViewTesting.java

I was not sure about KafkaIO. I believe this is safe for other runners since I already tested making the portable side input expansion the default and it only affects Dataflow.
The idea is that we limit the number of experiments to just one, and we don't really care which one, and then we move off of them.
Lang | SDK | Dataflow | …

Eliminate use_runner_v2, and use_unified_worker in the Java SDK, since beam_fn_api suffices

---

runners/spark/spark_runner.gradle
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/GroupByKeyTest.java

**Test**: testLargeKeys100MB
**Problem**: Out of Memory when running test
**Solution**: Increase max memory in spark_runner.gradle
**Test**: testGroupByKeyWithBadEqualsHashCode
**Problem**: IllegalAccessError on inner classes BadEqualityKey and DeterministicKeyCoder
**Solution**: Add access level modifier "protected" to classes. …

[BEAM-11023] Fix GroupByKeyTest testLargeKeys100MB and testGroupByKeyWithBadEqualsHashCode failing on Spark Structured Streaming runner

---

runners/google-cloud-dataflow-java/build.gradle

This has been failing for a week. …

Sickbay committed metrics, not attempted metrics, for Dataflow streaming V2

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

Add an option to create Dataflow piplines from a snapshot for python sdk

---

sdks/python/apache_beam/runners/portability/spark_runner.py
sdks/python/apache_beam/runners/portability/spark_uber_jar_job_server.py
website/www/site/content/en/get-started/quickstart-go.md

[BEAM-7093] Update some out-of-date Gradle Spark instructions.

---

sdks/java/container/license_scripts/pull_licenses_java.py

Fix a typo in license names

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow_streaming.groovy

The last stable build was 257 minutes of the 270 minute timeout. We should get further away from the likelihood of timeouts. (this is independent of working to reduce the duration)
Go | [![Build …

Increase Dataflow streaming ValidatesRunner timeout

---

runners/google-cloud-dataflow-java/build.gradle

Two independent commits easy to review together:
- sickbay new MapState and SetState (recently added but not healthy for Dataflow streaming)
- exclude committed metrics, which have never been supported
These are both failing https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming
Lang | SDK | Dataflow …

[BEAM-11886] Sickbay unsupported MapState, SetState, committed metrics for Dataflow streaming

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/runners/portability/expansion_service_test.py
sdks/python/apache_beam/transforms/external_test.py

This fixes a bug where some pipelines with external transforms would not correctly be identified as multi-language pipelines.
Dataflow needs to correctly identify multi-language pipelines to enable portable job submission (which is required to execute such pipelines).
--- | …

[BEAM-11862] Updates ExternalTransformFinder to consider external leaf transforms

---

CHANGES.md
sdks/python/apache_beam/dataframe/schemas_test.py
sdks/python/apache_beam/pvalue.py

Previously fields were sorted by name, which lead to a mismatch between the inferred schema and some interactions with the Row object (e.g. iterating), leading to bugs like BEAM-11929. With this change we just rely on the consistent dictionary ordering provided in python 3.6+ to provide a consistent field order. …

[BEAM-11929] Rely on py3.6+ dictionary ordering in beam.Row

---

sdks/python/apache_beam/utils/subprocess_server.py

Move java executable check to avoid --beam_services localhost:port case

---

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

Discovered that these ParDoTest cases were not running because they were annotated only as NeedsRunner.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job …

ParDoTest cases that should be ValidatesRunner

---

runners/flink/flink_runner.gradle
runners/flink/job-server/flink_job_server.gradle
runners/samza/build.gradle
sdks/java/core/src/test/java/org/apache/beam/sdk/testing/TestStreamTest.java

I noticed that these are only marked NeedsRunner, so they will be missed when checking implementations by various runners.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci- …

TestStream tests should be ValidatesRunner

---

sdks/python/apache_beam/dataframe/doctests.py

This modifies the regex used to remove whitespace after the Out[] prompt. The current version will continue trimming whitespace from the next line, this modifies it to stop after one line.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | …

Remove at most one line of whitespace after Out[]: prompt

---

.test-infra/jenkins/job_PostCommit_Java_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Java_DataflowV2.groovy
.test-infra/jenkins/job_PostCommit_Java_Hadoop_Versions.groovy
build.gradle.kts

Noticed in https://scans.gradle.com/s/u7e7etdouunmy/timeline that Dataflow integration tests are linearized and most of the time. This will make a small improvement by running V1 and V2 tests in parallel and separating those from the IO ITs.
--- | --- | --- | --- | --- | --- | …

Break up Java PostCommit a bit

---

CHANGES.md
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineRunner.java
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkRunner.java

As you suggested in the ML (it should be cherry picked I suppose).

[BEAM-11948] Add deprecation warning for Flink 1.8/1.9 support removal

---

sdks/java/io/parquet/src/main/java/org/apache/beam/sdk/io/parquet/ParquetIO.java
sdks/java/io/parquet/src/test/java/org/apache/beam/sdk/io/parquet/ParquetIOTest.java

I added it to all the other transforms. The test is only for the Read to be consistent with `TextIO`, `AvroIO` and the rest.
R: @aromanenko-dev

[BEAM-12057] Add missing populateDisplayData methods to ParquetIO

---

runners/flink/job-server/flink_job_server.gradle

These tests were incorrectly marked `NeedsRunner` instead of `ValidatesRunner`. They probably were never passing. In #14313 I fixed the annotation but did not run enough ValidatesRunner variations to catch the failure in https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/6184/
<table>
<thead>
<tr>
<th>Lang</th> …

[BEAM-12050] Sickbay portable Flink tests of event time timers with TestStream

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

According to [PostgreSQL JDBC documentation](https://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor), it is required to disable autocommit in order to allow cursor streaming.
In `JdbcIO:1548` we have `poolableConnectionFactory.setDefaultAutoCommit(false);`, however it is only applicable to poolable datasource. So any other usage will eventually lead to OOM since the JDBC driver silently falls back to full memoization of the request result.
The commit disables autocommit more systematically.
Superseedes #14338 
cc @jkff @aromanenko-dev 
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th> …

[BEAM-12044] JdbcIO read: always force autocommit to false

---

sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

This PR disallows `sort_index` and `sort_values` in most cases. `sort_index(axis=columns)` is the only configuration that is still allowed, since it simply re-orders the columns by name, which we can do at construction time.
- `sort_index(axis=rows)`, `sort_values(axis=rows)` are disallowed since they impose an ordering. In theory we can successfully perform these operations with `Singleton` partitioning, but this is sub-optimal, and we couldn't guarantee that the ordering wouldn't be lost after a repartition.
- `sort_values(axis=columns)` is disallowed because it re-orders the columns based on the values in the _data_, which we cannot know until execution time. …

[BEAM-9547] Raise WontImplement(order-sensitive) for operations that impose order

---

sdks/python/apache_beam/dataframe/io.py
sdks/python/apache_beam/dataframe/io_test.py

[BEAM-12030] DataFrame read_* raise FileNotFound for non-existent input

---

sdks/python/apache_beam/transforms/sideinputs_test.py

This tests accessing an iterable side input multiple times, in parallel, and at different pages (if small pagination is enabled). 
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](htt …

More extensive side input reiteration and pagination tests.

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/transforms_test.py

This PR adds support for [GroupBy.apply](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#flexible-apply). In general this is a pretty simple operation, just a very customizable unliftable aggregation, but there's one major complication: the frames passed to the apply function include the _original_ index, while our groupby(..) implementation overrides any existing index with just the grouping indexes/columns so we can conveniently use Index() partitioning.
There are a couple possible approaches to get the original index through, but neither is perfect:
1. Move the original indexes into columns, use set_index to move them back after grouping.
2. Don't remove the original indexes in groupby(..), instead just add any grouped columns, and keep all the original indexes. …

[BEAM-11628] Add initial support for GroupBy.apply

---

sdks/python/apache_beam/runners/interactive/utils_test.py

1. Replaced all assert_called_with with assert_any_call in the
ProgressIndicatorTest.
2. assert_called_with only asserts the most recent call. However, there
is an IPythonLogHandler we have customized to emit rich logging in
notebooks that also calls display to render HTML and JavaScript. The
emission of logs can happen any time during the test, causing the
flakiness. Instead of unregistering the log handler during tests that
could make the tests unnecessarily complicated, we could use
assert_any_call within the patched context for simplicity. …

[BEAM-11797] Fix wrong assertion usage

---

sdks/python/apache_beam/dataframe/io.py
sdks/python/apache_beam/dataframe/io_test.py

When given a concrete `FileSink`, `WriteToFiles` will re-use the same sink across windows: https://github.com/apache/beam/blob/e92d184abc79fe84c48de3dfd9dd168d9b38feac/sdks/python/apache_beam/io/fileio.py#L461
https://github.com/apache/beam/blob/e92d184abc79fe84c48de3dfd9dd168d9b38feac/sdks/python/apache_beam/io/fileio.py#L625
This leads to all data (aside from one partition), being written to the file for a single window. The fix is to pass in a function that creates a new sink instead.
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody> …

[BEAM-12071] Don't re-use WriteToPandasSink instances across windows

---

sdks/python/container/base_image_requirements.txt

It seems the previous upgrade in #14379 of httplib2 to version 1.18.1 still have issues. Let's see if this works as expected.
R: @aaltay 
CC @kennknowles

Update httplib2 to version 1.19.1 on Python container

---

sdks/java/io/amazon-web-services/build.gradle
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/options/AwsModule.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/options/AwsModuleTest.java

I've added more details in https://issues.apache.org/jira/browse/BEAM-12081
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompleted …

[BEAM-12081] Fix AwsOptions Jackson (de)serialization of integer values

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

Adds an implementation for `where` and `mask` on `DataFrame` and `Series`.
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)]( …

[BEAM-9547] Initial implementation for where, mask

---

runners/spark/src/main/java/org/apache/beam/runners/spark/SparkPipelineOptions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkPipelineRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/util/SparkCommon.java
runners/spark/src/main/java/org/apache/beam/runners/spark/util/SparkCompat.java
runners/spark/src/test/java/org/apache/beam/runners/spark/metrics/SparkMetricsPusherTest.java

R: @ibzib 
CC: @tszerszen (for awareness)

[BEAM-11213] Display Beam Metrics in Spark History Server for Classic Runner too

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/python/apache_beam/io/external/xlang_kafkaio_it_test.py
sdks/python/test-suites/portable/common.gradle

<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a> …

[BEAM-10663] Re-enable CrossLanguageKafkaIOTest

---

runners/spark/2/src/main/java/org/apache/beam/runners/spark/structuredstreaming/SparkStructuredStreamingRunner.java
runners/spark/2/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/PipelineTranslator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkCommonPipelineOptions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkPipelineOptions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkPipelineRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java

This solves a deployment issue for Spark Structured Streaming runner on YARN and reduces and makes code more consistent among runners.
R: @ibzib

[BEAM-12088] Make file staging uniform among Spark Runners

---

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineOptions.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineWorkerPoolOptions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkCommonPipelineOptions.java
runners/twister2/src/main/java/org/apache/beam/runners/twister2/Twister2PipelineOptions.java
sdks/java/core/src/main/java/org/apache/beam/sdk/options/FileStagingOptions.java
sdks/java/core/src/main/java/org/apache/beam/sdk/options/PortablePipelineOptions.java

[BEAM-4106] Add FileStagingOptions and merge staging file options between runners

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

- `attrs` is an experimental feature
- `argmax`, `argmin` return an offset into the DataFrame, not an index label, so they are sensitive to order
- `ravel` is a utility for producing a numpy `array`, a non-deferred type.
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a>
</td>
<td>---</td>
<td>---</td>
<td>
</a>
</td>
<td>---</td>
<td>
<a …

[BEAM-9547] Raise WontImplementError for a few more operations

---

sdks/python/apache_beam/runners/portability/spark_uber_jar_job_server.py

Missed a spot.
R: @iemejia 
cc: @kennknowles 
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a>
</td> …

[BEAM-12095] Fix Spark job server in uber jar path as well.

---

sdks/go/pkg/beam/core/runtime/pipelinex/replace.go
sdks/go/pkg/beam/core/runtime/pipelinex/replace_test.go
sdks/go/pkg/beam/core/runtime/xlangx/expand.go
sdks/go/pkg/beam/core/runtime/xlangx/namespace.go
sdks/go/pkg/beam/core/runtime/xlangx/namespace_test.go
sdks/go/pkg/beam/options/jobopts/options.go
sdks/go/pkg/beam/options/jobopts/stringSlice.go
sdks/go/pkg/beam/runners/dataflow/dataflow.go
sdks/go/pkg/beam/runners/dataflow/dataflowlib/job.go
sdks/go/test/integration/integration.go
sdks/go/test/run_validatesrunner_tests.sh

Contains a variety of small changes needed to enable cross-language tests to work on Dataflow. Here's a list of changes:
1. Allow running pipelines with portable job submission (required for x-lang transforms).
2. Allow submitting Dataflow jobs with multiple environments.
3. Add SdkHarnessContainerImageOverrides flag to allow specifying overrides for multiple environments. This implementation works by calling the flag multiple times, once for each override.
4. Update the ValidatesRunner script to use the above functionality (portable submission and overrides) as well as uploading a Java SDK container for cross-language in addition to a Go SDK container.
5. Don't namespace environments in external transform expansion. This avoids bugs that occurred because an environment with an empty …

[BEAM-11574] Enable cross-language integration tests on Dataflow

---

sdks/go/container/build.gradle
sdks/java/container/common.gradle
sdks/python/container/common.gradle

`COPY target/LICENSE target/go-licenses/* /opt/apache/beam/third_party_licenses/golang/` doesn't work on macOS when `docker-pull-licenses` is not set.
```
#7 [3/8] ADD target/linux_amd64/boot /opt/apache/beam/
#7 sha256:ba5950ec9b4d3dd4ccf61c67169a80c60727f4a8c4cdcca9487ba724d4521925
#7 DONE 0.1s
#8 [4/8] COPY target/LICENSE /opt/apache/beam/
#8 sha256:c985e805fc702262e6a25884ffdd287334450a61b32213cecd7431453084a710
#8 DONE 0.0s
#9 [5/8] COPY target/NOTICE /opt/apache/beam/
#9 sha256:657942f798562ea47d4f0899783382ae2f7bda6c9a185dc7e0ec8142efb7281b
#9 DONE 0.0s
#10 [6/8] COPY target/LICENSE target/go-licenses/* /opt/apache/beam/third_party_licenses/golang/
#10 sha256:e72eaf77fc75ad38a81071b0cb703717258889925f68ad811f4412d7145f2ea6
#10 ERROR: lstat …
```

[BEAM-12051] fix target/go-licenses: no such file or directory

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/SelectHelpers.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/transforms/SelectTest.java

Fixed `Select.flattenedSchema()` for nested array fields.
Test case:
```
Row[] transactions {
String bank,
Double purchaseAmount
}
->
String[] transactions_bank,
Double[] transactions_purchaseAmount
```
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[BEAM-11585] Select.flattenedSchema doesn't flatten nested array fields

---

runners/spark/job-server/spark_job_server.gradle

see also BEAM-10784
R: @tysonjh
cc: @fernando-wizeline
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a>
</td> …

[BEAM-11483] Ignore windowed GBK tests in Spark portable streaming.

---

sdks/python/apache_beam/utils/subprocess_server_test.py

To prevent future shenanigans.
R: @iemejia 
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a>
</td> …

[BEAM-12095] Add unit tests for path_to_beam_jar(artifact_id).

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Bump classgraph to 4.8.104
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a>
</td>
<td>---</td>
<td>---</td> …

[BEAM-12066] Bump classgraph to 4.8.104

---

sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlJavaUdfTypeTest.java

Exact same values as literal tests introduced in #14418, but reading from a table since some type implementations may differ from literals.
R: @apilloud 
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr> …

[BEAM-10925] Java UDF type tests for input refs.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/bigquery_tools_test.py

io.Bigquery rejects valid tableIds if they contain hyphens.:
However these are allowed by the BigQuery API:
https://cloud.google.com/bigquery/docs/tables#table_naming
If tableId includes hyphens, causes this error
```
ValueError: Expected a table reference (PROJECT:DATASET.TABLE or DATASET.TABLE) instead of project.dataset.table-id
```
modify the offending regex …

Fix: Allow BigQuery tableIds with hyphens

---

sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/bigquery_tools_test.py
sdks/python/scripts/generate_pydoc.sh

A followup to #14113 to improve the schema equality checking.
The check in the previous PR has a high false positive rate for detecting whether a schema update job needs to be run because a schema update job is created even if the field ordering is different.
This PR adds a schema equivalence check with more specificity. Now we can do a field-order insensitive comparison on the schema and only run a schema update job when the fields themselves are different.
Post-Commit …

[BEAM-11277] Add method to check if two TableSchema are equal

---

sdks/python/apache_beam/runners/interactive/testing/integration/notebook_executor.py
sdks/python/apache_beam/runners/interactive/testing/integration/tests/init_square_cube_test.py
sdks/python/setup.py

1. Updated dependency jupyter-client from ">=6.1.11,<7" to ">=6.1.11,<6.1.13"
as the newest version 6.1.13 contains a bug
https://github.com/jupyter/jupyter_client/issues/637 that breaks notebooks
when getting messages.
2. This is caught by screen diff integration tests of interactive beam.
3. Added a timeout=-1 to allow indefinite wait for execution of each
notebook cell in integration tests. The default value was 1 second.
Instead of timeout each cell, moved the timeout to each test using pytest mark. …

[BEAM-11045] Avoid broken deps

---

sdks/python/apache_beam/io/iobase.py
sdks/python/apache_beam/io/iobase_test.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a> …

SDF bounded wrapper returns None when any exception happen in the calculation

---

sdks/python/apache_beam/transforms/periodicsequence.py
sdks/python/apache_beam/transforms/periodicsequence_test.py
sdks/python/apache_beam/utils/timestamp.py

Fixing issue from BEAM-10854 and BEAM-11620, `PeriodicImpulse` would fail with default values.
Some notes:
- Lines [40-44] from `periodicsequence.py` could go directly in `PeriodicImpulse` (after line 162). But this would only fix `PeriodicImpulse` and would fail if other users decide to use `Timestamp` instead of `Float` for the times.
- lines [92-96] of `periodicsequence_test.py`, adding this line would work to check if the default values would work both for `start` and `end`. This would avoid new errors in case the transform is modified. Those lines could be removed if needed …

[BEAM-10854] Fix PeriodicImpulse for default values

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

- `DataFrame.isin` (previously only `Series.isin` was supported)
- Getter (construction-time) and setter for `Series.name`
- Setter for `Index.names`
- Construction-time getter for `Series.dtype`
- `interpolate` is WontImplement(order-sensitive)
<table>
<thead>
<tr>
<th>Lang</th>
<th>SDK</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>
</a>
</td>
<td>---</td>
<td>---</td>
<td>
</a>
</td> …

[BEAM-9547] Implementations for a few more DataFrame operations

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamCalcRel.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamComplexTypeTest.java

This is removing logical type optimizations broken by #11074 and removes the passthrough Beam types as `Object` optimization. After this change, inputs are always converted to Calcite types except for one special case of Row (which will be fixed in the next PR).
--- | --- | …

[BEAM-9379] Simplify BeamCalcRel inputs

---

.test-infra/jenkins/job_PostCommit_Java_PortableValidatesRunner_Spark2_Streaming.groovy
.test-infra/jenkins/job_PostCommit_Java_PortableValidatesRunner_Spark3_Streaming.groovy

The Gradle scripts were put into their own Jenkins job to avoid overloading the CI engine when running the tests.
@ibzib, could you take a look at this? Thanks in advance!
- [x ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
- [ x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue. …

[BEAM-11483] Spark PostCommit Test Improvements - creating one Jenkins job per Gradle task
