sdks/java/extensions/sql/hcatalog/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-5/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-6/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/build.gradle
sdks/java/io/hcatalog/build.gradle

Bump log4j2 version to 2.17.1 for CVE-2021-44832
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13591] Bump log4j2 version to 2.17.1

---

.test-infra/jenkins/job_PostCommit_Java_PortableValidatesRunner_Spark_Batch.groovy
.test-infra/jenkins/job_PreCommit_Java_PortableValidatesRunner_Flink_Docker.groovy
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/direct-java/build.gradle
runners/flink/flink_runner.gradle
runners/flink/job-server/flink_job_server.gradle
runners/google-cloud-dataflow-java/build.gradle
runners/jet/build.gradle
runners/portability/java/build.gradle
runners/samza/build.gradle
runners/samza/job-server/build.gradle
runners/spark/job-server/spark_job_server.gradle
runners/spark/spark_runner.gradle
runners/twister2/build.gradle
sdks/java/container/Dockerfile
sdks/java/container/boot.go
sdks/java/container/build.gradle
sdks/java/container/common.gradle
sdks/java/core/build.gradle
sdks/java/core/src/main/java/org/apache/beam/sdk/testing/UsesSdkHarnessEnvironment.java
sdks/java/core/src/test/java/org/apache/beam/sdk/SdkHarnessEnvironmentTest.java
sdks/java/harness/build.gradle
sdks/java/io/hadoop-format/build.gradle

This allows for accurate object sizing for caching.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13015] Add jamm as a java agent to the Java SDK harness container

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Partially revert https://github.com/apache/beam/commit/eaacf709a861ea1c260e3856b720266348b1aecc
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td> …

[BEAM-13430] Bump the version back to 2.37

---

sdks/python/apache_beam/io/avroio.py
sdks/python/apache_beam/io/avroio_test.py

instead of getting it by reference from the writer. This ensures that when we load the python writer implementation we don't run into an attribute error
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead> …

[BEAM-12391] update avro sink to close the opened file handle directly

---

sdks/python/apache_beam/runners/portability/expansion_service_main.py
sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/transforms/fully_qualified_named_transform.py
sdks/python/apache_beam/transforms/fully_qualified_named_transform_test.py
sdks/python/apache_beam/typehints/schemas.py

This allows one to create/invoke Python transforms without an extensive registration service.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td> …

[BEAM-13482] Python fully qualified name external transforms.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/splittabledofn/GrowableOffsetRangeTrackerTest.java

Partial rollforward of #16257
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[BEAM-11936] Enable FloatingPointAssertionWithinEpsilon errorprone check

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/data/RemoteGrpcPortWriteOperation.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/DefaultJobBundleFactory.java
sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java

Partial rollforward of #16257
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[BEAM-11936] Enable LockNotBeforeTry errorprone check

---

sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/NexmarkLauncher.java
sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/NexmarkQueryName.java
sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/Query14.java

This change adds Query14.java for testing the performance of Reshuffle transform.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13580] Add Nexmark Query14

---

runners/spark/job-server/spark_job_server.gradle
runners/spark/spark_runner.gradle

They are needed to spin up a standalone Spark cluster.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13569] Change Spark dependencies to implementation.

---

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/stream/PrefetchableIterable.java
sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/stream/PrefetchableIterables.java
sdks/java/fn-execution/src/test/java/org/apache/beam/sdk/fn/stream/PrefetchableIterablesTest.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/Caches.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/BagUserState.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/FnApiStateAccessor.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/IterableSideInput.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/LazyCachingIteratorToIterable.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/MultimapSideInput.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/MultimapUserState.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateFetchingIterators.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/BagUserStateTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/IterableSideInputTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/MultimapSideInputTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/MultimapUserStateTest.java

This change also ensures that prefetch can be invoked on the iterable to prevent the prefetch being lost once the iterator is discarded.
See https://s.apache.org/beam-fn-state-api-and-bundle-processing#heading=h.tms0ncgbzz6f
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr> …

[BEAM-13015] Migrate all user state and side input implementations to support caching.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Fix remaining failing perf IT tests.

---

sdks/python/apache_beam/runners/portability/sdk_container_builder.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[release-2.36.0][BEAM-13459] Fix sdk_container_builder too many values to unpack error

---

CHANGES.md

This adds a CHANGES.md entry for #16229 
R: @tvalentyn 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13459] Update CHANGES.md, add note about artifact caching python jobs

---

sdks/java/core/src/main/java/org/apache/beam/sdk/options/SdkHarnessOptions.java
sdks/java/core/src/test/java/org/apache/beam/sdk/options/SdkHarnessOptionsTest.java

The boot.go always sets the `-Xmx` value but we need a fallback incase used in different environments.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBu …

[BEAM-13015] Use 20% of memory when the maximum has been configured.

---

sdks/go/pkg/beam/runners/flag.go
sdks/go/pkg/beam/testing/ptest/ptest.go
sdks/go/pkg/beam/x/beamx/run.go

We need a consolidated flag definition in order to avoid flag redefinition errors between beamx and the integration package. Neither should be defining their own flags without excellent reason.
This will let us add the examples to our integration suite.
Maintains existing behaviors and exported surfaces.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th> …

[BEAM-13567] Consolidate runner flag definition.

---

sdks/python/apache_beam/typehints/schemas.py

This fixes apache_beam.tools.microbenchmarks_test.MicrobenchmarksTest.test_coders_microbenchmark.
Also separate out the named tuple and row cases as they have
little in common at this point.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td> …

[BEAM-13601] Don't cache Row types for a schema.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/options/AwsOptions.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java

This fixes a bad merge of conflicts that occurred on https://github.com/apache/beam/pull/16395
This was originally re-enabled in https://github.com/apache/beam/pull/16389
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13430] Re-enable checkerframework

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

[BEAM-13576] update bom

---

sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

1. Errors caused by metrics gathering no longer fail the GCS I/O.
2. Added a debug level log about potential permission issue and missing project id label for reported metrics.
3. Added a test for the failing execution route.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr> …

[BEAM-12879] Prevented missing permission from failing GCS I/O

---

sdks/python/apache_beam/io/gcp/experimental/spannerio.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-10345] Add an import guard to support recent google-cloud-spanner versions.

---

sdks/python/apache_beam/runners/interactive/cache_manager.py
sdks/python/apache_beam/runners/interactive/cache_manager_test.py
sdks/python/apache_beam/runners/interactive/caching/streaming_cache.py
sdks/python/apache_beam/runners/interactive/caching/streaming_cache_test.py
sdks/python/apache_beam/runners/interactive/interactive_runner.py
sdks/python/apache_beam/runners/interactive/pipeline_fragment_test.py

1. Fixed a test watching nested dictionaries by watching the
concerned PCollections directly;
2. Fixed cache manager's "exists" implementations to avoid treating
empty labels as wildcard when matching cache files. This bug
is not a security issue but could cause unexpected behavior when
getting materialized values of PCollections that are not cached.
<table> …

Fixed empty labels treated as wildcard when matching cache files

---

runners/spark/spark_runner.gradle

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13570] Remove erroneous compileClasspath dependency.

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-13015] Cache the state backed iterable used for large GBK results.

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/LogicalTypes.java

Argument values are calculated in any case, so when the base value is null, NPE occures.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a> …

[BEAM-13604] NPE while getting null from BigDecimal column

---

sdks/python/apache_beam/coders/row_coder_test.py

The current encoding position tests rely on creating user types first then generating and modifying schema protos. We can make the test more straightforward by writing the schema protos directly.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td> …

[BEAM-10277] re-write encoding position tests to declare schema protos explicitly

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/join/CoGbkResult.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/join/CoGbkResultTest.java

Cherrypick of #16354 and #16407 (replacing https://github.com/apache/beam/pull/16402)
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[release-2.36.0][BEAM-13541] More intelligent caching of CoGBK values. (#16354, #16407)

---

.github/workflows/local_env_tests.yml

local_env_tests.yml has been failing since https://github.com/apache/beam/pull/16291
Seems to be due to a minor typo.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastComplete …

Minor: Fix local_env_tests.yml syntax error

---

sdks/go/pkg/beam/io/filesystem/filesystem.go
sdks/go/pkg/beam/io/filesystem/filesystem_test.go
sdks/go/pkg/beam/io/filesystem/gcs/gcs.go
sdks/go/pkg/beam/io/filesystem/gcs/gcs_test.go
sdks/go/pkg/beam/io/filesystem/local/local.go
sdks/go/pkg/beam/io/filesystem/local/local_test.go
sdks/go/pkg/beam/io/filesystem/memfs/memory.go
sdks/go/pkg/beam/io/filesystem/memfs/memory_test.go
sdks/go/pkg/beam/io/filesystem/util.go
sdks/go/pkg/beam/io/filesystem/util_test.go
sdks/go/pkg/beam/runners/flag.go

Build up the filesystem abstraction with Copy, Remove, and Rename support.
Implement these interfaces for the GCS, Local, and InMemory implementations as appropriate.
Unit test the utility functions that build from the abstraction, and backfill testing.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th> …

[BEAM-13574] Filesystem abstraction Rename support

---

.github/workflows/java_tests.yml
.github/workflows/local_env_tests.yml
.github/workflows/python_tests.yml

With the removal of the GoGradlePlugin, we use our own shell scripts to deal with Go builds (such as for container boot scripts), but this mandates a minimum version of Go 1.16.
This updates our Github action workflows to specify that version.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[BEAM-13597] Setup Go in github actions

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13091] Generate missing staged names from hash for Dataflow runner

---

website/www/site/data/io_matrix.yaml

[adhoc] Fix BigTableIO description
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[adhoc] Fix BigTableIO description

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateFetchingIterators.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateFetchingIteratorsTest.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-13015] Remove dead code now that all instances have migrated to the state caching implementation.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Bump software.amazon.awssdk to 2.17.106
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-8727] Bump software.amazon.awssdk to 2.17.106

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/kinesis/src/test/java/org/apache/beam/sdk/io/kinesis/AmazonKinesisMock.java

Bump com.amazonaws to 1.12.135
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-4868] Bump com.amazonaws to 1.12.135

---

CHANGES.md
sdks/java/io/redis/build.gradle
sdks/java/io/redis/src/main/java/org/apache/beam/sdk/io/redis/RedisIO.java
sdks/java/io/redis/src/test/java/org/apache/beam/sdk/io/redis/RedisIOTest.java

Bump jedis to version 4.0.0
https://github.com/redis/jedis/blob/v4.0.0/docs/3to4.md
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-12092] Bump jedis to version 4.0.1

---

sdks/python/apache_beam/io/gcp/datastore/v1new/rampup_throttling_fn.py
sdks/python/apache_beam/io/gcp/datastore/v1new/rampup_throttling_fn_test.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[release-2.36.0/BEAM-13599] Fix overflow error in Python Datastore RampupThrottlingFn

---

playground/infrastructure/helper.py

[BEAM-13536]
Add processing of empty value in Beam tag validation method
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13536][Playground][Bugfix] CI step doesn't log case with empty category value

---

examples/java/src/main/java/org/apache/beam/examples/cookbook/DistinctExample.java

```
gradle examples:java:spotlessApply
```
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[adhoc] Run spotlessApply on java examples to fix master

---

sdks/python/apache_beam/internal/metrics/metric.py
sdks/python/apache_beam/io/gcp/bigtableio.py

1. bigtable mutate row might return None instead of Status when running
into retryable errors. Handled the special case as DEADLINE_EXCEEDED
because bigtable must have exhausted the retry timeout or when there
is no retry policy inplace.
2. For all rows mutated, if the response status is not ok, that data
might have lost. Added a TODO item for that.
<table> …

[BEAM-13602] Prevented metrics gathering from failing bigtable io

---

sdks/python/apache_beam/transforms/fully_qualified_named_transform.py
sdks/python/apache_beam/transforms/fully_qualified_named_transform_test.py

This make it easier to call cross language transforms.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Optional args and kwargs for named external transforms.

---

runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkJobServerDriverTest.java
runners/java-job-service/src/main/java/org/apache/beam/runners/jobsubmission/JobServerDriver.java
sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java

1. Update JobServerDriver to skip creating expansion server when expansion port is negative.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13432] Skip ExpansionService creation in Job Server

---

CHANGES.md
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsMessage.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsUnboundedReader.java

Currently, with fields being package private, `SqsMessage` and with that `SqsIO.read` for AWS Sdk v2 is barely usable.
- Visibility of all fields was fixed from `package private` to `public`.
- [BREAKING] Datatype of timestamp fields was changed from `String` to `long`, which is obviously a breaking change but seems reasonable as this IO is most likely not used for obvious reasons. …

[BEAM-13638] Fix visibility of fields in SqsMessage (AWS Sdk v2)

---

sdks/python/apache_beam/examples/wordcount.py

Fixed a typo in python example.
(This is partly a test to start contributing to this project.)
R: robertwb

[BEAM-13589] python sdk examples: Fixed typo in wordcount example.

---

sdks/python/apache_beam/transforms/ptransform.py
sdks/python/apache_beam/transforms/resources.py
sdks/python/apache_beam/transforms/resources_test.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-13656] [BEAM-12558] Provide an API to check whether a hint is known.

---

playground/backend/internal/code_processing/code_processing.go
playground/backend/internal/code_processing/code_processing_test.go
playground/backend/internal/executors/executor_builder.go
playground/backend/internal/executors/executor_test.go
playground/backend/internal/fs_tool/fs.go
playground/backend/internal/fs_tool/fs_test.go
playground/backend/internal/fs_tool/java_fs.go
playground/backend/internal/fs_tool/java_fs_test.go
playground/backend/internal/setup_tools/builder/setup_builder.go
playground/backend/internal/setup_tools/builder/setup_builder_test.go

[BEAM-13560][Playground]  Split builder into several builders for each step of pipeline execution
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/" …

[BEAM-13560][Playground] Split builder into several builders for each step of the pipeline execution

---

sdks/python/apache_beam/metrics/metric_test.py

We really should enforce this via a precommit.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Remove tab from source.

---

sdks/go/pkg/beam/core/util/protox/any_test.go

Removes implicit copies of BytesValue objects in test cases, which threw errors when go vet was run. Part of an effort to make the Go SDK code base go vet-compliant. 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-10206] Resolve go vet errors in protox package

---

vendor/README.md
vendor/calcite-1_28_0/build.gradle

Missed during initial PR https://github.com/apache/beam/pull/16473
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Edit comments and docs for vendoring

---

.test-infra/tools/README.md
.test-infra/tools/python_installer.sh

* [BEAM-12621] Added python installer tool and its documentation. 
* The `pyton_installer.sh` script was used to install the pyenv environments for python `3.6`, `3.7`, `3.8` and `3.9` versions in the latest Jenkins worker image (`jenkins-worker-boot-image-20220107`). 
* We can use the `python_installer.sh` tool to create pyenv environments in any Ubuntu distributions.
R: @tvalentyn  …

[BEAM-12621] - Update Jenkins VMs to modern Ubuntu version

---

sdks/go/pkg/beam/coder_test.go
sdks/go/pkg/beam/core/runtime/harness/harness.go
sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download.go
sdks/go/pkg/beam/core/runtime/xlangx/expansionx/process.go
sdks/go/pkg/beam/external_test.go
sdks/go/pkg/beam/pardo_test.go
sdks/go/pkg/beam/partition.go
sdks/go/pkg/beam/runners/universal/universal.go
sdks/go/pkg/beam/runners/vet/vet.go
sdks/go/pkg/beam/runners/vet/vet_test.go
sdks/go/pkg/beam/transforms/top/top.go

Addresses some of the staticcheck warnings in Go SDK files in preparation for adding staticcheck to GitHub actions. Currently avoiding package/function deprecation warnings and focusing on smaller code cleanliness issues.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr> …

[BEAM-10206] Clean up some simple staticcheck warnings in Go SDK

---

sdks/go/pkg/beam/core/runtime/exec/hash.go
sdks/go/pkg/beam/core/runtime/exec/hash_test.go

Update Primitives hashing benchmark to successfully execute. Previous benchmark as written led to nil pointer exceptions stemming from a lack of window encoders being put into the hash types.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td> …

[BEAM-13664] Fix Primitives hashing benchmark

---

sdks/java/io/elasticsearch-tests/elasticsearch-tests-5/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-6/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTestCommon.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTestUtils.java

Address Elasticsearch Unit Test Flakiness
Fixes BEAM-13137 and possibly BEAM-5172.  Elasticsearch read/split/size has often been flaky in unit tests, and it may be due to the non-deterministic nature of `_flush` whereby data buffered in the translog of ES is flushed to the index; this process happens independently of index `refresh`.  Adding explicit use of flush has stabilized tests locally. Next step is to see if this translates to stability in automated unit tests. …

[BEAM-13137] Fixes ES utest size flakiness with _flush api and index.store.stats_refresh_interval=0

---

sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/ITEnvironment.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/SqsIOIT.java

Integration test for SqsIO using Localstack (or AWS SQS)
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-8806] Integration test for SqsIO using Localstack (AWS Sdk v2)

---

buildSrc/build.gradle.kts
buildSrc/src/main/groovy/org/apache/beam/gradle/Repositories.groovy

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-13430] Remove jcenter repositories from gradle configuration.

---

playground/infrastructure/config.py

[BEAM-13641]
Add SCIO SDK support on the CI/CD step
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13641][Playground] Add SCIO SDK support on the CI/CD step

---

.test-infra/validate-runner/build.gradle
buildSrc/src/main/groovy/org/apache/beam/gradle/Repositories.groovy
sdks/java/io/azure/build.gradle

See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
There are already issues with spurious timeouts/failures.
This removes the remaining references left after https://github.com/apache/beam/pull/16532
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[BEAM-13430] Remove jcenter which will no longer contain any updates.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

R: @suztomo @reuvenlax 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13616] Update com.google.cloud:libraries-bom to 24.2.0

---

sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sqs/SqsIO.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sqs/SqsMessageCoder.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sqs/SqsUnboundedReader.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sqs/SqsUnboundedSource.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/sqs/SqsMessageCoderTest.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/sqs/SqsUnboundedReaderTest.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/sqs/SqsUnboundedSourceTest.java

Add deterministic SQS message coder to fix reading from SQS in batch mode.
See https://stackoverflow.com/questions/70648489/apache-beam-2-34-0-sqsio-illegal-mutation-exception for further details on the issue.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody> …

[BEAM-13631] Add deterministic SQS message coder to fix reading from SQS in batch mode (AWS Sdk v1)

---

sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/ITEnvironment.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/sqs/SqsIOIT.java

Integration test for SqsIO using Localstack on AWS SDK v1.
Note: This depends on https://github.com/apache/beam/pull/16480 and will fail until rebased ...
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-8806] Integration test for SqsIO using Localstack (AWS Sdk v1)

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

This new container now contains PubSub Lite.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Bump beam container version.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13616][BEAM-13646] Upgrade vendored calcite to 1.28.0:0.2

---

playground/frontend/lib/modules/editor/repository/code_repository/code_repository.dart

Fixed tests on frontend
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13680] [Playground] [Bugfix] Fix tests on frontend

---

sdks/go/pkg/beam/core/runtime/xlangx/expand.go
sdks/go/pkg/beam/transforms/sql/sql.go
sdks/go/pkg/beam/transforms/sql/sqlx/sqlx.go

Converts the `sqlx` package's `ExpansionPayload` to have its `Options` field unexported, as it is incompatible with the SQL transform schema as implemented in Java. Also propagates a corrected expansion address back into the graph representation of the expansion transform in the event of an overridden handler (either a `hardoverride` tag as a result of an xlangx.Require() call or a per-URN override.) …

[BEAM-13683] Correct SQL transform schema, fix expansion address override bug

---

sdks/go/examples/xlang/sql/sql.go

Create a cross-language Beam pipeline that runs SQL transforms in the Go SDK. Serves as both an example for users on how to use the sql package as well as a proven case of the SQL cross-language transforms functioning end-to-end. This is an example rather than an integration test as the SQL transforms need a fully stood-up expansion service to run, not just the test expansion service used in xlang integration tests. …

[BEAM-13683] Make cross-language SQL example pipeline

---

website/www/site/content/en/documentation/programming-guide.md

Fixes the typo described in [BEAM-13688](https://issues.apache.org/jira/browse/BEAM-13688).
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td> …

[BEAM-13688] fixes typo in BPG 4.5.3 window section for Go

---

runners/google-cloud-dataflow-java/build.gradle

Docker image was updated in #16412
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Update Java FnAPI beam master

---

.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow_Streaming.groovy

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[BEAM-13693] Bump beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming timeout to 12 hours

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/Select.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslArrayTest.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamCoGBKJoinRelBoundedVsBoundedTest.java

We use BeamSQL in our project. When we use any JOIN. SQL generates BeamCoGBKJoinRel plan which uses Select from core sdk. While Select infer output schema it loses nullability of complex types such as Array, Map. 
I added Test cases to catch error and also fix on Select's uniquifyNames function.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th> …

[BEAM-13577] Beam Select's uniquifyNames function loses nullability of Complex types while inferring schema

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiLoads.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StreamingWriteTables.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteRename.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteResult.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java

Similar to other IOs (Bigtable, FileIO, etc), it would be useful for BigQueryIO to emit an element (the TableDestination that was just loaded) when the load completes.
We've been running this in production in our own fork for awhile, if this looks good I'll add some tests in for it as well.
R: @pabloem @chamikaramj
<table>
<thead>
<tr>
<th>Lang</th> …

[BEAM-13689] Output TableDestination elements when BQ batch writes complete.

---

sdks/go/pkg/beam/core/runtime/exec/pardo_test.go
sdks/go/pkg/beam/core/runtime/exec/sdf_test.go

Replace goroutines calling Fatalf in tests/benchmarks to address `go vet` warnings. 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-10206] Remove Fatalf calls in non-test goroutines for tests/benchmarks

---

examples/multi-language/README.md
examples/multi-language/python/addprefix.py
examples/multi-language/python/javacount.py
examples/multi-language/python/javadatagenerator.py

Edited the README and the comments in the Python multi-language pipeline examples.
@chamikaramj 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td> …

edited README and comments in Python multi-lang pipes examples

---

.github/workflows/build_playground_backend.yml
.github/workflows/build_playground_frontend.yml

Set of updates for Github actions that used to build Playground applications, that fixes syntax and also some improvements related to generating docker tags and usage of proper secrets values
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td> …

[BEAM-13677][Playground]Update GitHub Actions to Build Playground Containers In Proper Way

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/BatchSpannerRead.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java

Moved the creation of metrics counter to startbundle.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13687] Improved Spanner IO request count metrics

---

sdks/python/setup.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-10897] Update the fastavro lower bound due to an issue on Windows

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/pandas_doctests_test.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[BEAM-13605] Update pandas_doctests_test denylists in preparation for pandas 1.4.0

---

playground/infrastructure/proxy/allow_list.py

[[BEAM-13711]](https://issues.apache.org/jira/browse/BEAM-13711)
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13711] [Playground] [Bugfix] Add Cloud Logging API in allow list

---

sdks/python/setup.py

The dependency can be transitively installed through needle, no need to
fix it in setup.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a> …

[BEAM-13275] Removed the explicit selenium dependency from setup

---

runners/google-cloud-dataflow-java/build.gradle

Dataflow job in beam_PostRelease_NightlySnapshot is failing to start up workers with the ClassNotFound error:
```
Info 2022-01-24 06:26:33.294 PST "Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/beam/vendor/grpc/v1p36p0/com/google/protobuf/Message$Builder"
Info 2022-01-24 06:26:33.294 PST " at org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness.main(DataflowBatchWorkerHarness.java:60)"
Info 2022-01-24 06:26:33.294 PST "Caused by: java.lang.ClassNotFoundException: org.apache.beam.vendor.grpc.v1p36p0.com.google.protobuf.Message$Builder"
Info 2022-01-24 06:26:33.294 PST " at java.net.URLClassLoader.findClass(URLClassLoader.java:381)"
Info 2022-01-24 06:26:33.294 PST " at java.lang.ClassLoader.loadClass(ClassLoader.java:424)"
Info 2022-01-24 06:26:33.294 …
```

Bump Dataflow container versions

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13716] Clear before creating a new virtual environment in setupVirtualenv

---

website/CONTRIBUTE.md
website/www/site/content/en/documentation/programming-guide.md

@chamikaramj 
Fixed up the "Multi-language pipelines" section of the programming guide:
* Made the language friendlier (i.e. less formal) and less verbose.
* Fixed stylistic issues (typos, awkward phrasing, etc.).
* Shortened the headings.
* Cleaned up comments in example code.
* Added syntax highlighting to all code samples.
* Added links to examples. …

Improved multi-language pipelines section of the programming guide

---

sdks/java/io/amazon-web-services2/build.gradle
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsCheckpointMark.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsUnboundedReader.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/EmbeddedSqsServer.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/SqsIOTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/SqsUnboundedReaderTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/SqsUnboundedSourceTest.java

Don't retry extending or deleting SQS messages on invalid SQS receipt handles that have expired already.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompleted …

[BEAM-13510] Don't retry on invalid SQS receipt handles (AWS Sdk v2)

---

sdks/go/pkg/beam/core/runtime/exec/combine.go
sdks/go/pkg/beam/core/runtime/exec/combine_test.go

Change lifting cache to compare encoded keys and windows, and overflow down a linked list on collisions.
Abstracts out the cache portions to make them testable.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13736] Make lifting cache exact.

---

sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/dynamodb/AwsClientsProvider.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/dynamodb/BasicDynamoDBProvider.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sns/AwsClientsProvider.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sns/BasicSnsProvider.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/ITEnvironment.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/dynamodb/StaticAwsClientsProvider.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/s3/S3FileSystemIT.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/sns/SnsIOIT.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/sns/SnsIOTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/ITEnvironment.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sns/SnsIOIT.java

Add integration test for SnsIO.write (Sdk v1 & v2)
Also fixes a bug in `BasicSnsProvider` (Sdk v1) which didn't set the service endpoint.
For clarity, obsolete implementations to create CloudWatch clients are deprecated where not needed.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[BEAM-8807] Add integration test for SnsIO.write (Sdk v1 & v2)

---

sdks/go/pkg/beam/runners/dataflow/dataflow.go
sdks/go/pkg/beam/runners/dataflow/dataflowlib/job.go

Adds a user-facing option to pass a disk type argument for a dataflow pipeline. Requires no validation of input as Dataflow will try to pick a reasonable option for the user on both empty and unrecognized inputs, preventing a pipeline failure if an unknown disk type parameter is provided.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th> …

[BEAM-7928] Allow users to specify worker disk type for Dataflow runner

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsModule.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/SSECustomerKey.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/AwsModuleTest.java

Fix deserialization of SSECustomerKey to allow all fields to be nullable and add missing tests for serialization / deserialization.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13746] Fix deserialization of SSECustomerKey for AWS Sdk v2

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Cherry-picks https://github.com/apache/beam/pull/16599 to Beam 2.36.0 release
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-11648] Fix exception with BigQuery StreamWriter TraceID.

---

playground/backend/CONTRIBUTE.md

[BEAM-13671]
Add `CONTRIBUTE.md` file
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13671][Playground] Add backend contribute guide to the project

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/portability/stager.py
sdks/python/apache_beam/runners/portability/stager_test.py
sdks/python/apache_beam/runners/worker/sdk_worker_main.py

Sets pickle library to cloud pickle before staging main session. Avoids loading main session when pickle library is cloudpickle
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13595] Don't load main session when cloudpickle is used.

---

examples/java/src/main/java/org/apache/beam/examples/complete/kafkatopubsub/kafka/consumer/Utils.java
examples/java/src/main/java/org/apache/beam/examples/complete/kafkatopubsub/options/KafkaToPubsubOptions.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[BEAM-13537] Fix NPE in kafkatopubsub example

---

sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/AwsOptionsTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/S3OptionsTest.java

Add basic tests for S3Options and AwsOptions.
@aromanenko-dev Btw, the reason the issue in https://github.com/apache/beam/pull/16607 didn't surface earlier is that factories in PipelineOptions are lazy. The new behavior now always triggers the factories as values get copied into the new configuration object...
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th> …

[adhoc] Test S3Options and AwsOptions for Sdk v2

---

.github/workflows/java_tests.yml

setup-go is misconfigured and blocking the build
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComp …

[BEAM-13740] update java_tests.yml to temporarily remove setup-go

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchedStreamingWrite.java

As reported in https://issues.apache.org/jira/browse/BEAM-13714 BigQuery connector logs every batch in streaming mode. 
For real-world pipeline it causes Cloud Logging throttling. 
As long as BigQuery insertAll API metrics (request count and percentiles for request sizes) are available in StackDriver, logging seems to be redundant, so I decided to remove logging at all.
@nehsyc - I would like to ask you for the review as an author of relevant changes in BigQuery connector.
https://github.com/apache/beam/commit/c1e5b3547b0dc23b4ae4804b410be2d018781470 …

[BEAM-13714] Get rid of unnecessary logs for BigQuery streaming writes

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/graph/PCollectionOutputTagVisitor.java
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/graph/ProjectionProducerVisitor.java
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/graph/ProjectionPushdownOptimizer.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/graph/ProjectionPushdownOptimizerTest.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-12976] Implement Java projection pushdown optimizer.

---

runners/google-cloud-dataflow-java/build.gradle

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Fix google3 import error due to missing Python gradle build file

---

website/www/site/content/en/documentation/sdks/python-multi-language-pipelines.md

@chamikaramj 
Added references to the example implementation to the Python multilang quickstart, and moved the instructions on running the expansion service to the correct place.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

added GitHub example references to Python multilang quickstart

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Includes minor bumps to dependencies
R: @tvalentyn 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Update Python SDK beam-master tags

---

CHANGES.md
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/DefaultS3FileSystemSchemeRegistrar.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystem.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystemConfiguration.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystemSchemeRegistrar.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3ReadableSeekableByteChannel.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3ResourceId.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3WritableByteChannel.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystemTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3ResourceIdTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3TestUtils.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3WritableByteChannelTest.java

This change allows users of the v2 Amazon S3 SDK to access other filesystems that speak the S3 API using the FileIO transforms. It introduces the S3FileSystemSchemeRegistrar and S3FilesystemConfiguration to enable users to register URI schemes for this purpose.
This ports https://github.com/apache/beam/pull/15036 to aws2. See BEAM-12435, BEAM-13245.
<table> …

[BEAM-13245] Generalize S3FileSystem to support multiple URI schemes.

---

sdks/python/apache_beam/runners/portability/stager_test.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13769] Skip test_main_session_not_staged_when_using_cloudpickle

---

playground/backend/internal/setup_tools/builder/setup_builder.go

[[BEAM-13773]](https://issues.apache.org/jira/browse/BEAM-13773)
Fix java unit-tests
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-13773] [Playground] [Bugfix] Error during executing of tests on Java SDK

---

playground/backend/internal/setup_tools/builder/setup_builder.go

[BEAM-13772][Playground][Bugfix] Fix bug with wrong name for go test command
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13772][Playground][Bugfix] Change executable name for go tests

---

sdks/go/pkg/beam/options/gcpopts/options.go
sdks/go/pkg/beam/options/gcpopts/options_test.go
sdks/go/pkg/beam/runners/dataflow/dataflow.go

The dataflow.go runner currently requires a project to be set via a flag. However, this can be inferred from the users config if they have set the `GOOGLE_APPLICATION_CREDENTIALS` env var to point to a service account ([details here](https://cloud.google.com/docs/authentication/production#auth-cloud-explicit-go)). This updates the runner to respect that setting if a project is not explicitly supplied. …

[BEAM-6744] Support implicitly setting project id in Go Dataflow runner

---

sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
sdks/java/maven-archetypes/gcp-bom-examples/src/main/resources/archetype-resources/pom.xml

Due to https://github.com/apache/beam/pull/16396 recently changing spark core libraries to compile (instead of provided), I believe we need to put this `excludes` now for the quickstarts to pass.  
R: @ibzib 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody> …

Exclude jul-to-slf4j from Spark runner in quickstart POM templates

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/cassandra/build.gradle
sdks/java/io/cassandra/src/test/java/org/apache/beam/sdk/io/cassandra/CassandraIOTest.java
sdks/java/io/hadoop-file-system/build.gradle
sdks/java/io/hadoop-format/build.gradle

We were pinning an older guava for _all_ configurations on a couple of projects that require it, unfortunately this breaks error-prone in some cases. This PR removes the pinned guava for `annotationProcessor` and `testAnnotationProcessor` configurations, so that error-prone checks can run.
Split from #16637
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td> …

[BEAM-11936] Enable a few errorprone checks that were broken by pinned guava in annotationProcessor

---

runners/twister2/build.gradle

r: @emilymye 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/last …

[BEAM-13749] Exclude per-key order tests on Twister2 runner

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConfluentSchemaRegistryDeserializerProvider.java

Change cache capacity to be specified as input parameter instead of default max integer. The usage can be quite different case by case and a default Integer max value can lead to error like this depending on the setup:
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`
Some documentation link on the parameter: https://docs.confluent.io/5.4.2/clients/confluent-kafka-dotnet/api/Confluent.SchemaRegistry.CachedSchemaRegistryClient.html#Confluent_SchemaRegistry_CachedSchemaRegistryClient_DefaultMaxCachedSchemas
R: @lukecwik …

[BEAM-13777] Accept cache capacity as input parameter instead of default max integer

---

.github/workflows/label_prs.yml

https://github.com/apache/beam/pull/16665 doesn't quite work because the labeler action requires token permissions that can't be given to forks for security permissions. Since prs execute the code that is in the fork, that is a security issue. Fortunately, GitHub introduced a trigger to work around this which will use the main repo's code, not the forks. …

[BEAM-13779] Fix labeler trigger

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/RetryManager.java

RetryManager's have short lifetime (for example processElement). This
means that many different threads are created instead of effectively
reusing them. This is adds expense but also can result in many threads
because the each individual thread lasts for up to 60 seconds and
until the GC runs.
<table> …

[BEAM-11648] Share thread pool across RetryManager instances.

---

sdks/java/testing/load-tests/build.gradle
sdks/java/testing/nexmark/build.gradle

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Fix Java SDK container image name for load-tests and nexmark

---

sdks/java/io/google-cloud-platform/build.gradle

Cherrypick of PR #16672
R: @suztomo @lukecwik 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[release-2.36.0][BEAM-13781] Exclude grpc-netty-shaded from gax-grpc's dependency

---

.github/workflows/java_tests.yml
.github/workflows/python_tests.yml

This correctly runs setup-go before some of our java and python tests. The previous iteration had 2 issues that caused it to not work:
1) The matrix strategy was incorrectly specified as:
`runs-on: [ubuntu-latest, macos-latest, windows-latest]`
instead of
```
runs-on: ${{ matrix.os }}
strategy:
fail-fast: false
matrix:
os: [ubuntu-latest, macos-latest, windows-latest]
```
(in fairness, I found at least 1 place where the docs on this were wrong)
2) Putting the setup-go step in its own job won't actually impact anything because new runners are spun up for each job if we're using the hosted service
This corrects both of those things and adds setup-go back in …

[BEAM-13740] Correctly install go before running tests

---

dev-support/docker/Dockerfile

Fix the local docker dev environment to have a more recent Go version.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-12830] Update local Docker env Go version.

---

sdks/python/.pylintrc
sdks/python/apache_beam/utils/timestamp.py
sdks/python/apache_beam/utils/timestamp_test.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
</a> …

[BEAM-13051][B] Enable pylint warnings (import-error/invalid-unary-operand-type)

---

runners/spark/spark_runner.gradle

During several Gradle 7 migrations these were changed to implementation. The eventual goal is to move away from provided, but for now we want to keep POMs as is. 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13430] Revert Spark libraries in Spark runner to provided

---

runners/spark/spark_runner.gradle

Cherrypick of #16675
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Fli …

[release-2.36.0][BEAM-13430] Revert Spark libraries in spark runner to provided

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

Currently, the dataflow runner creates collisions if two jobs are created at the same microsecond. 
This change adds eight random alphanumeric characters to the end of the job name, which increases the number of simultaneously started jobs required for collision odds to be over 50% from 2 (as they would definitely collide now) to 2 million. 
This change also updates the unit test to account for the new name format. 
`ValidatesRunner` compliance status …

[BEAM-13760] Add random component to default python dataflow job name

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOTestUtil.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOWriteIT.java
sdks/java/io/google-cloud-platform/src/test/resources/BUNDLE_PARSE_TEST/batch-success-failure.json
sdks/java/io/google-cloud-platform/src/test/resources/BUNDLE_PARSE_TEST/transaction-failure.json
sdks/java/io/google-cloud-platform/src/test/resources/BUNDLE_PARSE_TEST/transaction-success.json

BATCH bundles return a 200 status code even if entries fail, which results in us only incrementing the success counter and not the failure counters, even if all entries are failed to be written to the FHIR store. (Meanwhile, transaction bundles - which is all FhirIO has been tested with, return a non-20X HTTP response if *any* of the entries don't succeed).
Therefore, need to add parsing and metrics around this to be able to support bundles of type BATCH. …

[BEAM-13731] FhirIO: Add support for BATCH bundle errors.

---

website/www/site/content/en/documentation/programming-guide.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13011] Adds a link to Multi-language Pipelines Tips wiki page

---

sdks/python/apache_beam/runners/interactive/background_caching_job.py
sdks/python/apache_beam/runners/interactive/cache_manager.py
sdks/python/apache_beam/runners/interactive/cache_manager_test.py
sdks/python/apache_beam/runners/interactive/caching/streaming_cache_test.py
sdks/python/apache_beam/runners/interactive/interactive_beam.py
sdks/python/apache_beam/runners/interactive/interactive_environment.py
sdks/python/apache_beam/runners/interactive/interactive_environment_test.py
sdks/python/apache_beam/runners/interactive/utils.py
sdks/python/apache_beam/runners/interactive/utils_test.py

- Builds off of the work accomplished under [[BEAM-13685]](https://issues.apache.org/jira/browse/BEAM-13685)
- Modified interactive_environment.py to support caching to a bucket on GCS for batch processing pipelines
- If a specified bucket does not exist, the pipeline will terminate and return an error specifying that the bucket does not exist
- Added cleanup() functionality to cache_manager.py, to enable the FileBasedCacheManager class to automatically delete cached values on GCS when a bucket path is specified
- Added docstring to interactive_beam.py with an example of GCS path assignment
- Cached files on GCS will be stored under a directory represented by the value of id(pipeline).
- Example cached path: gs://my-gcs-bucket/cache/dir/id(pipeline)
Thank you for …

[BEAM-13734] Support cache directories that use GCS buckets

---

sdks/go/examples/large_wordcount/large_wordcount.go
sdks/go/examples/large_wordcount/large_wordcount_test.go
sdks/go/test/integration/integration.go

Adds a more complex example pipeline demonstrating a more production oriented wordcount. 
* Uses the SDF based textio read
* Sorts the output as long as keys fit in a single machine's memory
* Shards the output based on the output spec (or based on shard configuration.)
* Uses the Filesystem abstraction for "atomic" renames.
* Uses Map Side inputs.
* Tests the pipeline with passert & metrics querying. …

[BEAM-13574] Large Wordcount

---

sdks/go/pkg/beam/io/xlang/jdbcio/jdbc.go
sdks/go/test/integration/integration.go
sdks/go/test/integration/io/xlang/jdbc/jdbc.go

Update JDBC IO wrapper to have expansion service as an optional argument. Small refactoring and documentation.
Tests are filtered out because of [BEAM-13778](https://issues.apache.org/jira/browse/BEAM-13778). It will added once we resolve this.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[BEAM-13293] Refactor JDBC IO Go Wrapper

---

build.gradle.kts
sdks/java/container/license_scripts/dep_urls_java.yaml
sdks/java/container/license_scripts/license_script.sh
sdks/java/container/license_scripts/manual_licenses/xz/COPYING
sdks/java/container/license_scripts/pull_licenses_java.py

* Move from using a privately-managed git repo file to a local file for xz-java
* Update java license script for to providing absolute file path
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

Edit license script for Java, add manual licenses for xz 

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisIO.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisReader.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisSource.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/ShardReadersPool.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisReaderTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/ShardReadersPoolTest.java

This just prepares the Kinesis Source for use with a generalized ClientBuilderFactory.
Instead of passing on all `Read` parameters individually, pass on `Read` itself.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13563] Restructure Kinesis Source for AWS 2

---

model/fn-execution/src/main/resources/org/apache/beam/model/fnexecution/v1/standard_coders.yaml
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/ModelCoderRegistrar.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/CoderTranslationTest.java
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/wire/CommonCoderTest.java
sdks/go/test/regression/coders/fromyaml/fromyaml.go
sdks/python/apache_beam/coders/standard_coders_test.py

Add coverage for Java and Python. Skip testing for Go. Go change a future follow-up.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[BEAM-13801] Add standard coder tests for state backed iterable.

---

build.gradle.kts
sdks/java/container/license_scripts/dep_urls_java.yaml
sdks/java/container/license_scripts/license_script.sh
sdks/java/container/license_scripts/manual_licenses/xz/COPYING
sdks/java/container/license_scripts/pull_licenses_java.py

Cherrypick of #16692 since it's likely any builds of the release containers are going to start running into issues 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[release-2.36.0] Move xz licenses to manual licenses for Java containers

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageSourceBase.java

This NullPointerException is preventable, easily caught by checkerframework, but it was disabled. Found it via a user report so fixed checkerframework for just this class.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13768] Fix NullPointerException in BigQueryStorageSourceBase

---

sdks/go/prepare_go_version.sh

Make the instructions clearer on what to do when either there's no Go installed at all, or the version is too low. Add comments for why we need it (hermetic reproducible builds).
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td> …

[BEAM-12830] Print clearer go version fail message

---

website/www/site/content/en/documentation/resources/learning-resources.md
website/www/site/layouts/partials/section-menu/en/get-started.html

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

 Add reference to Books to Learning Resources in website

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/flink/flink_runner.gradle
runners/google-cloud-dataflow-java/worker/legacy-worker/build.gradle
sdks/java/extensions/sql/build.gradle
sdks/java/extensions/sql/datacatalog/build.gradle
sdks/java/io/hadoop-common/build.gradle
sdks/java/io/hadoop-format/build.gradle
sdks/java/io/hcatalog/build.gradle

Cherrypick of #16688
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Fli …

[release-2.36.0][BEAM-13430] Fix provided configuration 

---

sdks/java/harness/build.gradle

Unfortunately we can't simply shade it, as it's used in the public API
(AvroCoder) of sdks:java:core.  However, outside that use, it should not
be needed when running in portable mode.  Users will have to provide
their own avro (typically by depending on sdks:java:core, but possibly
choosing another version explicitly or from elsewhere).
<table>
<thead>
<tr> …

[BEAM-13800] Avoid packaging avro in the java harness jar.

---

sdks/go/examples/xlang/sql/sql.go
sdks/go/pkg/beam/core/runtime/xlangx/expand.go
sdks/go/pkg/beam/core/runtime/xlangx/registry.go
sdks/go/pkg/beam/core/runtime/xlangx/registry_test.go
sdks/go/pkg/beam/core/runtime/xlangx/resolve.go
sdks/go/pkg/beam/transforms/sql/sql.go
sdks/go/pkg/beam/transforms/sql/sqlx/sqlx.go

Adds eager artifact materialization for automated expansion service queries, avoiding leaking resources when used and allowing the service to be torn down after the `Expand()` call. This is achieved by adding a new `HandlerFunc` to manage this and logic in `getHandlerFunc()` to pass it back when needed. The SQL transform wrapper is modified to use this functionality when no expansion address is provided, and the written SQL example in the repository passes using this approach.
NOTE: the service start-up code depends on the Beam version found in `core/core.go` and the Beam version must be a non-dev release version with published JARs on Maven.
See the …

[BEAM-13399, BEAM-13683] Eagerly materialize artifacts for automated expansion service, add feature to SQL transform

---

.github/workflows/build_playground_backend.yml
.github/workflows/build_playground_frontend.yml
.github/workflows/playground_deploy_examples.yml

- Clean build directory
- Clean Kubernetes environments after CI/CD Examples (even if there are errors in the previous steps)
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13802][Playground] [Bugfix] Clean all build directroies, clean kubernetes env

---

sdks/go/test/build.gradle
sdks/go/test/integration/flags.go
sdks/go/test/run_validatesrunner_tests.sh

This is needed for integration tests of Schema IO based xlang transforms, like JDBC or BigQuery.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td> …

[BEAM-13293][BEAM-13806] Pipe a SchemaIO flag through Go integration test script.

---

playground/backend/internal/cloud_bucket/precompiled_objects.go

[BEAM-13737]
Update logic of receiving precompiled objects;
Increase timeout;
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13737][Playground] Local retrieving of example objects may fail with context deadline

---

sdks/go/pkg/beam/core/runtime/options.go
sdks/go/pkg/beam/core/runtime/options_test.go
sdks/go/pkg/beam/runners/dataflow/dataflow.go
sdks/go/pkg/beam/runners/direct/direct.go
sdks/go/pkg/beam/runners/universal/runnerlib/job.go
sdks/go/test/integration/primitives/pardo.go
sdks/go/test/integration/primitives/pardo_test.go

Right now, in the Go Sdk the Google Cloud Dataflow runner automatically populates PipelineOptions with a subset of the Command Line flags that a user passes in when running a pipeline, but all other runners do not. This document proposes unifying Go runners’ treatment of PipelineOptions so that by default each runner will populate PipelineOptions with all Command Line flags. We will still give each runner the ability to mask some subset of those flags.
Full design doc here - https://docs.google.com/document/d/1AyO5SDEd_DzyOyrz_TkyDLUv19eLsKI97vKM8I7fQ9o/edit#heading=h.wskna8eurvjv
For manual testing beyond the automated one I added, I ran this on the direct/dataflow/universal runners with a pipeline that just prints out the PipelineOptions key/values
**Direct runner**
**Spark (universal) …

[BEAM-13024] Unify PipelineOptions behavior

---

sdks/python/apache_beam/transforms/sql_test.py

[[BEAM-13815]](https://issues.apache.org/jira/browse/BEAM-13815)
This example doesn't do anything, decided to remove it.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13815] [Playground] [Bugfix] Remove Python SQL Test example from catalog

---

website/www/site/assets/scss/_case_study.scss

Fixed CSS for the `Case studies` page, especially this: https://beam.apache.org/case-studies/kio/.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ …

Fixed CSS for Case study page

---

sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/options/AwsOptions.java

Remove unused duplicate option for AWS client configuration (AWS Sdk v1), the correct option to use is `clientConfiguration`. `awsHttpClientConfiguration` was added in https://github.com/apache/beam/pull/11341, but isn't ever used.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[BEAM-13663] Remove unused duplicate option for AWS client configuration (AWS Sdk v1)

---

sdks/python/apache_beam/examples/complete/game/hourly_team_score.py
sdks/python/apache_beam/examples/complete/game/hourly_team_score_it_test.py
sdks/python/apache_beam/examples/complete/game/user_score.py

Fix failures introduced by #16154 in:
apache_beam.examples.complete.game.hourly_team_score_it_test.HourlyTeamScoreIT.test_hourly_team_score_it
apache_beam.examples.complete.game.user_score_it_test.UserScoreIT.test_user_score_it
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr> …

[BEAM-13811] Fix save_main_session arg in tests examples

---

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java
sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/data/BeamFnDataInboundObserver2.java
sdks/java/fn-execution/src/test/java/org/apache/beam/sdk/fn/CancellableQueueTest.java
sdks/java/fn-execution/src/test/java/org/apache/beam/sdk/fn/data/BeamFnDataInboundObserver2Test.java

This avoids the expense of constructing the stack trace for the common close operation.
This showed up as 2% sdk cpu on a runner harness integration benchmark.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13015] Calculate exception for closing BeamFnDataInboundObserver2 statically

---

vendor/README.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

Minor doc tweaks for validating vendoring.

---

sdks/go/pkg/beam/core/runtime/xlangx/resolve.go
sdks/go/pkg/beam/core/runtime/xlangx/resolve_test.go
sdks/go/pkg/beam/runners/dataflow/dataflowlib/stage.go

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13629] Update URL artifact type for Dataflow Go

---

sdks/go/pkg/beam/io/xlang/jdbcio/jdbc.go

Adds automated expansion service start up capability to JDBCio Read/Write calls. Validated by running integration test against an automated start-up scenario. 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13832] Add automated expansion service start-up to JDBCio

---

sdks/go/pkg/beam/io/xlang/debeziumio/debezium.go
sdks/go/test/integration/io/xlang/debezium/debezium_test.go

Adds capability for automatically starting a Debezium expansion service if a user does not provide an expansion service address. Also modifies the integration test for Debezium to allow auto startup for tests. 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody> …

[BEAM-13831] Add automated expansion service infra into Debezium Read()

---

sdks/go/pkg/beam/io/xlang/kafkaio/kafka.go
sdks/go/test/integration/io/xlang/kafka/kafka_test.go

Adds support for automatically starting up an expansion service for Kafka IO reads and writes if a user does not supply an address.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13821] Add automated expansion service start-up to KafkaIO

---

runners/direct-java/src/main/java/org/apache/beam/runners/direct/ExecutorServiceParallelExecutor.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/QuiescenceDriver.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoLifecycleTest.java

There was one more instance of this bug that was missed in the previous PR

[BEAM-11971] remove unsafe Concurrent data structure

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsModule.java

Avoid nullness issue during init of Jackson AwsModule.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13147] Avoid nullness issue during init of AwsModule (AWS Sdk v2)

---

runners/core-java/src/main/java/org/apache/beam/runners/core/TimerInternals.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/DirectTimerInternals.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/ExecutorServiceParallelExecutor.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/QuiescenceDriver.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/StatefulParDoEvaluatorFactory.java
runners/direct-java/src/main/java/org/apache/beam/runners/direct/WatermarkManager.java
runners/local-java/src/main/java/org/apache/beam/runners/local/ExecutionDriver.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

This reverts commit 8ea77f98376c396fa1b7002c98e26187bfe2d239.
R: @aaltay 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-11971] Revert "Fix timer consistency in direct runner"

---

website/www/site/content/en/documentation/io/built-in/snowflake.md
website/www/site/data/io_matrix.yaml

The documentation for SnowflakeIO has some bugs and it does not describe a few things very well. I would like to make the following changes:
- Fix code examples (!!)
- Add information about the need to add a maven package.
- Add links to other resources i.e. SnowflakeIO source code, SnowflakeIO Javadoc/pydoc, Snowflake docs
- Describe more precisely the `Snowflake.DataSourceConfiguration` object configuration for the different authentication methods.
- Add section about current limitations
- Improve file syntax
In the coming weeks, I will want to introduce more changes, but current changes seem crucial to me.
- I also had to turn off syntax highlighting as a temporary workaround as this guide does not yet follow the projects convention. We have separate documentation for Python and Java, …

[BEAM-13823] Update docs for SnowflakeIO

---

.test-infra/jenkins/job_PostCommit_Python_Examples_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Python_Examples_Direct.groovy
.test-infra/jenkins/job_PostCommit_Python_Examples_Flink.groovy
.test-infra/jenkins/job_PostCommit_Python_Examples_Spark.groovy

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[DO NOT MERGE] Running seed job for BEAM-12572

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/graph/ProjectionPushdownOptimizer.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/ …

[BEAM-12976] Log projection pushdown optimizations.

---

sdks/go/pkg/beam/runners/dataflow/dataflow.go

Right now, we perform checks on beam.Initialized in the universal and direct runners, but not in dataflow. This adds the check to dataflow so that we don't accidentally start pipelines without this step, which could result in misconfigured workers.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[BEAM-13419] Check for initialization in dataflow runner

---

playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown_body.dart
playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_form.dart

Changed color of "Delete" icon in the pipeline options dialog.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13820] [Playground] Outline delete icon in Pipeline options

---

playground/infrastructure/cd_helper.py
playground/infrastructure/grpc_client.py
playground/infrastructure/helper.py

[BEAM-13838]
Add logs for CD step
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13838][Playground] Add logs in case of empty graph for CD step

---

sdks/go/pkg/beam/io/xlang/jdbcio/jdbc.go
sdks/go/test/integration/integration.go
sdks/go/test/integration/io/xlang/jdbc/jdbc.go
sdks/go/test/integration/io/xlang/jdbc/jdbc_test.go

Updated the naming for expansion service address to maintain consistency in Go SDK IOs. Updated the flag check for `schemaio_expansion_addr` instead of `io_expansion_addr`
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13293] consistent naming for expansion service address and flag update

---

playground/backend/internal/cloud_bucket/precompiled_objects.go
playground/backend/internal/cloud_bucket/precompiled_objects_test.go
playground/infrastructure/helper.py

[BEAM-13790]
Update logic of receiving examples from the bucket;
Fix of setting up `link` for the `meta.file`
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComp …

[BEAM-13790][Playground] Change logic of receiving examples from the bucket on backend side

---

sdks/java/io/expansion-service/build.gradle

Updated the dependency for Java IO expansion service to include expansion service for debezium io as well.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastComplet …

[BEAM-13830] update dependency for debeziumio expansion service

---

sdks/go/test/run_validatesrunner_tests.sh

A quick bugfix on this oversight.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13806] Shutting down SchemaIO expansion services from Go VR script

---

sdks/python/scripts/generate_pydoc.sh

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13848] Update numpy intersphinx link

---

website/www/site/content/en/blog/beam-2.36.0.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[release-23.6.0] Fix JIRA link for 2.36 blog

---

sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/dynamodb/DynamoDBIO.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sns/SnsIO.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/dynamodb/DynamoDBIO.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sns/SnsIO.java

[BEAM-13840] Fix usage of legacy rawtypes in AWS modules
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13840] Fix usage of legacy rawtypes in AWS modules

---

sdks/python/apache_beam/examples/cookbook/bigtableio_it_test.py
sdks/python/apache_beam/io/gcp/bigtableio.py
sdks/python/apache_beam/io/gcp/bigtableio_test.py

Most Beam Runners should retry such bundles.
Also enables bigtableio_it_test.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13606] Fail bundles with failed BigTable mutations

---

sdks/python/apache_beam/transforms/ptransform.py

Because the return type of the ptransform_fn is not specified, [certain typecheckers](https://github.com/microsoft/pyright/issues/2688#issuecomment-990238720) will assume the type signature of functions decorated with it remain unchanged. However, ptransform_fn specifically adjusts the type signature such that the function no longer takes a pcoll.
This can be corrected by changing the the definition of ptransform_fn from:
```python
def ptransform_fn(fn):
```
to:
```python
def ptransform_fn(fn) -> Callable[..., _PTransformFnPTransform]: 
```
This allows the typechecker to understand the return type of a function decorated with ptransform_fn will instead be a _PTransformFnPTransform type.
Additionally, for Python 3.10, [ParamSpec](https://www.python.org/dev/peps/pep-0612/#parameter-specifica …

BEAM-13439 Type annotation for ptransform_fn

---

sdks/java/extensions/schemaio-expansion-service/build.gradle
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaIOProvider.java

Create a SchemaIO implementation for BigQueryIO, to externalize it so it can be used with cross-language. This initial implementation covers the bare minimum, and still needs additional debugging (it seems to have trouble reading elements from some tables), so this is currently marked as experimental.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th> …

[BEAM-13321] Initial BigQueryIO externalization.

---

sdks/go/test/build.gradle
sdks/go/test/integration/flags.go
sdks/go/test/integration/io/xlang/debezium/debezium_test.go
sdks/go/test/run_validatesrunner_tests.sh
sdks/java/io/expansion-service/build.gradle

This PR has following changes:
1.  remove debezium io dependency from :sdks:java:io expansion service
2. add a flag to startup debezium io expansion service separately
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13830] added a debeziumio_expansion_addr flag to GoSDK

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaIOProvider.java

Follow up for https://github.com/apache/beam/pull/16489
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Apply spotless.

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

R: @y1chi 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCom …

Update Dataflow Python dev container images.

---

sdks/go/examples/kafka/taxi.go
sdks/go/examples/xlang/bigquery/wordcount.go

Also does some polish and fixup to the Kafka taxi example to fix little nits that were noticed while adding this new example.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13732] Add example for Go BigQuery IO wrapper.

---

CHANGES.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Add Java 17 to CHANGES

---

CHANGES.md

Update CHANGES.md with Go SDK milestones.
In particular, the new, more convenient to uses Cross language Transforms with convenient automatic startup.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

Update CHANGES.md with Go SDK milestones.

---

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/data/BeamFnDataOutboundAggregator.java
sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/data/BeamFnDataOutboundObserver.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13193] Allow BeamFnDataOutboundObserver to flush elements.

---

sdks/java/io/amazon-web-services2/build.gradle
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/WatermarkPolicyTest.java

Just a bit of dependency cleanup ...
This removes the remaining usage of Powermock from aws2. There's no need to statically mock joda `Instant.now()`.
`DateTimeUtils` allows to easily wap the time provider for joda time and revert after tests.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th> …

[adhoc] Remove remaining usage of Powermock from aws2.

---

sdks/go/pkg/beam/core/runtime/exec/data.go
sdks/go/pkg/beam/core/runtime/exec/sideinput.go
sdks/go/pkg/beam/core/runtime/exec/sideinput_test.go
sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/runtime/graphx/translate_test.go
sdks/go/pkg/beam/core/runtime/harness/statemgr.go

Adds support for native iterable side inputs to the Go SDK, removing the fixed key + multimap infrastructure that was previously in place and replacing it with a Fn API iterable side input request instead. Also includes some refactors to clarify what functions are doing. 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th> …

[BEAM-13803] Add support for native iterable side inputs to the Go SDK

---

sdks/go/pkg/beam/core/funcx/fn.go
sdks/go/pkg/beam/core/funcx/fn_test.go
sdks/go/pkg/beam/core/funcx/output.go
sdks/go/pkg/beam/core/typex/class.go

Right now, when we have an emit function that takes in a nested type with a non-concrete type somewhere in it, we don't give a very clear error - e.g., if we tried to define the following pardo:
```
type nestedEmitType struct {
Ghi func(string) string
}
type emitType struct {
Abc string
Def nestedEmitType
}
func (f *extractFn) ProcessElement(ctx context.Context, line string, emit func(emitType)) {
... Do stuff ...
}
```
right now we get this error
```
panic: 	inserting ParDo in scope root/CountWords
constructing DoFn
invalid DoFn
caused by:
method ProcessElement invalid
caused by:
bad parameter type for reflect.methodValueCall: func(main.emitType)
```
This updates to give a much clearer error - e.g. for the same case with these changes:
```
panic: 	inserting ParDo in scope root/CountWords …
```

[BEAM-11095] Better error handling for illegal emit functions

---

sdks/java/io/expansion-service/build.gradle
sdks/python/apache_beam/io/external/xlang_jdbcio_it_test.py
sdks/python/apache_beam/io/jdbc.py
sdks/python/apache_beam/io/kafka.py
sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/transforms/external_test.py
sdks/python/apache_beam/utils/subprocess_server.py
sdks/python/setup.py

Adding support for including a new JAR in the classpath for Jdbc transforms.
- JAR can be a local path, URL, or gradle-style path inclusion.
r: @chamikaramj 
Passing new tests: https://ci-beam.apache.org/job/beam_PostCommit_Python38_PR/398/testReport/apache_beam.io.external.xlang_jdbcio_it_test/CrossLanguageJdbcIOTest/
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

Supporting JdbcIO driver in classpath for x-lang

---

release/src/main/scripts/publish_github_release_notes.sh
website/www/site/content/en/blog/beam-2.28.0.md
website/www/site/content/en/get-started/downloads.md

R: @aaltay 
R: @TheNeuralBit (FYI for next release)
I guess I could also hardcode the URL in the blog post template, but 🤷‍♀️ 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[release-2.36.0][website] Fix github release notes script, header for release 2.36.0

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

I was running into issues with the release where it was using /usr/bin/python and not my pyenv/$PATH-defined python. 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

Use shell to run python for setupVirtualenv

---

website/www/site/content/en/blog/beam-2.35.0.md

2.35 release is missing an important Bugfix related to data loss, and its contributor.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a> …

Add missing Bug and contributing user

---

sdks/go/test/run_validatesrunner_tests.sh

Quick fix to this issue.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13830] Properly shut down Debezium expansion service in IT script.

---

CHANGES.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

Minor: Add 2.38.0 section to CHANGES.md

---

runners/core-java/src/main/java/org/apache/beam/runners/core/SimpleDoFnRunner.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

Fix the log line (returned when an output timestamp is not valid) to properly print large skews (from doFn.getAllowedTimestampSkew()).
It fails to print when the number of years in the printed result is larger than an int. In this case, just print the skew as a long.
@udim 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th> …

Fix allowedSkew log line to properly print large skews

---

.test-infra/jenkins/job_PreCommit_Java.groovy
.test-infra/jenkins/job_PreCommit_Python.groovy
buildSrc/build.gradle.kts
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-12672] Add plugin to retry flaky tests

---

.test-infra/jenkins/job_PreCommit_Portable_Python.groovy

Cherry-picks https://github.com/apache/beam/pull/16812

[release-2.37.0] CP a typo fix in job_PreCommit_Portable_Python.groovy

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamIT.java

The GSON object was being initialized in a static context. When the DoFn that used it was called in another JVM, which did not initialized this object, we were getting a NPE exception.
Here, we move the initialization of the GSON object inside the DoFn itself (through a setup method).

[BEAM-12164]: Fixes SpannerChangeStreamIT

---

sdks/go/pkg/beam/options/gcpopts/options.go
sdks/go/pkg/beam/options/gcpopts/options_test.go

Improve our test coverage for gcpopts - I originally had some mocking to test the `gcloud config` path, but decided to cut it because mostly it was just testing my ability to mock something, not the actual underlying code. If you disagree, take a look at my first commit and let me know if you want me to add it back.
<table>
<thead>
<tr>
<th>Lang</th> …

[BEAM-13908] [Coverage] Better testing coverage for gcpopts

---

website/www/site/content/en/contribute/release-guide.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

Minor: Fix link to nexmark benchmarks

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamIT.java

The GSON object was being initialized in a static context. When the DoFn
that used it was called in another JVM, which did not initialized this
object, we were getting a NPE exception.
Here, we move the initialization of the GSON object inside the DoFn
itself (through a setup method).
<table>
<thead> …

[release-2.37.0][BEAM-12164]: Fixes SpannerChangeStreamIT (#16806)

---

.github/workflows/build_playground_backend.yml

fix name project id from secret on scio deploy action
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13862][Playground][Bugfix] Fix name of project Id for SCIO GHA

---

playground/frontend/lib/config/theme.dart
playground/frontend/lib/playground_app.dart
playground/frontend/pubspec.lock
playground/frontend/pubspec.yaml

Added local storage for a theme mode.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13655] [Playground] Persist the dark/light mode selection

---

website/www/site/content/en/blog/beam-2.36.0.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Update 2.36.0 blog post to mention ARM64 support

---

CHANGES.md
sdks/python/apache_beam/dataframe/schemas.py
sdks/python/apache_beam/runners/direct/direct_runner.py
sdks/python/apache_beam/transforms/core.py

This is technically a breaking change, but I think it's a safe one as I don't expect many people are overriding `DoFn.infer_output_type`. I looked for instances of this in internal Google code, and there's only one such case. Funnily enough, it actually respects _this_ proposed API, and returns the element type, not `Iterable[element_type]`.  This is also true for the place we override it in `apache_beam.dataframe.schemas`, previously that code had a workaround to deal with the improper handling, which can now be removed.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr> …

[BEAM-13860] Make `DoFn.infer_output_type` return element type

---

website/www/site/content/en/get-started/try-beam-playground.md

Update MinimalWordCount example link on the Try Beam Playground page from `SDK_JAVA/MinimalWordCount` to `SDK_JAVA/PRECOMPILED_OBJECT_TYPE_EXAMPLE/MinimalWordCount` according to the new examples architecture.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody> …

[BEAM-13941][Playground] Fix example link on the Playground get-started page

---

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/PerKeyOrderingTest.java

These tests all use State to check their output.
R: @pabloem 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13919] Annotate PerKeyOrderingTest with UsesStatefulParDo.

---

sdks/go/container/boot.go
sdks/go/container/boot_test.go

I split out the long main function into a couple of functions and added coverage. This isn't complete, but I think its as far as I want to go with this one - I think anything further would mostly be testing implementation or testing the dependencies this is calling
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th> …

[BEAM-13922] [Coverage] Make boot.go more testable and add tests

---

model/pipeline/src/main/proto/beam_runner_api.proto
runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/ParDoTranslation.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/ParDoTranslationTest.java
sdks/python/apache_beam/portability/common_urns.py
sdks/python/apache_beam/transforms/userstate.py
sdks/python/apache_beam/transforms/userstate_test.py

The ability to mix and match runners and SDKs is accomplished through two portability layers:
1. The Runner API provides an SDK-and-runner-independent definition of a Beam pipeline
2. The Fn API allows a runner to invoke SDK-specific user-defined functions
Apache Beam pipelines support executing stateful DoFns[1]. To support this execution the Runner API defines multiple user state specifications:
* ReadModifyWriteStateSpec
* BagStateSpec
* OrderedListStateSpec
* CombiningStateSpec
* MapStateSpec
* SetStateSpec
The Fn API[2] defines APIs[3] to get, append and clear user state currently supporting a BagUserState and MultimapUserState protocol.
Since there is no clear mapping between the Runner API and Fn API state specifications, there is no way for a runner to know that it supports a …

[Cherrypick 2.37.0][BEAM-13930] Address StateSpec consistency issue between Runner and Fn API.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java

Just a small javadoc improvement to avoid friction.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13854] Document casting trick for Avro value serializer in KafkaIO

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/InsertRetryPolicy.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImplTest.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13931] - make sure large rows cause BQIO to throw an error

---

sdks/java/io/hadoop-file-system/build.gradle

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[BEAM-13694] Force hadoop-hdfs-client in hadoopVersion tests for hdfs

---

sdks/java/io/hadoop-file-system/build.gradle

Cherrypick #16861 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[release-2.37.0][BEAM-13694] Force hadoop-hdfs-client in hadoopVersion tests for hdfs

---

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/PerKeyOrderingTest.java

Cherrypick #16811
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[release-2.37.0][BEAM-13919] Annotate PerKeyOrderingTest with UsesStatefulParDo

---

sdks/python/apache_beam/io/aws/s3io.py
sdks/python/apache_beam/io/aws/s3io_test.py

Change-Id: I017e239d2e824791b94fea4338b2b9b68a33b686
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13827] - fix medium file size upload to s3

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/InsertRetryPolicy.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImplTest.java

Cherry pick of #16838
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Fl …

[cherry-pick][release-2.37.0][BEAM-13931] - make sure large rows cause BQIO to throw an error

---

playground/frontend/lib/modules/sdk/components/sdk_selector.dart

I added support for SCIO Sdk.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13785] [Playground] enable SCIO sdk

---

runners/samza/build.gradle
sdks/java/core/src/main/java/org/apache/beam/sdk/testing/UsesProcessingTimeTimers.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/GroupByKeyTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

The three commits here are independent and should not be squashed.
1. create the category
2. label some tests
3. exclude the category from Samza runner
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

Create test category for UsesProcessingTimeTimers are exclude from Samza

---

website/www/site/content/en/roadmap/_index.md
website/www/site/content/en/roadmap/java-sdk.md

The website currently makes it look like Java 11 is not yet supported, so this is a small update to match current state.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

Update Java LTS roadmap info on website for Java 17

---

sdks/go/test/integration/integration.go

Cherrypick #16815
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[release-2.37.0][BEAM-13921] filter out debeziumIO test for spark runner

---

CHANGES.md
gradle.properties
runners/flink/1.11/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/AbstractStreamOperatorCompat.java
runners/flink/1.11/src/test/java/org/apache/beam/runners/flink/metrics/MetricGroupWrapper.java
runners/flink/1.12/src/test/java/org/apache/beam/runners/flink/streaming/StreamSources.java
runners/flink/1.13/src/test/java/org/apache/beam/runners/flink/streaming/StreamSources.java
runners/flink/1.14/build.gradle
runners/flink/1.14/job-server-container/build.gradle
runners/flink/1.14/job-server/build.gradle
runners/flink/1.14/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/AbstractStreamOperatorCompat.java
runners/flink/1.14/src/test/java/org/apache/beam/runners/flink/RemoteMiniClusterImpl.java
runners/flink/1.14/src/test/java/org/apache/beam/runners/flink/metrics/MetricGroupWrapper.java
runners/flink/1.14/src/test/java/org/apache/beam/runners/flink/streaming/StreamSources.java
runners/flink/flink_runner.gradle
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineExecutionEnvironment.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperator.java
runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkSavepointTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/metrics/FlinkMetricContainerTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/streaming/BoundedSourceRestoreTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/UnboundedSourceWrapperTest.java
sdks/python/apache_beam/options/pipeline_options.py
settings.gradle.kts

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13106] Add support for Flink 1.14

---

runners/google-cloud-dataflow-java/build.gradle

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Bump dataflow.fnapi_container_version

---

runners/google-cloud-dataflow-java/build.gradle

This test did not pass on Dataflow Streaming. Internal local runner tests did pass. Probably the latency built in to the test was not enough in production.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-13952] Disable AfterSynchronizedProcessingTime test on Dataflow

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

Fix one more log line to properly handle a large allowedskew when printing it.
This was one I missed in https://github.com/apache/beam/pull/16749.
@udim 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

Fix final allowskew error to properly handle a large allowedSkew

---

sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/AwsOptionsTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/S3OptionsTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/SerializationTestUtil.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td> …

[adhoc] Avoid using SerializablePipelineOptions for testing to minimize dependencies

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

[release-2.37.0][BEAM-13959] Fix StorageApi writes when a field is named f

---

sdks/python/.pylintrc
sdks/python/apache_beam/io/external/xlang_kinesisio_it_test.py
sdks/python/apache_beam/runners/common.py
sdks/python/apache_beam/runners/portability/portable_runner.py

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
</a> …

[BEAM-13051][C] Enable pylint warnings (misplaced-bare-raise/no-member)

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/mapper/ChangeStreamRecordMapper.java

struct.getValue() throws an error when getting a struct that contains
a json inside. We circumvent this, by checking the type and calling
either struct.getString() or struct.getJson().
r: @TheNeuralBit 
fyi @thiagotnunes 
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr> …

[cherry-pick][release-2.37.0][BEAM-12164]: fix bug when retrieving either string or json #16890

---

sdks/python/apache_beam/examples/complete/autocomplete_it_test.py
sdks/python/apache_beam/examples/complete/autocomplete_test.py
sdks/python/apache_beam/examples/complete/estimate_pi_it_test.py
sdks/python/apache_beam/examples/complete/estimate_pi_test.py
sdks/python/apache_beam/examples/complete/top_wikipedia_sessions_it_test.py
sdks/python/apache_beam/examples/complete/top_wikipedia_sessions_test.py
sdks/python/apache_beam/examples/cookbook/coders_it_test.py
sdks/python/apache_beam/examples/cookbook/coders_test.py
sdks/python/pytest.ini
sdks/python/test-suites/dataflow/common.gradle

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-12572] Fix failing python examples tests in Dataflow runner

---

sdks/java/io/amazon-web-services2/build.gradle
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/SqsUnboundedReaderTest.java
sdks/java/io/amazon-web-services2/src/test/resources/application.conf

[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20w …

[BEAM-13738] Reenable ignored SQS test after bumping elasticmq for fixed version

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageQueryTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadTest.java

Note that checking for only the main output ("output") is hacky. It works for now because we only look at the main output in the optimizer for now, but going forward we should have a way to make sure the optimizer actually works with other outputs.
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th> …

[BEAM-13796] projection pushdown in BQ IO

---

README.md

Right now, the Go is the only Sdk without a badge, this adds one!
R: @lostluck  …

Add Go badge to ReadMe

---

sdks/python/apache_beam/io/aws/clients/s3/boto3_client.py
website/www/site/content/en/blog/beam-2.36.0.md

`get_object_metadata()` went missing in 2.36.0. This PR adds it back.
Fixes BEAM-13980
R: @mosche @aaltay …

[BEAM-13980] Re-add method gone missing in af2f8ee6

---

sdks/go/pkg/beam/core/graph/mtime/time.go
sdks/go/pkg/beam/core/graph/mtime/time_test.go

Add unit tests to cover expected behavior of mtime package functions, remove `n2m()` function in favor of using the `time` package's millisecond functions. Unit tests were added first to ensure that the slight refactor did not break expected behavior at boundaries.  …

[BEAM-13884] Improve mtime package

---

.test-infra/jenkins/job_PreCommit_Java.groovy
.test-infra/jenkins/job_PreCommit_Python.groovy
buildSrc/build.gradle.kts
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Plugin Flaky-test-handler was causing stability issues in Jenkins master, revert of #16253 which is not going to work without the plugin.
Reference https://issues.apache.org/jira/browse/INFRA-22878 …

[BEAM-12672] Revert #16253 due errors with plugin flaky-test-handler

---

release/src/main/scripts/cut_release_branch.sh
release/src/main/scripts/set_version.sh

Confirmed, diff for a release branch for 2.37.0 would look like:
```diff
-    'dataflow.legacy_container_version' : 'beam-master-20220203',
-    'dataflow.fnapi_container_version' : 'beam-master-20220216',
+    'dataflow.legacy_container_version' : '2.37.0',
+    'dataflow.fnapi_container_version' : '2.37.0',
``` …

[BEAM-4767] Remove beam- prefix from release script tags

---

sdks/go/pkg/beam/util/errorx/guarded_test.go

Adds small clarifying parentheses to boolean assignment for guarded error check, also adds small unit tests.  …

[BEAM-13866] Add small unit tests to errorx, make boolean assignment clear

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/SimpleStateRegistry.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/FnApiTimerBundleTracker.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java

About 1% total of cpu on google internal benchmark, .8% for allowedLateness
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

Memoize some objects for timer processing to reduce overhead.

---

runners/google-cloud-dataflow-java/build.gradle

…ngState
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13952] Sickbaying testAfterProcessingTimeContinuationTriggerUsingState

---

sdks/go/pkg/beam/runners/dataflow/dataflow.go
sdks/go/pkg/beam/runners/dataflow/dataflow_test.go

Refactors dataflow.go and increases test coverage. This one wasn't hugely high value, but I think the refactor made sense anyways …

[BEAM-13912] Add more coverage for dataflow.go

---

sdks/go/pkg/beam/core/runtime/exec/coder.go
sdks/go/pkg/beam/core/runtime/exec/coder_test.go

Updates exec/coder.go unit tests to exercise coders that are currently untested. Also updates the window coder wrapper functions to encode/decode multiple windows instead of just one. …

[BEAM-14001] Update coder.go unit tests

---

sdks/go/pkg/beam/util/gcsx/example_test.go
sdks/go/pkg/beam/util/gcsx/gcs_test.go

This technically had a test file, but it was just an example of how to use the class (which I got rid of because it didn't seem very useful and didn't make much sense in a test file IMO).
Most of this package is wrappers around the gcs client which is not worth testing IMO (the mocking would probably be more complex than the functions being tested). This tests the other functions (mostly to do with url pathing) …

[BEAM-13910] Improve coverage of gcsx package

---

playground/backend/cmd/server/controller.go
playground/backend/cmd/server/server.go
playground/backend/containers/go/Dockerfile
playground/backend/containers/java/Dockerfile
playground/backend/containers/python/Dockerfile
playground/backend/containers/router/Dockerfile
playground/backend/containers/scio/Dockerfile
playground/backend/internal/cloud_bucket/precompiled_objects.go
playground/backend/internal/cloud_bucket/precompiled_objects_test.go
playground/backend/internal/environment/application.go
playground/backend/internal/environment/environment_service.go
playground/backend/internal/environment/environment_service_test.go
playground/backend/internal/utils/precompiled_objects_utils.go

[BEAM-13963]
Move the name of the bucket to the `environment_service`
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
<a …

[BEAM-13963][Playground] Get bucket name from environment variable

---

examples/java/src/main/java/org/apache/beam/examples/WindowedWordCount.java
examples/java/src/main/java/org/apache/beam/examples/complete/TfIdf.java
examples/java/src/main/java/org/apache/beam/examples/complete/TopWikipediaSessions.java
examples/java/src/main/java/org/apache/beam/examples/complete/TrafficMaxLaneFlow.java
examples/java/src/main/java/org/apache/beam/examples/complete/TrafficRoutes.java
learning/katas/python/IO/TextIO/ReadFromText/task.py
sdks/python/apache_beam/examples/complete/game/user_score.py

[BEAM-13874]
Tag multifile examples:
- `WindowedWordCount.java`
- `TfIdf.java`
- `TopWikipediaSessions.java`
- `TrafficMaxLaneFlow.java`
- `TrafficRoutes.java`
- python kata `ReadFromText`
- `user_score.py`
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr> …

[BEAM-13874][Playground] Tag multifile examples

---

.github/workflows/build_wheels.yml

Cherry pick #16964
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=mast …

[release-2.37.0][BEAM-12000] Build wheels for Python 3.9

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/BatchSpannerRead.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOReadTest.java

Cherrypick #16960
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=maste …

[release-2.37.0][BEAM-14005] Fix ignored exception in BatchSpannerRead

---

sdks/python/apache_beam/io/aws/clients/s3/boto3_client.py
website/www/site/content/en/blog/beam-2.36.0.md

Cherrypick #16918
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=maste …

[release-2.37.0][BEAM-13980] Re-add method gone missing in af2f8ee6 (#16918)

---

sdks/go/pkg/beam/x/debug/head_test.go
sdks/go/pkg/beam/x/debug/print_test.go

Improves testing of the debug package. Mostly sets up pipelines and verifies the results (with testing print I had to do some log capturing). …

[BEAM-13899] Improve coverage of debug package

---

release/src/main/python-release/python_release_automation_utils.sh
release/src/main/python-release/run_release_candidate_python_mobile_gaming.sh
release/src/main/python-release/run_release_candidate_python_quickstart.sh

This PR:
* Adds clean-up step prior to running HourlyTeamScore
* Fixes variable/naming of tables to make table name (per-runner) more clear 
* `s/verify_steaming_result/verify_streaming_result`
We may also want to consider not failing on first test failure (we have set -e) so we can get other test signals at least.
Tested by cherry-picking into a 2.37.0 test branch (https://github.com/apache/beam/pull/16944), [test run](https://ci-beam.apache.org/job/beam_PostRelease_Python_Candidate/229/) …

[BEAM-9150] Fix beam_PostRelease_Python_Candidate (python RC validation scripts)

---

sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java

Using `ProcessContext#outputWithTimestamp` is more fragile than `output`, and explicit use of `outputWithTimestamp` is not required in the case of ES module; in fact, code is currently trying to emulate `output` by storing and recalling element timestamps. This change is being made after finding an issue with timestamp validation when starting a pipeline from a snapshot that could have been avoided with this change.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easi …

Use default context output rather than outputWithTimestamp for ElasticsearchIO

---

website/www/site/content/en/case-studies/paloalto.md

Fixed link in the Palo Alto case study
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20so …

[Bugfix] Palo Alto case study - fix link

---

website/www/site/content/en/blog/upcoming-events-for-beam-in-2022.md
website/www/site/data/authors.yml

Add 2022 events blog post

---

sdks/go/pkg/beam/runners/direct/direct_test.go

Copy tests from my direct runner replacement project to add coverage to the direct runner. This handles a number of features tested elsewhere in the SDK, but it overall hurts our coverage number as a result. Adding a suite of simple pipelines against the Direct runner improves it's coverage by ~70%, even without touching the Combine and SDF edge cases. …

[BEAM-13911] Add basic tests to Go direct runner.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Bump org.mongodb:mongo-java-driver to 3.12.10
No breaking changes are expected …

[BEAM-5577] Bump org.mongodb:mongo-java-driver to 3.12.10

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java

Skipping flaky sad-path tests for Spanner changestreams

---

sdks/go/pkg/beam/core/graph/window/fn_test.go
sdks/go/pkg/beam/core/graph/window/windows.go
sdks/go/pkg/beam/core/graph/window/windows_test.go

Adds unit tests to window package, largely testing equality of windows and windowFns. Also adds function comments to the window Equals() functions that did not have them. …

[BEAM-13885] Add unit tests to window package

---

playground/frontend/lib/modules/graph/graph_builder/canvas_drawer.dart
playground/frontend/lib/modules/graph/graph_builder/graph_builder.dart
playground/frontend/lib/modules/graph/graph_builder/painters/edge_painter.dart
playground/frontend/lib/modules/graph/graph_builder/painters/graph_painter.dart
playground/frontend/lib/modules/output/components/graph.dart
playground/frontend/lib/modules/output/components/output_area.dart

I added vertical orientation for graphs. (https://issues.apache.org/jira/browse/BEAM-13999) …

[BEAM-13999] [Playground] support vertical orientation for graph

---

CHANGES.md
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/s3/S3FileSystem.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystem.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystemTest.java

This PR fixes the AWS2 S3FileSystem multipart copy. …

[BEAM-14011] fix s3 filesystem multipart copy

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.37.0.md
website/www/site/content/en/get-started/downloads.md

<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
</a>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>---</td>
</tr>
<tr>
<td>Java</td>
<td>
<a …

Doc updates and blog post for 2.37.0

---

sdks/python/apache_beam/examples/snippets/transforms/elementwise/pardo.py
website/www/site/content/en/documentation/transforms/python/elementwise/pardo.md

This makes the following two changes:
* Issue [BEAM-7885] has been resolved, so removing from the list of known issues.
* Updating the path `beam.window.GlobalWindow` to the new path `beam.transforms.window.GlobalWindow`.
R: @aaltay  …

Remove resolved issue in docs + update class path on sample

---

scripts/ci/pr-bot/processNewPrs.ts

TIL that Javascript 0 indexes months in its date constructor (it doesn't do so with days or years). This caused our date cutoff to be a month off so the PR bot didn't pick up our new PRs. …

[BEAM-13925] months in date constructor are 0 indexed

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/worker/sdk_worker_main.py
sdks/python/apache_beam/runners/worker/sdk_worker_main_test.py

The --beam_plugin PipelineOption is current unused and does not import plugins before starting the SdkHarness. This PR aims to import the plugins before starting the SdkHarness. …

[BEAM-13993] [BEAM-10039] Import beam plugins before starting SdkHarness

---

examples/notebooks/documentation/transforms/python/elementwise/pardo-py.ipynb

Follow up from #17018
R: @aaltay 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source% …

Remove resolved issue in notebook

---

sdks/go/pkg/beam/core/runtime/exec/fullvalue_test.go
sdks/go/pkg/beam/core/runtime/exec/pardo_test.go

Part of our streaming roadmap is validating window correctness - https://cwiki.apache.org/confluence/display/BEAM/Supporting+Streaming+in+the+Go+SDK
This knocks out the last item from that list by introducing some simple tests that we can access windows correctly in DoFns.
GitHub Actions …

[BEAM-11085] Test that windows are correctly observed in DoFns

---

.github/workflows/pr-bot-pr-updates.yml

Right now, the PR bot fails on pr-update events if the pr author doesn't have the right permissions. This gives all authors the correct permissions and pins the repo we checkout to master so that users can't do something malicious by changing the script we execute. …

[BEAM-13925] Give pr bot write permissions on pr update

---

sdks/go/examples/kafka/taxi.go

Adds step in taxi.go Kafka example to change working directory to Go subdirectory to avoid go.mod errors.  …

[BEAM-14050] Update taxi.go example instructions

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

[BEAM-11205] Upgrade Libraries BOM dependencies to 24.4.0

---

sdks/go/pkg/beam/core/util/reflectx/call_test.go
sdks/go/pkg/beam/core/util/reflectx/functions_test.go
sdks/go/pkg/beam/core/util/reflectx/structs_test.go
sdks/go/pkg/beam/core/util/reflectx/types_test.go

Adds testing for everything in reflectx except for calls.go (generated code) and tags.go (unused as best I can tell, PR to deprecate coming shortly). …

[BEAM-13904] Increase unit testing in the reflectx package

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/worker/sdk_worker_main.py
sdks/python/apache_beam/runners/worker/sdk_worker_main_test.py

[BEAM-14072] Revert "[BEAM-13993] [BEAM-10039] Import beam plugins before starting SdkHarness"

---

playground/frontend/lib/l10n/app_en.arb
playground/frontend/lib/modules/examples/components/description_popover/description_popover_button.dart
playground/frontend/lib/modules/examples/components/multifile_popover/multifile_popover_button.dart
playground/frontend/lib/modules/sdk/components/sdk_selector.dart
playground/frontend/lib/modules/shortcuts/components/shortcut_tooltip.dart
playground/frontend/lib/pages/playground/components/editor_textarea_wrapper.dart
playground/frontend/lib/pages/playground/components/feedback/feedback_dropdown_icon_button.dart
playground/frontend/lib/pages/playground/components/feedback/playground_feedback.dart
playground/frontend/lib/pages/playground/playground_page.dart

I added semantics to elements to improve accessibility (lighthouse report increased it from 73 to 80) …

[BEAM-14079] [playground] Improve accessibility

---

scripts/ci/pr-bot/shared/commentStrings.ts

The [last change](https://github.com/apache/beam/pull/17001) had a small bad copy from my test repo - unfortunately its impossible to fully test this without commenting on prs, so I didn't catch it. This fixes it up. …

[BEAM-13925] Fix import path

---

scripts/ci/pr-bot/shared/reviewerConfig.ts

Same underlying problem as https://github.com/apache/beam/pull/17068 - the [last change](https://github.com/apache/beam/pull/17001) had a small bad copy from my test repo - unfortunately its impossible to fully test this without commenting on prs, so I didn't catch it. This fixes it up. …

[BEAM-13925] Fix one more import path

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/worker/sdk_worker_main.py
sdks/python/apache_beam/runners/worker/sdk_worker_main_test.py

The `--beam_plugin` PipelineOption is current unused and does not import plugins before starting the SdkHarness. This PR aims to import the plugins before starting the SdkHarness. This also addresses the integration test failures as seen in BEAM-14072 …

[BEAM-14072] [BEAM-13993] [BEAM-10039] Import beam plugins before starting SdkHarness

---

sdks/python/apache_beam/io/snowflake.py

We don't have a coder defined for `typing.List`, but we do have one for `typing.Iterable` and we can use it.
CC: @pabloem 
This change is covered by tests, but they don't run on CI because credentials are missing. Does anyone know how I can configure these credentials? Snowflake will gladly cover the costs to avoid similar problems in the future. …

[BEAM-14075] [SnowflakeIO] Change a output type in WriteToSnowflake

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/build-tools/src/main/resources/beam/suppressions.xml
sdks/java/io/amazon-web-services2/build.gradle
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/common/ClientPool.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/AsyncPutRecordsHandler.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisIO.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisPartitioner.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/RecordsAggregator.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/common/ClientPoolTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/AsyncPutRecordsHandlerTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisIOIT.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisIOWriteTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/PutRecordsHelpers.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/RecordsAggregatorTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/AwsModuleTest.java

This implements the missing writer for Kinesis on AWS SDKV v2, one of the big milestones to get feature parity between the SDK v1 and v2 based IOs.
Currently the Kinesis Producer Library (KPL) is not available for SDK v2. Instead, this implements the writer using the async Kinesis client.
There's two different writer modes available:
- A default writer that asynchronously batches records to Kinesis with configurable concurrency.
- An aggregated record writer compatible with KPL / KCL record aggregation that is implemented on top of the default writer.
While record aggregation is compatible with KPL / KCL, aggregation here a lot less aggressive.
Only records with the same effective hash key are aggregated to keep complexity manageable. Otherwise, the aggregator would have to be aware of …

[BEAM-13175] Add KinesisIO.write for AWS SDK v2.

---

CHANGES.md

Making note of the [new write support in Kinesis IO](https://github.com/apache/beam/pull/16077) and providing a summary of recent fixes improvements in the v2 module:
`amazon-web-services2` has reached feature parity and is finally recommended over the earlier `amazon-web-services` and `kinesis` modules (Java). These will be deprecated in one of the next releases ([BEAM-13174](https://issues.apache.org/jira/browse/BEAM-13174)).
* Long outstanding write support for `Kinesis` was added ([BEAM-13175](https://issues.apache.org/jira/browse/BEAM-13175)).
* Configuration was simplified and made consistent across all IOs, including the usage of `AwsOptions` ([BEAM-13563](https://issues.apache.org/jira/browse/BEAM-13563), [BEAM-13663](https://issues.apache.org/jira/browse/BEAM-13663), …

[BEAM-13175] Document changes to IOs in amazon-web-services2 for AWS Java SDK v2

---

sdks/python/apache_beam/runners/worker/sdk_worker.py

Adding pydoc for StateHandler

---

release/src/main/scripts/run_rc_validation.sh

Also increases wait time for Dataflow jobs to 20 mins since 10 minutes can be inadequate. …

[BEAM-14047] Updates x-lang release validation to use staged jars

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContext.java

This is so it does not bind StreamingModeExecutionContext which has high memory cost …

Minor: Make ScopedReadStateSupplier final

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/SerializableCoder.java

Currently it is `This may produce incorrect results on some PipelineRunner` which is a bit awkward …

Minor: Make serializableCoder warning gramatically correct english

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/MonitoringUtil.java

[BEAM-14087] Mapped JOB_STATE_RESOURCE_CLEANING_UP to State.RUNNING

---

release/src/main/scripts/build_release_candidate.sh

R: @youngoli (as next release manager)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/b …

[BEAM-12777] Create symlink for `current` directory

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/CounterCell.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/DirtyState.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/DistributionCell.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/GaugeCell.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/HistogramCell.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/CounterCellTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/DirtyStateTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/DistributionCellTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/GaugeCellTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/HistogramCellTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MetricsContainerImplTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java

This prevents many unnecessary counter updates in the case of Dataflow
streaming pipelines when resets occur frequently.
Add missing HIstogramCellTest.java and add HistogramData equality/hash operators for that test. …

[BEAM-13015] Modify metrics to begin and reset to a non-dirty state.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py

Avoid storing a generator in _CustomBigQuerySource so that it can be used with the Python interactive runner. See details in https://issues.apache.org/jira/browse/BEAM-14112 .
Likely related to #15610 …

[BEAM-14112] Avoid storing a generator in _CustomBigQuerySource

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py

Populate environment capabilities in v1beta3 protos.

---

CHANGES.md
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkRunner.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadIT.java

[BEAM-12976] Enable projection pushdown in runners

---

sdks/python/test-suites/direct/common.gradle

R: @y1chi 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20 …

[BEAM-14123] Fix typo in hdfsIntegrationTest task name.

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

[BEAM-10212] Clean-up comments, remove rawtypes usage.

---

sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/dynamodb/DynamoDBIOWriteTest.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sns/SnsIOTest.java

Removing unused rule from aws2 tests
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20sour …

[adhoc] Removing unused rule from aws2 tests

---

website/www/site/data/io_matrix.yaml

Next step towards deprecating the initial aws IOs / module: Updating the IO matrix on the website to recommend the aws2 IOs. …

[BEAM-14125] Update website IO matrix to recommend aws2 IOs

---

.github/workflows/build_wheels.yml
.github/workflows/java_tests.yml
.github/workflows/playground_deploy_examples.yml
.github/workflows/python_tests.yml

setup-gcloud will be updating the branch name from master to main in
a future release. Even though GitHub will establish redirects, this
will break any GitHub Actions workflows that pin to master. This PR
updates your GitHub Actions workflows to pin to v0, which is the
recommended best practice.
GitHub Actions …

Pin setup-gcloud to v0 instead of master

---

CHANGES.md

Mention https://issues.apache.org/jira/browse/BEAM-14128 in CHANGES.md for 2.38 …

Update Changes.md w/Go pipeline pre-process fix.

---

sdks/python/container/Dockerfile

[BEAM-14122] Upgrade pip-licenses dependency

---

sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/ITEnvironment.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/dynamodb/testing/DynamoDBIOIT.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/testing/KinesisIOIT.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/testing/S3FileSystemIT.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sns/testing/SnsIOIT.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/testing/SqsIOIT.java

Move aws2 IT tests to `testing` package according to [best practices](https://docs.google.com/document/d/1V2FkGGunVgvLwi1dKHr-7mtDuwYjTuvuESV_oPzVnfQ) …

[adhoc] Move aws IT tests to testing package according to best practices

---

sdks/go/test/integration/io/xlang/debezium/debezium.go
sdks/go/test/integration/io/xlang/jdbc/jdbc.go
sdks/go/test/integration/primitives/cogbk.go
sdks/go/test/integration/primitives/window_panes.go

Small fix to eliminate static check error and go lint issues in Go SDK. …

fixes static checks and go lint issues in Go SDK

---

sdks/go/pkg/beam/core/runtime/exec/sideinput.go
sdks/go/pkg/beam/core/runtime/exec/sideinput_test.go
sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download.go
sdks/go/pkg/beam/options/gcpopts/options_test.go
sdks/go/pkg/beam/provision/provision_test.go
sdks/go/pkg/beam/runners/dataflow/dataflow_test.go
sdks/go/pkg/beam/transforms/sql/sqlx/sqlx.go

Addresses a number of staticcheck and linter warnings, mostly use of nil contexts in unit tests and missing comments for exported functions and variables.  …

[BEAM-14136] Clean up staticcheck and linter warnings in the Go SDK

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageTableSource.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadTest.java

Add display data for "Selected fields" and "Projection pushdown
applied". I also want to add one for "Number of fields pushed down", but
that will be a little more involved so I'll do it in a separate PR.
R: @apilloud  …

[BEAM-14124] Add display data to BQ storage reads.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py

Reverts apache/beam#17100
Caused Python PostCommit to fail: https://ci-beam.apache.org/job/beam_PostCommit_Python38/2407/

[BEAM-14138] Revert "[BEAM-14112] Avoid storing a generator in _CustomBigQuerySource"

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java

[BEAM-14152] Disable flaky SpannerChangeStreamErrorTest.testUnavailableExceptionRetries

---

sdks/java/io/google-cloud-platform/build.gradle

This should only be run in PostCommit_Java_Dataflow. …

[BEAM-14149] Disable BigQueryIOStorageWriteIT for general Java post-commit

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineOptions.java
sdks/java/container/Dockerfile
sdks/java/container/boot.go
sdks/java/container/common.gradle
sdks/java/container/java17/option-jamm.json
sdks/java/core/src/main/java/org/apache/beam/sdk/options/SdkHarnessOptions.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/Caches.java

Changes:
Add JDK add-open flag to pipeline options
Add ability to pass in json files to update java args, properties and classpath
Add jamm java args to boot script from json file
Tested:
Ran integration tests that uses boot script for Java 8/17
Docker logs from https://ci-beam.apache.org/job/beam_LoadTests_Java_CoGBK_Dataflow_V2_Batch_Java17_PR/6 includes the new jamm options in the execution
https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22dataflow_step%22%0Aresource.labels.job_id%3D%222022-03-22_14_23_07-6960246593216693989%22%0Alog_name%3D%22projects%2Fapache-beam-testing%2Flogs%2Fdataflow.googleapis.com%252Fdocker%22%0A%22jamm%22;timeRange=2022-03-22T21:23:07.646Z%2F2022-03-22T21:29:54.883Z;cursorTimestamp=2022-03-22T21:25:05.743895120Z?project=apache-beam-testing …

[BEAM-13695] Add option to add-open flags for Java container

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisReader.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisSource.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/SimplifiedKinesisClient.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/SimplifiedKinesisClientTest.java

Close AWS clients properly in KinesisSource. 
Additionally using lazy init for AWS clients to avoid unnecessary allocations for some use cases, e.g. for splitting (doesn't require cloudwatch). …

[BEAM-13232] Close clients properly in KinesisSource.

---

website/www/site/assets/scss/_page-nav.scss
website/www/site/data/en/community_list.yaml
website/www/site/layouts/community/baseof.html

[BEAM-13977]
- remove section with "send feedback" …

[BEAM-13977] [Website] Update Community landing page

---

website/www/site/content/en/community/contact-us.md
website/www/site/data/en/contact_us.yaml

[BEAM-13979]
- Mailing list, what are they, and how they work (update text, add links)
- Useful Tips for Sending Emails (update text, remove tip 3) …

[BEAM-13979] [Website] Update Community/Contact us page

---

sdks/go/pkg/beam/core/util/jsonx/jsonx_test.go

Adds some brief unit test cases to the jsonx package. Largely just ensures that inputs and outputs are equal and follow expected behavior.  …

[BEAM-13889] Add test cases to jsonx package

---

sdks/go/container/boot.go

Clean up an unreachable return value in getGoWorkerArtifactName() in boot.go. …

Remove unreachable code in container/boot.go

---

sdks/python/apache_beam/typehints/decorators.py

Minor: Make IOTypeHints a real NamedTuple

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/join/CoGbkResult.java

Ensure this is invoked in case asserts are not enabled in the worker. …

[BEAM-14171] More explicit asserts in CoGBKResult.

---

.test-infra/jenkins/job_PostCommit_Java_Examples_Direct.groovy
.test-infra/jenkins/job_PostCommit_Java_Examples_Flink.groovy
.test-infra/jenkins/job_PostCommit_Java_Examples_Spark.groovy

[BEAM-12572] Change java examples jobs to run periodically

---

.test-infra/jenkins/job_PostCommit_Java_Examples_Direct.groovy
.test-infra/jenkins/job_PostCommit_Java_Examples_Flink.groovy
.test-infra/jenkins/job_PostCommit_Java_Examples_Spark.groovy

[DO NOT MERGE] Run seed job for PR 17179

---

sdks/java/io/pulsar/build.gradle
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/PulsarIO.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/PulsarIOUtils.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/PulsarMessage.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/PulsarMessageCoder.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/PulsarSourceDescriptor.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFn.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/WriteToPulsarDoFn.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/package-info.java
sdks/java/io/pulsar/src/test/java/org/apache/beam/sdk/io/pulsar/FakeMessage.java
sdks/java/io/pulsar/src/test/java/org/apache/beam/sdk/io/pulsar/FakePulsarClient.java
sdks/java/io/pulsar/src/test/java/org/apache/beam/sdk/io/pulsar/FakePulsarReader.java
sdks/java/io/pulsar/src/test/java/org/apache/beam/sdk/io/pulsar/PulsarIOTest.java
sdks/java/io/pulsar/src/test/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFnTest.java
settings.gradle.kts

PulsarIO Connector first version
Contains:
- Pulsar Reader (SDF based)
- Pulsar Writer 
- Pulsar Transform
- Unit tests
- IT tests with Pulsar container
<table>
<thead>
<tr>
<th>Lang</th>
<th>ULR</th>
<th>Flink</th>
<th>Samza</th>
<th>Spark</th>
</tr>
</thead>
<tbody>
<tr>
<td>Go</td>
<td>---</td>
<td>
<a …

[BEAM-8218] PulsarIO Connector 

---

sdks/python/apache_beam/transforms/util.py

Fixes iterable_input_value_types to be typedefed to iterable instead of list.
I don't anticipate any backward compatibility issues as this is more permissive …

[BEAM-14084] iterable_input_value_types changed from list to iterable

---

sdks/python/apache_beam/testing/benchmarks/chicago_taxi/trainer/model.py
sdks/python/apache_beam/testing/benchmarks/chicago_taxi/trainer/task.py

Explicitly import estimator from tensorflow instead of accessing it via tf.estimator and depend on the tensorflow estimator target.
[![Build …

Explicitly import estimator from tensorflow 

---

website/www/site/content/en/blog/beam-2.36.0.md

Minor: Add warning about pubsub client to Beam 2.36.0 blog

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java

Follow-up fix for https://github.com/apache/beam/pull/17121 …

[BEAM-14177] Fix GBK re-iteration caching for portable runners.

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java

[cherry-pick][release-2.38.0][BEAM-14177] Fix GBK re-iteration caching for portable runners.

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py

[BEAM-14163] Fix typo in single core per container logic.

---

.github/workflows/playground_deploy_examples.yml
playground/infrastructure/checker.py

[BEAM-14140]
Add condition to check if it is needed to run CI/CD step …

[BEAM-14140][Playground] Fix Deploy examples CI to run only on changed examples

---

playground/backend/internal/setup_tools/builder/setup_builder_test.go
playground/backend/internal/setup_tools/life_cycle/life_cycle_setuper.go
playground/backend/internal/setup_tools/life_cycle/life_cycle_setuper_test.go

[[BEAM-13880]](https://issues.apache.org/jira/browse/BEAM-13880)
Add unit tests to increase test coverage for the setup_tools package.
[![Build …

[BEAM-13880] [Playground] Increase test coverage for the setup_tools package

---

playground/backend/internal/executors/executor_builder_test.go
playground/backend/internal/executors/executor_test.go

[[BEAM-13877]](https://issues.apache.org/jira/browse/BEAM-13877)
Add unit tests to increase test coverage for the executors package.
[![Build …

[BEAM-13877] [Playground] Increase test coverage for the executors package

---

sdks/python/apache_beam/io/gcp/bigquery.py

Adding `launchesBigQueryJobs` to the `display_data` used in the Read API Source. …

[BEAM-10917] Update display data in BigQuery Read API Source.

---

runners/samza/src/main/java/org/apache/beam/runners/samza/SamzaJobInvoker.java

Add protected constructor for SamzaJobInvoker so it can be extended as parent class. …

[BEAM-14200] Improve SamzaJobInvoker extensibility

---

sdks/go/pkg/beam/io/datastoreio/datastore.go
sdks/go/pkg/beam/io/datastoreio/datastore_test.go

* Add unit tests for datastoreio.Read
* Modify existing test case to increase coverage …

[BEAM-13918] Increase datastoreio go sdk unit test coverage

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/options/pipeline_options_validator.py
sdks/python/apache_beam/options/pipeline_options_validator_test.py

Explicitly disable prebuild_sdk_container_base_image flag, in case it was recommended to/discovered by customers using old SDKs with custom containers. …

Explicitly disallow the removed option prebuild_sdk_container_base_image.

---

sdks/python/apache_beam/transforms/util.py

Revert "[BEAM-14084] iterable_input_value_types changed from list to iterable"

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/options/pipeline_options_validator.py
sdks/python/apache_beam/options/pipeline_options_validator_test.py

Cherry-picks https://github.com/apache/beam/pull/17204 …

[release-2.38.0] [BEAM-14201] Ensure the removed option prebuild_sdk_container_base_image not used on its own.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java

(cherry picked from commit e7d752522512320cadf5a78817e0fff0408b6add) …

[cherry-pick][release-2.38.0][BEAM-14181] Make sure to evict connections from cache after closing them

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/dataflow/dataflow_job_service.py
sdks/python/apache_beam/runners/dataflow/dataflow_job_service_test.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/portability/local_job_service.py
sdks/python/apache_beam/runners/portability/portable_runner.py
sdks/python/scripts/generate_pydoc.sh

Add a portable job server that proxies the Dataflow backend.

---

sdks/python/apache_beam/coders/row_coder.py
sdks/python/apache_beam/coders/row_coder_test.py

This matches what we do to send schema metadata in Java …

[BEAM-14190] Python sends dataflow schema field for pre-portability pipelines

---

website/www/site/assets/scss/_playground.sass
website/www/site/layouts/index.html

[BEAM-14164]
- change padding in css
- change class in index.html from playground to playground-section …

[BEAM-14164] [Website] change styles

---

website/www/site/content/en/contribute/release-guide.md

[BEAM-13951] Update release guide with pointers on updating mass_comment.py

---

sdks/java/extensions/sql/hcatalog/build.gradle
sdks/java/extensions/sql/hcatalog/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/hcatalog/HCatalogTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/schema/BeamPCollectionTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/BaseBeamTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/bigtable/BigtableTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/parquet/ParquetTable.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamEnumerableConverterTest.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamSideInputLookupJoinRelTest.java

Fixes a build break.
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distributio …

[BEAM-13741] Remove forced calcite dependency from BaseBeamTable

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java

Cherry-picking #17228
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distributi …

[cherry-pick][release-2.38.0][BEAM-14179] Fix possibly null value

---

sdks/python/apache_beam/io/gcp/bigquery_tools.py

This API had been misused. The API actually provides an `int` directly.
See 1.xx: https://googleapis.dev/python/google-api-core/1.28.0/exceptions.html#google.api_core.exceptions.GoogleAPICallError
See latest: https://googleapis.dev/python/google-api-core/latest/exceptions.html#google.api_core.exceptions.GoogleAPICallError
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/mas …

Fix mishandling of API with BQIO

---

CHANGES.md
sdks/python/apache_beam/runners/interactive/README.md
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/README.md

Updates relevant documentation with all merged changes implementing the Flink on Dataproc project. …

[BEAM-14221] Update documentation with Flink on Dataproc features

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImplTest.java

[BEAM-14133] Fix potential NPE in BigQueryServicesImpl.getErrorInfo

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/ExternalPythonTransform.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/ExternalPythonTransformTest.java

Updates the API so that users can just specify arguments and/or keyword arguments instead of Row objects.
Doc: https://docs.google.com/document/d/164rn4otqtQA-8QoLlaoGunUDjLSBBvS2DuR0bn344MQ/edit …

[BEAM-14143] Simplifies the ExternalPythonTransform API

---

sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py

Ideally we would not log these in the first place, but this is an easy hack.
R: @kileys  …

Add self-descriptive message for expected errors.

---

sdks/go/pkg/beam/core/typex/special.go

Fix fmt break that was merged in PR #16923 …

Fix go fmt break in core/typex/special.go

---

website/www/site/content/en/documentation/runners/spark.md

[BEAM-8970] Add docs to run wordcount example on portable Spark Runner

---

website/www/site/content/en/documentation/sdks/go-cross-compilation.md
website/www/site/content/en/documentation/sdks/go.md
website/www/site/layouts/partials/section-menu/en/sdks.html

Add explainer page about how being a statically compiled language affects the Go SDK for pipeline execution.
Staging page: http://apache-beam-website-pull-requests.storage.googleapis.com/17256/documentation/sdks/go-cross-compilation/index.html …

[BEAM-5436] Add doc page on Go cross compilation.

---

scripts/ci/pr-bot/processNewPrs.ts

Right now, all reviews are counted as approvals, even just comments which leads to the bot sometimes triggering early. …

Pr-bot Don't count all reviews as approvals

---

.test-infra/jenkins/job_PostCommit_Python_MongoDBIO_Load_Test.groovy

[BEAM-9649] Add region option to Mongo Dataflow test.

---

runners/flink/job-server/flink_job_server.gradle

[BEAM-13952] Sickbay testAfterProcessingTimeContinuationTriggerUsingState

---

website/www/site/content/en/contribute/_index.md

* Fix markdown indent issue in Development Setup section
See https://beam.apache.org/contribute/#development-setup …

[Website] Contribution guide page indent bug fix

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadIT.java

Cloud spanner backend recently changed the table catalog field to return null instead of databaseId. Update the query in SpannerReadIT.testReadAllRecordsInDb to fix the issue. …

[BEAM-14222] Fix the error of SpannerReadIT

---

playground/frontend/web/index.html

I updated meta tags to improve playground SEO. …

[Playground] add meta tags

---

sdks/go/pkg/beam/core/graph/coder/coder.go
sdks/go/pkg/beam/core/runtime/harness/worker_status.go
sdks/go/pkg/beam/core/runtime/harness/worker_status_test.go
sdks/go/pkg/beam/core/typex/special.go

Small fixes for golint and godeprecated issues in Go SDK. …

fixes golint and deprecated issues in recent Go SDK import

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/runtime/harness/logging.go

Replace use of the deprecated ptypes package in graphx/translate.go and harness/logging.go in favor of dealing with the known proto type directly as recommended. …

[BEAM-14266] Replace deprecated ptypes package uses

---

sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/SnowflakeIO.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/crosslanguage/SnowflakeTransformRegistrar.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/crosslanguage/WriteBuilder.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/data/SnowflakeTableSchema.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/services/SnowflakeBatchServiceConfig.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/services/SnowflakeBatchServiceImpl.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/services/SnowflakeServices.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/services/SnowflakeServicesImpl.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/services/SnowflakeStreamingServiceConfig.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/services/SnowflakeStreamingServiceImpl.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/FakeSnowflakeBatchServiceImpl.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/FakeSnowflakeServicesImpl.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/FakeSnowflakeStreamingServiceImpl.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/TestUtils.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/data/SnowflakeDataTypeValidTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/read/SnowflakeIOReadTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/write/CreateDispositionTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/write/QueryDispositionLocationTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/write/SchemaDispositionTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/write/SnowflakeIOWriteTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/write/StreamingWriteTest.java

Fixed warnings found by error checker or JetBrains IDE.
The least obvious might be the changes to the `SnowflakeService` interface, which has now become `SnowflakeService[s]`, but I had to do that because `SnowflakeService` was a generic class, which made it difficult to fix rawtypes warnings and made the code overly complicated.
R: @pabloem @TheNeuralBit …

[BEAM-11936] Fix rawtypes warnings in SnowflakeIO

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PTransformFunctionRegistry.java

[BEAM-13015] Lookup the container for the step once when registering instead of on each execution.

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineDebugOptions.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/status/JfrzServlet.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/status/WorkerStatusPages.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/JfrInterop.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/MemoryMonitor.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/MemoryMonitorTest.java

This has been incredibly helpful for debugging performance issues (specifically GC related) in jobs.  When GC thrashing is detected, we now record a JFR profile (for a duration set by `--jfrRecordingDurationSec`, 60 seconds by default) and upload it to GCS (to the same path as set by `--saveHeapDumpsToGcsPath`).
Again not sure who to get to review this, @lukecwik maybe you or you can pass it off to someone else?
Also, side note, it looks like this class also now exists in the FnHarness code too. I didn't update it there, but would be happy to integrate these changes there in another review. …

[BEAM-14144] Record JFR profiles when GC thrashing is detected

---

sdks/go/pkg/beam/core/runtime/graphx/cogbk_test.go

Adds unit tests for graphx/cogbk.co, making sure that the composed union coders are correct.  …

[BEAM-13901] Add unit tests for graphx/cogbk.go

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

We can set this property for all Dataflow jobs now. …

[BEAM-14009] Sets 'sdk_harness_container_images' property for all Dataflow jobs - Python SDK

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java

We can set this property for all Dataflow jobs now. …

[BEAM-14009] Sets 'sdk_harness_container_images' property for all Dataflow jobs - Java SDK

---

sdks/go/pkg/beam/core/runtime/pipelinex/replace.go
sdks/go/pkg/beam/core/runtime/pipelinex/util.go
sdks/go/pkg/beam/core/runtime/pipelinex/util_test.go

Cleans up staticcheck warnings in the pipelinex package, largely simplifying existing code. Also removes an unused test helper function. 
[![Build …

[BEAM-14274] Fix staticcheck warnings in pipelinex

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update python beam-master container image. 

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

[BEAM-13767] Remove eclipse plugin as it generates a lot of unused tasks

---

.test-infra/jenkins/job_PreCommit_Java.groovy
.test-infra/jenkins/job_PreCommit_SQL.groovy
.test-infra/jenkins/job_PreCommit_SQL_Java11.groovy
.test-infra/jenkins/job_PreCommit_SQL_Java17.groovy
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/Dummy.java

[BEAM-11714] Spotbugs print errors to  Jenkins UI

---

.test-infra/jenkins/PrecommitJobBuilder.groovy

The default setting runs each job every 6 hours. …

Nit: correct description for precommit cron jobs.

---

sdks/python/apache_beam/runners/interactive/sql/beam_sql_magics.py
sdks/python/apache_beam/runners/interactive/sql/utils.py
sdks/python/apache_beam/runners/interactive/sql/utils_test.py

Printed more detailed stack trace rather than a simple error message
when an error occurs.
Added missing return or raise when beam_sql fails due to an excepted
error so that the the UX during such failures is more graceful.
Fixed a bug when pretty formatting a NamedTuple with an inner attribute
whose type has no __name__ attribute and fall back to its repr(). …

[BEAM-10708] Updated beam_sql error message

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test.py

Update nullable coder to try and generate a deterministic value coder when it is requested as a deterministic coder. …

[BEAM-14281] add as_deterministic_coder to nullable coder

---

sdks/python/apache_beam/utils/shared.py

Cleanup docs on Shared.

---

website/www/site/content/en/get-started/from-spark.md

* Fix the example to actually do what it says it does.
* Give real reason for side input differences.
* Some wordsmithing. …

Improvements to Beam/Spark quickstart.

---

runners/google-cloud-dataflow-java/build.gradle

[BEAM-14263] Disable BigQueryIOStorageWriteIT for Runner v2 test suite

---

sdks/python/apache_beam/io/gcp/datastore/v1new/datastoreio.py
sdks/python/apache_beam/io/gcp/datastore/v1new/datastoreio_test.py
sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

Not re-raising these errors could result in data correctness issues for downstream consumers. …

[BEAM-14282] Re-raise exceptions swallowed in several Python I/O connectors

---

sdks/go/pkg/beam/util/pubsubx/pubsub.go
sdks/go/pkg/beam/util/pubsubx/pubsub_test.go

Use the pstest fake pubsub server to test the pubsubx package.
Adds unit test coverage, and does small refactors to allow testing of the existing helper methods with the fake client. …

[BEAM-13898] Add tests to the pubsubx package.

---

sdks/go/pkg/beam/io/avroio/avroio_test.go
sdks/go/pkg/beam/io/databaseio/util_test.go
sdks/go/pkg/beam/io/filesystem/util_test.go
sdks/go/pkg/beam/io/rtrackers/offsetrange/offsetrange.go
sdks/go/pkg/beam/io/synthetic/source.go
sdks/go/pkg/beam/io/synthetic/step.go
sdks/go/pkg/beam/io/textio/textio_test.go

Address staticcheck warnings in the io packages, largely removing unused variables and cleaning up extra boolean comparisons.  …

[BEAM-14285] Clean up Staticcheck Warnings in io packages

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/IsmReaderImpl.java

This PR has two changes:
1. Fix NullPointerException and IllegalStateException in BEAM-14187.
2. Add more condition check for ISM data integrity. …

[BEAM-14187] Fix concurrency issue in IsmReaderImpl

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/AutoValueUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ByteBuddyUtils.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/AutoValueSchemaTest.java

This supports AutoValue nesting, including Memoized. …

[BEAM-13151] Support multiple layers of AutoValue nesting

---

sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/SnowflakeIO.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/DataSourceConfigurationTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/read/SnowflakeIOReadTest.java

[BEAM-14215] Improve argument validation in SnowflakeIO

---

.test-infra/jenkins/job_PreCommit_Kotlin_Examples.groovy

[BEAM-14013] Add PreCommit Kotlin examples Jenkins Job

---

.test-infra/jenkins/job_PreCommit_Kotlin_Examples.groovy

[DO NOT MERGE] Seed job for BEAM-14013 Add PreCommit Kotlin examples Jenkins Job

---

release/go-licenses/Dockerfile

Cherry-pick of #17343
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distributi …

[cherry-pick][release-2.38.0][BEAM-13538][BEAM-14296] Workaround to fix go-licenses crash.

---

sdks/python/apache_beam/io/gcp/datastore/v1new/datastoreio.py
sdks/python/apache_beam/io/gcp/datastore/v1new/datastoreio_test.py
sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

This cherry-picks https://github.com/apache/beam/pull/17329 to the 2.38.0 release branch. …

[cherry-pick][release-2.38.0][BEAM-14282] Re-raise exceptions swallowed in several Python I/O connectors

---

sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/read/SnowflakeIOReadTest.java

[BEAM-14300] Fix Java precommit failure

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/GrpcWindmillServer.java

This reverts commit 8ae7628b181e19fe126bafef3d9f842245d28d35 (see #17004).  …

[BEAM-14116] Rollback "Chunk commit requests dynamically (#17004)"

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/External.java

We can't assume that any expansion service resolves any artifact information. For example, Java artifacts returned from Java expansion service cannot be resolved (+downloaded) with Python expansion service. Also, one Python expansion service may returns Python artifacts which are unknown to other Python expansion service. We need to skip pre-existing artifacts and only resolves artifacts in new environments from the expansion service at the moment. …

[BEAM-14232] Only resolve artifacts in expanded environments for Java External Transform

---

sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download.go
sdks/go/pkg/beam/core/runtime/xlangx/registry.go

This fixes 2 small style issues:
1) We should prefer uppercase initials - https://github.com/golang/go/wiki/CodeReviewComments#initialisms - this is also consistent with the rest of the file
2) If we're returning a type/using it as a parameter in an exported function, it is best to export the type as well to make it easier to use. …

Fix a couple style issues

---

sdks/go/pkg/beam/core/graph/coder/map.go
sdks/go/pkg/beam/core/graph/coder/map_test.go
sdks/go/pkg/beam/core/graph/coder/registry_test.go
sdks/go/pkg/beam/core/graph/coder/row_test.go

Remove unused fields/variables and simplify some logic. …

[BEAM-14287] Clean up staticcheck warnings in graph/coder

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
sdks/python/apache_beam/runners/portability/local_job_service.py

There were a couple of Python-on-Python assumptions that I uncovered when trying to run other languages.  …

Improvements to dataflow job service for non-Python jobs.

---

sdks/go/pkg/beam/core/graph/edge.go
sdks/go/pkg/beam/core/runtime/exec/datasource.go
sdks/go/pkg/beam/core/runtime/exec/fn.go
sdks/go/pkg/beam/core/runtime/exec/fn_arity.go
sdks/go/pkg/beam/core/runtime/exec/fn_arity.tmpl
sdks/go/pkg/beam/core/runtime/exec/fn_test.go
sdks/go/pkg/beam/core/runtime/exec/fullvalue.go
sdks/go/pkg/beam/core/runtime/exec/pardo.go
sdks/go/pkg/beam/core/runtime/exec/sdf.go
sdks/go/pkg/beam/core/util/reflectx/calls.go
sdks/go/pkg/beam/core/util/reflectx/calls.tmpl

Pipes returned ProcessContinuations from the DoFn level up to the execution plan's DataSource level. This involves changes to two .tmpl files and the generated code they produce. Users are still not allowed to return ProcessContinuations as written.
Design Doc: https://docs.google.com/document/d/1_JbzjY9JR07ZK5v7PcZevUfzHPsqwzfV7W6AouNpMPk/edit?usp=sharing …

[BEAM-11104] Pipe Continuation to DataSource level

---

sdks/python/apache_beam/io/iobase.py
sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py

Respect output coder for TextIO.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/extensions/sql/build.gradle
sdks/java/io/google-cloud-platform/build.gradle

Upgrading bigtable-client-core to the latest and explicitly declaring a newer version of google-cloud-bigquery (a dependency of bigtable-client-core).
com.google.cloud.bigtable:bigtable-client-core is a library
for an implementation deatil of bigtable access. For Java 7
support, the library declares old version of google-cloud-bigtable
library. However the old version does not work with latest GAX
library. Beam users would face AbstractMethodError.
By explicitly declaring google-cloud-bigtable at this module, we
ensure that Beam users get newer version of google-cloud-bigtable
that is compatible with latest GAX library. …

[BEAM-8691] Declare newer google-cloud-bigtable explicitly

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Moving the semaphore aquire to outside the runnable, the tasks now wait before
getting submitted to the executor and reuse existing threads. …

[BEAM-14283] BigQueryServicesImpl: reduce number of threads spawned by BoundedExecutorService

---

examples/java/src/main/java/org/apache/beam/examples/snippets/Snippets.java

[BEAM-14307] Fix Slow Side input pattern bug in sample …

[BEAM-14307] Fix Slow Side input pattern bug in sample

---

sdks/go/pkg/beam/core/graph/fn.go
sdks/go/pkg/beam/core/runtime/genx/genx_test.go

Removes an unnecessary comparison to a boolean constant, simplifies a boolean return. …

[BEAM-14302] Simplify bools in fn.go, genx_test.go

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryQueryHelper.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryQuerySourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java

I found some DatasetService local variables that are not closed.  This can cause the harmless error logs in BEAM-12356. …

[BEAM-12356] Close DatasetService leak as local variables

---

sdks/python/apache_beam/ml/inference/api.py

Refactor the `api.py` file to call `base.RunInference` and refactor it to be more like a PTransform. …

[BEAM-14305] Add call to RunInference in API

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOMetadata.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Populate actual dataflow job id to bigquery write trace id

---

sdks/python/apache_beam/examples/dataframe/flight_delays_it_test.py

[BEAM-14336] Sickbay flight delays test - dataset seems to be missing

---

CHANGES.md

For @youngoli 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20an …

[BEAM-1857] CHANGES.md entry for 2.38.0

---

sdks/python/apache_beam/runners/interactive/dataproc/dataproc_cluster_manager_test.py
sdks/python/apache_beam/runners/interactive/interactive_environment.py
sdks/python/apache_beam/runners/interactive/interactive_environment_test.py
sdks/python/apache_beam/runners/interactive/interactive_runner.py
sdks/python/apache_beam/runners/interactive/interactive_runner_test.py

Disables the clusters cleanup to avoid unimplemented errors when tests
run in parallel racing the global state without necessary mocking.
[![Build …

[BEAM-14330] Temporarily disable the clusters auto-cleanup

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/ReadWriteIT.java

This has been a hard failure for 4 weeks. …

[BEAM-14253] Disable broken test pending Dataflow fix

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

[BEAM-14341]: BigQuery Storage Connector trace id population missing bracket

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.38.0.md
website/www/site/content/en/get-started/downloads.md

Update Beam website to release 2.38.0

---

sdks/python/apache_beam/transforms/batch_dofn_test.py
sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/typehints/batch.py
sdks/python/apache_beam/typehints/batch_test.py

Split from #17175. This includes just the API, not the worker changes necessary to actually execute a Batched DoFn.
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Asch …

[BEAM-14213] Add API and construction time validation for Batched DoFns

---

.test-infra/jenkins/job_PreCommit_CommunityMetrics.groovy
.test-infra/metrics/build.gradle

* Created a getClusterCredentials and removeKubeConfig tasks to get the credentials for the metrics cluster and remove the config every time the test is triggered. 
* Updated `--dry-run=client` to remove the warning for the deprecated usage.  …

[BEAM-14017] beam_PreCommit_CommunityMetrics_Cron test failing

---

sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py

[BEAM-10917] Annotating Read API tests.

---

CHANGES.md
website/www/site/content/en/blog/beam-2.29.0.md
website/www/site/content/en/blog/beam-a-look-back.md
website/www/site/content/en/blog/beam-summit-digital-2020.md
website/www/site/content/en/blog/beam-summit-europe-2019.md
website/www/site/content/en/blog/review-input-streaming-connectors.md
website/www/site/content/en/contribute/become-a-committer.md
website/www/site/content/en/contribute/release-guide.md
website/www/site/content/en/documentation/io/built-in/google-bigquery.md
website/www/site/content/en/documentation/io/testing.md
website/www/site/content/en/documentation/programming-guide.md
website/www/site/content/en/documentation/resources/learning-resources.md
website/www/site/content/en/documentation/runners/direct.md
website/www/site/content/en/documentation/runners/jstorm.md
website/www/site/content/en/documentation/runtime/environments.md
website/www/site/content/en/documentation/sdks/go.md

Fixing the broken links in the documentation identified in [BEAM-13582](https://issues.apache.org/jira/browse/BEAM-13582) …

BEAM-13582 Fixing broken links in the documentation

---

runners/spark/build.gradle
runners/spark/src/main/java/org/apache/beam/runners/spark/stateful/SparkTimerInternals.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/AbstractTranslationContext.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/CreatePCollectionViewTranslatorBatch.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/FlattenTranslatorBatch.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ParDoTranslatorBatch.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ReadSourceTranslatorBatch.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ReshuffleTranslatorBatch.java
runners/spark/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/streaming/ReadSourceTranslatorStreaming.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/GroupNonMergingWindowsFunctions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkBatchPortablePipelineTranslator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkExecutableStageFunction.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/TransformTranslator.java
runners/spark/src/test/java/org/apache/beam/runners/spark/GlobalWatermarkHolderTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/aggregators/metrics/sink/SparkMetricsSinkTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/TransformTranslatorTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/streaming/CreateStreamTest.java

Add spotless config for the shared Spark sources similar to Flink.
All other changes are just formatting ... …

[BEAM-14335] Spotless Spark sources

---

sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/SnowflakeIO.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/DataSourceConfigurationTest.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/read/SnowflakeIOReadTest.java

@reuvenlax commented that in some cases this change can cause regressions, so I revert it
R: @reuvenlax @pabloem @aaltay  …

Revert "Merge pull request #17223 from [BEAM-14215] Improve argument validation in SnowflakeIO"

---

sdks/python/apache_beam/runners/portability/fn_api_runner/execution.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py

The input buffer type can be either ListBuffer or GroupingBuffer, using None instead so that the actual Buffer can be replaced with first input later. …

[BEAM-14342] Fix wrong default buffer type in fn_runner

---

buildSrc/src/main/groovy/org/apache/beam/gradle/GrpcVendoring_1_43_2.groovy
runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/legacy-worker/build.gradle
sdks/java/io/google-cloud-platform/build.gradle

Updates opencensus-api dependency to the latest version - 0.31.0

[BEAM-14344] bumps opencensus-api

---

sdks/go/pkg/beam/core/graph/coder/panes.go
sdks/go/pkg/beam/core/graph/coder/panes_test.go

Adds unit testing to pane coder and makes tweaks to match the spec described in the runner api (https://github.com/apache/beam/blob/master/model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto#L922) …

[BEAM-14306] Add unit testing to pane coder

---

CHANGES.md

[BEAM-13657] Add python 3.6 update to CHANGES.md

---

sdks/java/io/google-cloud-platform/build.gradle

The previous change (https://github.com/apache/beam/pull/17375) didn't declare the dependency properly.
CC: @emilymye  …

[BEAM-8127] The GCP module to declare google-cloud-bigtable

---

sdks/go/pkg/beam/core/util/ioutilx/read.go

Ignore the staticcheck warning SA4016 for the noescape() function, as we use the function to hide a pointer from escape analysis.  …

[BEAM-14301] Add lint:ignore to noescape() func

---

sdks/go/pkg/beam/core/metrics/metrics.go

Replaces the struct literal construction of the QueryResults struct with a conversion from Results to QueryResults. The structs have an identical composition. …

[BEAM-14327] Convert Results to QueryResults directly

---

sdks/go/pkg/beam/core/graph/fn.go

Remove comparison to a boolean constant in a logical check.  …

[BEAM-14302] Simplify boolean check in fn.go

---

sdks/go.mod
sdks/go.sum
sdks/go/test/integration/io/xlang/jdbc/jdbc_test.go

Add retries to connect to a testcontainer. Without retries, `TestJDBCIO_BasicReadWrite` is a flaky test as it depends on the start of testcontainer. Python uses 3, I added 5 for Go SDK just in case. …

[BEAM-14358] add retry to connect to testcontainer

---

website/www/site/content/en/documentation/io/built-in/google-bigquery.md

On the Google BigQuery I/O connector page, added [documentation for the BQ Storage Write API](http://apache-beam-website-pull-requests.storage.googleapis.com/17391/documentation/io/built-in/google-bigquery/index.html#storage-write-api).
@chamikaramj 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-in …

[BEAM-13953] added documentation for BQ Storage Write API

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOJsonIT.java

BigQueryIOJsonIT.java is failing due to a missing pipeline option. This PR is for a small fix to get it running properly again.

[BEAM-14356] fixing a postcommit test

---

website/www/site/content/en/documentation/programming-guide.md

Minor addition to assist new users with a GroupByKey example in Java. Specifically:
Added the following content to provide a Java example at the end of section 4.2.2. GroupByKey.
Using <span class="language-java">`GroupByKey`</span> is straightforward:
{{< highlight java >}}
// The input PCollection.
PCollection<KV<String, String>> mapped = ...;
// Apply GroupByKey to the PCollection mapped.
// Save the result as the PCollection reduced.
PCollection<KV<String, Iterable<String>>> reduced = 
mapped.apply(GroupByKey.<String, String>create());
{{< /highlight >}}
R: @TheNeuralBit - could you take a look at this simple change - or recommend a reviewer who might? Thanks!  …

[BEAM-14320] Update programming-guide w/Java GroupByKey example

---

sdks/python/apache_beam/ml/inference/pytorch.py

Change return type for PytorchInferenceRunner

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/ExternalPythonTransform.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/ExternalPythonTransformTest.java

[BEAM-14343] Allow expansion service override in ExternalPythonTransform

---

sdks/python/apache_beam/ml/inference/api.py

Remove redundant decorator `@beam.ptransform_fn`. Having this in causes some running issues.  …

Remove unnecessary decorator from RunInference interface

---

sdks/go/pkg/beam/core/graph/coder/panes_test.go

bytes.Buffer gives copy by value error on Go SDK import, changed it to pass by reference. …

Fixes copy by value error for bytes.Buffer in Error

---

sdks/go/pkg/beam/artifact/materialize_test.go
sdks/go/pkg/beam/core/funcx/fn_test.go

Adds a linter exemption to fn_test.go since we use improper function signatures as test cases and removes unnecessary blank identifier uses in for loops in materialize_test.go …

[BEAM-14324, BEAM-14325] Staticcheck cleanup in test files

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/HttpHealthcareApiClient.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOSearchIT.java

The .setResourceType(...) behaviour is unintended on the generated client library, and is potentially unstable. …

[BEAM-14280] FhirIO: use .search() or .searchType() instead of SearchResourceRequest.setResourceType()

---

sdks/go/pkg/beam/core/runtime/exec/datasource.go
sdks/go/pkg/beam/core/runtime/exec/plan.go
sdks/go/pkg/beam/core/runtime/harness/harness.go

Adds code to split an SDF that has self-checkpointed and returns the result to the runner. Currently is not run in production, as returning process continuations is not yet enabled. …

[BEAM-11104] Add Checkpointing split to Go SDK

---

.test-infra/jenkins/job_00_seed.groovy
.test-infra/jenkins/job_seed_standalone.groovy

r: @kennknowles 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20 …

Improvement to Seed job configuration so we can launch seed jobs against PRs

---

CHANGES.md
sdks/python/apache_beam/examples/cookbook/coders.py

[BEAM-14351] Inherit from Coder.

---

sdks/java/container/common.gradle

[BEAM-14369] Fix "target/options: no such file or directory" error while building Java container without licenses

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/ChangeStreamMetrics.java

Updates the outdated documentation in the ChangeStreamMetrics.

[BEAM-14381]: update javadocs for ChangeStreamMetrics

---

website/www/site/assets/js/language-switch-v2.js
website/www/site/layouts/community/baseof.html
website/www/site/layouts/contribute/arrow_template.html
website/www/site/layouts/contribute/baseof.html
website/www/site/layouts/documentation/baseof.html
website/www/site/layouts/get-started/baseof.html
website/www/site/layouts/languages/baseof.html
website/www/site/layouts/roadmap/baseof.html
website/www/site/layouts/runners/arrow_template.html
website/www/site/layouts/runners/baseof.html
website/www/site/layouts/runners/capability-template.html
website/www/site/layouts/security/baseof.html

[BEAM-13229]
- change offset to 10px to activate an element via bootstrap's scrollspy library …

[BEAM-13229] [Website] bug side nav

---

sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py

This is useful when various elements have largely disparate weights. …

Add element weighting parameter to BatchElements.

---

sdks/go/pkg/beam/core/runtime/exec/coder_test.go
sdks/go/pkg/beam/core/runtime/exec/fn_test.go

Adds extra cases to existing test suites to catch code that was previously untested. …

[BEAM-14001] Add missing test cases to existing suites in exec package

---

.github/workflows/go_tests.yml
sdks/go/pkg/beam/staticcheck.conf

Adds Staticcheck to Github Actions precommits, adding another check for common issues in Go code. Disables three checks that are usually used by default: SA1019 (deprecation warnings,) U1000 (unused fields, vars, and functions,) and S1021 (merge variable declaration and assignment) with the latter two intended to be re-enabled once their instances are resolved.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md] …

[BEAM-14243] Add staticcheck to Github Actions Precommits

---

sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py

Minor: fix typo in FnApiRunner log statement

---

.github/workflows/java_tests.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

[BEAM-14375] Fix Java Wordcount Dataflow postcommit for Gradle 7.4

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/transforms.py
sdks/python/apache_beam/dataframe/transforms_test.py

This allows expressions of the form `(df - df.min()) / (df.max() - df.min())`. …

[BEAM-14391] Allow arithmetic between deferred scalars.

---

sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/bigquery_tools_test.py
sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

Adding user-agent to GCS client in Python

---

sdks/python/apache_beam/transforms/batch_dofn_test.py
sdks/python/setup.py

The upgraded ipykernel now supports the debugger in Jupyter notebooks. …

[BEAM-12575] Upgraded ipykernel from v5 to v6

---

sdks/python/apache_beam/io/aws/clients/s3/fake_client.py
sdks/python/apache_beam/io/aws/s3filesystem.py
sdks/python/apache_beam/io/aws/s3filesystem_test.py
sdks/python/apache_beam/io/aws/s3io.py
sdks/python/apache_beam/io/aws/s3io_test.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem_test.py
sdks/python/apache_beam/io/azure/blobstorageio.py
sdks/python/apache_beam/io/filesystem.py
sdks/python/apache_beam/io/filesystem_test.py
sdks/python/apache_beam/io/gcp/gcsfilesystem.py
sdks/python/apache_beam/io/gcp/gcsfilesystem_test.py
sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py
sdks/python/apache_beam/io/hadoopfilesystem.py
sdks/python/apache_beam/io/hadoopfilesystem_test.py
sdks/python/apache_beam/io/localfilesystem.py
sdks/python/apache_beam/io/localfilesystem_test.py

* Add last_updated_in_seconds field in FileMetaData and used in match
* Add metadata method for FileSystem implementations …

[BEAM-14314][BEAM-9532] Add last_updated field in filesystem.FileMetaData

---

sdks/java/io/elasticsearch-tests/elasticsearch-tests-5/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-6/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/build.gradle
sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java

Ensure ElasticsearchIO#write output maintains input windows.
Supersedes #17097 …

[BEAM-14064] fix es io windowing

---

sdks/python/apache_beam/runners/interactive/display/display_manager.py
sdks/python/apache_beam/runners/interactive/display/pcoll_visualization.py
sdks/python/apache_beam/runners/interactive/display/pipeline_graph.py
sdks/python/apache_beam/runners/interactive/interactive_environment.py
sdks/python/apache_beam/runners/interactive/utils.py
sdks/python/apache_beam/runners/interactive/utils_test.py
sdks/python/setup.py

Replaced deprecated IPython.core.display package imports with
IPython.display. …

[BEAM-13670] Upgraded ipython from v7 to v8

---

CHANGES.md
sdks/go/pkg/beam/core/funcx/fn.go
sdks/go/pkg/beam/core/funcx/fn_test.go
sdks/go/pkg/beam/core/runtime/exec/fn_test.go

Enables users to return ProcessContinuation interfaces from SDFs, allowing the writing of native streaming DoFns. A small logical change in funcx/fn.go adds stronger enforcement of ordering for ProcessContinuations. Also adds unit test cases that depend on being able to return those continuations for validation and could not be added prior.  …

[BEAM-11104] Enable ProcessContinuation return values, add unit test cases

---

sdks/python/apache_beam/coders/row_coder.py
sdks/python/apache_beam/coders/row_coder_test.py
sdks/python/apache_beam/typehints/schemas.py
sdks/python/apache_beam/typehints/schemas_test.py

[BEAM-14231] Roll-forward #17190 with fixes for flake

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java

Defer this decision to the service rather than the SDK. …

[BEAM-14403] Allow Prime to be used with legacy workers.

---

sdks/python/scripts/generate_pydoc.sh

r: @TheNeuralBit 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%2 …

re-add testing package to pydoc

---

sdks/python/apache_beam/coders/row_coder.py
sdks/python/apache_beam/coders/typecoders.py

Made row coder work with stringified typehint when a
NamedTupleInMainModule is registered with a RowCoder. …

[BEAM-14250] Amended the workaround

---

sdks/go/pkg/beam/core/runtime/exec/datasource.go

Fixed a broken boolean statement that assumed a return of no primary roots was nil, not an empty slice.  …

[BEAM-11104] Fix broken split result validation

---

CHANGES.md
runners/flink/flink_runner.gradle

feat(flink/BEAM-14386): Use flink for scala 2.12
Reviewed-by: @angoenka @mxm @tweise 
Refs: # (pull request) [[BEAM-14386](https://issues.apache.org/jira/browse/BEAM-14386)] (jira) …

[BEAM-14386] [Flink] Support for scala 2.12

---

sdks/python/apache_beam/io/gcp/datastore/v1new/types.py
sdks/python/apache_beam/io/gcp/datastore/v1new/types_test.py

[BEAM-9245] Unable to pull datatore Entity which contains dict properties

---

sdks/python/apache_beam/coders/fast_coders_test.py
sdks/python/apache_beam/coders/typecoders_test.py
sdks/python/apache_beam/runners/common.pxd
sdks/python/apache_beam/runners/common.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/portable_runner_test.py
sdks/python/apache_beam/runners/worker/bundle_processor.py
sdks/python/apache_beam/runners/worker/opcounters.pxd
sdks/python/apache_beam/runners/worker/opcounters.py
sdks/python/apache_beam/runners/worker/operations.pxd
sdks/python/apache_beam/runners/worker/operations.py
sdks/python/apache_beam/transforms/batch_dofn_test.py
sdks/python/apache_beam/transforms/combiners.py
sdks/python/apache_beam/transforms/ptransform_test.py
sdks/python/apache_beam/typehints/batch.py
sdks/python/apache_beam/utils/windowed_value.pxd
sdks/python/apache_beam/utils/windowed_value.py
sdks/python/apache_beam/utils/windowed_value_test.py

[BEAM-14294] Worker changes to support trivial Batched DoFns

---

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperator.java
runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkSavepointTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/ExecutableStageDoFnOperatorTest.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/WindowDoFnOperatorTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

Add test verifying output watermark handling when bundle being processed. …

[BEAM-14196] add test verifying output watermark propagation in bundle

---

CHANGES.md

Move master readme.md to 2.40.0

---

CHANGES.md
sdks/go/pkg/beam/core/funcx/fn.go
sdks/go/pkg/beam/core/funcx/fn_test.go
sdks/go/pkg/beam/core/runtime/exec/fn_test.go

Revert "[BEAM-11104] Enable ProcessContinuation return values, add unit test cases (#17533)"
This reverts commit 6a50718364282b4e0a2fb266a7d6767e50961607.
A bug preventing ProcessContinuations from being used properly was found after branch cut. Reverting this commit prevents this feature from being used with errors at construction time indicating the in-progress nature of the feature and removes reference to its availability in CHANGES.md for 2.39.0. …

[BEAM-14424] Revert commit enabling ProcessContinuation returns in Go

---

sdks/python/apache_beam/io/gcp/bigquery_tools_test.py

r: @angoenka 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and …

Fixing patching error on missing dependencies

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java

* Test reading from bigtable when connection start fails
* Test reading from bigtable when split() fails
* Test reading from bigtable when advance() fails
* Also cleaned up deprecated Builder calls …

[BEAM-14423] Add exception injection tests for BigtableIO read in BigtableIOTest

---

sdks/go/pkg/beam/core/runtime/exec/pardo.go
sdks/go/pkg/beam/core/runtime/exec/pardo_test.go

Fixes issue where a self-checkpointing SDF would return an error because its restriction was not fully processed in the execution. This prevents self-checkpointing SDFs from returning properly.  …

[BEAM-11104] Allow self-checkpointing SDFs to return without finishing their restriction

---

sdks/python/apache_beam/io/gcp/bigquery_test.py
sdks/python/apache_beam/utils/retry.py

r: @chamikaramj @johnjcasey 
**TODO**(@pabloem): Add a test for handling errors in some rows and not others, and tests for different RETRY values for BQIO …

[BEAM-14415] Exception handling tests for BQIO streaming inserts in Python

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java

[BEAM-14423] Add test cases for BigtableIO.BigtableWriterFn fails due to writeRecord

---

.github/codecov.yml
sdks/go/pkg/beam/register/doc.go
sdks/go/pkg/beam/register/emitter.go
sdks/go/pkg/beam/register/example_register_test.go
sdks/go/pkg/beam/register/iter.go
sdks/go/pkg/beam/register/register.go
sdks/go/pkg/beam/register/register.tmpl
sdks/go/pkg/beam/register/register_test.go

Per Robert's suggestion in #17574 `register.DoFnXxY` reads more clearly than `registration.DoFnXxY`. Accordingly, this updates the package to be register instead of registration. …

[BEAM-14347] Rename registration package to register

---

CHANGES.md

Adds self-checkpointing feature call-out to 2.40.0 New Features, removes reference to feature from 2.39.0 to match rollback on release branch.  …

[BEAM-11104] Add Go self-checkpointing to CHANGES.md

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

[BEAM-14096] bump junit-quickcheck to 1.0

---

release/src/main/scripts/mass_comment.py

Remove python 3.6 postcommit from mass_comment.py

---

.github/autolabeler.yml

This will let dependabot changes get tagged correctly …

[BEAM-12526] Correctly route go dependency changes to go label

---

CHANGES.md

This is now complete
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distributio …

[BEAM-14347] Add generic registration feature to CHANGES

---

sdks/python/apache_beam/io/gcp/bigquery_json_it_test.py

Reverts apache/beam#17551
r: @robertwb @TheNeuralBit

Revert "Better test assertion."

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaTransformReadProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaTransformWriteProvider.java

Fix checkstyle issue (guava) that was introduced in #17607  …

[BEAM-14035] Fix checkstyle issue

---

sdks/python/apache_beam/coders/fast_coders_test.py
sdks/python/apache_beam/runners/common.pxd
sdks/python/apache_beam/runners/common.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/portable_runner_test.py
sdks/python/apache_beam/runners/worker/bundle_processor.py
sdks/python/apache_beam/runners/worker/opcounters.pxd
sdks/python/apache_beam/runners/worker/opcounters.py
sdks/python/apache_beam/runners/worker/operations.pxd
sdks/python/apache_beam/runners/worker/operations.py
sdks/python/apache_beam/transforms/batch_dofn_test.py
sdks/python/apache_beam/transforms/combiners.py
sdks/python/apache_beam/transforms/ptransform_test.py
sdks/python/apache_beam/typehints/batch.py
sdks/python/apache_beam/utils/windowed_value.pxd
sdks/python/apache_beam/utils/windowed_value.py
sdks/python/apache_beam/utils/windowed_value_test.py

[release-2.39.0][BEAM-14481] Cherry-pick #17693 to release branch

---

website/www/site/content/en/documentation/io/connectors.md

* Many connectors that are not available have been incorrectly marked as available via x-lang.
* Connectors that are actually available should link to the corresponding SDK-specific wrappers.
* gcsio and s3io should not be identified as top level connectors (users should be using corresponding FileSystem implementations instead).
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/ …

Corrects I/O connectors availability status in Beam Website

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Minor: Bump Dataflow container versions

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
examples/java/build.gradle
examples/java/src/main/java/org/apache/beam/examples/multilang/PythonDataframeWordCount.java
examples/multi-language/build.gradle
examples/multi-language/src/main/java/org/apache/beam/examples/multilanguage/PythonDataframeWordCount.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/BaseExternalTest.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/ValidateRunnerXlangTest.java
runners/direct-java/build.gradle
runners/flink/job-server/flink_job_server.gradle
runners/google-cloud-dataflow-java/build.gradle
runners/samza/job-server/build.gradle
runners/spark/spark_runner.gradle
sdks/java/core/src/main/java/org/apache/beam/sdk/testing/UsesJavaExpansionService.java
sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExternalTest.java
sdks/java/extensions/python/build.gradle
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/DataframeTransformTest.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/io/DataframeTransform.java
sdks/python/apache_beam/io/external/generate_sequence_test.py
sdks/python/apache_beam/io/external/xlang_parquetio_test.py
sdks/python/apache_beam/runners/portability/expansion_service_test.py
sdks/python/apache_beam/transforms/validate_runner_xlang_test.py
sdks/python/scripts/run_expansion_services.sh

* adding `DataframeTransformTest`
* adding `PythonDataframeWordCount` example
* removing `UsesCrossLanguageTransform` annotation, adding `UsesPythonExpansionService`, `UsesJavaExpansionService` annotations …

[BEAM-14471] Adding testcases and examples for xlang Python DataframeTransform

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/PrecombineGroupingTable.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/PrecombineGroupingTableTest.java

[BEAM-14496] Ensure that precombine is inheriting one of the timestamps output values

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java
sdks/python/apache_beam/io/filebasedsink.py
sdks/python/apache_beam/io/iobase.py
sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py

[BEAM-14426] Allow skipping of any output when writing an empty PCollection.

---

website/www/site/content/en/get-started/downloads.md

Fix 2.38.0 download page.

---

sdks/python/apache_beam/io/gcp/bigquery.py

Fix 'RuntimeValueProvider' object has no attribute 'projectId' error in _CustomBigQuerySource.split …

[BEAM-14478] Fix missing 'projectId' attribute error

---

runners/google-cloud-dataflow-java/build.gradle

New images: https://gcr.io/cloud-dataflow/v1beta3/beam-java8-latest-batch:beam-master-20220525
https://gcr.io/cloud-dataflow/v1beta3/beam-java8-latest-streaming:beam-master-20220525 …

Update beam-master version for legacy

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/HealthcareApiClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/HttpHealthcareApiClient.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOLROIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOReadIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOTest.java

Currently, the `FhirIO.Export` transform only supports exports of Fhir resources to Google Cloud Storage. This PR expands its functionality to also be able to export to Google BigQuery by introducing a new method, namely `exportFhirResourceToBigQuery`, to `HealthcareApiClient` and modifying the existing `DoFn` `@ProcessElement` method to call the appropriate export method based on the input URI.
Also, changed the export behavior to not return a `PCollection` of the exported resources and instead output the URI where the store was exported to. @msbukal and I agreed that this would be a better approach because it gives more flexibility to the user by allowing them to chain with transforms tailored for reading resources. …

[BEAM-14451] Support export to BigQuery in FhirIO.Export

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java

[BEAM-14297] add nullable annotations and an integration test

---

sdks/go/examples/snippets/04transforms.go
website/www/site/content/en/documentation/programming-guide.md

Documentation for SDF truncation during drain added in #17432  …

[BEAM-11106] documentation for SDF truncation in Go

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java

r: @johnjcasey 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20a …

[BEAM-13945] Roll forward JSON support for BQIO

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java

[BEAM-14529] Add integer to float64 conversion support

---

sdks/typescript/README.md
sdks/typescript/src/apache_beam/coders/js_coders.ts
sdks/typescript/src/apache_beam/coders/required_coders.ts
sdks/typescript/src/apache_beam/coders/row_coder.ts
sdks/typescript/src/apache_beam/coders/standard_coders.ts
sdks/typescript/src/apache_beam/internal/pipeline.ts
sdks/typescript/src/apache_beam/pvalue.ts
sdks/typescript/src/apache_beam/runners/artifacts.ts
sdks/typescript/src/apache_beam/runners/direct_runner.ts
sdks/typescript/src/apache_beam/runners/portable_runner/runner.ts
sdks/typescript/src/apache_beam/runners/runner.ts
sdks/typescript/src/apache_beam/serialization.ts
sdks/typescript/src/apache_beam/transforms/external.ts
sdks/typescript/src/apache_beam/transforms/flatten.ts
sdks/typescript/src/apache_beam/transforms/group_and_combine.ts
sdks/typescript/src/apache_beam/transforms/internal.ts
sdks/typescript/src/apache_beam/transforms/pardo.ts
sdks/typescript/src/apache_beam/transforms/sql.ts
sdks/typescript/src/apache_beam/transforms/transform.ts
sdks/typescript/src/apache_beam/transforms/window.ts
sdks/typescript/src/apache_beam/transforms/windowings.ts
sdks/typescript/src/apache_beam/utils/service.ts
sdks/typescript/src/apache_beam/worker/operators.ts
sdks/typescript/src/apache_beam/worker/pardo_context.ts
sdks/typescript/src/apache_beam/worker/state.ts
sdks/typescript/src/apache_beam/worker/worker.ts
sdks/typescript/test/standard_coders_test.ts
sdks/typescript/test/worker_test.ts

This updates to prefer === instead of == per https://google.github.io/styleguide/tsguide.html#equality-checks (and our readme)
R: @robertwb  …

Clean up uses of == instead of === in ts sdk

---

README.md

I updated a bunch of docs already and there will be more updates to come, but I missed the Readme and wanted to take care of that immediately.
Issue: #21686  …

Update Jira -> Issues in the Readme

---

.test-infra/jenkins/job_PostCommit_Java_Tpcds_Dataflow.groovy
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/TpcdsOptions.java

[BEAM-12918] Add PostCommit_Java_Tpcds_Dataflow job …

[BEAM-12918] Add PostCommit_Java_Tpcds_Dataflow job

---

sdks/python/apache_beam/io/fileio.py
sdks/python/apache_beam/io/fileio_test.py

Apparently sink_fn does not produce new instance of FileSink as expected. This is due to a bug in the lambda constructed in _get_sink_fn. …

[BEAM-12554] Create new instances of FileSink in sink_fn

---

sdks/python/apache_beam/runners/portability/stager_test.py

[BEAM-13769]Add no_xdist marker for cloudpickle test

---

sdks/python/apache_beam/runners/worker/opcounters.py
sdks/python/apache_beam/runners/worker/opcounters_test.py
sdks/python/apache_beam/transforms/cy_combiners.py
sdks/python/apache_beam/transforms/cy_dataflow_distribution_counter.pxd
sdks/python/apache_beam/transforms/cy_dataflow_distribution_counter.pyx
sdks/python/apache_beam/transforms/py_dataflow_distribution_counter.py
sdks/python/apache_beam/transforms/window.py
sdks/python/apache_beam/typehints/batch.py
sdks/python/apache_beam/typehints/batch_test.py
sdks/python/apache_beam/utils/counters.pxd
sdks/python/apache_beam/utils/counters.py
sdks/python/apache_beam/utils/counters_test.py

Add basic byte size estimation for batches

---

.test-infra/jenkins/PostcommitJobBuilder.groovy
.test-infra/jenkins/job_PerformanceTests_BigQueryIO_Java.groovy
.test-infra/jenkins/job_PerformanceTests_FileBasedIO_IT.groovy
.test-infra/jenkins/job_PerformanceTests_HadoopFormat.groovy
.test-infra/jenkins/job_PerformanceTests_InfluxDBIO_IT.groovy
.test-infra/jenkins/job_PerformanceTests_JDBC.groovy
.test-infra/jenkins/job_PerformanceTests_KafkaIO_IT.groovy
.test-infra/jenkins/job_PerformanceTests_MongoDBIO_IT.groovy
.test-infra/jenkins/job_PerformanceTests_Python.groovy
.test-infra/jenkins/job_PerformanceTests_SQLIO_Java.groovy
.test-infra/jenkins/job_PostCommit_Python_MongoDBIO_Load_Test.groovy

Part of #21824
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20an …

Disable more comments triggers

---

.test-infra/jenkins/PhraseTriggeringPostCommitBuilder.groovy
.test-infra/jenkins/PostcommitJobBuilder.groovy
.test-infra/jenkins/job_PostCommit_Go.groovy
.test-infra/jenkins/job_PostCommit_Java.groovy
.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Python.groovy

Part of #21824
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20an …

Enable phrase trigger for a few post commits

---

runners/core-java/src/main/java/org/apache/beam/runners/core/StatefulDoFnRunner.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java

Fixes [BEAM-14265]
Closes https://github.com/apache/beam/issues/21712. …

[BEAM-14265] Add watermark hold for all timers

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update container names.
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribu …

Bump Python beam-master container

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/AvroIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextIO.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/FileIOTest.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/storage/GcsMatchIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/storage/GcsMatchIT.java

* Added overload versions of continuously for FileIO.match and .matchAll
accepting a third matchUpdatedFiles parameter.
* Watching for both new files and timestamp change of existing files
when matchUpdatedFiles is set as true …

[BEAM-14267] Update watchForNewFiles to allow watching updated files

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSink.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java

This change ensures that FileResultCoders with different destination coder component can be registered individually. Otherwise only the first FileResultCode will be registered successfully and later on be wrongly reused for other FileResultCoder that should use a different destination coder. …

[BEAM-14553] Add destination coder to FileResultCoder components

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerWriteIT.java

Flaky test SpannerWriteIT fails on a stage with anonymous transform names. Name the only anonymous transforms in this test class to help debug the flake. 
Issue #21702
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workf …

Add transform names to help debug flaky test

---

website/www/site/assets/js/language-switch-v2.js
website/www/site/assets/js/page-nav.js
website/www/site/assets/scss/_page-nav.scss
website/www/site/assets/scss/_toggler-nav.scss

NB!!! Merge this PR before https://github.com/apache/beam/pull/21731.
- add refresh to srcoll spy for language-switch-v2.js and page-nav.js
- add scrollTo new position after language switch
- change styles, add & sign to before pseudoselector, put before inside 'a' tag
- change html structure of language-switch buttons, delete 'a' tag, add langSwitch-content class to 'li' tag …

[BEAM-13229] side nav bug fixed

---

website/www/site/data/pipelines.yaml
website/www/site/data/works_with.yaml

- change links in pipelins.yaml and works_with.yaml from staging to actual site
- used relative links paths of absolute ones …

Fix links for pipelines

---

sdks/python/apache_beam/examples/inference/pytorch_image_classification.py

Several parameters should be required to run the pipeline. I added `required=True`. …

Add required=True to Pytorch image classification example

---

sdks/python/apache_beam/io/avroio.py
sdks/python/apache_beam/io/avroio_test.py
sdks/python/apache_beam/io/filebasedsource.py
sdks/python/apache_beam/io/fileio.py
sdks/python/apache_beam/io/fileio_test.py
sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py
sdks/python/apache_beam/transforms/periodicsequence.py
sdks/python/scripts/generate_pydoc.sh

* Update fileio.MatchContinuously to allow reading already read files with a new timestamp
*  Implement textio.ReadAllFromTextContinuously and avroio.ReadAllFilesContinuously …

[BEAM-14315] Match updated files continuously

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadIT.java

Verifies that Exceptions during read should abort the pipeline.
issue #21564
[![Java …

Add Spanner Integration tests to verify exception handling

---

sdks/python/apache_beam/ml/__init__.py
sdks/python/apache_beam/ml/inference/__init__.py
sdks/python/apache_beam/ml/inference/base.py
sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/apache_beam/ml/inference/sklearn_inference.py

Added documentation updates, mostly cleaning the documents for formatting but adding some extra clarifications in module documentation.
[![Build …

Updated documentation for ml.inference docs.

---

sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java

Fixes #21690.  Rather than using `setWindowingStrategyInternal`, use the more common `Window.into` with captured WindowFn from input PCollection.  This is an alternative to https://github.com/apache/beam/pull/21884
I validated in Dataflow where an upgrade to 2.39.0 resulted in the exact behaviour described in #21690, then upgrading the pipeline to the version of code in this PR and the casting error no longer occurred. …

Drops usage of setWindowingStrategyInternal in favour of direct use of WindowFn

---

.github/issue-rules.yml

#21888 introduced a few small issues with the issue-rules config. This fixes those problems
Part of https://github.com/apache/beam/issues/21684 …

Fix a few small config issues

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillTimeUtils.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WindmillTimeUtilsTest.java

This reverts commit 955177b8c38868e3dffad9ab4d7ee31dda06cc92.
This commit, from #21740, appears to be the culprit for failures starting at https://ci-beam.apache.org/view/PostCommit/job/beam_PreCommit_Java_Cron/5560/ …

Revert "convert windmill min timestamp to beam min timestamp"

---

runners/samza/build.gradle

Samza runner is also executing the BoundedReadFromUnboundedSourceTest test.
Adding it to Samza's exclusion list.
Bug reported here [BUG21709](https://github.com/apache/beam/issues/21709) and the CI error is here [Failed BoundedReadFromUnboundedSourceTest.testTimeBound](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/9581/testReport/org.apache.beam.sdk.io/BoundedReadFromUnboundedSourceTest/testTimeBound/)
@kennknowles or @damccorm, could you help me reviewing this?
Thanks!
- [ x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
- [ x] Mention the …

[21709] - Fix for "beam_PostCommit_Java_ValidatesRunner_Samza Failing"

---

examples/java/src/main/java/org/apache/beam/examples/complete/datatokenization/transforms/SerializableFunctions.java
examples/java/src/main/java/org/apache/beam/examples/complete/datatokenization/utils/ErrorConverters.java
examples/java/src/main/java/org/apache/beam/examples/complete/datatokenization/utils/FailsafeElement.java
examples/java/src/main/java/org/apache/beam/examples/complete/datatokenization/utils/FailsafeElementCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/AtomicCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/CoderProviders.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/DefaultCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/NullableCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/StringDelegateCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/SerializableFunctions.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/sqs/SqsMessageCoder.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirSearchParameterCoder.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/HL7v2MessageCoder.java

[BEAM-10496] Eliminate some null errors from core SDK coders

---

sdks/python/apache_beam/ml/inference/base.py
sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/apache_beam/ml/inference/sklearn_inference.py

1. Updates the example usage blocks to exist in a box.
2. Updates notes to be bold (this follows notes in other parts of the doc). 
[![Build …

Update run inference documentation

---

scripts/ci/pr-bot/shared/checks.ts

Right now, if the pr bot encounters skipped checks, it thinks they've failed and it doesn't action (see https://github.com/apache/beam/pull/21921#issuecomment-1158904893). This fixes that issue.
Part of #21417 …

Consider skipped checks successful

---

sdks/python/apache_beam/io/gcp/gcsio_integration_test.py

Unsickbay copy_rewrite_token tests

---

website/www/site/content/en/case-studies/hop.md
website/www/site/content/en/case-studies/paloalto.md
website/www/site/content/en/case-studies/ricardo.md
website/www/site/content/en/case-studies/seznam.md

NB!!! Merge this PR first, before merging https://github.com/apache/beam/pull/21891
- add publishdate attribute to case studies md files (study category: lyft, seznam, ricardo, paloalto, hop). It was done since file layouts\case-studies\list.html uses hugo and ranges throug all case-studies using `ByPublishDate `attribute like this `{{ $pages := .Pages.ByPublishDate.Reverse }}`, but ByPublishDate wasn't located in any case studies md files, so when you add a new case study it takes a place not an order you would expect (freshly added file was shown second, not first or last). To take control over this flow abovementioned case studies md files got publishdate attribute and by that a new added file gets a correct place. …

[Website] add publishdate attribute to case studies frontmatter

---

build.gradle.kts

Fix beam_PostCommit_Java_Sickbay build

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServices.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/CreateTableHelpers.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableSchemaCache.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/testing/FakeDatasetService.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImplTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilTest.java

This setting should help to avoid storage related calculations on the BQ table backend (caused by the default option).  …

Adding the BASIC view setting to getTable request 

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update container tags used by Dataflow runner with unreleased SDKs

---

website/www/site/layouts/index.html

Removing playground from main page due to scrolling

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillTimerInternals.java

* fix no output timestamp case
* revert unnecessary file …

[cherry-pick][release-2.40.0][21941] Fix no output timestamp case

---

.test-infra/jenkins/job_PostCommit_Java_Tpcds_Flink.groovy
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/TpcdsRun.java

Add PostCommit_Java_Tpcds_Flink Jenkins job
https://github.com/apache/beam/issues/21253 …

[BEAM-12918] Add PostCommit_Java_Tpcds_Flink job

---

sdks/python/apache_beam/ml/inference/base.py
sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/scripts/generate_pydoc.sh

Makes the following updates:
1. Update docs of a named tuple. Since standard doc styles doesn't work for a named tuple defined in this way use the __doc__ field.
2. Add docs for optional parameters in pytorch runinference.
3. Change |& to 2>&1 | in doc generation script. This is because older bash versions (common on macs) will fail to generate docs.  See: https://stackoverflow.com/questions/20553916/syntax-error-near-unexpected-token-using …

Update documentations and document generation

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/InsertRetryPolicy.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/InsertRetryPolicyTest.java

[BEAM-14523] Add a retry code to insertall retry policy

---

sdks/go/examples/snippets/04transforms.go
website/www/site/content/en/documentation/programming-guide.md

Fixes #21841
Adds a code snippet for GroupByKey transform for Go SDK in BPG. …

[Go SDK] Adds a snippet for GBK in BPG

---

playground/frontend/analysis_options.yaml
playground/frontend/lib/components/dropdown_button/dropdown_button.dart
playground/frontend/lib/components/split_view/split_view.dart
playground/frontend/lib/modules/editor/components/editor_textarea.dart
playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown.dart
playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown_body.dart
playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_form.dart
playground/frontend/lib/modules/examples/components/example_list/category_expansion_panel.dart
playground/frontend/lib/modules/examples/example_selector.dart
playground/frontend/lib/modules/graph/graph_builder/painters/node_painter.dart
playground/frontend/lib/modules/notifications/components/base_notification.dart
playground/frontend/lib/modules/sdk/components/sdk_selector_row.dart
playground/frontend/lib/modules/shortcuts/components/shortcuts_modal.dart
playground/frontend/lib/modules/shortcuts/models/shortcut.dart
playground/frontend/lib/pages/embedded_playground/components/embedded_split_view.dart
playground/frontend/lib/pages/playground/components/feedback/feedback_dropdown_content.dart
playground/frontend/lib/pages/playground/components/feedback/feedback_dropdown_icon_button.dart
playground/frontend/lib/pages/playground/states/examples_state.dart
playground/frontend/lib/pages/playground/states/playground_state.dart
playground/frontend/pubspec.lock
playground/frontend/pubspec.yaml
playground/frontend/test/utils/run_with_retry_test.dart

Resolves #21951 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20 …

[Playground] Upgrade Flutter linter, fix linter issues (#21951)

---

sdks/java/core/src/main/java/org/apache/beam/sdk/options/PipelineOptions.java
sdks/python/apache_beam/runners/dataflow/internal/clients/dataflow/dataflow_v1b3_messages.py

JobName regex is incorrect: the character limit is 1024, not 40.
R: @aaltay
R: @robertwb  …

Correcting the regex for the Dataflow job name

---

scripts/ci/issue-report/generateReport.js

changing url to html_url parameter. See example response:
https://docs.github.com/en/rest/issues/issues#list-repository-issues
r: @damccorm  …

Fix links for issue report

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformMessageToRowFactory.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformMessageToRowFactoryTest.java

This PR addresses #21412 by producing a [PubsubTransformToRow](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubMessageToRow.java) from a [PubsubSchemaTransformReadConfiguration](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformReadConfiguration.java).
The design goals of `PubsubSchemaTransformMessageToRowFactory` in this PR are to replicate logic in the existing [PubsubSchemaIOProvider](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaIOProvider.java) and provide readability on a future PR that commits a …

Implement PubsubSchemaTransformMessageToRowFactory

---

.gitignore
scripts/ci/issue-report/generateReport.js

Per https://lists.apache.org/thread/mz0ctj318j0h8lyhwrc104l7c0rco3cw we've decided to unify to a single issue report with the following categories:
- Unassigned P0s
- P0s with no update in the last 36 hours
- Unassigned P1s
- P1s with no update in the last 7 days
This PR updates to do that. I tested it out and sent the email to my personal account and it worked. …

Unify to a single issue report

---

scripts/ci/issue-report/generateReport.js

This causes some email clients to not recognize it as a valid url …

Remove colon in issue report

---

website/www/site/assets/js/fix-menu.js
website/www/site/assets/js/page-nav.js
website/www/site/layouts/baseof.html
website/www/site/layouts/partials/head_homepage.html

!!!NB Before merging this PR, please, merge https://github.com/apache/beam/pull/17731 first, since there will be conflicts. I will update this PR with incoming changes from 17731, solve all conflicts and then this PR can be merged. 
- add guard expressions before the init method in both fix-menu.js and page-nav.js since they execute code connected with side menu (page-nav menu). Both files were attached in head section and were present on each page. Homepage doesn't have side menu, but code still tried to run and mistakes were shown on console
- add separate head_homepage.html with no fix-menu.js and page-nav.js scripts for home page 
- add baseof.html for homepage in layouts/baseof.html …

[Website] add guard expressions to fix-menu and page-nav

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java

Fixes #22008 
Addresses DEADLINE_EXCEEDED flakiness by testing for "at least" rather than…"exactly" the number of retries. 
Randomness in the FluentBackoff implementation empirically allows (with current defaults) the number of actual retries in this test to drift between 8 and 10 retries. Other approaches to making this test deterministic (e.g. by setting the random number generator seed or explicitly specifying a maximum number of retries) would likely require fairly substantial refactoring of the SpannerIO configuration as none of these parameters appear to be plumbed through at present. …

Fix DEADLINE_EXCEEDED flakiness 

---

sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/CombinerTableBenchmark.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/PrecombineGroupingTable.java

checkStlye Fix: remove redundant static and public in interface. camel naming

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java

This fixes #21999
~Also fixes #21729~
* Fix runBatchQueryTestWithFailures api call verify condition.
Also remove PAssert that never executes due to exception thrown upstream
* Fix SpannerIOWriteExceptionHandlingTest
GitHub …

Fix SpannerIO flakes

---

sdks/go/test/integration/integration.go

We ran into this here - https://github.com/apache/beam/pull/22038 …

Add randomness to integration test job names to avoid collisions

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.40.0.md
website/www/site/content/en/get-started/downloads.md

Blog post and updates for release 2.40.0

---

sdks/python/apache_beam/runners/interactive/README.md

fixes #20877
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and% …

Issue#20877 Updated Interactive Beam README

---

.github/ACTIONS.md
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/workflows/self-assign.yml

This does 2 things:
1) Ports the existing label management issue to JS.
2) Adds the ability to add or remove labels from an issue.
Example of this in action - https://github.com/damccorm/playground/issues/19 …

Update issue bot to javascript and add label management

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformMessageToRowFactory.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformMessageToRowFactoryTest.java

This PR addresses #21412 by fixing #21953.
To validate this PR, I ran the following gradle tasks prior to submission:
```
./gradlew rat
./gradlew spotlessCheck
./gradlew sdks:java:io:google-cloud-platform:check
./gradlew sdks:java:io:google-cloud-platform:checkStyleMain
./gradlew sdks:java:io:google-cloud-platform:checkStyleTest
```
I would like to request the following to review this PR:
R: @pabloem  …

Fix PubsubSchemaTransformMessageToFactory

---

CHANGES.md

remove mention of dill in release notes as it's not relevant.

---

website/www/site/layouts/case-studies/baseof.html

- add scroll-spy to body in case-studies/baseof.html to fix case-studies right nav menu …

[Website] fix all case-studies right nav menu

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/BeamFnDataReadRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/PTransformRunnerFactory.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/BeamFnDataReadRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FnApiDoFnRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/PTransformRunnerFactoryTestContext.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java

This cleans up a TODO for a closed issue and moves short id logic to one time instantiation vs per bundle report for a minor perf improvement. …

[BEAM-6597] Replace ProgressRequestCallback with BundleProgressReporter

---

sdks/go/pkg/beam/core/runtime/harness/worker_status.go
sdks/go/test/integration/io/fhirio/fhirio_test.go
sdks/go/test/integration/io/xlang/bigquery/bigquery_test.go

This PR fixes the Go Lint issue encountered in a recent import into Google. …

[Go SDK] Go Lint fixes 

---

website/www/site/content/en/blog/beam-2.40.0.md

Part of #22091
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&e …

Add FlatMap(<builtin>) known issue to 2.40.0 blog

---

sdks/python/apache_beam/examples/inference/pytorch_language_modeling.py

Small change to the summary of the Pytorch LM example …

Change wording of Pytorch LM example

---

sdks/python/apache_beam/ml/inference/pytorch_inference.py

Add the missing `model_params` arg into `PytorchHandlerKeyedTensor`, and adjust the wording in both handler classes. …

Fix missing model_params in Pytorch docstring 

---

playground/frontend/lib/modules/analytics/analytics_events.dart
playground/frontend/lib/modules/analytics/analytics_service.dart
playground/frontend/lib/modules/analytics/google_analytics_service.dart
playground/frontend/lib/modules/examples/components/example_list/expansion_panel_item.dart
playground/frontend/lib/pages/embedded_playground/components/embedded_appbar_title.dart
playground/frontend/lib/pages/playground/components/editor_textarea_wrapper.dart
playground/frontend/lib/pages/playground/components/playground_page_providers.dart
playground/frontend/lib/utils/analytics_utils.dart

Fixes #22012 
This is a rebased copy of #21926 that contains all the fixes but does not include Matomo and retains Google Analytics. It also contains `AbstractAnalyticsService` to later swap Matomo in much easier. …

[Playground] Fix analytics for snippet changing, cancelling, and link following (#22012)

---

CHANGES.md
runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkRunner.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java

Kyle turned this on by default for batch in #17107, now we turn it on for streaming. Users are able to opt out of the change with the experiment, preserving upgrade compatibility.
(See https://github.com/apache/beam/pull/17107#discussion_r829543160) …

Projection Pushdown optimizer on by default

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml

Right now, we get a lot of "P0s" because people don't change the default or don't understand the priority meanings. In all templates, this:
1) Reverses the dropdown order so that p3 is the default.
2) Adds a link to the issue priorities doc.
3) Removes P0 from the feature/task templates since those are definitionally not P0 (or at the very least should only be set that way by people with label triage permission). …

Change default, options, and explanation for issue priority

---

playground/frontend/lib/pages/embedded_playground/embedded_page_providers.dart
playground/frontend/lib/pages/playground/components/playground_page_providers.dart

Fixes #21950 
R: @damondouglas 
We could not determine the reason why we were re-creating this state. It was this way since the inception of this file in October. Back then it did not matter because there were no async operations.
Classes like `PlaygroundState` should either be:
1. Mutable controllers, and persist throughout the life cycle of a parent widget, or
2. Immutable states emitted by some other business logic unit.
Currently, `PlaygroundState` is a mix of the two. Here we are making it (1). …

[Playground] Do not re-create PlaygroundState (#21950)

---

sdks/python/apache_beam/examples/inference/pytorch_language_modeling.py

Pass in `model_class=model_class`.
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source …

Fix typo in Pytorch Bert Language Modeling

---

sdks/go/data/fhir_bundles/transaction-success.json
sdks/go/pkg/beam/io/fhirio/common.go
sdks/go/pkg/beam/io/fhirio/execute_bundles.go
sdks/go/pkg/beam/io/fhirio/execute_bundles_test.go
sdks/go/pkg/beam/io/fhirio/read.go
sdks/go/pkg/beam/io/fhirio/read_test.go
sdks/go/pkg/beam/io/fhirio/search.go
sdks/go/pkg/beam/io/fhirio/search_test.go
sdks/go/pkg/beam/io/fhirio/utils_test.go
sdks/go/test/integration/io/fhirio/fhirio_test.go

Add [Search](https://github.com/apache/beam/blob/2574f9106c75e413310dcb7756952889da3fe7cd/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java#L1807) transform to Go FhirIO, enabling Go pipelines to query resources in a given Google Cloud Healthcare FHIR Store.
Buganizer ticket: [b/236784940](https://b.corp.google.com/issues/236784940)
Fixes #21977 …

Add Search transform to Go FhirIO

---

runners/google-cloud-dataflow-java/build.gradle

Bump dataflow fnapi java sdk version

---

runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/wire/ByteStringCoder.java
sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ByteStringCoder.java

This fixes #22143
R: @lukecwik (sorry to keep tagging you, you're the only one thats touched this in a long time) …

Tune ByteStringCoder allocations

---

runners/google-cloud-dataflow-java/build.gradle

Enable supported tests on dataflow runner v2.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContext.java

This fixes #22141 
R: @lukecwik  @reuvenlax  …

Tune StreamingModeExecutionContext allocations

---

sdks/python/apache_beam/dataframe/frames.py

Fixes #22170
This addresses an issue where our documentation incorrectly identified some global aggregations (those that have custom implementations on DeferredSeries, like std), as non-parallelizable.
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.c …

Fix documentation about hand implemented global aggregations

---

runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/BatchStatefulParDoOverridesTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/storage/GcsPathValidator.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/options/GcpOptionsTest.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/storage/GcsPathValidatorTest.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtilTest.java

[fixes #22078] Propogate error messages from GcsUtil

---

sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java

Kafka performance tests are failing just after being enabled, with stacktrace
`02:10:31 org.apache.beam.sdk.io.kafka.KafkaIOIT > testKafkaIOReadsAndWritesCorrectlyInStreaming FAILED
02:10:31     java.lang.IllegalStateException: withTopic() is required
02:10:31         at org.apache.beam.sdk.util.Preconditions.checkStateNotNull(Preconditions.java:471)
02:10:31         at org.apache.beam.sdk.io.kafka.KafkaIO$Write.expand(KafkaIO.java:2906)
02:10:31         at org.apache.beam.sdk.io.kafka.KafkaIO$Write.expand(KafkaIO.java:2699)
02:10:31         at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
02:10:31         at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499)
02:10:31         at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:376)
02:10:31 …

Fix testKafkaIOReadsAndWritesCorrectlyInStreaming failing for kafka performance test

---

sdks/python/apache_beam/io/hadoopfilesystem.py

Fix Hadoop upload corrupted due to buffer reuse

---

website/www/site/content/en/documentation/programming-guide.md

Calls out automated expansion service start-up workflow for Go, specifying how to use the automated start-up for Java and calling out that python expansion service start-up is not currently automated. 
Fixes #22176
[Staged website](http://apache-beam-website-pull-requests.storage.googleapis.com/22187/index.html)
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test- …

Update Go BPG xlang documentation to include Java automated service start-up

---

website/www/site/content/en/about/_index.md

- case studies link was leading to staging, changed it to lead to relative path …

[Website] fix change case studies link from staging to relative path

---

website/www/site/assets/scss/_connectors.sass
website/www/site/content/en/documentation/io/connectors.md
website/www/site/i18n/navbar/en.yaml
website/www/site/layouts/partials/header.html

- add I/O Connectors link to dropdown list on header menu
- update multi-language-pipelines link to relative path
- update connectors.sass styles …

[Website] add I/O Connectors link to dropdown list, update I/O Connectors

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoConstants.java
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java
sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/control/ExecutionStateSamplerBenchmark.java
sdks/java/harness/jmh/src/test/java/org/apache/beam/fn/harness/jmh/control/ExecutionStateSamplerBenchmarkTest.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ExecutionStateSampler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PTransformFunctionRegistry.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/status/BeamFnStatusClient.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ExecutionStateSamplerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistryTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/PTransformFunctionRegistryTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/status/BeamFnStatusClientTest.java

Msec counters benchmarks, 2.5x-3.5x faster, larger bundles have bigger wins
```
Benchmark                                                               Mode  Cnt         Score        Error  Units
ExecutionStateSamplerBenchmark.testLargeBundleHarnessStateSampler      thrpt   25     74093.492 ±    364.322  ops/s
ExecutionStateSamplerBenchmark.testLargeBundleRunnersCoreStateSampler  thrpt   25     19838.512 ±     81.986  ops/s
ExecutionStateSamplerBenchmark.testTinyBundleHarnessStateSampler       thrpt   25  10187284.157 ± 128030.350  ops/s
ExecutionStateSamplerBenchmark.testTinyBundleRunnersCoreStateSampler   thrpt   25   4099369.479 ±  25219.934  ops/s
```
Before
```
Benchmark                               Mode   Cnt      Score     Error  Units
ProcessBundleBenchmark.testTinyBundle   thrpt …
```

[BEAM-13015, #22050] Make SDK harness msec counters faster using ordered puts

---

website/www/site/content/en/contribute/get-started-contributing.md

[Website] Update minimum required Go version for sdk development

---

.github/workflows/playground_deploy_examples.yml

This has been red for a while https://github.com/apache/beam/actions/workflows/playground_deploy_examples.yml
Fixes #22227 …

Fix playground workflow

---

.asf.yaml

r: @VladMatyunin @damccorm 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20dist …

Adding VladMatyunin as collaborator

---

sdks/java/core/src/main/java/org/apache/beam/sdk/options/ExperimentalOptions.java

r: @udim 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20w …

Several requests to show experiments in UIs.

---

sdks/go/pkg/beam/runners/session/session.go

Marks the `session` package as deprecated and indicates that it will be removed in a future release. 
Part of #22241  …

Mark session runner as deprecated

---

sdks/go/test/integration/wordcount/wordcount.go

Shift to using the new generic registration for DoFns, iterators, and emitters in the native Go wordcount integration test.
Part of #22246 …

Move wordcount integration test to generic registration

---

sdks/go/test/integration/primitives/checkpointing.go
sdks/go/test/integration/primitives/drain.go
sdks/go/test/integration/primitives/pardo.go
sdks/go/test/integration/primitives/window_panes.go
sdks/go/test/integration/primitives/windowinto.go

Shift to using the new generic registration for DoFns, iterators, and emitters in the native Go primitives integration tests.
Part of #22246 …

Move Go Primitives Integration Tests to Generic Registration

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/SplittableParDo.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/SplittableParDoTest.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java

This fixes #22244 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution% …

Adds an experiment that allows opting into using Kafka SDF-wrapper

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Fix typo in comment
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution …

Fix typo in comment

---

.github/workflows/playground_deploy_examples.yml

Authentication test: GCP authentication was moved to first step to test if it will work …

Pg auth test

---

sdks/go/pkg/beam/io/fhirio/common.go
sdks/go/pkg/beam/io/fhirio/common_test.go
sdks/go/pkg/beam/io/fhirio/deidentify.go
sdks/go/pkg/beam/io/fhirio/deidentify_test.go
sdks/go/pkg/beam/io/fhirio/execute_bundles_test.go
sdks/go/pkg/beam/io/fhirio/read_test.go
sdks/go/pkg/beam/io/fhirio/search_test.go
sdks/go/pkg/beam/io/fhirio/utils_test.go
sdks/go/test/integration/integration.go
sdks/go/test/integration/io/fhirio/fhirio_test.go

Add Deidentify transform to Go FhirIO to enable deidentification of a source Fhir store to a given destination Fhir store.
Unit tests in progress.
Buganizer issue: [b/238025974](https://b.corp.google.com/issues/238025974)
Fixes #22151 …

Add fhirio.Deidentify transform

---

sdks/python/apache_beam/ml/inference/base.py

Update inference/base.py with two changes.
1. Specifies that the clock parameter is used for unit tests.
2. Adds description of parameter to MaybeKeyed and Keyed model handler wrappers. …

RunInference documentation updates.

---

sdks/python/apache_beam/examples/inference/README.md

Updating the RunInference ReadMe
- Typo fixes
- Clarifying requirements for each section
R: @yeandy  …

Reviewing the RunInference ReadMe file for clarity.

---

website/www/site/content/en/documentation/sdks/java-multi-language-pipelines.md

Refreshed the content for the Java multi-language pipeline quickstart. See: http://apache-beam-website-pull-requests.storage.googleapis.com/22263/documentation/sdks/java-multi-language-pipelines/index.html
@chamikaramj
@ihji  …

Rewrote Java multi-language pipeline quickstart

---

.github/workflows/pr-bot-new-prs.yml
.github/workflows/pr-bot-pr-updates.yml
.github/workflows/pr-bot-prs-needing-attention.yml
.github/workflows/pr-bot-update-reviewers.yml
.github/workflows/reportGenerator.yml
.github/workflows/typescript_tests.yml

Right now, our GitHub Actions tests run `npm install` which has the potential to run ci with a different set of dependencies than are represented in the package.json. This means that functionally, dependencies in CI are slowly moving forward without us making any code changes, and don't represent what is potentially going to be published. This is also a potential vector for security attacks.
This updates to use `npm ci` in CI. Fixes #22322 …

Use npm ci instead of install in CI

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

This fixes https://github.com/apache/beam/issues/22317 …

Fix typo in use_single_core_per_container logic.

---

sdks/typescript/src/apache_beam/coders/js_coders.ts
sdks/typescript/src/apache_beam/internal/urns.ts
sdks/typescript/src/apache_beam/runners/direct_runner.ts
sdks/typescript/src/apache_beam/transforms/combiners.ts
sdks/typescript/src/apache_beam/transforms/group_and_combine.ts
sdks/typescript/src/apache_beam/transforms/internal.ts
sdks/typescript/src/apache_beam/worker/operators.ts
sdks/typescript/test/combine_test.ts
sdks/typescript/test/js_coders_test.ts

Also improve direct CombineFn testing and array encoding. …

Support combiner lifting.

---

.asf.yaml

olehborysevych is working for Tour of Beam project and needs to be able to manage a Project inside beam repository …

Adding olehborysevych as collaborator 

---

build.gradle.kts

See https://github.com/apache/beam/pull/15786#issuecomment-1190377753
[![Java …

Drop `timeseries:postCommit` dependency

---

sdks/python/apache_beam/ml/inference/pytorch_inference_it_test.py

gs://apache-beam-ml/testing/inputs/it_coco_validation_inputs.txt was changed on July 21st and it needs to be addressed once the team gets back
https://github.com/apache/beam/issues/22413 …

Skip failing torch post commit test

---

sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/apache_beam/runners/portability/local_job_service.py
sdks/python/apache_beam/runners/worker/log_handler.py
sdks/python/apache_beam/utils/subprocess_server.py

Fixes #18570
* Honor Python SDK log level while logging
* Fix subprocess logging are bytes …

Log level fix on local runner

---

.test-infra/jenkins/job_LoadTests_Combine_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Python_reiterate.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Python.groovy
.test-infra/jenkins/job_LoadTests_SideInput_Python.groovy

Fixes #22422
See explanation in https://github.com/apache/beam/issues/22422#issuecomment-1193019507
[![Java …

Remove spaces in experiments

---

sdks/python/apache_beam/testing/load_tests/load_test_metrics_utils.py
sdks/python/apache_beam/utils/retry.py
sdks/python/setup.py

Altered setup.py to allow google-cloud-recommendations-ai up to latest currently available version in order to address #22287.  …

Update the upper bound for google-cloud-recommendations-ai.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/RowWriterFactory.java

Fix overly aggressive null check in RowWriterFactory

---

website/www/site/assets/js/copy-to-clipboard.js
website/www/site/assets/js/page-nav.js
website/www/site/assets/scss/_case_study.scss
website/www/site/layouts/partials/head.html
website/www/site/layouts/partials/head_homepage.html

Current state: img src didn't get correct path on staging in js and css files. Not resolved images make staging functionality differ from production and complicate review of impacted website changes.
Improvement: Below changes will enable staging resolve image sources with relative URLs, and staging will behave the same as production for images loaded in Javascript files.
- add absURL to page-nav.js and copy-to-clipboard.js, _case_study.scss to fix incorrect img src on staging
- add `resources.ExecuteAsTemplate` to head.html, head_homepage.html …

[WEBSITE] fix relative paths bug on staging in js files

---

.github/workflows/build_wheels.yml
sdks/java/extensions/python/src/main/resources/org/apache/beam/sdk/extensions/python/bootstrap_beam_venv.py
sdks/python/apache_beam/examples/complete/juliaset/setup.py
sdks/python/apache_beam/runners/portability/stager.py
sdks/python/container/Dockerfile
sdks/python/setup.py
website/www/site/content/en/documentation/sdks/python-pipeline-dependencies.md

Revert "Replace distutils with supported modules. "

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/transforms/DataframeTransform.java
sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/transforms/PythonMap.java
sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/transforms/RunInference.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/transforms/RunInferenceTransformTest.java

Also adds experimental tags for RunInference and other recently added Java cross-language transforms.
This fixes #22441  …

Adds KV support for the Java RunInference transform.

---

sdks/go/pkg/beam/core/runtime/harness/init/init.go
sdks/go/pkg/beam/util/syscallx/syscall_default.go
sdks/go/pkg/beam/util/syscallx/syscall_linux.go

Fixes go lint issues encountered on import. …

[Go SDK]: lint fixes for recent import

---

sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java

Remove code that generated a random group name
Added an integration test that verifies we don't re-process elements
Resolves #21730
[![Build …

21730 fix offset resetting

---

sdks/java/extensions/python/src/main/resources/org/apache/beam/sdk/extensions/python/bootstrap_beam_venv.py

Upgrades pip before installing Beam for Python default expansion service

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/samza/build.gradle
runners/samza/src/main/java/org/apache/beam/runners/samza/metrics/SamzaMetricsContainer.java
runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/DoFnOp.java
runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/SamzaDoFnRunners.java
runners/samza/src/main/java/org/apache/beam/runners/samza/util/DoFnUtils.java
runners/samza/src/test/java/org/apache/beam/runners/samza/util/DoFnUtilsTest.java

Adding default process ns metrics for executable stages in samza runner.
1. Nano second instead of milli second as the process time is expected to be arond 0.01 milli second.
2. Sampling metric to reduce performance impact.
3. Random based sampling instead of couting based sampling as SdkHarnessDoFnRunner is stateless and new instance created for each execution of ExecutableStage.
4. Suppress RandomModInteger warning since 1/n chance to be 0 is still expected. …

[22369] Default Metrics for Executable Stages in Samza Runner

---

sdks/go/examples/fhirio/read_write_pubsub.go
sdks/go/pkg/beam/io/fhirio/common.go
sdks/go/pkg/beam/io/fhirio/execute_bundles.go
sdks/go/pkg/beam/io/fhirio/execute_bundles_test.go
sdks/go/pkg/beam/io/fhirio/read.go
sdks/go/pkg/beam/io/fhirio/read_test.go
sdks/go/pkg/beam/io/fhirio/utils_test.go
sdks/go/test/integration/io/fhirio/fhirio_test.go

Add a sample `fhirio` pipeline to demonstrate usage of `Read` and `ExecuteBundles` transforms as well as integration with `pubsubio`.
Fixes #22305 …

Add read/write PubSub integration example fhirio pipeline

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a badge for the Go test workflow status on the master branch to match Python and Java. This PR uses the modified template it contains. 
Fixes #22507 …

Add Go test status to the PR template

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1ReadIT.java

Fix typo in Datastore V1ReadIT test that causes test failure …

Fix typo in Datastore V1ReadIT test

---

sdks/python/setup.py

Cherrypicks: https://github.com/apache/beam/pull/22513
Fixes: #22454 …

[release-2.41.0] Relax google-api-core dependency

---

sdks/python/apache_beam/examples/complete/juliaset/setup.py

cherrypicks:  https://github.com/apache/beam/pull/22503
Fixes: https://github.com/apache/beam/issues/22516 …

[release-2.41.0]Change _build import from setuptools to distutils

---

sdks/java/io/common/src/test/java/org/apache/beam/sdk/io/common/DatabaseTestHelper.java
sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOIT.java

Fix JDBCIOIT

---

.github/PULL_REQUEST_TEMPLATE.md

Update the pull request template to correctly point at the documentation that discourages squashing unreviewed commits. …

Update the imprecise link.

---

CHANGES.md
sdks/python/apache_beam/io/filesystem.py
sdks/python/apache_beam/io/filesystem_test.py
sdks/python/container/py37/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/setup.py

Adds zstd compression, issue #22393 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20sour …

Add zstd compression/decompression support

---

CHANGES.md

Separate changes that added before or after 2.41.0 cut. Needs to add change in another PR after this. …

Update CHANGE.md after 2.41.0 cut

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Updating tag to `beam-master-20220803` …

Update Dataflow container version

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java

Cherry-pick https://github.com/apache/beam/pull/22347 to release branch

[release-2.41.0]Merge pull request #22347: [22188]Set allowed timestamp skew

---

CHANGES.md

Another trivial catch of CHANGES. #22049 was merged in June 29 and should be added under [2.41.0]. Currently it is in template. …

Moving misplaced CHANGES from template to 2.41.0

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/TopicBacklogReaderImpl.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/TopicBacklogReaderImplTest.java

[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/ …

pubsublite: Fix max offset for computing backlog

---

website/www/site/content/en/documentation/sdks/python-machine-learning.md

Add PyDoc buttons to the top and bottom of the Machine Learning page. …

Add PyDoc buttons to the top and bottom of the Machine Learning page

---

learning/katas/java/Common Transforms/WithKeys/WithKeys/src/org/apache/beam/learning/katas/commontransforms/withkeys/Task.java

Modified Playground "WithKeys" Java example to trigger pipeline that deploys example to Playground (for testing purpose) …

[Playground]: Modified WithKeys Playground Example

---

website/www/site/content/en/documentation/transforms/java/aggregation/distinct.md

I noticed that there was no example for `Distinct` Java PTransform in the docs.
This PR changes that -- We add an example for `Distinct` Java PTransform in the docs.
Addresses some part of [BEAM-7703](https://issues.apache.org/jira/browse/BEAM-7703).
About choosing **Reviewers:** Not sure who to assign as a reviewer because I don't know who works on beam …

Add an example for `Distinct` PTransform

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_test.py
sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/bigquery_tools_test.py
sdks/python/setup.py

For Issue: #22451
Update BigQuery URI validation for fully qualified table names to align more with documenation:
- Support a wider range of characters for table names
- Allow either `proj:dataset.table` or `proj.dataset.table` format
- More rigorous validation of project id
GitHub Actions …

Update BigQuery URI validation to allow more valid URIs through

---

sdks/java/io/google-cloud-platform/build.gradle
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimatorTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/MutationUtilsTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerTransformRegistrarTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataAdminDaoTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataDaoTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dofn/InitializeDoFnTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dofn/PostProcessingMetricsDoFnTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/ChangeStreamRecordMetadataTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/PartitionMetadataTest.java

- Adds unit tests for SpannerIO library inside GCP project to improve overall code coverage. 
- Correctly generates Spanner code coverage report and uses Jacoco code coverage validation to enforce code coverage for SpannerIO. …

Add units tests for SpannerIO

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java

See #22631 
fixes #22631 
- ~[ ] Update `CHANGES.md` with noteworthy changes.~
- ~[ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~ …

Fix for #22631 KafkaIO considers readCommitted() as it would commit back the offsets, which it doesn't

---

playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_option_controller.dart
playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown_body.dart
playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_form.dart

Remove `kDefaultOption` global variable that had been caching an option even if unsaved.
Fixes #22075  …

Fix retaining unsaved pipeline options (#22075)

---

.asf.yaml

removed VladMatyunin from beam collaborators to claim back  issue triage permissions slots …

Removed VladMatyunin from beam collaborators

---

sdks/python/apache_beam/runners/dataflow/dataflow_exercise_metrics_pipeline_test.py

Sickbay `test_metrics_it` due to bug reported here https://github.com/apache/beam/issues/22605. Will unskip when finish investigating issue. …

Skip dataflow_exercise_metrics_pipeline_test.ExerciseMetricsPipelineTest.test_metrics_it

---

runners/spark/2/src/main/java/org/apache/beam/runners/spark/structuredstreaming/aggregators/AggregatorsAccumulator.java
runners/spark/2/src/main/java/org/apache/beam/runners/spark/structuredstreaming/metrics/MetricsAccumulator.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/aggregators/AggregatorsAccumulator.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/metrics/MetricsAccumulator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkPipelineRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunnerDebugger.java
runners/spark/src/main/java/org/apache/beam/runners/spark/TestSparkRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/aggregators/AggregatorsAccumulator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/io/MicrobatchSource.java
runners/spark/src/main/java/org/apache/beam/runners/spark/io/SourceDStream.java
runners/spark/src/main/java/org/apache/beam/runners/spark/metrics/MetricsAccumulator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/stateful/SparkGroupAlsoByWindowViaWindowSet.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/streaming/WatermarkSyncedDStream.java

Just a small adhoc fix, the Spark runner code is full of bad logging practices. …

Adhoc: Fix logging in Spark runner to avoid unnecessary creation of strings

---

.test-infra/jenkins/job_PostCommit_Python.groovy

Change timeout from 180 to 240 minutes per timeout issue identified here https://github.com/apache/beam/issues/22643 …

Change Python PostCommits timeout

---

website/www/site/content/en/documentation/resources/learning-resources.md

Fixing the broken link to the Retry Policy blogpost …

Fix broken link to Retry Policy blog

---

scripts/ci/issue-report/generateReport.js

Having a total in the email subject helps me to intuitively keep a mental tally and track changes. There is probably more we could do, like adding the date issues were files or some such. To get a quick "at a glance" sense of things from the email. …

Include total in header of issue report

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerTransformRegistrarTest.java

Update vendored gRPC version for SpannerTransformRegistrarTest

---

runners/samza/build.gradle
runners/samza/job-server/build.gradle
runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/SamzaTimerInternalsFactory.java

[#22647] Upgrade org.apache.samza to 1.6

---

.github/workflows/java_tests.yml

This was upgraded incorrectly in #22666 …

Fix wordcount setup-java

---

website/www/site/content/en/documentation/runners/dataflow.md
website/www/site/content/en/documentation/runners/jet.md
website/www/site/content/en/documentation/runners/samza.md
website/www/site/content/en/documentation/runners/spark.md
website/www/site/content/en/documentation/runners/twister2.md
website/www/site/layouts/shortcodes/flink_java_pipeline_options.html
website/www/site/layouts/shortcodes/flink_python_pipeline_options.html

Resolves #22708
- add container with overflow-x property to runners with table with content overflow
________________________________________________________________________________________________________________________________
before:
after:  …

[Website] update runners table content overflow

---

playground/backend/cmd/server/controller.go

fixes #22685 
@olehborysevych  …

[Playground] [Backend] added validation for snippet endpoints to avoid error panic
