sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformWriteConfiguration.java

This PR address #21412 with a PubsubSchemaTransformWriteConfiguration implementation.  It's design goals are to like-for-like replicate PubsubSchemaIOTransform write configuration details.  Subsequent to this PR's approval/merge, the plan is to implement the final PubsubSchemaTransformWriteProvider.
Due to repeatedly failing beam_PreCommit_Java tests, to validate this PR, I ran the following prior to submission:
```
./gradlew rat
./gradlew spotlessCheck
./gradlew sdks:java:io:google-cloud-platform:check
./gradlew sdks:java:io:google-cloud-platform:checkStyleMain
```
I would like to request the following to review this PR:
R: @pabloem 
- ~Update …

Implement PubsubSchemaTransformWriteConfiguration

---

runners/google-cloud-dataflow-java/build.gradle
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/SubscribeTransform.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/UnboundedReaderImpl.java

Also change places where UnboundedReader can throw in normal operation to log info instead. …

Add a dataflow override for runnerv1 to still use SDF on runnerv2.

---

website/www/site/assets/scss/_case_study.scss
website/www/site/assets/scss/_global.sass
website/www/site/layouts/case-studies/baseof.html
website/www/site/layouts/case-studies/list.html

- lessen right and left spaces on case-studies page
- make 3 case-studies cards in a row starting from desktop resolution (1024px) and more
- make a row of 4 cards for additional case studies on tablet resolutions (640px) and more. Center additional case studies on tablet resolution (between 640px and 1024px)
_________________________________________________________________________________________________________________________________
before:
after: …

[Website] update case-studies layout

---

runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/legacy-worker/build.gradle
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/MetricsEnvironment.java
sdks/java/harness/build.gradle
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PTransformFunctionRegistry.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistryTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/PTransformFunctionRegistryTest.java

This got rid of about half of the overhead of activating the metrics container for the current thread.
The updated implementation is about 48 ms for the two calls to activate:
While the existing implementation is 75 ms (+8 ms not shown for the `Closeable#close` invocation):
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUIL …

[BEAM-13015, #21250] Remove looking up thread local metrics container holder and object creation on hot path

---

runners/google-cloud-dataflow-java/worker/legacy-worker/build.gradle

[fixes #22731] Publish nightly snapshot of legacy Dataflow worker jar

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/spark/spark_runner.gradle
sdks/java/extensions/sorter/build.gradle
sdks/java/extensions/sql/build.gradle
sdks/java/io/hadoop-common/build.gradle
sdks/java/io/hadoop-file-system/build.gradle
sdks/java/io/hadoop-format/build.gradle
sdks/java/io/hcatalog/build.gradle
sdks/java/io/parquet/build.gradle

[fixes #22744] Update hadoop library patch versions to 2.10.2 and 3.2.4

---

sdks/python/apache_beam/typehints/schemas.py

To fix assertion error as documented in https://github.com/apache/beam/issues/22748 …

Remove assert schema.id

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ByteBuddyUtils.java

Improve error message on schema issues

---

sdks/java/core/src/main/java/org/apache/beam/sdk/Pipeline.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/GroupByKey.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PTransform.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/GroupByKeyTest.java

[#21935] Reject ill formed GroupByKey coders during pipeline.run validation within Beam Java SDK.

---

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtilTest.java

This fixes #22431
Related, it might be worth rewriting the [GCS staging process](https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/PackageUtil.java#L125) to do a bulk match, which would allow a single (or at least significantly less) API calls to check if the files to stage exist or not.  Doing so would require a pretty significant rewrite of that process though.
R: @chamikaramj
To check the …

[fixes #22431] Don't use batch interface for single object operations

---

website/www/site/content/en/contribute/_index.md

Current Contribution guide suggests using GitHub issue but doesn't provide link to Apache Beam GitHub issue.
For more friendly webside, I add a URL link about GitHub issue.
(This is my first PR for Apache Beam, Sorry if it's wrong PR to improve a website) …

[Website] Add GitHub issue link in  Contribution guide

---

website/www/site/content/en/documentation/sdks/python-machine-learning.md

Fix some typos in the ML doc

---

.github/workflows/playground_deploy_examples.yml

Testing authentication for Playground

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

To work around https://github.com/apache/beam/issues/22749 …

Downgrade bytebuddy version to 1.11.0

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java

This will reduce OOMs in the case where we are adding new writes faster then we are able to clean-up older ones across elements. …

[BEAM-12776, fixes #21095] Limit parallel closes from the prior element to the next element.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/PubsubSink.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillStateInternals.java

[BEAM-13015, #21250] Reuse buffers when possible when writing on Dataflow streaming hot paths.

---

website/www/site/data/en/contact_us.yaml

Resolves #22696
- remove text from Available contact channels table 
________________________________________________________________________________________________________________________________
before:
after: …

[Website] update Available contact channels table content

---

website/www/site/data/en/contact_us.yaml

Resolves #22520
- update commits link on contact-us page from `https://s.apache.org/beam-slack-channel` to `https://lists.apache.org/list.html?commits@beam.apache.org`
_______________________________________________________________________________________________________________________________________
before:
after:
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github. …

[Website] update commits link

---

sdks/go/pkg/beam/core/funcx/fn.go
sdks/go/pkg/beam/core/graph/fn.go
sdks/go/pkg/beam/core/runtime/exec/fn.go
sdks/go/pkg/beam/core/runtime/exec/translate.go
sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/state/state.go
sdks/go/pkg/beam/core/state/state_test.go

Fixes go lint error caught on import …

[Go SDK] Fix go lint errors

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go

ID is an initialism and should always be capitalized. …

Fix lint issues

---

sdks/python/mypy.ini

[BEAM-13657] Update Python version used by mypy.

---

sdks/java/io/neo4j/src/main/java/org/apache/beam/sdk/io/neo4j/Neo4jIO.java

Aligning the error messages thrown by `checkArgument` with the API …

Align neo4j error messages with API

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Java_IO_IT_Tests_Dataflow.json
sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java
sdks/java/testing/test-utils/src/main/java/org/apache/beam/sdk/testutils/NamedTestResult.java

Fixes #21117
* Reject invalid large negative values
* Fixes grafana TextIOIT 1 GB GCS "Many files" GCS Copies …

Evaluate proper metric in TextIOIT

---

playground/terraform/applications/default/main.tf

resolves #22720 Since ShareAnyCode required Datastore, there are couple of changes in this Pull Request, related terraform changes:
1. Datastore was added in App Engine and database type was defined
2. Setup Datastore …

[Playground] Setup Datastore in Playground project using Terraform - change main.tf file

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.41.0.md
website/www/site/content/en/get-started/downloads.md
website/www/site/data/authors.yml

Update Beam 2.41.0 release docs

---

CHANGES.md
website/www/site/content/en/blog/beam-2.41.0.md
website/www/site/content/en/get-started/downloads.md

Fix dates for 2.41.0 release

---

website/www/site/content/en/get-started/wordcount-example.md

Adding a link to the Java setup instructions in the Java WordCount example, to make sure the user has generated the Maven example. This resolves https://github.com/apache/beam/issues/19548.
Staged changes: http://apache-beam-website-pull-requests.storage.googleapis.com/22832/get-started/wordcount-example/index.html#wordcount-example
@damccorm @kileys @pabloem …

Added link to setup instructions in WordCount example

---

sdks/go/test/integration/integration.go
sdks/go/test/integration/primitives/state.go
sdks/go/test/integration/primitives/state_test.go

As promised, follow up to #22816
Part of #22736 …

Add an integration test for bag state

---

website/www/site/content/en/get-started/downloads.md

Updates old releases to use archive.apache.org

---

website/www/site/content/en/documentation/resources/videos-and-podcasts.md

- embed video to documentation/resources/videos-and-podcasts/ …

[Website] Update videos section

---

runners/google-cloud-dataflow-java/build.gradle

Updates the Dataflow fnapi_container_version for the dataflow runner to a more recent build. …

Update Dataflow fnapi_container_version

---

website/www/site/content/en/documentation/io/connectors.md

Resolves #22845
- add Python implementation to KinesisIO on https://beam.apache.org/documentation/io/connectors/
before:
after: …

[Website] add Python implementation to KinesisIO 

---

sdks/go/pkg/beam/core/state/state.go
sdks/go/test/integration/primitives/state.go

This fixes a few small linting issues introduced by recent changes around function comments. …

Small lint fixes

---

sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py
sdks/python/apache_beam/transforms/window.py

Fixes https://github.com/apache/beam/issues/22723 …

Yield BatchElement batches at end of window.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/build-tools/src/main/resources/beam/suppressions.xml
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/DefaultPackageTest.java

This release includes the fix for the issue with visibility checks for
types in the default package that caused
https://github.com/apache/beam/issues/22749. …

Update to Byte Buddy 1.12.14

---

.gitignore
sdks/python/apache_beam/examples/wordcount_minimal.py

pipeline_args.extend in wordcount_minimal.py adds the pipeline options, which requires manual changes. Following other examples, we can remove these code and add some option documents to show how to use DataflowRunner. …

Update wordcount_minimal.py by removing pipeline_args.extend

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/mapper/ChangeStreamRecordMapper.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/DataChangeRecord.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dofn/PostProcessingMetricsDoFnTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamOrderedWithinKeyGloballyIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamOrderedWithinKeyIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/mapper/ChangeStreamRecordMapperTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/DataChangeRecordTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/ModelEncodingTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/util/TestStructMapper.java

This change adds support for handling transaction tag fields, introduced to the output of Cloud Spanner Change Stream queries, in the Beam/Dataflow. If Cloud Spanner writes are relying on transaction tag feature for auditing, these transaction tags will be included in corresponding Change Stream records produced by the Change Streams tracking affected keyspace.
Design doc: https://docs.google.com/document/d/1qA-PE8CcwNHonhnHG46kOgi7-b9tTnzaZ89daVbeYUU/edit
R: @thiagotnunes 
R: @nancyxu123
R: @pabloem   …

[BEAM-12164] Feat: Added support to Cloud Spanner Change Streams connector for including transaction tags in the Change Stream records

---

sdks/python/apache_beam/dataframe/io.py
sdks/python/apache_beam/dataframe/io_test.py
sdks/python/apache_beam/io/fileio.py

[BEAM-22923] Allow sharding specification for dataframe writes.

---

.github/workflows/build_playground_backend.yml
playground/index.yaml

resolves #22336 A step with "index creation" should be added to the "build_playground_backend" pipeline as part of the "ShareAnyCode" feature addition.  …

[Playground] Update build_playground_backend.yml - add "Index creation" in backend pipeline

---

playground/backend/cmd/server/controller.go
playground/backend/cmd/server/controller_test.go
playground/backend/cmd/server/server.go
playground/backend/internal/db/mapper/datastore_mapper.go
playground/backend/internal/db/mapper/datastore_mapper_test.go
playground/backend/internal/db/mapper/mapper.go
playground/backend/internal/utils/file_utils.go
playground/backend/internal/utils/file_utils_test.go

fixes #22789 
@olehborysevych  …

[Playground] [Backend] added SDK validation to save a code snippet

---

sdks/go/pkg/beam/core/runtime/exec/fullvalue.go
sdks/go/pkg/beam/core/runtime/exec/sideinput_test.go
sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/state/state.go
sdks/go/pkg/beam/pardo.go

This fixes a few small linting issues introduced by recent changes by me + others. …

Fix linting violations

---

sdks/go/test/run_validatesrunner_tests.sh

When multiple postcommits are running at the same time, they can consume enough dataflow resources that it can't complete in 2 hours. For example: https://ci-beam.apache.org/job/beam_PostCommit_Go_PR/519/ and https://ci-beam.apache.org/job/beam_PostCommit_Go_PR/520/ both failed with timeout issues.
This bumps the postcommit timeout to 3 hours to make sure we don't run into that issue. …

Bump up postcommit timeout

---

examples/multi-language/build.gradle
website/www/site/content/en/documentation/sdks/java-multi-language-pipelines.md

Updates the supported version to be consistent for all runners.
Adds instructions for running with the portable DirectRunner.
This fixes #22916  …

Updates to multi-lang Java quickstart

---

sdks/go/test/integration/integration.go

Spark and Flink don't support map based state types, which means map/set tests shouldn't run on those runners. …

Filter out unsupported state tests

---

sdks/python/apache_beam/examples/snippets/transforms/elementwise/runinference_test.py
sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/apache_beam/ml/inference/pytorch_inference_test.py

Addresses GPU -> CPU conversion bugs in https://github.com/apache/beam/issues/22711 and https://github.com/apache/beam/issues/22712
Also fixes CUDA OOM error as reported in https://github.com/apache/beam/issues/22811. …

Fix gpu to cpu conversion with warning logs

---

CHANGES.md
sdks/go/test/integration/integration.go
sdks/go/test/integration/primitives/state.go
sdks/go/test/integration/primitives/state_test.go

This adds state to CHANGES.md and fixes a few linting violations.
Part of #22736 …

Add Go stateful DoFns to CHANGES.md and fix linting violations

---

sdks/go/examples/cookbook/combine/combine.go
sdks/go/examples/cookbook/filter/filter.go
sdks/go/examples/cookbook/join/join.go
sdks/go/examples/cookbook/max/max.go
sdks/go/examples/cookbook/tornadoes/tornadoes.go

Shift to using the new generic registration for DoFns and emitters in the Go example under the cookbook directory.
the same as #22245 , #22249 …

Move Go examples under the cookbook directory to generic registration

---

runners/java-fn-execution/build.gradle
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/ReferenceCountingExecutableStageContextFactoryTest.java
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ExecutionStateSampler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ExecutionStateSamplerTest.java

This fixes the logging issue to include the transform id.
There is now a public unit test that will prevent a similar regression in the future. …

[fixes #22980] Migrate BeamFnLoggingClient to the new execution state sampler.

---

sdks/python/apache_beam/dataframe/io_it_test.py

Fix lint failure from #22616
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?b …

Minor: Fix lint failure

---

sdks/go/pkg/beam/io/databaseio/database.go
sdks/go/pkg/beam/io/databaseio/writer.go
sdks/go/pkg/beam/io/databaseio/writer_test.go

Prior to this change, `databaseio` couldn't handle the `postgres` driver as psql wants `($1,$2),($3,$4)` and not `(?,?)(?,?)` which `databaseio` was originally designed to use for templating.
I've added `valueTemplateGenerator` which encapsulates generation of the template string. It also has some sanity unit-tests.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.c …

Allows to use databaseio with postgres driver

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonService.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/PythonExternalTransformTest.java

Packages can be passed as a list of identifiers when creating an external PythonTransform, which will cause them to be installed in the auto-started environment as well as installed in the workers.
This fixes #22859. …

[BEAM-22859] Allow the specification of extra packages for external Python transforms.

---

runners/google-cloud-dataflow-java/build.gradle

Unsickbay testEventTimeTimerSetWithinAllowedLateness test

---

website/www/site/content/en/blog/beam-2.40.0.md

Add java Bigquery IO known issue to beam 2.40 release blogpost

---

.github/workflows/playground_deploy_examples.yml

Need to remove Authentication step from "playground_deploy_examples" pipeline …

[Playground] - Remove authentication step for Example pipeline

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/issue-rules.yml

Right now, we manually label all run-inference issues and its easy for things to slip through the cracks (I've noticed a few different issues with this problem this morning). I'd propose we use this label for any run-inference issues we create going forward. …

Add run-inference component for autolabeling

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/transforms/RunInference.java

Also adds a method so that users can manually specify the set of dependencies if needed.
This fixes #22860 
[![Build …

Updates Java RunInference to infer Python dependencies when possible

---

sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/Main.java
sdks/java/testing/test-utils/src/main/java/org/apache/beam/sdk/testutils/NamedTestResult.java
sdks/java/testing/test-utils/src/main/java/org/apache/beam/sdk/testutils/publishing/InfluxDBPublisher.java
sdks/java/testing/test-utils/src/test/java/org/apache/beam/sdk/testutils/publishing/InfluxDBPublisherTest.java

Generalize interface of InfluxDBPublisher in `test-utils` to support more use cases (in preparation for #22238). …

Generalize interface of InfluxDBPublisher to support more use cases (test-utils)

---

sdks/python/apache_beam/utils/subprocess_server.py

Reverts apache/beam#22654
gRPC 1.48.1 has been released and released Beam is working without any issues. So we should not need to include this change in future releases.

Revert "Remove subprocess.PIPE usage by using a temp file"

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

This change allows users to specify ClassLoaders to be used for loading JDBC drivers.  …

Allow users to pass ClassLoader to dynamically load JDBC drivers.

---

sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

Add tryClaim to when we stop reading from a partition. This results claiming the last element of the split, which enables us to stop processing data, preventing an exception when tracker.checkDone() is called …

Fix withCheckStopReadingFn to not cause the pipeline to crash

---

.github/workflows/build_playground_backend.yml

@MakarkinSAkvelon 
fixes #23031  …

[Playground] [Backend] Missing DB index creation step condition

---

sdks/python/apache_beam/tools/utils.py

Replaces `collections.namedtuple` with `typing.NamedTuple`, and declares typehints for callbacks.
[![Java …

Minor: Use typehints in benchmark utilities

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonService.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/PythonServiceTest.java

[BEAM-22856] PythonService Beam version compatibility

---

gradle/wrapper/gradle-wrapper.properties
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextRowCountEstimator.java

This fixes https://nvd.nist.gov/vuln/detail/CVE-2022-31156 for us …

Upgrade to Gradle 7.5.1

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/transforms/RunInference.java

Fixes RunInference test failure

---

.github/PULL_REQUEST_TEMPLATE.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java

Allowing more flexible precision for TIMESTAMP, DATETIME fields.

---

sdks/python/apache_beam/ml/inference/sklearn_inference_test.py

Adds back tests that were previously sickbayed. Only one was actually failing and its because `tempfile.NamedTemporaryFile` [wasn't keeping the file open correctly](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile).
Fixes #21449 …

Reenable run-inference tests on windows

---

sdks/go/pkg/beam/register/doc.go
sdks/go/pkg/beam/register/example_register_test.go

Thanks @pcoet for catching this …

Fix example registration input arity

---

sdks/python/apache_beam/examples/inference/README.md
sdks/python/apache_beam/examples/inference/pytorch_image_classification.py
sdks/python/apache_beam/examples/inference/pytorch_image_segmentation.py
sdks/python/apache_beam/examples/inference/pytorch_language_modeling.py
sdks/python/apache_beam/examples/inference/sklearn_mnist_classification.py

I walked through the inference examples - they're great, but I wanted to try to clean up some points of friction, confusion, or inconsistency that I found and streamline them a bit. Note, this is a little opinionated, definitely feel free to disagree if you think this makes things less clear in places.
Also removes the skip_header_lines arg when we're reading from txt files. I didn't get why we had that, but if there's a good reason we should doc it in the README.
Fixes #23056
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributin …

Clarify inference example docs

---

.github/workflows/stale.yml

This config will keep stale bot from closing issues like it has recently started to do (https://github.com/actions/stale#days-before-issue-close for config option) …

Keep stale action from closing issues

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
sdks/python/apache_beam/runners/portability/expansion_service_main.py
sdks/python/apache_beam/runners/portability/local_job_service_main.py

This works around bugs in dill regarding functions defined with eval and exec used for the PythonCallable types here.
Also fix flag that was placed on the wrong binary.
This is a follow-up to https://github.com/apache/beam/pull/22999 …

Use cloudpickle for Java Python transforms.

---

sdks/go/examples/wordcount/wordcount.go

Updated wordcount.go example:
* Edited comments for readability.
* Called out types of DoFns: structural and functional.
* Formatted comments to fit on 80-char lines (because it's prettier).
* Registered `formatFn`.
I tested the code in a different environment using the local runner, then copied it back into this file.
@damccorm
@lostluck
@jrmccluskey  …

clean up comments and register functional DoFn in wordcount.go

---

.github/workflows/build_playground_backend.yml
.github/workflows/build_playground_frontend.yml
.github/workflows/build_wheels.yml
.github/workflows/go_tests.yml
.github/workflows/java_tests.yml
.github/workflows/local_env_tests.yml
.github/workflows/python_tests.yml
.github/workflows/typescript_tests.yml

Fixes #23089
The concurrency condition works: https://github.com/Abacn/beam/actions/runs/3016483393
Get message like "Canceling since a higher priority waiting request for 'Java Tests @ Abacn:dumb' exists"
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS …

Auto-cancel old unit test Actions Runs

---

.github/workflows/typescript_tests.yml
sdks/typescript/test/io_test.ts

Cross-langauge tests in github actions.

---

CHANGES.md

Update CHANGES.md for 2.42.0 cut, and add 2.43.0 section …

Update CHANGES.md for 2.42.0 cut, and add 2.43.0 section

---

sdks/go/cmd/specialize/main.go
sdks/go/container/boot_test.go
sdks/go/pkg/beam/artifact/materialize_test.go
sdks/go/pkg/beam/artifact/stage.go
sdks/go/pkg/beam/artifact/stage_test.go
sdks/go/pkg/beam/core/runtime/harness/datamgr_test.go
sdks/go/pkg/beam/core/runtime/harness/statemgr_test.go
sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download_test.go
sdks/go/pkg/beam/core/util/symtab/symtab_test.go
sdks/go/pkg/beam/io/avroio/avroio_test.go
sdks/go/pkg/beam/io/fhirio/import_test.go
sdks/go/pkg/beam/io/filesystem/memfs/memory.go
sdks/go/pkg/beam/io/filesystem/util.go
sdks/go/pkg/beam/io/parquetio/parquetio.go
sdks/go/pkg/beam/options/gcpopts/options_test.go
sdks/go/pkg/beam/runners/dot/dot.go
sdks/go/pkg/beam/util/gcsx/gcs.go
sdks/go/test/load/util.go
sdks/go/test/regression/coders/fromyaml/fromyaml.go
sdks/go/test/regression/coders/fromyaml/fromyaml_test.go

`"io/ioutil"` has been deprecated since Go 1.16.
https://tip.golang.org/doc/go1.16#ioutil …

remove `"io/ioutil"` package

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/JsonUtils.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/JsonUtilsTest.java

This PR fixes #22768 by implementing JsonUtils with SimpleFunctions. …

Implement JsonUtils

---

.test-infra/jenkins/TpcdsDatabaseProperties.groovy
.test-infra/jenkins/job_PostCommit_Java_Tpcds_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Java_Tpcds_Flink.groovy
.test-infra/jenkins/job_PostCommit_Java_Tpcds_Spark.groovy
.test-infra/metrics/grafana/dashboards/perftests_metrics/TPC-DS_Dataflow_SQL.json
.test-infra/metrics/grafana/dashboards/perftests_metrics/TPC-DS_Flink_SQL.json
.test-infra/metrics/grafana/dashboards/perftests_metrics/TPC-DS_Spark_Classic_New_SQL.json
sdks/java/testing/tpcds/build.gradle
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/SqlTransformRunner.java
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/TpcdsOptions.java
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/TpcdsRun.java
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/TpcdsRunResult.java
sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/TpcdsUtils.java

Store TPC-DS metrics into BigQuery and InfluxDB:
- Collect the results and send them into BigQuery and InfluxDB for every benchmark job;
- Related Jenkins jobs are adjusted;
- Removed Spark 2 runner support (Spark 2 is deprecated in Beam);
- Added Grafana dashboards files;
- Added more TPC-DS queries, that should pass with Beam SQL, to run on Jenkins.
Fixes #21254  …

[TPC-DS] Store metrics into BigQuery and InfluxDB

---

website/www/site/content/en/get-started/from-spark.md

Resolves #22896
- add table-container-wrapper to tables Setup and Transform on [from-spark page ](https://beam.apache.org/get-started/from-spark/)
before:
after: …

[Website] Update from-spark page table content overflow

---

website/www/site/assets/scss/_footer.sass
website/www/site/assets/scss/_pillars.scss

Resolves #22522
- app padding to Apache Beam Features pillars-item class to create space from the borders
- change styles of footer logos so they don't stretch footer and whole page too much
before:
after: …

[Website] update homepage mobile styles

---

website/www/site/assets/scss/_ctas.sass

Resolves #22521
- change media-query max-width to ak-breakpoint-xl variable, so ctas button container have horizontal scroll to fit all buttons on screen when they overflow
____________________________________________________________________________________________________
before:
after: …

[Website] Update ctas button container on homepage

---

website/www/site/assets/scss/_global.sass

Resolves #22888
- add overflow to all `code` tags, so content would fit on screen on small mobile resoultions on pages like https://beam.apache.org/documentation/programming-guide/#1314-defining-a-urn or https://beam.apache.org/documentation/runners/spark 
____________________________________________________________________________________________________________________________________
before:
after: …

[Website] fix code tags content overflow

---

release/src/main/scripts/run_rc_validation.sh

Clean up Kafka Cluster and pubsub topic in rc validation script

---

sdks/python/apache_beam/io/gcp/experimental/spannerio_read_it_test.py

Changed SpannerIO tests so that they actually run and test something meaningful, as well as altering expected data so it would be the same going in and coming out of Spanner. …

Fix assertions in the Spanner IO IT tests

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
sdks/python/apache_beam/runners/portability/expansion_service_main.py

Cherry-pick https://github.com/apache/beam/pull/23111 into the release branch.

[release-2.42.0] Use existing pickle_library flag in expansion service.

---

runners/samza/src/main/java/org/apache/beam/runners/samza/translation/GroupByKeyTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/ParDoBoundMultiTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/PortableTranslationContext.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/ReshuffleTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/SamzaPortablePipelineTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/TranslationContext.java

Consolidate Samza TranslationContext and PortableTranslationContext

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaIOProvider.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSchemaTransformReadConfiguration.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSchemaTransformReadProvider.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaSchemaTransformReadProviderTest.java

I am removing several configuration options for Kafka Write SchemaTransform Configuration to simplify its usage (though we'll probably still need consumer configuration maps for authentication and so on).
For BQ I'm just adding a couple required lines.
GitHub …

Improvements to SchemaTransform implementations for BQ and Kafka

---

.github/ACTIONS.md

* Added detailed information in ACTIONS.md file regarding how the workflows need to be implemented in order to runs-on self-hosted runners.
Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly …

[GitHub Actions] - Added documentation in ACTIONS.md

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/CheckpointMarkImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/CloserReference.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/Refcounted.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/UnboundedReaderImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/UnboundedSourceImpl.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/CheckpointMarkImplTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/UnboundedReaderImplTest.java

Cherry-picks: https://github.com/apache/beam/pull/22762
Fixes: https://github.com/apache/beam/issues/23176
[![Build …

[release-2.42.0] Only close committers after all CheckpointMarks have gone away. 

---

sdks/go/test/build.gradle

Don't depend on java 11 docker container for go test

---

sdks/java/core/src/test/java/org/apache/beam/sdk/testing/TestStreamTest.java

Annotate stateful VR test in TestStreamTest with UsesStatefulParDo for https://github.com/apache/beam/pull/22620 (#22472). …

Annotate stateful VR test in TestStreamTest with UsesStatefulParDo (related to #22472)

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/SchemaCoderCloudObjectTranslator.java

Schema coders in cloud schema currently have a JSON representation of the schema.  By excluding insignificant whitespace, we reduce the amount of space that the JSON representation uses on disk. …

Exclude insignificant whitespace from cloud object

---

sdks/python/apache_beam/coders/coders_property_based_test.py
sdks/python/apache_beam/coders/row_coder.py
sdks/python/setup.py

I discovered this little library and decided to try it out to write a couple tests.
We may be able to use it to write some simple x-lang coder tests? : )
For info (and examples) of the library: https://hypothesis.readthedocs.io/en/latest/quickstart.html
fyi: @TheNeuralBit @robertwb 
GitHub …

Trying out property-based tests for Beam python coders

---

sdks/python/build-requirements.txt
sdks/python/setup.py

`Fix` #23227
Keep issue open for tracking.
[![Build …

Exclude protobuf 3.20.2

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java

Fix IllegalStateException in StorageApiWriteUnshardedRecords error handling

---

scripts/ci/issue-report/generateReport.js

Right now, we're doing a null/length check on `<issue>.assignee` to see if an issue is assigned, but the expected payload is:
```
{
assignee: {object} (possibly null)
assignees: {list of objects} (never null)
}
```
We can simplify/correct this by doing a single length check on `<issue>.assignees.length` …

Fix assignees check

---

release/src/main/scripts/cut_release_branch.sh
release/src/main/scripts/set_version.sh
release/src/main/scripts/verify_release_build.sh

Resolve script parsing error when changing from bash to sh.
https://unix.stackexchange.com/questions/45781/shell-script-fails-syntax-error-unexpected
Basically, unless "bash" is specifically invoked in ubuntu flavours of linux, it uses it's "dash" shell instead, which has very basic features.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/mast …

Resolve script parsing error when changing from bash to sh.

---

website/www/site/content/en/get-started/resources/learning-resources.md
website/www/site/content/en/get-started/resources/videos-and-podcasts.md
website/www/site/layouts/partials/section-menu/en/get-started.html

Resolves #22902
- move Learning Resources from documentation section to get-started
- add aliases to learning-resources.md, so now there is a redirect to correct path /get-started/resources/learning-resources even in case somebody uses /documentation/resources/learning-resources
- add [Spark page](https://beam.apache.org/get-started/from-spark/) to Quickstarts navigation menu
Pages with menus checked:
- https://beam.apache.org
- https://beam.apache.org/get-started/beam-overview/
- https://beam.apache.org/documentation/
- https://beam.apache.org/roadmap/
- https://beam.apache.org/community/
- https://beam.apache.org/contribute/
- https://beam.apache.org/blog/
- https://beam.apache.org/case-studies/
before:
after: …

[Website] update site navigation #22902

---

.test-infra/jenkins/job_PerformanceTests_KafkaIO_IT.groovy
.test-infra/kubernetes/kafka-cluster/05-kafka/configmap-config.yaml
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java

Test fix Kafka Performance test batch

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Bump up dataflow python container version to beam-master-20220914

---

examples/notebooks/beam-ml/run_custom_inference.ipynb
website/www/site/content/en/documentation/sdks/python-machine-learning.md

* Added some descriptions in pydoc to show how to run the inference using the custom models.
@rezarokni 
[![Build …

updated the pydoc for running a custom model on Beam

---

sdks/go/pkg/beam/runners/direct/gbk.go

Fix wrong comment

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicSequence.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/PeriodicSequenceTest.java

[Java SDK core] emit watermark from PeriodicSequence (#23301)

---

sdks/java/testing/nexmark/src/main/resources/log4j.properties

`DEBUG` shouldn't be used as default log level. Changing to use `WARN` instead. …

Fix Nexmark default log level

---

sdks/go/pkg/beam/core/runtime/graphx/coder.go

Fix lint errors in go sdk introduced in #23222  …

[Go SDK] lint fixes to go

---

runners/google-cloud-dataflow-java/build.gradle

Bump Java FnApi Container version to beam-master-20220923

---

CI.md

Added new PreCommit and PostCommit tables with placeholders to [CI.md](https://github.com/fernando-wizeline/beam/blob/gam-cimd-table/CI.md)
Also added a tip under GitHub Action Tips regarding the need of GCP credentials.
Hi @damccorm 
What do you think about this formatting?
Thanks for reviewing!
- [ x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
- [ x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close …

GA Migration PreCommit and PostCommit Tables in CI.md

---

runners/samza/src/main/java/org/apache/beam/runners/samza/SamzaPipelineExceptionContext.java
runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/OpAdapter.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/FlattenPCollectionsTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/GroupByKeyTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/ParDoBoundMultiTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/SplittableParDoTranslators.java
runners/samza/src/main/java/org/apache/beam/runners/samza/translation/WindowAssignTranslator.java
runners/samza/src/main/java/org/apache/beam/runners/samza/util/SamzaPipelineExceptionListener.java

Feature:
1. Added support for displaying the full tranform name with any stack-trace for Samza Runner
2. Added support for decorating stack traces with additional debugging information by adding a SamzaExceptionListener via the observer pattern
Example: Full transform name will be displayed with stack-trace on any exception thrown at runtime for ex
```
2022-08-02 11:45:30 ERROR [OpAdapter] [Samza StreamProcessor Container Thread-0] Op My Custom Operator/ParMultiDo(Anonymous) threw an exception during processing
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: My Custom Exception
at org.apache.beam.runners.samza.metrics.DoFnRunnerWithMetrics.withMetrics(DoFnRunnerWithMetrics.java:96) ~[beam-runners-samza-200.30.0.5.jar:?]
at …
```

Stack Trace Decoration for Beam Samza Runner

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/Date.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/DateTime.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/Time.java

Make the identifier of Date/Time/DateTime to be a public static field, @manuzhang  …

Make identifier of Date/Time/DateTime to be a public static field

---

CHANGES.md

Add ISSUE#23071 to CHANGES.md

---

.github/workflows/tour_of_beam_backend.yml
.github/workflows/tour_of_beam_backend_integration.yml
learning/tour-of-beam/backend/README.md
learning/tour-of-beam/backend/docker-compose.yml
learning/tour-of-beam/backend/function.go
learning/tour-of-beam/backend/integration_tests/api.go
learning/tour-of-beam/backend/integration_tests/client.go
learning/tour-of-beam/backend/integration_tests/function_test.go
learning/tour-of-beam/backend/integration_tests/local.sh
learning/tour-of-beam/backend/internal/entity.go
learning/tour-of-beam/backend/internal/fs_content/builders.go
learning/tour-of-beam/backend/internal/fs_content/load.go
learning/tour-of-beam/backend/internal/fs_content/load_test.go
learning/tour-of-beam/backend/internal/sdk.go
learning/tour-of-beam/backend/internal/sdk_test.go
learning/tour-of-beam/backend/internal/storage/adapter.go
learning/tour-of-beam/backend/internal/storage/datastore.go
learning/tour-of-beam/backend/internal/storage/index.yaml
learning/tour-of-beam/backend/internal/storage/schema.go
learning/tour-of-beam/backend/middleware.go
learning/tour-of-beam/backend/samples/api/get_content_tree.json
learning/tour-of-beam/backend/samples/api/get_sdk_list.json
learning/tour-of-beam/backend/samples/api/get_unit_content.json
learning/tour-of-beam/backend/samples/api/get_unit_content_full.json

A collection of minor changes in API
addresses #23400
Per-commit review is strongly suggested …

[Tour Of Beam] API adjustments

---

sdks/python/apache_beam/runners/worker/sdk_worker_main.py

Part of a documentation audit to add relevant gcloud docs links. …

Add relevant docs to Cloud Profiler exceptions.

---

sdks/python/apache_beam/runners/worker/statecache.py
sdks/python/apache_beam/runners/worker/statecache_test.py

Internal testing within Google discovered that weakref.proxy causes isinstance to raise an Exception and that certain Pandas types causes sys.getsizeof to fail.
See https://github.com/apache/beam/issues/23389 and https://github.com/liran-funaro/objsize/issues/6 for additional details.
Fixes #23389  …

Update state cache to not fail when measuring object sizes.

---

examples/notebooks/beam-ml/README.md
examples/notebooks/beam-ml/run_inference_pytorch.ipynb

This (a) fixes a small variable slipup (should be using 2 different models) and (b) fixes the readme link so that GitHub knows its actually a link …

Small pytorch notebook bug fix

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOTest.java

This PR addresses https://github.com/apache/beam/issues/23022:
- Adds validations to consider [Pub/Sub Resource limits](https://cloud.google.com/pubsub/quotas#resource_limits), which should be done over the entire message (payload + attributes) and not only the payload.
- Fixes a scenario in which `String.length()` was not enough to verify if attribute keys/values are over the limits, because they are specified in bytes.
- Adds test cases to cover existing gaps.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-rev …

PubsubIO - Improve limit validations to consider attributes

---

sdks/python/apache_beam/runners/interactive/interactive_environment.py

Part of a documentation audit to add relevant gcloud docs links. …

Add documentation link to the interactive environment

---

website/www/site/assets/js/language-switch-v2.js
website/www/site/assets/scss/_capability-matrix.scss
website/www/site/assets/scss/_global.sass
website/www/site/assets/scss/_playground.sass
website/www/site/assets/scss/_syntax-highlighting.scss
website/www/site/content/en/documentation/runners/flink.md
website/www/site/content/en/documentation/runners/jet.md
website/www/site/content/en/documentation/runners/spark.md
website/www/site/content/en/documentation/runners/twister2.md
website/www/site/layouts/shortcodes/language-switcher.html
website/www/site/layouts/shortcodes/playground.html
website/www/site/layouts/shortcodes/playground_snippet.html

We will soon replace many examples in the Beam doc with runnable embedded Playground instances. This PR adds the means for this:
1. **`playground` and `playground_snippet` Hugo shortcodes** that can be used like this:
```hugo
{{< playground height="700px" >}}
{{< playground_snippet language="java" example="SDK_JAVA/PRECOMPILED_OBJECT_TYPE_KATA/AggregationCount" >}}
{{< playground_snippet language="py" example="SDK_PYTHON/PRECOMPILED_OBJECT_TYPE_KATA/AggregationCount" >}}
{{< playground_snippet language="go" example="SDK_GO/PRECOMPILED_OBJECT_TYPE_EXAMPLE/MinimalWordCount" >}}
{{< playground_snippet language="scio" example="SDK_SCIO/PRECOMPILED_OBJECT_TYPE_EXAMPLE/MinimalWordCount" >}}
{{< /playground >}}
```
To save resources, each instance of the embedded playground serves all languages …

Send JavaScript messages to Playground iframes when switching the language in docs (#22361)

---

website/www/site/content/en/documentation/programming-guide.md

Expand Python cross language docs.

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_ML_RunInference_Benchmark_Tests.json

RunInference Benchmarks UI

---

sdks/python/setup.py

Remove redundant pip check which causes installation failure when using non-pip package managers like `poetry` or `pipenv`.  See https://github.com/python-poetry/poetry/issues/4888 for the issue the `pip` check causes in `poetry`. …

Relax `pip` check in setup.py to allow installation via other package managers (e.g. `poetry`)

---

.github/workflows/build_wheels.yml
sdks/python/apache_beam/coders/coder_impl.pxd
sdks/python/apache_beam/coders/coder_impl.py
sdks/python/apache_beam/coders/coder_impl_row_encoders.pyx
sdks/python/apache_beam/coders/row_coder_test.py
sdks/python/apache_beam/coders/standard_coders_test.py
sdks/python/apache_beam/tools/coders_microbenchmark.py
sdks/python/build-requirements.txt
sdks/python/scripts/generate_pydoc.sh
sdks/python/setup.py

This implements conversion directly from a dict of numpy arrays to a concatinated-row-encoded form, and vice versa.
This is generally 5-20x more efficient for encoding and 2-10x more efficient for decoding, depending on the row types and contents.
Benchmarks:
tiny_row, BatchRowCoderFalse, 1000 element(s)    : p. element median time cost: 3.79658e-06 sec, relative std: 5.82%
tiny_row, BatchRowCoderTrue, 1000 element(s)     : p. element median time cost: 3.9053e-07 sec, relative std: 6256.41%
large_row, BatchRowCoderFalse, 1000 element(s)   : p. element median time cost: 2.4623e-05 sec, relative std: 2.46%
large_row, BatchRowCoderTrue, 1000 element(s)    : p. element median time cost: 1.91796e-06 sec, relative std: 8.61%
nullable_row, BatchRowCoderFalse, 1000 element(s): p. element median …

Batch encoding and decoding of schema data.

---

sdks/python/apache_beam/typehints/opcodes.py
sdks/python/apache_beam/typehints/trivial_inference_test.py

Fix type inference for set/delete attr.

---

.test-infra/jenkins/README.md
.test-infra/jenkins/job_Java_Jmh.groovy
build.gradle.kts
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Add cron job to trigger Java JMH micro-benchmarks weekly on Sundays (addresses #22238). …

Add cron job to trigger Java JMH micro-benchmarks weekly 

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

JdbcIO fetchSize can be set to Integer.MIN_VALUE

---

learning/tour-of-beam/backend/internal/entity.go
learning/tour-of-beam/backend/internal/fs_content/builders.go
learning/tour-of-beam/backend/internal/fs_content/load.go
learning/tour-of-beam/backend/internal/fs_content/load_test.go
learning/tour-of-beam/backend/internal/fs_content/sdk_context.go
learning/tour-of-beam/backend/internal/sdk.go
learning/tour-of-beam/backend/internal/sdk_test.go
learning/tour-of-beam/backend/internal/storage/adapter.go
learning/tour-of-beam/backend/internal/storage/datastore.go
learning/tour-of-beam/backend/internal/storage/schema.go
learning/tour-of-beam/backend/samples/api/get_content_tree.json
learning/tour-of-beam/backend/samples/api/get_unit_content.json
learning/tour-of-beam/backend/samples/learning-content/python/module 1/intro-unit/unit-info.yaml

We have a convention between Playground and Tour Of Beam that ToB examples and snippets (and files and pc_objects too)
have the following key:
`<origin>_<SDK>_<name>` where
```
origin = "TB_EXAMPLES"
SDK = "SDK_JAVA" | "SDK_PYTHON" | "SDK_GO" | "SDK_SCIO"
name = /beam-playground/name
```
name is from an embedded yaml tag in a code example
duplicated also as taskName or solutionName in `learning-content/.../unit-info.yaml`
addresses #23421
To …

[Tour Of Beam] return taskSnippetId/solutionSnippedId

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffset.java

Beam 21465 add requires stable input to KafkaIO commit in finalize

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py

We are in the single digits of number of jobs/projects.  Old SDKs will continue to work. …

Require time-bound flag for non-UW streaming Python jobs for new SDKs.

---

website/www/site/assets/scss/_global.sass
website/www/site/assets/scss/_lists.scss
website/www/site/assets/scss/_playground.sass
website/www/site/assets/scss/_section-nav.scss
website/www/site/layouts/contribute/arrow_template.html
website/www/site/layouts/documentation/baseof.html
website/www/site/layouts/languages/baseof.html
website/www/site/layouts/runners/arrow_template.html

Resolves #22698
- change styles of main content and left menu. Left navbar is no longer positioned absolute, it's in the flow with main content, so left menu doesn't overlap footer in case when content of the page is too short and left menu contains too many bullet points
- limit width of playground, so it fits 
before:
after:
before:
after: …

[Website] fix navbar footer overlap

---

sdks/go/pkg/beam/transforms/filter/distinct_test.go

go test GA action permared since #22882 …

[Minor] Fix go fmt error

---

sdks/python/apache_beam/ml/inference/base.py
sdks/python/apache_beam/ml/inference/base_test.py
sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/apache_beam/ml/inference/sklearn_inference.py
sdks/python/apache_beam/ml/inference/tensorrt_inference.py

Revert "Add drop_example flag to the RunInference and Model Handler"

---

sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/package.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/__tests__/clusters/Clusters.test.tsx
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/src/clusters/Clusters.tsx

- Updated the delete_cluster usage with cleanup for the cluster manager widget to delete notebook-managed clusters.
- Updated the usage of rmwc Data Table to include DataTableHead and DataTableBody.
- Updated jest tests.
- Updated package version to 3.0.0. …

Prep sidepanel 3.0.0 release

---

.pre-commit-config.yaml
sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/tox.ini

addresses #22206 by adding supporting PyTorch versions in docstrings of PytorchModelHandlerTensor as well as a reminder in tox.ini to update those docstrings if the supported versions of PyTorch change. …

Documented supported PyTorch versions

---

.github/actions/gradle-command-self-hosted-action/action.yml
.github/actions/setup-self-hosted-action/action.yml

Several workflows fail due to the ~/.m2/settings.xml being created for each matrix intersection.
Adding this extra step in a common location so that it gets executed before the gradle command, fixes the issue.
R: @damccorm
- [ x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`). …

GA Migration Adding Removal of /.m2/settings.xml

---

learning/tour-of-beam/backend/internal/entity.go
learning/tour-of-beam/backend/internal/fs_content/load.go
learning/tour-of-beam/backend/internal/fs_content/load_test.go
learning/tour-of-beam/backend/internal/storage/adapter.go
learning/tour-of-beam/backend/internal/storage/schema.go
learning/tour-of-beam/backend/samples/api/get_content_tree.json
learning/tour-of-beam/backend/samples/learning-content/python/module 1/group/group-info.yaml

It is used on frontend for the state management
adresses #23442 
depends on #23419 …

[Tour Of Beam] export group.id in API

---

.github/workflows/issue-tagger.yml

This workflow recently started failing with `Error: HttpError: Resource not accessible by integration` (example: https://github.com/apache/beam/actions/runs/3152081896/jobs/5126846654, all runs: https://github.com/apache/beam/actions/workflows/issue-tagger.yml). This usually [stems from a permissions error](https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac), I'm guessing this is due to some sort of token scoping change, and am hoping explicitly granting the correct permissions will solve it. This is a good practice regardless. …

Give issue tagger permission to write issues

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_ML_RunInference_Benchmark_Tests.json

Update UID of the RunInference Benchmarks

---

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java

Improve error message in GcsUtil

---

sdks/typescript/src/apache_beam/coders/row_coder.ts
sdks/typescript/src/apache_beam/internal/environments.ts
sdks/typescript/src/apache_beam/transforms/external.ts
sdks/typescript/src/apache_beam/transforms/python.ts
sdks/typescript/src/apache_beam/transforms/window.ts
sdks/typescript/src/apache_beam/transforms/windowings.ts
sdks/typescript/test/docs/programming_guide.ts
website/www/site/content/en/documentation/io/built-in.md
website/www/site/content/en/documentation/programming-guide.md
website/www/site/data/io_matrix.yaml

This also fills out a couple of features, like logical types, that are needed for the examples. …

Add more typescript examples to the programming guide.

---

website/www/site/content/en/documentation/ml/online-clustering.md

The PR fixes the broken code link referenced in the online clustering documentation.  …

Fix broken link in online clustering documentation

---

website/www/check-links.sh
website/www/site/content/en/blog/adding-data-sources-to-sql.md
website/www/site/content/en/blog/dataframe-api-preview-available.md
website/www/site/content/en/blog/graduation-media-recap.md
website/www/site/content/en/blog/python-sdk-now-public.md
website/www/site/content/en/blog/six-months.md
website/www/site/content/en/contribute/committer-guide.md
website/www/site/content/en/contribute/release-guide.md
website/www/site/content/en/documentation/io/built-in/snowflake.md
website/www/site/content/en/documentation/sdks/java/testing/tpcds.md
website/www/site/content/en/get-started/beam-overview.md
website/www/site/content/en/get-started/from-spark.md
website/www/site/content/en/get-started/resources/learning-resources.md
website/www/site/content/en/get-started/resources/videos-and-podcasts.md
website/www/site/layouts/partials/footer.html
website/www/site/layouts/partials/header.html

Links to pages on the beam website over https where applicable …

[Website] update links to https

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/SimplifiedKinesisClient.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/SimplifiedKinesisClientTest.java

Correctly detect retryable TransientKinesisExceptions. `ResourceNotFoundException` and similar should not be retried  (fixes #23517) …

Correctly detect retryable TransientKinesisExceptions (fixes #23517)

---

website/www/site/content/en/get-started/_index.md

The right nav on the [Get Started](https://beam.apache.org/get-started/) page isn't rendering correctly. It doesn't play well with the combination of links and commas. I removed the links from the heading and created a list with links to the quickstarts within the section.
fixes #23542
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.tes …

Fixing right nav on Get Started page

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonService.java

Fix small error message typo

---

website/www/site/assets/scss/_global.sass
website/www/site/content/en/community/youtube-channel.md
website/www/site/content/en/get-started/resources/videos-and-podcasts.md

Resolves #23499
- update styles of iframes with video, so right-nav menu doesn't overlap them on pages https://beam.apache.org/community/youtube-channel/ and https://beam.apache.org/get-started/resources/videos-and-podcasts/
before:
after: …

[Website] fix right nav-menu and videos overlap

---

website/www/site/assets/scss/_local.scss
website/www/site/assets/scss/main.scss
website/www/site/content/en/documentation/sdks/python-dependencies.md

Resolves #23478
- add word-break rule to link, so it doesn't stretch the page on mobile resolutions
- add scss file for future minor local changes
before:
after: …

[Website] update python-dependencies.md link 

---

sdks/python/apache_beam/runners/worker/sdk_worker.py
sdks/python/apache_beam/runners/worker/statecache.py
sdks/python/apache_beam/runners/worker/statecache_test.py

Also record statistics for the cost of performing a load. …

[fixes #23000] Update the Python SDK harness state cache to be a loading cache

---

.github/workflows/build_wheels.yml

This GitHub Action has been failing: https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule
Change tested on fork branch
Before change: https://github.com/Abacn/beam/actions/runs/3221975519
After change: https://github.com/Abacn/beam/actions/runs/3221982893 …

Fix permission for Build python wheel branch_repo_nightly step

---

sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/README.md

fixes #23488. With v3.0.0 released, updated the requirements table to reflect the change. …

Updated README for jupyterlab-sidepanel

---

website/www/site/content/en/documentation/programming-guide.md

I fixed sample code of `distribution` metrics in golang programming guide.
https://pkg.go.dev/github.com/apache/beam/sdks/v2/go/pkg/beam#Distribution …

[Website] fix distribution example in golang guide

---

sdks/python/apache_beam/utils/multi_process_shared.py
sdks/python/apache_beam/utils/multi_process_shared_test.py
sdks/python/setup.py

MultiProcessShared is used to share a single object across processes.
For example, one could have the class::
class MyExpensiveObject(object):
def __init__(self, args):
[expensive initialization and memory allocation]
def method(self, arg):
...
One could share a single instance of this class by wrapping it as::
my_expensive_object = MultiProcessShared(lambda: MyExpensiveObject(...))
which could then be invoked as::
my_expensive_object.method(arg)
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easie …

Add a multi-process shared utility.

---

website/www/site/content/en/blog/review-input-streaming-connectors.md
website/www/site/content/en/documentation/io/built-in/snowflake.md
website/www/site/content/en/documentation/io/connectors.md

Replace website references to deprecated aws / kinesis modules with more recent aws2 module. …

Replace website references to deprecated aws / kinesis modules with more recent aws2 module.

---

sdks/go/pkg/beam/core/runtime/harness/harness.go

Remove unmarshalling plans from the harness control lock critical section. A first step to resolving #23335 
This removes a large blocking operation from holding the lock unnecessarily, which exacerbates handling GRPC messages since more than the ProcessBundle methods can block on that lock, which should be used only for quick map protection operations. …

[Go SDK] Don't construct plans in lock section.

---

.test-infra/jenkins/job_PostCommit_Python.groovy

Currently sometimes tests timeout after 4 hrs.
Long term: test suite will be split up and migrated to GH actions. …

Increase Python PostCommit timeout.

---

.github/workflows/playground_deploy_examples.yml
playground/infrastructure/cd_helper.py
playground/infrastructure/checker.py
playground/infrastructure/ci_cd.py
playground/infrastructure/ci_helper.py
playground/infrastructure/config.py
playground/infrastructure/datastore_client.py
playground/infrastructure/helper.py
playground/infrastructure/test_cd_helper.py
playground/infrastructure/test_ci_cd.py
playground/infrastructure/test_ci_helper.py
playground/infrastructure/test_datastore_client.py
playground/infrastructure/test_helper.py
sdks/go/examples/stringsplit/stringsplit.go

adresses #23039
Make separate Playground CI/CD steps for Playground and Tour Of Beam examples.
For that, we introduce 2 command line parameters for ci_cd.py:
* --subdirs: a list of dirs to search for examples, relative to BEAM_PROJECT_ROOT
* --origin: PG_EXAMPLES or TB_EXAMPLES
Sample CI/CD run step:
```
export BEAM_ROOT_DIR=../../
export SUBDIRS="learning/katas sdks examples"
python3 ci_cd.py --step CD --sdk SDK_JAVA --origin PG_EXAMPLES --dirs $SUBDIRS
```
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewe …

[Playground][Tour Of Beam] Datastore entities split by origin

---

sdks/python/apache_beam/examples/cookbook/bigtableio_it_test.py

Extend a timeout to create a bt cluster.

---

website/www/site/content/en/documentation/runners/direct.md

addresses #21349
Adding information to [Using the Direct Runner](https://beam.apache.org/documentation/runners/direct/) page:
The Direct Runner is not designed for production pipelines, because it’s optimized for correctness rather than performance. The Direct Runner must fit all user data in memory, whereas the Flink and Spark runners can spill data to disk if it doesn’t fit in memory. Consequently, Flink and Spark runners are able to run larger pipelines and are better suited to production workloads. …

Added content: The direct runner is not suited to production pipelines

---

website/www/site/data/en/join_beam.yaml

fixes #21245
Adding information about and a link to the Beam content in Towards Data Science to the community page, collocated with the link to the Beam section on StackOverflow. …

Adding beam blog info to the Community page

---

release/src/main/scripts/publish_github_release_notes.sh

This will include auto-generated notes appended after the "body" that we pass in. …

Update publish_release_notes to generate PR list

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Bump Legacy dataflow container image tag

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/PipelineTranslator.java

Align translation logging for Spark dataset runner with rdd runner for better comparison of the two. …

Align translation logging for Spark dataset runner with rdd runner

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/SparkSessionFactory.java

This prevents the factory to fail if using `local[*]` …

Fix SparkSessionFactory to not fail when using Spark master local[*]

---

learning/tour-of-beam/backend/README.md

Described basic usage scenario and deployment
Depends on #23349 …

[Tour Of Beam] README update

---

.test-infra/jenkins/job_PerformanceTests_PubsubIO_Python.groovy
sdks/python/apache_beam/io/gcp/pubsub_io_perf_test.py
sdks/python/apache_beam/testing/load_tests/build.gradle

Fixes permared test beam_PerformanceTests_PubsubIOIT_Python_Streaming …

Fix  beam_PerformanceTests_PubsubIOIT_Python_Streaming

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.42.0.md
website/www/site/content/en/get-started/downloads.md

2.42.0 Release Blog Post 

---

website/www/check-links.sh

This should speed up the workflow significantly, and get it to pass most of the time. …

Fixes #23627: Speed up website checks

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoIT.java

This change suppresses a build error, to work around https://github.com/apache/beam/issues/23666. …

Suppress a FloatingPointLiteralPrecision error

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py

Better error for disabling runner v2 with cross language pipelines.

---

sdks/python/apache_beam/examples/wordcount_it_test.py
sdks/python/apache_beam/options/pipeline_options.py

Update scopes to match the existing set and update test to clear credentials during failure

---

.github/workflows/assign_milestone.yml

This will automatically assign any closed issues to the milestone of the currently in development version of Beam. This will ensure that closed issues cleanly map to Beam versions.
Example of this working when the milestone needs to be created - https://github.com/damccorm/beam/issues/128
Example of it working when the milestone already exists - https://github.com/damccorm/beam/issues/129 …

Add workflow to update milestone on issue close

---

website/www/site/content/en/documentation/ml/data-processing.md
website/www/site/content/en/documentation/ml/overview.md
website/www/site/layouts/partials/section-menu/en/documentation.html

This PR adds a data processing page for AI/ML pipelines under documentation on the website. …

add website page about data processing for ML

---

sdks/python/apache_beam/transforms/combiners.py

Include CombineFn's in __all__

---

.test-infra/jenkins/job_PerformanceTests_InfluxDBIO_IT.groovy

Spins up influx db and runs test for direct runner.  …

[23286] Run beam_PerformanceTests_InfluxDbIO_IT on beam-perf node

---

.test-infra/jenkins/job_Publish_SDK_Image_Snapshots.groovy

[23697] Add java 11 home to jenkins test

---

CHANGES.md
sdks/go/pkg/beam/transforms/xlang/dataframe/dataframe.go
sdks/go/pkg/beam/transforms/xlang/python/external.go

This PR enables use of automatic expansion service for dataframe transform added in #23450  …

[Go SDK]: Enable automatic python expansion service 

---

sdks/python/apache_beam/coders/coder_impl.pxd

This eases the build for anything cimporting coder_impl. …

Remove numpy C API dep from public declarations.

---

sdks/go/pkg/beam/core/runtime/xlangx/expand.go
sdks/go/pkg/beam/core/runtime/xlangx/registry.go

Adds the user-facing part of adding extra packages to automated python expansion service added in #23582 
[![Build …

[Go SDK] add expansion service option for extra packages

---

website/www/site/content/en/documentation/sdks/python-machine-learning.md

This PR does 2 things:
1. Moves the Tensorflow documentation next to the sklearn and pytorch documentation.
2. Moves the keyedModel handler documentation to it's own section (instead of being TF specific).
The reason for #2 is that any framework may want to use keyed examples (not just TF). …

Move Tensorflow Documentation

---

learning/tour-of-beam/frontend/lib/pages/tour/widgets/content.dart
learning/tour-of-beam/frontend/lib/pages/tour/widgets/unit_content.dart
learning/tour-of-beam/frontend/pubspec.lock
learning/tour-of-beam/frontend/pubspec.yaml
playground/frontend/playground_components/lib/src/constants/colors.dart
playground/frontend/playground_components/lib/src/constants/sizes.dart
playground/frontend/playground_components/lib/src/theme/theme.dart
playground/frontend/playground_components/pubspec.yaml

[ToB] [Frontend] Unit Content markdown styles (#23592)

---

.github/ACTIONS.md
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/workflows/self-assign.yml

Add a command to allow non-committers to reopen any issue …

Add reopen issue command

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Bump up python container versions.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Revert bigdataoss version upgrade

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py37/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt

Generated according to the instructions [here](https://beam.apache.org/contribute/release-guide/#3-update-base-image-dependencies-for-python-container-images). …

Updating Python dependencies for the 2.43.0 release

---

sdks/python/container/run_validatescontainer.sh

Update the timeout in ValidatesContainer suite.

---

sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/SortValues.java

The `SortValues` transform sorts elements based on their byte representation, to mirror the behavior of `GroupByKey`, and as required by portability.
Fixes #20109 …

Verify that secondary key coder is deterministic in SortValues

---

sdks/go/pkg/beam/core/runtime/xlangx/expansionx/process.go
sdks/go/pkg/beam/transforms/xlang/python/external.go

fixes few go lints encountered in recent import …

[Go SDK] Fix lints in recent import

---

sdks/python/apache_beam/internal/gcp/auth.py
sdks/python/apache_beam/io/gcp/gcsio.py

Update GcsIO initialization to support converting input parameters to PipelineOptions for authentication

---

sdks/python/apache_beam/internal/gcp/auth.py
sdks/python/apache_beam/io/gcp/gcsio.py

Needed to not break Python authentication with GCP on workers.
fixes #23764 …

[cherry-pick][release-2.43.0] Update GcsIO initialization to support converting input parameters to PipelineOptions for authentication (#23766)

---

.test-infra/jenkins/Flink.groovy
.test-infra/jenkins/job_LoadTests_Combine_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_coGBK_Flink_Python.groovy
.test-infra/jenkins/job_PostCommit_Python_Chicago_Taxi_Example_Flink.groovy

Use Flink 1.13 for load tests

---

sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/pubsub/PubsubTableProviderIT.java

This appears to have been fixed by #22612
I did not witness a flake in 100 runs like so:
```
for i in `seq 1 100` ; do
echo "RUN $i"
./gradlew --quiet :runners:direct-java:cleanTest
./gradlew --quiet :sdks:java:extensions:sql:integrationTest \
--tests 'PubsubTableProviderIT.testSQLSelectsArrayAttributes[0]'
done
```
fixes #20937
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](htt …

Re-enable PubsubTableProviderIT.testSQLSelectsArrayAttributes

---

sdks/python/apache_beam/typehints/schemas.py

CloudPickle notices that schema_pb2 (from the closure of the locally defined __reduce__ method) is not importable under its declared name (org.apache.beam...) and tries to pickle it (which fails due to proto classes themselves being unpicklable).  This avoids that error by moving it out. …

Avoid pickling unstable reference to moved proto classes.

---

sdks/python/apache_beam/typehints/schemas_test.py

Unskip test_generated_class_pickle for cloudpickle.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/options/ExecutorOptions.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptions.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Rollforward fix, since other PRs depended on the rolled-back PR.

Revert 23234: issue #23794

---

sdks/java/testing/jpms-tests/build.gradle

The Spark 3 dependency version is out of date, removing respective dependencies as they are not required.
[![Build …

Remove unnecessary dependencies from jpms test

---

website/www/site/content/en/contribute/release-guide.md
website/www/site/content/en/documentation/sdks/java/testing/nexmark.md

Update remaining pointers to Spark runner to Spark 3 module (addresses #23728) …

Update remaining pointers to Spark runner to Spark 3 module 

---

runners/google-cloud-dataflow-java/build.gradle

Bump dataflow java fn container version to  beam-master-20221022

---

.github/codecov.yml
sdks/python/apache_beam/testing/benchmarks/nexmark/nexmark_launcher.py

Publish Python nexmark metrics to influxdb. …

Publish Python nexmark metrics to influxdb

---

sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipelineOptions.java

Pipelines in beam_PostCommit_Java_VR_Dataflow_V2_Streaming timeout, but complete successfully.  …

Increate timeout for test pipelines

---

sdks/python/setup.py

Updated ipywidgets from v7 to v8 to work with JupyterLab. …

Updated ipywidgets

---

sdks/python/apache_beam/typehints/schemas.py

CloudPickle notices that schema_pb2 (from the closure of the locally defined __reduce__ method) is not importable under its declared name (org.apache.beam...) and tries to pickle it (which fails due to proto classes themselves being unpicklable).  This avoids that error by moving it out.
Cherry-picking https://github.com/apache/beam/pull/23739 to the 2.43.0 release branch. …

Avoid pickling unstable reference to moved proto classes. (#23739)

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/MoreFutures.java
sdks/java/core/src/test/java/org/apache/beam/sdk/util/MoreFuturesTest.java

This resolves ConcurrentModificationExceptions seen within WriteFiles and other places that use MoreFutures.allAsList* methods.
Fixes #23809 …

Allow MoreFutures.allAsList/allAsListWithExceptions to have the passed in list to be mutated

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/MoreFutures.java
sdks/java/core/src/test/java/org/apache/beam/sdk/util/MoreFuturesTest.java

This resolves ConcurrentModificationExceptions seen within WriteFiles and other places that use MoreFutures.allAsList* methods.
Fixes #23809 …

[release-2.43.0][cherry-pick] Allow MoreFutures.allAsList/allAsListWithExceptions to have the passed in list to be mutated (#23811)

---

.asf.yaml

adding rshamunov to beam collaborators …

Adding Ruslan Shamunov to collaborators

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

This allows turning off checkerframework still by `-PenableCheckerFramework=false` …

Enable checkerframework by default

---

sdks/java/maven-archetypes/gcp-bom-examples/src/main/resources/archetype-resources/pom.xml

This is for addressing #23813 
The test should pass after the next set of Beam SNAPSHOTs are built. …

Adds a dependency to Python Multi-language library to the GCP Bom examples arche-type

---

website/www/site/layouts/partials/header.html

Get started on the top nav should go to https://beam.apache.org/get-started
See https://github.com/apache/beam/issues/21537 …

Fixing Get Started header link

---

sdks/python/apache_beam/io/kinesis.py

This PR fixes issue #23693 as discussed with @mosche. There is a bug where the `ReadDataFromKinesis` class references the wrong URN, preventing it to start the expansion service.  …

Update ReadDataFromKinesis URN to registered URN

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_schema_tools.py

Cherry pick #23784 onto release branch 2.43.0
Fixes https://github.com/apache/beam/issues/23760 …

[cherry-pick][release-2.43.0] Avoid Circular imports related to bigquery_schema_tools

---

sdks/go/pkg/beam/core/metrics/dumper_test.go
sdks/go/pkg/beam/core/metrics/metrics_test.go
sdks/go/pkg/beam/core/metrics/store_test.go

The metrics package had 41.6% code coverage, and it was desired to increase it to at least 50%.
This PR adds some tests to increase the coverage to 59%
Fixes #21385 …

[Go SDK] Add tests to the metrics package

---

website/www/site/content/en/documentation/sdks/python-machine-learning.md

Does 3 documentation updates.
1. Removes sample code in the documentation and instead points user to notebook for TFX.
2. Adds links to sklearn and PyTorch notebooks.
3. Wrapping ModelHandlers in KeyedModelHandler is documentated in two places. This PR merges the documentation into a single location. …

Updated documentation to point to notebooks instead of having samples

---

website/www/site/content/en/contribute/release-guide.md

* Include link to Go Package Doc for RCs in the Vote email.
* Be consistent about using RELEASE_VERSION as the env variable for the release. …

Post 2.42.0 Updates to release guide

---

website/www/site/content/en/get-started/downloads.md

Instructions for Go were missing, so this adds how to depend on beam in Go. …

Add Go usage instructions to download page.

---

sdks/java/io/neo4j/src/test/java/org/apache/beam/sdk/io/neo4j/Neo4jIOIT.java

[BEAM-23815] Fix Neo4j tests.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageTableSource.java

Part of #20970
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&e …

BigQueryStorageTableSource: Use the DatasetService that will be auto-closed

---

CHANGES.md

In addition to #23833, update CHANGES.md with more details. …

[23832] nit: update CHANGES.md

---

website/www/site/content/en/documentation/programming-guide.md

addresses #21022
In the section "Using Schema Transforms" of the Python programming guide, there are missing examples.  I've written the examples for top-level fields, nested fields and wildcards …

 adding examples in schema transforms section of programming guide for python  (changes for issue #21022)

---

website/www/site/assets/scss/_calendar.scss
website/www/site/assets/scss/_local.scss
website/www/site/layouts/index.html

Resolves #22694
- on small mobile resolutions (max-width: 374px) make all 3 calendar blocks ( tweets, blogs, upcoming events) width no more than 260px, so they don't stretch the page or cling to the edges
- add horizontall scroll to upcoming events section on max-width: 374px
____________________________________________________________________________________________________________________
before:
after:  …

[Website] update upcoming-events calendar section

---

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py

This is follow-up from https://github.com/apache/beam/pull/23558. …

More bigquery native sink cleanup.

---

website/www/site/content/en/documentation/ml/overview.md

This PR aims to add brief description about different end-to-end pipelines in the overview page.  …

Add brief descriptions about end-to-end ML Pipelines

---

CHANGES.md
sdks/java/extensions/sql/jdbc/build.gradle
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamCalcRel.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/utils/CalciteUtils.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamComplexTypeTest.java

Fix Beam Sql Calcite Util does not support CHAR, VARCHAR, BINARY, VARBINARY

---

playground/frontend/playground_components/lib/src/controllers/playground_controller.dart
playground/frontend/playground_components/lib/src/controllers/snippet_editing_controller.dart
playground/frontend/playground_components/pubspec.yaml
playground/frontend/pubspec.lock

This PR:
- Resolves #21125
- Allows to copy folded text
- Fixes a bug with folding the default Go example
[![Build …

Upgrade Akvelon editor (#23415)

---

website/www/site/assets/scss/_case_study.scss
website/www/site/content/en/case-studies/akvelon.md
website/www/site/layouts/case-studies/list.html

NB!!! Merge this PR first before https://github.com/apache/beam/pull/23899
- add hugo to the additional cards layout, so they could be clickable and lead to certain webpages
- add link to the akvelon logo description
- add optional property `hasLink ` to md logos  in frontmatter. If you need your logo to be a link on hover, add this property to your case-study. If you need card description to be shown on hover, skip this property
before:
after:
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make- …

[Website] Update additional case studies

---

website/www/site/assets/js/shuffle-elements.js
website/www/site/assets/scss/_case_study.scss
website/www/site/layouts/case-studies/list.html

- add function that shuffles logos on [case-study page](https://beam.apache.org/case-studies/)
before:
after: …

[Website] add shuffle to logos

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java

Fix javadoc link, move off of deprecated `getProperties()` method to `getPropertiesOrThrow()` …

Clean-up DatastoreV1.java

---

.test-infra/jenkins/job_PostCommit_Java_Jpms_Dataflow_Java11.groovy
.test-infra/jenkins/job_PostCommit_Java_Jpms_Dataflow_Java17.groovy

This reverts commit 4adde54edc4a1aa01b8a20d5b1dc7f268ca09342. …

[release-2.43.0] Revert accidental push

---

release/src/main/scripts/mass_comment.py

This test suite seems to be disabled: https://ci-beam.apache.org/job/beam_PostCommit_Java11_Examples_Dataflow_Portability/
I suspect what we want to test here is the same as "Run Java 11 Examples on Dataflow Runner V2" which is running fine: https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Dataflow_V2_java11/ …

Remove Dataflow Portability test suite from mass_comment.py

---

.test-infra/metrics/sync/github/sync.py

When I was configuring my local environment of the metrics dashboard, I found out that some JSON data for GH PRs was incomplete, so the code breaks with an error, the sync is cycled, and never finishes.
Skipping the bad JSON and letting the sync continue would be better. …

Small fix to sync gh prs metrics when a json data is incomplete

---

sdks/python/apache_beam/typehints/arrow_type_compatibility.py
sdks/python/apache_beam/typehints/arrow_type_compatibility_test.py

Part of https://github.com/apache/beam/issues/23454
This PR re-uses much of the logic from #23455 to add a `pa.Array` `BatchConverter` implementation.
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+T …

Add support for converting to/from pyarrow Arrays

---

website/www/site/content/en/case-studies/kio.md

- update layout of [kio page](https://beam.apache.org/case-studies/kio/)
before:
after: …

[Website] update kio page layout

---

examples/multi-language/README.md
website/www/site/content/en/documentation/sdks/java-multi-language-pipelines.md

Updates Multi-language Java examples documentation

---

website/www/site/content/en/documentation/programming-guide.md
website/www/site/layouts/partials/section-menu/en/documentation.html

Initial draft of Batched DoFn user guide

---

sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py

These have been flaking at an extremely high rate (plenty of evidence in https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/ and https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/) and are keeping us from getting any signal from the python precommit.
Related to #23944
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test …

Disable flaky fn_api_runner tests

---

sdks/python/apache_beam/transforms/core.py

Improve Iterator error message

---

sdks/typescript/src/apache_beam/runners/direct_runner.ts
sdks/typescript/src/apache_beam/transforms/windowings.ts
sdks/typescript/src/apache_beam/utils/service.ts
sdks/typescript/src/apache_beam/worker/data.ts
sdks/typescript/src/apache_beam/worker/external_worker_service.ts
sdks/typescript/src/apache_beam/worker/logging.ts
sdks/typescript/src/apache_beam/worker/operators.ts
sdks/typescript/src/apache_beam/worker/worker.ts
sdks/typescript/src/apache_beam/worker/worker_main.ts
sdks/typescript/test/io_test.ts
sdks/typescript/test/worker_test.ts

Correctly capture log levels and attach stage information.

---

sdks/typescript/src/apache_beam/pvalue.ts
sdks/typescript/src/apache_beam/runners/direct_runner.ts
sdks/typescript/src/apache_beam/runners/portable_runner/runner.ts
sdks/typescript/src/apache_beam/runners/runner.ts
sdks/typescript/src/apache_beam/testing/proto_printing_runner.ts
sdks/typescript/src/apache_beam/transforms/pardo.ts
sdks/typescript/src/apache_beam/worker/metrics.ts
sdks/typescript/src/apache_beam/worker/operators.ts
sdks/typescript/src/apache_beam/worker/pardo_context.ts
sdks/typescript/src/apache_beam/worker/worker.ts
sdks/typescript/test/io_test.ts
sdks/typescript/test/primitives_test.ts

Add basic counter support to the typescript SDK.

---

website/www/site/content/en/blog/beam-starter-projects.md
website/www/site/data/authors.yml

Add blog post for Beam starter projects.
R: @aaltay, @pcoet, @VeronicaWasson  …

Beam starter projects blog post

---

.github/workflows/typescript_tests.yml
sdks/typescript/src/apache_beam/runners/runner.ts
sdks/typescript/test/docs/programming_guide.ts
sdks/typescript/test/io_test.ts
sdks/typescript/test/primitives_test.ts

Enable more portable-runner requiring tests.

---

website/www/site/assets/scss/_case_study.scss

- change width of case-study-card on mobile devices on https://beam.apache.org/case-studies/
before:
after: …

[Website] change case studies page mobile layout

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

Enforce splitting invariants by ensuring split state is reset in the same synchronized block as window index increments. 

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

Multiplexing was put into the PCollectionConsumerRegistry a long time ago and this seems to have been missed during that migration. This is towards issue #21250
Benchmark results show that this is noise.
New code:
```
Result org.apache.beam.fn.harness.jmh.ProcessBundleBenchmark.testLargeBundle:
988.040 ±(99.9%) 36.859 ops/s [Average]
(min, avg, max) = (939.097, 988.040, 1031.625), stdev = 34.478
CI (99.9%): [951.181, 1024.899] (assumes normal distribution)
```
Old code:
```
Result "org.apache.beam.fn.harness.jmh.ProcessBundleBenchmark.testLargeBundle":
984.372 ±(99.9%) 11.445 ops/s [Average]
(min, avg, max) = (965.547, 984.372, 1000.351), stdev = 10.705
CI (99.9%): [972.928, 995.817] (assumes normal distribution)
``` …

[#21250] Trivial removal of loop over something that always has one element

---

sdks/python/apache_beam/ml/inference/base.py

Editorial review of the ML base API descriptions …

Editorial review of the ML base API descriptions

---

website/www/site/data/authors.yml

Mini-PR just to update my Twitter handle for blog posts author name
[![Java …

Update my Twitter handle

---

CHANGES.md
website/www/site/content/en/blog/beam-2.42.0.md

Retroactively announce Batched DoFn support in 2.42.0 Blog

---

CHANGES.md

Add CHANGES.md listing for pipeline level resource hints, set via a flag for the Go SDK (#23893).
Correct formatting of adjacent python related change. …

[Go] Add pipeline resource hints to CHANGES.md

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryAvroUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryAvroUtilsTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java

As discussed in issue #23541, `BigQueryAvroUtils` does not correctly generate the Avro schema for certain BigQuery data types, such as `Numeric` and `BigNumeric`. This PR address this issue and generates the correct avro schema. This further helps in transformation of GenericRecord -> TableRow, via `convertGenericRecordToTableRow` function, that rely on these BigQuery data types.
R: @steveniemitz @kennknowles @vachan-shetty …

Handle Avro schema generation for logical data types in BigQueryAvroUtils

---

playground/backend/containers/java/Dockerfile

fixes #24058
We are fixing the base image for java runner container base beam java SDK image version and bumping the grpc vendor version …

Fix dependency mismatch in Playground Java runner 

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/SparkStructuredStreamingRunner.java

Enable projection pushdown for Spark dataset runner to match behavior or RDD runner, see https://github.com/apache/beam/pull/17107. …

[Spark Dataset runner] Enable projection pushdown for Spark dataset runner

---

sdks/go/pkg/beam/io/filesystem/s3/s3.go
sdks/go/pkg/beam/io/filesystem/s3/util.go
sdks/go/pkg/beam/io/filesystem/s3/util_test.go
sdks/go/pkg/beam/options/jobopts/options.go
sdks/go/pkg/beam/options/jobopts/options_test.go
sdks/go/pkg/beam/options/resource/hint.go
sdks/go/pkg/beam/options/resource/hint_test.go

A few recent changes introduced lowercase initialisms. This keeps these consistent with the rest of our codebase …

Convert initialisms to all caps

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/runtime/xlangx/expand.go

Cherry-pick for #24066. Fixes #24065 and unblocks RC1 …

[cherry-pick][Go SDK] Fix Dataframe wrapper issue 

---

.github/issue-rules.yml

We have two semantically equivalent labels, one of them has only 7 issue tagged. let's remove test-failures in favor of 'failing test' https://github.com/apache/beam/issues?q=is%3Aissue++sort%3Aupdated-desc+label%3A%22failing+test%22+ https://github.com/apache/beam/issues?q=is%3Aissue++sort%3Aupdated-desc+label%3A%22test-failures%22+ …

Remove a duplicate label

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java

Current: https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.html
See also links not working and has wrong html; the paragraph after see also does not render links; code snippets missing a right brace} …

Fix FhirIO javadoc format broken

---

.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh

This is the expected outcome from running this script today: https://gist.github.com/pabloem/95cff6aca3e17fd09f4c792a54d14dde
Should we run it? …

Improving stale container cleanup script

---

learning/tour-of-beam/backend/README.md
learning/tour-of-beam/backend/integration_tests/client.go
learning/tour-of-beam/backend/middleware.go

Essentially, done as recommended in [CF docs](https://cloud.google.com/functions/docs/samples/functions-http-cors#code-sample), but kept only relevant headers:
```
Access-Control-Allow-Methods: (GET|POST)
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: *
Access-Control-Max-Age: 3600
```
- simulate pre-flight requests in integration test for every endpoint
- updated README
addresses #24087 …

[Tour Of Beam] handle CORS pre-flight requests

---

playground/backend/containers/java/Dockerfile

fixing docker linter error.
Linter is complaining about a perfectly valid Dockerfile syntax.
Redeclaring the ARG value to fix broken GA. …

[Playground] [Task] Fixing Dockerfile linter error

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryQueryHelper.java

cherry pick #24041: fixing BigQuery Query retry vulnerability

---

runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/OpAdapter.java
runners/samza/src/main/java/org/apache/beam/runners/samza/util/SamzaPipelineExceptionListener.java

Custom Exception Listeners need access to pipeline options to get info related to the pipeline to decorate stack traces, this change will wire SamzaPipelineOptions to the SamzaExceptionListener interface. …

Wire SamzaPipelineOptions to Exeption listener interface

---

sdks/python/apache_beam/ml/inference/__init__.py

Right now, its not clear that TFX is supported from https://beam.apache.org/releases/pydoc/2.42.0/apache_beam.ml.inference.html#submodules - this fixes that problem …

Add TFX support in pydoc

---

.github/workflows/playground_examples_ci.yml

It got broken after #23879 was merged
Task to fix it: #24120 …

[Playground] temporarily disable Playground Examples CI

---

sdks/go.mod
sdks/go.sum
sdks/go/test/integration/io/xlang/jdbc/jdbc_test.go

Resolves the issue due to testcontainer dependency upgrade at #23821  …

[Go SDK] Resolve testcontainer dependency upgrade

---

.test-infra/jenkins/job_CleanUpPrebuiltSDKImages.groovy
.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh

Followup of #24040 and Fixes #24038
* prebuilt_beam_sdk/beam_python_prebuilt_sdk no longer exists in gcr.io Add correct paths to cleanup
These are mostly generated by validate_runner and other postcommit test jobs:
** jenkins/*
https://github.com/apache/beam/blob/a4a94da1936d8cd2f8d1145fd2e8329fe06a2990/sdks/python/container/run_validatescontainer.sh#L74
** java-postcommit-it/*
https://github.com/apache/beam/blob/a4a94da1936d8cd2f8d1145fd2e8329fe06a2990/runners/google-cloud-dataflow-java/build.gradle#L147
** python-postcommit-it/*
https://github.com/apache/beam/blob/a4a94da1936d8cd2f8d1145fd2e8329fe06a2990/sdks/python/test-suites/dataflow/common.gradle#L380
* Bump grace time to ~15~30 days
* Run job daily as in code comment …

More cleanup containers

---

sdks/python/apache_beam/runners/portability/stager.py
sdks/python/apache_beam/runners/portability/stager_test.py
sdks/python/container/boot.go
sdks/python/setup.py

Fixes: https://github.com/apache/beam/issues/24110
Apache beam releases manylinux_2014 wheels from `2.43.0` release. Update the tag on the stager to match the wheel pattern. …

Update staging of Python wheels

---

sdks/python/apache_beam/examples/wordcount_it_test.py

Add a ValidatesContainer integration test that exercises --experiments=[no]use_sibling_sdk_workers
See https://github.com/apache/beam/issues/24092 …

Add a ValidatesContainer integration test for use_sibling_sdk_workers

---

sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestStream.java

Found via errorprone. I guess we don't have all the checks that internal Google does. I will try to update it. …

Fix checkArgument format string in TestStream

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/ExecutionStateTracker.java

Another format string found via errorprone. Just opening a PR for each because I am taking them as they come... …

Fix checkArgument format string in ExecutionStateTracker

---

website/www/site/content/en/documentation/basics.md
website/www/site/content/en/get-started/_index.md

Resolves #24082
- change headers size from h4 to h2 on https://beam.apache.org/get-started/, to make right nav menu initially visible without scroll
- change headers size from h3 to h2 on https://beam.apache.org/documentation/basics/, to make right nav menu initially visible without scroll
before:
after:
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](htt …

[Website] Change headers size from h4,h3 to h2

---

.test-infra/dataproc/flink_cluster.sh
.test-infra/jenkins/CommonTestProperties.groovy
.test-infra/jenkins/Flink.groovy
.test-infra/jenkins/job_LoadTests_Combine_Flink_Go.groovy
.test-infra/jenkins/job_LoadTests_Combine_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Flink_Go.groovy
.test-infra/jenkins/job_LoadTests_GBK_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Flink_Go.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Flink_Python.groovy
.test-infra/jenkins/job_LoadTests_SideInput_Flink_Go.groovy
.test-infra/jenkins/job_LoadTests_coGBK_Flink_Go.groovy
.test-infra/jenkins/job_LoadTests_coGBK_Flink_Python.groovy
.test-infra/jenkins/job_PostCommit_Python_Chicago_Taxi_Example_Flink.groovy

Test Dataproc 2.1 with Flink load tests

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOReadTest.java

Not sure what this is here for, but non-null is the default anyhow and this creates an undesirable dependency. …

Remove extraneous jetbrains annotation

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowBatchWorkerHarness.java

In recent runs, there were serious connectivity problems when reaching Dataflow's backend, which caused jobs to be stuck without displaying any logs at all.
If there is logspam for any other reason, I believe we would need to be more selective about hiding them.  …

Change DataflowBatchWorkerHarness doWork log level to INFO

---

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/gcsfs/GcsPath.java

Only `%s` is supported - conversion to `%i` has to be eager or rely on `String.valueOf`. …

Fix checkArgument format in GcsPath

---

website/www/site/content/en/documentation/sdks/java-multi-language-pipelines.md

Updates Multi-lang Java quickstart

---

.test-infra/jenkins/job_CleanUpGCPResources.groovy
.test-infra/tools/build.gradle
.test-infra/tools/stale_bq_datasets_cleaner.sh

Cleanup stale BQ datasets

---

sdks/java/extensions/python/src/main/resources/org/apache/beam/sdk/extensions/python/bootstrap_beam_venv.py
sdks/typescript/README.md
sdks/typescript/build.sh

Adding a quickstart to README for the TS SDK

---

.test-infra/tools/stale_bq_datasets_cleaner.sh

More dataset templates to clean up

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/typescript/test/primitives_test.ts

This avoids possible flag conflicts. …

Rename the test_splits flag to direct_test_splits.

---

website/www/site/assets/scss/_global.sass

Resolves #23064
- update copy icon styles, change from float to position absolute 
- fix styles, so links get correct position in pre tag
before:
after: …

[Website] Update copy icon styles

---

learning/tour-of-beam/frontend/pubspec.lock
playground/frontend/lib/modules/examples/components/example_list/example_item_actions.dart
playground/frontend/lib/modules/examples/models/example_loading_descriptors/examples_loading_descriptor_factory.dart
playground/frontend/lib/modules/examples/models/example_token_type.dart
playground/frontend/playground_components/lib/playground_components.dart
playground/frontend/playground_components/lib/src/controllers/example_loaders/empty_example_loader.dart
playground/frontend/playground_components/lib/src/controllers/example_loaders/examples_loader.dart
playground/frontend/playground_components/lib/src/controllers/example_loaders/http_example_loader.dart
playground/frontend/playground_components/lib/src/controllers/example_loaders/standard_example_loader.dart
playground/frontend/playground_components/lib/src/controllers/playground_controller.dart
playground/frontend/playground_components/lib/src/controllers/snippet_editing_controller.dart
playground/frontend/playground_components/lib/src/enums/complexity.dart
playground/frontend/playground_components/lib/src/models/example.dart
playground/frontend/playground_components/lib/src/models/example_base.dart
playground/frontend/playground_components/lib/src/models/example_loading_descriptors/content_example_loading_descriptor.dart
playground/frontend/playground_components/lib/src/models/example_loading_descriptors/example_loading_descriptor.dart
playground/frontend/playground_components/lib/src/models/example_loading_descriptors/http_example_loading_descriptor.dart
playground/frontend/playground_components/lib/src/models/example_loading_descriptors/standard_example_loading_descriptor.dart
playground/frontend/playground_components/lib/src/models/example_loading_descriptors/user_shared_example_loading_descriptor.dart
playground/frontend/playground_components/lib/src/models/example_view_options.dart
playground/frontend/playground_components/lib/src/repositories/models/get_snippet_response.dart
playground/frontend/playground_components/lib/src/util/string.dart
playground/frontend/playground_components/lib/src/widgets/editor_textarea.dart
playground/frontend/playground_components/pubspec.yaml
playground/frontend/playground_components/test/src/controllers/example_loaders/http_example_loader_test.dart
playground/frontend/pubspec.lock
playground/frontend/test/modules/examples/models/example_loading_descriptors/examples_loading_descriptor_factory_test.dart
playground/frontend/test/modules/examples/models/example_token_type_test.dart
website/www/site/layouts/shortcodes/playground.html
website/www/site/layouts/shortcodes/playground_snippet.html

- Resolves #22357
- Resolves #22359
- Resolves #23925
- Resolves #23926 
- Adds `HttpExampleLoader`.
- Uses `null` for lack of complexity instead of a special enum value.
1. Add the following code to /website/www/site/content/en/documentation/programming-guide.md:
```
{{< playground height="700px" >}}
{{< playground_snippet language="java" example="SDK_JAVA/PRECOMPILED_OBJECT_TYPE_KATA/AggregationCount" >}}
{{< playground_snippet language="py" example="https://raw.githubusercontent.com/apache/beam/master/sdks/python/apache_beam/examples/snippets/snippets.py" unfold="pipelines_constructing_creating" readonly="pipelines_constructing_writing" >}}
{{< playground_snippet language="go" example="https://raw.githubusercontent.com/apache/beam/master/sdks/go/examples/snippets/01_03intro.go" …
```

Configure flutter_code_editor options with Hugo shortcode (#23926)

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

This method is deprecated as of Java 9. I have also been having trouble with connections leaking and staying open after encountering database errors and think this is the culprit.
I believe this is also the issue occurring in #22299  …

Using Teardown context instead of deprecated finalize

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/BatchViewOverrides.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/gcsfs/GcsPath.java

Fix arguments to checkState in BatchViewOverrides

---

.github/workflows/go_tests.yml

Go 1.19 has different gofmt behavior, requiring a bit more effort for migrating the github action formatting tests.
Reverting just the action change #24175 that keys the formatting change. Issue to fix the formating changes (and upgrade to 1.19 here) is filed in #24190 …

revert upgrade to go 1.19 for action unit tests

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerConfig.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessorTest.java

Fine-grained access control was added to Spanner, and the property DatabaseRole was added to Beam's SpannerConfig (https://github.com/apache/beam/pull/23377).
However, unlike the rest of the configuration class, ValueProvider support wasn't added, which is necessary to use it in Template jobs (more information [here]( https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#use-valueprovider-in-your-pipeline-options)).
To …

Use only ValueProviders in SpannerConfig

---

website/www/site/content/en/blog/splitAtFraction-method.md
website/www/site/content/en/blog/splittable-do-fn.md
website/www/site/content/en/documentation/runners/dataflow.md

Broken hyperlink in Apache Beam docs for Dataflow runner
fixes https://github.com/apache/beam/issues/24196
[![Build …

refs: issue-24196, fix broken hyperlink

---

sdks/python/apache_beam/typehints/batch.py

Introduced in #24022 but somehow pylint did not detect it. …

Fix PythonLint

---

release/src/main/python-release/python_release_automation_utils.sh
release/src/main/python-release/run_release_candidate_python_quickstart.sh

Update Python wheel format for RC validation. …

Update Python wheel format for RC validation

---

sdks/java/io/elasticsearch-tests/elasticsearch-tests-5/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-6/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-8/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTestUtils.java
sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java

Fixes #24117
Ensures that index size estimation accounts for index aliases, patterns, and datastreams by using `_all` stats for an aggregate value of `size_in_bytes`.
All credit to @JeffBolle for this patch. …

Uses _all to follow alias/datastreams when estimating index size

---

sdks/python/apache_beam/transforms/combiners_test.py
sdks/python/apache_beam/transforms/core.py

Force discarding mode in with_fanout without rewindowing.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryQueryHelper.java

Another one that used `{}` when it needed to be `%s` …

Fix checkArgument format string in BigQueryQueryHelper

---

sdks/go/pkg/beam/pardo.go
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java
sdks/python/apache_beam/transforms/core.py
website/www/site/content/en/documentation/programming-guide.md

Clarify that restriction size method needs to be thread safe

---

sdks/java/harness/build.gradle
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ExecutionStateSampler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/stream/HarnessStreamObserverFactories.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FnHarnessTest.java

The harness dependency on google-cloud-platform-core has caused a number of pipeline issues for Beam users recently. …

Remove google-cloud-platform-core dependency from harness

---

sdks/python/apache_beam/runners/interactive/interactive_beam.py

Addresses #24161 Emphasizes that interactive_beam.Clusters class only manages clusters implicitly created by Beam. This class is not needed and should not be used otherwise. …

Issue#24161 Updated docstring for Clusters class

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_ML_RunInference_Benchmark_Tests.json
sdks/python/apache_beam/examples/inference/README.md
sdks/python/apache_beam/testing/benchmarks/inference/README.md
website/www/site/content/en/documentation/ml/runinference-metrics.md
website/www/site/content/en/documentation/sdks/python-machine-learning.md

Right now, we have some nice RunInference benchmarks (https://s.apache.org/beam-community-metrics/d/ZpS8Uf44z/python-ml-runinference-benchmarks?orgId=1), but we don't link to them anywhere, and they aren't clearly explained. This fixes that problem.
Fixes #23898 …

Document our benchmarks

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/CreateTableHelpers.java

Fix checkArgument calls in BQ dynamic destinations

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.43.0.md
website/www/site/content/en/get-started/downloads.md

Website updates for Beam 2.43.0 release

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaTransformWriteProviderTest.java

Add @RunWith annotation to BQ test class

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/range/ByteKeyRange.java

Found via static analysis. `checkArgument` uses `%s` not `{}` …

Fix checkArgument format string in ByteKeyRange

---

website/www/site/content/en/blog/beam-2.43.0.md
website/www/site/content/en/get-started/downloads.md

Several fixes to the Website regarding the Beam 2.43.0 release

---

website/www/site/content/en/documentation/sdks/python-machine-learning.md

This removes a section from the troubleshooting guide about dictionary prediction results (https://github.com/apache/beam/issues/22240) because it was fixed in #23087
This shouldn't be merged until the 2.43 release is cut.
Fixes #22240  …

Remove section from troubleshooting about fixed dictionary issue

---

examples/notebooks/beam-ml/README.md

Adding the list of example notebooks to the ML readme file. …

Adding the list of example notebooks to the ML readme file

---

website/www/site/content/en/blog/beam-2.43.0.md

Updating timezone for Beam 2.43.0 release

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

The prior attempt to turn it on in #23792 was not correct. This simplifies the code and takes out the CI-dependent aspect since we don't need it. …

Only skip checkerframework if explicitly requested

---

sdks/python/apache_beam/dataframe/io.py

Addresses #21430 Label the dataframe gbq io so that it does not get pruned incorrectly by interactive beam. …

Issue#21430 Updated dataframe io to avoid pruning

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/BlockingCommmitterImplTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/CheckpointMarkImplTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/UnboundedReaderImplTest.java

A few classes were missing this. …

Add @RunWith annotation to pubsublite test

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PublisherOptions.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/SubscriberOptions.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/UuidDeduplicationOptions.java

Moving to the one method they actually need to apply to. …

Remove overly broad CanIgnoreReturnValue

---

website/www/site/content/en/documentation/sdks/java-multi-language-pipelines.md

* Move command for running using a Maven Archetype to top.
* Remove the warning regarding https://github.com/apache/beam/issues/23717 since the fix has been released. …

Update Java Multi-lang quickstart after the Beam 2.43.0 release

---

CHANGES.md

Add warning about google-cloud-platform-core dependency change in #24235

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py37/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/setup.py

Upgrade objsize since https://github.com/liran-funaro/objsize/issues/7 seems to have been addressed.
Fixes #24261 …

[#24261] Update to objsize 0.6.1

---

.github/workflows/typescript_tests.yml
sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/portability/local_job_service.py
sdks/typescript/src/apache_beam/internal/pipeline.ts
sdks/typescript/src/apache_beam/runners/dataflow.ts
sdks/typescript/src/apache_beam/runners/direct_runner.ts
sdks/typescript/src/apache_beam/runners/flink.ts
sdks/typescript/src/apache_beam/runners/portable_runner/runner.ts
sdks/typescript/src/apache_beam/runners/runner.ts
sdks/typescript/src/apache_beam/runners/universal.ts
sdks/typescript/src/apache_beam/testing/multi_pipeline_runner.ts
sdks/typescript/src/apache_beam/worker/operators.ts
sdks/typescript/src/apache_beam/worker/worker.ts
sdks/typescript/test/primitives_test.ts

This tests all the "primitive" tests in a single Dataflow pipeline (each in its own component). …

Add a Dataflow smoke test.

---

sdks/python/apache_beam/ml/inference/tensorrt_inference.py
sdks/python/apache_beam/ml/inference/tensorrt_inference_test.py

Adds support for specifying a custom inference function to the TensorRT model handler, enabling custom logic to be run during RunInference calls. 
Part of #22572 …

TensorRT Custom Inference Function Implementation

---

examples/multi-language/README.md

the region was still us-central1 in the example mvn command of SKlern Mnist Classification. …

Fix mvn command to refer the GCP_REGION variable

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryResourceNaming.java

fixed typo

---

website/ADD_CASE_STUDY.md
website/www/site/content/en/case-studies/intuit.md
website/www/site/content/en/case-studies/ricardo.md
website/www/site/layouts/case-studies/list.html
website/www/site/layouts/partials/quotes/quote.html

- change share your story button link on [homepage ](https://beam.apache.org/) and [caset-studies](https://beam.apache.org/case-studies/) to `https://github.com/apache/beam/blob/master/website/ADD_CASE_STUDY.md` from `mailto:dev@beam.apache.org?subject=Beam Website Add New Case Study`
- add text to ADD_CASE_STUDY.md
- add videos to [ricardo ](https://beam.apache.org/case-studies/ricardo/ )and [intuit ](https://beam.apache.org/case-studies/intuit/) case-studies
before:
after: …

[Website] update share button and ADD_CASE_STUDY.md

---

playground/frontend/lib/modules/examples/components/example_list/category_expansion_panel.dart
playground/frontend/lib/modules/examples/components/example_list/expansion_panel_item.dart

Fixed display of the selected example
resolves #23865  …

Fixed display of the selected example

---

.github/workflows/dask_runner_tests.yml

Dask runner tests action

---

website/www/site/content/en/community/presentation-materials.md
website/www/site/content/en/documentation/dsls/sql/calcite/lexical-structure.md
website/www/site/content/en/documentation/dsls/sql/zetasql/data-types.md
website/www/site/content/en/documentation/dsls/sql/zetasql/lexical.md
website/www/site/content/en/documentation/dsls/sql/zetasql/operators.md
website/www/site/content/en/documentation/dsls/sql/zetasql/query-syntax.md
website/www/site/layouts/shortcodes/community/table_with_icons.html

NB!!! Please merge this PR first before https://github.com/apache/beam/pull/24195
Resolves #23460
- update pages with table content overflow, add scroll.
https://beam.apache.org/documentation/dsls/sql/zetasql/data-types/
https://beam.apache.org/documentation/dsls/sql/zetasql/query-syntax/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/operators/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/lexical/index.html
https://beam.apache.org/documentation/dsls/sql/calcite/lexical-structure/
https://beam.apache.org/community/presentation-materials/index.html
https://beam.apache.org/community/contact-us/index.html
before:
after: …

[Website] Update pages with table content overflow

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Java_JMH_benchmarks.json

Add 'performance tests' tag to JMH dashboard  …

[Metrics] Add 'performance tests' tag to JMH dashboard 

---

examples/notebooks/beam-ml/run_inference_pytorch.ipynb
examples/notebooks/beam-ml/run_inference_pytorch_tensorflow_sklearn.ipynb
examples/notebooks/beam-ml/run_inference_sklearn.ipynb

Update apache beam installation in notebook

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update Python dataflow containers to beam-master-20221122

---

buildSrc/build.gradle.kts

Recent versions of the plugin plus recent versions of checkerframework further incrementalize compile.
Unclear why #24238 has the problems it has - I have not been able to reproduce it locally. Maybe this will help? …

Upgrade checkerframework gradle plugin to 0.6.19

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WorkItemStatusClient.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkItemStatusClientTest.java

This fixes crashes caused by ignoring the field. Followup to #12994 …

Handle CompleteWorkStatus shutdown signal

---

CHANGES.md
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/portability/java/build.gradle
sdks/java/harness/build.gradle
sdks/java/harness/jmh/build.gradle

This reduces the surface area of the shadowJar to avoid conflicts with user code. It is expected that the user will provide a working copy of Beam core and its dependencies. …

Simplify sdks/java/harness shadowJar

---

sdks/java/io/sparkreceiver/2/build.gradle
sdks/java/io/sparkreceiver/2/src/test/java/org/apache/beam/sdk/io/sparkreceiver/SparkReceiverIOIT.java

[CdapIO] Fix SparkReceiverIOIT

---

CHANGES.md

Adds the custom inference function feature to CHANGES.md for release 2.44.0. …

Add custom inference fns to CHANGES.md

---

website/www/site/assets/js/copy-to-clipboard.js
website/www/site/assets/scss/_global.sass

Resolves #24372
- update copy-to-clipboard.js. Fix the structure of pre tag, so copy icon would stay on one place in case of scroll
before:
after: …

[Website] update copy-to-clipboard.js

---

.github/workflows/tour_of_beam_backend_integration.yml
playground/backend/cmd/server/controller.go
playground/backend/internal/db/datastore/datastore_db.go

[Playground] [Backend] minor fixes for error msgs

---

.github/workflows/cut_release_branch.yml
CI.md

As part of the [Beam Release Process](https://beam.apache.org/contribute/release-guide/), the following PR includes the workflow to run the [cut_release_branch.sh](https://github.com/apache/beam/blob/master/release/src/main/scripts/cut_release_branch.sh) script described in [step 5. Use cut_release_branch.sh to cut a release branch
](https://beam.apache.org/contribute/release-guide/#use-cut_release_branchsh-to-cut-a-release-branch)
Files:
- Cut Release Branch: .github/workflows/cut_release_branch.yml
- Updated CI.md file …

[Github Actions] - Cut Release Branch Workflow

---

sdks/python/apache_beam/io/azure/blobstorageio.py

Fixes #24440
According to https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.models.blobproperties?view=azure-python-previous there is an etag field for BlobProperties …

Fix BlobstorageIO.checksum Attribute Error

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryDirectReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryDirectReadSchemaTransformProviderTest.java

Don't set BigQuery services in schema transform configuration

---

.test-infra/jenkins/job_IODatastoresCredentialsRotation.groovy

This pool recently got renamed, breaking https://ci-beam.apache.org/job/Rotate%20IO-Datastores%20Cluster%20Credentials/ …

Rename from default-pool to pool-1

---

.test-infra/jenkins/job_IODatastoresCredentialsRotation.groovy
.test-infra/jenkins/job_MetricsCredentialsRotation.groovy

Follow up from https://github.com/apache/beam/pull/24466 - the current links don't work because they get replaced at seed job time. …

Fix error messages in cred rotation email

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java

Support integer values to be provided as input for columns of type NUMERIC and BIGNUMERIC. …

Add integer to NUMERIC and BIGNUMERIC conversion support

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

Fixes #24441, and gets fixes for some CVEs. …

24441: Update Jackson version from 2.13.3 to 2.14.1.

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_ML_RunInference_Benchmark_Tests.json

Add GPU benchmark to RunInference Grafana dashboard

---

.test-infra/jenkins/job_PerformanceTests_SparkReceiverIO_IT.groovy

[CdapIO] Update read timeout for SparkReceiverIOIT job

---

.github/workflows/build_wheels.yml
sdks/python/apache_beam/transforms/core.py

Currently, build wheels on linux aarch64 is one of the slowest GitHub Action for Python PRs, ran more than 2 hr. It builds all py3.7-3.10 wheels. This is barely useful as precommit.
This PR reduces python versions running build_wheels workflow when triggered by a pull request event (open pull request, new commits). windows, macOS, linux-aarch64 now run only on lowest and highest supported python version; while linux-x86 still runs on full list of supported versions.
* Run on ~lowest and~ highest supported version on pull request event
ubuntu x64 still run full on all supported version
* Unimportant typo fix to trigger python build …

Reduce version matrix of build wheel on pull request event

---

.github/workflows/stale.yml

Nobody seems to use this label, and its inferrable by looking at updated …

Never mark issues as stale

---

sdks/python/apache_beam/runners/render.py
sdks/python/apache_beam/runners/render_test.py

* Dashed rather than dotted lines are more visible for side inputs.
* A light fill for all nodes brings out the shape of the pipeline better.
See
`python -m apache_beam.examples.wordcount_minimal --runner=apache_beam.runners.render.RenderRunner --render_output=out.png` …

Minor visibility improvements to render runner.

---

website/ADD_CASE_STUDY.md
website/www/site/assets/scss/_case_study.scss
website/www/site/layouts/case-studies/list.html

Rsolves #24486
- update `case-studies/list.html`, add options to case-studies to be able to add сoauthor to `https://beam.apache.org/case-studies/`
- update related ADD_CASE_STUDY.md where it is noted how to add a new case-study
GitHub …

[Website] Add coauthor option to case-studies

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_ML_RunInference_Benchmark_Tests.json

This will render like this at the top of the page.
I also removed the link which was not very visible.
[![Build …

Add panel pointing to docs for ml benchmarks

---

.github/workflows/typescript_tests.yml

These have been failing because the testing bucket doesn't contain the gs:// prefix. This follows the pattern in https://github.com/apache/beam/blob/b28236c2cdc02d7afc22034904a5f74f20c1c543/.github/workflows/python_tests.yml#L207
Fixes #24491 
GitHub Actions …

Fix broken typescript tests

---

sdks/java/extensions/sql/datacatalog/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datacatalog/DataCatalogTableProvider.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/CalciteQueryPlanner.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamSqlRelUtils.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/bigquery/BigQueryTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/mongodb/MongoDbTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/parquet/ParquetTable.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java

Minor fixes to logging, applying best practices. …

[SQL extension] Minor fixes to logging applying best practices

---

playground/terraform/build.gradle.kts

This PR closes #24506 by applying gradle task configuration avoidance according to the playground terraform gradle tasks.  Essentially configuring the tasks as `task(String)` led to the gradle terraform plugin executing terraform init even for gradle projects unrelated to `playground:terraform`.
- ~[ ] Update `CHANGES.md` with noteworthy changes.~
- ~[ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~ …

Apply task configuration avoidance to playground terraform gradle tasks

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_ML_RunInference_Benchmark_Tests.json

#24503 broke http://104.154.241.245/d/ZpS8Uf44z/python-ml-runinference-benchmarks?orgId=1 because I pushed the wrong version of the dashboard with a duplicate id (id 2 is used elsewhere). This fixes it. Example running locally …

Fix grafana dashboard id

---

runners/spark/spark_runner.gradle

Support running (VR) tests with Java 17 (closes #24400) …

[Spark runner] Support running (VR) tests with Java 17

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

Since the finalize() method depreciates in Java 9, it is recommended to replace the method with the DoFn.Teardown annotation.
Performed the renaming of the method to tearDown and increased the visibility to public.
[Task: #24181] …

Replaced deprecated finalize with DoFn Teardown

---

sdks/python/apache_beam/io/filebasedsink.py
sdks/python/apache_beam/io/fileio.py

Batch rename request for WriteToFiles
Should be part of #20547 as finishing a TODO in code. Batch rename request is already present in FileBasedSink and used in WriteToText transforms. However, the WriteToFiles transform in fileio module rename tmp files to final file one by one currently. …

Batch rename requests in fileio.WriteToFiles

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

I missed doing this in #23973 and it is currently causing postcommits to fail
Fixes #24531  …

Update dataflow container version for Pandas upgrade

---

website/www/site/layouts/about/baseof.html

Resolves #24521
- center the main content of [about page](https://beam.apache.org/about/)
before:
after: …

[Website] center the main content of about page

---

website/www/site/assets/scss/_table-wrapper.scss

Resolves #24426
- update positioning of copy icon in tables to the right top corner, since it is consitent with other copy icons positioning and it will not disturb in case of long content or overflow
- make copy icon visible on mobile devices
before:
after:
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-i …

[Website] Update copy icon positioning

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/io/BoundedDatasetFactory.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/PipelineTranslator.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/SparkSessionFactory.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/TransformTranslator.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/DoFnMapPartitionsFactory.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/GroupByKeyTranslatorBatch.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ParDoTranslatorBatch.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ReadSourceTranslatorBatch.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/functions/GroupAlsoByWindowViaOutputBufferFn.java

Broadcast pipeline options to avoid repeated serialization in closures. …

[Spark Dataset runner] Broadcast pipeline options

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AppendClientInfo.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java

Fix null pointer exception caused by clearing member variable

---

.github/workflows/build_playground_backend.yml
.github/workflows/build_playground_frontend.yml
.github/workflows/java_tests.yml
.github/workflows/playground_deploy_backend.yml
.github/workflows/playground_deploy_examples.yml
.github/workflows/playground_examples_ci_reusable.yml
.github/workflows/run_rc_validation.yml

actions/setup-java v3.7.0 has disappeared (https://github.com/actions/setup-java/issues/422) and causing GitHub Action tests failing
This reverts commit ea1de174fb7df213d299a787aaca8c014d428c2e. …

Revert "Bump actions/setup-java from 3.6.0 to 3.7.0 (#24484)"

---

sdks/go/pkg/beam/artifact/materialize_test.go
sdks/go/pkg/beam/internal/errors/errors.go
sdks/go/pkg/beam/io/avroio/avroio.go
sdks/go/pkg/beam/io/avroio/avroio_test.go
sdks/go/pkg/beam/io/bigqueryio/bigquery.go
sdks/go/pkg/beam/io/bigtableio/bigtable_test.go
sdks/go/pkg/beam/io/databaseio/database.go
sdks/go/pkg/beam/io/databaseio/loader.go
sdks/go/pkg/beam/io/databaseio/mapper.go
sdks/go/pkg/beam/io/databaseio/util.go
sdks/go/pkg/beam/io/databaseio/writer.go
sdks/go/pkg/beam/io/datastoreio/datastore_test.go
sdks/go/pkg/beam/io/fhirio/execute_bundles.go
sdks/go/pkg/beam/io/fhirio/search.go
sdks/go/pkg/beam/io/filesystem/s3/helper_test.go
sdks/go/pkg/beam/io/parquetio/parquetio.go
sdks/go/pkg/beam/io/parquetio/parquetio_test.go
sdks/go/pkg/beam/io/rtrackers/offsetrange/offsetrange.go
sdks/go/pkg/beam/io/rtrackers/offsetrange/offsetrange_test.go
sdks/go/pkg/beam/io/textio/textio.go
sdks/go/pkg/beam/io/xlang/jdbcio/jdbc.go
sdks/go/pkg/beam/io/xlang/schemaio/schemaio.go
sdks/go/pkg/beam/log/log.go

Continues the effort started in https://github.com/apache/beam/pull/24505 (aka my new I have 15 minutes free hobby) …

Interface{}->any for more subfolders

---

sdks/go/pkg/beam/testing/passert/equals.go
sdks/go/pkg/beam/testing/passert/floats.go
sdks/go/pkg/beam/testing/passert/passert.go
sdks/go/pkg/beam/testing/ptest/ptest.go
sdks/go/pkg/beam/testing/ptest/ptest_test.go
sdks/go/pkg/beam/testing/teststream/teststream.go
sdks/go/pkg/beam/testing/teststream/teststream_test.go

Moves testing utilities in the Go SDK from using `interface{}` to `any` to follow new style recommendations.  …

Migrate testing subpackages from interface{} to any

---

sdks/go/pkg/beam/core/graph/xlang.go
sdks/go/pkg/beam/core/typex/special.go

fix lints discovered on latest import …

[Go SDK] fix go lints

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/legacy-worker/build.gradle
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/Aggregators.java
runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/functions/CachedSideInputReader.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/SortedMapCoder.java
sdks/java/harness/build.gradle
sdks/java/io/mongodb/src/main/java/org/apache/beam/sdk/io/mongodb/AggregationQuery.java

This upgrades all the way to the most recent checkerframework. Some added exclusions and some fixes. This should enable even finer-grained incremental compilation.
Fixes #21068 
Fixes #24397 …

Upgrade checker framework to 3.27.0

---

.test-infra/jenkins/job_PerformanceTests_FileBasedIO_IT.groovy
.test-infra/kubernetes/hadoop/LargeITCluster/hdfs-multi-datanode-cluster.yml

Fixes #24549
* Use docker image under apache-beam-testing
* Decrease frequency of cron jobs to twice a day …

Bump to Hadoop 3.3.4 for performance tests

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClient.java

pubsub: fix typo in grpc client factory

---

learning/tour-of-beam/backend/README.md
playground/infrastructure/helm-playground/templates/deployment-router-grpc.yml
playground/infrastructure/helm-playground/templates/service-router-grpc.yml

1. Bring up a Playground Router instance to serve GRPC API
2. Create a LoadBalancer for this instance
3. Use its host as PLAYGROUND_ROUTER_HOST in a `postUserCode` CF …

[Tour Of Beam] Playground Router GRPC API host

---

sdks/java/io/neo4j/src/main/java/org/apache/beam/sdk/io/neo4j/Neo4jIO.java

Since the finalize() method depreciates in Java 9, it is recommended to replace the method with the DoFn.Teardown annotation.
Performed the renaming of the method to tearDown and increased the visibility to public.
[Task: #24181] …

Replaced finalize with DoFn Teardown in Neo4jIO

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/failing_test.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/issue-rules.yml

Specifically to match the description here: https://lists.apache.org/thread/tkxb4wmd2b3hqgztvw3skv05yqf734k5
[![Build …

Simplify issue report templates

---

.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml

Broke these in my last change to the templates …

Fix bugs in issue template yml

---

.github/ISSUE_TEMPLATE/failing_test.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/issue-rules.yml

Fix issue templates

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java

Cherry pick of https://github.com/apache/beam/pull/24447 in the 2.44.0 release branch. 
Kudos original author [agrawal-siddharth](https://github.com/agrawal-siddharth) for the code changes …

[Cherry Pick #24447] Add integer to NUMERIC and BIGNUMERIC conversion support

---

runners/spark/src/test/java/org/apache/beam/runners/spark/SparkRunnerDebuggerTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/FlatMapElements.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/MapElements.java

Fixes #24024
Stop wrapping light weight functions with Contextful as they add a lot of overhead for functions that are meant to do almost no work.
Whole profile is 33.64s. We can eliminate (36.94-19.19)+(92.42-37.9) millis from which leads to a 0.2% performance improvement for the pipeline but leads to substantially larger gains for trivial lambdas. It may lead to a larger improvement as we are reducing the wasteful creation and destruction of the wrapped context.
See attached pprof data.
[profile (47).pb.gz](https://github.com/apache/beam/files/9956221/profile.47.pb.gz) …

[#24024] Stop wrapping light weight functions with Contextful as they add a lot of overhead for functions that are meant to do almost no work.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProvider.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java

Implement Kafka Write Schema Transform

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcUtil.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/LogicalTypes.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/SchemaUtil.java

This adds enough annotation and checks to re-enable nullness checking in JdbcIO. It does not do any significant refactor that might make it less error-prone. …

Eliminate null errors from JdbcIO

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/Filter.java
website/www/site/content/en/documentation/programming-guide.md

fixes: #24100 
Grep'ed the following methods found in [Filter.Inner API doc](https://javadoc.io/static/org.apache.beam/beam-sdks-java-core/2.43.0/org/apache/beam/sdk/schemas/transforms/Filter.Inner.html) and added `.create()` calls if appropriate:
- expand()
- whereFieldId()
- whereFieldIds()
- whereFieldName()
- whereFieldNames() …

docs(fix): Filter.whereFieldName(s?) -> Filter.create().whereFieldName(s?)

---

runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/wire/CommonCoderTest.java
sdks/java/core/build.gradle
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/DefaultCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/runners/PTransformOverride.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FieldValueTypeInformation.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FromRowUsingCreator.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/Group.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/SchemaAggregateFn.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ReflectUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/join/CoGbkResult.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/resourcehints/ResourceHints.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/resourcehints/ResourceHintsOptions.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/MoreFutures.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/PCollectionList.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/PCollectionTuple.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/Row.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/RowWithGetters.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/TypeDescriptors.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamAggregationRel.java

This was turned off entirely, so we were easily introducing new issues.
A step for #20447 to continue to eliminate rawtype issues. After this PR it will only be possible to introduce into our test code, which is not as important for users if there is an issue. …

Turn rawtype checking back on for core Java SDK

---

sdks/go/pkg/beam/register/emitter.go
sdks/go/pkg/beam/register/iter.go
sdks/go/pkg/beam/register/register.go
sdks/go/pkg/beam/register/register.tmpl
sdks/go/pkg/beam/register/register_test.go

Yet another interface -> any conversion. …

interface{} -> any for registration

---

.github/workflows/python_tests.yml
sdks/python/setup.py

Please look at https://github.com/apache/beam/issues/24603 for more information. …

Restrict tox to be in 3.x version

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageStreamSource.java

[BigQueryIO] Initialize and increment Storage API Read metrics properly

---

sdks/java/io/debezium/build.gradle
sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/KafkaConnectUtils.java
sdks/java/io/debezium/src/test/java/org/apache/beam/io/debezium/KafkaConnectSchemaTest.java
sdks/java/io/debezium/src/test/java/org/apache/beam/io/debezium/SourceRecordJsonTest.java

This feature is an intermediate step to add schema transform support for DebeziumIO. …

Add schema conversion support from Kafka Connect Record schemas to Beam schemas

---

.github/workflows/go_tests.yml

* Updates in workflow Go Tests to `runs-on` self-hosted runners
* Ubuntu …

[GitHub Actions] - Updates in Go Tests to runs-on Self-hosted runners

---

.github/workflows/label_prs.yml

* Updates in workflow Label PRs  to `runs-on` self-hosted runners
* Ubuntu …

[GitHub Actions] - Updates in Label PRs to runs-on Self-hosted runners

---

sdks/python/apache_beam/transforms/combiners_test.py
sdks/python/apache_beam/transforms/core.py

A temporary quick fix for #20528 until we can make it work entirely. …

Disallow sliding windows with combiner fanout to prevent data loss

---

.github/actions/activate-service-account/action.yml

Adding a composite action to activate service accounts for jobs that will be migrated from Jenkins and might require to get a special permissions to work. …

Composite Action to activate SA in GitHub Actions Runners

---

sdks/java/io/hadoop-format/build.gradle
sdks/java/io/hadoop-format/src/test/java/org/apache/beam/sdk/io/hadoop/format/HadoopFormatIOSequenceFileTest.java

Removed "examples" dependency from "hadoop-format-io", because it caused cyclic dependencies issue. 
`Examples` → `CdapIO` →`HadoopFormatIO` → `Examples`. …

[CdapIO] Remove 'examples' dependency from HadoopFormatIO

---

website/www/site/assets/scss/_table-wrapper.scss
website/www/site/content/en/documentation/dsls/sql/calcite/data-types.md
website/www/site/content/en/documentation/dsls/sql/calcite/lexical-structure.md
website/www/site/content/en/documentation/dsls/sql/extensions/create-external-table.md
website/www/site/content/en/documentation/dsls/sql/zetasql/conditional-expressions.md
website/www/site/content/en/documentation/dsls/sql/zetasql/conversion-rules.md
website/www/site/content/en/documentation/dsls/sql/zetasql/data-types.md
website/www/site/content/en/documentation/dsls/sql/zetasql/lexical.md
website/www/site/content/en/documentation/dsls/sql/zetasql/math-functions.md
website/www/site/content/en/documentation/dsls/sql/zetasql/operators.md
website/www/site/content/en/documentation/dsls/sql/zetasql/query-syntax.md
website/www/site/content/en/documentation/programming-guide.md
website/www/site/content/en/get-started/from-spark.md
website/www/site/layouts/shortcodes/table.html

Resolves https://github.com/apache/beam/issues/24194 https://github.com/apache/beam/issues/24193
- add `table-wrapper--equal-p` class to css in order to make tables 3rd column content not to stand out from other columns content and to make space between columns
- add `table-wrapper--pr` class to css to create space between 2 columns
- remove redundant styles from tables
- pages:
https://beam.apache.org/documentation/dsls/sql/extensions/create-external-table/index.html
https://beam.apache.org/documentation/dsls/sql/calcite/lexical-structure/index.html
https://beam.apache.org/documentation/dsls/sql/calcite/data-types/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/conditional-expressions/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/conversion-rules/inde …

Website update keywords table

---

sdks/python/apache_beam/transforms/combiners_test.py
sdks/python/apache_beam/transforms/core.py

Mitigates #20528 for this release …

Cherrypick #24606 to 2.44.0 release branch (disallow sliding windows in Python fanout combiner per key)

---

.github/workflows/update_python_dependencies.yml

This workflow is part of the release automation process. Will run the gradle task related to the update python dependencies ./gradlew :sdks:python:container:generatePythonRequirementsAll  , if this taks make changes on the branch the workflows will commit, push and create a PR with the changes.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/ma …

Release Automation - Update Python Dependencies

---

website/www/site/content/en/documentation/io/connectors.md

Updating the connector page to show that BigtableIO supports streaming.

Updating connector page for BigtableIO

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConfluentSchemaRegistryDeserializerProvider.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffset.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaExactlyOnceSink.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ProducerRecordCoder.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ConfluentSchemaRegistryDeserializerProviderTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibilityTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOUtilsTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoderTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ProducerRecordCoderTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

One more baby step toward #20447 …

Eliminate rawtypes from KafkaIO

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineOptions.java

This fixes a regression due to https://github.com/apache/beam/pull/14970 which resulted in 'serviceAccount' option not being visible in the Dataflow Cloud Console UI.  …

Remove 'Hidden' attribute from serviceAccount PipelineOption

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/UpdateSchemaDestination.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/DicomIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubSubPayloadTranslation.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dofn/DetectNewPartitionsDoFn.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/DicomIOReadIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/util/TestTransactionAnswer.java

Just getting rid of a few annotations that are not needed, and GCP IO is mostly modernized. …

Eliminate rawtypes from GCP IO

---

website/www/site/assets/scss/_lists.scss
website/www/site/assets/scss/_local.scss
website/www/site/content/en/community/join-beam.md

Resolves #24611
- fix mobile layout of [join beam page](https://beam.apache.org/community/join-beam/)
- make ellipses images not overlap other elements
- make headers not overlap other elements
before:
after: …

[Website] Fix join beam page mobile layout

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineOptions.java

Cherry-picks https://github.com/apache/beam/pull/24642 into the 2.44.0 release branch.
Issue is https://github.com/apache/beam/issues/24649. …

Remove 'Hidden' attribute from serviceAccount PipelineOption (#24642)

---

website/www/site/content/en/documentation/io/connectors.md

Fix: https://github.com/apache/beam/issues/23489
I believe the debezium source supports both bounded (via [`withMaxNumberOfRecords`](https://github.com/apache/beam/blob/master/sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/DebeziumIO.java#L201-L203)) & unbounded mode, but I might be wrong...
cc: @kennknowles  …

Add Debezium IO to doc

---

sdks/python/apache_beam/runners/worker/log_handler.py
sdks/python/apache_beam/runners/worker/log_handler_test.py

Ensure that we handle formatting errors during logging in portable Python jobs.

---

sdks/python/apache_beam/runners/dataflow/dataflow_exercise_metrics_pipeline_test.py

Tracking issue: https://github.com/apache/beam/issues/22605 …

Sickbay test_metrics_fnapi_it

---

sdks/python/apache_beam/io/filebasedsink.py

Add additional logging when filebasedsink didn't delete temp files
This is for #24638  …

Add additional logging for temp file deletion

---

.github/workflows/pr-bot-prs-needing-attention.yml

* Updates in workflow PR Bot PRs Needing Attention to `runs-on` self-hosted runners
* Ubuntu …

[GitHub Actions] - Updates in PR Bot PRs Needing Attention to runs-on Self-hosted runners

---

.github/workflows/reportGenerator.yml

* Updates in workflow Report Generator to `runs-on` self-hosted runners
* Ubuntu …

[GitHub Actions] - Updates in Report Generator to runs-on Self-hosted runners

---

.github/workflows/self-assign.yml

* Updates in workflow Self-assign to `runs-on` self-hosted runners
* Ubuntu …

[GitHub Actions] - Updates in Self-assign to runs-on Self-hosted runners

---

.github/workflows/typescript_tests.yml

* Updates in workflow Typescript Tests to `runs-on` self-hosted runners
* Ubuntu
* Windows
[BEAM-12812](https://issues.apache.org/jira/browse/BEAM-12812): Original Jira may contain additional context. …

[GitHub Actions] - Updates in Typescript Tests to runs-on Self-hosted runners

---

.github/workflows/stale.yml

`DO NOT MERGE until the infrastructure is in place. Please talk to @dannymartinm @elink21 before merging`
* Updates in workflow Stale to `runs-on` self-hosted runners
* Ubuntu …

[GitHub Actions] - Updates in Stale to runs-on Self-hosted runners

---

.github/workflows/pr-bot-new-prs.yml

* Updates in workflow PR Bot New PRs to `runs-on` self-hosted runners
* Ubuntu …

[GitHub Actions] - Updates in PR Bot New PRs to runs-on Self-hosted runners

---

.test-infra/jenkins/NexmarkBuilder.groovy
.test-infra/jenkins/job_PostCommit_Java_Nexmark_Dataflow.groovy
.test-infra/jenkins/job_PostCommit_Java_Nexmark_Dataflow_V2.groovy
.test-infra/jenkins/job_PostCommit_Java_Nexmark_Dataflow_V2_Java11.groovy
.test-infra/jenkins/job_PostCommit_Java_Nexmark_Dataflow_V2_Java17.groovy
.test-infra/jenkins/job_PostCommit_Java_Nexmark_Direct.groovy
.test-infra/jenkins/job_PostCommit_Java_Nexmark_Flink.groovy
.test-infra/jenkins/job_PostCommit_Python_Nexmark_Direct.groovy
sdks/python/apache_beam/testing/benchmarks/nexmark/nexmark_launcher.py

Run some Batch Nexmark on Python! …

Add Python Nexmark tests to Jenkins

---

.github/issue-rules.yml

Fix auto labeler since we standardized on "flake" and not "flaky" or "flakey".
Ref: 
https://github.com/apache/beam/issues/24664#issuecomment-1353597440 …

flaky -> flake in autolabeler

---

website/www/site/content/en/blog/gsoc-19.md
website/www/site/content/en/get-started/from-spark.md
website/www/site/content/en/get-started/mobile-gaming-example.md
website/www/site/content/en/get-started/quickstart-go.md
website/www/site/content/en/get-started/quickstart-java.md
website/www/site/content/en/get-started/quickstart-py.md
website/www/site/content/en/get-started/quickstart/java.md
website/www/site/content/en/get-started/resources/videos-and-podcasts.md
website/www/site/content/en/get-started/try-apache-beam.md
website/www/site/content/en/get-started/wordcount-example.md

Fixes a broken link to https://beam.apache.org/documentation/resources/videos-and-podcasts. Correct links should be: https://beam.apache.org/get-started/resources/videos-and-podcasts/
I do not know if that is the best solution. As an alternative we could consider setting up a redirect for the old link. We do not know who else would be still linking to the old one. …

Fix link to videos-and-podcasts page.

---

sdks/java/io/singlestore/src/main/java/org/apache/beam/sdk/io/singlestore/schematransform/SingleStoreSchemaTransformReadConfiguration.java
sdks/java/io/singlestore/src/main/java/org/apache/beam/sdk/io/singlestore/schematransform/SingleStoreSchemaTransformWriteConfiguration.java

Fix some typos

---

.test-infra/jenkins/job_PerformanceTests_SingleStoreIO.groovy

Fix SingleStoreIO performance test job

---

examples/notebooks/tour-of-beam/reading-and-writing-data.ipynb

I'm new to this project and glad to contribute. 😊
This PR could correct the URL link in notebooks for "Tour of Beam". …

Fix a small wrong url link in notebook

---

runners/google-cloud-dataflow-java/build.gradle

See https://github.com/apache/beam/issues/24750, we need to exclude MultimapState related tests in Dataflow legacy worker validates runner tests, https://github.com/apache/beam/pull/23491 excluded only runner v2 tests. …

Exclude MultimapState related tests in Dataflow legacy worker validates runner tests

---

.github/workflows/git_tag_released_version.yml
CI.md

As part of the [Beam Release Process](https://beam.apache.org/contribute/release-guide/), the following PR includes the workflow to run the [Git Tag](https://beam.apache.org/contribute/release-guide/#git-tag) described in the Beam Release Process
Files:
- Git Tag Released Version Workflow: `.github/workflows/git_tag_released_version.yml`
- CI.md  …

[Release Tasks Migration] - Git Tag Workflow

---

playground/backend/containers/go/build.gradle

Followup of #24256
An error shown when build the project locally:
```
Build file '/Users/yathu/beam/playground/backend/containers/go/build.gradle' line: 62
A problem occurred evaluating project ':playground:backend:containers:go'.
> Could not copy file '/Users/yathu/beam/sdks/go/examples/.gogradle/project_gopath/pkg/mod/cloud.google.com/go/storage@v1.15.0/iam.go' to '/Users/yathu/beam/playground/backend/containers/go/build/beam/go/examples/.gogradle/project_gopath/pkg/mod/cloud.google.com/go/storage@v1.15.0/iam.go'.
> /Users/yathu/beam/playground/backend/containers/go/build/beam/go/examples/.gogradle/project_gopath/pkg/mod/cloud.google.com/go/storage@v1.15.0/iam.go (Permission denied)
* Try:
> Run with --stacktrace option to get …
```

Fix Permission denied error build beam locally

---

sdks/go/pkg/beam/core/runtime/exec/translate_test.go

I found a typo in sdks/go/pkg/beam/core/runtime/exec/translate_test.go, and I fix it …

fix typo: UnmarshallWindowFn should be UnmarshalWindowFn

---

sdks/go/pkg/beam/runners/direct/buffer.go
sdks/go/pkg/beam/runners/direct/direct_test.go

Updates the `NewKeyedIterable()` implementation to correctly parse a multimap side input from an in memory ReStream.
Fixes #24774 …

[Go SDK] Fix multimap support for the direct runner

---

runners/google-cloud-dataflow-java/build.gradle

Update Java portable beam-master container for Dataflow

---

sdks/python/test-suites/direct/common.gradle

Fixes(partly): https://github.com/apache/beam/issues/24787 …

Install sklearn < 1.20.0 for sklearn postcommit tests

---

sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/typehints/trivial_inference.py
sdks/python/apache_beam/typehints/trivial_inference_test.py
sdks/python/apache_beam/utils/python_callable.py
sdks/python/apache_beam/utils/python_callable_test.py

This is particularly valuable for cross-language calls. …

Better naming and inference for PythonCallable.

---

runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/CombineGloballyTest.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/CombineGroupedValuesTest.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/CombinePerKeyTest.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ComplexSourceTest.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/FlattenTest.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/GroupByKeyTest.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/SimpleSourceTest.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/WindowAssignTest.java

Reuse SparkSession when testing using class rule. …

[Spark Dataset runner] Reuse SparkSession when testing using class rule.

---

.test-infra/jenkins/job_PerformanceTests_KafkaIO_IT.groovy
.test-infra/jenkins/job_PerformanceTests_xlang_KafkaIO_Python.groovy
.test-infra/metrics/grafana/dashboards/perftests_metrics/Java_IO_IT_Tests_Dataflow.json
.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_IO_IT_Tests_Dataflow.json
sdks/java/io/bigquery-io-perf-tests/src/test/java/org/apache/beam/sdk/bigqueryioperftests/BigQueryIOIT.java
sdks/java/io/hadoop-format/src/test/java/org/apache/beam/sdk/io/hadoop/format/HadoopFormatIOIT.java
sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOIT.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
sdks/python/apache_beam/io/external/xlang_kafkaio_perf_test.py
sdks/python/apache_beam/io/filebasedio_perf_test.py
sdks/python/apache_beam/io/kafka.py
sdks/python/apache_beam/testing/load_tests/load_test_metrics_utils.py

Add Python xlang KafkaIO performance test

---

sdks/go/pkg/beam/core/runtime/exec/sdf.go

Discovered there's an inconsistency with how FullValue wrappings occur between SDF phases and DataSource decoding. Undiscovered due to fusion hiding the inconsistency.
Discovered while adding SDF handling to the replacement runner tracked in https://github.com/apache/beam/issues/24789.
Ideally, there would be no such distinction, but would entail a major consistency cleanup in the execution layer. For now, we wrap if needed, but cleaning up the inconsistency would improve SDK throughput.
This is a re-do of #24790 since that pr was targeted incorrectly.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make …

[#24789] Spot fix fullvalue wrapping for SDF.

---

sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java
sdks/java/extensions/avro/src/test/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtilsTest.java

Sync changes from #24756 to `extensions/avro`
#23299 …

Support SqlTypes Date in AvroUtils (sync)

---

.github/workflows/playground_examples_ci_reusable.yml
playground/infrastructure/checker.py
playground/infrastructure/test_checker.py

added check for deleted files when processing gitt diff
fixes #24807  …

Playground Example CI fix for 24807

---

.test-infra/jenkins/job_sonarqube_report.groovy

Track issue: #24768
This PR disables the cron job https://ci-beam.apache.org/job/beam_sonarqube_report/ run on every 6 hour on jenkins but seems never succeeded. …

Disable sonarqube cron job

---

playground/infrastructure/conftest.py
playground/infrastructure/datastore_client.py
playground/infrastructure/grpc_client.py
playground/infrastructure/test_datastore_client.py
playground/infrastructure/verify.py

Empty run output, log and graph are saved to enforce example consistency
Test fixed 
fixes #24876 …

Saving empty output and log precompiled objects for consistency

---

playground/README.md
playground/infrastructure/grpc_client.py
playground/infrastructure/proxy/allow_list.py

Whitelisting maven repo for sbt to work
Externalizing grpc timeout
Adding example deployment to readme
fixes #24872 …

Playground runners scala update

---

sdks/go/pkg/beam/core/runtime/exec/translate_test.go
sdks/go/pkg/beam/core/runtime/exec/userstate_test.go

Increase unit testing coverage in the exec package
addresses #21391 …

[#21391]Increase unit testing coverage in the exec package

---

.github/workflows/playground_examples_ci_reusable.yml
playground/infrastructure/checker.py

This resolves issue with `checker.py` CI/CD [failing](https://github.com/apache/beam/actions/runs/3845665122/jobs/6550073679) when adding new examples as it was not loading the list of permitted categories.
resolves #24899 …

[Playground] Load categories from BEAM_EXAMPLE_CATEGORIES in checker.py

---

sdks/python/test-suites/direct/common.gradle

* Install sklearn < 1.20.0
* fixup syntax …

[release-2.44.0]Install sklearn < 1.20.0 for sklearn postcommit tests (#24788)

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java

Found in the error message in #24870. 
```
Error message from worker: java.lang.IllegalArgumentException: Unable to encode element 'GenericData{classInfo=[f], {dt=2022-12-21}}' with coder 'SchemaCoder<Schema: Fields:
Field{name=dt, description=, type=LOGICAL_TYPE, options={{}}}
```
It would be easier to troubleshooting if `type=LOGICAL_TYPE` shows the logical type identifier.
To …

Print logical identifier in FieldType.toString

---

.test-infra/jenkins/job_LoadTests_Combine_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Python.groovy
.test-infra/jenkins/job_LoadTests_GBK_Python_reiterate.groovy
.test-infra/jenkins/job_LoadTests_ParDo_Python.groovy
.test-infra/jenkins/job_LoadTests_SideInput_Python.groovy
.test-infra/jenkins/job_PerformanceTests_KafkaIO_IT.groovy
runners/google-cloud-dataflow-java/build.gradle
sdks/python/scripts/run_integration_test.sh

Remove shuffle mode=appliance in tests

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaTranslationTest.java

cherry picks #24910 into release-2.44.0 branch
* Attempt deserialize all non-standard logical types from proto
* Fixes portable and not-yet-standard logical type get deserialized to UnknownLogicalType …

[release-2.44.0] Cherry pick: Attempt deserialize all non-standard portable logical types from proto

---

website/www/site/content/en/get-started/quickstart/java.md

The Java version on beam website is not correct, this PR will fix it. …

Update quickstart document Java version from 11 to 17

---

sdks/go/pkg/beam/transforms/sql/sql_test.go

Improves test coverage by adding unit tests.
See #21384. …

[#21384] Add unit tests to the sql package

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/Dockerfile
sdks/java/container/boot.go
sdks/java/container/build.gradle
sdks/java/container/common.gradle
sdks/java/core/build.gradle
sdks/java/core/src/test/java/org/apache/beam/sdk/SdkHarnessEnvironmentTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/testing/ExpectedLogs.java
sdks/java/io/elasticsearch-tests/elasticsearch-tests-5/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-6/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-8/build.gradle
sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/build.gradle

This routes JCL/log4j/log4j2 messages to SLF4 which is then routed to JUL and finally over the Fn Logging API to the runner.
Fixes #24927 …

[#24927] Ensure the SDK harness handles JCL/log4j/log4j2 messages.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Fixes https://github.com/apache/beam/issues/21368

[#21368] Re-apply single executor to storage write API writes

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

This is a minor clean-up for https://github.com/apache/beam/pull/24950 to re-use existing implementation from gax-java …

[#21368] Clean-up and use the FixedExecutorProvider

---

playground/frontend/build.gradle

Add doLast on Playground integration tests (#24954)

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java

Fix bug that could cause us to append to a closed client.

Fix pinning bug in storage-api writes

---

.github/workflows/playground_deploy_examples.yml
.github/workflows/playground_examples_cd_reusable.yml
.github/workflows/playground_examples_ci_reusable.yml
playground/README.md
playground/infrastructure/ci_cd.py
playground/infrastructure/config.py
playground/infrastructure/datastore_client.py
playground/infrastructure/test_ci_cd.py
playground/infrastructure/test_datastore_client.py

Add an input variable for CI/CD scripts to support custom namespaces for Datastore client
fixes #24815
[![Build …

[Playground] Add an option for Datastore namespace value for ci_cd.py script

---

.github/workflows/playground_examples_ci_reusable.yml
playground/infrastructure/ci_cd.py
playground/infrastructure/test_ci_cd.py

Merge of [24818](https://github.com/apache/beam/pull/24818) introduced a regression CI/CD scripts which causes them to fail. This PR resolves it. …

[Playground] Fix for failing CI/CD in playground

---

website/www/site/content/en/_index.md

Adding the registered trademark symbol to the Apache Beam title on the browser tab.
R: @aaltay …

Adding the registered trademark symbol

---

sdks/go/pkg/beam/io/mongodbio/read.go

Fixes #25012 and sets `allowDiskUse` to true in the `mongodbio.Read` bucketAuto aggregation. …

Set allowDiskUse to true in MongoDB bucketAuto aggregation

---

sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
sdks/java/maven-archetypes/gcp-bom-examples/src/main/resources/archetype-resources/pom.xml

Fix beam_PostRelease_NightlySnapshot …

Add kafka version to pom

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubWriteSchemaTransformConfiguration.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubWriteSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteWriteSchemaTransformProvider.java

enabling public construction of typed schematransforms

---

website/www/site/content/en/documentation/programming-guide.md

Fix typo in join explanation.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/DoFnSignatures.java

r: @kileys 
When we have an anonymous class, `simpleName` is empty (and we weren't showing the class anyway, which is not nice). …

improve some errors from DoFnSignature

---

website/www/site/content/en/documentation/programming-guide.md

Adjust documentation until #22969 is addressed. …

Document that yield and return shouldn't be mixed.

---

.test-infra/jenkins/job_PostCommit_Python_Examples_Dataflow.groovy

This job has a timeout rate ~ 50 % : https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python_Examples_Dataflow/ …

Bump timeout for beam_PostCommit_Python_Examples_Dataflow to 3h

---

website/www/site/content/en/community/case-study.md

- update content of [community case study page](https://beam.apache.org/community/case-study/)
before:
after: …

[Website] update content of community case study page

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java

cherry pick #25062 into release-2.45.0 branch.
Fixes #25061 …

[Release-2.45.0] Cherry pick: Set maxConnections optional in incoming schema

---

.github/REVIEWERS.yml

Remove kileys from Java reviewers

---

runners/samza/job-server/build.gradle

Samza portable runner does not support Multimap state, so exclude the tests. …

Exclude UsesMultimapState in Samza validatesPortableRunner tests

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/PythonExternalTransformTest.java

Bump timeout for default transient expansion service

---

sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/DebeziumReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformReadProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubWriteSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteWriteSchemaTransformProvider.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProvider.java
sdks/java/io/singlestore/src/main/java/org/apache/beam/sdk/io/singlestore/schematransform/SingleStoreSchemaTransformReadProvider.java
sdks/java/io/singlestore/src/main/java/org/apache/beam/sdk/io/singlestore/schematransform/SingleStoreSchemaTransformWriteProvider.java

Adding autoservice annotations to all SchemaTransformProviders

---

website/www/site/content/en/documentation/sdks/python-machine-learning.md

This will highlight Java RunInference support better. Java RunInference is stable and fully supported.
[![Build …

Adds a reference x-lang RunInference Javadoc

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamPostgresIT.java

Enable postgres IT for change streams

[BEAM-12164] Enable postgres IT for change streams

---

sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_transform.py

Fix a couple typos caught by an internal linter

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Updated containers are [here](https://pantheon.corp.google.com/gcr/images/cloud-dataflow/GLOBAL/v1beta3?e=-13802955&jsmode=o&mods=dataflow_dev) …

Update Dataflow container versions

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AppendClientInfo.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServices.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/SplittingIterable.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinations.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsBeamRow.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsTableRow.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiLoads.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritePayload.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteRecordsInconsistent.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/testing/FakeDatasetService.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java

Cherry pick/fix bigquery inconsistent cache

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java

Fixing a table existence verifier for BQ

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

(cherry picked from commit 40243ffc2844b954e13bc3578d59661e2037ffcf) …

update GCP cloud libraries BOM to 26.5.0

---

sdks/python/apache_beam/transforms/util.py

Log BatchElement statistics.

---

website/www/site/content/en/documentation/sdks/go.md

Update Github issues link for Go SDK in website

---

website/www/site/content/en/documentation/transforms/java/elementwise/withkeys.md

[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%2 …

Fix a typo.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadSchemaTransformConfiguration.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformMessageToRowFactory.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadSchemaTransformProviderTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaTransformMessageToRowFactoryTest.java

Standardizing naming and URN for Pubsub Read Schema Transform

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteGroupedRecordsToFiles.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java

Investigating #25207
Flakiness not found locally so add test class timeout and run on jenkins
related: already found one scenario where mock not working and causing extended time of tests (https://github.com/apache/beam/issues/21533#issuecomment-1406929345). This mostly likely happen in error handling tests. …

Attempt fix GCPIO_Direct tests timeout

---

sdks/python/apache_beam/runners/interactive/sql/utils.py

Ignore all the flags when using beam_sql for PipelineOptions …

Ignore flags for beam_sql magic

---

.github/workflows/typescript_tests.yml
sdks/typescript/test/primitives_test.ts

Fix typescript github action failures.

---

sdks/java/extensions/sql/perf-tests/build.gradle
sdks/java/testing/expansion-service/build.gradle
sdks/java/testing/kafka-service/build.gradle

Towards #25190 cleaning up current test utilities in `sdks/java/testing`
these three projects only have code in `test` and the generated jars are empty anyways. …

Stop publishing empty test-only artifacts

---

sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/test-suites/tox/py38/build.gradle
sdks/python/tox.ini

Update/add torch versions to tox.ini

---

learning/tour-of-beam/backend/internal/fs_content/load.go
learning/tour-of-beam/backend/internal/fs_content/load_test.go
learning/tour-of-beam/backend/samples/api/get_unit_content.json
learning/tour-of-beam/backend/samples/learning-content/module 1/group/unit-challenge/hint1.md
learning/tour-of-beam/backend/samples/learning-content/module 1/unit-challenge/hint1.md
learning/tour-of-beam/backend/samples/learning-content/module 2/unit-challenge/hint1.md

Pass unit challenges hints thorough the same templating logic as the units descriptions themselves.
resolves #25097 …

[Tour of Beam]Add support for templates in task hints

---

.github/workflows/build_playground_backend.yml
.github/workflows/playground_deploy_backend.yml
.github/workflows/playground_examples_ci_reusable.yml
playground/backend/containers/java/Dockerfile
playground/backend/containers/java/build.gradle

Change dependency management for Playground java runner to use 2.44.
This change was required due to breaking changes in 2.44 with java sdk harness
Also removing lintdocker since it doesn't support valid syntax of redeclaring ARGs
resolves #25262
GitHub Actions …

[Tour of Beam] [Task] Fix dependency management for 2.44 Playground java runner

---

CHANGES.md

It looks like these changes went in after the 2.45 release branch was cut (they don't show up in the [release branch's version](https://github.com/apache/beam/blob/release-2.45.0/CHANGES.md)), so they should be moved to 2.46
Original changes: https://github.com/apache/beam/pull/25068 and https://github.com/apache/beam/pull/24837
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](htt …

Move changes to correct release in CHANGES.md

---

sdks/python/apache_beam/ml/inference/base.py

I was looking at custom model handler and I think this could cause a breaking change without this PR. 
https://github.com/apache/beam/blob/master/examples/notebooks/beam-ml/run_custom_inference.ipynb
Don't raise an error when update_model is called. if it is not implemented for custom model handler, it could raise NotImplementedError in Beam 2.46.0 when running RunInference …

Don't raise an error if update_model is not implemented for custom model handlers

---

sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/CdapIO.java
sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java

[CdapIO] Implement windowed write

---

website/www/site/content/en/documentation/ml/overview.md

This is a great overview video of Apache Beam ML
✨ [RENDERED](http://apache-beam-website-pull-requests.storage.googleapis.com/25302/documentation/ml/overview/index.html) ✨  …

Embed ML video to docs

---

sdks/go/pkg/beam/core/runtime/xlangx/expand_test.go

[Go SDK] skip automated expansion test

---

sdks/go/pkg/beam/core/runtime/xlangx/expand_test.go

[cherry-pick] skip automated expansion test

---

sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/control/ExecutionStateSamplerBenchmark.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ExecutionStateSampler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PTransformFunctionRegistry.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ExecutionStateSamplerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistryTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/PTransformFunctionRegistryTest.java

This cuts our per element processing overhead significantly down. For example in the ProcessBundleBenchmark.testLargeBundle we saw a reduction of about half of the execution state management overhead for each element (10.6% to 5.6% CPU overhead per element).
Before:
After:
The benchmark reflects this with a nice 11.5% performance improvement.
Before:
```
Result "org.apache.beam.fn.harness.jmh.ProcessBundleBenchmark.testLargeBundle":
3265.141 ±(99.9%) 238.744 ops/s [Average]
(min, avg, max) = (2952.616, 3265.141, 3525.482), stdev = 223.321
CI (99.9%): [3026.398, 3503.885] (assumes normal distribution)
```
After:
```
Result "org.apache.beam.fn.harness.jmh.ProcessBundleBenchmark.testLargeBundle":
3642.512 ±(99.9%) 45.865 ops/s [Average]
(min, avg, max) = (3582.394, 3642.512, 3713.820), stdev …
```

Swap setting a context from being on the hot path when we emit elements to only be done during bundle creation and teardown #21250

---

sdks/python/apache_beam/examples/inference/large_language_modeling/main.py
website/www/site/content/en/documentation/ml/large-language-modeling.md

Adds some more details from going through the instructions. …

Clarify llm download/loading instructions

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java

Allow for setMaxRetryJobs in BigQueryIO to be configurable

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

Fix output timestamp for multi output receiver in FnApiDoFnRunner #25344

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/UnboundedScheduledExecutorService.java
sdks/java/core/src/test/java/org/apache/beam/sdk/util/UnboundedScheduledExecutorServiceTest.java

ThreadPoolExecutor creates a new thread if offer(Runnable) returns false. With a SynchronousQueue under contention, this may return false even if there are already idle threads in the pool. To avoid creating a thread unnecessarily and growing the pool we modify offer to wait with a small timeout of 10ms. This may delay initial execution on the pool but that should be rare as it is encountered only once the high-watermark is exceeded.
Also add a timeout to the non-core threads so that the pool reduces size.
Both of these changes are motivated to reduce memory usage due to per-thread buffers in Beam and AvroCoder.
Add a test contending adds on the pool which previously showed the pool growing beyond the necessary amount (ie created 104 threads when 100 is sufficient).
**Please** add a …

Change UnboundedScheduledExecutorService to avoid creating threads when there is contention on the SynchronousQueue.

---

CHANGES.md
sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py

Make Python's BatchElements more aggressive batching in some cases, capping at 10 second rather than 1 second batches by default and excluding fixed cost in this computation. …

Better batching for higher fixed costs.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/DetectNewPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/QueryChangeStreamAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataDao.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataDaoTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/ChangeStreamTestPipelineOptions.java

[BEAM-12164] Enforced only positive state transitions from CREATED -> SCHEDULED -> RUNNING -> FINISHED for the change stream metadata table.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java

Add simple instructions on how to use Bigtable Change Stream API …

Add simple instructions on how to use Bigtable Change Stream API

---

sdks/python/apache_beam/pipeline_test.py
sdks/python/apache_beam/runners/worker/bundle_processor.py
sdks/python/apache_beam/transforms/environments.py

Addresses one of the main painpoints of #25312. …

Fail the pipeline when a mismatched Python or Beam version is detected.

---

sdks/go/pkg/beam/runners/dataflow/dataflowlib/metrics_test.go

Simplifies a composite literal protobuf in metrics_test.go, resolving a small nit.
Fixes #21516 …

[#21516] Simplify composite literal in metrics_test.go

---

sdks/go/cmd/specialize/main.go
sdks/go/pkg/beam/util/shimx/generate.go

Removes references to the deprecated strings.Title() function in the Go SDK in favor of cases.Title
Fixes #21514 …

Replace use of deprecated strings.Title function

---

release/src/main/scripts/build_release_candidate.sh
sdks/typescript/package.json

These were discovered while trying to run in a clean client. …

Minor updates to typescript generation.

---

build.gradle.kts
sdks/python/test-suites/direct/common.gradle

Explicitly set mongo container version for testing

---

sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/apache_beam/ml/inference/pytorch_inference_test.py
sdks/python/apache_beam/ml/inference/sklearn_inference.py
sdks/python/apache_beam/ml/inference/sklearn_inference_test.py

Adds support for optionally passing in batching controls as arguments to the sklearn and pytorch model handlers (tensorrt already does this as positional args).
This can be accomplished today by overriding the model handler, but it is a less clean experience. …

Support batching as config in RunInference (sklearn and pytorch)

---

CHANGES.md

Add a note on increased lower bounds.

---

runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/SamzaMetricsBundleProgressHandler.java

Major fixes: 
In #25068, we tried to support UDF metrics with the samza portable runner, but we were missing a step to copy beam metrics into samza metrics.
This change has been tested on the linkedin/beam mirror, and confirmed the metrics are working now.
Other fixes:
Cleaning up logs: lower a log line from `warn` to `debug`.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https …

Support samza portable UDF metrics.

---

playground/infrastructure/grpc_client.py

Fixed a bug with reading grpc timeout value
Bumped timeout value 
fixes #25360  …

Fixed reading env variable for grpc_timeout

---

website/www/site/content/en/documentation/io/built-in/google-bigquery.md

fix doc on bq sxtorage

---

sdks/go.mod
sdks/go.sum
sdks/go/pkg/beam/runners/prism/README.md
sdks/go/pkg/beam/runners/prism/internal/README.md

Initial commits for adding Prism Runner.
Uber PR for all changes: https://github.com/apache/beam/pull/25391
See #24789 …

[prism] Initial commit for READMEs and go.mod

---

website/www/site/content/en/documentation/ml/tensorrt-runinference.md

The PR fixes a minor typo in tensorRT documentation. It replaces 
```
--sdk_container_image="us.gcr.io/{GCP_PROJECT}/{MY_DIR}/tensor_rt tensor_rt"
```
with 
```
--sdk_container_image="us.gcr.io/{GCP_PROJECT}/{MY_DIR}/tensor_rt
``` …

Fix typo in args in documentation

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java

BigtableIO includes some options accepting ValueProvider. We don't plan on supporting ValueProvider values.
[![Build …

Remove ValueProvider from BigtableIO ReadChangeStream

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfig.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ByteStringRangeHelper.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamMetrics.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamMutation.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/TimestampConverter.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/UniqueIdGenerator.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ActionFactory.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/GenerateInitialPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/ChangeStreamDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/DaoFactory.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableAdminDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/DetectNewPartitionsDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/InitializeDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/ReadChangeStreamPartitionDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/model/PartitionRecord.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/restriction/ReadChangeStreamPartitionProgressTracker.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/restriction/StreamProgress.java

Annotate Cloud Bigtable implementation details as Internal …

Annotate Cloud Bigtable implementation details as Internal

---

website/www/site/content/en/documentation/pipelines/test-your-pipeline.md

This will make it easier to drop in these examples to get started with testing …

Add dependencies in some examples

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java

This fixes https://github.com/apache/beam/issues/25417 …

Copy environment capabilities when creating the WorkerPool for Java pipelines

---

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/transforms/PythonMap.java
sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/transforms/RunInference.java
sdks/java/extensions/python/src/test/java/org/apache/beam/sdk/extensions/python/transforms/PythonMapTest.java

Update PythonMap transform to accept extra packages

---

model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto

Remove PBD id filter from the SampleDataRequest; it was creating too much complexity for too little value.
Also rename request/response field names to match other instructions.
Task https://github.com/apache/beam/issues/25064 …

Data sampling proto

---

website/www/site/content/en/documentation/pipelines/test-your-pipeline.md

Whitespace lint is broken at https://github.com/apache/beam/pull/25425 …

Fix whitespace

---

sdks/go/pkg/beam/core/runtime/pipelinex/util.go
sdks/go/pkg/beam/runners/dataflow/dataflowlib/job.go
sdks/go/pkg/beam/runners/dataflow/dataflowlib/job_test.go

Handle #25417 but in the Go SDK. …

[#25417][go] copy env details to dataflow images

---

.test-infra/jenkins/job_CloudMLBenchmarkTests_Python.groovy
sdks/python/apache_beam/testing/benchmarks/cloudml/cloudml_benchmark_test.py
sdks/python/apache_beam/testing/benchmarks/cloudml/requirements.txt
sdks/python/test-suites/dataflow/common.gradle

Fixes: https://github.com/apache/beam/issues/25345 …

Add runtime metric to TFT tests

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsContainerImpl.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoConstants.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MetricsContainerImplTest.java

Support gauge metrics in portable mode.
The `getMonitoringInfos()` wraps the worker side metrics into `MonitoringInfos`, that is later returned to the runner though `ProcessBundleResponse`.
However, `getMonitoringInfos()` only implemented steps for counter and distribution metrics, and missed out the gauge. This PR adds the implementation to support gauge metrics.  …

Support gauge metrics in portable mode

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableAdminDao.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableAdminDaoTest.java

Add metadata table admin unit tests. Based off https://github.com/apache/beam/pull/25364. Merge into `bigtable-cdc-feature-branch` branch …

Add metadata table admin unit tests

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamMetrics.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/GenerateInitialPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/ChangeStreamDao.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/GenerateInitialPartitionsActionTest.java

Add to DetectNewPartitionDoFn to generate the initial list partitions to output. This only happens when the restriction tracker is at 0 which is the initial value of the restriction tracker.
This PR is based on https://github.com/apache/beam/pull/25364
GitHub …

Generate initial list of partitions to stream

---

sdks/java/container/license_scripts/dep_urls_java.yaml

Fix pulling licenses

---

sdks/java/container/license_scripts/dep_urls_java.yaml

Cherry pick changes from #25456 …

Cherry pick: Fix pulling licenses (#25456)

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Java_JMH_benchmarks.json

This also adds the distribution type as a tag as well. …

Update grafana dashboard to handle name change for CombinerTableBenchmark to PrecombineGroupingTableBenchmark

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamMetrics.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/ChangeStreamDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/encoder/MetadataTableEncoder.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/encoder/package-info.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/model/PartitionRecord.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/restriction/StreamProgress.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDaoTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/MetadataTableDaoTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/restriction/ReadChangeStreamPartitionProgressTrackerTest.java

Cloud Bigtable stream changes and handle Heartbeat responses …

Cloud Bigtable stream changes and handle Heartbeat responses

---

.github/workflows/go_tests.yml

Use codecov-action@v3; v2 is no longer supported due to node12 being unsupported. V3 uses the current supported action version of node. …

Use codecov-action@v3; v2 is no longer supported.

---

website/www/site/content/en/get-started/quickstart-py.md

Update the title to correctly reflect the new content. (follow up to : https://github.com/apache/beam/pull/24804) …

Update the title of the wordcount quickstart

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ActionFactory.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/GenerateInitialPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/ChangeStreamDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/DetectNewPartitionsDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/model/PartitionRecord.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/GenerateInitialPartitionsActionTest.java

We do not want to support end time in the first iteration of Cloud Bigtable Change Stream connector. …

Not including support for end time in Bigtable Change Stream connector

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerConfig.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadIT.java

SpannerIO: parameterizing partitionQuery and partitionRead timeouts. fixes #25025  …

SpannerIO: parameterizing partitionQuery timeout

---

sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformProvider.java

Fix provider to be found by AutoService

---

website/www/site/content/en/blog/beam-2.45.0.md

Update documents for 2.45

---

website/www/site/content/en/get-started/downloads.md

This is causing https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/ to persistently fail …

Fix whitespace check

---

website/www/site/content/en/documentation/io/connectors.md

#24744 removed some links because they weren't released yet. Now that 2.45.0 has been released we can add them back
Fixes #24745
✨ [RENDERED](http://apache-beam-website-pull-requests.storage.googleapis.com/25513/documentation/io/connectors/index.html) ✨ 
GitHub …

Add back links removed in #24744

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamMetrics.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamAction.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamActionTest.java

Cloud Bigtable stream changes and handle Mutation responses …

Cloud Bigtable stream changes and handle Mutation responses

---

sdks/go/pkg/beam/runners/prism/internal/jobservices/metrics.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/metrics_test.go

Adds metrics store handling and initial unit tests.
For Prism's initial implementation.
See https://github.com/apache/beam/issues/24789. …

[#24789][prism] internal/jobservices metrics + tests

---

website/www/site/content/en/contribute/release-guide.md

There's no reason a normal committer can't do this …

Move closing milestone out of PMC-only tasks

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

Update GCP cloud libraries BOM to 26.8.0 …

Update GCP cloud libraries BOM to 26.8.0

---

sdks/python/apache_beam/runners/worker/bundle_processor.py
sdks/python/apache_beam/runners/worker/bundle_processor_test.py
sdks/python/apache_beam/runners/worker/data_sampler.py
sdks/python/apache_beam/runners/worker/data_sampler_test.py
sdks/python/apache_beam/runners/worker/sdk_worker.py
sdks/python/apache_beam/runners/worker/sdk_worker_main.py
sdks/python/apache_beam/runners/worker/sdk_worker_test.py
sdks/python/apache_beam/transforms/environments.py

This adds the capability for the Python SDK to sample in-flight elements. The implementation modifies the ProcessBundleDescriptor when received by the BundleProcessor to create additional DataSampling PTransforms on PCollections. The samples are then returned when the SDK receives a SampleDataRequest.
Task #25064 …

Task #25064: Python SDK Data sampling implementation

---

runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/DefaultJobBundleFactory.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java
runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/environment/EmbeddedEnvironmentFactory.java
sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/ProcessBundleBenchmark.java
sdks/java/harness/jmh/src/test/java/org/apache/beam/fn/harness/jmh/ProcessBundleBenchmarkTest.java

Add support for all Java based portable runners to consume elements embedding on the control response.

---

website/www/site/content/en/documentation/io/built-in/google-bigquery.md

Include details on how to define BigQueryIO query execution project in Java SDK. …

Update BigQueryIO documentation with details on how to override the query execution project

---

sdks/java/io/cdap/README.md
sdks/java/io/sparkreceiver/2/README.md
website/www/site/content/en/documentation/io/built-in/cdap.md

Updated the complete examples links in the CdapIO and SparkReceiverIO READMEs and in the CdapIO website page.
Links to the examples' source code -> links to the folder with all examples and README. …

[CdapIO][SparkReceiverIO] Complete examples links in READMEs and CdapIO website page fixed

---

.github/workflows/pr-bot-pr-updates.yml

Run prbot updates on hosted runners

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java

This removes the overhead shown in https://user-images.githubusercontent.com/10078956/219762523-1e76e849-18b9-4c40-a513-000364baea52.png
This is for #21250 …

Stop paying the iterator object creation tax in MultiplexingMetricTrackingFnDataReceiver

---

sdks/python/apache_beam/ml/inference/tensorflow_inference_it_test.py
sdks/python/tox.ini

Fixes: https://github.com/apache/beam/issues/25552 …

Fix Tensorflow intergration test model path

---

sdks/go.mod
sdks/go.sum
sdks/go/examples/wasm/README.md
sdks/go/examples/wasm/wasm.go

This PR fixes #25429 bumping wazero version to 1.0.0-pre.9 and refactoring the wasm example.  The fix was tested following steps documented in [sdks/go/examples/wasm/README](https://github.com/damondouglas/beam/tree/25429-fix-wazero-example/sdks/go/examples/wasm/README.md) on the local, flink, and dataflow runners.  In all three environments wrote expected output:
```
Hello, Ada!
Hello, Lovelace!
Hello, World!
Hello, Beam!
Hello, Senior López!
Hello, Random unicorn emoji 🦄!
```
- ~If this contribution is large, please file an Apache [Individual Contributor License …

Bump github.com/tetratelabs/wazero from 1.0.0-pre.7 to 1.0.0-pre.9 in /sdks

---

sdks/go/pkg/beam/runners/prism/internal/jobservices/artifact.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/metrics.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/server.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/server_test.go

Add in the initial job services for managing a job.
Unit test coverage is lower since until involving other SDKs the runner is expected only to be run on the same machine against a local process, so this code will change a fair bit.
See #24789 for more information. …

[#24789][prism] Minimum required jobservices

---

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager_test.go

Add in the core element manager for Prism. This is the heart of the runner, tracking watermarks for stages, and when stages are able to fire with which elements.
See https://github.com/apache/beam/issues/24789 for more information. …

[prism] Add in element manager

---

sdks/python/apache_beam/runners/direct/transform_evaluator.py
sdks/python/apache_beam/utils/timestamp.py
sdks/python/apache_beam/utils/timestamp_test.py

If the tzinfo field is not filled out, we currently fail with an unhelpful error that doesn't show the problem or the message causing the problem. This fixes that problem for pubsub and helps with other consumers of from_utc_datetime …

Better error for missing timezone info

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ByteStringRangeHelper.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamMetrics.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/ReadChangeStreamPartitionDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/restriction/ReadChangeStreamPartitionProgressTracker.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/restriction/StreamProgress.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ByteStringRangeHelperTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDaoTest.java

Cloud Bigtable stream changes and handle CloseStream responses …

Cloud Bigtable stream changes and handle CloseStream responses

---

sdks/go/pkg/beam/io/mongodbio/read.go

Fixes #25533 and refactors the mongodbio.Read SDF methods to take a context parameter instead of creating a context.Background and return an error instead of panicking. …

[Go SDK]: Use context param and error return value in mongodbio.Read SDF methods

---

sdks/go/pkg/beam/core/runtime/xlangx/expand.go

[Go SDK] Remove unnecessary error check

---

CHANGES.md
sdks/go/pkg/beam/runners/prism/README.md
sdks/go/pkg/beam/runners/prism/internal/coders_test.go
sdks/go/pkg/beam/runners/prism/internal/execute.go
sdks/go/pkg/beam/runners/prism/internal/execute_test.go
sdks/go/pkg/beam/runners/prism/internal/separate_test.go
sdks/go/pkg/beam/runners/prism/internal/stage.go
sdks/go/pkg/beam/runners/prism/prism.go

Add the final connections for making the runner usable.
Add in the pipeline execution tests, and initial separation harness tests.
Note, SDF splitting isn't yet implemented, although non-splitting expansion is supported.
See #24789. This doesn't complete the the issue as the issue is intended to replace the default Go SDK runner. This PR doesn't yet set prism as default, which would require at minimum instructions for switching back to the legacy direct runner, and for repository infrastructure to test on presubmit. …

[#24789][prism] V0 Go Direct Runner Replacement, Prism.

---

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java
runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/EnvironmentsTest.java

Add Data Sampling capability URN to Java SDK

---

.test-infra/jenkins/CommonJobProperties.groovy

It is found that when Jenkins is putting much pressure on GitHub, GitHub refuses to connect and the job stucks at fetching github. As far as I know all jobs are either run on branch head (master, release branches, etc) or pull request head, so we should be able use shallow clone and skip tags.
Ref: https://plugins.jenkins.io/git/#plugin-content-checkout-with-a-shallow-clone-to-reduce-data-traffic
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers …

Apply shallow clone for jenkins

---

sdks/python/scripts/generate_pydoc.sh
sdks/python/tox.ini

Don't install packages during docs build. Mock them instead. …

Move dependencies from tox.ini docs task to mocking

---

.test-infra/dataproc/flink_cluster.sh

flink python and go load tests failing since Feb 5 (e.g. https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_ParDo_Flink_Batch/) because the preview version of DataProc 2.1 is no longer available. Bump to the released 2.1 version
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/b …

Bump to Dataproc 2.1

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/io/Providers.java
sdks/java/extensions/schemaio-expansion-service/src/main/java/org/apache/beam/sdk/extensions/schemaio/expansion/ExternalSchemaIOTransformRegistrar.java

Cherry Pick: Prioritise Avro providers from "extensions/core" (#25611)

---

CHANGES.md

realized that the CHANGE.md not get updated yet when review of #25584 done. This could probably be added to the release step along with the version label bump commit (e.g. https://github.com/apache/beam/commit/27c55107e56e3cf86955d0d3ef2e71d23c1d299e)
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/ap …

Update CHANGE.md to 2.47.0

---

sdks/python/apache_beam/pipeline.py

Fix typo in docstring

---

CHANGES.md
sdks/python/apache_beam/io/fileio.py
sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py
sdks/python/scripts/generate_pydoc.sh
sdks/python/setup.py

These were available via the dataframes API, but asking how to do this is a common question.  …

Add ReadFrom/WriteTo Csv/Json as top-level transforms to the Python SDK.

---

sdks/typescript/package.json

This is missing from release automation …

Fix ts version on master

---

sdks/typescript/package.json

This is missing the needed release automation …

Move beam to 2.46 on release branch for ts

---

release/src/main/scripts/build_release_candidate.sh

This is a workaround to the problems in https://github.com/apache/beam/issues/25649 and gets the release script working. …

gen protos before running py38-docs in build_release_candidate

---

sdks/python/tox.ini

Tox has changed this name - https://tox.wiki/en/latest/config.html#allowlist_externals
This has been supported since 3.18.0 - https://tox.wiki/en/3.18.1/changelog.html#v3-18-0-2020-07-23 and is now fully removed in tox >=4. Without this change, some tooling doesn't work on the newest tox …

whitelist->allowlist in tox.ini

---

release/src/main/scripts/set_version.sh

This was missed in the previous updates …

Add typescript to changed version files

---

sdks/python/apache_beam/io/azure/integration_test/docker-compose.yml

Python3.7 PostCommit  Current failing with error
```
HttpResponseError(\'The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry.
If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch.
Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error.
RequestId:a37b6d7b-9698-45c1-a77c-e66a0e615a33
Time:2023-02-27T19:22:59.106Z
ErrorCode:InvalidHeaderValue\')}')}
```
recent update of blob-storage-client (https://pypi.org/project/azure-storage-blob/12.15.0/) likely bumped the azure API version and need azurite upgrade to run the integration test. …

Fix Python3.7 PostCommit Azure integration test

---

sdks/python/apache_beam/io/azure/integration_test/docker-compose.yml
sdks/python/apache_beam/ml/inference/tensorflow_inference_it_test.py

These both are causing Postcommits to fail, this fixes the problems. They both only touch tests, so they should be very safe. …

Cherry pick some changes to fix the python postcommits

---

.test-infra/metrics/grafana/dashboards/perftests_metrics/Python_TFT_Criteo_benchmarks.json
sdks/python/apache_beam/testing/benchmarks/cloudml/cloudml_benchmark_test.py

Create tft criteo grafana dashboards

---

playground/backend/internal/preparers/python_preparers.go
playground/backend/internal/preparers/python_preparers_test.go
playground/backend/logging.properties

Set INFO instead of DEBUG log level for Java and Python pipelines 
resolves https://github.com/apache/beam/issues/23942 …

Adjust log level for Playground java and Python pipelines 

---

runners/google-cloud-dataflow-java/build.gradle

Part of https://github.com/apache/beam/issues/25675 this will get https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/ back to green hopefully.
This is a known issue on the Dataflow Unified Worker …

Sickbay autosharding test on Dataflow V2

---

runners/google-cloud-dataflow-java/build.gradle

Cherry pick: Sickbay autosharding test on Dataflow V2 (#25677)

---

sdks/python/test-suites/tox/common.gradle

These are causing tests to fail (see #25696) …

Temporarily remove dask tests

---

sdks/python/test-suites/tox/common.gradle

Cherry pick of #25697 - these are causing tests to fail (see https://github.com/apache/beam/issues/25696)
[![Build …

Cherry-pick: Remove dask tests (#25697)

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProviderTest.java

Changing the metric name "element-counter" and "error-counter" to be more descriptive of the pipeline type.
[![Build …

changed metric name to be descriptive of the pipeline type

---

learning/tour-of-beam/backend/README.md
learning/tour-of-beam/backend/internal/storage/schema.go

Extracting datastore namespace into environment variable
resolves #25712  …

Externalize datastore namespace for ToB

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ParDoTranslatorBatch.java

Prevent Stackoverflow in ParDo load tests when using RDDs to break linage for large number of consecutive ParDos. …

[Spark Dataset runner] Prevent stackoverflow in ParDo load tests

---

website/www/site/content/en/documentation/ml/large-language-modeling.md

This PR aims to update the documentation by adding parameters that I used to successfully run t5-11b model using Dataflow Runner. …

Update documentation by adding parameters for Dataflow Runner

---

.github/workflows/playground_backend_precommit.yml
.github/workflows/playground_examples_ci_reusable.yml
playground/backend/build.gradle.kts
playground/backend/cmd/server/http.go
playground/backend/cmd/server/wrapper.go
playground/backend/env_setup.sh
playground/backend/internal/cache/cache.go
playground/backend/internal/code_processing/code_processing.go
playground/backend/internal/constants/datastore_constants.go
playground/backend/internal/constants/emulator_constants.go
playground/backend/internal/db/datastore/datastore_db.go
playground/backend/internal/environment/environment_service.go
playground/backend/internal/environment/property.go
playground/backend/internal/executors/executor.go
playground/backend/internal/executors/executor_builder.go
playground/backend/internal/logger/logger.go
playground/backend/internal/preparers/go_preparers.go
playground/backend/internal/preparers/java_preparers.go
playground/backend/internal/preparers/preparer.go
playground/backend/internal/preparers/preparer_test.go
playground/backend/internal/preparers/python_preparers.go
playground/backend/internal/preparers/scio_preparers.go
playground/backend/internal/setup_tools/life_cycle/life_cycle_setuper.go
playground/backend/internal/streaming/run_output_writer.go
playground/backend/internal/tests/test_data/test_data.go
playground/backend/internal/utils/common.go
playground/backend/internal/utils/preparers_utils.go
playground/backend/internal/utils/system_utils.go
playground/backend/internal/validators/java_validators.go
playground/backend/internal/validators/scio_validators.go

Playground PreCommit checks were not being executed in CI.
- Add Github Action to run PreCommit checks
- Add gofmt check to precommit
- Reformat code to pass gofmt check
resolves #25745 …

Run Playground precommit checks in CI, check gofmt, reformat Go code

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ParDoTranslatorBatch.java

Very minor cleanup, removing some obsolete code …

[Spark Dataset runner] Remove obsolete code

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java

Fix DatastoreIO bug causing low throughput on certain writes

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java

passing consumer configs from user-passed parameters

---

website/www/site/i18n/footer/en.yaml
website/www/site/layouts/partials/footer.html

The item "Contact Us" displayed is in the Resources block of the footer instead of community block . 'addresses #22695 ' …

apache#22695

---

sdks/java/testing/load-tests/build.gradle

Disable Spark UI for load tests …

Disable Spark UI for load tests

---

website/www/site/content/en/get-started/downloads.md

Updates 2.45.0 artifacts to use archive.apache.org

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py37/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/setup.py

Accept pymongo 4.x for Python SDK

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Reuse client when constructing StreamWriter

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java

Make IncomingMessage class public so it can be accessed in other packages.  Otherwise, the PubsubTestClient class isn't really usable. The counter-part OutgoingMessage is public already. …

make incoming message public

---

CHANGES.md

Mark that 2.46 has been released now that the release is finalized

---

sdks/python/apache_beam/io/gcp/pubsub_io_perf_test.py

Remove save main session option in pubsubio_perf_test

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/resourcehints/ResourceHints.java

We have report that users pass in values like `withMinRam(1073741824 * 16)` crashes the pipeline after job starts. This is due to java literal int overflow: `1073741824 * 16 = 0`. While this can be avoided by setting up spotbug guard. It is nice to have a more obvious logging for this error. …

LOG error for illegal ramBytes

---

examples/java/src/main/java/org/apache/beam/examples/snippets/Snippets.java

Original Fix for [BEAM-14307] had incorrect placement of combiner …

[BEAM-14307] Re-Fix Slow Side input pattern bug in sample

---

sdks/python/apache_beam/typehints/native_type_compatibility.py
sdks/python/apache_beam/typehints/native_type_compatibility_test.py

Adds support for the `collections.abc` module's `Iterable`, `Iterator`, and `Generator` containers as type hints. The `typing` module equivalents had previously been supported but are deprecated as of Python 3.9, so support for the new recommended container types was necessary.  …

Add support for common collections.abc types

---

sdks/go.mod
sdks/go.sum
sdks/go/examples/wasm/README.md

This PR bumps the wazero version to v1.0.0-rc.1.  It was tested on all three local, flink and Dataflow runners per [instructions](https://github.com/damondouglas/beam/blob/bump-wazero-v1.0.0-rc.1/sdks/go/examples/wasm/README.md).
~[ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.~
~[ ] Update `CHANGES.md` with noteworthy changes.~
~[ ] If this contribution is large, please file an Apache [Individual Contributor …

Bump wazero to v1.0.0-rc.1

---

runners/google-cloud-dataflow-java/build.gradle

Re-enable Storage Write API tests for Runner v2

---

.github/REVIEWERS.yml

I now work on another part of Dataflow and will no longer have the bandwidth to do arbitrary Beam Java reviews. …

Drop myself from Java reviewers

---

release/src/main/scripts/start_snapshot_build.sh
website/www/site/content/en/contribute/release-guide.md

Clarifies some things that were not obvious to me as I went through the process. …

Update release docs with problems encountered during release

---

website/www/site/content/en/documentation/ml/about-ml.md
website/www/site/content/en/documentation/ml/data-processing.md
website/www/site/content/en/documentation/ml/inference-overview.md
website/www/site/content/en/documentation/ml/large-language-modeling.md
website/www/site/content/en/documentation/ml/overview.md
website/www/site/content/en/documentation/sdks/python-machine-learning.md
website/www/site/content/en/documentation/transforms/python/elementwise/runinference-pytorch.md
website/www/site/content/en/documentation/transforms/python/elementwise/runinference-sklearn.md
website/www/site/content/en/documentation/transforms/python/elementwise/runinference.md
website/www/site/layouts/partials/section-menu/en/documentation.html

* Changed the AI/ML Overview page to a Get Started page where users can navigate directly to the content they're looking for.
* Created an About ML page and moved the conceptual content from the Overview to that page. Added content from the Python ML page to this page. Eventually, this page/section should become the primary ML content, and at that point, we can make the Python page targeted to Python.
* Restructured the TOC to categorize the pages. The categorization matches the categories in the Overview page.
* Updated the Python ML page
* Specify that the page is for Python
* Add links to the main Beam ML content
* Updated the RunInference transform content:
* Moved the examples into their own pages to improve discoverability
* Added those pages to the TOC
* Fixed some headings …

Reorganizing the ML content

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamZetaSqlCalcRel.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamZetaSqlCalcRelTest.java
sdks/java/extensions/sql/zetasql/src/test/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSqlDialectSpecTest.java

The reverted change causes incorrect results in error cases in the ZetaSQL compliance tests.
This reverts commit 299be58cf997d9e1561409034692ea4f2d4ff357.
The reverted change caused failure in ZetaSQL compliance testing, specifically for error cases.
GitHub …

Revert "Adding support for DLQ for ZetaSQL (#25426)"

---

sdks/python/apache_beam/io/hdfs_integration_test/docker-compose.yml

Fixes Python PostCommit current failing.
Tested locally:
```
test_1      | ___________________________________ summary ____________________________________
test_1      |   hdfs_integration_test: commands succeeded
test_1      |   congratulations :)
hdfs_it-non-jenkins_test_1 exited with code 0
Stopping hdfs_it-non-jenkins_datanode_1 ... 
Stopping hdfs_it-non-jenkins_namenode_1 ... 
Stopping hdfs_it-non-jenkins_datanode_1 ... done
Stopping hdfs_it-non-jenkins_namenode_1 ... done
Aborting on container exit...
real    2m16.029s
user    0m1.031s
sys     0m0.132s
+ finally
+ docker-compose -p hdfs_IT-non-jenkins down
Removing hdfs_it-non-jenkins_test_1     ... 
Removing hdfs_it-non-jenkins_datanode_1 ... 
Removing hdfs_it-non-jenkins_namenode_1 ... 
Removing hdfs_it-non-jenkins_datanode_1 ... …
```

Use self hosted hadoop docker image in hdfsIntegrationTest

---

sdks/python/MANIFEST.in

Remove changes from MANIFEST.in

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/Read.java

Before this change, the portable Java splitting of BoundedSource was capped at 64k. Changed to match the Python behavior, which has some fairly reasonable default split sizes that seem to work well in practice. …

Update default splitting behavior to get fewer, larger, splits

---

sdks/python/apache_beam/typehints/opcodes.py
sdks/python/apache_beam/typehints/trivial_inference.py
sdks/python/apache_beam/typehints/trivial_inference_test.py

Adds typehinting support for CPython 3.11 opcodes, aiming to unblock adding support for Python 3.11.  …

Add support for CPython 3.11 opcodes

---

sdks/java/io/google-cloud-platform/build.gradle

These tests are failing due to service-side changes
This mitigates #25851 …

Disable firestore integration tests temporarily

---

sdks/go/pkg/beam/io/filesystem/filesystem.go
sdks/go/pkg/beam/io/filesystem/gcs/gcs.go
sdks/go/pkg/beam/io/filesystem/local/local_test.go
sdks/go/pkg/beam/io/filesystem/memfs/memory_test.go
sdks/go/pkg/beam/io/filesystem/s3/s3.go
sdks/go/pkg/beam/io/filesystem/s3/s3_test.go
sdks/go/pkg/beam/io/filesystem/s3/util_test.go
sdks/go/pkg/beam/util/fsx/prefix.go
sdks/go/pkg/beam/util/fsx/prefix_test.go

Fixes #25810 and makes the behavior of filesystem List more consistent across the different implementations
[![Build …

[Go SDK]: Align filesystem List behaviors

---

sdks/go/pkg/beam/pardo.go

Fixes #25778 and updates the section about splittable DoFns in the `beam.ParDo` doc comment …

[Go SDK]: Update beam.Pardo doc comment about SDFs

---

sdks/go/pkg/beam/io/bigqueryio/bigquery.go
sdks/go/test/integration/io/bigqueryio/bigqueryio_test.go
sdks/go/test/integration/io/bigqueryio/helper_test.go

Addresses [25318](https://github.com/apache/beam/issues/25318), allows one to set a create disposition when writing to BigQuery so that the user can control whether a table should be created or not. I tried to make the changes backwards-compatible. 
I'm a newbie to Go and beam, so I was hoping for some guidance around testing. I wasn't quite sure if it was worth creating a unit test for this small logic, or perhaps whether I should create some sort of integration test to see whether a pipeline integrates correctly with bigquery. Any suggestions would be most welcome!  …

add write options with create disposition for bigqueryio

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ByteStringRangeHelper.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDao.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ByteStringRangeHelperTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDaoTest.java

Advance DetectNewPartition's watermark  by aggregating the low watermark of ReadChangeStreamPartitions
We do this to hold the low watermark for the pipeline back when not all partitions are being streamed by ReadChangeStreamPartitions (after splits and merges before DetectNewPartitions has output the new partitions)
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.c …

Advance DetectNewPartition's watermark 

---

build.gradle.kts

Move inference tests from py37 to py38

---

sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_test.py

These are aliases for the first and last transform in the transforms list, but may be a more natural way to express a pipelines's intent. …

Add a source and sink option to yaml pipelines.

---

examples/notebooks/get-started/learn_beam_basics_by_doing.ipynb
examples/notebooks/get-started/try-apache-beam-go.ipynb
examples/notebooks/get-started/try-apache-beam-java.ipynb
examples/notebooks/get-started/try-apache-beam-py.ipynb

Fix the invalid notebook error …

Move license to a code block

---

buildSrc/build.gradle.kts
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/Dockerfile
sdks/java/container/common.gradle
sdks/python/container/Dockerfile
sdks/python/container/common.gradle
sdks/typescript/container/Dockerfile
sdks/typescript/container/build.gradle
sdks/typescript/package-lock.json

A start for #20807. This just allows building the images; full testing, etc. remains to be done. …

[BEAM-20807] Support Beam docker images on ARM64.

---

examples/java/build.gradle

Previously, this task was configured eagerly and also pulling properties from the wrong place so neither main class nor args could be passed on the command line. …

Fix :examples:java:execute so it can be used on the command line

---

playground/terraform/README.md
playground/terraform/build.gradle.kts

- Removed all `exec{}` blocks which relied on system-installed terraform and replaced them with TerraformTask derivatives
- Pass `docker-repository-root` through gradle parameters as this value should be set as a global parameter before projects which use docker plugin are loaded
resolves #25901
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/m …

Remove exec calls to terraform from playground/terraform/build.gradle.kts

---

examples/notebooks/beam-ml/tfma_beam.ipynb

This matches the pattern from our other notebooks (and is convenient).
✨ [RENDERED](https://github.com/apache/beam/blob/users/damccorm/tfma-links/examples/notebooks/beam-ml/tfma_beam.ipynb) ✨  …

Add links to tfma notebook for running in colab/github

---

.github/workflows/run_perf_alert_tool.yml

Add write permissions to perf analysis yml file

---

CHANGES.md
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/CloudDebuggerOptions.java

Part of #25959
See discussion in https://github.com/apache/beam/pull/25960#discussion_r1146856705 …

Deprecate Cloud Debugger and its pipeline options

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslator.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableReadOptions.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteOptions.java

BigtableIO is migrated to use java-bigtable veneer client instead bigtable-client-core. As part of the effort, we ported over some of the BigtableOptions that could be configured by customers. This pr translates more BigtableOptions configurations to veneer settings. However, we don't want to expose these options on BigtableIO surface yet. 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_ST …

fix: Porting more BigtableOptions

---

sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipeline.java
sdks/java/core/src/test/java/org/apache/beam/sdk/testing/TestPipelineTest.java

Fixes #25699
* Fix TestPipeline.runWithAdditionalOptionArgs ignore additionalArgs when system property PROPERTY_BEAM_TEST_PIPELINE_OPTIONS is empty …

Fix TestPipeline.runWithAdditionalOptionArgs ignore additionalArgs

---

playground/backend/cmd/server/controller.go
playground/backend/cmd/server/controller_test.go
playground/backend/internal/environment/environment_service.go
playground/backend/internal/environment/environment_service_test.go

Exit immediately from controller methods which should not be executed when the backend is running in a runner mode
resolves #25929 …

[Playground] Guard router methods from being executed on runners

---

playground/backend/internal/db/datastore/datastore_db.go
playground/backend/internal/db/mapper/mapper.go
playground/backend/internal/db/mapper/precompiled_object_mapper.go
playground/backend/internal/db/mapper/precompiled_object_mapper_test.go

Use the same example id that was used to query precompiled examples
addresses #25468  …

Fix example id for precompiled objects
