apache/beam

CHANGES.md
=> Update CHANGES.md for HBaseIO.WriteRowMutations

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java
Small change to make it easier to debug these error messages. …
=> BigQueryHelpers: log statuses using PrettyString

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ByteStringRangeHelper.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamContinuationTokenHelper.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamMetrics.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsAction.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionAction.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDao.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ByteStringRangeHelperTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/ChangeStreamContinuationTokenHelperTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsActionTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionActionTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDaoTest.java
Also update this to support API that will populate the `NewPartitions` fields on CloseStreams and maintain backwards compatibility with old API which will not. …
=> Make DetectNewPartitions handle Splits and Merges

sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtobufUtil.java, sdks/java/extensions/protobuf/src/test/java/org/apache/beam/sdk/extensions/protobuf/ProtobufUtilTest.java
ProtobufUtil.checkProto2Syntax is not used in beam and is not publicly exposed.
This type of utility method should also become obsolete in future versions of protobuf. …
=> Remove unused checkProto2Syntax from ProtobufUtil.java and test.

sdks/python/test-suites/tox/py38/build.gradle, sdks/python/tox.ini
=> Add pytorch 2.0 tests

sdks/go.mod, sdks/go.sum, sdks/go/pkg/beam/runners/prism/internal/coders.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go
Update slog to fix breaking changes. This is blocking some dependabot updates, which update slog incidentally. Since slog is still in preview, it can make breaking changes, however, it's becoming more stable with fewer edges. …
=> [Go SDK] Update slog in prism to fix breaking changes.

runners/samza/src/main/java/org/apache/beam/runners/samza/SamzaPipelineOptions.java
This reverts commit 14ca840f3462aa9ba3ebbe773b498d4a914d50aa.
We found out there are other problems when having both Samza and Flink runners in the same classpath, so this change doesn't help but introduces some backward incompatible side effects. Reverting it for now. …
=> Revert "Change the type of Samza Runner MaxBundleSize pipeline option (#25854)"

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/container/license_scripts/dep_urls_java.yaml
Bumping up the libraries bom and spanner java client libraries version. …
=> Bumping up the Cloud libraries bom and spanner java client libraries version

.github/actions/setup-self-hosted-action/action.yml, .github/workflows/local_env_tests.yml, .github/workflows/python_tests.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, release/go-licenses/Dockerfile, sdks/go/run_with_go_version.sh
To ensure the boot loaders are built from the most up to date Go standard library version.
Also strips some needless version specifying in the self-hosted-runner set up. Go doesn't have the same runtime version issues Python and Java have, and should follow the latest Go version. Either the action needs Go or it doesn't. …
=> [Go SDK] Update beam infra to Go 1.20.2

.github/REVIEWERS.yml
Right now, I'm picking up too many reviews. I've done [422 reviews of PRs created in the last 6 months](https://github.com/apache/beam/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Adamccorm+created%3A%3E%3D2022-09-01+-author%3Adamccorm) between ML/Python, Tour of Beam, Beam playground, infrastructure reviews, and Go.
I think `@abacn` has done the 2nd most [with 137](https://github.com/apache/beam/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Aabacn+created%3A%3E%3D2022-09-01+-author%3Aabacn+) so I'm way out of band here. `@lostluck` is the only other person I'm aware of who has done at least 100.
Dropping Go won't fully resolve this, but it should help and its the area I'm probably least needed at this point. …
=> Remove myself from Go reviewers

sdks/go/container/Dockerfile, sdks/go/container/build.gradle
=> [BEAM-20807] Support Beam Go docker images on ARM64.

examples/notebooks/beam-ml/run_inference_xgboost.ipynb
This PR adds the notebook example for the XGBoostModelhandler …
=> Add XGBoost example notebook

sdks/python/apache_beam/internal/dill_pickler.py, sdks/python/apache_beam/transforms/window_test.py
Fix some known compatibility issues with newer versions of dill.
See: #24143 , https://github.com/apache/beam/pull/24143
=> Fix compatibility with dill 0.3.6.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
fixes: https://github.com/apache/beam/issues/26058
=> Restore deleted reference to pendingInserts.clear()

sdks/python/apache_beam/__init__.py
The Python SDK is stable now, no need to scare first time users. :) …
=> Remove status disclaimer from pydoc root.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/TimestampConverter.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ActionFactory.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamAction.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/ReadChangeStreamPartitionDoFn.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/BytesThroughputEstimator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/EncodingException.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/NullThroughputEstimator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/SizeEstimator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/ThroughputEstimator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/package-info.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/TimestampConverterTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamActionTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/ReadChangeStreamPartitionDoFnTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/BytesThroughputEstimatorTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/estimator/NullThroughputEstimatorTest.java
Estimate throughput for ReadChangeStreamPartition and use it to estimate the backlog. This is returned from GetSize so it can be used to autoscale …
=> Implement GetSize for ReadChangeStream to support autoscaling 

playground/frontend/playground_components/assets/symbols/go.g.yaml, sdks/go/pkg/beam/runners/universal/runnerlib/stage.go, sdks/go/pkg/beam/runners/universal/runnerlib/stage_test.go
There are some ifs that always return - this cleans those up and cleans up some initialisms that weren't properly capitalized while at it. …
=> Clean up some unneccessarily nested ifs in stage.go

examples/notebooks/beam-ml/run_inference_tensorflow.ipynb, examples/notebooks/beam-ml/run_inference_tensorflow_with_tfx.ipynb
Different notebooks to demonstrate `tfx-bsl`'s model handler and `TFModelHandlerNumpy`. Majority of the content is same as earlier notebook. …
=> [Python] Separate out notebooks for tensorflow with tfx and built-in model handler

release/src/main/python-release/python_release_automation.sh
=> Add Python 3.11 to python_release_automation.sh

.github/REVIEWERS.yml
@liferoad  - feel free to suggest alternative group of people as you see fit. Thanks. …
=> Update REVIEWERS list

.asf.yaml
They will be managing an infrastructure upgrade project and needs these permissions to do so. …
=> Give andreydevyatkin issue triage permissions

.test-infra/jenkins/job_PreCommit_Java_IOs.groovy, sdks/java/core/build.gradle
* Follow up of #25956 where some module has different package name than module folder name
* Clean up leftover code …
=> Fix Jacoco not working for a few modules

.test-infra/jenkins/job_PostCommit_Python_Sickbay.groovy, .test-infra/jenkins/job_PreCommit_Portable_Python.groovy, build.gradle.kts, sdks/java/container/license_scripts/requirement.txt
=> Fix a couple of Python3.11 support followup

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkExecutionEnvironments.java, runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineOptions.java
Disable operator chaining hurts performance, but it is useful for diagnosing and understand how beam translate beam job to flink job. I have verified it locally. Here's the screenshots of flink pipeline  w/wo operator chain.
* Enable operator chain (default)
* Disable operator chain 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test- …
=> [#26095][Feature Request]: Allow to set operator chaining for flink runner

.test-infra/jenkins/job_PostCommit_Python_Sickbay.groovy, .test-infra/jenkins/job_PreCommit_Portable_Python.groovy, build.gradle.kts, sdks/java/container/license_scripts/requirement.txt
=> [release-2.47.0] Cherry pick #26151 and #26174 into release branch

release/src/main/scripts/cut_release_branch.sh
Adds a `git add` for the TypeScript package config that is changed in set_version.sh but was not included in the commit incrementing to 2.48.0 …
=> Update release branch script to increment TypeScript version

examples/notebooks/beam-ml/README.md
A bunch of notebooks have been added in the past few months, but few of them have made it into the Readme.
[![Build …
=> Add recently added notebooks to readme

sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOIT.java
=> [release-2.47.0] Cherry pick #26179 into release branch

sdks/go/container/Dockerfile, sdks/go/container/build.gradle, sdks/java/container/Dockerfile, sdks/java/container/common.gradle, sdks/python/container/Dockerfile, sdks/python/container/common.gradle, sdks/typescript/container/Dockerfile, sdks/typescript/container/build.gradle
Cherry pick of #26183 to resolve issues with skipping go licences in dev containers. (Release containers didn't have this issue).
Fixes https://github.com/apache/beam/issues/26180 for 2.47.0. …
=> Touch a dummy file for go licenses.

.test-infra/jenkins/CommonJobProperties.groovy, .test-infra/jenkins/PrecommitJobBuilder.groovy, .test-infra/jenkins/job_PostCommit_Go_ValidatesRunner_Flink.groovy, .test-infra/jenkins/job_PostCommit_Java_Nexmark_Flink.groovy, .test-infra/jenkins/job_PostCommit_Python_Examples_Flink.groovy, .test-infra/jenkins/job_PreCommit_Java.groovy, .test-infra/jenkins/job_PreCommit_Python.groovy, .test-infra/jenkins/job_PreCommit_SQL.groovy
These builds are taking up too much space, so we should retain less. See https://lists.apache.org/thread/3qsl57mdzgqvgt2lm2mmw201f6dckw22 …
=> Reduce build retention to 40 for some builds

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
Cherry pick the BigtableIO fix #26205 into release 2.47.0.  …
=> [release-2.47.0] Cherrypick #26205 into release branch

playground/backend/cmd/server/controller.go, playground/backend/internal/code_processing/code_processing.go, playground/backend/internal/code_processing/code_processing_test.go, playground/backend/internal/utils/cache_utils.go, playground/backend/internal/utils/cache_utils_test.go
- Refactor pipeline execution functions to accept only one context
- Return errors from pipeline functions
- Use context cancellation function to cancel execution
resolves #25277
resolves #25077 …
=> [Playground] Simplify contexts in code_processing/Process()

.github/REVIEWERS.yml
=> Remove Pablo from Python reviewers

examples/notebooks/beam-ml/automatic_model_refresh.ipynb, examples/notebooks/beam-ml/run_inference_multi_model.ipynb, examples/notebooks/beam-ml/run_inference_pytorch.ipynb, examples/notebooks/beam-ml/run_inference_sklearn.ipynb, examples/notebooks/beam-ml/run_inference_tensorflow.ipynb, examples/notebooks/beam-ml/run_inference_tensorflow_with_tfx.ipynb, examples/notebooks/beam-ml/run_inference_with_tensorflow_hub.ipynb, examples/notebooks/beam-ml/run_inference_xgboost.ipynb, examples/notebooks/beam-ml/tfma_beam.ipynb
Copy editing Beam ML notebooks to prepare to pull them into DevSite.
Also added Colab/Github buttons to the Automatic model refresh notebook. …
=> Copy editing Beam ML notebooks

sdks/java/core/src/main/java/org/apache/beam/sdk/io/UnboundedSource.java
Description :
Added a the description point `<p>Note that: The implementations of this interface should be encodable (have an associated Coder)` about UnboundedSource.CheckpointMark. fixes #19708 …
=> Added checkpoints description. Resolves : Improve checkpoints documentation #19708

sdks/go/test/integration/integration.go
Continue to get some signal from Samza by filtering Debezium from running against it. #26126 to track this eventually being resolved so we can re-enable it.
This PR to be cherry picked to resolve release blocker: #26241. …
=> [#26126] Disable Debezium xlang test against Samza runner.

.github/workflows/stale.yml
I went to run this manually to help us catch up on our labels and realized I couldn't. I'd still like to run this manually …
=> Add manual trigger to stale

sdks/java/core/src/main/java/org/apache/beam/sdk/io/ReadAllViaFileBasedSource.java, sdks/java/core/src/main/java/org/apache/beam/sdk/io/ReadAllViaFileBasedSourceTransform.java, sdks/java/core/src/main/java/org/apache/beam/sdk/io/ReadAllViaFileBasedSourceWithFilename.java, sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java, sdks/java/core/src/test/java/org/apache/beam/sdk/io/AvroIOTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOReadTest.java
Adds `ReadAllViaFileBasedSourceWithFilename`, which retains the input filename with the read elements.
We (spotify) regularly have this as an internal feature request, typically where some id or key is part of the filename or directory itself.
GitHub Actions …
=> Add filename-retaining ReadAllViaFileBasedSource

sdks/python/apache_beam/runners/dataflow/internal/names.py
TODO: rerun tests after containers are actually released.
=> Update dev containers for Dataflow

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsContainerImpl.java, runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsContainerStepMap.java, runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsMap.java
- use forEach instead of requiring  Iterator/UnmodifiableIterator overhead
- optimize shortId cache hasing by just using MetricName as stepName is fixed
- reduce MetricKey objects
- avoid MetricsUpdate construction in getMonitoringData by directly processing maps …
=> Optimize counters by reducing allocations

sdks/go/test/integration/integration.go
=> [Cherry Pick #26243] Disable debezium xlang against samza

sdks/python/tox.ini
Fixes: https://github.com/apache/beam/issues/26251 …
=> Download codecov uploader since codecov has been removed from pypi

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsModule.java, sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java, sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/options/AwsModuleTest.java
=> Support Assume-Role with web identity

sdks/python/apache_beam/io/gcp/bigquery.py
Fixes issue #22733 by deferring unique ID creation to later function.  …
=> Generating Unique ID within function so that it's unique for every run.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/QueryChangeStreamAction.java
=> Add more logging to QueryChangeStreamAction exceptions

playground/README.md, playground/backend/build.gradle.kts, playground/backend/cmd/remove_unused_snippets.go, playground/backend/internal/db/datastore/datastore_db.go
Add Gradle task to allow remove snippets form datastore by the snippet ID
resolves #26164 …
=> [Playground] Gradle task to remove snippet by its ID

website/www/site/content/en/documentation/ml/about-ml.md, website/www/site/content/en/documentation/sdks/python-machine-learning.md
The location of the underlying notebook has changed …
=> Fix broken links

runners/flink/src/test/java/org/apache/beam/runners/flink/batch/ReshuffleTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/CombineTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/FlattenTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoSchemaTest.java
Mitigate #26301
Now it should fails the stuck test instead of timing out after 4h and does not report test result.
* Mitigate test suite timeout for beam_PreCommit_Java_PVR_Flink_Batch
GitHub Actions …
=> Add timeout to a couple of validate runner tests

runners/samza/src/main/java/org/apache/beam/runners/samza/translation/ConfigBuilder.java, runners/samza/src/main/java/org/apache/beam/runners/samza/util/ConfigUtils.java, runners/samza/src/test/java/org/apache/beam/runners/samza/translation/ConfigGeneratorTest.java
Refactor the samza runner configs into a new function with consideration of autosizing configs. Also add unit test for it. …
=> Clean up bundle config generation for Samza Runner

sdks/python/apache_beam/io/gcp/bigquery.py
Reverts apache/beam#26270
Details in [comment](https://github.com/apache/beam/pull/26270#discussion_r1171221658).
=> Revert #26270

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/PrecombineGroupingTable.java
Prevent hashmap growing too large. Improves performance for too many Unique Keys cases.
Flush all key-values if map size reach to 12K entries + keep using LRU cache
* Micro BenchMark Result: 5x to 6x improvement for uniqueKeys PrecombineGroupingTableBenchmark, Minor impact on other
* End To End WordCount Pipeline: Approx 25% improvement
Before
```
Benchmark                                                 (distribution)  (globallyWindowed)   Mode  Cnt   Score   Error  Units
PrecombineGroupingTableBenchmark.sumIntegerBinaryCombine         uniform                true  thrpt   15  52.584 ± 5.631  ops/s
PrecombineGroupingTableBenchmark.sumIntegerBinaryCombine         uniform               false  thrpt   15  48.427 ± 4.090  ops/s
PrecombineGroupingTableBenchmark.sumIntegerBinaryCombine …
```
=> Prevent hashmap growing too large. Improves performance for too many Unique Keys cases.

CHANGES.md, sdks/go/pkg/beam/io/textio/textio.go, sdks/go/pkg/beam/io/textio/textio_test.go
Fixes #25812 and adds a `textio.ReadWithFilename` transform …
=> [Go SDK]: Create textio.ReadWithFilename transform

.test-infra/jenkins/job_LoadTests_ParDo_Python.groovy
Addresses timeout portion of https://github.com/apache/beam/issues/26345
=> Increase the timeout in one of the loadtest suites.

sdks/python/apache_beam/examples/inference/tensorflow_imagenet_segmentation.py, sdks/python/apache_beam/ml/inference/tensorflow_tests_requirements.txt
Applies the same changes we applied to the notebook. Interestingly, this also fixed a pickling issue I was facing (not really sure why, might have to do with the private fields not getting pickled correctly) …
=> Clean up tensorflow example

sdks/go/pkg/beam/io/filesystem/filesystem.go, sdks/go/pkg/beam/io/filesystem/gcs/gcs.go, sdks/go/pkg/beam/io/filesystem/gcs/gcs_test.go, sdks/go/pkg/beam/io/filesystem/local/local.go, sdks/go/pkg/beam/io/filesystem/local/local_test.go, sdks/go/pkg/beam/io/filesystem/memfs/memory.go, sdks/go/pkg/beam/io/filesystem/memfs/memory_test.go, sdks/go/pkg/beam/io/filesystem/s3/s3.go, sdks/go/pkg/beam/io/filesystem/s3/s3_test.go
Introduces a new filesystem interface for retrieving a file's last modified time and implements the method in the existing filesystems. Fixes #26187. …
=> [Go SDK]: Implement LastModified method in filesystems

runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/ExternalTranslationTest.java
Use containsInAnyOrder instead of equalTo to compare collections in `ExternalTranslationTest`.
This test is currently flaky because it relies on the iteration order of the collections being tested. …
=> Use containsInAnyOrder instead of equalTo to compare collections in ExternalTranslationTest

website/www/site/content/en/documentation/io/built-in/google-bigquery.md
=> update the BQ limitations

sdks/python/apache_beam/io/textio.py, sdks/python/apache_beam/runners/render.py, sdks/python/apache_beam/yaml/README.md, sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py
Add a basic readme to the yaml directory. …
=> Yaml pipeline readme.

release/src/main/scripts/build_release_candidate.sh
This isn't strictly necessary, but it is used in filtering and its confusing when its not outputted …
=> Add release number to python wheels script

website/www/site/content/en/documentation/sdks/python-pipeline-dependencies.md
=> Adding info on picklers to docs [follow-on]

sdks/python/setup.py
=> Fix lint errors from #26170

sdks/python/apache_beam/examples/inference/tensorflow_imagenet_segmentation.py
This got flagged in https://ci-beam.apache.org/job/beam_PreCommit_PythonFormatter_Commit/15717/console - not sure why the original PR didn't catch it …
=> Fix formatting violation

sdks/python/apache_beam/utils/multi_process_shared.py, sdks/python/apache_beam/utils/multi_process_shared_test.py
This will allow things like models that are invoked via `model(args*)` to work.
Fixes #26169 …
=> Allow multi_process_shared objects to be called

CHANGES.md, sdks/python/apache_beam/examples/inference/README.md, sdks/python/apache_beam/examples/inference/pytorch_image_classification.py, sdks/python/apache_beam/examples/inference/tensorflow_imagenet_segmentation.py, sdks/python/apache_beam/ml/inference/base.py, sdks/python/apache_beam/ml/inference/base_test.py
Adds the ability to add built in pre/post processing map functions as part of your RunInference call.
fixes #26308 …
=> Add support for pre/post processing in RunInference

runners/google-cloud-dataflow-java/build.gradle
and disable it on Dataflow V1 VR, fixes #25675
[![Build …
=> Enable testWithShardedKeyInGlobalWindow on Dataflow V2 VR

sdks/python/container/build.gradle
Looks like this got accidentally excluded in https://github.com/apache/beam/commit/8be511cc0730bfd78866c42b9d20e8189c706578
We can just manually run the dockerpush step, so this doesn't need cherry picked (unless we get to rc2 in which case I'll do it)
GitHub …
=> Push containers for python 3.10 and 3.11

examples/notebooks/beam-ml/automatic_model_refresh.ipynb
There were some indent/parentheses issues, this fixes those …
=> Fix syntax issues with notebook

sdks/java/core/src/main/java/org/apache/beam/sdk/io/Read.java
This eliminates outright nullness and rawtype errors where possible, and localizes some cases that are reasonable compromises or hacks that I don't want to mess with.
One small step towards #20507 …
=> Eliminate nullness and rawtype errors from java SDK Read class

sdks/java/extensions/sql/hcatalog/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/hcatalog/HCatalogTableProvider.java
Seems there weren't any to begin with
Fixes #20500 …
=> Eliminate nullness errors from sdks/java/extensions/sql/hcatalog

sdks/python/setup.py
Lower the lower bound of protobuf. Requested by TFX …
=> Lower the lower bound of protobuf.

sdks/python/apache_beam/transforms/combiners.py
Fixes documentation in #19819. 
TODO: A follow up PR that removes the compare argument from functions. 
[![Build …
=> Updating Combiners.Top PTransform Documentation

sdks/python/tox.ini
To capture regressions early, we will use the pre-released dependencies for unit tests(precommits). More discussion at https://lists.apache.org/thread/owcm7x208wlpgohgn60z5fzdc3vclw0f
Instead of creating new test suites, we will use the current precommits to use pre-released dependencies.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/. …
=> Run unit tests with pre-released dependencies.

sdks/go/pkg/beam/core/sdf/sdf.go
An old warning still lived on the sdf package documentation giving a bad impression to users. …
=> Remove out of date experimental warning on SDFs

sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformConfiguration.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryDirectReadSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerWriteSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangestreamsReadSchemaTransformProvider.java
Add field annotations for BigQuery Storage Read, File Write, Spanner Changestreams Read, and Spanner Write schema transforms. This is necessary for tying a description to each field, so that when a schema transform config is generated, each field would have a description of what it is supposed to do
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/bl …
=> Add field annotations for high-priority Syndeo schema transforms

sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
=> Revert "Modify batch IT to use count instead of hash"

release/src/main/scripts/mass_comment.py
This checks to make sure mass_comment.py has started the jobs it thinks it has. If jobs aren't started successfully, it keeps trying to start them.
Verified on this pr - https://github.com/apache/beam/pull/26455
A follow up to this will be automating updating the Jenkins triggers. This will eventually need to be extended to GitHub Actions as well once we have comment triggers there. …
=> keep retrying mass_comment until it has started all jobs

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java, sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java, sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcUtil.java, sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/SchemaUtil.java, sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcUtilTest.java, sdks/python/apache_beam/io/jdbc.py
Add driverJars parameter to JdbcIO.  …
=> Add driverJars parameter to JdbcIO.

sdks/python/apache_beam/yaml/README.md, sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_test.py
=> Add flexible windowing syntax to yaml.

sdks/java/io/mongodb/src/main/java/org/apache/beam/sdk/io/mongodb/MongoDbIO.java, sdks/java/io/mongodb/src/test/java/org/apache/beam/sdk/io/mongodb/MongoDbIOTest.java
Previously, there were some cases where users could succeed at reading a view/query but others that would fail because they asked for the estimated size. Now it just returns `0` for unknown when size cannot be estimated.
Also inline some extraneous abstraction to make tests read more straight-line, etc. …
=> Survive errors in size estimation in MongoDbIO

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java, sdks/python/apache_beam/io/jdbc.py
=> Fix jdbc xlang schema type mismatch

sdks/python/setup.py
Lower the lower bound of protobuf to 3.20.3.
cherrypick: #26446 …
=> [release-2.47.0]Lower the lower bound of protobuf. #26446

sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
=> Revert "Revert "Modify batch IT to use count instead of hash""

playground/backend/internal/code_processing/code_processing.go, playground/backend/internal/code_processing/code_processing_test.go
Playground can crash if a cache access to check if a cancellation was requested coincides with execution timeout.
addresses #25077 …
=> [Playground] Fix crash when example pipeline execution timed out

learning/katas/python/Core Transforms/Combine/Combine PerKey/task.py, playground/backend/internal/db/mapper/precompiled_object_mapper.go, playground/backend/internal/db/mapper/precompiled_object_mapper_test.go, playground/infrastructure/conftest.py, playground/infrastructure/datastore_client.py, playground/infrastructure/helper.py, playground/infrastructure/models.py, playground/infrastructure/test_helper.py
- Make fields categories and context_line optional in examples tag
- Resolve bug with incorrectly calculated context line after tag is removed from an example
- Resolve bug with an incorrectly reported context line for an example in catalog
resolves #26256 …
=> [Playground] Make fields "categories" and "context_line" optional in examples tags

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteReadSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/PubsubLiteDlqTest.java
I have added dlq support in the Pubsub Read schema transform by tagging with an appropriate TupleTag. I have also added a Counter to keep track of the number of failed elements in a bundle. …
=> Added dlq and error metrics to pubsublite read schema transform

sdks/python/apache_beam/examples/streaming_wordcount_it_test.py, sdks/python/apache_beam/runners/dataflow/dataflow_exercise_streaming_metrics_pipeline_test.py
* Bump streaming WC test timeout
* Bump metrics test timeout
Should result in integration tests being more reliable.  …
=> Cherrypick bump streaming test timeouts into 2.47.0 release branch

model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto
=> Add custom_data field to LogEntry

sdks/go/examples/native_wordcap/nativepubsubio/native.go, sdks/go/examples/wasm/wasm.go, sdks/go/pkg/beam/core/graph/window/trigger/trigger.go, sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download.go, sdks/go/pkg/beam/io/fhirio/common.go, sdks/go/pkg/beam/io/fhirio/deidentify.go, sdks/go/pkg/beam/io/fhirio/execute_bundles.go, sdks/go/pkg/beam/io/fhirio/import.go, sdks/go/pkg/beam/io/fhirio/read.go, sdks/go/pkg/beam/io/fhirio/search.go, sdks/go/pkg/beam/pardo.go, sdks/go/pkg/beam/transforms/sql/sql.go, sdks/go/pkg/beam/windowing.go
Per the dev list discussion: https://lists.apache.org/thread/lkbvb6rorrgz8h33w6q35q7ncbz7yp6z
This PR removes leftover experimental designations that no longer apply. …
=> [Go SDK] Remove experimental designation from places in the Go SDK.

learning/tour-of-beam/frontend/lib/pages/tour/widgets/markdown/code_builder.dart, learning/tour-of-beam/frontend/lib/pages/tour/widgets/markdown/tob_markdown.dart, learning/tour-of-beam/frontend/pubspec.lock, learning/tour-of-beam/frontend/pubspec.yaml, playground/frontend/playground_components/assets/translations/en.yaml, playground/frontend/playground_components/lib/src/cache/example_cache.dart, playground/frontend/playground_components/lib/src/controllers/playground_controller.dart, playground/frontend/playground_components/lib/src/theme/theme.dart, playground/frontend/playground_components/pubspec.yaml, playground/frontend/pubspec.lock
=> [Tour of Beam] [Frontend] Markdown selection fix

sdks/python/apache_beam/transforms/core.py, sdks/python/apache_beam/transforms/ptransform_test.py
=> Add timeout parameter to with_exception_handling.

release/src/main/scripts/build_release_candidate.sh, release/src/main/scripts/run_rc_validation.sh
This does 2 things:
1) Prompts for confirmation before running the java artifact validation (this should save time)
2) Undoes the changes from https://github.com/apache/beam/commit/bc4ee851b5cb49a8c88754a22e75b0d45c16557e which caused artifacts to be staged to dist.apache.org with an `_rcX` appended to them …
=> Small release fixes

playground/backend/internal/cache/local/local_cache.go, playground/backend/internal/code_processing/code_processing.go, playground/backend/internal/db/datastore/emulator_wrapper.go, playground/backend/internal/emulators/kafka.go
Tickers can leak resources unless stopped. Consistently defer ticker.Stop so this leak doesn't occur. See https://pkg.go.dev/time#NewTicker …
=> [Playground] defer Stop tickers to avoid leaks.

learning/tour-of-beam/frontend/lib/components/scaffold.dart, learning/tour-of-beam/frontend/lib/pages/welcome/screen.dart
Module complexity on the welcome screen and navigation to homepage on logo click.  …
=> [Tour of Beam] [Frontend] Module complexity on the welcome screen

sdks/python/apache_beam/ml/inference/base.py
Fixes: https://github.com/apache/beam/issues/26500 …
=> Add watch_pattern keyword arg to RunInference

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
Cherry-picking https://github.com/apache/beam/pull/26503 to release 2.47.0.
=> Cherry-pick #26503: fix dataloss bug in batch Storage API sink.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteOptions.java
Enable batch write flow control in BigtableIO.
When flow control is enabled, traffic to Bigtable is automatically rate-limited to prevent overloading Bigtable clusters while keeping enough load to trigger Bigtable Autoscaling (if enabled) to provision more nodes as needed.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD …
=> Bigtable: enable batch write flow control

examples/notebooks/get-started/learn_beam_windowing_by_doing.ipynb
Add one end-to-end example about how to use Beam windowing for AQI analysis
Colab link: https://colab.research.google.com/github/liferoad/beam/blob/windowing/examples/notebooks/get-started/learn_beam_windowing_by_doing.ipynb …
=> add one windowing example

examples/notebooks/get-started/learn_beam_transforms_by_doing.ipynb
Add the notebook to show how to learn Beam transforms.
Plan to add the colab link to https://beam.apache.org/documentation/programming-guide/#transforms
Colab link: https://colab.research.google.com/github/liferoad/beam/blob/learn-transforms/examples/notebooks/get-started/learn_beam_transforms_by_doing.ipynb
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apach …
=> Add the example to learn transforms

sdks/java/extensions/ml/src/test/java/org/apache/beam/sdk/extensions/ml/DLPTextOperationsIT.java
=> Fix DLPTextOperationsIT.inspectsText

sdks/java/extensions/ml/build.gradle, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateImages.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoBytesWithContextFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoFromBytesFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoFromURIFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoURIWithContextFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/DLPDeidentifyText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/DLPInspectText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/DLPReidentifyText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/MapStringToDlpRow.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAICreateCatalogItem.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIImportCatalogItems.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIImportUserEvents.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIPredict.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIWriteUserEvent.java
=> Eliminate nullness errors from sdks/java/extensions/ml

website/Dockerfile
This is an attempt to fix the website precommit which is currently permared - https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/
stretch-slim seems to sit on an older deprecated version of debian and the package lookups aren't working anymore. We could try to workaround this, but upgrading to a newer/maintained image is probably better …
=> Fix website dependency issue

release/src/main/scripts/run_rc_validation.sh
Fix flipped boolean operator based on response ('y' was skipping the artifact validation) and adds a brief sleep between curl invocations to avoid being rate limited by Nexus. …
=> [release] Improve Java Artifact Validation Logic

sdks/go/pkg/beam/core/runtime/harness/sampler.go
Tiny change to allow for quicker exits of sampler goroutine. Sleep can't be pre-empted, but the ticker channel can. This allows test runs with prism to have cleaner goroutine dumps. …
=> [Go SDK] Switch sampler to use ticker instead of sleep.

website/www/site/content/en/documentation/programming-guide.md
Addresses #26511 temporarily.
TODO: Embed colab tutorial on the webpage itself. …
=> Adding links to PTransform Colab Notebook.

website/www/site/content/en/contribute/release-guide.md
Adds an explicit callout to not merge the website update PR and cleans up the example docker pulls to match how we actually format tags (no underscore before the `rcX` suffix.) …
=> Clean up small release guide nits and typos

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteWriteSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/PubsubLiteDlqTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/PubsubLiteWriteDlqTest.java
Added error metrics and dlq routing support for pubsub lite write schema transform. Tested the DoFn functionality with unit test. …
=> Add Pubsub lite write metrics and DLQ support

learning/tour-of-beam/terraform/build.gradle.kts
Follow up for #26544
Resolves ToB deployment tasks failing to import on first time project import in Idea.
resolves #26601 …
=> [Tour of Beam]Use default value for pg_router_host if it's not specified

sdks/python/apache_beam/testing/analyzers/github_issues_utils.py
Fixes: https://github.com/apache/beam/issues/26501 …
=> Fix json int64 serialization for perf alert commenting

sdks/java/extensions/ml/build.gradle, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateImages.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoBytesWithContextFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoFromBytesFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoFromURIFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateVideoURIWithContextFn.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/DLPDeidentifyText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/DLPInspectText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/DLPReidentifyText.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/MapStringToDlpRow.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAICreateCatalogItem.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIImportCatalogItems.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIImportUserEvents.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIPredict.java, sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/RecommendationAIWriteUserEvent.java
This reverts commit 9ec4cec5986197529f6fb31e5fe95ae041924dc2
Failure at https://ci-beam.apache.org/job/beam_PostCommit_Java/lastBuild/testReport/org.apache.beam.sdk.extensions.ml/RecommendationAIUserEventIT/createUserEvent/
It was also merged hastily, mistakenly thinking it had been reviewed, but it had not.
Fixes #26614 …
=> Revert "Eliminate nullness errors from sdks/java/extensions/ml"

CHANGES.md, website/www/site/config.toml, website/www/site/content/en/blog/beam-2.47.0.md, website/www/site/content/en/get-started/downloads.md, website/www/site/data/authors.yml
Updates the website with the release listing and blog post
DO NOT SUBMIT until an 2.47.0 RC candidate is approved and the remaining fields are updated.  …
=> Beam 2.47.0 Release Website Updates

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ActionFactory.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamAction.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsAction.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/GenerateInitialPartitionsAction.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionAction.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/package-info.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/BigtableChangeStreamAccessor.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/ChangeStreamDao.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/package-info.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/DetectNewPartitionsDoFn.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/package-info.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/model/PartitionRecord.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/model/package-info.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/package-info.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/restriction/package-info.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ChangeStreamActionTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/DetectNewPartitionsActionTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/GenerateInitialPartitionsActionTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/action/ReadChangeStreamPartitionActionTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/MetadataTableDaoTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/ReadChangeStreamPartitionDoFnTest.java
Add end time parameter to finish stream after reading up to the given time. This is not reliable right now so we don't expose it to users yet.
Additionally update client configuration, add a couple unit tests and do some minor clean up.  …
=> Add ReadChangeStream end time logic, minor cleanup

sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoCoder.java
After offline chat, updating the description:
This is to remove the benign race so that concurrency analyzers are happy. …
=> Add synchronized to getExtensionRegistry() lazy initialization

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java
Add an experiments flag `enable_client_side_metrics` to enable client side metricshttps://cloud.google.com/bigtable/docs/client-side-metrics …
=> Bigtable: add an experiments flag to enable client side metrics

sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformProvider.java
Minor fixup to the FileWriteTransformProvider. The current output has not coder/schema set. …
=> Fix FileWriteSchemaTransformProvider

sdks/python/apache_beam/ml/inference/tensorflow_inference.py, sdks/python/apache_beam/ml/inference/tensorflow_inference_test.py
This matches the convention followed by other ModelHandlers.
Also:
1) adds 2 unit tests that run a full pipeline w/ the direct runner
2) refactors a couple tests that were using mocks into their own class because the mocks were interfering with other tests (the ones I added).
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BU …
=> Add max/min batch size to tf model handlers

.github/autolabeler.yml
=> Configure spanner label

website/www/site/content/en/contribute/release-guide.md
This does a few things around rc validation:
- Added details to rc email encouraging non-pmc to vote + explaining process
- Add some context on validation for release manager
- Add required permissions for script …
=> Enrich docs around rc validations

sdks/go/pkg/beam/runners/universal/runnerlib/compile.go, sdks/go/run_with_go_version.sh, website/www/site/content/en/documentation/sdks/go-cross-compilation.md
Avoid glibc mismatches for container bootloaders and other beam infra Go SDK builds.
Update the default cross compile for same. 
Update the cross compilation documents for same. …
=> [#26576] Set CGO_ENABLED=0 for go builds.

learning/tour-of-beam/frontend/assets/translations/en.yaml, learning/tour-of-beam/frontend/integration_test/tour_page_test.dart, learning/tour-of-beam/frontend/integration_test/welcome_page_test.dart, learning/tour-of-beam/frontend/lib/components/scaffold.dart, learning/tour-of-beam/frontend/lib/models/content_tree.dart, learning/tour-of-beam/frontend/lib/models/node.dart, learning/tour-of-beam/frontend/lib/models/parent_node.dart, learning/tour-of-beam/frontend/lib/models/unit.dart, learning/tour-of-beam/frontend/lib/pages/tour/controllers/content_tree.dart, learning/tour-of-beam/frontend/lib/pages/tour/page.dart, learning/tour-of-beam/frontend/lib/pages/tour/path.dart, learning/tour-of-beam/frontend/lib/pages/tour/state.dart, learning/tour-of-beam/frontend/lib/pages/tour/widgets/complete_unit_button.dart, learning/tour-of-beam/frontend/lib/pages/tour/widgets/content_tree.dart, learning/tour-of-beam/frontend/lib/pages/tour/widgets/unit_content.dart, learning/tour-of-beam/frontend/lib/pages/welcome/screen.dart, playground/frontend/playground_components/pubspec.yaml
Previous, Next unit navigation. …
=> [Tour of Beam] [Frontend] Unit navigation 

settings.gradle.kts
This PR publishes a build scan for every CI build on Jenkins and GitHub Actions and for every local build from an authenticated Apache committer. The build will not fail if publishing fails.
The build scans of the Apache Beam project are published to the Gradle Enterprise instance at https://ge.apache.org/, hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Gradle Enterprise instance has all features and extensions enabled and is freely available for use by the Apache Beam project and all other Apache projects.
Currently, the Apache Beam build is configured to publish build scans to the publicly available https://scans.gradle.com/. This pull request enhances that functionality by instead publishing build scans to https://ge.apache.org/. On …
=> Capture build scans on ge.apache.org to benefit from deep build insights

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProto.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProtoTest.java
Fixes #26408
Actually protobuf lib's ByteString.copyFrom has overloads of both byte[] and ByteBuffer (as well as String), but the utility class in Beam SDK only assumes the former.
GitHub Actions …
=> Support ByteBuffer and String objects in BeamRowToStorageApiProto

playground/infrastructure/ci_cd.py, playground/infrastructure/config.py, playground/infrastructure/datastore_client.py, playground/infrastructure/test_datastore_client.py
Add support for `PG_BEAMDOC` origin for examples intended for Playground embedded into documentation
resolves #26194 …
=> [Playground] Add support for PG_BEAMDOC origin

.github/REVIEWERS.yml
The proposal to add more IO reviewers for the bot. …
=> proposal for more reviewers

CHANGES.md, website/www/site/content/en/blog/beam-2.47.0.md
- Python SDK still supports protobuf 3.x (3.20.3) dependency
- minor cleanup …
=> Fix 2.47.0 release notes

release/src/main/Dockerfile
Adds a Dockerfile to the release code that constructs an environment capable of building Beam containers. This acts as a workaround in the event that a release manager's local environment provides a different version of Glibc than expected during the release process, as seen in 2.47.0 RC3's initial container rollout. 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github …
=> [Release] Add build container dockerfile to release code

sdks/python/apache_beam/ml/inference/base.py, sdks/python/apache_beam/ml/inference/base_test.py
Right now, we always load our models into each worker process. This may not be ideal (e.g. if the model is very large), so this introduces the ability to share a single model across all worker processes in a vm or container.
Right now, no model handlers utilize this capability, but this will be exposed in our first party model handlers in a future PR(s).
Part of #26687 …
=> Allow model handlers to request multi_process_shared model

sdks/go/pkg/beam/core/graph/fn.go, sdks/go/pkg/beam/core/runtime/exec/timers.go, sdks/go/pkg/beam/core/runtime/harness/harness.go
=> [Go SDK] Resolve go lints

sdks/python/apache_beam/transforms/deduplicate.py
Fixes task #26664
Currently, ValueError raised by `Deduplicate` PTrasform contains grammatical mistakes.
```
raise ValueError(
'Deduplicate requires at lease provide either'
'processing_time_duration or event_time_duration.')
```
Namely:
- `lease` -> `least`
- `provide` -> `providing`
- no space between `either` and `processing_time_duration`
Additionally, there is a typo in the docstring of the class. …
=> Improve ValueError message and docstring in Deduplicate

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java
=> Add BigTable batch size and latency metrics for writes

sdks/python/apache_beam/ml/inference/pytorch_inference.py, sdks/python/apache_beam/ml/inference/pytorch_inference_test.py
Added optional args to PyTorch model handler in case of custom config for saving/loading the model.
https://pytorch.org/docs/stable/generated/torch.load.html …
=> [Python] Added load model option args for PyTorch Model Handler

sdks/java/container/build.gradle
This resolves the issue of docker tasks failing on machines without wget installed, and curl is installed by default on Macs …
=> Update cloud profile download to use curl instead of wget

runners/portability/java/build.gradle, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ViewTest.java
=> Properly tag test so it is excluded on unsupported runners

playground/backend/internal/logger/logger_test.go, playground/backend/internal/logger/std_handler.go
Use stdout for INFO, WARN and DEBUG messages and stderr for the rest to improve logging analysis experience in GCP.
resolves #26734 …
=> [Playground] Split logging between stdout and stderr

playground/backend/containers/go/setup_sdk.sh
Add beam/io/bigquery dependency explicitly for Go examples as examples using bigquery fail to compile otherwise. …
=> [Playground] Add bigquery dependency to for Go examples template

sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py37/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
Updated protobuf version and generated all requirements for base image.
Part of #25590 …
=> [Python] Update protobuf version to 4.23

examples/notebooks/beam-ml/run_inference_windowing.ipynb
This is currently invalid - https://github.com/apache/beam/blob/master/examples/notebooks/beam-ml/run_inference_windowing.ipynb - this fixes the problem - https://github.com/apache/beam/blob/b07fa3b80d332c53bba3bde83dc8fd11b236a571/examples/notebooks/beam-ml/run_inference_windowing.ipynb …
=> Fix run_inference_windowing.ipynb json

.github/workflows/cut_release_branch.yml
Normally, I'd expect us to get this by default but we may be restricting it with apache org policies.
If this doesn't work, we may need to turn this workflow into one that creates a pr instead …
=> Update cut_release_branch.yml with write permissions

.github/workflows/cut_release_branch.yml
This is needed to create the snapshot job pr …
=> Update cut_release_branch.yml with pr creation permissions

sdks/python/apache_beam/runners/worker/sdk_worker_main.py
Issue: https://github.com/apache/beam/issues/26756
Make Python SDK Worker terminations log CRITICAL
Note that log.exception uses the ERROR level:
> exception(msg, *args, **kwargs)
> 
> Logs a message with level ERROR on this logger. The arguments are interpreted as for [debug()](https://docs.python.org/3/library/logging.html#logging.debug). Exception info is added to the logging message. This method should only be called from an exception handler. …
=> 26756-Python-SDK-Harness-Failure-Log-Critical

settings.gradle.kts
Before #26351, builds had the local build cache enabled for local development builds as well as CI builds. #26351 inadvertenly disabled the local build cache for CI builds. This re-enables it.
You can see in [this Gradle Enterprise graph](https://ge.apache.org/scans/trends?search.relativeStartTime=P90D&search.rootProjectNames=beam&search.tags=ci&search.timeZoneId=Europe/Berlin&trends.activeMetrics=%7B%22avoidanceSavings%22:%22localBuildCache%22%7D&trends.section=avoidanceSavings) that the local build cache was disabled for CI builds.
Fixes #26776 …
=> Enable local build caching for CI builds

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/go/run_with_go_version.sh
Go 1.20.2 contains vulnerabilities, update the version to the latest, 1.20.4. …
=> bump go version to 1.20.4

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ConvertHelpers.java
Follow-up to https://github.com/apache/beam/commit/68e19a596a5d0136ba4592be01888f487463c2f3. This fixes another similar issue with the latest JDK versions. …
=> Replace another use  of `ClassLoadingStrategy.Default.INJECTION`

website/www/site/layouts/index.html
=> Close the iframe tag (#26804)

website/www/site/content/en/blog/beam-2.47.0.md
Update the 2.47.0 release notes by adding the autoUpdateSchema bug as known issues
addresses #26789 …
=> Update the 2.47 release notes with the autoUpdateSchema issue

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableSchemaUpdateUtils.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableSchemaUpdateUtilsTest.java
=> #26789 Fix auto schema update when schema order has changed.

CHANGES.md, sdks/python/container/boot.go
=> Cherry-picks #26797 to the release branch.

CHANGES.md
=> Update CHANGES.md for new release version

website/www/site/content/en/documentation/sdks/go-cross-compilation.md
fix container environment links in cross-compilation page …
=> fix container environment links in cross-compilation page

website/www/site/content/en/contribute/release-guide.md
Accidentally linked to my fork instead of the main repo 😳  …
=> Fix broken link

sdks/python/setup.py
=> [Minor] Remove notebook utils from interactive_test

website/www/site/content/en/get-started/quickstart/go.md
The GO quickstart has this flag incorrectly shown as *--inputText="Greetings"* but in the source for the example the corresponding flag is actually *--input-text* …
=> Typo -- fixed incorrect command flag

examples/notebooks/beam-ml/run_inference_xgboost.ipynb
=> install beam from a released version instead of head

.github/workflows/build_release_candidate.yml
This adds a workflow for staging java artifacts to dist.apache.org. I didn't remove it from the script or add it to the release instructions since I haven't been able to fully validate it; I validated that everything up to committing works, but I didn't want to mess with the current release process.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/bl …
=> Add workflow for staging java artifacts

playground/frontend/lib/pages/embedded_playground/widgets/embedded_actions.dart
fix button cropping
resolves #26837 …
=> issue26837 fix button cropping

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
#25232
- bump log4j2 to 2.19.0
- I'd liket update version to lates for log4j2 https://logging.apache.org/log4j/2.x/download.html …
=> #25232 bump log4j2 to 2.20.0

build.gradle.kts
These were recently added, but aren't getting auto-picked up …
=> Push transform service containers with rest of containers

build.gradle.kts
Cherry picks this change to the release branch in case we need more RCs …
=> Push transform service containers with rest of containers (#26869)

.test-infra/jenkins/job_LoadTests_Combine_Python.groovy, .test-infra/jenkins/job_LoadTests_GBK_Python.groovy, .test-infra/jenkins/job_LoadTests_ParDo_Python.groovy, .test-infra/jenkins/job_LoadTests_SideInput_Python.groovy, .test-infra/jenkins/job_PerformanceTests_BigQueryIO_Python.groovy, .test-infra/jenkins/job_PerformanceTests_FileBasedIO_Python.groovy, .test-infra/jenkins/job_PerformanceTests_PubsubIO_Python.groovy, .test-infra/jenkins/job_PerformanceTests_SpannerIO_Python.groovy, .test-infra/jenkins/job_PerformanceTests_xlang_KafkaIO_Python.groovy, sdks/python/apache_beam/testing/fast_test_utils.pxd, sdks/python/apache_beam/testing/fast_test_utils.pyx, sdks/python/apache_beam/testing/load_tests/load_test.py, sdks/python/apache_beam/testing/synthetic_pipeline.py, sdks/python/apache_beam/testing/test_utils.py, sdks/python/apache_beam/testing/test_utils_test.py, sdks/python/scripts/generate_pydoc.sh
=> Implement a fast (lcg) random generator for Python SyntheticSource

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaIOProvider.java
=> Fix failing BQ tests on XVR GoUsingJava tests

website/www/site/content/en/contribute/release-guide.md
The `--signing-key` flag is required when building an RC but is omitted from the example command. Adds it into the command and has the release manager set an environment variable with the public key as part of RC build prep. …
=> [release] Add signing key flag and env variable to release documentation

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/graph/PipelineValidator.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java, runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
=> Validate that a URN is set on all non-composite transforms.

release/src/main/scripts/mass_comment.py
=> Exclude sickbay test suite in mass comment

.github/workflows/cut_release_branch.yml
This will allow us to skip the release branch piece if its already been done. It also fixes a bug where the release branch was getting cut before the master branch was updated. This would only matter if the second part (pushing the release branch) failed, because then a future attempt could get started at a later commit which would contain the updated master version. …
=> Gate pushing release branch on input (default true)

playground/backend/configs/SDK_JAVA.json, playground/backend/internal/code_processing/code_processing_test.go, playground/backend/internal/setup_tools/builder/setup_builder.go, playground/backend/internal/setup_tools/builder/setup_builder_test.go
Use directory with source files as working directory for Go and Java runners to avoid confusion for multifile examples with files which contain data. Without this change the data files could be accessed only by prepending `./src/` prefix to their name. This change allow loading such files simply by referring to them by their name. …
=> [Tour of beam][Playground] Use source directory as working directory

website/www/site/content/en/documentation/io/connectors.md
SingleStore row didn't have Typescript row.
Added link to the connector guide. …
=> Fixed SingleStore row in the Built-in I/O Connectors table.

playground/backend/cmd/server/controller.go, playground/backend/internal/code_processing/code_processing.go, playground/backend/internal/errors/lifecycle_error.go
Log messages related to pipeline cancellation as warnings
resolves #26839 …
=> [Playground] Log cancellation messages as warnings

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java
=> Fix ClassCastException in toBeamValue with List<{Primitive}> types

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangestreamsReadSchemaTransformProvider.java
Adding `@AutoService(SchemaTransformProvider.class)` annotation to SpannerChangestreamsReadSchemaTransformProvider …
=> Add AutoService annotation to SpannerChangestreamsReadSchemaTransformProvider

sdks/python/container/piputil.go
=> Always install dev wheel if passed to sdk_version

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkExecutionEnvironments.java, runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkExecutionEnvironmentsTest.java, sdks/java/core/src/main/java/org/apache/beam/sdk/options/PipelineOptionsFactory.java, website/www/site/layouts/shortcodes/flink_java_pipeline_options.html, website/www/site/layouts/shortcodes/flink_python_pipeline_options.html
This PR adds functionality to publish the job's pipeline option values to Flink's web UI (issue #26822). This is quite useful for debugging purposes where users can inspect the runtime arguments passed to the beam job, for flink runner. …
=> Publish pipeline options to flink web ui

learning/tour-of-beam/learning-content/schema-based-transforms/schema-concept/logical-type/unit-info.yaml
=> remove taskName tag

sdks/python/apache_beam/yaml/main.py
Refactoring entry file for yaml module.
- `parser.add_argument()` takes 'help' as an argument.
- `yaml_transform.expand_pipeline()` takes 'pipeline_spec' as an argument, not `known_args.pipeline_spec` …
=> Fix and refactor main.py file for yaml

playground/backend/internal/preparers/java_preparers.go
Instead of replacing `pipeline.run()` string inside of the examples, insert the graph saving code right before it. …
=> [Playground] Make graph saving injection more robust

playground/infrastructure/helper.py, playground/infrastructure/test_helper.py, playground/infrastructure/test_verify.py, playground/infrastructure/verify.py
Fetch example execution results right after each example execution instead of waiting for all examples to finish execution
resolves #26930 …
=> [Playground] Resolve Playground examples CI/CD failures

.github/workflows/build_release_candidate.yml
These were updated in https://issues.apache.org/jira/browse/INFRA-24520. I validated that this works in https://github.com/apache/beam/actions/runs/5125449144
Fixes #26767 …
=> Use correct secrets when publishing to Nexus

playground/infrastructure/fetch_scala_examples.py, playground/infrastructure/requirements.txt
Add script to fetch SCIO examples …
=> [Playground] Add script to fetch SCIO examples

CHANGES.md, website/www/site/config.toml, website/www/site/content/en/blog/beam-2.48.0.md, website/www/site/content/en/get-started/downloads.md
=> update website for release-2.48.0 and blog post

.github/gh-actions-self-hosted-runners/arc/README.md, .github/gh-actions-self-hosted-runners/arc/config/arc_deployment.tpl, .github/gh-actions-self-hosted-runners/arc/environments/beam.env, .github/gh-actions-self-hosted-runners/arc/kubernetes.tf
- Changes runner type to organizational which uses `beam` group
- Updated docs
- Added environments folder where variable sets are kept …
=> ARC Terraform updates

.github/workflows/beam_PreCommit_Go.yml, .github/workflows/beam_PreCommit_Go_Commit.yml
PR migrates Jenkins Job "https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_Go_Commit/" to Github Actions Workflow ".github/workflows/beam_PreCommit_Go.yml".
The workflow is triggered by pull requests to the master branch at the specified paths ['model/', 'sdks/go*', 'release/'].
It consists of 3 steps: git checkout, environment preparation (java, go, gradle installation), script execution.
The code has been tested on GitHub Provided Runners, Self-hosted GKE runners ubuntu 20.04.
The tests was made by creating pull requests with changes in trigger paths.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how …
=> Added Github Workflow Replacement for Jenkins Job, beam_PreCommit_Go

.test-infra/jenkins/CommonJobProperties.groovy
=> Revert "populate jobs with gradle scans access"

website/www/site/data/authors.yml
=> adding myself to author list for blog

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java
This includes @ahmedabu98 's unit test to validate the fix.
R: @johnjcasey 
R: @ahmedabu98
=> Refix offset error: add back line that was deleted during a merge

sdks/python/apache_beam/transforms/environments.py
This log "Default Python SDK image for environment..." is too verbose and is not useful at all. Remove it. …
=> Remove this log "Default Python SDK image for environment..."

sdks/java/transform-service/launcher/build.gradle
Fixes https://github.com/apache/beam/issues/26985 …
=> Removing an unnecessary dependency

sdks/python/apache_beam/runners/dataflow/internal/names.py
Updated tags with newly built legacy container …
=> [Python] update tags after including guppy in dataflow legacy container

website/www/site/content/en/blog/beam-2.47.0.md, website/www/site/content/en/blog/beam-2.48.0.md
Fix download links in blog 2.47, 2.48 …
=> fix blog links

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangestreamsReadSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangestreamsReadDlqTest.java
I have added dlq support in the Spanner Changestream read schema transform by tagging with an appropriate TupleTag. I have also added a Counter to keep track of the number of failed elements in a bundle. …
=> Added dlq and error metrics to SpannerChangestreamsReadSchemaTransformProvider

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiFinalizeWritesDoFn.java
=> Add metric counting finalized rows as reported by BQ

website/www/site/layouts/index.html
Fixes https://github.com/apache/beam/issues/26998.
=> Do not skip latest blog entry from footer

sdks/python/apache_beam/yaml/pipeline.schema.yaml, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/setup.py
=> Add yaml validation using jsonschema.

playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/locals.tf, playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/triggers.tf, playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/variables.tf, playground/terraform/infrastructure/gke/main.tf, playground/terraform/infrastructure/gke/variables.tf, playground/terraform/infrastructure/main.tf, playground/terraform/infrastructure/variables.tf
Decouple min_count from initial pool count. Initial pool gets deleted anyways and this will cause re-deployments when changing node count …
=> added initial node count variable

examples/java/src/main/java/org/apache/beam/examples/cookbook/MinimalBigQueryTornadoes.java, examples/java/src/test/java/org/apache/beam/examples/cookbook/MinimalBigQueryTornadoesTest.java, playground/terraform/infrastructure/setup/iam.tf
- Add new example for Playground to demonstrate BigQuery usage
- Add BigQuery Read Session User role to allow BigQuery read access …
=> Add minimal example for BigQuery usage

sdks/go/pkg/beam/core/timers/timers.go
=> [Go SDK] Lint fixes: receiver consistency.

sdks/go/pkg/beam/runners/prism/internal/jobservices/management_test.go
Avoids an accidental copy of a mutex by value by passing a reference to a proto to cmp.Diff instead of a value.  …
=> [prism] Pass reference instead of value to cmp.Diff

sdks/python/apache_beam/io/components/__init__.py, sdks/python/apache_beam/io/components/adaptive_throttler.py, sdks/python/apache_beam/io/components/adaptive_throttler_test.py, sdks/python/apache_beam/io/components/util.py, sdks/python/apache_beam/io/gcp/datastore/v1new/datastoreio.py
Moves the AdaptiveThrottler implementation previously in the datastore module out to a new `io.components` module, as the implementation is pretty general and can be used elsewhere. …
=> Move AdaptiveThrottler impl to new Components directory

sdks/python/apache_beam/examples/snippets/snippets_examples_wordcount_debugging.py, sdks/python/apache_beam/examples/snippets/snippets_examples_wordcount_wordcount.py, sdks/python/apache_beam/examples/snippets/transforms/aggregation/count_per_element.py, sdks/python/apache_beam/examples/snippets/transforms/aggregation/distinct.py, sdks/python/apache_beam/examples/snippets/transforms/aggregation/groupby_global_aggregate.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/keys.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/kvswap.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_function.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_lambda.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_multiple_arguments.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_side_inputs_dict.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_side_inputs_iter.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_side_inputs_singleton.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_simple.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/map_tuple.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/tostring_kvs.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/values.py
Several of the new examples for Playground were not runnable by the Playground as they were missing the invocation of the example function itself, however they were executed fine in tests. …
=> [Playground] Make new python examples runnable

website/www/site/content/en/get-started/resources/learning-resources.md
Fixes #26867 by identifying a permanent place in the docs. …
=> Add Certification + Beam Quest to Documentation

website/www/site/content/en/blog/beam-2.48.0.md
=> Add note for changed release tag for 2.48.0

website/www/site/content/en/blog/beamquest.md
1) Added a quote (thanks @shunping-google !)
2) Added a PS section on how to share the badge once earned.
[![Build …
=> Quote Addition + Sharing instructions [Beam Quest Blog]

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/container/license_scripts/dep_urls_java.yaml
Update google_cloud_platform_libraries_bom to 26.16.0. Associated updates to google_cloud_spanner_version, gax_version, and grpc_version. …
=> Update to Google Cloud libraries-bom 26.16.0

.github/workflows/beam_PreCommit_Go.yml
https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_Go_Cron/
https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_Go_Commit/
https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_Go_Phrase/
All three Jenkins jobs were combined in one workflow `.github/workflows/beam_PreCommit_Go.yml`:
1. Added a push trigger, as requested in a similar PR "https://github.com/apache/beam/pull/26968#discussion_r1213572366";
2. Added "issue_comment" trigger, which allows you to start a workflow from a comment in a PR; 
3. Added scheduled cron trigger that will run every 6 hours (in jenkins cron job it ran "H H/6 * * *");
4. line 17 condition OR, required for checking the triggers: for PR, comment in PR 'Run Go PreCommit', cron
The code has been tested on GitHub Provided Runners …
=> Github Workflow Replacement for Jenkins Job, beam_PreCommit_Go (Cron, Commit, Phrase)

playground/frontend/playground_components/lib/src/controllers/code_runner.dart
=> Preserve output when a pipeline dies on timeout (#26928)

playground/terraform/infrastructure/setup/iam.tf
Playground:
- New role "roles/bigquery.jobUser" was applied for Service Account …
=> [Playground] - New role add

website/www/site/content/en/contribute/release-guide.md
Instruction for Release Manager to update Playground environment
=> Release Guide update for Playground environment

website/www/site/content/en/get-started/resources/learning-resources.md, website/www/site/layouts/partials/section-menu/en/get-started.html
Update learning-resources.md with links to video material …
=> Update learning-resources.md with links to video material

playground/frontend/playground_components/lib/src/controllers/snippet_editing_controller.dart, playground/frontend/playground_components/lib/src/widgets/output/result_tab_content.dart, playground/frontend/playground_components/lib/src/widgets/tabbed_snippet_editor.dart
=> Cut the Playground output if it is too long (#27083)

sdks/python/tox.ini
Fixes the :sdks:python:test-suites:direct:py<version>:hdfsIntegrationTest failing due to tox upgrade …
=> Add required commands to allowlist_externals in tox.ini

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangestreamsReadSchemaTransformProvider.java
BigQuery Write Transform already has necessary logic for capturing errors and tagging them. The necessary error metrics are also being generated. The tags used however are not consistent with the rest of the transforms. Adding the correct error tag will enable the error records to be picked up by the dlq. 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/ …
=> Adding error tags in BigQuery Write Transforms

examples/notebooks/beam-ml/run_inference_generative_AI.ipynb, examples/notebooks/beam-ml/run_inference_streaming_pipeline.ipynb
Adds a notebook with PubSubIO for RunInference using most of the code from: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9926
Thanks @davidcavazos  …
=> Add notebook for run inference with streaming pipeline example

playground/frontend/CONTRIBUTE.md, playground/frontend/README.md, playground/frontend/lib/modules/examples/models/example_loading_descriptors/examples_loading_descriptor_factory.dart, playground/frontend/playground_components/lib/src/models/example.dart
This PR fixed the recently introduced bug of not showing the graph for examples loaded with a direct link (this includes all embeddings).
It also cleans up an old CONTBUTE.md that was not updated since the phase 1 of Playground. …
=> Fix graph, update the Playground frontend README

runners/samza/OWNERS
Add OWNER file and reviewer list for Samza Runner. …
=> Add OWNERS file for Samza Runner

sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/logging/BeamFnLoggingClientBenchmark.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/QuotaEvent.java
Allows logging quota issues as in a structured form.
Based on structured logging code added in: #26460
[![Build …
=> Initial implementation of QuotaEvent

sdks/java/io/google-cloud-platform/build.gradle, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
This PR extends certain quota-related log entries with QuotaEvent data. …
=> QuotaEvents for BigQuery

.github/workflows/beam_PreCommit_Website.yml
Similar workflow migration PR as reference: https://github.com/apache/beam/pull/27042
PR migrates Jenkins Jobs to Github Actions Workflow ".github/workflows/beam_PreCommit_Website.yml":
1. https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_Website_Commit/
2. https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_Website_Cron/
3. https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_Website_Phrase/
The tests was made by creating pull requests with changes in trigger path 'website/**', by adding a comment to the PR, by creating a push. …
=> Github Workflow Replacement for Jenkins Job, beam_PreCommit_Website (Cron, Commit, Phrase)

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/debug/ElementSample.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/debug/OutputSampler.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/debug/OutputSamplerTest.java
Implements sampling of elements during exceptions. The proto changes are not in yet, so the metadata will be filled in a follow-up PR.
addresses #26704 …
=> Implement Java exception sampling

sdks/python/apache_beam/typehints/schemas.py, sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_mapping.md, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_mapping_test.py, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py
Examples can be found in the doc. …
=> Implement basic mapping capabilities for YAML.

sdks/python/apache_beam/yaml/readme_test.py
=> Pylint repression same line

sdks/python/apache_beam/io/azure/integration_test/docker-compose.yml, sdks/python/test-suites/direct/common.gradle, sdks/python/tox.ini
=> Fix Python37 PostCommit azure-cli not support Bookworm

sdks/python/apache_beam/examples/inference/sklearn_examples_requirements.txt, sdks/python/apache_beam/ml/inference/sklearn_inference_it_test.py
=> Fix sklearn requirement file in Py311

website/www/site/content/en/documentation/runners/flink.md
=> #27115 Add supported Flink versions to website

sdks/java/io/components/build.gradle, sdks/java/io/components/src/main/java/org/apache/beam/sdk/io/components/deadletterqueue/DLQRouter.java, sdks/java/io/components/src/main/java/org/apache/beam/sdk/io/components/deadletterqueue/sinks/ThrowingSink.java, sdks/java/io/components/src/test/java/org/apache/beam/sdk/io/components/deadletterqueue/DLQRouterTest.java
=> Add initial DLQ router

plugins/beam-code-completion-plugin/build.gradle.kts, plugins/beam-code-completion-plugin/src/main/java/BeamCompletionConfidence.java, plugins/beam-code-completion-plugin/src/main/java/BeamCompletionContributor.java, plugins/beam-code-completion-plugin/src/main/resources/META-INF/plugin.xml, plugins/beam-code-completion-plugin/src/test/java/BeamCompletionContributorTestCase.java, plugins/beam-code-completion-plugin/src/test/testData/TestCompletions.java, plugins/beam-code-completion-plugin/src/test/testData/TestCompletionsWrongClass.java, plugins/beam-code-completion-plugin/src/test/testData/TestCompletionsWrongMethod.java
1. Implemented an Element Pattern that is triggered after 'apply' method of org.apache.beam.sdk.Pipeline class.
2. Wrote tests that ensure the element pattern is triggered at expected places. …
=> Code Completion Plugin: Define Element Pattern for Beam Java SDK

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/stream/DirectStreamObserver.java, sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/logging/BeamFnLoggingClientBenchmark.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/BeamFnControlClient.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/BeamFnControlClientTest.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java
Otherwise it can cause deadlocks if the log buffer fills up but is no longer being drained. …
=> Ensure that the BeamFnLoggingClient terminates process if stream breaks

sdks/go/cmd/prism/README.md, sdks/go/cmd/prism/prism.go, sdks/go/pkg/beam/runners/prism/internal/README.md, sdks/go/pkg/beam/runners/prism/internal/doc.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/web/jobdetails.html, sdks/go/pkg/beam/runners/prism/internal/web/web.go
Does a number of things to improve the Prism runner UI experience.
* Allows the UI to be pointed to any JobManagement instance, where it will render the information it gets.
* Improve the JobDetails page with topologically sorted transforms, and the input and output pcollection element counts.
* Have the state included in the details page.
* Include basic instructions on using the stand alone prism command.
* Allow the command to run either the management server or the UI as desired. This allows using the UI against any JobManagement endpoint, including a different instance of itself. This allows better iteration on the UI since the state of the JobManagement server doesn't need to restart from scratch each time for checking changes. Probably allows for automatic recompiles in the future. …
=> [prism] UI improvements.

playground/frontend/lib/modules/shortcuts/constants/global_shortcuts.dart, playground/frontend/playground_components/lib/src/repositories/backend_urls.dart, playground/frontend/playground_components/lib/src/theme/theme.dart, playground/frontend/playground_components/lib/src/theme/transitions.dart, playground/frontend/web/index.html
Improvements in this PR:
- Fixed a bug that was causing the backend initial ping that was only intended for staging. This can cut 500-1000 ms from the load time.
- Dropped the animation of the page initial appearance. This improves the perceived performance. …
=> Performance improvements

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java, website/www/site/layouts/shortcodes/flink_java_pipeline_options.html, website/www/site/layouts/shortcodes/flink_python_pipeline_options.html
=> [runners-flink] #27175 fix coder for eagerly bound state

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerWriteSchemaTransformProvider.java
Fixes #27159
Reverts apache/beam#27021
Let's revert this commit to get the precommit back green at this moment
=> Revert "Adding error tag and metrics in SpannerWriteSchemaTransformProvider"

playground/backend/internal/cache/redis/redis_cache.go, playground/backend/internal/code_processing/code_processing.go, playground/backend/internal/components/cache_component.go, playground/backend/internal/db/datastore/datastore_db.go, playground/backend/internal/utils/file_utils.go, playground/backend/internal/utils/system_utils.go
Decreasing severity of several expected "error" messages …
=> [Playground] Decrease severity of not important log messages

playground/terraform/README.md, playground/terraform/build.gradle.kts, playground/terraform/infrastructure/cloudfunctions/main.tf
Rename CloudFunction "playground_function_put_url" to "playground_function_del_url" …
=> [Playground] - Cloudfunction rename

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerWriteSchemaTransformProvider.java
Found the root cause of the issue caused by #27021. Fixed it, hence reverting #27204  …
=> Adding error tag and metrics in SpannerWriteSchemaTransformProvider

.github/workflows/beam_PreCommit_Website.yml
Disable PreCommit Website Github Workflow until its figured out what is causing slow tests …
=> disabling triggers on precommit website due to regression

sdks/python/apache_beam/testing/analyzers/constants.py, sdks/python/apache_beam/testing/analyzers/github_issues_utils.py, sdks/python/apache_beam/testing/analyzers/perf_analysis.py, sdks/python/apache_beam/testing/analyzers/perf_analysis_utils.py, sdks/python/apache_beam/testing/analyzers/tests_config.yaml
Improve performance alerting tool UI. 
add additional information such as test link, dashboard link etc …
=> Improve performance alert tool

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/container/license_scripts/dep_urls_java.yaml
Update google_cloud_platform_libraries_bom to 26.17.0. Associated updates to google_cloud_spanner_version, gax_version, and protobuf_version. …
=> Update to libraries-bom 26.17.0

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
=> Using capabilities instead of the container name to set use_single_core_per_container

CHANGES.md, website/www/site/content/en/blog/beam-2.48.0.md
https://github.com/apache/beam/issues/27000
=> Add #27000 as a known issue released in Beam 2.48.0

sdks/python/apache_beam/runners/worker/bundle_processor.py, sdks/python/apache_beam/runners/worker/bundle_processor_test.py, sdks/python/apache_beam/runners/worker/data_sampler.py, sdks/python/apache_beam/runners/worker/data_sampler_test.py, sdks/python/apache_beam/runners/worker/operations.pxd, sdks/python/apache_beam/runners/worker/operations.py, sdks/python/apache_beam/runners/worker/sdk_worker.py, sdks/python/apache_beam/runners/worker/sdk_worker_test.py
Should decrease Python data sampling overhead from 20% to less than 2%.
Code was checking whether to sample on a per-element basis. This led to a large performance degradation. Now, a shared reference to a data class is given to each output and a timer. Every so often, the timer wakes up and grabs the most recent sample. The samples are still held in a circular buffer to minimize memory usage risk. …
=> Python data sampling optimization 

sdks/typescript/src/apache_beam/io/index.ts, sdks/typescript/src/apache_beam/transforms/index.ts, sdks/typescript/tsconfig.json
fixes #26299
I don't know why you didn't set `declaration: true` or why you included the test dirs.  I tried flattening the structure of the dist dir, but I got all sorts of import errors.  Someone with more knowledge of the intricacies of NPM packages may be able to do better than I did.
I added more exports because there was no other way to access things inside `io` or the `windowings.js` exports.  Not sure why everything isn't exported, because I can't see another way to use the code.
Happy to revise if someone suggests a better fix, but this fixes all of my import issues. …
=> fix(typescript): Publish types correctly, don't publish tests

README.md
Add Beam Playground and Tour of Beam to Readme. …
=> update readme with Beam Playground, Tour of Beam

gradle.properties, sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
Leftover work of [https://github.com/apache/beam/commit/561870be80cc8696a926d7322b0f47ddeddcc222](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fapache%2Fbeam%2Fcommit%2F561870be80cc8696a926d7322b0f47ddeddcc222) …
=> Remove leftover Python 3.7 references

CHANGES.md
Note the availability of timers in CHANGES.md for the 2.490 release. …
=> [#22737] Add line about timer support for Go

website/www/site/content/en/get-started/tour-of-beam.md
Fixes #27241 
`Note`: I didn't re-add this page onto the nav bar. I don't think its needed, as once a user is on the site, they can navigate directly to `Tour of Beam (Beta)`. This is just a landing page for those that search through a search engine, to provide better UX w/o a broken link.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/ …
=> Add Tour of Beam Page

sdks/go/cmd/prism/prism.go
Updates a flag to `serveHTTP` to align with Go style decisions on initialisms.  …
=> [prism] Fix linting issue for flag var

sdks/java/io/splunk/src/main/java/org/apache/beam/sdk/io/splunk/SplunkIO.java
A lot of the SplunkIO parameters are supposed to be optional parameters, yet there are checks to make sure these parameters are not null. This PR will rid of these erroneous null checks. …
=> Remove some null checks for optional SplunkIO parameters

sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/AvroWriteSchemaTransformFormatProvider.java, sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/CsvWriteSchemaTransformFormatProvider.java, sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformFormatProvider.java, sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformFormatProviders.java, sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformProvider.java, sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/JsonWriteSchemaTransformFormatProvider.java, sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/ParquetWriteSchemaTransformFormatProvider.java, sdks/java/io/file-schema-transform/src/main/java/org/apache/beam/sdk/io/fileschematransform/XmlWriteSchemaTransformFormatProvider.java, sdks/java/io/file-schema-transform/src/test/java/org/apache/beam/sdk/io/fileschematransform/AvroWriteSchemaTransformFormatProviderTest.java, sdks/java/io/file-schema-transform/src/test/java/org/apache/beam/sdk/io/fileschematransform/CsvWriteSchemaTransformFormatProviderTest.java, sdks/java/io/file-schema-transform/src/test/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformFormatProviderTest.java, sdks/java/io/file-schema-transform/src/test/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformFormatProvidersTest.java, sdks/java/io/file-schema-transform/src/test/java/org/apache/beam/sdk/io/fileschematransform/JsonWriteSchemaTransformFormatProviderTest.java, sdks/java/io/file-schema-transform/src/test/java/org/apache/beam/sdk/io/fileschematransform/ParquetWriteSchemaTransformFormatProviderTest.java, sdks/java/io/file-schema-transform/src/test/java/org/apache/beam/sdk/io/fileschematransform/XmlWriteSchemaTransformFormatProviderTest.java
Add metrics to all `FileWriteSchemaTransforms`. A few refactoring is needed to make this possible
* Change all FileSchemaTransformFormatProvider to returning `PCollectionTuple` instead of just `PCollection<String>` to plumb error rows out
* Add an `ErrorCounterFn` that can be used generally with all FileSchemaTransforms. …
=> Add error metrics and DLQ support to GCS/File write schema transforms

.github/workflows/run_perf_alert_tool.yml, sdks/python/apache_beam/testing/analyzers/perf_analysis.py, sdks/python/apache_beam/testing/analyzers/perf_analysis_test.py
=> Fix perf tool tests

playground/backend/internal/code_processing/code_processing.go, playground/backend/internal/errors/lifecycle_error.go
Decrease severity of messages which come from child processes as they indicate errors in user-submitted code
[![Build …
=> [Playground] Decrease run log failure messages severity

sdks/go/test/integration/xlang/expansion_test.go
Sets the target Beam version for the expansion service JAR to the current version in core - 2 minor versions. This selection will ensure that when a release is being cut the targets pointed to by the code will still exist.
Fixes #21279 …
=> Programmatically choose target Beam version for Automated Expansion Service tests

examples/notebooks/beam-ml/run_inference_with_tensorflow_hub.ipynb
Added a note for using `TFModelHandler` with TF2 saved model format. …
=> [Python] Add note for using TF2 models with TensorFlow Hub

sdks/java/container/java21/java21-security.properties, sdks/java/container/java21/option-java21-security.json
Changes:
* Add Java version-specific override to the security property jdk.tls.disabledAlgorithms via a container image meta option. Noting that the property value is derived from openjdk 21-ea and this action does not reflect that a Beam SDK container officially supporting Java 21 is available. 
See #24619 for more historical context.  …
=> Add boilerplate Java21 security properties support for Java SDK containers

sdks/python/apache_beam/runners/common.pxd, sdks/python/apache_beam/runners/common.py, sdks/python/apache_beam/runners/worker/bundle_processor.py, sdks/python/apache_beam/runners/worker/bundle_processor_test.py, sdks/python/apache_beam/runners/worker/data_sampler.py, sdks/python/apache_beam/runners/worker/data_sampler_test.py, sdks/python/apache_beam/runners/worker/operations.pxd, sdks/python/apache_beam/runners/worker/operations.py, sdks/python/apache_beam/runners/worker/sdk_worker.py, sdks/python/apache_beam/runners/worker/sdk_worker_test.py
This utilizes the ExecutionContext to set the current OutputSampler for the the input value.
Addresses #26704 …
=> Implement Exception Sampling in the Python SDK

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Forgot to merge this before release cut
R: @bvolpato  …
=> Cherry pick #27285 into release-2.49.0 branch

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/go/run_with_go_version.sh
Bump the Go version to 1.20.5
Similar to a previous pr, to bump to 1.20.4
https://github.com/apache/beam/pull/26787 …
=> bump go version to 1.20.5

sdks/python/expansion-service-container/Dockerfile
=> Use requirements file as a constraint when building the expansion service container

website/www/site/content/en/get-started/quickstart-go.md
Update the Go quickstart to reduce the environmental demand on a user. This PR fixes walls users might encounter from following the instructions.
* Move from installing the wordcount to simply executing it. Installing runs the risk the user doesn't have the go/bin directory on their PATH (or OS equivalent). We shouldn't make this assumption.
* Remove unnecessary steps leading to execution.
* Reference the Beam Go Starter project in next steps.
The Quickstart really should jump from that to building a pipeline from scratch with Go and explain a little bit more about what's going on, as Quickstarts are often a first landing page for new users. But that's a task for a later PR.
Fixes #27207  …
=> [#27207] Update Go quickstart.

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/GrpcWindmillServer.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillServerStub.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/FakeWindmillServer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/GrpcWindmillServerTest.java, runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto
=> Populate getWorkStream latencies in dataflow streaming worker harness

sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/KafkaSourceConsumerFn.java
Fixed a bug which caused a NPE when unboxing this.restriction.milisToRun. Removed the first check because it was just for the case when milisToRun == -1 (which was made for backward compatibility I assume). Added this comparison to the second check in the way so that milisToRun is not null when it is compared to -1
fixes #27302 …
=> BugFix for #27302 DebeziumIO fails to claim records from a database

.github/workflows/build_release_candidate.yml
There are 2 problems/tasks that need to be addressed before this can be published/merged: …
=> Publish Docker artifacts from build_release_candidate.yml

sdks/python/apache_beam/examples/snippets/snippets_test.py
This makes the code more uniform and slightly simplifies managing internal copy of Beam we have. …
=> Remove relative imports.

CHANGES.md
* Move entry added in between to correct section …
=> Update CHANGES.md after 2.49.0 cut

learning/tour-of-beam/frontend/lib/pages/tour/state.dart
=> [Tour of Beam] [Frontend] Refinement from 26.06.23

.github/workflows/build_runner_image.yml
Add `google-github-actions/setup-gcloud` to auth against gcp SA
Push to registry is triggered only on PR push …
=> add gcloud auth and push to registry on merge PR

buildSrc/build.gradle.kts, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, ownership/JAVA_DEPENDENCY_OWNERS.yaml, sdks/java/build-tools/src/main/resources/beam/suppressions.xml
Updates the obsolete Avro Gradle plugin by commercehub to the earliest version of davidmc24's Avro plugin and addresses #27231.
It seems the obsolete artifact versions are being yanked, which caused 0.11.0 to go missing.
Obsolete versions of the commercehub plugin are still available through releases by davidmc24 on GitHub which are accessible through Jitpack. I've added a new repository restricted to only include com.github.davidmc24.gradle-avro-plugin.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-j …
=> Upgrade obsolete Avro plugin to 0.16.0

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile
Install GitHub CLI to the runner image …
=> adds GitHub CLI to runner image

.github/workflows/build_runner_image.yml
- Fixes registry path for credential helper
- Adds paths to push trigger …
=> fix repo and add paths to push trigger

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
=> Updates PythonExternalTransform to support IPv6 addresses

.github/workflows/build_runner_image.yml
Fixes:
- wrong file path in push trigger
- Wrong env variable used in docker load and push
Tested on my fork and runners …
=> wrong path fix

CI.md
This is out of date, updates to most recent permissions …
=> Keep roles for gcp SA updated

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile
Adds `gcloud` and `kubectl` to the image …
=> adding glcoud cli and kubectl

sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java
fixes #27292 
Handles that the client may batch logs into fewer requests than would trigger onReady evaluation
Fix phaser usage error which didn't sychronize threads as intended
Only counts attempted fake logs to avoid other logging from causing failures.
Improves test speed by fixing fake server to terminate stream.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github. …
=> Remove flakes of BeamFnClientLoggingTest

.github/gh-actions-self-hosted-runners/arc/README.md, .github/gh-actions-self-hosted-runners/arc/config/arc_autoscaler.tpl, .github/gh-actions-self-hosted-runners/arc/config/arc_deployment.tpl, .github/gh-actions-self-hosted-runners/arc/environments/beam.env, .github/gh-actions-self-hosted-runners/arc/gke.tf, .github/gh-actions-self-hosted-runners/arc/helm.tf, .github/gh-actions-self-hosted-runners/arc/kubernetes.tf, .github/gh-actions-self-hosted-runners/arc/variables.tf
Adds a possibility to create new runner pools with matching node pools.
Update env file to accommodate new variables …
=> Arc additional pools

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableReadSchemaTransformProviderIT.java
Fixes #27319
Move code that creates the BT table into setup and add some variability to the table name (date stamp) to make it more reliable. Added a log for debugging
=> Address failing BT read tests in #27319

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java, sdks/java/transform-service/launcher/src/main/java/org/apache/beam/sdk/transformservice/launcher/TransformServiceLauncher.java
This is a Java SDK update similar to the Python SDK update added in https://github.com/apache/beam/pull/27228.
This fixes https://github.com/apache/beam/issues/27226. …
=> Automatically use Docker Compose based transform service for PythonExternalTransform when needed.

.github/workflows/README.md, .github/workflows/job_PreCommit_Python.yml, .github/workflows/job_PreCommit_PythonAutoformatter.yml, .github/workflows/job_PreCommit_Python_Dataframes.yml, .github/workflows/job_PreCommit_Python_Examples.yml, .github/workflows/job_PreCommit_Python_Runners.yml, .github/workflows/job_PreCommit_Python_Transforms.yml, .github/workflows/job_Precommit_PythonLint.yml, .github/workflows/job_Precommit_Python_Coverage.yml, .github/workflows/job_Precommit_Python_DockerBuild.yml
Moving the following jobs to Github Actions:
job_PreCommit_PythonAutoformatter
job_PreCommit_Python_Dataframes
job_PreCommit_Python_Examples
job_PreCommit_Python_Runners
job_Precommit_Python
job_Precommit_Python_Coverage
job_Precommit_Python_DockerBuild
job_Precommit_PythonLint
job_PreCommit_Python_Transforms
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apac …
=> python precommit jobs and readme

sdks/typescript/container/Dockerfile
=> Restore trailing slash accidentally removed in https://github.com/apache/beam/pull/25665

build.gradle.kts, sdks/python/container/build.gradle
Cherry pick if we do RC2. This should fix the GHA workflow …
=> Cherry-pick: Add flag to do a docker system prune between docker push steps (#26967)

.github/workflows/beam_PreCommit_Java_Examples_Dataflow.yml
The following jenkins jobs have been migrated:
- https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Commit/
- https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Cron/
- https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Phrase/
- by creating pull requests with changes in trigger paths
- by making a push …
=> Migrate "beam_PreCommit_Java_Examples_Dataflow" Jenkins job to Github Actions

sdks/typescript/container/Dockerfile
=> [Release-2.49.0] Restore trailing slash accidentally removed in https://github.com/apache/beam/pull/25665 (#27386)

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java, sdks/java/fn-execution/src/test/java/org/apache/beam/sdk/fn/CancellableQueueTest.java
Keeping the references around means that memory usage can grow as the queue is reused, even if the queue is being drained regularly.
Fixes #27401 …
=> Ensure CancellableQueue doesn't keep references to logically removed objects

.github/workflows/beam_PreCommit_Java_Examples_Dataflow.yml
=> temporarily disable PreCommit_Java_Examples_Dataflow.yml

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java, sdks/java/fn-execution/src/test/java/org/apache/beam/sdk/fn/CancellableQueueTest.java
=> [Release-2.49.0] Ensure CancellableQueue doesn't keep references to logically removed objects. (#27403)

.test-infra/jenkins/job_PreCommit_Whitespace.groovy, build.gradle.kts, learning/tour-of-beam/terraform/build.gradle.kts, sdks/python/test-suites/tox/py38/build.gradle
recent change added whitespace to build.gradle.kts breaking internal checks …
=> Add build.gradle.kts to whitespace check

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile, .github/workflows/beam_PreCommit_Website.yml
Runner image:
- add BuildX
- Fix Gcloud permission issue
PreCommit Website:
- Update to latest
- add `small` label for runner label list …
=> Runner image buildx and Website Precommit update

sdks/python/apache_beam/ml/transforms/base.py, sdks/python/apache_beam/ml/transforms/base_test.py, sdks/python/apache_beam/ml/transforms/handlers.py, sdks/python/apache_beam/ml/transforms/handlers_test.py, sdks/python/apache_beam/ml/transforms/tft.py, sdks/python/apache_beam/ml/transforms/utils.py
Implement _ _ call _ _ method for BaseOperation instances. …
=> Refactor MLTrasform BaseOperation class

.github/workflows/beam_PreCommit_Go.yml, .github/workflows/beam_PreCommit_Java_Examples_Dataflow.yml, .github/workflows/beam_PreCommit_Typescript.yml, .github/workflows/beam_PreCommit_Website.yml, .github/workflows/beam_PreCommit_Whitespace.yml, .github/workflows/job_PreCommit_Python.yml, .github/workflows/job_PreCommit_PythonAutoformatter.yml, .github/workflows/job_PreCommit_Python_Dataframes.yml, .github/workflows/job_PreCommit_Python_DockerBuild.yml, .github/workflows/job_PreCommit_Python_Examples.yml, .github/workflows/job_PreCommit_Python_Runners.yml, .github/workflows/job_PreCommit_Python_Transforms.yml, .github/workflows/job_Precommit_PythonLint.yml, .github/workflows/job_Precommit_Python_Coverage.yml
- Changes `runs-on` labels for most jobs to use ` main`
- Updated PreCommit whitespace job to conform to others …
=> adding main labels to workflows. Updated whitespace job

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
=> Fix unused import to unbreak presubmit lint.

sdks/python/apache_beam/io/range_trackers.py
- [] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
Not applicable
Not applicable
Not applicable …
=> [Python] Typo in docstring of UnsplittableRangeTracker

website/www/site/content/en/contribute/release-guide.md
This is working now, so we can add it to the docs.
✨ [RENDERED](http://apache-beam-website-pull-requests.storage.googleapis.com/27457/contribute/release-guide/index.html#run-build_release_candidate-github-action-to-create-a-release-candidate) ✨ 
GitHub Actions …
=> Add dockerhub step to release guide

build.gradle.kts, sdks/python/test-suites/dataflow/build.gradle, sdks/python/test-suites/dataflow/common.gradle
Continues ripping out runner v2 infra (started in #26543)
Part of https://github.com/apache/beam/issues/26546 …
=> Some more runner v2 cleanup

sdks/python/apache_beam/ml/inference/vertex_ai_inference.py
Adds handling for a subnetwork kwarg, allowing the use of a private Vertex AI endpoint and uncapping the maximum request size the service will accept. Also updates the docstring to reflect this.  …
=> Allow use of private endpoints for Vertex AI requests

model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto, model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto
Fill in a long standing gap in the proto documentation, by explicitly including the source and sink transforms among the StandardPTransform primitives.
I suspect a reason it went on so long without is that the Urns are largely in the Runner Proto, but everything about the transform is tied to the FnAPI implementation.
Since we no longer expect alternative FnAPI impelementations in Beam V2 that are not GRPC based, it's time to fill that gap. …
=> [#27435] Describe the Source and Sink transform and urns in the protos.

.test-infra/jenkins/job_PostCommit_Python_ValidatesRunner_Dataflow.groovy, CHANGES.md, sdks/python/apache_beam/examples/inference/runinference_metrics/pipeline/options.py, sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py, sdks/python/apache_beam/options/pipeline_options.py, sdks/python/apache_beam/runners/dataflow/dataflow_metrics_test.py, sdks/python/apache_beam/transforms/combinefn_lifecycle_test.py, sdks/python/scripts/run_integration_test.sh, sdks/python/test-suites/dataflow/build.gradle, sdks/python/test-suites/dataflow/common.gradle, sdks/python/test-suites/gradle.properties
I think this clears out the rest of it. Continuation of #27464
Fixes #26546
Fixes #20610 …
=> Finish removing dataflow runner v1/v2 splits

sdks/java/io/kafka/kafka-integration-test.gradle
It is found in release validation that there are several empty artifacts (e.g. https://repository.apache.org/content/repositories/orgapachebeam-1349/org/apache/beam/beam-sdks-java-io-kafka-kafka-251/2.49.0/beam-sdks-java-io-kafka-kafka-251-2.49.0.jar) that is generated from test project.
This change disabled release of the following generated `beam-sdks-java-io-kafka-kafka-xxx` project. As we did for test only projects in #25191 …
=> Stop release generated kafka-[version] test artifacts

sdks/python/apache_beam/ml/transforms/tft.py, sdks/python/apache_beam/ml/transforms/tft_test.py
Add NGrams and ScaleByMinMax data processing transforms with unit tests …
=> Add ScaleByMinMax and NGrams data processing transformations

sdks/python/apache_beam/examples/ml_transform/ml_transform_basic.py
=> Refactor MLTransform basic example

sdks/go/examples/snippets/04transforms.go, website/www/site/content/en/documentation/programming-guide.md
Translate the Timers examples into Go for the programming guide.
Include them in the programming guide.
Final work for #22737  …
=> [#22737] Add Go SDK timers to programming guide

website/www/site/config.toml, website/www/site/content/en/blog/beam-2.49.0.md, website/www/site/content/en/documentation/io/connectors.md, website/www/site/content/en/documentation/runners/flink.md, website/www/site/content/en/get-started/downloads.md, website/www/site/data/authors.yml
=> Update Beam website to release 2.49.0

.github/workflows/build_wheels.yml, sdks/python/build.gradle
Pin the Build Wheels workflow to Cython < 1 in an effort to get the workflows green. Matches pinned Cython for our containers. …
=> Pin Build Python Wheels to Cython < 1

sdks/python/apache_beam/ml/transforms/base_test.py, sdks/python/apache_beam/ml/transforms/handlers_test.py, sdks/python/apache_beam/ml/transforms/tft.py, sdks/python/apache_beam/ml/transforms/tft_test.py
Fixes:  https://github.com/apache/beam/issues/27505
This PR supports splitting strings based on a delimiter string. delimiter string can contain multiple delimiters.
Also, this PR removes the name batch from the unit tests, since the inputs are not exactly batched. …
=> Add splitting string for string related data transforms

.github/workflows/beam_PreCommit_CommunityMetrics.yml, .test-infra/metrics/build.gradle
The following jenkins jobs have been migrated:
https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_CommunityMetrics_Commit/
https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_CommunityMetrics_Cron/
https://ci-beam.apache.org/view/PreCommit/job/beam_PreCommit_CommunityMetrics_Phrase/
How has it been tested?
by creating pull requests with changes in trigger paths
by adding a comment to the PR
by making a push …
=> Add GitHub Workflow Replacement for Jenkins job_PreCommit_Community_Metrics

sdks/typescript/package.json
=> Add missing package to imports.

sdks/python/apache_beam/runners/worker/bundle_processor_test.py, sdks/python/apache_beam/runners/worker/data_sampler_test.py
correct python lints found in https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Commit/20229/consoleText …
=> [Python] Fix python lints

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py, sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py, sdks/python/apache_beam/runners/dataflow/internal/names.py
=> Update Dataflow dev container image tag.

runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto, runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill_service.proto
add workermetadata to windmill protos
R: @scwhittle @dustin12 
-----------------------
[![Java …
=> add worker metadata to windmill* protos

sdks/go/pkg/beam/testing/passert/equals_test.go, sdks/go/pkg/beam/testing/passert/floats.go, sdks/go/pkg/beam/testing/passert/passert.go, sdks/go/pkg/beam/testing/passert/passert_test.go
Fixup and register functions so passert can be tested against prism.
See #27550 and #24789.
Remaining cleanup for registrations in passert tracked in #27567. …
=> Register passert functions & fix up floats.

playground/README.md
=> Drop stray `

.test-infra/pipelines/infrastructure/03.io/api-overuse-study/README.md, .test-infra/pipelines/infrastructure/03.io/api-overuse-study/common.tfvars, .test-infra/pipelines/infrastructure/03.io/api-overuse-study/namespace.tf, .test-infra/pipelines/infrastructure/03.io/api-overuse-study/provider.tf, .test-infra/pipelines/infrastructure/03.io/api-overuse-study/variables.tf
This PR addresses #27088 by creating Infrastructure-as-Code to setup a Kubernetes environment. It's README guides the developer on usage. The API Overuse Study (see linked issue for details) requires a quota aware mock API deployed on Kubernetes.
To …
=> [API Overuse Study] Setup a Kubernetes environment

sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
Prism side changes to ensure the job failure message is actually emitted when the job fails.
Dual of https://github.com/apache/beam/pull/27570 …
=> [prism] Send job failure message.

sdks/go/test/regression/lperror.go, sdks/go/test/regression/pardo.go
Add registrations for the regression integration test package.
See https://github.com/apache/beam/pull/27550 and https://github.com/apache/beam/issues/24789.  …
=> [prism] registrations for Regression tests.

website/www/site/content/en/get-started/beam-overview.md, website/www/site/layouts/partials/section-menu/en/get-started.html
* removed Beta for both Beam Playground and Tour of Beam
* added the cookbook github link to the beam overview …
=> add the cookbook link

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
=> Fix correct netty version

sdks/java/transform-service/src/main/java/org/apache/beam/sdk/transformservice/TransformServiceConfig.java
This PR addresses #20507 by removing the SuppressWarnings from TransformServiceConfig.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/ …
=> Remove SuppressWarnings from TransformServiceConfig

sdks/java/core/src/test/java/org/apache/beam/sdk/values/RowTest.java
Addresses #19561 
After #24773, it was discovered that there needs to be an improvement to the unit tests for Row.equals to test edge cases on null values …
=> add null value edge case to unit test for Row.equals

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/Group.java, sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/transforms/GroupTest.java, sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamWindowRel.java
=> Support withFanout and withHotKeyFanout on schema group transform

website/www/site/content/en/get-started/try-beam-playground.md, website/www/site/layouts/index.html
=> Remove beta label from playground in a few more spots

sdks/python/apache_beam/examples/inference/vertex_ai_image_classification.py
Fixes an typing incompatibility with Python 3.8 and processes a glob of files rather than a single image.
[![Build …
=> Vertex AI Model Handler Example Improvements

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ByteBuddyUtils.java
This change resolves `Caused by: java.lang.IllegalArgumentException: ... must be defined in the same package as org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Function` errors.
The lookup used by `ClassLoadingStrategy.UsingLookup` "can define types only in the same class loader and in the same package as the type within which it was created" 
https://github.com/apache/beam/issues/26981 …
=> Make class loading consistent for generated Function implementations

sdks/python/container/piputil.go
=> Fix container startup fail when requirement exists

.github/PULL_REQUEST_TEMPLATE.md
=> Add trigger phrases link to PR template

.test-infra/pubsub/README.md, .test-infra/pubsub/gcs_image_looper.py, .test-infra/pubsub/test_image_looper.py
* Check the README.md for more details. The process now is manual. …
=> added a simple pub/sub topic for testing

sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisIOReadTest.java
This test accidentally succeeded when running on a fast machine.
This PR disambiguates the stubs to prevent that and fixes a copy paste bug.
Closes #27666 …
=> [AWS] Fix bug in KinesisIOReadTest (closes #27666)

.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml, .github/workflows/beam_PreCommit_Go.yml, .github/workflows/beam_PreCommit_Java_Examples_Dataflow.yml, .github/workflows/beam_PreCommit_PythonDocs.yml, .github/workflows/beam_PreCommit_Python_Integration.yml, .github/workflows/beam_PreCommit_RAT.yml, .github/workflows/beam_PreCommit_SQL_Java11.yml, .github/workflows/beam_PreCommit_Typescript.yml, .github/workflows/beam_PreCommit_Website.yml, .github/workflows/beam_PreCommit_Whitespace.yml, .github/workflows/job_PreCommit_Python.yml, .github/workflows/job_PreCommit_PythonAutoformatter.yml, .github/workflows/job_PreCommit_PythonLint.yml, .github/workflows/job_PreCommit_Python_Coverage.yml, .github/workflows/job_PreCommit_Python_Dataframes.yml, .github/workflows/job_PreCommit_Python_DockerBuild.yml, .github/workflows/job_PreCommit_Python_Examples.yml, .github/workflows/job_PreCommit_Python_Runners.yml, .github/workflows/job_PreCommit_Python_Transforms.yml
We should always allow manual triggering of jobs from committers …
=> Add worfklow_dispatch triggers to all new jobs

sdks/python/apache_beam/ml/__init__.py, sdks/python/apache_beam/ml/transforms/tft.py
=> Add MLTransform to __init__ and change input types of transforms

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java
=> Don't make StorageAPI tablerow names case-sensitive

.github/workflows/README.md
Once this is merged, I'll send an email to the dev list with similar instructions …
=> Add instructions on adding new Actions workflows

.github/workflows/beam_PreCommit_ItFramework.yml, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/utils/ParquetTestUtil.java
=> Add It_Framework PreCommit

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, it/cassandra/build.gradle, it/cassandra/src/main/java/org/apache/beam/it/cassandra/CassandraResourceManager.java, it/cassandra/src/main/java/org/apache/beam/it/cassandra/CassandraResourceManagerException.java, it/cassandra/src/main/java/org/apache/beam/it/cassandra/CassandraResourceManagerUtils.java, it/cassandra/src/main/java/org/apache/beam/it/cassandra/matchers/CassandraAsserts.java, it/cassandra/src/main/java/org/apache/beam/it/cassandra/matchers/package-info.java, it/cassandra/src/main/java/org/apache/beam/it/cassandra/package-info.java, it/cassandra/src/test/java/org/apache/beam/it/cassandra/CassandraResourceManagerIT.java, it/cassandra/src/test/java/org/apache/beam/it/cassandra/CassandraResourceManagerTest.java, settings.gradle.kts
Add Cassandra Resource manager to manage Cassandra Resources in tests. …
=> It cassandra

sdks/go/pkg/beam/create.go, sdks/go/pkg/beam/create_test.go
Fix beam.Create tests to pass under prism. …
=> [#24789] Register create functions to pass on prism.

.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml, build.gradle.kts, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/go/container/build.gradle, sdks/go/test/run_validatesrunner_tests.sh
- Introduce new flags to build and push multi-arch Go containers(will not affect the current building of x86 containers if flags are not specified during build);
- Change the validatesRunner script so it builds and pushes multi-arch Go container;
- Fix Go Dataflow ARM github actions test by adding the missing $USER variable. …
=> Add flags to build multiarch Go SDK containers and fix Go Dataflow ARM github actions test

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
=> Populate name map during snapshot restore

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Bump HCLS v1 API Version to most recent update (05/2023). …
=> Bump HCLS V1 API Version to latest [05/2023]

it/elasticsearch/build.gradle, it/elasticsearch/src/main/java/org/apache/beam/it/elasticsearch/ElasticsearchResourceManager.java, it/elasticsearch/src/main/java/org/apache/beam/it/elasticsearch/ElasticsearchResourceManagerException.java, it/elasticsearch/src/main/java/org/apache/beam/it/elasticsearch/ElasticsearchUtils.java, it/elasticsearch/src/main/java/org/apache/beam/it/elasticsearch/package-info.java, it/elasticsearch/src/test/java/org/apache/beam/it/elasticsearch/ElasticsearchResourceManagerIT.java, it/elasticsearch/src/test/java/org/apache/beam/it/elasticsearch/ElasticsearchResourceManagerTest.java, it/elasticsearch/src/test/java/org/apache/beam/it/elasticsearch/ElasticsearchUtilsTest.java, settings.gradle.kts
Add Elasticsearch resource manager to manage elastic search resources in tests. …
=> Add ElasticsearchResourceManager to manage Elasticsearch resources in tests.

.github/workflows/README.md
The previous flow doesn't work with self hosted runners …
=> Update instructions to account for self-hosted runners

sdks/python/apache_beam/runners/worker/operations.py
Some versions of Cython complain about this closure not being allowed here, preventing compilation. …
=> Fix error about monitoring_infos closure.

it/kafka/build.gradle, it/kafka/src/main/java/org/apache/beam/it/kafka/KafkaResourceManager.java, it/kafka/src/main/java/org/apache/beam/it/kafka/KafkaResourceManagerException.java, it/kafka/src/main/java/org/apache/beam/it/kafka/KafkaResourceManagerUtils.java, it/kafka/src/main/java/org/apache/beam/it/kafka/package-info.java, it/kafka/src/test/java/org/apache/beam/it/kafka/KafkaResourceManagerTest.java, it/kafka/src/test/java/org/apache/beam/it/kafka/KafkaResourceManagerUtilsTest.java, settings.gradle.kts
=> Add Kafka Resource managers to manage kafka resources in tests.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, it/mongodb/build.gradle, it/mongodb/src/main/java/org/apache/beam/it/mongodb/MongoDBResourceManager.java, it/mongodb/src/main/java/org/apache/beam/it/mongodb/MongoDBResourceManagerException.java, it/mongodb/src/main/java/org/apache/beam/it/mongodb/MongoDBResourceManagerUtils.java, it/mongodb/src/main/java/org/apache/beam/it/mongodb/conditions/MongoDBDocumentsCheck.java, it/mongodb/src/main/java/org/apache/beam/it/mongodb/conditions/package-info.java, it/mongodb/src/main/java/org/apache/beam/it/mongodb/matchers/MongoDBAsserts.java, it/mongodb/src/main/java/org/apache/beam/it/mongodb/matchers/package-info.java, it/mongodb/src/main/java/org/apache/beam/it/mongodb/package-info.java, it/mongodb/src/test/java/org/apache/beam/it/mongodb/MongoDBResourceManagerIT.java, it/mongodb/src/test/java/org/apache/beam/it/mongodb/MongoDBResourceManagerTest.java, it/mongodb/src/test/java/org/apache/beam/it/mongodb/MongoDBResourceManagerUtilsTest.java, settings.gradle.kts
=> Add MongoDB Resource managers to manage mongodb resources in tests.

sdks/java/io/neo4j/src/main/java/org/apache/beam/sdk/io/neo4j/Neo4jIO.java
A single source row was read as many times as the underlying Neo4j driver needs to retry the execution (in case of transient failures, or cluster leader switch e.g.).
Only the mapping should occur within the transaction function, the actual output should be emitted only once the transaction execution has succeeded.
=> Fix Neo4j read mapping

.github/workflows/beam_PreCommit_Website_Stage_GCS.yml
Right now, the stage gcs workflow is failing because it uses the jwalton/gh-find-current-pr action which hasn't been blessed by infra. We could ask infra to allow list it, but its a small enough piece of code that its probably easier to just roll our own, plus that decreases our vulnerability/supply chain surface
Example failing run: https://github.com/apache/beam/actions/runs/5716072272
Example success after this change on my fork: https://github.com/damccorm/beam/actions/runs/5719430241/job/15497299667?pr=173 (it eventually fails on authing to GCP because I don't have the right env vars set) …
=> Inline jwalton/gh-find-current-pr

.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml
Example of doing this from this branch - https://github.com/apache/beam/actions/runs/5729963480/job/15527738013 …
=> Authenticate to gcr instead of ar in ARM workflow

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/container/license_scripts/dep_urls_java.yaml
Update to libraries-bom 26.21.0 with Guava 32.1.2-jre which resolves the gradle issue from 32.1.1.
Reverts a configuration change made recently by @bvolpato . CC @Abacn …
=> Update to libraries-bom 26.21.0

sdks/python/apache_beam/io/gcp/healthcare/dicomclient.py
Revised documentation for `dicomclient.py` …
=> Improve Documentation on DicomClient.py

website/www/site/content/en/documentation/io/connectors.md
=> Update website with DicomIO

.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh
- Added us.gcr.io/apache-beam-testing/github-actions as one of the repository to clean. …
=> Update script to clean stale containers pushed by GH tests

.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml, .github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml
This will help avoid incorrect interrupts to in progress workflows
For more context, see https://github.com/apache/beam/pull/27671 …
=> Use correct concurrency condition to avoid incorrect interrupts

.github/REVIEWERS.yml
Removing myself from the IO reviewer list as I don't have much context on Beam IO. With the recent reorg, I would have even less opportunity to explore this side :( …
=> Update REVIEWERS.yml 

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, it/neo4j/build.gradle, it/neo4j/src/main/java/org/apache/beam/it/neo4j/Neo4jResourceManager.java, it/neo4j/src/main/java/org/apache/beam/it/neo4j/Neo4jResourceManagerException.java, it/neo4j/src/main/java/org/apache/beam/it/neo4j/Neo4jResourceManagerUtils.java, it/neo4j/src/main/java/org/apache/beam/it/neo4j/conditions/Neo4jQueryCheck.java, it/neo4j/src/main/java/org/apache/beam/it/neo4j/conditions/package-info.java, it/neo4j/src/main/java/org/apache/beam/it/neo4j/package-info.java, it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerIT.java, it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerTest.java, it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerUtilsTest.java, settings.gradle.kts
=> Add Neo4j Resource manager to manage Neo4j resources in tests.

sdks/python/apache_beam/io/gcp/healthcare/dicomio_test.py
This PR:
1) Refactors some existing documentation around the DicomIO Unit tests (in the Python SDK).
2) Renames `fake client` to `mock client` to match industry standard terminology (https://realpython.com/testing-third-party-apis-with-mocks/).
GitHub Actions …
=> Refactor `dicomio_test.py`

release/go-licenses/common.gradle
-  When Docker buildx builder is used, set the load flag to true to load the image into the local repository. …
=> Explicitly load go license container locally

sdks/python/apache_beam/yaml/README.md, sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_mapping.md, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_mapping_test.py, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_test.py
Previously these were implicitly lifted from the base dictionary.
We may want to consider allowing that again, but it is easier to loosen restrictions than tighten them up once this is declared stable. …
=> Nest all transform-specific arguments in an explicit 'config' parameter.

release/go-licenses/common.gradle
The load flag wasn't recognized previously, add buildx flag to pick it up. …
=> Add buildx flag to pick up the load flag.

.github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml, sdks/go/test/run_validatesrunner_tests.sh, sdks/python/container/run_validatescontainer.sh
- Fix typo for the gradle task to push the multi-arch Python SDK container to correct repository
- Made changes to keep multi-arch containers in GCR for 6 weeks. …
=> Push multi-arch Python SDK containers built by GH tests to GCR and remove auto delete

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Combine.java
=> propagate fewKeys to hot-key path

.github/workflows/beam_PostCommit_Java_Examples_Dataflow_ARM.yml
- Change the repo to push so now all ARM tests for diff language SDK containers are under the same parent repo.
- Change the steps of the test job so that all java version tests run in parallel, one version's failure won't stop the build of another version. …
=> Make different Java versions ARM tests run in parallel

.github/workflows/beam_PostCommit_Java_Examples_Dataflow_ARM.yml
- The previous builds failed due to a missing argument for Pjava${version}Home flag, add this flag in this PR.
- Though building java8 doesn't need this flag, the extra (not working) Pjava8Home flag won't make the build fail. …
=> Add javaHome for building Java 11 and 17 multi-arch containers.

examples/notebooks/get-started/learn_beam_basics_by_doing.ipynb
Fixes https://github.com/apache/beam/issues/27411 …
=> Fix broken url for 'Tour of Beam'

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Follow up to https://github.com/apache/beam/pull/27828
The versions list can be obtained from:
```
wget https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/26.21.0/libraries-bom-26.21.0.pom -O base.pom && mvn help:effective-pom -f base.pom -Doutput=effective.pom && cat effective.pom | grep -v 'dependencyManagement' > cleanup.pom && mvn dependency:tree -f cleanup.pom 
```
=> Update versions based on libraries-bom, and add comment to keep consistency

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/stream/DirectStreamObserver.java, sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/stream/ForwardingClientResponseObserver.java, sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/stream/OutboundObserverFactory.java, sdks/java/fn-execution/src/test/java/org/apache/beam/sdk/fn/stream/DirectStreamObserverTest.java, sdks/java/fn-execution/src/test/java/org/apache/beam/sdk/fn/stream/ForwardingClientResponseObserverTest.java
This can fix classes of stuckness during termination if the channel breaks but threads are blocked on the
phaser attempting to send. …
=> Ensure that if grpc stream terminates that DirectStreamObserver does not block on Phaser.

.github/actions/setup-action/action.yml, .github/workflows/beam_PreCommit_Java_Flink_Versions.yml
Fixes #27854
example run:
- pull request creation: https://github.com/Abacn/beam/actions/runs/5766352092/job/15634107987 in https://github.com/Abacn/beam/pull/57
- pull request phrase trigger: https://github.com/Abacn/beam/actions/runs/5766319108/job/15634024620 in https://github.com/Abacn/beam/pull/56
it appears there is still an issue in the pull request trigger. Once triggered, it will abort the push or schedule run on master branch …
=> Fix action run on base branch

sdks/python/container/run_validatescontainer.sh, sdks/python/test-suites/dataflow/common.gradle
=> Temp changes to see the failure of validatesContainer ARM

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile
Fixes permissions on .config/gcloud …
=> reset permission on .config

.github/gh-actions-self-hosted-runners/arc/config/arc_deployment.tpl
Adds pod UID to env as POD_UID.
Needed for some jobs  …
=> add Pod UID to environment

sdks/python/test-suites/dataflow/common.gradle
=> Fix formatting for Python ValidatesContainer Dataflow ARM

examples/notebooks/beam-ml/nlp_tensorflow_streaming.ipynb, examples/notebooks/beam-ml/run_inference_generative_ai.ipynb, examples/notebooks/healthcare/beam_nlp.ipynb
These just detract from the readability of the notebooks …
=> Remove extraneous warnings from notebook output

.github/workflows/beam_PreCommit_ItFramework.yml, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/LoadTestBase.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/ClassicTemplateClient.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/FlexTemplateClient.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datagenerator/DataGenerator.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastore/DatastoreResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dlp/DlpResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/kms/KMSResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/monitoring/MonitoringClient.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/secretmanager/SecretManagerResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManager.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOLT.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOLT.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerIT.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/ClassicTemplateClientTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/FlexTemplateClientTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/datastore/DatastoreResourceManagerIT.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/kms/KMSResourceManagerIT.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/kms/KMSResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/secretmanager/SecretManagerResourceManagerTest.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/storage/FileBasedIOLT.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/storage/GcsResourceManagerTest.java
This change should make sure that credentials are not required for unit tests. …
=> Add `credentials` as a parameter to builder in Resource managers.

CHANGES.md
The cut for 2.50 is tomorrow so we should make sure these are added …
=> Add MLTransform and Vertex Private endpoints to CHANGES.md

.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh
These get automatically generated as part of https://github.com/apache/beam/blob/e03a14c7d524629f0167f6860a17252382f34af6/.test-infra/metrics/build.gradle#L120 but we only use the latest ones. We should be periodically cleaning up old containers
GitHub Actions …
=> Automatically clean up old metrics containers

sdks/go/pkg/beam/core/runtime/xlangx/payload.go, sdks/go/pkg/beam/io/xlang/bigtableio/bigtable.go, sdks/go/pkg/beam/transforms/xlang/inference/inference.go, sdks/go/pkg/beam/transforms/xlang/schema/external.go, sdks/go/test/build.gradle, sdks/go/test/integration/flags.go, sdks/go/test/integration/integration.go, sdks/go/test/integration/io/xlang/bigtable/bigtable.go, sdks/go/test/integration/io/xlang/bigtable/bigtable_test.go
This addresses #27509 by adding the scalable Java BigTableIO via Xlang. …
=> Implement go xlang wrapper for reading from Bigtable

runners/google-cloud-dataflow-java/arm/build.gradle
- Only running wordcount should be sufficient. …
=> Only include WordCount for PostCommit Java Examples Dataflow ARM.

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubWriteIT.java
#27286 merged in between test run on #27895 and #27895 merged …
=> Replace remaining old guava namespace happens after #27895

sdks/python/apache_beam/io/gcp/bigquery.py, sdks/python/apache_beam/io/gcp/bigquery_read_internal.py
Fix for `ReadFromBigQuery` to support `str` input parameters since yaml pipelines pass these values as strings. …
=> [yaml] Fix BigQueryIO for yaml pipeline compatibility

CHANGES.md
Update changelog to mention new SqsIO.writeBatches (relates to #21429). …
=> Update changelog to mention new SqsIO.writeBatches

.test-infra/metrics/grafana/Dockerfile
From https://hub.docker.com/r/grafana/grafana/tags, use grafana 10.0.3
Fixes #27908 …
=> Use grafana 10.0.3

.asf.yaml
=> Give liferoad issue triage permission

runners/google-cloud-dataflow-java/arm/build.gradle, sdks/go/test/run_validatesrunner_tests.sh, sdks/python/container/run_validatescontainer.sh
These were a little off in their description of the image cleaner …
=> Clean up image cleaner comments

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
Since blocking was a non existant variable i removed references to it in the dockstring on line 75 and fixed it with what it should be.
Issue address #24693. …
=> dataflow runner pydoc fix

sdks/python/apache_beam/transforms/util.py
At least one customer was confused by this when they ran batchElements in the global window and then tried to rewindow.
Behavior is defined here - https://github.com/apache/beam/blob/0a8e3cc0907a996e287629ac544debb480fa8abf/sdks/python/apache_beam/transforms/util.py#L583
and here - https://github.com/apache/beam/blob/0a8e3cc0907a996e287629ac544debb480fa8abf/sdks/python/apache_beam/transforms/util.py#L634
Feature request for improving this is also here - https://github.com/apache/beam/issues/22853 …
=> Clarify timestamp behavior for BatchElements

runners/google-cloud-dataflow-java/arm/build.gradle, runners/google-cloud-dataflow-java/build.gradle
=> Bump Java containers to beam-master-20230809

.github/codecov.yml
We consistently get a red codecov patch mark on python PRs because examples are only covered by integration tests, not unit tests. This should fix it.
Example of this (only adding tests an examples) - https://github.com/apache/beam/pull/27880 …
=> Remove python examples from codecov

sdks/python/apache_beam/examples/ml_transform/ml_transform_basic.py, sdks/python/apache_beam/ml/transforms/base.py, sdks/python/apache_beam/ml/transforms/base_test.py, sdks/python/apache_beam/ml/transforms/handlers.py, sdks/python/apache_beam/ml/transforms/tft_test.py
Using read_artifact_location and write_artifact_location seems cleaner. This doesn't extend down to the TFTProcessHandler since that's not user facing, though that would be a nice future cleanup. …
=> Update how we specify artifact modes

.github/actions/setup-action/action.yml, .github/workflows/beam_PreCommit_RAT.yml
Right now, checkout fails if no merge commit has been created (e.g. there's a merge conflict). This fixes the problem by falling back to the branch contents.
Example with merge conflicts - https://github.com/damccorm/beam/pull/179 (eventually fails because the branch doesn't contain action.yml, but it does successfully checkout) - action run - https://github.com/damccorm/beam/actions/runs/5821884233/job/15785245339?pr=179
Example without merge conflicts - https://github.com/damccorm/beam/pull/180 - action run - https://github.com/damccorm/beam/actions/runs/5821902336/job/15785306991?pr=180 …
=> Fix setup action checkout

sdks/python/apache_beam/yaml/pipeline.schema.yaml, sdks/python/apache_beam/yaml/standard_providers.yaml, sdks/python/apache_beam/yaml/yaml_provider.py
=> Also use config pattern for yaml providers.

examples/notebooks/beam-ml/README.md
=> Add missing notebooks to Readme

website/www/site/content/en/contribute/runner-guide.md
=> Initial pass at modernizing the Runner author guide.

.github/workflows/playground_frontend_test.yml, .github/workflows/tour_of_beam_frontend_test.yml
=> Bump setup-chromedriver to v2

website/Dockerfile
Our current hugo version v0.68.3 was released 3+ years ago, and the framework has improved since then. In particular, better error messages would be handy.
The latest release 0.117.0 was released 4 days ago. …
=> Move beam website to most recent Hugo release (v0.117.0)

website/www/site/content/en/get-started/downloads.md
In updating hugo, in #27974 I noted that some of the download links were broken. This fixes them. …
=> Fix typos in release download links.

.test-infra/terraform/google-cloud-platform/google-kubernetes-engine/README.md
This PR fixes an incorrect URL reference in the README. …
=> Fix referenced README url

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsIO.java, sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/SqsIOWriteBatchesTest.java
Support strict expiration of AWS SQS batches when writing.
Closes #27483 …
=> [AWS SQS] Support strict expiration of SQS batches when writing

.github/REVIEWERS.yml
=> Remove Pablo from IO reviewers

CHANGES.md
To explicitly call out the future security fixes in Beam Java/Python/Go SDKs, we propose to add the new section (i.e., `Security Fixes`) to the template of CHANGES.md …
=> Added the security section into CHANGES

sdks/python/container/run_validatescontainer.sh
=> Add pytest logging in VC tests.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Bump GCP HCLS API to latest version (07/2023) …
=> Bump GCP HCLS API to latest [07/2023]

.github/workflows/beam_PostCommit_Java_Examples_Dataflow_ARM.yml, .github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml
-Added another step to generate the unique tag as the current timestamp. …
=> Fix the generated unique tag for Java and Python multi-arch containers

build.gradle.kts, sdks/go/test/build.gradle
Bring Dataflow Go PostCommits onto the up to date script pattern, rather than have a special path.
The Java SDK container was missing for the cross language smoke tests, causing them to fail. …
=> Remove legacy path for Go Dataflow post commits.

sdks/java/container/boot.go
Cherry picks fix for #27842 to release branch. Should resolve Arguments Too Long errors for the 2.50 release. 
It's SDK side sibling is already in the branch: https://github.com/apache/beam/pull/27841 …
=> [#27842] Cherry pick using a file for PipelineOptions.

.github/workflows/beam_PostCommit_Java_Examples_Dataflow_ARM.yml, runners/google-cloud-dataflow-java/arm/build.gradle
- Test failed due to missing dependency, added in this PR. …
=> Add required dependency for Github Actions Java ARM Test Suite.

.github/workflows/build_release_candidate.yml
=> Add docker buildx to the release yml file to build multi-arch containers

README.md
This PR:
1) Removes the `Getting Started` section, as it's redundant with the `Learn More` Section.
2) Moves the `Contact Us` section to the end of the file.
3) Removes the links for `Subscribe` and `mail`. The underlying links do not redirect me anywhere, and thus I feel they are not needed. …
=> Refactored ReadMe

sdks/python/pytest.ini
The Kafka Xlang IT tests were seemingly not running because the `uses_io_expansion_service` tag was not defined. This should fix those warnings and enable those tests.  …
=> Fix Pytest Unknown Marker Error for Xlang Kafka IT Test

.github/workflows/build_release_candidate.yml
=> Update build_release_candidate.yml publish_java_artifacts to be self hosted.

sdks/python/apache_beam/io/parquetio.py, sdks/python/apache_beam/runners/dataflow/internal/apiclient.py, sdks/python/apache_beam/runners/portability/requirements_cache_it_test.py, sdks/python/apache_beam/runners/portability/stager.py, sdks/python/apache_beam/tools/microbenchmarks_test.py, sdks/python/build-requirements.txt, sdks/python/setup.py
Replaces most usage of the deprecated pkg_resources module with importlib.resources, importlib.metadata, and packaging packages. All usage of the pkg_resources module cannot be replaced within Beam as there are also a number of dependencies that use it, but this cleans up most of the uses we have. Updating the `gen_protos.py` script is the last non-setup invocation, and that will be done separately.   …
=> Replace deprecated pkg_resources module

sdks/java/transform-service/launcher/build.gradle
This fixes https://github.com/apache/beam/issues/28047. …
=> Adds the error_prone_annotations dependency used by Guava

sdks/python/apache_beam/ml/transforms/base.py
We missed this piece of the update …
=> Fix produce/consume pydoc

website/www/site/content/en/documentation/programming-guide.md
Editorial pass on the new Transform service documentation. …
=> Editorial pass on the new Transform service docs

CHANGES.md
Put newly added item to appropriate version
[![Build …
=> Update CHANGES.md to include 2.51.0 section

examples/java/src/main/java/org/apache/beam/examples/cookbook/BigQueryTornadoes.java, examples/java/src/main/java/org/apache/beam/examples/cookbook/FilterExamples.java, examples/java/src/main/java/org/apache/beam/examples/cookbook/JoinExamples.java, examples/java/src/main/java/org/apache/beam/examples/cookbook/MaxPerKeyExamples.java, examples/java/src/main/java/org/apache/beam/examples/cookbook/MinimalBigQueryTornadoes.java, examples/java/src/main/java/org/apache/beam/examples/snippets/Snippets.java, examples/kotlin/src/main/java/org/apache/beam/examples/kotlin/cookbook/BigQueryTornadoes.kt, examples/kotlin/src/main/java/org/apache/beam/examples/kotlin/cookbook/FilterExamples.kt, examples/kotlin/src/main/java/org/apache/beam/examples/kotlin/cookbook/JoinExamples.kt, examples/kotlin/src/main/java/org/apache/beam/examples/kotlin/cookbook/MaxPerKeyExamples.kt, examples/kotlin/src/main/java/org/apache/beam/examples/kotlin/snippets/Snippets.kt, learning/tour-of-beam/learning-content/io/big-query-io/read-table/description.md, learning/tour-of-beam/learning-content/io/big-query-io/read-table/java-example/Task.java, learning/tour-of-beam/learning-content/io/rest-api/description.md, playground/backend/internal/fs_tool/ExampleData.scala, sdks/go/examples/cookbook/filter/filter.go, sdks/go/examples/cookbook/join/join.go, sdks/go/examples/cookbook/max/max.go, sdks/go/examples/cookbook/tornadoes/tornadoes.go, sdks/java/core/src/main/java/org/apache/beam/sdk/io/package-info.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryClusteringIT.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryTimePartitioningClusteringIT.java, sdks/python/apache_beam/examples/cookbook/bigquery_tornadoes.py, sdks/python/apache_beam/examples/cookbook/filters.py, sdks/python/apache_beam/examples/snippets/snippets.py
Replace clouddataflow-readonly.samples with apache-beam-testing.samples.
Fix #27523 …
=> Use apache-beam-testing.samples

website/www/site/content/en/documentation/io/connectors.md
=> Add CloudBigtableIO to connector list

website/www/site/content/en/documentation/programming-guide.md
Changed the text description for Python's ParDo block to match the code.
Before:
After:  …
=> [Python] Fix python's Beam Programming Guide text block for ParDo

sdks/go/pkg/beam/runners/prism/internal/execute.go
Unblock users from running non-go pipelines against prism if they are single external/loopback environments.
[![Build …
=> [Cherry Pick #28083][prism] support single external env pipelines.

sdks/python/container/Dockerfile
Cherry pick https://github.com/apache/beam/pull/28036 into the 2.50.0 release branch …
=> [Cherry-pick #28036] Add libgeos-dev for ARM components of multi-arch Beam SDK Python containers

sdks/python/tox.ini
=> Cherry pick: Pin hugging face docs (#28106)

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/DicomIOReadIT.java
Because of #20644 , an integration test for DICOM IO was ignored. Filed and linked a new GH issue (#28099), to add working integration tests to this file. …
=> Change GH Issue linked to ignored DICOM IT

sdks/python/apache_beam/ml/inference/base.py
These aren't correctly warning right now. …
=> Fix error condition checking

sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download.go, sdks/go/pkg/beam/core/runtime/xlangx/expansionx/download_test.go, sdks/python/container/boot.go, sdks/python/container/piputil.go, sdks/python/expansion-service-container/boot.go
Use `GetPythonVersion` utility to find the available python command to use. If `PYTHON_PATH` is set then it uses that.
Fixes #26958  …
=> [Python] Get available python version and use it for Python SDK harness boot entry point 

sdks/python/apache_beam/examples/inference/huggingface_language_modeling.py, sdks/python/apache_beam/examples/inference/pytorch_language_modeling.py, sdks/python/apache_beam/examples/inference/sklearn_mnist_classification.py, sdks/python/apache_beam/examples/inference/tensorflow_mnist_classification.py, sdks/python/apache_beam/examples/inference/xgboost_iris_classification.py, sdks/python/apache_beam/ml/inference/huggingface_inference_it_test.py, sdks/python/apache_beam/ml/inference/pytorch_inference_it_test.py, sdks/python/apache_beam/ml/inference/sklearn_inference_it_test.py, sdks/python/apache_beam/ml/inference/tensorflow_inference_it_test.py, sdks/python/apache_beam/ml/inference/xgboost_inference_it_test.py
In my per-key model handler work I've found some issues with the large model setting on a per-framework basis. This adds some IT tests for each framework. …
=> Add integration tests to exercise large model on different frameworks

examples/notebooks/beam-ml/run_inference_tensorflow.ipynb
Ensures use of new package versions by automatically restarting the Python runtime after installation. Follows the pattern in https://github.com/apache/beam/blob/master/examples/notebooks/beam-ml/run_inference_multi_model.ipynb …
=> Update TF notebook example to auto-restart the runtime after dependency installation

.github/workflows/build_release_candidate.yml
Right now, we're repeatedly running out of disk space when trying to publish docker images. This should free up ~30 GB for us to use.
https://issues.apache.org/jira/browse/INFRA-24918 requests that infra allow list this action …
=> Free disk space before running build_release_candidate

.github/gh-actions-self-hosted-runners/arc/environments/beam.env
Adds a high memory runner for workflows. 
To use it add `highmem` to runs-on array.
Changes tested and applied on infra …
=> adding highmem runner to ARC

website/www/site/layouts/shortcodes/documentation/sdks.html
=> add bullet points to SDK list on home page (resolves #22307)

sdks/python/apache_beam/io/gcp/bigquery.py, sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py, sdks/python/apache_beam/io/gcp/bigquery_schema_tools.py, sdks/python/apache_beam/io/gcp/bigquery_schema_tools_test.py
Fixes https://github.com/apache/beam/issues/28152. …
=> Fix Bigquery read when selected_fields is used with beam rows output.

website/www/site/content/en/contribute/ptransform-style-guide.md
Adds PTransform Design doc to the public Beam website. …
=> Add PTransform Design Doc to website

sdks/typescript/package-lock.json, sdks/typescript/package.json
Was running into the same error as this question, which was resolved in the same fashion: updating to ttypescript 1.5.15
https://stackoverflow.com/questions/76951014/yarn-run-build-dist-typeerror-cannot-set-property-constructor-of-object-obje …
=> Update ttypescript version.

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/debug/OutputSampler.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/debug/OutputSamplerTest.java
Code incorrectly does not synchronize the "exceptions" member. Fix is a synchronized swap with a new list.
[![Build …
=> Fix ConcurrentModificationException in OutputSampler

sdks/python/apache_beam/ml/transforms/tft.py, sdks/python/apache_beam/ml/transforms/tft_test.py
=> Add BagOfWords to tft data transforms

.test-infra/jenkins/metrics_report/tox.ini
This is causing https://ci-beam.apache.org/job/beam_Metrics_Report/159/console to fail with error: `failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'WORKSPACE INFLUXDB_USER INFLUXDB_USER_PASSWORD'`
This has been enforced since https://github.com/tox-dev/tox/issues/2658 …
=> Use commas in passenv

sdks/python/apache_beam/ml/transforms/tft.py, sdks/python/apache_beam/ml/transforms/tft_test.py
=> Add word count to BagOfWords

sdks/python/apache_beam/examples/inference/pytorch_model_per_key_image_segmentation.py, sdks/python/apache_beam/ml/inference/base.py, sdks/python/apache_beam/ml/inference/base_test.py
There was consensus around this being a better name …
=> Update KeyMhMapping to KeyModelMapping

CHANGES.md, website/www/site/config.toml, website/www/site/content/en/blog/beam-2.50.0.md, website/www/site/content/en/get-started/downloads.md
TODO, update with final release dates.
Add 2.50.0 release blog.
Update CHANGES.md with 2.50.0 final release date.
Update latest beam version to 2.50.0.
Add 2.50.0 to downloads section, and move 2.49.0 to archive links. …
=> Doc updates for 2.50.0 release

sdks/java/expansion-service/container/build.gradle, sdks/java/transform-service/controller-container/build.gradle, sdks/python/expansion-service-container/build.gradle
- fix https://github.com/apache/beam/issues/28214
- Multi-arch images are pushed during build so dockerPush will fail since there are no longer local copies of the containers. …
=> Change calls to dockerPush to docker for multi-arch containers

sdks/go/test/integration/integration.go
=> Add github issue link to TODO

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteTest.java
Fixes https://github.com/apache/beam/issues/28092 …
=> SpannerIO: retry if concurrent transaction is aborted by emulator

.test-infra/metrics/build.gradle
Adds --namespace to all kubectl calls in metrics/build.gradle
This is due namespace in runners defaulting to arc instead of default.  …
=> adding --namespace to beam metrics gradle build

.github/workflows/beam_PostCommit_BeamMetrics_Publish.yml
Adds step to configure docker credential helper …
=> added call to gcloud to setup the docker credential helper

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcDeadlineClientInterceptor.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServerTest.java
remove sync stub for non appliance jobs.  this is no longer supported
r: @scwhittle  …
=> remove sync stub list from GrpcWindmillServer

runners/samza/src/main/java/org/apache/beam/runners/samza/TestSamzaRunner.java
Previous TestSamzaRunner uses a single tmp folder for test runs. This leads to problem when multiple tests are running in parallel. Update the logic to generate tmp folder for each run. …
=> Generate separate tmp folder for TestSamzaRunner state store

website/www/site/content/en/documentation/runtime/environments.md
Its best to avoid latest/mutable tags for reproducible runs and to avoid container skew across the life of a pipeline …
=> Add guidance on container versioning

sdks/go/pkg/beam/x/debug/head_test.go
Using the direct runner to avoid a flake in the logging here.
A more substantial fix would be better allowing pipeline execution to capture logging service output for a given pipeline run. However, that's way out of scope for now. …
=> [Go] Use direct runner to avoid  logging flake.

CHANGES.md
Mention https://github.com/apache/beam/issues/28246 in the notes.
=> Reference the memory leak in CHANGES.md

sdks/python/apache_beam/testing/analyzers/perf_analysis_test.py, sdks/python/apache_beam/testing/analyzers/perf_analysis_utils.py, sdks/python/apache_beam/testing/analyzers/tests_config.yaml
Fixes: https://github.com/apache/beam/issues/28223 …
=> Add relative median threshold filtering to perf alert tool

examples/notebooks/beam-ml/speech_emotion_tensorflow.ipynb
Added a notebook demonstrating the use of Beam in audio processing. It achieves the following:
* Imports and processes the CREMA-D dataset for speech emotion analysis.
* Perform various data augmentation and feature extraction techniques using the Librosalibrary.
* Develops a TensorFlow model to classify emotions.
* Stores the trained model.
* Constructs a Beam pipeline that:
* Creates a PCollection of audio samples.
* Applies preprocessing transforms.
* Utilizes the trained model to predict emotions.
* Stores the emotion predictions. …
=> Add Speech Emotion Recognition TensorFlow Notebook

examples/notebooks/beam-ml/nlp_tensorflow_streaming.ipynb
=> Fix a couple notebook typos

.github/workflows/beam_Release_Python_NightlySnapshot.yml, sdks/python/scripts/run_snapshot_publish.sh
- Removes link step from workflow
- removes `src/` from paths, which is jenkins specific …
=> remove src from path and remove link step for src

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Bump HCLS API to latest version  …
=> Bump HCLS API [08/2023]

sdks/python/apache_beam/io/iobase.py, sdks/python/apache_beam/runners/render.py, sdks/python/apache_beam/runners/render_test.py
* Error message rather than silence when no rendering requested.
* Fix render_leaf_composite_nodes to act on names rather than ids.
* Allow rendering of raw .dot files when graphviz is not installed. …
=> Various render runner improvements.

sdks/python/apache_beam/transforms/util.py, sdks/python/apache_beam/transforms/util_test.py
beam.LogElements by default prints to stdout, and such logs are not visible when running jobs on Dataflow.
With this change users can route the messages to via logging and customize the logging severity. …
=> Allow customizing log level in beam.LogElements

CHANGES.md
=> Add per key models to changes.md

sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_unit_test.py
=> Better error messages on missing or malformed yaml providers.

sdks/java/testing/tpcds/build.gradle
Disable AQE with Spark 3.2 in TPCDS benchmarks to reduce overhead for complex queries 
(closes #28249) …
=> [Spark, TPCDS] Disable AQE with Spark 3.2 in TPCDS benchmarks to reduce overhead for complex queries 

sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform_test.py
This will give us a schema'd Create which will work better with other transforms and cross-language. …
=> Interpret yaml mapping elements as rows.

CHANGES.md, sdks/python/apache_beam/ml/inference/vertex_ai_inference.py
We need to override this to support inference args since https://github.com/apache/beam/blob/eee81113b8bb63a428fe6f579e8914c26d8afbe5/sdks/python/apache_beam/ml/inference/base.py#L218 throws otherwise when you pass in inference args. We do try to use this and I was able to pass it through correctly in a test pipeline - https://github.com/apache/beam/blob/eee81113b8bb63a428fe6f579e8914c26d8afbe5/sdks/python/apache_beam/ml/inference/vertex_ai_inference.py#L192
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers …
=> Allow users to pass inference args into vertex ai model handler

sdks/python/.pylintrc, sdks/python/apache_beam/options/pipeline_options.py
Enables the `use-implicit-booleaness-not-comparison` pylint check that was disabled when pylint was bumped to 2.17.5
Fixes #28244  …
=> Enable use-implicit-booleaness-not-comparison check

sdks/python/container/boot.go
Uses the buffered logger to capture SDK worker process logs that aren't reported to the logging service, specifically capturing crash logs and logging them at error back to the logging service specifically.  …
=> Direct Python SDK worker crash logs through Logging API

sdks/python/apache_beam/examples/inference/README.md
This will allow people to find and run these examples. …
=> Add descriptions for the 2 vertex examples

sdks/python/apache_beam/typehints/schemas.py, sdks/python/apache_beam/typehints/schemas_test.py, sdks/python/apache_beam/typehints/typehints.py, sdks/python/apache_beam/yaml/pipeline.schema.yaml, sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_errors.md, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_transform.py
Also improves type inference a bit for a smoother experience here. …
=> Add some documentation on yaml error handling.

sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_scope_test.py, sdks/python/apache_beam/yaml/yaml_transform_unit_test.py
Beam now considers the possible providers of consuming transforms. There is still room for improvement, but this should be a decent general heuristic. …
=> Informed choice of yaml provider for root transforms.

sdks/python/apache_beam/runners/worker/data_sampler.py
Previously sampled every 30s, now samples every 0.5s for the first 30s. After which it samples at every 30s again. …
=> Update Python data sampling algorithm

CHANGES.md, website/www/site/content/en/blog/beam-2.50.0.md
These will get automatically picked up when we pick up the new `python:3.XX-bullseye` images which have upgraded their debian versions already (for example https://hub.docker.com/layers/library/python/3.9-bullseye/images/sha256-d7e28b2648cb4611a94f068d92a236e7faaf6edb7589e01c09c1c16035c26d0a?context=explore has debian/aom 1.0.0.errata1-3+deb11u1 which has the fix). I confirmed that all 4 versions 3.<8, 9, 10, and 11> have the fix.
To check the …
=> Call out fixed security vulnerabilities

website/www/site/content/en/contribute/release-guide.md
Fix a typo, and make some of the instructions more explicit. …
=> Fix typos, and clarify playground deploy.

sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
Addresses remaining concerns from #28318. …
=> Bump orjson version

.github/workflows/beam_PreCommit_Whitespace.yml
Right now, this only triggers on md/gradle changes in the base directory, this fixes the problem.
Example PR where the triggers didn't fire but should've - https://github.com/apache/beam/pull/28315 …
=> Fix whitespace triggers

.github/workflows/go_tests.yml
Adds a [govulncheck](https://pkg.go.dev/golang.org/x/vuln@v1.0.1/cmd/govulncheck) step to the Go Tests workflow to add an extra check against known vulnerabilities. Also allows us to manually trigger the workflow …
=> Add govulncheck to Go Tests workflow

sdks/java/build-tools/src/main/resources/beam/checkstyle/suppressions.xml
=> Exclude source-overrides from checkStyle javadocPackage

.github/workflows/go_tests.yml
This reverts commit 846a1ab64164c6326fd550e2d86f6a0adbf64b66.
The workflow has been getting cancelled since it was merged, reverting to unblock development  …
=> Revert "Add govulncheck to Go Tests workflow (#28226)"

examples/notebooks/beam-ml/README.md, examples/notebooks/beam-ml/run_inference_huggingface.ipynb
Adds a notebook with 2 examples of using Hugging Face model handlers.
[Notebook](https://github.com/riteshghorse/beam/blob/hf-notebook/examples/notebooks/beam-ml/run_inference_huggingface.ipynb) …
=> Add notebook for RunInference with Hugging Face 

sdks/python/apache_beam/yaml/cache_provider_artifacts.py, sdks/python/apache_beam/yaml/yaml_provider.py
This should be run during template docker image creation and will greatly increase yaml template startup.
[![Build …
=> Add script to cache provider artifacts for faster startup.

sdks/python/apache_beam/runners/dataflow/internal/names.py
=> Update Dataflow container used by dev SDKs

sdks/python/apache_beam/utils/python_callable.py, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_udf_test.py, sdks/python/container/license_scripts/dep_urls_py.yaml, sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
This PR adds preliminary UDF support to YAML mapping transforms (namely `MapToFields` and `Filter`). There are also a series of simple tests to ensure the basic function is working.
A future PR will be opened for more extensive UDF tests as well as documentation on how to specify the various types of UDF's.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/b …
=> [yaml] Add UDF support to mapping transforms

sdks/java/transform-service/launcher/src/main/java/org/apache/beam/sdk/transformservice/launcher/TransformServiceLauncher.java, sdks/python/apache_beam/utils/transform_service_launcher.py
=> Increase transform service timeout

.github/workflows/README.md
This will be useful to most folks and was requested here - https://lists.apache.org/thread/43z0yo7lvsxr3g4ccmrw2nq8xks6vbj1 …
=> Add instructions on manually running jobs

.github/workflows/beam_PreCommit_Website_Stage_GCS.yml
This is running correctly here - https://github.com/apache/beam/actions/runs/6190313697/job/16806300291 …
=> Consolidate env blocks for stage website precommit

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/debug/DataSampler.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/debug/OutputSampler.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/debug/DataSamplerTest.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/debug/OutputSamplerTest.java
Automatic exception samplingThis enables exception sampling when either the "enable_data_sampling" or "enable_always_on_exception_sampling" experiment is present. This disables automatic exception sampling when "disable_always_on_exception_sampling" is given.  …
=> Add flag to control automatic exception sampling in Java (disabled)

sdks/python/apache_beam/yaml/yaml_io.py
We should be explicit about which IOs we support and their signatures, and ensure they act on schema'd PCollections. …
=> Remove implicitly defined IOs.

sdks/go/pkg/beam/beam.shims.go, sdks/go/pkg/beam/create.go, sdks/go/pkg/beam/util.go
The additional registrations were causing log spam for *all* Go SDK pipelines. This removes the code gen registrations for createFn, and the redundant init block for the generic registrations. …
=> Remove extra registrations for createFn.

.github/workflows/beam_PostCommit_Java_Examples_Dataflow_V2.yml, .github/workflows/beam_PostCommit_Java_Examples_Dataflow_V2_Java.yml
The following jenkins jobs have been migrated:
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_Examples_Dataflow_V2/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_Examples_Dataflow_V2_java11/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_Examples_Dataflow_V2_java17/
How has it been tested?
by adding a comment to the PR
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTI …
=> Add GitHub Workflow Replacement for Jenkins job_PostCommit_Java_Examples_Dataflow_V2

.github/workflows/beam_PreCommit_GoPrism.yml, sdks/go/test/run_validatesrunner_tests.sh
In the action context, it's unable to build prism since it's just outside beam's go.mod file. Changing into the sdks directory should resolve this.
https://github.com/apache/beam/actions/runs/6227148815/job/16901190193 run where it got past the previous break. …
=> Fix building prism in action.

sdks/go/pkg/beam/io/databaseio/writer.go, sdks/go/pkg/beam/io/databaseio/writer_test.go
Includes pgx in the Postgres value template generation case when writing to a table. Fixes #28520. …
=> [Go SDK]: Support writes to Postgres with pgx driver

sdks/java/io/google-ads/build.gradle
=> Update build.gradle -- remove duplicate deps

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/BeamFnControlClient.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ExecutionStateSampler.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingMDC.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ExecutionStateSamplerTest.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistryTest.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java
This is implemented with a new state variable in the state sampler to only log uncaught exceptions from user code once per bundle. Also includes a small cleanup to get the transform id to make it more testable. …
=> Log user code exceptions in Java

sdks/python/apache_beam/runners/common.py, sdks/python/apache_beam/runners/worker/log_handler_test.py
Adds a log statement to emit uncaught exceptions from user code in Python. Adds a test in log_handler_test for this. It's long but only because it sets up a BundleProcessor to test the log statement with a real FnApiLogRecordHandler. …
=> Log user code exceptions in Python

sdks/python/apache_beam/ml/inference/huggingface_inference.py
Adds a note to use `model_id` string instead of an actual model when using `HuggingFacePipelineModelHandler`. Also, adds the latest pipeline task to enum. …
=> Update HuggingFace api doc and add text2audio pipeline task

sdks/go/pkg/beam/runners/prism/internal/web/assets/style.css, sdks/go/pkg/beam/runners/prism/internal/web/debugz.go, sdks/go/pkg/beam/runners/prism/internal/web/debugz.html, sdks/go/pkg/beam/runners/prism/internal/web/index.html
Some usability fixes for the prism debugz page.
* Use humanize and time to improve display of Bytes, durations, and other numbers in the debugz page.
* Move descriptions to hover tooltips & remove the extra column.
* Fix debugz table header to represent their contents.
* Due to the goroutine and build info being in the same table, it's still very wide. Those will be split into another table in a later improvement round.
* Fix footer on index page so that it's always at the bottom, of either the screen or beneath the job table.
No screenshot available. …
=> [prism] Improve prism debugz page.

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/IOLoadTestBase.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/LoadTestBase.java
=> Make launcher method public in Load test base classes.

sdks/go/pkg/beam/runners/prism/internal/environments.go
Just noticed this needs to be set to have the desired behavior of not leaving a mess around. …
=> [prism] Auto remove containers after stop.

.github/workflows/beam_PerformanceTests_BiqQueryIO_Read_Python.yml, .github/workflows/beam_PerformanceTests_BiqQueryIO_Write_Python_Batch.yml, .github/workflows/performance-tests-job-configs/config_PerformanceTests_BiqQueryIO_Read_Python.txt, .github/workflows/performance-tests-job-configs/config_PerformanceTests_BiqQueryIO_Write_Python.txt
".github/workflows/beam_PerformanceTests_BiqQueryIO_Read_Python.yml"
".github/workflows/beam_PerformanceTests_BiqQueryIO_Write_Python_Batch.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_BiqQueryIO_Read_Python/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_BiqQueryIO_Write_Python_Batch/
Example runs:
beam_PerformanceTests_BiqQueryIO_Read_Python https://github.com/aleksandr-dudko/beam/actions/runs/6222973853
beam_PerformanceTests_BiqQueryIO_Write_Python_Batch https://github.com/aleksandr-dudko/beam/actions/runs/6222972109 …
=> Add GitHub Workflow Replacements for job_PerformanceTests_BiqQueryIO_Read_Python and job_PerformanceTests_BiqQueryIO_Write_Python_Batch

.github/workflows/beam_LoadTests_Go_Combine_Dataflow_Batch.yml, .github/workflows/load-tests-job-configs/config_Combine_Go_Batch_10b.txt, .github/workflows/load-tests-job-configs/config_Combine_Go_Batch_Fanout_4.txt, .github/workflows/load-tests-job-configs/config_Combine_Go_Batch_Fanout_8.txt
https://ci-beam.apache.org/job/beam_LoadTests_Go_Combine_Dataflow_Batch
https://ci-beam.apache.org/job/beam_LoadTests_Go_Combine_Dataflow_Batch_PR …
=> Add Load Tests Combine Dataflow Batch Go workflow

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerUtils.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerTest.java
Fix breakage caused by #28541 while trying to fix checkStyle error
Replicates https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1066 …
=> Fix sync it framework BigtableResourceManager

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerUtils.java, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerTest.java
Cherry pick #28588 into release branch …
=> [Release-2.51.0] Cherry pick #28588: Fix sync it framework BigtableResourceManager

.test-infra/metrics/sync/github/sync_workflows.py
http://metrics.beam.apache.org/d/CTYdoxP4z/ga-pos…
Also exclude cancelled runs since many runs will fall into that category. Did limited testing since the dashboard is currently useless anyways, and prod testing is probably easier. May require a few iterations here. …
=> Add all GHA runs to dashboard

sdks/java/io/hadoop-file-system/src/main/java/org/apache/beam/sdk/io/hdfs/HadoopFileSystemRegistrar.java
=> Add viewfs to HA_SCHEMES to support ViewFs file system

contributor-docs/java-dependency-upgrades.md
This was at https://cwiki.apache.org/confluence/display/BEAM/Dependency+Upgrades and is included as a floating GitHub Issue in the release guide …
=> Move java dependency upgrades from wiki to contributor-docs

website/www/site/content/en/contribute/_index.md
=> Fix broken release guide link

contributor-docs/release-guide.md
These were in a floating issue. Just getting them right into the release guide to have a single document.
[![Build …
=> Move instructions for upgrading Go version to release guide

.github/workflows/beam_LoadTests_Go_SideInput_Dataflow_Batch.yml, .github/workflows/load-tests-job-configs/config_SideInput_Go_Batch_Dataflow_First_Iterable.txt, .github/workflows/load-tests-job-configs/config_SideInput_Go_Batch_Dataflow_Iterable.txt
https://ci-beam.apache.org/job/beam_LoadTests_Go_SideInput_Dataflow_Batch
https://ci-beam.apache.org/job/beam_LoadTests_Go_SideInput_Dataflow_Batch_PR …
=> Add Load Tests SideInput Dataflow Batch Go workflow

.github/workflows/beam_LoadTests_Go_CoGBK_Dataflow_Batch.yml, .github/workflows/load-tests-job-configs/config_CoGBK_Go_Batch_MultipleKey.txt, .github/workflows/load-tests-job-configs/config_CoGBK_Go_Batch_Reiteration_10KB.txt, .github/workflows/load-tests-job-configs/config_CoGBK_Go_Batch_Reiteration_2MB.txt, .github/workflows/load-tests-job-configs/config_CoGBK_Go_Batch_SingleKey.txt
https://ci-beam.apache.org/job/beam_LoadTests_Go_CoGBK_Dataflow_batch
https://ci-beam.apache.org/job/beam_LoadTests_Go_CoGBK_Dataflow_batch_PR
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github …
=> Add Load Tests CoGBK Dataflow Batch Go workflow

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/failing_test.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/task.yml, .github/issue-rules.yml
Add a YAML SDK component to the issue templates so that the yaml label can be automatically assigned to new bugs/features. …
=> [yaml] add YAML SDK component to issue template

sdks/java/io/hadoop-common/src/main/java/org/apache/beam/sdk/io/hadoop/SerializableConfiguration.java
=> Make SerializableConfiguration cacheable

.test-infra/jenkins/job_PostCommit_Python_CrossLanguage_Gcp_Dataflow.groovy, .test-infra/jenkins/job_PostCommit_Python_CrossLanguage_Gcp_Direct.groovy, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java, sdks/python/apache_beam/io/external/xlang_bigqueryio_it_test.py, sdks/python/apache_beam/io/gcp/bigquery.py, website/www/site/content/en/documentation/io/built-in/google-bigquery.md
Cherry picking PR #28618 into 2.51.0
=> Cherry picking PR #28618 into 2.51.0 (setting numShards for Python BigQuery xlang)

sdks/python/apache_beam/runners/dataflow/internal/names.py
=> Bump Python FnAPI beam-master container.

.github/workflows/beam_PerformanceTests_Cdap.yml, .github/workflows/beam_PerformanceTests_HadoopFormat.yml, .github/workflows/beam_PerformanceTests_MongoDBIO_IT.yml, .github/workflows/beam_PerformanceTests_PubsubIOIT_Python_Streaming.yml, .github/workflows/beam_PerformanceTests_SparkReceiver_IO.yml, .github/workflows/beam_PerformanceTests_TFRecordIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_WordCountIT_PythonVersions.yml, .github/workflows/performance-tests-job-configs/TFRecordIOIT_HDFS.txt, .github/workflows/performance-tests-job-configs/cdap.txt, .github/workflows/performance-tests-job-configs/hadoopFormat.txt, .github/workflows/performance-tests-job-configs/mongoDBIO_IT.txt, .github/workflows/performance-tests-job-configs/pubsubIOIT_Python_Streaming.txt, .github/workflows/performance-tests-job-configs/sparkReceiver_IO.txt, .github/workflows/performance-tests-job-configs/wordCountIT_Python.txt
The following jenkins jobs have been migrated:
- https://ci-beam.apache.org/job/beam_PerformanceTests_Cdap/
- https://ci-beam.apache.org/job/beam_PerformanceTests_HadoopFormat/
- https://ci-beam.apache.org/job/beam_PerformanceTests_MongoDBIO_IT/
- https://ci-beam.apache.org/job/beam_PerformanceTests_PubsubIOIT_Python_Streaming/
- https://ci-beam.apache.org/job/beam_PerformanceTests_SparkReceiver_IO/
- https://ci-beam.apache.org/job/beam_PerformanceTests_WordCountIT_Py38/
- beam_PerformanceTests_TFRecordIOIT_HDFS (removed in Jenkins)
The jobs have been tested on Self-hosted GKE runners ubuntu 20.04.
- by manually running the job (`workflow_dispatch`) …
=> Migrate Jenkins jobs to GitHub Actions

.github/workflows/beam_LoadTests_Java_Combine_Dataflow_Batch.yml, .github/workflows/load-tests-job-configs/config_Combine_Java_Dataflow_Batch_10b.txt, .github/workflows/load-tests-job-configs/config_Combine_Java_Dataflow_Batch_Fanout_4.txt, .github/workflows/load-tests-job-configs/config_Combine_Java_Dataflow_Batch_Fanout_8.txt
https://ci-beam.apache.org/job/beam_LoadTests_Java_Combine_Dataflow_Batch
https://ci-beam.apache.org/job/beam_LoadTests_Java_Combine_Dataflow_Batch_PR …
=> Add Load Tests Combine Dataflow Batch Java workflow

.github/workflows/beam_PerformanceTests_SQLBigQueryIO_Batch_Java.yml, .github/workflows/beam_PerformanceTests_SpannerIO_Read_2GB_Python.yml, .github/workflows/beam_PerformanceTests_SpannerIO_Write_2GB_Python_Batch.yml, .github/workflows/performance-tests-job-configs/SQLBigQueryIO_Batch_Java.txt, .github/workflows/performance-tests-job-configs/spannerIO_Read_2GB_Python.txt, .github/workflows/performance-tests-job-configs/spannerIO_Write_2GB_Python.txt
".github/workflows/beam_PerformanceTests_SpannerIO_Read_2GB_Python.yml"
".github/workflows/beam_PerformanceTests_SpannerIO_Write_2GB_Python_Batch.yml"
".github/workflows/beam_PerformanceTests_SQLBigQueryIO_Batch_Java.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_SpannerIO_Read_2GB_Python/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_SpannerIO_Write_2GB_Python_Batch/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_SQLBigQueryIO_Batch_Java/
Example runs:
**beam_PerformanceTests_SpannerIO_Read_2GB_Python** https://github.com/aleksandr-dudko/beam/actions/runs/6267220982 …
=> Add GitHub Workflow Replacements for Jenkins job_PerformanceTests_SpannerIO and job_PerformanceTests_SQLBigQueryIO_Batch_Java

.github/workflows/beam_PerformanceTests_BiqQueryIO_Read_Python.yml, .github/workflows/beam_PerformanceTests_BiqQueryIO_Write_Python_Batch.yml, .github/workflows/beam_PerformanceTests_JDBC.yml, .github/workflows/performance-tests-job-configs/JDBC.txt, .github/workflows/performance-tests-job-configs/biqQueryIO_Read_Python.txt, .github/workflows/performance-tests-job-configs/biqQueryIO_Write_Python_Batch.txt
".github/workflows/beam_PerformanceTests_JDBC"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_JDBC/
Example runs:
beam_PerformanceTests_JDBC https://github.com/aleksandr-dudko/beam/actions/runs/6266173351 …
=> Add GitHub Workflow Replacements for Jenkins job_PerformanceTests_JDBC

.github/workflows/beam_PerformanceTests_Kafka_IO.yml, .github/workflows/performance-tests-job-configs/kafka_IO_Batch.txt, .github/workflows/performance-tests-job-configs/kafka_IO_Streaming.txt
PR migrates Jenkins Job to Github Actions Workflow:
".github/workflows/beam_PerformanceTests_Kafka_IO.yml"
Jenkins Job:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_Kafka_IO/
Example runs:
beam_PerformanceTests_Kafka_IO https://github.com/aleksandr-dudko/beam/actions/runs/6325066954 …
=> Add GitHub Workflow Replacements for Jenkins job_PerformanceTests_Kafka_IO

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Released a long time ago: https://github.com/google/flogger/releases/tag/flogger-0.7.4 / https://github.com/google/flogger/compare/flogger-0.7.3...flogger-0.7.4
Also aligned with version from hadoop-connectors/gcsio: https://github.com/GoogleCloudDataproc/hadoop-connectors/blame/757c0853720a6ff4216d706063ca3ab44a9588ba/pom.xml#L94 …
=> Update flogger-system-backend to 0.7.4

.github/workflows/beam_PerformanceTests_TextIOIT.yml, .github/workflows/beam_PerformanceTests_TextIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_TextIOIT_Python.yml, .github/workflows/performance-tests-job-configs/textIOIT.txt, .github/workflows/performance-tests-job-configs/textIOIT_HDFS.txt, .github/workflows/performance-tests-job-configs/textIOIT_Python.txt
".github/workflows/beam_PerformanceTests_TextIOIT.yml"
".github/workflows/beam_PerformanceTests_TextIOIT_HDFS.yml"
".github/workflows/beam_PerformanceTests_TextIOIT_Python.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_TextIOIT/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_TextIOIT_HDFS/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_TextIOIT_Python/
Example runs:
**beam_PerformanceTests_TextIOIT** https://github.com/aleksandr-dudko/beam/actions/runs/6259152115
**beam_PerformanceTests_TextIOIT_HDFS** https://github.com/aleksandr-dudko/beam/actions/runs/6261298366 …
=> Add GitHub Workflow Replacements for Jenkins job_PerformanceTests_TextIOIT

.github/workflows/beam_LoadTests_Go_ParDo_Flink_Batch.yml, .github/workflows/load-tests-job-configs/go_ParDo_Flink_Batch_100_counters.txt, .github/workflows/load-tests-job-configs/go_ParDo_Flink_Batch_10_counters.txt, .github/workflows/load-tests-job-configs/go_ParDo_Flink_Batch_10_times.txt, .github/workflows/load-tests-job-configs/go_ParDo_Flink_Batch_200_times.txt
https://ci-beam.apache.org/job/beam_LoadTests_Go_ParDo_Flink_Batch
https://ci-beam.apache.org/job/beam_LoadTests_Go_ParDo_Flink_Batch_PR
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/a …
=> Add LoadTests Go ParDo Flink Batch workflow

.github/workflows/beam_PostCommit_Java_SingleStoreIO_IT.yml, .test-infra/kubernetes/singlestore/sdb-operator.yaml
Migrate beam_PostCommit_Java_SingleStoreIO_IT
Job is failing in Jenkins due to singlestore version issue which is fixed here however test is still failing and will look into it later …
=> postcommit java singlestoreIO_IO

sdks/java/io/google-ads/src/main/java/org/apache/beam/sdk/io/googleads/GoogleAdsV14.java
The public access modifiers on GoogleAdsV14.SimpleRateLimitPolicy were omitted, but are required for external use.
Impact of this bug is mostly a nuisance to users since the class is visible, but instance construction is not possible.
Copying and pasting the policy definition works (e.g. https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/359/files#diff-ce3226be2f184d35619a87b3efbd9262f1807645c6b8d3cd7288c430380aeaf1), but that's not the user experience I intended for it.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTI …
=> Add missing access modifiers to SimpleRateLimitPolicy

sdks/python/container/piputil.go
Wraps the existing returned error with more context + a link to the new documentation introduced in #28702 for an explanation of what an "unrecoverable" error is.  …
=> Add callout of PIP failures as unrecoverable, link to new documentation

.github/workflows/build_release_candidate.yml
This tag seems to have been removed - https://github.com/jlumbroso/free-disk-space/tags …
=> Fix dockerhub task

sdks/python/apache_beam/yaml/yaml_provider.py
=> Fix input detection.

.github/autolabeler.yml
=> yaml label

sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/SqlTransformRunner.java
Quick fix to make it working with trailing delimiters  …
=> TPC-DS: Fix CSV format

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GceMetadataUtil.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOMetadata.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
* Add new functions to retrieve job name and work id from GCE metadata
* Concatenate job name, job id and worker id with ":". …
=> Add job name and worker id to traceId of AppendRowsRequest.

.github/workflows/beam_PreCommit_CommunityMetrics.yml, .test-infra/metrics/build.gradle, buildSrc/build.gradle.kts
This reverts commit 544745ca72868d3e385654a6cfaff444c012d00b.
track issue regarding why it's breaking: #28829 …
=> Revert "Bump com.avast.gradle:gradle-docker-compose-plugin (#28465)"

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOMetadata.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
Introduced in #28729 due to _all_ GHA was not triggered on that PR
thankfully we also have push event for precommit, and it shows this is the only broken presubmit, so forward fix should be fine
GitHub …
=> Fix spotless on master

sdks/python/test-suites/tox/py38/build.gradle
Fixes https://github.com/apache/beam/pull/28756#issuecomment-1748738691
- exclude intermediate build directory. Specifically /beam/build/ …
=> Fix whitespace precommit after gradle 8

.github/REVIEWERS.yml, .github/autolabeler.yml
Adding reviewers from Bigtable team
=> Add Bigtable connector reviewers

.github/workflows/beam_Publish_Docker_Snapshots.yml
https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/ …
=> Add Publish Docker Snapshots workflow

.github/workflows/beam_LoadTests_Python_Combine_Flink_Batch.yml, .github/workflows/beam_LoadTests_Python_Combine_Flink_Streaming.yml, .github/workflows/load-tests-job-configs/python_Combine_Flink_Batch_2GB_10_byte_records.txt, .github/workflows/load-tests-job-configs/python_Combine_Flink_Batch_2GB_Fanout_4.txt, .github/workflows/load-tests-job-configs/python_Combine_Flink_Batch_2GB_Fanout_8.txt, .github/workflows/load-tests-job-configs/python_Combine_Flink_Streaming_2GB_10_byte_records.txt, .github/workflows/load-tests-job-configs/python_Combine_Flink_Streaming_2GB_Fanout_4.txt, .github/workflows/load-tests-job-configs/python_Combine_Flink_Streaming_2GB_Fanout_8.txt
".github/workflows/beam_LoadTests_Python_Combine_Flink_Batch.yml"
".github/workflows/beam_LoadTests_Python_Combine_Flink_Streaming.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_Combine_Flink_Batch/
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_Combine_Flink_Streaming/
Example runs:
beam_LoadTests_Python_Combine_Flink_Batch.yml https://github.com/magicgoody/beam/actions/runs/6402007031
beam_LoadTests_Python_Combine_Flink_Streaming.yml https://github.com/magicgoody/beam/actions/runs/6415766336
The workflow is not working since June.
Thank you for your contribution! Follow this checklist …
=> Github Workflow Replacement for Jenkins Jobs, beam_LoadTests_Python_Combine_Flink_*

.github/workflows/beam_CleanUpDataprocResources.yml
https://ci-beam.apache.org/job/Cleanup%20Dataproc%20Resources/ …
=> Add Cleanup Dataproc Resources workflow

.github/workflows/beam_IODatastoresCredentialsRotation.yml, .github/workflows/beam_MetricsCredentialsRotation.yml
https://ci-beam.apache.org/job/Rotate%20IO-Datastores%20Cluster%20Credentials/
https://ci-beam.apache.org/job/Rotate%20Metrics%20Cluster%20Credentials/ …
=> Add rotate credentials workflows

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
https://ci-beam.apache.org/job/beam_Publish_Beam_SDK_Snapshots/ …
=> Add Publish Beam SDK Snapshots workflow

.github/workflows/beam_Java_JMH.yml, .github/workflows/beam_Java_Jmh.yml
https://ci-beam.apache.org/job/beam_Java_JMH/ …
=> Add Java JMH workflow

contributor-docs/release-guide.md
This updates the release guide in a couple of major ways:
- Fixes the process, which incorrectly combined the process of cutting the release branch with building an RC
- Clarifies what is done by GitHub Actions and what is done by scripts
- Eliminates some of the excessive verbosity about how to do things that script do (just read the script)
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_ST …
=> Update release guide somewhat according to 2.51.0 release experience

.github/workflows/beam_PostCommit_Python.yml, release/src/main/scripts/github_actions_jobs.txt, release/src/main/scripts/mass_comment.py
=> Add GitHub Action workflows to mass_commit

sdks/python/apache_beam/testing/analyzers/perf_analysis.py
=> Add keyword arg to func call for perf alert tool

.github/workflows/beam_PostCommit_Python.yml, release/src/main/scripts/github_actions_jobs.txt, release/src/main/scripts/mass_comment.py
This has no impact on the release build but will make the release branch internally consistent and able to run this script. (The scripts do not need to be run from the release branch, this is just a nice-to-have) …
=> Cherry-pick #28665 to 2.51.0 release branch: Add GitHub Action workflows to mass_commit

sdks/java/testing/jpms-tests/build.gradle
This enables JPMS tests to succeed on GitHub Actions on the release branch. This does not change the artifacts that were built in RC1 but it is necessary for GHA tests on the branch to succeed. (Jenkins tests are fine I believe) …
=> Cherrypick #28726 to 2.51.0 release branch: fix JPMS tests

sdks/python/apache_beam/testing/load_tests/build.gradle
As per https://docs.gradle.org/current/userguide/upgrading_version_7.html
`execResult` has been deprecated in favor of `executionResult` from gradle 7 to 8 upgrade  …
=> Update executionResult in favor of deprecated of execResult

sdks/python/apache_beam/testing/analyzers/__init__.py, sdks/python/apache_beam/testing/analyzers/github_issues_utils.py, sdks/python/apache_beam/testing/analyzers/perf_analysis.py, sdks/python/apache_beam/testing/analyzers/perf_analysis_test.py, sdks/python/apache_beam/testing/analyzers/perf_analysis_utils.py, sdks/python/apache_beam/testing/analyzers/tests_config.yaml
Fixes: https://github.com/apache/beam/issues/28395
Groups the variables in Dataclasses for better readability and extensibility  …
=> Add dataclasses to perf alert tool and refactor code.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Ensure boot loaders are built using the latest Go patch release. …
=> Update container version in BeamModulePlugin.groovy

sdks/go/test/integration/integration.go, sdks/go/test/integration/io/fhirio/fhirio_test.go
I updated the service account with the appropriate permissions needed and ran this successfully - https://github.com/apache/beam/actions/runs/6456288968
I also improved the error logging for the test so that it indicates why it fails
Fixes #28227
GitHub Actions …
=> Reenable TestFhirIO.* on GHA

sdks/go/test/integration/integration.go
Remove unused os import causing precommit failures
GHA failure link: https://github.com/apache/beam/actions/runs/6461486510/job/17563107114?pr=26307 …
=> [Go] Remove unused os import

sdks/python/apache_beam/runners/worker/bundle_processor.py
Fix python lint detected in https://github.com/apache/beam/actions/runs/6462058505/job/17564161354?pr=28904
[![Build …
=> Fix Python Precommit lint

.github/workflows/pr-bot-pr-updates.yml, .github/workflows/self-assign.yml
mitigate #28909 . the number of github action workflow is limited by github, even we have self-hosted runner setup, we still rely github's resource to queue jobs.
Every time codecov updates its comment, these two actions get queued. This change would further reduce the number of queued actions by issue_comment trigger. …
=> Run self-assign and pr-updates only in create event

.github/workflows/beam_PostCommit_Python_ValidatesContainer_Dataflow_With_RC.yml
This is causing repeated failures (e.g. https://github.com/apache/beam/actions/runs/6478627017/job/17590709062) …
=> Fix missing backslash in arguments of job

sdks/python/.pylintrc, sdks/python/apache_beam/runners/portability/flink_uber_jar_job_server.py, sdks/python/apache_beam/testing/analyzers/github_issues_utils.py, sdks/python/apache_beam/testing/benchmarks/nexmark/nexmark_launcher.py, sdks/python/apache_beam/testing/load_tests/load_test_metrics_utils.py
Enables the missing-timeout check and adds timeouts in request calls that did not have them previously.
Fixes #28240  …
=> Enable missing-timeout pylint check

sdks/python/apache_beam/ml/transforms/base.py, sdks/python/apache_beam/ml/transforms/base_test.py
Adds counters to the MLTransform and data processing transforms. …
=> Add counter for MLTransform and data processing transforms

.github/workflows/beam_LoadTests_Python_CoGBK_Dataflow_Batch.yml, .github/workflows/beam_LoadTests_Python_CoGBK_Dataflow_Streaming.yml, .github/workflows/beam_LoadTests_Python_CoGBK_Flink_Batch.yml, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Batch_100b_Multiple_Keys.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Batch_100b_Single_Key.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Batch_10kB.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Batch_2MB.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Flink_Batch_100b_Multiple_Keys.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Flink_Batch_100b_Single_Key.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Flink_Batch_10kB.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Streaming_100b_Multiple_Keys.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Streaming_100b_Single_Key.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Streaming_10kB.txt, .github/workflows/load-tests-job-configs/python-cogbk/python_CoGBK_Dataflow_Streaming_2MB.txt
".github/workflows/beam_LoadTests_Python_CoGBK_Dataflow_Batch.yml"
".github/workflows/beam_LoadTests_Python_CoGBK_Dataflow_Streaming.yml"
".github/workflows/beam_LoadTests_Python_CoGBK_Flink_Batch.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_CoGBK_Dataflow_Batch/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_CoGBK_Dataflow_Streaming/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_CoGBK_Flink_Batch/
Example runs:
beam_LoadTests_Python_CoGBK_Dataflow_Batch https://github.com/aleksandr-dudko/beam/actions/runs/6352300938
beam_LoadTests_Python_CoGBK_Dataflow_Streaming …
=> Add GitHub Workflow Replacements for Jenkins job_LoadTests_Python_CoGBK subgroup

.github/workflows/beam_LoadTests_Python_SideInput_Dataflow_Batch.yml, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_10gb_1000window_first_iterable.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_10gb_1000window_iterable.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_10gb_1window_first_iterable.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_10gb_1window_iterable.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_1gb_1000window_1key_percent_dict.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_1gb_1000window_99key_percent_dict.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_1gb_1window_1key_percent_dict.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_1gb_1window_99key_percent_dict.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_1gb_1window_first_list.txt, .github/workflows/load-tests-job-configs/python_SideInput_Dataflow_Batch_1gb_1window_list.txt
".github/workflows/beam_LoadTests_Python_SideInput_Dataflow_Batch.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_SideInput_Dataflow_Batch/
Example runs:
beam_LoadTests_Python_SideInput_Dataflow_Batch https://github.com/aleksandr-dudko/beam/actions/runs/6407828449 …
=> Add GitHub Workflow Replacements for Jenkins job_LoadTests_Python_SideInput_Dataflow_Batch

.github/workflows/beam_Prober_CommunityMetrics.yml
https://ci-beam.apache.org/job/beam_Prober_CommunityMetrics/ …
=> Add Community Metrics Prober workflow

.github/workflows/go_tests.yml
Configure caching go deps properly in Go Tests action.
This should reduce runtime of the action somewhat.
[![Build …
=> Update go_tests.yml to cache Go Deps correctly.

CHANGES.md, website/www/site/config.toml, website/www/site/content/en/blog/beam-2.51.0.md, website/www/site/content/en/get-started/downloads.md
This adds the blog post and updates the "latest version" config for the Beam site. …
=> [Website] Announce Beam 2.51.0

examples/notebooks/beam-ml/per_key_models.ipynb
Right now we're installing from head, but that's not needed with the release of 2.51 …
=> Use latest released beam in notebook

.github/workflows/beam_Inference_Python_Benchmarks_Dataflow.yml, .github/workflows/load-tests-job-configs/beam_Inference_Python_Benchmarks_Dataflow_Pytorch_Imagenet_Classification_Resnet_152.txt, .github/workflows/load-tests-job-configs/beam_Inference_Python_Benchmarks_Dataflow_Pytorch_Imagenet_Classification_Resnet_152_Tesla_T4_GPU.txt, .github/workflows/load-tests-job-configs/beam_Inference_Python_Benchmarks_Dataflow_Pytorch_Language_Modeling_Bert_Base_Uncased.txt, .github/workflows/load-tests-job-configs/beam_Inference_Python_Benchmarks_Dataflow_Pytorch_Language_Modeling_Bert_Large_Uncased.txt, .github/workflows/load-tests-job-configs/beam_Inference_Python_Benchmarks_Dataflow_Pytorch_Vision_Classification_Resnet_101.txt
https://ci-beam.apache.org/job/beam_Inference_Python_Benchmarks_Dataflow/
https://ci-beam.apache.org/job/beam_Inference_Python_Benchmarks_Dataflow_PR/ …
=> Add Inference Python Benchmarks Dataflow workflow

.github/workflows/go_tests.yml
Removes the still-flakey govulncheck action …
=> Remove govulncheck for Go Test workflow

examples/notebooks/beam-ml/mltransform_basic.ipynb
Fix typo and remove extra button in the MLTransform_basic notebook. …
=> Fix typo and remove extra button

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml, .github/workflows/beam_Publish_Docker_Snapshots.yml
=> Fix publish snapshots github actions

.github/workflows/beam_Java_LoadTests_Combine_Smoke.yml, .github/workflows/beam_LoadTests_Python_GBK_Flink_Batch.yml, .github/workflows/beam_PerformanceTests_xlang_KafkaIO_Python.yml, .github/workflows/beam_PostCommit_XVR_GoUsingJava_Dataflow.yml, .github/workflows/load-tests-job-configs/java_LoadTests_Combine_Smoke_CombineLoadTest_load_test_Dataflow-1.txt, .github/workflows/load-tests-job-configs/java_LoadTests_Combine_Smoke_CombineLoadTest_load_test_Dataflow-2.txt, .github/workflows/load-tests-job-configs/java_LoadTests_Combine_Smoke_CombineLoadTest_load_test_Dataflow-3.txt, .github/workflows/load-tests-job-configs/python_GBK_Flink_Batch_2GB_of_100B_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Flink_Batch_2GB_of_10B_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Flink_Batch_fanout_4_times_with_2GB_10-byte_records_total.txt, .github/workflows/load-tests-job-configs/python_GBK_Flink_Batch_fanout_8_times_with_2GB_10-byte_records_total.txt, .github/workflows/load-tests-job-configs/python_GBK_Flink_Batch_reiterate_4_times_10kB_values.txt
".github/workflows/beam_Java_LoadTests_Combine_Smoke_PR.yml"
".github/workflows/beam_LoadTests_Python_GBK_Flink_Batch.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/LoadTests/job/beam_Java_LoadTests_Combine_Smoke_PR/
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_GBK_Flink_Batch/
Example runs:
beam_Java_LoadTests_Combine_Smoke_PR https://github.com/magicgoody/beam/actions/runs/6451485468
Job is disabled in Jenkins.
***
beam_LoadTests_Python_GBK_Flink_Batch.yml
Test run results in Jenkins, the same as in Github run.
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_GBK_Flink_Batch_PR/
Test works very slow and fails, there is an …
=> Github Workflow Replacement for Jenkins Jobs, beam_LoadTests_Python_GBK_Flink_Batch; beam_Java_LoadTests_Combine_Smoke_PR

.github/workflows/beam_LoadTests_Java_GBK_Smoke.yml, .github/workflows/beam_LoadTests_Python_Smoke.yml, .github/workflows/load-tests-job-configs/java_Smoke_GroupByKey_Dataflow.txt, .github/workflows/load-tests-job-configs/java_Smoke_GroupByKey_Direct.txt, .github/workflows/load-tests-job-configs/java_Smoke_GroupByKey_Flink.txt, .github/workflows/load-tests-job-configs/java_Smoke_GroupByKey_Spark.txt, .github/workflows/load-tests-job-configs/python_Smoke_GroupByKey_Dataflow.txt, .github/workflows/load-tests-job-configs/python_Smoke_GroupByKey_Direct.txt
".github/workflows/beam_Python_LoadTests_Smoke.yml"
".github/workflows/beam_Java_LoadTests_GBK_Smoke.yml"
Jenkins Jobs:
https://ci-beam.apache.org/job/beam_Python_LoadTests_Smoke_PR/
https://ci-beam.apache.org/view/LoadTests/job/beam_Java_LoadTests_GBK_Smoke_PR/
Example runs:
beam_Python_LoadTests_Smoke https://github.com/aleksandr-dudko/beam/actions/runs/6423999549
beam_Java_LoadTests_GBK_Smoke https://github.com/aleksandr-dudko/beam/actions/runs/6424001711 …
=> Add GitHub Workflow Replacements for Jenkins job_LoadTests_Python_Smoke and job_LoadTests_Java_GBK_Smoke

.github/workflows/beam_LoadTests_Python_ParDo_Dataflow_Batch.yml, .github/workflows/beam_LoadTests_Python_ParDo_Dataflow_Streaming.yml, .github/workflows/beam_LoadTests_Python_ParDo_Flink_Batch.yml, .github/workflows/beam_LoadTests_Python_ParDo_Flink_Streaming.yml, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Batch_100_Counters.txt, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Batch_10_Counters.txt, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Batch_10_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Batch_200_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Streaming_100_Counters.txt, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Streaming_10_Counters.txt, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Streaming_10_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Dataflow_Streaming_200_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Batch_10_Counters.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Batch_10_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Batch_200_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Streaming_100_Counters.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Streaming_10_Counters.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Streaming_10_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Streaming_200_Iterations.txt, .github/workflows/load-tests-job-configs/python_ParDo_Flink_Streaming_5_Iterations.txt
".github/workflows/beam_LoadTests_Python_ParDo_Dataflow_Batch.yml"
".github/workflows/beam_LoadTests_Python_ParDo_Dataflow_Streaming.yml"
".github/workflows/beam_LoadTests_Python_ParDo_Flink_Batch.yml"
".github/workflows/beam_LoadTests_Python_ParDo_Flink_Streaming.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_ParDo_Dataflow_Batch/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_ParDo_Dataflow_Streaming/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_ParDo_Flink_Batch/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Python_ParDo_Flink_Streaming/ …
=> Add GitHub Workflow Replacements for Jenkins job_Python_ParDo_DataFlow and job_Python_ParDo_Flink

website/www/site/content/en/documentation/programming-guide.md
Explicitly document how to share the instances across threads for Python.  …
=> Updated the DoFn doc with pickling

.github/workflows/beam_LoadTests_Python_Combine_Dataflow_Streaming.yml, .github/workflows/beam_LoadTests_Python_GBK_reiterate_Dataflow_Batch.yml, .github/workflows/beam_LoadTests_Python_GBK_reiterate_Dataflow_Streaming.yml, .github/workflows/load-tests-job-configs/python_Combine_Dataflow_Streaming_2GB_10_byte_records.txt, .github/workflows/load-tests-job-configs/python_Combine_Dataflow_Streaming_2GB_Fanout_4.txt, .github/workflows/load-tests-job-configs/python_Combine_Dataflow_Streaming_2GB_Fanout_8.txt, .github/workflows/load-tests-job-configs/python_GBK_reiterate_Dataflow_Batch_reiterate_4_times_10kB_values.txt, .github/workflows/load-tests-job-configs/python_GBK_reiterate_Dataflow_Batch_reiterate_4_times_2MB_values.txt, .github/workflows/load-tests-job-configs/python_GBK_reiterate_Dataflow_Streaming_reiterate_4_times_10kB_values.txt, .github/workflows/load-tests-job-configs/python_GBK_reiterate_Dataflow_Streaming_reiterate_4_times_2MB_values.txt
".github/workflows/beam_LoadTests_Python_GBK_reiterate_Dataflow_Batch.yml"
".github/workflows/beam_LoadTests_Python_GBK_reiterate_Dataflow_Streaming.yml"
".github/workflows/beam_LoadTests_Python_Combine_Dataflow_Streaming.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_GBK_reiterate_Dataflow_Batch/
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_GBK_reiterate_Dataflow_Streaming/
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_Combine_Dataflow_Streaming/
Example runs:
beam_LoadTests_Python_GBK_reiterate_Dataflow_Batch.yml https://github.com/magicgoody/beam/actions/runs/6430029725 …
=> Github Workflow Replacement for Jenkins Jobs, beam_LoadTests_Python_GBK_reiterate_Dataflow_*, beam_LoadTests_Python_Combine_Dataflow_Streaming

.github/workflows/beam_CloudML_Benchmarks_Dataflow.yml, .github/workflows/load-tests-job-configs/beam_CloudML_Benchmarks_Dataflow_arguments.txt
https://ci-beam.apache.org/job/beam_CloudML_Benchmarks_Dataflow/
https://ci-beam.apache.org/job/beam_CloudML_Benchmarks_Dataflow_PR/
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apach …
=> Add CloudML Benchmarks Dataflow workflow

website/www/site/content/en/documentation/ml/multi-model-pipelines.md, website/www/site/content/en/documentation/sdks/python-machine-learning.md
Add KeyedModelHandler content to the multi-model ML page.
Also made some small edits to the existing content.
[![Build …
=> Add KeyedModelHandler content to the multi-model ML page

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/SubscribeTransform.java
=> Set MIN_PER_PARTITION_MEMORY to 10 MiB instead of 4 MiB to match the change in the backend limit.

sdks/python/apache_beam/runners/portability/stager.py
Fixes: https://github.com/apache/beam/issues/28990
Fixes: https://github.com/apache/beam/issues/29020 …
=> Change the if condition to check if build is installed

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
This reverts commit d38fdd8e7d075effca51980b4d7dfb47882dc47e. …
=> Revert "Add no-cache-dir to tox install"

sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponseio/CacheWrite.java
This PR addresses #28908 by stubbing a PTransform that caches associated requests and responses to be read later by the CacheRead transform. …
=> [RRIO] [CACHE] Stub the CacheWrite transform

.github/workflows/beam_PreCommit_Java_PVR_Flink_Batch.yml
- by creating pull requests with changes in trigger paths
- by making a push …
=> Fix PreCommit Java PVR Flink Batch job

.github/workflows/beam_CancelStaleDataflowJobs.yml, .github/workflows/beam_CleanUpGCPResources.yml, .github/workflows/beam_CleanUpPrebuiltSDKImages.yml, .test-infra/tools/build.gradle, .test-infra/tools/stale_k8s_workload_cleaner.sh
We experience elevated stale k8s workloads which triggers internal vulnerability alerts. This PR adds a script to auto clean up them …
=> Add cleanup stale k8s namespace to CleanUpGCPResource workflow

sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponseio/CacheRead.java
This PR addresses #28907 via stubbing the `class CacheRead<RequestT, ResponseT> extends PTransform<PCollection<RequestT>, Result<RequestT, ResponseT>>` …
=> [RRIO] [Cache] Stub CacheRead transform

sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/ThrottleEnqueue.java
This PR addresses #28932 via a stub of an Enqueue PTransform that enqueues elements to control pre-call throttling:
`PTransform<PCollection<RequestT>, PCollection<ApiIOError>>` …
=> [RRIO] [Throttle] Stub Enqueue PTransform

sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/ThrottleRefreshQuota.java
This PR addresses #28932 by stubbing a quota refreshing transform. …
=> [RRIO] [Throttle] stub the refresh quota transform

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineOptions.java
Add a link to the Dataflow service options page from the DataflowPipelineOptions Java docs. …
=> Add link to the Dataflow service options page

.github/workflows/beam_PostCommit_Java_ValidatesRunner_Dataflow_JavaVersions.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_Direct.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_Direct_JavaVersions.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink_Java11.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_Spark_Java11.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_ULR.yml, .github/workflows/beam_PostCommit_Python_Examples_Flink.yml, .github/workflows/beam_PostCommit_Python_ValidatesContainer_Dataflow.yml, .github/workflows/beam_PostCommit_Python_ValidatesContainer_Dataflow_With_RC.yml
Added fixes in order to stabilize some of the GitHub Actions workflows …
=> Fix and stabilize some GitHub Actions workflows

contributor-docs/release-guide.md
This should ideally be done well in advance of the release, and should be best effort from the release manager
[![Build …
=> Move Java Google BOM to best effort post-release task

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/BeamKafkaTable.java, sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/KafkaTestTable.java
make BeamKafkaTable.createKafkaRead to be protected, and we can override it appending options to KafkaIO.Read …
=> Make BeamKafkaTable.createKafkaRead to be protected

.github/workflows/beam_PerformanceTests_SingleStoreIO.yml, .github/workflows/performance-tests-job-configs/config_PerformanceTests_SingleStoreIO.txt
Migrate PerformanceTest SingleStoreIO …
=> beam_performance_singlestoreio

website/www/site/content/en/documentation/io/built-in/google-bigquery.md, website/www/site/content/en/documentation/sdks/python-unrecoverable-errors.md, website/www/site/content/en/get-started/_index.md, website/www/site/content/en/get-started/downloads.md
* Edited the Python unrecoverable errors page
* Edited the BigQuery I/O connector updates
* On the Downloads page, removed the TM symbol and replaced with ® (see issue #24754)
* In the Get Started page, removed links from headers and moved them to the content …
=> Editorial pass on content

sdks/python/apache_beam/yaml/yaml_io_test.py, sdks/python/apache_beam/yaml/yaml_mapping_test.py, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_test.py, sdks/python/apache_beam/yaml/yaml_transform_unit_test.py, sdks/python/apache_beam/yaml/yaml_udf_test.py
This can be taken directly from what's passed to it. This eliminates the need for the awkward input: input spec in basic uses. …
=> [YAML] Don't require redundant input for YamlTransform.

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowOperationContext.java
The `LogRecord`'s `threadId` is set to the sampler thread's `threadId`, so this adds useful information about the thread id of the thread experiencing the lull. …
=> Include ID and name of tracked thread in lull message

website/www/site/content/en/blog/beam-sql-with-notebooks.md
The provided API to fetch covid data from has changed to: https://api.covidtracking.com/v1/states/current.json …
=> Update beam-sql-with-notebooks.md with working API link

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
Part of #28120
As the Jenkins counterpart stays green after #28918 we can move forward to make the same change on GHA side. …
=> Publish Java21 container for Publish SDK container GitHub Action

sdks/python/apache_beam/runners/dataflow/internal/names.py
To include the dependency updates in https://github.com/apache/beam/commit/1885251330.
The tag of the new container image is beam-master-20231023. …
=> Update the version of beam-master container image for python.

sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/ThrottleWithoutExternalResource.java
This PR addresses #28930 by stubbing a transform that aims to throttle a PCollection without using an external resource. …
=> [RRIO] [Throttle] Stub throttle without external resource

CHANGES.md, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Updates Go build version to address [CVE-2023-39325](https://www.cve.org/CVERecord?id=CVE-2023-39325)
Fixes #29118 …
=> Increment Go build version to 1.21.3

learning/katas/python/Core Transforms/Flatten/Flatten/task.py
This should hopefully address #29111 …
=> Fix flatten docs

.github/workflows/beam_Metrics_Report.yml, .test-infra/jenkins/metrics_report/report_generator.py, .test-infra/jenkins/metrics_report/tox.ini
Needed for Metrics report. 
- Adds a conditional to report_generator.py to construct the path
- Adds env vars to tox.ini …
=> change report generator to be aware of GH and passtrough vars to tox

.github/workflows/beam_PerformanceTests_Kafka_IO.yml
Adds authentication step to gcloud using credentials provided in github secrets.  …
=> add auth to gcp step

.github/workflows/beam_LoadTests_Python_CoGBK_Dataflow_Streaming.yml, .github/workflows/beam_LoadTests_Python_CoGBK_Flink_Batch.yml
- fix for path not found in https://github.com/apache/beam/actions/runs/6628902519/job/18007023210 and https://github.com/apache/beam/actions/runs/6628928745/job/18007118069 …
=> remove subdir from test config paths

.github/workflows/beam_MetricsCredentialsRotation.yml, .github/workflows/beam_Metrics_Report.yml, .github/workflows/beam_PostCommit_BeamMetrics_Publish.yml, .github/workflows/beam_Publish_Beam_SDK_Snapshots.yml, .github/workflows/beam_Publish_Docker_Snapshots.yml, .github/workflows/beam_Release_NightlySnapshot.yml, .github/workflows/beam_Release_Python_NightlySnapshot.yml, .github/workflows/build_runner_image.yml
Some workflows publish resources or have other side effects. These should only ever be run on apache/beam. This restricts forks from accidentally doing things like publishing snapshots …
=> Restrict workflows to run on apache/beam

.github/workflows/beam_IODatastoresCredentialsRotation.yml, .github/workflows/beam_MetricsCredentialsRotation.yml
=> Add Send email step

sdks/python/apache_beam/transforms/core.py, sdks/python/apache_beam/yaml/options.py, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_udf_test.py
=> [YAML] Guard javascript UDFs with experimental feature enablement.

CHANGES.md, sdks/java/container/build.gradle
Part of #28120
As publish sdk snapshot container is and java21 tests are running good, we can add the container to release process now. …
=> Publish Java21 container in release process

sdks/python/apache_beam/typehints/native_type_compatibility.py, sdks/python/apache_beam/typehints/native_type_compatibility_test.py, sdks/python/apache_beam/typehints/typehints_test.py
Modifies the set matcher to include `collections.abc.Set` and derived types while also providing a passthrough to the matcher for supported `collections.abc` types. 
Part of #29135 …
=> Add typehint support for collections.abc.Set types

.github/workflows/beam_PreCommit_Java_RequestResponse_IO_Direct.yml, sdks/java/io/rrio/build.gradle, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RedisClient.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RedisClientTestIT.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RedisExternalResourcesRule.java
This PR addresses #28932, addresses #28924, addresses #28922 by creating a RedisClient utility. The value of this class over using the direct java Redis client is that it is Serializable and handles the setup/teardown with null checks needed when using a non-Serializeable client.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/ …
=> [RRIO] create RedisClient utility

runners/google-cloud-dataflow-java/build.gradle
=> Bump Dataflow dev container versions to beam-master-20231026

.test-infra/metrics/grafana/dashboards/GA-Post-Commits_status_dashboard.json, .test-infra/metrics/sync/github/sync_workflows.py
This attempts to split our dashboard into categories. Obviously its quite large, so I'll explain the methodology used to generate this and we can go from there with a heavier code review on the more potentially error prone spots.
I'll also note that I'm planning on making this better over time, so the splitting of things into labels should end up being more precise than it is in this iteration. 
How I did this:
1) All changes to sync_workflows were manual and should be reviewed normally. The goal here is to add a `dashboard_category` which maps to one of `core_<lang>`, `<runner>_<lang>`, or `misc` so that we can split tests into these categories.
2) To generate the dashboard changes (the bulk of the changes), I used the UI:
- First, I copied the existing dashboard 12 times using grafana's …
=> First pass at sorting gha dashboard

.test-infra/metrics/grafana/dashboards/GA-Post-Commits_status_dashboard.json
While preparing #29151 it seems like the UI changed the data source for some reason. This reverts all panels to the original data source and undoes some of the unnecessary change from that PR. …
=> Revert grafana data source

.github/workflows/beam_PostCommit_Python.yml
Attempt to restore the Python Postcommit to green.  …
=> Bump Python Postcommit to high memory runner

.github/actions/setup-environment-action/action.yml, .github/workflows/beam_PostCommit_Website_Publish.yml
This is currently permared because we check out a branch that doesn't have our setup action's post-step as part of publishing the website. This fixes the problem by checking out the original branch again
Example success - https://github.com/apache/beam/actions/runs/6669683640
History of failure - https://github.com/apache/beam/actions/workflows/beam_PostCommit_Website_Publish.yml …
=> Checkout repo for post step in website publish

sdks/python/apache_beam/utils/subprocess_server.py
This change allows GCS locations to be specified for reading "local" java jars in the external transform service. …
=> [YAML] add GCS support for external transform jars

sdks/go/pkg/beam/pardo.go, sdks/go/pkg/beam/partition.go, sdks/go/pkg/beam/transforms/filter/filter.go
Anonymous functions don't serialize or test well, and lead to habits that don't function on portable runners. 
This updates the code snippets, and descriptions to clarify that they must not be used. …
=> [Go Docs] Remove outdated examples of anonymous functions from pardo, partition, and filter.

sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_combine.md, sdks/python/apache_beam/yaml/yaml_combine.py, sdks/python/apache_beam/yaml/yaml_combine_test.py, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py
This follows the spirit of the schema-aware GroupBy operations in Java, Python, Typescript, etc. Syntactic sugar is provided for simplified forms.
This is currently guarded as experimental until we've fully vetted the API. …
=> [YAML] Add a basic aggregating transform to Beam Yaml.

sdks/python/apache_beam/io/gcp/bigtableio_it_test.py
Currently there are 130+ stall bigtable instances in apache-beam-testing project. …
=> Better naming and logging to investigate leaking bigtable resources

examples/notebooks/beam-ml/automatic_model_refresh.ipynb
This is needed for some notebook tooling that tries to run cells to produce an output since they don't know how to handle the authenticated pieces. …
=> Add empty outputs to AMR notebook

examples/notebooks/beam-ml/run_inference_windowing.ipynb
This moves the comment/install off the same line so that the datatable install actually gets executed
Before:
After: …
=> Fix notebook installs

.github/workflows/beam_PreCommit_Java_Examples_Dataflow_Java21.yml, CHANGES.md, runners/google-cloud-dataflow-java/examples/build.gradle
Part of #28120
Also fix #29168 …
=> Add Dataflow Example Java21 PreCommit

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/External.java
=> Delete beam-artifact temp file on exit
