apache/beam

runners/spark/src/main/java/org/apache/beam/runners/spark/SparkNativePipelineVisitor.java, runners/spark/src/test/java/org/apache/beam/runners/spark/SparkRunnerDebuggerTest.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/MapElements.java
fixes #21207.
Synthetic field generated for inner classes is replaced by explicit reference to `outer` class instance of  [MapElements](https://github.com/apache/beam/blob/7754ab9eab8951eb047643857623ea435ccbe894/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/MapElements.java#L161C28-L161C28). It will remove usage of synthetic field `this$0`, which is planned to be [omitted](https://bugs.openjdk.java.net/browse/JDK-8271717) in Inner classes not referencing instance variables of enclosing class.
=> Replace synthetic field this$0 by explicit instance

sdks/go/pkg/beam/runners/prism/internal/execute.go
Prism was hard expecting Go environments, but it should be expecting single external (aka, loopback) environments at this time. …
=> [prism] support single external env pipelines.

sdks/python/apache_beam/runners/worker/bundle_processor.py, sdks/python/apache_beam/runners/worker/bundle_processor_test.py
Loosen the environment validation for RC pipelines (see: https://github.com/apache/beam/issues/28084).
RC releases are currently compatible with RC Docker images, only the SDK version string is different, but SDK installation in the Docker  image actually includes the code from the RC .
Some customers make modifications to Beam releases and responsible customers set different version names for such SDKs. It makes sense to still verify that when customers modify the SDK at submission, they also have the matching installation at runtime , as opposed to just check the base version and ignoring all the suffixes.
=> Loosen environment validation checks for RCs

sdks/python/tox.ini
The upgraded version is causing docs precommit to fail.
Part of #28104 …
=> Pin hugging face docs

sdks/python/apache_beam/runners/worker/bundle_processor.py, sdks/python/apache_beam/runners/worker/bundle_processor_test.py
Addresses the release-blocking portion of https://github.com/apache/beam/issues/28084
=> [release-2.50.0] CP #28100 to the release branch.

sdks/python/container/build.gradle
* Add back docker prune step between python container pushes
* Extract to variables
* Define var inside loop to avoid async race condition …
=> Cherry pick: Add back docker prune step between python container pushes (#28033)

sdks/python/apache_beam/metrics/cells.py
Experiment with adding an explicit `int` type hint to CounterCell's `update` method. This should avoid an accidental aggregation of non-ints that is only caught when trying to serialize the metric.
Should prevent #27469 in the future …
=> Add type hint to CounterCell

sdks/python/apache_beam/options/pipeline_options_validator.py, sdks/python/apache_beam/options/pipeline_options_validator_test.py
This change makes 'localhost' a non service runner. …
=> is_service_runner now returns false  with dataflow_endpoint=localhost

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageQueryTest.java
Relates to #27971
Fixes issue faced in #26329 without solving discrepancies in source creation between BQ and avro.
=> Pass BQ coder to underlying avro source

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/CreateTableHelpers.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/CreateTables.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/DynamicDestinations.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/DynamicDestinationsHelpers.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinations.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkRowUpdateIT.java
Since tables must be created using a primary key, this PR also adds support for specifying the primary key.
R: @ahmedabu98
=> Allow using CREATE_IF_NEEDED when writing deletes or updates to BigQuery

.github/workflows/build_release_candidate.yml, website/www/site/content/en/contribute/release-guide.md
Create Docs PR with a Github Action for building release artifacts.
Based largely on the existing build_release_candidate.sh script, but with the following changes:
* No longer quarantine each doc generator into it's own clone.
* Leverage available steps for checking out code instead.
* Use `gh` instead of `hub`.
* Adds a use of the release managers' github token.
* Converts parts to steps to clarify logging and failures.
* Uses local envs, and working directory to clarify where we're working.  …
=> [release automation] Add documentation building job to build_release_candidate.yml workflow

sdks/go/pkg/beam/runners/prism/internal/coders.go, sdks/go/pkg/beam/runners/prism/internal/coders_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/handlerunner.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go
Improve error handling around panics and length prefixing unknown coders.
There's more work to do on this, but this should assist in executing the Swift SDK on prism.
Partly handles #28126. …
=> [#28126] plumb coder errors with better context.

sdks/go/pkg/beam/runners/prism/internal/execute.go
Add the missing check to trigger pipeline failures at stage construction.
Related to #28126  …
=> [prism] Fail pipeline execution properly on descriptor build errors.

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutor.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
Use MockClock instead of real system clock to fix the test flakiness.
=> Fix flaky test StreamingDataflowWorkerTest

sdks/python/apache_beam/ml/inference/base.py, sdks/python/apache_beam/ml/inference/base_test.py
Right now, we're not calculating batch sizes correctly for keyed examples in the per key model handler implementation; we should be shelling out to the underlying model handler which can do this more effectively. This adds support to do this.
Part of #27628 …
=> Shell out to model handlers to collect byte sizes

sdks/go/pkg/beam/runners/prism/internal/web/assets/style.css, sdks/go/pkg/beam/runners/prism/internal/web/debugz.go, sdks/go/pkg/beam/runners/prism/internal/web/debugz.html, sdks/go/pkg/beam/runners/prism/internal/web/web.go
Add a page to the stand alone command that produces the various Go runtime metrics of the binary.
In particular, this includes the formatted goroutine dump, which can be useful in investigating stuck or unusually behaving jobs, when expanding prism's abilities.
Available at /debugz or from the link at the bottom of the index page.
Related to #28187. …
=> [#28187][prism] Add a debugz page to standalone web ui.

sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/server.go, sdks/go/pkg/beam/runners/prism/internal/preprocess.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go
Some fixes while trying to use the experimental Swift SDK against prism.
* Use an actual loopback address for endpoints instead of the net package listener default of unspecified.
* IPv6 uses "[::]" to mean an unspecified address, which Go then treats as the loopback address. This isn't true across all SDKs, so we must explicitly indicate the loopback address.
* Note: We create the server to listen to any traffic to that port however, so other connections, possibly off the machine, remain valid.
* Increase default receive buffer to max.
* Fail jobs if the SDK worker doesn't connect after 1 minute.
* Error job failures on log on slog side.
* Minor log clean up, to a debug log.
Related to #28187 …
=> [#28187][prism] worker shutdown, cleanup, log fail, port spec, grpc recv size

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java
The race condition could cause NPE:
- Thread 1 enters close and get the refCount == 0, the refCount for configId is decremented to 0.
- Before Thread 1 could remove the configId from entry maps and refCount maps, Thread 2 enters getServiceForReading and get the lock.
- For thread 2, entry is not null, it increment the counter in refCounts and exit. Now the refCount for configId is 1.
- Thread 2 finishes the work and also entered close(). gets the ref count again, and refCount is decremented to 0 again.
- Thread 1 gets the lock since refCount is 0, removes configId from the map.
- Thread 2 gets the lock since refCount is 0, tries to removes the configId from the map and gets NPE. …
=> fix: fix a race condition in BigtableService cache

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FromRowUsingCreator.java
The conversion of rows to the external object is rather inefficient. The code to convert Row fields to the external field types required for the constructor / setters in `FromRowUsingCreator` is branch heavy and rather hard to optimize for Java's JIT compiler.
Maps and Collections / Lists are currently handled inconsistently:
- Maps are eagerly rewritten / copied, making their usage rather expensive. The user object will contain fully operable maps.
- Collections / Lists are converted using Guava views (e.g. `Lists.transform`). The user object will contain collections that can mostly just be read from, THOUGH it's possible to remove items from the underlying collection potentially causing issues.
- On first usage, generate a converter function for every field based on schema & type …
=> [Java][Schemas] Improve performance of GetterBasedSchemaProvider#fromRowFunction

sdks/go/test/integration/integration.go
- When the user is github-actions, exclude the test. …
=> Exclude "TestFhirIO.*" from Go PostCommit Dataflow ARM test suite

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteTables.java
Example log message:
```
Use TableSchema for tableSpec: *****.xxxxx: {"fields":[{"mode":"REQUIRED","name":"key","type":"INT64"},{"mode":"NULLABLE","name":"timestamp","type":"TIMESTAMP"}]}
```
GitHub …
=> Add debug logs for updated schema in BigQueryIO

sdks/go/pkg/beam/core/graph/fn.go, sdks/go/pkg/beam/core/runtime/exec/sdf.go, sdks/go/pkg/beam/core/runtime/harness/datamgr.go, sdks/go/pkg/beam/io/datastoreio/datastore.go, sdks/go/pkg/beam/register/iter.go, sdks/go/pkg/beam/runners/prism/internal/config/config.go, sdks/go/pkg/beam/runners/universal/runnerlib/stage.go, sdks/go/pkg/beam/staticcheck.conf, sdks/go/pkg/beam/util/execx/exec.go
Makes the Go SDK compliant with and enables the following Staticcheck checks: [ST1016](https://staticcheck.dev/docs/checks/#ST1016), [ST1020](https://staticcheck.dev/docs/checks/#ST1020), [ST1022](https://staticcheck.dev/docs/checks/#ST1022), [ST1023](https://staticcheck.dev/docs/checks/#ST1023), and [S1021](https://staticcheck.dev/docs/checks/#S1021). 
Part of #21513 …
=> Improve Go SDK Staticcheck Compliance

sdks/python/apache_beam/io/gcp/gcsfilesystem_integration_test.py
Adding integration tests for GCSFileSystem to improve the odds of a clean GCS migration (see #25676). …
=> Integration tests for GCSFileSystem

sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/io/AvroDatumFactory.java
addresses #28279 
Avro has a discrepancy between reflect reader and writer side:
- In the reader side, `new ReflectDatumReader<>(clazz)` returns a [new model data](https://github.com/apache/avro/blob/60796e5df4581589717cfa32952da792dec79b68/lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumReader.java#L52)
- In the writer side `new ReflectDatumWriter<>(clazz)` returns the [singleton model data](https://github.com/apache/avro/blob/60796e5df4581589717cfa32952da792dec79b68/lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumWriter.java#L45)
Updating the model data's logical types is not a thread safe operation, so we must not use the singleton instance in this case.
=> Return new ReflectData for both reflect datum reader and writer

website/www/site/content/en/documentation/runners/spark.md
The PR updated the Spark runner document, including the way to run the beam job on a spark kubernetes cluster.
The work at Affirm has verified this.
address #27985 …
=> [Task] Update document for spark runner on a kubernetes cluster

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go, sdks/go/pkg/beam/runners/prism/internal/worker/bundle_test.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go, sdks/go/pkg/beam/testing/passert/equals_test.go
If the control connection for a job is lost, eg. by an SDK worker crash (detected via grpc stream context cancel), then fail all extant instructions, and terminate the job, rather than leave it running perpetually.
Further, ensure the extant bundles are cleaned up from the element manager, to allow failed jobs to be properly garbage collected.
Reduce routine log messages to debug to avoid noise.
Use ctx.WithCancelCause properly, which requires calling context.Cause on the context.
Restructures the bundle processing loop in execute.go to better allow for eager bundle splitting. Would need to move bundle data acquisition to be moved out of stage.Execute, and split there.
Special thanks to the Swift SDK for being in a crashing on worker state to reliably validate this.
Related #28187 …
=> [prism] Fail jobs on SDK disconnect.

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineOptions.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/SourceInputFormat.java
In the current implementation of file sources, the Flink runner will try to fix the size of input splits using the formula `source estimated size / parallelism`. Most of the time, the resulting desired split size will be much larger than the size of files read by this source.  In that case each individual file becomes full split, and the number of splits is larger than parallelism. 
This creates an issue when the size of individual files varies a lot. At Spotify we commonly read datasets stored on GCS where individual files range from a few Mb to 1 or 2 Gb. Because of this, work distribution is sub-optimal because some workers will be consuming larges splits while other worker consume smaller splits.  
This PR limits the maximum size of each split to 128Mb (configurable), which is a …
=> Reduce the maximum size of input splits in Flink to better distribute work

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/BeamSqlSeekableTable.java, sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/transform/BeamJoinTransforms.java
=> Pass runtime configs & variables to BeamSqlSeekableTable

sdks/go/pkg/beam/runners/dataflow/dataflow.go, sdks/go/pkg/beam/runners/dataflow/dataflow_test.go
Adds handling for being passed `use_public_ips` instead of `no_use_public_ips`. Adds some extra validation to throw an error if provided both flags with the same value.  …
=> Add use_public_ips to Go Dataflow Runner

.github/workflows/beam_Release_NightlySnapshot.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Adds nightly publish workflow. 
Added isNightly gradle parameter to facilitate timestamp versioning …
=> adding nightly publish

.github/workflows/beam_PreCommit_Java_Examples_Dataflow_Java11.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
=> Fix Java 11 Example PreCommit GItHub Action

sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
Remediation for: https://github.com/apache/beam/issues/28318.
If orjson doesn't come up with a fix, we can pin the last tested version.
=> Pin orjson dependency.

sdks/go/pkg/beam/core/runtime/exec/to_string.go, sdks/go/pkg/beam/core/runtime/exec/to_string_test.go, sdks/go/pkg/beam/core/runtime/exec/translate.go, sdks/go/pkg/beam/core/runtime/graphx/translate.go
This adds the ToStringFn implementation to Golang. This allows Runners to call the SDK to translate an element to a human-readable representation.
Design-doc:
https://s.apache.org/data-sampling-go-sdk-design 
See https://issues.apache.org/jira/browse/BEAM-11151 …
=> [BEAM-11151]Adds the ToStringFn Bundle Processor to Golang

release/src/main/scripts/publish_docker_images.sh
- fix https://github.com/apache/beam/issues/28341 …
=> Retag 2.50.0 RC2 to publish multi-arch containers

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ConvertHelpers.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/RowSchemaInformationProvider.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/SchemaInformationProvider.java, sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroSchemaInformationProvider.java
Fixes an issue with hard Avro dependency that was found in #27851 
It uses `SchemaInformationProvider` instead now. …
=> Refactor ConvertHelpers in "core" to not depend on Avro

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile
- Adds maven to the image
- Sets MAVEN_HOME so there is no need to use -Pmaven_home gradle switch …
=> adds maven to image

.github/workflows/beam_Release_NightlySnapshot.yml
This removes the step where we were accidentally blowing away the .m2 file. …
=> Inline publish script

sdks/go/container/tools/buffered_logging.go, sdks/go/pkg/beam/util/execx/exec.go, sdks/python/container/boot.go, sdks/python/container/piputil.go
Adds the buffered logger type to the Python bootloader script, capturing subprocess output and assigning an appropriate severity to them over the FnAPI (debug if the subprocess returns exit code 0, error if the subprocess returns exit code 1.) Also removes the quiet directive from pip invocations so full output is captured. 
Example of new pip output, with package information logged appropriately: …
=> Add buffered logger to the Python bootloader

sdks/python/apache_beam/internal/dill_pickler.py
This should help with the segfault portion of https://github.com/apache/beam/issues/27330.
=> Apply the monkey-patch with backport of newer changes to dill pickler also in Python 3.10.

.github/workflows/beam_Release_NightlySnapshot.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
These were added in #28255 but it looks like the assumption that these would function normally was baked deeper than we were aware of. …
=> Undo changes to BeamModulePlugin.groovy

website/www/site/content/en/documentation/sdks/python-pipeline-dependencies.md
=> Edit for clarity

sdks/python/apache_beam/dataframe/frames.py, sdks/python/apache_beam/dataframe/frames_test.py
This is a step to supporting Pandas 2.0 in Beam by keeping the API consistent between the two.
Partially fixing #27221
=> Remove mad and tshift when Pandas >= 2.0 as they are removed there.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/resources/ClasspathScanningResourcesDetectorTest.java
I'm helping to investigate a scenario where classpath scanning is taking a lot of time (>10 minutes), and from the logs the only operation between the lines below seem to be classgraph.
> INFO 2023-08-22T01:36:26Z [main] INFO org.apache.beam.runners.dataflow.options.DataflowPipelineOptions$StagingLocationFactory - No stagingLocation provided, falling back to gcpTempLocation
> INFO 2023-08-22T01:49:04Z [main] INFO org.apache.beam.runners.dataflow.DataflowRunner - PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 1 files. Enable logging at DEBUG level to see which files will be staged.
Unfortunately I couldn't reproduce locally, but debugging or raising bugs is not likely to go anywhere because the version is over 2 years old, and missing …
=> Bump classgraph version to 4.8.162

website/www/site/content/en/documentation/ml/data-processing.md, website/www/site/content/en/documentation/ml/overview.md, website/www/site/content/en/documentation/ml/preprocess-data.md, website/www/site/layouts/partials/section-menu/en/documentation.html
New documentation page for MLTransform.
This needs to be published with https://github.com/apache/beam/pull/27709 and the 2.50.0 release.
R: @damccorm
R: @AnandInguva 
R: @rezarokni
=> New MLTransform documentation

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProviderTest.java, sdks/python/apache_beam/io/gcp/bigquery.py, sdks/python/apache_beam/pipeline.py, sdks/python/apache_beam/transforms/external.py, sdks/python/apache_beam/transforms/external_test.py, sdks/python/apache_beam/typehints/schema_registry.py, sdks/python/apache_beam/yaml/main.py, sdks/python/apache_beam/yaml/standard_io.yaml, sdks/python/apache_beam/yaml/yaml_io.py, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py
This adapts the Java and Python BigQuery IOs to have the same interface and be callable from Yaml.
Several bugfixes were required along the way to make this work smoothly which are divided out in the commit history.  …
=> [YAML] Implement a consistent BigQuery read and write transform.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java, sdks/python/apache_beam/io/gcp/bigquery.py, sdks/python/apache_beam/pipeline.py, sdks/python/apache_beam/transforms/external.py, sdks/python/apache_beam/transforms/external_test.py, sdks/python/apache_beam/typehints/schema_registry.py, sdks/python/apache_beam/yaml/main.py, sdks/python/apache_beam/yaml/standard_io.yaml, sdks/python/apache_beam/yaml/yaml_io.py, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py
Uses infrastructure from https://github.com/apache/beam/pull/28169 which should be reviewed first. …
=> Add standard {ReadFrom,WriteTo}{Csv,Json} yaml endpoints.

website/www/site/content/en/contribute/release-guide.md
This is a larger cleanup of the release guide to clarify timings and positioning of the broader steps.
Larger emphasis has been put on the Release Manager's role prior to the release cut. If issues are addressed in the main branch before the cut, they do not need to be addressed afterwards. The release manager is empowered to do so.
Clarify some timing around the begining and end of the release by calling out the preparation steps should be performed within the week prior to the release cut. Also call out that release finalization tasks can be done within a few hours of the release being completed.
While the guide isn't materially shorter, maintaining the simpler structure as in the overview will make it less overwheling to release managers, since it's clearer when the various subtasks …
=> Post 2.50.0 Streamline release guide improvements

.github/workflows/beam_PreCommit_Spotless.yml
This PR was created to add an action that visualize the results of Checkstyle tests and adds them to the workflow summary page.
The action requires additional permissions:
checks: write (allow to add test result to workflow summary page)
Example runs:
no error: https://github.com/magicgoody/beam/actions/runs/5964470451
with error: https://github.com/magicgoody/beam/actions/runs/5949179444
Example screenshots:
Checkstyle result without violations
Checkstyle result with violations
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING. …
=> Publish Checkstyle Results

sdks/python/container/boot.go
The minimum Python version currently supported is 3.8, but there was some leftover logic in the Python boot.go script around wheel naming for versions 3.6 and 3.7. This change removes that unused logic.  …
=> Remove bootloader naming logic for unsupported Python versions

runners/google-cloud-dataflow-java/worker/build.gradle, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/AbstractWindmillStream.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/ForwardingClientResponseObserver.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/StreamObserverFactory.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillEndpoints.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillServiceAddress.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillStream.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcCommitWorkStream.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcGetDataStream.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcGetWorkStream.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcGetWorkerMetadataStream.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcGetWorkerMetadataStreamTest.java, runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto, runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill_service.proto
Adding a stream for GetWorkerMetadata
Does not include (the following will be in a seperate CL)
1. Storing the metadata
2. Using the metadata
3. Adding stream to GrpcWindmillServer (I will add tests to GRPCWindmillServer as well)
- Updated the type parameters for the *ResponseObserver.java files
- Add unit tests (should do this for all of the stream classes)
- make GetWorkerMetadata RPC a BiDi Stream
r: @scwhittle @dustin12 
To check the …
=> add getworkermetadata streaming rpc

sdks/python/apache_beam/typehints/trivial_inference.py, sdks/python/apache_beam/typehints/trivial_inference_test.py
The previous workaround would capture cases where the call was correctly structured and consume too much of the stack.
https://github.com/python/cpython/issues/102403 …
=> More targeted workaround for Python 3.11 comprehension bug.

sdks/python/apache_beam/transforms/ptransform.py, sdks/python/apache_beam/yaml/yaml_transform_test.py
We should add this to all transforms that are simply parameterized. …
=> Add an annotation to expose transforms to yaml.

sdks/go/container/tools/buffered_logging.go, sdks/go/container/tools/buffered_logging_test.go, sdks/python/container/boot.go, sdks/python/container/piputil.go
Adds the capacity for the buffered logger to print directly to the console or write directly over the logging service if available to cover the last print statements in the script. Routes through a buffered logger type to support the container prebuild workflow. Also adds the ability to periodically flush output during long-running operations (like PIP dependency resolution) rather than waiting for the end of the process.  …
=> Route remaining prints in boot.go through logging service if possible, add periodic flush for PIP invocations

runners/google-cloud-dataflow-java/build.gradle, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/FileLoadsStreamingIT.java
Addressing this big integration testing gap.
Includes streaming with single load jobs, copy jobs, auto-sharding/fixed shards, and dynamic destinations.
Limiting it to test only ~half the cases with Dataflow runner.
Uncovered an issue with dynamic destinations while doing this: #28309
=> Add file loads streaming integration tests

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutor.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
Reverts apache/beam#28173
The enabled test has been flaky on both Jenkins and actions. e,g, https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/7319/testReport/junit/org.apache.beam.runners.dataflow.worker/StreamingDataflowWorkerTest/testMaxThreadMetric_0___streamingEngine_false__/
and the commit trigger seeing this quite often: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/
```
Stacktrace
java.lang.AssertionError: expected:<1000> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorkerTest.testMaxThreadMetric(StreamingDataflowWorkerTest.java:2935)
at …
```
=> Revert "Fix flaky test StreamingDataflowWorkerTest"

sdks/python/apache_beam/runners/worker/data_sampler.py, sdks/python/apache_beam/runners/worker/data_sampler_test.py, sdks/python/apache_beam/runners/worker/operations.py, sdks/python/apache_beam/runners/worker/sdk_worker_main.py
This enables exception sampling when either the "enable_data_sampling" or "enable_always_on_exception_sampling" experiment is present. This disables automatic exception sampling when "disable_always_on_exception_sampling" is given. …
=> Add flag to control automatic exception sampling in Python (disabled)

CHANGES.md, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Fix [CVE-2023-39320](https://security-tracker.debian.org/tracker/CVE-2023-39320) …
=> use go 1.21.1 for build

.github/workflows/beam_PreCommit_Java.yml
Found in https://github.com/apache/beam/pull/28434#issuecomment-1718278586
Also addressing https://github.com/apache/beam/pull/28075#issuecomment-1714652977
* Also upload human readable test reports on failure …
=> Fix Java PreCommit Action correct branch to run

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfig.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/BigtableChangeStreamAccessor.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/BigtableClientOverride.java
Adds `BigtableClientOverride` interface to provide a way to override client settings we need to change for testing.  …
=> Add mechanism to override bigtable client for testing

runners/samza/src/main/java/org/apache/beam/runners/samza/SamzaPipelineOptions.java, runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/GroupByKeyOp.java, runners/samza/src/test/java/org/apache/beam/runners/samza/runtime/GroupByKeyOpTest.java
This patch adds the `DoFnRunners.lateDataDroppingRunner()` in SamzaRunner GroupByKey translation so we allow users to drop late data in windowing when needed. Also add a boolean flag in SamzaPipelineOptions to turn it on/off. …
=> Allow dropLataData in GBK for SamzaRunner

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
=> [BEAM-28399] Ensure dataflow experiments are always set when dataflowflow runner is used.

CHANGES.md, sdks/go/pkg/beam/io/parquetio/parquetio.go, sdks/go/pkg/beam/io/parquetio/parquetio_test.go
Removes the `t reflect.Type` parameter from `parquetio.Write` and derives the element type from the input PCollection instead. Fixes #28490. …
=> [Go SDK]: Retrieve element type from input PCollection in parquetio.Write

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java, sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaTranslationTest.java, sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/LogicalTypes.java, sdks/python/apache_beam/io/external/xlang_jdbcio_it_test.py, sdks/python/apache_beam/io/jdbc.py
Part of #28359 (date and time support without breaking change); fixes #19715
* Add identifier to  URN for legacy Java logical types
* Implement JdbcIO logical type javasdk_date and javasdk_time in Python
* Add tests
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUIL …
=> Support legacy DATE and TIME logical types in xlang JdbcIO

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java
This PR addresses #28080 by refactoring the static [BigQueryIO.read(SerializableFunction)](https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.html#read-org.apache.beam.sdk.transforms.SerializableFunction-) to not need a try/catch when invoking the DatumReaderFactory.
The existing code first converted the TableSchema to a JSON string using BigQueryIO.JSON_FACTORY's toString method. This throws an IOException that the original code logged as a warning. A GenericDatumTransformer's constructor received that JSON string that was used to set a private Suppler property, called tableSchema. This Supplier property, when invoked, would convert the JSON string back to a TableSchema object.
This PR simplifies the code by creating a new …
=> Remove TableSchema to JSON conversion.

sdks/python/apache_beam/runners/render.py, sdks/python/apache_beam/runners/render_test.py
While trying to use the `RenderRunner`, I came across a few warts.
- It accepts a pipeline proto but doesn't use `run_portable_pipeline`
- Not 100% sure about this but it used `dotX` instead of `dot` for one of its subprocess calls
- `RenderOptions` couldn't be used with `.view_as` because the init-time validation
- The `RenderRunner` logging used the root logger instead of the module logger
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+sourc …
=> RenderRunner cleanup

.github/workflows/beam_PreCommit_GoPrism.yml, build.gradle.kts, sdks/go/README.md, sdks/go/cmd/prism/prism.go, sdks/go/pkg/beam/runners/prism/internal/environments.go, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go, sdks/go/pkg/beam/runners/prism/prism.go, sdks/go/test/build.gradle, sdks/go/test/integration/integration.go, sdks/go/test/run_validatesrunner_tests.sh
Add a github action precommit for the standalone prism runner. Standalone prism uses job specified environments (usually docker containers), by default.
* Updates the go run_validates_runner.sh test script. Ensure prism binary shuts down and cleans up afterwards. 
* Add gradle actions to invoke script as the prism runner.
* Add github action workflow to trigger as precommit. Copied from the GoPortable precommit workflow. https://github.com/apache/beam/blob/master/.github/workflows/beam_PreCommit_GoPortable.yml
* Check for docker manifest for image to avoid pull failures for unpushed images.
* Plumb Pipeline options through to workers for container provisioning.
* Filter out Xlang tests for prism, since it's not yet capable of them.
* Make prism use loopback mode by default for in-process …
=> [#28187] Add standalone prism validates runner precommit

website/www/site/content/en/documentation/io/built-in/google-bigquery.md
Found when looking at a number of Runner V2 pipelines that stream to BQ with Storage Write API (including #28168)
=> Updating Storage API Autosharding documentation to include that it doesn't work on Runner V2

sdks/python/apache_beam/dataframe/frames.py
Remove the one remaining Pandas append call for Pandas 2 compatability.
Partially fixes #27221
=> Remove internal series.append call from frames.py

sdks/java/container/boot.go
We set the Xmx to the recommended max value(32G) with set_recommended_max_xmx is enabled. Under 32G JVM enables CompressedOops. CompressedOops utilizes memory more efficiently, and has positive impact on GC performance and cache hit rate.  …
=> Sets recommended max Xmx 32G when set_recommended_max_xmx experiment is enabled

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile
Install kubectl latest directly and gauth plugin
Needed a up to date version of kubectl due to requirement for `kubectl wait` jsonpath support for a workflow …
=> update gcloud components in runner

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java
=> Revert "Remove TableSchema to JSON conversion."

sdks/python/apache_beam/dataframe/frames.py
One more removed_args that I missed before.
Umbrella issue: #27221
=> Remove inplace argument from set_axis for Pandas 2

sdks/python/apache_beam/dataframe/frames.py, sdks/python/apache_beam/dataframe/frames_test.py
Two changes here:
1) In 2.0, value_counts has different naming. See https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#value-counts-sets-the-resulting-name-to-count for more details.
2) Fix df.value_counts interaction of subset and dropna, discovered by a new
doctest failure. Previously we were dropping rows with NA in any column, not
just the columns of interest if subset was non-empty. 
Umbrella issue:  #27221
=> Fix value_counts for Pandas 2

CHANGES.md, sdks/python/apache_beam/io/gcp/bigquery_test.py, sdks/python/apache_beam/io/gcp/bigquery_tools.py, sdks/python/apache_beam/io/gcp/bigquery_write_it_test.py
Would like to get feedback on this approach. Marking the MR as draft because more tests would need to be added and I haven't run existing tests yet, either.
The purpose of this change is to get exceptions caught and re-raised [here](https://github.com/apache/beam/blob/26b77723445cf383365098b296b9db77409af94c/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L732-L740) to output rows to failed_rows rather than just causing a pipeline error. Outputting to failed_rows tag is necessary to avoid streaming pipelines that infinitely retry messages that result in these pipeline errors.
These exceptions cause infinite retries because [this self.bigquery_wrapper.insert_rows call](https://github.com/apache/beam/blob/26b77723445cf383365098b296b9db77409af94c/sdks/python/apache_beam/io/gcp/bigquery.py#L1 …
=> Return errors for insert_rows_json exceptions (#21080)

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java, sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/SchemaUtil.java
Marking `JdbcIO.inferBeamScheam()` and `SchemaUtil.BeamRowMapper()` as `public` in order to use them in the Jdbc Templates. …
=> Updating access modifiers for utility methods

sdks/python/apache_beam/ml/inference/vertex_ai_inference_it_test.py, sdks/python/test-suites/dataflow/common.gradle
Mark the Vertex AI IT tests as using tensorflow and add an extra check to ensure the dependency has been installed before running the test suite.  …
=> Add extra marks to VertexAI IT tests

sdks/python/apache_beam/yaml/standard_io.yaml, sdks/python/apache_beam/yaml/yaml_io.py
=> Add schema-aware text file reading and writing.

sdks/python/apache_beam/dataframe/frames.py
=> Remove deprecated week and weekofyear for Pandas 2

sdks/python/apache_beam/dataframe/frames_test.py
Came across this while trying to debug other things, but if a series has a non-unique index run_test would fail because ser.columns doesn't exist.
I guess none of our existing tests have non-unique indices for series.
=> Fix logic for _run_test in frames_test.py

sdks/python/apache_beam/transforms/external.py
Doing this so that we can identify the transform URN when looking at a pipeline DAG.
=> Label Python external SchemaTransform with its URN

sdks/typescript/package-lock.json, sdks/typescript/package.json, sdks/typescript/src/apache_beam/runners/dataflow.ts
* Bad dependbot upgrades.
* Missing experiments due to Python dataflow runner change. …
=> Typescript changes for Beam 2.51.0

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicImpulse.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicSequence.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageWriteIT.java
Until there is a consensus of #28272, let's get in the part not related to FILE_LOAD first, which fixes BigQueryIOStorageWrite  streaming tests currently using bounded source
Introduce PeriodicImpulse.stopAfter()
* Use it in streaming BigQueryIO integration test
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://gith …
=> Use unbounded source in BigQueryIOStorageWrite streaming tests

sdks/python/apache_beam/dataframe/frame_base.py, sdks/python/apache_beam/dataframe/frame_base_test.py
In Pandas 1, the `copy` arg always had a default of `True`, while in Pandas 2 the new copy-on-write mechanism means that `copy` defaults to `None`, which indicates "use the global copy_on_write setting". For Beam, copy-on-write should always be true, so just fill in the None defaults with True.
Umbrella issue: #27221
=> Change handling of copy=None defaults for Pandas 2

sdks/python/apache_beam/dataframe/frames_test.py
In Pandas 2, groupby().apply() will append group keys to an index that already has them in cases where the apply is really a transform (the resulting index is same as the incoming one). This is a change from Pandas 1.5.  
When running the original test with Pandas 1.5, we get the following warning:
```FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use
>>> .groupby(..., group_keys=False)
To adopt the future behavior and silence this warning, use 
>>> .groupby(..., group_keys=True)
df.groupby(['provider']).apply(lambda x: x)
```
So I set group_keys to False to retain the 1.5 behavior.
=> Fix test for new group keys behavior for Pandas 2

sdks/python/apache_beam/transforms/core.py, sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_mapping.md, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_mapping_test.py, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_test.py, sdks/python/apache_beam/yaml/yaml_udf_test.py
* Avoid the use of MetaProviders, which was always kind of hacky. We may want to remove this infrastructure altogether as it does not play nicely with provider inference.
* Split MapToFields into separate mapping, filtering, and exploding operations.
* Allow MapToFields to act on non-schema'd PCollections.
The various langauge flavors of these UDFs are now handled by a preprocessing step.  This will make it easier to extend to other langauges, including in particular possible multiple (equivalent) implementations of javascript to minimize cross-langauge boundary crossings.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips …
=> Refactor and cleanup yaml MapToFields.

.test-infra/jenkins/job_PostCommit_Python_CrossLanguage_Gcp_Dataflow.groovy, .test-infra/jenkins/job_PostCommit_Python_CrossLanguage_Gcp_Direct.groovy, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java, sdks/python/apache_beam/io/external/xlang_bigqueryio_it_test.py, sdks/python/apache_beam/io/gcp/bigquery.py, website/www/site/content/en/documentation/io/built-in/google-bigquery.md
Allow users to set a number of streams for the Storage Write API sink. 
Fixes #28587
Provides a workaround for issue in #28168
=> [Python BQ] Allow setting a fixed number of Storage API streams

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteSchemaTransformProviderIT.java, sdks/python/apache_beam/io/gcp/bigtableio.py, sdks/python/apache_beam/io/gcp/bigtableio_it_test.py
=> [Fix Python Bigtable dataloss bug] Stop unsetting timestamps of -1

.github/workflows/beam_PostCommit_BeamMetrics_Publish.yml
Recently the metrics job has failed sometimes due to an actions issue (https://github.com/apache/beam/actions/runs/6302595278)
This adds a scheduled job for 2 reasons:
1) If there are infra failures or other flakes on a given push, it will keep trying
2) If future problems arise, it will make it easier to determine when the problem started
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATU …
=> Run metrics job daily to catch any failed runs

CHANGES.md, website/www/site/content/en/blog/beam-2.49.0.md, website/www/site/content/en/blog/beam-2.50.0.md
Add bug #28632 to release notes
=> Add Bigtable xlang bug to release notes for versions 2.49.0 and 2.50.0

sdks/python/apache_beam/ml/inference/vertex_ai_inference_it_test.py, sdks/python/pytest.ini, sdks/python/test-suites/dataflow/common.gradle
Don't reuse it_postcommit tag in vertex ai tests so that we don't run it twice.
=> Fix Vertex AI postcommit suite to run the tests only once.

sdks/python/apache_beam/ml/inference/vertex_ai_inference_it_test.py, sdks/python/pytest.ini, sdks/python/test-suites/dataflow/common.gradle
This cherrypicks #28571 "Fix Vertex AI postcommit suite to run the tests only once" to release branch.
=> [release-2.51.0] Cherrypick #28571 to release branch.

contributor-docs/release-guide.md
These were just a level of indirection away, and I also inlined reasoning so the release manager can have a bigger picture idea of what they are doing without having to click through all the links.  …
=> Move Python dep upgrade instructions into release guide

sdks/python/apache_beam/examples/wordcount_it_test.py, sdks/python/container/run_validatescontainer.sh
This will give us the same level of confidence that we have with normal python containers.
Example arm tests - https://github.com/apache/beam/actions/runs/6283251262 (including [job running on arm](ntheon.corp.google.com/dataflow/jobs/us-central1/2023-09-22_14_34_35-16892955735525074437))
Example non-arm tests - https://github.com/apache/beam/actions/runs/6283252657 (tougher to pick out a job that definitely was from this run, maybe [this one](https://pantheon.corp.google.com/dataflow/jobs/us-central1/2023-09-22_14_00_55-7344145176816373684))
2 tests which use `prebuild_sdk_container_engine` don't work (which makes sense), so I special cased them:
https://github.com/apache/beam/blob/68cf802626a1ef7d41aadca13d009f0d1b609b33/sdks/python/apache_beam/examples/wordcount_it_test.py#L98-L105
We …
=> Run arm suite against all validates_container tests

website/www/site/content/en/documentation/io/connectors.md
GoogleAdsIO was added by @sjvanrossum at https://github.com/apache/beam/pull/27681, but it wasn't added to the list.
Fixing the gap here
=> Add GoogleAdsIO to the list of built-in connectors

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py, sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py, sdks/python/apache_beam/runners/portability/stager.py
Beam Dev SDK containers also include Beam SDK, which might be not the same as what users have locally when they submit a Dataflow pipeline. Provide an explicit error to make sure pipelines running with Dev SDKs  supply an SDK location. 
This was already a requirement before we switched to use external containers.
=> Require --sdk_location for Dataflow pipelines running with dev SDKs.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteSchemaTransformProviderIT.java, sdks/python/apache_beam/io/gcp/bigtableio.py, sdks/python/apache_beam/io/gcp/bigtableio_it_test.py
Cherry picking #28624 into 2.51.0
=> CP for #28624 into release 2.51.0 (Bigtable Python timestamp bug fix)

.github/workflows/beam_PostCommit_Java.yml
Postcommit java is failing due
```github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/checks/runs#create-a-check-run"}```
Looks like it needs write to checks api. This fixes that
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD …
=> add write to checks due to publish unit test result

learning/tour-of-beam/learning-content/introduction/introduction-concepts/pipeline-concepts/setting-pipeline/python-example/task.py
This example was mixing the with-statement style of doing pipelines with actually calling the run method. This changes the example to only use the with-statement, which is the most common style found in the documentation.
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedul …
=> Update example in Tour of Beam

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowWorkUnitClient.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WorkUnitClient.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/counters/NameContext.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkState.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Commit.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ComputationState.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ExecutionState.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/KeyCommitTooLargeException.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ShardedKey.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/StageInfo.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/WeightedBoundedQueue.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/BatchDataflowWorkerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowWorkUnitClientTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkStateTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/WeightBoundedQueueTest.java
StreamingDataflowWorker file is quite large. Opting to break out the inner static classes to a top level and introduce /streaming directory under the worker/ directory.  
There will be future changes to these classes to support direct path, and this change will make the files easier to work with.
includes some formatting changes required by spotless
Slowly switching to java.util.Optional instead of the google Optional.
r: @kennknowles 
To check …
=> break nested  classes out of StreamingDataflowWorker

sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionServiceSchemaTransformProvider.java, sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceSchemaTransformProviderTest.java
Just because schemas are compatible doesn't mean that they're identical (e.g. up to field ordering).
This is important as schema generation in Java is not always determanistic, so even if the payload is encoded with the exact schema that was previously provided it might not agree when the request comes in.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/be …
=> Ensure configuration schema used to decode configuration.

website/www/site/content/en/documentation/sdks/python-unrecoverable-errors.md, website/www/site/content/en/documentation/sdks/python.md, website/www/site/layouts/partials/section-menu/en/sdks.html
Add a site page to cover what we consider unrecoverable errors as part of the effort to reduce detection times.
Staged at https://apache-beam-website-pull-requests.storage.googleapis.com/28702/documentation/sdks/python-unrecoverable-errors/index.html
GitHub …
=> Create documentation page for Python SDK unrecoverable errors

sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
Adding experiments is now also done in [run_pipeline](https://github.com/apache/beam/blob/80311628c27ea68704f46d9f5e6edea6466dfcb3/sdks/python/apache_beam/runners/dataflow/dataflow_runner.py#L362) . `apply()` seems like a wrong place to do this.
GitHub Actions …
=> Better flag documentation.

examples/notebooks/beam-ml/README.md, examples/notebooks/beam-ml/per_key_models.ipynb
✨ [RENDERED](https://github.com/damccorm/beam/blob/703e9c64c3d067ec35038a511bdc92bc4270aef4/examples/notebooks/beam-ml/per_key_models.ipynb) ✨ 
This should not be merged until 2.51 is released, it was tested by replacing the beam install with a clone/install from the Beam repo though.
Resolves #27628 …
=> Add notebook for per key models

.github/workflows/beam_PostCommit_Python.yml, .github/workflows/beam_PreCommit_Java_GCP_IO_Direct.yml
Reverts apache/beam#28719
We have disabled the offending test that causing OOM. And the highmem cluster seems missing some credential and causing this workflow continuously failing: #28803
=> Revert "assign highmem runner to beam_PostCommit_Python and to beam_PreCommit…"

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java
Fix error expectations in SpannerChangeStreamErrorTest. 
UNAVAILABLE / ABORTED codes are always retried, so they should have the short retry settings only. Otherwise, if you use the default timeout (i.e. 2 hours), the test will timeout.
=> Fix SpannerChangeStreamErrorTest.java and stop disabling tests

sdks/python/apache_beam/dataframe/frames.py
Fix the way that categorical dtypes were checked. This was raising deprecation warnings.
=> Fix dtype usage

sdks/python/apache_beam/dataframe/frames.py
In Pandas 2.1 the method argument is deprecated, and they replaced the default None with lib.no_default (which then gets translated to None after a deprecation warning). We don't use it anyway so just take it as None directly.
=> Fix method argument handling for pandas 2.1

examples/notebooks/beam-ml/automatic_model_refresh.ipynb
Fixes: https://github.com/apache/beam/issues/28773 …
=> Add num_workers and save_main_session flag to auto_model_refresh notebook

sdks/python/apache_beam/dataframe/frames_test.py
Starting with Pandas 2.1, observed=False is deprecated as the default for groupby, and raises warnings when grouping on categoricals. Explicitly set observed=False in these tests to stop that.
=> Add observed=False to be explicit for Pandas 2.1

sdks/python/apache_beam/dataframe/frames.py, sdks/python/apache_beam/dataframe/frames_test.py
In Pandas 2.1, applymap is deprecated and map is the replacement. Fix it here for those
=> Add map function and skip applymap for 2.1

CHANGES.md, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
Fixes #28793 in the way suggested in https://github.com/apache/beam/issues/28793#issuecomment-1745361478:
- `BoundedReadEvaluatorFactory#getInitialInputs` may still calculate a `bytesPerBundle` of `0` (e.g. when `targetParallelism > estimatedBytes`); but
- `BigtableSource#split` will interpret it as `1` in order to not violate the `checkArgument()` in https://github.com/apache/beam/blob/71c8459633ec86e576eca080a26be9f42474ecb2/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java#L1623-L1626 …
=> BigtableIO: Force minimum value of `desiredBundleSizeBytes` to be 1

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
The intended project version source of truth is [gradle.properties](https://github.com/apache/beam/blob/161cd6b1c8de9a2a68b6aaf81cc5e13f827b6f50/gradle.properties#L33). It is set statically to either `-SNAPSHOT` when on a non-terminal commit or non-`SNAPSHOT` on terminal RC commits.
This change eliminates one place where that source of truth is both duplicated and violated.
Discovered when this behavior broke 2.51.0 RC builds by adding `-SNAPSHOT` to them.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-j …
=> Do not rewrite project version in BeamModulePlugin

.github/workflows/beam_LoadTests_Python_GBK_Dataflow_Batch.yml, .github/workflows/beam_LoadTests_Python_GBK_Dataflow_Streaming.yml, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Batch_2GB_of_100B_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Batch_2GB_of_100kB_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Batch_2GB_of_10B_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Batch_fanout_4_times_with_2GB_10-byte_records_total.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Batch_fanout_8_times_with_2GB_10-byte_records_total.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Streaming_2GB_of_100B_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Streaming_2GB_of_100kB_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Streaming_2GB_of_10B_records.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Streaming_fanout_4_times_with_2GB_10-byte_records_total.txt, .github/workflows/load-tests-job-configs/python_GBK_Dataflow_Streaming_fanout_8_times_with_2GB_10-byte_records_total.txt
".github/workflows/beam_LoadTests_Python_GBK_Dataflow_Batch.yml"
".github/workflows/beam_LoadTests_Python_GBK_Dataflow_Streaming.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_GBK_Dataflow_Batch/
https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_GBK_Dataflow_Streaming/
Example runs:
beam_LoadTests_Python_GBK_Dataflow_Batch.yml https://github.com/magicgoody/beam/actions/runs/6400975104
beam_LoadTests_Python_GBK_Dataflow_Streaming.yml https://github.com/magicgoody/beam/actions/runs/6401367865 …
=> Github Workflow Replacement for Jenkins Jobs, beam_LoadTests_Python_GBK_Dataflow_*

sdks/python/.pylintrc, sdks/python/apache_beam/typehints/decorators_test.py
Enables the typevar-name-mismatch pylint check and skips the check on the one instance the rule is violated within the Python sdk (which was already skipped for mypy checks.)
Fixes #28241 …
=> Enable typevar-name-mismatch check

sdks/python/apache_beam/transforms/ptransform.py, sdks/python/apache_beam/yaml/json_utils.py, sdks/python/apache_beam/yaml/yaml_io.py, sdks/python/apache_beam/yaml/yaml_io_test.py
This makes https://github.com/apache/beam/issues/28694 more useful. …
=> [YAML] Add JSON parsing to PubSub IO.

sdks/python/apache_beam/io/avroio.py, sdks/python/apache_beam/io/avroio_test.py, sdks/python/apache_beam/pvalue.py, sdks/python/apache_beam/typehints/schemas.py, sdks/python/apache_beam/yaml/standard_io.yaml, sdks/python/apache_beam/yaml/yaml_provider.py
This fixes https://github.com/apache/beam/issues/28852 …
=> [YAML] Schemify avroio and add a yaml provider.

.github/workflows/build_release_candidate.yml, release/src/main/scripts/download_github_actions_artifacts.py
This directly ports the logic in `build_release_candidate.sh` to the GitHub Action in `build_release_candidate.yml …
=> Add python wheel staging to GitHub Actions build_release_candidate

sdks/python/apache_beam/runners/worker/sdk_worker_main.py
Update state cache size from 0 to 100 MB. This is test how state cache is impacting Beam pipelines in the test suites.
Refactoring changes are tracked in the PR https://github.com/apache/beam/pull/28781 and will be merged before release cut of 2.52.0 or this change will be reverted.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-inf …
=> [Python]Update state cache size to 100 MB

website/www/site/content/en/documentation/io/built-in/google-bigquery.md
- Updated the description regarding failed rows for Storage Write API.
- Made `PCollection` formatting consistent.
fixes #27298 
Current [documentation](https://beam.apache.org/documentation/io/built-in/google-bigquery/#exactly-once-semantics) mentions `WriteResult.getFailedInserts` does not work for Storage Write API. But now `WriteResult.getFailedStorageApiInserts` will return the failed rows for Storage Write API. 
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.m …
=> Update BigQueryIO Documentation

sdks/python/apache_beam/io/gcp/bigquery.py
Catch EOFError along with StopIteration to align with fastavro's latest release 1.8.4
Fixes #28811  …
=> Catch EOFError along with StopIteration

sdks/python/apache_beam/pipeline.py, sdks/python/apache_beam/transforms/display.py, sdks/python/apache_beam/yaml/main.py
This will be useful in case the UI wants to display it.  …
=> Populate top-level display data in yaml main.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, runners/flink/flink_runner.gradle, sdks/java/maven-archetypes/examples/build.gradle, sdks/java/maven-archetypes/gcp-bom-examples/build.gradle
=> Fix sourceJar task dependencies

sdks/python/apache_beam/runners/dataflow/internal/names.py, website/www/site/content/en/documentation/runtime/environments.md
Updating to include the dependency updates in #28880
=> Update Dataflow containers

runners/flink/flink_runner.gradle
Follow up of #28900
Specifically, this change missing a `.get()`: https://github.com/apache/beam/pull/28900/files#diff-f6fd92149aed337db34a59ef88ca8ed1c7d9aa2371d48e4eb592c36b453eadceR49
causing `"${sourceOverridesBase}/main/java"` generates a very long directory …
=> Fix buildDirectory

build.gradle.kts, runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/TransformUpgrader.java, sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java, sdks/java/transform-service/docker-compose/.env, sdks/java/transform-service/docker-compose/docker-compose.yml, sdks/java/transform-service/launcher/build.gradle, sdks/java/transform-service/launcher/src/main/java/org/apache/beam/sdk/transformservice/launcher/TransformServiceLauncher.java, sdks/java/transform-service/launcher/src/test/java/org/apache/beam/sdk/transformservice/launcher/TransformServiceLauncherTest.java, sdks/java/transform-service/src/main/java/org/apache/beam/sdk/transformservice/ExpansionService.java, sdks/java/transform-service/src/test/java/org/apache/beam/sdk/transformservice/ExpansionServiceTest.java, sdks/python/apache_beam/utils/transform_service_launcher.py, sdks/python/expansion-service-container/boot.go
Also performs following fixes.
* Transform service controller waits for expansion services to start before performing expansion or discovery operations.
*  When expansion requests fail, transform service controller sends back a detailed error with errors from all expansion services instead of just sending the last failure.
Issue is https://github.com/apache/beam/issues/26833. …
=> Updates the Transform Service to accept Python extra packages through the Java API

sdks/go/pkg/beam/runners/prism/internal/web/web.go
Add in User counters, user Distributions, and msec samples to Prism UI.
Also pre-sort the transform IDs before topological sort so display remains stable on refreshes.
I wasn't expecting the PTransforms keys in the metrics to be the human readable unique names, and instead expected the global ids from the transforms map. This is either prism, or SDK dependent. Any later fix would be to make it consistent for all uses. …
=> [prism] Add user counters and msec metrics to prism UI.

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
(Tongue in cheek) Spotless caught me when I did not end the first sentence of the Javadoc with a a dot, but it did not tell me I had an extra space before the `</a>` tag at the end of the sentence.
The extra space was introduced in https://github.com/apache/beam/pull/28798 …
=> Remove unnecessary a space character that got through Javadoc CI ;)

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/UnboundedReadFromBoundedSource.java, runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/UnboundedReadFromBoundedSourceTest.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSources.java
This is another case of #20970 (harmless error logs with gRPC leak). 
`BigQueryIO.read()` with `Method.DIRECT_READ` in Dataflow **streaming** jobs can cause Dataflow to output the gRPC leak error logs like below. 
This is because `getCheckpointMark()` in `BoundedToUnboundedSourceAdapter`  calls `init()` where `residualSource` field is updated, but it missed closing old `residualSource`, which caused a leak of `ResidualSource#reader` closing. The `reader` in the stacktrace below is `BigQueryStorageStreamReader`.  Not closing `BigQueryStorageStreamReader` causes the gRPC leak error logs. 
Error mesasge:
``` 
*~*~*~ Previous channel ManagedChannelImpl{logId=9, target=bigquerystorage.googleapis.com:443} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait …
```
=> [#20970] Fix gRPC leak by closing ResidualSource at BoundedToUnboundedSourceAdapter.Reader#init() in Dataflow worker

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Upgrade due to GitHub security advisory: GHSA-55g7-9cwv-5qfv
=> Bump snappy-java version to 1.1.10.4

.github/workflows/beam_LoadTests_Java_CoGBK_Dataflow_Batch.yml, .github/workflows/beam_LoadTests_Java_CoGBK_Dataflow_V2_Batch_JavaVersions.yml, .github/workflows/beam_LoadTests_Java_CoGBK_Dataflow_V2_Streaming_JavaVersions.yml, .github/workflows/beam_LoadTests_Java_CoGBK_SparkStructuredStreaming_Batch.yml, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_Batch_100b_Multiple_Keys.txt, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_Batch_100b_Single_Key.txt, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_Batch_10kB.txt, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_Batch_2MB.txt, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_V2_Streaming_Java_100b_Multiple_Keys.txt, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_V2_Streaming_Java_100b_Single_Key.txt, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_V2_Streaming_Java_10kB.txt, .github/workflows/load-tests-job-configs/java_CoGBK_Dataflow_V2_Streaming_Java_2MB.txt, .github/workflows/load-tests-job-configs/java_CoGBK_SparkStructuredStreaming_Batch_100b_Multiple_Keys.txt, .github/workflows/load-tests-job-configs/java_CoGBK_SparkStructuredStreaming_Batch_100b_Single_Key.txt, .github/workflows/load-tests-job-configs/java_CoGBK_SparkStructuredStreaming_Batch_10kB.txt, .github/workflows/load-tests-job-configs/java_CoGBK_SparkStructuredStreaming_Batch_2MB.txt
".github/workflows/beam_LoadTests_Java_CoGBK_Dataflow_Batch.yml"
".github/workflows/beam_LoadTests_Java_CoGBK_Dataflow_V2_Batch_JavaVersions.yml"
".github/workflows/beam_LoadTests_Java_CoGBK_Dataflow_V2_Streaming_JavaVersions.yml"
".github/workflows/beam_LoadTests_Java_CoGBK_SparkStructuredStreaming_Batch.yml"
Jenkins Jobs:
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Java_CoGBK_Dataflow_Batch/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Java_CoGBK_Dataflow_V2_Batch_Java17/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Java_CoGBK_Dataflow_V2_Batch_Java11/
https://ci-beam.apache.org/view/PerformanceTests/job/beam_LoadTests_Java_CoGBK_Dataflow_V2_Streaming_Java11/ …
=> Add GitHub Workflow Replacements for Jenkins job_LoadTests_Java_CoGBK

sdks/python/apache_beam/yaml/yaml_io.py, sdks/python/apache_beam/yaml/yaml_io_test.py
=> [YAML] Avro format for PubSub.

examples/notebooks/beam-ml/automatic_model_refresh.ipynb, examples/notebooks/beam-ml/mltransform_basic.ipynb, examples/notebooks/beam-ml/per_key_models.ipynb
Editing RunInference notebooks to prepare for DevSite import
R: @damccorm 
R: @AnandInguva  …
=> Editing notebooks to prepare for DevSite import

.github/actions/gradle-command-self-hosted-action/action.yml
Right now, some workflows are broken because they don't include a `\` at the end of their input arguments when calling our gradle action. This shouldn't need to be required. This fixes the flow by reordering arguments so that they are all continuous.
Running dataframes precommit that has no slash at end - https://github.com/apache/beam/actions/runs/6512587812/job/17690530384
Running precommit java which does have a slash at the end - https://github.com/apache/beam/actions/runs/6512628719/job/17690656217 …
=> reorder args to avoid newline issues

sdks/java/io/rrio/build.gradle, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponseio/ApiIOError.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponseio/RequestResponseIO.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponseio/CallerTest.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponseio/SetupTeardownTest.java
This PR addresses #28934 by stubbing the RequestResponseIO transform. The point of this PR is to get this class out early so that documentation and functionality could be developed as [tasks](https://github.com/apache/beam/issues?q=is%3Aissue+is%3Aopen+%5BRRIO%5D) complete.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_ …
=> [RRIO] Stub the RequestResponseIO transform

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
The default for fetchSize is 50000 (https://github.com/apache/beam/blob/master/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java#L372), which is not even supported by some databases. 
For example, DB2 limits to 32767 (source: https://knowledge.informatica.com/s/article/000205468?language=en_US). 
This change will not only allow performance tuning when needed, but will enable usage of partitions on specific databases.
=> [JdbcIO] Allow fetchSize to be set for partitioned reads

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/container/license_scripts/dep_urls_java.yaml
Quite a lot of manual digging through transitive deps of the libraries listed at https://github.com/googleapis/java-cloud-bom/tree/v26.23.0 to figure out some of these :-(
Then @bvolpato tells me I should just run this :-)
```
cd /tmp; wget https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/26.23.0/libraries-bom-26.23.0.pom -O base.pom && mvn help:effective-pom -f base.pom -Doutput=effective.pom && cat effective.pom | grep -v 'dependencyManagement' > cleanup.pom && mvn dependency:tree -f cleanup.pom
```
(still manual scraping to match up versions)
Fixes #28379 …
=> Update Google Cloud Java Libraries BOM from 26.22.0 to 26.23.0

.github/workflows/README.md
=> Fix concurrency groups in Readme

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/python/apache_beam/ml/transforms/base.py
Take a look at https://github.com/apache/beam/issues/29022 …
=> Add no-cache-dir to tox install

examples/notebooks/beam-ml/README.md
Update the Beam ML readme to include the new notebooks …
=> Update the Beam ML readme

sdks/java/core/src/main/java/org/apache/beam/sdk/values/Row.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadSchemaTransformConfiguration.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubWriteSchemaTransformConfiguration.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubWriteSchemaTransformProvider.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadSchemaTransformProviderTest.java
=> [YAML] Java PubSubIO

sdks/python/setup.py
For internal tests, tar ball is created by copybara and it doesn't include gen_protos.py. In the PR https://github.com/apache/beam/pull/28385, we provide hard RuntimeError when error originates from gen_protos.py. By pass the error when gen_protos is not found. 
FYI, externally built sdist contains gen_protos.py but for internal imports, we don't. Since it is a build time dependency for building proto files, it is not necessary to raise RuntimeError while installing tar ball using `pip install <>.tar.gz` …
=> Log warning when gen_protos is not found

sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponseio/CallShouldBackoff.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponseio/CallShouldBackoffBasedOnRejectionProbability.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponseio/CallShouldBackoffBasedOnRejectionProbabilityTest.java
This PR fixes #28936 by defining the interface and default implementation based on https://sre.google/sre-book/handling-overload/. …
=> [RRIO] [Call] Create CallShouldBackoff and default implementation

sdks/java/io/rrio/build.gradle, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/ApiIOError.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/CacheRead.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/CacheWrite.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/CallShouldBackoff.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/CallShouldBackoffBasedOnRejectionProbability.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Caller.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/SetupTeardown.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeExecutionException.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeQuotaException.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeTimeoutException.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/package-info.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CallShouldBackoffBasedOnRejectionProbabilityTest.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CallerTest.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/SetupTeardownTest.java
This PR closes #29039 by renaming the  the `:sdks:java:io:rrio` package to `org.apache.beam.io.requestresponse`. …
=> Rename rrio package

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
This adds two new config input options to `BigtableIO.Read` and `BigtableIO.Write` so users can set the application profile used by the Bigtable client, without having to use other methods that are now deprecated.
This fixes #28862 
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&ev …
=> Add withAppProfileId to BigtableIO Read and Write

sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/ThrottleDequeue.java
This PR addresses #28932 by creating a stub of a PTransform that dequeues elements at a fixed rate. …
=> [RRIO] [Throttle] stub the dequeue transform

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/JsonUtils.java
Comments suggested that org.json was in sync with libraries-bom, but when analyzing through
```
cd /tmp; wget https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/26.22.0/libraries-bom-26.22.0.pom -O base.pom && mvn help:effective-pom -f base.pom -Doutput=effective.pom && cat effective.pom | grep -v 'dependencyManagement' > cleanup.pom && mvn dependency:tree -f cleanup.pom
```
We can see that it brings a much newer (and not in the CVE range) version:
```
[INFO] --- dependency:3.6.0:tree (default-cli) @ libraries-bom ---
[INFO] com.google.cloud:libraries-bom:pom:26.22.0
[INFO] +- com.google.cloud:google-cloud-bigquery:jar:2.31.1:compile
[INFO] |  +- org.json:json:jar:20230618:compile
```
=> [Security] Bump org.json:json due to CVE-2022-45688

sdks/python/apache_beam/ml/gcp/recommendations_ai_test_it.py
Fixes #29054
This test has been permared on GHA but actually due to an issue on the test itself. The teardownClass is always attempted and fail if missing gcp permission, even though all test cases skipped. …
=> Fix Python PreCommit GHA recommendations_ai teardown

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java, sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java
Follow up on https://github.com/apache/beam/pull/28999
Support to fetchSize was added, but missed the Schema Provider to be able to use it through xlang (thanks @Abacn!)
=> [JdbcIO] Add fetchSize to the schema provider for partitioned reads

website/www/site/content/en/get-started/quickstart-go.md
Remove command prompts from [Go quickstart](https://beam.apache.org/get-started/quickstart-go/) commands
Fixes #20948 …
=> Remove command prompts from Go  quickstart commands

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
mitigate #28957
A testing PR #23785 found a stuck test path
```
Class org.apache.beam.runners.dataflow.worker.StreamingDataflowWorkerTest
testActiveThreadMetric[0: [streamingEngine=false]]
org.junit.runners.model.TestTimedOutException: test timed out after 600 seconds
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorkerTest.testActiveThreadMetric(StreamingDataflowWorkerTest.java:2850)
...
```
this would make the test under this test class timeout after 600s, instead the whole test suite hanging indefinitely
Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly …
=> TImeout StreamingDataflowWorkerTest when test stuck

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/CoderProviders.java, sdks/java/core/src/main/java/org/apache/beam/sdk/coders/DefaultCoder.java, sdks/java/io/splunk/build.gradle, sdks/java/io/splunk/src/main/java/org/apache/beam/sdk/io/splunk/HttpEventPublisher.java, sdks/java/io/splunk/src/main/java/org/apache/beam/sdk/io/splunk/SplunkEvent.java, sdks/java/io/splunk/src/main/java/org/apache/beam/sdk/io/splunk/SplunkEventCoder.java, sdks/java/io/splunk/src/main/java/org/apache/beam/sdk/io/splunk/SplunkEventWriter.java, sdks/java/io/splunk/src/main/java/org/apache/beam/sdk/io/splunk/SplunkIO.java, sdks/java/io/splunk/src/test/java/org/apache/beam/sdk/io/splunk/SplunkEventCoderTest.java, sdks/java/io/splunk/src/test/java/org/apache/beam/sdk/io/splunk/SplunkEventTest.java, sdks/java/io/splunk/src/test/java/org/apache/beam/sdk/io/splunk/SplunkEventWriterTest.java, sdks/java/io/splunk/src/test/java/org/apache/beam/sdk/io/splunk/SplunkIOTest.java
This PR makes the following improvements/bug fixes,
* Add support for Splunk 'fields' metadata
* Add checks to make sure url is valid.
* Fix WRITE_LATENCY_MS metric to report milliseconds instead of nanoseconds.
* Fix gzip compression in HttpEventPublisher.
* Fix coder issues for SplunkEvent. …
=> Fix various issues in SplunkIO 

sdks/python/apache_beam/yaml/README.md, sdks/python/apache_beam/yaml/pipeline.schema.yaml
Slightly stricter definitions for catching more errors, as well as avoding the use of anyOf which often makes it difficult to deduce what the true error is.
This does mean a pipeline must have a transform (or source/sink) block rather than simply be itself a list of transforms.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BU …
=> [YAML] Improved pipeline schema definition.

sdks/python/apache_beam/yaml/main.py
This PR adds support for specifying a GCS YAML file when running `main.py`
i.e. `python -m apache_beam.yaml.main --pipeline_spec_file="gs://path/to/yaml/file"` …
=> [yaml] support gcs location for main.py yaml input file

sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java, sdks/java/core/src/test/java/org/apache/beam/sdk/util/HistogramDataTest.java
fixes #29085 HistogramData.java and HistogramDataTest.java has few typos. In this PR, I am correcting them. 
[![Build …
=> Fix typos in HistogramData.java and HistogramDataTest.java

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineOptions.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperatorTest.java, website/www/site/layouts/shortcodes/flink_java_pipeline_options.html, website/www/site/layouts/shortcodes/flink_python_pipeline_options.html
Currently, drain operation does not work for flink pipelines when RequiresStableInput annotation is used. This is caused by buffered data not being processed before the final checkpoint operation that causes watermark hold related exception. This PR addresses this issue by processing the buffer before the final checkpoint completes. More context in https://github.com/apache/beam/issues/28554. …
=> [flink] Flush buffer during drain operation for requiresStableInput operator

.github/workflows/beam_Metrics_Report.yml
Adds metrics report to GH actions. 
Waiting on approval for the mail action. …
=> adding metrics report

runners/flink/1.12/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/SourceTestCompat.java, runners/flink/1.14/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/SourceTestCompat.java, runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkRunnerResult.java, runners/flink/src/main/java/org/apache/beam/runners/flink/metrics/FlinkMetricContainer.java, runners/flink/src/main/java/org/apache/beam/runners/flink/metrics/FlinkMetricContainerBase.java, runners/flink/src/main/java/org/apache/beam/runners/flink/metrics/FlinkMetricContainerWithoutAccumulator.java, runners/flink/src/main/java/org/apache/beam/runners/flink/metrics/ReaderInvocationUtil.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSource.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderBase.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSource.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSourceReader.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSource.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java, runners/flink/src/test/java/org/apache/beam/runners/flink/metrics/FlinkMetricContainerTest.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/TestCountingSource.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderTestBase.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSourceReaderTest.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReaderTest.java
This is an updated version of the abandonned https://github.com/apache/beam/pull/25753.
I simply rebased master in the original PR and reviewed the code.
fixes https://github.com/apache/beam/issues/25741 …
=> Add MetricsContainer support to the Flink sources.

sdks/python/apache_beam/options/pipeline_options.py, sdks/python/apache_beam/pipeline.py, sdks/python/apache_beam/pipeline_test.py
Motivating Issue
----------------
The python SDK requires users specify a unique label for every transform. Often times, the first time a transform is applied there is a default label that will be unique, but any future applications of the transform will require that the user specify a new and unique label. This can be quite tedious since there are many (?) scenarios where a user won't actually care about the labels. A couple scenarios that came up in my experience:
- Writing unit tests with multiple `assert_that()`s requires unique label for each assert
- Writing a pipeline that branches and applies the same transform to each branch
- Writing a linear pipeline where I want to reuse the same transform (e.g. `LogElements` or `Deduplicate`)
Change Summary
------------------
This change adds …
=> [PYTHON] Add new `--auto_unique_labels` option to StandardOptions 

runners/google-cloud-dataflow-java/build.gradle
After #27287, similar issue still happens for sometimes Dataflow test fails at teardown, e.g.
```
> Task :runners:google-cloud-dataflow-java:cleanUpDockerJavaImages
Untagged: us.gcr.io/apache-beam-testing/java-postcommit-it/java:20231024141605
Untagged: us.gcr.io/apache-beam-testing/java-postcommit-it/java@sha256:c8142402aa8db2ea907d19e58a522ca1c0baf0003efd6d9d33127886186d0b63
ERROR: (gcloud.container.images.untag) Image could not be found: [us.gcr.io/apache-beam-testing/java-postcommit-it/java:20231024141605]
> Task :runners:google-cloud-dataflow-java:cleanUpDockerJavaImages FAILED
```
see  https://github.com/apache/beam/actions/runs/6628112374/job/18004534799
while #27287 tolerated the non-zero return value for third command line in `cleanUpDockerJavaImages` task. This PR tolerates the …
=> IgnoreExitValue for dataflow runner cleanUpDockerJavaImages

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java
Exceptions in JvmInitializers were being printed in the STDOUT by the FnHarness, so handled/displayed on Dataflow as an info log:
This change should help making errors more obvious, and allow users to leverage Error Reporting.
I still kept `e.printStackTrace();` in case there was someone relies on looking at errors on STDOUT/STDERR (happy to remove if seen as a bad practice).
=> Change level of initialization exception to error, make errors obvious

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
It's possible to pass in parameters in properties files (mainly [sdk.properties](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/resources/org/apache/beam/sdk/sdk.properties)) with an empty string, which shouldn't be allowed. Adding a precondition should correct this issue.
I'm not sure if it's possible to write a test to check for the preconditions, since all the Dataflow runner unit tests populate 'name' and 'version' based on the [name default value](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/util/ReleaseInfo.java#L84) and the above `sdk.properties` file respectively, however, I did perform the following to validate correctness:
1. Ran all the Java Dataflow runner tests, setting `version=` in `sdk.properties`. The …
=> [Java][Dataflow Runner] Add precondition to make sure userAgent name and version are not empty

sdks/python/apache_beam/typehints/native_type_compatibility_test.py
Adds some extra tests around enumeration type hinting in collections, also covers the built-in `frozenset`case that didn't have a test. 
Part of #29135 …
=> Add extra typehinting tests

.gitignore, .test-infra/mock-apis/README.md, .test-infra/mock-apis/infrastructure/kubernetes/echo/configmap.yaml, .test-infra/mock-apis/infrastructure/kubernetes/echo/deployment.yaml, .test-infra/mock-apis/infrastructure/kubernetes/echo/kustomization.yaml, .test-infra/mock-apis/infrastructure/kubernetes/echo/service.yaml, .test-infra/mock-apis/infrastructure/kubernetes/redis/kustomization.yaml, .test-infra/mock-apis/infrastructure/kubernetes/redis/redis-values.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/base/configmap.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/base/deployment.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/base/kustomization.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/123079b5-1e58-4b28-a185-66702e2b10c3/configmap.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/123079b5-1e58-4b28-a185-66702e2b10c3/deployment.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/123079b5-1e58-4b28-a185-66702e2b10c3/kustomization.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/e1064224-3671-46fe-971d-47887fac3d4c/configmap.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/e1064224-3671-46fe-971d-47887fac3d4c/deployment.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/e1064224-3671-46fe-971d-47887fac3d4c/kustomization.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/f588787b-28f8-4e5f-8335-f862379daf59/configmap.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/f588787b-28f8-4e5f-8335-f862379daf59/deployment.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/f588787b-28f8-4e5f-8335-f862379daf59/kustomization.yaml, .test-infra/mock-apis/infrastructure/terraform/.terraform.lock.hcl, .test-infra/mock-apis/infrastructure/terraform/artifact_registry.tf, .test-infra/mock-apis/infrastructure/terraform/cluster.tf, .test-infra/mock-apis/infrastructure/terraform/iam.tf, .test-infra/mock-apis/infrastructure/terraform/prerequisites.tf, .test-infra/mock-apis/infrastructure/terraform/provider.tf, .test-infra/mock-apis/infrastructure/terraform/variables.tf
This PR closes #28709 with Kubernetes manifests and terraform to deploy a Mock quota-aware API and dependent resources:
- Provisions a private auto-pilot GKE cluster with minimally permissive custom service account
- Deploys a quota Refresher service for three UUID identified quotas
- Deploys the Echo service
- Exposes the Echo service via an internal LoadBalancer with a private IP …
=> [RRIO] [Testing] Infrastructure-as-Code deploys API & dependencies

sdks/go/examples/minimal_wordcount/minimal_wordcount.go
Remove anon functions from minimal wordcount example. They got missed in the move to prism as default.
Anonymous functions don't work on any portable runner and can't be detected meaningfully at runtime.
Fixes #28981  …
=> [#28981] remove anon functions from minimal wordcount

sdks/go/pkg/beam/runners/prism/internal/jobservices/server.go
Increase the Job Management + associated front end services to accept larger messages/pipelines.
Fixes #29147
[![Build …
=> [#29147] increase received message size to max for Job Management.

sdks/go/pkg/beam/io/fileio/example_test.go
Fixes #29185 and removes the anonymous function used in the `fileio.ReadMatches` doc example. …
=> [Go SDK]: Remove anonymous function from fileio.ReadMatches example

examples/notebooks/beam-ml/run_custom_inference.ipynb, sdks/python/apache_beam/ml/inference/base.py
This broke https://colab.sandbox.google.com/github/apache/beam/blob/master/examples/notebooks/beam-ml/run_custom_inference.ipynb#scrollTo=7f841596-f217-46d2-b64e-1952db4de4e7
since the custom model handler doesn't set `_env_vars` …
=> Don't assume env vars are set in model handler

CHANGES.md, sdks/java/io/google-cloud-platform/build.gradle, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/FirestoreOptions.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/FirestoreStatefulComponentFactory.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/it/FirestoreTestingHelper.java
address https://github.com/apache/beam/pull/27256#issuecomment-1745564522
> This option has a risk of conflicting with other PipelineOptions classes (not to mention non-PipelineOptions arguments)
R: @kellen @SabaSathya …
=> Rename --host to --fireStoreHost

runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkCombineFn.java, runners/spark/src/test/java/org/apache/beam/runners/spark/translation/SparkCombineFnTest.java
=> [runners-spark] Do not set accTimestamp to null in SparkCombineFn (#28256)

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Fixes CVE-2023-5072
libraries-bom 26.23.0 is still at `20230618`, but libraries-bom 26.26.0, which we'll likely go next, is already at `20231013`.
No breaking changes reported https://github.com/stleary/JSON-java/releases/tag/20231013
=> [Security] Bump org.json version due to CVE-2023-5072

sdks/java/container/build.gradle, sdks/java/container/common.gradle, sdks/python/container/build.gradle, sdks/python/container/common.gradle
Fixes #29220
When `:sdks:java:container:goBuild` executes before  `:sdks:python:container:goBuild`, XVR tests fail at build python container due to missing launcher binary because both launcher shared the same gradle configuration.
* Rename sdkHarnessLauncher in java container and python container gradle project …
=> Fix launcher artifact gradle configuration name conflict

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProvider.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProviderTest.java, sdks/python/apache_beam/yaml/standard_io.yaml
=> [YAML] - Kafka write and RAW format

sdks/python/apache_beam/testing/analyzers/io_tests_config.yaml, sdks/python/apache_beam/testing/analyzers/load_test_perf_analysis.py, sdks/python/apache_beam/testing/analyzers/perf_analysis_utils.py
This PR adds ability to run regression checks against Beam IO load tests.
Below is the command to run this,
```
python3 apache_beam/testing/analyzers/load_test_perf_analysis.py --config_file_path=apache_beam/testing/analyzers/io_tests_config.yaml
```
We can automate runs for these regression checks by adding a GH workflow in a separate PR.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATU …
=> Add ability to run performance regression checks on Beam IO Load tests.

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java
=> Improve Coder encode/decode documentation.

sdks/python/apache_beam/ml/inference/huggingface_inference.py
=> [Python] Add device param to HuggingFacePipelineModelHandler

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Tested by run `./gradlew spotlessApply`
The issue is similar to https://github.com/diffplug/spotless/issues/1572 but as https://github.com/apache/kafka/pull/13205 noted, new version of spotless plugin dropped support of java8. The workaround  is needed for current spotless plugin run in gradle 8 …
=> Fix ./gradlew spotlessApply fail groovy check

sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
=> Upgrade protobuf version to remediate a leak.

sdks/go/pkg/beam/core/graph/graph.go, sdks/go/pkg/beam/core/graph/scope.go, sdks/go/pkg/beam/core/runtime/contextreg/contextreg.go, sdks/go/pkg/beam/core/runtime/contextreg/contextreg_test.go, sdks/go/pkg/beam/core/runtime/graphx/translate.go, sdks/go/pkg/beam/core/runtime/graphx/translate_test.go, sdks/go/pkg/beam/core/runtime/graphx/tree.go, sdks/go/pkg/beam/pipeline.go
* Adds PTransform annotation plumbing through context.Context
* Lays groundwork to do the same for PTransform Display Data.
* Deferred to another PR: Doing the same for environments. 
* Punted from this PR since it's a much broader change to install.  
Working on #23893. …
=> [#23893] Support composite scope transform metadata

sdks/java/container/common.gradle, sdks/python/container/common.gradle
=> Fix XVR test fail python docker

.test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/echo-10-per-1s-quota/configmap.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/echo-10-per-1s-quota/deployment.yaml, .test-infra/mock-apis/infrastructure/kubernetes/refresher/overlays/echo-10-per-1s-quota/kustomization.yaml, .test-infra/mock-apis/src/main/go/test/integration/echo/echo_test.go, .test-infra/mock-apis/src/main/go/test/integration/vars.go
This PR addresses #28932, #28930, and #28926 with a Refresher configuration that sets a quota at 10 elements per 1s rate. …
=> [RRIO] [Testing] Add a 10/1s Quota Refresher

.github/workflows/build_release_candidate.yml, release/src/main/scripts/download_github_actions_artifacts.py
Both these workflows were failing. The java source was accidentally modified as part of the pyproject.toml work, this reverts it back to its previous state. The python source never worked and had a bunch of issues that needed fixing.
Example successful workflow - https://github.com/apache/beam/actions/runs/6754402902/job/18361839573 …
=> Fix staging java source/python source

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
This is a doc only PR that updates `BigQueryIO` documentation.
Upserts, in streaming, with STORAGE_AT_LEAST_ONCE work also using CREATE_IF_NEEDED if a primary key is specified. Actually, the code examples included in the documentation were already using CREATE_IF_NEEDED, I guess the bits of doc touched in this PR were not updated when the examples were written.
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+br …
=> [BigQueryIO] Upserts work with CREATE_IF_NEEDED -- doc only PR

sdks/python/apache_beam/runners/dataflow/internal/names.py
Updates container image tag used by Dataflow runner with dev SDK. 
This will help with importing changes to setup.py, which updated protobuf version.
=> Update dev container tags.

sdks/go/pkg/beam/runners/direct/direct_test.go, sdks/go/pkg/beam/runners/prism/README.md, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/execute_test.go, sdks/go/pkg/beam/runners/prism/internal/handlecombine.go, sdks/go/pkg/beam/runners/prism/internal/handlepardo.go, sdks/go/pkg/beam/runners/prism/internal/handlerunner.go, sdks/go/pkg/beam/runners/prism/internal/preprocess.go, sdks/go/pkg/beam/runners/prism/internal/preprocess_test.go, sdks/go/pkg/beam/runners/prism/internal/separate_test.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go
Add robust fusion heuristics to Prism's graph Pre-processing, leading to improved performance when it's enabled. In this PR it's enabled by default, but in a subsequent PR, it'll be enabled by default in the stand alone command, and generally all variants except the "test" variant.
* Largely cribbed from Python fn_api_runner/translations.py, which is based on two main heuristics: Avoiding side input conflicts, and indicating situations where a producing transform must not be fused with a consuming transform.
* Updated handlers and fact computation to use return structs.
* Add simple benchmarks for the Go Direct Runner, and Prism to demonstrate fusion was effective.
* Clean up no-longer necessary exec side override for environments (handled in handlers now).
* Fix Bug in ProcessBundle …
=> [prism] Add fusion.

sdks/go.mod, sdks/go.sum, sdks/go/pkg/beam/io/natsio/common.go, sdks/go/pkg/beam/io/natsio/example_test.go, sdks/go/pkg/beam/io/natsio/helper_test.go, sdks/go/pkg/beam/io/natsio/write.go, sdks/go/pkg/beam/io/natsio/write_option.go, sdks/go/pkg/beam/io/natsio/write_test.go
Addresses #29000 and implements a Write transform for writing to NATS.
The Read transform is more involved and will be in a separate PR. …
=> [Go SDK]: Create natsio.Write transform for writing to NATS

.github/workflows/deploy_release_candidate_pypi.yaml
These were needed to get it working. Successful run - https://github.com/apache/beam/actions/runs/6778059487/job/18422857586 …
=> A couple small fixes to the pypi deploy action

sdks/python/apache_beam/typehints/native_type_compatibility.py, sdks/python/apache_beam/typehints/native_type_compatibility_test.py, sdks/python/apache_beam/typehints/typehints.py, sdks/python/apache_beam/typehints/typehints_test.py
Adds a new internal Beam representation for type hints that are _exactly_ `collections.abc.Collections` types. Allows for more general type hinting guarantees. 
Part of #29135 …
=> Add support for collections.abc.Collection type hints

sdks/python/apache_beam/io/azure/integration_test/docker-compose.yml, sdks/python/apache_beam/io/hdfs_integration_test/docker-compose.yml
Adds lower MTU (1460) to python docker-compose files due to GKE having lower mtu than default. 
Partly fixes #29214  …
=> add mtu to docker comose files in python test suite

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimatorTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java
fixes #29312 
Adding support for pg Jsonb datatype in SpannerIO …
=> Adding support for pg Jsonb datatype in SpannerIO

.github/workflows/beam_PreCommit_Spotless.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, runners/google-cloud-dataflow-java/arm/build.gradle, runners/google-cloud-dataflow-java/build.gradle, runners/google-cloud-dataflow-java/examples/build.gradle
#29353 introduced several test failures. However, I would argue a forward fix because these failures was due to existing problem of build.gradle get revealed
- Fixes #29386 . It get revealed because these test were missed previously, and then exposes a problem in runner-cloud-dataflow-java/example/build.gradle that is affected by #19191. It was not found during the work of #29353 because I use a custom tempLocation so the default (having a trailing slash) was not used.
- Fixes `./gradlew :buildSrc:spotlessApply`.  Apparently `./gradlew spotlessCheck` does not run buildSrc's spotless check, nor `./gradlew spotlessApply` applies to buildSrc. #29353 introduced spotless violation that not caught by beam precommit test, and failing internal tests on import. This may originate from gradle …
=> Followup #29353 fix several test failures

sdks/python/apache_beam/__init__.py, sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
Address #29392 until we upgrade to newer version of pyarrow.
Note that `import apache_beam` already imports pyarrow, therefore invoking the patch in top-level `__init__.py`
=> Invoke pyarrow_hotfix to alleviate concerns due to CVE-2023-47248.

contributor-docs/release-guide.md, website/www/site/content/en/blog/validate-beam-release.md
Fixes #29405 and updates the documentation for RC image tags to reflect the recently used tags. …
=> Update image tag pattern for RCs in release docs

it/conditions/src/main/java/org/apache/beam/it/conditions/ConditionCheck.java
I want to use the checker in a specific way, and we didn't expose the `success` or `message`:
```java
assertThat(pubsubCheck.check().isSuccess()).isTrue();
```
Right now we only have `pubsubCheck.get()` but it's not expressive enough (and wouldn't return the message if it failed).
=> Add getters to CheckResult in IT framework

sdks/java/harness/build.gradle
Bug: https://github.com/apache/beam/issues/29413
After https://github.com/apache/beam/pull/27851, user code that depends on versions newer than Avro 1.8.2 are having problems running on Dataflow.
For example in https://github.com/GoogleCloudPlatform/DataflowTemplates, where we moved on to Avro 1.11.3, there were incompatibility errors:
> Caused by: java.io.InvalidClassException: org.apache.avro.specific.SpecificRecordBase; local class incompatible: stream classdesc serialVersionUID = -1463700717714793795, local class serialVersionUID = 189988654766568477
and
> Caused by: java.lang.NoSuchMethodError: 'boolean org.apache.avro.generic.GenericRecord.hasField(java.lang.String)'   com.google.cloud.teleport.v2.transforms.FormatDatastreamRecordToJson.getMetadataIsDeleted(FormatDatastreamRecordToJs …
=> Mark Avro as provided in harness JAR

sdks/python/apache_beam/runners/worker/data_plane.py
Log when elements for an instruction are missing in data plane more than 5 minutes. This can help surface processing inefficiency between an SDK and a runner.
=> Add logging in data plane code when processing is stuck waiting on data for an instruction.

it/common/src/main/java/org/apache/beam/it/common/PipelineLauncher.java
Parameterized / parallel tests have been suffering with flakes because of job name collision when only suffixed with timestamp:
```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
POST https://dataflow.googleapis.com/v1b3/projects/{PROJECT}/locations/us-central1/flexTemplates:launch
{
"code": 409,
"errors": [
{
"domain": "global",
"message": "(78f666ea16e50f79): There is already an active job named test-jdbc-to-pubsub-20231115093811749. If you want to  submit a second job, try again by setting a different name.",
"reason": "alreadyExists"
}
],
"message": "(78f666ea16e50f79): There is already an active job named test-jdbc-to-pubsub-20231115093811749. If you want to  submit a second job, try again by setting a different name.",
"status": "ALREADY_EXISTS"
} …
```
=> Add random chars as the job name suffix by default on IT, avoid name collision

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/it/BigtableChangeStreamIT.java
BigtableChangeStreamIT explicitly specifies a start time that is sent to the server. Sometimes, the test code runs so fast that a small discrepancy in system clock between the test runner and Bigtable backend results in missing results.
For example
Time since epoch. There's a 10ms difference between system clocks.
Test runner: r=1000
Bigtable server: b=990
1. Test runner sets start time to 1000 (r=1000, b=990)
1. Test runner sends a write to Bigtable (r=1000, b=990)
1. Bigtable receives the write at 999 and records the write time (r=1009, b=999)
1. Test runner sends a ReadChangeStreamRequest at 1010 (r=1010, b=1000)
1. Bigtable receives ReadChangeStreamRequest at 1003 and returns changes starting at 1000. (r=1013, b=1003)
The write was recorded at 999, so Bigtable does not return the …
=> Make BigtableChangeStreamIT less flaky by adding a short sleep

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java
* Cherry pick two previous commits on migrating gcs client
The two commits are merged into one:
* Reapply "Replace StorageV1 client with GCS client (#28079)" (#28721)
* added project parameter to apiclient
* Initialze storage client with project from pipeline option.
---------
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.m …
=> Fix stuck nexmark streaming

sdks/python/apache_beam/io/gcp/gcsio.py
This value was changed in PR #29360 to 1000, which led to internal test failure. …
=> Revert the value of MAX_BATCH_OPERATION_SIZE in gcsio

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java
* We added the a new Distribution metric to record the raw message size in KafkaIO read. 
* The metric will be available for both code paths of KafkaIO read, i.e. legacy code path and SDF code path.
* We also added one unit test for each of the code path. 
GitHub …
=> Collect metric of message size distribution in KafkaIO read.

sdks/python/apache_beam/pvalue.py, sdks/python/apache_beam/transforms/core_test.py
Right now, if you have a transform with multiple outputs, the tagged outputs lose the boundedness value of their input and default to always be bounded. This was discovered in #29196 with the Partition transform. This fixes the problem.
Example of my test failing before my change (after first commit, before second commit on this PR) - https://github.com/apache/beam/actions/runs/6944498801/job/18891751771?pr=29506
The test is now passing in CI.
Fixes #29196
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-j …
=> Propagate correct boundedness when using multiple outputs

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
We noticed a consistent increase in Kafka consumer lag, especially with topics that had higher message traffic when we use Flink Runner. Our investigation revealed that the lag was related to how Apache Beam's **UnboundedSourceWrapper** and **KafkaUnboundedReader** were handling Kafka partitions. We found that for topics with lower traffic, the processing thread would wait unnecessarily, causing a lag in processing higher traffic topics. To address this We created adaptive timeout on KafkaUnboundReader. 
More detailed explanation done by Intuit team also too. Blog post is old but it is even applicable current master 
https://antonio-si.medium.com/how-intuit-debug-consumer-lags-in-apache-beam-22ca3b39602e
Please help me to merge this change. We used this solution on production. We dont …
=> Kafka adaptive timeout implementation to handle empty topic cases

it/conditions/src/main/java/org/apache/beam/it/conditions/ConditionCheck.java, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
Provides a quick way to troubleshoot / go to the affecting job when an IT fails.
Also improved the wording around unmet checks. They are not failed until the last poll happened, so renamed to "not met"
=> Improve actionability on IT errors (with Dataflow job URL)

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
This PR fixes #29512 bumping the grpc_version to 1.59.0. …
=> Bump grpc_version dependency

.github/workflows/README.md, .github/workflows/beam_PostCommit_Javadoc.yml
Following https://github.com/apache/beam/tree/master/.github/workflows#testing-workflow-updates to test.
Fixes https://github.com/apache/beam/issues/26445
Tested this using my own fork: 
The job ran fine: https://github.com/liferoad/beam/actions/runs/6914434714/job/18812289459
The generated html now has the canonical link. One example is: …
=> add canonical link into javadocs when running post commit

sdks/go/pkg/beam/io/fileio/read_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/handlecombine.go, sdks/go/pkg/beam/runners/prism/internal/handlecombine_test.go, sdks/go/pkg/beam/runners/prism/internal/handlepardo.go, sdks/go/pkg/beam/runners/prism/internal/preprocess.go, sdks/go/pkg/beam/runners/prism/internal/preprocess_test.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/util/pubsubx/pubsub_test.go
Fix error in prism's fusion handling. Re-instates fusion.
Instead of passing the consuming transform ID to get the downstream side inputs, we passed the PCollection ID, causing the computation to fail. Ultimately, the hangs were because there was a stage that depended on it's own produced side input.
Adds unit sufficient testing to avoid replicating the issue, and fixes the issue.
Exported fields on `link` and `fusionFacts` types to let them be compared for diffs by cmp. 
Adds additional debug logging for the resulting hang that was occurring.
(Long due to the unit tests, and necessary renames, the actual fix is a single line that I've commented to point out.)
---
Addendum: There was another bug in prism that when combined with fusion prevented one of the xlang tests from passing. In …
=> [prism] Fix downstream side input computations.

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java
=> Change StateBackedIterable to implement ElementByteSizeObservableIterable avoiding iteration to estimate observe bytes.

CHANGES.md, sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIO.java, sdks/java/io/clickhouse/src/main/javacc/ColumnTypeParser.jj, sdks/java/io/clickhouse/src/test/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIOTest.java
Support for [LowCardinality](https://clickhouse.com/docs/en/sql-reference/data-types/lowcardinality) for ClickHouse. …
=> Clickhouse support low cardinality

contributor-docs/release-guide.md
Right now, this shows up as a jumbled mess in the docs.
Before:
After: …
=> Fix rendering of playground deployment steps

sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/coders/AvroCoder.java
`useReflectApi` is inverted on one `AvroCoder` factory method
=> Respect useReflectApi parameter

sdks/java/core/src/main/java/org/apache/beam/sdk/testing/JsonMatcher.java
This PR addresses #20507 by replacing JsonMatcher's use of the SuppressWarnings nullness annotation with:
- Apply `final` to constructor initialized field
- Apply the `@MonotonicNonNull` annotation to a late initialized field `actualMap` that is checked for nullness using `checkStateNotNull`. …
=> Remove SuppressWarnings nullness from JsonMatcher

sdks/python/apache_beam/options/pipeline_options.py
Adds a warning log for unknown pipeline option.
Part of https://github.com/apache/beam/issues/28402 …
=> Add warning for unknown pipeline options

sdks/java/io/hadoop-common/src/main/java/org/apache/beam/sdk/io/hadoop/SerializableConfiguration.java
Fixes https://github.com/spotify/scio/issues/5099
use another variable `confMutated` to track cache validity to avoid NPE in any case, while keep the ability to run writeExternal in parallel (which is known slow code path)
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-inf …
=> Fix NPE due to racing condition in hadoop.SerializableConfiguration

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java
https://github.com/googleapis/gapic-generator-java/pull/1473 is resolved so we can set waitTimeout on the top level. Clean up the todo.  …
=> chore: clean up BigtableIO client creation code

runners/flink/src/main/java/org/apache/beam/runners/flink/CreateStreamingFlinkView.java
See https://github.com/apache/beam/issues/29547 for context …
=> Fix windowed singleton side inputs

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
```
java.lang.UnsupportedOperationException
at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:268)
at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:1341)
at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:198)
at org.apache.beam.sdk.Pipeline.run(Pipeline.java:321)
at org.apache.beam.sdk.Pipeline.run(Pipeline.java:307)
```
- ~[ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to …
=> Fix UnsupportedOperationException because of ImmutableCollection.add

CHANGES.md, sdks/python/apache_beam/io/gcp/bigquery.py, website/www/site/content/en/blog/beam-2.52.0.md
=> Fix small doc issues

CHANGES.md, model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto, runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java, runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/EnvironmentsTest.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java, runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/DefaultJobBundleFactory.java, runners/java-job-service/src/main/java/org/apache/beam/runners/jobsubmission/InMemoryJobService.java, sdks/java/expansion-service/build.gradle, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionServiceOptions.java, sdks/python/apache_beam/pipeline.py, sdks/python/apache_beam/runners/dataflow/dataflow_runner.py, sdks/python/apache_beam/runners/portability/expansion_service.py, sdks/python/apache_beam/runners/portability/expansion_service_main.py, sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py, sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py, sdks/python/apache_beam/runners/portability/local_job_service.py, sdks/python/apache_beam/transforms/environments.py, sdks/python/apache_beam/transforms/external.py, sdks/python/apache_beam/utils/subprocess_server.py, sdks/python/apache_beam/utils/subprocess_server_test.py
This is accomplished by re-using the expansion service subprocesses as the workers themselves.  …
=> Allow local runners to execute arbitrary cross language pipelines without Docker.

sdks/java/io/rrio/build.gradle, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Repeater.java, sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeRemoteSystemException.java, sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RepeaterTest.java
This PR closes #28926 by:
- Defining a Repeater interface
- Implementing a default Repeater implementation using exponential backoff …
=> [RRIO] [Call] Implement the Repeater

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableService.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteOptions.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImplTest.java
Batcher#closeAsync already sends out remaining elements and wait on them to finish before closing. Calling closeAsync let us set a timeout on the future and it should not take longer than the operation timeout. 
Another hang seems to come from calling service.close() in tearDown. Since we create the service in startBundle, closing the service in finishBundle addresses the issue. …
=> fix: have a timeout on the wait when closing BigtableIO#Writer

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/BatchSpannerRead.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/NaiveSpannerRead.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/ReadOperation.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
It is sometimes possible for Spanner reads to fail while reading the result of a query. In this case the exception rarely has any information about the query that triggered the failure. 
Add error logging to include the ReadOperation (SQL query or table read) when the read fails. 
Additionally adds some javadoc to document unused options. 
Fixes #29638
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Ama …
=> SpannerIO add more logging when Reads fail

model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto, runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/MultimapSideInput.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/FakeBeamFnStateClient.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/MultimapSideInputTest.java, sdks/python/apache_beam/runners/portability/fn_api_runner/execution.py, sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py, sdks/python/apache_beam/runners/worker/bundle_processor.py
The ability to perform point lookups for multi-map side inputs is great for maps that are too large to fit into memory, but can be very inefficient in requiring an entire state request per key for small maps.
This change adds an optional protocol to request an entire map as a stream of key-values in one (possibly paginated) API call, and uses this to bulk pre-fetch an initial set of values from the map before falling back to point lookups.
To …
=> More efficient map side inputs for small maps.

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderBase.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplitEnumerator.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSourceReader.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderTestBase.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSourceReaderTest.java
* added position to FlinkBoundedSource checkpoint
Fixes #29558  …
=> [runners-flink] #29558 emit watermark before source shutdown

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/BatchDataflowWorkerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowWorkUnitClientTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContextTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingSideInputDoFnRunnerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingSideInputFetcherTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/logging/DataflowWorkerLoggingInitializerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkStateTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/WeightBoundedQueueTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/sideinput/SideInputStateFetcherTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/WindmillStreamPoolTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkerMetadataStreamTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/StreamingEngineClientTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/WindmillStreamSenderTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateCacheTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternalsTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateReaderTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/budget/EvenGetWorkBudgetDistributorTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/budget/GetWorkBudgetRefresherTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/budget/GetWorkBudgetTest.java
Mitigate #28957 (happened again)
We are experiencing stuck Java PreCommit caused by `:runner:google-cloud-dataflow-java:worker:test`. Some recent streaming worker changes may have caused this (). Although Gradle tasks can set a task level timeout, it does not help to identify which exact test stuck. To do it, need to set a timeout rule for each test class.
This PR adds this rule to all dataflow legacy worker test class has ever been changed since Beam 2.50.0. …
=> Add per test timeout in recently changed dataflow legacy worker tests

CHANGES.md, sdks/go/pkg/beam/io/natsio/end_estimator.go, sdks/go/pkg/beam/io/natsio/end_estimator_test.go, sdks/go/pkg/beam/io/natsio/example_test.go, sdks/go/pkg/beam/io/natsio/helper_test.go, sdks/go/pkg/beam/io/natsio/read.go, sdks/go/pkg/beam/io/natsio/read_option.go, sdks/go/pkg/beam/io/natsio/read_test.go, sdks/go/pkg/beam/io/natsio/time_policy.go, sdks/go/pkg/beam/io/natsio/time_policy_test.go, sdks/go/pkg/beam/io/natsio/watermark_estimator.go, sdks/go/pkg/beam/io/natsio/watermark_estimator_test.go, sdks/go/pkg/beam/io/natsio/write_test.go
Implements a `natsio.Read` transform for reading from NATS JetStream. Fixes #29000. …
=> [Go SDK]: Implement natsio.Read transform for reading from NATS

sdks/python/apache_beam/ml/transforms/tft.py, sdks/python/apache_beam/ml/transforms/tft_test.py
Add a column name to the output vocab file to distinguish vocab file name for multiple columns in a single transform.
Make the default args to be same as the tft operations so that if the user doesn't provide any value, tft will take care of it instead of us doing it.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS …
=> Add suffix for vocab files in tft transforms

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImplTest.java
Optimize the segement reader so we're actually fetching more rows when the buffer size is low.
`future` in segment reader is only reset to null in `waitReadRowsFuture()` method. This means that on the 2nd page of the read, we set the future to `fetchNextSegment();` (line 343), but we never checks if the future is resolved until the buffer is empty (line 345). Adding the check on line 334 will make sure we move the results to the buffer and reset future to null. So next time when the buffer size is small we send the request for the next page.  …
=> fix: optimize segment reader

sdks/python/apache_beam/runners/worker/sdk_worker.py
After protobuf v4 upgrade we are seeing SDK crashes in #27330 .
A possible reason might be that micro-protobuf protos objects are more sensitive to unsafe concurrent modifications, leading to process memory corruption.
This change should reduce the risk of concurrent modifications.
=> Deep-copy the process bundle descriptor when creating a new bundle processor.

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/ExecutionStateSampler.java, runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/ExecutionStateTracker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/ActiveMessageMetadata.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionContext.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSampler.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkState.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ComputationState.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionContextTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSamplerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/FakeWindmillServer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkStateTest.java, runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto
Tracks the amount of time dofn processing takes for individual messages run on the StreamingDataflowWorker.
Changes:
- modifies the DataflowExecutionStateTracker to record processing times per message per DoFn.
- When the tracker transitions state, the time spent in state is recorded in an in-memory map (keyed by DoFn name) 
- Trackers are now identified by shardingkey-worktoken.
- adds a DataflowExecutionStateSampler (extension of existing ExecutionStateSampler) that is responsible for managing ExecutionStateTrackers over the lifetime of the StreamingDataflowWorker.
- When trackers get removed (ie, processing has completed for the thread / work item it was responsible for), synthesized summary statistics from the tracker are held onto inside of the sampler until the work item has been …
=> Per DoFn latency instrumentation

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/SplittableParDo.java, runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/SplittableParDoNaiveBounded.java, runners/core-java/src/main/java/org/apache/beam/runners/core/OutputAndTimeBoundedSplittableProcessElementInvoker.java, runners/core-java/src/main/java/org/apache/beam/runners/core/SimpleDoFnRunner.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Create.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFnOutputReceivers.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFnTester.java, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/GlobalWindow.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/CreateTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/DoFnInvokersTest.java, sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamZetaSqlCalcRel.java, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java, sdks/java/io/pulsar/src/test/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFnTest.java, sdks/java/io/sparkreceiver/2/src/test/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFnTest.java
This adds the ability (which we don't expect to use much, and not really at all from users) to output a full windowed value. This allows a proper implementation of Reshuffle in the SDK and could be useful in some other testing scenarios.
Pulling this off #28853 for simpler review while working out final issues there.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.co …
=> Add outputWindowedValue capability to Java SDK

sdks/go/pkg/beam/runners/prism/internal/engine/data.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/engine_test.go, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/execute_test.go, sdks/go/pkg/beam/runners/prism/internal/handlepardo.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/preprocess.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go, sdks/go/pkg/beam/runners/prism/internal/urns/urns.go, sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go, sdks/go/test/integration/primitives/state.go
Adds State API handling to Prism.
In particular:
* Stateful stages are forced to be fusion roots.
* Persisted state is added to engine.stageState
* Tentative state is held onto in worker.Bundle, and mutated there as needed.
* Add eager key extracting parsing for stateful receiving stages.
* Very inefficient at present.
* Implements FnAPI handling for:
* BagState
* MultimapState
* MultimapKeysState
* Unified handling for the two main state kinds
* WRT/ Garbage collection and copying to bundles, and interaction.
* Added a variable for State Unit Tests to switch between to stateful execution modes:
* Greedily pack bundles with all data and state.
* One Element Per Key.
* One Key per Bundle.
* One Element per Key, one key per Bundle. 
Resolves #28543
Thank you for …
=> [#28543][prism] Implement State API

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionContext.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSampler.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionContextTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSamplerTest.java
Cherry pick of #29786 to fix a bug …
=> getProcessingTimesByStep returns a modifiable map (#29786)

sdks/java/core/src/main/java/org/apache/beam/sdk/providers/GenerateSequenceSchemaTransformProvider.java
Right now, this is breaking the java precommit because it is causing a spotbugs failure.
Example: https://github.com/apache/beam/actions/runs/7245514035/job/19735677563
From the report:
```
FS | Format string should use %n rather than \n in org.apache.beam.sdk.providers.GenerateSequenceSchemaTransformProvider.description()
  | Bug type VA_FORMAT_STRING_USES_NEWLINE (click for details)In class org.apache.beam.sdk.providers.GenerateSequenceSchemaTransformProviderIn method org.apache.beam.sdk.providers.GenerateSequenceSchemaTransformProvider.description()Called method String.format(String, Object[])Format string "Outputs a PCollection of Beam Rows, each containing a single INT64 number called "value". The count is produced from the given "start"value and either up to the given "end" or until …
```
=> Fix GenerateSequenceSchemaTransformProvider formatting

sdks/python/container/boot.go
Corrects a nil pointer usage when Python containers are built through `processArtifactsInSetupOnlyMode()`
Fixes #29803 …
=> [#29803] Fix nil pointer access in logRuntimeDependencies

sdks/python/apache_beam/runners/dataflow/internal/names.py
=> Update dataflow container tag

.github/workflows/build_wheels.yml
Right now, building wheels is failing because it tries to upload an artifact for the multi-arch wheels with the same name as the regular wheels. Previously this worked silently and one was dropped. This fixes that issue by appending `-aarch64` to the multi-arch wheels and makes sure that it gets uploaded to gcs as well.
Example succeeding now - https://github.com/apache/beam/actions/runs/7266076148 …
=> Build and publish multi-arch wheels separately from main wheels

runners/portability/java/build.gradle
These tests used to work because a request for the multimap_keys_side_input state type used to return the empty set rather than (more correctly) returning an error that this was unsupported (which in turn cause these empty side input tests to serendipitously pass).
The bug getting these to actually work is at https://github.com/apache/beam/issues/20878 …
=> Remove failing multimap key iteration tests.

.github/workflows/build_release_candidate.yml
It looks like this action builds a docker container and copies in the working directory. That means that absolute paths don't work for inputs, but relative paths do. Got past this step on my fork with this change. …
=> Fix javadoc action in build-release-candidate

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/internal/CustomSources.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineDebugOptions.java
Dataflow Streaming: Add a pipeline option `--desiredNumUnboundedSourceSplits` to override the desired number of splits for CustomSources
=> Dataflow Streaming: Add a pipeline option `--desiredNumUnboundedSourceSplits`

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Cherry-picking https://github.com/apache/beam/pull/29864 to release-2.53.0
=> [Cherry-pick] Update google-api-services-storage to match libraries-bom

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/RemoveSafeDeltaCounterCell.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/RemoveSafeDeltaCounterCellTest.java
Dataflow Streaming harness's metrics container will store `per worker counters` in a new `RemoveSafeDeltaCounterCell`.
For the new `PerWorkerMetrics` we want to support dynamically creating metrics that may not live the lifetime of the job, therefore we need to implement garbage collection for stale metrics.
E.g. We want to support BigQuery Metrics on a per-bigquery-table basis. If the pipeline uses dynamic destinations to write to 100 tables at 12:00 and at 15:00 is only writing to a few tables, the underlying MetricsContainer should not hold on to metrics for all 100 tables.
In`RemoveSafeDeltaCounterCell` metric updates and deletions are handled atomically - using `ConcurrentHashMap::compute` and `ConcurrentHashMap::remove` respectively - ensuring safe garbage collection. …
=> Use RemoveSafeDeltaCounterCell for PerWorker counters

sdks/go/pkg/beam/core/runtime/exec/translate.go, sdks/go/pkg/beam/core/runtime/exec/window.go, sdks/go/test/integration/integration.go, sdks/go/test/integration/primitives/timers.go, sdks/go/test/integration/primitives/timers_test.go
Add event time timer validation tests.
Execute both with bounded, and unbounded modes incase runners execute them differently (namely dataflow).
Fix bug in handling MapWindows, which couldn't map from Global Windows to GlobalWindows properly due to a quirk in the SDK's Window Coder + KV handling.
Pre-Work for #29772
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com …
=> [#29772][Go SDK] Add EventTime Timer tests.

sdks/go/pkg/beam/core/runtime/exec/translate.go, sdks/go/test/integration/integration.go, sdks/go/test/integration/primitives/timers.go
Fix exec side transform identification using the global transformID and not the "UniqueName". The error occurred prior to the FnAPI becoming solid ~4 years ago, or sufficient understanding to root case it at the time.
The Go SDK has been "refering" to transforms incorrectly when communicating back to the runner, which largely affects things like metrics. This was noticable in state and timers since only Dataflow implemented additional translations to the Go SDK approach, which was to use the "UniqueName" from the transforms.
This fix allows enabling additional tests against Spark and Flink runners for state and timers, and presumably fixes handling of metrics.
Pre-cursor to #29772, since it doesn't make sense to try and maintain the transform identification name handling error in Prism, …
=> [#29848][Go SDK] Fix exec side transform identification.

runners/flink/flink_runner.gradle, runners/flink/job-server/flink_job_server.gradle, runners/samza/src/test/resources/ExpectedDag.json, sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Reshuffle.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java
This fixes the Reshuffle default implementation to preserve all metadata and be a true no-op, whereas before it did not preserve the pane info.
Regarding update compatibility, my understanding of runners that have long-lived streaming jobs and perform updates, as of this writing:
- Flink: overrides Reshuffle
- Samza: overrides Reshuffle
- Dataflow v1: overrides Reshuffle
- Dataflow v2: executes default implementation
I went ahead and used the update compatibility flag anyhow just in case, so it can be reverted to exactly the old implementation on demand.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make …
=> Fix Reshuffle implementation in Java SDK

sdks/java/core/src/main/java/org/apache/beam/sdk/options/PipelineOptionsFactory.java
This pr aims to fix a classloader leak caused by ThreadLocal in PipelineOptionFactory. The threadlocal for DESERIALIZATION_CONTEXT cannot be removed and will eventually cause meatspace oom in Flink Jobmanager, which has been reported by several users https://github.com/apache/beam/issues/29890, https://github.com/apache/beam/issues/25510.
We can remove the ThreadLocal and use `DefaultDeserializationContext.copy` instead.
=> fix memory leak caused by ThreadLocal in PipelineOptionFactory

sdks/java/extensions/protobuf/build.gradle, sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteUtils.java, sdks/java/extensions/protobuf/src/test/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteUtilsTest.java, sdks/java/io/kafka/build.gradle, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProvider.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProviderTest.java, sdks/python/apache_beam/yaml/standard_io.yaml
- Include the option of sending the protobuf schema as string not only as a file descriptor
addresses #28664
[![Build …
=> [YAML] - Kafka Proto String schema

sdks/go/pkg/beam/core/timers/timers.go, sdks/go/pkg/beam/runners/prism/internal/coders.go, sdks/go/pkg/beam/runners/prism/internal/engine/data.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/engine_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/timers.go, sdks/go/pkg/beam/runners/prism/internal/handlepardo.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/preprocess.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go, sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go, sdks/go/pkg/beam/runners/prism/internal/worker/bundle_test.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go, sdks/go/test/integration/integration.go
Updates Prism to support EventTime Timers.
Fixes a bug in Go SDK timer handling unset watermark holds would have the wrong default hold. They should default to the firing time.
Timer implementation tracked in #29772.
Largely handles event time timers by treating them as data elements in the processing, with the goal of minimizing unique handling of timers vs data.
Timers with the same event time must always sort *after* data elements with the same event time, so they can be reasonably be consolidated when firing.
Since only a single timer can be set for a [window, user key, timerfamily, tag] tuple we track the last set EventTime + Hold. This avoids scanning the element queue for a key every time a timer is written at the expense that more timers are retained in memory (a "spend RAM to …
=> [#29772][prism] Handle EventTime Timers.

sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/metrics.go, sdks/go/pkg/beam/runners/prism/internal/stage.go
Return the total element count to the progress loop, and use as part of the split computation.
This avoids prism being hyper aggressive at splitting SDFs, and but still splits a bundle when stuck.
While out of scope for this PR, the total element count will monotonically increase during the bundle's lifetime, and will indicate if *any* progress is being made in the bundle, not simply at the root transform. (Within Beam's domain of course, since we don't have a way to measure external progress.) eg. We could track the progress at the last few ticks and only split if progress dips below our estimated progress.
Fixes #29180 …
=> [#29180][prism] Return total element count to progress loop. Split less aggressively.

runners/portability/java/build.gradle, runners/samza/job-server/build.gradle, runners/spark/job-server/spark_job_server.gradle, runners/spark/spark_runner.gradle
Mitigates #29973 but I will leave the issue open because the tests are just being disabled because the runners do not preserve reshuffle metadata …
=> sickbay new reshuffle test on runners that do not support it

playground/infrastructure/logger.py
Beam Playground currently outputs a ton of info messages when you run a python example. In my experience with showing people the examples, new users got a bit overwhelmed by the logging and it made it harder to pick out the actual expected input.
I tried to change the log level here to just WARNING for stdout. I looked a little at the playground local deployment docs but got a bit overwhelmed. I'd appreciate if someone with more experience with playground local deployments could give this a review / test, as I don't expect to make many changes like this so I'm not sure it's worth figuring it out for my own environment
=> Remove INFO from playground python logger

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternalsTest.java
These were attempting to reproduce a bug that ended up being in the test pipeline, but they seem worthwhile keeping to improve coverage. …
=> Additional tests for windmill OrderedListState implementation.

sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java, sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOReadTest.java
When processing a CRLF-delimited file and the read buffer has CR as the last character, startOfNextRecord will be set to the position after the CR, i.e. the following LF. Let's say the position of this LF is p.
In the next buffer, even though the actual start of record should be p+1, startOfRecord is set to startOfNextRecord, which is p.
Then the code processes the next record by skipping the LF and yields a record starting from p+1. It decides whether the record is valid by checking if startOfRecord is in the range defined in RangeTracker.
If there is a split right after p, i.e. we have ranges [a, p+1) and [p+1, b), then the above record would be considered as valid in the split [a, p+1), because its startOfRecord is p < p+1. However, the record is also considered valid when split [p+1, …
=> Fix an edge case of getting duplicated records when using TextIO.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java, runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/ExecutionStateSampler.java, runners/flink/src/main/java/org/apache/beam/runners/flink/metrics/Metrics.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowMetrics.java, runners/spark/spark_runner.gradle, sdks/java/core/build.gradle, sdks/java/core/src/main/java/org/apache/beam/sdk/io/Read.java, sdks/java/core/src/main/java/org/apache/beam/sdk/values/RowWithGetters.java, sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoSchemaTranslator.java, sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/BufferedExternalSorter.java, sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/schemas/AwsTypes.java, sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/RetryManager.java, sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java, sdks/java/io/mongodb/src/main/java/org/apache/beam/sdk/io/mongodb/MongoDbGridFSIO.java, sdks/java/io/mongodb/src/main/java/org/apache/beam/sdk/io/mongodb/MongoDbIO.java, sdks/java/io/singlestore/src/main/java/org/apache/beam/sdk/io/singlestore/SingleStoreDefaultRowMapper.java, sdks/java/testing/tpcds/src/main/java/org/apache/beam/sdk/tpcds/TableSchemaJSONLoader.java
Released December 2023 could be useful …
=> Upgrade checkerframework to 3.42.0

CHANGES.md, sdks/python/apache_beam/io/requestresponse.py, sdks/python/apache_beam/io/requestresponse_it_test.py, sdks/python/apache_beam/io/requestresponse_test.py, sdks/python/apache_beam/io/requestresponseio.py, sdks/python/apache_beam/transforms/enrichment.py, sdks/python/apache_beam/transforms/enrichment_handlers/__init__.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigtable.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigtable_it_test.py, sdks/python/apache_beam/transforms/enrichment_it_test.py, sdks/python/apache_beam/transforms/enrichment_test.py
This PR contains the implementation of:
1. [Enrichment transform](https://s.apache.org/enrichment-transform) and its tests.
2. BigTable handler for enrichment and integration test.
3. Default Throttler and Exponential Backoff of requests.
Cross-lang enablement and caching will be added in subsequent PRs.
Part of https://github.com/apache/beam/issues/29787 …
=> Enrichment Transform with BigTable handler

sdks/python/apache_beam/yaml/README.md, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_provider_unit_test.py, sdks/python/apache_beam/yaml/yaml_transform_test.py, sdks/python/apache_beam/yaml/yaml_transform_unit_test.py
Adds time unit suffixes (ms, s, m, h, d) to windowing syntax. …
=> [YAML] add time unit suffix to windowing

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamDockerPlugin.groovy, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, runners/flink/job-server-container/flink_job_server_container.gradle, runners/spark/job-server/container/spark_job_server_container.gradle, sdks/go/container/build.gradle, sdks/java/container/common.gradle, sdks/java/expansion-service/container/build.gradle, sdks/java/transform-service/controller-container/build.gradle, sdks/python/container/common.gradle, sdks/python/expansion-service-container/build.gradle, sdks/typescript/container/build.gradle
It has been found `DockerExtension.ext.buildx` parameter is always true even for local testing. The issue is 
```
def useBuildx = project.containerPlatforms() != [project.nativeArchitecture()]
```
this gives
```
"linux/amd64" != "amd64"
``` …
=> Fix buildx always been true

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/PipelineTranslation.java, runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/TransformUpgrader.java, runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/TransformUpgraderTest.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
PR Also includes following two updates.
* Add an annotation to upgraded transforms so that they can be easily identified by looking at the pipeline proto.
* Prevent Dataflow from performing upgrading when building the Runner v1 pipeline (otherwise, Dataflow will unnecessarily start/shutdown the transform service twice).
This fixes https://github.com/apache/beam/issues/30060. …
=> Automatically enable Dataflow Runner v2 for pipeliens that use the transform upgrade feature

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteRename.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java
=> split write rename and temp table deletion into to dofns with a shuffle

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetrics.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetricsTest.java
Expected bq metric names/label names have changed since they were originally implemented.
Additionally, there were a few spots in [StorageApiWritesShardedRecords.java](https://github.com/apache/beam/compare/master...JayajP:beam:Fixbqmetrics3?expand=1#diff-7a37e64a2dd8c51763204b5de1463318e35292177068e8a11ef0cd4764d8b261) where we did not increment metrics or supply the table_id parameter, this PR also fixes this issue.
This is a no-op change since we currently don't send metrics to the backend. …
=> Fix BigQuerySinkMetrics constants and increment metrics in more places. 

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/Window.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/WindowIntoTransformProvider.java, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_unit_test.py
=> [YAML] Allow windowing to be done in Java or Python.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
Adding below lines in PubsubIO.readMessagesWithAttributesAndMessageIdAndOrderingKey()
`.setNeedsAttributes(true)
.setNeedsMessageId(true)
`
would enable PubsubUnboundedSource.expand method to select the correct Serializable function to parse PubsubMessage.
```
if (getNeedsAttributes() || getNeedsMessageId()) {
function = new PubsubMessages.ParsePubsubMessageProtoAsPayload();
} else {
function = new DeserializeBytesIntoPubsubMessagePayloadOnly();
}
```
Thus preventing **the CoderException: cannot encode a null String** in PubsubMessageWithAttributesAndMessageIdAndOrderingKeyCoder.encode.
=> fix for #30078 [PubsubIO.readMessagesWithAttributesAndMessageIdAndOrderingKey not working]

sdks/python/apache_beam/transforms/enrichment_handlers/bigtable.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigtable_it_test.py
Add an option to return timestamp associated with the fetched value from the BigTable read_row instead of just the value. This could be useful for users when they want to get a series of historical data stored for that key. 
By default, though, only the latest value without timestamp is fetched.
Part of #29787 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apac …
=> [Python] Add an option to retain timestamp returned from the BigTable row

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
This method allows us to periodically extract perWorkerMetric updates for an input `MetricsContainerRegistry`. This is the same pattern we use to support existing DFE counters (see `StreamingStepMetricsContainer::extractMetricUpdates`).
Additionally, this PR adds support to clean up stale PerWorkerCounters. Counters will be removed from the underlying `perWorkerCounters` map if they have been zero valued for longer than 5 minutes. This allows us to create counters with dynamic metric labels that might not last the lifetime of the job, e.g. BQ table IDs set with dynamic destinations. …
=> Add StreamingStepMetricsContainer::extractPerWorkerMetrics method.

sdks/go/pkg/beam/core/runtime/contextreg/contextreg.go, sdks/go/pkg/beam/core/runtime/harness/init/init.go
Beam is currently using go 1.20, but was accidentally depending on the go 1.21 standard libary versions of "maps" and "slices". This changes them to be the compatibility packages.
While beam advocates using the latest release (go 1.21) of Go when using it (which avoids problems when compiling those targets), the occasionally subtle dependency semantics allowed for that mismatch, leading to the compiler error. (IIRC this is not a problem past 1.21, which has better tooling awareness, but won't cause regressions for packages authored before those semantics...)
Going to cherry pick this into the 2.54.0 release to restore the compatibility with go 1.20. …
=> [Go SDK] Don't depend on the go 1.21 standard lib yet

sdks/go/pkg/beam/core/runtime/harness/datamgr.go
Resolve a memory leak as a result of the Data Manager read cache not evicting data streams for which it had not known it had seen all the data streams. 
See the new comment in the code for details.
We don't take the alternative approach of checking the DataChannel's endedInstruction cache because it's possible that cache of instruction references might have a gap, with more than the current cache cap of ended instructions cycling through before the data channel is triggered to observe it. Best to check the cache's contents directly.
Fixes #28142.
I'm not sure how to test for this unfortunately without significantly changing the code, as it's a goroutine local cache, and adding additional synchronization is undesirable.
While this regression has been in the SDK for a while (since around …
=> [#28142][Go SDK] Evict closed readers from the cache.

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSampler.java
make getProcessingDistributionsForWorkId threadsafe to avoid race conditions with remove tracker
the race condition happens in getProcessingDistributionsForWorkId because we check for the existence of the work id in the activeTrackersByWorkId map before retrieving the value from the map. if another thread removes the tracker from the map in-between us checking for its existence and actually grabbing the object, we will get a null tracker that then throws a NullPointerException when we try to access data on it. 
Was able to repro this with a chaos test locally and confirmed that synchronizing the getProcessingDistributionsForWorkId method solves the issue. Decided to not commit the chaos test since it's a bit messy and deviates from test patterns in this repo. …
=> make getProcessingDistributionsForWorkId threadsafe

sdks/python/apache_beam/io/gcp/bigquery.py
Request ID is just a random number between (0, 100,000). For long streaming jobs, this will inevitably create requests with identical ID's. This becomes a problem because query jobs are created from these IDs and BQ ignores identical job names.
=> Make ReadFromBigQueryRequest id more randomized

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverter.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverterTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetrics.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetricsTest.java
`BigQuerySinkMetrics` support labelled metrics by concatenating a base metric name with the metric labels. The characaters `-`, `:` and `;` are used as delimiters in this process. Using `-` as a delimiter causes issues since `-` can also be used a BQ table name. This PR replaces the `-` delimiter with `*` which cannot be used in table ids. (All other metric labels are generated from known enums so we do not need to worry about them).
Additionally changes:
- In `BigQuerySinkMetrics::ParsedMetricName::parsemetricname` create string splitters with `limit(2)` when we split the base metric name from labels, and when we split a metric labels keys and values. This makes parsing more resilient incase delimiters are added to metric labels. 
- modify …
=> Don't use '-' as a delimiter in BigQuerySinkMetrics

.test-infra/tools/stale_bq_datasets_cleaner.sh
Also, add a little more logging on failed commands.
Right now, its common for a dataset to be present at the start of the run and then to disappear by the time the cleaner gets to it (for ephemeral test datasets). This will allow those to be skipped.
This was permared before this change - https://github.com/apache/beam/actions/workflows/beam_CleanUpGCPResources.yml
Example run with this change - https://github.com/apache/beam/actions/runs/7731108048
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easi …
=> Allow stale_bq_datasets_cleaner.sh to run to completion, even when there are failures to grab a dataset

.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh
Two efficiency improvement
- For the nonzero sized images themself (creation time not in epoch), do not invoke `docker manifest inspect`
- For images in us.gcr.io (that are for testing purpose), decrease the retention time to 3 days so there are fewer zero-sized image that need to check digest and decide the actual creation time each time the workflow is run …
=> Fix stale dataflow prebuilt image cleaner

sdks/python/build.gradle
Another attempt to fix https://github.com/apache/beam/issues/28703
Looks like flakes are still happening and retries not happening:
https://github.com/apache/beam/actions/runs/7757756669/job/21157951160
```
> Task :sdks:python:bdistPy310linux
Collecting cibuildwheel==2.9.0
Downloading cibuildwheel-2.9.0-py3-none-any.whl (63 kB)
...
cibuildwheel version 2.9.0
Build options:
platform: 'linux'
architectures: {<Architecture.x86_64: 'x86_64'>, <Architecture.i686: 'i686'>}
build_selector: {'build_config': 'cp310-manylinux_*64*', 'skip_config': '', 'requires_python': None, 'prerelease_pythons': False}
container_engine: 'docker'
output_dir: PosixPath('/runner/_work/beam/beam/sdks/python/build')
package_dir: PosixPath('/runner/_work/beam/beam/sdks/python')
test_selector: {'skip_config': ''} …
```
=> Try a different approach for cibuildwheel flake.

sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management_test.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/server_test.go
This PR addresses #29669 via implementation of jobservices.Server Cancel method. …
=> [Prism] Implement jobservices.Server Cancel

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
Reverts apache/beam#30215, which can trigger exception on commit thread
=> Revert "When failing work items during commit, make sure to call completeWork…"

website/www/site/content/en/contribute/runner-guide.md
While reading the Runner Authoring Guide, I found that some links are not showing properly like the following screenshot.
So fixing those links on that page.
=> Fix markdown links

sdks/python/apache_beam/io/gcp/gcsio.py, sdks/python/apache_beam/io/gcp/gcsio_test.py
We replace `client.get_bucket()` with `client.bucket()`, and `bucket.get_blob()` with `bucket.blob()` in a few places where a lightweight instance of bucket/blob is sufficient for the function calls.
The fix reduces unnecessary get requests (from `get_bucket` and `get_blob`) in the following gcsio apis:
* open
* delete
* delete_batch
* copy
* copy_batch
* list_files
addresses #28398 …
=> gcsio: reduce number of get requests in function calls

sdks/java/transform-service/app/build.gradle, sdks/java/transform-service/build.gradle, sdks/java/transform-service/launcher/build.gradle
This is a piece of #29924 that adjusts dependencies slightly and is separable from the main change. …
=> Adjust transform-service module names and deps with sdks/java/core

sdks/java/io/jms/build.gradle, sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsCheckpointMark.java, sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java, sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOIT.java, sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOTest.java
Attempt to fix - #30054
There were two issues in the JmsIO read checkpoint implementation
1. checkpoint was a mutable member of the reader, returned to the runner each time getCheckpointMark is called:
https://github.com/apache/beam/blob/27f1c0774fd93e846de9a8b668e6effc5a41eb10/sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java#L600
This is not correct as the checkpoint by definition should not change after made. Here, record after the checkpoint made still add to the same checkpoint:
https://github.com/apache/beam/blob/27f1c0774fd93e846de9a8b668e6effc5a41eb10/sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java#L566
When checkpoint is finalized (by finalizeCheckpoint call from runner), messages read between the checkpoint made and finalizing the …
=> Fix Jms drop record

CHANGES.md, sdks/go/container/Dockerfile
Move Go SDK image to use distroless as the base image, instead of the docker debian image.
Technically, the same version of debian, but with everything but glibc stripped out of it.
Go binaries (Go SDK binaries in particular) don't need external deps or most other parts of the OS toolchains, so this reduces the vulnerabilities to largely intractable to fix glibc issues. 
We could remove glibc as by default the SDK doesn't need to compile with C-go enabled (the only reason to link in glibc for go running binaries) but it is handy for users who would depend on it.
distroless has the ca-certificates pre-installed, and as long as we build against latest, it remains relatively up to date. It's not clear to me why we chose to remove the licenses except when configured, but it's harder to remove …
=> [Go SDK] Use distroless:debian12 (no-ssl) as base image.

runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/PTransformTranslation.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionServiceSchemaTransformProvider.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/JavaClassLookupTransformProvider.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/TransformProvider.java, sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceTest.java, sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExternalTest.java, sdks/java/testing/expansion-service/src/test/java/org/apache/beam/sdk/testing/expansion/TestExpansionService.java
This makes us get IllegalArgumentException and clearer stack traces than the NoClassDefFound error which will only show up in the first attempt.
Separating this change and related refactors from #30235  …
=> Fail later when duplicate transform translators are on the classpath

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PTransform.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/PTransformTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java
This PR proposes a new PTransform API, `setDisplayData`, for adding DisplayData items to the transform.
Motivation: Adding DisplayData is easy to do via the `HasDisplayData#populateDisplayData` method that most transform-like types inherit. However, as a user and library owner, I don't always have access to the construction of the PTransform or DoFn and can't override `populateDisplayData`. For example, it would be difficult to add custom displayData labels to any of these transforms unless I wrapped them into new PTransforms:
```java
pipeline
.apply(Create.of(1, 2, 3))
.apply("Map Elements", MapElements.via(...))
.apply("GBK", GroupByKey.create())
```
This PR adds a method `setDisplayData` that can be invoked on any PTransform instance.
Note: I followed the convention of other setter …
=> [Proposal] Improve DisplayData support in PTransform API

runners/google-cloud-dataflow-java/worker/build.gradle, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricTrackingWindmillServerStub.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/options/StreamingDataflowWorkerOptions.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServer.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/IsolationChannel.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillChannelFactory.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillStubFactory.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/IsolationChannelTest.java
- introduce an IsolationChannel class that uses a separate channel per-rpc. As rpcs complete, the channel will be available for subsequent rpcs. This isn't a good idea in general but given we have a few long-lived rpcs in the streaming client.
- use a separate GetDataStream rpc for heartbeats from read requests. This ensures that heartbeats are not delayed by other read requests. …
=> Add options giving more isolation between grpc streaming rpcs.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
There is a mismatch between grpc version pinned in beam versus the one inherited from libraries-bom 26.30.0. The issue was introduce in https://github.com/apache/beam/pull/30028.
For libraries-bom:26.30.0, the effective grpc version in there is 1.60.0 rather than 1.61.0.
```shell
$ cd /tmp; VERSION=26.30.0; wget https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/${VERSION}/libraries-bom-${VERSION}.pom -O base.pom && mvn help:effective-pom -f base.pom -Doutput=effective.pom && cat effective.pom | grep -a2 'grpc-api'
...
<dependency>
<groupId>io.grpc</groupId>
<artifactId>grpc-api</artifactId>
<version>1.60.0</version>
</dependency>
```
This is necessary to fix the problem when accessing GCS with grpc (an experimental feature) in java. …
=> Downgrade grpc version to 1.60.0

sdks/python/apache_beam/examples/ml_transform/ml_transform_it_test.py, sdks/python/apache_beam/examples/ml_transform/vocab_tfidf_processing.py, sdks/python/apache_beam/ml/transforms/utils.py
fixes: https://github.com/apache/beam/issues/30191 …
=> Update artifacts fetcher to download artifacts locally using FileSystems

sdks/java/core/src/test/java/org/apache/beam/sdk/fn/data/BeamFnDataInboundObserverTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/util/UnboundedScheduledExecutorServiceTest.java
* For test of `testCloseVisibleToAwaitCompletionCallerAndProducer` 
* It is flaky due to a race condition.
* There are two threads running (future and future2). Thread 2 may execute and close the observer before Thread 1 reaching the while loop. This will cause `BeamFnDataInboundObserver.CloseException` thrown at calling `future.get()`.
* The fix is just to let Thread2 wait a little time so that Thread 1 can reach the infinite while loop before the observer is closed by Thread 2.
* I was able to reproduce the flake 10/10 prior to the fix, but after that I have tested it about 30 times with no failure.
* For test `testThreadsAreAddedOnlyAsNeededWithContention`, my attempt is to increase the threshold so we can allow more extra threads being created.
Thank you for …
=> Fix two flaky tests

runners/google-cloud-dataflow-java/build.gradle, sdks/python/apache_beam/io/gcp/pubsub.py
fixed documentation in sdks/python/apache_beam/io/gcp/pubsub.py WriteToPubSub
sdks/python/apache_beam/io/gcp/pubsub.py WriteToPubSub documentation
topic arg changed from
topic: Cloud Pub/Sub topic in the form "/topics/<project>/<topic>".
to
topic: Cloud Pub/Sub topic in the form "/projects/<project>/topics/<topic>".)
=> fixed documentation in sdks/python/apache_beam/io/gcp/pubsub.py WriteToPubSub

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
Currently the max buffering duration for batch processing during JDBC writes is not configurable and defaulted to 200ms. I'm proposing that we add an option to configure this setting to allow for a longer duration period to accumulate batched elements. We've run into an issue where batches are committed too frequently causing many small batches to be written rather than fewer larger batches, and I'm hoping to tweak this setting to allow for the latter.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-e …
=> [JdbcIO] - Adding option for max batch buffering duration

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionContext.java
getProcessingTimesByStepCopy was not returning a copy. That and the lack of synchronization on the processingTimesByStep object was causing concurrent modification race conditions. …
=> fix bug in getProcessingTimesByStepCopy

runners/google-cloud-dataflow-java/build.gradle, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
Fixes #30297
- if KafkaIO is not used, there is no KafkaIO.Read in the pipeline to run override
- If KafkaIO is used, it should already be declared as an implementation dependency
Though it is generally not recommended to catch Error (NoClassDefFoundError), I find this may be preferrable to reduce the number of staged artifacts, and also no longer mandate io.confluent repository to submit a pipeline on Dataflow runner.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING. …
=> Make kafka dependency optional for runner-google-cloud-dataflow-java

sdks/python/apache_beam/ml/transforms/handlers.py
This PR attempts to remove CoGBK from MLTransform's TFTProcessHandler. 
Instead of using CoGBK, encode the dict of columns not specified by the user into bytes and pass them in the original dict with a temporary key specified in the schema for TFT. In the TFT `AnalyzeDataset` or `TransformDataset`, this temp column would be a no-op. Once TFT is done processing data, decode the bytes into their actual format.
This only affects the data processing operations specified at `apache_beam/ml/transforms/tft.py`. The operations support float and string data. We have tests for them already. 
For encoding and decoding purposes, I used `apache_beam/pickler` for now. 
Fixes: https://github.com/apache/beam/issues/29593 …
=> Remove CoGBK in MLTransform's TFTProcessHandler

CHANGES.md, website/www/site/content/en/documentation/runtime/environments.md
Add a message to 2.55.0's Breaking Changes regarding the Go container moving to distroless. 
While the existing instructions for
https://beam.apache.org/documentation/runtime/environments/#modify-existing-base-image do work, the simplicity of Go's handling in this case is valuable to emphasize.
Staging:
https://apache-beam-website-pull-requests.storage.googleapis.com/30290/documentation/runtime/environments/index.html#from-scratch-go
To check …
=> Add instructions for Go custom container builds, link from 2.55.0 release notes.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, scripts/tools/bomupgrader.py, scripts/tools/gcpbomupgrader.py
Command: `python scripts/tools/gcpbomupgrader.py 26.30.0`
If run `python scripts/tools/gcpbomupgrader.py 26.31.0` based on this PR, it would give:
```
INFO:root:Changed com.google.api:gax: 2.39.0 -> 2.41.0
INFO:root:Changed com.google.cloud:google-cloud-spanner: 6.56.0 -> 6.57.0
INFO:root:Changed io.grpc:grpc-netty: 1.60.0 -> 1.61.0
INFO:root:Unchanged: io.netty:netty-transport:4.1.100.Final
INFO:root:Changed com.google.protobuf:protobuf-java: 3.25.1 -> 3.25.2
INFO:root:Changed org.apache.arrow:arrow-memory-core: 14.0.2 -> 15.0.0
``` …
=> Add an automatic GCP-BOM dependency upgrader

CHANGES.md, website/www/site/config.toml, website/www/site/content/en/blog/beam-2.54.0.md, website/www/site/content/en/get-started/downloads.md
Update CHANGES.md, and the Beam website for the 2.54.0 release. …
=> Beam 2.54.0 release blog.

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WorkerPipelineOptionsFactory.java, sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcpOptions.java, sdks/java/harness/build.gradle, sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java
When using `impersonateServiceAccount`, per https://cloud.google.com/dataflow/docs/reference/pipeline-options#security_and_networking, Dataflow UI should display this useful option but this option should be ignored when staring the worker harness.
This PR fixes this. Here is what the UI displays with this option is set:
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github …
=> fixed the display issue for impersonateServiceAccount with Java

sdks/python/apache_beam/io/gcp/gcsio.py
The PR #30205 introduced a bug of early termination when there is any exception in batch copy/delete. As a result, the error code is not propagated correctly and one of our post-commit tests failed.
```
AssertionError: BeamIOError not raised
self = <apache_beam.io.gcp.gcsfilesystem_integration_test.GcsFileSystemIntegrationTest testMethod=test_rename_error>
@pytest.mark.it_postcommit
def test_rename_error(self):
num_copies = 10
srcs = [self.INPUT_FILE] * num_copies
dests = [
self.gcs_tempdir + '/%s_%d' % (self.INPUT_FILE, i)
for i in range(num_copies)
]
self.fs.copy(srcs, dests)
new_names = [
self.gcs_tempdir + '/%s_%d' % ("renamed", i) for i in range(num_copies)
]
bad_name = self.gcs_tempdir + '/errorbadwrong'
dests[int(num_copies / 2)] = bad_name
>     with …
```
=> Fix post-commit failure after pr/30205.

sdks/java/extensions/python/build.gradle
Many changes were made in #29924 to merge `runners:core-construction-java` into `sdks:java:core`. One missing line is causing build failures for postcommits
Error for failing postcommits ([example](https://github.com/apache/beam/actions/runs/7919598056/job/21620744814)) looks like:
```
What went wrong:
A problem occurred evaluating project ':sdks:java:extensions:python'.
> Could not get unknown property 'sourceSets' for project ':sdks:java:core' of type org.gradle.api.Project.
```
=> Fix Python postcommits 

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/container/license_scripts/dep_urls_java.yaml
Reverts apache/beam#30324
This breaks various postcommits.
The script was not complete. Lots of google-apis were not included in that script
=> Revert "Update to libraries-bom 26.32.0"

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/engine_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/teststream.go, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go, sdks/go/pkg/beam/testing/teststream/teststream.go, sdks/go/test/integration/integration.go, sdks/go/test/integration/primitives/teststream.go, sdks/go/test/integration/primitives/teststream_test.go
Adds initial TestStream support for Prism for #29917.
* Handles watermark advancement.
* Multiple Outputs (though, this is untested until covered by Python, as Go doesn't permit tag specification, however, the same lookup mechanism remains in the single output case)
* Handles arbitrary element bytes.
* Handles being consumed as a side input.
A bit of light experimentation on handling design puts most test stream related code into a single file, and uses an interface to delegate the execution of events to the different events themeselves.
The only easily testable logic outside of a pipeline execution context would be popping events from a queue. But as the alternative to correct popping is a pipeline freeze and crash (pending elements remaining, but nothing to trigger their processing), …
=> [#29917][prism] Initial TestStream support

it/google-cloud-platform/build.gradle, it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java
This pull request introduces stress tests for BigQueryIO, designed to assess the performance under various conditions. The stress tests simulate dynamic load increases and evaluate the behavior of BigQueryIO for different write formats and methods.
**Changes:**
- Added stress tests for BigQueryIO.
- Implemented dynamic load increases over time to simulate varying workloads.
- Introduced configurations for controlling the stress test parameters, such as the number of columns, write method, write format, etc.
- Added support for exporting metrics to _InfluxDB_ or _BigQuery_ based on the configuration parameter.
**Dynamic load increases over time example:** …
=> Implement BigQuery Stress Test

sdks/python/apache_beam/io/gcp/bigquery.py
Removing the JSON type check when using WriteToBigQuery with FILE_LOAD method in Python SDK. Throwing a warning instead.
* Related to the change in Java SDK: https://github.com/apache/beam/pull/29923. Consistent with this PR for Java SDK, I have changed the `raise ValueError` to a logging.warn`.
* Relevant lines of code
https://github.com/apache/beam/blob/8a74a1c279c86a262def9b99418e7eb03366e2d9/sdks/python/apache_beam/io/gcp/bigquery.py#L2178-L2191
I did some hackish testing against a table of my own and it was able to insert the json fields correctly without a problem.
NOT RECOMMENDED but it solves the problem for those who need this tomorrow:
In my docker file that has Apache Beam installed, I used `sed` to replace the check:
```bash
RUN sed -i 's/if field\['\''type'\''\] == …
```
=> Allow JSON type in TableSchema for WriteToBigQuery with FILE_LOAD method in Python SDK

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/StreamingEngineClient.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/StreamingEngineClientTest.java
Removed flaky logic around waiting in tests.
Removed thread.sleep and replaced with triggers via CountDownLatch
R: @scwhittle @Abacn  …
=> fix flaky test

.gitignore, sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_mapping_test.py, sdks/python/setup.py
This is a follow-up to https://github.com/apache/beam/pull/30161 …
=> Add the ability to test examples from yaml docs.

CHANGES.md, sdks/python/apache_beam/options/pipeline_options.py
Make state cache optional due to a potential performance regression that might affect some users: https://github.com/apache/beam/issues/30360.
=> Make state cache optional due to a potential performance regression for some users. 

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/AutoValueUtils.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/POJOUtils.java, sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroByteBuddyUtils.java, sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java, sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/schemas/AwsSchemaUtils.java
Remove some uses of ClassLoadingStrategy.Default.INJECTION in favor of
ByteBuddyUtils.getClassLoadingStrategy which prevents issues with newer java versions.
See #25578 for more details
Related to #30358
There are more changes required in sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java but due to difficulty testing they will be done separately. …
=> Remove some uses of ClassLoadingStrategy.Default.INJECTION

sdks/python/apache_beam/io/filebasedsink.py, sdks/python/apache_beam/io/textio.py
Fixes #27926 
Add clarifying doc comment for skip_if_empty in WriteToText …
=> [Python] Add doc comment for WriteToText.skip_if_empty

sdks/python/apache_beam/transforms/core.py, sdks/python/apache_beam/transforms/core_test.py
When these windows don't match, it can create unexpected behavior downstream; it doesn't really make sense to flatten different windows.
Fixes #22903 …
=> Ensure flatten windows match

sdks/python/apache_beam/io/gcp/bigquery_json_it_test.py
Fixes #30437
This is the same fix of the java counterpart of #29923 …
=> Fix Python PostCommit BigQuery JSON

sdks/python/apache_beam/transforms/ptransform.py, sdks/python/apache_beam/transforms/ptransform_test.py
It would be good to have a better way to do this, but this is compatible with how things work for now.  …
=> Fix updating of annotations for explicitly named transforms.

sdks/java/extensions/avro/build.gradle
=> Fix Avro Version PostCommit

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefresher.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefreshers.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/DispatchedActiveWorkRefresher.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/DispatchedActiveWorkRefresherTest.java
StreamingDataflowWorker is a very large class.  This breaks out the active work refresh and invalidating commit logic ( async work management) to another class.
Initial implementation is what currently exists today.  There will be another implementation of `refreshActiveWork()` later for direct path, but this PR lays the ground work for it.  Also add tests to have more coverage over individual components than just the StreamingDataflowWorkerTest which is larger.
R: @arunpandianp 
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING …
=> ActiveWorkRefresh

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageStreamSource.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadTest.java
Follow up of #28778, stay in alignment with #25392 where the streams returned by the server won't be splited further …
=> Disable BigQueryStorageStreamSource.splitAtFraction when read api v2 used

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
We've noticed that a failure to process a bigquery `Mutation` (for instance due to a coder exception), results with the following error in the logs:
```
Batcher was not closed properly!!! Make sure to call close().
java.lang.RuntimeException: Batcher allocation site
at com.google.api.gax.batching.BatcherImpl$BatcherReference.<init>(BatcherImpl.java:552)
at com.google.api.gax.batching.BatcherImpl.<init>(BatcherImpl.java:210)
at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.newMutateRowsBatcher(EnhancedBigtableStub.java:690)
at com.google.cloud.bigtable.data.v2.BigtableDataClient.newBulkMutationBatcher(BigtableDataClient.java:1113)
at com.google.cloud.bigtable.data.v2.BigtableDataClient.newBulkMutationBatcher(BigtableDataClient.java:1080)
at …
```
=> Cleanup bigtable open resources on teardown

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/python/apache_beam/io/gcp/bigtableio_it_test.py
The test suite is green currently but seems like it's just passing trivially due to tests being skipped.
This fixes https://github.com/apache/beam/issues/30238. …
=> Make the TransformService test suite not pass trivially.

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineWorkerPoolOptions.java
This PR fixes #30483. Removing the JsonIgnore annotation restores visibility of the parameter on the console.
[![Build …
=> Remove JsonIgore for usePublicIps

website/www/site/content/en/documentation/sdks/yaml.md
=> Document yaml pipeline options

sdks/python/apache_beam/io/external/xlang_jdbcio_it_test.py
This reverts commit 2b8a737ebd0942da69f0988180e3c9160b267ba2. …
=> Revert "Add test code to overwrite SQL in Beam Python JDBC (#30417)"

build.gradle.kts, sdks/python/apache_beam/io/hdfs_integration_test/docker-compose.yml, sdks/python/test-suites/direct/common.gradle
Fix #30459
For some reason there are connection refused error between test_node, name_node and data_node. Might due to recent upgrade of Python official docker image (base image upgrade)
GitHub Actions …
=> Fix hdfs integration test

playground/backend/containers/java/Dockerfile, playground/backend/containers/python/Dockerfile
1) Fixes python backend container build issue. After update to debian bookworm openjdk-11-jre-headless package is no longer availabile in stable. Fix downloads the package from bullseye repo and uses apt to install. This was chosen instead of adding bullseye as oldstable to avoid package conflicts. There was an option to update to openjdk-17 but was not sure if playground code would be affected. 
2) Fixes java container build where for some reason maven uses offline  mode when doing `dependency:list`. Instead of removing offline (it was there for some reason) we just add `mvn dependency:go-offline` to preload the needed dependencies
See the …
=> fix playground backend container builds

runners/google-cloud-dataflow-java/examples/build.gradle
Fix https://github.com/apache/beam/pull/30562#issuecomment-1984867014 apparently our test relied on empty `--workerHarnessContainerImage`
It was introduced in #29170 where I thought the change of runners/google-cloud-dataflow-java/examples/build.gradle was no-op but apparently it didn't …
=> Fix Dataflow PreCommit on release branch

website/www/site/content/en/documentation/ml/large-language-modeling.md
=> Add info on large_model flag in LLM page

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java, runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java, runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
Fixes #30469
Currently there is inconsistent rewriting and validation. …
=> Skip runner Dataflow v1 steps when a job will run on v2

sdks/python/apache_beam/ml/inference/tensorflow_tests_requirements.txt
Fixes #30613 
Pin keras version for `tf_inference_it_test` in postcommits to less than 3.0.0. Created https://github.com/apache/beam/issues/30616 to support Keras 3. …
=> [Python] Pin keras version for tensorflow inference test

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryDirectReadSchemaTransformProviderTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProviderTest.java
These tests use a fake bigquery service, so they don't belong as integration tests.
=> [fix postcommit] Rename tests to remove them from dataflow test suite

sdks/python/apache_beam/coders/coder_impl.py, sdks/python/apache_beam/coders/coders.py, sdks/python/apache_beam/coders/coders_test_common.py, sdks/python/apache_beam/portability/python_urns.py, sdks/python/apache_beam/runners/portability/flink_runner_test.py, sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py, sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py, sdks/python/apache_beam/utils/timestamp.py
This was exposed by #28972 when the set of "known" coders was inadvertently reduced. …
=> Properly handle timestamp prefixing of unkown window types.

sdks/python/apache_beam/runners/worker/data_plane.py
This will cause an exception when the too-large element is emitted, rather than later when the proto is serialized (which happens on another thread and may also cause spurious errors in the data channel consumption). …
=> Better error message for large elements.

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillBag.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillValue.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillWatermarkHold.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternalsTest.java
Include byte size of stateKey in estimated weight of WindmillBag, WindmillValue, and WindmillWatermarkHold
The weight is used to track and limit the total StateCache memory size. For certain workloads stateKey consitutes major portion of total memory pinned by cache entries. Not including it into the weight results in severe underestimate of the real cache size, and may leads to GC thrashing and eventually to workers crashing OOM.
To check the …
=> Include byte size of stateKey in estimated weight of WindmillBag, WindmillValue, and WindmillWatermarkHold

.github/trigger_files/beam_PostCommit_Java_Avro_Versions.json, buildSrc/build.gradle.kts, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/extensions/avro/build.gradle, sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProto.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/GcpApiSurfaceTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProtoTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryAvroUtilsTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClientTest.java, sdks/java/io/kafka/build.gradle
=> update confluent dependency version to 7.6.0

.github/workflows/beam_LoadTests_Python_Combine_Dataflow_Streaming.yml, .github/workflows/load-tests-pipeline-options/python_Combine_Dataflow_Streaming_2GB_10_byte_records.txt
`python_Combine_Dataflow_Streaming_2GB_10_byte_records.txt` failed due to the limited number of workers. Increase this to 50, which should finish the test within 2 hours (~16$).
Tests are here: https://github.com/apache/beam/blob/50f33cd786dc63463688315a1c73b1cf4ef18807/sdks/python/apache_beam/testing/load_tests/combine_test.py#L121
Cron:
https://github.com/apache/beam/blob/50f33cd786dc63463688315a1c73b1cf4ef18807/.github/workflows/beam_LoadTests_Python_Combine_Dataflow_Streaming.yml#L20C14-L20C25
Fixes #23904 …
=> Use 50 workers for 2GB 10 bytes combine test

sdks/python/apache_beam/runners/worker/sdk_worker.py
We've seen this section hang, eating up the lock when shutdown takes a long time. This should minimize the size of the critical section to a single copy of `self.last_access_times.items()` so that it still avoids #27501 (which the lock was introduced for) without hanging too long. …
=> Minimize scope of expensive lock

release/src/main/groovy/MobileGamingCommands.groovy, release/src/main/groovy/mobilegaming-java-dataflow.groovy, release/src/main/groovy/mobilegaming-java-direct.groovy
This PR addresses #30447 assigning a unique Google Cloud storage path to mobile gaming tests' output. Even `./gradlew :release:runJavaExamplesValidationTask` at master failed on my local machine so I'm seeing if the checks in this PR could help validate this change. …
=> Fix mobile gaming tests Google Cloud storage object output clash

CHANGES.md, website/www/site/content/en/blog/beam-2.53.0.md, website/www/site/content/en/blog/beam-2.54.0.md
Add issue fixed in #30679 to CHANGES and effected blogs …
=> Add known python issue

release/src/main/groovy/mobilegaming-java-dataflowbom.groovy
PR #30690 fixed [beam_PostRelease_NightlySnapshot](https://github.com/apache/beam/actions/workflows/beam_PostRelease_NightlySnapshot.yml)
as shown in [latest run](https://github.com/apache/beam/actions/runs/8378389784).
However, some Google Cloud Storage paths contained `null`. For example:
`gs://temp-storage-for-release-validation-tests/nightly-snapshot-validation/java-userscore-result-dataflow-runner/null/output`.
It still worked because the test run that had a valid UUID was still different than "null".
This PR adds the same unique test ID strategy for Google Cloud Storage object path uniqueness to the Dataflow BOM tests. (It was missed in the previous PR #30690) …
=> Add unique ID to Dataflow BOM tests

.github/workflows/beam_PreCommit_Python_Coverage.yml, sdks/python/tox.ini
Adds PYTHONPATH environment variable to cloudcoverage tox environment set to toxinidir (sdks/python). 
This allows pytest to load all the modules and run the correct coverage report
Also removes codecov uploader which has issues if no codecov token is provided. Its replaced by codecov-action which can work in tokenless setup …
=> add pythonpath to cloudcoverage tox environment

.github/workflows/beam_PostCommit_Python_Dependency.yml, .github/workflows/beam_PostCommit_TransformService_Direct.yml, .github/workflows/beam_PreCommit_Python.yml, .github/workflows/beam_PreCommit_Python_Coverage.yml, .github/workflows/beam_PreCommit_Python_Dataframes.yml, .github/workflows/beam_PreCommit_Python_Examples.yml, .github/workflows/beam_PreCommit_Python_Runners.yml, .github/workflows/beam_PreCommit_Python_Transforms.yml
The generated wheel is currently only used in Dataflow test-suite, and unused in these workflows
The wheel is built by cibuildwheel which spins up a container. Remove it saves 3-5 min per test
GitHub …
=> Remove -PuseWheelDistribution for direct runner workflows

.github/workflows/beam_PostCommit_Java_SingleStoreIO_IT.yml
please merge after chages in #30725  are merged
should fix #30523  …
=> add finalizer removeal to postcommit java singlestoreio it

examples/notebooks/beam-ml/README.md, examples/notebooks/beam-ml/vertex_ai_feature_store_enrichment.ipynb
[Notebook link](https://colab.research.google.com/drive/1wE_3IJGxb7O2AXxHbkTjfN6UUrtYbBly?usp=sharing)
Add an example notebook to demonstrate enrichment transform with Vertex AI Feature Store handler.
Part of #30386  …
=> [Docs] Add Vertex AI Feature Store enrichment notebook

learning/tour-of-beam/learning-content/common-transforms/aggregation/count/go-example/main.go, learning/tour-of-beam/learning-content/common-transforms/aggregation/max/go-example/main.go, learning/tour-of-beam/learning-content/common-transforms/aggregation/mean/go-example/main.go, learning/tour-of-beam/learning-content/common-transforms/aggregation/min/go-example/main.go, learning/tour-of-beam/learning-content/common-transforms/aggregation/sum/go-example/main.go, learning/tour-of-beam/learning-content/common-transforms/filter/go-example/main.go, learning/tour-of-beam/learning-content/common-transforms/motivating-challenge/go-challenge/main.go, learning/tour-of-beam/learning-content/common-transforms/motivating-challenge/go-solution/main.go, learning/tour-of-beam/learning-content/introduction/introduction-concepts/creating-collections/from-memory/go-example/from_memory.go, learning/tour-of-beam/learning-content/introduction/introduction-concepts/creating-collections/reading-from-csv/go-example/csvExample.go, learning/tour-of-beam/learning-content/introduction/introduction-concepts/creating-collections/reading-from-text/go-example/textIo.go, learning/tour-of-beam/learning-content/introduction/introduction-concepts/pipeline-concepts/creating-pipeline/go-example/main.go, learning/tour-of-beam/learning-content/introduction/introduction-concepts/pipeline-concepts/setting-pipeline/go-example/main.go
Fix all the Go examples for the Tour of Beam all the way until "Core Transformations". A subsequent PR will fix the rest of the examples. 
`beam.Init` was missing on all the files making it impossible to run in the Playground. 
Also, `go fmt` format wasn't respected on a lot of the files. 
This fixes #30477 (partly)
=> Fix all tour examples from part 1

sdks/python/apache_beam/examples/snippets/transforms/elementwise/enrichment.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/enrichment_test.py, website/www/site/content/en/documentation/transforms/python/elementwise/enrichment-bigtable.md, website/www/site/content/en/documentation/transforms/python/elementwise/enrichment-vertexai.md, website/www/site/content/en/documentation/transforms/python/elementwise/enrichment.md, website/www/site/content/en/documentation/transforms/python/elementwise/runinference.md, website/www/site/layouts/partials/section-menu/en/documentation.html
Adds beam webpage for vertex ai enrichment handler and update the transform catalog.
[Staged website](http://apache-beam-website-pull-requests.storage.googleapis.com/30692/documentation/transforms/python/elementwise/enrichment/index.html)
Part of #30386 
GitHub …
=> [Docs] Beam website doc for vertex ai enrichment handler

sdks/java/core/build.gradle
Fixes #30776
The core SDK has a hard dependency on `org.everit.json.schema`. Because it was thought of as "optional" it was marked `provided`. But `provided` means that the expected runtime will provide a library. It should not be used for "optional". Optionality is achieved by factoring logic into separate modules which a user may choose to depend on or not. In this case, the core SDK has a compile time and runtime dependency on this, so this PR fixes this one dependency (among many) to be correct. …
=> Fix core SDK misuse of "provided" dep for everit_json_schema

sdks/java/extensions/schemaio-expansion-service/build.gradle
=> Include everit_json_schema in schemaio expansion service uber jar

runners/google-cloud-dataflow-java/build.gradle
Will probably need to immediately go to rc2 because I forgot to do this before generating rc1 …
=> Update dataflow containers on release branch

sdks/python/apache_beam/coders/coders.py, sdks/python/apache_beam/coders/coders_test.py
(Duplicate of another [PR](https://github.com/apache/beam/pull/30559) but without rebase issues)
LengthPrefixCoder doesn't define to_type_hint even though it seems pretty well defined. I've implemented it by just inferring it from its value coder.
Motivating use case - we have some debug tools that infer the types of pcollections based on to_type_hint. The LPCoder is used in a lot of places.
Bonus/unrelated change - I've pulled out the GitHub issue referenced in the NotImplementedError raised by to_type_hint. Every time I run into this error, I check the github issue and get more confused. It doesn't seem useful to refer to it in the error message, but does still seem relevant, so I pulled it out into a comment.
Testing Done
I haven't actually run the new unit test I wrote since I'm …
=> Implement LengthPrefixCoder.to_type_hint

sdks/go/pkg/beam/runners/prism/internal/environments.go
When upgrading to 2.55, the Docker deprecated types in Docker - `github.com/docker/docker v26.0.0`, have been removed. Migrate them to the new types. 
[Docker Go Types](https://pkg.go.dev/github.com/docker/docker@v25.0.5+incompatible/api/types#ContainerStartOptions) …
=> Docker - Remove Deprecated Types

sdks/python/apache_beam/yaml/yaml_transform.py, sdks/python/apache_beam/yaml/yaml_transform_unit_test.py
This should fix https://github.com/apache/beam/issues/30446 …
=> [YAML] Interpret PDone as no outputs.

sdks/python/setup.py
It is incorrect to use `<=` in this case, see: https://cwiki.apache.org/confluence/display/BEAM/Dependency+management+guidelines+for+Beam+Python+SDK+maintainers
=> Correct the version spec

website/www/site/content/en/documentation/sdks/yaml.md
Realized I merged https://github.com/apache/beam/pull/30842 before this was addressed. …
=> Remove outdated comment about docker.

sdks/python/apache_beam/internal/gcp/auth.py, sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py, sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py, sdks/python/apache_beam/runners/worker/statecache.py
The playground examples have tons of info logging that drown out any actual logging that the example might've caused. This is somewhat of a big hit to the playground experience (not just noted by me, but by others that I've been introducing to Beam)
I attempted a fix to change the playground's [log level](https://github.com/apache/beam/pull/29948) but that didn't seem to take. Vlado Djerek also tried to figure out where the logging level is set but was also unsuccessful.
In lieu of a real fix, I just changed or deleted various logging statements that I suspect are probably not all that useful. I suspect especially that the translation prints which really clog up the examples don't offer much useful information.
Here's an example of what running the example looks like right now:
=> Lower various logging statement levels to clean up example printing

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/join/CoGbkResult.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/join/CoGbkResultTest.java
In particular Runner v2 does not produce Reiterables, which resulted in the entire stream being read into memory. In this case we can leverage the fact that the first 100MB will be cached and quick to reiterate over.
Formerly, if the underlying iterable was not a reiterable, it would attempt to store the entire thing in memory. Now it will fall back to re-iterating (and filtering) from the start if the iterator does not support iterating from an arbitrary point, which may not be as efficient in some cases, but will not OOM.  …
=> Allow lazy iteration for non-reiterables.

sdks/python/apache_beam/runners/common.py
There are cases where environments are specified at the transform/windowing level that are not included in the top-level components' environments.
This is particularly present when running sql-backed provider on multiple inputs (i.e. when joining 2 pcollections) in Beam YAML which creates 2 default environments, but only declares one in the proto.components.environments section.
Perhaps the real issue lies in how Beam YAML providers create transforms, but this is a nice safeguard regardless. …
=> merging non-canonical environments fails

sdks/python/apache_beam/examples/snippets/transforms/elementwise/flatmap_nofunction.py, sdks/python/apache_beam/examples/snippets/transforms/elementwise/flatmap_test.py, sdks/python/apache_beam/transforms/core.py, sdks/python/apache_beam/transforms/core_test.py, website/www/site/content/en/documentation/transforms/python/elementwise/flatmap.md
Per the [mailing list suggestion](https://lists.apache.org/thread/k1p3f803fpzn2nvsknr2r7prcfr45xgm), I've added an identity function as the default to `beam.FlatMap`
=> Add identity function as default to FlatMap

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, scripts/tools/bomupgrader.py, sdks/java/container/license_scripts/dep_urls_java.yaml, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImplTest.java
=> Bump GCP-BOM to 26.36.0

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineOptions.java, runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkTransformOverrides.java, runners/flink/src/test/java/org/apache/beam/runners/flink/FlinkPipelineOptionsTest.java
This PR removes the automated file sharding normally applied when the runner is passed `--useDataStreamForBatch`.
Currently `FlinkStreamingPipelineTranslator.StreamingShardedWriteFactory` automatically forces file sharding because without it each bundle becomes an output file. Writing a very large number of small files is obviously very inefficient, but for batch jobs we can simply make bundles much much larger which makes sharding unnecessary.
Without this fix, `useDataStreamForBatch` can be much slower because of the extra shuffle step. 
It seems the dataflow runner is following a similar approach were sharding in only added in streaming mode. 
See …
=> [Flink] Speed up file write in batch mode by using larger bundle size

sdks/python/tox.ini
Follow up for: https://github.com/apache/beam/pull/30863 https://github.com/apache/beam/issues/30852 …
=> Update a restriction for another test suite 

CHANGES.md, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibility.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java
addresses #30870. The changes in this PR make the consumer polling timeout configurable for KafkaIO.Read with following new command:
KafkaIO.read().withConsumerPollingTimeout(Duration duration)
The duration must be greater than zero. If not specified, the default will be 1 second.
=> [bug30870]: make consumer polling timeout configurable for KafkaIO.Read

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateCache.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateCacheTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternalsTest.java
Existing code incorrectly assumes per-entry HashMap overhead is 16 bytes.
In reality it's 32 bytes [per this article](https://appsintheopen.com/posts/52-the-memory-overhead-of-java-ojects), confirmed by profiling: 1.22GB for 40.96M objects ~ 32 bytes/object …
=> Correct per-entry HashMap overhead in WindmillStateCache

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/planner/BeamRuleSets.java, sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlAliasTest, sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/impl/rule/BeamAggregateProjectMergeRuleTest.java
Fixes #30498
See full discussion
=> [java-extension-sql]Beam Sql doesn't honor aliases because of `BeamAggregateProjectMergeRule` optimization

.github/workflows/beam_PreCommit_Yaml_Xlang_Direct.yml, sdks/python/build.gradle
This should have caught the issue at https://github.com/apache/beam/issues/30776 …
=> Add gradle target and github workflow for cross-langauge yaml tests.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimator.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/MutationUtils.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/StructUtils.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimatorTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/MutationUtilsTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/StructUtilsTest.java
Adds support for the newly added FLOAT32 type in Google Cloud Spanner.
Since FLOAT was already mapped to FLOAT64, this change modifies the existing mapping to FLOAT -> FLOAT32 instead.
Addresses #30700.
Please ignore the commit bumping the BOM version to 26.36.0. This is already being done as part of #30868 
[![Python …
=> Support FLOAT32 type in Spanner

release/src/main/groovy/MobileGamingCommands.groovy
Address #30505. The current time out value is 20 minutes. I checked few successful runs, which usually took less than 20 minutes. However, given sleeping 1 min (https://github.com/apache/beam/blob/master/release/src/main/groovy/mobilegaming-java-dataflow.groovy#L112) could happen randomly, the job might run out of 20 minutes. 
Double this value for now to check whether this can reduce the flaky rate. …
=> Increase the timeout value for LeaderBoard example on DataflowRunner

.github/workflows/README.md
Document workarounds for #28909 in the beginning of the doc.
=> Document how to trigger test suites.

sdks/python/pyproject.toml
https://github.com/apache/beam/issues/30955
Reverts apache/beam#30956
=> Revert setuptools upperbound since buggy releases are yanked.

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkStreamingTransformTranslators.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSource.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderBase.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplit.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplitEnumerator.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSource.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSourceReader.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/impulse/BeamImpulseSource.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/bounded/FlinkBoundedSourceReaderTest.java
=> #30903: Do not reemit data from impulse

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderBase.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplit.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplitEnumerator.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReaderTest.java
=> [runners-flink] Fix watermark emission for empty splits (#29816)

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderBase.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplit.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReaderTest.java
=> #29902 finalize checkpoints after checkpoint

CHANGES.md, sdks/python/apache_beam/runners/dataflow/dataflow_runner.py, sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
This version is guarded by an experiment in case the old behavior is needed. …
=> Automatically execute unbounded pipelines in streaming mode.

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java, sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java, sdks/python/apache_beam/io/kafka.py
addresses #30870. Previous PR (https://github.com/apache/beam/pull/30877) made consumer polling timeout configurable for KafkaIO.Read in Java SDK. This PR contains changes to make the same configurable for Python SDK with the new configuration variable: consumerPollingTimeoutSeconds., which must be greater than 0. If not specified, the default will be 2 second.
=> [#30870]: support consumer polling timeout in KafkaIO expansion service

.github/trigger_files/beam_PostCommit_Python.json, CHANGES.md, sdks/python/apache_beam/transforms/enrichment_handlers/bigtable.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigtable_it_test.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigtable_test.py
Allow users to use a custom function to build a composite row key from for the Bigtable row.  …
=> [Python] Allow lambda function in bigtable handler to build a custom row key

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplit.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReaderTest.java
=> [Flink] finalize checkpoint marks in the new Flink source implementation (#30849)

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/join/CoGbkResult.java
This could be useful in guiding future optimizations. …
=> Add some metrics for CoGBK profiling.

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibility.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java, sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java, sdks/python/apache_beam/io/kafka.py
addess #30941: fix upgrade test due to  missed config ConsumerPollingTimeout in  KafkaIOTranslation
=> [#30941]fix upgrade test due to  missed config ConsumerPollingTimeout

sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
A change in google-api-core 2.17.0 triggered a regression introduced in grpcio==1.58.0, which will be fixed in grpcio==1.63.0 and possibly in grpcio==1.62.2.  The regression affects Beam 2.55.0 (#30927 #30867).
This temporary change will help avoid the dependency version combination that might trigger the failure until the grpc fix is available.
=> Downgrade google-api-core to mitigate #30927

.github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink.yml, gradle.properties, runners/flink/1.12/build.gradle, runners/flink/1.12/src/main/java/org/apache/beam/runners/flink/translation/types/CoderTypeSerializer.java, runners/flink/1.12/src/test/java/org/apache/beam/runners/flink/translation/types/CoderTypeSerializerTest.java, runners/flink/1.14/build.gradle, runners/flink/1.15/build.gradle, runners/flink/1.16/build.gradle, runners/flink/1.17/build.gradle, runners/flink/1.17/job-server-container/build.gradle, runners/flink/1.17/job-server/build.gradle, runners/flink/1.17/src/main/java/org/apache/beam/runners/flink/translation/types/CoderTypeSerializer.java, runners/flink/flink_runner.gradle, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/types/UnversionedTypeSerializerSnapshot.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/types/UnversionedTypeSerializerSnapshotTest.java, settings.gradle.kts, website/www/site/layouts/shortcodes/flink_java_pipeline_options.html, website/www/site/layouts/shortcodes/flink_python_pipeline_options.html
Support Flink 1.17. Closes #29939. …
=> Flink 1.17

sdks/go/pkg/beam/runners/prism/internal/environments.go
Reverts apache/beam#30826
We need more time to upgrade this since we need to upgrade https://github.com/moby/moby as well.
=> Revert "Docker - Remove Deprecated Types"

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StreamingInsertsMetrics.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StreamingInsertsMetricsTest.java
Some minor updates to StreamingInsertsMetrics:
- Remove some AtomicIntegers from StreamingInsertsMetricsImpl. `SuccessfulRowsCount` and `FailedRowsCount` can be derived from the main thread executing the bundle. 
- Cache Histogram metric as a `static final` in `StreamingInsertsMetricsImpl` instead of recreating it once per bundle. 
- Record latency metrics one at a time instead of through a double stream, while the DoubleStream helps large bundles that result in multiple BigQuery RPCs, it hurts small bundles that only send a single RPC.  …
=> Minor updates to StreamingInsertsMetrics

sdks/python/apache_beam/runners/common.pxd, sdks/python/apache_beam/runners/common.py
As there are potential performance concerns, put the removal of caching of global window inputs added by #30991 behind an experiment. …
=> Change caching of global window inputs to be guarded by experiment

contributor-docs/code-change-guide.md
=> Add code change guide contributor-doc

sdks/python/container/py310/base_image_requirements.txt, sdks/python/container/py311/base_image_requirements.txt, sdks/python/container/py38/base_image_requirements.txt, sdks/python/container/py39/base_image_requirements.txt, sdks/python/setup.py
cherry-pick: #31044 to the release branch. 
fixes: #30867
=> [release-2.56.0] Exclude broken versions of GRPCIO and upgrade the base image requirements 

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/engine_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/teststream.go, sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go, sdks/go/test/integration/primitives/teststream.go, sdks/go/test/integration/primitives/teststream_test.go, sdks/go/test/integration/primitives/timers.go
While working on adding Processing Time handling, it came to light that there were some inconsistent cases WRT handling TestStream based pipelines, in particular when there were no impulses included.
This fix uses the existing watermark hold system to restrain execution until the test stream is ready, and reflect holds based on test stream watermark events properly before their execution.
This discovered flaky fail behavior due to how timers and data outputs were handled in bundle processing, also fixed in this PR.  …
=> [#30083][prism] Stabilize additional teststream cases.

sdks/python/apache_beam/runners/portability/stager.py
Using isolated builds requires internet connection, which might otherwise not be necessary and not available in some scenarios.
=> Don't use isolated builds when building an sdist for a pipeline package supplied in --setup_file option.

sdks/python/apache_beam/runners/portability/stager.py
Don't use isolated builds when building an sdist for a pipeline package supplied in --setup_file option.
=> [release-2.56.0] Cherry-picks #31070

sdks/python/apache_beam/yaml/yaml_io.py, sdks/python/apache_beam/yaml/yaml_io_test.py, website/www/site/content/en/documentation/sdks/yaml.md
=> [YAML] - Normalize YAML PubSub format

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineDebugOptions.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSources.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSourcesTest.java
Reverts apache/beam#31037
Causing breakages with the dataflow worker
=> Revert "Change type for UnboundedReaderMaxReadTimeSec"

it/kafka/src/test/java/org/apache/beam/it/kafka/KafkaIOST.java
Previously, the assertion was that writeNumRecords was greater than readNumRecords because the read pipeline couldn't finish reading all records before the pipeline timeout. Now, thanks to the increased timeout, all records are successfully read, so readNumRecords is greater than writeNumRecords.
Example of tests:
[Write to kafka job](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-04-23_13_13_52-10599600595588945166;step=Write%20to%20Kafka;mainTab=JOB_GRAPH;graphView=0?project=apache-beam-testing&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22)))
[Read from kafka job](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-04-23_13_14_29-10921604080829783601;step=Read%20from%20Kafka;mainTab=JOB_GRAPH;graphView=0?project=apache-beam-testing&pageState=(%22dfTime% …
=> Change assertion and pipeline timeout for kafka stress test

sdks/python/apache_beam/ml/inference/base.py, sdks/python/apache_beam/ml/inference/base_test.py, sdks/python/apache_beam/ml/inference/huggingface_inference.py, sdks/python/apache_beam/ml/inference/onnx_inference.py, sdks/python/apache_beam/ml/inference/pytorch_inference.py, sdks/python/apache_beam/ml/inference/sklearn_inference.py, sdks/python/apache_beam/ml/inference/tensorflow_inference.py, sdks/python/apache_beam/ml/inference/tensorrt_inference.py
Sometimes loading one model per process isn't feasible, but you still want multiple models loaded (e.g. if you have a GPU that can hold 3 copies of the model). This gives users the ability to express this.
Design doc (in review) - https://docs.google.com/document/d/1FmKrBHkb8YTYz_Dcec7JlTqXwy382ar8Gxicr_s13c0/edit
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/a …
=> Add ability to load multiple copies of a model across processes

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServices.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageStreamSource.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImplTest.java
Fixes #30646. Actually the feature is there but there is a bug prevented it from working properly.
The pipeline, when throttled, can see warning
```
Reporting metrics are not supported in the current execution environment.
```
raised from here: https://github.com/apache/beam/blob/8454cc9503008e28f5d3e90d39659352d46af9c2/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java#L1676
This is because the method is called on a callback thread that does not have thread level metrics container. Change it to increment the metrics back to StorageClientImpl temporarily then add it to Beam metrics in work item thread resolved the issue.
Tested with reading TPCDS_1T
- max worker 106
- throttling-msecs	15,060,000
- max worker: 57
- max worker: 43 …
=> Fix reporting metrics not supported warning for BigQueryIO Direct read when throttled

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/holds.go, sdks/go/pkg/beam/runners/prism/internal/engine/holds_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/teststream.go
Refactor out hold tracking to dedicated structures, so the logic is not replicated everywhere. Document the purpose of watermark holds within that.
This is yet another change to make the processing time change easier to read. In particular, event time watermark hold management is critical for correct behavior when waiting for processing time triggers. …
=> [#30083][prism] Factor out hold tracking to dedicated structures

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/ReadChangeStreamPartitionDoFn.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/SerializableSupplier.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dofn/ReadChangeStreamPartitionDoFnTest.java
ReadChangeStreamIO estimates the backlog (via `getSize`) for each partition using `partitionLowWatermark * partitionThroughtput`. The low watermark is held back by replication delay for replicated bigtable instances, which can cause the backlog to stay above the downscaling threshold even when the pipeline is 'caught up'
This adds a parameter to adjust the backlog downwards based on an estimate of the replication delay. We default it to 30 seconds which testing has shown works well for replicated instances.  …
=> Add ReadChangeStream IO param to adjust backlog estimates for replication delay

sdks/java/io/elasticsearch-tests/elasticsearch-tests-8/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOIT.java, sdks/java/io/elasticsearch-tests/elasticsearch-tests-8/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java, sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTestCommon.java, sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTestUtils.java, sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
This change adds a BoundedReader implementation based on the newer Point In Time search API (see [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html)). This API is the recommended mode when reading data from large indexes that imply retrieving documents using deep iteration (more than 10000 hits per slice). 
This mode should be available for Elasticsearch clusters with version 8 and up. 
When using the default read implementation, based on Scrolls, when the index is big enough and the number of documents is large, the creation of slices with more than 10000 elements to be iterated would make the read operations to fail. Now, with the PIT implementation, this is not a problem since ES does not have to keep track of the whole state of the index while …
=> Elasticsearch enable Point In Time based searches

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
New BigQuery Metrics will be auto-enabled after this change. Metrics can be disabled for a pipeline by passing the experiment `disable_per_worker_metrics`.  …
=> Enable BigQueryMetrics by default

model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto
This is the proto changes only for https://github.com/apache/beam/pull/30317 to unblock runner-side implementations. …
=> FnAPI proto changes for ordered list state.

sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management_test.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/server_test.go, sdks/go/pkg/beam/runners/prism/internal/web/assets/job-action.js, sdks/go/pkg/beam/runners/prism/internal/web/jobdetails.html, sdks/go/pkg/beam/runners/prism/internal/web/web.go
This PR addresses #29669 connecting Web UI cancel requests with the backend Job Management server.
- Fixes loading of CANCELED state for previously canceled Jobs
- Triggers Web request from UI to backend on cancel clicks
- Adds to /job/cancel http handler more detailed error reporting
In addition to `go test ...`, manual testing of this PR was as follows:
1. Run prism via `go run ./go/cmd/prism`
2. Execute example via `go run ./go/examples/large_wordcount --output=/tmp/large_wordcount/out --runner=universal --endpoint=localhost:8073 --environment_type=LOOPBACK`
3. Validate job display in web console at http://localhost:8074/job/job-001 with state `RUNNING`
4. Click Cancel button
5. Validate cancel-related log messages populate in console after [filtering for debug level …
=> [Prism] Connect Web UI cancel requests with backend

.test-infra/kafka/proxy/.terraform.lock.hcl, .test-infra/kafka/proxy/README.md, .test-infra/kafka/proxy/common.tfvars, .test-infra/kafka/proxy/compute.tf, .test-infra/kafka/proxy/prerequisites.tf, .test-infra/kafka/proxy/provider.tf, .test-infra/kafka/proxy/variables.tf
This PR automates [this guide](https://cloud.google.com/kubernetes-engine/docs/tutorials/private-cluster-bastion) using a terraform module to provision a compute engine instance bastion host to act as a proxy to a private Kafka cluster. See README committed in this PR for description, prerequisites, requirements, and usage. The goal is so that the same Kafka cluster can be used for local development/testing as well as for remote usage in a pipeline such as Dataflow.
Essentially, the solution creates a bastion host compute engine instance and outputs the gcloud command needed to tunnel traffic to the developer's local machine. …
=> Terraform module to provision a kafka proxy

.github/workflows/beam_PostCommit_Java_IO_Performance_Tests.yml
Once 2.56.0 is in, we can safely do this. Example - https://github.com/apache/beam/actions/runs/8929264960
Fixes #30787 …
=> Re-enable schedule trigger for PostCommit Java IO Performance Tests

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/logging/DataflowWorkerLoggingHandler.java
This is a continuation of https://github.com/apache/beam/pull/25922 and an attempt to fix an issue with Dataflow logging, when log messages sometimes get corrupted.
DataflowWorkerLoggingHandler logs message to a physical file, then a separate process in Dataflow reads this file and exports logs to Cloud Logging.
I found that the Jackson generator used by DataflowWorkerLoggingHandler has the SerializationFeature.FLUSH_AFTER_WRITE_VALUE feature enabled by default, which makes it flush the JSON output to the underlying stream after every object write. DataflowWorkerLoggingHandler currently writes the "severity" field as an object (generator.writeObjectField("severity", ...))., which results in the log message being flushed between "severity" and "message" fields, and some time Dataflow …
=> Avoid excessive flushing in DataflowWorkerLoggingHandler.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageStreamSource.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadTest.java
`Resolve` https://github.com/apache/beam/issues/30646#issuecomment-2080102737
* Reject split attempt early when there is an ongoing hasNext call in work item thread
* TImeout hasNext call in splitAtFraction in alignment with client splitReadStreamSettings
The issue exist on both released Beam and after #31096
Tested on read stream API v1 (default) and Dataflow legacy runner in a quota restricted project:
Without the change, the pipeline appears to stuck indefinitely. the [onRetryAttempt](https://github.com/apache/beam/blob/673da546c1465c931fdbbc5769e7d566ff55b4d8/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java#L1683) callback get called periodically. …
=> Suppress BigQuery read stream splitAtFraction when API  busy call or timeout

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkExecutionEnvironments.java, runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineOptions.java
fixes #21233
Add support for unaligned checkpoint for Flink runner. 
As I understand the python configuration and documentation will be automatically generated from the files I modified ?
=> add support for unaligned checkpoint for flink runner

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/LockFreeHistogram.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/LockFreeHistogramTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverterTest.java
Currenlty, PerWorkerHistograms are in a Map that's keyed by `KV<MetricName, BucketType>`. After this change the map they're stored in will be Keyed by `MetricName`.
Computing a hash/equality for the `KV` object is non-trivial and has a fair amount of overhead [src](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/values/KV.java#L124). Since we need to do a map lookup for the histogram metric every time we record a value, we can remove a lot of the overhead by simply using a map that's only Keyed by `MetricName`.
The first time a `Histogram` is requested for a `<Metric Name, Bucket Type>` we will use the `BucketType` to create the histogram object. Future requests for a `Histogram` for that `Metric Name` will return the original histogram object, …
=> Stop using KV as the Key for Histogram Metrics

sdks/python/apache_beam/typehints/intrinsic_one_ops.py, sdks/python/apache_beam/typehints/intrinsic_one_ops_test.py, sdks/python/apache_beam/typehints/opcodes.py, sdks/python/apache_beam/typehints/trivial_inference.py, sdks/python/apache_beam/typehints/trivial_inference_test.py
Implements new operations for trivial inference ahead of Python 3.12 support to fix existing unit tests. These operations can be seen listed at https://docs.python.org/3/library/dis.html
Not every operation has been implemented, but not every operation comes up in the context of us doing type introspection on functions. A few of these operations were actually introduced in 3.11 and weren't used in our test cases until 3.12!
fixes: #31047 
To …
=> Fix trivial inference tests for Python 3.12 support

build.gradle.kts, sdks/python/test-suites/tox/py38/build.gradle, sdks/python/test-suites/tox/pycommon/build.gradle, sdks/python/tox.ini
Delegate the choice of python version for linters, docs generation and mypy checks to GHA configs, instead of hardcoding both in tox.ini, in gradle configs, and in yml files for GHA actions.
Possible sideeffects: when running the checks locally, different users might not be using a consistent python version, which might cause issues for if mypy produces different results on different versions. GHA should still run with a consistent version for everyone. It is still possible to manually set `basepython = python3.8` setting in tox.ini if it becomes necessary.  
https://github.com/apache/beam/issues/20209 …
=> Don't hardcode python version in tox.ini for lint, mypy and docs.

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java
These tests should have always failed. But they seem to only fail in particular contexts inside Google when we re-run them with internal tools. Perhaps worth a follow-up to check that this enforcement actually works... …
=> Turn off abandoned node enforcement in some Reshuffle unit tests where it is not needed

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/YamlUtils.java, sdks/java/io/kafka/build.gradle, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProviderTest.java, sdks/java/managed/build.gradle, sdks/java/managed/src/main/java/org/apache/beam/sdk/managed/Managed.java, sdks/java/managed/src/main/java/org/apache/beam/sdk/managed/ManagedSchemaTransformProvider.java, sdks/java/managed/src/main/java/org/apache/beam/sdk/managed/ManagedTransformConstants.java
Onboarding KafkaIO to be available via Managed API
=> Support Kafka Managed IO

.github/actions/setup-default-test-properties/test-properties.json, sdks/go/examples/wasm/README.md, sdks/python/apache_beam/options/pipeline_options.py, sdks/typescript/src/apache_beam/runners/flink.ts, settings.gradle.kts, website/www/site/content/en/documentation/runners/flink.md
Adds documentation on how to correctly update published versions of Flink runner. …
=> [flink] Add documentation for Flink runner versions updates

it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java
Add new AVRO and JSON tests for BigQueryIOST for AT_LEAST_ONCE writing method. 
[Write job example](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-05-09_16_07_40-7286799108460747700;step=Write%20to%20BQ;mainTab=JOB_GRAPH;bottomTab=JOB_LOGS;logsSeverity=ERROR;graphView=0?project=apache-beam-testing)
=> Add new BigQueryIO stress tests for AT_LEAST_ONCE writing method

sdks/python/apache_beam/dataframe/frames_test.py
=> Exclude a test that doesn't pass due to an upstream issue.

sdks/python/apache_beam/options/pipeline_options_test.py, sdks/python/apache_beam/testing/test_pipeline_test.py
fixes: https://github.com/apache/beam/issues/31048
=> Remove a deprecated test helper.

sdks/python/apache_beam/typehints/intrinsic_one_ops_test.py, sdks/python/apache_beam/typehints/opcodes.py
Fixes a bug with `load_fast_and_clear` that was deleting an index in an array that was later used as intermediate storage instead of setting the value to `None` in the interim and fixed the list comprehension in the intrinsic operations test that seems to have been accidentally clobbered in an in-between state from an old form and the new one before merging.
Fixes #31047 …
=> Fix Python 3.12 python hinting errors on MacOS

sdks/python/container/boot.go
Using logger directly may result in Null pointer exception like:
```
panic: runtime error: invalid memory address or nil pointer dereference
```
This PR uses BufferedLogger instance to log reliably.
Tried on Dataflow Runner: …
=> [Python] Use BufferedLogger instead of logger to log in boot.go

examples/java/src/main/java/org/apache/beam/examples/snippets/Snippets.java
This should help users avoid https://github.com/apache/beam/issues/26465#issuecomment-1764155906 …
=> Avoid side input issue where Latest.globally produces 2 elements in a window

sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipeline.java
Since #31229 made me take a quick look at this code, I thought I would also eliminate the nullness errors. The code could really be simplified too. There is a whole class hierarchy just for one enforcement... …
=> Fix nullness errors in TestPipeline

.github/workflows/beam_PreCommit_Python.yml, .github/workflows/beam_PreCommit_Python_Dataframes.yml, .github/workflows/beam_PreCommit_Python_Examples.yml, .github/workflows/beam_PreCommit_Python_ML.yml, .github/workflows/beam_PreCommit_Python_Runners.yml, .github/workflows/beam_PreCommit_Python_Transforms.yml, sdks/python/apache_beam/transforms/sql.py
This reverts commit 3ca2c5f27e611a9611950ddf388fbbe5e8a1ca31 from https://github.com/apache/beam/pull/31255
=> Revert "Don't specify an unnecessary config given that tox task and gradle config already defines the Python version."

sdks/python/apache_beam/ml/transforms/embeddings/huggingface_test.py, sdks/python/setup.py
- Skip TFT tests on 3.11+ due to https://github.com/tensorflow/transform/issues/313
- Add an upper bound to TF due to https://github.com/apache/beam/issues/31294
- Run Huggingface tests serially
Fixes: #31287
=> Skip tests using TFT in Beam ML unit test suite on Python 3.11+

.github/workflows/IO_Iceberg_Unit_Tests.yml
We need to setup GCP auth before running integration tests.
=> Fix permared Iceberg unit tests

.github/workflows/beam_PostCommit_Python_Dependency.yml
Dependency postcommit suite runs multiple small suites of unit tests. Installing beam takes 3-4 minutes to build a wheel. Using a wheel to install beam should speed up the suite, since the wheel will be built once. …
=> Install Beam from wheels in Dependency Compat Test Suite.

sdks/python/apache_beam/io/requestresponse_test.py
Refactor to use retry decorator in https://github.com/apache/beam/pull/31247 …
=> [Python] Use retry decorator for retrying

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/RetryHttpRequestInitializer.java, sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/Transport.java, sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/TransportTest.java
This PR implements feature request #31299 for Java SDK.
We also try to make the Java user-agent consistent with the Python one (see #31300) 
by inserting "apache-beam/VERSION".
---
Some more notes:
In Java SDK, GCSIO (from `com.google.cloud.hadoop.gcsio`) is used as an accessing layer to communicate with GCS. Internally, it depends on the storage client (from `com.google.api.services.storage`) to assemble and handle HTTP requests.  
GCSIO can either create a new Google Cloud Storage client during initialization or utilize an existing one, which is the approach adopted by Beam. Ideally, it will be better if Beam can use the first code path so that we can leave all the GCS connection detail to GCSIO. 
Follow-up tasks
=> [Java] Add job name to GCS custom audit info

.github/trigger_files/beam_PostCommit_Python.json, CHANGES.md, sdks/python/apache_beam/io/requestresponse.py, sdks/python/apache_beam/transforms/enrichment.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigquery.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigquery_it_test.py, sdks/python/apache_beam/transforms/enrichment_handlers/bigquery_test.py, sdks/python/scripts/generate_pydoc.sh
Implemented the BigQuery handler for Enrichment transform.
To use this handler you need either of the following combinations:
1. `table_name`, `row_restriction_template`, `fields`
2. `table_name`, `row_restriction_template`, `condition_value_fn`
3. `query_fn`
In addition to this, batch size can be specified with `min_batch_size` and `max_batch_size`. These are passed to the `BatchElements` transform just before making calls to BigQuery. This helps reducing the cost on the BigQuery side.
By default, the handler pulls all columns from the BigQuery table. To override this, use the `column_name` parameter to specify a list of column names to fetch.
The user interface here is pretty similar to [`TableReadOptions`](https://cloud.google.com/python/docs/reference/bigquerystorage/latest/google.clou …
=> [Python] BigQuery handler for enrichment transform

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOTest.java
This change adds `readMessagesWithAttributesWithCoderAndParseFn` that enables forwarding of the Pubsub message attributes to make them available when applying the provided ParseFn. The new method is similar to `readMessagesWithCoderAndParseFn`, but adds `setNeedsAttributes(true)`.
The `readMessagesWithCoderAndParseFn` of PubsubIO skips forwarding the pubsub message attributes to the provided parse function. In the use case I am solving, the attributes of the message contain the schema fingerprint needed for the parsing. …
=> PubsubIO: add readMessagesWithAttributesWithCoderAndParseFn

sdks/go/pkg/beam/core/runtime/exec/datasource.go
Make it clearer that Data and Timers aren't interacting negatively, as a cursory look made it appear that if Elements ever contained Data and Timers simultaneously, that a successful execution of timers would cause an error processing data to be swallowed.
Likely a red herring though, as Data and Timers do not have the same PtransformID: Data always points to the synthetic DataSource transform, while timers are directly routed to their consuming Transform's OnTimer callback. But it's nicer to not have to remember that.
Similarly, in the name of readability, the split check is also moved into the Data handling callback in DataSource.Process, so it doesn't look like a Split in bundle processing would skip any outstanding timers. Since the check relies on the targeted PTransformID and they …
=> [Go SDK] Make it clearer that timers and data don't interact negatively in element batches.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetrics.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetricsTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilTest.java
=> Enable BigQueryIO write throttling detection

sdks/python/apache_beam/io/filesystems.py
fixes #31218 
This PR contains these changes;
- Added a new error handling for `ModuleNotFoundError`
- no logging  
- Changed the error handling for `ImportError`
- logging warn log with the exception to identify any issues around import. …
=> Logging loading  filesystems failures.

sdks/python/apache_beam/io/gcp/gcsio.py, sdks/python/apache_beam/io/gcp/gcsio_integration_test.py, sdks/python/apache_beam/io/gcp/gcsio_test.py, sdks/python/setup.py
addresses #31330 in Python SDK. The logic is similar to #31324.
=> [Python] Disable soft delete policy when creating new default bucket.

.github/workflows/build_wheels.yml, sdks/python/build.gradle
Follow up for #31321 
Required for: #29149
=> Upgrade cibuildwheel in another place as well.

sdks/java/io/debezium/src/test/java/org/apache/beam/io/debezium/DebeziumReadSchemaTransformTest.java
`Fix` #31346
The "wrong host" used for the test is a real IP. It is resolvable. It either changed recently or added firewall rule causing test failure
solution is to use a true wrong host (169.254.x.x), and remove the check of error content, as it is platform dependent
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https …
=> Fix DebeziumIO testWrongHost trying to connect real external address

.github/workflows/build_wheels.yml, .test-infra/jenkins/CommonJobProperties.groovy, sdks/python/build.gradle, sdks/python/setup.py
Setting this variable breaks wheel building workflow on Python 3.12 and doesn't seem to be necessary anymore on new releases of setuptools.
Required for #29149
=> Don't set SETUPTOOLS_USE_DISTUTILS=stdlib 

.github/workflows/beam_PostCommit_Java_Tpcds_Flink.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink.yml, CHANGES.md, contributor-docs/release-guide.md, gradle.properties, release/build.gradle.kts, release/src/main/groovy/quickstart-java-flinklocal.groovy, runners/flink/1.18/build.gradle, runners/flink/1.18/job-server-container/build.gradle, runners/flink/1.18/job-server/build.gradle, sdks/go/examples/stringsplit/stringsplit.go
Reintroduce Flink 1.18 support. …
=> Reapply "[#30789] Add support for Flink 1.18 (#31062)"

sdks/python/setup.py
=> Don't install TF on Python 3.12, since there is no compatible version atm.

sdks/java/core/src/test/java/org/apache/beam/sdk/testing/CoderPropertiesTest.java
This test asserts on the message of an AssertionError thrown by a
failing hamcrest assertion. The message changes in the latest versions
of hamcrest.
```
1) testBadCoderIsNotDeterministic(org.apache.beam.sdk.testing.CoderPropertiesTest)
java.lang.AssertionError:
Expected: a string containing "<84>, <101>, <115>, <116>, <68>"
but: was "
Expected: [<24b>, <84b>, <101b>, <115b>, <116b>, <68b>, <97b>, <116b>, <97b>, <51b>, <51b>, <50b>, <54b>, <49b>, <57b>, <57b>, <52b>, <57b>, <48b>, <57b>, <57b>, <55b>, <48b>, <53b>, <53b>]
but: was [<24b>, <84b>, <101b>, <115b>, <116b>, <68b>, <97b>, <116b>, <97b>, <51b>, <51b>, <50b>, <54b>, <49b>, <57b>, <57b>, <52b>, <56b>, <50b>, <48b>, <52b>, <49b>, <54b>, <49b>, <53b>]"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at …
```
=> Fix an incompatibility with hamcrest 2.2

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderBase.java, runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/EmptyUnboundedSource.java, runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReaderTest.java
=> [flink] #31390 emit watermark with empty source

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableService.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImplTest.java
The underlying issue with attempt timeout is fixed in the Bigtable client. We don't need to pass around operation and attempt timeout in the reader anymore. This PR cleans up the code that's not used anymore. …
=> Clean up stale code in BigtableService

sdks/python/apache_beam/io/gcp/bigquery_write_it_test.py, sdks/python/apache_beam/ml/inference/tensorflow_inference_test.py
After https://github.com/apache/beam/pull/31364 is merged, we started seeing this:
```
=================================== FAILURES =================================== |  
-- | --
  | [31m[1m_ BigQueryWriteIntegrationTests.test_big_query_write_temp_table_append_schema_update _[0m |  
  | [gw5] linux -- Python 3.10.14 /runner/_work/beam/beam/build/gradleenv/417525523/bin/python3.10 |  
  |   |  
  | args = (<apache_beam.io.gcp.bigquery_write_it_test.BigQueryWriteIntegrationTests testMethod=test_big_query_write_temp_table_append_schema_update>,) |  
  | kw = {} |  
  |   |  
  | @functools.wraps( |  
  | f, functools.WRAPPER_ASSIGNMENTS + ("__defaults__", "__kwdefaults__") |  
  | ) |  
  | def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any: |  
  | >       return self(f, *args, **kw) |   …
```
=> Changed the retry order for test_big_query_write_temp_table_append_schema_update

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
fixes #31360 Add withoutValidation option to Bigtable change stream IO.
This aligns with withoutValidation of Read and Write IO. This allows users to create a pipeline without validating the correctness of the change stream configurations. This includes validating the change stream table exists, metadata table exists, metadata table is using the correct schema, and app profile used is appropriate. This allows the users to create a pipeline without Bigtable permissions locally. Bigtable permissions is still required by the pipeline itself in order to stream the table. …
=> Add option to disable validation of cloud bigtable change stream IO

release/src/main/Dockerfile, release/src/main/python-release/python_release_automation.sh, release/src/main/scripts/build_release_candidate.sh
Include Python 3.12 for release validation purposes.
drive-by change: update a reference to docs tox task, it was recently changed, see: https://github.com/apache/beam/blob/e764fc9c17dbc575d4a16b5e6454f4d38ef752be/sdks/python/tox.ini#L148
#29149
=> Include Python 3.12 in release validation steps.

sdks/python/apache_beam/dataframe/expressions.py, sdks/python/apache_beam/dataframe/io_test.py, sdks/python/apache_beam/dataframe/transforms.py
ReadFromCsv with an explicit dtype produced graphs that had quadratic traversal (though the computed results, sets, were always correct).
This fixes https://github.com/apache/beam/issues/31152 and should help other deep expressions with common references as well. …
=> Memoize some dataframes analysis operations.

sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java, sdks/python/apache_beam/transforms/external.py, sdks/python/apache_beam/transforms/external_test.py, sdks/python/apache_beam/yaml/tests/sql.yaml
=> Better mixed Java/Python error messages for external transforms.

sdks/python/apache_beam/io/gcp/bigquery.py
Before (using a gcp project of limited quota):
upscale to 270+ worker aggressively, before cancel the job
After (note: backend change not yet rolled out on prod):
(up-hill part, max worker=181)
(down-hill part)
note: autoscaler won't kill active worker until current work item finish, and there is a 6 min lapse from worker started to reactive downscale working, see https://github.com/apache/beam/pull/31253#issuecomment-2118608486 …
=> enable BigQueryIO Storage Read throttling detection for Python SDK

.github/workflows/build_release_candidate.yml
Adds a build & stage to RC creation to release signed hashed and zipped prism binaries to a release.
Currently requires a release with the RC tag to exist, actually straightening out the logic is best handled in a separate PR, as this change is sufficiently complex as is without including the clobber protection logic if targetting an already published release.
Changes the workflow dispatch to us a JSON object instead of individual string fields. The dialog now looks like this:
Not an ideal experience, but we hit the 10 input limit otherwise.
The action syncs down the Dev Apache SVN repo, builds prism binaries for ARM64, AMD64 for Linux, Darwin (osx), and Windows, zipping up the binary, creating signature and sha512 hash files.
These are uploaded to a Github prerelease for the RC tag, like …
=> [#29697] Add prism artifact building workflow.

sdks/python/apache_beam/yaml/yaml_combine.py, sdks/python/apache_beam/yaml/yaml_mapping.py, sdks/python/apache_beam/yaml/yaml_mapping_test.py
There have been type inferencing issues with Beam YAML `MapToFields` where the type(s) from the upstream pcollection are dropped when the `beam.Select` is used on unmapped fields in the `MapToFields` expansion (i.e. when using `append: true`, the unmapped fields are mapped to AnyType). 
The fix is to register type hints for the implicitly appended fields. …
=> [YAML] Fix simple YAML mappings type hinting

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AppendClientInfo.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProto.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProto.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/RowMutation.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/RowMutationInformation.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiCDC.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsBeamRow.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsGenericRecord.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsTableRow.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/testing/FakeDatasetService.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProtoTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProtoTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/RowMutationInformationTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkRowUpdateIT.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java
This PR closes #31335 via refactoring BigQueryIO's assignment of the `_CHANGE_SEQUENCE_NUMBER` pseudo column from a long to fixed hex string.
All BigQuery related tests for `./gradlew :sdks:java:io:google-cloud-platform:postCommit` and `./gradlew :sdks:java:io:google-cloud-platform:build` passed on my local machine.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com …
=> Refactor RowMutationInformation to use string type

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerConfig.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java, sdks/java/io/google-cloud-platform/src/test/java/com/google/cloud/spanner/OptionsImposter.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteTest.java
Addresses https://github.com/apache/beam/issues/31007 …
=> SpannerIO: support max commit delay

sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/SortValues.java, sdks/java/extensions/sorter/src/test/java/org/apache/beam/sdk/extensions/sorter/SortValuesTest.java
A small optimization for `SortValues` transform to avoid doubly roundtrip encoding values that are already `byte[]`s -- they can be passed directly to the Sorter. …
=> Don't re-encode byte[] values in SortValues transform

sdks/python/apache_beam/runners/worker/data_plane.py
https://github.com/apache/beam/pull/30639 added an codepath to fail early when SDK emits a large element. 
This PR adds a warning when we detect large elements that can be problematic, but still within the GRPC limits.
=> Emit a warning when large elements are detected.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/container/license_scripts/dep_urls_java.yaml, sdks/java/io/cdap/build.gradle, sdks/java/io/hadoop-format/build.gradle
=> Bump Jackson databind to 2.15

website/www/site/content/en/documentation/programming-guide.md
The line break in front of the `span` lead to a space between "method" and the dot if Python was not selected.
[![Build …
=> Remove excess space from Programming Guide (typo fix)

examples/java/build.gradle
**Fix one small typo in build script to match the instruction at [line](https://github.com/VineetRamuk/beam/blob/5c30b1d6db27fff299fc28249f9f195d54651abd/contributor-docs/code-change-guide.md?plain=1#L221)** …
=> Fix one small typo in build script.

sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go
This PR addresses #31461 adding Never Trigger to the list of feature support checks in the Prepare Job context.
To validate this fix:
1. Run Prism server.
```
./gradlew :runners:prism:runServer
```
2.  Execute `:runners:portability:java:ulrLoopbackValidatesRunnerTests` on Prism, filtering for `org.apache.beam.sdk.testing.PAssertTest`:
```
TEST=org.apache.beam.sdk.testing.PAssertTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
``` …
=> Add Trigger_Never to Prepare features check

CHANGES.md, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableService.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
Make sure to close the reader, (and therefore the underlying stream) when finishing a read in BigtableIO. See the issue here: https://github.com/apache/beam/issues/31477. …
=> Ensure that BigtableIO closes the stream after reading

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/core/build.gradle, sdks/java/expansion-service/build.gradle, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/Dependency.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionServiceConfig.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionServiceOptions.java, sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/JavaClassLookupTransformProvider.java, sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceTest.java, sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/JavaClassLookupTransformProviderTest.java, sdks/java/expansion-service/src/test/resources/test_expansion_service_config.yaml, sdks/java/transform-service/build.gradle, sdks/java/transform-service/src/main/java/org/apache/beam/sdk/transformservice/TransformServiceConfig.java, sdks/java/transform-service/src/main/java/org/apache/beam/sdk/transformservice/TransformServiceOptions.java, sdks/java/transform-service/src/test/java/org/apache/beam/sdk/transformservice/ExpansionServiceTest.java, sdks/java/transform-service/src/test/resources/test_transform_service_config.yml
This fixes https://github.com/apache/beam/issues/31405. …
=> Parse YAML ExpansionService configs directly using SnakeYAML

sdks/java/io/hadoop-format/build.gradle
https://github.com/apache/beam/pull/31406 bumped up the SnakeYAML dependency used by Expansion Services to 2.2 which seems to have changed the dependency resolution for the hadoop-format module resulting in a failure. This tries to resolve by pinning the SnakeYAML version to 1.33. …
=> Pins SnakeYAML version to 1.33 for Hadoop Format tests

sdks/python/apache_beam/pipeline.py, sdks/python/apache_beam/pipeline_test.py
Now we surface `auto_unique_labels` in the error message when two PTransforms have the same labels.
Context: https://github.com/apache/beam/pull/28984 …
=> Update the transform label error message

sdks/python/apache_beam/transforms/ptransform.py
The superclass implementation of `__rrshift__` was getting overridden by the `__getattr__` code that was writen with the express intent of preserving the given label (for other operations).
In particular this is needed for transforms like ReadFromCsv where a default label is provided but users should be able to override it. …
=> Fix issue where manual subsequent label designations were ignored.

sdks/go/test/integration/integration.go
New TestStream using test was added, and not filtered out from the spark runs, causing failures.
Part of resolving #31475 …
=> [#31475] Filter out test stream using test from spark suite

sdks/python/apache_beam/io/gcp/big_query_query_to_table_it_test.py
Addresses https://github.com/apache/beam/issues/30513 and https://github.com/apache/beam/issues/29617
Simply retry this test for now. …
=> retry test_big_query_legacy_sql

sdks/python/apache_beam/ml/transforms/embeddings/huggingface.py, sdks/python/apache_beam/ml/transforms/embeddings/huggingface_test.py
Adds support for generating image embeddings via the sentence-transformers library. 
Part of #31500 …
=> Implement Hugging Face Image Embedding MLTransform

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
`SpannerIO` is setting pipeline options under the hood, causing potential clashes with user defined options, or when the connector is used more than once in the same pipeline (and using conflicting values).
This PR just removes the code setting the pipeline options. All tests are passing. Running this version in a job using the `readChangeStream()` connector is working fine. The only noticeable effect is that the `metadata_table` option is not set in the pipeline options.
This fixes #31411 
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch= …
=> Remove pipeline options override from SpannerIO readChangeStream connector

sdks/python/apache_beam/io/gcp/gcsio.py, sdks/python/apache_beam/io/gcp/gcsio_test.py, sdks/python/apache_beam/options/pipeline_options.py, sdks/python/apache_beam/options/pipeline_options_test.py
@address https://github.com/apache/beam/issues/31330 for Python SDK
=> [Python] Add warning to temp_location and staging_location when the bucket has soft delete enabled

sdks/python/apache_beam/yaml/main.py, sdks/python/apache_beam/yaml/main_test.py
This will make it much easier to use YAML for writing dataflow templates. In particular, one will be able to specify the ParameterMetadata as one does for other templates, along with a (presumably hidden) parameter enumerating these parameters as `jinja_variable_flags` and a (likewise likely hidden) parameter for `yaml_pipeline_file` pointing to the yaml file on GCS and using the standard YAML template base image.
Future work could possibly automate this.
We could consider putting this code at https://github.com/Polber/DataflowTemplates/blob/main/python/src/main/python/yaml-template/main.py , but this form seems non-invasive enough to keep here (especially compared to the other variant that just blindly interpreted all flags as jinja variables) and that lets the template version simply …
=> Allow flags to be used as jinja template variables.

sdks/python/apache_beam/yaml/yaml_io.py
As well as being good practice, this will give us better generated documentation. …
=> Add documentation and types to ReadFrom/WriteToBigQuery.

local-env-setup.sh
=> Update Python version in the dev environment script.

.github/workflows/beam_PreCommit_Java_Solace_IO_Direct.yml, sdks/java/io/solace/build.gradle, settings.gradle.kts
This is a PR for the Solace Read connector which includes a minimal project setup (addresses #31440).
It contains a gradle module setup and a github workflow file. …
=> Solace Read connector - project init

sdks/python/apache_beam/ml/transforms/embeddings/tensorflow_hub.py, sdks/python/apache_beam/ml/transforms/embeddings/tensorflow_hub_test.py
Adds an image embedding manager for tensorflow hub usage and a small test case. Leverages the same general code as the text version, but removes the preprocessing url option to avoid hitting a code path in the handler that is specific to BERT output. 
Part of #31500  …
=> Add image embedding support to TFHub MLTransforms

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamCalcRel.java, sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslBase.java
=> Support Row fields with type ITERABLE in Beam SQL Extension

CHANGES.md, sdks/java/core/src/main/java/org/apache/beam/sdk/util/RowJsonUtils.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowJsonCoder.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowJsonCoderTest.java
Fix a regression noted in #26743 …
=> Fix StreamConstraintsException introduced in jackson 2.15

contributor-docs/release-guide.md
Update the Release guide with currently gitHub release steps for prism #29697. …
=> [#29697] Update the Release guide with currently manual GitHub release steps for prism.

sdks/python/apache_beam/runners/worker/data_plane.py
#31581 reduces intermittent errors in pipelines that have large elements.
Reasons to cherry-pick: 
1) In 2.57.0 we introduced a warning about large elements with https://github.com/apache/beam/pull/31363, however this warning might be unactionable for cases when large elements were implicitly created by Beam.  
2) At least one customer is waiting  to see this change in a stable version of Beam.
=> [release-2.57.0] Cherrypick #31581 into the release branch.

CHANGES.md, sdks/java/core/src/main/java/org/apache/beam/sdk/util/RowJsonUtils.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowJsonCoder.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowJsonCoderTest.java
Fix a regression noted in #26743 …
=> [Release-2.57.0] Cherry-pick #31580 into release branch

sdks/python/apache_beam/io/gcp/gcsio.py, sdks/python/apache_beam/options/pipeline_options.py
We observed a few timeout failures in our internal test suite. This PR will fix the timeouts by setting a deadline for the request. It will also fix a missing scenario where we need to check whether to fire the warning.
=> Fix internal test failure caused by PR 31550

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
Use the original way of validating Bigtable Change Stream table existance to improve compatibility with testing.
In #31376 I moved around validation and introduced a different way of checking the existence of the Change Stream table using BigtableServiceFactory instead of BigtableChangeStreamAccessor. BigtableChangeStreamAccessor has some customization that is not included in BigtableServiceFactory and is needed for integration testing against different environments.
Ideally, we have only one way of interfacing with Bigtable services, so we would merge BigtableServiceFactory and BigtableChangeStreamAccessor. But meanwhile, we should revert back to using BigtableChangeStreamAccessor in the ChangeStream connector. …
=> Use the original way of validating Bigtable Change Stream table existance to improve compatibility with testing

sdks/python/apache_beam/io/gcp/gcsio_integration_test.py
=> Add try-except block to guard against NotFound exception from GCS delete

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager_test.go, sdks/go/pkg/beam/runners/prism/internal/execute.go
This PR closes #31338, refactoring `engine.ElementManager` `Bundles` method to receive a `context.CancelCauseFunc` so that the Job fails instead of panic. This allows us to associate failing validation tests with stuck jobs. …
=> [Prism] Terminate Job with CancelFn instead of panic

sdks/python/apache_beam/io/gcp/gcsio.py, sdks/python/apache_beam/io/gcp/gcsio_test.py, sdks/python/apache_beam/options/pipeline_options.py
Cherry-pick #31550 and #31602 onto release branch …
=> Cherrypick #31550 and #31602 onto release branch

sdks/java/io/solace/build.gradle, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/SolaceCheckpointMark.java
PR for the Solace Read connector (addresses #31440).
Adds checkpoint-related classes.
Unit tests are depended on the UnboundedReader from #31476 so will be added there.
Depends on #31595 …
=> Solace Read connector: checkpoint-related classes

sdks/java/io/solace/build.gradle, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/MessageReceiver.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SempClient.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SempClientFactory.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SessionService.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SessionServiceFactory.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/SolaceCheckpointMark.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/UnboundedSolaceReader.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/UnboundedSolaceSource.java
PR for the Solace Read connector (addresses #31440).
Adds UnboundedSource and UnboundedReader …
=> Solace Read connector: UnboundedSource and UnboundedReader

sdks/python/apache_beam/options/pipeline_options.py, sdks/python/apache_beam/pipeline.py, sdks/python/apache_beam/pipeline_test.py
Fix #31523
`auto_unique_labels` is only supported by Python. …
=> warn when using auto_unique_labels

.github/workflows/build_release_candidate.yml
Fix issue where the release version directory might not exist yet for the SVN repo when the prism build step occurs.
```
...........Adding prism artifacts to the Dev Apache SVN repo...........
svn: E150000: Can't find parent directory's node while trying to add '/home/runner/work/beam/beam/beam/2.57.0/prism'
svn: E155010: The node '/home/runner/work/beam/beam/beam/2.57.0' was not found.
```
Adding --parents makes SVN also add intermediate parents before making the update. …
=> Update build_release_candidate.yml to resolve an ordering issue WRT prism dev artifacts.

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow.json, .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming.json, .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow_V2.json, .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow_V2_Streaming.json, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/RedistributeByKeyOverrideFactory.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/internal/DataflowGroupByKey.java
https://github.com/apache/beam/pull/31490 plumbs Redistribute "allow_duplicates" property to Dataflow.
Reason to cherry-pick:
With release-2.57.0, Dataflow customers can use per-stage checkpointless shuffle (which allows duplicated elements in the output) by using the Redistribute transform, rather than having to enable checkpointless shuffle mode for the entire pipeline through an experiment. …
=> [release-2.57.0] Cherrypick #31490 into the release branch.

sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
While working on #31403, the changes herein were required to allow Python's Wordcount to execute.
While the pipeline does succeed, some the python shutdown is sometimes noisy WRT GRPC ordering, which may need to be sorted out at a later time. …
=> [#31403] Relax prism constraints to allow python wordcount to execute.

sdks/python/apache_beam/yaml/pipeline.schema.yaml, sdks/python/apache_beam/yaml/yaml_provider.py, sdks/python/apache_beam/yaml/yaml_provider_unit_test.py, sdks/python/apache_beam/yaml/yaml_transform.py
This can be more useful than jinja's {% include %} as it can refer to urls, does not have to assume perfect indentation of the included file, and avoids applying templitization to the included file. …
=> [YAML] Allow explicitly including external provider lists.

sdks/go/pkg/beam/runners/prism/internal/worker/worker.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go
This PR closes #31628 adding handling for MultimapKeysSideInput in State GetRequests. Since this surfaced in Java validation tests of `org.apache.beam.sdk.transforms.ViewTest`, validated on Prism via:
```
TEST=org.apache.beam.sdk.transforms.ViewTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
```
This PR fixes the following ViewTest tests:
- testMapAsEntrySetSideInput
- testWindowedMultimapAsEntrySetSideInput
- testWindowedMapAsEntrySetSideInput
- testMultimapAsEntrySetSideInput …
=> Handle MultimapKeysSideInput in State GetRequests

sdks/go.mod, sdks/java/container/boot.go, sdks/java/container/boot_test.go
The current setting (70% of max memory) is not efficient for extremely large memory machine.
Internal context: b/340891295#comment14 …
=> Adjust JVM heap size for extremely large memory machine

sdks/java/io/solace/build.gradle, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/RetryCallableManager.java, sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/RetryCallableManagerTest.java
This is the 2nd PR for the Solace Read connector (addresses #31440).
It depends on the #31476 (root). 
The files that are added/modified in this PR, comparing to the #31476:
- build.gradle
- RetryCallableManager.java
- RetryCallableManagerTest.java
This mechanism will be used for any network calls, such as creating and starting a message receiver (will be added in following PRs). …
=> Solace Read connector: RetryCallable mechanism 

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProto.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProtoTest.java
fixes #31674 
There is an issue with the `AvroGenericRecordToStorageApiProto.java` class in Apache Beam, which is responsible for converting an Avro generic record into a proto object for writing to BigQuery using the Storage API.
The funtion `private TableFieldSchema fieldDescriptorFromAvroField(Schema.Field field)` handles the array types effectively when the array in the Avro schema is defined as follows:
```json
{
"name": "anullablearray",
"type": "array",
"items": "string",
"default": []
}
```
it produces such a proto field as expected:
```proto
name: "De0c5bb51_aded_475d_946d_6ece875416a8"
field {
name: "anullablearray"
number: 1
label: LABEL_REPEATED
type: TYPE_STRING
}
```
However, it doesn't preserve the type `array` and uses the element type of the array when a nullable array is …
=> Fix nullable array issue 31674 in AvroGenericRecordToStorageApiProto

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java
This fixes a regression introduced by https://github.com/apache/beam/pull/31128. …
=> Fixes a regression related to BQ read transform upgrade via the TransformService

runners/core-java/src/test/java/org/apache/beam/runners/core/StateInternalsTest.java, runners/spark/src/main/java/org/apache/beam/runners/spark/stateful/SparkStateInternals.java, runners/spark/src/test/java/org/apache/beam/runners/spark/stateful/SparkStateInternalsTest.java
fixes #31668 
This PR contains theses change
- add `isEmpty` test in `StateInternalsTest#testMap`
- add map state in `SparkRunner` …
=> Add spark mapstate

sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java, sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransformOptions.java, sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonService.java
Fix #31680
This was exposed in bootstrap_beam_venv.py, incuding the ability to send a tarball:
https://github.com/apache/beam/blob/90d3f8a177ff935a09852fd85892bb1399b85c91/sdks/java/extensions/python/src/main/resources/org/apache/beam/sdk/extensions/python/bootstrap_beam_venv.py#L70-L71
However, it is not exposed in PythonExternalTransform that uses it.
Tested by manually adding a test (after adding direct-java dependency in test runtime classpath)
```
@Test
public void testCustomBeamRequirement() {
PythonExternalTransformOptions options = PipelineOptionsFactory.fromArgs("--customBeamRequirement=2.55.0").create().as(PythonExternalTransformOptions.class);
Pipeline p = Pipeline.create(options);
p.apply(Create.of("a")).apply(PythonExternalTransform
.<PCollection<String>, …
```
=> Allow override beam version for PythonExternalTransform via pipeline option

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AppendClientInfo.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
Storage API connections in batch are left open and not closed properly.
This is because we pin the underlying StreamAppendClient twice: once for the bundle and once for the cache
When we are finished with the stream however, we only unpin once for the bundle (and not for the cache).
Batch mode already creates a lot of streams and connections (one stream/connection per destination per bundle) compared to streaming mode. Leaving connections unclosed leads to many concurrent connections and can quickly exhaust the [quota](https://cloud.google.com/bigquery/quotas#write-api-limits).
This change adds a line to invalidate the cached client after we finish using it in a bundle.
Also creates a counter to keep track of active connections.
=> Properly close Storage API batch connections

sdks/python/apache_beam/options/pipeline_options.py, sdks/python/apache_beam/runners/portability/prism_runner.py, sdks/python/apache_beam/runners/portability/prism_runner_test.py
Adds Prism as a runner for the Python SDK.
* For release versions, attempts to download a platform specific zip from the GitHub release, if a local binary one is not found in the local cache.
* For dev versions, requires an override
* Version used for this can be overridden by `--prism_beam_version_override`
* The above is fully overridden by a `--prism_location` flag that provides a location of an appropriate zip or binary for the local platform, or the root github release page for a version, to use the download logic. The latter of these should also override the Beam version to match the artifact, but will ultimately select the right platform to acquire.
Resolves #31403 …
=> [#31403] Python wrapper to download, use, or build and run prism.

.github/workflows/beam_Publish_Website.yml, .github/workflows/beam_Release_NightlySnapshot.yml, .github/workflows/deploy_release_candidate_pypi.yaml, .github/workflows/finalize_release.yml
Right now, there is some potential for cache poisoning from other workflows. We shouldn't read from the cache in workflows with access to sensitive credentials to avoid this risk …
=> Dont read from cache in sensitive workflows

sdks/java/io/bigquery-io-perf-tests/build.gradle, sdks/java/io/cdap/build.gradle, sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOIT.java, sdks/java/io/file-based-io-tests/build.gradle, sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/avro/AvroIOIT.java, sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/parquet/ParquetIOIT.java, sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java, sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/tfrecord/TFRecordIOIT.java, sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/xml/XmlIOIT.java, sdks/java/io/google-cloud-platform/build.gradle, sdks/java/io/hadoop-format/build.gradle, sdks/java/io/hadoop-format/src/test/java/org/apache/beam/sdk/io/hadoop/format/HadoopFormatIOIT.java, sdks/java/io/jdbc/build.gradle, sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOIT.java, sdks/java/io/jms/build.gradle, sdks/java/io/kafka/build.gradle, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java, sdks/java/io/mongodb/build.gradle, sdks/java/io/mongodb/src/test/java/org/apache/beam/sdk/io/mongodb/MongoDBIOIT.java, sdks/java/io/neo4j/build.gradle, sdks/java/io/singlestore/build.gradle, sdks/java/io/singlestore/src/test/java/org/apache/beam/sdk/io/singlestore/SingleStoreIOPerformanceIT.java, sdks/java/io/snowflake/build.gradle, sdks/java/io/solace/build.gradle, sdks/java/io/sparkreceiver/2/build.gradle, sdks/java/io/sparkreceiver/2/src/test/java/org/apache/beam/sdk/io/sparkreceiver/SparkReceiverIOIT.java, sdks/java/testing/nexmark/build.gradle, sdks/java/testing/tpcds/build.gradle
Context: https://github.com/apache/beam/pull/30193#discussion_r1476233448 …
=> Remove testRuntimeMigration configuration for test-utils dependencies

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/BasicAuthJcsmpSessionService.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/BasicAuthJcsmpSessionServiceFactory.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SolaceMessageReceiver.java
This is the 3rd PR for the Solace Read connector (addresses #31440).
It depends on the #31539 and #31476 (root).
The files that are added/modified in this PR, comparing to the #31539:
- BasicAuthJcsmpSessionService.java
- BasicAuthJcsmpSessionServiceFactory.java
- SolaceMessageReceiver.java
These are implementations of SessionService, SessionServiceFactory and MessageReceiver. SessionServiceFactory can be used as an argument to `SolaceIO.withSessionServiceFactory(...)`.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-t …
=> Solace Read connector: adding Basic Authentication support

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/WithKeys.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/WithKeysTest.java
=> Set SchemaCoder for key in WithKeys transform

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
`jackson-datatype-joda` already pulls joda-time 2.10.14. Sync version
=> Update joda-time to 2.10.14

.github/actions/setup-default-test-properties/test-properties.json, .github/gh-actions-self-hosted-runners/arc/images/Dockerfile, .github/workflows/go_tests.yml, .github/workflows/local_env_tests.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, dev-support/docker/Dockerfile, sdks/go/run_with_go_version.sh
Bumps Go version across Beam to 1.22.4 as per https://github.com/apache/beam/blob/master/contributor-docs/release-guide.md#update-go-version-used-for-container-builds …
=> Update Go Version to 1.22.4

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
`grpc-census`, `grpc-protobuf-lite` and `grpc-xds` are now part of the `google_cloud_platform_libraries_bom`
=> Use GCP libraries-bom version for all grpc

sdks/java/io/solace/build.gradle, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/data/Solace.java, sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/data/SolaceDataUtils.java
Beam Schemas don't support `ByteString` types. The pipeline was throwing the following exception in runtime:
```
SEVERE: Error occurred within org.apache.beam.runners.direct.DirectTransformExecutor@3df140ba
java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
org/apache/beam/sdk/io/solace/data/SchemaUserTypeCreator$SchemaCodeGen$uTIIUHuv.create([Ljava/lang/Object;)Ljava/lang/Object; @90: invokevirtual
Reason:
Type 'java/lang/Iterable' (current frame, stack[2]) is not assignable to 'org/apache/beam/vendor/grpc/v1p60p1/com/google/protobuf/ByteString'
Current Frame:
bci: @90
flags: { }
locals: { 'org/apache/beam/sdk/io/solace/data/SchemaUserTypeCreator$SchemaCodeGen$uTIIUHuv', '[Ljava/lang/Object;' }
stack: { …
```
=> Solace Read connector: Use ByteBuffer instead of BytesString in the Record class

sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go
This addresses #31756 to increase test coverage of Prism.
=> [#31756][Prism] Add a test for getting state with MultimapSideInput StateKey

website/www/site/content/en/documentation/transforms/python/elementwise/flatmap.md, website/www/site/content/en/documentation/transforms/python/elementwise/map.md
=> Fix playground snippets

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
The test waited for 1 commit but expected and validated the 2 commits.
It would pass if both commits happened to be present and fail otherwise. …
=> Fix flaky StreamingDataflowWorkerTest which wasn't waiting for enough commits

CHANGES.md, runners/core-java/src/main/java/org/apache/beam/runners/core/StateTags.java, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java, runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/AbstractWindmillMap.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/CachingStateTable.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillMap.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillMapViaMultimap.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillMultimap.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillSet.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateCache.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternals.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContextTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WindmillStateTestUtils.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSourcesTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateCacheTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternalsTest.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/DispatchedActiveWorkRefresherTest.java, sdks/java/core/src/main/java/org/apache/beam/sdk/state/StateSpecs.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java
Tests were not enabled for MapState/SetState for appliance on legacy runner. Enabling tests shows that MapState wasn't conforming to the spec that a read iterator is unaffected by subsequent writes, so this was fixed. Additional tests for the new map state built on MultimapState, exposed that MultimapState had a bug with remove/put/remove/put sequence which was fixed.
Related to issue #18200  …
=> Enable MapState and SetState for dataflow streaming engine pipelines with legacy runner by building on top of MultimapState.

sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/services/SnowflakeBatchServiceImpl.java
Set Snowflake escape char to backslash since it is the default used by CSVParser (fixes #24467).
One improvement would be to have this as configuration, but the change would be quite important.
It does not fix a related problem: it fails in some cases with `\n` in the data.
[![Python …
=> Set Snowflake escape char to backslash

.github/actions/setup-environment-action/action.yml, .github/workflows/go_tests.yml, .github/workflows/local_env_tests.yml
Follow up of #31747 . Tests setting up go with setup-environment-action still uses go 1.21
* Switch to use setup-environment-action instead of setup-go directly …
=> Use go 1.22 for self-hosted GHAs

sdks/go/pkg/beam/runners/prism/internal/handlerunner.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
This PR closes #31463 and closes #31462 adding handling for support of WindowStrategy related Pane and AllowedLateness features. It reduces the number of failed Java Prism Validation Runner tests from 52 to 31 (out of 253).
To validate this PR:
1. Run Prism server.
```
./gradlew :runners:prism:runServer
```
2.  Execute `:runners:portability:java:ulrLoopbackValidatesRunnerTests` on Prism:
Many tests fail were failing with these errors, but to see the output of one quickly:
```
TEST=org.apache.beam.sdk.transforms.ReshuffleTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
```
See the …
=> Add support for WindowStrategy Pane and AllowedLateness features

.github/gh-actions-self-hosted-runners/arc/images/Dockerfile, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, dev-support/docker/Dockerfile, sdks/go/run_with_go_version.sh
Follow-up to #31747 as Go 1.22.5 was released shortly afterward. This updates the Go version used in Beam infra, but does **not** increment the minimum Go version required by the Go SDK, which is a separate change. …
=> Update Go Version to 1.22.5

sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java
This should fix the incorrectly rendered javadoc for that method, see the problem [here](https://beam.apache.org/releases/javadoc/2.57.0/org/apache/beam/sdk/io/jms/JmsIO.Write.html#withTopicNameMapper-org.apache.beam.sdk.transforms.SerializableFunction-)
GitHub …
=> correctly close the javadoc tag in JmsIO.Write

.github/workflows/beam_PreCommit_Java_Solace_IO_Direct.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/io/solace/build.gradle, sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/SolaceContainerManager.java, sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/SolaceIOIT.java
The PR for the Solace Read connector (addresses #31440).
The files that are relevant in this PR (only the last commit):
- BeamModulePlugin.groovy
- build.gradle
- SolaceContainerManager.java
- SolaceIOIT.java
Other modified files in this pr are included in PRs that this one depends on.
This PR implements a basic integration test with testcontainers. It can be improved with the Write connector, once that is submitted and merged.
To check the …
=> Solace Read connector: integration tests with testcontainers

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibility.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibilityTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java, sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java, sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java, sdks/python/apache_beam/io/kafka.py, sdks/python/apache_beam/runners/portability/flink_runner_test.py
Add option to enable Kafka Read with redistribute afterwards to increase paralellism …
=> Add in redistribute option for Kafka Read

runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/BeamAdapterCoderUtils.java, runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/BeamAdapterUtils.java, runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/BeamFlinkDataSetAdapter.java, runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/BeamFlinkDataStreamAdapter.java, runners/flink/src/test/java/org/apache/beam/runners/flink/adapter/BeamFlinkDataSetAdapterTest.java, runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/wire/LengthPrefixUnknownCoders.java
The runner infrastructure typically substitutes "unknown" coders for length-prefixed bytes, but for elements going into or out of the Beam pipeline fragment we want the actual objects.  Fortunately, we know these coders are known on the Runner side as well as the SDK side as we have them in hand there. …
=> Avoid length-prefix-bytes substitutions for Flink boundaries.

scripts/ci/pr-bot/processPrUpdate.ts, scripts/ci/pr-bot/shared/commentStrings.ts, scripts/ci/pr-bot/shared/userCommand.ts
Fixes #31437
Enables the command `assign set of reviewers` to restart notifications if stopped, for example after manual reviewer assignment. 
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+ …
=> Allow pr-bot to re-assign reviewers when stopped

runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismExecutor.java, runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismPipelineOptions.java, runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismExecutorTest.java
This PR closes #31792 via a support class for executing the Prism binary.
cc: @lostluck  …
=> Support class executes the Prism binary

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageSourceBase.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java
- Adds a Helper class which wraps around StringSet metrics to define sources/sinks metrics for lineage.
- Add support in BQ IO Java SDK sources to emit the dataset they are accessing as lineage via stringset metrics.
addresses https://github.com/apache/beam/issues/31804
[![Python …
=> Introduce support for emitting lineage in BQ Source

sdks/python/apache_beam/io/gcp/bigtableio.py
**Issue**
In https://github.com/apache/beam/pull/27085/files, we replaced `_MutationsBatcher` with `MutationsBatcher` from `google.cloud.bigtable.batcher`.
However we didn't set `flush_count` and `max_row_bytes` of `MutationsBatcher` thus both constants `FLUSH_COUNT` and `MAX_ROW_BYTES` are currently not in used.
=> This PR fixed that issue
**Implication**
Although, in `google.cloud.bigtable` library, `MutationsBatcher` also set default value for `flush-count` but there is currently a discrepancy between default value in documentation `1000` and actual default value `100` [See more](https://github.com/googleapis/python-bigtable/blob/c573e9b695658f3e0c78eb3443d0cf26fea57da9/google/cloud/bigtable/batcher.py#L26)
For small/medium size use cases, there shouldn't be any problems. But I have 1 …
=> Add missing params to Python Bigtable MutationsBatcher

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContext.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
This can be reverted once Dataflow supports these.
The publishing logic is conditional so that the tests still run. …
=> Avoid publishing string set metrics on the Dataflow legacy runner.

runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismLocator.java, runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismPipelineOptions.java, runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismLocatorTest.java
This PR closes #31402 with a support class that locates, downloads, and prepares the Prism binary.
cc: @lostluck  …
=> Locate and download Prism binary

model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/metrics.proto, runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsContainerImpl.java, runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoConstants.java, runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/SimpleMonitoringInfoBuilder.java, runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MetricsContainerImplTest.java
This ensures they'll be available on Dataflow Runner v2. …
=> Export string sets in monitoring infos.

.github/workflows/build_wheels.yml
Test run: https://github.com/apache/beam/actions/runs/9910325847 upload artifacts succeeded (previously it was failing, e.g. https://github.com/apache/beam/actions/runs/9901420812)
Though test is still running …
=> Switch to use self-hosted runner for build_wheels action

CHANGES.md, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AppendClientInfo.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
=> Cherrypicking #31721 to release 2.58.0

.github/workflows/IO_Iceberg_Integration_Tests.yml, .github/workflows/IO_Iceberg_Performance_Tests.yml, .github/workflows/IO_Iceberg_Unit_Tests.yml, .github/workflows/beam_PerformanceTests_AvroIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_Cdap.yml, .github/workflows/beam_PerformanceTests_Compressed_TextIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_HadoopFormat.yml, .github/workflows/beam_PerformanceTests_JDBC.yml, .github/workflows/beam_PerformanceTests_Kafka_IO.yml, .github/workflows/beam_PerformanceTests_ManyFiles_TextIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_MongoDBIO_IT.yml, .github/workflows/beam_PerformanceTests_ParquetIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_SingleStoreIO.yml, .github/workflows/beam_PerformanceTests_SparkReceiver_IO.yml, .github/workflows/beam_PerformanceTests_TFRecordIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_XmlIOIT_HDFS.yml, .github/workflows/beam_PerformanceTests_xlang_KafkaIO_Python.yml, .github/workflows/beam_PostCommit_Java_InfluxDbIO_IT.yml, .github/workflows/beam_PostCommit_Java_SingleStoreIO_IT.yml, .github/workflows/beam_StressTests_Java_KafkaIO.yml, .github/workflows/build_runner_image.yml
Fix Performance tests part of #31848
These tests all uses io-datastores k8s instances, previously authenticate with GHA secret. However, either the secret becomes invalid or the auth action has problems, causing "invalid JWT Signature" issue
These tests are running on self-hosted runners in the same GCP project with io-datastores instance, and the credential is in place, no need to auth again.
Example run: 
* Jdbc Performance test: https://github.com/apache/beam/actions/runs/9914644914
* HDFS Performance test: https://github.com/apache/beam/actions/runs/9915736828
* SparkReceiver Performance test: https://github.com/apache/beam/actions/runs/9915739255
IO_Iceberg tests has the same issue: …
=> Remove auth@1 in tests running on self hosted runner

sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecord.java, sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecordTest.java
=> [CsvIO] Create CsvIOStringToCsvRecord Class

sdks/python/apache_beam/io/gcp/bigquery_read_internal.py, sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py
Caught by CleanupGCPResource workflow. There are many stale "bq_read_all_" datasets in the test project.
There is a consistent temp dataset leaking for Python SDK's ReadAllFromBigQuery. Each run will leave an empty dataset prefixed "bq_read_all_"
Cause:
* ReadFromBigQuery sets a default dataset of prefix "bq_read_all_"
https://github.com/apache/beam/blob/faff55c2882a0083a8cb8d1e2cf3ec9d365f677f/sdks/python/apache_beam/io/gcp/bigquery_read_internal.py#L215
* BigQueryWrapper thinks this is a user configured dataset and won't delete it 
https://github.com/apache/beam/blob/faff55c2882a0083a8cb8d1e2cf3ec9d365f677f/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L895
Solution:
Remove the prefix so BigQueryWrapper will use the default temp_dataset_* prefix and will delete it when …
=> Fix ReadAllFromBigQuery leak temp dataset

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessorTest.java
Configures SpannerAccessor to set the `setFailIfPoolExhausted`  `SessionPoolOption` which ensures that the Spanner client throws an error if the session pool is exhausted. …
=> Add SessionPoolOptions.setFailIfPoolExhausted in SpannerAccessor

sdks/python/build.gradle
There was a missing jinja2 import breaking the docs task for the 2.58.0 release, this fixes the job. Successful run validated locally. …
=> Fix generateYamlDocs gradle task

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Direct.json, sdks/java/core/src/main/java/org/apache/beam/sdk/testing/PAssert.java, sdks/java/core/src/test/java/org/apache/beam/sdk/testing/PAssertTest.java
=> Better assertion error messages for PAssert.thatSingleton

.github/trigger_files/IO_Iceberg_Integration_Tests.json, sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOIT.java
=> Use default auth for Iceberg integration tests

runners/prism/java/build.gradle, runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismExecutor.java, runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismPipelineResult.java, runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismPipelineResultTest.java
This PR closes #31793 with a package private PipelineResult implementation. The goal of tests are to validate shutting down the Prism executable during termination-related methods (cancel, waitUntilFinish) and the storing of terminal State and metrics. To focus tests on this behavior without executing Pipelines, it uses the mockito library.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STAT …
=> [Prism] Implement PrismPipelineResult

sdks/python/apache_beam/io/gcp/bigquery_read_internal.py
Follow up of #31895
Dataflow runner does not respect DoFn LifeCycle, in particular, it does not call teardown (#31381).
#31895 was tested on direct runner but not Dataflow runner. This change tested on both direct runner and Dataflow runner and confirms that dataset has been deleted.
It will only delete the dataset that is created in setup bundle. The same service account owns the same dataset and should not have problem to delete it. …
=> Move dataset cleanup to finishBundle for ReadAllFromBigQuery

sdks/python/apache_beam/ml/inference/huggingface_inference.py
Right now, if we detect a GPU is available but the user doesn't specify a device, we set the device to `cuda:1` - if there's just one accelerator, this will fail because ordering starts at 0. This fixes the issue. …
=> Use correct device ordinal when GPU is detected

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java
Internal tests found after #31805, BigQueryIO export read (with query) will make an additional BigQuery query job.
This is due to getTableToExtract call will try to create a temp dataset and initiate a query job. Arguably this Lineage metrics call is not necessary, right above in L156,
https://github.com/apache/beam/blob/eadb81fd01f281755f18a8a3095e3c2c8194e9fc/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java#L156
extractFiles already had same Lineage metrics call:
https://github.com/apache/beam/blob/eadb81fd01f281755f18a8a3095e3c2c8194e9fc/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java#L124 …
=> Dedup Lineage and getTableToExtract call in BigQuerySourceBase

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContext.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowSystemMetrics.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/StageInfo.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContextTest.java, sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Metrics.java, sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/MetricsEnvironment.java, sdks/java/core/src/main/java/org/apache/beam/sdk/util/StringUtils.java, sdks/java/core/src/test/java/org/apache/beam/sdk/util/StringUtilsTest.java, sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/RetryHttpRequestInitializer.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteOptions.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/RampupThrottlingFn.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetricsTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java, sdks/java/io/synthetic/src/main/java/org/apache/beam/sdk/io/synthetic/SyntheticStep.java
Fix #19632
Introduce a namepace named "beam-throttling-metrics", put under java core's Metrics.java, and use this namespace for Dataflow worker
Currently, Dataflow worker only considers several "known" namespace for throttling metrics, including bigquery streaming inserts, etc. After this change, "beam-throttling-metrics" is added to known namespace for batch Dataflow worker; and streaming dataflow worker will react on all counters named "throttliing-msecs"
* Introduce a generic throttling namespace and counter
* Dataflow accumulates throttling time from generic throttling counter
* Apply throttling counter to BigtableIO write …
=> Generic throttling metrics namespace and BigtableIO write throttling counter

sdks/python/container/piputil.go
Occasionally dependency installation might get stuck, however we won't see logs until they flush unless we use a logger that flushes periodically. …
=> Use buffered loggers that periodically flush.

sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpers.java, sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpersTest.java
This PR closes #31995 . It updates the class for representing and parsing date-times in CsvIOParseHelpers::parseCell(String, Schema.Field) from [java.time.Instant](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html) to [org.joda.time.Instant](https://www.joda.org/joda-time/apidocs/org/joda/time/Instant.html). …
=> [CsvIO]: update class for representing date-time in CsvIOParseHelpers::parseCell(String, Schema.Field)

runners/google-cloud-dataflow-java/build.gradle, runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowMetrics.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContext.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java, runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
Reverts apache/beam#31825
Dataflow backend (legacyrunner) now supports stringset
=> Revert "Avoid publishing string set metrics on the Dataflow legacy runner."

.github/workflows/build_wheels.yml
When run for RCs, the workflow builds the wheels from source as well as the RC tag, doubling the run time for the workflow and running into timeouts on self-hosted runners. This change mirrors the RC logic and should only execute the source wheel build when invoked against non-RCs …
=> Update Build Wheels to only build once on RCs

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/SolaceIO.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/data/Solace.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/write/SolaceOutput.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/write/package-info.java
This is a followup PR to #31906, and part of the issue #31905
This adds the interface of the Write connector and a few classes (data classes, POutput) that are used by the connector.
More changes are coming in a subsequent PR.
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=sc …
=> SolaceIO.Write: add data classes, connector interface

sdks/go/pkg/beam/runners/prism/internal/handlerunner.go
Correctly implement the WindowingStrategy OutputTime feature, which specify the event time of outputs from GroupByKeys. 
In particular, this allows the test `org.apache.beam.sdk.transforms.GroupByKeyTest\$BasicTests.testTimestampCombinerEarliest` and similar to pass.
Fixes #31462. …
=> [#31462] [prism] Correctly chose earliest or latest in pane timestamps for aggregations.

.github/workflows/build_wheels.yml
Reverts apache/beam#32009 because both builds are used in RC deployment at different places.
=> Revert "Update Build Wheels to only build once on RCs"

.github/workflows/build_wheels.yml
Reverts apache/beam#32010 because both builds are used in RC deployment at different places. Mirrors #32014 on the master branch.
=> Revert "[Cherrypick] Update Build Wheels to only build once on RCs (#32009)"

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Metrics.java, sdks/python/apache_beam/metrics/cells.pxd, sdks/python/apache_beam/metrics/cells.py, sdks/python/apache_beam/metrics/cells_test.py, sdks/python/apache_beam/metrics/execution.py, sdks/python/apache_beam/metrics/execution_test.py, sdks/python/apache_beam/metrics/metric.py, sdks/python/apache_beam/metrics/metricbase.py, sdks/python/apache_beam/metrics/monitoring_infos.py, sdks/python/apache_beam/metrics/monitoring_infos_test.py, sdks/python/apache_beam/runners/dataflow/dataflow_metrics.py, sdks/python/apache_beam/runners/direct/direct_metrics.py, sdks/python/apache_beam/runners/direct/direct_runner_test.py, sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py, sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py, sdks/python/apache_beam/runners/portability/portable_metrics.py, sdks/python/apache_beam/runners/portability/portable_runner.py
Direct runner and Flink runner (loopback) working. For Dataflow runner, needs to regenerate apiclient, will be done in a separate PR …
=> Add StringSet metrics to Python SDK

sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
Allows composites that only do SDK Side PCollection graph manipulation.
These composites have no payload, or subtransforms, so there's nothing for a runner to do with
them for execution. Simply ignore them.
This allows 3 Java validates runner tests in PipelineTest to pass: testIdentityTransform, testTupleProjectionTransform, and testTupleInjectionTransform.
Fixes #31991  …
=> [#31991][prism] Allow Empty Composites

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
In very rare cases a transform, such as a flatten can be in a pipeline without any real inputs.
Without inputs, nothing kicked off watermark processing, which then blocked use of the empty flatten output as a side input, which blocked that transform from executing.
This manifested as the upstream stage (the flatten), never getting watermark refreshed, and therefore the downstream stage never being able to execute, since the side input data from the upstream stage was never ready.
The solution in this PR is when a stage is added without inputs, it must be part of the initial watermark refresh set. Further taken to keep this part of the "impulse" set when a TestStream is involved in the Pipeline, since that manipulates initial refreshes.
Additionally adds a line to the stuck pipeline dump …
=> [#32003][prism] Support empty transform input sets, such as for flattens.

sdks/go/pkg/beam/core/runtime/exec/hash.go, sdks/go/pkg/beam/runners/prism/internal/stage.go
Prism wasn't length prefix wrapping unknown coders for bundle internal PCollections, or for the parallel input pcollection. This prevented Java and Python SplittableDoFns from correctly encoding their sub element split results, since they pull their coder from the input PCollection.
Go is arguably incorrectly pulling it's coder from the DataSource transform itself, but explains why prism developed this bug.
This change ensures all the internal PCollections are wrapped, and updated with the correct coder. Further prism now only sends precisely the PCollections needed or used in the bundle, instead of the entire set of pipeline PCollections.
Fixes #32004. …
=> [#32004] Ensure all pcollection coders are length prefixed if necessary.

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/AutoValueSchema.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/CachingFactory.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Factory.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FromRowUsingCreator.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/GetterBasedSchemaProvider.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/GetterBasedSchemaProviderV2.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/JavaBeanSchema.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/JavaFieldSchema.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SetterBasedCreatorFactory.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/annotations/DefaultSchema.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/providers/JavaRowUdf.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/AutoValueUtils.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/FieldValueTypeSupplier.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/JavaBeanUtils.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/POJOUtils.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ReflectUtils.java, sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/StaticSchemaInference.java, sdks/java/core/src/main/java/org/apache/beam/sdk/values/RowWithGetters.java, sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/JavaBeanUtilsTest.java, sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/POJOUtilsTest.java, sdks/java/extensions/arrow/src/main/java/org/apache/beam/sdk/extensions/arrow/ArrowConversion.java, sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/AvroRecordSchema.java, sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java, sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java, sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoMessageSchema.java, sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/schemas/AwsSchemaProvider.java, sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/schemas/AwsTypes.java, sdks/java/io/thrift/src/main/java/org/apache/beam/sdk/io/thrift/ThriftSchema.java
This is the first part of a series of PRs which when brought together are equivalent to the change previously proposed in #31648 - the code of this PR doesn't introduce or remove any features from the schema inference mechanisms existing already, it merely prepares the ground for doing that in the subsequent PRs. It does so by passing on down the call hierarchy the `TypeDescriptor`s where previously the code worked with bare `Class`es. This way the full information carried by `TypeDescriptor`s regarding the type signatures is not lost, and the schema inference, as well as, on the fly bytecode generation facilities will be able to use it to infer beam schemas for generic java types. 
Adding the support for schema inference of generic types was proposed in a section of this [design …
=> Replace Class with TypeDescriptor in SchemaProvider implementations

CHANGES.md, sdks/python/apache_beam/options/pipeline_options.py, website/www/site/content/en/blog/beam-2.49.0.md
fixes: #32030 - see the issue description for context.
Some IOs  capture pipeline options and inadvertently pass them to Dataflow runner:
https://github.com/apache/beam/blob/release-2.56.0/sdks/python/apache_beam/io/gcp/bigquery.py#L723
https://github.com/apache/beam/blob/release-2.56.0/sdks/python/apache_beam/io/gcp/bigquery.py#L1148
Given that more IOs might do this in the future, this PR adds a custom serialization logic to filter out the `impersonate_service_account` option whenever we serialize pipeline options, similarly to how we filter it out whenever we convert pipeline options into a proto: https://github.com/apache/beam/blob/e7847c9448c5fe4bff4566c77cf12711afc34b4e/sdks/python/apache_beam/runners/dataflow/internal/apiclient.py#L281 …
=> Remove `--impersonate_service_account` whenever PipelineOptions are serialized 

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImplTest.java
=> Fix row ranges issue in Bigtable Read.

sdks/go/pkg/beam/runners/prism/internal/handlepardo.go, sdks/go/pkg/beam/runners/prism/internal/preprocess.go, sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/worker/worker.go
The Java SDK at the very least examines the ParDoPayload and expects side inputs across all SDF component transforms if the original one does.
Prior to this PR, Prism wasn't properly doing graph analysis for these components, so side inputs were being missed. 
Initially the side input was only being provided to ProcessSizedElementsAndRestrictions, but this was causing the Java SDK to hang.
An attempt at rewriting the ParDoPayload and dropping the side inputs in the other transforms was made, but ultimately failed, since it looked like further stages in the execution relied on other information to detect a side input, or did actually need the side input. It wasn't worth the additional time to investigate further at this stage.
Minor comment, and debug logging adjustments for readability. …
=> [#31992][prism] Send side inputs for all SDF phases.

runners/direct-java/src/main/java/org/apache/beam/runners/direct/ExecutorServiceParallelExecutor.java, runners/flink/flink_runner.gradle, runners/spark/spark_runner.gradle, sdks/java/core/src/test/java/org/apache/beam/sdk/metrics/MetricResultsMatchers.java, sdks/java/core/src/test/java/org/apache/beam/sdk/metrics/MetricsTest.java
Address #32021 for direct runner
* Added a validate runner test for this scenario
Tested manually - BUILD SUCCESSFUL for the following commands
```
./gradlew :runners:direct-java:validatesRunner --tests *testBoundedSourceMetricsInSplit
```
confirmed the new test already passing on portable runners:
```
./gradlew :runners:flink:1.18:job-server:validatesPortableRunnerBatch --tests *testBoundedSourceMetricsInSplit
./gradlew :runners:spark:3:job-server:validatesPortableRunnerBatch --tests *testBoundedSourceMetricsInSplit
./gradlew :runners:google-cloud-dataflow-java:validatesRunnerV2Test -PgcpProject=... -PgcpRegion=us-central1 -PgcpTempRoot=gs://.../tmp --tests *testBoundedSourceMetricsInSplit -info
```
Dataflow legacy runner does …
=> Support metrics at Source.split for Direct Runner

runners/prism/java/build.gradle, runners/prism/java/src/main/java/org/apache/beam/runners/prism/StateListener.java, runners/prism/java/src/main/java/org/apache/beam/runners/prism/StateWatcher.java, runners/prism/java/src/test/java/org/apache/beam/runners/prism/StateWatcherTest.java
This PR closes #32032 with a package private StateWatcher. It sends a GetJobStateRequest to the state stream endpoint of the Job Management service and reports any changes in State to listeners, invoking onStateChanged. …
=> StateWatcher watches and reports changed Pipeline State

runners/prism/java/build.gradle, runners/prism/java/src/main/java/org/apache/beam/runners/prism/WorkerService.java, runners/prism/java/src/test/java/org/apache/beam/runners/prism/WorkerServiceTest.java
This PR closes #32054 with an encapsulated `GrpcFnServer<ExternalWorkerService>` that closes via its `StateListener::onStateChanged` callback when the `PipelineResult.State` is terminal. …
=> [Prism]: Enable ExternalWorkerService during Prism Runner lifecycle

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py, sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py
In Python SDK submitting to Dataflow job there is a logic overriding `apache/beam_python3.X_sdk:<label>` to `gcr.io/cloud-dataflow/v1beta3/beam_python3.X_sdk:<label>`:
https://github.com/apache/beam/blob/21009e68eabc9d8e05c5cfadaf5016fa23646fb7/sdks/python/apache_beam/runners/dataflow/internal/apiclient.py#L736
This generally works except the container has a release candidate tag. which were pushed to dockerhub, e.g. `apache/beam_python3.11_sdk:2.58.0rc2` the corresponding `gcr.io/cloud-dataflow/v1beta3/beam_python3.11_sdk:2.58.0rc2` does not exist, then Dataflow job fails indefinitely.
This does not happen for Python job alone, because the `__version__` of the package does not contain "rcX" suffix (even though the pypi version …
=> Handle rc container in _update_container_image_for_dataflow

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/timers.go
Add a sequence field to elements so that elements with the same timestamp, (and typically, in the same key and and from the same bundle), retain their order within a key.
This wouldn't be required if the sort in the heap package were stable, outside of the heap invariant.
The allows the Java validate runner PerKeyOrderingTests to pass.
Fixes #32064. …
=> [#32064][prism] Keep elements heap in sequence order.

.github/workflows/beam_LoadTests_Python_CoGBK_Flink_Batch.yml, .github/workflows/beam_LoadTests_Python_ParDo_Flink_Batch.yml, .github/workflows/beam_LoadTests_Python_ParDo_Flink_Streaming.yml
Fix https://github.com/apache/beam/actions/workflows/beam_LoadTests_Python_ParDo_Flink_Streaming.yml
This is a funny one. when github.run_id incremented from 9995517471 -> 10011544246, gcloud.dataproc.clusters.create fails with cluster name too long …
=> Fix load test dataproc cluster name exceeded allowed length

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java
Extended the SpannerSchema.Column class to be able to parse a Spanner TOKENLIST typed column. This is needed to support search indexes in Teleport.
R: @darshan-sj
=> Added support for the TOKENLIST type in Spanner

runners/prism/java/build.gradle, runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismArtifactStager.java, runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismArtifactStagerTest.java
This PR closes #32055 enabling artifact staging for the Prism runner. …
=> [Prism] Enable artifact staging during Prism Runner lifecycle

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java, sdks/java/io/google-cloud-platform/build.gradle, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableService.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableReadIT.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteIT.java
=> Add Lineage metrics for BigtableIO

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubUnboundedSink.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubUnboundedSource.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClientTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOTest.java
Covers
UnboundedReader
PubsubBoundedWriter
PubsubUnboundedWriter (PubsubSink / PubsubDynamicSink) …
=> Add Lineage metrics to PubsubIO

sdks/go/pkg/beam/runners/prism/internal/handlerunner.go, sdks/python/apache_beam/runners/portability/prism_runner_test.py
* Updates the basic session windowing to correctly aggregate across windows and remove old data.
* Fixes session windowing to respect the correct output timestamp.
* Overrides the fn_runner_test.py test_windowing method to a slightly more robust test, having an inner session, rather than just an first and last. This better validates boundary conditions.
* There seemed to be a weird interpretation issue WRT the int timestamp converting to microseconds properly. It appears to be done properly in the timestamp type, but I couldn't figure out where the discrepency lies. Prism was receiving the element timestamps as microseconds, but the session gap was correctly converted to microseconds from seconds. 
Fixes #32085  …
=> [#32085][prism] Fix session windowing.

sdks/python/apache_beam/dataframe/pandas_doctests_test.py, sdks/python/setup.py
=> Exclude a not yet implemented pandas op from dataframe tests.

.github/trigger_files/IO_Iceberg_Integration_Tests.json, sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java, sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergUtilsTest.java
Fixes #32050
Current iceberg utils does Schema conversion in a way where unique IDs are given to nested fields before top-level fields. When retrieving an Iceberg table's schema and inspecting it, we see that unique IDs are given to top-level fields first, then each nested type. This PR fixes our utils to align with it
=> Fix Beam Schema to Iceberg Schema ID conversion logic

sdks/python/apache_beam/io/gcp/bigquery_file_loads.py, sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py, sdks/python/apache_beam/io/gcp/bigquery_tools.py
Found a case where if we retry a successful load job (e.g. due to bundle failure), we get a 409 `ALREADY_EXISTS` error along with a job reference that **does not contain a location**. 
In finish bundle, we perform wait operations on job references, where we get and poll until the job is finished. If we attempt to get a job without a location, the API will default it to US multi region. However, this is problematic when we're writing to a different region because BQ won't be able to find the job and we encounter a 404 `NOT_FOUND` error.
In such a case where the job reference has null location, we should override it with the table's location
=> Override BQ load job location when necessary

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Fix #31634
Reverted https://github.com/apache/beam/pull/28756/files#diff-0435a83a413ec063bf7e682cadcd56776cd18fc878f197cc99a65fc231ef2047L1918-L1919
This was indeed introduced in #28756. Task.classifier was removed in Gradle8 to arChiveClassifier, however, ProjectDependency still has classifier field.
Tested with `./gradlew :sdks:java:io:clickhouse:publishToMavenLocal -Ppublishing` and inspected the generated pom has
```
<dependency>
<groupId>com.clickhouse</groupId>
<artifactId>clickhouse-jdbc</artifactId>
<version>0.3.2-patch10</version>
<scope>compile</scope>
<classifier>all</classifier>
``` …
=> Fix classifier dropped in artifact pom.xml

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/SolaceIO.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/UnboundedSolaceReader.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/UnboundedSolaceSource.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/WatermarkParameters.java, sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/WatermarkPolicy.java, sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/SolaceIOTest.java
=> Expose watermarkIdleDurationThreshold parameter to the user in SolaceIO read connector

sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
Add an explicit failure for SDFs that also use State or Timers. See #32139 for an explanation of why they aren't currently supported.
This is to register this as a Known Issue of prism, and to defer implementation until we see if users require this combination, as well as suggest a path forward via the issue. …
=> [#32139] Fail pipelines with Stateful SDFs.

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/timers.go, sdks/python/apache_beam/runners/portability/prism_runner_test.py
* Prism wasn't decoding *all* timers returned in the logical timer stream, dropping later set timers.
* Moved timer decoding to be iterator compatible for the future, instead of trying to reprocess inplace, or returning the remaining byte buffer.
* From there supporting clearing timers was simple, by additionally returning the window set, and deleting existing entries to the pending timer list. 
* Needed to re-write + override the timer clearing test, since for some reason the test DoFn would not execute when there were multiple timer parameters to the DoFn.
Allows a few of the Python timer based tests to pass.
TODO for a different test: Support interval and custom window functions for timers.
Fixes #32115 …
=> [#32115] Fix timer support, support timer clears.

sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParse.java, sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseConfiguration.java, sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseTest.java
This PR closes #31875. 
It impements a method for adding and validating custom field mapped lambdas. …
=> [CsvIO]: Implement CsvIOParse::withCustomRecordParsing method

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
Shamelessly stolen from https://github.com/apache/beam/pull/7097. This change is in response to b/357784942.
Regarding testing, the HTTPWriteTimeout also has no tests, and adding those would require, from what I can tell, hundreds of lines of refactoring, making this no longer a trivial 4-line (not including comments and whitespace) change.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STAT …
=> Add support for setting an HTTP read timeout for BigQueryIO

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark.json, .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming.json, .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark_Java11.json, runners/core-java/src/main/java/org/apache/beam/runners/core/StateTag.java, runners/spark/src/main/java/org/apache/beam/runners/spark/stateful/SparkStateInternals.java
fixes #31797 
This PR contains theses changes
- replace `StateTag.StateBinder` to top level `StateBinder` in `SparkStateInternals`
- modify `StateTag.StateBinder` doc for link top level `StateBinder` (org.apache.beam.sdk.state.StateBinder)
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob …
=> Replace StateTag.StateBinder to top level StateBinder in SparkStateInternals

CHANGES.md, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/SplittingIterable.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiConvertMessages.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinations.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsBeamRow.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsGenericRecord.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsProto.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiDynamicDestinationsTableRow.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritePayload.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java
=> Support withFormatRecordOnFailureFunction() for BigQuery STORAGE_WRITE_API and STORAGE_API_AT_LEAST_ONCE methods

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/SerializableComparator.java, sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/SerializableComparatorTest.java
Fixes https://github.com/apache/beam/issues/30257
Adds a static `comparing` method to the `SerializableComparator` interface. This almost similar to the inbuilt Java's `Comparator#comparing(Function)` method except that it uses `SerializableFunction`.
=> Fixes GitHub issue #30257

sdks/python/apache_beam/io/gcp/bigquery.py, sdks/python/apache_beam/io/gcp/bigquery_file_loads.py, sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py, sdks/python/apache_beam/io/gcp/bigquery_read_internal.py, sdks/python/apache_beam/io/gcp/bigquery_schema_tools_test.py, sdks/python/apache_beam/io/gcp/bigquery_test.py, sdks/python/apache_beam/metrics/metric.py, sdks/python/apache_beam/metrics/metric_test.py
* Introduce metric.Lineage StringSet wrapper Reflect Java SDK #32090
* Direct Read
* Export Read
* ReadAllFromBigQuery
* FILE_LOAD Write …
=> Add Lineage metrics to Python BigQueryIO

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java, sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FnApiDoFnRunnerTest.java
This ensures that an SDF makes progress if the runner repeatedly attempts to split the restriction before work has been claimed.
This affects the Dataflow Runner which attempts to split in streaming pipelines after 5 seconds by default. If the SDF takes over 5 seconds to read the first element and attempt to claim it, the split will occur first, checkpointing the same restriction and the element will be dropped. On retry, it will resume from the same restriction and this may repeat.
This matches the behavior of the core java sdf invoker [here](https://github.com/apache/beam/blob/2f93d8bc19917f83d15f531bcbbfb7f36e21ff88/runners/core-java/src/main/java/org/apache/beam/runners/core/OutputAndTimeBoundedSplittableProcessElementInvoker.java#L309) which didn't start the split thread until the …
=> Change FnApiDoFnRunner to skip trySplit checkpoint requests if not draining and nothing has yet been claimed by the tracker.

sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSink.java, sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSource.java, sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystem.java, sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystems.java, sdks/java/core/src/main/java/org/apache/beam/sdk/io/ReadAllViaFileBasedSourceTransform.java, sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java, sdks/java/core/src/test/java/org/apache/beam/sdk/metrics/LineageTest.java, sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystem.java, sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/s3/S3FileSystem.java, sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystem.java, sdks/java/io/azure/src/main/java/org/apache/beam/sdk/io/azure/blobstore/AzureBlobStoreFileSystem.java, sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageSourceBase.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/CreateTables.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteRename.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteTables.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubUnboundedSink.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubUnboundedSource.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableReadIT.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteIT.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClientTest.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOTest.java
This PR depends on #32068
- read covered by FileBasedSource.split
- readAll covered by ReadAllViaFileBasedSourceTransform . It is based on FileBasedSink, but it does not split, instead creating a reader and read directly inside a DoFn
- write covered by FileBasedSink …
=>  Add Lineage metrics to FileSystems

.github/trigger_files/beam_PostCommit_Python.json, sdks/python/apache_beam/examples/inference/sklearn_examples_requirements.txt
=> Fix PostCommit Python sklearn on Python3.12

sdks/python/apache_beam/runners/portability/prism_runner_test.py
Related to #28187.
Skip the copied kafka, SQL, and external transform tests that require an expansion Service stood up.
We should eventually have a post commit for these, but in the short term, filter them out to enable a pre-commit suite to execute.
GitHub …
=> [prism] Skip python tests that require an expansion service at this time.

runners/google-cloud-dataflow-java/build.gradle, runners/google-cloud-dataflow-java/examples/build.gradle, sdks/java/container/common.gradle, sdks/java/testing/test-utils/build.gradle
Two issues
1. It is found that after #28918, the java version verification test only checks that the source code was compile with Java8, but not test code compiled/running on certain Java version
2. We had overly strict sdks:java:docker:javaX:validateJavaHome . If system java version is Java11, xlangPythonUsingJava will add a java 11 docker task, which currently requires `-Pjava11Home`, which is not necessary.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-t …
=> Fix verifyJavaVersion in a few places

CHANGES.md, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java, website/www/site/content/en/blog/beam-2.58.0.md
=> Fix configuration of ReadFromKafkaViaSDF which was always enabling redistribute and allowing duplicates instead of basing it on configuration.

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
Publishing snapshots times out occasionally (and often enough to get https://github.com/apache/beam/issues/32161 even though I think that is an overly eager signal). This should fix it.
Example timeout job - https://github.com/apache/beam/actions/runs/10391031406 - you can see that the other python jobs are a little close to the timeout as well
Fixes #32161 …
=> Increase snapshot publish timeout

sdks/go/pkg/beam/runners/prism/internal/coders.go, sdks/go/pkg/beam/runners/prism/internal/coders_test.go, sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/timers.go, sdks/go/pkg/beam/runners/prism/internal/execute.go, sdks/go/pkg/beam/runners/prism/internal/handlerunner.go, sdks/go/pkg/beam/runners/prism/internal/stage.go
Support interval windows when used with timers. Largely plumbs the awareness of the input collection's window coder type, with a stop gap for custom windowFns.
In the future, we may wish to fully move to the "error free" decoder style for dealing with windows and elements, and avoid io.Reader/io.Writer indirection. This would be preferable to putting Custom window fun machinery into the SDK, without the SDK being a user itself, and would avoid unnecessary error handling.
Fixes #32121. …
=> [#32121] Support timers in interval windows.

runners/google-cloud-dataflow-java/build.gradle
=> Update dataflow container versions

sdks/python/apache_beam/transforms/core.py, sdks/python/apache_beam/transforms/core_test.py
Allows users to define a callback to execute only on failure. Step 1 of https://github.com/apache/beam/issues/32137 though this is also a standalone feature
See full design here - https://docs.google.com/document/d/19ves6iv-m_6DFmePJZqYpLm-bCooPu6wQ-Ti6kAl2Jo/edit …
=> Add callback to with_exception_handling

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/stage.go
In going over the threading model for Prism, two goroutines stood out as not handling recoverable panics.
The handling in each is to ultimately fail the job in question, with the goal of keeping the prism server instance up, and cleaning up the job's resources. 
Related #29650, and #28187
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.te …
=> [prism] Catch panics in primary execution goroutines.

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/ExternalWorkerService.java
This fixes metrics from the Java SDK when running in Loopback mode against Prism (and probably a few other usecases too).
* The Provision API is usually called by the container bootloader to initialize the worker.
* Without calling the ProvisionAPI, the worker doesn't know a runner's capabilities.
* This lead to the Java SDK to send old style metrics in loopback mode, which prism doesn't support.
* That meant there were no metrics being propagated at in the UI.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-review …
=> [#31926] [java] call provision service when creating external workers.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/go/examples/kafka/taxi.go, sdks/go/examples/xlang/bigquery/wordcount.go, sdks/go/test/build.gradle
The default Xlang transforms got moved to Java 11, but we were only building the Java8 ones, so 11 wasn't available.
Move to use Java 11 to unbreak the existing tests. …
=> [Java11 Migration] Migrate Go testing to use Java11 container image for xlang

.github/workflows/beam_PostCommit_Go_VR_Samza.yml, .github/workflows/beam_PostCommit_Java_PVR_Samza.yml, .github/workflows/beam_PostCommit_Java_ValidatesRunner_Samza.yml, .github/workflows/beam_PostCommit_Python_ValidatesRunner_Samza.yml, .github/workflows/beam_PostCommit_XVR_Samza.yml, .github/workflows/beam_PreCommit_Java_HCatalog_IO_Direct.yml, .github/workflows/beam_PreCommit_Java_IOs_Direct.yml, .github/workflows/beam_PreCommit_Java_Spark3_Versions.yml, buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
* Fix Java IOs/HCatalogIO PreCommit typo
* Run Spark3 Version PreCommit on Java8 - opened #32208 to track Samza runner Java11 support
* Run Samza tests on Java8 - opened #32207 to track Spark 3.4.0+ runner Java11 support …
=> More Java11 test fix

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SempBasicAuthClientExecutor.java, sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/broker/SempBasicAuthClientExecutorTest.java
Addresses #32108 
Making sure any url parameters are encoded when calling Solace REST API …
=> SolaceIO.read: Encode url parameters in REST requests.

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go, sdks/go/pkg/beam/runners/prism/internal/engine/teststream.go
In documenting the broad strokes of the watermark evaluation Goroutine, it became clear that the field "watermarkRefreshes" while accurate, was unclear. Renamed to be what they contain, stages that have changed, rather than what it's for, which is knowing which stages need a watermark refresh.
Watermark refresh now refers cleanly to the action, rather than the pending action as a result of other work. This should make it a bit easier to follow in the code.
"We evaluate changed stages for watermark advancement with the `refreshWatermarks()` method." compared to
"We process watermark refreshes in the `refreshWatermarks()` method." …
=> [prism] rename watermarkRefreshs concept to changedStages.

sdks/python/apache_beam/utils/multi_process_shared.py, sdks/python/apache_beam/utils/multi_process_shared_test.py
Adds an unsafe delete option to be used for garbage collection of multi_process_shared objects. This allows cleanup of multiprocess objects even if some references have been entirely lost (e.g. due to running in a subprocess mode) or if its unclear when they'll be invoked again (because Beam may not schedule work to that DoFn for a bit).
This is intentionally unsafe and should only be used when other synchronization mechanisms are in place to prevent usage of the already deleted object. For example, this will be used as part of our runinference timeout feature - for more details see  https://docs.google.com/document/d/19ves6iv-m_6DFmePJZqYpLm-bCooPu6wQ-Ti6kAl2Jo/edit#heading=h.cfdh3ijyabi3 …
=> Add hard delete function to multi_process_shared

sdks/python/apache_beam/yaml/readme_test.py, sdks/python/apache_beam/yaml/yaml_join.py, website/www/site/content/en/documentation/sdks/yaml-join.md
As we're using the fake SQL and not checking the outputs, this is not substitute for real testing, but at the very least it ensures the joins are syntactically correct. …
=> Add basic testing for yaml join docs.

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy, sdks/java/build-tools/src/main/resources/beam/checkstyle/suppressions.xml, sdks/java/io/google-ads/build.gradle, sdks/java/io/google-ads/src/main/java/org/apache/beam/sdk/io/googleads/GoogleAdsIO.java, sdks/java/io/google-ads/src/main/java/org/apache/beam/sdk/io/googleads/GoogleAdsV17.java, sdks/java/io/google-ads/src/test/java/org/apache/beam/sdk/io/googleads/DummyRateLimitPolicy.java, sdks/java/io/google-ads/src/test/java/org/apache/beam/sdk/io/googleads/GoogleAdsV17Test.java, sdks/java/io/google-ads/src/test/java/org/apache/beam/sdk/io/googleads/MockGoogleAdsClientFactory.java
Fix #32241
however, the way GoogleAdsIO bookkeeping Google-ads API version requires recurring breaking change, including this PR, which should be revisited later …
=> Bump google-ads API to v17

CHANGES.md, sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIO.java
Add to ClickHouseIO dedicated user agent #32252  …
=> Add to ClickHouseIO dedicated useragnet

runners/portability/java/src/main/java/org/apache/beam/runners/portability/JobServicePipelineResult.java, runners/portability/java/src/main/java/org/apache/beam/runners/portability/PortableRunner.java, runners/portability/java/src/test/java/org/apache/beam/runners/portability/PortableRunnerTest.java
This is a draft PR that cleans up existing errors in the Portable runner. …
=> Portable runner fixes

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaExactlyOnceSink.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedSource.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriter.java, sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibilityTest.java, sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java
=> Add Lineage metrics to KafkaIO

CHANGES.md, sdks/go/pkg/beam/core/runtime/harness/statemgr.go
Copy bytes sent over the State API Writer. Eagerly nil the buffer if it's at zero length.
* stateKeyWriter wasn't implementing the io.Writer interface correctly, as it was retaining a reference to the passed in byte slice.
* This, combined with the escape analysis subversion function (ioutilx.WriteUnsafe), and a change in Go 1.23 made a data corruption more likely, as the underlying memory for the byte slice was used for other things. 
* This largely only happened sometimes because state is written to asynchronously over 3 goroutines (user, writer, reader, with user blocking until the reader confirms the write response).
A better fix would be to avoid the WriteUnsafe hack altogether, but that leads to an egregious number of small allocations, hurting performance, and would be much wider …
=> [#32245][Go SDK] Copy bytes sent over the State API Writer.

sdks/go/pkg/beam/runners/prism/internal/stage.go, sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go, sdks/python/apache_beam/runners/portability/prism_runner_test.py
Timers were failing due to prism not actually sending the correct "is_last" messages to the SDK side.
This was caught by the Java SDK looking up each stream explicitly and failing at the "empty" timer family prism was sending.
Python had the subtle issue of hanging during the timer clear test. This test now passes, so the override has been removed.
Fixes #32221 …
=> [#32221] [prism] Terminate streams for each timerfamily+transform pair.

.github/trigger_files/IO_Iceberg_Integration_Tests.json, sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java
For example, write to `data/my-file-name.parquet` instead of `data/my-file-name`
=> Attach file extension to Iceberg writes

CHANGES.md, sdks/java/io/google-cloud-platform/build.gradle, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java, sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImplTest.java
This fixes https://github.com/apache/beam/issues/28149 …
=> Allow setting BigQuery endpoint

runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/SplittableDoFnOperator.java, runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/SplittableProcessFnFactory.java, runners/samza/src/main/java/org/apache/beam/runners/samza/runtime/SplittableParDoProcessKeyedElementsOp.java
=> Do not create new Executor everytime createRunner

sdks/go/cmd/prism/prism.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go, sdks/go/pkg/beam/runners/prism/internal/jobservices/server.go, sdks/go/pkg/beam/runners/prism/internal/web/web.go, sdks/go/pkg/beam/runners/prism/prism.go
Cherry pick of #32276 to the release branch. …
=> Cherrypick #32276 to 2.59.0 release branch.

sdks/python/apache_beam/ml/inference/base.py
This makes way more sense since it will save a bunch of cross process calls on large bundles
Closes #32137
[![Build …
=> Move RunInference GC to finalize_bundle

CHANGES.md
New release cut, need to add section for next release. …
=> [CHANGES.md] Add 2.60.0 section.

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpersTest.java
This addresses https://github.com/apache/beam/issues/32168, please see rationale there
=> Loose BigQuery GCP project ID regex restrictions

.github/workflows/build_wheels.yml
This will greatly speed up our time to release (now docker artifacts will be the bottleneck, though we could do something similar for them if needed
- [Example](https://github.com/apache/beam/actions/runs/10521866265) of this running on a non-rc -  **takes ~1 hour**
- [Example](https://github.com/apache/beam/actions/runs/10521905504) of this running on a (fake) RC - RC faked with https://github.com/apache/beam/commit/a56dd56c640f96e618a577b7b66fecad41a22a13 - **takes <2.5 hours**.
- [Example](https://github.com/apache/beam/actions/runs/10518838682) of running without this change on a non-RC - **takes 5 hours** (admittedly on the high end of what is normal in my experience)
- [Example](https://github.com/apache/beam/actions/runs/10408455748) of running without this change on an RC - …
=> Parallelize building wheels per language version

sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java, sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOReadTest.java
=> Fix TextIO.read() split with non-default delimiter

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java, sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpersTest.java
Cherry pick of this PR: https://github.com/apache/beam/pull/32178
cc @lostluck
=> Cherry Pick #32178: Loose BigQuery GCP project ID regex restrictions
