apache/beam

- sdks/python/apache_beam/yaml/README.md
- sdks/python/setup.py
This will make it easy for new users to get started. …
> Add apache_beam[yaml] options.

- it/cassandra/src/main/java/org/apache/beam/it/cassandra/CassandraResourceManagerUtils.java
- it/cassandra/src/main/java/org/apache/beam/it/cassandra/matchers/CassandraAsserts.java
- it/cassandra/src/test/java/org/apache/beam/it/cassandra/CassandraResourceManagerTest.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/LoadTestBase.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/utils/JsonTestUtil.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DirectRunnerClient.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datagenerator/DataGenerator.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastore/matchers/DatastoreAsserts.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dlp/DlpResourceManager.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/kms/KMSResourceManager.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/monitoring/MonitoringClient.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/matchers/SpannerAsserts.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOLT.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerIOLT.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/storage/FileBasedIOLT.java
- it/jdbc/src/main/java/org/apache/beam/it/jdbc/AbstractJDBCResourceManager.java
- it/jdbc/src/main/java/org/apache/beam/it/jdbc/JDBCResourceManager.java
- it/jdbc/src/main/java/org/apache/beam/it/jdbc/MSSQLResourceManager.java
- it/jdbc/src/main/java/org/apache/beam/it/jdbc/MySQLResourceManager.java
- it/jdbc/src/main/java/org/apache/beam/it/jdbc/OracleResourceManager.java
- it/jdbc/src/main/java/org/apache/beam/it/jdbc/PostgresResourceManager.java
- it/kafka/src/main/java/org/apache/beam/it/kafka/KafkaResourceManager.java
- it/mongodb/src/main/java/org/apache/beam/it/mongodb/MongoDBResourceManager.java
- it/mongodb/src/main/java/org/apache/beam/it/mongodb/matchers/MongoDBAsserts.java
- it/neo4j/src/main/java/org/apache/beam/it/neo4j/Neo4jResourceManager.java
- it/neo4j/src/main/java/org/apache/beam/it/neo4j/conditions/Neo4jQueryCheck.java
- it/splunk/src/main/java/org/apache/beam/it/splunk/SplunkResourceManager.java
- it/testcontainers/src/main/java/org/apache/beam/it/testcontainers/TestContainerResourceManager.java
- it/truthmatchers/src/main/java/org/apache/beam/it/truthmatchers/RecordsSubject.java
> Update `it` module.

- sdks/java/extensions/schemaio-expansion-service/build.gradle
This unbreaks precommits.
(Separately, looking at this more, we should probably be declaring the versions elsewhere rather than hard coding them here. An expert on gradle would know the best way to do that.) …
> Declare undeclared libraries to work around BEAM-11761.

- .github/REVIEWERS.yml
add self to java reviewers to be able to merge and review streaming worker code. …
> add self to java reviewers to be able to merge and review streaming worker

- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java
> Avoid potential null pointer exceptions in logging.

- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ExecutionStateSampler.java
Once the threshold has been reached, don't report on every sample, but instead in a capped exponentially decaying manner. …
> Less frequent reporting of potentially stuck records.

- sdks/python/apache_beam/yaml/yaml_provider.py
This PR removes the redundant experimental WithSchema transform. …
> [YAML] Remove redundant WithSchema transform

- CHANGES.md
> [YAML] add yaml release notes

- sdks/python/apache_beam/transforms/core.py
- sdks/python/apache_beam/yaml/yaml_mapping.py
- sdks/python/apache_beam/yaml/yaml_udf_test.py
Add JSObject python conversion to YAML Javascript UDF Mapping transforms. …
> [YAML] fix javascript UDF output in mapping transforms

- sdks/python/apache_beam/io/gcp/bigtableio_it_test.py
Introduced in #29203 
The file already had `from datetime import datetime` …
> Fix bigtable_it_test instance naming

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateReader.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WrappedFuture.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateReaderTest.java
Fix issue with MultimapState delayed fetches due to batching.
fixes #28370 …
> Change WindmillStateReader to not batch OrderedListFetches for the same family and tag. 

- sdks/python/container/py310/base_image_requirements.txt
- sdks/python/container/py311/base_image_requirements.txt
- sdks/python/container/py38/base_image_requirements.txt
- sdks/python/container/py39/base_image_requirements.txt
- sdks/python/setup.py
master PR: https://github.com/apache/beam/pull/29255
Supercedes https://github.com/apache/beam/pull/29260
[![Build …
> [release-2.52.0] CP a protobuf upgrade.

- sdks/python/apache_beam/yaml/pipeline.schema.yaml
- sdks/python/apache_beam/yaml/yaml_provider.py
This PR adds caching to the `RenamingProvider` and fixes schema validation for composite pipelines. …
> [YAML] fix renaming provider caching and YAML schema validation

- sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java
> Don't invalidate streams on quota errors

- .test-infra/metrics/grafana/dashboards/GA-Post-Commits_status_dashboard.json
- .test-infra/metrics/sync/github/sync_workflows.py
This attempts to do 2 things http://metrics.beam.apache.org/d/CTYdoxP4z/ga-post-commits-status?orgId=1
1) Organize it into more helpful categories
2) Make it config driven so it is easier for anyone to move things around/rearrange
It is a non-goal for this to be the perfect final representation of what we want the dashboard to look like, it is supposed to move things in the right direction though …
> Organize dashboard and make it more config driven

- sdks/python/apache_beam/yaml/yaml_errors.md
> [YAML] Note about error output schemas.

- sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/providers/ErrorHandling.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProvider.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaDlqTest.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProviderTest.java
- sdks/python/apache_beam/yaml/standard_io.yaml
- sdks/python/apache_beam/yaml/yaml_transform.py
Add proper error handling to KafkaReadSchemaTransform and KafkaWriteSchemaTransform  …
> [YAML] Fix error handling for KafkaSchemaTransforms

- sdks/python/apache_beam/yaml/cache_provider_artifacts.py
Pyenv caching fails on non-dev versions of beam when running Beam YAML `cache_provider_artifacts`. …
> [YAML] Fix PyPi caching for non-dev beam

- sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/providers/ErrorHandling.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProvider.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaDlqTest.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProviderTest.java
- sdks/python/apache_beam/yaml/standard_io.yaml
- sdks/python/apache_beam/yaml/yaml_transform.py
Cherry pick #29261 for 2.52.0 release. …
> [YAML] Fix error handling for KafkaSchemaTransforms (#29261)

- sdks/python/apache_beam/yaml/pipeline.schema.yaml
- sdks/python/apache_beam/yaml/yaml_provider.py
Cherry pick https://github.com/apache/beam/pull/29271 for 2.52.0 release. …
> [YAML] fix renaming provider caching and YAML schema validation  (#29271)

- sdks/python/apache_beam/yaml/cache_provider_artifacts.py
Cherry pick https://github.com/apache/beam/pull/29273 for 2.52.0 release. …
> [YAML] Fix PyPi caching for non-dev beam (#29273)

- sdks/python/apache_beam/io/fileio.py
Fixes: https://github.com/apache/beam/issues/29195 …
> Pass empty_match_treatment flag in MatchFiles

- .test-infra/tools/build.gradle
- .test-infra/tools/stale_cbt_instances_cleaner.sh
- sdks/python/apache_beam/io/gcp/bigtableio_it_test.py
It constantly get leaked instance since bigtable integration test have setup. However, the bigtable cli (cbt) does not support fetch the creation date of instances, so we have to encode this into the instance name for the tests, and delete instances of >5d age. …
> Setup Bigtable instance cleaner

- sdks/java/bom/build.gradle
Right now, generating an RC is failing because there is an implicit dependency here - https://github.com/apache/beam/actions/runs/6747166089/job/18342723439 (publish_java_artifacts failure). This should hopefully fix that …
> Declare signMavenJavaPublication dependency on copyPom

- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
Previously this was a NullPointerException. …
> Better error on late use of DoFnContext.

- sdks/java/bom/build.gradle
Cherry pick of #29296
Right now, generating an RC is failing because there is an implicit dependency here - https://github.com/apache/beam/actions/runs/6747166089/job/18342723439 (publish_java_artifacts failure). This should hopefully fix that
GitHub Actions …
> [CP] Declare signMavenJavaPublication dependency on copyPom

- .github/workflows/build_wheels.yml
This is blocking the release and causing workflows to fail - https://github.com/apache/beam/actions/runs/6747149106/job/18342697260 …
> fix typo in workflow

- .github/workflows/build_wheels.yml
Fix typo needed for release workflow …
> [cp] fix typo in workflow (#29300)

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/SplitQueryFnIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1ReadIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1TestUtil.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1WriteIT.java
This reverts commit 181296dec2a6d6973e7aaa17f2cb0286c9308457 which did not deal with the default id correctly
[![Build …
> Revert "Support DatabaseID in Datastore beam connector (#27987)"

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/SplitQueryFnIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1ReadIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1TestUtil.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1WriteIT.java
This reverts commit 181296dec2a6d6973e7aaa17f2cb0286c9308457.
Cherry pick of #29317 …
> [CP] Revert "Support DatabaseID in Datastore beam connector (#27987)"

- .github/workflows/deploy_release_candidate_pypi.yaml
Untested since its pretty hard to test manual workflows on branches, after merge I'll try it and make any fixes as needed. …
> Add action to publish RC to PyPi

- sdks/go/pkg/beam/core/runtime/exec/sdf.go
- sdks/go/pkg/beam/core/runtime/exec/sdf_test.go
Fixes #29210 and sets the progress fraction to 0 if the amount of done work is 0 to avoid returning NaN.
[![Build …
> [#29210][Go SDK]: Fix SDF progress fraction to not return NaN

- .github/workflows/beam_PostCommit_Python_ValidatesContainer_Dataflow.yml
The rest of the job was actually set up assuming comment triggers, the trigger itself was just missing …
> Add missing comment trigger

- CHANGES.md
New changes should be targeted at 2.53 …
> Add new CHANGES.md section

- .github/workflows/beam_CloudML_Benchmarks_Dataflow.yml
- .github/workflows/beam_Inference_Python_Benchmarks_Dataflow.yml
- .github/workflows/beam_PerformanceTests_SingleStoreIO.yml
- .github/workflows/beam_PostCommit_BeamMetrics_Publish.yml
- .github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml
- .github/workflows/beam_PostCommit_Java_Examples_Dataflow.yml
- .github/workflows/beam_PostCommit_Java_Examples_Dataflow_ARM.yml
- .github/workflows/beam_PostCommit_Java_IO_Performance_Tests.yml
- .github/workflows/beam_PreCommit_Java_Examples_Dataflow_Java21.yml
- .github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml
Part of the effort of reducing the concurrent Dataflow jobs in precommit stage to reasonable level
Found that several postcommit jobs have "Push" trigger, while most does not. This PR then removes all push trigger except for precommit workflows. It also removes issue_comment trigger for remaining loadtest/performance test. Also in current practice we barely monitor push triggers.
To …
> Remove push trigger for non-precommit workflows

- sdks/python/apache_beam/io/azure/integration_test/docker-compose.yml
Just change network name in docker-compose to be consistent with the intetion …
> revert network name

- sdks/python/apache_beam/io/gcp/bigquery_tools.py
Just fixing a tiny typo in the docstring on the get_table_schema_from_string method …
> Fix small typo on get_table_schema_from_string

- .github/gh-actions-self-hosted-runners/arc/config/arc_deployment.tpl
Sets the dockerMTU for all containers started using docker create/run
Second f.i.x to the #29214  …
> set dockerMTU to 1460 to align with GKE

- sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/data/BeamFnDataGrpcMultiplexer.java
This warning emitted every time a python-use-java xlang pipeline execution ends. Checking the code it is a hook that extended from Grpc's StreamObserver [1]
The onCompleted() callback documents as "Receives a notification of successful stream completion."
https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html#onCompleted()
The warning is redherring. This PR changes it to appropriate level.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the …
> Change BeamFnDataGrpcMultiplexer.onCompleted logging to INFO

- .github/workflows/beam_CleanUpGCPResources.yml
- .test-infra/tools/stale_cbt_instances_cleaner.sh
Followup #29279
* Fix clean up stale cbt instance failing due to no cli in PATH
* Bump run frequency from daily to twice a day …
> Install cbt cli for cleanup gcp resource

- .github/workflows/beam_PostCommit_Java_SingleStoreIO_IT.yml
Tasks were missing and that was causing the one there to fail.  …
> add missing gradle tasks to postcommit java singlestoreio test

- model/job-management/src/main/proto/org/apache/beam/model/job_management/v1/beam_expansion_api.proto
- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/TransformUpgrader.java
- sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java
- sdks/python/apache_beam/runners/portability/expansion_service.py
This should be used to interpret the components provided with the request.
For example, this may be used to provide the `StandardRequirements` related to `ParDo`s which otherwise cannot be derived from the components provided.
https://github.com/apache/beam/blob/f3636f32b3f5a97bdd5c8421bf3b1f702ad0980f/model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto#L1668
This fixes https://github.com/apache/beam/issues/29354.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier …
> Adds a list of requirements to the expansion request

- .github/workflows/beam_PreCommit_PythonDocker.yml
This was missing, the job is already configured to allow workflow_dispatch …
> Update beam_PreCommit_PythonDocker.yml to allow manual triggering

- contributor-docs/release-guide.md
Fixes some things and updates the guide to reflect new release actions …
> Updates to release guide RC creation

- .github/workflows/beam_PostRelease_NightlySnapshot.yml
Looks like we missed https://github.com/apache/beam/blob/master/.test-infra/jenkins/job_PostRelease_NightlySnapshot.groovy, this migrates it over …
> Add job for validating release snapshots

- .github/workflows/beam_PostRelease_NightlySnapshot.yml
Forgot to rename a few fields and now its hard to disambiguate this job with the normal release snapshot
[![Build …
> Fix beam_PostRelease_NightlySnapshot.yml naming

- .github/workflows/beam_PreCommit_PythonDocker.yml
Example passing run - https://github.com/apache/beam/actions/runs/6813791913 …
> Upgrade go version in python docker build

- .github/workflows/beam_PostCommit_XVR_Flink.yml
- .test-infra/tools/build.gradle
- .test-infra/tools/stale_dataflow_jobs_cleaner.sh
- .test-infra/tools/stale_k8s_workload_cleaner.sh
- .test-infra/tools/stale_spanner_cleaner.sh
The test_data table got accidentally deleted when manually clean up test tables, because https://github.com/apache/beam/actions/workflows/beam_CancelStaleDataflowJobs.yml?page=2 shows there were tables cannot be cleaned by the cron cleaner job
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/ …
> Fix clean up resource workflow; fix XVR Flink

- .github/workflows/finalize_release.yml
Right now, this is all manual, this upgrades everything we can to automation …
> Create workflow for finalizing release

- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/CheckStopReadingFn.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/CheckStopReadingFnWrapper.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/WatchForKafkaTopicPartitions.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java
> Involve CheckStopReadingFn class adding a chance to release resources gracefully

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Update Go version used to build container boot loaders.
Note, should be cherry picked to release branch in case of a next RC. …
> Update default Go version to 1.21.4

- sdks/python/apache_beam/dataframe/expressions.py
- sdks/python/apache_beam/dataframe/pandas_docs_test.py
- sdks/python/apache_beam/runners/portability/flink_uber_jar_job_server_test.py
- sdks/python/apache_beam/runners/portability/spark_uber_jar_job_server_test.py
- sdks/python/apache_beam/runners/worker/logger.py
- sdks/python/apache_beam/transforms/external.py
- sdks/python/apache_beam/transforms/fully_qualified_named_transform.py
This could should exit regardless of whether the operations under the context threw exceptions. …
> Add some missing finally blocks on context managers.

- sdks/java/io/mongodb/src/main/java/org/apache/beam/sdk/io/mongodb/SSLUtils.java
- sdks/java/io/mongodb/src/test/java/org/apache/beam/sdk/io/mongodb/SSLUtilsTest.java
This was introduced in #26481 and supposed to fixed in #27250. However the fix was not complete. It leads KeyStore uninitialized if no ssl certificate present
The lesson learned
- even trivial change (eliminate nullness warning to make checkStyle happy) can introduce bug
- Add testing is encouraged. in this case, a smoke test would have revealed the problem missed in #27250
To check …
> Fix MongoDBIO ignore SSL KeyStore not initialized

- sdks/python/apache_beam/__init__.py
- sdks/python/container/py310/base_image_requirements.txt
- sdks/python/container/py311/base_image_requirements.txt
- sdks/python/container/py38/base_image_requirements.txt
- sdks/python/container/py39/base_image_requirements.txt
- sdks/python/setup.py
Cherry-pick https://github.com/apache/beam/pull/29396 to release branch. …
> [release-2.52.0] Cherrypick pyarrow mitigation to the release branch. 

- sdks/java/io/mongodb/src/main/java/org/apache/beam/sdk/io/mongodb/SSLUtils.java
- sdks/java/io/mongodb/src/test/java/org/apache/beam/sdk/io/mongodb/SSLUtilsTest.java
Cherrypicks #29393 to release branch in case we will proceed with RC4. …
> [release-2.52.0] Cherry-pick MongoDBIO fix.

- sdks/java/extensions/protobuf/build.gradle
- sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteUtils.java
- sdks/java/extensions/protobuf/src/test/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteUtilsTest.java
- sdks/java/extensions/protobuf/src/test/resources/README.md
- sdks/java/extensions/protobuf/src/test/resources/proto_byte/file_descriptor/proto_byte_utils.pb
- sdks/java/extensions/protobuf/src/test/resources/proto_byte/proto_byte_utils.proto
- sdks/java/io/kafka/README.md
- sdks/java/io/kafka/build.gradle
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProvider.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaWriteSchemaTransformProviderTest.java
- sdks/java/io/kafka/src/test/resources/proto_byte/file_descriptor/proto_byte_utils.pb
- sdks/java/io/kafka/src/test/resources/proto_byte/proto_byte_utils.proto
- sdks/python/apache_beam/yaml/standard_io.yaml
- Include the option to read and write proto in YAML Beam [KAFKA]
addresses #28664 …
> [YAML] - Kafka Read and Write proto

- sdks/python/apache_beam/yaml/pipeline.schema.yaml
The '__line__` and `__uuid__` fields are missing from pipeline.schema.yaml …
> [YAML] Add yaml metadata to provider schema

- sdks/java/harness/build.gradle
* Mark Avro as provided in harness JAR
* Add permitUnusedDeclared for Avro
Got this from `git cherry-pick abc0a057935d66dadd6841595850329fc84dcba5`, cherry-picking #29412 …
> Mark Avro as provided in harness JAR (#29412)

- sdks/python/apache_beam/typehints/typehints.py
- sdks/python/apache_beam/typehints/typehints_test.py
Plugs a gap in Collections handling where lists were not being treated as compatible with Collections. 
Part of #29135 …
> Establish list to collection compatibility

- sdks/python/apache_beam/io/gcp/bigquery_tools_test.py
* Here we skip the credential authentication, and
* we also mock gcp_bigquery so it won't raise an exception that causes this test to be skipped. …
> Fix the test 'test_user_agent_passed' without skipping it

- sdks/python/apache_beam/io/requestresponseio.py
- sdks/python/apache_beam/io/requestresponseio_it_test.py
This PR addresses #28710 and addresses #28711 by defining Caller and SetupTeardown abstract classes in Python. Implementation tests implement these classes, calling the HTTP supported [.test-infra/mock-apis](https://github.com/apache/beam/tree/master/.test-infra/mock-apis).
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_ …
> [RRIO] [Call] Define Caller & SetupTeardown interfaces

- sdks/go/pkg/beam/runners/prism/internal/preprocess.go
The "Large Wordcount" example is failing with fusion in prism enabled. Go back to the previous approach while it's being resolved. …
> [prism] Fix Go Precommits by disabling fusion.

- sdks/python/apache_beam/runners/dataflow/internal/names.py
> Update container tag to 20231113

- .github/workflows/beam_PreCommit_Go.yml
- .github/workflows/beam_PreCommit_GoPortable.yml
- .github/workflows/beam_PreCommit_GoPrism.yml
Typo in the Go precommit triggers (go.**, instead of **.go) prevented the Go Precommit Actions from triggering appropriately. …
> Fix Go Precommit Triggers

- .github/workflows/beam_Metrics_Report.yml
This PR fixes an invalid workflow file error.
https://github.com/apache/beam/actions/runs/6862672705 reports that:
```
Invalid workflow file
The workflow is not valid. .github/workflows/beam_Metrics_Report.yml (Line: 56, Col: 9): Unexpected end of expression: ''workflow_dispatch''. Located at position 98 within expression: ((github.event_name == 'schedule' && github.repository == 'apache/beam') ||
github.event_name == 'workflow_dispatch'
```
To …
> Fix closing parenthesis in beam_Metrics_Report.yml

- .github/REVIEWERS.yml
This PR adds myself (damondouglas) to .github/REVIEWERS.yml under the Java, IO, and fallback sections. …
> Add damondouglas to REVIEWERS

- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubSubPayloadTranslation.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
Updates pubsub payload translation to allow custom pubsub source and sink for runner v2.
addresses #29397 
[![Build …
> Add custom pubsub source and sink experiment support for runner v2.

- settings.gradle.kts
When build locally, every project stuck at `Building ... Requesting from remote build cache` for ~20 s …
> Disable remote cache when no credential provided

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- examples/java/build.gradle
- runners/google-cloud-dataflow-java/arm/build.gradle
- sdks/java/io/kafka/build.gradle
> Fix Dataflow ARM PostCommit failing on Java21

- CHANGES.md
Mention worker start-up logging changes to the Python SDK in 2.50.0 and 2.51.0 …
> Add logging changes to CHANGES.md

- CHANGES.md
> [changes.md] #29451 notice about deprecation of Euphoria DSL

- runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java
Add tests to check the name of the transform …
> Test sink name

- sdks/python/apache_beam/runners/dataflow/internal/names.py
> Update beam-master container tag for python

- website/www/site/content/en/blog/splittable-do-fn.md
Add a link to SDF from blog.
http://apache-beam-website-pull-requests.storage.googleapis.com/29458/index.html
[![Build …
> Update splittable-do-fn.md with links to doc

- .github/REVIEWERS.yml
Give the website prs more attention from folks who are equipped to do so …
> Add website reviewers

- sdks/go/examples/snippets/04transforms.go
- sdks/python/apache_beam/examples/snippets/snippets_test.py
- website/www/site/content/en/documentation/programming-guide.md
Fixes #28129
✨ [RENDERED](https://apache-beam-website-pull-requests.storage.googleapis.com/29466/documentation/programming-guide/index.html#combine) ✨  …
> Document compact lifecycle method

- CHANGES.md
- website/www/site/config.toml
- website/www/site/content/en/blog/beam-2.52.0.md
- website/www/site/content/en/get-started/downloads.md
> Website updates for the 2.52.0 release

- .github/workflows/finalize_release.yml
As I went through the flow I found several issues. In the end I got all jobs to run succesfully (in separate runs across https://github.com/apache/beam/actions/workflows/finalize_release.yml) …
> Fix finalize_release

- contributor-docs/release-guide.md
Clarifies some incomplete/incorrect/missing pieces and updates docs to reflect newest automation …
> Update release guide with post rc edits

- examples/notebooks/beam-ml/custom_remote_inference.ipynb
Copy edit the Custom Remote Inference notebook …
> Copy edit the Custom Remote Inference notebook

- runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto
Define PerStepNamespaceMetrics proto that will be used to send metric updates on the GetData heartbeat requests.
We will use this proto to send the new BigQuery metrics to WMWs.
These metric updates will be part of the GlobalDataRequest since they are not tied to a particular work item. We will add some additional logic in the Dispatcher to route these requests appropriately.
Additionally, add a worker_id field to GetDataRequest so we can store metrics on a per user worker basis on WMW. …
> Define PerStepNamespaceMetrics proto that will be used to send metric updates on the GetData heartbeat requests.

- CHANGES.md
Add call-out for type hint changes to 2.53.0 CHANGES.md …
> Add type hint changes to CHANGES.md

- sdks/python/apache_beam/io/requestresponseio.py
- sdks/python/apache_beam/io/requestresponseio_it_test.py
As a suggestion from https://github.com/apache/beam/pull/29421#discussion_r1395015226 …
> [RRIO][Python] Replace call with __call__ to make caller callable

- contributor-docs/release-guide.md
> Adding instructions for PMC finalization

- playground/kafka-emulator/build.gradle
Fixes #29472
Gradle 8 removed baseName property, but the recommended replacement `archiveBaseName` behaves differently (lazy config). In this case, its toString() form does not print its value, causing file name not set correctly …
> Fix kafka emulator dist name

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
> Attach exact cause in RuntimeException raised

- .github/workflows/build_release_candidate.yml
I did some researches. The easiest way is to use https://github.com/cicirello/javadoc-cleanup when releasing our javadoc.
Fixes #26445 
Tested using PR #29475  …
> add canonical link into javadocs when releasing javadoc

- website/www/site/content/en/documentation/sdks/java-dependencies.md
* Add a section with information about dependency management from the blog post: https://beam.apache.org/blog/managing-beam-dependencies-in-java/
* Reorganize the existing content to make it clearer …
> Update Java dependency management page

- sdks/python/apache_beam/utils/subprocess_server.py
This fixes https://github.com/apache/beam/issues/29424. …
> Close the gRPC channel started for the expansion service

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Revert protobuf version update from #29357
> Revert protobuf version

- sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIO.java
- sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/ClickHouseWriter.java
- sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/TableSchema.java
- sdks/java/io/clickhouse/src/main/javacc/ColumnTypeParser.jj
- sdks/java/io/clickhouse/src/test/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIOTest.java
- sdks/java/io/clickhouse/src/test/java/org/apache/beam/sdk/io/clickhouse/TableSchemaTest.java
Add bool type to ClickHouse SDK addresses #29087 …
> Add bool type to ClickHouse SDK

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Reset protobuf version to 3.24.4 as an internal error is resolved.
This reverts commit 183141d2eab4f8b1f4ffd67200f5618c3abd48af. …
> Revert "revert protobuf version (#29523)"

- website/www/site/content/en/blog/beam-2.52.0.md
Right now, this renders with a date of 0001/01/01 (see https://beam.apache.org/blog/ and https://beam.apache.org/blog/beam-2.52.0/), this fixes the problem.
✨ [RENDERED](https://apache-beam-website-pull-requests.storage.googleapis.com/29544/blog/beam-2.52.0/index.html) ✨ 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_ST …
> Fix blog date format

- model/job-management/src/main/proto/org/apache/beam/model/job_management/v1/beam_expansion_api.proto
> Add a description field to the schema transform config.

- sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
Add pathPrefix for ElasticSearch rest client. #29526 …
> Add pathPrefix for ElasticSearch rest client.

- website/www/site/content/en/documentation/programming-guide.md
- website/www/site/layouts/partials/section-menu/en/documentation.html
For more information, please see the Github issue: https://github.com/apache/beam/issues/27943 …
> Documents the transform upgrade feature

- website/www/site/content/en/documentation/programming-guide.md
> Fix typos in documentation

- sdks/python/apache_beam/yaml/yaml_provider.py
This produces better results when using renaming providers in particular. …
> Consider underlying providers in both directions when doing affinity test.

- .github/actions/gradle-command-self-hosted-action/action.yml
- .github/workflows/java_tests.yml
- .gitmodules
This change removes the `gradle-command-action` submodule, and all of it's usages, in favor of the updated `gradle-build-action` version of this action.
fixes https://github.com/apache/beam/issues/29479 …
> Replace usage of custom `gradle-command-action` with `gradle-build-action`

- .github/workflows/java_tests.yml
This change properly escapes array arguments that are passed into `integrationTestPipelineOptions`. This fixes a Gradle parsing error introduced by the change made in https://github.com/apache/beam/pull/29480. …
> Escape strings in integrationTestPipelineOptions in Java Tests

- NOTICE
- sdks/python/apache_beam/runners/dask/transform_evaluator.py
Closes #26669 
Explicitly set the number of partitions in the underlying Dask bag to avoid concurrency limits in Dask.
cc @alxmrs @cisaacstern  …
> Dask runner: Use bag sqrt scaling

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteReadSchemaTransformProvider.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteWriteSchemaTransformProvider.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/PubsubLiteDlqTest.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/PubsubLiteWriteDlqTest.java
- sdks/python/apache_beam/yaml/standard_io.yaml
> [YAML] - PubSubLite Normalization

- sdks/python/apache_beam/yaml/README.md
Refactor README.md to mark existing features as stable. …
> [yaml] Unmark as experimental

- sdks/python/apache_beam/runners/dataflow/internal/names.py
A new container version has been cloned …
> Update dataflow container tag

- sdks/python/apache_beam/transforms/ptransform.py
The existing `functools.wraps` is insufficient as the signature is modified.  …
> Better introspection of PTransforms defined with @ptransform_fn.

- .github/workflows/beam_PostCommit_XVR_GoUsingJava_Dataflow.yml
Right now, this is failing to create a container correctly because its missing buildx. This fixes the problem, though the job still has other issues. 
Run before this change - https://github.com/apache/beam/actions/runs/7114073479/job/19367356933
Run with this change - https://github.com/apache/beam/actions/runs/7107131541
It is still failing, but no longer because of container issues. Here's an example job - https://pantheon.corp.google.com/dataflow/jobs/us-central1/2023-12-05_14_57_46-2655664355236774149;step=;bottomTab=WORKER_LOGS;logsSeverity=ERROR;graphView=0?project=apache-beam-testing&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22))&e=13802955&mods=logs_tg_staging - looks like the worker fails somehow. …
> Add buildx install to postcommit_XVR_Go

- sdks/python/apache_beam/yaml/yaml_transform.py
Fix issue where user labels get overridden by manual 'yaml' label.  …
> [yaml] fix yaml label appending

- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryStreamingLT.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AppendClientInfo.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServices.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiFinalizeWritesDoFn.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiFlushAndFinalizeDoFn.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/testing/FakeBigQueryServices.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/testing/FakeDatasetService.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImplTest.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilTest.java
Fixes #29603
* Avoid unnecessary STORAGE_WRITE_API client creation and teardown when DatasetService is not used for storage write api …
> Split BigQuery DatasetService and WriteStreamService

- sdks/python/apache_beam/ml/inference/huggingface_inference.py
- sdks/python/apache_beam/ml/inference/onnx_inference.py
- sdks/python/apache_beam/ml/inference/pytorch_inference.py
- sdks/python/apache_beam/ml/inference/sklearn_inference.py
- sdks/python/apache_beam/ml/inference/tensorflow_inference.py
- sdks/python/apache_beam/ml/inference/tensorrt_inference.py
- sdks/python/apache_beam/ml/inference/vertex_ai_inference.py
- sdks/python/apache_beam/ml/inference/xgboost_inference.py
- sdks/python/apache_beam/transforms/util.py
Uses the shared.py framework to generate a key per worker process for stateful element batching, improving parallelization. Also exposes the parameter to enable stateful element batching though the model handlers + adds batching parameter support to model handlers that previously did not have it. 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/m …
> Add per-worker keys to stateful BatchElements, plumb through batching options to all model handlers

- sdks/python/apache_beam/yaml/yaml_io.py
Disable mypy on yaml_io.py to restore the failing the Python lint precommit.
Part of #29665 …
> Disable failing mypy check in yaml_io.py

- sdks/python/apache_beam/transforms/ptransform.py
For some cases (e.g. builting functions) signature retrieval fails. In this case, don't attempt to patch the (non-available) signature. …
> Fix for signature exceptions in ptransform_fn.

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/container/license_scripts/dep_urls_java.yaml
Update google_cloud_platform_libraries_bom to 26.28.0. Associated updates to google_cloud_spanner_version, gax_version, and protobuf_version. …
> Update to Libraries-Bom 26.28.0

- sdks/python/apache_beam/yaml/generate_yaml_docs.py
- sdks/python/apache_beam/yaml/yaml_provider.py
> Fix some lint errors in Python.

- sdks/python/apache_beam/io/requestresponseio.py
- sdks/python/apache_beam/io/requestresponseio_it_test.py
- sdks/python/apache_beam/io/requestresponseio_test.py
Adds a Call PTransform with setup and teardown.
Expect this experimental at this point (changes to the transform are possible) since Cache and Throttling (Preventive/Adaptive) are yet to be added.
Part of #29063 …
> [Python][RRIO] Call PTransform with setup teardown

- sdks/python/apache_beam/testing/load_tests/load_test_metrics_utils.py
> Publish job

- sdks/python/build.gradle
This might mitigate:  https://github.com/apache/beam/issues/28703
> Retry building a wheel up to 3 times.

- runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java
- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/MultimapSideInput.java
- sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/MultimapSideInputTest.java
- sdks/python/apache_beam/runners/worker/bundle_processor.py
This is needed as some runners (e.g. Dataflow) do not gracefully return errors on unkown state read types.
This flag will be set via runner capabilites in a future PR. …
> Guard keys-values multi map input with a flag.

- sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/SchemaTransformProvider.java
- sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java
- sdks/java/extensions/sql/expansion-service/src/main/java/org/apache/beam/sdk/extensions/sql/expansion/SqlTransformSchemaTransformProvider.java
- sdks/python/apache_beam/transforms/external.py
- sdks/python/apache_beam/yaml/standard_providers.yaml
- sdks/python/apache_beam/yaml/yaml_mapping.py
- sdks/python/apache_beam/yaml/yaml_provider.py
[yaml-autogenerated-docs.md](https://github.com/apache/beam/files/13605886/yaml-autogenerated-docs.md) …
> [YAML] Add and cleanup documentation for several builtin transforms.

- sdks/python/scripts/generate_pydoc.sh
- sdks/python/tox.ini
> Mock packages instead of installing in tox pydocs task

- sdks/python/container/boot.go
Adds logging for packages installed in runtime environment for Python SDK.
Part of #28563 
Dependencies log:
Python version log: …
> [Python] Log dependencies in runtime environment

- sdks/python/apache_beam/testing/load_tests/load_test_metrics_utils.py
> Save Job IDs of dataflow load tests

- model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto
- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/FnApiStateAccessor.java
- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/MultimapSideInput.java
- sdks/python/apache_beam/portability/common_urns.py
- sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
- sdks/python/apache_beam/runners/worker/bundle_processor.py
- sdks/python/apache_beam/runners/worker/bundle_processor_test.py
- sdks/python/apache_beam/runners/worker/log_handler_test.py
- sdks/python/apache_beam/runners/worker/sdk_worker.py
- sdks/python/apache_beam/runners/worker/sdk_worker_main.py
- sdks/python/apache_beam/runners/worker/sdk_worker_test.py
- sdks/python/gen_protos.py
This should finish the SDK-side changes needed for https://github.com/apache/beam/issues/29691 …
> Enable keys values multimap protocol based on runner capabilities.

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
Google Cloud BigQuery supports spaces in table names, but the airflow connector does not. This PR modifies the regex that matches table names to support a space. …
> Support BigQuery tables with spaces

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetrics.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetricsTest.java
This method will be used to extract the base metric name and the metric labels when extracting perworker metric updates from the user worker.  …
> Add utility method to parse metric labels/base name from a mangled bigquery  metric name. 

- sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/util/HistogramDataTest.java
Implement 'getAndReset' method in `HistogramData`.
This will be used to extract the updates from a `HistogramData` object that is shared between multiple threads into a `HistogramData` object that is only used by a single thread. SDKs can use the newly created `HistogramData` to safely extract metric updates. …
> Add HistogramData::getAndReset method

- sdks/python/apache_beam/ml/inference/huggingface_inference.py
adds missing parenthesis, otherwise the evaluation is always true …
> Fix syntax 

- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/TestDataflowRunner.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystems.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/io/FileSystemsTest.java
- sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtilIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryClusteringIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOJsonIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOReadIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadTableRowIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryKmsKeyIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryNestedRecordsIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaUpdateOptionsIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryTimePartitioningClusteringIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryToTableIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/storage/GcsKmsKeyIT.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/storage/GcsMatchIT.java
Fixes #19191
* Add FileSystems.matchNewDirectory and replace the raw string concatenate throughout the code base …
> Deal with trailing slash in tempRoot

- runners/google-cloud-dataflow-java/build.gradle
> Bump dataflow Legacy Container Version

- examples/notebooks/beam-ml/run_custom_inference.ipynb
Change "inforamtion" to "information" …
> Fix typo in Custom Remote Inference notebook

- CHANGES.md
- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Both [CVE-2023-45285](https://security-tracker.debian.org/tracker/CVE-2023-45285) and [CVE-2023-39326](https://security-tracker.debian.org/tracker/CVE-2023-39326) are resolved with go 1.21.5 …
> Upgrade go version to resolve vulnerabilities

- examples/java/src/main/java/org/apache/beam/examples/KafkaStreaming.java
> revert kafka host change

- sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/JvmInitializers.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
Add logs to confirm JvmInitializer completed running and Spanner successfully connected. …
> Add logs to confirm JvmInitializer completed running and Spanner successfully connected.

- sdks/python/container/py310/base_image_requirements.txt
- sdks/python/container/py311/base_image_requirements.txt
- sdks/python/container/py38/base_image_requirements.txt
- sdks/python/container/py39/base_image_requirements.txt
The new bigtable client should fix the issue reported in https://github.com/apache/beam/issues/28715 …
> Update Bigtable python client version

- it/jdbc/src/main/java/org/apache/beam/it/jdbc/AbstractJDBCResourceManager.java
Needed to retrieve port for connecting to various JDBC resources (MySQL, Postgres, Oracle, etc.) when connecting to another RM in an IT. …
> Pass getPort method through JDBC Resource Managers

- sdks/python/apache_beam/typehints/schemas.py
Fixes #29684 
Remove this line for now to unblock the release cut. Filed #29756 …
> Remove setting _beam_schema_proto 

- sdks/go/pkg/beam/core/runtime/harness/harness.go
Fix to panic caused by handling data sampling request when it's not enabled.
Fixes #29760 …
> [#29760] Only respond to sampling request while data sampling is enabled

- sdks/python/apache_beam/yaml/yaml_mapping.py
- sdks/python/apache_beam/yaml/yaml_transform.py
Ran into a case where MapToFields-java did not like being passed a non-iterable drop parameter in config.
[![Build …
> [yaml] Normalize drop on MapToFields

- build.gradle.kts
- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/TransformUpgrader.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java
- sdks/java/io/kafka/upgrade/build.gradle
- sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java
- sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java
Seems like this feature broke due to.
* Object serialization issues (specifically BQ coder and BigQueryServicesImpl).
* A new field addition to KafkaIO.
Makes the implementation more robust and adds the Kafka upgrade module to IO precommit.
This fixes https://github.com/apache/beam/issues/29730
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/mast …
> Fixes breakages of the upgrade feature

- sdks/go/pkg/beam/core/runtime/harness/harness.go
Cherry pick of #29761 to the 2.53.0 release branch.  
Fixes #29760 …
>  [#29760] Only respond to sampling request while data sampling is enabled

- sdks/python/apache_beam/io/gcp/gcsio.py
- sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
- sdks/python/apache_beam/runners/interactive/utils.py
- sdks/python/apache_beam/runners/portability/sdk_container_builder.py
- sdks/python/setup.py
The user-agent string was added into gcsio in [PR 27211](https://github.com/apache/beam/pull/27211). However, due to the fact that google-cloud-storage<2.13.0 does not support extra header, we did not keep user-agent during the migration [PR 29360](https://github.com/apache/beam/pull/29360).
Now, as we upgrade google-cloud-storage dependency to the latest version (2.14.0), we can support user-agent string in the request header again.
To check …
> Add user-agent string for Beam in the GCS request header.

- sdks/python/apache_beam/typehints/schemas.py
> [cherry-pick] Remove setting _beam_schema_proto (#29754)

- .github/workflows/beam_PreCommit_Java_Examples_Dataflow.yml
- .github/workflows/beam_PreCommit_Java_Examples_Dataflow_Java21.yml
Adds a 15 minute bump to the workflow timeouts for PreCommit_Java_Examples_Dataflow and PreCommit_Java_Examples_Dataflow_Java21 actions that have been getting cancelled before completing on the 2.53.0 release branch …
> Bump Precommit Java Examples Timeouts

- CHANGES.md
Updates CHANGES.md after the 2.53.0 release branch cut …
> Add 2.54.0 release section to CHANGES.md

- sdks/go/pkg/beam/core/runtime/exec/datasink.go
- sdks/go/pkg/beam/core/runtime/exec/pcollection.go
Decrease sampling frequency for streaming jobs to avoid oversampling …
> [Go SDK] Decrease sampling frequency for streaming jobs to avoid oversampling

- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/StreamingEngineClientTest.java
> Ignore testOnNewWorkerMetadata_correctlyRemovesStaleWindmillServers

- .github/workflows/beam_PostCommit_Java_Tpcds_Spark.yml
Add `SparkStructuredStreamingRunner` to `beam_PostCommit_Java_Tpcds_Spark` workflow since it was lost during Jenkins -> GitHub Actions migration. …
> Add SparkStructuredStreamingRunner to beam_PostCommit_Java_Tpcds_Spark workflow

- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/TransformUpgrader.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java
- sdks/java/io/kafka/upgrade/build.gradle
- sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java
- sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java
Cherry-picks https://github.com/apache/beam/pull/29731 to the 2.53.0 release branch.
This fixes https://github.com/apache/beam/issues/29730.
* Fixes breakages of the upgrade feature
* Fix spotless
* Addressing reviewer comments
* Removing unused import
* Reverting the PreCommit update …
> Fixes breakages of the upgrade feature (#29731)

- buildSrc/src/main/groovy/org/apache/beam/gradle/GrpcVendoring_1_54_0.groovy
add alts to grpc vendored lib.  it is needed for direct path. …
> add alts to grpc vendored lib

- .github/gh-actions-self-hosted-runners/arc/locals.tf
https://github.com/actions/actions-runner-controller/issues/3159
Temporary fix …
> pin dind image temoporarily due to issues #3159

- sdks/go/pkg/beam/core/runtime/exec/datasampler.go
- sdks/go/pkg/beam/core/runtime/exec/datasampler_test.go
make DataSample external
based on Golint:
exported method GetSamples returns unexported type map[string][]*exec.dataSample, which can be annoying to use …
> [Go SDK] (delint) make DataSample external

- .github/workflows/build_wheels.yml
- .github/workflows/python_tests.yml
#29777 upgraded all upload-artifact usage to v4, but download-artifact was not upgraded. Per https://github.com/actions/download-artifact/issues/250#issuecomment-1857317206 these need to be kept in sync now.
This was causing workflows to fail previously - e.g. https://github.com/apache/beam/actions/runs/7251952779
Example of same workflow not running into this issue with my change - https://github.com/apache/beam/actions/runs/7252030342
To …
> Upgrade download-artifact to v4

- sdks/python/container/boot.go
Cherrypick #29804 into release branch …
> [release-2.53.0] Fix nil pointer access in logRuntimeDependencies 

- build.gradle.kts
> Adds Kafka upgrade module to the I/O precommit

- sdks/python/apache_beam/yaml/yaml_provider.py
> [YAML] Properly deligate methods for renaming provider.

- sdks/python/apache_beam/yaml/standard_providers.yaml
Issues with unknown logical types.
This fixes #29825. …
> Revert to non-schema-based Sql transform.

- runners/portability/java/build.gradle
Cherrypick of #29836 into release branch …
> [release-2.53.0] Remove failing multimap key iteration tests.

- .github/workflows/build_release_candidate.yml
> Fix input issue and quoting

- .github/workflows/deploy_release_candidate_pypi.yaml
- .github/workflows/finalize_release.yml
Same fix as https://github.com/apache/beam/pull/29840 …
> Fix logging/quoting

- learning/tour-of-beam/learning-content/core-transforms/map/co-group-by-key/description.md
Right now, this renders go code for the python example, this fixes the problem.
Fixes #29535 …
> Fix tour of beam co-group-by-key python example

- learning/tour-of-beam/learning-content/core-transforms/map/co-group-by-key/description.md
> [TOB] Fix constructor names

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
- sdks/python/apache_beam/io/gcp/pubsub.py
Change pubsub message cap size from 10MiB to 10MB
Pubsub's max allowed message size is 10million bytes and not 10 * 2^20 bytes https://cloud.google.com/pubsub/quotas …
> Change pubsub message cap size from 10MiB to 10MB

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
```
cd /tmp; wget https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/26.28.0/libraries-bom-26.28.0.pom -O base.pom && mvn help:effective-pom -f base.pom -Doutput=effective.pom && cat effective.pom | grep -v 'dependencyManagement' > cleanup.pom && mvn dependency:tree -f cleanup.pom
```
Yields
```
[INFO] |  +- com.google.apis:google-api-services-storage:jar:v1-rev20231202-2.0.0:compile
```
Making the change accordingly, since this mismatch is causing some errors on RC validation: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1233/checks?check_run_id=19897484522
```
java.lang.NoClassDefFoundError: com/google/api/services/storage/model/Bucket$ObjectRetention
at com.google.cloud.storage.JsonConversions.<init>(JsonConversions.java:120)
at …
```
> Update google-api-services-storage to match libraries-bom

- .github/workflows/beam_PostCommit_Python.yml
- .github/workflows/beam_PostCommit_Python_Arm.yml
- .github/workflows/beam_PreCommit_Python.yml
- .github/workflows/beam_PreCommit_Python_Dataframes.yml
- .github/workflows/beam_PreCommit_Python_Examples.yml
- .github/workflows/beam_PreCommit_Python_Integration.yml
- .github/workflows/beam_PreCommit_Python_Runners.yml
- .github/workflows/beam_PreCommit_Python_Transforms.yml
- .github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml
Fixes https://github.com/apache/beam/actions/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml. Likely caused by #29777 . Error message:
```
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#m …
> Fix uploadArtifact@4 naming conflict

- contributor-docs/release-guide.md
This got missed for the last release …
> Add docs on updating the starter repos as a post release task

- website/www/site/content/en/get-started/_index.md
- website/www/site/content/en/get-started/resources/learning-resources.md
> Added some learning doc links

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
It is possible for the SpannerAccessor to be in the process of being closed at the same time as its refcount is being increased.
This would lead to java.lang.IllegalStateException: Pool has been closed errors.
These 2 functions are only called in `@Setup` and `@Teardown`  functions of SpannerIO, so high performance is not needed and a global lock is adequate.
In a large pipeline, this affects ~1% of workers at random, and (probably) only affects pipelines running on multi-CPU machines (where there is more than 1 worker thread per worker node). 
Fixes #29832 …
> Fix race condition in SpannerAccessor

- .test-infra/jupyter/README.md
- sdks/go/pkg/beam/runners/prism/internal/stage.go
Just fix a typo: s/commiting/committing/ …
> fix: Fix typo s/commiting/committing/

- sdks/java/io/neo4j/src/main/java/org/apache/beam/sdk/io/neo4j/Neo4jIO.java
Use result.next instead of result.list that returns the full result, stored in memory. Fixes #29762.
[![Java …
> Make Neo4JIO streamed (Fixes #29762)

- settings.gradle.kts
> Revert "Bump com.gradle.enterprise from 3.15.1 to 3.16"

- sdks/go/test/integration/primitives/timers.go
- sdks/go/test/integration/primitives/timers_test.go
Remove underscores from test names for style lint reasons.
Fixes #29893. 
----- …
> [#29895][Go SDK] Update timer test function names.

- runners/portability/java/build.gradle
- sdks/python/apache_beam/runners/portability/fn_api_runner/execution.py
- sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
> Support key iteration in Python ULR.

- .github/REVIEWERS.yml
> fix indent in reviewers file

- sdks/python/apache_beam/options/pipeline_options.py
- sdks/python/apache_beam/options/pipeline_options_test.py
This brings Python in line with typescript. …
> Allow pulling default beam services from an environment variable.

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
- website/www/site/content/en/documentation/io/built-in/google-bigquery.md
> update bq docs on stable schemas

- .github/workflows/go_tests.yml
- .github/workflows/java_tests.yml
- .github/workflows/python_tests.yml
Example run:
Java tests: https://github.com/apache/beam/actions/runs/7402094110/job/20139216970
Python tests: https://github.com/apache/beam/actions/runs/7402107570/job/20139271254
Go tests: https://github.com/apache/beam/actions/runs/7402110712/job/20139292833 …
> Switch to use self hosted runners for linux unit tests

- sdks/python/apache_beam/runners/dataflow/dataflow_job_service.py
- sdks/python/apache_beam/runners/dataflow/dataflow_job_service_test.py
Check has_job to cover for when creating a template and not creating a job
addresses #29884
I did not add a test for this, as the current test uses a dry_run, and im not sure how to add proper tests …
> Fix: creating templates with the Typescript SDK

- CHANGES.md
- website/www/site/config.toml
- website/www/site/content/en/blog/beam-2.53.0.md
- website/www/site/content/en/get-started/downloads.md
Adds 2.53.0 release information to the beam website. DO NOT MERGE until release is approved  …
> [release] 2.53.0 Website Updates

- .github/workflows/cut_release_branch.yml
Adds the additional context of the RELEASE_VERSION var being the version of the branch being cut …
> [release] Add extra context for release branch cut action input

- sdks/typescript/src/apache_beam/runners/dataflow.ts
Fixes: https://github.com/apache/beam/issues/29884 …
> [Typescript] stop service when done

- examples/notebooks/beam-ml/data_preprocessing/compute_and_apply_vocab.ipynb
- examples/notebooks/beam-ml/data_preprocessing/huggingface_text_embeddings.ipynb
- examples/notebooks/beam-ml/data_preprocessing/scale_data.ipynb
- examples/notebooks/beam-ml/data_preprocessing/vertex_ai_text_embeddings.ipynb
> Install beam from pypi instead of github in mltransform notebooks

- examples/notebooks/beam-ml/data_preprocessing/vertex_ai_text_embeddings.ipynb
> Remove TODO in the notebook

- contributor-docs/release-guide.md
Make the copy instructions precise. …
> Update pmc finalization in release-guide.md

- CHANGES.md
- website/www/site/content/en/blog/beam-2.53.0.md
We should use  Security Fixes not Breaking Changes for the go update. …
> Updated the doc with Security Fixes for 2.53.0

- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineDebugOptions.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/sideinput/SideInputCache.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/sideinput/SideInputStateFetcher.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/sideinput/SideInputStateFetcherTest.java
> [Dataflow Streaming] Make SideInputCache bytes and expiry configurable

- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/ApiIOError.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Cache.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/CallShouldBackoff.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/CallShouldBackoffBasedOnRejectionProbability.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/DefaultSerializableBackoffSupplier.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Monitoring.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Quota.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RedisClient.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Repeater.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Result.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/SerializableSupplier.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/ThrottleWithExternalResource.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeExecutionException.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeQuotaException.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeRemoteSystemException.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/UserCodeTimeoutException.java
- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoff.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CacheIT.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CallShouldBackoffBasedOnRejectionProbabilityTest.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CallTest.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoGRPCCallerWithSetupTeardownIT.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoResponseCoder.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RedisClientIT.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RepeaterTest.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOIT.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOTest.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/ThrottleWithExternalResourceIT.java
- sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoffTest.java
This PR closes #28934 with final planned incorporation of various features - Throttle, Cache, and Call. The PR adds additional Call related features such as backoff and repeat. This PR also closes #29724 by removing the unnecessary and flaky test.
GitHub Actions …
> [RRIO] Build RequestResponseIO and related dependency changes

- .github/workflows/beam_PreCommit_Java_Kafka_IO_Direct.yml
This workflow consistently sits around an hour in runtime, causing it to often fail because of this timeout - https://github.com/apache/beam/actions/workflows/beam_PreCommit_Java_Kafka_IO_Direct.yml?query=event%3Aschedule …
> Bump timeout to 120 minutes

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/container/license_scripts/dep_urls_java.yaml
Increment GCP Libraries BOM to latest as per the post-release workflow …
> Bump GCP Libraries BOM to v26.29.0

- .github/workflows/build_wheels.yml
Since upgrading to v4 we've experienced some flakiness in our downloads. It looks like uploading and then immediately downloading has some issues with the new artifact protocol. This temporarily downgrades us until that is fixed.
The GitHub issue is tracked in https://github.com/actions/download-artifact/issues/249 …
> Downgrade artifact version in build_wheels

- sdks/python/apache_beam/yaml/yaml_mapping.py
- sdks/python/apache_beam/yaml/yaml_transform.py
- sdks/python/apache_beam/yaml/yaml_transform_test.py
This allows windowing to be easily used for a batch context. It could be used for Streaming as well, but care needs to be taken that the timestamps are always assigned forward in time. (It's easier to guarantee this at the source.) …
> [YAML] Add AssignTimestamps transform.

- sdks/python/apache_beam/yaml/README.md
- sdks/python/apache_beam/yaml/main.py
This PR replaces the `--pipeline_spec` and `--pipeline_spec_file` parameters when running main.py to `--yaml_pipeline` and `--yaml_pipeline_file`, respectively. The old parameters will still be available as aliases for backwards compatibility.
GitHub Actions …
> [yaml] Replace pipeline_spec with yaml_pipeline in main.py

- sdks/python/apache_beam/runners/dataflow/internal/names.py
> Update python container tag(contains Pandas 2.0) 

- CHANGES.md
> update CHANGES.md with error handling for fileIO and bigtableIO

- .github/workflows/build_runner_image.yml
This will fix issues like https://github.com/apache/beam/pull/29992#issuecomment-1887920548 …
> Only auth and push on master branch

- sdks/python/apache_beam/transforms/fully_qualified_named_transform.py
- sdks/python/apache_beam/yaml/inline_python.md
- sdks/python/apache_beam/yaml/readme_test.py
- sdks/python/apache_beam/yaml/yaml_provider.py
- sdks/python/setup.py
This will be helpful when we don't yet support various features.  …
> [YAML] Better support for inline PyTransforms.

- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManager.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManagerTest.java
When reading from a topic using PubsubIO, Beam creates a `input_beam_` subscription.
When using PubsubResourceManager to create the topic and reading that topic, the topic would go away but the `input_beam_` would be leftover in the project.
This should make tests more self-contained and avoid reaching quota limits when running too many tests
> [IT] Pub/Sub RM should delete subscriptions that were created by Beam

- sdks/java/io/file-schema-transform/build.gradle
- sdks/java/io/parquet/build.gradle
Addresses #29906. This Parquet upgrade unblocks logical type support for parquet-avro, new predicate types, and more. …
> Upgrade Parquet to 0.13.1

- sdks/python/apache_beam/yaml/generate_yaml_docs.py
- sdks/python/apache_beam/yaml/json_utils.py
- sdks/python/apache_beam/yaml/main.py
- sdks/python/apache_beam/yaml/yaml_transform.py
This allows us to use json validation for config parameters of specific transforms. …
> [YAML] More complete schema validation.

- sdks/python/apache_beam/ml/transforms/base.py
- sdks/python/apache_beam/ml/transforms/base_test.py
- sdks/python/apache_beam/ml/transforms/embeddings/huggingface.py
- sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai.py
- sdks/python/apache_beam/ml/transforms/handlers.py
Part of #29356 
Support DLQ for MLTransform embeddings. 
For tft based transforms, raise NotImplementedError since the DoFn's implementations live in `tensorflow_transform` code base. …
> Support DLQ in MLTransform

- sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GceMetadataUtil.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOMetadata.java
> Add a read timeout and cache BigQueryIOMetadata

- website/www/site/content/en/documentation/programming-guide.md
Fixes a typo / bug in an example Python code block in the docs …
> typo in docs

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/providers/CsvWriteTransformProvider.java
- sdks/python/apache_beam/yaml/standard_io.yaml
> [YAML] Support comment and delimiter attributes on CSV IO.

- .test-infra/terraform/google-cloud-platform/google-kubernetes-engine/README.md
- .test-infra/terraform/google-cloud-platform/google-kubernetes-engine/us-central1.apache-beam-testing.tfvars
- .test-infra/terraform/google-cloud-platform/google-kubernetes-engine/us-west1.apache-beam-testing.tfvars
This PR adds a node_config argument to enable custom service accounts.  Additionally, it removes the `master_authorized_networks_config` to enable an external endpoint while keeping the cluster nodes private. …
> Update GKE autopilot terraform

- model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto
- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/WriteFilesTranslation.java
- runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/WriteFilesTranslationTest.java
- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
- runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/Pipeline.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextIO.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/PipelineTest.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/io/WriteFilesTest.java
Allows for runner support for autosharding for the textio transform.
Fixes #20949 …
> Add withAutosharding flag to textio transform

- sdks/python/apache_beam/dataframe/io.py
- sdks/python/apache_beam/yaml/inline_python.md
- sdks/python/apache_beam/yaml/readme_test.py
Follow-up to https://github.com/apache/beam/pull/29958 …
> Add a ReadFromTsv example.

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/container/license_scripts/dep_urls_java.yaml
Update libraries-bom version to 26.30.0 …
> Update to libraries-bom 26.30.0

- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Reshuffle.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/ReshuffleTrigger.java
RIght now, we've marked ReShuffle as deprecated, but it is still heavily used and there is no suitable replacement. We should undeprecate it until there is a suitable replacement (e.g. [Redistribute](https://lists.apache.org/thread/rc4tcq7k0950cdgw9lyd0s7vkz8rz5s9)) …
> Undeprecate reshuffle

- sdks/python/apache_beam/runners/worker/sdk_worker.py
I came across a couple of reports where SDK was not able to parse and execute a request received from the runner like in #28131. Adding some logs so that we can better understand cause of the error. …
> Add logging to help understand errors from #28131.

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/container/agent/build.gradle
- sdks/java/core/src/test/java/org/apache/beam/sdk/SdkHarnessEnvironmentTest.java
- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/Caches.java
- sdks/java/io/hadoop-format/build.gradle
According to the comment mark
```
// Swap to use the officially published version of 0.4.x once available
// instead of relying on a community published copy. See
// https://github.com/jbellis/jamm/issues/44 for additional details.
```
Offical jamm 0.4.0 has been released in July 2023: https://mvnrepository.com/artifact/com.github.jbellis/jamm/0.4.0 …
> Use official jamm

- runners/spark/job-server/spark_job_server.gradle
- runners/spark/spark_runner.gradle
> Exclude newly added failing validation runner tests

- sdks/python/apache_beam/portability/common_urns.py
- sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py
- sdks/python/apache_beam/runners/trivial_runner.py
Just move the executable stage urn string into `common_urns.py`
> Centralize exec stage urn string

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslator.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslatorTest.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteIT.java
If timeouts are set on BigtableIO directly, it should always override the configuration set in BigtableOptions. …
> Fix BigtableConfigTranslator

- sdks/java/io/cassandra/build.gradle
Fixes https://github.com/apache/beam/actions/workflows/beam_PreCommit_Java_Cassandra_IO_Direct.yml?query=event%3Aschedule after #30034
We did the same thing in #30034 for the embedded cassandra server in hadoop-format tests but missed this one. …
> Fix Cassandra Test

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowWorkUnitClientTest.java
Plumbing remaining autoscaling metrics: OutstandingBytes and MaximumOutstandingBytes …
> add remaining metrics

- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/PTransformTranslation.java
- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/PipelineTranslation.java
- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/TransformUpgrader.java
- runners/core-construction-java/src/test/java/org/apache/beam/runners/core/construction/TransformUpgraderTest.java
- sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java
- sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionServiceSchemaTransformProvider.java
- sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/JavaClassLookupTransformProvider.java
- sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceSchemaTransformProviderTest.java
- sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceTest.java
- sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExternalTest.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslationTest.java
- sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java
- sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java
- sdks/java/testing/expansion-service/src/test/java/org/apache/beam/sdk/testing/expansion/TestExpansionService.java
This fixes https://github.com/apache/beam/issues/30031. …
> Fixes an upgrade compatibility breakage for the BQ write transform

- runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderBase.java
- runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java
- runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/EmptyUnboundedSource.java
- runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceReaderTestBase.java
- runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReaderTest.java
> [flink] Fix watermark generation for empty UnboundedSource

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverter.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverterTest.java
Add a MetricsToPerStepNamespaceMetricsConverter class that converts metric updates to PerStepNamespaceMetrics objects.
We will periodically extract BigQuerySink metric updates, convert them into the PerStepNamespaceMetrics format, and send them to the Dataflow backend on the WorkerMessages api.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/mast …
> Add converter class to convert metrics to PerStepNamespaceMetrics

- sdks/python/apache_beam/ml/transforms/handlers.py
- sdks/python/apache_beam/ml/transforms/handlers_test.py
fixes: https://github.com/apache/beam/issues/30062 …
> Use FileSystems.exist to check the remote the path

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java
- sdks/python/apache_beam/yaml/standard_io.yaml
> [YAML] Require numStreams for unbounded BigQueryStorageWriteApiSchemaTransform xlang transform

- sdks/python/apache_beam/ml/transforms/base.py
- sdks/python/apache_beam/ml/transforms/base_test.py
> [MLTransform]Throw an error when specifiend columns are not present in the input data

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Quick update to the latest Go version before the release. This one doesn't have any CVE fixes, and is mostly runtime fix backports from the upcoming 1.22.0 release.
See https://go.dev/doc/devel/release for details. …
> Update container build version to Go 1.21.6

- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/DicomIOReadIT.java
These tests were unignored recently but still failing on Dataflow runner PostCommit: https://github.com/apache/beam/runs/20816595239 …
> Ignore DicomMetadataRead tests

- CHANGES.md
Add section for 2.55.0, cleanup 2.54.0 due to cut. …
> [Post Release Cut] CHANGES.md - Add section for 2.55.0, cleanup 2.54.0 due to cut.

- sdks/python/apache_beam/transforms/external_transform_provider.py
- sdks/python/apache_beam/transforms/external_transform_provider_test.py
> Cherry pick ExternalTransform rename (#30102)

- build.gradle.kts
- sdks/python/apache_beam/io/gcp/bigquery.py
- sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
- sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py
- sdks/python/test-suites/dataflow/common.gradle
> Fix failing python BQ test

- build.gradle.kts
- sdks/python/apache_beam/io/gcp/bigquery.py
- sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
- sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py
- sdks/python/test-suites/dataflow/common.gradle
> Cherry pick fix for Python postcommits

- sdks/go/pkg/beam/core/runtime/contextreg/contextreg.go
- sdks/go/pkg/beam/core/runtime/harness/init/init.go
Cherry pick to improve the Go SDK's compatibility with Go 1.20. …
> Don't depend on the go 1.21 standard lib yet

- sdks/python/apache_beam/testing/analyzers/perf_analysis.py
Most likely, the returned type is changed from the BQ client. …
> Check the issue number type

- runners/google-cloud-dataflow-java/build.gradle
> Bump Dataflow dev container version

- .github/workflows/update_python_dependencies.yml
This piece of automation has never worked, in part because it doesn't have all necessary python versions and in part because its missing permissions
Successful run with these changes - https://github.com/apache/beam/actions/runs/7670229674/job/20905956462
Example PR created by workflow - https://github.com/apache/beam/pull/30128
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https …
> Update update_python_dependencies.yml with all python versions

- CI.md
- README.md
Fix 
While #30112 is P3, there are a few handful doc clean ups in project root included in this PR …
> Update project root documentations reflecting Jenkins shutdown

- .github/workflows/beam_CancelStaleDataflowJobs.yml
- .github/workflows/beam_CleanUpGCPResources.yml
- .github/workflows/beam_CleanUpPrebuiltSDKImages.yml
- .test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh
https://github.com/apache/beam/actions/workflows/beam_CleanUpPrebuiltSDKImages.yml?page=3 has been failing since Nov 16th. The reason is that the multiarch consideration has a call `docker manifest inspect` rejected by some repositories.
While we can extend the permission, it is not necessary to do so as of quick fix. …
> Fix clean up stale container workflow

- website/www/site/content/en/contribute/_index.md
> Add info on getting started contributing

- sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcpOptions.java
> Respect gcloud active configuration, if any, rather than always using default.

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSampler.java
Cherry pick of #29979 to fix #29987 in 2.54.0 …
> [Cherry Pick #29979] Fix race condition in Dataflow sampler.

- .github/workflows/beam_PostCommit_Java_DataflowV2.yml
beam_PostCommit_Java_DataflowV2 is consistently reaching 4h timing out: https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_DataflowV2.yml?query=event%3Aschedule
Before that, a successful run already took 3h50min. Bumping timeout to 6h and schedule run interval to 8h, as we did for Dataflow runner v2 validation test …
> Bumping timeout for beam_PostCommit_Java_DataflowV2

- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/join/CoGbkResult.java
Move test for Reiterator in CoGbkResult outside of loop. …
> [sdks-java-core] Test for Reiterator outside loop in CoGbkResult

- website/Dockerfile
This was preventing local website development. 
I tried to fix this in the build file, but it got really messy (and I wasn't able to get it to work), so this seemed simpler.  …
> Fix git trusted directory errors in website build.

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java
Fixes #30159
Unless we fully understand the limitation this kind of proactive restriction has chance to breaking existing use case. …
> Remove constraint introduced in #30059

- sdks/java/extensions/protobuf/build.gradle
- sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteUtils.java
- sdks/java/extensions/protobuf/src/test/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteUtilsTest.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteReadSchemaTransformProvider.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteWriteSchemaTransformProvider.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/PubsubLiteDlqTest.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsublite/internal/PubsubLiteWriteDlqTest.java
- sdks/python/apache_beam/yaml/standard_io.yaml
> [YAML] - PubSubLite proto

- sdks/python/apache_beam/io/gcp/gcsio.py
This smooths the code path of feeding output of list_prefix() to delete_batch().
fixes #30166 …
> gcsio: Support dict as the input of delete_batch

- contributor-docs/release-guide.md
* Missing $ in bash var definition.
* Copypasta between the Java and Python loops. …
> Fix script typos for validating docker licenses.

- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowPipelineDebugOptions.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
Add a config to use multiple commit threads
> [Dataflow Streaming] Add a config to use multiple commit threads

- sdks/python/apache_beam/io/gcp/bigquery.py
Cherry pick #30156 into 2.54.0 release branch. …
> [Cherry pick #30156 into 2.54.0] Make ReadFromBigQueryRequest id more randomized

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java
Cherry pick #30148 into 2.54.0 release branch. …
> [Cherry pick #30148 into 2.54.0] Marks failed bit as volatile since multiple threads read and write it.

- sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOAutoPartitioningIT.java
[CherryPick #30179] Fix JdbcIO PreCommit mysql breaking change into the 2.54.0 release branch. …
> [CherryPick #30179] Fix JdbcIO PreCommit mysql breaking change

- runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReader.java
Added a default watermark emit interval in FlinkUnboundedSourceReader.
addresses #30125  …
> Adding a default watermark emit interval for FlinkUnboundedSourceReader

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkState.java
Cherry pick #30229 into the 2.54.0 release branch. …
> [CherryPick #30229] [Dataflow Streaming] Invalidate caches and remove work on failure before commit

- runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/SplittableParDo.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java
- sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/BeamZetaSqlCalcRel.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java
- sdks/java/io/pulsar/src/test/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFnTest.java
- sdks/java/io/sparkreceiver/2/src/test/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFnTest.java
Fix (on main branch) #30203
* Revert changes of override method that simply throw UnsupportedOperationException in subclasses …
> Add Default method for OutputReceiver.outputWindowedValue

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowBatchWorkerHarness.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowWorkerHarnessHelper.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WorkerPipelineOptionsFactory.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowWorkerHarnessHelperTest.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkerPipelineOptionsFactoryTest.java
Prior to this fix options in StreamingDataflowWorkerOptions were not taking effect when passed via cli
> Fix to take StreamingDataflowWorkerOptions from external options

- sdks/python/apache_beam/io/gcp/gcsio.py
Cherry Pick #30188 into the 2.54.0 release branch. …
> [Cherry Pick #30188] gcsio: support dict as the input of delete_batch

- .github/workflows/beam_PostCommit_TransformService_Direct.yml
> Fix a naming conflict of the TransformService test suite

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkState.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ComputationState.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkStateTest.java
Add support for current active work budget.
This will be used by direct path to pass to the `GetWorkBudgetDistributor`.
r: @scwhittle  …
> Add support for current active work budget.

- sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
Doc comment exported ErrCancel. …
> [lint] Doc comment exported ErrCancel.

- sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java
- sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcUtil.java
- sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcWriteSchemaTransformProvider.java
- sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProviderTest.java
- sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcWriteSchemaTransformProviderTest.java
- sdks/python/apache_beam/yaml/standard_io.yaml
- sdks/python/apache_beam/yaml/yaml_transform.py
PR adds ability to specify a JDBC type/flavor to the `ReadFromJdbc` and `WriteToJdbc` Beam YAML transforms.
[![Build …
> [YAML] Add ability to specify JDBC type to read/write

- sdks/python/apache_beam/testing/analyzers/perf_analysis_test.py
> Fix change point analysis unit test

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContext.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/counters/NameContext.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/StageInfo.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionContextTest.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContextTest.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSourcesTest.java
StreamingDataflowWorker was being passed into StreamingModeExecutionContext but not being referenced and every test was passing in a null value.
Remove it to clean up code.
R: @scwhittle  …
> Remove unused parameter

- sdks/python/apache_beam/io/fileio.py
No need to keep apache_beam.io.fileio.WriteToFiles experimental. …
> Remove WriteToFiles is experimental.

- sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java
- sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java
This fixes https://github.com/apache/beam/issues/30263. …
> Fixes a bug related to upgrading Kafka read transforms using the Transform Service

- examples/notebooks/beam-ml/bigtable_enrichment_transform.ipynb
Adds a notebook for bigtable-enrichment-transform. …
> Add example notebook for bigtable enrichment

- learning/prompts/documentation-lookup/29_advanced_side_inputs.md
- learning/prompts/documentation-lookup/30_advanced_additional_outputs.md
- learning/prompts/documentation-lookup/31_advanced_batched_dofn.md
- Side inputs
- Additional outputs
- Batched DoFn …
> Duet AI advanced DoFn documentation lookup prompts

- sdks/java/extensions/arrow/build.gradle
- sdks/java/io/google-cloud-platform/build.gradle
> Exclude slf4j 2.x for arrow dependency

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/container/license_scripts/dep_urls_java.yaml
Updatte to libraries-bom 26.32.0 …
> Update to libraries-bom 26.32.0

- website/www/site/content/en/documentation/pipelines/test-your-pipeline.md
The spurious extra "-" between "debugging" and "failed" drastically changes the grammar of the sentence and makes it hard to parse. …
> Remove a single "-" from test-your-pipeline.md

- sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteUtils.java
> [YAML] - Pick file descriptor based on messageName

- .github/workflows/beam_PostCommit_Java_DataflowV1.yml
> Bump PostCommit Java DataflowV1 timeout to 6h

- sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java
- sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOTest.java
Runner best effort deduplication will be conducted if set
```
JmsIO.read().withRequiresDeduping()
``` …
> Introduce JmsIO.Read.requiresDeduping

- sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSource.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/io/CompressedSourceTest.java
Log the error that contains the resource id could help users identify which file could cause issues.   …
> Log the resource id when IOException happens in FileBasedSource

- .github/workflows/beam_PostCommit_Java_PVR_Spark3_Streaming.yml
This test runs >1h50min https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_PVR_Spark3_Streaming.yml?query=event%3Aschedule
found when doing #30354 …
> Bump timeout of PostCommit Java PVR Spark3 Streaming to 3h

- .test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh
This is repeatedly failing - https://github.com/apache/beam/actions/runs/7992925962 - and this should fix it.
[![Build …
> Add some tolerance for skippped images in cleaner

- sdks/python/apache_beam/pvalue.py
https://beam.apache.org/releases/pydoc/current/apache_beam.pvalue.html does not mention  `AsMultiMap`. I suspect it is because it is not part of `__all__`. …
> Also export AsMultiMap view.

- CHANGES.md
> add bqio changes to CHANGES.md

- .test-infra/metrics/grafana/provisioning/alerts/flaky_test.yaml
- .test-infra/metrics/grafana/provisioning/datasources/beampostgresql.yaml
Adds a grafana alert that will trigger when number of failed runs is bigger than threshold value. 
Also adds a UID to BeamPSQL datasource as its required by the alert provisioning API …
> Grafana flaky test alert

- sdks/java/extensions/google-cloud-platform-core/build.gradle
- sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtilIT.java
The gRPC feature is an experimental feature from GCS. As it is approaching GA, we need to add some basic test to make sure it works with Beam.
The test will be invoked from a post commit test github action: https://github.com/apache/beam/blob/e6cc0809646da44b5621b3772704d645b79d8253/.github/workflows/beam_PostCommit_Java.yml#L80
`:JavePostCommit` (defined in `build.gradle.tks`)
-> `:sdks:java:extensions:google-cloud-platform-core:postCommit` (defined in `sdks/java/extensions/google-cloud-platform-core/build.gradle`)
-> `:sdks:java:extensions:google-cloud-platform-core:integrationTestKms`
-> `sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtilIT.java` …
> Add a test to read and write GCS with gRPC enabled.

- .github/flaky_test_detection.py
- .github/workflows/flaky_test_detection.yml
- .test-infra/tools/flaky_test_detection.py
Python scripts that will fetch all the firing alerts and create an issue for the failing workflows if it does not exist yet. 
Also adds the github workflow that will call the script. 
@damccorm It is set to read only for now and its only on dispatch. Once we are ready we can set the schedule trigger
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob …
> Flaky test issue script

- website/www/site/content/en/documentation/sdks/yaml-inline-python.md
> Restore yaml inline python page.

- website/www/site/content/en/documentation/sdks/yaml.md
> [YAML] Add note about running yaml pipelines directly via gcloud.

- website/www/site/content/en/documentation/sdks/yaml.md
> [YAML] Delete redundant (and now broken) links at bottom of main yaml page.

- website/www/site/static/.htaccess
Attempt to fix: #30394
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/30391/index.html …
> Allow frame references to Beam Playground.

- website/www/site/layouts/index.html
Staged URL:  http://apache-beam-website-pull-requests.storage.googleapis.com/30408/index.html
> Remove the CSP-blocked iframes pointing outside of apache.org

- sdks/python/apache_beam/yaml/yaml_mapping.py
MapToFields error_handling output would infer the original payload "element" to be of type `Any` which would break use-cases that redirect error output to a Java transform using Xlang.
This PR passes the original type of the payload so that the typehints can be properly set.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD …
> [YAML] Fix MapToFields error output type inference

- website/www/site/content/en/blog/beam-2.54.0.md
> Update beam-2.54.0.md about v2 default.

- sdks/java/extensions/ml/build.gradle
> Use BeamModulePlugin org.json version in extensions/ml

- sdks/python/apache_beam/io/gcp/bigquery.py
Removes a stray escape sequence that causes pytest to fail.  
Addresses https://github.com/apache/beam/issues/30392 …
> Fix invalid escape sequence '\#'

- sdks/python/tox.ini
We're running into the same issue as https://github.com/NVIDIA/TensorRT-LLM/issues/1145 causing the python precommit to fail - https://github.com/apache/beam/actions/workflows/beam_PreCommit_Python_Coverage.yml?query=event%3Aschedule - this is an attempt to fix the problem …
> Force downgrade mpmath to avoid test breakages

- sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Monitoring.java
This PR fixes the Monitoring configuration Builder's method by making it public. …
> Make Monitoring build method public

- website/www/site/content/en/documentation/sdks/yaml.md
> [yaml] fix providers doc

- website/www/site/content/en/documentation/sdks/python-pipeline-dependencies.md
Minor update for guidelines on managing Python dependencies to better reflect when various options should be used.
> Revise documentation on managing dependencies.

- .test-infra/tools/flaky_test_detection.py
Make the `flaky_test_detection.py` script read only by default …
> Make the flaky_test_detection script read only by default

- sdks/go/test/integration/integration.go
Filter out TestTestStreamInt16Sequence from flink VR tests, to fix same. …
> [Go SDK] filter out TestTestStreamInt16Sequence from flink VR tests.

- sdks/python/apache_beam/io/gcp/bigquery_tools_test.py
The test was somehow skipped during the recent gcsio migration. I verified it is working locally so I am putting it back.
(internal bug id: 302004313) …
> Unskip test_user_agent_insert_all

- .github/workflows/update_python_dependencies.yml
See https://github.com/apache/beam/pull/30470 for context …
> Add instructions on reviewing Python version updates

- .github/workflows/beam_MetricsCredentialsRotation.yml
Right now this is failing on its first try because its running into conflicts with another operation, I'm guessing from a fork. This _should_ fix the problem by moving the workflow trigger time to earlier and it will hopefully help avoid forks doing this in the future once they are updated.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/. …
> Move credential rotation and gate on beam repo

- learning/prompts/documentation-lookup-nolinks/50_beam_yaml.md
Adding a prompt about Beam YAML. …
> Duet AI Prompt - Beam YAML (no links)

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/go/run_with_go_version.sh
Use the latest security release for Go v1.21.8.
Not bumping to Go v1.22 series at this time. …
> Update Go Version for artifacts to Go v1.21.8

- sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java
> Expose JmsIO read receive timeout

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslator.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslatorTest.java
Provide a way to override random BigtableDataSettings for debugging / testing purpose. This gives us the flexibility to test random configurations without adding a new API to the Bigtable connector surface. And would be helpful when tuning customer cases to override the settings directly on BigtableDataSettings.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apa …
> Bigtable: provide a way to override BigtableDataSettings

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslator.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableConfigTranslatorTest.java
Switch the dynamic loading of the override class to use InstanceBuilder to match the rest of beam.  …
> Bigtable: use InstanceBuilder to dynamic load override class

- runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/BeamAdapterUtils.java
- runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/BeamFlinkDataSetAdapter.java
- runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/FlinkInput.java
- runners/flink/src/main/java/org/apache/beam/runners/flink/adapter/FlinkOutput.java
> Reduce nullness checks in flink adapters.

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
This PR addresses #30379 by adding the Vertex AI dependency. This is needed for future example. …
> Add vertex AI dependency

- examples/notebooks/beam-ml/run_inference_gemma.ipynb
Adds a notebook example to run a Beam pipeline with RunInference and a Gemma open model locally. …
> Add local Run Inference with Gemma notebook

- sdks/java/core/src/main/java/org/apache/beam/sdk/util/construction/TransformUpgrader.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/util/construction/TransformUpgraderTest.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java
This fixes https://github.com/apache/beam/issues/30534. …
> Fixes an upgrade imcompatiblity of BQ read/write transforms

- sdks/python/apache_beam/io/gcp/bigquery_tools_test.py
PR #30455 has caused some internal test failure. We are going to skip the test if BigQueryWrapper cannot be imported.
(Internal bug id: 302004313) …
> Fix internal test failure from PR-30455

- .github/workflows/beam_PostCommit_Java_InfluxDbIO_IT.yml
Fix https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_InfluxDbIO_IT.yml
Manually kicked off run https://github.com/apache/beam/actions/runs/8193866554/job/22408577737 passed "Install InfluxDB" step
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BU …
> Bump InfluxDB PostCommit timeout

- sdks/python/test-suites/containers/tensorrt_runinference/tensor_rt.dockerfile
Fix Python PostCommit tensorrttest …
> Do not pre-install beam in tensorrt container

- sdks/java/core/src/main/java/org/apache/beam/sdk/util/construction/TransformUpgrader.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/util/construction/TransformUpgraderTest.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java
Fixes #30534
Will wait until PostCommit https://github.com/apache/beam/actions/runs/8193778498 and https://github.com/apache/beam/actions/runs/8193799778 done …
> [Release-2.55] Cherry-pick #30551 into release branch

- runners/google-cloud-dataflow-java/examples/build.gradle
Fix Java Dataflow PreCommit on release branch
[![Build …
> [release-2.55.0] Cherypick #30574 into release branch

- .github/workflows/beam_PostCommit_Java_InfluxDbIO_IT.yml
Fixes InfluxDB PostCommit on release breanch
[![Build …
> [release-2.55.0] Cherrypick #30561 into release branch

- sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
Fixes PostCommit_XVR_Direct on release branch
[![Build …
> [Release-2.55.0] Cherrypick #30568 into release branch

- learning/prompts/documentation-lookup-nolinks/48_sdk_harness.md
- learning/prompts/documentation-lookup-nolinks/49_transform_service.md
- learning/prompts/documentation-lookup/48_sdk_harness.md
- learning/prompts/documentation-lookup/49_transform_service.md
Transform service lookup prompts …
> Duet AI Transform service SDK Harness prompts

- website/www/site/content/en/community/youtube-channel.md
- website/www/site/content/en/documentation/ml/overview.md
Fixes https://github.com/apache/beam/issues/30590 
https://privacy.apache.org/policies/website-policy.html seems to suggest some specific policies around Youtube embeddings, but given link problems on https://privacy.apache.org/examples/youtube-html/with-youtube-api.html, I propose we remove them for now. …
> Remove Youtube Embeddings from Website

- settings.gradle.kts
Fix https://issues.apache.org/jira/browse/INFRA-25595
See https://github.com/apache/beam/issues/30534#issuecomment-1986090586 and comments below for context …
> Disable remote gradle cache until it is cleaned

- settings.gradle.kts
* Disable remote gradle cache until it is cleaned
* trigger test …
> [Release-2.55.0] Cherry-pick #30584 into release branch

- runners/spark/spark_runner.gradle
This test was excluded in #30030. However, the change was later reverted in https://github.com/apache/beam/commit/f73ce82fb37c62aac66fb1d06e941932faa0982a#diff-005880cee144b69c4a7a7ff12b65497a75a41011570c1585fc9eced3e2c73323 likely unintended rebase error …
> Redo spark_runner exclude test

- runners/spark/spark_runner.gradle
Fix beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming on release branch …
> [Release-2.55.0] Cherry-pick #30589 into release branch

- .github/REVIEWERS.yml
> Remove Anand, add Shunping to reviewers

- contributor-docs/release-guide.md
CHANGES.md tends to stay up to date better than our blog posts …
> Update blog template with known issues link to CHANGES

- CHANGES.md
> Add a known issue for gcsio in the notes of 2.53.0 and 2.54.0.

- website/www/site/assets/js/sliders/top-banners.js
- website/www/site/layouts/partials/header.html
This PR closes #30599 by replacing website banner auto transition with user controlled navigation. Additionally, removes outdated announcement. …
> [website] Replace website banner auto transition with navigation

- sdks/java/io/google-cloud-platform/build.gradle
> Add hamcrest as an implementation dependency

- sdks/java/io/google-cloud-platform/build.gradle
> [Release-2.55] Cherrypick #30635 into release branch

- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowStreamingPipelineOptions.java
to manage rolling out of direct path
will not work if:
- direct path is not enabled in streaming backend
- VMs setting this flag are not using IPv6 …
> add flag for direct path that reads from system properties

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillBag.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillValue.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillWatermarkHold.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternalsTest.java
* Update WindmillBag.java
Include byte size of the stateKey on the BagState weight used to estimate and limit the total state cache size
* Update WindmillValue.java
Include stateKey size in the byte size of a WidnmillValue
* Update WindmillWatermarkHold.java
Include keyState size in the WatermarkHold estimated byte size
* Fix formatting issue
* Fix expected cache item weights in WindmillStateInternalsTest
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-re …
> [Release-2.55] Cherry pick  #30654 into release branch

- sdks/python/apache_beam/io/gcp/bigquery.py
Following https://stackoverflow.com/questions/67441316/attributeerror-runtimevalueprovider-object-has-no-attribute-projectid, we need to support  ValueProvider for _CustomBigQueryStorageSource …
> Support ValueProvider for _CustomBigQueryStorageSource

- .github/trigger_files/beam_PostCommit_XVR_PythonUsingJavaSQL_Dataflow.json
- settings.gradle.kts
This reverts commit a3ea9ef706cf798fc1f6b026dcdf7171434e74d8. …
> Revert "Disable remote gradle cache until it is cleaned (#30584)"

- sdks/python/apache_beam/runners/portability/samza_runner_test.py
- sdks/python/apache_beam/runners/portability/spark_runner_test.py
This should fix https://github.com/apache/beam/issues/30657 and https://github.com/apache/beam/issues/30645
[![Build …
> Disable unsupported custom window type test on samza and spark.

- .github/workflows/beam_PostCommit_Java_BigQueryEarlyRollout.yml
This should be actioned on immediately, so we'll send an email to do so. …
> Send email when BQ early rollout workflow fails

- it/google-cloud-platform/build.gradle
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/IOLoadTestBase.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/IOStressTestBase.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOST.java
- it/kafka/build.gradle
- it/kafka/src/test/java/org/apache/beam/it/kafka/KafkaIOST.java
- sdks/java/build-tools/src/main/resources/beam/checkstyle/suppressions.xml
This pull request introduces stress tests for BigTableIO, designed to assess the performance under various conditions. The stress tests simulate dynamic load increases and evaluate the behavior of BigTableIO.
Changes:
- Added stress tests for BigTableIO.
- Implemented dynamic load increases over time to simulate varying workloads.
- Added support for exporting metrics to InfluxDB or BigQuery based on the configuration parameter.
- Added ability for user to configure Dataflow version in KafkaIO Stress test
- Refactored the code of BigQueryIO and KafkaIO stress tests.
[Writing job example](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-03-14_01_04_09-6829471925970253865;step=Write%20to%20BigTable;mainTab=JOB_GRAPH;bottomTab=WORKER_LOGS;logsSeverity=WARNING;graphView=0?projec …
> Add BigTableIO Stress test

- sdks/python/apache_beam/runners/worker/sdk_worker.py
> Add warning when retrieving state cache inefficiency detected

- learning/prompts/code-explanation/java/07_io_json.md
- learning/prompts/code-explanation/java/08_io_csv.md
- learning/prompts/code-explanation/java/09_io_avro.md
- learning/prompts/code-explanation/java/10_io_parquet.md
- learning/prompts/code-generation/java/07_io_json.md
- learning/prompts/code-generation/java/08_io_csv.md
- learning/prompts/code-generation/java/09_io_avro.md
- learning/prompts/code-generation/java/10_io_parquet.md
Duet AI prompts for:
CSV
JSON
Parquet
Avro …
> Duet AI code-explanation and code-generation prompts basic

- CHANGES.md
- sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
- sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
This reverts commit 1c55117fc3349508edf8af07b1b361313c4b8a33.
This commit has been associated with failures related to data sampling in Dataflow.
- N/A internal: ~Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.~
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier …
> Revert #30533: Automatically execute unbounded pipelines in streaming mode.

- sdks/python/apache_beam/yaml/yaml_combine.py
- sdks/python/apache_beam/yaml/yaml_mapping.py
- sdks/python/apache_beam/yaml/yaml_provider.py
We have comprehensive documentation for these; this change adds pointers to it from the transform catalogue.
[![Build …
> [YAML] Add simple description and doc reference for several transforms.

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
This PR addresses #30447 by adding a random segment to the object path for validation tests. Failures such as https://github.com/apache/beam/actions/runs/8393376940/job/22988190113#step:5:34459 may result from tests sharing the same Google Cloud Storage Object path. …
> Randomize object path for validation tasks

- .github/workflows/beam_PreCommit_Python_Coverage.yml
Revert to v3 because v4 has issues with tokenless …
> revert codecov action to v3

- CHANGES.md
- website/www/site/config.toml
- website/www/site/content/en/blog/beam-2.55.0.md
- website/www/site/content/en/get-started/downloads.md
> Beam 2.55.0 website updates

- examples/notebooks/beam-ml/bigtable_enrichment_transform.ipynb
Update links pointing to `ExceptionLevel` since it is now moved to utils. (Rest of the changes may have auto triggered because I edited the notebook in VS Code directly. It loads fine - [link](https://github.com/riteshghorse/beam/blob/correct-link/examples/notebooks/beam-ml/bigtable_enrichment_transform.ipynb)) 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apa …
> Update documentation link in bigtable_enrichment notebook

- playground/backend/build.gradle.kts
- playground/backend/containers/java/Dockerfile
> Fix playground build for Beam 2.55.0 change

- website/www/site/content/en/get-started/downloads.md
> Fix typo in download webpage 2.55.0

- .test-infra/metrics/grafana/provisioning/alerting/flaky_test.yaml
- .test-infra/metrics/sync/github/github_runs_prefetcher/code/main.py
- .test-infra/tools/flaky_test_detection.py
This PR is fixing the gap between `flaky_test_detection` and `workflow_prefetcher` scripts: due to different startup times there is a gap where `workflow_prefetcher` fetches data from the API and an issue is open, then someone closes the issue and then `flaky_test_detection` runs. …
> Fix the gap between flaky_test_detection and workflow_prefetcher scripts

- sdks/python/apache_beam/pipeline.py
- sdks/python/apache_beam/runners/common.py
- sdks/python/apache_beam/runners/common_test.py
- sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
- sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
This can be especially useful for those pipelines with many cross-language transforms. …
> Deduplicate common environments.

- examples/notebooks/beam-ml/run_inference_gemma.ipynb
- examples/notebooks/beam-ml/vertex_ai_feature_store_enrichment.ipynb
Copy editing two notebooks to prepare to import them to DevSite:
* Vertex AI Feature Store enrichment transform
* RunInference with Gemma …
> Copy editing ML notebooks for DevSite import

- website/www/site/content/en/documentation/sdks/yaml.md
- website/www/site/layouts/partials/section-menu/en/sdks.html
> Add link to official reference on beam site.

- examples/notebooks/beam-ml/bigtable_enrichment_transform.ipynb
Clearly explain and demonstrate the use of enrichment transform for `BigTableEnrichmentHandler`. …
> [Docs] Update Bigtable enrichment notebook

- .github/codecov.yml
- .github/workflows/beam_PreCommit_Java.yml
- .github/workflows/beam_PreCommit_Java_GCP_IO_Direct.yml
- .github/workflows/beam_PreCommit_SQL.yml
- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
> Fix JaCoCo test report

- .github/workflows/build_release_candidate.yml
- release/src/main/scripts/build_release_candidate.sh
- sdks/python/build.gradle
> Gradle target and script for adding YAML reference manual to site.

- .github/workflows/beam_PreCommit_Java.yml
- .github/workflows/beam_PreCommit_Java_GCP_IO_Direct.yml
- .github/workflows/beam_PreCommit_SQL.yml
Changed the version of the Codecov plugin to v3, as it works without a token. …
> Change version of Codecov plugin

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutor.java
> [Dataflow Streaming] Add workToken to thread name for easier debugging

- sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/DynamicProtoCoder.java
- sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoCoder.java
> Make GetParser method synchronized, to prevent multiple threads from accessing memoizedParser at the same time

- sdks/python/apache_beam/runners/dataflow/internal/names.py
Released new containers after #30677. This PR updates the tag for the dev containers. …
> [Python] Update dev SDK container tag for Python SDK

- .github/workflows/beam_PostCommit_Java_IO_Performance_Tests.yml
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryStreamingLT.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOLT.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/storage/FileBasedIOLT.java
Fixes:
- Uses new google auth action for authenticating gcloud
- get the latest beam release version, this will fix workflow not working as some actions were not availiable in hardcoded beam release - should close #28330 
The test is still failing due to bigtable issues. This only fixes workflow issues …
> add get beam latest release and fix GCP auth

- learning/tour-of-beam/learning-content/core-transforms/side-inputs/description.md
Change `pvalue.AsIteor(pcoll)` to `pvalue.AsIter(pcoll)`. …
> Fix typo in side-inputs `README.md`

- sdks/python/apache_beam/transforms/display.py
> Don't double-nest display data payloads.

- learning/prompts/code-explanation/java/02_io_pubsub.md
- learning/prompts/code-explanation/java/03_io_bigquery.md
- learning/prompts/code-explanation/java/04_io_bigtable.md
- learning/prompts/code-explanation/java/05_io_spanner.md
- learning/prompts/code-generation/java/02_io_pubsub.md
- learning/prompts/code-generation/java/03_io_bigquery.md
- learning/prompts/code-generation/java/04_io_bigtable.md
- learning/prompts/code-generation/java/05_io_spanner.md
Duet ai code prompts  for gcloud services:
PubSub
BigQuery
BigTable
Spanner …
> Duet ai code prompts  for gcloud services

- learning/prompts/code-explanation/java/01_io_kafka.md
- learning/prompts/code-explanation/java/06_io_tfrecord.md
- learning/prompts/code-explanation/java/11_io_jdbc.md
- learning/prompts/code-generation/java/01_io_kafka.md
- learning/prompts/code-generation/java/06_io_tfrecord.md
- learning/prompts/code-generation/java/11_io_jdbc.md
Added Duet AI code prompts:
Kafka,
TFRecord
JDBC …
> Duet AI code prompts final

- sdks/java/extensions/schemaio-expansion-service/build.gradle
> Include everit_json_schema in schemaio expansion service uber jar (#30779)

- sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
- sdks/python/apache_beam/transforms/util.py
- sdks/python/apache_beam/transforms/util_test.py
This effect has always been possibly by explicitly using side inputs, but that is far from obvious. …
> Add WaitOn transform to Python, analogous to Java's Wait.on.

- .asf.yaml
> Protect 2.55.1 branch

- sdks/go/pkg/beam/runners/prism/internal/web/assets/job-action.js
- sdks/go/pkg/beam/runners/prism/internal/web/assets/style.css
- sdks/go/pkg/beam/runners/prism/internal/web/jobdetails.html
This PR closes #30810 adding a cancel button to the Prism UI. See issue description for expected behavior. Currently clicking the button only console.debug's out. A future PR will implement sending the cancel request to the backend. …
> Add cancel button to Prism UI

- contributor-docs/release-guide.md
Add documentation on performing a patch release …
> Add patch release docs

- .github/trigger_files/beam_PostCommit_Java_Avro_Versions.json
- CHANGES.md
- sdks/java/extensions/avro/build.gradle
After #30638, Beam repo tests no longer exercises with avro 1.8.2. We should add it back as the support for old avro hasn't discontinued yet. …
> Add back Avro 1.8.2 to test

- .github/gh-actions-self-hosted-runners/arc/images/Dockerfile
Update gcloud SDK to 471. 
This is needed to be able to access Autopilot clusters with gcloud CLI …
> update gcloud to 471 in runner image

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
With JDK 21 support https://github.com/raphw/byte-buddy/issues/1396 https://github.com/raphw/byte-buddy/releases
https://github.com/raphw/byte-buddy/compare/byte-buddy-1.12.14..byte-buddy-1.14.12
Without such upgrade, there are some issues running Beam SDK on JDK 21.
Related issues https://github.com/apache/beam/issues/21524 https://issues.apache.org/jira/browse/BEAM-12241 https://issues.apache.org/jira/browse/BEAM-14065
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTIN …
> byte-buddy:1.14.12

- sdks/python/apache_beam/runners/portability/expansion_service.py
The cli-invoking variant already parses and passes these in manually. Internal uses should not automatically pick up `sys.argv`. …
> Use empty flags for default expansion service options.

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowWorkUnitClient.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WorkUnitClient.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingWorkerStatusReporter.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutor.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowWorkUnitClientTest.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingWorkerStatusReporterTest.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutorTest.java
Workers will read the StreamignScalingReportResponse from worker messages and configure the executor pool size based on the specified value.
R: @scwhittle  …
> Tune maximum thread count for streaming dataflow worker executor dynamically.

- website/www/site/content/en/documentation/sdks/yaml.md
Makes the following changes
- Organize into several main sections
- Make the "Getting Started" section more procedural. 
- Use a self-contained pipeline for Getting Started. (No input data files required)
- Add explanatory text to motivate the example YAMLs
- General style edits …
> Proposed edits for Beam YAML overview

- sdks/python/setup.py
- sdks/python/tox.ini
> Adds a bound on pydantic to exclude incompatible versions in the compat test.

- CHANGES.md
- website/www/site/config.toml
- website/www/site/content/en/get-started/downloads.md
> Patch release website changes

- examples/notebooks/get-started/try-apache-beam-yaml.ipynb
- sdks/python/apache_beam/yaml/examples/README.md
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_count_minimal.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_max_minimal.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_mean_minimal.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_min_minimal.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_multiple_aggregations.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_sum.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_sum_minimal.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/group_into_batches.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/top_largest_per_key.yaml
- sdks/python/apache_beam/yaml/examples/transforms/aggregation/top_smallest_per_key.yaml
- sdks/python/apache_beam/yaml/examples/wordcount_minimal.yaml
- sdks/python/apache_beam/yaml/programming_guide_test.py
- sdks/python/apache_beam/yaml/readme_test.py
- sdks/python/apache_beam/yaml/yaml_combine.py
- sdks/python/apache_beam/yaml/yaml_combine_test.py
- sdks/python/apache_beam/yaml/yaml_transform_test.py
- website/www/site/content/en/documentation/sdks/yaml-combine.md
Removes the need to set `--yaml_experimental_features=Combine` to run aggregations in Beam YAML …
> [yaml] remove Combine from yaml_experimental_features

- sdks/python/apache_beam/yaml/yaml_mapping.py
- sdks/python/apache_beam/yaml/yaml_udf_test.py
- sdks/python/setup.py
js2py is not supported in Python 3.12, so to prevent future issues arising from Beam Python 3.12 support, this js2py import is being excluded for Beam installs starting with Python 3.12 and the feature will throw error if the package does not exist.
Tracked in https://github.com/apache/beam/issues/30829
js2py issues
* https://github.com/PiotrDabkowski/Js2Py/issues/282#issuecomment-1327954348
* https://github.com/PiotrDabkowski/Js2Py/issues/317 …
> [yaml] disable javascript mapping for python >=3.12

- .github/REVIEWERS.yml
> Remove Bruno from reviewer pool

- .github/workflows/beam_LoadTests_Java_PubsubIO.yml
- .github/workflows/beam_StressTests_Java_BigQueryIO.yml
- .github/workflows/beam_StressTests_Java_BigTableIO.yml
- .github/workflows/beam_StressTests_Java_KafkaIO.yml
- .github/workflows/beam_StressTests_Java_SpannerIO.yml
- it/google-cloud-platform/build.gradle
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/IOLoadTestBase.java
- it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/LoadTestBase.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOST.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/pubsub/PubSubIOLT.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/pubsub/PubsubIOLT.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerIOST.java
- it/kafka/build.gradle
- it/kafka/src/test/java/org/apache/beam/it/kafka/KafkaIOST.java
**Changes**:
- Added workflows for the next tests:
- SpannerIO Stress Test
- BigTable Stress Test
- BigQuery Stress Test
- Kafka Stress Test
- Pubsub Load Test
- Fixed exporting metrics to InfluxDB
- Refactoring, other improvements and fixes …
>  Load and Stress Tests: Add workflows, improvements and fixes

- website/www/site/content/en/blog/beam-yaml-release.md
- website/www/site/data/authors.yml
Adds a Beam YAML announcement blog …
> [yaml] Add Beam YAML Blog

- .github/workflows/beam_StressTests_Java_KafkaIO.yml
> Fix cron in github workflow file

- examples/notebooks/get-started/try-apache-beam-yaml.ipynb
This keeps the notebook from rendering because its not valid json.
With my change: https://github.com/apache/beam/blob/3775aa2a4721e6041f81085f77457d6bb9ae074e/examples/notebooks/get-started/try-apache-beam-yaml.ipynb
Without my change: https://github.com/apache/beam/blob/master/examples/notebooks/get-started/try-apache-beam-yaml.ipynb …
> Remove comma that breaks formatting

- website/www/site/content/en/blog/beam-yaml-release.md
Link and formatting fixes for Beam YAML Blog. …
> [yaml] Fix Beam YAML blog links

- .github/workflows/IO_Iceberg.yml
There was an interpolation variable incidentally left in it when I forked from another file. …
> Fixup iceberg GitHub Action workflow

- playground/infrastructure/requirements.txt
- sdks/python/pyproject.toml
Upgrades the pinned version of grpcio-tools to a newer version, which is compatible with Python 3.12.
Fixes https://github.com/apache/beam/issues/30820  …
> Upgrade grpcio-tools.

- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java
- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java
Noticed `KafkaReadSchemaTransformConfiguration.validate()` is never called by `KafkaReadSchemaTransform.from()` …
> Add config validation to kafka read schema transform

- .github/workflows/beam_PreCommit_Whitespace.yml
- it/google-cloud-platform/build.gradle
Lint got broken by https://github.com/apache/beam/pull/30886 , but lint check didn't run on that PR. …
> Fix broken lint and improve lint rules.

- sdks/python/build.gradle
This should resolve https://github.com/apache/beam/issues/30950 from breaking presubmits until we figure out what the issue is.  …
> [BEAM-30950] Disable failing test for now.

- contributor-docs/java-dependency-upgrades.md
> Update java-dependency-guide contributor-doc reflecting gcpbomupgrader script

- .test-infra/metrics/kubernetes/beamgrafana-deploy.yaml
Set creds for beam metrics grafana to read only …
> change grafana creds to use readonly account for beammetrics cloudsql db

- CHANGES.md
- sdks/python/container/piputil.go
This is a follow-up for https://github.com/apache/beam/pull/28317/commits/31119dad62a951a075d532813e92e5d108e044da . …
> Restore pip logs also for requirements.txt case

- .github/workflows/build_wheels.yml
This is due to https://github.com/pypa/setuptools/issues/4300 …
> Fix build wheels due to setuptools changed naming

- .github/workflows/beam_PostCommit_XVR_PythonUsingJavaSQL_Dataflow.yml
- .github/workflows/beam_PostCommit_XVR_PythonUsingJava_Dataflow.yml
Removes CLOUDSDK env variable which is not needed and causes issues with the new gcloud sdk versions  …
> remove CLOUDSDK env variable , not needed here

- sdks/python/scripts/generate_pydoc.sh
There's no value to generating docs for these, and the auto-generated names are causing warnings. …
> Skip generating docs for yaml/integration_tests.py.

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GetWorkTimingInfosTracker.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java
- remove spammy log
- use service provided timestamps when scaling
fixes #29028 …
> Improvements to GetWorkTimingInfosTracker when there is clock skew between the worker and service.

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSampler.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateSamplerTest.java
Also ensure that the result is not modified by observing it. Previously we were merging into completed with each observation which appeared unintended.
Fixes #30643 …
> Fix ConcurrentModification exception possible in DataflowExecutionStateSampler

- .github/workflows/beam_PreCommit_Java_Kafka_IO_Direct.yml
- .github/workflows/beam_PreCommit_Yaml_Xlang_Direct.yml
* Add :sdks:java:io:kafka:upgrade:build to KafkaIO PreCommit
* Correct naming of Yaml PreCommit …
> Follow up of recent GHA breakages

- sdks/python/apache_beam/runners/common.py
Instead rely on the higher-level cache which utilizes the side input cache tokens allowing the runner to determine the caching used for side inputs. …
> Remove caching of global window side input param when invoking.

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/RemoveSafeDeltaCounterCell.java
This is a minor optimization for incrementing the new `PerWorkerCounters`. 
The benefits of this PR are detailed below:
- Some quick load tests show that this makes incrementing counter metrics 25% faster.
- Compute blocks a portion of the ConcurrentHashMap while executing [src](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#compute-K-java.util.function.BiFunction-).  …
> Skip calling Compute in RemoveSafeDeltaCounterCell if value exists

- .github/workflows/dask_runner_tests.yml
- .github/workflows/python_tests.yml
Follow #30972 to fix other cases
Fix #31006 and #30528 …
> fix naming changes caused by setuptools

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverter.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverterTest.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
Cache parsed metrics in StreamingStepMetricsContainer since this is a non-trivial amount of work.
We will cache parsed names for both PerWorkerCounters and PerWorkerHistograms.
- Parsed Histogram names will always stay in the cache.
- Parsed Counter names will be removed from the cache if a stale counter gets removed from PerWorkerCounters
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATU …
> Cache parsed metrics in StreamingStepMetricsContainer

- sdks/go/pkg/beam/runners/prism/internal/web/web.go
This PR addresses #30810 adding a /job/cancel endpoint to the prism web server. This endpoint will receive calls from the UI's cancel action (#30811). It simply routes the HTTP post to the backend gRPC job management service, avoiding the need to configure CORS because the UI request would have the same origin.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apac …
> Add /job/cancel endpoint to prism web server.

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetrics.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySinkMetricsTest.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StreamingInsertsMetricsTest.java
Use base 2 exponential histograms in BigQuerySinkMetrics. This shows better performance on load tests either because the bucket index computation is faster or because there are fewer buckets to send to DFE. …
> Use base 2 exponential histograms in BigQuerySinkMetrics

- CHANGES.md
> [changes] Update CHANGES.md (#29939)

- CHANGES.md
> [changes] Update CHANGES.md (#29939) (#31017)

- .github/workflows/beam_PostCommit_XVR_JavaUsingPython_Dataflow.yml
CLOUDSDK env not needed here and is causing issues …
> remove CLOUDSDK from javausingpython dataflow xvr workflow

- website/www/site/static/.htaccess
Partially address https://github.com/apache/beam/issues/30981 …
> Allow IFrames to youtube.

- .test-infra/metrics/README.md
- .test-infra/metrics/sync/github/github_runs_prefetcher/code/main.py
Adds readme trace of the user used and the requirement to grant permissions on new tables
Also adds grant call for the kubeproxyuser_ro user in the prefetcher script …
> add new user info to metrics Readme

- sdks/python/apache_beam/runners/common.pxd
- sdks/python/apache_beam/runners/common.py
* Change caching of global window inputs to be guarded by experiment disable_global_windowed_args_caching
[![Build …
> CP #31013: Change caching of global window inputs to be guarded by experiment

- sdks/python/apache_beam/io/gcp/bigquery.py
* add missing closing parenthesis
* add unique names to PTransform operations …
> Clean doc related to write data in bigquery.py

- .github/trigger_files/beam_PostCommit_Java_Tpcds_Flink.json
- .github/workflows/beam_PostCommit_Java_Tpcds_Flink.yml
Fix https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_Tpcds_Flink.yml?query=event%3Aschedule broken after removing Flink 1.12, 1.13 suport …
> Bump TPCDS test Flink version

- website/www/site/static/.htaccess
Addresses missing `www` from https://github.com/apache/beam/pull/31021 …
> fix url for content security

- sdks/python/apache_beam/runners/dataflow/internal/names.py
> Updates Python Dev container used by Dataflow

- sdks/python/apache_beam/ml/transforms/tft.py
Small typo fix for a helper function  …
> Fix typo in count_unique_words()

- sdks/python/container/py310/base_image_requirements.txt
- sdks/python/container/py311/base_image_requirements.txt
- sdks/python/container/py38/base_image_requirements.txt
- sdks/python/container/py39/base_image_requirements.txt
- sdks/python/setup.py
> Upgrade the version of GRPC to pick up a fix for #30867

- sdks/python/apache_beam/ml/transforms/tft.py
- sdks/python/apache_beam/ml/transforms/tft_test.py
Adds the `scale_to_gaussian` [Tensorflow Transform](https://github.com/tensorflow/transform/blob/fdef5f3fab6dd2dcade260cc80ec229948de448b/tensorflow_transform/mappers.py#L71) to `MLTransform` with accompanying unit tests …
> Add ScaleToGaussian TFTransform

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowBatchWorkerHarness.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/Pipeline.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/util/construction/CoderTranslation.java
- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java
Hopefully this will give enough details to resolve the situation whenever it is encountered. …
> Better and earlier error for #30994.

- website/www/site/content/en/get-started/resources/videos-and-podcasts.md
Fixes https://github.com/apache/beam/issues/30981
Sample rendering: …
> fix website embedding issue 

- website/www/site/content/en/get-started/resources/videos-and-podcasts.md
https://github.com/apache/beam/pull/31019 had 2 broken links. This PR fixes those. …
> fix broken links on website 

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowBatchWorkerHarness.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/Pipeline.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/util/construction/CoderTranslation.java
- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnHarness.java
Hopefully this will give enough details to resolve the situation whenever it is encountered.
This is a cherry-pick of https://github.com/apache/beam/pull/31042 …
> Better and earlier error for missing service loader metadata. (#31042)

- .test-infra/metrics/sync/github/github_runs_prefetcher/code/main.py
Exclude three months old grafana workflow runs from consideration by the flaky test detection tool
Change request: https://github.com/apache/beam/issues/30530#issuecomment-2070524490 …
> Exclude three months old grafana workflow runs

- sdks/java/harness/src/test/java/org/apache/beam/fn/harness/CachesTest.java
Some locales use commas as decimal separators, causing these tests to spuriously fail.  …
> Fix test failure due to locale sensitivity.

- .github/workflows/build_release_candidate.yml
We changed the naming of our python artifacts, and the yaml one never worked.
Example failures: https://github.com/apache/beam/actions/runs/8801284724/job/24154261321 …
> Fix building release candidate

- sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
- sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager_test.go
- sdks/go/pkg/beam/runners/prism/internal/stage.go
Light refactor to how Residuals are handled in the element manager, to prepare for deferring their processing via processing time.
Moves timer triage to it's own method as well to prepare for the additional processing time handling code.
PR doesn't make any behavioral changes, just code moves and restructuring with types.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://gith …
> [#30083][prism] Refactor Residuals to prepare for processing time scheduling.

- sdks/java/core/src/main/java/org/apache/beam/sdk/values/PCollectionViews.java
Using `View#asList()` can be *significantly* more expesnive than `View#asIterable()` as the former creates a distribtued mapping of range(0, N) to the elements, and iterating over it (while respecting this order) requries O(N) non-continguous point lookups.
These counters should be useful in diagnosing performance issues.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://gith …
> Add usage counters to ListView side inputs.

- .github/workflows/deploy_release_candidate_pypi.yaml
One more instance of failing workflows from this …
> Python package string change

- .github/workflows/beam_PerformanceTests_xlang_KafkaIO_Python.yml
Use strimzi kafka for PerformanceTests xlang KafkaIO Python
Fixes #30526 …
> use strimzi kafka on beam_utility cluster

- .github/workflows/java_tests.yml
> Use java 11 for java_tests workflow

- examples/java/twitter/build.gradle
Before:
```
> Task :examples:java:twitter:execute FAILED
Error: Could not find or load main class org.apache.beam.examples.twitterstreamgenerator.TwitterStream
```
after
```
BUILD SUCCESSFUL in 1m 21s
```
the task does not have a dependency. It seems it never worked …
> Fix :examples:java:twitter:execute task

- sdks/python/apache_beam/ml/inference/base.py
- sdks/python/apache_beam/ml/inference/base_test.py
- sdks/python/apache_beam/ml/inference/huggingface_inference.py
- sdks/python/apache_beam/ml/inference/onnx_inference.py
- sdks/python/apache_beam/ml/inference/pytorch_inference.py
- sdks/python/apache_beam/ml/inference/sklearn_inference.py
- sdks/python/apache_beam/ml/inference/tensorflow_inference.py
- sdks/python/apache_beam/ml/inference/tensorrt_inference.py
Cherry pick the ability to load multiple copies of a model across processes. This isn't worth another RC on its own, but if we go to another one (which I think is likely) I'd like to merge it since its a specific customer ask …
> Add ability to load multiple copies of a model across processes (#31052)

- .github/workflows/build_wheels.yml
I'm trying out this fix here - https://github.com/apache/beam/actions/runs/8848815089 …
> Try fixing build wheels

- .github/workflows/build_wheels.yml
This needs cherry-picked since the release branch commits are run against that branch …
> Try fixing build wheels (#31115)

- sdks/python/apache_beam/io/avroio_test.py
fix failing `apache_beam/io/avroio_test.py::TestFastAvro::test_avro_schema_to_beam_schema_
with_nullable_atomic_fields` test. It was failing when using the Flink runner in the `:runners:flink:1.15:job-server:validatesCrossLanguageRunnerPythonUsingSql` gradle task because the Flink runner isn't accessing the local file system when opening files. 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD …
> fix test added in "python sdk: fix several bugs regarding avto <-> beam schema conversion"

- .github/workflows/build_wheels.yml
After https://github.com/apache/beam/pull/31115 the previous step now works, but the following one fails on rc builds trying to download the artifact becuase it looks for macos-latest artifact instead of macos-13 …
> One more macos change

- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Flink.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Samza.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark.json
- model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto
- runners/flink/flink_runner.gradle
- runners/flink/job-server/flink_job_server.gradle
- runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkBatchPortablePipelineTranslator.java
- runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkBatchTransformTranslators.java
- runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkStreamingPortablePipelineTranslator.java
- runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkStreamingTransformTranslators.java
- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java
- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/PropertyNames.java
- runners/samza/src/main/java/org/apache/beam/runners/samza/translation/RedistributeByKeyTranslator.java
- runners/samza/src/main/java/org/apache/beam/runners/samza/translation/ReshuffleTranslator.java
- runners/samza/src/main/java/org/apache/beam/runners/samza/translation/SamzaPipelineTranslator.java
- runners/spark/src/main/java/org/apache/beam/runners/spark/translation/TransformTranslator.java
- runners/spark/src/main/java/org/apache/beam/runners/spark/translation/streaming/StreamingTransformTranslator.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Redistribute.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/util/construction/PTransformTranslation.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/RedistributeTest.java
This initial PR adds Redistribute transform(s) according to:
- [Design doc for Redistribute](https://s.apache.org/beam-redistribute) ([dev@ thread](https://lists.apache.org/thread/rc4tcq7k0950cdgw9lyd0s7vkz8rz5s9))
- [Design doc for Redistribute allowing duplicates](https://s.apache.org/beam-redistribute-allowing-duplicates) ([dev@ thread](https://lists.apache.org/thread/y7zzfc21804lwnwslbhvg6gq7scw2dso))
The various runners were unable to pass the tests without specialized translation, which suggests bugs in their GBK implementation actually. But I just went ahead and implemented specialized translations to match `Reshuffle`.
*Note that the commits in the PR are independent and should not be squashed* …
> Add Redistribute transform to model, Java SDK, and most active runners

- website/www/site/static/.htaccess
> Also allow links to Drive materials.

- .test-infra/kafka/strimzi/02-kafka-persistent/overlays/gke-internal-load-balanced/listeners.yaml
Need to add finalizers as strimzi removes it for some reason preventing LB deletion. 
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#garbage-collecting-load-balancers …
> add finalizers to kafka loadbalancer services

- .test-infra/kafka/strimzi/01-strimzi-operator/kafka.tf
removes wait so it does not time out if the cluster needs time to scale. 
also removes atomic as atomic will set wait to true  …
> remove atomic and wait from strimzi helm terrafrom

- .gitignore
As `pyenv` is recommended for use in [beam's Python's Developer Guide](https://cwiki.apache.org/confluence/display/BEAM/), it makes sense to include `.python-version` in the `.gitignore` file. It makes development with `pyenv` easier by automatically detecting the `venv` in the terminal when entering the beam's directory. Including this file in the `.gitignore` prevents accidental committing of this file. …
> Add `.python-version` to .gitignore

- CHANGES.md
Added in #31052 cherry-picked to release branch in #31104 …
> Add controlling multiple models across processes to CHANGES

- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibility.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibilityTest.java
> Fix spotbug warning in KafkaIO PreCommit

- examples/notebooks/beam-ml/automatic_model_refresh.ipynb
I noticed a different version of tf was getting installed locally and remotely and that was causing the notebook to fail. We should pin to avoid chances of this causing issues. I think leaving tf_hub is fine since it should be configured to work with the installed tensorflow version
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-inf …
> Pin tensorflow version in notebook

- runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslatorTest.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/IsmSideInputReaderTest.java
> Fix ISM-expecting tests by explicilty requisting random access.

- CHANGES.md
Highlight per-worker BigQuery metrics enablement in Changes.md …
> Highlight per-worker BigQuery metrics enablement in Changes.md

- contributor-docs/java-dependency-upgrades.md
Looks like this was a typo - https://github.com/apache/beam/blob/master/scripts/tools/bomupgrader.py …
> Fix bomupgrader naming

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/container/license_scripts/dep_urls_java.yaml
Done with `python scripts/tools/bomupgrader.py 26.38.0` based on https://github.com/apache/beam/blob/master/contributor-docs/java-dependency-upgrades.md
Latest bom is 26.38 - https://mvnrepository.com/artifact/com.google.cloud/libraries-bom …
> Update gcp bom

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToCounterUpdateConverter.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
Add support for int gauge metrics in DataflowRunner …
> Add support for int gauge metrics in DataflowRunner

- website/www/site/content/en/blog/beam-2.55.0.md
- website/www/site/content/en/blog/beam-2.56.0.md
> Fix blog typo

- CHANGES.md
- website/www/site/content/en/blog/beam-2.56.0.md
- website/www/site/content/en/documentation/io/connectors.md
> Adds Managed I/O / Iceberg to 2.56.0 blog and the I/O connectors catalog

- CHANGES.md
- website/www/site/content/en/blog/beam-2.56.0.md
This was missed from changes initially …
> Add ordered processing transform to changes/blog

- sdks/python/apache_beam/ml/inference/vertex_ai_inference.py
Pass the vertex endpoint location explicitly when retrieving it instead of relying on aiplatform.init() to carry that value forward. Avoids an issue where endpoints outside of us-central1 were not being found. …
> Pass location for Vertex endpoint retrieval

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/IsmSideInputReader.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/View.java
This triggered a case with Dataflow Runner v1 and PTransformOverrides that exposed https://github.com/apache/beam/issues/20873 . …
> Add a workaround for BEAM-20873 for optimized list side inputs.

- sdks/go/pkg/beam/runners/prism/internal/web/web.go
This PR decodes Web cancel Job request into a private struct that forwards the JobId to the jobpb.CancelJobRequest, avoiding encoding/json.Unmarshal on composite types containing protobuf message types. …
> Avoid json Unmarshal on proto CancelJobRequest

- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/View.java
Both input and materializationInput are the same logical PCollection, but the Spark test is sensitive to which one is used. …
> Update hack to make Spark runner happy as well.

- contributor-docs/release-guide.md
This shouldn't be the base case, but it would be good to have some troubleshooting available …
> Add guidance on fixing cloud build triggers

- .github/actions/setup-environment-action/action.yml
This is currently breaking precommits …
> Fix version issue

- sdks/java/managed/src/main/java/org/apache/beam/sdk/managed/ManagedSchemaTransformProvider.java
> Updates the error message related to schema-transform discovery

- sdks/python/setup.py
This was accidentally demoted in https://github.com/apache/beam/pull/31164 due to a bad merge. …
> Restore pandas version constraint.

- CHANGES.md
- sdks/python/container/py310/base_image_requirements.txt
- sdks/python/container/py311/base_image_requirements.txt
- sdks/python/container/py39/base_image_requirements.txt
Manually update the Pandas dependency. Not updating other dependencies since we periodically updating them after a release cut. …
> Targeted dependency update for Pandas 2.1

- sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
An identical experiment was introduced in https://github.com/apache/beam/pull/16773 so let's just use that one. Also I want a user to _have to_ type the word "unsafe" if they are going to do this. …
> Use already-existing and more appropriately alarmist experiment in Python

- sdks/go/pkg/beam/runners/prism/internal/web/web.go
Fixes lint warning: JobId vs JobID. …
> Fix lint warning: JobId vs JobID

- CHANGES.md
- sdks/python/apache_beam/typehints/schemas.py
- sdks/python/apache_beam/yaml/main.py
- sdks/python/apache_beam/yaml/main_test.py
- sdks/python/scripts/run_pylint.sh
- sdks/python/setup.py
This will allow Beam YAML to be used for various template applications. …
> [YAML] Add the ability to pre-process yaml files with jinja2.

- sdks/python/apache_beam/transforms/util.py
- sdks/python/apache_beam/transforms/util_test.py
Right now, we have the potential to unnecessarily exceed our target batch size. This fixes that problem by being a bit more conservative on when we emit
Fixes #29350 …
> Avoid oversizing batch sizes with size estimation function

- .github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
- sdks/python/container/license_scripts/dep_urls_py.yaml
> Publish snapshots for Python 3.12 container images.

- sdks/python/apache_beam/io/requestresponse_test.py
> [Python] Add retries for flaky test - requestresponse_test.py::TestCaller::test_default_throttler 

- website/www/site/content/en/documentation/sdks/yaml.md
> Update yaml to non-beta link

- website/www/site/content/en/documentation/runners/direct.md
> Disclaimer - direct runner result can be different from remote runners

- examples/notebooks/get-started/try-apache-beam-yaml.ipynb
Fix for Beam YAML Day Zero Notebook to use built-in magic method `%%writefile` instead of removed `save_to_file` method. …
> Beam YAML day zero notebook save file fix

- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow_V2.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow_V2_Streaming.json
- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java
- runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/PropertyNames.java
This reverts commit 3b272d2c6c95fe888a03ccf100537b4149682546.
This is a pure revert, because:
- Dataflow translation did not have a problem in the original #30545. It was reverted because the core transform had to be reverted due to other runners's bugs.
- Dataflow v1 and v2 both execute the composites correctly already.
Now the original transform is re-introduced and runners with bugs have their tests sickbayed appropriately, so we can move forward safely.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers- …
> Reapply "Add direct Dataflow translation of Redistribute transform"

- contributor-docs/code-change-guide.md
Copy edit the Beam code contribution guide …
> Copy edit the code contribution guide

- .github/trigger_files/beam_PostCommit_Java_PVR_Spark3_Batch.json
- .github/trigger_files/beam_PostCommit_Java_PVR_Spark_Batch.json
- runners/spark/job-server/spark_job_server.gradle
Fix https://github.com/apache/beam/pull/31156#issuecomment-2110550940 …
> Exclude testRedistributePreservesMetadata from Spark PVR batch

- release/build.gradle.kts
- runners/flink/flink_runner.gradle
Also, only create validation task on single Flink version to avoid confusion …
> Fix post release revert leftover from #31274

- .github/trigger_files/beam_PostCommit_Java_PVR_Samza.json
- .github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Samza.json
- runners/samza/src/main/java/org/apache/beam/runners/samza/translation/RedistributeByKeyTranslator.java
- runners/samza/src/main/java/org/apache/beam/runners/samza/translation/ReshuffleTranslator.java
- runners/samza/src/main/java/org/apache/beam/runners/samza/translation/SamzaPipelineTranslator.java
This reverts commit ab9af72aeedea78dc57e172f4607a69c7d0c899e. …
> Reapply "Add Redistribute translation to Samza runner"

- sdks/python/apache_beam/ml/transforms/tft.py
- sdks/python/apache_beam/ml/transforms/tft_test.py
Implements the `deduplicate_tensor_per_row()` tensorflow transform in MLTransform. …
> Implement DeduplicateTensorPerRow in MLTransform

- .github/trigger_files/IO_Iceberg_Unit_Tests.json
- .github/workflows/IO_Iceberg_Unit_Tests.yml
Fixing yaml config changes from #31306
> Fix iceberg unit tests

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/container/license_scripts/dep_urls_java.yaml
Done with python scripts/tools/bomupgrader.py 26.39.0 based on https://github.com/apache/beam/blob/master/contributor-docs/java-dependency-upgrades.md
Latest bom is 26.39 - https://github.com/googleapis/java-cloud-bom/releases/tag/v26.39.0 …
> Upgrade GCP BOM to 26.39.0

- sdks/python/build.gradle
> Upgrade cibuildwheel version.

- website/www/site/content/en/documentation/pipelines/test-your-pipeline.md
Update the version and new artifact id for hamcrest.
> Update hamcrest dependency documentation version

- sdks/python/apache_beam/examples/snippets/transforms/aggregation/approximatequantiles.py
- sdks/python/apache_beam/examples/snippets/transforms/aggregation/approximateunique.py
add core transforms category to approximatequantiles.py and approximateunique.py to pass playground validation
[![Build …
> add category where missing in aggregation transforms

- sdks/go/pkg/beam/runners/prism/internal/coders.go
This PR fixes #31336. I performed the following to validate this change:
1) Run Prism server.
```
./gradlew :runners:prism:runServer
```
2) Execute `:runners:portability:java:ulrLoopbackValidatesRunnerTests` on Prism:
```
TEST=org.apache.beam.sdk.transforms.CombineFnsTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
``` …
> [Prism]: Fix unknown coder urn key: beam:coder:nullable:v1

- runners/google-cloud-dataflow-java/worker/build.gradle
> Upgrade jetty to latest 9.x for dataflow legacy worker

- sdks/python/setup.py
Looks like the latest [requests](https://pypi.org/project/requests/) release had an issue described in - https://github.com/psf/requests/issues/6707
This affected some of our tests - https://github.com/apache/beam/issues/31357
This is likely to be fixed with `requests==2.32.2` when that is out - https://github.com/psf/requests/issues/6707#issuecomment-2122490651
Fixes #31357  …
> [Python] Skip requests version 2.32.0,2.32.1 from package dependencies

- sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcpOptions.java
- sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/options/GcpOptionsTest.java
@address #31330 for adding a warning message when gcpTemplocation has soft delete enabled.
> [Java] Add warning to gcpTempLocation when its bucket has soft delete enabled

- sdks/java/expansion-service/container/boot.go
- sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java
- sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionServiceOptions.java
- sdks/java/io/expansion-service/build.gradle
For more details on ALTS, please see https://grpc.io/docs/languages/java/alts/. …
> Updates the Java Expansion Service container to support gRPC ALTS authentication

- examples/multi-language/README.md
> Update README.md (fix typo)

- sdks/java/extensions/ordered/build.gradle
> Fixed the extension name in Java SDK Ordered Processing extension

- website/www/site/content/en/blog/beamquest.md
> Fix beam quest link

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
This field is unused
it is only populated but never read and the 2 implementations of `DataflowWorkExecutor#extractMetricUpdates` return empty lists. …
> remove unused field

- sdks/python/apache_beam/yaml/tests/sql.yaml
> Remove bad dialect option.

- sdks/python/apache_beam/ml/inference/tensorflow_tests_requirements.txt
Addresses #30513
https://ge.apache.org/s/jifk6hz2rspue/console-log/task/:sdks:python:test-suites:direct:py38:tensorflowInferenceTest?anchor=194&page=1
```
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/runner/_work/beam/beam/build/gradleenv/1398941892/lib/python3.8/site-packages/typing_extensions.py)
``` …
> pin the lower bound for typing-extensions

- sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptions.java
- sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java
- sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/RetryHttpRequestInitializer.java
- sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/Transport.java
- sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtilTest.java
With WriteFiles, if the temp staging region/replication differs from the final output location, the rewrite operations used are not metadata operations but involve copying data.
This may be desirable to reduce replication changes as GCS bills bytes*replication for temporary files separately even if they are rewritten with a metadata rewrite op.
Currently when experimenting with this, the pipeline can fail due to read timeouts executing the rewrite op batches. Batch operations are best used for lightweight operations and I believe the timeout is occurring due to too much batching when copying data.
This PR changes the lowers the batch size for rewrite operations that likely involve copying due to different buckets, as well as adding options to control the timeouts and batch size if further …
> Add options to specify read and write http timeout for gcs as well as lower batching limit for rewrite operations which are copying.

- sdks/python/apache_beam/runners/worker/data_sampler.py
Add try-excepts around data sampler encoding …
> Add try-excepts around data sampler encoding

- sdks/python/apache_beam/yaml/generate_yaml_docs.py
- sdks/python/apache_beam/yaml/yaml_provider.py
This is the first transform in the (alphabetical) list, so it'd be good to not have it empty.
Also produce slightly nicer examples for repeated arguments. …
> Add docs for YAML AssertThat.

- sdks/python/apache_beam/io/gcp/bigquery.py
fix #31372
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20sou …
> Update bigquery.py documentation

- CHANGES.md
Add CHANGES.md notes about
* Prism binaries being published.
* Prism supporting synthetic ProcessingTime timer handling. …
> [prism] Report prism changes.

- sdks/python/apache_beam/yaml/yaml_join.py
- sdks/python/apache_beam/yaml/yaml_provider.py
This allows us to get good docs for Join. …
> Pass through docs (and configs) for SqlProviders.

- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOST.java
- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerIOST.java
**Changes:**
* BigQueryIOST
* * Fixed settings in Write PTransform
* * Increased number of records
* BigTableIOST
* * Increased number of records 
* SpannerIOST
* * Increased number of records
* * Increased rowsPerSecond
[SpannerIOST write job](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-05-29_03_08_53-12420853673353456558)
[BigTableIOST write job](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-05-29_03_09_43-13031585565482980110)
[BigQueryIOST write job](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-05-30_06_06_41-74254488501071130)
See the [Contributor Guide](https://beam.apache.org/contribute) …
> Change configurations for stress tests. Fix BigQueryIOST

- sdks/python/apache_beam/io/gcp/gcsio.py
> Set retry policy to DEFAULT_RETRY when initializing BlobWriter.

- sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java
- sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/CommonJms.java
- sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOIT.java
- sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOTest.java
- sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/MockNonSerializableConnectionFactory.java
addresses #18110
Added a new configuration method `withConnectionFactoryProviderFn` to the JmsIO's Read and Write transforms, which enables the user to specify a lazily instantiated CF objects in case they're not serializable …
> add support for ConnectionFactory ProviderFn in JmsIO

- sdks/python/apache_beam/transforms/ptransform_test.py
> Add test of Select type inference.

- sdks/python/apache_beam/yaml/examples/simple_filter.yaml
- sdks/python/apache_beam/yaml/examples/simple_filter_and_combine.yaml
- sdks/python/apache_beam/yaml/examples/wordcount_minimal.yaml
- sdks/python/apache_beam/yaml/tests/avro.yaml
- sdks/python/apache_beam/yaml/tests/bigquery.yaml
- sdks/python/apache_beam/yaml/tests/csv.yaml
- sdks/python/apache_beam/yaml/tests/java-map.yaml
- sdks/python/apache_beam/yaml/tests/join.yaml
- sdks/python/apache_beam/yaml/tests/json.yaml
- sdks/python/apache_beam/yaml/tests/parquet.yaml
- sdks/python/apache_beam/yaml/tests/sql.yaml
- sdks/python/apache_beam/yaml/tests/text.yaml
- sdks/python/apache_beam/yaml/tests/windowing.yaml
Looks like these were edited by a botched find-and-replace somewhere. …
> Fix mangled license headers.

- .github/workflows/beam_CleanUpGCPResources.yml
- .github/workflows/beam_PostCommit_Go.yml
- .github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml
- .github/workflows/beam_PostCommit_Java_BigQueryEarlyRollout.yml
- .github/workflows/beam_PostCommit_Java_Examples_Dataflow_ARM.yml
- .github/workflows/beam_PreCommit_CommunityMetrics.yml
- .github/workflows/beam_PreCommit_Java_Examples_Dataflow.yml
- .github/workflows/beam_PreCommit_Java_Spark3_Versions.yml
- .github/workflows/beam_PreCommit_Website_Stage_GCS.yml
- .github/workflows/beam_Publish_BeamMetrics.yml
- .github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
- .github/workflows/beam_Publish_Docker_Snapshots.yml
- .github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml
- .github/workflows/beam_Release_Python_NightlySnapshot.yml
> Remove setup gcp credential step for beam_ workflows running on self-hosted runner

- .github/trigger_files/beam_PostCommit_XVR_Flink.json
- sdks/java/extensions/python/src/main/resources/org/apache/beam/sdk/extensions/python/bootstrap_beam_venv.py
Fix Postcommit XVR suite, built upon #31479 …
> Extract latest beam version directly from the request

- sdks/go/container/boot.go
- sdks/go/container/tools/pipeline_options.go
- sdks/go/pkg/beam/core/runtime/harness/init/init.go
- sdks/java/container/boot.go
* Move the pipeline options file creation to the tools package for boot loader consistency.
* Apply the pipeline options reading to the Go SDK. Fallback to the options flag incase an older boot loader is being used for this SDK.
Handles #27839 for the Go SDK. …
> [#27839][Go SDK] Write pipeline options to a file, instead reading from a flag.

- examples/notebooks/get-started/try-apache-beam-yaml.ipynb
- sdks/python/apache_beam/yaml/examples/simple_filter_and_combine.yaml
- sdks/python/apache_beam/yaml/integration_tests.py
- website/www/site/content/en/documentation/sdks/yaml-combine.md
Additional cleanup to mark Combine transform as stable. …
> [YAML] mark Combine transform as stable

- sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Redistribute.java
Delete RedistributeByKeyAllowingDuplicates since this class is unused. …
> Delete RedistributeByKeyAllowingDuplicates from Redistribute

- sdks/typescript/src/apache_beam/runners/flink.ts
Fix #31456
introduced in #31394 …
> fix typescript syntax

- sdks/python/apache_beam/ml/transforms/base.py
- sdks/python/apache_beam/ml/transforms/base_test.py
- sdks/python/setup.py
Adds the base class for Image Embedding model use. Largely functions like the `_TextEmbeddingHandler` class but operating on image types. The input validation is somewhat sparse, largely because the image representations can vary from framework to framework and adding extra imports to cover those felt antithetical to the concept of having a base class. 
Part of #31500  …
> Add base _ImageEmbeddingHandler

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Quick update to the most recent Go release to  be cherry picked into the 2.57.0 branch as well. …
> Update Go container build version to 1.21.11

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Cherry pick of #31515 updating the Go version used for container builds to the latest. …
> [Cherrypick][#31515] Update Go container build version to 1.21.11

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
Mitigate one specific occurrence of #31505 …
> Do not suppress downstream Exception in BigQueryIO Storage write API FailedStorageApiInserts Handling

- sdks/java/managed/src/main/java/org/apache/beam/sdk/managed/Managed.java
> Cherrypicking #31517 Managed doc fixes 

- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java
> Add missing import

- sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai.py
- sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai_test.py
Adds support for Vertex AI image embedding generation to the MLTransform suite along with a test. 
Part of #31500  …
> Implement Vertex AI Image Embedding MLTransform

- sdks/python/apache_beam/ml/transforms/base.py
Streamlines the base Embedding Handlers (text, image) be deduplicating shared code and making the input-specific implementations simpler. 
Part of #31500  …
> Deduplicate Base Embedding Handler Code

- it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java
> BigQueryIOST: fix assert message, fix streaming mode

- sdks/python/apache_beam/internal/gcp/auth.py
- sdks/python/apache_beam/internal/gcp/auth_test.py
The Python Linting pre-commit went red, catching changes in the gcp auth.py and auth_test.py files. I'm not entirely sure why months-old changes started getting hit with linting errors now, but this fixes them, …
> Fix Python Linting Errors on Master

- sdks/python/apache_beam/transforms/external_test.py
> Escape literal tab in error message.

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
- sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/ITEnvironment.java
Upgrading testcontainer version to 1.19.7, as this version supports "org.testcontainers:solace" dependency, required in #31476  …
> Upgrading testcontainer version to 1.19.7

- sdks/python/apache_beam/ml/transforms/tft_test.py
The test class was erroneously named "HashWordsTest"  …
> Correct test name to HashStringsTest

- sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py
> make the table name unique in ReadUsingStorageApiTests

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java
- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutor.java
- runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutorTest.java
Work.java no longer implements the Runnable interface, ExecutableWork does this.
Fix the bad cast and correctly extract work token in BoundedQueueExecutor. …
> Fix incorrect Work.java cast and logging

- .github/workflows/playground_backend_precommit.yml
- playground/backend/containers/scio/Dockerfile
- playground/backend/env_setup.sh
- playground/backend/new_scio_project.sh
- Fixes permissions issue with sbt scala artifact starting with scala 2.13. More info: https://github.com/scala-js/scala-js/issues/4212
- Fixes the missing library dependency that was removed from scio template
- Uses a fixed scio template commit to prevent future changes breaking #30757 
- Fixes #30737 
Already tested on staging …
> Fix Playground scio examples, fix playground lint

- runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
Cherrypick #31555 onto release branch to fix bug  …
> Cherrypick #31555 onto release branch

- sdks/python/apache_beam/internal/gcp/auth.py
- sdks/python/apache_beam/internal/gcp/auth_test.py
This type checking is red on the release branch …
> Cherrypick #31546 to 2.57.0 release branch

- website/www/site/content/en/documentation/io/built-in/google-bigquery.md
> Remove notes now that Dataflow v2 supports BQ autosharding

- sdks/python/apache_beam/ml/transforms/tft.py
- website/www/site/content/en/documentation/ml/preprocess-data.md
Also updates the Python versions listed as supporting MLTransform. …
> Update documentation for new TFT Transforms

- sdks/go/test/integration/integration.go
> [Cherrypick of #31509] Filter out tests for unsupported features for Spark.

- .github/workflows/beam_PreCommit_Java_IOs_Direct.yml
- sdks/java/io/clickhouse/build.gradle
- sdks/java/io/clickhouse/src/test/java/org/apache/beam/sdk/io/clickhouse/BaseClickHouseTest.java
- sdks/java/io/clickhouse/src/test/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIOTest.java
> Fix clickhouse tests

- sdks/python/apache_beam/utils/subprocess_server.py
The current subprocess_server uses process.send_signal to terminate the process. On Windows, this will raise a ValueError, as .terminate() should be used instead.
This would close #21069
GitHub Actions …
> Add try-except for process.send_signal so it can work on Windows.

- website/www/site/content/en/documentation/patterns/side-inputs.md
This is a reasonable place to call folks attention to enrichment …
> Call out enrichment in side input patterns

- sdks/python/apache_beam/runners/dataflow/internal/names.py
Needed for small dependency updates …
> Clone dataflow containers

- sdks/java/io/parquet/src/main/java/org/apache/beam/sdk/io/parquet/ParquetIO.java
Fix and harmonize setConfigartion methods documentation for ParquetIO sink
> Improve  javadoc in ParquetIO

- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
Updating KafkaIO's documentation. It mentioned the `KafkaIO.readAll()` method, which never existed. …
> Update KafkaIO's docstring to match current implementation

- sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/build.gradle
- sdks/java/io/elasticsearch-tests/elasticsearch-tests-7/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
- sdks/java/io/elasticsearch-tests/elasticsearch-tests-8/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTest.java
- sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/build.gradle
- sdks/java/io/elasticsearch-tests/elasticsearch-tests-common/src/test/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIOTestUtils.java
- sdks/java/io/elasticsearch/build.gradle
- sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
>  Allow compression of Elasticsearch requests

- .github/workflows/build_release_candidate.yml
fixes: #31641 
Rootcause: https://github.com/apache/beam/pull/31222 …
> Use correct name for tox doc task.

- sdks/python/apache_beam/io/gcp/gcsio.py
- sdks/python/apache_beam/io/gcp/gcsio_test.py
- sdks/python/apache_beam/options/pipeline_options.py
- sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
addresses #31465
Added new metrics that can be enabled via the following command line flags: "--enable_bucket_read_metric_counter" and "--enable_bucket_write_metric_counter". These metrics reports the number of bytes read/written from/to a GCS bucket per job. …
> Feature add metrics counting the number of bytes read/written from/to GCS bucket per job

- learning/katas/python/Core Transforms/GroupByKey/GroupByKey/task.py
- sdks/python/apache_beam/examples/snippets/transforms/aggregation/approximatequantiles.py
- sdks/python/apache_beam/examples/snippets/transforms/aggregation/approximateunique.py
- website/www/site/content/en/documentation/transforms/python/aggregation/approximatequantiles.md
- website/www/site/content/en/documentation/transforms/python/aggregation/approximateunique.md
- website/www/site/content/en/documentation/transforms/python/aggregation/batchelements.md
- website/www/site/content/en/documentation/transforms/python/aggregation/count.md
- website/www/site/content/en/documentation/transforms/python/aggregation/groupbykey.md
- website/www/site/content/en/documentation/transforms/python/aggregation/tolist.md
- website/www/site/content/en/documentation/transforms/python/overview.md
- website/www/site/layouts/partials/section-menu/en/documentation.html
> Fix playground examples

- sdks/java/io/rabbitmq/src/main/java/org/apache/beam/sdk/io/rabbitmq/RabbitMqMessage.java
- sdks/java/io/rabbitmq/src/test/java/org/apache/beam/sdk/io/rabbitmq/RabbitMqMessageTest.java
Fixes #31397
Tested locally with List type headers. …
> RabbitIO: fix serialization for list type headers

- sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextIO.java
- sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java
- sdks/java/core/src/test/java/org/apache/beam/sdk/io/WriteFilesTest.java
> Expose GroupIntoBatches parameters for WriteFiles auto-sharding transform

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteRecordsInconsistent.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java
> Add Storage API streaming max retries parameter for BigQueryOptions

- build.gradle.kts
- sdks/java/extensions/combiners/build.gradle
- sdks/java/extensions/combiners/src/main/java/org/apache/beam/sdk/extensions/combiners/Histogram.java
- sdks/java/extensions/combiners/src/main/java/org/apache/beam/sdk/extensions/combiners/package-info.java
- sdks/java/extensions/combiners/src/test/java/org/apache/beam/sdk/extensions/combiners/HistogramTest.java
- settings.gradle.kts
Design document: [here](https://docs.google.com/document/d/1dEDOa8TM1lGajd0n_is_W60w1XajhoA7N5dkRwsXJzw/edit?usp=sharing) …
> Add Histogram combiner

- CHANGES.md
- website/www/site/config.toml
- website/www/site/content/en/blog/beam-2.57.0.md
- website/www/site/content/en/get-started/downloads.md
> Blog and site updates for Beam 2.57.0 release

- sdks/java/io/csv/build.gradle
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseError.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseErrorTest.java
This PR closes #31699 by creating a CsvIOParseError data class. …
> Create CsvIOParseError data class

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseConfiguration.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseConfigurationTest.java
This PR closes #31704 by creating a CsvIOParseConfiguration class.  …
> [CsvIO] Create CsvIOParseConfiguration

- sdks/python/apache_beam/io/parquetio_test.py
> Remove excessive logging in test.

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseResult.java
> [CsvIO] Move CsvIOParseResult

- sdks/go/container/tools/pipeline_options.go
- sdks/go/container/tools/pipeline_options_test.go
This PR address #31731, increasing test coverage for Go sdk. …
> Add a unit test for MakePipelineOptionsFileAndEnvVar

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpers.java
This PR closes #31703 by scaffolding the CsvIOParseHelpers. This enables the method implementations to happen in parallel PRs. …
> [CsvIO] Scaffold CsvIOParseHelpers

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOReadFiles.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOReadFilesTest.java
> create CsvIOReadFiles class

- sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
- sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadWithPartitionsHelper.java
- sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcUtil.java
- sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOTest.java
- sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcUtilTest.java
> Support custom JdbcReadWithPartitionsHelper

- .github/workflows/go_tests.yml
Updating the build Go version in #31747 made Go workflows perma-red because of a crash with the previous Staticcheck version running against 1.22. Our staticcheck was also behind, not officially supporting Go 1.21 which we were on previously …
> Update Staticcheck to 2023.1.7

- playground/backend/containers/python/Dockerfile
The Playground nightly CI job has been perma-red because of a 404-ing OpenJDK11 download in the dockerfile. This updates the dockerfile to download an existing target.
Fixes #30612 …
> Update Playground Python Dockerfile

- sdks/go/pkg/beam/util/gcsx/gcs.go
- sdks/go/pkg/beam/util/gcsx/gcs_test.go
> Disable SoftDeletePolicy when creating a default bucket

- playground/backend/containers/python/Dockerfile
#31745 omitted updating the install invocation for the OpenJDK JRE, this fixes it …
> Fix installation invocation for OpenJDK

- buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
Updates which version of the Dataflow service API to use.
@damondouglas  …
> Updates Dataflow service API version.

- sdks/python/apache_beam/typehints/schemas.py
- sdks/python/apache_beam/yaml/json_utils.py
- sdks/python/apache_beam/yaml/main.py
- sdks/python/apache_beam/yaml/yaml_provider.py
- sdks/python/apache_beam/yaml/yaml_provider_unit_test.py
- sdks/python/apache_beam/yaml/yaml_transform.py
This allows one to define new transforms with YAML that can be imported and used in other pipelines. …
> Basic yaml-defined provider.

- sdks/java/core/src/main/java/org/apache/beam/sdk/util/SerializableSupplier.java
Adding a reusable SerializableSupplier function into a core package accessible throughout the repository.
[![Build …
> Add SerializableSupplier to the core package.

- CHANGES.md
- sdks/go.mod
- sdks/go.sum
- sdks/go/pkg/beam/core/runtime/xlangx/expand.go
- sdks/go/test/integration/internal/containers/containers.go
The Apache Beam Go SDK included a software dependency using the LGPL license. This is a violation of the ASF 3rd party license policy. This PR replaces the offending dependency with a comparable one that has an allowed license.
Fixes #31765 …
> Replace LGPL dep in Go SDK with an MIT alternative

- website/www/site/content/en/documentation/programming-guide.md
> Polish DoFn.Setup

- CHANGES.md
In PR #31769 I accidentally added to the 2.57.0 section of CHANGES.md which is released. I should have actually made the change to the unreleased 2.58.0 section. This PR fixes that mistake.  …
> Fix CHANGES.md from #31769 which incorrectly added to a released version

- .github/actions/setup-environment-action/action.yml
- .github/workflows/build_release_candidate.yml
Follow up to https://github.com/apache/beam/pull/31734 with the same goals …
> Don't cache when building release candidates

- .github/ACTIONS.md
This is to hopefully create a built in response for questions around this, we can evolve it as needed …
> Add link to security model

- sdks/java/io/solace/build.gradle
The final PR for the Solace connector - switch flags to publish doc and the connector. (addresses #31440).
[![Build …
> Solace Read connector: switch flags to publish the package

- CHANGES.md
Adding changelog notes.
Addresses #31440. …
> Solace Read: add changelog notes regarding Solace read connector

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/FirestoreOptions.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/FirestoreV1ReadFn.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/FirestoreV1WriteFn.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/it/FirestoreTestingHelper.java
> Allow Firestore project to be configurable

- sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergIO.java
> CP(#31833) Add doc warning against using icebergio directly

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageSourceBase.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/CreateTables.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteRename.java
- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteTables.java
- sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/ba …
> Add lineage information for BigQuery sinks.

- sdks/python/apache_beam/io/fileio.py
address https://github.com/apache/beam/issues/29515#issuecomment-1822574823 …
> Change orphan file log to warning

- playground/backend/containers/python/Dockerfile
Update to openjdk-17-jre-headless package which is served via debian repositories in bookworm …
> playground python image update openjdk to 17

- sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/SnowflakeIO.java
> SnowflakeIO: Use fileNameTemplate attribute for file prefix

- sdks/python/apache_beam/io/fileio.py
> [Release-2.58.0] Cherry-pick #31835 into release branch

- contributor-docs/code-change-guide.md
This came up as a point of confusion when talking with some folks …
> Add a little more info on snapshot containers

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIO.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpers.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpersTest.java
This PR closes #31712 . 
It implements a helper method for validating the [CSVFormat](https://javadoc.io/static/org.apache.commons/commons-csv/1.8/org/apache/commons/csv/CSVFormat.html) required for parsing CSV. …
> [CsvIO] Implement CsvIOParseHelpers::validate(CSVFormat)

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpers.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpersTest.java
This PR closes #31716. 
It implements a helper method for validating the [CSVFormat](https://javadoc.io/static/org.apache.commons/commons-csv/1.8/org/apache/commons/csv/CSVFormat.html) in relation to the [Schema](https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/schemas/Schema.html), both of which are required for parsing CSV.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD …
> [CsvIO] implement CsvIOParseHelpers::validate(CSVFormat, Schema)

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParse.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseTest.java
> [CsvIO] Create CsvIOParse scaffold

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseKV.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseKVTest.java
This PR closes #31871.
It adds an unimplemented CsvIOParseKV class to allow parallel PR efforts. …
> [CsvIO] Create scaffold CsvIOParseKV class

- .github/workflows/beam_CancelStaleDataflowJobs.yml
- .github/workflows/beam_CleanUpGCPResources.yml
- .github/workflows/beam_CleanUpPrebuiltSDKImages.yml
- .test-infra/tools/stale_bq_datasets_cleaner.sh
Cancel Stale Dataflow Jobs: https://github.com/apache/beam/actions/runs/9941755982
Clean up pre-built images: https://github.com/apache/beam/actions/runs/9941759271/job/27461609869
Clean up GCP Resources: https://github.com/apache/beam/actions/runs/9941757656
These jobs run on self hosted runner, no need to auth using secret (which is currently bad), then the jobs no longer fail at auth step
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-ea …
> Fix auth for clean up actions

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpers.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpersTest.java
> [CsvIO] Create CsvIOParseHelpers::mapFieldPositions method

- CHANGES.md
Updates CHANGES.md on master now that the 2.58.0 release branch has been cut. …
> Update CHANGES.md with 2.59.0 Section

- model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/metrics.proto
- runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsContainerImpl.java
- runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoConstants.java
- runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/SimpleMonitoringInfoBuilder.java
- runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MetricsContainerImplTest.java
This is a cherry pick of https://github.com/apache/beam/pull/31838 …
> Export string sets in monitoring infos. (#31838)

- .github/workflows/playground_backend_precommit.yml
- .github/workflows/run_perf_alert_tool.yml
tests:
https://github.com/apache/beam/actions/runs/9961872013/job/27524386990
https://github.com/apache/beam/actions/runs/9961885669/job/27524433237 …
> Remove remaining use of setup-cloud@v0 action

- .github/workflows/build_wheels.yml
The setup-gcloud@v0 deprecation breaks the python wheel action on the release branch and needs to be updated to build RC1 …
> [Cherrypick] Switch to use self-hosted runner for build_wheels action (#31866)

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecord.java
Co-authored-by: francisohara24 francisohara@google.com
This PR closes #31919. …
> [CsvIO] Change method signature of CsvIOStringToCsvRecord class

- .github/workflows/java_tests.yml
- .github/workflows/python_tests.yml
> Disable Dataflow run for java_test and python_test

- contributor-docs/release-guide.md
- release/src/main/scripts/run_rc_validation.sh
The hyphenated `apache-beam` python artifacts stopped being built as a result of #30955 but the release guide and RC validation scripts still referred to them instead of the `apache_beam` artifacts that are actually built. This updates references to the new names. …
> Update Python artifact name in release process

- contributor-docs/code-change-guide.md
- runners/google-cloud-dataflow-java/arm/build.gradle
- runners/google-cloud-dataflow-java/build.gradle
- sdks/python/test-suites/dataflow/common.gradle
- sdks/python/test-suites/direct/common.gradle
- sdks/python/test-suites/direct/xlang/build.gradle
Reduce a friction running integration tests locally, and update the documentation accordingly
Previously, gcpProject is used in some projects, while dataflowProject is used in some others
This change dedup the parameters used to run integration tests manually and align these additional parameters
* Change dataflowProject -> gcpProject
* Change dataflowRegion -> gcpRegion
* Change dataflowTempRoot -> gcpTempRoot
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make- …
> Clean up integration test manual run parameters

- website/www/site/content/en/documentation/io/connectors.md
These are additional Python IO connectors which some users may find useful …
> Callout beam-pyio

- .github/ISSUE_TEMPLATE/bug.yml
- Add an "Infrastructure" option for issues related to CICD, github etc.
- Set the default for priorities to priority 2 as implied by the text already. (I could not find the docs for this but found an example here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) …
> Add an Infrastructure option to issue template

- .github/ISSUE_TEMPLATE/failing_test.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/task.yml
- .github/issue-rules.yml
Follow up to #31947 - this:
1) Applies the same changes to the other issue templates
2) Autolabels infra issues with the `infra` label …
> Add infra option for remaining templates + autolabel

- sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
- sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java
Only check for presence of topic partition if we receive no records, instead of doing it for each bundle.   
[![Build …
> remove listing topics when processing each element

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIO.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpers.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecord.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseHelpersTest.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecordTest.java
This PR addresses #31854 by adding more test coverage. …
> [CsvIO]: Expand test coverage of CsvIOStringToCsvRecord

- examples/notebooks/beam-ml/bigtable_enrichment_transform.ipynb
This guarantees auth is done correctly and allows the notebook to work correctly …
> Auth with project id in our notebook

- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/FnApiStateAccessor.java
Adds handling of ordered list state in FnApiAccessor. Caching for ordered list state is handled the same as for bag and multimap state, it was just missing from the switch statement. …
> Adds ordered list user state support to fnapi accessor cache.

- sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/SolaceIO.java
Make the SolaceIO.Read constructor private.
Addresses #31440. …
> Solace Read: Make the SolaceIO.Read constructor private.

- website/www/site/content/en/documentation/io/connectors.md
- update the project link to GitHub organization
- correct streaming support status
- streaming support marked as ✘ but some connectors support it …
> Correct details of Beam PyIO (Collection of Python IO connectors)

- sdks/python/apache_beam/yaml/pipeline.schema.yaml
- sdks/python/apache_beam/yaml/yaml_transform.py
> [yaml] Fix yaml provider schema validation and merging

- sdks/python/container/piputil.go
Cherry-pick #31977 to the 2.58.0 release branch to improve observability. …
> Use buffered loggers that periodically flush.

- CHANGES.md
> Note SpannerIO.read new validation in 2.58.0 breaking change section

- sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java
cherry-pick #31960 into release branch
This is a minor performance regression introduced by #31805 (make one additional BigQuery query job, ~ 5s per read transform). …
> [Release-2.58.0] Dedup Lineage and getTableToExtract call in BigQuerySourceBase (#31960)

- sdks/python/apache_beam/yaml/pipeline.schema.yaml
- sdks/python/apache_beam/yaml/yaml_transform.py
Cherrypick #31974 into the 2.58.0 release branch. …
> [cherrypick][yaml] Fix yaml provider schema validation and merging (#31974)

- sdks/python/apache_beam/runners/portability/stager.py
If the requirements cache is skipped then we shouldn't generate a requirements_cache folder. 
- [ x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
- [ x] Update `CHANGES.md` with noteworthy changes.
- [ x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).
See the …
> Requirements_cache shouldn't create a cache folder when skipped.

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParse.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseConfiguration.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOReadFiles.java
This PR addresses #31704 . It adds new parameters to the CsvIOParseConfiguration class and ensures that it is Serializable.
----------------------- …
> [CsvIO]: add Coder and FromRowFn to CsvIOParseConfiguration class.

- sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/BasicAuthJcsmpSessionService.java
- sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/MessageReceiver.java
- sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SolaceMessageReceiver.java
- sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/MockSessionService.java
> Solace Read connector: Explicitly close the FlowReceiver

- .github/workflows/build_wheels.yml
Cherrypick #32009 to the release branch since it is invoked at the repo tag …
> [Cherrypick] Update Build Wheels to only build once on RCs (#32009)

- sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/FnApiStateAccessor.java
Cherry-pick #31923 into release 2.58.0 …
> Adds ordered list user state support to fnapi accessor cache. (#31923)

- website/www/site/content/en/documentation/dsls/sql/extensions/user-defined-functions.md
https://github.com/apache/beam/issues/32020
as titled …
> beam-sql-udf-example-mistake

- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseConfiguration.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseError.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseKV.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParseResult.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIORecordToObjects.java
- sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecord.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIORecordToObjectsTest.java
- sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecordTest.java
This PR updates error and result handling related to CSV parsing. …
> [CsvIO]: Update error and result handling.

- sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java
fixes #32035 
- Updated the `StaticCredentialsProvider` section of the `AwsOptions` class documentation. …
> update document in `AwsOptions`
