apache/beam

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerQuerySourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaRetrievalException.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerTableSourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/StructUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/StructUtilsTest.java

Following change adds `SpannerIO.readWithSchema()` method for reading Spanner table schema. This performs a call to the source table to get schema metadata for constructing a `RowCoder` for the output `PCollection` without having to manually provide a schema.
Logic follows `BigQuerySourceDef` very closely.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/be …

Add schema to SpannerIO read

---

sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoSchemaTranslator.java
sdks/java/extensions/protobuf/src/test/java/org/apache/beam/sdk/extensions/protobuf/ProtoSchemaTranslatorTest.java
sdks/java/extensions/protobuf/src/test/java/org/apache/beam/sdk/extensions/protobuf/TestProtoSchemas.java
sdks/java/extensions/protobuf/src/test/proto/proto3_schema_messages.proto
sdks/java/extensions/protobuf/src/test/proto/proto3_schema_options.proto

I found that ProtoSchemaTranslator fails to translate the schema when proto3 definitions have optional fields. 
These optional fields creates synthetic oneOfs internally and ProtoSchemaTranslator runs into errors treating them are real oneOfs. This excludes that from happening.
I had to use `getRealContainingOneof()` since they have [deprecated isSynthetic()](https://github.com/protocolbuffers/protobuf/commit/b6b86e21fb67e22b762b7230427bce00ee8c9fec)
Fixes #32199
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-revi …

fix failing ProtoSchemaTranslator on proto3 optional fields

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PreparePubsubWriteDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubUnboundedSink.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubUnboundedSource.java

* Move Lineage report outside of PubsubUnboundedSource
* Move Lineage report outside of PubsubUnboundedSink …

Refactor PubsubIO Lineage metrics to work with all runners

---

CHANGES.md
sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py

This avoids surprises like https://github.com/pandas-dev/pandas/issues/42471 …

Preserve numeric string literals when reading from json.

---

sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/PulsarIO.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFn.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/WriteToPulsarDoFn.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/package-info.java

Until this is better supported, we should warn folks away from it.
See https://github.com/apache/beam/issues/31078 for a collection of issues …

Add quality warnings to pulsar

---

.test-infra/metrics/sync/github/github_runs_prefetcher/code/main.py

We don't need to be paying attention to these old runs.
I deployed this to test and it works - https://pantheon.corp.google.com/functions/details/us-central1/github_workflow_prefetcher?q=search&referrer=search&project=apache-beam-testing&e=13802955&mods=-ai_platform_fake_service,ai_platform_staging_service&tab=metrics
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.c …

Filter out old actions runs from dashboard

---

runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java

There is a long time flaky test, see example: https://github.com/apache/beam/runs/29315435535
Originally it only considered ExecutionException -> RuntimeException -> InterruptedException, but InterruptedException at any stage is possible. …

Fix remote execution test flakiness in tearDown

---

sdks/python/apache_beam/ml/inference/base_test.py

As pointed out in https://github.com/apache/beam/pull/32237#issuecomment-2315911281 this test can be flaky. This tests that after `20` is processed (and times out) **and** at least 10 (2*timeout) seconds have passed, that the model will be full deleted.
Right now, it relies on timing and assumes that the pcollection will be processed in order (or at least the `20` will be processed early). This tries to deflake the test by adding some more elements which are guaranteed to timeout to ensure that after the first times out, sufficient time will pass for garbage collection to occur. It does admittedly lengthen the time to run to ~1 minute, unfortunately. …

Try deflaking test timing

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffset.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffsetTest.java

The reshuffle adds a barrier so that the read records were committed before possibly committing offsets. However this is unnecessary as the DoFn is annotated with RequiresStableInput and the fusion barrier can be introduced with just shuffling the offsets.
In both cases it is possible for a commit offset to be committed back to kafka before the data has been entirely processed by the pipeline. However with support to drain data from the pipeline (such as in Cloud Dataflow) this allows for exactly-once semantics for KafkaIO via the committed offsets to the topics across pipeline drain and restart. …

Remove expensive shuffle of read data in KafkaIO when using sdf and commit offsets

---

sdks/python/apache_beam/io/gcp/gcsio.py

`GcsIO` is failing when trying to use from a `DoFn` in Dataflow, due to repeated parsing of the pipeline options. This change avoids parsing the options just to retrieve an already-parsed option.
This change fixes #32361.

Fix using `GcsIO` from a `DoFn`in Python

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageStreamSource.java

A variable shadowing was introduced  [here](https://github.com/apache/beam/commit/4e8d7fbf7dfef6bcef9d7f01ce986c93f26ed958#diff-c3aff238bc5d7e190d1f7b4d80ce30ef24a42613a36034d6047b1decf2a285e8R306), preventing modification of the stream reader source after splitting.
I don't know the implication of this bug.

Fix BQ storage stream split

---

sdks/python/apache_beam/transforms/util.py

Stateful BatchElements behavior (particularly the impact on throughput) was not explained. Updating the doc string to explain what the stateful option is doing as well as how the value of `max_batch_duration_secs` impacts throughput makes this behavior more clear.  …

Improve BatchElements documentation

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/MetricKey.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/MetricName.java

This PR addresses the performance overhead caused by repeated string concatenation in the toString() method of the MetricName and MetricKey classes. The issue was identified as a significant contributor to CPU usage during metric processing in Beam’s Samza integration.
To mitigate this, the toString() results for MetricName and MetricKey are now cached. By storing the computed string representation on first access, we eliminate redundant concatenation operations in subsequent calls. This change reduces the computational cost associated with metrics processing, leading to improved performance in scenarios with frequent metric updates.
See the …

Memoize toString() for MetricKey and MetricName

---

sdks/python/apache_beam/runners/interactive/cache_manager.py
sdks/python/apache_beam/runners/interactive/cache_manager_test.py
sdks/python/apache_beam/runners/interactive/interactive_runner_test.py
sdks/python/apache_beam/runners/interactive/recording_manager_test.py
sdks/python/apache_beam/runners/interactive/utils.py

Formerly the coder used was always a url-excaped pickling[1] of windowed values. This is quite inefficient in time and space.
The default (text) sink is modified to use base64 encoding to avoid embedded newlines, and also has compression by defuault (which helps enormously in the case of common windowing and timestamp metadata).
[1] The FastPrimitivesCoder is targeted at efficiently coding elements, not windows or windowedvalues.
Also add compression to account for base64 expansion and (often) highly repetative windowing metadata. …

Use proper coders in interactive cache.

---

sdks/java/io/iceberg/hive/exec/build.gradle

Cherrypicking 32363 hive-exec shading fix

---

sdks/python/apache_beam/runners/interactive/interactive_beam.py
sdks/python/apache_beam/runners/interactive/non_interactive_runner_test.py

It is often more efficient to do a single run computing multiple collections at a time than to do multiple runs. …

Allow ib.collect(...) to take multiple PCollections.

---

CHANGES.md
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOReadTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextSourceTest.java

I believe this PR can fix  #32251 (it's closed but still not fully fixed. see [this case](https://github.com/apache/beam/issues/32251#issuecomment-2323647986)) and #32249.
Fix #32249, #32251. …

Use Knuth–Morris–Pratt algorithm for delimiter search in TextIO

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/OperationalLimits.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContext.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/ComputationWorkExecutorFactory.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContextTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSourcesTest.java

Planning to move OperationslLimits along with other settings from backend into a common class. `throwExceptionOnLargeOutput` is calculated from PipelineOptions, moving it out of OperationalLimits to avoid making the new classes depend on PipelineOptions.

[Dataflow Streaming] Move `throwExceptionOnLargeOutput` out of OperationalLimits

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Add jobLabelsMap parameter to BigQueryOptions

---

CHANGES.md
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/io/SerializableAvroCodecFactory.java
sdks/java/extensions/avro/src/test/java/org/apache/beam/sdk/extensions/avro/io/AvroIOTest.java
sdks/java/extensions/avro/src/test/java/org/apache/beam/sdk/extensions/avro/io/SerializableAvroCodecFactoryTest.java

fixes #32349
Adds support for Zstandard compression in Avro writes …

Support Zstd codec in SerializableAvroCodecFactory

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
sdks/python/apache_beam/metrics/metric.py
sdks/python/apache_beam/metrics/metric_test.py

Received feedback of #32319 that the standalone Impulse->DoFn lineage reporting may be confusing as user sees an extra transform while expanding PubSubIO read in their UI
This PR moves Lineage report into the existing MapElement step, using a wrapper SerializableFunction. In this way job graph is unchanged. …

Move PubsubIO source Lineage report to MapElements

---

sdks/python/apache_beam/ml/inference/base_test.py

Supercedes #32351 and avoids running this test on windows since its flaky there. I suspect its because of inconsistencies in the `__del__` lifecycle …

Dont run flaky test on windows

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaCoder.java
sdks/java/core/src/test/java/org/apache/beam/sdk/coders/RowCoderTest.java

Add tests that fail without the change covering encoding and decoding
Also add tests that cover the static position overrides which was not tested previously.
Some other cleanup to help debug other possible encoding positions issues in the future:
- ensure that only a single RowCoder is created for a given UUID by using synchronization when generating coders
- add some logging if encoding position overrides arrive after a RowCoder has already been generated for the UUID
fixes #32388 
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBU …

Fix RowCoderGenerator to use the encodingPositions when encoding and decoding the bit set representing null fields.

---

.github/workflows/python_tests.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/python/pyproject.toml
sdks/python/setup.py
sdks/python/tox.ini

Originally, this PR is to pin pip to version 24.1, so that `pip check` would not fail on xgboost-1.7.6 and grpcio-1.66.1.
After some attempts, it seems it is a bit inconvenient to enforce pip version, especially inside the venv set up by tox.
Therefore, we decide to make the following changes
1) for xgboost, since we don't have any plan to invest further on it, we are going to remove it from deps.  After that, the xgboost related tests in the ML test suite will be skipped. We can put it back in the future if we decide to support xgboost again (https://github.com/apache/beam/issues/31252) .
2) for grpcio, the failure only occurs on MacOS, so we decide to skip `pip check` on MacOS until https://github.com/grpc/grpc/issues/37660 is fixed.
#fixes #31285

Temporarily fix pip check failure on xgboost and grpcio

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/setup.py

Fixes: #32324  
Tested: apache/beam/actions/runs/10839063060/job/30078643883?pr=32446
One more run in flight: https://github.com/apache/beam/actions/runs/10840227044
GRPCIO issue: https://github.com/grpc/grpc/issues/37710 …

downgrade grpc

---

sdks/python/apache_beam/io/aws/s3filesystem.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem.py
sdks/python/apache_beam/io/filebasedsink.py
sdks/python/apache_beam/io/filebasedsource.py
sdks/python/apache_beam/io/filesystem.py
sdks/python/apache_beam/io/filesystems.py
sdks/python/apache_beam/io/gcp/bigtableio.py
sdks/python/apache_beam/io/gcp/bigtableio_test.py
sdks/python/apache_beam/io/gcp/gcsfilesystem.py
sdks/python/apache_beam/io/gcp/pubsub.py
sdks/python/apache_beam/io/gcp/pubsub_test.py

Add Lineage metrics to Python PubsubIO, BigtableIO, FileIO

---

playground/README.md
playground/backend/containers/go/build.gradle
playground/backend/containers/java/Dockerfile
playground/backend/containers/python/Dockerfile
playground/backend/containers/python/build.gradle
playground/backend/containers/router/Dockerfile
playground/backend/containers/router/build.gradle
playground/backend/containers/scio/Dockerfile
playground/backend/playground_functions/Dockerfile
playground/infrastructure/cloudbuild/playground_ci_examples.sh
release/go-licenses/Dockerfile

Where possible stop being specific about which Go image version to use, or which Go version to download.
* As of Go 1.21+, modules are built using their version of the Go language toolchain.
* The playground should be using the latest version of Go anyway, when updated.
Also including the go-licences image because it's not used for specific builds, but it does need to run on any of our go code to produce the container license manifests.
Fixes #32441  (In particular, it's required to fix the Playground CI Nightly build). …

Update Playground and other location usage of Go  to use latest released version by default.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java

badRecords gets updated from the gRPC response thread and read from the beam worker's main thread …

fix: use threadsafe data structure thats shared between threads

---

website/www/site/content/en/documentation/programming-guide.md

This patch adds documentation within the programming guide on how to use Beam metrics within Python as before this patch the only two languages with such information were Go and Java. This prevents the need to look at specific examples (or needing to read the source code) to learn how to use metrics in Python.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apach …

Add information on python metrics to the programming guide

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibilityTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java

Change KafkaIO read withDuplicates to warn but still commit offsets if configured
Two ways to enable commits, 
1) explicitly via commitOffsetsInFinalize()
2) Via consumer config  ENABLE_AUTO_COMMIT_CONFIG=true
If the first is true, redistribute can't be enabled
If the second is true, the pipeline can still be passed, but isn't the most optimal, since if the runner wants to enable duplicates, there is no point of introducing the additional overhead of checkpointing messages within Kafka itself., though it is not semantically incorrect.  The first option uses internal beam state to track which messages have been processed for preventing duplicates, which doesn't make sense if we also have a runner hint that duplicates can be allowed. 
Before this fix, it just meant customers weren't able to …

Fix Kafka with Redistribute

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

Fixes a breakage causing the coverage precommit to go red. Updates the test to a later python version to exercise the code …

Update Dataflow internal client test

---

sdks/java/io/google-cloud-platform/build.gradle
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java

Unfortunately, `BigQueryIO` continues to refer to pipeline option post graph construction time, for example during `@FinishBundle` in `UpdateSchemaDestination`, and `@JsonIgnore` prevents endpoint URL to be serialized, and the whole thing doesn't work. This fixes that.

`@JsonIgnore` causes emulator endpoint to be missing in DoFn's

---

sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java

Fix JmsIO NPE

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

Add missing test to test added commit stage is added if enabled.
There was a bug introduced in [9cbdda1](https://github.com/apache/beam/commit/9cbdda1b4e52452728cc9da2fa8498d0ace5ed7b). Added missing tests that would have caught that error. …

Add missing test to test added commit stage is added if enabled.

---

sdks/java/io/mqtt/src/main/java/org/apache/beam/sdk/io/mqtt/MqttIO.java
sdks/java/io/mqtt/src/test/java/org/apache/beam/sdk/io/mqtt/MqttIOTest.java

also fix #19092 . There was a timing issue in the test, that the messages published in between connection and subscription established are lost. …

Emit warning when Mqtt waiting for connection for extended period of time

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/expansion-service/build.gradle
sdks/java/io/iceberg/hive/exec/build.gradle
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AppendFilesToTables.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergIO.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergWriteSchemaTransformProvider.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteToDestinations.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOWriteTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergWriteSchemaTransformProviderTest.java

Apply some windowing and add a new `triggering_frequency_seconds` parameter to support streaming writes to Iceberg tables.
The triggering frequency controls how often we commit data and create new snapshots

Support Managed Iceberg streaming writes

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicSequence.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/PeriodicSequenceTest.java

Instead of reporting all the work it will do as backlog it should report just the scheduled based upon the current time that have not been produced yet.
This is done via GetSize but could be done by changing how Progress is reported. This seems more targeted fix as I'm not sure of all the implications of modifying progress.
Also fixup BOUNDED/UNBOUNDED since an effective end-of-time timestamp can be set. …

Change PeriodicSequence to report backlog accurately

---

sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers_test.py

`WorkerHandlerManager` stores cached handlers as `self._cached_handlers = defaultdict(str)`. When you reset the manager with `manager.close_all()` it resets the cached to just a regular dict instead of a default dict, i.e. `self._cached_handlers = {}`.
If you try to create another worker handler after calling `close_all()`, you'll get a KeyError.

[Python] Fix bug where WorkerHandlerManager.close_all re-initialized state with incorrect dict type

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteOptions.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java

Rollback Bigtable throttling counter

---

sdks/go/pkg/beam/runners/prism/internal/preprocess_test.go
sdks/go/pkg/beam/runners/prism/internal/stage.go

Prism splits too aggressively in low latency scenarios, which for textio can cause splitting to single byte inputs most of which don't output anything.
While it would be nice to make this configurable, that is more plumbing than I'd like to do right now. Instead we add some per stage back off and catchup.
* Give each stage an atomic progress interval value for its "ticks".
* If no progress has been made in the interval (via no PCollections element count or channel index changes), split.
* If we successfully split, back off the interval for all instances of the stage.
* This back off is clamped to a 30 second interval maximum.
* Back off is multiplicative (by a factor of 4).
* New bundles for this stage use that value.
* Reduces noisy per bundle log printouts by splitting less.
* If …

[#32498][prism] Add split / progress back off + catch-up.

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/options/pipeline_options_test.py

Skip or mock the check of `is_soft_delete_enabled`, because it requires a networck connection to access GCS.

[GCSIO] Fix internal unit test failure

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

In some cases because of inconsistency in metadata tracking on Kafka server, the server might not know how far the client has already read. In these cases the Kafka server can send records which have already been consumed when calling `poll()`. These records can be safely skipped. …

ReadFromKafkaDoFn: handle failed seek

---

sdks/python/apache_beam/dataframe/doctests.py

In preparation of NumPy 2 support.
NumPy 2 made some intended (breaking) changes, e.g. https://github.com/numpy/numpy/issues/26774 , follow the fix there as we still support numpy 1.x
Alternative: Increase pandas upperbound to 2.2.2, which supports NumPy 2. However, tested that  NumPy 2 + pandas 2.2.3 still fails doctest on the latest. Need upstream (pandas) fix.
Revisit until we drop numpy 1.x and/or pandas fixed doctest in newer versions
To …

Set np printoptions

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/RowFilter.java
sdks/java/core/src/test/java/org/apache/beam/sdk/util/RowFilterTest.java

Utility to easily filters columns in Beam Rows
Part of #32365
See #31807 for how this can work for portable dynamic destinations

Add RowFilter utility

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/OneOfType.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaTranslationTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/logicaltypes/LogicalTypesTest.java
sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
sdks/java/managed/src/test/java/org/apache/beam/sdk/managed/ManagedSchemaTransformTranslationTest.java

Schemas are immutable so this meets the guarantee that a consistent UUID is used for matching schemas. Cleanup some cases setting a random UUID after creating Schema, fix case where same UUID was assigned to different Schema after sorting, and use Immutable data structures to enforce immutability.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/m …

Set a UUID when building a Schema object.

---

learning/tour-of-beam/terraform/build.gradle.kts
playground/terraform/build.gradle.kts

Reverts apache/beam#32541
This is causing build failure:
```
A problem occurred configuring project ':playground:terraform'.
> Could not resolve all files for configuration ':playground:terraform:classpath'.
> Could not resolve com.pswidersk:terraform-gradle-plugin:1.1.1.
Required by:
project :playground:terraform > com.pswidersk.terraform-plugin:com.pswidersk.terraform-plugin.gradle.plugin:1.1.1
> No matching variant of com.pswidersk:terraform-gradle-plugin:1.1.1 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
```

Revert "Bump com.pswidersk.terraform-plugin from 1.0.0 to 1.1.1"

---

sdks/go/pkg/beam/transforms/periodic/periodic.go
sdks/go/pkg/beam/transforms/periodic/periodic_test.go
sdks/python/apache_beam/transforms/periodicsequence.py
sdks/python/apache_beam/transforms/periodicsequence_test.py

This affects monitoring and autoscaling decisons made by runners.
In particular the Dataflow runner utilizes this backlog bytes for autoscaling and unbounded periodic sequences previously reported a large backlog causing pipelines to upscale and not downscale.   …

Fix backlog reported by periodicsequence in python and go sdks to not include future outputs

---

.github/workflows/beam_Inference_Python_Benchmarks_Dataflow.yml
sdks/python/test-suites/containers/tensorrt_runinference/tensor_rt.dockerfile

The Python Inference benchmarks were running on a container with Python 3.8 and the upgrade to 3.9 caused a submission/runtime version mismatch on Dataflow. This updates the base container to a tensorrt image with 3.10 and updates the test as well.
The updated container has been pushed to the `apache-beam-testing` artifact registry. …

Update Python Inference Benchmark Test to Python 3.10

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowStreamingPipelineOptions.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/config/FakeGlobalConfigHandle.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/StreamPoolHeartbeatSender.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/StreamPoolHeartbeatSenderTest.java

The logic is guarded behind an experiment `streaming_engine_use_job_settings_for_heartbeat_pool`. The experiment will be removed once backend changes are rollback safe.

[Dataflow Streaming] Use separate heartbeat streams based on job settings

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowStreamingPipelineOptions.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDispatcherClient.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServer.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillStubFactoryFactory.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillStubFactoryFactoryImpl.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDispatcherClientTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/testing/FakeWindmillStubFactoryFactory.java

The change is behind an experiment `streaming_engine_use_job_settings_for_isolated_channels`. The experiment will be removed once backend changes are rollback safe.

[Dataflow Streaming] Use isolated windmill streams based on job settings

---

learning/tour-of-beam/learning-content/introduction/introduction-concepts/pipeline-concepts/overview-pipeline/description.md
learning/tour-of-beam/learning-content/introduction/introduction-concepts/runner-concepts/description.md
learning/tour-of-beam/learning-content/introduction/introduction-guide/description.md

Just some formatting and clarification changes to a few Tour of Beam pages. (I've been referring many people to Tour of Beam!)
- Broke up the first page of the Tour of Beam which was just a huge blob of unbroken text.
Before: 
After: (just with local markdown rendering)
- Adjusted `PTransform` definition which used to say that PTransforms took one or more PCollection when they can really take zero or more.
- Small capitalization / language clarifications

Tour of Beam markdown touchups

---

sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/core_test.py

fixes #28061
Replicated #28159
Add warning log if implemented process function return None as Expected to notify users in following case:
1. function return explicitly as `return None`
2. function pass `pass`
3. function do not have `return` or `yield`
Fix _get_function_body_without_inners function in corner case if function def is 
```python
def process(param1,  
param2):
```
The current function will be fail. That will address this comment https://github.com/apache/beam/pull/28159#issuecomment-1695291184 …

Log warning if process function return None

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java

We've seen (internal bug: 367930654) pipeline stuck at closing reader indefinitely, but it is not obvious from worker log, apparently straggler detector does not work for closeReader.
This log is added so that worker log will print the actual cause of Exception before conducting clean up steps (e.g. closeReader for source, etc) …

Add info log between executing work failed and cleanup

---

sdks/python/apache_beam/transforms/ptransform_test.py
sdks/python/apache_beam/typehints/typed_pipeline_test.py
sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

Currently, python Beam transforms will complain about type incompatibilities if you try to supply ints for floats/complexes or floats as complexes. It's not hard to work around this but it comes up fairly often and is a bit tedious to fix over and over when ints work fine in place of floats/complexes.
PEP484 states that ints should be compatible with floats/complexes and floats as complexes, so this change just updates our type check to allow for these special cases
[Dev mail thread on this](https://lists.apache.org/thread/d4cbch0tghm24gggwyvz912l66vyojsv)

[Python] Allow ints to be considered as floats/complexes and floats as complexes

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryAvroUtils.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryQuerySourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageSourceBase.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryTableSourceDef.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageQueryTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOStorageReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryDirectReadSchemaTransformProviderTest.java

Extracted from https://github.com/apache/beam/pull/32360
Trim BQ schema using selected fields instead of avro schema.

BigQuery trim schema with selected fields

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java

Keep string FQN as a way to add lineage information in a generic way.
addresses https://github.com/apache/beam/issues/31788 …

Keep string FQN as a way to add lineage information

---

sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/providers/CsvWriteTransformProvider.java
sdks/java/io/json/src/main/java/org/apache/beam/sdk/io/json/providers/JsonWriteTransformProvider.java

Before this change, streaming pipelines that use the Java variant of WriteToJson would fail with error:
```
ValueError: Error apply transform "WriteToJson" at line 16: java.lang.IllegalArgumentException: Must use windowed writes when applying WriteFiles to an unbounded PCollection
```
even when Windowing is explicitly set. This is due to WriteFiles requiring an explicit `.withWindowedWrites()` call to preserve input windowing.
Also fixes same probably issue with WriteToCsv
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#mak …

[yaml] Preserve windowing for unbounded input when using FileIO Java providers

---

sdks/python/apache_beam/transforms/environments.py

Reduce the logging severity to remove verbose logging. 

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
CHANGES.md
sdks/java/core/src/main/java/org/apache/beam/sdk/util/RowFilter.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/RowStringInterpolator.java
sdks/java/core/src/test/java/org/apache/beam/sdk/util/RowFilterTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/util/RowStringInterpolatorTest.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AssignDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/DynamicDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergIO.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergWriteSchemaTransformProvider.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/OneTableDynamicDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/PortableIcebergDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteGroupedRowsToFiles.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteToDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteUngroupedRowsToFiles.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOWriteTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergWriteSchemaTransformProviderTest.java

Fixes #32365
This PR adds support for writing to dynamic Iceberg destinations, meaning that one transform instance can write to multiple Iceberg tables.
IcebergIO is offered as a Managed transform, which makes it a portable transform. Instead of offering a function of some sort, users can specify a String template and we will substitute in the appropriate record field values to determine the destination (see [RowStringInterpolator](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/util/RowStringInterpolator.java) for more details and examples)
For more information on portable dynamic destinations, see #32365

Managed Iceberg dynamic destinations

---

sdks/python/apache_beam/transforms/core.py

Fixes #28061
Some functions are defined in a class like this:
```
class A:
@Tagging
def process():
```
The current function does not remove @Tagging because the line begins with a space, rather than directly with the @ symbol. This will lead to miss-warning of class `apache_beam.dataframe.convert.DataFrameToRowsFn` …

Fix a bug in _get_function_body_without_inners for module sdks.python.transforms.core

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProtoTest.java

We should relax our type checking and default null array values to empty arrays. This is already done for TableRows [1] and is also the behavior of GoogleSQL [2]
[1] https://github.com/apache/beam/blob/111f4c34ab2efd166de732c32d99ff615abf6064/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java#L845-L849
[2] https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array_type

[Java BQ] Default null array in Beam Row to empty array

---

sdks/python/apache_beam/transforms/combinefn_lifecycle_test.py
sdks/python/apache_beam/transforms/core.py

Deepcopy combine_fn in PrecombineFn and PostCombineFn to avoid sharing state between lifted stages when using cloudpickle.
Previously PrecombineFn and PostCombineFn  assign setup, create_accumulator attributes as references the setup, create_accumulator methods on the original combine_fn [1] passed to _CombinePerKeyWithHotKeyFanout.
When using cloudpickler with combiner lifting Precombine is split into ExtractOutputs/Merge stages in the case of FnApiRunner and as a result if these stages run in the same process the state is shared. Similarly when the BundleBasedDirectRunner is used the Precombine is split into PartialGroupByKeyCombiningValues and FinishCombine, both invoking the setup  [2][3] and teardown method.
This change ensures a new instance of the combine_fn is used in the lifted …

Deepcopy combine_fn in PrecombineFn and PostCombineFn.

---

sdks/python/apache_beam/yaml/yaml_io.py

Writing raw messages to pubsub in Beam YAML writes a string object instead of encoded bytes (which is the expected type) - this PR fixes raw messages to instead be converted to bytes format …

Fix writing raw messages to pubsub

---

sdks/java/io/expansion-service/build.gradle
sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/kafka-312/build.gradle
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java

Patch fix to include kafka client 3.1.2 in JAR that contains Kafka provider (used by Beam YAML) in case #32486 does not pass tests in time for 2.60 cut. …

[yaml] package kafka_clients 3.1.2 in Kafka Provider jar

---

sdks/python/apache_beam/transforms/combinefn_lifecycle_test.py
sdks/python/apache_beam/transforms/core.py

Reverts apache/beam#32598
deepcopy fails when a module is passed to the CombineFn as an arg.

Revert "Deepcopy combine_fn in PrecombineFn and PostCombineFn."

---

CHANGES.md
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AppendFilesToTables.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AssignDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergIO.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteGroupedRowsToFiles.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteToDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteUngroupedRowsToFiles.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOWriteTest.java

CP iceberg autosharding

---

CHANGES.md
website/www/site/content/en/blog/beam-2.59.0.md

Update CHANGES.md add 2.61.0 section and 2.59.0 known issue

---

sdks/python/apache_beam/runners/portability/prism_runner_test.py
sdks/python/pytest.ini
sdks/python/test-suites/gradle.properties
sdks/python/test-suites/portable/build.gradle
sdks/python/test-suites/portable/common.gradle
sdks/python/tox.ini

* Copies the Flink equivalent tasks.
* Validated that the validatesRunnerTests build and pass (assuming you have all the Python set up)
* Sickbayed / skipped the 3 remaining failing tests around CustomWindows and Coders for now.   
* Added target for iterating against trigger semantics. Will eventually be part of the PreCommit.
This is a required task before adding a Precommit action for running the Python suites against prism. That work will be in a separate PR.
A part of #28187.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTIN …

[#28187] Add gradle targets to execute python tests with prism.

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
CHANGES.md
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AppendFilesToTables.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FileWriteResult.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergIO.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteGroupedRowsToFiles.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteToDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteUngroupedRowsToFiles.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/RecordWriterManagerTest.java

When writing to Iceberg, we need to write just one manifest file per snapshot.
However, we are currently writing one manifest file per bundle (or one per GIB batch for streaming writes), which is a lot more frequent than needed. In medium/large streaming jobs, we can end up with thousands of extra manifest files. For an Iceberg table, the effect of this inefficiency is felt in two ways:
- Writing more files than necessary
- During query planning, having to open and read more files than necessary 
Solution:
Continue writing bundles/batches to **data files**, but stop writing manifest files at that frequency. Instead, group data files by destination then write and commit just one manifest file per destination. Essentially, the number of manifest files should be 1-1 with snapshots/commits …

[Managed Iceberg] Make manifest file writes and commits more efficient

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessorTest.java

Cherry-pick of #31663 for release 2.60 
Addresses Bug #32697
This reverts commit efee92bf02b55bee86848a9d0d291de58cb8412a.
Specific cause:
Spanner has a max number of 400 sessions in a session pool, where a session is used for a read or a write operation.
When using streaming pipelines on Dataflow with a high degree of parallelisation, where each work item can be reading from and writing to spanner, Dataflow will have up to 300 threads per worker, which potentially means 300 simultaneous read sessions, and 300 simultaneous downstream writes.
In some scenarios, this can lead to session pool exhaustion, followed by a worker failing due to this flag. …

Revert "Set setFailIfPoolExhausted in SessionPoolOptions for SpannerAccessor"

---

sdks/python/apache_beam/ml/inference/tensorrt_inference.py
sdks/python/setup.py

Fix https://github.com/apache/beam/issues/32681 …

allow numpy 2.1.x

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetCell.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/StringSetDataTest.java
sdks/python/apache_beam/metrics/cells.pxd
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/cells_test.py
sdks/python/apache_beam/metrics/execution.py
sdks/python/apache_beam/metrics/execution_test.py
sdks/python/apache_beam/metrics/monitoring_infos.py

Fix #32649
* Make StringSetData set mutable. This avoids copy and create new ImutableSet every time …

Enforce a size limit on StringSetData

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSink.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSource.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystem.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystems.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/ReadAllViaFileBasedSourceTransform.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystem.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystemTest.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/s3/S3FileSystem.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/s3/S3FileSystemTest.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystem.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystemTest.java
sdks/java/io/azure/src/main/java/org/apache/beam/sdk/io/azure/blobstore/AzureBlobStoreFileSystem.java
sdks/java/io/azure/src/test/java/org/apache/beam/sdk/io/azure/blobstore/AzureBlobStoreFileSystemTest.java
sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java
sdks/python/apache_beam/io/aws/s3filesystem.py
sdks/python/apache_beam/io/aws/s3filesystem_test.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem_test.py
sdks/python/apache_beam/io/filebasedsink.py
sdks/python/apache_beam/io/filebasedsource.py
sdks/python/apache_beam/io/filesystem.py
sdks/python/apache_beam/io/filesystems.py
sdks/python/apache_beam/io/gcp/gcsfilesystem.py
sdks/python/apache_beam/io/gcp/gcsfilesystem_test.py

supercedes #32642
- FileBasedSource will report **every** read-in file if number of file <= 100
- FileBasedSource will report **every** unique directory (one level up) if number of file > 100 but number of unique directory <= 100
- FileBasedSource will report bucket otherwise
- ReadAll will report **every** file if number of file <= 100
- ReadAll will report bucket otherwise
- FileBasedSink will report **every** write-to file if shards <= 100
- FileBasedSink (for each destination) will report **single** directory to write if number of file > 100
In contrast to read, we are able to report single directory because shards are in the same directory. …

Report File Lineage on directory

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkState.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutor.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutorTest.java

Thread.setName is expensive and uses upto 4% cpu on jobs with many keys.

[Dataflow Streaming] Remove call to Thread.setName and track thread name inside Work.

---

sdks/python/apache_beam/transforms/combinefn_lifecycle_pipeline.py
sdks/python/apache_beam/transforms/combinefn_lifecycle_test.py
sdks/python/apache_beam/transforms/core.py

Roll forward with https://github.com/apache/beam/pull/32598 + fix the copy behavior if a module is being copied. …

Try deepcopy combine_fn and fallback to pickling if TypeError.

---

.github/trigger_files/beam_PostCommit_Java_IO_Performance_Tests.json
.github/workflows/beam_PostCommit_Java_IO_Performance_Tests.yml

The test of `PostCommit Java IO Performance Tests` has been permred:
https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_IO_Performance_Tests.yml
The error message is as follows.
```
Run google-github-actions/auth@v2
Created credentials file at "/runner/_work/beam/beam/gha-creds-839d6022ed8787fc.json"
Error: google-github-actions/auth failed with: failed to generate Google Cloud OAuth 2.0 Access Token for ahmedabualsaud-test@clouddfe.google.com.iam.gserviceaccount.com: ***
"error": ***
"code": 401,
"message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
"status": "UNAUTHENTICATED"
***
***
```
I noticed that …

Attempt to fix the permred "PostCommit Java IO Performance Tests"

---

sdks/python/apache_beam/runners/interactive/dataproc/dataproc_cluster_manager.py
sdks/python/apache_beam/runners/interactive/interactive_beam.py

see https://github.com/apache/beam/pull/32737 for more details …

Checky-pick https://github.com/apache/beam/pull/32737/

---

sdks/python/scripts/run_snapshot_publish.sh

Since setuptools 69.3.0,  the distribution name of a package has been normalized according to https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode to support PEP 625 (https://github.com/pypa/setuptools/commit/b0135f5097f32a27b7a14e2c6296ba14bcb4e10b). 
In our case, the source and  binary distribution name would be changed from `apache-beam` to `apache_beam`.
This PR is to fix the script for publishing python snapshot so that the file can be published to gcs.
fixes #32729
related thread: #30955

Fix the snapshot publishing script

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/scripts/generate_pydoc.sh
sdks/python/setup.py
sdks/python/tox.ini

Updates the Pydoc precommit script to work on 3.9 with updated dependencies, process new doc formatting correctly. Will need a second pass to clean up some warnings, but this unblocks the 2.60.0 release pydoc generation
Fixes #32728 …

Fix Pydoc Precommit

---

.github/workflows/build_release_candidate.yml
.github/workflows/build_wheels.yml

Fix build_wheels and build_release_candidate

---

sdks/python/container/boot.go

Fix https://github.com/apache/beam/issues/32743 …

Do not fail the job when submission_environment_dependencies.txt cannot be loaded

---

CHANGES.md
website/www/site/content/en/blog/beam-2.52.0.md

I found this while trying to debug an upgrade issue; I don't think there's anything to be done about it at this point, but it is worth calling out. …

Add 2.51->52 breaking incompatibility to CHANGES.md

---

sdks/java/expansion-service/build.gradle
sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java
sdks/java/extensions/sql/expansion-service/build.gradle
sdks/java/io/expansion-service/build.gradle
sdks/python/apache_beam/io/filesystems.py

disable expansion service cache

---

.github/workflows/build_release_candidate.yml
.github/workflows/build_wheels.yml

* Fix build_wheels and build_release_candidate
[![Build …

[Release 2.60.0] Cherry-pick #32725 into release branch

---

sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/scripts/generate_pydoc.sh
sdks/python/setup.py
sdks/python/tox.ini

[Release-2.60.0] cherry-pick #32747 into release branch

---

sdks/java/io/mqtt/src/test/java/org/apache/beam/sdk/io/mqtt/MqttIOTest.java

fixes #32764 
This PR contains these changes
- fix flaky test
- extract common method for connect to Mqtt …

Fix flaky mqtt test

---

.github/trigger_files/beam_PostCommit_Java_PVR_Spark_Batch.json
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystems.java
sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipeline.java

Fix #30512
Random tests in this test suite failing due to tmp file get deleted half way, likely a racing condition.
This is a longstanding and tricky issue, see earlier investigation in
https://github.com/apache/beam/issues/30512#issuecomment-2402923733
as the validate runner test set adds//enables more tests, the test becomes increasingly flaky.
In TestPipeline scenario, it is found that setDefaultPipelineOptions is called at least twice
1. When TestPipelineOptions object is created: https://github.com/apache/beam/blob/4cf99ea31aa2f3b4e8fa0da479939bbe92bd46dd/sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipeline.java#L518
2. Right before pipeline runs : https://github.com/apache/beam/blob/4cf99ea31aa2f3b4e8fa0da479939bbe92bd46dd/sdks/java/core/src/main/java/org/apache/beam …

Reduce setDefaultPipelineOptions call on creating TestPipelineOptions

---

sdks/python/apache_beam/transforms/core.py

Fixed up the `.with_exception_handling()` docstring. The main issue is that the example didn't actually pipe the transform into anything, which was confusing when I and another user were looking at it.
I also replaced "record" with "input". AFAICT, most of the Beam python docs don't refer to elements as "records".

Polish .with_exception_handling docstring

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/apache_beam/ml/inference/vllm_inference.py

Because of how vLLM does batching, it is much more efficient if you're able to push as many requests to it as possible so that it can make the appropriate batching decision. Right now, per worker thread we send requests serially; this fixes that inefficiency by sending all data asynchronously to the vLLM server and then awaiting the response.
Fixes #32528 …

vLLM model handler efficiency improvements

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/AutoValueSchema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FieldValueTypeInformation.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/JavaBeanSchema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/JavaFieldSchema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaProvider.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaRegistry.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/providers/JavaRowUdf.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/AutoValueUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ByteBuddyUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ConvertHelpers.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/JavaBeanUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/POJOUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ReflectUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/StaticSchemaInference.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/AutoValueSchemaTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/JavaBeanSchemaTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/JavaFieldSchemaTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/JavaBeanUtilsTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/POJOUtilsTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/TestJavaBeans.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/TestPOJOs.java
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroByteBuddyUtils.java
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java
sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java
sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoMessageSchema.java
sdks/java/extensions/python/src/main/java/org/apache/beam/sdk/extensions/python/PythonExternalTransform.java
sdks/java/io/thrift/src/main/java/org/apache/beam/sdk/io/thrift/ThriftSchema.java

Beam automatically infers schema for common Java types: POJOs, JavaBean, AutoValue, AVRO, among others. In addition for it's use with schema transforms, this also provides a simple, efficient way of using these types in PCollections without needing to construct a Coder. A frequent complaint has been that this inference did not work in the presence of generic type parameters. E.g. this means that while Beam can handle PCollections of this class:
@DefaultSchema(JavaFieldSchema.class)
class MyType {
String field1;
}
PCollection<MyType> myTypes = read();
Schema inference would fail for this:
@DefaultSchema(JavaFieldSchema.class)
class MyType\<T\> {
T field1;
}
PCollection<MyType<String>> myTypes = read();
This PR adds support for generic type parameters to schema inference for common types, …

Schema inference parameterized types

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/apache_beam/transforms/enrichment_handlers/bigquery.py
sdks/python/apache_beam/transforms/enrichment_handlers/bigquery_it_test.py

Fix the following BigQuery enrichment transform issues
1. Conditions on more than one field returns duplicate rows
2. Batching returns incorrect results (checks equality of restriction field on all columns of the returned data)
3. Batched_condition_template does not wrap conditions in parenthesis
Issues 1 and 2 are fixed by keying batched requests by a tuple of values.
Issue 3 is fixed by wrapping conditions in parenthesis. 
Also modify integration tests to 
1. Set up and tear down a new table on each test
2. Add test cases for above mentioned issues
3. Verify actual enriched pcollection output …

Bigquery fixes

---

it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java

Fix StressTests Java BigQueryIO job flakiness

---

sdks/python/apache_beam/yaml/integration_tests.py
sdks/python/apache_beam/yaml/standard_providers.yaml
sdks/python/apache_beam/yaml/tests/enrichment.yaml
sdks/python/apache_beam/yaml/yaml_enrichment.py
sdks/python/apache_beam/yaml/yaml_enrichment_test.py
sdks/python/apache_beam/yaml/yaml_provider.py

1. Added enrichment transform 
2. Registered it in standard_providers.yaml
3. Added integration and unit tests for enrichment transform …

[yaml] Add enrichment transform to Beam YAML

---

CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubJsonClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubTestClient.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClientTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubJsonClientTest.java

fix: https://github.com/apache/beam/issues/18027
adding validation to check topic exist or not for PubsubIO
previous [PR](https://github.com/apache/beam/pull/32465) validation is default. But this disable default.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_ …

feat: add pubsub topic validation

---

sdks/python/pyproject.toml

Reverts apache/beam#32773
No need to do this. This is only needed when installing the Python build system. If we use `python -m build --sdist` to install the Beam package, the build system should be created with another Python env, which should not impact the Beam dependencies.

Revert "Update pyproject.toml by using grpcio-tools==1.65.5"

---

sdks/python/apache_beam/yaml/yaml_enrichment.py

Currently, the yaml enrichment pydoc is causing precommit failures. This fixes that problem and also links out to the handler docs instead of duplicating them inline.
Example failure before my change …

Enrichment pydoc improvements

---

.github/workflows/beam_PostRelease_NightlySnapshot.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
release/src/main/groovy/TestScripts.groovy

mitigate #32824 ; mitigate #32808
The task runs 8 individual tasks in parallel, each spins up a fresh local maven repository, likely get rate limited by maven repository server …

Using single temp maven local repository for release validation tasks

---

sdks/python/apache_beam/yaml/tests/map.yaml

Fix failing YAML mapping IT

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/GlobalDataStreamSender.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingEngineBackends.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/WindmillStreamSender.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillEndpoints.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillServiceAddress.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/WindmillStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillStreamFactory.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillChannelFactory.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/budget/EvenGetWorkBudgetDistributor.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/budget/GetWorkBudgetDistributors.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/budget/GetWorkBudgetSpender.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/FakeWindmillServer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/WindmillStreamSenderTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/budget/EvenGetWorkBudgetDistributorTest.java

Remove the budget distributor thread and move the managing of each server's internal budget to the direct GetWorkStream.
R: @arunpandianp @scwhittle  …

Simplify budget distribution logic and new worker metadata consumption

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamDockerPlugin.groovy
runners/google-cloud-dataflow-java/build.gradle

Closes #32819 enabling [BuildKit](https://docs.docker.com/build/buildkit/) via Gradle `:docker` task defined in [buildSrc/src/main/groovy/org/apache/beam/gradle/BeamDockerPlugin.groovy](https://github.com/apache/beam/blob/master/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamDockerPlugin.groovy).
Prior to creating PR, validated via running `:sdks:go:container:docker`, `:sdks:Java:container:java11:docker`, `:sdks:python:container:py311:docker`,  `:runners:google-cloud-dataflow-java:validatesRunnerV2`, and `:runners:google-cloud-dataflow-java:validatesCrossLanguageRunnerPythonUsingPython`. The Dataflow validates runner tests detect errors in the container image build as a result of using BuildKit within an Job execution context. …

Enable BuildKit on gradle docker task

---

sdks/python/apache_beam/runners/direct/direct_runner.py
sdks/python/apache_beam/runners/portability/prism_runner.py

This change does two tasks:
* Enables Python SDK developers to have prism automatically build and run locally using local changes to Prism when using PrismRunner.
* Sets Prism to be attempted to be used in the Python DirectRunner in some circumstances.
The main change is to the prism_runner behavior when the SDK reports a `.dev` version.
In that case:
* Try to `go install github.com/apache/beam/sdks/v2/go/cmd/prism` to the binary cache directory.
* If that doesn't succeed, inspect the output for module errors 
* If there are no *module* errors, then the local version of prism couldn't compile, OR go isn't installed. Either way, this is a developer addressable error.
* If there are module errors, then those modules don't have access to a version of Beam Go, so instead install the latest …

[prism] Dev prism builds for python  and Python Direct Runner fallbacks. 

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDispatcherClient.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDispatcherClientTest.java

Remove experiments guarding isolated channels enablement based on job settings

Remove experiments guarding isolated channels enablement based on jobsettings

---

website/www/site/content/en/documentation/sdks/yaml-errors.md

Update docs on error handling output schema.

---

runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverter.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/StageInfo.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaMetrics.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetrics.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaMetricsTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetricsTest.java

Add per worker metric for Kafka poll latency. This is specifically for Dataflow V1 runner.
Next steps would be to extend this to add latency for other RPC calls. …

Kafka metrics

---

.github/workflows/beam_PreCommit_Java.yml
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteTables.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/RpcQos.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/RpcQosImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubWriteSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteWriteSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerWriteSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangestreamsReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/BaseFirestoreV1WriteFnTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/FirestoreV1FnBatchWriteWithDeadLetterQueueTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/FirestoreV1FnBatchWriteWithSummaryTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/RpcQosSimulationTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/RpcQosTest.java
sdks/java/javadoc/build.gradle

Pin PreCommit Java to Java8 for now due to #32208 and #32911
change "failOnError" to false for Javadoc workflow due to #32726. It appears this flag didn't work for Java8 (see #32726)
GCP_IO precommits failed due to 
```
Mockito cannot mock this class: interface org.apache.beam.sdk.io.gcp.firestore.RpcQos$RpcWriteAttempt
Caused by: java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface org.checkerframework.checker.nullness.qual.UnknownKeyFor: @org.checkerframework.checker.nullness.qual.UnknownKeyFor()
```
in Firestore tests.
I think this is a mockito + checkframework + Java11 incompatibility bug, however not able to adjust dependency to resolve it. Removed one of the two generic argument in `RpcWriteAttempt.newFlushBuffer` magically resolved the issue …

Test fix after runner bump to Java11

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Sync version with GCP libraries, pulling 1.17.1
https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/26.45.0/index.html

Update commons-codec to 1.17.1

---

examples/notebooks/beam-ml/run_inference_vllm.ipynb

Follow up now that #32528 is completed and released to create a notebook showing how to use vLLM …

Add a vLLM notebook

---

.github/workflows/beam_PreCommit_Java_PVR_Prism_Loopback.yml
runners/prism/build.gradle
runners/prism/java/build.gradle
runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismExecutor.java
runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismLocator.java
runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismPipelineOptions.java
runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismRunner.java
runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismLocatorTest.java
sdks/go/cmd/prism/prism.go

* Add a Java gradle task to run validates runner tests on Prism.
* Filtered to green tests. Added notes about what's broken with them, along with links to pertinent issues.
* Broken tests that will terminate are in the sickbay list, to separate data, from configuration.
* Add log_level filtering to prism. It was easier to have the Java PrismRunner wrapper re-launch the binary all the time. Set Java default to warning log. Can be overridden by a `--prismLogLevel` flag. Replaces the recently added `--debug` flag. 
* Add a Gradle Action to run as Precommit.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make …

[#28187] Add a Java gradle task to run validates runner tests on Prism.

---

sdks/go/test/integration/io/xlang/debezium/debezium_test.go
sdks/java/io/debezium/src/test/java/org/apache/beam/io/debezium/DebeziumIOPostgresSqlConnectorIT.java
sdks/java/io/debezium/src/test/java/org/apache/beam/io/debezium/DebeziumReadSchemaTransformTest.java
sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOIT.java
sdks/python/apache_beam/io/external/xlang_debeziumio_it_test.py

For DebeziumIO PreCommit, it's due to https://debezium.io/blog/2023/04/25/container-images-quayio/
For JmsIO PreCommit, it appears tests run on Java11 experiences elevated number of unack message
GitHub …

Fix DebeziumIO JmsIO PreCommit

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteBundlesToFiles.java

Investigating an issue that is causing our WriteBundlesToFiles to swallow errors. In the worst case, this can lead to data-loss because we don't retry these errors. This is a potential candidate for where this swallowing might happen. We're also realizing it doesn't make too much sense to put a try-block here

Don't swallow BQ file loads writer errors 

---

sdks/python/apache_beam/typehints/row_type.py
sdks/python/apache_beam/typehints/schemas.py
sdks/python/apache_beam/typehints/schemas_test.py

#29561 introduced the ability to persist Field descriptions defined in Cross-language transform configs as shown here: https://github.com/apache/beam/blob/80c7450f77f58c9e02087cc578ad8abe07648736/sdks/python/apache_beam/typehints/schemas.py#L546-L570
However, this information is dropped when converting the NamedTuple (parsed from the proto) into a `RowTypeConstraint` type.
This PR propagates this optional data so that when converting from `RowTypeConstraint` to `schema_pb2.Schema` (runner_api), the field descriptions can be included in the proto.
---
This is also helpful for Beam YAML auto documentation which attempts to use the description field from the `schema_pb2.Schema`, but is not populated by default. After this change, the auto documentation can pull in decsriptions for …

Propogate field_descriptions to RowTypeConstraint

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/AutoValueSchema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/CachingFactory.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FieldValueGetter.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FieldValueTypeInformation.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/GetterBasedSchemaProvider.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/GetterBasedSchemaProviderV2.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/JavaBeanSchema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/JavaFieldSchema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/AutoValueUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ByteBuddyUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/JavaBeanUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/POJOUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/ReflectUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/common/ReflectHelpers.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/Row.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/RowWithGetters.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/FieldValueTypeInformationTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/JavaBeanUtilsTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/POJOUtilsTest.java
sdks/java/extensions/arrow/src/main/java/org/apache/beam/sdk/extensions/arrow/ArrowConversion.java
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/AvroRecordSchema.java
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java
sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java
sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoMessageSchema.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/schemas/AwsSchemaProvider.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/schemas/AwsSchemaUtils.java
sdks/java/io/thrift/src/main/java/org/apache/beam/sdk/io/thrift/ThriftSchema.java

This is a 2nd PR in the series of PRs (based on the now closed #31648, with the first PR being #31785) whose ultimate goal is to add support for generic classes to schema providers. 
`FieldValueTypeInformation` creators will now accept a `TypeDescriptor` parameter describing the field's containing class, that will let them infer more accurate type information about that field. For example - consider a `MyClass<T>` class - now with a `TypeDescriptor` of `MyClass<String>` and the getter of type `T` the type resolver can infer the type of field to be `String` , see the added test class that shows the new functionality …

make FieldValueTypeInformation creators take a TypeDescriptor parameter

---

.github/trigger_files/beam_PostCommit_Java_PVR_Flink_Batch.json
.github/trigger_files/beam_PostCommit_Java_PVR_Flink_Docker.json
.github/trigger_files/beam_PostCommit_Java_PVR_Spark3_Streaming.json
.github/trigger_files/beam_PostCommit_Java_PVR_Spark_Batch.json
runners/flink/job-server-container/Dockerfile
runners/spark/job-server/container/Dockerfile

openjdk images have been long deprecated: https://hub.docker.com/_/openjdk …

Bump Flink and Spark job server container base imager to tumerin-11

---

.github/workflows/self-assign.yml

Right now, if the awaiting triage label doesn't exist on an issue we fail the assignment workflow. This fixes the problem by silently swallowing errors. Example - https://github.com/apache/beam/actions/runs/11617248390 …

Swallow errors removing awaiting triage label

---

sdks/python/apache_beam/internal/dill_pickler.py
sdks/python/apache_beam/internal/pickler_test.py

Apache Beam does the following:
- Pickle Python code
- Send the pickled source code to "worker" VMs
- The workers unpickle and execute the code
In the environment that these Beam pipelines execute, the source code is in a temporary directory whose name is random and changes. The source code paths relative to the temporary directory are constant. Using absolute paths prevents pickled code from being cached because the absolute path keeps changing. Using relative paths enables this caching and promises significant resource savings and speed-ups.
Additionally the absolute paths leak information about the directory structure of the machine pickling the source code. When the pickled code is passed across the network to another machine, the absolute paths may no longer be valid when the other …

Support caching in Apache Beam by using relative co_filename paths.

---

sdks/python/apache_beam/ml/inference/onnx_inference.py

This method was removed from onnx, so we should not rely on it. This pulls the main pieces of it out from https://github.com/onnx/onnx/blob/994c6181247d7b419b28889fc57d5817e2089419/onnx/__init__.py#L56
Fixes #32998 …

Remove usage of deprecated _serialize

---

sdks/python/apache_beam/yaml/json_utils.py
sdks/python/apache_beam/yaml/yaml_mapping.py
sdks/python/apache_beam/yaml/yaml_mapping_test.py

[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/ba …

Add a simple validation transform to yaml.

---

playground/backend/internal/preparers/python_preparers.go
playground/backend/internal/preparers/python_preparers_test.go
sdks/python/apache_beam/transforms/ptransform_test.py

I get a lot of complaints about all the logging in Beam playground for python examples. It really drowns out any output that might be coming from the examples.
I attempted to just remove the logging altogether for the python examples here, though I have no way of testing it.
My rationale is that the Beam playground environment doesn't really make sense to have logging for. If something goes wrong with an example, it makes a lot more sense to just copy and paste the example into your local Beam environment and debug it there (and optionally turn on logging in your own environment).

Remove beam logging in playground for Python

---

sdks/java/io/snowflake/build.gradle

Snowflake stopped JDBC pilot support up to 3.13.27, so update it to latest 3.20.0 version. 
[![Java …

Update snowflake-jdbc to 3.20

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
CHANGES.md
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AppendFilesToTables.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FileWriteResult.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteToDestinations.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/RecordWriterManagerTest.java

Users may update the table's spec while a write pipeline is running (e.g. streaming). Sometimes, this update can happen after serializing DataFiles. The partition spec is not serializable so we don't preserve it, but we do keep its ID. We can use this information to fetch the correct partition spec and recreate the DataFile before appending to the table.
Fixes #32862

[Managed Iceberg] Allow updating partition specs during pipeline runtime

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/WeightedBoundedQueue.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/WeightedSemaphore.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/Commits.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingApplianceWorkCommitter.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingEngineWorkCommitter.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/WeightBoundedQueueTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingEngineWorkCommitterTest.java

Factor out semaphore logic out of WeightBoundedQueue to allow for sharing the weigher
R: @scwhittle  …

extract semaphore logic out of WeightBoundedQueue to allow for sharing the weigher

---

sdks/go/container/tools/buffered_logging.go
sdks/python/container/boot.go

Adds a default flush interval of 15 seconds to the BufferedLogger type to avoid logs being held until the job ends.  …

Add Flush Interval to default Buffered Logger 

---

sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/KafkaTestTable.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaMocks.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

Use `endOffsets` instead of `seekToEnd` and `position` to determine the backlog element size in `KafkaUnboundedReader` and `ReadFromKafkaDoFn`. Determining the end offsets by seeking and retrieving the position may trigger `poll` and prefetch records which will never be consumed by the offset consumer.
Forcibly retrieving the partition's high watermark in offset consumers might not be necessary, but this will be addressed separately.
To check …

[KafkaIO] Determine partition backlog using endOffsets instead of seek2End and position

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java

The `closed` property is never read by the instance and its `isClosed` getter is never called externally. The `isClosed` getter would never be observed to return `true` since `finalize` is called after the VM has determined that no thread holds a strong reference to the instance.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/ …

[KafkaIO] Remove unused property, assignment in finalize will not be observed

---

runners/direct-java/build.gradle
sdks/java/core/build.gradle

Alternative fix of #32696
We already vendored and repackaged antlr runtime into the jar. It was intended to avoid dependency version conflict if user using different antlr versions. However, beam java core still declares it as a dependency.
Before:
java core pom has antlr4-runtime dependency, e.g. in https://repo1.maven.org/maven2/org/apache/beam/beam-sdks-java-core/2.60.0/beam-sdks-java-core-2.60.0.pom
```
<dependency>
<groupId>org.antlr</groupId>
<artifactId>antlr4-runtime</artifactId>
<version>4.7</version>
<scope>compile</scope>
```
after:
ran `./gradlew :sdks:java:core:publishToMavenLocal -Ppublishing` and checked that antlr-runtime is no longer a dependency of beam java core in generated pom.
Also checked the jar still repackaged antlr runtime in …

Remove antlr from dependency from java-core pom

---

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/WithKeysTest.java

I can't find the presubmit I observed this but it was this log:
https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/util/MutationDetectors.java#L146
This Pojo uses SchemaCoder which is consistentWithEquals, meaning Coder.structuralValue returns the value itself. Since this Pojo didn't have equals method it woudl trigger the log on equivalent pojos with the same encoding but different objects.
To check the …

Add equals/hashcode to test data class to avoid direct runner coder warning

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/construction/PipelineOptionsTranslation.java
sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java
sdks/java/expansion-service/src/test/java/org/apache/beam/sdk/expansion/service/ExpansionServiceTest.java

This fixes https://github.com/apache/beam/issues/33022. …

Update Java ExpansionService to use arbitrary PipelineOptions set through an ExpansionRequest

---

.github/trigger_files/beam_PostCommit_Java_Hadoop_Versions.json
sdks/java/io/hadoop-common/build.gradle
sdks/java/io/hadoop-file-system/build.gradle
sdks/java/io/hadoop-format/build.gradle
sdks/java/io/hcatalog/build.gradle
sdks/java/io/iceberg/build.gradle
sdks/java/io/parquet/build.gradle

In preparation of upgrading hadoop version in BeamModulePlugin
hadoop 2.8.x and 2.9.x last release were in 2018, both were eol. Current supported hadoop version is 3.3.x and 3.4.x
DataflowTemplates already uses 3.4: https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/1c6d07be4b222a4c21d331e48ed72a70f0089cbe/pom.xml#L67 …

Bump Hadoop versions for compatibility test

---

sdks/python/apache_beam/runners/common.py

Right now, PreCommit Python is persistently red - https://github.com/apache/beam/actions/workflows/beam_PreCommit_Python.yml?query=event%3Aschedule
When this goes red, we see the following errors:
```
Traceback (most recent call last): |  
  | File "apache_beam/runners/common.py", line 1501, in apache_beam.runners.common.DoFnRunner.process |  
  | return self.do_fn_invoker.invoke_process(windowed_value) |  
  | File "apache_beam/runners/common.py", line 689, in apache_beam.runners.common.SimpleInvoker.invoke_process |  
  | self.output_handler.handle_process_outputs( |  
  | File "apache_beam/runners/common.py", line 1687, in apache_beam.runners.common._OutputHandler.handle_process_outputs |  
  | self._write_value_to_tag(tag, windowed_value, watermark_estimator) |  
  | File …
```

Fix exception sampling logic

---

sdks/python/apache_beam/transforms/external_test.py

These depend on https://github.com/apache/beam/blob/47740d07ed9e0824b4975ca4cadece74aae38302/sdks/python/apache_beam/transforms/external.py#L1007 which can lead to errors like:
```
def test_classpath(self):
with tempfile.TemporaryDirectory() as temp_dir:
try:
oldwd = os.getcwd()
os.chdir(temp_dir)
with open('a1.jar', 'w') as _:
pass
service = JavaJarExpansionService(
'main.jar', classpath=['a*.jar', 'b.jar'])
>         self.assertEqual(
service._default_args(),
['{{PORT}}', '--filesToStage=main.jar,a1.jar,b.jar'])
E             AssertionError: Lists differ: ['{{P[13 chars]lesToStage=main.jar,a1.jar,b.jar', '--alsoStartLoopbackWorker'] != ['{{P[13 chars]lesToStage=main.jar,a1.jar,b.jar']
E             
E             First list contains 1 additional elements.
E             First extra …
```

Remove nondeterminism from expansion tests

---

runners/flink/job-server-container/Dockerfile
website/www/site/content/en/documentation/runners/flink.md

Tested this locally by building the `beam-flink-runner` container image and running the simple test.
Created `flink-conf/flink-conf.yaml` and the yaml file contains:
```
parallelism.default: 23
taskmanager.memory.network.fraction: 0.2
taskmanager.memory.network.max: 2gb
```
Then started the container:
```
docker run --net=host -v /path/flink-conf:/flink-conf beam-flink-runner
```
Simple test:
```python
from apache_beam.options.pipeline_options import PipelineOptions
options = PipelineOptions([
"--runner=PortableRunner",
"--job_endpoint=localhost:8099",
"--environment_type=LOOPBACK"
])
with beam.Pipeline(options=options) as pipeline:
elements = pipeline | beam.Create([1, 2, 3, 4, 5])
elements | 'Print elements' >> beam.Map(print)
``` …

Fixed the broken beam python on flink with PortableRunner

---

website/www/site/content/en/documentation/runtime/environments.md
website/www/site/content/en/documentation/sdks/python-sdk-image-build.md
website/www/site/layouts/partials/section-menu/en/sdks.html

This is a guide for users who needs customized Python SDK image. b/375969331 …

Add a guide to build custom Beam Python SDK image

---

sdks/java/core/src/main/java/org/apache/beam/sdk/fn/data/BeamFnDataGrpcMultiplexer.java
sdks/java/core/src/test/java/org/apache/beam/sdk/fn/data/BeamFnDataGrpcMultiplexerTest.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/BeamFnDataClient.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/BeamFnDataGrpcClient.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/PTransformRunnerFactoryTestContext.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/data/BeamFnDataGrpcClientTest.java

Previously it could occur that an instruction id was observed on the control stream but due to exception it would never register a handler and the data stream would be forever blocked trying to multiplex elements to it's queue.
Fixes #32714 …

Support poisioning instruction ids to prevent the FnApi data stream from blocking on failed instructions

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/container/Dockerfile
sdks/python/container/common.gradle
sdks/python/test-suites/dataflow/build.gradle
sdks/python/test-suites/dataflow/common.gradle
sdks/python/test-suites/gradle.properties

The PR is causing PostCommit Python to fail(https://github.com/apache/beam/actions/workflows/beam_PostCommit_Python.yml) . I tried to fix it with #33083, but I did not get a clean test result. Trying to see if reverting it can make the test green.
#address #30513

Revert PR #32960

---

sdks/python/apache_beam/transforms/enrichment_handlers/bigquery.py
sdks/python/apache_beam/transforms/enrichment_handlers/bigtable.py
sdks/python/apache_beam/transforms/enrichment_handlers/bigtable_it_test.py
sdks/python/apache_beam/transforms/enrichment_handlers/feast_feature_store.py
sdks/python/apache_beam/transforms/enrichment_handlers/feast_feature_store_it_test.py
sdks/python/apache_beam/transforms/enrichment_handlers/vertex_ai_feature_store.py

Updates type hints to PEP 585 standards.
Part of #32969  …

Update Enrichment Handlers to PEP 585 typing

---

CHANGES.md
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java
sdks/python/apache_beam/io/jdbc.py

Addresses #31111
Adding flag to conditionally disable auto-commit for JdbcIO read due to current incompatibility with Informix database.  …

[JdbcIO] Adding disableAutoCommit flag

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java

This reverts #31137 and #31281. The changes in the former PR overwrite the per-split metric `backlog_bytes.${SPLIT}` with the per-partition metric rather than the accumulated value for the split. The latter PR introduced a map to store metrics for all past and current splits (1 partition) of the `ReadFromKafkaDoFn` instance and may repeatedly overwrite non-current splits with stale values. The map used to store these values is not thread-safe and may trigger a `ConcurrentModificationException` since `GetSize` and other SDF methods may concurrently attempt to read and write the map.
Finally, the per-split caches kept by the instance are keyed on `TopicPartition`, which is not unique among all splits since the split may override the bootstrap server. This has been fixed for this cache, all …

[KafkaIO] Fix per-split metric updates for KafkaUnboundedReader and ReadFromKafkaDoFn

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystems.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/DelegatingCounter.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Metrics.java
sdks/java/core/src/test/java/org/apache/beam/sdk/metrics/MetricsTest.java

Introduce pipeline options to disable user counter and user stringset

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java

This change adds shared caches among unique instances of `ReadFromKafkaDoFn`, identified by a static `AtomicLong` which is stored as an instance field and incremented during construction of the `DoFn`. The constructor is bypassed during deserialization at execution time, thus providing a shared identifier for all instances of `ReadFromKafkaDoFn` for a single transform.
Note: this PR is stacked on top of #32921, #32920 and #32889
To check the …

[KafkaIO] Share size and offset estimators among ReadFromKafkaDoFn instances per PTransform

---

sdks/python/apache_beam/yaml/standard_io.yaml
sdks/python/apache_beam/yaml/tests/map.yaml

Refactor standard_io.yaml to use snake_case for JDBC providers.
There was a change to the naming convention used by the cross-language service here: https://github.com/apache/beam/pull/31374/
which also migrated most of the YAML provider definitions to use the new format. Unfortunately, JDBC providers that inherit the top-level JDBC Provider (MySQL, Postgres, Oracle and Sql Server) were missed. This causes YAML pipelines who use these transforms to fail when the `jdbc_type` (formerly `jdbcType`) config parameter is parsed during expansion.
This PR refactors these transform config parameters to use the new snake_case naming convention.
See the …

fix JDBC providers

---

examples/java/src/main/java/org/apache/beam/examples/subprocess/ExampleEchoPipeline.java
examples/java/src/main/java/org/apache/beam/examples/subprocess/Readme.MD

Fixes https://github.com/apache/beam/issues/33104 by clarifying how to run the pipeline. 
**Validated pipeline on Dataflow Runner:**
**Rendered Preview** …

Adds detailed instructions on how to execute ExampleEchoPipeline.java

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryManagedIT.java

BigQueryManagedIT.testBatchDynamicDestinations and BigQueryManagedIT.testBatchFileLoadsWriteRead failing because requires gcs temp location. …

Add temp location to  batch file loads

---

.github/workflows/build_release_candidate.yml

The docker step is failing on hosted, it seems like because of connectivity issues - https://github.com/apache/beam/actions/runs/11826936978
This fixes the problem + it just is probably better for us to keep this on our own highmem machines anyways. After this change, I could run the action - https://github.com/apache/beam/actions/runs/11838213683/job/32986838541 …

Build docker RC on self-hosted

---

runners/core-java/build.gradle
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoEncodings.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MonitoringInfoEncodingsTest.java
sdks/java/core/build.gradle
sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java
sdks/java/harness/build.gradle

Add ability to encode and decode histogram data to portable runners
https://github.com/apache/beam/issues/33090 …

Add ability to encode and decode histogram data to portable runners

---

.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Dataflow.json
.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Direct.json
sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/transforms/managed_iceberg_it_test.py

Enable Dataflow managed backend service for python managed tests

Enable Dataflow managed service for Python tests

---

sdks/java/core/src/main/java/org/apache/beam/sdk/Pipeline.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/CoderRegistry.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaRegistryTest.java

This reverts commit c243491254896e039e912662e4cfbe4bd38c766f.
Cherry-pick of https://github.com/apache/beam/pull/33133 …

CP: Revert "Merge pull request #32705: fix schema inference for parameterized types" (#33133)

---

sdks/python/apache_beam/ml/transforms/base_test.py

Use random gcs bucket name to ensure it does not exist. …

Use random gcs bucket name

---

.github/trigger_files/beam_PostCommit_Python_Xlang_Gcp_Dataflow.json
.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Dataflow.json
.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Direct.json
sdks/python/apache_beam/transforms/external.py

* plug annotations thru
* trigger xlang tests
[![Build …

CP: Plug transform annotations thru cross-lang interface (#33150)

---

sdks/python/apache_beam/coders/coder_impl.py

This fixes https://github.com/apache/beam/pull/33137 …

Don't use __getstate__ for pickling for objects with a custom __reduce__.

---

it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/WordCountIT.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java

Fixes #32531
The proposed changes are only limited to DataflowRunner and are kept simple. When a GCS file is detected in `filesToStage`, we first download this to a local temp file and replace the GCS file with this local temp file.
- Added functionality to handle GCS files in `replaceGcsFilesWithLocalFiles()` method
- Files with GCS paths (gs://) are now downloaded to local temp files before being staged
- Maintains original file names when downloading from GCS
- Handles both files with and without staging names specified
- Adds logging for file downloads and replacements
- Temp files are created with same names as original GCS files for consistency
- Files are downloaded using FileSystems API for proper GCS integration
- Original functionality for local files is preserved unchanged
- …

Added replaceGcsFilesWithLocalFiles

---

.github/gh-actions-self-hosted-runners/arc/config/arc_autoscaler.tpl
.github/gh-actions-self-hosted-runners/arc/environments/beam.env
.github/workflows/beam_PostCommit_Python_Examples_Flink.yml

- Adds a new runner named `highmem22` based on `c3-highmem-22` node
- Adds `TotalNumberOfQueuedAndInProgressWorkflowRuns` to the runner autscaler metrics list. This will allow to scale from zero as `PercentageRunnersBusy` cannot do that. This metrics is only considered if number of runners is zero and allows to start the scaling. 
- Moves `PostCommit_Python_Examples_Flink` to `highmem22` …

Highmem22 runners

---

examples/notebooks/beam-ml/run_inference_vllm.ipynb

In https://github.com/apache/beam/pull/32687 I updated the vLLM model handler to use an asyncio event loop. This led to huge efficiency gains (around <batch_size>x faster), but also broke it in environments where there is already an asyncio event loop because of https://stackoverflow.com/questions/55409641/asyncio-run-cannot-be-called-from-a-running-event-loop-when-using-jupyter-no
This is generally fine (this is not a normal environment to run Beam), but it does break things for colab environments. It can be easily fixed with this tweak, though - this PR makes that tweak to our example so that this keeps working. I've confirmed we don't need this to run in Dataflow/other runners …

Update vllm colab to work with asyncio requirements

---

examples/notebooks/beam-ml/run_inference_vllm.ipynb

Reverts apache/beam#33122
I got ahead of myself - this shouldn't be merged until 2.61.0 is in because it pins Beam to 2.61.0 - temporarily reverting, will recreate the PR/merge once the release is done

Revert "Update vllm colab to work with asyncio requirements"

---

.github/workflows/republish_released_docker_containers.yml
.test-infra/metrics/sync/github/github_runs_prefetcher/code/config.yaml
contributor-docs/release-guide.md

This moves the publish script to run regularly every monday. I tested that this works on demand with [this job](https://github.com/apache/beam/actions/runs/11916109686/job/33207990489), which produced container images like [this one](https://pantheon.corp.google.com/artifacts/docker/apache-beam-testing/us/gcr.io/updated_released_container_images%2Fbeam_flink1.15_job_server?e=13802955&mods=-ai_platform_fake_service&project=apache-beam-testing)
Fixes #33166
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-jo …

Publish updated containers regularly

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/container/Dockerfile-distroless
sdks/python/test-suites/dataflow/common.gradle

Addresses https://github.com/apache/beam/issues/32817 adding Python SDK (non-ML) [distroless](https://github.com/GoogleContainerTools/distroless) variant. **Future PR will add a GitHub workflow to run checks**.
Before submitting this PR, the following tests passed:
```
:sdks:python:test-suites:dataflow:py39:validatesDistrolessContainer
:sdks:python:test-suites:dataflow:py310:validatesDistrolessContainer
:sdks:python:test-suites:dataflow:py311:validatesDistrolessContainer
:sdks:python:test-suites:dataflow:py312:validatesDistrolessContainer
``` …

Create Python SDK Distroless variant

---

runners/flink/job-server-container/Dockerfile
website/www/site/content/en/documentation/runners/flink.md

CP: Revert "Fixed the broken beam python on flink with PortableRunner"

---

sdks/java/extensions/sql/zetasql/build.gradle
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/AggregateScanConverter.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/translation/ExpressionConverter.java

In preparation of upcoming GCP-BOM update …

Bump zetasql version to 2024.11.1

---

sdks/python/apache_beam/yaml/yaml_enrichment.py

Minor improvements to the Enrichment Transform docs …

[yaml] Enrichment transform doc improvements

---

.github/trigger_files/beam_PostCommit_Java.json
.github/trigger_files/beam_PostCommit_Java_DataflowV2.json
runners/google-cloud-dataflow-java/build.gradle
sdks/java/container/Dockerfile-distroless

This PR addresses #32818 adding Java SDK Distroless container image variants. **Future PR will add a GitHub workflows that runs `examplesJavaRunnerV2IntegrationTestDistroless`** …

Enable Java SDK Distroless container image variants.

---

.github/trigger_files/beam_PreCommit_Flink_Container.json
.github/workflows/beam_PreCommit_Flink_Container.yml

Address #33180
Will trigger this later with:
```
on:
pull_request_target:
paths:
- 'model/**'
- 'sdks/python/**'
- 'release/**'
- 'sdks/java/io/kafka/**'
- 'runners/core-construction-java/**'
- 'runners/core-java/**'
- 'runners/extensions-java/**'
- 'runners/flink/**'
- 'runners/java-fn-execution/**'
- 'runners/reference/**'
- 'release/trigger_all_tests.json'
- '.github/trigger_files/beam_PreCommit_Flink_Container.json'
push:
branches: ['master', 'release-*']
tags: 'v*'
schedule:
- cron: '0 */6 * * *'
workflow_dispatch:
```
For now, just manually trigger this for developing.
This PR introduces a new PreCommit workflow to test Flink container functionality across Go, Python, and Java SDKs. The workflow runs combine load tests in each language to verify the Flink container's functionality. …

Add a new precommit workflow to test flink container

---

.github/trigger_files/beam_PreCommit_Flink_Container.json
.github/workflows/beam_PreCommit_Flink_Container.yml

Addresses https://github.com/apache/beam/issues/33180 …

Fixed the new flink container precommit

---

sdks/python/apache_beam/internal/metrics/cells.py
sdks/python/apache_beam/metrics/cells.pxd
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/runners/direct/direct_metrics.py

Simplify metrics in preparation for adding another metric type.

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowStreamingPipelineOptions.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/SingleSourceWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingWorkerStatusPages.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingWorkerStatusReporter.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/ThrottledTimeTracker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/throttling/ThrottleTimer.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/throttling/ThrottledTimeTracker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/StreamPoolHeartbeatSender.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/SingleSourceWorkerHarnessTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingWorkerStatusReporterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/StreamPoolHeartbeatSenderTest.java

Add direct path code branch 
R: @scwhittle @arunpandianp  …

Integrate direct path with StreamingDataflowWorker code path

---

sdks/java/core/src/main/java/org/apache/beam/sdk/options/SdkHarnessOptions.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java

Done via an option so that it can be controlled further such as never GC'ing if desired
fixes #29797 …

Change the  Java sdk harness cache timeout for bundle processors to be an hour for streaming pipelines instead of 1 minute.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java

Took me a while to figure I should use `com.fasterxml.jackson.databind.JsonNode` to map to JSON BigQuery column, so updating the warning log accordingly to help the next ones.
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?que …

Make the warning about JSON BigQuery column type more precise

---

.github/workflows/go_tests.yml

This may at least partially address #32627. Following the suggestion by @lostluck there. …

Increase Go test coverage run timeout to 25 minutes

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillEndpoints.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDispatcherClient.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/ChannelCache.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/ChannelCacheTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/testing/FakeWindmillStubFactory.java

`MoreExecutors.directExecutor()/directExecutorService` runs all tasks on the calling thread (w/o offloading to another thread for async work) and calls to `submit` and `execute` will block until the submitted task returns (i.e `Runnable.run()`).
Use this in test implementations of `ChannelCache` and `FanOutStreamingEngineWorkerHarness` to prevent threads waiting on each other.  The old implementation seems to work locally but in the test runner environment has increased in flakiness.
Flakiness is referenced in https://github.com/apache/beam/issues/28957
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make …

use direct executor to deflake tests

---

.github/trigger_files/beam_PostCommit_Python_Dependency.json
sdks/python/apache_beam/ml/inference/tensorflow_inference_test.py
sdks/python/tox.ini

Make the model names unique and fix the tox package deps for tensorflow tests

---

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/BasicAuthSempClient.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SempBasicAuthClientExecutor.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/write/AddShardKeyDoFn.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/BasicAuthMultipleSempClient.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/BasicAuthMultipleSempClientFactory.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/SolaceIOMultipleSempIT.java

Users were not able to create a custom BasicAuthSempClient due to some package-private fields. This PR fixes that and adds example on how to create and use a custom client.
Depends on https://github.com/apache/beam/pull/32060, waiting for that to be merged
GitHub …

SolaceIO: refactor to allow inheritance of BasicAuthSempClient

---

sdks/python/apache_beam/ml/transforms/base_test.py
sdks/python/apache_beam/ml/transforms/handlers_test.py
sdks/python/setup.py
sdks/python/tox.ini

- Pin tensforflow to 2.12.x
- Fix the collections issue …

fixed ML tests

---

.github/trigger_files/beam_PostCommit_Python_ValidatesDistrolessContainer_Dataflow.json
.github/workflows/beam_PostCommit_Python_ValidatesDistrolessContainer_Dataflow.yml

This PR addresses #33003 fixing docker unauthentication errors.
See https://github.com/apache/beam/actions/runs/12040206193 for the workflow against this branch. This PR's failing check, https://github.com/apache/beam/actions/runs/12040477141/job/33570463577?pr=33232, runs against the failing version in master not this branch. …

Fix python distroless workflow

---

CHANGES.md
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

bump hadoop version

---

.test-infra/metrics/sync/github/github_runs_prefetcher/code/config.yaml

These tests can all be ignored by our automation/dashboard monitoring
Fixes #31954 …

Add safe to ignore category to dashboard/alerting

---

CHANGES.md
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Fix #33257 , fix #33252
Reverts apache/beam#33011
PreCommit Java HBase IO Direct and PostCommit Java Hadoop Versions are failing due to NoClassDefFoundError.
This is due to the hadoop forward compatibility issue. The original PR changed compiling Beam with Hadoop 3. Likely we still need to compile Beam with Hadoop 2, but can overwrite expansion service jar to use hadoop 3 as an alternative fix

Revert "bump hadoop version"

---

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/BasicAuthJcsmpSessionService.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/MessageReceiver.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SessionService.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SolaceMessageReceiver.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/SolaceCheckpointMark.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/UnboundedSolaceReader.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/MockEmptySessionService.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/MockSessionService.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/SolaceIOReadTest.java

This reverts commit e279e55f47683bcee1c59c0b7aea2b21741fadb3. PR #32962 Introduced flakiness. …

Revert "SolaceIO.Read: handle occasional cases when finalizeCheckpoint is not executed (#32962)"

---

examples/notebooks/beam-ml/run_inference_vllm.ipynb

This was merged prematurely, but it should work after the 2.61.0 release
Reverts apache/beam#33170

Revert "Revert "Update vllm colab to work with asyncio requirements""

---

CHANGES.md
website/www/site/content/en/blog/beam-2.61.0.md

Add the following note to the release blog and CHANGES.md
* Use Prism as a fallback to the Python Portable runner when running a pipeline with the Python Direct runner [#32876](https://github.com/apache/beam/pull/32876)
(a similar change will be backup dated to the 2.61 release branch: https://github.com/apache/beam/pull/33263) …

[CHANGES] Add prism note to 2.61 release blog and CHANGES.md

---

CHANGES.md

Release branch equivalent to https://github.com/apache/beam/pull/33262 which updates the blog as well.
The note has already been added to the github release blurb: https://github.com/apache/beam/releases/tag/v2.61.0
Back updating the CHANGES for something that made the 2.61 release, but wasn't noted in the CHANGES
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/a …

Update CHANGES.md with Python prism note.

---

learning/tour-of-beam/learning-content/common-transforms/aggregation/count/description.md
learning/tour-of-beam/learning-content/common-transforms/aggregation/max/description.md
learning/tour-of-beam/learning-content/common-transforms/aggregation/min/description.md
learning/tour-of-beam/learning-content/common-transforms/filter/description.md
learning/tour-of-beam/learning-content/core-transforms/additional-outputs/description.md
learning/tour-of-beam/learning-content/core-transforms/branching/description.md
learning/tour-of-beam/learning-content/core-transforms/combine/combine-per-key/description.md
learning/tour-of-beam/learning-content/core-transforms/combine/simple-function/description.md
learning/tour-of-beam/learning-content/core-transforms/composite/description.md
learning/tour-of-beam/learning-content/core-transforms/flatten/description.md
learning/tour-of-beam/learning-content/core-transforms/map/co-group-by-key/description.md
learning/tour-of-beam/learning-content/core-transforms/map/group-by-key/description.md
learning/tour-of-beam/learning-content/core-transforms/map/map-elements/description.md
learning/tour-of-beam/learning-content/core-transforms/map/pardo-one-to-one/description.md
learning/tour-of-beam/learning-content/core-transforms/partition/description.md
learning/tour-of-beam/learning-content/core-transforms/side-inputs/description.md
learning/tour-of-beam/learning-content/introduction/introduction-concepts/runner-concepts/description.md

Fix some minor formatting, typos, and data types in the Tour of Beam descriptions. …

Tour of Beam: formatting/typos

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/PubsubLiteWriteSchemaTransformProvider.java
sdks/python/apache_beam/yaml/generate_yaml_docs.py

PubSubLite is deprecated as per https://cloud.google.com/pubsub/lite/docs, scheduled to be turned down March 18, 2026, and is no longer available for new customers as of September 24, 2024.
In order to avoid confusion for new Beam YAML users, this transform will be hidden from the API docs, but still usable within the YAML API …

[yaml] remove PubSubLite from API docs

---

sdks/python/apache_beam/yaml/generate_yaml_docs.py
sdks/python/apache_beam/yaml/yaml_errors.py

Depends on #33027 (needs to rebase to clear unrelated files from diff) …

[yaml] error_handling normalization follow-up

---

sdks/python/apache_beam/metrics/cells.py

This PR fixes #33279. Internal tests show that this error resolved by simply using `Set[str]` of the Python `typing.Set` instead of `set[str]`. …

Fix TypeError: 'type' object is not subscriptable

---

CHANGES.md
runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py

testEventTimeTimerOrderingWithCreate was hanging due to timers being fired in incorrect order. The issue was that the heap variant wasn't being maintained on inserting timers for a key. This would cause timers to fire out of event time ordering. In particular, the "GC" timer would fire first (because it was set first), instead of the earlier firing "append" timer.
This incorrect ordering was also what caused testTwoTimersSettingEachOtherWithCreateAsInputUnbounded to fail.
Fixes #32222. …

[#32222] Actually maintain the heap invariant for timers.

---

sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go
sdks/go/pkg/beam/runners/prism/internal/worker/worker.go

In working on OnWindowExpiry, it shows SDK side disconnects would cause the job to hang indefinitely if there were outstanding ProcessBundleRequests. 
Instead, the job should fail (as SDK disconnects are not WAI behavior), and terminate execution instead.
Not testable as a closed form Go side without a more involved set up, but obvious in certain Python and Java side test failures. Clean job termination leads to better iteration than hangs do.
Part of #32211 
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewer …

[#32211] Fail job on SDK worker disconnect, instead of hanging forever.

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java
sdks/python/apache_beam/io/jdbc.py

This PR fixes #33286 due to changes introduced by #33205. Changing the order of the Python WriteToJdbc configuration to match the order of the fields in the corresponding JdbcSchemaIOProvider schema is what fixed the failing tests. …

Synchronize JdbcSchemaIO provider and Python transform configuration field order

---

sdks/python/apache_beam/yaml/yaml_combine.py
sdks/python/apache_beam/yaml/yaml_mapping.py

Fixing a couple formatting issues with various providers.
- add args to Combine doc
- StripErrorMetadata code was not in code block
- StripErrorMetadata ignore super class (PTransform) args (label) …

[yaml] various inline provider doc fixes

---

sdks/python/apache_beam/transforms/core.py

The docstrings  for `FlatMapTuple` and `MapTuple` are a bit difficult to interpret. I adjusted the example a little and removed mentions of python 2 which I think were more distracting than clarifying

Polish FlatMapTuple and MapTuple docstrings

---

.github/trigger_files/beam_PostCommit_Java_IO_Performance_Tests.json
.github/workflows/beam_PostCommit_Java_IO_Performance_Tests.yml

This PR fixes #30527 removing an outdated pattern for authentication to Google Cloud platform. See [full SBAR](https://github.com/apache/beam/issues/30527#issuecomment-2529926397) for situation, background, Assessment and recommendation. 
See workflow run at the branch of this PR: https://github.com/apache/beam/actions/runs/12246491594 …

Remove the use of google-github-actions/auth@v1

---

.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Direct.json
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/expansion-service/build.gradle
sdks/java/io/iceberg/build.gradle

Fixes the failing [beam_PostCommit_Python_Xlang_IO_Direct](https://github.com/apache/beam/actions/workflows/beam_PostCommit_Python_Xlang_IO_Direct.yml) and [beam_PostCommit_Python_Xlang_IO_Dataflow](https://github.com/apache/beam/actions/workflows/beam_PostCommit_Python_Xlang_IO_Dataflow.yml) tests, which are running into the following error after the [recent hadoop bump](https://github.com/apache/beam/pull/33312) from 2.10.2 --> 3.4.1:
<details>
<summary> Error stacktrace: </summary>
```
E       RuntimeError: org.apache.beam.sdk.util.UserCodeException: java.lang.NoSuchMethodError: org.apache.hadoop.security.HadoopKerberosName.setRuleMechanism(Ljava/lang/String;)V
E               at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)
E               at …
```

Add hadoop-auth

---

runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverter.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/StageInfo.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOInitializer.java

The introduced dependency breaks internal import and effectively re-introduced #21096
. see https://github.com/apache/beam/pull/32402#discussion_r1872386710 …

Remove mandatory beam-sdks-io-kafka dependency for dataflow worker jar

---

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/BasicAuthJcsmpSessionService.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/MessageReceiver.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SessionService.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SolaceMessageReceiver.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/SolaceCheckpointMark.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/read/UnboundedSolaceReader.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/MockEmptySessionService.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/MockSessionService.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/SolaceIOReadTest.java

Reapply changes that were introduced and reverted in https://github.com/apache/beam/pull/32962. See the main discussion there.  …

Reapply "SolaceIO.Read: handle occasional cases when finalizeCheckpoint is not executed (#32962)" (#33259)

---

model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/metrics.proto
sdks/python/apache_beam/metrics/cells.pxd
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/cells_test.py
sdks/python/apache_beam/metrics/monitoring_infos.py

This depends on https://github.com/apache/beam/pull/33195 …

Add bounded Trie metric type to Python.

---

CHANGES.md
runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager_test.go
sdks/go/pkg/beam/runners/prism/internal/execute.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
sdks/go/pkg/beam/runners/prism/internal/preprocess.go
sdks/go/pkg/beam/runners/prism/internal/stage.go
sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go

* Adds tracking for keys used within a window, so the OnWindowExpiration callback can be invoked.
* Restricts the output watermark from advancing until a window's been garbage collected and all keys have been expired.
* Added a "side channel" mechanism to insert bundles for execution outside of normal execution flow.
* This may ultimately be used for ProcessingTime timers, as well as for Triggers/
* Supports OnWindowExpiration, enabling initial GroupIntoBatches support. 
Fixes #32211
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBU …

[#32211] Support OnWindowExpiration in Prism.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/Repositories.groovy

Problem: Beam build searches `repository.apache.org` for artifacts not to be found there.  (See also #33333.)
Repro:
```
$ rm -fr ~/.gradle/caches
$ ./gradlew --info sdks:java:io:kafka:compileJava
...
Resource missing. [HTTP GET: https://repository.apache.org/snapshots/io/confluent/kafka-avro-serializer/7.5.5/kafka-avro-serializer-7.5.5.pom]
Resource missing. [HTTP GET: https://repository.apache.org/snapshots/io/confluent/kafka-schema-registry-client/7.5.5/kafka-schema-registry-client-7.5.5.pom]
Resource missing. [HTTP GET: https://repository.apache.org/content/repositories/releases/io/confluent/kafka-schema-registry-client/7.5.5/kafka-schema-registry-client-7.5.5.pom]
Resource missing. [HTTP GET: https://repository.apache.org/content/repositories/releases/io/confluent/kafka-avro-serialize …
```

Fix Apache snapshot repo usage

---

.github/trigger_files/beam_PostCommit_Java_PVR_Spark_Batch.json
.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark.json
.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark_Java11.json
CHANGES.md
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/GroupCombineFunctions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/GroupNonMergingWindowsFunctions.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/GroupNonMergingWindowsFunctionsTest.java

fixes #20943
This PR improves the performance of GroupByKey transform in SparkRunner by replacing the current implementation that uses Spark's `groupByKey` with `combineByKey`. 
The current implementation uses Spark's `groupByKey` which causes all the data to be shuffled across the network before grouping. This can lead to significant performance overhead and potential OOM issues with large datasets.
By switching to Spark's `combineByKey`, we can:
- Perform partial combining at the map side before shuffling
- Reduce the amount of data transferred across the network
- Improve memory utilization and overall performance …

Batch optimized SparkRunner groupByKey

---

sdks/go/pkg/beam/core/runtime/harness/datamgr_test.go

* The two flaky tests both followed the pattern of "remove the instruction prior to a bundle reading it". And tried to assert a specific amount of elements would be read.
* This isn't generally useful behavior.
* There was no guarantee that the element channel would have ingested any data before the removal, short of a read being attempted.
* Their case is better covered in other tests anyway, with deterministic results (eg PartialReadThenEndInstruction, which should always return 0s). …

Remove flaky Go DataMGR tests that terminate before read.

---

.github/workflows/java_tests.yml

This PR closes #33343 with the following changes:
- Remove Wordcount Dataflow runner step
- Remove google-github-actions/auth@v1 step
See code comments on this PR for contextual rationale for why these are proposed for removal.
See https://github.com/apache/beam/actions/runs/12266911887 for execution outcome of the workflow at this PR's branch. …

Clean up Java Tests GitHub workflow

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

google cloud bigdataoss released a version 2.2.26 that is protobuf 3 and 4 compatible (previously it was only 3 compatible). Would like to include it in Apache beam to alleviate customer issues with protobuf 4 compatibility specifically with gscio.

chore: Upgrade google cloud bigdataoss version

---

sdks/python/apache_beam/ml/rag/__init__.py
sdks/python/apache_beam/ml/rag/chunking/__init__.py
sdks/python/apache_beam/ml/rag/chunking/base.py
sdks/python/apache_beam/ml/rag/chunking/base_test.py
sdks/python/apache_beam/ml/rag/chunking/langchain.py
sdks/python/apache_beam/ml/rag/chunking/langchain_test.py
sdks/python/apache_beam/ml/rag/embeddings/__init__.py
sdks/python/apache_beam/ml/rag/embeddings/base.py
sdks/python/apache_beam/ml/rag/embeddings/base_test.py
sdks/python/apache_beam/ml/rag/embeddings/huggingface.py
sdks/python/apache_beam/ml/rag/embeddings/huggingface_test.py
sdks/python/apache_beam/ml/rag/types.py
sdks/python/apache_beam/ml/transforms/base.py
sdks/python/apache_beam/ml/transforms/base_test.py
sdks/python/apache_beam/ml/transforms/embeddings/huggingface.py

Add rag types, chunking and huggingface embeddings. …

Rag chunking embedding

---

sdks/python/apache_beam/coders/coder_impl.pxd
sdks/python/apache_beam/coders/coder_impl.py
sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test_common.py

This will get used in a windowed reshuffle, among other places. …

Faster default coder for unknown windows.

---

CHANGES.md
runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/data.go
sdks/go/pkg/beam/runners/prism/internal/engine/data_test.go
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/execute.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
sdks/go/pkg/beam/runners/prism/internal/stage.go
sdks/go/pkg/beam/runners/prism/internal/urns/urns.go
sdks/go/pkg/beam/runners/prism/internal/worker/worker.go

Adds support for the OrderedListState to Prism.
* Sorts values by VarInt Millis timestamp order on append.
* Lookup values by range requests from SDK.
* Handles known fixed leaf types as values (bools, doubles), varints,  and length prefixed types.
* If the type can be length prefixed, then Prism will do that for that coder.
* Otherwise fails for unknown coders that can't be handled.
* Runner side, Only OrderedListState needs to parse the individual values, so they can be manipulated, so the length function plumbing isn't otherwise necessary. It would not be difficult to extend this for all state types in the future, should it be required.
Note, must be submitted after #33337 because OrderedListState tests require OnWindowExpiration.
Fixes #32929. 
Thank you for …

[#32929] Add OrderedListState support to Prism.

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test.py

This is to fix some internal test failure caused by #33363.

Add missing to_type_hint to WindowedValueCoder

---

sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/transforms/external_transform_provider.py

Part of #33358
No change in functionality here, just improvements in the documentation and error messaging when using `JavaJarExpansionService`

Python ExternalTransformProvider improvements

---

sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_test.py

Addresses https://github.com/apache/beam/issues/32339 
The code raises a ValueError for transforms that self references it's input. …

Validate circular reference for yaml

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test.py
sdks/python/apache_beam/coders/typecoders.py
sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py
sdks/python/apache_beam/typehints/native_type_compatibility.py
sdks/python/apache_beam/typehints/typehints.py

- Fix custom coder not being used in Reshuffle (global window) (#33339)
- Fix custom coders not being used in Reshuffle (non global window) #33363
- Add missing to_type_hint to WindowedValueCoder #33403
It is causing some internal test failure so we revert it for now.

Revert three commits related to supporting custom coder in reshuffle

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/build.gradle
sdks/java/io/iceberg/hive/build.gradle

We can't bump to v1.7.0 as java 8 support was dropped.  …

Bump Iceberg to v1.6.1

---

examples/multi-language/python/wordcount_external.py
examples/multi-language/src/main/java/org/apache/beam/examples/multilanguage/schematransforms/ExtractWordsProvider.java
examples/multi-language/src/main/java/org/apache/beam/examples/multilanguage/schematransforms/JavaCountProvider.java
examples/multi-language/src/main/java/org/apache/beam/examples/multilanguage/schematransforms/WriteWordsProvider.java
sdks/python/apache_beam/transforms/external.py

Part of #33358
Simplify the Python example, and refactor the Java SchemaTransforms to be consistent

Improve existing Python multi-lang SchemaTransform examples

---

sdks/python/apache_beam/io/aws/s3filesystem.py
sdks/python/apache_beam/io/aws/s3filesystem_test.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem_test.py
sdks/python/apache_beam/io/filebasedsink.py
sdks/python/apache_beam/io/filebasedsource.py
sdks/python/apache_beam/io/filesystem.py
sdks/python/apache_beam/io/filesystems.py
sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/gcsfilesystem.py
sdks/python/apache_beam/io/gcp/gcsfilesystem_test.py
sdks/python/apache_beam/io/localfilesystem.py
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/metric.py
sdks/python/apache_beam/metrics/metric_test.py

Also cleans up the filesystem-specific logic. …

Migrate lineage counters to bounded tries.

---

sdks/python/apache_beam/yaml/standard_providers.yaml
sdks/python/apache_beam/yaml/yaml_ml.py
sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_unit_test.py
sdks/python/apache_beam/yaml/yaml_utils.py
sdks/python/apache_beam/yaml/yaml_utils_test.py

This PR adds support for calling RunInference with preliminary support for VertexAI through the use of the `VertexAIModelHandlerJSON` ModelHandler.
In order to implement more robust validation for the transform, the `SafeLineLoader` was refactored out of `yaml_transform.py` into a separate `yaml_utils.py` file to avoid import cycles.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md]( …

[yaml] add RunInference support with VertexAI

---

.github/workflows/README.md

This PR adds additional instructions to practically fix GitHub workflows.
- ~Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.~ …

Update .GitHub/workflows README.md

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/build.gradle
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskReader.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOReadTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/TestDataWarehouse.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/TestFixtures.java

Support Iceberg partition identity transform

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

Job creation involves staging multiple files (artifacts, pipeline proto, job file, template). While artifact staging has retry logic, these other types do not, leading to potential job failures due to transient service issues.
This commit introduces `stage_file_with_retry`, a new function with built-in retry logic.  Several `stage_file` calls in `apiclient.py` have been replaced with this new function.
Internal bug id: 384579652.

Implement "stage_file_with_retry" for robust file staging

---

scripts/ci/pr-bot/shared/checks.ts

Sometimes checks don't succeed or fail, they come back as neutral; these shouldn't block reviewer assignment. An example is the spot bugs response below:
this blocked reviewer assignment in https://github.com/apache/beam/pull/33456 for no real reason
GitHub …

Don't block bot on neutral responses

---

sdks/java/expansion-service/container/Dockerfile

This will drive down the number of vulnerabilities in this container and the expansion container shouldn't be relying on other things here …

Update Java expansion service to use distroless

---

sdks/python/apache_beam/runners/worker/sdk_worker.py
sdks/python/apache_beam/runners/worker/worker_status.py

This PR closes #33450, forwarding the worker_id to the interceptor where it was previously missing.
Failing check `Build python cp312- wheels on aarch64 for ubuntu-20.04` already has a history of failures and nothing to do with this PR. See https://github.com/apache/beam/actions/workflows/build_wheels.yml
See internal chat about tests of this PR on Dataflow. …

Fix missing worker_id from interceptor

---

sdks/java/expansion-service/container/Dockerfile

Reverts apache/beam#33464
Per conversation in https://github.com/apache/beam/pull/33464#issuecomment-2567963274 this did not actually drive down vulnerability counts

Revert "Update Java expansion service to use distroless"

---

.github/workflows/republish_released_docker_containers.yml

This will make identifying things easier. Also tweaked the workflow since it was failing
Example test run: https://github.com/apache/beam/actions/runs/12585577995/job/35077661479 (failing partway through because of unrelated docker issues I'm also looking at)
Example container created: https://pantheon.corp.google.com/artifacts/docker/apache-beam-testing/us/gcr.io/updated_released_container_images%2Fbeam_flink1.17_job_server?e=13802955&mods=-ai_platform_fake_service
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-r …

Add descriptive tags to republished containers

---

sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/cells_test.py

When merging on empty trie calculate delta based on other. …

Fix bounded trie merge when merging on empty trie

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test.py

This PR addresses internal test failures (internal bug ID: 385108730) introduced by recent Reshuffle code changes. It does not impact existing Reshuffle functionality, but is a necessary prerequisite for upcoming Reshuffle modifications.

Use other fallback coders for protobuf message base class

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProtoTest.java

Avro bytes are represented with java ByteBuffer.
Current implementation expects a byte array. This fails in practice with a ClassCastException: 
`class java.nio.HeapByteBuffer cannot be cast to class [B`

[java] Fix avro bytes conversion for BQ storage

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/teststream.go
sdks/go/pkg/beam/runners/prism/internal/execute.go
sdks/go/pkg/beam/runners/prism/internal/preprocess.go
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

Unblock two Java Bundle Finalization tests.
* Fix potential for fused transforms to flip finalization state of a stage. If any transform requires finalization, then so does the entire stage.
* Fix the tests themselves: They were making assumptions on bundle production outside of the needs of the tests.
* Reduce the "attempts" count, since they should now play better with other runners as well.
* Remove unnecessary impulse kick set for TestStream. This plays better with Side input validation. …

[#31912] Fix bug in finalization for Prism & fix the Java bundle finalizing tests.

---

.github/workflows/build_wheels.yml

I found that this workflow works on GitHub Actions runners, so I'm proposing we move to those temporarily to get things unblocked.
Example successful run - https://github.com/apache/beam/actions/runs/12638389111
I'm tracking undoing this in https://github.com/apache/beam/issues/33506
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-in …

Build wheels on gha runners instead of local runners

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/build.gradle
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AppendFilesToTables.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FileWriteResult.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergReadSchemaTransformProvider.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergScanConfig.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/OneTableDynamicDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/PortableIcebergDestinations.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOReadTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergUtilsTest.java

This is a proposal that uses Json representation of Iceberg `TableIdentifier` to support special characters, more specifically, cases when tables contain a `dot` in the name.
Fixes: #33292 …

Add support for Iceberg table identifiers with special characters

---

sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/SolaceIO.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/BasicAuthJcsmpSessionServiceFactory.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/JcsmpSessionService.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SessionService.java
sdks/java/io/solace/src/main/java/org/apache/beam/sdk/io/solace/broker/SessionServiceFactory.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/MockEmptySessionService.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/MockSessionService.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/FixedCredentialsBasicAuthJcsmpSessionServiceFactory.java
sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/SolaceIOCustomSessionServiceFactoryIT.java

Refactored to separate authentication and session settings, and allow inheritance and overriding of SessionService.
Depends on https://github.com/apache/beam/pull/32400, waiting for that to be merged …

SolaceIO: separate auth and session settings

---

.github/trigger_files/beam_PostCommit_Java_Hadoop_Versions.json
sdks/java/io/hadoop-file-system/build.gradle

This fixes breakages caused by https://github.com/apache/beam/pull/33192#issuecomment-2575548781
Fixes https://github.com/apache/beam/issues/33252 …

Pin protobuf for older hadoop tests

---

sdks/go/pkg/beam/transforms/stats/quantiles.go
sdks/go/pkg/beam/transforms/stats/quantiles_test.go

ApproximateQuantiles() returns a list of numQuantiles - 1 elements. If the numQuantiles is 1 then we don't need to analyze the input and can immediately return the empty result.
Fix #33449

[#33449] Return zero elements immediately if the requested number of quantiles is 1.

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/handlepardo.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/job.go
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java

* Adds Support for @RequireTimeStortedInput
* Largely forced a fusion break, and then prism automatically sorts data by event time.
* Adds precise late data handling, dropping received data if the watermark is already past the window.
* Fixes two of three tests relying on data being "late" without correctly making the data be late, by moving the data past the end of the global window. The test using allowedlateness was skipped for later, when prism starts to support it.
Unblocks 5 tests, but breaks a Reshuffle/Redistribute test, which adds late data. They're disabled for now until we confirm if the tests are valid or not.
Fixes #33513 
See the …

[#33513][prism]Handle Time sorted requirement and drop late data.

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/build.gradle
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskReader.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOReadTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/TestDataWarehouse.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/TestFixtures.java

Add Iceberg support for name-based mapping schema

---

CHANGES.md
sdks/java/io/debezium/build.gradle
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClient.java

Proto 4 is breaking debezium IO - https://github.com/apache/beam/pull/33192#issuecomment-2575651407 - I tried fixing this by upgrading debezium in https://github.com/apache/beam/pull/33526 but found that newer versions are not proto 4 compatible yet (and it is a non-trivial upgrade), so our only real option is forcing proto 3. To best keep up with the google bom we need proto 4, and many users will want to start using this.
The good news here is that clients that need protobuf should generally be ok with proto 3 for a little while (going the other direction is usually the tough part as of now), so this may be ok. But it is non-ideal and we should address it once we're able.
Fixes #31346 …

Pin protobuf 3 for debezium

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/strategy.go
sdks/go/pkg/beam/runners/prism/internal/engine/strategy_test.go
sdks/go/pkg/beam/runners/prism/internal/execute.go
sdks/go/pkg/beam/runners/prism/internal/handlerunner.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
sdks/go/pkg/beam/runners/prism/internal/urns/urns.go
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java
sdks/python/apache_beam/runners/portability/prism_runner_test.py

One thing lead to another with this so this PR does a few related things.
* Exports the windowing strategy struct to configure aggregation stages in the element manager.
* This is prep-work for fully supporting the rest of the windowing strategies + triggers.
* Uses the above to support AllowedLateness.
* In doing so, it was noted that incorrect conversions from integers (representing durations of nanosecond precision) to `mtime.Time` which is strictly a millisecond duration. This fix revealed two issues with Session Windows.
* Fixes to Session Window Merging
* Merging wasn't correctly happening per key. Windows were being treated "globally".
* We were incorrectly using the GapSize in prism. GapSize was already accounted for in the generation of the SessionWindow's interval Window …

[#31438] WindowingStrategy Plumbing + AllowedLateness + Fixing Session Windows

---

.github/trigger_files/beam_PostCommit_Java_DataflowV2.json
CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServices.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/testing/FakeDatasetService.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java

Cherry pick for BQIO auto-schema update fix

---

.test-infra/tools/stale_k8s_workload_cleaner.sh

Right now, the clean gcp resources actions runs are failing on deleting beam-performancetests-singlestoreio-12661373176 -  they just hang because the resource doesn't exist. This looks like maybe a gke bug.
To work around this, I'm removing this resource from the delete command. Hopefully this is just temporary and things heal over time.
Example failure without my change - https://github.com/apache/beam/actions/runs/12689615728/job/35368720669
Example success with my change - https://github.com/apache/beam/actions/runs/12693438231/job/35381012473 …

Temporarily skip deleting beam-performancetests-singlestoreio-12661373176

---

sdks/python/test-suites/dataflow/common.gradle

Adds a GitHub issue link for the disabled TensorRT tests since it may be disabled for a longer period of time.
[![Build …

Add issue link to disabled TensorRT integration test

---

CHANGES.md
sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

A transient error might occur when writing a lot of shards to GCS, and right now the GCS IO does not have any retry logic in place:
https://github.com/apache/beam/blob/a06454a2/sdks/python/apache_beam/io/gcp/gcsio.py#L269
It means that in such cases the entire bundle of elements fails, and then Beam itself will attempt to retry the entire bundle, and will fail the job if it exceeds the number of retries.
This change adds new logic to retry only failed requests, and uses the typical exponential backoff strategy.
Note that this change accesses a private method (`_predicate`) of the retry object, which we could avoid by basically copying the logic over here. But existing code already accesses `_responses` property so maybe it's not a big deal. …

Add retry logic to each batch method of the GCS IO

---

.github/trigger_files/beam_PreCommit_Flink_Container.json
sdks/python/apache_beam/testing/fast_test_utils.pxd
sdks/python/apache_beam/testing/fast_test_utils.pyx
sdks/python/apache_beam/testing/test_utils.py
sdks/python/apache_beam/testing/test_utils_test.py

follow up #33510
* It's internal and test only code, fine to change method name …

Use randbytes in custom LCG random generator

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

It is found that shadow jars with exportJavadoc set to false still publishes an empty javadoc jar to maven repository. This reduces release overhead by 100+ artifacts …

Do not publish javadoc jar when exportJavadoc disabled

---

sdks/go/container/boot.go
sdks/go/container/pool/workerpool.go
sdks/go/container/pool/workerpool_test.go
sdks/go/pkg/beam/options/jobopts/options.go
sdks/go/pkg/beam/runners/prism/internal/environments.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/server.go
sdks/go/pkg/beam/runners/prism/prism.go

* Allows the Go SDK Container to execute as a SideCar worker pool from the default Beam Go container, with the default port of 50000.
* Enables use as a containered local worker pool as described here for the External configuration: https://beam.apache.org/documentation/runtime/sdk-harness-config/
* All execution is *pooled* locally as per normal.
* Code can be shared to other SDK container boot loaders, since it largely just re-executes the current bootloader process in the container.   …

[Go SDK] Container Worker pool functionality.

---

sdks/python/apache_beam/yaml/json_utils.py
sdks/python/apache_beam/yaml/yaml_combine.py
sdks/python/apache_beam/yaml/yaml_enrichment.py
sdks/python/apache_beam/yaml/yaml_io.py
sdks/python/apache_beam/yaml/yaml_join.py
sdks/python/apache_beam/yaml/yaml_mapping.py
sdks/python/apache_beam/yaml/yaml_ml.py
sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_utils.py

Updates python type hints in the YAML directory to PEP 585 standards. 
Part of #32969  …

Update Python typehints in Beam YAML

---

learning/katas/java/Core Transforms/FlattenWith/FlattenWith/src/org/apache/beam/learning/katas/coretransforms/flattenWith/Task.java
learning/katas/java/Core Transforms/FlattenWith/FlattenWith/task-info.yaml
learning/katas/java/Core Transforms/FlattenWith/FlattenWith/task.md
learning/katas/java/Core Transforms/FlattenWith/FlattenWith/test/org/apache/beam/learning/katas/coretransforms/flattenWith/TaskTest.java
learning/katas/java/Core Transforms/FlattenWith/lesson-info.yaml
learning/katas/java/Core Transforms/Tee/Tee/src/org/apache/beam/learning/katas/coretransforms/tee/Task.java
learning/katas/java/Core Transforms/Tee/Tee/task-info.yaml
learning/katas/java/Core Transforms/Tee/Tee/task.md
learning/katas/java/Core Transforms/Tee/Tee/test/org/apache/beam/learning/katas/coretransforms/tee/TaskTest.java
learning/katas/java/Core Transforms/Tee/lesson-info.yaml
learning/katas/java/build.gradle
learning/katas/python/Core Transforms/FlattenWith/FlattenWith/__init__.py
learning/katas/python/Core Transforms/FlattenWith/FlattenWith/task-info.yaml
learning/katas/python/Core Transforms/FlattenWith/FlattenWith/task.md
learning/katas/python/Core Transforms/FlattenWith/FlattenWith/task.py
learning/katas/python/Core Transforms/FlattenWith/FlattenWith/tests/__init__.py
learning/katas/python/Core Transforms/FlattenWith/FlattenWith/tests/test_task.py
learning/katas/python/Core Transforms/FlattenWith/lesson-info.yaml
learning/katas/python/Core Transforms/Tee/Tee/__init__.py
learning/katas/python/Core Transforms/Tee/Tee/task-info.yaml
learning/katas/python/Core Transforms/Tee/Tee/task.md
learning/katas/python/Core Transforms/Tee/Tee/task.py
learning/katas/python/Core Transforms/Tee/Tee/tests/__init__.py
learning/katas/python/Core Transforms/Tee/Tee/tests/test_task.py
learning/katas/python/Core Transforms/Tee/lesson-info.yaml
learning/katas/python/requirements.txt
website/www/site/content/en/documentation/transforms/java/other/flattenWith.md
website/www/site/content/en/documentation/transforms/java/other/tee.md
website/www/site/content/en/documentation/transforms/python/other/flattenwith.md
website/www/site/content/en/documentation/transforms/python/other/tee.md

learning+website: add `FlattenWith` and `Tee` to Playground and Transform Catalog

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/BeamFnDataReadRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/BeamFnDataWriteRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/CombineRunners.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/PTransformRunnerFactory.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/AssignWindowsRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/BeamFnDataReadRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/BeamFnDataWriteRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/CombineRunnersTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FlattenRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FnApiDoFnRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/MapFnRunnersTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/PTransformRunnerFactoryTestContext.java

Reduces memory footprint of storing map of coders, pcollections and windowStrategies within FnApiDoFnRunner by reusing the immutable component created once per stage vs copied recursively for earch transform.

Improve memory efficiency in FnApiDoFnRunner

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/build.gradle
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/AppendFilesToTables.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FileWriteResult.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergReadSchemaTransformProvider.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergScanConfig.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/OneTableDynamicDestinations.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/PortableIcebergDestinations.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOReadTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergUtilsTest.java

Reason: performance regression caught by internal tests (Iceberg write spends 100% more time)
half of time spends on  IcebergUtils.parseTableIdentifier.
The code path suggests OBJECT_MAPPER.readTree always throws in my test case, and wasted most of time to assemble Exception object.
In general using try {} catch {} for what if clause does is an antipattern.
Possible forward fix could be using a cache.
This reverts commit d6e0b0c5c0f4cd8acad230833c2ed42e220d6178. …

Revert "Add support for Iceberg table identifiers with special characters (#33293)"

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/BigtableChangeStreamAccessor.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/changestreams/dao/DaoFactory.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java

This is useful if the runner's checkpoint duration is longer than 15s which is the default we set for ReadChangeStream API. If the runner's checkpoint duration is longer than 15s, the ReadChangeStream request will get deadline exceeded error before the runner initiated. This will cause the run to fail and return to the previous checkpoint.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATU …

Add option to adjust ReadChangeStream API timeout to allow longer timeout for longer checkpoint durations

---

sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/runners/interactive/display/pcoll_visualization.py

sdks/python: replace `applymap` with `map` in `DataFrame`

---

sdks/python/apache_beam/ml/rag/embeddings/vertex_ai.py
sdks/python/apache_beam/ml/rag/embeddings/vertex_ai_test.py

Add Vertex embeddings wrapper RAG package that uses RAG types. …

Add Vertex embeddings to RAG package.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/ChangeStreamsConstants.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/ActionFactory.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/DetectNewPartitionsAction.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/AsyncWatermarkCache.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/CacheFactory.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/NoOpWatermarkCache.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/WatermarkCache.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/package-info.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dofn/DetectNewPartitionsDoFn.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/DetectNewPartitionsActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/CacheFactoryTest.java

Asynchronously compute the minimum watermark from Spanner change stream partitions and cache them for DoFn access.
This PR addresses the issue that if computing the minimum watermark from the metadata partition table takes over 5s (max time to issue a split for a DoFn), the pipeline will not be able to progress. Here, we initialize a static guava cache that executes the watermark query asynchronously, thus not being limited by the 5s compute time.

feat: caches watermark for Spanner change streams

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkState.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ComputationState.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/SingleSourceWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/WorkItemReceiver.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/WorkItemScheduler.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/failures/WorkFailureProcessor.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/FakeWindmillServer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContextTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSourcesTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkStateTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ComputationStateCacheTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/WindmillStreamSenderTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutorTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingApplianceWorkCommitterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingEngineWorkCommitterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/failures/WorkFailureProcessorTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefresherTest.java

Prior to this change WorkItem::getSerializedSize is called on the GetWorkStream thread for every work item, it shows up like in cpu profiles. Replacing it with the byteSize computed from the response bytes makes the work submit path a bit more efficient
https://github.com/apache/beam/issues/33578

[Dataflow Streaming] Avoid calling WorkItem::getSerializedSize

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1WriteIT.java

- Introduces `withResults()` API to `DatastoreV1.Write`, `DatastoreV1.DeleteEntity` and `DatastoreV1.DeleteKey` PTransforms, which returns `PCollection<DatastoreV1.WriteSuccessSummary>` instead of `PDone`.
- Allows Wait.on semantics for DatastoreIO, e.g.
```
PCollection<Entity> firstBatch = ... ;
PCollection<Entity> secondBatch = ... ;
PCollection<DatastoreV1.WriteSuccessSummary> firstWriteResults =
firstBatch.apply(DatastoreIO.v1().write().withProjectId(project).withResults());
secondBatch
.apply(Wait.on(firstWriteResults)) // Allows Wait.on
.setCoder(secondBatch.getCoder())
.apply(DatastoreIO.v1().write().withProjectId(project)); // Returns PDone without withResults()
```
- Maintains backward compatibility with existing API structure
- Draws inspiration from JdbcIO and FirestoreIO …

DatastoreV1.Write, DeleteEntity and DeleteKey can optionally return PCollection

---

sdks/python/apache_beam/ml/rag/chunking/langchain_test.py
sdks/python/setup.py

Also fix some tests that weren't asserting correctly. …

Add langchain dep to ML tests.

---

sdks/python/apache_beam/yaml/standard_io.yaml
sdks/python/apache_beam/yaml/tests/iceberg.yaml
sdks/python/apache_beam/yaml/yaml_io.py

Support for Iceberg from YAML via ManagedIO.

---

runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/LargeCommitTest.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/OperationalLimits.java
sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/GroupByKeyTest.java

fixes https://github.com/apache/beam/issues/33588

[Dataflow Streaming Appliance] Fix per key commit size validation

---

sdks/python/apache_beam/transforms/environments.py
sdks/python/apache_beam/yaml/yaml_provider.py

Use local loopback worker from Python expansion services.

---

sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_unit_test.py

There was a bug with pipeline-level windowing with transforms that define `error_handling` in which pipelines would fail with error:
```
Ambiguous output at line 16: Stream has outputs [None, 'errors']
```
This was due to a check to ensure a transform only outputs a "good" collection and optionally a collection defined by the named output in the `error_handling` config. Since the `error_handling` was not propagated to the top-level composite constructed as part of pipeline-level windowing, the check would fail.
Example affected pipeline:
```
pipeline:
transforms:
- type: ReadFromPubSub
name: Stream
config:
topic: projects/pubsub-public-data/topics/taxirides-realtime
format: json
schema:
type: object
properties:
ride_id: {type: string}
error_handling:
output: errors
- type: LogForTesting …
```

[yaml] propogate error_handling to windowing composite config

---

CHANGES.md
sdks/go/pkg/beam/core/runtime/graphx/translate.go
sdks/go/pkg/beam/core/runtime/graphx/translate_test.go
sdks/go/pkg/beam/runners/prism/internal/environments.go

Process Env execution is another kind of Environment type that allows you to set a process to be started up as a worker.
Useful where docker isn't appropriate, for testing the bootloader directly.
The protocol for Process environments is nearly identical to the standard container contract. The process will be provided a --id and a --provision_endpoint flag, and otherwise be expected to handle the rest of the boot container logic.
Largely added for completeness prior to supporting the Any environment in Prism. …

[GoSDK + Prism] Support Process env execution.

---

CHANGES.md
sdks/go/pkg/beam/runners/prism/internal/environments.go
sdks/go/pkg/beam/runners/prism/internal/environments_test.go
sdks/go/pkg/beam/runners/prism/internal/urns/urns.go

* Adds basic AnyOf support enables handling for environment selection.
* Prefers External/Loopback, then Process, then docker, then any others.
* Could be improved later via a configuration that changes the ranking, or by going with a "fallback" approach in the case of AnyOf environments. (eg. Sorts as presently, tries to make the external worker, if that fails, move to the next version, checks if it can start the process environment, etc._
To …

[prism] Support AnyOf in Prism.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/fn/stream/DirectStreamObserver.java
sdks/java/core/src/test/java/org/apache/beam/sdk/fn/stream/DirectStreamObserverTest.java

A dynamic race condition detector correct identifies an unsynchronized read-after-write between the field initializer and the first call of onNext.
Additionally, this fixes a benign inconsistency in which it would wait one extra message the first time around. …

Eliminate benign race condition in DirectStreamObserver and make first and subsequent iterations consistent

---

CHANGES.md

Add known issue to CHANGES.md #33588

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateCache.java

Increasing the state cache concurrency level to reduce contention on state cache.

[Dataflow Streaming] Increase windmill state cache concurrency level

---

.test-infra/tools/flaky_test_detection.py

Recently the Flaky test detection tool stopped adding to the issue non-existent labels (e.g. 'workflow_id: xxx').
Tested this fix on the fork. …

Fix flaky test detection tool labels

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergCatalogConfig.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/BigQueryMetastoreCatalogIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/HadoopCatalogIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/HiveCatalogIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/IcebergCatalogBaseIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/hiveutils/TestHiveMetastore.java

Collection of some improvements:
- cache Catalog instead of recreating it unnecessarily
- use faster IO implementation `org.apache.iceberg.gcp.gcs.GCSFileIO` in tests
- tests drop tables and namespaces right after completion
- tests close resources properly

[IcebergIO] cleanups, improvements, and test tweaks

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/common/worker/WorkProgressUpdater.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryStorageStreamSource.java

This is usually a harmless Exception, however, failed splitAtFraction in combination with other internal bug caused issue on legacy Dataflow worker (internal tracker: 359214843)
This change includes two action item for it
- promote the warning log to error log, align with what runner v2 doing
- Suppress the Exception in known common source (e.g. BigQuery read) when it is safe to do
To …

Handle error on source split in BigQueryStorageStreamSource

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/counters/CounterFactory.java

This counter shows up on wallz when workers are under load 
#33578

[Dataflow] Replace AtomicLong with LongAdder in LongSumCounterValue to reduce contention between harness threads

---

sdks/python/test-suites/tox/py39/build.gradle
sdks/python/tox.ini

pin sentence-transformers==3.3.1

---

.github/workflows/finalize_release.yml
.github/workflows/republish_released_docker_containers.yml

Should get autocreated based on the promoted tag, then we can consume it in our postrelease workflow …

Update release finalization to push postrelease branch

---

.github/workflows/beam_PerformanceTests_Kafka_IO.yml
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java

Fixes [#31929](https://github.com/apache/beam/issues/31929)
Successful run example: https://github.com/akashorabek/beam/actions/runs/12884293766 …

Fix Java KafkaIO Performance test job

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/build.gradle
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/RecordWriterManagerTest.java

Previously we were manually doing conversions to determine a record's partition. We recently [found](https://github.com/apache/iceberg/issues/11899) that Iceberg has existing public utils that do this; this change switches to use those utils.
Fixes #32865

[IcebergIO] Use InternalRecordWrapper partition util

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/common/worker/OutputObjectAndByteCounter.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/common/worker/OutputObjectAndByteCounterTest.java

Example profile showing the relevant stacks <img width="1688" alt="Screenshot 2025-01-22 at 9 44 53 PM" src="https://github.com/user-attachments/assets/1a2e7d69-e429-4956-8cc0-0eec1629f14c" />
#33578

[Dataflow] Use ThreadLocalRandom instead of Random in OutputObjectAndByteCountert o reduce contention

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/SingleSourceWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/common/worker/OutputReceiver.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GetWorkResponseChunkAssembler.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GetWorkTimingInfosTracker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/WorkItemReceiver.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/WorkItemScheduler.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/FakeWindmillServer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContextTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/WorkerCustomSourcesTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkStateTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/ComputationStateCacheTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutorTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingApplianceWorkCommitterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingEngineWorkCommitterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/failures/WorkFailureProcessorTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefresherTest.java

1. Moving recordGetWorkStreamLatencies to run outside work submission loop
2. Change OutputReceiver::outputCounters from HashMap to LinkedHashmap
#33578

[Dataflow Streaming] Optimizing work submit loop

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/internal/CustomSources.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingModeExecutionContext.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java
runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto
sdks/java/core/src/main/java/org/apache/beam/sdk/io/UnboundedSource.java

Add offset-based deduplication to Unbounded Source and Dataflow Runner.
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?event=schedule&&?branch=master)](https:/ …

Add offset-based deduplication to Unbounded Source and Dataflow Runner.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/LengthPrefixCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/CombineFns.java

Fixes #33620
Half of the sdk coders have getEncodedElementByteSize  public because they are invoked outside of beam.sdk.coders package. 
Some accumulators like ComposedAccumulatorCoder should have access to optimized methods for calculating size but due to it can be any Coder.
Optimized way of calculating size shouldn't be limited to Coders implemented in beam.sdk.coders only.
This change changes it to public and fixes all the coders in beam sdk.
This will break coders implemented in customer codebase requiring small patch to change visibility.

make Coder.getEncodedElementByteSize public to allow performance improvements in higher level coders

---

sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/test-suites/tox/py39/build.gradle
sdks/python/tox.ini

[Issue #30799](https://github.com/apache/beam/issues/30799)
Successful run example: https://github.com/akashorabek/beam/actions/runs/12926316024 …

Fix python postcommit dependency workflow

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverter.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/MetricsToPerStepNamespaceMetricsConverterTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/DelegatingGauge.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/MetricsContainer.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/NoOpGauge.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaMetrics.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetrics.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaMetricsTest.java

Add per worker gauge support to add per backlog partition for kafka with java legacy worker for   Dataflow
[![Build …

Kafka add gauge v1

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/GroupByKeyTranslatorBatch.java
runners/spark/3/src/test/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/GroupByKeyTest.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkCommonPipelineOptions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/EvaluationContext.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/GroupByKeyVisitor.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/TransformTranslator.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/GroupByKeyVisitorTest.java

Restore priority of memory sensitive GBK translation in spark-runner to avoid OOM #33520 …

[Spark] Restore memory sensitive GBK translation (#33520)

---

runners/google-cloud-dataflow-java/build.gradle

Fix #33748
The tests has been failing consistently on Dataflow runner
It's likely due to spanner service change, e.g. attempt to read from a bad session will now create the session and make it valid on retry. The test still passed on Direct runner which does not retry.
We had excluded similar BigtableIO error handling tests flaky on Dataflow runner due to timing differences.
internal bug: 391864650
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers …

Exclude SpannerReadIT.testReadFailsBadSession from Dataflow runner

---

runners/core-java/build.gradle
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoEncodings.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MonitoringInfoEncodingsTest.java
sdks/java/core/build.gradle
sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java
sdks/java/harness/build.gradle

This reverts commit 5bfacc935f8510bdf287d8c87b810e08ab9a79ae. The change caused the core SDK, the SDK harness, and the shared runners-core library to depend on Dataflow.
Because it depends only on the Dataflow cloud API it did not (quite/yet) introduce a cyclic dependency. We just need to correct it so that it doesn't bite us later, and to preserve Beam's overall architecture. …

Revert "Add ability to encode and decode histogram data to portable runners (#33013)"

---

.github/workflows/cut_release_branch.yml
contributor-docs/release-guide.md
release/src/main/scripts/choose_rc_commit.sh

This makes more sense because it allows us to cut patch releases off the same branch. This is also convenient because it allows us to cherry-pick low risk, moderate value fixes to the release branch in case a patch happens, and it is just all around a more accurate naming. …

Rename release branch to release-2.XX instead of release-2.XX.0

---

sdks/python/apache_beam/typehints/opcodes.py
sdks/python/apache_beam/typehints/row_type.py
sdks/python/apache_beam/typehints/trivial_inference_test.py

This also fixes a bug where literals rather than their types were loaded onto the stack and non-field Row attributes are accessed. …

More complete type inference for fstrings, etc.

---

sdks/python/apache_beam/ml/inference/sklearn_inference_it_test.py

[#30760](https://github.com/apache/beam/issues/30760)
For now, disabled the tests for python 3.9 and 3.10 in `sklearn_inference_it_test.py` due to an incompatibility with the new `NumPy` versions. This issue caused the following error: `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject.` Created the [issue](https://github.com/apache/beam/issues/33796) to investigate possible workarounds. 
Example of a job without the `ValueError` - https://github.com/akashorabek/beam/actions/runs/13031140520. (The failure in Python 3.12 is unrelated and is caused by an [existing issue](https://github.com/apache/beam/issues/33425) with the `build_wheels` task) …

Fix postcommit python arm workflow

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStreamTest.java

the test has been consistently failing internally, also highly flaky on GitHub Action: ref https://github.com/apache/beam/pull/32774#issuecomment-2622585362 …

Skip highly flaky test

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java
sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CallTest.java

Revert "Increase timeouts in CallTest to reduce flakiness"

---

examples/java/src/main/java/org/apache/beam/examples/complete/game/utils/WriteToBigQuery.java
release/src/main/groovy/mobilegaming-java-dataflow.groovy
release/src/main/groovy/mobilegaming-java-direct.groovy

Addresses #30505
Successful run: https://github.com/Amar3tto/beam/actions/runs/13038973346 …

Fix PostRelease Nightly Snapshot

---

.github/trigger_files/beam_PostCommit_Java_DataflowV1.json
CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/CombineAsIterable.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java

Workaround an unknown side input bug reported internally
internal ref: 373833916 …

Change Reify.asIterable to GBK in BigQueryIO File loads

---

sdks/python/apache_beam/runners/dask/dask_runner.py
sdks/python/apache_beam/runners/dask/overrides.py
sdks/python/apache_beam/runners/dask/transform_evaluator.py

`dask.optimize()` isn't a cure-all for everything. It won't remove tasks in a highly-duplicated graph, like the one we collect in the DaskRunner's visitor. The fix, however, is quite simple: We can get away with the dask distributed client only running the last value in the translated operation graph.
Even with this small change, all tests pass. Further, it should lead to a significant performance improvement. …

Run a significantly smaller Dask Graph.

---

sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/SnowflakeIO.java
sdks/java/io/snowflake/src/test/java/org/apache/beam/sdk/io/snowflake/test/unit/write/SnowflakeIOWriteTest.java

When sending CSV to Snowflake for `COPY`, do not quote empty fields (`''`).
With some types, like integer, it leads to an error like this: `net.snowflake.client.jdbc.SnowflakeSQLException: Numeric value '' is not recognized`.
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https:/ …

SnowflakeIO: do not quote empty fields 

---

.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh

Reverts apache/beam#32354
the artifact registry issue is resolved. This can be seen as no recent test flakiness due to disappearing private repo container (which still has clean up enabled)

Revert "Pause delete images in public AR"

---

sdks/python/setup.py
sdks/python/test-suites/tox/py39/build.gradle
sdks/python/tox.ini
website/www/site/content/en/documentation/ml/ml-dependency-extras.md
website/www/site/content/en/documentation/ml/overview.md
website/www/site/layouts/partials/section-menu/en/documentation.html

Add extras following the process described in https://docs.google.com/document/d/1c84Gc-cZRCfrU8f7kWGsNR2o8oSRjCM-dGHO9KvPWPw/edit?tab=t.0 …

Add python ml extras

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/hive/build.gradle

Silenced these two alerts:
CVE-2022-39135 	 Critical	9.8	Yes	Unspecified	org.apache.calcite:calcite-core
CVE-2020-13955 	 Medium	5.9	Yes	Unspecified	org.apache.calcite:calcite-core …

Upgrade calcite to 1.37.0 used by io-expansion service

---

CHANGES.md
sdks/python/apache_beam/runners/dask/dask_runner.py
sdks/python/apache_beam/runners/dask/dask_runner_test.py
sdks/python/apache_beam/runners/dask/overrides.py
sdks/python/apache_beam/runners/dask/transform_evaluator.py

Configuring the number of partitions in the Dask runner is very important to tune performance. This CL gives users control over this parameter. …

The Bag Partition is now configurable.

---

sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py

In this commit, we enable named aggregation to deferred DataFrame groupby.
Fixes #27278
Before             |  After
:-------------------------:|:-------------------------:
```python
import pandas as pd
from apache_beam.dataframe import convert
employee_data = {
'Department': ['HR', 'HR', 'Engineering', 'Engineering', 'Sales', 'Sales'],
'Salary': [50000, 55000, 70000, 75000, 60000, 65000],
'Performance_Score': [8, 9, 7, 6, 8, 8],
'Years_of_Experience': [2, 5, 8, 10, 3, 4]
}
employee_df = pd.DataFrame(employee_data)
CSV_HEADER = "Department,Mean_Salary,Median_Performance_Score,Total_Years_of_Experience"
def process_aggregated_data(row):
"""Convert aggregated data into a format suitable for CSV output."""
department = row.Department
salary = row.Mean_Salary …
```

sdks/python: enable named aggregation to deferred DataFrame groupby

---

sdks/python/apache_beam/io/gcp/bigquery_tools.py
sdks/python/apache_beam/io/gcp/bigquery_tools_test.py

Addresses #32155 and fixes the handling of missing repeated fields inside a dicts when converting a dict to a beam row. As described in the issue it matches BigQuery standard behaviour of converting Null repeated fields to empty arrays on insert.
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array_nulls 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](htt …

Adding handling of Nulled lists to beam_row_from_dict

---

sdks/java/container/license_scripts/license_script.sh

License script - fix dependencies installation

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCheckpointMark.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibility.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOUtils.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedSource.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibilityTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java
sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java
sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java

Offset-based deduplication for Kafka source.
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/act …

Offset-based deduplication for Kafka source.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Metrics.java
sdks/java/core/src/test/java/org/apache/beam/sdk/metrics/MetricsTest.java

Add a flag to disable user bounded trie.  …

Btrie disable flag

---

CHANGES.md
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/options/DataflowStreamingPipelineOptions.java

With this change user workers will request batched responses from backend and backend will send multiple WorkItems in the same response proto. Backend changes are rollbacksafe.
The feature can be disabled by passing `--windmillRequestBatchedGetWorkResponse=false`

[Dataflow Streaming] Enable Windmill GetWork Response Batching by default

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java

For Dataflow V2, StateBackedIterable is iterated by readers after gbk shuffle. Examples are ParDo after GBK or merging combiners after GBK. 
[metrics.proto](https://github.com/apache/beam/blob/master/model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/metrics.proto#L244) specifies that Sampling is used  because calculating the byte count involves serializing the elements which is CPU intensive. 
In case of StateBackedIterable sampling is not occurring which impacts performance of some of the pipelines that have expensive coders.
This change introduces sampling. 
Fully fixes #33620 as previous fix was improvement.

Calculate byte size via sampling in StateBackedIterable if size is not cheap to calculate

---

sdks/python/apache_beam/testing/benchmarks/README.md

Creates a quick overview on how to write cost benchmarks within the current framework.  …

Write how-to doc on dataflow cost benchmarking

---

CHANGES.md
model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto
sdks/go/pkg/beam/core/graph/coder/panes.go
sdks/go/pkg/beam/core/graph/coder/panes_test.go
sdks/go/pkg/beam/core/graph/window/trigger/trigger.go
sdks/go/pkg/beam/core/typex/special.go

While implementing Triggers + Panes for Prism, I ran into inexplicable failing tests.
It turns out that portable encoding of panes in the protos *does not* match the implementations in the Python, and Java SDKs, or the internal Dataflow implementation, and never has in the 5 years since it was added to the protocol buffers.
Specifically, the bits for first and last panes are swapped with first being the 7 indexed bit, and last being the 6 indexed bit.
Compare Python and Java
https://github.com/apache/beam/blob/master/sdks/python/apache_beam/utils/windowed_value.py#L92
https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/PaneInfo.java#L134
To Go's current implementation.
https://github.com/apache/beam/blob/release-2.62.0/sdks/go/pk …

[Go SDK + Protos] Fix Proto Spec for Pane encoding + Go SDK implementation.

---

sdks/go/pkg/beam/runners/prism/internal/engine/data.go
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/strategy.go
sdks/go/pkg/beam/runners/prism/internal/engine/strategy_test.go
sdks/go/pkg/beam/runners/prism/internal/execute.go

Mostly locking in some fixes and work to avoid making Triggers impossible to review. 
This PR has 3 components.
* Adds the bulk of the Trigger State Machine to be used in a different PR.
* Excludes handling Processing Time, and Merging Windows at this time.
* https://s.apache.org/beam-triggers for general handling. 
* Checked understanding against the Java TriggerStateMachine code which supports execution for Java runners.
* Compressed the logic into less abstract form, and simplified shouldFire and Fire handling into a single isReady tree.
* While it's building on Prism's state handling, it is *not* getting serialized and deserialized all the time, saving some memory and processing. 
* Fixes a bug WRT state and timer execution: Bundles can't mix timers and data, since there is no …

[#31438] Trigger Precusor work for Prism.

---

CHANGES.md
sdks/python/apache_beam/io/gcp/gcsfilesystem.py
sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

In this PR, we enable recursive deletion for Google Cloud Storage (GCS) paths, including directories and blobs. The `delete` method is updated to remove all blobs under a directory (prefix) when deleting GCS directories. 
Additionally, we update the delete test to verify the recursive deletion of directories containing multiple files.
Changes include:
- Enhanced `delete` method to support recursive directory deletion.
- Added tests for recursive deletion of directories and files.
Fixes #27605
Before             |  After
:-------------------------:|:-------------------------: …

sdks/python: enable recursive deletion for GCSFileSystem Paths

---

website/www/site/content/en/contribute/attributes.md
website/www/site/content/en/contribute/become-a-committer.md

It seems that this page was edited in a stylistic revamp, with links and text changed. I've restored it to its original content but kept the style changes. …

Restore "attributes of a Beam committer" to prior accuracy

---

.github/workflows/cut_release_branch.yml
release/src/main/scripts/set_version.sh
release/src/main/scripts/verify_release_build.sh

This is still probably easier than doing some regex slicing off of the last digit …

Update release branch cut to still update container and snapshot versions to 2.XX.0

---

sdks/python/apache_beam/ml/rag/ingestion/alloydb.py
sdks/python/apache_beam/ml/rag/ingestion/alloydb_it_test.py

Disabled test while I figure out how to configure the database arguments to run in dataflow and github action runners. …

Add AlloyDB vector writer.

---

sdks/python/apache_beam/ml/rag/ingestion/alloydb.py
sdks/python/apache_beam/ml/rag/ingestion/alloydb_it_test.py

Cherry-pick: Add AlloyDB vector writer. (#33841)

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/BoundedTrieCell.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/BoundedTrieData.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/BoundedTrieNodeTest.java
runners/google-cloud-dataflow-java/build.gradle
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowMetrics.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowMetricsTest.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContext.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToCounterUpdateConverter.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContextTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/MetricsToCounterUpdateConverterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java

- Adds support for bounded trie in Dataflow legacy workers.
- Streaming reports delta counters. This is essential because without it streaming will end up remaining same counters as cumulative through it's entire lifespan. This will be bad even with bounded trie which is self-limiting in size because in backend the level db monitoring writer keeps taking snapshot of counters on publish and writing to level db and for a long running job even with self-limiting data store the file sizes will keep growing. …

Add support for bounded trie metric in legacy worker

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

Sometimes this dry run will just not execute because of permissions issues. Unfortunately, permissions issues are 403s, and quota issues are also 403s so its tough to differentiate.
Since the dry run isn't necessary for the job to complete, but does block the job from starting, this reduces the total number of retries. Given the starting backoff of 1s, this should at most backoff: `1s+2s+4s+8s+16s = 31s`, which should be fine.
To check the …

Reduce time spent backing off dry run query

---

it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java
it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryStreamingLT.java

Fixes: [#30527](https://github.com/apache/beam/issues/30527)
Successful `PostCommit Java IO Performance Tests` example: https://github.com/akashorabek/beam/actions/runs/13194245851
Successful `BigQuery Stress test` example: https://github.com/akashorabek/beam/actions/runs/13194261396
Screen that correct number of rows were written to both tables (`PostCommit Java IO Performance Tests`):
Expected table:
Actual table: …

Fix Postcommit Java IO Performance tests workflow and BigQuery Stress Test

---

model/interactive/src/main/proto/org/apache/beam/model/interactive/v1/beam_interactive_api.proto
model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto
sdks/python/apache_beam/runners/direct/test_stream_impl.py
sdks/python/apache_beam/testing/test_stream_service.py
sdks/python/apache_beam/testing/test_stream_service_test.py

Notably this allows the protos in model/pipeline to be definitions only rather than mixing services and definitions. …

Move interactive-specific TestStreamService to interactive protos.

---

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow.json
runners/google-cloud-dataflow-java/build.gradle
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContext.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java

Skip BoundedTrie on Dataflow till service is have BoundedTrie 

---

.github/workflows/self-assign.yml

Fixing #33934 git task/close workflow breakage

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/data.go
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/engine_test.go
sdks/go/pkg/beam/runners/prism/internal/engine/strategy.go
sdks/go/pkg/beam/runners/prism/internal/engine/teststream.go
sdks/go/pkg/beam/runners/prism/internal/execute.go
sdks/go/pkg/beam/runners/prism/internal/handlecombine.go
sdks/go/pkg/beam/runners/prism/internal/handlecombine_test.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go

* Effectively makes all aggregation transforms (AKA, GBKs) stateful.
* Adds all non-processing time derived triggers.
* Adds support for Accumulation mode.
* Adds computation of panes for the triggered aggregation results.
* Handles trigger edge case WRT Lifted combines and ElementCount triggers by disabling lifting when one is detected.
* Added some of the Go trigger tests to the engine_test.go file, to maintain coverage.
* Note, the Go trigger tests are *not* canonical as the Go SDK has issues regarding panes, largely due to not having any runner that would support testing them. (see #31153)(until prism). 
Important notes: Does not support processing time triggers, or triggered side inputs or triggers against merging windows at this PR. Those will be supported at a later PR. 
Blocks …

[#31438] Non-processing time triggers pass w/accumulation.

---

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow.json
runners/google-cloud-dataflow-java/build.gradle
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContext.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java

Cherry-pick skip BoundedTrie on Dataflow till service is have BoundedTrie  (#33921) to release 2.63

---

sdks/go/pkg/beam/core/runtime/graphx/serialize.go
sdks/go/pkg/beam/runners/vet/vet.go
sdks/go/pkg/beam/runners/vet/vet_test.go

sdks/go: add string utf-8 check to vet runner for serialization

---

CHANGES.md
sdks/python/apache_beam/runners/worker/worker_status.py

This PR adds a workaround for https://github.com/python/cpython/issues/106883 .
fixes: https://github.com/apache/beam/issues/33966  …

Disable GC before collecting stack frames on Python 3.11

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/ResettableThrowingStreamObserver.java

do not spam logs when onNext called on closed StreamObserver as this can happen often outside of range movements
R: @scwhittle  …

do not spam logs when onNext called on closed StreamObserver

---

CHANGES.md
sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test.py
sdks/python/apache_beam/coders/typecoders.py
sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py
sdks/python/apache_beam/typehints/native_type_compatibility.py
sdks/python/apache_beam/typehints/typehints.py

* Revert the previously revert PR (#33414)
* Use `update_compatibility_version` flag to determine whether to change back to the previous behavior. (A suggestion from https://github.com/apache/beam/pull/33414#issuecomment-2555698837)
fixes #29908
fixes #33356

Support custom coders in Reshuffle

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java

This code is creating a field with the same type as a method return type. The return type is erased, but calling `getGenericSignature()` turns the erased type back into a generic type. For methods with type parameters, this results in signatures that are invalid for field declarations, for example
`<T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/io/Serializable;`. Future versions of bytebuddy reject the invalid signature.
See also https://github.com/raphw/byte-buddy/issues/1771
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md# …

Fix an invalid signature in ByteBuddyDoFnInvokerFactory

---

sdks/java/container/boot.go

#33508 supported use staged sdk harness, however, it is only effective when a staged jar named after beam-sdks-java-harness*.jar. In. the case a uber jar is used, the flag isn't effective.
This change will make the flag effective regardless the staged jar file names. …

Make use staged sdk harness effective whenever experiment flag added

---

.github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml

Fixes: [#33065](https://github.com/apache/beam/issues/33065)
Temporarily moved to GH hosted ubuntu-22.04 
Successful run example: https://github.com/akashorabek/beam/actions/runs/13375479284 …

Fix Python ValidatesContainer Dataflow ARM workflow

---

sdks/python/apache_beam/ml/anomaly/base.py
sdks/python/apache_beam/ml/anomaly/specifiable.py
sdks/python/apache_beam/ml/anomaly/univariate/__init__.py
sdks/python/apache_beam/ml/anomaly/univariate/base.py
sdks/python/apache_beam/ml/anomaly/univariate/mean.py
sdks/python/apache_beam/ml/anomaly/univariate/mean_test.py
sdks/python/apache_beam/ml/anomaly/univariate/perf_test.py
sdks/python/apache_beam/ml/anomaly/univariate/quantile.py
sdks/python/apache_beam/ml/anomaly/univariate/quantile_test.py
sdks/python/apache_beam/ml/anomaly/univariate/stdev.py
sdks/python/apache_beam/ml/anomaly/univariate/stdev_test.py

This is a follow-up PR of #33845.
We added tracker classes that will be used in the detectors and other components of the transform.

[AnomalyDetection] Add univariate trackers

---

sdks/python/apache_beam/ml/inference/huggingface_tests_requirements.txt

Fixes #30513
Successful run: https://github.com/akashorabek/beam/actions/runs/13414050137/job/37470457734
[![Build …

Fix PostCommit Python job

---

sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/WaitTest.java

There are lots of error logs showing up otherwise.
See https://github.com/apache/beam/actions/runs/13367967271/job/37335398780?pr=33979 for example:
```org.apache.beam.sdk.transforms.WaitTest > testWindowExpiration STANDARD_ERROR
[direct-runner-worker] WARN org.apache.beam.sdk.util.MutationDetectors - Coder of type class org.apache.beam.sdk.schemas.SchemaCoder has a #structuralValue method which does not return true when the encoding of the elements is equal. Element org.apache.beam.sdk.transforms.WaitTest$WindowExpirationValue@aaa632c
[direct-runner-worker] WARN org.apache.beam.sdk.util.MutationDetectors - Coder of type class org.apache.beam.sdk.schemas.SchemaCoder has a #structuralValue method which does not return true when the encoding of the elements is equal. Element …
```

add hashcode/equals to WaitTest helper classes to avoid log error

---

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Dataflow.json
runners/google-cloud-dataflow-java/build.gradle

Fix #33723; fix #33722; fix #33720 …

Add enable_lineage experiment to Dataflow tests

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java

Add support for UUID in `SpannerSchema.Column` class. This is needed to support UUID in Teleport.
R: @darshan-sj

Add UUID support in SpannerSchema

---

model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/metrics.proto
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoEncodings.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MonitoringInfoEncodingsTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java

This is a forward fix for https://github.com/apache/beam/pull/33761, where this was added in `java:core` with a dependency on the `dataflow-runner`. This adds it back in without that dependence.
Addresses https://github.com/apache/beam/issues/33093
GitHub Actions …

Add histogram parsing in runner v2

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java

sync https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2144 to Beam
* Refactor to use a immutablemap for fast mapping …

Update SpannerSchema to support postgres tokenlist

---

sdks/go/pkg/beam/io/bigqueryio/bigquery.go
sdks/go/pkg/beam/io/bigqueryio/bigquery_test.go

sdks/go: require type registrations in Native BigQuery IO

---

.github/workflows/beam_PreCommit_Java_GCP_IO_Direct.yml
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkRowUpdateIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/RampupThrottlingFnTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/HL7v2IOReadIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamOrderedWithinKeyIT.java

Fixes: [#33909](https://github.com/apache/beam/issues/33909)
Successful run example: https://github.com/akashorabek/beam/actions/runs/13397067650 …

Fix Java GCP-IO Direct job

---

sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/KafkaSourceConsumerFn.java
sdks/java/io/debezium/src/test/java/org/apache/beam/io/debezium/KafkaSourceConsumerFnTest.java

Example warning
```
WARNING: Can't verify serialized elements of type OffsetHolder have well defined equals method. This may produce incorrect results on some PipelineRunner implementations
Feb 20, 2025 11:02:40 AM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
WARNING: Coder of type class org.apache.beam.sdk.coders.KvCoder has a #structuralValue method which does not return true when the encoding of the elements is equal. Element KV{{topic=any, from=1, to=3, delay=0.2}, org.apache.beam.io.debezium.KafkaSourceConsumerFn$OffsetHolder@58983367}
Feb 20, 2025 11:02:40 AM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
``` …

add equals/hashCode to avoid coder warning

---

sdks/python/apache_beam/yaml/examples/transforms/aggregation/combine_sum_windowed.yaml
sdks/python/apache_beam/yaml/yaml_mapping.py
sdks/python/apache_beam/yaml/yaml_mapping_test.py

YAML users don't have access to DoFn params or annotations, so we provide this as an explicit transform.
[![Build …

Add an ExtractWindowingInfo transform.

---

sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

Previously, parameterized generics that made it to the issubclass call would
fail and cause obscure stack traces to bubble up. Short-circuiting this logic
by unconditionally rejecting ensures the type check failure case will handle
the error message generation and display.

Preempt issubclass error for generic types

---

sdks/python/apache_beam/transforms/stats.py
sdks/python/apache_beam/typehints/native_type_compatibility.py
sdks/python/apache_beam/typehints/native_type_compatibility_test.py
sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

Work towards #29135
Notes:
- The naming used for the TypeConstraint is necessary to avoid colliding with
the existing base class used for other collections.abc generics.
- The change in transforms/stats.py is required due to a test failure that
appears to require `int` be a valid param instead of `Sequence[int]`.

Add support for collections.abc.Sequence

---

sdks/python/apache_beam/yaml/examples/regex_matches.yaml
sdks/python/apache_beam/yaml/examples/simple_filter.yaml
sdks/python/apache_beam/yaml/examples/simple_filter_and_combine.yaml
sdks/python/apache_beam/yaml/examples/wordcount_minimal.yaml
sdks/python/apache_beam/yaml/generate_yaml_docs.py

This should help discoverability.  …

Create a listing of YAML examples for the docs.

---

sdks/python/apache_beam/options/pipeline_options.py

Improve the handling of the `update_compatibility_version` option.
- When the argument is not provided, the default value `None` is used.
- Previously, using the argument as a standalone flag (e.g., `--update_compatibility_version`) resulted in an exception. This has been corrected to also resolve to `None`, aligning with the intended behavior.
- Explicitly providing a version (e.g., `--update_compatibility_version=2.63.0`) will use that specified value.
(Internal bug id: 398402007, 399132073)

Fix the case when update_compatibility_version is used without argument.

---

.github/workflows/republish_released_docker_containers.yml
build.gradle.kts

Allow docker push to be easily split up into pieces by excluding tasks which have been run in a different piece.
Part 1 of https://github.com/apache/beam/issues/34084 …

Enable splitting up docker publish workflow

---

sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py
sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/options/pipeline_options_test.py

Users can use pipeline options `--gcs-custom-audit-entry` or `--gcs-custom-audit-entries` to specify custom information that will be attached to audit logs.
For example, when a user specifies an entry with of `key:value`, a header entry of `x-goog-custom-audit-key:value` will be included in the request.
See https://cloud.google.com/storage/docs/audit-logging#add-custom-metadata for more details.
(Internal bug id: 398744411)

Allow users to specify custom audit entries in pipeline options.

---

CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProtoTest.java

I noticed that in Beam 2.63, TIME types were being encoded incorrectly when using the Storage Write API. For example, I'd try to write a value of 6:30 and it would get written to BQ as 5:28. See #34038.
I looked at what the other *ToStorageApiProto classes were doing ([TableRowToStorageApiProto](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java), [BeamRowToStorageApiProto](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProto.java)) and noticed they were using this `CivilTimeEncoder` class to translate TIME types to Longs, whereas `AvroGenericRecordToStorageApiProto` was trying to …

(fix #34038) Use CivilTimeEncoder to encode Time values in AvroGenericRecordToStorageApiProto

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/flink/flink_runner.gradle
runners/flink/src/test/java/org/apache/beam/runners/flink/metrics/FlinkMetricContainerTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerStaticTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowRunnerTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/util/PackageUtilTest.java
runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/HotKeyLoggerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillStateInternalsTest.java
runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/BundleFinalizationHandlersTest.java
runners/samza/src/test/java/org/apache/beam/runners/samza/runtime/ClassicBundleManagerTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/SparkExecutableStageFunctionTest.java
sdks/java/build-tools/src/main/resources/beam/checkstyle/checkstyle.xml
sdks/java/expansion-service/build.gradle
sdks/java/io/google-cloud-platform/build.gradle
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubUnboundedSink.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/firestore/BaseFirestoreV1WriteFnTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOExternalTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/ChildPartitionsRecordActionTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataDaoTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/testing/BigqueryClientTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/testing/BigqueryMatcherTest.java
sdks/java/io/hadoop-format/src/test/java/org/apache/beam/sdk/io/hadoop/format/HadoopFormatIOReadTest.java
sdks/java/io/influxdb/build.gradle
sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaWriter.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOExternalTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ProducerRecordCoderTest.java

Part of #34056 . Powermock is not compatible with Mockito 4, had to remove its usage in most tests, if applicable
* Split tests need mockStatic outside of DataflowTest
To be able to run DataflowTest internally which did not support mockStatic
* Remove usage of powermock for GcpIO, KafkaIO, DataflowRunner tests
* Minimize powermock dependency for Flink runner …

Bump to Mokito 4

---

sdks/python/apache_beam/testing/util.py

The process of `assert_that` has a `coGroupByKey()` call to ensure that it always executes; however, this process produces an output of an `Iterable` type that doesn't provide guarantees of materialization downstream. Automatically coercing the iterable output to a list forces the values to be materialized for the purposes of type checking, allowing matchers to call `__len__` and `__getitem__` with tighter guarantees of their availability. As we already document and expect the values used in `assert_that` to be materialized, this is not a backwards-incompatible change. Additionally, this will not break existing matcher implementations as `list` types inherit from `Iterable` and can be treated as such in matching code.  …

Coherce values in assert_that to lists from iterables

---

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark.json
.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming.json
runners/spark/spark_runner.gradle

Fix post commit test failure on spark after slf4j 2.x upgrade (#33574).
- https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_ValidatesRunner_Spark.yml
- https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming.yml

Add log4j2 deps for spark validatesRunner tasks.

---

.github/workflows/refresh_looker_metrics.yml
.test-infra/tools/refresh_looker_metrics.py

Automatically refresh Performance Metrics Graphs using Looker

---

CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java

related to https://github.com/apache/beam/pull/33368; Beam cannot upgrade its [bigdataoss libs](https://github.com/GoogleCloudDataproc/hadoop-connectors) to 3.x yet, since they target Java 11 bytecode. However, there are a few breaking changes in 3.x that prohibit me as an end-user from upgrading my project to use 3.x.  In addition to the linked PR, this one updates the reference to `AsyncWriteChannelOptions.UPLOAD_CHUNK_SIZE_DEFAULT`, which has been removed in 3.x, and uses an API compatible with both 2.x and 3.x. …

Use bigdataoss 3.x-compatible API in BigQueryIO's BatchLoads

---

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark.json
.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming.json
.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark_Java11.json
runners/spark/src/main/java/org/apache/beam/runners/spark/TestSparkPipelineOptions.java
runners/spark/src/main/java/org/apache/beam/runners/spark/TestSparkRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SingleEmitInputDStream.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/streaming/StreamingTransformTranslator.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/SingleEmitInputDStreamTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/streaming/StreamingTransformTranslatorTest.java

fixes #18144
fixes #20426
This PR replaces Spark's queueStream with a custom SingleEmitInputDStream implementation 
for the Flatten transform in Spark streaming. The queueStream was not checkpoint-able, 
which caused issues when recovering pipelines with flattened bounded and unbounded PCollections.
The custom SingleEmitInputDStream ensures:
- Proper checkpoint recovery for Flatten transform
- Single emission of bounded data in streaming context
- Reliable handling of mixed bounded/unbounded PCollections
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how …

Spark Runner : Replace queueStream with custom DStream in Spark streaming Flatten transform

---

.github/actions/setup-environment-action/action.yml
.github/gh-actions-self-hosted-runners/arc/images/Dockerfile
.github/workflows/build_release_candidate.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
dev-support/docker/Dockerfile
playground/infrastructure/cloudbuild/playground_ci_examples.sh
sdks/go/run_with_go_version.sh

Follow https://github.com/apache/beam/blob/master/contributor-docs/release-guide.md#dependency-checks to update Go. …

updated Go to 1.24.0

---

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptions.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/Transport.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptionsTest.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/util/TransportTest.java

This PR implements the same functionality of #34062 in Java SDK.

[Java] Allow users to specify GCS custom audit entries in pipeline options 

---

sdks/java/io/mqtt/src/test/java/org/apache/beam/sdk/io/mqtt/MqttIOTest.java

From local tests, it looks like even though we publish 10 messages, the server isn't up yet, so we miss the first couple of messages which is why the assertions fail. What isn't clear to me is why that has transient failures, but the regular read test doesn't 
History: https://develocity.apache.org/scans/tests?search.relativeStartTime=P28D&search.timeZoneId=America%2FLos_Angeles&tests.container=org.apache.beam.sdk.io.mqtt.MqttIOTest
This is flakey enough that you can see this running locally, but adding in a sleep got rid of it. Ideaaly there would be a nicer method of checking if the server was up and ready to accept messages, but couldn't figure out a nice quick easy way to do that.  …

Add sleep to give enough time for server to be up

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/Read.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/ReadTest.java

Previously reportProgress could cache a reader for the initialRestriction of a source that was unstarted. If this was used for a subsequent read it could happen that the source is advanced and checkpointed without having start called. …

[Java] Fix UnboundedReaderAsSdfFn to avoid using unstarted unbounded reader.

---

CHANGES.md

Call out the potential for incorrect Sequence type hints to break after #33999  …

Add Sequences support to Breaking Changes

---

sdks/java/managed/src/main/java/org/apache/beam/sdk/managed/Managed.java
sdks/python/apache_beam/transforms/managed.py

Updates Managed Javadocs and pydocs to refer to runner specific features

---

runners/spark/3/src/main/java/org/apache/beam/runners/spark/structuredstreaming/translation/batch/ParDoTranslatorBatch.java
runners/spark/src/main/java/org/apache/beam/runners/spark/DependentTransformsVisitor.java
runners/spark/src/main/java/org/apache/beam/runners/spark/SparkRunner.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/EvaluationContext.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/TransformTranslator.java
runners/spark/src/test/java/org/apache/beam/runners/spark/DependentTransformsVisitorTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/RDDTreeParser.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/TransformTranslatorTest.java

Find pCollections which are outputs of multi-output PadDo and skip them in case they are not consumed by any other pTransform. This prevents a fork in Spark job dag and does not process source data multiple times unnecessarily #33771  …

[Spark] Skip unused outputs of ParDo in SparkRunner (#33771)

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

`./gradlew clean` can fail because we create a new virtual environment as part of the clean python task, then run a script which eventually calls https://github.com/apache/beam/blob/master/sdks/python/gen_xlang_wrappers.py - this has dependency requirements.
I ran into this and it kept me from correctly cleaning the environment, but this should fix the problem.
Fixes #30954 …

Fix cleanPython

---

sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient_test.py

Right now, if you submit a job like:
```
options = PipelineOptions()
options.view_as(StandardOptions).runner = "DataflowRunner"
<other options>
options.view_as(GoogleCloudOptions).labels = {'env': 'bluecore-qa-extensibility', 'team': 'cdp-vertical'}
with beam.Pipeline(options=options) as p:
<do stuff>
```
The job does not correctly recognize the labels. We could validate and fail because labels is expected to be a list, but that might break existing (mostly working) pipelines. This is an in between where we can still do a best effort to correctly identify/use the user's labels. …

Correctly parse labels if they are passed as a single string instead of a list

---

.github/trigger_files/beam_PostCommit_Python_Xlang_Gcp_Direct.json
sdks/python/apache_beam/ml/rag/ingestion/alloydb.py
sdks/python/apache_beam/ml/rag/ingestion/alloydb_it_test.py

Add AlloyDB language connector capabilities to alloydb vector writer. This allows iam auth, connecting via instance name and mlts. …

Alloy language connector

---

sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

Calls of `get_yielded_type()` when used on a `Union` of `Iterables` would fail, as the `UnionConstraint` class does not provide an `inner_type` attribute. This allows the function to properly recurse and produce a union of the potential yielded types when all members of the input union are iterable.  …

Catch union-of-iterables case in get_yielded_type()

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java

Fixes: [#34173](https://github.com/apache/beam/issues/34173)
Removed the assertion from `testInvalidRecordReceived` because it's acceptable for the test to show more than 2 retries. The error happens after the call returns a bad result, not during the call itself, so each retry counts as a full request. I think this behavior is expected and doesn't indicate a problem with the retry logic. …

Remove retry count assertion from testInvalidRecordReceived

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/InsertRetryPolicy.java

BigQueryIO's `InsertRetryPolicy` only applies to per-element errors within 200 OK responses. Non-200 responses (e.g., 400 Bad Request) are not handled by the policy and cause indefinite retries in Dataflow streaming jobs, even with `InsertRetryPolicy.neverRetry()`. (b/399533242)
This PR updates the `InsertRetryPolicy` javadoc to clarify this behavior. …

Clarify BigQuery InsertRetryPolicy behavior for non-200 responses

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java

Fixes: [#30729](https://github.com/apache/beam/issues/30729)
Successful run example: https://github.com/akashorabek/beam/actions/runs/13722098733 …

Fix PostCommit Java DataflowV2

---

sdks/java/extensions/schemaio-expansion-service/src/main/java/org/apache/beam/sdk/extensions/schemaio/expansion/ExternalSchemaIOTransformRegistrar.java

We don't need this after avro is fully moved out of sdks/java/core
Resolve a TODO added in #25611 …

Clean up ExternalTransformRegistrar

---

.github/workflows/python_dependency_tests.yml
sdks/python/container/base_image_requirements_manual.txt
sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt

Pin python-snappy==0.6.1

---

model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/metrics.proto
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsContainerImpl.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoConstants.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoMetricName.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MetricsContainerImplTest.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/MonitoringInfoConstantsTest.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/DelegatingGauge.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/LabeledMetricNameUtils.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/MetricName.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Metrics.java
sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/MetricsContainer.java
sdks/java/core/src/test/java/org/apache/beam/sdk/metrics/LabeledMetricNameUtilsTest.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/firestore/RpcQosImpl.java
sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaMetrics.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetrics.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaMetricsTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetricsTest.java

Add per worker metadata on metrics propaged over FnApi. This is on top of https://github.com/apache/beam/pull/33408  …

Kafka add counters v1 uw2

---

dev-support/docker/Dockerfile
dev-support/docker/pkglist

I was setting up the dev environment using Docker and came across these errors...
1. python12-disutils not found - From https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated, it looks like ```distutils``` is deprecated and removed in python 3.12 in place of ```setuptools``` which we already installed with ```python3-setuptools```. 
2. NullPointerException when running task :sdks:java:core:compileJava - From the Docker image I was using Java 8 and got this NPE error. If I used Java 11, it was fine. Based on the ```contributor-docs/code-change-guide.md```, Java 11 is preferrable but in the ```CONTRIBUTING.md``` Java 8 is still being recommended... …

Fix Docker dev environment set up

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/MultimapSideInput.java

We never actually re-issue this call, and in addition the cache key didn't take the bulkReadRequest into account resulting in key collisions and class cast errors. …

Don't attempt to cache the bulk multimap lookup call.

---

sdks/python/apache_beam/ml/anomaly/transforms.py
sdks/python/apache_beam/ml/anomaly/transforms_test.py

- Add transforms for anomaly detection
Depends on #34232

[AnomalyDetection] Add main and auxiliary transforms.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java

Putting the default retry settings for spanner which was overridden in Dataflow templates Dataflow templates …

Putting the default retry settings which was overridden in Dataflow templates

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/RecordWriterManagerTest.java

This PR adds support for configuring metrics in Iceberg data writers.Also added tests for the same.
Fixes #34112 …

[Java] Added Metrics Configuration Support to Iceberg Data Writers

---

.github/trigger_files/beam_PostCommit_Java_PVR_Spark3_Streaming.json
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java

fixes #20426 
This PR addresses an issue in the `translateImpulse` method of the `SparkStreamingPortablePipelineTranslator`, which was introduced in the changes made under #34080.
The root cause of the test failures was the use of `ConstantInputDStream` instead of `SingleEmitInputDStream`. This incorrect implementation led to the impulse being emitted multiple times, causing unexpected behavior.
By replacing `ConstantInputDStream` with `SingleEmitInputDStream`, this issue has been resolved.
related PR : #34253 …

Spark Runner : Fix invalid translateImpulse

---

CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProto.java

`Schema.Field` in Avro 1.8 doesn't support the three-arg constructor that's available in 1.11:
https://github.com/apache/avro/blob/release-1.8.2/lang/java/avro/src/main/java/org/apache/avro/Schema.java#L393-L424
vs
https://github.com/apache/avro/blob/release-1.11.4/lang/java/avro/src/main/java/org/apache/avro/Schema.java#L588-L589
Switching to the four-arg constructor makes the storage write API compatible for Avro 1.8 through Avro 1.11.
To …

Use Avro 1.8-compatible Schema constructors in Storage Write API translator

---

sdks/python/apache_beam/ml/anomaly/specifiable.py
sdks/python/apache_beam/ml/anomaly/specifiable_test.py
sdks/python/apache_beam/ml/anomaly/transforms.py

With this PR, we will now support generating Spec for a specifiable initialized with classes or functions as init arguments.
In addition, re-registering a spec_type with the same class is now allowed. Trying to override with a different class will still lead to an exception though.

[AnomalyDetection] Support functions and classes as init arguments in specifiable.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillEndpoints.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillChannelFactory.java

`HostAndPort#getPort` throws an `IllegalStateException` if `getPort` is called w/o a port set. 
Supply a default port in these cases. `443` is currently the default port specified in `DataflowStreamingPipelineOptions`
r: @scwhittle @acrites 
example error:
GitHub …

add default port for HostAndPort instances used in Windmill

---

sdks/python/apache_beam/examples/snippets/snippets_test.py

Fix typo in docs related to **9.5.2. Composition with AfterWatermark**
[https://beam.apache.org/documentation/programming-guide/#composite-afterwatermark](https://github.com/apache/beam/pull/url)
addresses [#34224](https://github.com/apache/beam/issues/34224)

docs: fix typo in snippets_test.py

---

sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_test.py

Better error messages for unavailable providers.

---

sdks/python/apache_beam/utils/subprocess_server.py

Fix #21006
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels …

Honor JAVA_HOME when it is set

---

sdks/python/apache_beam/ml/anomaly/base.py
sdks/python/apache_beam/ml/anomaly/specifiable.py
sdks/python/apache_beam/ml/anomaly/specifiable_test.py

- Better type hinting in specifiable with overloads
- Move non-method attributes and static methods out of Specifiable Protocol
- Make spec_type a function which returns a class-specific spec_type variable
- Add tests for some uncommon use cases.

[AnomalyDetection] Refactor and improve Specifiable

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/portability/expansion_service_main.py
sdks/python/apache_beam/runners/portability/fn_api_runner/worker_handlers.py
sdks/python/apache_beam/utils/subprocess_server.py
sdks/python/apache_beam/yaml/examples/testing/examples_test.py
sdks/python/apache_beam/yaml/examples/transforms/elementwise/map_to_fields_with_deps.yaml
sdks/python/apache_beam/yaml/examples/transforms/elementwise/map_to_fields_with_java_deps.yaml
sdks/python/apache_beam/yaml/yaml_enrichment_test.py
sdks/python/apache_beam/yaml/yaml_mapping.py
sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/setup.py

Allow declaration of external dependencies for YAML UDFs.

---

sdks/python/apache_beam/ml/anomaly/detectors/offline.py
sdks/python/apache_beam/ml/anomaly/transforms.py
sdks/python/apache_beam/ml/anomaly/transforms_test.py

[AnomalyDetection] Support offline detectors

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillTimerInternals.java

#33578
Example 
old profile: 
new profile:

[Dataflow Streaming] WindmillTimerInternals: Use a single map to store timer data + liveness

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/construction/UnboundedReadFromBoundedSource.java
sdks/java/core/src/test/java/org/apache/beam/sdk/util/construction/UnboundedReadFromBoundedSourceTest.java

To resolve warning logs:
```
[direct-runner-worker] WARN org.apache.beam.sdk.util.MutationDetectors - Coder of type class org.apache.beam.sdk.coders.SerializableCoder has a #structuralValue method which does not return true when the encoding of the elements is equal. Element Shard{source=org.apache.beam.sdk.util.construction.UnboundedReadFromBoundedSource$BoundedToUnboundedSourceAdapter@5f6608ca, maxNumRecords=100, maxReadTime=null}
```
To …

add equals hashCode to BoundedToUnboundedSourceAdapter

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/common/worker/ReadOperation.java

In some cases it is possible for a thread pool executor to hang on cancelled tasks when awaitTermination is called - https://bugs.openjdk.org/browse/JDK-7069418 - and we've seen some hangs in practice.
This attempts to fix the problem by waiting up to 10 minutes before forcing a hard termination. I don't have a repro of the initial problem, so I can't be sure this is a fix. But it should be low risk and may resolve the issue, if not it will give more telemetry next time. The downside of this seems fairly minimal since we're almost definitely already in a bad state if we encounter this.
Internal issue: b/401998125 …

Remove cancelled tasks from ReadOperation queue when shutting down

---

.github/workflows/beam_PreCommit_Flink_Container.yml
.github/workflows/flink-tests-pipeline-options/python_Combine_Flink_Batch_small.txt
.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Fixes: [#33942](https://github.com/apache/beam/issues/33942)
Added additional steps to build and push the Python SDK with the PR changes, triggered by the 'pull_request_target' event.
Successful run example: https://github.com/akashorabek/beam/actions/runs/13788874678/job/38563303866?pr=7
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.te …

Fix precommit flink container

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisTransformRegistrar.java
sdks/python/apache_beam/io/external/xlang_kinesisio_it_test.py
sdks/python/apache_beam/io/kinesis.py

addresses https://github.com/apache/beam/issues/34319
I have added an option to do aggregation in the `apache_beam.io.kinesis` module. …

Aggregation option in Kinesis Writer Python sdk

---

sdks/python/apache_beam/dataframe/doctests.py

This should resolve the apache_beam/dataframe/pandas_doctests_test.py::DoctestTest::test_top_level failure sometimes seen in beam_PreCommit_Python_Dataframes. …

Fix pandas doctests sensitive to NumpyExtensionArray formatting.

---

sdks/java/core/src/main/java/org/apache/beam/sdk/fn/data/BeamFnDataInboundObserver.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java

This is accomplished by changing to iterators which throw away elements that have been passed as well as just referring to the inputstream of the element instead of the entire stream. If the ByteString is based upon a ByteBuffer this will allow blocks that have been advanced past to be gc'd.
This isn't done for the inlined elements to process data as that request is kept alive in many other places. I investigated fixing it but it resulted in some complicated code and since inlining is only performed for small-enough inputs it doesn't seem worth it. …

Avoid holding data elements alive via stack frame gc roots.

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsContainerImpl.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MonitoringInfoEncodings.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetrics.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java

Adds sdf poll metrics to kafka for runner v2
Should be merged after  https://github.com/apache/beam/pull/34244
[![Build …

Add sdf kafka poll latencies

---

examples/notebooks/beam-ml/alloydb_product_catalog_embeddings.ipynb

The new example runs in dataflow because streaming with xlang is not supported on Python DirectRunner [1]
[1] https://github.com/apache/beam/blob/611eb6a7e4a86b89d5350a16eddb7681bbcd8175/sdks/python/apache_beam/runners/direct/direct_runner.py#L569
GitHub Actions …

Add streaming example to AlloyDB colab.

---

sdks/python/apache_beam/runners/portability/expansion_service_main.py

Fixes #30960
Successful run: https://github.com/Amar3tto/beam/actions/runs/13992581500 …

Fix PostCommit TransformService Direct job

---

.github/trigger_files/beam_PostCommit_Python_Xlang_Gcp_Direct.json
sdks/python/apache_beam/coders/coder_impl.pxd
sdks/python/apache_beam/coders/coder_impl.py
sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test_common.py
sdks/python/apache_beam/coders/row_coder.py
sdks/python/apache_beam/coders/row_coder_test.py
sdks/python/apache_beam/coders/slow_stream.py
sdks/python/apache_beam/coders/stream.pxd
sdks/python/apache_beam/coders/stream.pyx
sdks/python/apache_beam/coders/stream_test.py
sdks/python/apache_beam/io/external/xlang_jdbcio_it_test.py
sdks/python/apache_beam/utils/subprocess_server.py

Fix #34089
This fixes negative int32 field passed from java to python in xlang transform  …

Create a varint32 coder and used it for RowCoder

---

.github/trigger_files/beam_PostCommit_XVR_Direct.json
.github/trigger_files/beam_PostCommit_XVR_PythonUsingJavaSQL_Dataflow.json
sdks/python/apache_beam/coders/coder_impl.py
sdks/python/apache_beam/coders/stream.pxd
sdks/python/apache_beam/coders/stream.pyx

Follow up #34354
to make test involved in #34438 happy. This is a possible use case that a integer overflow happened in the middle then recovered back …

tolerate integer overflow when encoding varint32

---

sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

See #34410 for context.
Testing:
- Unit tests: `pytest -v apache_beam/typehints/*_test.py`
- I patched the change into the Google monorepo and ran a global presubmit

Use list instead of set to make type hint serialization deterministic

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/ExecutionStateTracker.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/common/worker/MapTaskExecutorTest.java

in an attempt to fix "data race ExecutionStateTracker.java:261 in org.apache.beam.runners.core.metrics.ExecutionStateTracker.deactivate()V" reported by internal test (internal bug: 401543527)
The source already declared "millisSinceBundleStart" volatile. "nextBundleLullDurationReportMs" operated by the same methods "reportBundleLull" should be consistent with it …

Move ExecutionStateTracker.nextBundleLullDurationReportMs reset attempt to resolve race detection

---

playground/frontend/playground_components/assets/symbols/java.g.yaml
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java
sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProviderTest.java
sdks/python/apache_beam/yaml/standard_io.yaml

addresses #34349 Beam Yaml JdbcIO partitioning …

Feature: Yaml JdbcIO partitioning for ReadRows

---

sdks/python/setup.py

warning for copy_tests_from_docs

---

.github/workflows/refresh_looker_metrics.yml
website/www/site/data/performance.yaml

Changes:
- Fix `tensorflowmnist` section on website
- Remove schedule trigger for `refresh_looker_metrics` workflow.
Explanation: We're using Looker Cloud (Google Cloud core) with active API3 credentials, which allows us to successfully authenticate and call most Looker API endpoints such as `search_looks` or `run_look`. However, when we attempt to call render-related methods like `create_look_render_task`, the API returns an error requiring an OAuth login (or OAuth session expired).
This happens because in Looker Cloud, API3 tokens do not create a full OAuth session, which is required for rendering visualizations. One possible workaround I am considering in the short term is manually logging into Looker via a browser to activate a user session, and then running the workflow (via …

Fix looker metrics

---

CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
website/www/site/content/en/blog/beam-2.64.0.md

After upgrading the spanner library, users can run into a NPE because we were not correctly guarding against null or empty spanner hosts. Previously, the spanner client swallowed this error, but it now throws.
Users can currently fix this by not calling `withHost` when constructing `SpannerConfig` if their host is null or empty.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https …

Fix Spanner NPE when withHost called with null or empty host

---

it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManager.java
it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerTest.java

Goal: I would like to be able to set up time partitioned testing tables using BigqueryResourceManager.
Issue: fixes #34470 , and is a blocker for https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/2273 in DataflowTemplates
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow%3 …

Support Time Partitioned Test Tables in BigqueryResourceManager

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go

Otherwise the original non-reified windowing is used and can confuse the runner, which encodes the gbk input using global windows but was attempting to decode it as original windowing.
This fixes Dataflow runner harness failures when a non-global windowed pcollection is reshuffled.  A work around before this fix would be to explicitly rewindow to the global window before reshuffling and reapply the desired windowing after reshuffling.
This isn't caught by prism because the entire reshuffle is replaced. …

[Go] Fix reshuffle implementation to use the global window for gbk output

---

CHANGES.md
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/build-tools/src/main/resources/beam/checkstyle/suppressions.xml
sdks/java/io/google-ads/build.gradle
sdks/java/io/google-ads/src/main/java/org/apache/beam/sdk/io/googleads/GoogleAdsIO.java
sdks/java/io/google-ads/src/main/java/org/apache/beam/sdk/io/googleads/GoogleAdsV19.java
sdks/java/io/google-ads/src/test/java/org/apache/beam/sdk/io/googleads/DummyRateLimitPolicy.java
sdks/java/io/google-ads/src/test/java/org/apache/beam/sdk/io/googleads/GoogleAdsIOTest.java
sdks/java/io/google-ads/src/test/java/org/apache/beam/sdk/io/googleads/MockGoogleAdsClientFactory.java

In preparation for Beam 2.65.0. GoogleAdsv17 is set to sunset on June 4, 2025: https://developers.google.com/google-ads/api/docs/sunset-dates
* Make pipeline source code using GoogleAdsIO backward compatible
* Move GoogleAds dependencies outside of BeamModulePlugin since only one module using it …

Bump GoogleAdsIO to v19

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java

This brings it in line with ReadFromPubSub. …

Add STRING format to ReadFromKafka schema transform.

---

.github/workflows/cut_release_branch.yml
release/src/main/scripts/set_version.sh

Add a tag (e.g. v-2.64.0-RC00) to master branch when release is cut.
Currently, `git describe` inquiry on master branch gives `jupyterlab-sidepanel-v3.0.0`, this confused some internal import tool parse the version to 3.0.0 (see: cl/741579610)
by introducing a v-2.xx.0-RC00 on master branch `git describe` can have expected results
Tested on fork: https://github.com/Abacn/beam/actions/runs/14227274801
It does created a tag: https://github.com/Abacn/beam/tree/v2.65.0-RC00
after this is merged, I'm going to manually push v2.64.0-RC00 points to 24c230510be8b5e400021e8325ea654481c13698 (the branch right before 2.65.0-SNAPSHOT) …

Add an v-2.XX.0-RC00 tag to master when release branch is cut to enable git describe

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/AbstractWindmillStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcCommitWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillStreamFactory.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/AbstractWindmillStreamTest.java

Currently a single blocked stream can prevent health checks from multiple streams.  Use the stream's internal executor to hand do the health check RPC in a way that does not block the health check scheduling thread.
R: @acrites @scwhittle  …

do not block other threads from health checking if a stream is blocked

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java

Avoid calling getStackTrace when results are cached in RowCoderGenerator.generate

---

sdks/python/apache_beam/ml/inference/base.py
sdks/python/apache_beam/ml/inference/base_test.py
sdks/python/apache_beam/utils/retry.py

Implementation of a generic remote model handler abstract base class with small unit tests. The intent is to refactor the existing Vertex AI model handler to use this base class in a follow-up PR, followed by fresh implementations afterwards.
Outlined in a brief design doc - https://docs.google.com/document/d/17A_oHJ7s3ol4TGCUpKeYc6iozkcTwN_e4H_J3kRlgPM/edit?usp=sharing …

Introduce RemoteModelHandler abstract base class

---

sdks/python/apache_beam/internal/cloudpickle_pickler.py
sdks/python/apache_beam/internal/cloudpickle_pickler_test.py

#21298
EnumDescriptors:
Cloudpickle encodes globals from main module to be able to recreate them in the runtime environment. Dill is more lightweight and just expects the main session to be loaded.
EnumDescriptors cannot be pickled because of complex cythonized code. This PR adds a way to serialize enum descriptors by reference for cloudpickle
Locks:
Dill has built in support for pickling locks. Cloudpickle added similar functionality for RLocks https://github.com/apache/beam/blob/fdb285d91f86fd345a254e082c025fc6db624c96/sdks/python/apache_beam/internal/cloudpickle_pickler.py#L106. This PR adds the same for reguar threading.Lock …

Add reducers for threading.Lock and EnumDescriptor.

---

sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3ReadableSeekableByteChannelTest.java

This PR adds comprehensive unit tests for the `S3ReadableSeekableByteChannel` class to improve reliability and prevent issues like BEAM-4421, which highlighted potential problems with S3 file handling.
Closes #18757 
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUI …

[Java] Added tests for S3ReadableSeekableByteChannel

---

website/www/site/content/en/documentation/sdks/python-custom-multi-language-pipelines-guide.md
website/www/site/layouts/partials/section-menu/en/sdks.html

Fixing typos for page https://beam.apache.org/documentation/sdks/python-custom-multi-language-pipelines-guide

Fix link typos

---

sdks/python/apache_beam/ml/rag/chunking/langchain_test.py
sdks/python/tox.ini

Fixes: [#31285](https://github.com/apache/beam/issues/31285), [#30799](https://github.com/apache/beam/issues/30799)
Successful PostCommit Python Dependency example: https://github.com/akashorabek/beam/actions/runs/14305849321
Successful PreCommit Python ML tests with ML deps installed example: https://github.com/akashorabek/beam/actions/runs/14305842322
Explicitly installed latest `accelerate` for tests that require the latest version of `transformers (4.51.0)`, since otherwise it throws the error: "NameError: name 'init_empty_weights' is not defined". The solution is described [here](https://github.com/huggingface/transformers/issues/37326#issuecomment-2781631737). Also switched from encode to tokenize in langchain_test.py. …

Fix PostCommit Python Dependency and PreCommit Python ML tests

---

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkJobInvoker.java
runners/java-job-service/src/main/java/org/apache/beam/runners/jobsubmission/JobInvoker.java

Note that this is an actual error not just a hardening of the codebase: the `retrievalToken` is marked as required in the proto. …

Fix incorrect nullness in FlinkJobInvoker and JobInvoker

---

sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
sdks/go/pkg/beam/runners/prism/internal/preprocess.go
sdks/go/pkg/beam/runners/prism/internal/preprocess_test.go
sdks/python/apache_beam/runners/portability/prism_runner_test.py

Fix Prism on handling empty and identity transforms

---

CHANGES.md
sdks/java/io/file-schema-transform/build.gradle
sdks/java/io/iceberg/build.gradle
sdks/java/io/parquet/build.gradle

Addresses https://nvd.nist.gov/vuln/detail/CVE-2025-30065 …

Switch to parquet_version 1.15.1

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/runners/common.py
sdks/python/apache_beam/runners/common_test.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/runners/pipeline_utils.py
sdks/python/apache_beam/runners/pipeline_utils_test.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/runner.py

Specifically, merge environments that are identical except for their dependencies, but where one environment's dependencies are a superset of the others.
This will reduce the number of distinct environments of the same type, and the associated materialization costs of moving between them.
Ideally this would be done in a runner for environments that are already co-located on the same worker, but that is a further optimization. …

More eagerly merge compatible environments.

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/handlerunner.go

Fix coder corruption in prism while handling flatten

---

sdks/python/apache_beam/io/requestresponse.py
sdks/python/apache_beam/ml/inference/vertex_ai_inference.py

Simplifies the Vertex AI model handler implementation by migrating to the new RemoteModelHandler base class. Should be a backwards-compatible change, as the args to the constructor have not changed. …

Migrate Vertex AI Model Handler to new base class

---

sdks/go/pkg/beam/runners/prism/internal/handlerunner.go

We see some test flakiness (https://github.com/apache/beam/actions/workflows/beam_PreCommit_Prism_Python.yml) after #34582. 
Here is a simple pipeline to reproduce:
```python
with beam.Pipeline(options=options) as p:
side1 = p | 'side1' >> beam.Create([('a', 1)])
side2 = p | 'side2' >> beam.Create([('b', 2)])
third_element = [('another_type')]
side3 = p | 'side3' >> beam.Create(third_element)
side = (side1, side2) | 'Flatten1' >> beam.Flatten()
_ = (side, side3) | 'Flatten2' >> beam.Flatten() | beam.Map(print)
```
In #34582, we replace the coder ids in the input PCollections of each flatten transform. However, if there are multiple flatten transforms **and** they are connected to each other, the order of replacing matters:
- If we replace the coder of `Flatten1` and then `Flatten2`:
- the …

Fix a flatten flaky test when two flattens are used sequentially.

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Bump BQMS version

---

CHANGES.md
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/ZetaSQLQueryPlanner.java
sdks/java/extensions/sql/zetasql/src/main/java/org/apache/beam/sdk/extensions/sql/zetasql/package-info.java
website/www/site/content/en/documentation/dsls/sql/overview.md
website/www/site/content/en/documentation/dsls/sql/zetasql/overview.md

First step of #34423
* Announce deprecation in Beam website, changes, Javadoc
* Issue warning on SqlTransform expansion to ZetaSQL …

Deprecate ZetaSQL

---

sdks/go/pkg/beam/runners/prism/internal/coders.go
sdks/python/apache_beam/runners/portability/prism_runner_test.py

fixes #32636
Inspired by https://github.com/apache/beam/pull/34348#discussion_r2021658318 and some offline discussions with @lostluck.

Fix coder parsing for any non-standard composite coder types

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/coders.go

The original NullableCoder implementation incorrectly assumed its component coder was always length-prefixed (LP'd).
In scenarios like a test [`testFlattenMultipleCoders`](https://github.com/apache/beam/blob/61cf27fdef56a8c43572e20a350aa1109d17d3aa/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/FlattenTest.java#L188) using `Nullable[VarLong]`, the inner `VarLongCoder` would not be LP'd by the prism runner. This decoder mismatch caused incorrect bytes to be read for the element, leading to incorrect buffer offsets.
Notice that the PR only fixes `org.apache.beam.sdk.transforms.FlattenTest.testFlattenMultipleCoders`. The fact that the other test `org.apache.beam.sdk.transforms.FlattenTest.testFlattenWithDifferentInputAndOutputCoders2` still fails implies a separate root cause. …

Use component coder when handling nullable coder in prism.

---

sdks/python/apache_beam/runners/portability/prism_runner.py
sdks/python/apache_beam/runners/portability/prism_runner_test.py

Previously, when we have cache enabled for prism binary/zip and both binary and zip file in cache, `PrismJobServer` will still unzip the prism zip file. This leads to the error of `Text file busy` when we try to run a prism runner the second time in colab (https://github.com/apache/beam/issues/33623#issuecomment-2599237539).
This PR fixes this problem and adds an array of unit tests. 
addresses #33623
Notice that there is another problem in the original issue regarding running the prism runner multiple times results in multiple prism processes in colab. There will be a follow-up PR (#34623) for that.

Use cached prism binary without re-unzipping by default.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedSource.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/WatchForKafkaTopicPartitions.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java

Reverts apache/beam#34258
The original change breaks Kafka job submission without access to kafka clusters https://github.com/apache/beam/issues/34630

Revert "Fail Fast if Resources Do Not Exist in Kafka Cluster"

---

sdks/python/apache_beam/runners/portability/prism_runner.py
sdks/python/apache_beam/runners/portability/prism_runner_test.py

Follow-up to #34616, addressing #33623.
Introduces an experimental feature for Prism Runner to maintain only a single background Prism server instance. This is beneficial in environments like Google Colab where long-lived Python processes may trigger Prism Runner multiple times across different pipeline executions.

Add an experiment to make prism server a singleton

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/config/StreamingGlobalConfigHandle.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/StreamingWorkerStatusPages.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/WindmillConnection.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDispatcherClient.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServer.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillStreamFactory.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/ChannelCache.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/IsolationChannel.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillChannelFactory.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillChannels.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/WindmillStubFactoryFactoryImpl.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/WindmillStreamSenderTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/ChannelCacheTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/testing/FakeWindmillStubFactory.java

consume flow control settings updates from job settings, lazily create streams/channels to use new flow control settings
- propogate current flow control settings to channel creation
- consume new flow control settings in `ChannelCache`
- lazily recreate streams in `WindmillConnection`  to pick up new flow control settings
- update tests
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS. …

consume flow control settings updates from job settings

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/handlerunner.go
sdks/go/pkg/beam/runners/prism/internal/preprocess.go
sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/samza_runner_test.py
sdks/python/apache_beam/runners/portability/spark_runner_test.py

Following the idea of identity transform (https://github.com/apache/beam/issues/32930#issuecomment-2803609322) and valuable discussions with @lostluck, I have developed a **"simpler and more general fix"** for Prism runner issues involving `Flatten`. This approach works not only for `Flatten->Flatten` scenarios, but also for others like `GroupBy->Flatten`.
The key observations are:
- Prism's Runner `Flatten` only passes data through from its input PCollections.
- No subsequent step within the runner enforces the correct output coder for this Runner `Flatten` output.
Previous approaches (including #34602) attempted to fix this by by overwriting the *upstream* coders with the `Flatten` output coder. This works in many scenarios, especially when the upstream transform is a SDK-side transform …

Inject SDK-side flattens while handling input/output coder mismatch in flattens.

---

sdks/python/apache_beam/ml/anomaly/transforms.py

Improve the performance of offline detectors by putting the original example in the key and removing unnecessary `CoGroupByKey` step.

Get rid of unnecessary cogbk when running offline detector.

---

sdks/python/apache_beam/io/gcp/bigquery.py

The current `ReadFromBigQuery` and `_CustomBigQuerySource` doesn't properly propagate the `validate` argument when it reads data with `EXPORT` mode.
This PR makes it pass the argument properly so that users can configure it as they want. …

Make validation for BQ export source configurable

---

sdks/python/apache_beam/runners/portability/samza_runner_test.py
sdks/python/apache_beam/runners/portability/spark_runner_test.py

fixes #30645
fixes #30657
Tracking issue: #34647

Ignore test_flatten_and_gbk for spark and samza runners.

---

website/www/site/content/en/documentation/sdks/yaml-providers.md

addresses #34308 
Replace Polber link with [beam-starter-java-provider](https://github.com/apache/beam-starter-java-provider) link …

Update link in yaml-providers.md

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCheckpointMark.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java

KafkaCheckpointMark previously did not have the reader available which was required for offset deduplication.
This changes to always provide the reader for committing offsets and offset deduplication. …

Provide kafka unbounded reader to checkpoint mark when offset based deduplication is supported.

---

website/www/site/content/en/documentation/sdks/yaml-testing.md

I was just checking to see if they had published and noticed a couple of improvements.  …

Minor fixes to yaml testing docs.

---

sdks/python/apache_beam/ml/anomaly/detectors/offline.py
sdks/python/apache_beam/ml/anomaly/transforms.py
sdks/python/apache_beam/ml/anomaly/transforms_test.py

Previously, `OfflineDetector` assumed that user-provided model handlers would output floating-point score values. This assumption often doesn't hold, particularly for third-party anomaly detection models (like [PyOD's](https://github.com/yzhao062/pyod/blob/d5954868b540d99b922ba07a0885f98e4b09b04d/pyod/models/base.py#L140)) that output labels instead of scores.
This PR addresses this by making the output type generic (using a type variable). It also introduces common adapters to convert `RunInference` predictions into the `AnomalyPrediction` format. This approach improves ease-of-use for common scenarios while preserving flexibility for future extensions.

Add adapters to address output conversion for OfflineDetector.

---

sdks/python/apache_beam/yaml/yaml_mapping.py
sdks/python/apache_beam/yaml/yaml_mapping_test.py

Properly propagate schemas of Beam YAML Partition transform.

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java

tl;dr just adding some missing logic to support converting BQ timestamp type --> Java logical timestamp type --> Python timestamp type
We have some existing Schema translation between Python and Java SDKs for Timestamps. A Python Timestamp [maps](https://github.com/apache/beam/blob/73739725633f76e1a960e61171e498df1be9012f/sdks/python/apache_beam/typehints/schemas.py#L36) to a Java MicrosInstant (aka [SqlTypes.TIMESTAMP](https://github.com/apache/beam/blob/73739725633f76e1a960e61171e498df1be9012f/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/SqlTypes.java#L42))
Writing timestamps to BQ Storage Write API with the Python SDK works fine, but when a row fails and we try converting the BQ type back to a MicrosInstant, we get the following error:
``` …
```

[BigQueryIO] support MicrosInstant type (for xlang)

---

sdks/python/apache_beam/yaml/tests/explode.yaml
sdks/python/apache_beam/yaml/tests/filter.yaml
sdks/python/apache_beam/yaml/tests/flatten.yaml
sdks/python/apache_beam/yaml/tests/partition.yaml
sdks/python/apache_beam/yaml/tests/pytransform.yaml
sdks/python/apache_beam/yaml/yaml_mapping.py

Add core and missing transformers for yaml integration testing - phase 2sh

---

.github/workflows/beam_PreCommit_Yaml_Xlang_Direct.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/python/apache_beam/yaml/tests/assign_timestamps.yaml
sdks/python/apache_beam/yaml/tests/create.yaml
sdks/python/apache_beam/yaml/tests/extract_windowing_Info.yaml
sdks/python/apache_beam/yaml/tests/ml_transform.yaml
sdks/python/apache_beam/yaml/tests/validate_with_schema.yaml

Phase 1 of this document - https://s.apache.org/beam-yaml-it 
https://github.com/apache/beam/issues/34611
[![Build …

Phase 1sh - more yaml integration tests

---

sdks/python/apache_beam/runners/portability/prism_runner.py
sdks/python/apache_beam/runners/portability/prism_runner_test.py

Add a md5sum check before overwriting a cached file.
Additionally, we add support for using GCS path as prism location.
Particularly, to set the prism location for running a pipeline, we can use `--prism_location`. The following scenarios are now supported:
- `--prism_location=/path/to/bin_or_zip`
- `--prism_location=https://github.com/apache/beam/releases/download/...`
- `--prism_location=https://github.com/apache/beam/releases/tag/...`
- `--prism_location=gs://bucket/path/to/bin_or_zip`    <- newly supported case

Add a md5sum check before overwriting a cached prism file

---

sdks/java/io/iceberg/build.gradle
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/BigQueryMetastoreCatalogIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/HiveCatalogIT.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/IcebergCatalogBaseIT.java

Fixes: [#31931](https://github.com/apache/beam/issues/31931)
Successul run example: https://github.com/akashorabek/beam/actions/runs/14610522701 …

Fix Iceberg Integration tests

---

sdks/python/apache_beam/ml/inference/base.py
sdks/python/apache_beam/ml/inference/base_test.py
sdks/python/apache_beam/ml/inference/huggingface_inference.py
sdks/python/apache_beam/ml/inference/huggingface_inference_test.py
sdks/python/apache_beam/ml/inference/onnx_inference.py
sdks/python/apache_beam/ml/inference/pytorch_inference.py
sdks/python/apache_beam/ml/inference/sklearn_inference.py
sdks/python/apache_beam/ml/inference/sklearn_inference_test.py
sdks/python/apache_beam/ml/inference/tensorflow_inference.py
sdks/python/apache_beam/ml/inference/tensorflow_inference_test.py
sdks/python/apache_beam/ml/inference/tensorrt_inference.py
sdks/python/apache_beam/ml/inference/utils.py
sdks/python/apache_beam/ml/inference/vllm_inference.py
sdks/python/apache_beam/ml/inference/xgboost_inference.py
sdks/python/apache_beam/ml/inference/xgboost_inference_test.py

Updates RunInference model handlers to PEP 585 standards, migrating away from the `typing` module as appropriate. 
Part of #32969
--------------------------------------------------------------------------------------- …

Update RunInference type hints to PEP 585 standards

---

sdks/python/apache_beam/io/gcp/gcsio_retry_test.py

Temporarily silent the noise from `TestGCSIORetry.test_retry_on_throttling`.
Revert this once issue https://github.com/apache/beam/issues/34736 is fixed.

Skip this failed test until further investigation is done.

---

contributor-docs/code-change-guide.md

Update contributor doc reflecting #33954

---

.github/REVIEWERS.yml

To help streamline review assignments and focus my efforts, I'll be opting out of Java reviews and dedicating more of my review capacity to Python and Go going forward.

Remove myself from java reviewers and focus on python and go.

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/runners/interactive/interactive_beam_test.py

Users typically expect the pipeline options they provide to remain unchanged after running a pipeline. Therefore, we make a deep copy of the provided options to prevent any accidental modification or "overwrite" during pipeline preparation and execution.
fixes #34722

Deep copy PipelineOptions and keep the input intact.

---

sdks/python/apache_beam/internal/cloudpickle_pickler.py
sdks/python/apache_beam/internal/cloudpickle_pickler_test.py
sdks/python/apache_beam/internal/dill_pickler.py
sdks/python/apache_beam/internal/pickler.py
sdks/python/apache_beam/internal/pickler_test.py
sdks/python/apache_beam/internal/set_pickler.py
sdks/python/apache_beam/internal/set_pickler_test.py
sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/runners/pipeline_context.py
sdks/python/apache_beam/transforms/ptransform.py

The motivation for this change is Flume caches pickled code and non-determinism breaks the caching. While making pickling fully-determinism is infeasible, increasing the determinism is still useful due to the increase in cache hits. Sets are a common source of non-determinism. This change sorts set elements to provide deterministic serialization. Because not all types provide a comparison operator, the sorting routine implements generic element comparison logic.
See: #34410

Add option to pickler dumps() for best-effort determinism

---

.github/workflows/beam_PreCommit_Java_Debezium_IO_Direct.yml
CHANGES.md

This is step 1 for issue #34747 to get to a newer Debezium IO version in Beam, as Debezium requires Java 17 or later with version 3.0 (or later). I tested the local build with gradle and Java 17 before making this change for the build system. 
GitHub Actions …

Use Java 17 for Debezium IO #34747

---

CHANGES.md
sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py

Add reshuffle before triggering load jobs.

---

CHANGES.md
sdks/python/apache_beam/typehints/native_type_compatibility.py
sdks/python/apache_beam/typehints/native_type_compatibility_test.py

`TypedDict` is not a type, but a constructor of `dict` that supplies type hints to static type checkers about the keys. As a result, `TypedDict`s are not compatible with Mapping or Dict, giving errors like this:
```
apache_beam.typehints.decorators.TypeCheckError: Input type hint violation at MyPipelineStage: expected Mapping[<class 'str'>, Any], got <class 'google3.my_pipeline.MyCoolTypedDict'>
```
This implementation could be improved. For one thing, something which is typed as accepting a `TypedDict` will happily accept a `dict[str, Any]`, which is not as strict as it could be. For another, we could be more specific about the key type (e.g. a union of all types found in the `TypedDict`). However, I think this is a distinct improvement on the current state and will unbreak some of our …

Improve the apache beam type system to handle TypedDict.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutor.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutorTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/failures/WorkFailureProcessorTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefresherTest.java

The change can be activated by passing `--experiments=windmill_bounded_queue_executor_use_fair_monitor`

[Dataflow Streaming] BoundedQueueExecutor: Add an experiment to use fair monitor

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOReadImplementationCompatibility.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedSource.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/WatchForKafkaTopicPartitions.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java
sdks/java/io/kafka/upgrade/src/test/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslationTest.java

This PR is a fix and reintroduction of https://github.com/apache/beam/pull/34258.
ORIGINAL DESCRIPTION: If a specified topic or partition do not exist in a kafka cluster, the pipeline should fail before submission. There are some caveats to this, such as whether or not the cluster is reachable, so we only fail in the case where the cluster is reachable but the specified partitions or topics are not present.
This PR also adds a new change to address https://github.com/apache/beam/issues/34630 which details an error if the local machine cannot connect to the cluster during verification steps. The error is no longer thrown and a new test case has been added to verify this issue no longer happens. …

Fail Fast if Resources Do Not Exist in Kafka Cluster.

---

sdks/python/apache_beam/io/gcp/bigquery_file_loads.py

…ble (#34807)
* Add name to bq lambda.
* Add comment.
--------- …

Add name to BQ File Loads lambda to ensure changes are update compat

---

.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Flink.json
.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Samza.json
.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Spark.json
sdks/go/pkg/beam/runners/prism/internal/coders.go
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/samza_runner_test.py

Prism windowed value coder

---

.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Flink.json
.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Samza.json
.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Spark.json
sdks/go/pkg/beam/runners/prism/internal/coders.go
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/samza_runner_test.py

Cherrypick #34830 into release 2.65
* Support windowed value coder in prism.
* Add a new test case that previously failed to run in prism.
* Fix lints and trigger some validatesrunner tests.
* Disable the newly added test for samza runner.

Cherrypick - Prism windowed value coder (#34830)

---

sdks/java/build-tools/src/main/resources/beam/checkstyle/checkstyle.xml
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/BeamFnDataReadRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/BeamFnDataWriteRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/CombineRunners.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FlattenRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/MapFnRunners.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/PTransformRunnerFactory.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/AssignWindowsRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/BeamFnDataReadRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/BeamFnDataWriteRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/CombineRunnersTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FlattenRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FnApiDoFnRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/MapFnRunnersTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/PTransformRunnerFactoryTestContext.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java

I am attempting to make it easier to comprehend and improve the Java SDK harness. This is a small initial step.
- `PTransformRunnerFactory` did not use its type parameter and abused rawtypes significantly, so the type parameter was silly.
- The return value was just barely used. It is clearer to just match the existing design of `addBlahBlah` in the one place it was used and eliminate all the extraneous returns. (I don't like the design of "pass a mutate-anything-you-want context to a visitor" pattern but at least it is consistent)
- The `create` method was actually _not_ just creating things, but attaching them and registering them. Now I just renamed.
Eventually, `FnApiDoFnRunner` is basically 4 or 5 different runners with different types that abuse typing and every method has a …

Improve clarity of PTransformRunnerFactory in Java SDK harness

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java

Regex for parsing array types did not take into account sized primitive types, eg ARRAY<STRING(MAX)>
Fixes #34863
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java …

fix: correct spanner column schema type parser

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
.github/trigger_files/IO_Iceberg_Integration_Tests_Dataflow.json
sdks/java/core/src/main/java/org/apache/beam/sdk/util/RowFilter.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/CreateReadTasksDoFn.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergCdcReadSchemaTransformProvider.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergIO.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergReadSchemaTransformProvider.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergScanConfig.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IncrementalScanSource.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ReadFromTasks.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ReadUtils.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanSource.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskReader.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskSource.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOReadTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/ReadUtilsTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/IcebergCatalogBaseIT.java
website/www/site/content/en/documentation/io/managed-io.md

Part of #34789 
Allows users to pass a list of field names to either keep or drop when reading from an Iceberg table.
For example, say we have a table with columns `colA`, `colB`, `colC`, `colD`, `colE`. Either of the following will produce the same output:
- `keep: ["colA", "colE"]`
- `drop: ["colB", "colC", "colD"]`
`keep` and `drop` are mutually exclusive and an error will be thrown if both are specified

[IcebergIO] Support column pruning

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateFetchingIterators.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java

Avoids all the bookeeping logic of creating and caching blocks of elements, which in addition to reducing total work and simplifying the codepaths allows decoded elements to be ephemerally decoded and consumed one at a time rather than storing them in large lists even when actual caching is disabled which should play much better with the garbage collector.
Note that this disables caching of the tail of GBK iterables, which will result in more side input reads and possible performance degradation for those GBKs whose value iterables are too large to fit over the Data API but small enough to be substantially cached *and* are re-iterated. IMHO this is a reasonable tradeoff as (1) large values like this are the antithesis of what one wants to place in the cache (which can result in evicting …

Streamline non-cached state backed iterable.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/agent/build.gradle

An optional `requireJavaVersion` parameter is added to `JavaNatureConfiguration` 
Generalize what we have done for sdks/java/container/agent, prerequisite for #34747 …

Enable certain Beam module compile with newer Java version

---

sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

Addresses https://github.com/apache/beam/issues/34792
Note: **This wont fix the slowness when checking 50K GCD files exist. But this optimizes the speed slightly.** …

use blob.exists to check the GCS file

---

sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/coders/AvroCoder.java
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/coders/AvroGenericCoder.java
sdks/java/extensions/avro/src/test/java/org/apache/beam/sdk/extensions/avro/coders/AvroCoderTest.java

This addresses issue https://github.com/apache/beam/issues/34749.
Results on heap allocation:
**AvroDatumFactory**
before: 32%
after: 0.036%
**AvroCoder**
before: 69%
after: 11%
As we thought, this improves not only user code, but also sdk performance.
Example taken from another pipeline:
**org.apache.beam.runners.dataflow.worker.StreamingModeExecutionContext.flushState()**
before: 43%
after: 10%
**Before**
**After**
See also PR https://github.com/apache/beam/pull/34750 for more details

34749 added cache for avro coder to reduce memory footprint

---

sdks/python/apache_beam/ml/anomaly/transforms.py
sdks/python/apache_beam/ml/anomaly/transforms_test.py

- Add tests for unkeyed input.
- Optimize the case when running one non-ensemble detector (using empty string instead of computing uuid).

[AnomalyDetection] Support unkeyed input for the transform.

---

CHANGES.md
sdks/python/apache_beam/runners/direct/direct_runner.py

Right now, when switching between direct runner implementations, Prism checks `pr.state.is_terminal()` and if it throws it will fallback to a different runner implementation. This means that Prism is never auto-enabled. This fixes that problem.
Part of #34549 - I initially targeted the whole thing in https://github.com/apache/beam/pull/34612, but that is proving difficult and needs to be chunked up somehow. …

Correctly auto-enable prism for some pipelines

---

.github/trigger_files/beam_PostCommit_Python_Dependency.json
sdks/python/apache_beam/ml/transforms/embeddings/huggingface.py

addresses: [#30799](https://github.com/apache/beam/issues/30799)
Successful run example: https://github.com/akashorabek/beam/actions/runs/15021539713
Changed the default URL for the HF Inference API since the old one recently started responding server errors …

Change HF inference default api url

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataAdminDao.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dofn/InitializeDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/mapper/PartitionMetadataMapper.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/InitialPartition.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/PartitionMetadata.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/PartitionMetadataTest.java

The ParentToken column is used for single-split based change stream partitions. If multi-split based change stream is supported, then the column will be null.
To support multi-split based change stream, the metadata table of the connector should keep the ParentToken column nullable. So that for single-split based change streams, the ParentToken column has value, whereas for multi-split based change streams, the column is null.

[BEAM-12164]: Make the spanner change stream connector metadata table ParentTokens column nullable.

---

CHANGES.md
sdks/python/apache_beam/options/pipeline_options.py

Today, you can abbreviate arguments in Beam. This is generally convenient since you can do things like specify `--r` instead of `--runner`, and Beam will infer your intent.
Unfortunately, it also has unintended side effects. For example, specifying `--u` will impact not just `--update`, but also `--update_compatibility_version` (caused bug fixed by https://github.com/apache/beam/pull/34083), and specifying `--output` like we do in most examples will impact [`--output_executable_path`](https://github.com/apache/beam/blob/f6d209ff6a3ea638f11dfb96e52f7c21292dfbc1/sdks/python/apache_beam/options/pipeline_options.py#L1693) as well (notably, this cannot be fixed in an easy way like `update_compatibility_version` since both `output` and `output_executable_path` might be expecting strings). There …

Disable argument abbreviation in Python

---

runners/spark/src/test/java/org/apache/beam/runners/spark/translation/streaming/StreamingTransformTranslatorTest.java

fixes #34945 
ignore some spark runner flaky test
[![Build …

[Spark Runner] ignore flaky test `testStreamingSideInputAsIterableView`

---

.github/workflows/beam_PostCommit_Java_Examples_Dataflow_V2.yml
build.gradle.kts

Looks to me like this CI job should run `:runners:google-cloud-dataflow-java:examplesJavaRunnerV2IntegrationTestDistroless` instead of `:runners:google-cloud-dataflow-java:examplesJavaDistrolessRunnerV2PreCommit`. …

Fix gradle target for Java Examples on Dataflow Runner V2

---

runners/spark/3/build.gradle
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/streaming/StreamingTransformTranslatorTest.java

Fix flaky test
Bump to latest patch version for each versions.
Another reason [test](https://github.com/apache/beam/actions/workflows/beam_PreCommit_Java_Spark3_Versions.yml) being flaky is that the compatiblility test suites run on 11 different versions. Then a 5% flaky test becomes 40% flaky. Change to exercises on each minor version …

Fix Flaky PreCommit Spark runner Java version test

---

.github/workflows/beam_PreCommit_Java_Spark3_Versions.yml
runners/spark/3/build.gradle

Fix #32207
Beam already moved to slf4j 2. Tested locally `./gradlew :runners:spark:3:sparkVersionsTest` now passed on Java11.
This should also fix the test on master branch …

Use default CI Java for Spark3 Java Version PreCommit

---

model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto
model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto

as part of https://s.apache.org/beam-element-extended-metadata we want to add ElementMetadata that will hold in the future additional metadata fields e.g. drainMode, element kind or tracing metadata. …

Update beam_runner_api.proto with element metadata

---

.github/workflows/update_python_dependencies.yml

The automatic run after 2.65.0 release https://github.com/apache/beam/actions/runs/14950558614 failed. This allows committer to trigger the workflow manually …

Always trigger update Python dependency on manual run

---

sdks/python/apache_beam/runners/portability/stager.py
sdks/python/apache_beam/runners/portability/stager_test.py

Resolves a part of #32380 
- Adding support for pyproject.toml file.
- Added test case for setup.py file build case. …

Adding support for pyproject.toml file (resolves a part of #32380)

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/extensions/schemaio-expansion-service/build.gradle
sdks/java/extensions/sql/expansion-service/build.gradle
sdks/java/io/expansion-service/build.gradle
sdks/java/io/google-cloud-platform/expansion-service/build.gradle

fixes https://github.com/apache/beam/issues/34968 with the workaround only for expansion service. …

force avro 1.11.4 for the expansion service

---

CHANGES.md
sdks/java/io/cassandra/src/main/java/org/apache/beam/sdk/io/cassandra/ReadFn.java

Addresses #34160
There are 2 high level approaches discussed in #34160:
1. Rethrow
2. Let the user plug in an exception handler.
While a default Rethrow might change the behavior from silently logging errors and proceeding, not doing so has issues of data correctness  as rows that get any errors are never read and the pipeline still succeeds. …

Rethrowing Exception from CassandraIO's ReadFn

---

sdks/python/pyproject.toml
sdks/python/setup.py

Sets a specific dependency boundary for `grpcio` and `grpcio-tools` for future Python 3.13 support. Leaves the bounds for current python versions as-is due to the unknown status of https://github.com/grpc/grpc/issues/37710
Part of #34869 …

Update GRPC dependencies for Python 3.13

---

sdks/python/apache_beam/pipeline.py

Correcting the pipeline object definition

---

sdks/python/apache_beam/yaml/examples/testing/examples_test.py

https://github.com/apache/beam/issues/35030 Phase 1 …

add doc string to examples test file

---

sdks/python/apache_beam/yaml/integration_tests.py
sdks/python/apache_beam/yaml/tests/kafka.yaml
sdks/python/apache_beam/yaml/tests/oracle.yaml
sdks/python/apache_beam/yaml/tests/pubsub.yaml
sdks/python/apache_beam/yaml/tests/runinference.yaml
sdks/python/apache_beam/yaml/yaml_ml.py
sdks/python/setup.py

Phase 3 of this document - https://s.apache.org/beam-yaml-it
https://github.com/apache/beam/issues/34611
[![Build …

Yaml IT - Phase 3b

---

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/stage.go

Fixes #35090.
Running the same test code from https://github.com/apache/beam/issues/35090#issue-3102012585, we no longer see timer callback being invoked.
Furthermore, if we change the test code to set firing timestamp of a timer to be the timestamp of first element + 2 (rather than 10 in the original test), we will see the timer callback is actually called.
```
set timer to Timestamp(1748577640.693000)
timer callback start (timestamp=Timestamp(1748577640.693000))
timer callback elements: [1748577638.693265, 1748577639.693265, 1748577640.693265]
timer callback end
batch process start
1748577638.693265
1748577639.693265
1748577640.693265
1748577641.693265
1748577642.693265
batch process end
clear timer
set timer to Timestamp(1748577645.693000)
timer callback start …
```

Prism: Fix event-time timer firing earlier than the time set.

---

sdks/python/apache_beam/yaml/generate_yaml_docs.py

Addresses #34772 by adding code changes to consider user provided providers if they are provided via command-line arguments.
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?event=schedu …

Fix for issue 34772 to include user provided providers

---

website/www/site/content/en/documentation/pipelines/test-your-pipeline.md

Fixes #18391
Tested locally and passed. …

update test your pipeline with TestPipeline and Rule

---

website/www/site/content/en/documentation/sdks/yaml.md

#34783
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml …

add extra_transforms block documentation to chain transform documentation

---

.github/workflows/beam_PostCommit_Go_VR_Samza.yml
runners/google-cloud-dataflow-java/build.gradle

Fix PostCommit Dataflow v2 Nexmark: https://github.com/apache/beam/actions/runs/15426788090/job/43415616858 
Fix Go VR Samza: https://github.com/apache/beam/actions/runs/15427335623 …

Fix tests affected by Java 8 container turn down

---

sdks/python/gen_protos.py
sdks/python/pyproject.toml
sdks/python/setup.py

Migrates `pkg_resources` usage in the Python SDK to `packaging` and `importlib.resources` equivalents and re-defines utility functions (`to_filename()` and `normalize_path()` which were small string utilities from `pkg_resources`.) `pkg_resources` is deprecated and these changes are the suggested migration path.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apa …

Replace usages of deprecated pkg_resources package

---

sdks/python/apache_beam/io/gcp/bigquery_test.py
sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/pipeline_test.py

Add a better error message for situation where PBegin is accidentally passed a transform that expects a pcollection
(resolves https://github.com/apache/beam/issues/34703) …

Improve error message when accidentally using PBegin/Pipeline

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/DequeCoder.java

The DequeCoder uses ArrayDeque internally, which disallows null elements. We could switch Deque implementations, but this change is better. To quote the JDK docs: "While Deque implementations are not strictly required to prohibit the insertion of null elements, they are strongly encouraged to do so. Users of any Deque implementations that do allow null elements are strongly encouraged not to take advantage of the ability to insert nulls. This is so because null is used as a special return value by various methods to indicated that the deque is empty." …

Constrain DequeCoder type correctly, as it does not support nulls

---

sdks/java/io/iceberg/build.gradle

Make SDK harness change effective on Iceberg Dataflow test

---

sdks/python/apache_beam/yaml/README.md
sdks/python/apache_beam/yaml/extended_tests/postgres.yaml

Helps prevent https://github.com/apache/beam/issues/35122 from happening again. …

[YAML]: Update postgres IT test and readme

---

examples/java/cdap/hubspot/build.gradle
examples/java/cdap/salesforce/build.gradle

IntelliJ sync gradle project see the following error:
```
Could not find avro-mapred-1.11.2-hadoop2.jar (org.apache.avro:avro-mapred:1.11.2).
Searched in the following locations:
https://repo.maven.apache.org/maven2/org/apache/avro/avro-mapred/1.11.2/avro-mapred-1.11.2-hadoop2.jar
```
On IntelliJ 2022, it prevents IntelliJ resolving all dependencies, with no hint where the problem is
On IntelliJ 2025, it still outputs error, but make it clearer the problem happens on this two subproject.
The problem is the vendored `com:avkelon` plugin depends on Beam 2.41 SparkReceiverIO, confused the dependency resolver. …

Fix IntelliJ sync project failure due to circular Beam dependency

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test_common.py
sdks/python/apache_beam/ml/anomaly/transforms.py

Add cloudpickle coder.

---

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/execute.go

Add a new experiment flag to enable real-time clock as processing time.

---

sdks/python/apache_beam/dataframe/transforms_test.py
sdks/python/apache_beam/examples/snippets/transforms/elementwise/pardo_dofn_methods.py
sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py
sdks/python/apache_beam/io/gcp/bigquery_test.py
sdks/python/apache_beam/io/gcp/bigtableio_test.py
sdks/python/apache_beam/io/gcp/experimental/spannerio_test.py
sdks/python/apache_beam/io/gcp/pubsub_test.py
sdks/python/apache_beam/ml/gcp/cloud_dlp_test.py
sdks/python/apache_beam/ml/inference/base_test.py
sdks/python/apache_beam/ml/inference/tensorflow_inference_test.py
sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/pipeline_test.py
sdks/python/apache_beam/runners/direct/direct_runner_test.py
sdks/python/apache_beam/runners/interactive/non_interactive_runner_test.py
sdks/python/apache_beam/runners/runner_test.py
sdks/python/apache_beam/transforms/trigger_test.py
sdks/python/apache_beam/typehints/typecheck_test.py
sdks/python/apache_beam/yaml/readme_test.py

As part of https://github.com/apache/beam/issues/34549 to enable Prism by default, this identifies tests which are for behaviors which either:
1) Are not testable on prism. Examples include tests which use mocks which need to be referenced in the same python process (which doesn't work since Prism is portable), tests which access attributes which are only present on the FnApiRunner, or tests which require behaviors only guaranteed by the FnApiRunner
2) Are minor behavior differences which may or may not require a fix, but should not require holding back making prism the default, and which cannot be systematically checked when [walking the pipeline](https://github.com/apache/beam/blob/df54bf439b28b23c3380b913811633fd8678c403/sdks/python/apache_beam/runners/direct/direct_runner.py#L115). …

Force FnApiRunner in cases where prism can't handle use case

---

sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/core_test.py
sdks/python/apache_beam/typehints/decorators.py
sdks/python/apache_beam/typehints/decorators_test.py
sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

The following pipeline currently throws an error:
```python
with beam.Pipeline() as pipeline:
letters = (
pipeline
| beam.Create([['abc']], reshuffle=False)
| beam.FlatMap()
| beam.Map(lambda s: s.upper()).with_input_types(str))
```
with error: (roughly)
```
TypeCheckError: The transform '[4]: Map(<lambda at <ipython-input-4-04b6d203d131>:6>)' requires PCollections of type '<class 'str'>' but was applied to a PCollection of type 'List[<class 'str'>]' (produced by the transform '[4]: FlatMap(identity)'). 
```
This can be fixed by just updating the `FlatMap` identity function to just have no type hints, which allows trivial inference to correctly determine the right pcollection types.
Before realizing that solution, I ended up fixing a few type hinting functions that strip iterables so that …

Fix incorrect typehints generated by FlatMap with default identity function

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/pipeline_test.py

This change (introduced in https://github.com/apache/beam/pull/35160) unfortunately can break some pipelines which rely on the current behavior. Specifically, I found people running into issues with pipelines which looked like:
```
class MyDofn(...):
expand(self, ...):
if self.condition:
return None
...
def construct_pipeline():
foo = p | MyDofn(...)
if foo is not None:
foo | more_transforms(...)
```
This probably should remain valid, I don't think its worth breaking existing pipelines for the correctness semantics. …

Remove breaking PDone change

---

sdks/python/apache_beam/ml/inference/vllm_inference.py

When vLLM server exits, several threads may concurrently attempt to start the server without waiting for an invocation to fully initialize. 
Fix the logic to only allow one invocation per thread at a time. …

Allow only one thread at a time to start the VLLM server.

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
CHANGES.md
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergIO.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergScanConfig.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ReadFromTasks.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskReader.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskSource.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/FilterUtilsTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOReadTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergUtilsTest.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/IcebergCatalogBaseIT.java

This includes two separate fixes, outlined below. For the sake of time, I just put them in the same PR, but I can split them into separate PRs if necessary.
1. Fix conversion logic for lists of structs and maps of structs
2. Fix output schema resolution when using column pruning
Fixes #34887
Fixes #35199

[IcebergIO] Fix conversion logic for arrays of structs and maps of structs; fix output Schema resolution with column pruning

---

sdks/python/setup.py

fix long_description when the md file cannot be found

---

website/www/site/content/en/documentation/sdks/java-dependencies.md

Fix typo: (x) beam-sdks-java-io-google-cloud-platform-bom  --> (o) beam-sdks-java-google-cloud-platform-bom
[![Build …

Fix typo java-dependencies.md

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/apache_beam/io/external/xlang_jdbcio_it_test.py
sdks/python/apache_beam/io/jdbc.py
sdks/python/apache_beam/typehints/schemas.py
sdks/python/apache_beam/yaml/main.py

fixes #35244
fixes #28151
The date type in Java is encoded with the same logic as `Timestamp` in Python. 
When we construct the schema proto of a python `date` field, it first resolves its logical type to `JdbcDateType`. From there, it finds its representation type. 
Originally, the representation type of `JdbcDateType` is `Timestamp`. Because `Timestamp` is not an atomic type, it tries to find what is the corresponding logical type of `Timestamp`. However, there are two logical types defining `Timestamp` as their language type, `MillisInstant` and `MicrosInstant`. The latter one overrides the registration of the former. Therefore, we resolve the representation type of `JdbcDataType` as `MicrosInstant`, which is a logical type that can be expanded to a representation type of a named tuple …

Fix a logical type issue about JdbcDateType and JdbcTimeType

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TFRecordIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TFRecordWriteSchemaTransformConfiguration.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TFRecordWriteSchemaTransformProvider.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextIO.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TFRecordSchemaTransformProviderTest.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/io/AvroIO.java
sdks/java/extensions/avro/src/test/java/org/apache/beam/sdk/extensions/avro/io/AvroIOTest.java
sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIO.java
sdks/java/io/json/src/main/java/org/apache/beam/sdk/io/json/JsonIO.java
sdks/standard_external_transforms.yaml

enable setting max_writer_per_bundle for avroIO and other IO

---

.test-infra/mock-apis/go.mod
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/go.mod
sdks/go/run_with_go_version.sh

Set go version 1.24.4

---

sdks/python/apache_beam/yaml/integration_tests.py

[YAML]: add more doc strings for yaml integration tests

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
.github/trigger_files/beam_PostCommit_SQL.json
CHANGES.md
sdks/java/extensions/sql/build.gradle
sdks/java/extensions/sql/src/main/codegen/config.fmpp
sdks/java/extensions/sql/src/main/codegen/includes/parserImpls.ftl
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/parser/SqlCreateExternalTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/Table.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/catalog/InMemoryCatalog.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/TableProvider.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergMetastore.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTableProvider.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlCliTest.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/PubsubToIcebergIT.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergReadWriteIT.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTableProviderTest.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java

Add create table with partitioning capabilities to Beam SQL (extension of #34966)

[IcebergIO] extend table partitioning to Beam SQL

---

it/common/src/main/java/org/apache/beam/it/common/utils/ResourceManagerUtils.java

Adds a `failOnCleanup` parameter to the `cleanResources` method in `ResourceManagerUtils`, allowing callers to specify whether an exception should be thrown when resource cleanup fails.
This provides more control over the test failure behavior, with the default set to `false` to avoid throwing exceptions on cleanup failures. …

feat: Add option to control resource cleanup failure for IT

---

buildSrc/build.gradle.kts

Reverts apache/beam#35301
Looks like this broke at least one workflow - https://github.com/apache/beam/actions/runs/15682822701/job/44181078420?pr=35289 - probably more.

Revert "Bump org.ajoberstar.grgit:grgit-gradle from 4.1.1 to 5.3.2"

---

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/execute.go

Fixes #30683
Reverts #35202
Successful run example: https://github.com/akashorabek/beam/actions/runs/15685138523 …

Fix PreCommit Java workflow

---

sdks/python/apache_beam/ml/ts/util.py
sdks/python/apache_beam/ml/ts/util_test.py

A fix following #35300.
See the explanation below (copied from the inline comments):
In `ImpulseSeqGenRestrictionProvider`, the total number of counts (i.e. `total_outputs`) is computed by `ceil((end - start) / interval)` (https://github.com/apache/beam/blob/facdc4e0e73fd938d5ca5c6ebbbe46b534e8f05a/sdks/python/apache_beam/transforms/periodicsequence.py#L45), where `end` is `start + duration` (https://github.com/apache/beam/blob/facdc4e0e73fd938d5ca5c6ebbbe46b534e8f05a/sdks/python/apache_beam/ml/ts/util.py#L172).
Due to precision error of arithmetic operations, even if `duration` is set to `len(self._data) * interval`, `(end - start) / interval` could be <ins>a little bit</ins> smaller or bigger than `len(self._data)`.
In case of being bigger, `total_outputs` would be `len(self._data) + …

Fix unstable output of periodic sequence due to precision error.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/core/build.gradle

java.library.antlr/antlr_runtime is only used in Java core
antlr is not a dependency for other Beam component than Java core. For java core, antlr is a (pre)compile only dependency and antlr_runtime is shaded and repackaged, which means antlr isn't a dependency for Java core jar either, see https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-core/2.65.0
Unpin it to unblock tests that has transient dependencies on newer antlr (DebeziumIO). This change does not affect any published artifacts
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to …

Unpin antlr in BeamModulePlugins

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java

Fixes https://github.com/apache/beam/issues/35190
The docs says STRING is one of the valid format https://beam.apache.org/releases/yamldoc/current/#readfromkafka, but we're currently not validating for the STRING format here https://github.com/apache/beam/blob/master/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformConfiguration.java#L50-L85...
To …

Allow STRING format in Kafka config

---

sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py

I recently use LogElements for debugging purpose and I find it useful if it can print out pane info (in addition to the supported timestamp and window info). 
Moreover, sometimes rfc3339 timestamp format would be harder to read and compare than timestamp in seconds. So I add a flag to switch to epoch time.
The default behavior of LogElements is not changed. All new features are controlled by optional flags.

Improve LogElements to show pane_info and timestamps in seconds.

---

sdks/python/apache_beam/runners/worker/sdk_worker.py
sdks/python/apache_beam/runners/worker/sdk_worker_test.py

When we fail an instruction, we tell the instruction cache that we've failed it, but we don't provide details. This makes it harder to raise a good exception, but exceptions can still bubble up from the instruction cache (e.g. this happens in the prism runner when a bundle fails during a split request).
This change provides the original exception context that caused the runner to fail in the first place. …

Improve exception raised from cache

---

.github/workflows/build_release_candidate.yml

Ordering was introduced into this workflow to prevent race conditions as multiple jobs write to svn. However, the wrong ordering was applied, and staging python and prism to svn are blocked on pushing java artifacts to maven instead of the job that pushes java artifacts to svn.
This currently works because publishing to maven takes much longer than the svn step, so the ordering is effectively maintained, but it means that it takes way longer for python/go artifact publishing to start, lengthening the overall job run time and making it expensive to deal with failures.
This fixes the problem …

Reduce issues induced by ordering

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

following https://commons.apache.org/proper/commons-dbcp/configuration.html,
defaultQueryTimeout: If non-null, the value of this Integer property determines the query timeout that will be used for Statements created from connections managed by the pool. null means that the driver default will be used.
This probably won't help PreparedStatement, but should be useful for some hanging query executions.  …

added defaultQueryTimeout for jdbc io

---

CHANGES.md
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/.gitignore
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/README.md
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/apache_beam_jupyterlab_sidepanel/__init__.py
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/apache_beam_jupyterlab_sidepanel/_version.py
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/package.json
sdks/python/apache_beam/runners/interactive/extensions/apache-beam-jupyterlab-sidepanel/pyproject.toml

Summary
This PR enables the `apache-beam-jupyterlab-sidepanel` JupyterLab extension to be installed via `pip` directly, without requiring the use of `jupyter labextension install`. Fixing the issue #35397 
This makes the extension fully compatible with the [JupyterLab prebuilt extension system](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions), improves ease of use, and aligns with the packaging approaches adopted by other JupyterLab 4.x-compatible projects.
Changes
- Introduced pyproject.toml based on [PEP 621](https://peps.python.org/pep-0621/) and [hatchling](https://hatch.pypa.io/latest/).
- Added hatch-jupyter-builder for handling JS asset bundling.
- Configured shared-data installation of labextension files into …

✨[Feature]: Add pip-based install support for JupyterLab side panel extension

---

.github/workflows/beam_PostCommit_Python_Dependency.yml
.github/workflows/beam_PostCommit_Python_Xlang_Gcp_Direct.yml

It seems like we periodically run into these - e.g. https://github.com/apache/beam/actions/runs/15853561529/attempts/1?pr=34612 and https://github.com/apache/beam/actions/runs/15853561539/job/44693047995?pr=34612 …

Bump workflow timeout

---

.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Samza.json
.github/trigger_files/beam_PostCommit_Python_ValidatesRunner_Spark.json
sdks/python/apache_beam/runners/portability/samza_runner_test.py
sdks/python/apache_beam/runners/portability/spark_runner_test.py

fixes #30645
fixes #30657
Successful runs:
- https://github.com/apache/beam/actions/runs/15878210817/job/44771150210?pr=35430
- https://github.com/apache/beam/actions/runs/15878210798/job/44771150231?pr=35430

Skip sliding window tests on samza and spark runner test suites

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/AsyncWatermarkCache.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/cache/NoOpWatermarkCache.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataDao.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/SpannerChangeStreamErrorTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamOrderedByTimestampAndTransactionIdIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamOrderedWithinKeyGloballyIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamOrderedWithinKeyIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamPostgresIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamTransactionBoundariesIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamsSchemaTransformIT.java

To improve the performance of the query for GetUnfinishedMinWatermark, we can add a filter to the query.
Note that the query run on a cache to refresh every 1s. We can remember the cached value every time and use the value as a filter in the next time query.
Also add class level timeout for all change stream integration tests.
Note that, the CacheLoader's refresh function cannot return null, because that will be deemed invalid, then the cache will not be updated. As the result, the connector will run forever. Hence we still keep the return type optional.

Add filter to GetMinUnfinishedWatermark queryAdd filter tester

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/transforms/display.py
sdks/python/apache_beam/transforms/display_test.py

This adds a `display_data` attribute to `AppliedPTransforms`, similar to `annotations` and `resource_hints`. This gives us a little more flexibility with adding display data, e.g. if someone wants to create a `PipelineVisitor` that adds general display data for every ptransform (like a link to github pointing to the source) …

Add display_data to AppliedPTransforms

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/MemoryMonitorTest.java
sdks/java/container/boot.go
sdks/java/core/src/main/java/org/apache/beam/sdk/options/MemoryMonitorOptions.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/status/MemoryMonitor.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/status/MemoryMonitorTest.java

This configures the boot script to use JVM flags so that it dumps heaps to a directory that the MemoryMonitor will look in.
Other improvements are made to:
- allow configuring remote upload location separately from tempLocation 
- add default-on support to gzip uploads to speed them up
These changes were tested with a manual dataflow test with a pipeline that leaked memory.
I confirmed that files were successfully dumped by the JVM and then uploaded.  Unzipping and loading the hprof files in VisualVM was successful in identifying the objects pinning memory and leading to OOMs. …

[Java Harness] Improve heap dump support by configuring JVM to dump heap on OOM exceptions

---

runners/google-cloud-dataflow-java/worker/build.gradle
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowExecutionStateRegistry.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/KeyTokenInvalidException.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/logging/DataflowWorkerLoggingMDC.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/getdata/ApplianceGetDataClient.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/ChannelzServlet.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GetWorkResponseChunkAssembler.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/ChannelCache.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/state/WindmillMapViaMultimap.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/failures/WorkFailureProcessor.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefresher.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/FixedStreamHeartbeatSender.java

Remove the broad suppression and fix up errors that are now surfaced.
Fixes #30183
```
/runner/_work/beam/beam/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/getdata/ApplianceGetDataClient.java:140: error: [dereference.of.nullable] dereference of possibly-null reference pendingResponses.get(WindmillComputationKey.create(computationResponse.getComputationId(), keyResponse.getKey(), keyResponse.getShardingKey()))
.get(
^
> Task :runners:google-cloud-dataflow-java:worker:compileJava
/runner/_work/beam/beam/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GetWorkResponseChunkAssembler.java:121: error: [argument] incompatible argument for parameter …
```

Fix broad suppression of dataflow worker windmill package.

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/apache_beam/internal/cloudpickle/cloudpickle.py
sdks/python/apache_beam/internal/cloudpickle_pickler.py

Add the ability to override the default behavior of Cloudpickle by passing a CloudPickleConfig to cloudpickle.dumps.
The goal is to maintain default behavior, but add flexibility when different behavior is desired for example foregoing isinstance semantics for deterministic pickling of dynamic types.
This was copied from my cloudpickle fork https://github.com/claudevdm/cloudpickle/tree/cloudpickle-configurable, where I added unit test coverage for a bunch of different configurations and modified tests where appropriate.
I ran internal presubmit and tap for these changes and no issues found.
This is a prerequisite to relaxing dill pickler strict dependency https://github.com/apache/beam/issues/21298. …

Cloudpickle configurable

---

sdks/java/container/license_scripts/dep_urls_java.yaml
sdks/java/core/build.gradle
sdks/java/core/src/test/java/org/apache/beam/sdk/fn/JvmInitializersTest.java

The junit-dep dependency seems to be causing build issues lately. The system-rules dependency imports junit-dep instead of junit. As far as I could tell it's the only dependency that imports junit-dep and junit is preferred over junit-dep as a dependency. The system-rules dependency hasn't been updated since 2018 and its functionality can be replaced with relative ease. …

Drop junit-dep dependency by removing system-rules usage

---

sdks/python/apache_beam/yaml/tests/create.yaml
sdks/python/apache_beam/yaml/yaml_provider.py

fixed https://github.com/apache/beam/issues/35434 …

fixed the beam yaml create issue by creating the full dict

---

sdks/python/apache_beam/transforms/periodicsequence.py
sdks/python/apache_beam/transforms/periodicsequence_test.py

A follow-up on #35412.
I've identified a flaky test in the test_fuzzy_interval for periodic impulse, which you can see in this [failed test run](https://github.com/apache/beam/actions/runs/15930463705/job/44938138857). The test fails intermittently because the periodic impulse output is either missing an element or has an extra one.
I can reproduce this failure about once every 50-100 runs. The failure rate increases significantly if the interval is set to 1 microsecond.
Here's a comparison of a normal and a failed run after I added some debugging logs:
- Normal run:
```
WARNING:root:random seed=1751056034036
start=1751056297.165744 data_duration=7.9e-05 interval=1e-06, end=1751056297.165824
input: 1751056297165744, 1751056297165824, 1
WARNING:root:outputs=80.000000, …
```

Fix flakiness in fuzzy tests and support TimestampTypes in PeriodicImpulse. 

---

sdks/python/apache_beam/utils/windowed_value.py

Today, if you compare `IntervalWindow(MIN_TIMESTAMP, MAX_TIMESTAMP)` and `IntervalWindow(MIN_TIMESTAMP - 10, MAX_TIMESTAMP + 10)`, they are not considered equal, but functionally they are actually equivalent. This is particularly problematic since some portable runners will automatically truncate `IntervalWindow(MIN_TIMESTAMP - 10, MAX_TIMESTAMP + 10)` to `IntervalWindow(MIN_TIMESTAMP, MAX_TIMESTAMP)`. We can play well with this change by considering these windows to be equal.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md …

Consider windows with bands outside of [Min, Max] equivalent

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowBatchWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/config/StreamingEngineComputationConfigFetcher.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/AbstractWindmillStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServer.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/BackOff.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/BackOffUtils.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/RateLimitPolicyFactory.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/ShardListingUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/V1TestUtil.java
sdks/java/io/influxdb/src/test/java/org/apache/beam/sdk/io/influxdb/InfluxDbIOIT.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java
sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Repeater.java
sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOTest.java

Update some now unnecessary call-site handling. …

Remove unused IOException from Backoff and BackoffUtils.

---

sdks/python/apache_beam/io/avroio.py
sdks/python/apache_beam/io/avroio_test.py

Fix TypeError in avro_union_type_to_beam_type with complex union types
Fixes: #35462
The `avro_union_type_to_beam_type` function fails with `TypeError: unhashable type: 'dict'` when processing union types containing complex Avro types (like records) with null.
The function attempts to check `if avro_type in AVRO_PRIMITIVES_TO_BEAM_PRIMITIVES` without verifying that `avro_type` is hashable. When `avro_type` is a record (dict), this causes a TypeError since dicts cannot be used as dictionary keys.
Added `isinstance(avro_type, str)` check before the dictionary lookup to ensure only string primitive types are checked against `AVRO_PRIMITIVES_TO_BEAM_PRIMITIVES`. Complex types now correctly fall through to return `Any` type. …

Fix TypeError in avro_union_type_to_beam_type with complex union types

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/ChangeStreamResultSet.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/mapper/ChangeStreamRecordMapper.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/model/DataChangeRecord.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/mapper/ChangeStreamRecordMapperTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/util/TestProtoMapper.java

No implementation change.
Only changes:
1. remove pined proto version
2. update the ChangeStreamrecordMapper comments.
Reverts [#35469](https://github.com/apache/beam/pull/35469)
[#35480](https://github.com/apache/beam/pull/35480) should solve the dependency issue in the original reverted PR [#35408](https://github.com/apache/beam/pull/35408)

Revert "Revert "Parse v2 record. (#35408)" (#35469)"

---

.github/workflows/beam_PostCommit_Python.yml
sdks/java/io/debezium/build.gradle
sdks/java/io/debezium/expansion-service/build.gradle
sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/DebeziumReadSchemaTransformProvider.java
sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/DebeziumTransformRegistrar.java
sdks/python/apache_beam/io/debezium.py
sdks/python/apache_beam/io/external/xlang_debeziumio_it_test.py

Fix Debezium xlang

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/BeamSqlPipelineOptions.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/JdbcDriver.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/impl/JdbcDriverTest.java

Fixes https://github.com/apache/beam/issues/35457 …

Support BigQuery dialect in Beam SQL

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/AbstractWindmillStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/AppendableInputStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcCommitWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStreamRequests.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkerMetadataStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/observers/StreamObserverFactory.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorkerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/AbstractWindmillStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/WindmillStreamPoolTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/FakeWindmillGrpcService.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcCommitWorkStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStreamRequestsTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkerMetadataStreamTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java

Currently this should be equivalent behavior but the separate physical stream handlers will allow for multiple distinct physical substreams when we want to cleanly terminate streams to avoid deadlines.
Add additional tests for the reconnection on stream errors (which already occurs). These could be committed separately if desired.
While at it change the deadline used for get data parsing timeout to be consistent with the deadline used for the response observers.  Currently this won't change much but as we use a longer deadline for direct streams and update that in the future we will avoid these spurious errors. …

[Dataflow Streaming] Modify AbstractWindmillStream to separate logical stream from physical streams.

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/commits/StreamingEngineWorkCommitterTest.java

Fix flake in StreamingEngineWorkCommitterTest by waiting for responses

---

sdks/python/apache_beam/runners/portability/prism_runner.py

The improvements from this PR are listed below.
- Broke long functions into smaller and manageable ones.
- Added comments
- Fixed typos
- Added some handling for release candidates.
The code change does not break any existing tests (at the cost of keeping some public interfaces).
---
The core part of this class is to determine what version of prism to use, how to find it and prepare it to run. 
For future reference, the general logic is as follows:
1. Determine what version:
- version override (e.g. `--prism_beam_version_override=v2.66.0`)
- default (no override): use beam version
- location override (e.g. `--prism_location=/tmp/bin/prism`)
- default (no override):
- for release version: get the release version of prism
- for dev version: install local change or the latest tag
- other …

Refactor PrismJobServer python class

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/IntegrationTestEnv.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/it/SpannerChangeStreamPlacementTableIT.java

Add an integration test for the connector against a placement table.
Also change the IntegrationTestEnv to be able to:
1. create a placement table
2. create a change stream with MUTABLE_KEY_RANGE option
For now this integration test is against cloud-devel. In the near future we will adjust it to cloud-prod.
Note that the test is ignored for now. The only way to run it is manually. We will enable it after placement table is supported by change stream.

Proto-based connector integration test.

---

sdks/python/apache_beam/transforms/external.py
sdks/python/apache_beam/utils/transform_service_launcher.py

Support Docker Compose v2 in Python TransformServiceLauncher
From July 2023, Compose v1 (`docker-compose`) stopped receiving updates. Probably it's time to migrate to modern Compose v2 (`docker compose`).
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/be …

Support Docker Compose v2 in Python TransformServiceLauncher

---

CHANGES.md
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/parquet/ParquetTable.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/parquet/ParquetTableProviderTest.java
website/www/site/content/en/documentation/dsls/sql/extensions/create-external-table.md

This PR modifies ParquetTable to intelligently resolve the file path before passing it to ParquetIO.
It uses FileSystems.match() to check if the provided LOCATION corresponds to a directory.
If it's a directory, a wildcard (*) is appended to the path to maintain the existing behavior of reading all files within it.
If it's not a directory (i.e., it's a file or a path that doesn't exist yet), it's treated as a user-provided pattern (either a glob or a single file path) and is used as-is.
fixes #20884  …

Add glob and single file support to BeamSQL ParquetTable LOCATION

---

CHANGES.md
sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/options/pipeline_options_test.py
sdks/python/apache_beam/options/value_provider_test.py

Implement _CommaSeparatedListAction to handle comma-separated values for experiments and dataflow_service_options, matching Java SDK behavior. This allows more flexible input formats while maintaining backward compatibility.
Fixes #35563 …

feat(options): add support for comma-separated options

---

sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/JsonSchemaConversionTest.java

Test was sometimes failing because it validated using strict equality, but json schema with multiple nullable fields can result in random Beam schema field ordering:
https://github.com/apache/beam/blob/1fd8ce382d71ea5cb37281cf0b9f439ef3b87734/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/utils/JsonUtils.java#L231-L233
Fixing test by checking for equivalence, which permits fields being out of order

Fix json schema test

---

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark.json
.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Spark_Java11.json
CHANGES.md
runners/spark/src/main/java/org/apache/beam/runners/spark/stateful/SparkTimerInternals.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/AbstractInOutIterator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkInputDataProcessor.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/TranslationUtils.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/streaming/ParDoStateUpdateFn.java
runners/spark/src/main/java/org/apache/beam/runners/spark/translation/streaming/StatefulStreamingParDoEvaluator.java
runners/spark/src/main/java/org/apache/beam/runners/spark/util/TimerUtils.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/AbstractInOutIteratorTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/translation/streaming/StatefulStreamingParDoEvaluatorTest.java
runners/spark/src/test/java/org/apache/beam/runners/spark/util/TimerUtilsTest.java

fixes #33633 
The Spark Runner did not support timers due to the following technical challenges:
1. **Timer Triggering Difficulties**: `UnboundedInOutIterator` objects are periodically created and destroyed at each Spark Streaming batch interval, rendering the internal `while (true)` loop ineffective for timer management.
2. **Sparse Key Issue**: As a consequence of the above limitation, sparse keys lose their timer triggering capability once their corresponding `UnboundedInOutIterator` objects are destroyed, leaving no mechanism to fire pending timers.
---
This PR resolves the above issues to enable Processing Time Timer functionality. …

[Spark runner] Support for ProcessingTime Timer for Spark Runner

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
.github/trigger_files/IO_Iceberg_Managed_Integration_Tests_Dataflow.json
.github/trigger_files/beam_PostCommit_SQL.json
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Use bqms-1.6.1-1.0.1

---

sdks/java/core/src/main/java/org/apache/beam/sdk/fn/splittabledofn/RestrictionTrackers.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/RestrictionTracker.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/Holder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/KV.java
sdks/java/core/src/main/java/org/apache/beam/sdk/values/WindowedValue.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/HandlesSplits.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/ProgressUtils.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/SplittableSplitAndSizeRestrictionsDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/SplittableTruncateSizedRestrictionsDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/WindowedSplitResult.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/FnApiDoFnRunnerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/ProgressUtilsTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/SplittableTruncateSizedRestrictionsDoFnRunnerTest.java

This follows #34919, splis out calls to `@TruncateRestriction`. This is the first Fn API transform that deals with responding to splits so it is a bit more complex than the prior refactors that only touched `@GetSize` and `@GetInitialRestriction` and `@SplitRestriction` that do not respond to split requests.
As I understand it, this responds to split requests by delegating them downstream, as it is expected to be fused with final element+restriction processing.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-review …

Refactor: separate SplittableTruncateSizedRestrictions

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableDestination.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryWriteConfiguration.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/PortableBigQueryDestinations.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryManagedIT.java
sdks/python/apache_beam/io/external/xlang_bigqueryio_it_test.py
sdks/python/apache_beam/io/gcp/bigquery.py
website/www/site/content/en/documentation/io/managed-io.md

It resolves a part of #35329 
1.Dynamic clustering is not supported yet. It makes sense to support dynamic clustering after we support dynamic schema for Python Bigquery Storage Write API.
2.Clustering Support for Bigquery Managed IO. …

Adding clustering support for python storage write api

---

CHANGES.md
sdks/python/apache_beam/io/gcp/bigquery_file_loads.py
sdks/python/apache_beam/io/gcp/bigquery_file_loads_test.py

I was thinking first to use only datasetId+tableId, but i changed my mind, since it makes better sense to use the full reference instead. All the other details can be found in the mentioned bug filing #34247.
I added **integration tests**.
Alongside it, I modified the package and used local executor to test the endresult manually (**devtest**), and worker fine. Didn't test it on master tho, just on the release branch.
Originally I aimed for the 2.63.0 branch so it gets fixed at least there and OFC in the next release candidate. If u tell me don't bother this release I'm also fine, but I need to have a working solution ASAP, I don't really care if it's the new version (if it comes alive soon-ish) or the currently latest stable.
I had to figure out the hard way, since nobody was telling me …

[Python] Fix WriteToBigQuery transform using CopyJob does not work with WRITE_TRUNCATE write disposition (#34247)

---

.github/trigger_files/beam_PostCommit_SQL.json
CHANGES.md
sdks/java/extensions/sql/src/main/codegen/config.fmpp
sdks/java/extensions/sql/src/main/codegen/includes/parserImpls.ftl
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/parser/SqlCreateDatabase.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/parser/SqlDropDatabase.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/parser/SqlUseDatabase.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/catalog/Catalog.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/catalog/InMemoryCatalog.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergCatalog.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTableProvider.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlCliDatabaseTest.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/BeamSqlCliIcebergTest.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTableProviderTest.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergCatalogConfig.java

Addresses #35637
These changes allow the following:
- `CREATE DATABASE ( IF NOT EXISTS )? database_name`
- `USE DATABASE database_name`
- `DROP DATABASE [ IF EXISTS ] database_name [ RESTRICT | CASCADE ]`
- `RESTRICT` (default) will throw an error if the database contains a table. `CASCADE` will drop all tables within the database before dropping the database. 
For Iceberg catalogs, `CREATE` and `DROP` will create/drop real external tables in the appropriate data platform.
These implementations will help bring Beam closer to alignment with existing [Flink](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/overview/) and [Spark](https://spark.apache.org/docs/4.0.0/sql-ref-syntax.html) syntax

[Beam SQL] Support DATABASE concept in Beam SQL, with implementation for Iceberg

---

sdks/python/apache_beam/runners/portability/prism_runner.py

We shouldn't fail prism pipelines just because we can't stat a file (read) or change its permissions (own), the only permission we need is exec. …

Dont fail pipeline on failed stat

---

CHANGES.md
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

When using `JdbcIO.write().withBatchSize(N).withWriteResults()`, `withWriteResults` silently drops `withBatchSize`. This may result in user confusion when they were trying to improve JdbcIO write performance in their application by increasing batch size.
GitHub …

Allow setting BatchSize and MaxBufferingDuration in JDBCIO's WriteWithResults

---

sdks/python/scripts/run_pytest.sh

This change set allow us to pass user-defined pytest markers.
Towards #35598.
Towards #35577.
Related https://lists.apache.org/thread/d1dkpsfl5yj8p1mod4oscj1m846yo64b.
It implements @damccorm's proposed solution https://github.com/apache/beam/pull/35598#discussion_r2208337172
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUIL …

sdks/python/scripts: support pytest user markers

---

dev-support/docker/Dockerfile

Ubuntu 20.04 has reached its end of life, so container images created with `dev-support/docker` no longer seem to work.
<details><summary>Log for start-build-env.sh on master (fail)</summary>
```
shingofuruyama@shingofuruyama:~/git/beam$ ./start-build-env.sh 
Sending build context to Docker daemon  15.87kB
Step 1/28 : FROM ubuntu:20.04
---> 626a42b93d93
Step 2/28 : ARG DEBIAN_FRONTEND=noninteractive
---> Using cache
---> deee3d578557
Step 3/28 : WORKDIR /root
---> Using cache
---> 770ab9a5fad2
Step 4/28 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
---> Using cache
---> 53829ca48107
Step 5/28 : RUN echo APT::Install-Recommends "0"\; > /etc/apt/apt.conf.d/10disableextras
---> Using cache
---> fa1b85cfa64d
Step 6/28 : RUN echo …
```

Upgrade base image for dev-support docker image(Ubuntu 20.04 -> Ubuntu 24.04)

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java

cannot use Strings.isNullOrEmpty because of
```
> Compilation failed; see the compiler output below.
/Users/runner/work/beam/beam/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java:1863: error: [argument] incompatible argument for parameter firstVersion of TransformUpgrader.compareVersions.
&& TransformUpgrader.compareVersions(requestedVersionString, "2.66.0") < 0) {
^
found   : @Initialized @Nullable String
required: @Initialized @NonNull String
2 errors
```
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUT …

fix the version string checks in KafkaIO

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java
sdks/java/core/src/main/java/org/apache/beam/sdk/util/MoreFutures.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java

With 2.63 we still observed a pipeline stuck in WriteShardsIntoTempFilesFn joining with no apparent activity on the ForkJoinPool.
Thus  #29926 may still exist, perhaps just less common.  This change further simplifies the futures constructed since we don't require the list and perhaps there is some edge case on joining a future contributing the allof future within a chained apply. We don't need the returned list in this case so can delegate just to CompletableFutures.allof alone.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING …

[Java] Further simplify MoreFutures usage in case it is cause of issues with ForkJoin pool stuckness

---

.github/workflows/beam_PostCommit_Python.yml
.github/workflows/beam_PreCommit_Python_ML.yml

Given that we have support for pytest user markers (#35655), we can extend this functionality to our post/pre commit workflows targeting ML tests on the first iteration mainly for Milvus itests.
https://github.com/apache/beam/pull/35585
https://github.com/apache/beam/pull/35598 (reverted because pytest user markers wasn't allowed back then)
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STAT …

workflows: run ML tests requiring docker-in-docker environment on `ubuntu-latest`

---

.github/workflows/beam_PostCommit_Python.yml
.github/workflows/beam_PreCommit_Python_ML.yml

https://github.com/apache/beam/pull/35733#issuecomment-3134782624 …

.github: remove `ubuntu-latest` environment temporary from `beam_PreCommit_Python_ML` and `beam_PostCommit_Python` to make CI green again

---

.github/trigger_files/beam_PostCommit_Python.json
.github/workflows/beam_PostCommit_Python.yml
.github/workflows/beam_PreCommit_Python_ML.yml
sdks/python/scripts/run_pytest.sh

This change set supposed to fix failed regressions in `beam_PreCommit_Python_ML` and `beam_PostCommit_Python` as regression of this PR #35698.
https://github.com/apache/beam/pull/35698#issuecomment-3134448623 …

sdks/python/scripts: fix posargs for `run_pytest.sh`

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

The [JdbcIO.ReadAll.inferCoder](https://github.com/apache/beam/blob/v2.66.0/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java#L1229-L1231) outputs a warning log when it failed to infer a coder with `SchemaRegistry`, however it has a fallback logic to infer the coder using `CoderRegistry`.  As the log is just a noisy warning, the log level should be lowered to info.
FYI. the logging was introduced at https://github.com/apache/beam/pull/15848/commits/4819e680fd215149670a206b7061362e137cff22.
b/434936715 …

chore(JdbcIO): Lower log level for harmless SchemaCoder inference failure in JdbcIO

---

sdks/python/apache_beam/dataframe/io.py
sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py
sdks/python/apache_beam/yaml/standard_io.yaml
sdks/python/apache_beam/yaml/tests/csv.yaml

This commit introduces a feature to include the source filename alongside the data when reading from files. This is useful for data provenance and downstream processing that depends on the origin of the data.
The following changes are included:
- Rather than suing the boolean `include_filename` parameter, switch to a more flexible `filename_column` string parameter.
- This functionality is exposed in the Beam YAML API for both `ReadFromText` and `ReadFromCsv`.
- Unit tests have been added to validate the new behavior for the Python SDK, DataFrame API, and YAML interface.
Fixes https://github.com/apache/beam/issues/35773
Tested:
```
python -m pytest -v sdks/python/apache_beam/yaml/integration_tests.py::CsvTest 
python -m pytest sdks/python/apache_beam/io/textio_test.py
``` …

feat(io): Add option to include source filename in file reads

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamCalcRel.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamComplexTypeTest.java

* Fix BeamSQL CalcRel DATETIME expression
* Add nullable array test case
* fix checkstyle …

[Release-2.67] Cherry pick #35743 into release branch

---

contributor-docs/code-change-guide.md

Previously removed in #34640. But to test changes in `sdks/java/container` (e.g. boot.go and Dockerfile), one still needs to build custom SDK container …

Update code-change-guide add back build SDK container

---

.github/workflows/build_release_candidate.yml

part-1 fix for https://github.com/apache/beam/issues/35746. This new action creates the managed-io doc PR against master. To maintain consistency we raise an empty PR incase of no changes that release manager choose to close. 
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow …

Add Action to generate ManagedIO doc PR

---

CHANGES.md
sdks/python/apache_beam/io/gcp/experimental/spannerio.py
sdks/python/apache_beam/metrics/monitoring_infos.py

Fix SpannerIO TypeError due to monitoring_info
Also fix monitoring info error format string
Fix #35850
Part 1 of #35860 …

Deprecate Python native SpannerIO, with exposed bug fix

---

sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py

We received an internal report (internal bug id: 430560535) that cogbk does not honor custom coders.
Below is the code to reproduce.
```Python
"""Test Beam's use of coders for keys in CoGroupByKey."""
from apache_beam.options import pipeline_options
class _Unpicklable:
def __init__(self, value):
self.value = value
def __getstate__(self):
raise NotImplementedError()
def __setstate__(self, state):
raise NotImplementedError()
def __repr__(self):
return f"Unpicklable({self.value})"
class _UnpicklableCoder(beam.coders.Coder):
"""."""
def encode(self, value):
return str(value.value).encode()
def decode(self, encoded):
return _Unpicklable(int(encoded.decode()))
def to_type_hint(self):
return _Unpicklable
def is_deterministic(self):
return True …
```

Fix a bug in cogbk for not using registered coder.

---

.github/workflows/beam_PreCommit_Python.yml

Increase GRPC timeouts and force sequential execution for increased stability. you can see successful runs here: https://github.com/A1K28/beam/actions/workflows/beam_PreCommit_Python.yml
fixes #34739  …

increase grpc timeouts & force seq exec (#34739)

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner.py
sdks/python/apache_beam/runners/dataflow/dataflow_runner_test.py

Remove weird verification if flag was unset but experiment was set, which caused failure even if we otherwise ignore the flag by overwriting it. …

[Python] Deprecate --enable_streaming_engine flag since it is always enabled.

---

sdks/python/apache_beam/yaml/integration_tests.py
sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py310/ml_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py311/ml_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py312/ml_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/container/py39/ml_image_requirements.txt
sdks/python/setup.py

[Postrelease-2.67] Remove mysql-connector-python dependency

---

.editorconfig

Follow up to this pr: https://github.com/apache/beam/pull/35564
Adds `.editorconfig` file so that new contributors do not need to change their editor indent settings to start contributing to this project. Mainly, since this project uses 2 spaces for Python files and the default in most editors and other Python projects is 4 spaces.
Defaults to 2 spaces for all file extensions since that is what I found after looking at these various extensions:
- `.py`
- `.sh`
- `.java` / `.gradle`
- `.sql`
- `.html`
- `.xml`
- `.css`
- `.md`
- `.js`
- `.ts`
- `.json`
- `.yml` / `.yaml`
There were some inconsistencies in some of the above file extensions including `.sh`, `.html`, `.xml`, `.css`, `.js`, and `.json`.
Defaults `.go` file extensions …

adds EditorConfig to configure a consistent indent style and size for each file extension

---

.github/trigger_files/beam_PostCommit_XVR_Direct.json
.github/trigger_files/beam_PostCommit_XVR_Flink.json
.github/trigger_files/beam_PostCommit_XVR_GoUsingJava_Dataflow.json
.github/workflows/beam_PostCommit_XVR_GoUsingJava_Dataflow.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/go/test/integration/expansions.go
sdks/go/test/integration/expansions_test.go
sdks/go/test/run_validatesrunner_tests.sh

fix(integration): improve expansion service startup verification with retry logic
refactor(gradle): re-enable GoUsingJava tests after fixing underlying issues
fix(script): add docker daemon health check and auto-start in validatesrunner tests
Addresses https://github.com/apache/beam/issues/32492
I suggest we enable this workflow for now and then fix the issues from post commits. …

ci(workflow): re-enable XVR GoUsingJava Dataflow tests

---

sdks/python/apache_beam/typehints/typehints.py
sdks/python/container/ml/py310/base_image_requirements.txt
sdks/python/container/ml/py311/base_image_requirements.txt
sdks/python/container/ml/py312/base_image_requirements.txt
sdks/python/container/ml/py39/base_image_requirements.txt
sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py313/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/setup.py

Introduces Beartype into Beam Python for type checking as discussed in https://s.apache.org/beam-python-third-party-type-checking, uses the `is_subhint()` method over `is_subclass()` as a first step towards migrating more checks to Beartype. …

Introduce Beartype Dependency for Type Checking

---

sdks/python/apache_beam/yaml/integration_tests.py
sdks/python/container/ml/py310/base_image_requirements.txt
sdks/python/container/ml/py311/base_image_requirements.txt
sdks/python/container/ml/py312/base_image_requirements.txt
sdks/python/container/ml/py39/base_image_requirements.txt
sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py313/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/setup.py

checked that the dependency indeed gets removed after rerun generate requirement file
manually patched #35900 after regenerated requirements …

Remove mysql-connector-python dependency

---

sdks/go/pkg/beam/runners/prism/internal/environments.go

The PR also added some debugging logs for process and docker env.
Blocked by #35964.

[Prism] Fix segv when docker container self-terminated.

---

sdks/python/apache_beam/yaml/examples/README.md
sdks/python/apache_beam/yaml/examples/testing/examples_test.py
sdks/python/apache_beam/yaml/examples/testing/input_data.py
sdks/python/apache_beam/yaml/examples/transforms/jinja/import/README.md
sdks/python/apache_beam/yaml/examples/transforms/jinja/import/macros/wordCountMacros.yaml
sdks/python/apache_beam/yaml/examples/transforms/jinja/import/wordCountImport.yaml

#35909
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml …

[YAML]: add import jinja pipeline example

---

CHANGES.md

https://github.com/apache/beam/pull/35946 is the PR.
Tested this change with the SNAPSHOT run with Dataflow Templates: https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/17294873776/job/49090516119
Used this:
https://repository.apache.org/content/groups/snapshots/org/apache/beam/beam-sdks-java-io-mongodb/2.68.0-SNAPSHOT/beam-sdks-java-io-mongodb-2.68.0-20250828.122729-36.pom
The tests look green.
Fixes https://github.com/apache/beam/issues/35858
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-rev …

update the changes.md for upgrading MongoDB Java driver

---

sdks/go/pkg/beam/runners/prism/internal/worker/worker.go

When running a pipeline directly with `PrismRunner` (not using `PortableRunner`) and configuring a Docker environment type, the pipeline fails during the artifact staging phase.
The core issue seems to lie in how artifact materialization is handled in `boot.go`. Specifically, when the dependencies field in the environment proto is empty, the system falls back to using the legacy artifact service. This legacy service expects a manifest file, which is not provided in this scenario, leading to an error.
The fallback logic can be seen here:
https://github.com/apache/beam/blob/e28a69a36eec73b24e2229be48d171e41fd67c13/sdks/go/pkg/beam/artifact/materialize.go#L60-L68
This fallback is problematic because Prism always set the retrieval token (rt in the above code) to be `JobKey`: …

[Prism] Fix an issue when running a pipeline on docker in python

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml
sdks/java/extensions/arrow/src/main/java/org/apache/beam/sdk/extensions/arrow/ArrowConversion.java
sdks/java/io/google-cloud-platform/build.gradle

Update BOM to 26.65.0

---

.github/trigger_files/beam_PostCommit_SQL.json
sdks/java/extensions/sql/build.gradle
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/mongodb/MongoDbTable.java

Modify filter composition logic to avoid $and wrapping when possible by merging conditions directly into a composite Document. This addresses behavior changes in MongoDB driver 5.x while maintaining backward compatibility.
Fixes https://github.com/apache/beam/issues/35514
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_ST …

fix(mongodb): update filter composition to handle MongoDB 5.x driver

---

CHANGES.md
build.gradle.kts
contributor-docs/code-change-guide.md

Addresses https://github.com/apache/beam/issues/35760
This only adds `./gradlew formatChanges` to make sure some simple rules are enforced in CHANGES.md.
Next: add a github workflow to check the format for CHANGES.md. …

refactor(build): update changelog formatting in gradle task

---

sdks/python/apache_beam/runners/worker/data_sampler_test.py
sdks/python/setup.py

Why? Currently Apache Beam pins protobuf<6.0.0.dev0. Protobuf 6.30.0 was released on March 4, 2025: https://pypi.org/project/protobuf/6.30.0/, https://github.com/protocolbuffers/protobuf/releases/tag/v30.0 is the corresponding release.
Also fixed two flaky tests that became more flaky with the new Protobuf version. They were flaky because Protobuf doesn't guarantee map iteration order, so the sampler instances created [here](https://github.com/apache/beam/blob/b60ce5be96b2ea97084c1330430c8556ca59a8d9/sdks/python/apache_beam/runners/worker/data_sampler.py#L320) doesn't guarantee `'a'` is the first and `'b'` is the second sampler when the tests use `self.make_test_descriptor(outputs=['a', 'b'])`.
Fixes #35432.
Thank you for your contribution! Follow this checklist …

Support Protobuf 6.x.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java

Repeatedly calling `MemoizingPerInstantiationSerializableSupplier#get()` comes with some overhead from volatile reads which can be avoided by fetching the shared caches once in setup and reusing those references through non-volatile fields. …

[KafkaIO] Only retrieve the shared caches once during setup in ReadFromKafkaDoFn

---

.github/workflows/beam_IODatastoresCredentialsRotation.yml
.github/workflows/beam_MetricsCredentialsRotation.yml
.github/workflows/beam_Metrics_Report.yml
.github/workflows/beam_PostCommit_Java_BigQueryEarlyRollout.yml

Successful run: https://github.com/apache/beam/actions/runs/17467348772 …

Comment send email action

---

website/www/site/content/en/documentation/programming-guide.md

Issue Link : https://github.com/apache/beam/issues/34906 …

Added documentation for return vs yield usage in DoFn.process()

---

sdks/python/apache_beam/runners/direct/direct_runner.py

In https://github.com/apache/beam/pull/36031#pullrequestreview-3185384741 it became clear that external transforms were not being correctly excluded from Prism which was causing some flakiness across probably several tests. This PR should correctly exclude these by using the same mechanism we use for external transforms generally in pipelines.
I'm still not totally sure why the previous mechanism wasn't working, but I am confident in this version.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier …

Correctly exclude prism when using external transforms

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/providers/ReadFromPostgresSchemaTransformProvider.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/providers/WriteToPostgresSchemaTransformProvider.java

Fixes https://github.com/apache/beam/issues/35198
```
025-09-09T17:57:22.3193168Z =========================== short test summary info ============================
2025-09-09T17:57:22.3194694Z FAILED apache_beam/yaml/integration_tests.py::PostgresTest::test_only - ValueError: Error applying transform "WriteToPostgres" at line 33: java.lang.IllegalArgumentException: Wrong JDBC type. Expected 'postgres' but got ''
2025-09-09T17:57:22.3196717Z 	at org.apache.beam.sdk.io.jdbc.providers.WriteToPostgresSchemaTransformProvider.from(WriteToPostgresSchemaTransformProvider.java:63)
2025-09-09T17:57:22.3198431Z 	at org.apache.beam.sdk.io.jdbc.providers.WriteToPostgresSchemaTransformProvider.from(WriteToPostgresSchemaTransformProvider.java:36)
2025-09-09T17:57:22.3200284Z 	at …
```

Fix JDBC type validation to check for empty strings in Postgres

---

sdks/go/pkg/beam/runners/prism/internal/handlecombine.go
sdks/go/pkg/beam/runners/prism/internal/handlecombine_test.go
sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go

Same as TriggerElementCount, TriggerAlways does not work well with combiner lifting. Therefore, we disable if there is such a trigger in the window strategy.
With this fix, the TriggerAlways integration test passed.
fixes #36145

[Prism] Disable combiner lifting for TriggerAlways

---

sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/core_test.py
sdks/python/apache_beam/transforms/ptransform.py

Fixes #36088 
**Description:**
This PR addresses an issue where resource hints, particularly `tags`, are not correctly propagated when using the `with_exception_handling()` method on a `ParDo` transform.
Currently, any resource hints applied via `.with_resource_hints()` are lost when `with_exception_handling()` wraps the transform. The hints are not passed from the original `ParDo` to the `_ExceptionHandlingWrapper`, and subsequently not to the inner `ParDo` created within the wrapper's `expand` method. This prevents effective control over stage fusion, which is critical for pipelines utilizing accelerators like TPUs.
**Fix:**
This PR implements the following changes:
1.  Modified `ParDo.with_exception_handling` to copy resource hints from the `ParDo` instance to the created …

[Python] Fix: Propagate resource hints through with_exception_handling

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java

Set default redistribute key limit for KafkaIO read.
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java …

Set default redistribute key limit for KafkaIO read.

---

runners/google-cloud-dataflow-java/build.gradle

Previously, the Dataflow V2 tests rebuilt the distroless container using an overridden base image that was the `:latest` tag from the live docker repo. Now it should use the version that was built from head, and the V1 and V2 logic are roughly matching.
I did not refactor to make them share code, because I don't yet know exactly which parts of the shared code would be from logical necessity. …

Use distroless container built from HEAD in Dataflow V2 integration tests

---

sdks/go/pkg/beam/beam.shims.go
sdks/go/pkg/beam/core/runtime/exec/emit.go
sdks/go/pkg/beam/core/runtime/exec/optimized/emitters.go
sdks/go/pkg/beam/core/runtime/exec/optimized/emitters.tmpl
sdks/go/pkg/beam/core/runtime/exec/pardo.go
sdks/go/pkg/beam/register/emitter.go
sdks/go/pkg/beam/register/emitter_test.go
sdks/go/pkg/beam/runners/vet/testpipeline/testpipeline.shims.go
sdks/go/pkg/beam/testing/passert/passert.shims.go
sdks/go/pkg/beam/util/shimx/generate.go
sdks/go/pkg/beam/x/debug/debug.shims.go

fixes #31153
Rather the default pane mentioned in the bug (also shown below), 
```
got pane {Timing:0 IsFirst:false IsLast:false Index:0 NonSpeculativeIndex:0}
```
we get the [NoFiringPane](https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/core/typex/fulltype.go#L439) after the fix.
```
"got pane {Timing:unknown IsFirst:true IsLast:true Index:0 NonSpeculativeIndex:0}"
```

[Go SDK] Propagate paneInfo correctly.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/ResettableThrowingStreamObserver.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/observers/DirectStreamObserver.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/observers/StreamObserverCancelledException.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/ResettableThrowingStreamObserverTest.java

Example error that could be observed previously when onComplete was called on ResettableThrowingStreamObserver which already called delegate.onError within onNext.
```json
{
"jsonPayload": {
"exception": "java.lang.IllegalStateException\n    at com.google.common.base.Preconditions.checkState(Preconditions.java:527)\n    at org.apache.beam.runners.dataflow.worker.windmill.client.grpc.observers.DirectStreamObserver.onCompleted(DirectStreamObserver.java:198)\n    at org.apache.beam.runners.dataflow.worker.windmill.client.ResettableThrowingStreamObserver.onCompleted(ResettableThrowingStreamObserver.java:143)\n    at org.apache.beam.runners.dataflow.worker.windmill.client.AbstractWindmillStream.halfClose(AbstractWindmillStream.java:450)\n    at …
```

[Dataflow Streaming Java] Fix possible IllegalStateException when grpc streams have deadline exceeded.

---

sdks/python/apache_beam/io/parquetio.py

Installing pyarrow can be painful, especially on macs with M1s (I've run into this), and it isn't necessary for most python development. At the same time, doing anything involving conftest.py causes parquetio.py to be loaded[1], and this currently fails when pyarrow is not installed.
This is because even though pyarrow imports are guarded behind a try/except block, we assume that `pa` is defined later in the file when we enforce the `pa.Table` type. This works around that issue by creating a variable that holds `pa.Table` when it is defined, and None otherwise. Invoking these functions will still fail, but now you can load the file without issues.
[1] The dependency path that errors is:
```
ImportError while loading conftest '/Users/dannymccormick/beam/sdks/python/conftest.py'. …
```

Allow parquet import to be None

---

.github/workflows/python_tests.yml

Reverts apache/beam#36221 due to performance impact on Python unit tests.

Revert "Install go for python unit tests to use prism runner."

---

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/teststream.go

I have seen the following panic in one of the precommit test logs (	https://github.com/apache/beam/actions/runs/17888682703/job/50866217521?pr=36226).
```
0: panic in ElementManager.Bundles watermark evaluation goroutine: assignment to entry in nil map
goroutine 5592 [running]:
runtime/debug.Stack()
/home/runner/sdk/go1.24.4/src/runtime/debug/stack.go:26 +0x5e
github.com/apache/beam/sdks/v2/go/pkg/beam/runners/prism/internal/engine.(*ElementManager).Bundles.func2.1()
/runner/_work/beam/beam/sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go:385 +0x39
panic({0x169b4c0?, 0x2d0a4a0?})
/home/runner/sdk/go1.24.4/src/runtime/panic.go:792 +0x132
github.com/apache/beam/sdks/v2/go/pkg/beam/runners/prism/internal/engine.set[...].insert(...) …
```

[Prism] Fix panic in teststream

---

sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/pipeline_test.py

The pipeline proto generated by the python SDK for a composite transform that has multiple output pcollections was incorrect. It would _only_ specify the "main" pcollection of the DoOutputsTuple.
I think this has had no functional effect on runners since composite transforms are just an organizational container. I only happened to observe this from looking at visualizations of the pipeline. Here are before and after visualizations using the RenderRunner:
Since the "main" pcollection is not consumed by anything, the pipeline ends up being made up of disjoint subgraphs. …

[python] Fix output pcollections of composite transforms that return DoOutputsTuple

---

contributor-docs/release-guide.md

Clarify that it is the older release that should be in the archives. …

Clarify release-guide.md

---

examples/java/build.gradle
examples/java/common.gradle
examples/java/iceberg/build.gradle

Adding gradle task to run Iceberg examples. Issue  created with recent refactoring https://github.com/apache/beam/pull/35981
copied gradle task from examples/java
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Test …

Fix Build Issues with Iceberg Upgrade

---

sdks/go/pkg/beam/runners/prism/internal/engine/strategy.go
sdks/go/pkg/beam/runners/prism/internal/engine/strategy_test.go
sdks/go/pkg/beam/runners/prism/internal/execute.go

Construct after-processing-time trigger from proto and define trigger callbacks.
This is part of the original PR #36069, but with more tests and some changes to handle trigger reset.

[Prism] Support AfterProcessingTime triggers - part 1

---

sdks/python/apache_beam/testing/benchmarks/cloudml/requirements.txt

Fixes #36181
Successful run: https://github.com/apache/beam/actions/runs/17979979013/job/51143130603 …

Fix CloudML Benchmarks Dataflow job

---

build.gradle.kts
sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipeline.java
sdks/java/testing/junit/build.gradle
sdks/java/testing/junit/src/main/java/org/apache/beam/sdk/testing/TestPipelineExtension.java
sdks/java/testing/junit/src/test/java/org/apache/beam/sdk/testing/TestPipelineExtensionAdvancedTest.java
sdks/java/testing/junit/src/test/java/org/apache/beam/sdk/testing/TestPipelineExtensionTest.java

The module wasn't functioning. The test was not exercised (and actually would fail)
* Revert TestPipeline change in #35688 and move shared logic into package-private methods
* Remove TestPipeline private member in Extension. It messed up with Context store.
* Exercise tests on precommit
* Publish javadoc
#35688 was likely AI authored and was incomplete …

Fix JUnit 5 module

---

sdks/python/apache_beam/transforms/util.py
sdks/python/apache_beam/transforms/util_test.py
sdks/python/setup.py

Add a transform which allows users to use a secret manager to ensure that any GBK data is encrypted before being sent to a runner. This allows users to avoid unencrypted data at rest when using GBK.
Part of https://github.com/apache/beam/issues/36214
GitHub …

Add GroupByEncryptedKey transform

---

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
.github/workflows/beam_Publish_Docker_Snapshots.yml

This pull request updates the GitHub Actions workflows responsible for publishing Beam SDK and runner Docker images. The main goal is to ensure that the "latest" Docker tag is only applied when building from the `master` branch, preventing non-master branches from overwriting the "latest" tag, fixes #24130 .
A step was added to set the `LATEST_TAG` variable to `,latest` only when the workflow runs on the `master` branch, ensuring the "latest" tag is only used in that context. Outside of `master` it uses only the commit SHA.

Set latest tag based on branch in sdk and docker snapshots

---

CONTRIBUTING.md

Follow-up on https://github.com/apache/beam/pull/36301#discussion_r2383481481. …

CONTRIBUTING.md: include workflows README doc reference

---

.github/actions/gradle-command-self-hosted-action/action.yml

I have an guess, this will fix the Snapshots Build issue. I did some analysis to arrive at this
1. We are successfully exporting the python images for every build
2. We do this process for 4 python versions and not every time the same workflow times out. So, its just flakiness
3. When the workflow completes, it actually completes in less than 2 hours. So, its not a time out
4. I see many other build file has the --no-demon command. So, thought this addition might help close the process 
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?event=schedule&&?branch=master)](https:/ …

Exit gradle process after build complete

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/engine/strategy.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/management.go
sdks/go/pkg/beam/runners/prism/internal/unimplemented_test.go
sdks/go/test/integration/integration.go
sdks/go/test/integration/primitives/windowinto.go
sdks/go/test/integration/primitives/windowinto_test.go

This PR is a follow-up to #36126. The majority of this PR has been reviewed in #36069, and I've added comments to the code to indicate where the feedback has been addressed.

[Prism] Support AfterProcessingTime triggers - part 2

---

sdks/python/apache_beam/ml/inference/base_test.py

https://github.com/apache/beam/pull/36333 incidentally regressed ML tests because:
1) These tests previously couldn't run on Prism because of a trigger type. This unsupported capability was removed in https://github.com/apache/beam/pull/36333
2) These tests assumed they'd receive a value error, but portable pipelines raise RuntimeErrors always
This should fix the problem …

Make ml tests portable

---

runners/prism/java/build.gradle
sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go

Re-enable test: `org.apache.beam.sdk.testing.TestStreamTest.testEarlyPanesOfWindow` in prism.
This test uses accumulating mode in window strategy and the previous failure is due to not handling pendingAdjustment from `buildTriggeredBundle` (pointed out in the comment below). The fix is to plumb the pendingAdjustment out and correctly address it.

[Prism] Handle pending adjustment for processing time bundle correctly

---

sdks/python/apache_beam/ml/rag/enrichment/milvus_search.py

Prevent unnecessary connection attempts by returning early when receiving empty requests
```
apache_beam/ml/rag/enrichment/milvus_search_it_test.py:577: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
target/.tox-py313-ml/py313-ml/lib/python3.13/site-packages/apache_beam/pipeline.py:670: in __exit__
self.result = self.run()
^^^^^^^^^^
target/.tox-py313-ml/py313-ml/lib/python3.13/site-packages/apache_beam/testing/test_pipeline.py:118: in run
result = super().run(
target/.tox-py313-ml/py313-ml/lib/python3.13/site-packages/apache_beam/pipeline.py:620: in run
self._options).run(False)
^^^^^^^^^^
target/.tox-py313-ml/py313-ml/lib/python3.13/site-packages/apache_beam/pipeline.py:644: in run
return self.runner.run_pipeline(self, self._options) …
```

fix: handle empty requests in milvus search to avoid connection attempts

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStream.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetDataStreamTest.java

This caused test flakiness of GetDataStreamTest.testRequestKeyedData_reconnectOnStreamErrorAfterHalfClose
Fixes #36347 …

[Dataflow Streaming] Fix race in GetDataStream that could leave get data requests orphaned on stream errors after half-closing.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/python/apache_beam/examples/inference/anomaly_detection/anomaly_detection_pipeline/setup.py
sdks/python/apache_beam/examples/inference/sklearn_examples_requirements.txt
sdks/python/container/ml/py313/ml_image_requirements.txt
sdks/python/container/py313/base_image_requirements.txt
sdks/python/test-suites/tox/py313/build.gradle
website/www/site/content/en/documentation/runtime/environments.md

Fixes #31285, Fixes #30760
Successful runs: https://github.com/apache/beam/actions/runs/18283812412/job/52053326989, https://github.com/apache/beam/actions/runs/18284043559 …

Fix Python 3.13 workflows

---

sdks/python/apache_beam/coders/coder_impl.pxd
sdks/python/apache_beam/coders/coder_impl.py
sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test_common.py
sdks/python/apache_beam/pipeline_test.py

Ensures file paths are deterministically pickled on runners where the worker filepath may not be deterministic.
Adds a version tag to the coder name so that update compatibility checks fail if users upgrade without specifying update compatibility flag.
GitHub …

Pickle the relative path for code objects when cloudpickle is used to encode special deterministic types.

---

.github/workflows/beam_Infrastructure_PolicyEnforcer.yml
.github/workflows/beam_Infrastructure_SecurityLogging.yml
.github/workflows/beam_Infrastructure_ServiceAccountKeys.yml
.github/workflows/build_release_candidate.yml
.github/workflows/build_wheels.yml
.github/workflows/dask_runner_tests.yml
.github/workflows/flaky_test_detection.yml
.github/workflows/python_dependency_tests.yml
.github/workflows/refresh_looker_metrics.yml
.github/workflows/republish_released_docker_containers.yml
.github/workflows/run_perf_alert_tool.yml
.github/workflows/run_rc_validation_python_mobile_gaming.yml
.github/workflows/run_rc_validation_python_yaml.yml
.github/workflows/typescript_tests.yml

Reverts apache/beam#36277
Causing failures like https://github.com/apache/beam/actions/runs/18325592266/job/52189151483?pr=36426

Revert "Bump actions/setup-python from 4 to 6"
