runners/google-cloud-dataflow-java/build.gradle

Follow up of #31938 . Tested with command
```
./gradlew :runners:google-cloud-dataflow-java:validatesRunnerV2Test --tests *test*StringSetMetrics -PgcpProject=google.com:clouddfe -PgcpRegion=us-central1 -PgcpTempRoot=gs://.../tmp
``` …

Fix Dataflow v2 test failed tag container if project contains colon

---

website/www/site/content/en/get-started/quickstart-java.md

Update gradle syntax in quickstart docs. As is, I am getting:
```
A problem occurred evaluating root project 'word-count-beam'.
> Could not find method task() for arguments [execute, org.codehaus.groovy.runtime.MethodClosure@68cd5988, build_7ru3okd8nveeaa6nyo9lcm9l2$_run_closure5@76ad0289] on root project 'word-count-beam' of type org.gradle.api.Project.
```
Might be a change in syntax in newer gradle versions. …

Change the gradle task definition in quickstart.

---

sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIO.java
sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOParse.java
sdks/java/io/csv/src/main/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecord.java
sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOParseTest.java
sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOStringToCsvRecordTest.java
sdks/java/io/csv/src/test/java/org/apache/beam/sdk/io/csv/CsvIOTest.java

[CsvIO] Create CsvIOParse Class

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/config/StreamingEngineComputationConfigFetcher.java

Adds null checks when accessing OperationalLimits in config since they might not have been set yet. …

Adds null checks when accessing OperationalLimits in config.

---

website/www/site/content/en/documentation/ml/large-language-modeling.md

This came up in a conversation with a user who had this issue …

Add some large model troubleshooting steps

---

sdks/python/apache_beam/examples/complete/top_wikipedia_sessions.py
sdks/python/apache_beam/examples/complete/top_wikipedia_sessions_test.py

Update top_wikipedia_sessions to be more idiomatic with beam.Map.

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefresher.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/work/refresh/ActiveWorkRefresherTest.java

Fix error when ActiveWorkRefresher processed empty heartbeat map.

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java

Minor optimization for the common case of merging empty string sets.

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.58.0.md
website/www/site/content/en/get-started/downloads.md

Updates the Beam website with the 2.58.0 release blog post and download links.
DO NOT MERGE until 2.58.0 is approved  …

Beam Website Updates for 2.58.0 Release

---

runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismJobManager.java
runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismJobManagerTest.java

This PR closes #32056 enabling Job management for the Java Prism runner with auto closer when the Job State is terminal. …

[Prism] Enable Job management for the Prism runner

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java

#32068 introduced an unintended breaking change to standard Lineage metrics naming …

Fix Lineage name breaking change

---

website/www/site/content/en/documentation/sdks/yaml-join.md
website/www/site/layouts/partials/section-menu/en/sdks.html

Beam YAML doc to be published in the Beam [site](https://beam.apache.org/documentation/sdks/yaml/)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+eve …

Create Beam YAML Join documentation

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java

issue: https://github.com/apache/beam/issues/21599
cover datetime string fraction 1 to 6 or absent. …

fix: cover bigquery datetime fraction 1 to 6 or absent

---

README.md

Fix broken Beam Quest URL in README.md

---

README.md

fix BeamQuest link on ReadMe

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

This PR updates the Beam SDK Container Image tag. …

Update names.py with container image tag

---

examples/notebooks/beam-ml/gemma_2_sentiment_and_summarization.ipynb

Copy editing the Gemma notebook to prepare it for import to DevSite. …

Copy editing the Gemma notebook

---

.asf.yaml

Protect release branch

---

CHANGES.md
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java

Cherry-picks #32134 into the 2.58.1 release branch …

Cherry pick #32134

---

sdks/python/apache_beam/yaml/yaml_combine.py
website/www/site/content/en/documentation/sdks/yaml-combine.md
website/www/site/content/en/documentation/sdks/yaml-inline-python.md
website/www/site/content/en/documentation/sdks/yaml.md

**Explicitly define Beam imports for callables**
* PR adds explicit beam import statements to inlined python callables. This is technically redundant as 'apache_beam' already gets imported as 'beam' in several places along the codepath, so it is already imported when the callable is run. However, this is not guaranteed to stay this way, and it is more clear to the user than they must import dependencies which are not included on the hidden code path.
**Add suffix to windowing in a couple examples**
* A couple windowing examples did not include recently added time suffix
**Upgrade gcloud dataflow yaml command to use non-beta version**
* gcloud dataflow yaml run command was still referencing beta version
SQL Combine
* The example in the docs was not valid due to a small error in the …

[yaml] Doc improvements

---

examples/notebooks/beam-ml/gemma_2_sentiment_and_summarization.ipynb

Remove references to a local kernel, correct the pip invocation …

Update Gemma 2 Notebook

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.58.1.md
website/www/site/content/en/get-started/downloads.md

Update website for 2.58.1 release

---

CHANGES.md
sdks/java/io/clickhouse/build.gradle
sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIO.java
sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/ClickHouseWriter.java
sdks/java/io/clickhouse/src/test/java/org/apache/beam/sdk/io/clickhouse/ClickHouseIOTest.java

Update ClickHouseIO to use the latest version of the ClickHouse JDBC driver (0.6.4) #32228  …

Update ClickHouseIO to use the latest version of the ClickHouse JDBC driver (0.6.4)

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update beam-master image to 20240819. …

Update beam-master to 20240819

---

website/www/site/content/en/documentation/patterns/overview.md
website/www/site/content/en/documentation/patterns/shared-class.md
website/www/site/layouts/partials/section-menu/en/documentation.html

A cache is a software component that stores data so that future requests for that data can be served faster. Side inputs, stateful `DoFn` and calling an external service can be used for accessing a cache. The Python SDK provide another option in the shared module, which can be more efficient than side inputs in terms of the amount of memory required and simpler than stateful `DoFn`.
The samples on this page show you how to use the Shared class of the [shared module](https://beam.apache.org/releases/pydoc/current/apache_beam.utils.shared.html) to enrich elements in both bounded and unbounded `PCollection`s
It supports this issue - https://github.com/apache/beam/issues/32177 …

Add a pattern for using a shared object as a cache

---

sdks/python/apache_beam/yaml/yaml_io.py

Adds a meaningful error message for `ReadFromPubSub` when a JSON/AVRO format is specified without a schema.
This PR also changes logic to allow upper or lowercase format similar to Java implementation. …

[yaml] Fix PubSub error message

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt

Dependabot is trying to resolve a vulnerability on nltk 3.8.1 but 3.9 has an issue loading wordnet. This bumps to 3.9.1 which fixes that issue. …

Update nltk version to 3.9.1

---

sdks/java/io/kafka/upgrade/src/main/java/org/apache/beam/sdk/io/kafka/upgrade/KafkaIOTranslation.java

Fixes a breakage related to Kafka upgrade

---

runners/portability/java/src/main/java/org/apache/beam/runners/portability/JobServicePipelineResult.java
runners/portability/java/src/main/java/org/apache/beam/runners/portability/PortableRunner.java
runners/portability/java/src/test/java/org/apache/beam/runners/portability/PortableRunnerTest.java

Reverts apache/beam#32247
It causes pipelines to pass that should fail, so reverting.

Revert "Portable runner fixes"

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt

Fix CVE-2024-35195 for Beam Python images …

Update requests package to 2.32.0

---

sdks/python/apache_beam/utils/subprocess_server.py

Better error when Python xlang download jar not available

---

sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoSchemaTranslator.java

Better error message when trying to get Beam Schema from proto schema with Struct

---

runners/spark/src/main/java/org/apache/beam/runners/spark/stateful/SparkStateInternals.java
runners/spark/src/test/java/org/apache/beam/runners/spark/stateful/SparkStateInternalsTest.java

fixes #32225 
This PR contains these changes
- add `SparkSetState` in `SparkStateInternals`
- remove ignored setState tests …

Add SetState support for SparkRunner

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowWorkProgressUpdater.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java

The `enable_hot_key_logging` experiment is a valid way to turn on hotkey logging, but we don't respect it today. This respects both the service option and the experiment. …

Check experiment for hotkey logging

---

runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowWorkProgressUpdater.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java

Cherry pick: Check experiment for hotkey logging (#32285)

---

.github/workflows/beam_PostCommit_Sickbay_Python.yml

This is not adding any value. We can still get the ability to run/share a sickbay suite by just removing the scheduled trigger though …

Disable sickbay scheduled runs

---

contributor-docs/release-guide.md

These have all been automated away …

Remove some setup steps we don't need anymore

---

sdks/python/apache_beam/yaml/standard_io.yaml
sdks/python/apache_beam/yaml/tests/tsv.yaml

Rename delimiter to sep to pass to pandas.

---

sdks/python/apache_beam/io/gcp/bigquery_test.py

Make autosharding test more robust

---

website/www/site/layouts/partials/header.html

This probably makes more sense given that it is time sensitive …

Move beam summit banner to top of swiper slide

---

.github/workflows/build_wheels.yml

Right now, we only sometimes build wheels, but we always try to add checksums/upload them. This leads to issues like https://github.com/apache/beam/actions/runs/10598179779/job/29370575807 which is causing wheel building to consistently fail.
This fixes it by matching conditions for building/checksums/pushing …

Fix pr building of wheels

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/DynamicDestinations.java

Document an existing issue #32335 …

Document dynamic destination key should be unique over the pipeline

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceFactory.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableSharedClientTest.java

This PR expands the refcount lease on the underlying Bigtable client from Start/StopBundle to the first StartBundle until Teardown. The previous behavior had a lot client & connection churn when all worker threads had similar load.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/ …

Fix BigtableIO.write() client sharing

---

.test-infra/tools/stale_dataflow_prebuilt_image_cleaner.sh

After Artifact registry, public images are aggressively deleted. Remove them from clean up list until we figure it out …

Pause delete images in public AR

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/hive/exec/build.gradle

This is causing some conflicts for Iceberg writes with HiveCatalog

Relocate guava in shaded hive-exec

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Updates Python SDK harness HEAD container for Dataflow. …

Updates Python SDK harness HEAD container for Dataflow.

---

sdks/python/apache_beam/pipeline_test.py
sdks/python/apache_beam/runners/common.py
sdks/python/apache_beam/transforms/core.py

This is useful when one wants to capture and preserve all the windowing information for later use (and is both more convenient and less error-prone than gathering the timestamp, windows, and pane info separately).
New values with the same windowing value can be constructed via WindowedValue.with_value(...) and emitted asynchronously (e.g. after batching or in finish_bundle). …

Add WindowedValueParam option to DoFns.

---

sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_unit_test.py
website/www/site/content/en/documentation/sdks/yaml-errors.md

[YAML] Better errors for unconsumed error outputs.

---

sdks/python/apache_beam/runners/interactive/interactive_beam.py
sdks/python/apache_beam/runners/interactive/pipeline_fragment.py
sdks/python/apache_beam/runners/interactive/pipeline_fragment_test.py
sdks/python/apache_beam/runners/interactive/recording_manager.py

Allow ib.collect to work with non-interactive runners.

---

.github/workflows/build_wheels.yml
.github/workflows/python_tests.yml

Dependabot tried to do this partially in https://github.com/apache/beam/pull/32390 but got upload/download versions out of sync, which can cause issues. This upgrades everything to v4 and download-artifact to v4.1.7 which has the patch we need
GitHub Actions …

Upgrade artifact actions to v4

---

examples/notebooks/blog/unittests_in_beam.ipynb

Split this notebook addition separately from the blog post "Unit Testing in Beam" (will reference it there).
[![Build …

Colab Notebook for Unit Tests in Beam

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py38/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt
sdks/python/setup.py

- [CVE-2024-22195](https://nvd.nist.gov/vuln/detail/CVE-2024-22195)
- [CVE-2024-34064](https://nvd.nist.gov/vuln/detail/CVE-2024-34064) …

Bump jinja2 to 3.1.4 to resolve vulnerability issue

---

sdks/python/setup.py

js2py is an optional feature for Beam YAML only, so moving to yaml tag to avoid forcing dependency for python users …

[yaml] Move js2py package to yaml deps

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
scripts/tools/bomupgrader.py
sdks/java/container/license_scripts/dep_urls_java.yaml

`python scripts/tools/bomupgrader.py 26.45.0` logs:
```
INFO:root:Changed com.google.api:gax: 2.48.0 -> 2.52.0
INFO:root:Changed com.google.cloud:google-cloud-spanner: 6.66.0 -> 6.74.0
INFO:root:Changed io.grpc:grpc-netty: 1.62.2 -> 1.66.0
INFO:root:Unchanged: io.netty:netty-transport:4.1.100.Final
INFO:root:Changed com.google.protobuf:protobuf-java: 3.25.3 -> 3.25.4
INFO:root:Unchanged: org.apache.arrow:arrow-memory-core:15.0.2
INFO:root:Changed com.google.apis:google-api-services-bigquery: v2-rev20240323-2.0.0 -> v2-rev20240815-2.0.0
INFO:root:Unchanged: com.google.apis:google-api-services-cloudresourcemanager:v1-rev20240310-2.0.0
INFO:root:Changed com.google.apis:google-api-services-storage: v1-rev20240319-2.0.0 -> v1-rev20240706-2.0.0
INFO:root:Changed …
```

Upgrade gcp-bom to 26.45.0

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/pipeline.py
sdks/python/apache_beam/pipeline_test.py

Fixes #20964
When `--no_wait_until_finish` is set and defining pipelines with the `with` statement,  the job execution continues without waiting for completion. …

[Python] Add the "no_wait_until_finish"  option without waiting 

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Disable permared test suite as per: https://github.com/apache/beam/issues/30517 …

Disable permared go xlang tests.

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.59.0.md
website/www/site/content/en/get-started/downloads.md

Update the Beam site pages with the 2.59.0 release, happening on 2024-09-11. …

2.59.0 Beam site updates.

---

website/www/site/content/en/get-started/downloads.md

Noted some issues with the download page. …

Fixes link typo in 2.59, and fixes archive links.

---

sdks/python/setup.py

This was causing test failures, so we added an upper bound. I tried removing the bound and it seems like tests are passing again; looks like there was a new version released, so I'm guessing that fixed the issue …

Bump spanner max bound back to <4

---

sdks/python/apache_beam/runners/interactive/display/pcoll_visualization_test.py
sdks/python/apache_beam/runners/interactive/interactive_beam.py
sdks/python/apache_beam/runners/interactive/non_interactive_runner_test.py
sdks/python/apache_beam/runners/interactive/pipeline_fragment.py
sdks/python/apache_beam/runners/interactive/recording_manager.py

This will avoid having to specify things at pipeline creation time (and re-create everything, including destroying the caches) if the choice of runner or other desired options changes.  …

Accept runner and options in ib.collect.

---

website/www/site/layouts/partials/header.html

Once the summit is over I'll move this out of draft …

Remove beam summit banner

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Updates to a container build sept 10 2024 …

Bump Python SDK container for Dataflow

---

.github/workflows/tour_of_beam_backend_integration.yml

Fixes the call to `docker-compose` which in new versions is `docker compose`. 
Also sets the runner version to `ubuntu-22.04` instead of `ubuntu-latest`. This way i hope we wont have such breaking changes.  …

fix docker compose command

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java

Xlang ReadFromKafka transform was overriding consumer config updates passed to transform. …

Don't override existing consumer config values KafkaIO xlang

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableService.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIOTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImplTest.java

Previously this was done as a side effect of batcher.close. Now we explicitly ensure that all element future have been resolved and any handler errors are propagated …

fix: ensure that all outstanding future have completed in FinishBundle

---

contributor-docs/discussion-docs/2016.md
contributor-docs/discussion-docs/2017.md
contributor-docs/discussion-docs/2018.md
contributor-docs/discussion-docs/2019.md
contributor-docs/discussion-docs/2020.md
contributor-docs/discussion-docs/2021.md
contributor-docs/discussion-docs/2022.md
contributor-docs/discussion-docs/2023.md
contributor-docs/discussion-docs/2024.md
contributor-docs/discussion-docs/generate_doc_md.py

This script generates a Markdown file containing a list of discussion documents submitted to the dev@beam.apache.org mailing list for a given year. **This should be able to extract most of documents.**
1. **Download email archives:** The script requires local copies of the dev@beam.apache.org mbox files for the desired year. You can download these manually or modify the script to automate the download process.
2. **Run the script:**
```bash
python generate_doc_md.py <year>
```
3. **Output:** The script will create a Markdown file named <year>.md containing a table of discussion documents with their authors, subjects, and submission dates.
* The script currently extracts links to Google Docs and Apache short links (s.apache.org).
* Ensure you have the necessary libraries installed (e.g., …

Add the script to extract docs from the dev list

---

sdks/python/tox.ini

Fixes the test environment definition for macos unit tests that got clobbered during merge conflict resolution. …

Fix macos tox.ini definition

---

sdks/python/apache_beam/yaml/yaml_io.py

Restores an ignore that was accidentally removed in the Python 3.8 actions removal, leading to the linting precommit being red. …

Restore mypy ignore[call-arg] in yaml_io.py

---

CHANGES.md
sdks/python/apache_beam/__init__.py
sdks/python/setup.py

Adds a warning for use of Beam 3.8, as the Python version is reaching EOL and support will be removed in Beam 2.61.0
Part of #31192  …

Warn when using Beam with Python 3.8

---

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
.github/workflows/build_wheels.yml
.github/workflows/update_python_dependencies.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
gradle.properties
local-env-setup.sh
release/src/main/Dockerfile
release/src/main/python-release/python_release_automation.sh

With the decision being made to hold off on full removal of Python 3.8 support until the 2.61.0 release, some workflows (including publishing snapshot containers) needed to be reverted. These changes should allow the 2.60.0 release to include all python 3.8 artifacts correctly.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BU …

Restore release-essential references to 3.8

---

sdks/python/apache_beam/options/pipeline_options.py

This prevents obscure errors later on when this single string is "iterated" over into its characters. …

Better error message for incorrect pipeline options flags.

---

.github/build.gradle
.github/workflows/beam_PostCommit_XVR_GoUsingJava_Dataflow.yml

Disable a permared suite.

---

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml

Tested by running the workflow manually:
https://github.com/apache/beam/actions/runs/10911969900/job/30285739294
https://pantheon.corp.google.com/artifacts/docker/apache-beam-testing/us/gcr.io/beam-sdk%2Fbeam_java_expansion_service?e=-13802955&inv=1&invt=AbcZpQ&jsmode=o&mods=dataflow_dev&project=apache-beam-testing …

Publish Java Expansion Service SNAPSHOT containers

---

build.gradle.kts
runners/prism/java/build.gradle
runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismLocatorTest.java

Fix https://github.com/apache/beam/pull/32414#issuecomment-2344042627 …

Add runners/prism/java to java PreCommit

---

sdks/java/expansion-service/build.gradle

This PR allows a user to create a custom expansion service JAR without needing to provide `jamm` manually as a dependency.
e8cebdf4fe7e920b6494156aa3127037f23b58fe added a dependency on `":sdks:java:harness"` in the expansion service target which has a transitive dependency on a 'provided' `jamm`: https://github.com/apache/beam/blob/33a0bfb5d374fae99b1f19405aba341a0716b1c0/sdks/java/harness/build.gradle#L40
By adding it as a `runtimeOnly` dependency in the expansion service target, a user can create a cross-language Java transform by simply importing the `beam-sdks-java-expansion-service` JAR. …

Include jamm as runtime dependency in expansion-service

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java

Introduced in #32381 so not yet made to release
[![Build …

Remove debug leftover

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/apache_beam/ml/gcp/visionml_test_it.py

This assert was inadvertently ignored, until https://github.com/apache/beam/pull/30771 exposed that and turned the meaningless assert into an error. This broke the python postcommit - https://github.com/apache/beam/actions/workflows/beam_PostCommit_Python.yml - this fixes the problem
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-in …

Move assert into pipeline

---

.test-infra/jenkins/build.gradle

We should also move this out of the jenkins folder, which is why this was missed.
Example run with the change - https://github.com/apache/beam/actions/runs/11018241174 …

Update build.gradle to use 3.12 for metrics report

---

sdks/java/io/solace/src/test/java/org/apache/beam/sdk/io/solace/it/SolaceIOIT.java

Fixing flaky integration test in SolaceIO. 
I think the problem comes from the Direct Runner which closes 5% of open readers ([source](https://github.com/apache/beam/blob/d93f93abf0e44c050781a635c3c5a834dd292627/runners/direct-java/src/main/java/org/apache/beam/runners/direct/UnboundedReadEvaluatorFactory.java#L155)). This causes some of the messages to not be acknowledged, and therefore they are redelivered. Turing on the deduplication should make the test stable.
Addresses #32548
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTI …

SolaceIO: deduplicate records in the integration test

---

CHANGES.md
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubJsonClient.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubTestClient.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClientTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIOTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubJsonClientTest.java

Reverts apache/beam#32465
This breaks Java PreCommit

Revert "fix: add topic existing validation"

---

sdks/python/apache_beam/io/kafka.py

Update python KafkaIO docstring to add the `use_deprecated_read` option. It'll resolve https://github.com/apache/beam/issues/31839. …

Update python KafkaIO docstring to add the use_deprecated_read option

---

sdks/python/apache_beam/transforms/core.py

typo fix
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20sourc …

represenation->representation

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java

Fixes a transform upgrade compatibility issue related to BigqueryIO

---

contributor-docs/release-guide.md

Update Guidance to incorporate the Github Release into the validation process.
* The main change is that once the RC is ready, we publish the pre-release page (no longer draft, not yet latest).
* Includes linking to the Github Release page from the Vote email template.
* This allows review of the Github Release description during validation and vote, and public access to the pre-release assets.
* Update contributor one-liner to produce comma separated names instead of newline separated names. This avoids the list of names dominating the blog post content.
* Emphasizes updating the GitHub release with the final release tag, not simply leaving it as the RC forever. …

Update Release guide with new github release guidance.

---

sdks/python/apache_beam/yaml/yaml_io.py

I'm removing this warning since we agreed not to deprecate lowercase formats, but to accept both. …

[YAML] - Remove warning message

---

runners/google-cloud-dataflow-java/build.gradle

This PR mirrors latest Beam container image tags `beam-master-20240930`.
~Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.~
~Update `CHANGES.md` with noteworthy changes.~
~If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~ …

Bump dataflow java container version to beam-master-20240930

---

sdks/python/apache_beam/metrics/metric.py
sdks/python/apache_beam/metrics/metric_test.py

Python SDK counterpart of #32585 …

Support string FQN as a way to add lineage information

---

runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismRegistrar.java
runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismRegistrarTest.java

* Ensure the option types are AutoService registered for parity with other runners.
* Rename existing file to PrismRegistrar (matches DirectRunner set up), and homes both registrations in them. …

[prism][Java] Register option types

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/BatchSpannerRead.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/NaiveSpannerRead.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/ReadOperation.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/FakeServiceFactory.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteTest.java

Report Lineage metrics for SpannerIO

---

runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismLocator.java
runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismPipelineOptions.java
runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismLocatorTest.java
website/www/site/content/en/blog/validate-beam-release.md

* In particular support the "deriving the download URL from the Release Page URL" behavior.
* Change the tests slightly to validate the location construction behavior.
* Update flag descriptions.
* Add RC Validation instructions for Prism. …

[prism][java] Update Prism locator to match Python SDK semantics.

---

CHANGES.md
sdks/python/apache_beam/testing/util.py

I got the feedback from some internal customers that we're not clear enough about this error message when they upgraded to the latest version. This should help. …

Call out breaking assert_that change more explicitly

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTranslation.java

Extracted from https://github.com/apache/beam/pull/32360

BigQuey fix invalid null checks in io translation

---

playground/infrastructure/cloudbuild/playground_cd_examples.sh
playground/infrastructure/requirements.txt

Adds virtualenv to bypass the new debian pip requirement of using system packages. Given that requirements.txt is used pip is easier to handle. This was chosen instead of --break-system-packages switch for pip as i could not see if it would cause issues elsewhere. 
Also bumps PyYAML to 6.0.2 because of some issue with cython. 
Should help with #32544  …

add virtualenv to playground CD 

---

sdks/java/container/license_scripts/pull_licenses_java.py

This is causing flaky test, e.g.,
https://github.com/apache/beam/actions/runs/11124458886/job/30910041003
https://github.com/apache/beam/actions/runs/11118209889/job/30891413059
Mitigate https://github.com/jd/tenacity/issues/486
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.te …

Fix pull_licenses_java script retry broken for tenacity 8.5

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/go/run_with_go_version.sh

* Pre-release just in case bump. …

Update building steps to use go 1.23.2

---

.github/workflows/load-tests-pipeline-options/python_Combine_Flink_Batch_2GB_10_byte_records.txt
.github/workflows/load-tests-pipeline-options/python_Combine_Flink_Batch_2GB_Fanout_4.txt
.github/workflows/load-tests-pipeline-options/python_Combine_Flink_Batch_2GB_Fanout_8.txt
.github/workflows/load-tests-pipeline-options/python_GBK_Flink_Batch_2GB_of_10B_records.txt
examples/multi-language/README.md

Move remaining reference of python3.8 docker image to python 3.9

---

sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/ptransform_test.py

Make parent thread state sampler available in child thread when running ParDo#with_exception_handling(timeout).
- ParDo#with_exception_handling(timeout) executes the DoFn in a new thread [1]
- Incrimenting a counter invokes tries to access the state sampler that was declared in the main thread local storage from the child thread [2]
- Since the child thread does not have access to the state sampler from the main thread the get_current_tracker method fails silently [3] and the counter isnt actually incremented
This change makes the parent thread's state sampler available to the child thread.
[1] https://github.com/apache/beam/blob/1eddbdca4c5efe4bfccc11af29624f9689ea2997/sdks/python/apache_beam/transforms/core.py#L2599
[2] https://github.com/apache/beam/blob/1eddbdca4c5efe4bfccc11af29624f96 …

Fix counter metrics for ParDo#with_exception_handling(timeout).

---

.github/workflows/build_wheels.yml

Right now, this doesn't render a arch or python version …

Improve wheels job name

---

sdks/python/apache_beam/io/fileio.py

In this commit, we add note on `output_fn` constructor argument in `WriteToFiles` class to indicate that It is unused and only retained for backward compatibility.
fixes #30009 …

sdks/python/apache_beam/io: add note on `output_fn` ctor arg to  indicate that It is unused and only retained for backward compatibility

---

sdks/go/BUILD.md
sdks/go/README.md

Fix linter errors in Go SDK BUILD.md and README.md files …

Fix linter errors in Go SDK BUILD.md and README.md files

---

website/www/site/content/en/get-started/quickstart-java.md

previous syntax for the snippet was in Groovy, but in step 1&2 of the Gradle conversion we use Kotlin
[![Python …

Update quickstart-java.md , corrected Kotlin syntax

---

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml

This is needed to run pipelines that use the default environment at HEAD, for example, when a pipeline uses an expansion service built from HEAD.
Example run: https://github.com/apache/beam/actions/runs/11209507982/job/31154805045
Updated container: docker pull gcr.io/apache-beam-testing/beam-sdk/beam_java11_sdk:2.61.0.dev …

Tags Java SNAPSHOT containers with the '.dev' version

---

sdks/java/io/expansion-service/build.gradle

#32623 was intended to package kafka-clients 3.1.2 into the expansion-service JAR, but gradle favors versions specified in groovy plugin module, so the version was being overridden with 2.4.1. This PR forces 3.1.2 to be used during runtime.  …

Force kafka 3.1.2 for expansion-service jar

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSink.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileBasedSource.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystem.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileSystems.java
sdks/java/core/src/main/java/org/apache/beam/sdk/io/ReadAllViaFileBasedSourceTransform.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystem.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystemTest.java
sdks/java/io/amazon-web-services/src/main/java/org/apache/beam/sdk/io/aws/s3/S3FileSystem.java
sdks/java/io/amazon-web-services/src/test/java/org/apache/beam/sdk/io/aws/s3/S3FileSystemTest.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystem.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystemTest.java
sdks/java/io/azure/src/main/java/org/apache/beam/sdk/io/azure/blobstore/AzureBlobStoreFileSystem.java
sdks/java/io/azure/src/test/java/org/apache/beam/sdk/io/azure/blobstore/AzureBlobStoreFileSystemTest.java
sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java
sdks/python/apache_beam/io/aws/s3filesystem.py
sdks/python/apache_beam/io/aws/s3filesystem_test.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem_test.py
sdks/python/apache_beam/io/filebasedsink.py
sdks/python/apache_beam/io/filebasedsource.py
sdks/python/apache_beam/io/filesystem.py
sdks/python/apache_beam/io/filesystems.py
sdks/python/apache_beam/io/gcp/gcsfilesystem.py
sdks/python/apache_beam/io/gcp/gcsfilesystem_test.py

* Report File Lineage on directory
* added comments, restore lineage assert in TextIOIT
* Report bucket level Lineage for files larger than 100
* fix lint …

[Release-2.60.0] Cherry-pick #32662 into the release branch

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetCell.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/StringSetDataTest.java
sdks/python/apache_beam/metrics/cells.pxd
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/cells_test.py
sdks/python/apache_beam/metrics/execution.py
sdks/python/apache_beam/metrics/execution_test.py
sdks/python/apache_beam/metrics/monitoring_infos.py

* Enforce a size limit on StringSetData
* Make StringSetData set mutable. This avoids copy and create new ImutableSet every time
* adjust warning log …

[Release-2.60.0] Cherry pick #32650 into the release branch

---

sdks/java/io/expansion-service/build.gradle

[Release-2.60.0] Cherry-pick #32703 into the release branch

---

sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java

Follow up of #32706
It's breaking TextIO Performance test for test cases that do not assign numShards.
Isn't release blocking as it is a glitch in test …

Fix assert in TextIOIT

---

buildSrc/src/main/groovy/org/apache/beam/gradle/kafka/KafkaTestUtilities.groovy
sdks/java/extensions/avro/build.gradle
sdks/java/extensions/avro/src/test/java/org/apache/beam/sdk/extensions/avro/AvroVersionVerificationTest.java
sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/kafka-integration-test.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOTest.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

Add check to avro and kafka compatibility tests

---

sdks/python/apache_beam/utils/subprocess_server.py
sdks/python/pyproject.toml
sdks/python/tox.ini

Addresses #32681 and fixes the failed tests in. https://github.com/apache/beam/actions/runs/11278619395/job/31367491096 …

Fixed the tox and pyproject settings for numpy 2

---

.github/workflows/finalize_release.yml

Weirdly, searching for `apache/beam` does much better than `apache/beam_` when using docker search. This was causing us to miss real images which we needed to push. For example, here are the top 20 results for each.
With my changes:
```
docker search "apache/beam" --format "{{.Name}}" --limit 100
apache/beam_go_sdk
apache/beam_java11_sdk
apache/beam_python3.8_sdk
apache/beam_python3.7_sdk
apache/beam_java8_sdk
apache/beam_python3.10_sdk
apache/beam_python3.11_sdk
apache/beam_python3.9_sdk
apache/beam_java17_sdk
apache/beam_java_sdk
apache/beam_python3.6_sdk
apache/beam_spark_job_server
apache/beam_flink1.13_job_server
apache/beam_spark3_job_server
apache/beam_flink1.12_job_server
apache/beam_java21_sdk
apache/beam_flink1.14_job_server
apache/beam_flink1.16_job_server …
```

Fix docker search

---

sdks/python/tox.ini

Fix the failed numpy2 related tests in https://github.com/apache/beam/actions/runs/11291150541/job/31404478814
[![Build …

Fix more numpy 2 test issues

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java

Closing on each bundle will cause slowness in Bigtable read. In the future we'll migrate BigtableRead to SplittableDoFn to clean up the resource properly. …

fix: skip close on bundles

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java

[Release-2.60.0] Cherry pick #32661 into the release branch

---

.github/workflows/build_release_candidate.yml

Usse ubuntu-22.04 for release candidate build for now

---

release/src/main/scripts/download_github_actions_artifacts.py

Fix download artifact truncate page

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/ActiveWorkState.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/Work.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStream.java

Plumb the backend tokens to work items
R: @scwhittle @arunpandianp  …

plumb backend worker token to work items

---

sdks/python/apache_beam/transforms/environments.py

This is a follow-up of PR #32326 to add ordered list state to python sdk capabilities.

Add ordered list state to python capabilities

---

bigquery_enrichment_transform.ipynb

Add example notebook for BigQuery enrichment transform. …

Created using Colab

---

sdks/java/expansion-service/build.gradle
sdks/java/extensions/sql/expansion-service/build.gradle
sdks/java/io/expansion-service/build.gradle
sdks/python/apache_beam/yaml/yaml_provider.py

re-enable gradle cache after stablelized
(a trivial typo fix is used to trigger precommits, including the originally affected Yaml_xlang precommit) …

Revert disabled Gradle cache in #32751

---

website/www/site/content/en/blog/beam-summit-2024-overview.md

Add the beam summit 2024 overview blog

---

sdks/python/apache_beam/ml/inference/vllm_inference.py

Right now if our vLLM server fails to spin up, we retry forever. This is because we're resetting the retry count every time we go through the start_server/check_connectivity loop. This fixes the issue. …

Correctly propogate retries

---

.github/actions/setup-default-test-properties/test-properties.json
.github/workflows/beam_LoadTests_Java_GBK_Smoke.yml
.github/workflows/beam_PostCommit_Java_Examples_Flink.yml
.github/workflows/beam_PostCommit_Java_Nexmark_Flink.yml
.github/workflows/beam_PostCommit_Java_PVR_Flink_Streaming.yml
.github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink_Java8.yml
.github/workflows/beam_PostCommit_XVR_Flink.yml
.github/workflows/beam_PreCommit_Java_PVR_Flink_Batch.yml
.github/workflows/beam_PreCommit_Java_PVR_Flink_Docker.yml

These changes need to happen before #32836 because the tests will pull their definitions from `master` branch.
[![Build …

Move GitHub Actions workflows to Flink 1.19 and remove 1.15 and 1.16

---

website/www/site/content/en/blog/beam-2.60.0.md
website/www/site/content/en/get-started/downloads.md

2.60.0 Release blog post

---

sdks/python/apache_beam/runners/interactive/caching/reify.py

Use WindowedValueParam for interactive cache.

---

.github/workflows/beam_PreCommit_Prism_Python.yml

Run the Prism Validates Runner suite as a Python Precommit.
Fixes #32847 …

[#32847][prism] Add Github Action for Prism as a Python precommit

---

CHANGES.md
website/www/site/config.toml

Folow up of #32738
* Update release date in CHANGE.md
* Update latest version for website …

Follow up website and change.md after 2.60 release

---

CHANGES.md

Seems I put it in the template :-) …

Note Flink 1.19 support in CHANGES.md

---

website/www/site/content/en/documentation/ml/large-language-modeling.md

Even though we want to build out more in this space, this is doable with Beam primitives today; this doc should help people get started and we can enhance it as we go …

Add RAG to docs

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamDockerPlugin.groovy

Closes #32820 adding a new `target` parameter that if used forwards to `docker build --target=<target>`.  Prior to creating this PR, tested via `sdks:python:container:py311:docker` and `:sdks:java:container:java11:docker` using `--debug` to validate the expected forwarded args, temporarily hardcoding the value in the respective Dockerfiles. …

Add target parameter to BeamDockerPlugin

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/test-suites/portable/common.gradle
website/www/site/content/en/documentation/runtime/environments.md

Fix #32896
after self hosted github action runner bumped to Java11 …

Fix java sdk container dependency for Python PostCommit

---

.github/workflows/README.md
contributor-docs/release-guide.md

Doc fixes after 2.60 release

---

runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismExecutor.java
runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismExecutorTest.java
runners/samza/src/test/java/org/apache/beam/runners/samza/metrics/TestSamzaRunnerWithTransformMetrics.java
runners/samza/src/test/java/org/apache/beam/runners/samza/runtime/GroupByKeyOpTest.java
runners/samza/src/test/java/org/apache/beam/runners/samza/runtime/SamzaStoreStateInternalsTest.java

FIx #32911, mitigate #32208
* Fix PrismRunner test assert
* Disable affected Samza runner test in Java9+ …

Fix JavaPreCommit on Java11

---

runners/java-fn-execution/src/test/java/org/apache/beam/runners/fnexecution/control/RemoteExecutionTest.java

Increase RemoteExecutionTest sdk start timeout, caused flaky failure.

---

learning/tour-of-beam/learning-content/introduction/introduction-concepts/runner-concepts/description.md
website/www/site/content/en/documentation/runners/flink.md

Fix web page references to Flink 1.19 support since it is not released until 2.61.0

---

runners/portability/java/build.gradle
runners/prism/java/build.gradle

Accidentally introduced a new hard java8 in a Gradle action, so I'm fixing the new one I added, and correcting where I got it from. …

Remove gradle task java8's

---

sdks/python/apache_beam/runners/worker/bundle_processor.py

Separating this one out as it had a lot of changes. …

Modernize type hints for bundle_processor.py.

---

examples/notebooks/beam-ml/bigquery_enrichment_transform.ipynb
examples/notebooks/beam-ml/rag_usecase/opensearch_rag_pipeline.ipynb
examples/notebooks/beam-ml/run_inference_vllm.ipynb

These were flagged by an internal linter …

Fix a few notebook typos

---

website/www/site/content/en/documentation/programming-guide.md
website/www/site/content/en/get-started/quickstart-py.md

Note Python 3.12 support in documentation.
- https://beam.apache.org/get-started/quickstart-py/
- https://beam.apache.org/documentation/programming-guide/ …

Add Python 3.12 to documentation

---

examples/notebooks/beam-ml/bigquery_enrichment_transform.ipynb

There are currently 2 colab buttons, this removes one of them. I think the second one gets automatically added when running the export to GitHub …

Remove duplicate button from notebook

---

examples/notebooks/beam-ml/gemma_2_sentiment_and_summarization.ipynb

This was rendering poorly before. Example:
This fixes the problem. Example after my change:
✨  [RENDERED](https://colab.sandbox.google.com/github/apache/beam/blob/users/damccorm/gemmaFormatting/examples/notebooks/beam-ml/gemma_2_sentiment_and_summarization.ipynb) ✨  …

Fix gemma notebook formatting

---

contributor-docs/discussion-docs/2024.md

Update discussion docs

---

sdks/python/apache_beam/runners/interactive/display/pcoll_visualization.py

A future warning raised in Dataflow notebook affecting layout. However, we cannot easily change to data.map as long as we still support pandas dataframe < 2.1.0 …

Suppress future warning affecting Dataflow notebook

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Use beam-vendor-grpc-1_60_1:0.3

---

.github/trigger_files/beam_PostCommit_TransformService_Direct.json
sdks/python/expansion-service-container/build.gradle

Not doing this is causing https://github.com/apache/beam/actions/workflows/beam_PostCommit_TransformService_Direct.yml to fail with an error while building the Dockerfile:
```
Dockerfile:32 |  
-- | --
  | -------------------- |  
  | 30 \| |  
  | 31 \|     # Copy the requirements file |  
  | 32 \| >>> COPY target/requirements.txt /opt/apache/beam/ |  
  | 33 \| |  
  | 34 \|     # Copy the boot program |  
  | -------------------- |  
  | ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 9d7709f1-833a-4b95-b66f-14deb3703584::r9k42oghrhk8aon151jao368m: "/target/requirements.txt": not found
```
See the …

Copy in correct requirements file

---

sdks/python/apache_beam/ml/transforms/base.py
sdks/python/apache_beam/ml/transforms/base_test.py
sdks/python/apache_beam/ml/transforms/embeddings/huggingface.py
sdks/python/apache_beam/ml/transforms/embeddings/tensorflow_hub.py
sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai.py
sdks/python/apache_beam/ml/transforms/handlers.py
sdks/python/apache_beam/ml/transforms/handlers_test.py
sdks/python/apache_beam/ml/transforms/tft.py
sdks/python/apache_beam/ml/transforms/utils.py

Updates MLTransform files to PEP 585-style type hints
Part of #32969 …

Update MLTransform code to PEP 585 types

---

website/www/site/data/capability_matrix.yaml

Update the Dataflow column of the Capability Matrix with the following change:
The MapState and SetState classes are supported with streaming pipelines that use Streaming Engine and version 2.58.0 or later of the Java SDK. `SetState` and `MapState` are not supported for pipelines that use Runner v2.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob …

Update docs for MapState and SetState support update

---

website/www/site/content/en/documentation/programming-guide.md

fix typo: self.gaguge->self.gauge

---

sdks/python/apache_beam/examples/complete/estimate_pi.py
sdks/python/apache_beam/examples/cookbook/bigtableio_it_test.py
sdks/python/apache_beam/examples/cookbook/datastore_wordcount.py
sdks/python/apache_beam/examples/cookbook/group_with_coder.py
sdks/python/apache_beam/examples/inference/huggingface_language_modeling.py
sdks/python/apache_beam/examples/inference/huggingface_question_answering.py
sdks/python/apache_beam/examples/inference/onnx_sentiment_classification.py
sdks/python/apache_beam/examples/inference/pytorch_image_classification.py
sdks/python/apache_beam/examples/inference/pytorch_image_classification_with_side_inputs.py
sdks/python/apache_beam/examples/inference/pytorch_image_segmentation.py
sdks/python/apache_beam/examples/inference/pytorch_language_modeling.py
sdks/python/apache_beam/examples/inference/pytorch_model_per_key_image_segmentation.py
sdks/python/apache_beam/examples/inference/run_inference_side_inputs.py
sdks/python/apache_beam/examples/inference/sklearn_japanese_housing_regression.py
sdks/python/apache_beam/examples/inference/sklearn_mnist_classification.py
sdks/python/apache_beam/examples/inference/tensorflow_imagenet_segmentation.py
sdks/python/apache_beam/examples/inference/tensorflow_mnist_classification.py
sdks/python/apache_beam/examples/inference/tensorrt_object_detection.py
sdks/python/apache_beam/examples/inference/tfx_bsl/tensorflow_image_classification.py
sdks/python/apache_beam/examples/inference/vertex_ai_image_classification.py
sdks/python/apache_beam/examples/inference/vllm_text_completion.py
sdks/python/apache_beam/examples/inference/xgboost_iris_classification.py
sdks/python/apache_beam/examples/kafkataxi/kafka_taxi.py
sdks/python/apache_beam/examples/wordcount_xlang_sql.py

Updates Python code examples to PEP 585-style type hints (built-in types and collections classes for most type hints.) Also corrects some places where the typing module was imported directly. 
Part of #32969 …

Update type hinting in Python examples to PEP 585 standards

---

sdks/python/test-suites/dataflow/common.gradle

A container issue for the TensorRt postcommit suite broke the python postcommit, this disables the test while the problem is investigated. …

Temporarily disable TensorRT PostCommit suite

---

examples/java/src/test/java/org/apache/beam/examples/WordCountTest.java
examples/java/src/test/java/org/apache/beam/examples/complete/TopWikipediaSessionsTest.java
examples/java/src/test/java/org/apache/beam/examples/complete/game/GameStatsTest.java
examples/java/src/test/java/org/apache/beam/examples/complete/game/HourlyTeamScoreTest.java
examples/java/src/test/java/org/apache/beam/examples/complete/game/UserScoreTest.java
examples/java/src/test/java/org/apache/beam/examples/cookbook/BigQueryTornadoesTest.java
examples/java/src/test/java/org/apache/beam/examples/cookbook/DistinctExampleTest.java
examples/java/src/test/java/org/apache/beam/examples/cookbook/FilterExamplesTest.java
examples/java/src/test/java/org/apache/beam/examples/cookbook/JoinExamplesTest.java
examples/java/src/test/java/org/apache/beam/examples/cookbook/MaxPerKeyExamplesTest.java
examples/java/src/test/java/org/apache/beam/examples/cookbook/MinimalBigQueryTornadoesTest.java
examples/java/src/test/java/org/apache/beam/examples/cookbook/TriggerExampleTest.java
examples/kotlin/src/test/java/org/apache/beam/examples/kotlin/cookbook/DistinctExampleTest.kt
examples/kotlin/src/test/java/org/apache/beam/examples/kotlin/cookbook/FilterExamplesTest.kt
examples/kotlin/src/test/java/org/apache/beam/examples/kotlin/cookbook/JoinExamplesTest.kt
examples/kotlin/src/test/java/org/apache/beam/examples/kotlin/cookbook/MaxPerKeyExamplesTest.kt

Some cleanup.
The `ValidatesRunner` tests are meant to be compliance tests for the Beam model. There are unit tests of the examples so they don't belong in that category. They are not included in the ValidatesRunner suites anyhow, because we do not scan these test jars. …

Remove extraneous/incorrect ValidatesRunner classification from examples unit tests

---

.github/workflows/beam_PreCommit_Java.yml

this avoids breakage from Java dependency upgrade gets in, follow up of #33028 …

Add buildSrc to trigger path of Java PreCommit

---

sdks/python/apache_beam/ml/inference/vllm_inference.py

This approach should work if `python` doesn't resolve to an interpreter (e.g. it's python3 on ubuntu distros) 
[![Build …

Use sys.executable to find python command.

---

examples/notebooks/beam-ml/run_inference_vllm.ipynb

Its usually better to suggest a custom tag to avoid overwriting containers from old jobs …

Don't pin to latest tag

---

sdks/python/apache_beam/yaml/generate_yaml_docs.py
sdks/python/apache_beam/yaml/yaml_mapping.py

This PR normalizes all instances of `error_handling` as a parameter in the API catalog to use the same config/description.
Before this, there were different typings being used for various transforms, and the Java implementation could get out-of-sync despite the functionality being the same.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/. …

[yaml] Normalize error_handling docs on API catalog

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerWriteSchemaTransformProvider.java
sdks/python/apache_beam/yaml/standard_io.yaml

This PR adds a couple parameters to the ReadFromSpanner transform and specifies more robust usage docs. …

[yaml] SpannerIO docs and minor improvments

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/MoreFutures.java

This is clearer how it interacts with ForkJoinPool execution as there are not separate completion stages.
I was unable to reproduce observed stuckness in pipeline where runAsync scheduled tasks appear not to have completed on forkjoinpool and the pool workers appears idle. I am wondering if this could be a possible cause because with the existing code, the futures on the fork join pool are not being directly joined and thus perhaps not explicilty tied to the async work. This may affect if the tasks not being pushed into execution.  The common pool used is not in asyncMode and ForkJoinExecutor indicates it is safer for non-joining use if asyncMode is set.
Fix #29926 …

Simplify MoreFutures.supplyAsync and MoreFutures.runAsync using a wrapper instead of chained stages and multiple completions.

---

sdks/java/core/build.gradle

Fix antlr analyzeClassesDependencies

---

sdks/python/apache_beam/io/gcp/pubsub.py

Improved test pipeline reading/publishing cloud pubsub messages throughput by 10%
Profile:
Separately I am going to see if allowing the next dofn to just process proto PubsubMessage avoids this expense. …

Optimize proto PubsubMessage to/from conversion to beam PubsubMessage

---

sdks/java/core/src/main/java/org/apache/beam/sdk/fn/stream/DataStreams.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateFetchingIterators.java

- remove reference to completed encoded input page from decoder once we have read it.
- re-read from cache after loading the next page to give eviction a chance to remove blocks …

Changes to reduce memory pinned while iterating through state backed iterable

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFnTest.java

instead of looking at all topics. This limits how much data we query for, and avoids access denied errors when a user queries for a topic they don't have permissions to …

Change dead partition detection to only look at the current topic

---

.github/REVIEWERS.yml

Add Kafka tag to review bot

---

sdks/java/io/jdbc/build.gradle
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcUtil.java
sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOTest.java
sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcUtilTest.java

* Report table the pipeline read from and write to …

Lineage support for JdbcIO

---

sdks/python/apache_beam/dataframe/convert.py
sdks/python/apache_beam/dataframe/doctests.py
sdks/python/apache_beam/dataframe/expressions.py
sdks/python/apache_beam/dataframe/frame_base.py
sdks/python/apache_beam/dataframe/frames.py
sdks/python/apache_beam/dataframe/frames_test.py
sdks/python/apache_beam/dataframe/pandas_top_level_functions.py
sdks/python/apache_beam/dataframe/partitionings.py
sdks/python/apache_beam/dataframe/schemas.py
sdks/python/apache_beam/dataframe/transforms.py

Updates the dataframes API to PEP 585 typing, also modernizes some of the type hints.
Part of #32969  …

Update dataframes to PEP 585 typing

---

.github/trigger_files/beam_PostCommit_Java_Avro_Versions.json
sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java

https://github.com/apache/beam/pull/32081#discussion_r1841033733 seems to have broken AvroUtils for Avro 1.8.2 - for example: https://github.com/apache/beam/actions/runs/11820539714
This fixes the problem by undoing that section of the pull request.
GitHub …

Make AvroUtils compatible with older versions of Avro

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java

Add logging to see which topic each split is reading from, and update per worker polling metrics accordingly.
[![Build …

Add logging to see which topic each split is reading from

---

sdks/python/apache_beam/yaml/standard_io.yaml

Cherry-pick this since it makes jdbc providers unusable …

CP: fix JDBC providers (#32985)

---

CHANGES.md

This is where new features/fixes should now go …

Add 2.62.0 to changes

---

contributor-docs/release-guide.md

Fix small typos in release email

---

examples/notebooks/beam-ml/run_inference_vllm.ipynb

Fix vllm typo

---

.github/trigger_files/beam_PostCommit_TransformService_Direct.json
sdks/java/transform-service/build.gradle

Disable cache for failing post commit test. …

Disable gradle cache for transform service shadowJar

---

runners/flink/src/test/resources/flink-conf.yaml
sdks/python/test-suites/portable/common.gradle

Fixes #32794. Following https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/memory/mem_setup_tm/#detailed-memory-model, optimize runners/flink/src/test/resources/flink-conf.yaml and switch to this conf for the flink tests.
Tested locally for both Python 3.12 and 3.9:
```bash
./gradlew :sdks:python:test-suites:portable:py39:flinkExamples --max-workers=8 --continue \                      fix-flink-test 
-Dorg.gradle.jvmargs=-Xms2g -Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.vfs.watch=false -Pdocker-pull-licenses \
-PpythonVersion=3.12
``` …

Fix the broken flink tests by optimizing conf

---

.github/workflows/beam_PostCommit_Python_Examples_Flink.yml

Fixes #32794
Check https://github.com/apache/beam/issues/32794#issuecomment-2481370497 …

Use highmem for beam_PostCommit_Python_Examples_Flink.yml

---

sdks/java/core/src/main/java/org/apache/beam/sdk/Pipeline.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/CoderRegistry.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaRegistryTest.java

mitigates #33132
Reverts apache/beam#32705

Revert "fix schema inference inside parameterized types"

---

website/www/site/content/en/get-started/from-spark.md

docs: missing word

---

scripts/ci/pr-bot/findPrsNeedingAttention.ts
scripts/ci/pr-bot/processNewPrs.ts
scripts/ci/pr-bot/shared/reviewersForLabel.ts

Right now, if we can't find a committer for a label we fail. This makes this more robust. …

Use fallback reviewers for bot

---

sdks/python/apache_beam/ml/transforms/base_test.py

* Use random gcs bucket name
* Linter fixes …

CP: Use random gcs bucket name (#33151)

---

website/www/site/content/en/case-studies/yelp_streaming.md

updated the yelp blog

---

examples/notebooks/beam-ml/automatic_model_refresh.ipynb

Without this change, this notebook fails because of mismatched keras versions. We should more aggressively pin dependencies to avoid this mismatch …

Pin notebook dependencies

---

.github/workflows/republish_released_docker_containers.yml

This is step 1 in allowing us to publish updated containers as needed
Part of #33166 …

Create workflow for republishing released containers

---

sdks/python/apache_beam/typehints/schemas.py

When performing schema translation from runner_api, if the root type is a Beam Row, and the Row contains subfields of Beam Rows, the subfield descriptions are not propagated during translation.
This PR propagates the descriptions to the output RowTypeConstraint. …

propogate descriptions for nested Beam Rows during schema translation

---

sdks/python/tox.ini

use the tight range for dask

---

runners/flink/job-server-container/Dockerfile
website/www/site/content/en/documentation/runners/flink.md

Revert "Fixed the broken beam python on flink with PortableRunner"

---

website/www/site/content/en/documentation/runners/flink.md

Fixes #33061. We do not need to change the docker entrypoint. …

Fix the flink runner doc

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

Upgrade GCP-BOM to 26.49.0

---

.test-infra/dataproc/flink_cluster.sh

From https://github.com/apache/beam/issues/30507#issuecomment-2494385957, try to use the default machine types for Flink with slightly more memory. …

Remove the default machine types

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/ReadOperation.java

even though this is not a frequent log spam, it was unintended to get in at the first place …

Remove leftover print statement in SpannerIO

---

sdks/python/apache_beam/yaml/yaml_mapping.py

More complete error message for StripErrorMetadata.

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.61.0.md
website/www/site/content/en/get-started/downloads.md

Part of https://github.com/apache/beam/blob/master/contributor-docs/release-guide.md#merge-website-pull-requests …

Update website for 2.61.0 release

---

.github/workflows/beam_PreCommit_Flink_Container.yml
.github/workflows/flink-tests-pipeline-options/go_Combine_Flink_Batch_small.txt
.github/workflows/flink-tests-pipeline-options/java_Combine_Flink_Batch_small.txt
.github/workflows/flink-tests-pipeline-options/python_Combine_Flink_Batch_small.txt

Green now: https://github.com/apache/beam/actions/runs/12023228294/job/33516778889 …

Fixed beam_PreCommit_Flink_Container.yml

---

.github/trigger_files/beam_PostCommit_Python_ValidatesDistrolessContainer_Dataflow.json
.github/workflows/beam_PostCommit_Python_ValidatesDistrolessContainer_Dataflow.yml

This PR closes #33003, adding scheduled checks for Python SDK (non ML) distroless variants via GitHub workflows. …

Add beam_PostCommit_Python_ValidatesDistrolessContainer_Dataflow

---

sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_unit_test.py

Addresses https://github.com/apache/beam/issues/32333 …

Better error messaging for chain-type pipelines

---

.github/trigger_files/beam_PostCommit_Python_ValidatesDistrolessContainer_Dataflow.json
.github/workflows/beam_PostCommit_Python_ValidatesDistrolessContainer_Dataflow.yml

Push directly to branch as per https://github.com/apache/beam/tree/master/.github/workflows#testing-workflow-updates …

Fix python distroless workflow

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
.github/workflows/IO_Iceberg_Integration_Tests.yml
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOIT.java

Cleanup Iceberg test files

---

examples/notebooks/beam-ml/run_inference_vllm.ipynb

Remove dupe metadata

---

sdks/python/apache_beam/typehints/decorators.py
sdks/python/apache_beam/typehints/decorators_test.py
sdks/python/apache_beam/typehints/native_type_compatibility.py
sdks/python/apache_beam/typehints/native_type_compatibility_test.py
sdks/python/apache_beam/typehints/opcodes.py
sdks/python/apache_beam/typehints/typed_pipeline_test.py
sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

Typehinting infrastructure and tests have a number of logical branches based on the current running python version so we can support features that are present in some officially supported python versions but not in others. The typehint module contained some conditional branches looking for versions before 3.9, which is now the minimum, so this PR cleans up that dead code and branch conditions that were always true. …

Remove unnecessary branches on Python version in typehint code

---

.github/workflows/republish_released_docker_containers.yml

Update republish workflow with latest beam

---

sdks/python/apache_beam/yaml/yaml_join.py

Fixes #33272
This should now allow `Join` to be used (and validate) against incoming Rows using BeamSchema and Row schema …

[yaml] Fix YAML join with upstream ReadFromPubSub

---

sdks/python/apache_beam/yaml/yaml_transform.py

Small string fix for error message

---

website/www/site/content/en/documentation/sdks/yaml.md

[YAML] Document jinja templatization features.

---

.github/trigger_files/beam_PostCommit_Python.json
sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai.py

This ports the same kind of throttling we have in https://github.com/apache/beam/blob/160ffd53ce0f5ac2b91f917abba42dda635841d9/sdks/python/apache_beam/ml/inference/vertex_ai_inference.py to our embedding transform …

Add throttling metrics and retries to vertex embeddings

---

sdks/python/apache_beam/metrics/cells.py

#33196 seemed to break Python build after re-generating cython files due to an incorrect return type hint in the new `BoundedTrieData` metric type …

fix BoundedTrieData get_result return type hint

---

.github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink.yml

See https://pantheon.corp.google.com/functions/details/us-central1/github_workflow_prefetcher where we start crashing 5 days ago:
and logs indicate the issue:
Introduced in #33353. Probably we should have a yaml linter to catch little stuff like this.
GitHub …

Fix duplicate yml entry causing test result dashboard sync to fail

---

.github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink_Java8.yml

Fix yaml error in Flink Java8 ValidatesRunner

---

CHANGES.md
sdks/python/apache_beam/yaml/main_test.py
sdks/python/apache_beam/yaml/yaml_transform.py

This will make it much easier for users to create templates that output to timestamped directories and such.
[![Build …

[YAML] Make datetime available for jinja templatization.

---

website/www/site/content/en/documentation/sdks/yaml.md

[YAML] Document the yaml provider include syntax.

---

sdks/python/apache_beam/metrics/cells.pxd
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/execution.py
sdks/python/apache_beam/metrics/metric.py
sdks/python/apache_beam/metrics/metricbase.py
sdks/python/apache_beam/metrics/monitoring_infos.py
sdks/python/apache_beam/runners/direct/direct_metrics.py
sdks/python/apache_beam/runners/direct/direct_runner_test.py
sdks/python/apache_beam/runners/portability/flink_runner_test.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner.py
sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/portable_metrics.py
sdks/python/apache_beam/runners/portability/portable_runner.py
sdks/python/apache_beam/runners/portability/prism_runner_test.py

This should finish the Python implementation.  …

End to end BoundedTrie metrics through worker and runner APIs.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java

Committing consumer offsets to Kafka is not critical for KafkaIO because it relies on the offsets stored in KafkaCheckpointMark, but throwing an exception makes Dataflow retry the same work item unnecessarily.

KafkaIO: Do no throw exceptions if commitSync fails in KafkaUnboundedReader.

---

contributor-docs/code-change-guide.md

To improve build times and reduce load on the snapshot server …

In contributor docs, don't try to download releases from snapshot repo

---

start-build-env.sh

#33400 fix error on start-build-env.sh

fix error on start-build-env.sh

---

CHANGES.md

And tidied the 2.62.0 section. TBD if things need to be added. …

Add 2.63.0 section to CHANGES.md

---

sdks/python/apache_beam/yaml/yaml_provider.py

LogForTesting will fail with a JSON serialization error for fields that are of type `bytes` (since JSON has no such concept), so transforms like ReadFromPubSub (using RAW format) will fail. This refactor will print the bytes as-is to help with debuggability without the use of an intermediate MapToFields (which may not be obvious if the user does not know the upstream transform insert a bytes field into the output Row). …

[yaml] allow logging bytes in LogForTesting

---

website/www/site/content/en/documentation/sdks/python-custom-multi-language-pipelines-guide.md

Part of #33358
Adding a new page to the Beam site

[docs] Add new Python SchemaTransform multi-lang guide

---

.github/workflows/typescript_tests.yml

This PR closes #33344 removing reference to static credentials. Additionally, makes certain tests conditional per TODO comment referencing https://github.com/apache/beam/issues/33346.
See https://github.com/apache/beam/actions/runs/12521462042 for outcome of running this PR's branch.
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-in …

Clean up Typescript Tests workflow

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/Convert.java

The documentation for `Convert.fromRows` was not consistent. The output generic type in one of the methods was `Row` making the conversion from `Row` to `Row` which seems incorrect. It should be from `Row` to `OutputT`. …

Fix typo of output type in the docs.

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/build.gradle

Fix iceberg ITs

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

After https://github.com/apache/beam/pull/33456 these are no longer used.
Fixes #33430 …

Remove aws v1 dependencies

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryFileLoadsSchemaTransformProvider.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/PortableBigQueryDestinations.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java

Cherrypicking #33392 into release 2.62.0

[Cherrypick] Managed BigQuery use file loads with Avro format for better performance

---

.gitignore
local-env-setup.sh

fix error on https://github.com/apache/beam/issues/33460

fix error on local-env-setup.sh

---

.github/workflows/beam_Publish_Java_SDK_Distroless_Snapshots.yml

This PR addresses #33201 staging a GitHub workflow that aims to publish to a staging registry at gcr.io/apache-beam-testing as with the non-distroless variants. Currently nothing happens with this workflow as it needs to be merged before testing with self-hosted runners. …

Stage beam_Publish_Java_SDK_Distroless_Snapshots.yml

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update BEAM_DEV_SDK_CONTAINER_TAG for deps update.

---

sdks/python/apache_beam/yaml/yaml_provider.py

Better error message on incorrect package listing.

---

.github/workflows/beam_Publish_Java_SDK_Distroless_Snapshots.yml

This PR closes #33201 via building and pushing snapshots to apache-beam-testing artifact registry. …

[Distroless] Publish Java SDK distroless variants

---

sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/cells_test.py

Cherry-pick https://github.com/apache/beam/pull/33483 to release 2.62.0. …

Fix bounded trie merge when merging on empty trie

---

.github/workflows/republish_released_docker_containers.yml

This workflow was failing because it doesn't auto-pick up the defaults if triggered via schedule, it only uses the defaults for workflow dispatch. This meant the release/rc variables weren't getting set.
This fixes the problem and gets checkout running correctly ([example](https://github.com/apache/beam/actions/runs/12634416515/job/35202103064)). There is a good chance the workflow will still fail because all of our docker tasks are currently flaky due to https://github.com/apache/beam/issues/33425 but the core workflow logic should be good …

Fix republish docker branch

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/OutputTooLargeException.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/KeyCommitTooLargeException.java

Adds references to KeyCommitTooLargeException docs whenever we throw the exception and also mentions `--experiments=throw_exceptions_on_large_output` as an option. …

Adds references to KeyCommitTooLargeException docs 

---

website/www/site/content/en/documentation/io/connectors.md

Documents the connectors supported via the Managed API

---

.github/workflows/build_wheels.yml

This is needed to avoid failures like https://github.com/apache/beam/actions/runs/12692477655
References:
- #33505 
- #33506  …

Cherry-pick #33505 to 2.62.0 release branch (Build wheels on gha runners instead of local runners)

---

.asf.yaml

Our triage permissions are outdated with people who are either already committers or are no longer as active in the project. This updates to a more reasonable set of people who are planning on being actively engaged. …

Give some folks triage permissions

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
CHANGES.md
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOIT.java

Cherrypick Iceberg partition value race condition

---

sdks/java/container/boot.go

Dataflow legacy worker job supports `--dataflowWorkerJar` pipeline option essentially adding a custom worker jar to the staged files. Actually the same logic (partly) exists in java SDK harness (#6665), but is long broken due to change of artifact names, etc. This change adds it back.
To use it, add custom java SDK harness to runtime class path of your project:
```
runtimeOnly(group: 'org.apache.beam', name: 'beam-sdks-java-harness', version: "$beam_version")
```
then run the pipeline with experiments `--experiments=use_runner_v2,use_staged_dataflow_worker_jar`
example job id: `2025-01-06_12_05_52-7194427615925076100`
confirmed that it shows a log
```
DEBUG 2025-01-06T20:07:45.090268040Z Using staged java harness: beam-sdks-java-harness-2.63.0-SNAPSHOT-Ni9ph3nD4RLvDXNe63bjaKTCqOIHFVnCientE …
```

Support use staged harness for Dataflow runner v2 job

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

Fix #33498
This make sure the if clause called once per table, no matter Lineage is reported or not
Fix issues …

Fix log spam when using a JdbcIO DataSource not support Lineage report

---

sdks/python/apache_beam/yaml/yaml_provider.py

Fix yaml environment cloning for dev branches.

---

sdks/python/apache_beam/metrics/metric.py

This avoids any potential complexities with mixing old and new metrics with the same name but different types (e.g. after a streaming update across an sdk upgrade). …

Place bounded lineage metrics under a new name.

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Actions status badges were broken in both the README and the pull request template, this updates those following [GH documentation](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge) …

Fix GitHub Actions workflow status badges

---

CHANGES.md

Update CHANGES with some Prism and Go SDK notes.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

Update to the most recent GCP Bom for the next release …

Update gcp bom to 26.52.0

---

.github/workflows/beam_PerformanceTests_xlang_KafkaIO_Python.yml
.github/workflows/performance-tests-pipeline-options/xlang_KafkaIO_Python.txt

Fixes #30526 
Successful run: https://github.com/Amar3tto/beam/actions/runs/12792091566/job/35661728120.
[![Build …

Fix PerformanceTests xlang KafkaIO Python job

---

sdks/python/apache_beam/transforms/stats.py

The stats.py type hinting changes were interacting weirdly with cython, reverting while investigating any further steps to update the type hints in cythonized code. …

Revert typing changes to stats.py

---

sdks/python/apache_beam/yaml/integration_tests.py

There are many of these, and this needlessly explodes the number of tests that are created when adding debugging. …

Don't multiply tests on LogForTesting providers.

---

.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Flink.json
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSource.java
runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplitEnumerator.java
runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/FlinkSourceSplitEnumeratorTest.java

[flink] FlinkRunner initializes the same split twice (#31313)

---

CHANGES.md
website/www/site/content/en/blog/beam-2.61.0.md

Addresses #33639 for Beam 2.61.0 and 2.62.0 …

Added the numpy issues to CHANGES.md

---

.github/workflows/finalize_release.yml

Following the suggestion in the output at https://github.com/apache/beam/actions/runs/12889303815/job/35936182411 (which seems correct) and https://stackoverflow.com/questions/53578341/git-tag-another-tag …

Adjust finalize_release workflow for new git tag syntax/semantics

---

.github/workflows/finalize_release.yml

Failure at https://github.com/apache/beam/actions/runs/12889690303/job/35937516496
Confirmed locally that it fails without this change and succeeds with it. (the failure is new due to changes to robots.txt) …

Ignore robots.txt when finalizing release

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.62.0.md
website/www/site/content/en/get-started/downloads.md

Following https://github.com/apache/beam/blob/master/contributor-docs/release-guide.md#propose-pull-requests-for-website-updates …

Blog post and site update for Release 2.62.0

---

sdks/python/apache_beam/yaml/main.py
sdks/python/apache_beam/yaml/yaml_io.py
sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_provider_unit_test.py
sdks/python/apache_beam/yaml/yaml_transform.py

Currently all references must be absolute (or are resolved relative to the cwd). This change allows one to more easily list transform providers along with their dependencies (e.g. jar jars or local pypi packages) regardless of how they're referenced.
GitHub …

Support relative paths for yaml includes and resources.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

`python3 scripts/tools/bomupgrader.py 26.53.0` logs
```
INFO:root:-----Read BeamModulePlugin-----
INFO:root:-----check dependency defs in BeamModulePlugin-----
INFO:root:-----prepare build.gradle for example project-----
INFO:root:-----resolve dependency-----
INFO:root:-----Update BeamModulePlugin-----
INFO:root:Changed com.google.api:gax: 2.59.0 -> 2.59.1
INFO:root:Changed com.google.cloud:google-cloud-spanner: 6.83.0 -> 6.85.0
INFO:root:Unchanged: io.grpc:grpc-netty:1.69.0
INFO:root:Unchanged: io.netty:netty-transport:4.1.110.Final
INFO:root:Changed com.google.protobuf:protobuf-java: 4.28.3 -> 4.29.0
INFO:root:Unchanged: org.apache.arrow:arrow-memory-core:15.0.2
INFO:root:Changed com.google.apis:google-api-services-bigquery: v2-rev20241115-2.0.0 -> v2-rev20241222-2.0.0 …
```

Upgrade gcp-bom to 26.53.0

---

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml
runners/google-cloud-dataflow-java/build.gradle
sdks/java/container/distroless/common.gradle

This PR addresses https://github.com/apache/beam/issues/33425 distroless related broken Jobs in the Publish Beam SDK Snapshots workflow.
See the following for successful runs of this PR's branch:
- https://github.com/apache/beam/actions/runs/12895179954/job/35955530767
- https://github.com/apache/beam/actions/runs/12895179954/job/35955531080
What remains broken is the Jobs related to `java:container:*` tasks unrelated to Distroless.
To check …

Fix distroless related Publish Beam SDK Snapshots

---

sdks/go/pkg/beam/core/runtime/graphx/translate.go

* Protos encoded as JSON should be unmarshaled with protojson, and not encoding/json …

[Go] Use protojson instead.

---

sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_provider_unit_test.py
sdks/python/apache_beam/yaml/yaml_transform.py

Transforms defined in a provider in YAML are now expanded in context, which means in particular that they can reference other transforms (including themselves) that have been exported. …

More complete YAML provider implementation.

---

sdks/java/testing/expansion-service/build.gradle

Follow up #33472. This testing expansion service isn't build like other expansion service, instead via a custom target, and missed by the previous fix …

Add multi-release to testing expansion service

---

website/www/site/content/en/documentation/sdks/yaml-providers.md

[YAML] Add documentation of YAML-defined YAML-providers to the site.

---

.github/workflows/beam_LoadTests_Go_GBK_Flink_Batch.yml
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_100b.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_100kb.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_10b.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_Fanout_4.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_Fanout_8.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_Reiteration_10KB.txt

Fixes #30507
Successful run: https://github.com/Amar3tto/beam/actions/runs/12888086073/job/35932163827
Issue for investigation the root cause: https://github.com/apache/beam/issues/33753. …

Fix LoadTests Go GBK Flink Batch job

---

.github/workflows/beam_LoadTests_Go_Combine_Flink_Batch.yml
.github/workflows/load-tests-pipeline-options/go_Combine_Flink_Batch_10b.txt
.github/workflows/load-tests-pipeline-options/go_Combine_Flink_Batch_Fanout_4.txt
.github/workflows/load-tests-pipeline-options/go_Combine_Flink_Batch_Fanout_8.txt

Reduced the num_records for now, we'll investigate the root cause further. 
[Issue #30521](https://github.com/apache/beam/issues/30521)
Successful run example: https://github.com/akashorabek/beam/actions/runs/12955019632
Issue for investigation the root cause: https://github.com/apache/beam/issues/33753. …

Fix go combine flink batch workflow

---

sdks/python/apache_beam/yaml/yaml_provider.py

We assume urls, remote paths, and pypi identifiers are immutable, but don't want to re-use the cache if a local package (say, one under development) has changed.  …

[YAML] Use hash rather than path when keying on local packages.

---

.github/workflows/beam_LoadTests_Go_SideInput_Flink_Batch.yml
.github/workflows/load-tests-pipeline-options/go_SideInput_Flink_Batch_First_Iterable.txt
.github/workflows/load-tests-pipeline-options/go_SideInput_Flink_Batch_Iterable.txt

Reduced the num_records for now, we'll investigate the root cause further. 
[Issue #30515](https://github.com/apache/beam/issues/30515)
Successful run example: https://github.com/akashorabek/beam/actions/runs/12952845936
Issue for investigation the root cause: https://github.com/apache/beam/issues/33753. …

Fix go sideinput flink batch load test workflow

---

sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java
sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CallTest.java

See failure here
https://github.com/apache/beam/runs/36238793957 …

Increase timeouts in CallTest to reduce flakiness

---

release/src/main/groovy/MobileGamingCommands.groovy

Fix PostRelease Nightly Snapshot job

---

sdks/python/apache_beam/examples/complete/distribopt.py
sdks/python/apache_beam/examples/complete/distribopt_test.py

Fixes #33764, #33765
Successful runs: [Spark](https://github.com/Amar3tto/beam/actions/runs/13013437171), [Direct](https://github.com/Amar3tto/beam/actions/runs/13013435910) …

Fix PostCommit Python Examples Spark/Direct jobs

---

examples/notebooks/beam-ml/run_inference_huggingface.ipynb

This is one of the more useful pieces of runinference, especially with HuggingFace - its really easy to swap in different models …

document how to swap in another model like deepseek

---

.github/workflows/build_wheels.yml

Fixes: [#31882](https://github.com/apache/beam/issues/31882)
Changed github actions runner to `ubuntu-22.04` since building-wheels on `ubuntu:latest`(24.04) for `aarch64` was failing with `segmentation fault` error
Successful job example: https://github.com/akashorabek/beam/actions/runs/13044714282 …

Fix build-wheels python workflow

---

sdks/java/io/mqtt/src/test/java/org/apache/beam/sdk/io/mqtt/MqttIOTest.java
sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/CallTest.java

Fixes: #33793
Successful run: https://github.com/Amar3tto/beam/actions/runs/13050234843 …

Fix PreCommit Java IOs Direct job

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContextTest.java

Fix test
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.y …

Fix failing extractMetricUpdatesStringSet

---

contributor-docs/discussion-docs/2025.md

Added 2025.md to track Beam docs

---

sdks/python/container/run_validatescontainer.sh

Fixes: https://github.com/apache/beam/issues/30525
Successful run example: https://github.com/akashorabek/beam/actions/runs/13109887220 …

Fix The PostCommit Python ValidatesContainer Dataflow With RC workflow

---

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml

Fixes: [#32161](https://github.com/apache/beam/issues/32161)
Temporarily changed to `ubuntu-22.04` since `building-wheels` step fails on `ubuntu:latest (24.04)`. 
Successful run example: https://github.com/akashorabek/beam/actions/runs/13106224215
GitHub Actions …

Fix Publish Beam SDK Snapshots workflow

---

learning/katas/java/Core Transforms/FlattenWith/FlattenWith/src/org/apache/beam/learning/katas/coretransforms/flattenWith/Task.java
learning/katas/java/Core Transforms/Tee/Tee/src/org/apache/beam/learning/katas/coretransforms/tee/Task.java
learning/katas/python/Core Transforms/FlattenWith/FlattenWith/task.py
learning/katas/python/Core Transforms/Tee/Tee/task.py
playground/categories.yaml

Fixes #30612
Successful run: https://github.com/Amar3tto/beam/actions/runs/13114541498 …

Fix Playground CI Nightly job

---

runners/prism/java/build.gradle

Disable the BoundedTrie tests for the Prism suite until they're implemented in prism side. …

[Prism] Disable trie tests.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

Update dataflow client version. This is needed for the new metric type bounded Trie to be available in Beam. 
The Metric/Counter proto which has bounded trie is up here https://dataflow.googleapis.com/$discovery/rest?version=v1b3
I took the version referencing: 
- [google-api-client](https://mvnrepository.com/artifact/com.google.api-client/google-api-client)
- [google-api-services-dataflow](https://central.sonatype.com/artifact/com.google.apis/google-api-services-dataflow/overview)
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTI …

Update Dataflow api client version

---

runners/google-cloud-dataflow-java/build.gradle

* To include vendor grpc upgrade …

Bump beam-master container version

---

CHANGES.md
website/www/site/content/en/contribute/_index.md

Fix user mailing list link on contribution page

---

.github/workflows/cut_release_branch.yml

Moving to 2.XX versioning for branches broke the regex input validation for cut_release_branch, this updates it.  …

Fix cut_release_branch workflow

---

runners/google-cloud-dataflow-java/build.gradle

This got messed up as part of a bad workflow change …

Fix release version

---

CHANGES.md

Add a CHANGES.md section for the 2.64.0 release now that the 2.63.0 branch has been cut …

Update CHANGES.md to include the 2.64.0 release

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/go/run_with_go_version.sh

Update the Go version for artifact building to the latest release (Go 1.23.6)
See https://go.dev/dl/ for the latest go releases. …

Update build Go version to 1.23.6

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/go/run_with_go_version.sh

See #33876 for details. Cherry pick of the same. …

Cherry pick #33876 - update Go version to 1.23.6

---

.github/workflows/choose_rc_commit.yml

I couldn't think of a cleaner way to specify this since github's expressions are fairly limited  …

Force specifying release branch

---

.github/workflows/build_release_candidate.yml

Build docker artifacts from self-hosted runners

---

runners/portability/java/build.gradle

Fixes #33859
Successful run: https://github.com/Amar3tto/beam/actions/runs/13177148731 …

Fix PostCommit Java ValidatesRunner ULR job

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/BoundedTrieCell.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/BoundedTrieData.java
runners/core-java/src/test/java/org/apache/beam/runners/core/metrics/BoundedTrieNodeTest.java
runners/google-cloud-dataflow-java/build.gradle
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowMetrics.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/DataflowMetricsTest.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContext.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/MetricsToCounterUpdateConverter.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainer.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/BatchModeExecutionContextTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/MetricsToCounterUpdateConverterTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/StreamingStepMetricsContainerTest.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java

Cherry-pick https://github.com/apache/beam/pull/33474 to release 2.63 …

Cherry pick Add support for bounded trie metric in legacy worker

---

website/www/site/content/en/documentation/sdks/yaml-providers.md

Expand yaml provider documentation.

---

.github/workflows/reportGenerator.yml
scripts/ci/issue-report/generateReport.js

Reduce frequency of issue report

---

.github/workflows/beam_LoadTests_Go_CoGBK_Flink_batch.yml
.github/workflows/beam_LoadTests_Go_GBK_Flink_Batch.yml
.github/workflows/load-tests-pipeline-options/go_CoGBK_Flink_Batch_Reiteration_10KB.txt
.github/workflows/load-tests-pipeline-options/go_CoGBK_Flink_Batch_Reiteration_2MB.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_100b.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_100kb.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_Fanout_4.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_Fanout_8.txt
.github/workflows/load-tests-pipeline-options/go_GBK_Flink_Batch_Reiteration_10KB.txt

Fixes #30502, Fixes #30507
Issue for investigation the root cause: https://github.com/apache/beam/issues/33753. …

Fix LoadTests Go CoGBK / GBK Flink Batch jobs

---

.test-infra/metrics/sync/github/github_runs_prefetcher/code/main.py

As discussed, we decided to change the period to 30 days as this will help us identify issues faster. …

Change the period for checking if the workflow is flaky

---

.github/ACTIONS.md
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/failing_test.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/workflows/self-assign.yml
CONTRIBUTING.md
website/www/site/content/en/contribute/_index.md

#33925 - Adds unassign issue feature. …

Add unassign issue feature

---

website/www/site/content/en/community/contact-us.md

Fix unsubscribe emails on Contact Us page

---

sdks/python/apache_beam/testing/benchmarks/README.md

The Action definition had some missing information that had been clobbered somehow, this restores it to a correct definition …

Fix error in Dataflow Cost Benchmark README

---

.github/workflows/typescript_tests.yml

Fixes #30506
Do not run Typescript tests on windows-server-2019, because it is outdated type of runner, which is currently not available.
Successful run: https://github.com/Amar3tto/beam/actions/runs/13263552344 …

Fix TypeScript Tests job

---

sdks/python/apache_beam/io/aws/s3filesystem.py
sdks/python/apache_beam/io/aws/s3filesystem_test.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem.py
sdks/python/apache_beam/io/azure/blobstoragefilesystem_test.py
sdks/python/apache_beam/io/filebasedsink.py
sdks/python/apache_beam/io/filebasedsource.py
sdks/python/apache_beam/io/filesystem.py
sdks/python/apache_beam/io/filesystems.py
sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/gcsfilesystem.py
sdks/python/apache_beam/io/gcp/gcsfilesystem_test.py
sdks/python/apache_beam/io/localfilesystem.py
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/metrics/metric.py
sdks/python/apache_beam/metrics/metric_test.py

Reverts emitting lineage as boundedtrie from python in 2.63 release. It will be a part of 2.64 release instead:
Reverts: 
- https://github.com/apache/beam/pull/33482
- https://github.com/apache/beam/pull/33381 …

Revert emitting lineage as boundedtrie from python

---

sdks/python/apache_beam/transforms/periodicsequence.py

This is very unclear right now …

Improve docstring for fire_interval

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtilsTest.java

Cherry picking 33919

---

CHANGES.md

Update CHANGES.md for lineage

---

.github/workflows/beam_PreCommit_Flink_Container.yml

This test leaks Dataproc VM instance, causing GCP project drains quota.
It also does not test the PR change as it runs on snapshot images e.g. gcr.io/apache-beam-testing/beam-sdk/beam_go_sdk:latest gcr.io/apache-beam-testing/beam_portability/beam_flink1.17_job_server:latest (#33942)
Until both issues are resolved, we have to disable this test to avoid continued outage of testing infrastructure.
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job …

Disable PreCommit Flink Container

---

sdks/go/pkg/beam/core/runtime/exec/fullvalue_test.go

In this PR, we mainly replace `reflect.DeepEqual` with the `cmp` package  for comparisons in [`fullvalue_test.go`](https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/core/runtime/exec/fullvalue_test.go) test file. The `cmp` package provides a more powerful and safer alternative for value equality checks.  
Closes #20154.  
As stated in the upstream issue and the [cmp documentation](https://pkg.go.dev/github.com/google/go-cmp/cmp):  
> _Package cmp determines equality of values._  
> _This package is intended to be a more powerful and safer alternative to reflect.DeepEqual for comparing whether two values are semantically equal._  
~The upsteram issue specifically mentioned [`fullvalue_test.go`](https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/core/runtime/exec/fullvalue …

sdks/go: utilize `cmp` package for comparison in `fullvalue_test.go`

---

runners/google-cloud-dataflow-java/build.gradle
sdks/java/container/distroless/common.gradle

Addresses: [#33646](https://github.com/apache/beam/issues/33646)
Successful run example: https://github.com/akashorabek/beam/actions/runs/13285259426 …

Fix Postcommit Java Examples Dataflow V2 workflow

---

runners/jet/src/main/java/org/apache/beam/runners/jet/metrics/JetMetricsContainer.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java

Fix timestamp propagation to successful-loads PCollection.

---

.github/workflows/republish_released_docker_containers.yml
sdks/java/container/license_scripts/pull_licenses_java.py

Addresses: [#33834](https://github.com/apache/beam/issues/33834)
Successful run example: https://github.com/akashorabek/beam/actions/runs/13295526587 …

Fix Republish Released Docker Images workflow

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpersTest.java

Fixes https://github.com/apache/beam/issues/33920. …

sdks/java: support non-ascii BigQuery table name 

---

.github/workflows/self-assign.yml

Fixes #33934
Successful run: https://github.com/Amar3tto/beam/actions/runs/13323593706/job/37212479670
Reason: Errors in async functions don’t trigger synchronous try-catch. …

Fix Assign or close an issue job

---

CHANGES.md
website/www/site/content/en/blog/beam-2.59.0.md
website/www/site/content/en/blog/beam-2.60.0.md
website/www/site/content/en/blog/beam-2.61.0.md
website/www/site/content/en/blog/beam-2.62.0.md

Add Lineage known issues for Beam 2.59.0; update blog post

---

runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/environment/DockerEnvironmentFactory.java

log the docker cmd to help debug

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java

Multiple assignments can be racily collapsed causing the verification to block. …

Fix race in FanOutStreamingEngineWorkerHarnessTest

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDirectGetWorkStreamTest.java

Fix GrpcDirectGetDataStreamTest waiting for 2 responses instead of the 3 present.

---

.github/workflows/finalize_release.yml

The message currently doesn't match the commit - https://github.com/apache/beam/commit/bc7c0d520faf4e45bcf9bbc4b8fbaa8280b50590 …

Fix commit message in finalize workflow

---

runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto

R: @scwhittle 
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wh …

add endpoint type to WorkerMetadataResponse proto

---

sdks/go/pkg/beam/util/starcgenx/starcgenx.go

Adds a missing line when handling alias types. It's important to also register types and imports even if that type is an alias, so, the generated files won't drop the types. Necessary for support on Go 1.24+, when the `register` package isn't being used.
GitHub …

[Go SDK] Add missing type inspection case for Alias types.

---

.asf.yaml

This will allow triaging of issues - Claude and Shunping are regularly involved in the repo and this will make life a little easier for them. …

Give some more folks triage permissions

---

sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_provider_unit_test.py

Avoid missing hashlib.file_digest for Python < 3.11.

---

sdks/python/apache_beam/ml/rag/ingestion/alloydb.py

Pass extra write args from AlloyDB writer to WriteToJdbc.

---

contributor-docs/java-dependency-upgrades.md

Add info on protobuf dependency

---

.github/workflows/beam_LoadTests_Go_CoGBK_Flink_batch.yml
.github/workflows/beam_LoadTests_Go_GBK_Flink_Batch.yml
.github/workflows/load-tests-pipeline-options/go_CoGBK_Flink_Batch_MultipleKey.txt

Addresses: [#30507](https://github.com/apache/beam/issues/30507),  [#30502](https://github.com/apache/beam/issues/30502)
Successful GBK run example: https://github.com/akashorabek/beam/actions/runs/13530792021
Successful CoGBK run example: https://github.com/akashorabek/beam/actions/runs/13531199632
Issue to track why load increase causes failures: [#33753](https://github.com/apache/beam/issues/33753) …

Fix Go Load tests CoGBK and GBK

---

build.gradle.kts

Cherry-pick of #34082 to the postrelease branch
Part of https://github.com/apache/beam/issues/34084 …

[Cherry pick] Enable splitting up docker publish workflow (#34082)

---

sdks/python/container/build.gradle

Even after https://github.com/apache/beam/pull/34082 pushing containers takes 4 hours because python containers take so long each. This will allow parallelizing at the level of python version. The end goal of this is something like https://github.com/apache/beam/pull/34086/files
Part of https://github.com/apache/beam/issues/34084 …

Enable skipping individual python docker images

---

sdks/python/container/build.gradle

Even after https://github.com/apache/beam/pull/34082 pushing containers takes 4 hours because python containers take so long each. This will allow parallelizing at the level of python version. The end goal of this is something like https://github.com/apache/beam/pull/34086/files
Part of https://github.com/apache/beam/issues/34084 …

[Cherry pick] Enable skipping individual python docker images

---

sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkRowUpdateIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java

Fix lint errors - this is preventing new changes from passing  …

Fix lint errors

---

sdks/python/apache_beam/utils/subprocess_server.py
sdks/python/apache_beam/utils/subprocess_server_test.py

Fix expansion service parsing in Python SDK for rc build

---

sdks/python/apache_beam/io/kafka.py

Updated the docstring to include a clear example of how to enable t the legacy mode (ReadFromKafkaViaUnbounded) in the ReadFromKafka transform. This helps users switch from the default mode (ReadFromKafkaViaSDF) based connector to the legacy connector for scenarios requiring fewer Kafka connections. …

Update docstring in kafka.py for ReadFromKafka transform.

---

sdks/java/extensions/schemaio-expansion-service/build.gradle

Add alloydb language connector to schemaio expansion service.

---

sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

Parameterized built-in types were getting converted to typing equivalents before being passed to `convert_to_beam_type()` which was just converting them back to their original representations anyway. Additionally, collections types were not being passed through which could lead to incorrect mismatches (e.g. a processed internal `Sequence` hint representation throwing an error when presented with a `collections.abc.Sequence` type that did not get normalized correctly.)
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the …

Update routing of types into convert_to_beam_type in normalize()

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java

Fix flakes in FanOutStreamingEngineWorkerHarnessTest

---

CHANGES.md

Call out race condition fix in CHANGES

---

sdks/python/apache_beam/utils/annotations.py
sdks/python/apache_beam/utils/annotations_test.py

Fixes #22265
Note for Python SDK, we do not use experimental. …

Make pydoc docstring reflecting deprecated

---

.github/workflows/republish_released_docker_containers.yml

This should speed up the republish workflow so that it can complete in under 6 hours.
Example run: https://github.com/apache/beam/actions/runs/13553862695 (took <2 hours)
Closes #34084 …

Update republish workflow to split docker pushes

---

sdks/python/apache_beam/yaml/examples/transforms/elementwise/map_to_fields_with_resource_hints.yaml
sdks/python/apache_beam/yaml/main.py
sdks/python/apache_beam/yaml/pipeline.schema.yaml
sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_transform_test.py
website/www/site/content/en/documentation/runtime/resource-hints.md

Add resource hint capabilities to YAML.

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOInitializer.java

Enable kafka metrics by default for streaming dataflow jobs on v1 …

Enable kafka metrics by default for streaming dataflow jobs on v1

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java

fix for adding unexpected Empty Records in Nested Arrays in BigQueryIO

---

.github/workflows/beam_PostCommit_Python_Xlang_Gcp_Direct.yml

Install docker compose in PostCommit Python Xlang Gcp Direct to run xlang_jdbc tests in xlang direct workflow.

---

sdks/python/apache_beam/options/pipeline_options_test.py

Add test ensuring pipeline options observes kwargs.

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java

Fix failing test: Add more time for grpc cleanup

---

runners/flink/src/test/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/source/unbounded/FlinkUnboundedSourceReaderTest.java

Fix failing test: Increase timeout

---

runners/google-cloud-dataflow-java/build.gradle

Bump dataflow java container version to beam-master-20250307

---

sdks/python/apache_beam/ml/anomaly/base.py
sdks/python/apache_beam/ml/anomaly/detectors/__init__.py
sdks/python/apache_beam/ml/anomaly/detectors/iqr.py
sdks/python/apache_beam/ml/anomaly/detectors/iqr_test.py
sdks/python/apache_beam/ml/anomaly/detectors/robust_zscore.py
sdks/python/apache_beam/ml/anomaly/detectors/robust_zscore_test.py
sdks/python/apache_beam/ml/anomaly/detectors/zscore.py
sdks/python/apache_beam/ml/anomaly/detectors/zscore_test.py
sdks/python/apache_beam/ml/anomaly/univariate/base.py
sdks/python/apache_beam/ml/anomaly/univariate/mad.py
sdks/python/apache_beam/ml/anomaly/univariate/mad_test.py
sdks/python/apache_beam/ml/anomaly/univariate/median.py
sdks/python/apache_beam/ml/anomaly/univariate/median_test.py
sdks/python/apache_beam/ml/anomaly/univariate/quantile.py

- Add Z-score, robust Z-score and IQR detectors.
- Add median and mad trackers that are used in the detectors
- Add secondary quantile tracker that can share internal buffer with the primary.

[AnomalyDetection] Add detectors and some necessary univariate trackers.

---

sdks/python/apache_beam/io/tfrecordio.py

Fixes #33407
This only polishes the warning message. The better fix is probably to get rid of snappy and switch to the `crc32c` Python library if TFRecord can work. …

call out the snappy version in the warning message

---

sdks/python/apache_beam/yaml/yaml_io.py
sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_utils.py

This will make it easier to accommodate packaging schemes that do not place the data files next to the python files. …

Factor out data file discovery.

---

website/www/site/content/en/documentation/runtime/resource-hints.md

Fix typo on resource hints page.

---

runners/google-cloud-dataflow-java/build.gradle

Bump dataflow java container version - 20250312

---

.github/workflows/cut_release_branch.yml

This is cosmetic, but brings these 2 options in line with each other to avoid confusion …

Use same format for next and current release versions

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update DF Python container tag

---

runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java

Fixes #34207.
For Spark 3, the behavior that was before #34080 has been reverted.
Successful run: https://github.com/Amar3tto/beam/actions/runs/13794580478 …

Fix PostCommit Java PVR Spark3 Streaming job

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

Needed to match LTS version with other clients. …

Update to latest bom

---

.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Direct.json
sdks/java/io/expansion-service/build.gradle
sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/kafka-390/build.gradle
settings.gradle.kts

Kafka supports authenticating via OAuth credentials, but the packages were renamed in 3.4.0. This update to the Expansion service will allow Kafka users to utilize OAuth credentials in any kafka client version post 3.4.0. …

Update pinned kafka version to 3.9.0 in Expansion Service.

---

.github/workflows/beam_PostCommit_Python_ValidatesContainer_Dataflow_With_RC.yml
sdks/python/container/run_validatescontainer.sh

Fixes #30525 
Successful run: https://github.com/Amar3tto/beam/actions/runs/13782630155 …

Fix PostCommit Python ValidatesContainer Dataflow With RC job

---

it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryIOST.java

Successful run example: https://github.com/akashorabek/beam/actions/runs/13532591588 …

Fix Stress Tests Java Bigquery

---

sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java

Fix #34277
The only remaining expression was used to handle Consumer.assign() pre and after kafka 0.10.0.0: https://github.com/apache/kafka/commit/4332175c11dda5deb491f27a6ecf66661676ca47
and is no longer needed as current Beam supports Kafka 2.0.x onwards
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com …

Eliminate springframework dependency in KafkaIO

---

sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java
sdks/java/core/src/test/java/org/apache/beam/sdk/metrics/LineageTest.java
sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystem.java
sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/storage/GcsFileSystemTest.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystem.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/s3/S3FileSystemTest.java
sdks/java/io/azure/src/main/java/org/apache/beam/sdk/io/azure/blobstore/AzureBlobStoreFileSystem.java
sdks/java/io/azure/src/test/java/org/apache/beam/sdk/io/azure/blobstore/AzureBlobStoreFileSystemTest.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PreparePubsubWriteDoFn.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableReadIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableWriteIT.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOReadTest.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteTest.java
sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOTest.java

- Updates Lineage to use BoundeedTrie
- Handles backtick in segments which needs escaping too. See https://b.corp.google.com/issues/380375877#comment3 for details. 
- Update IO to use the updated Lineage class changes. …

Use BoundedTrie metric to track lineage in IO

---

CHANGES.md

Updates 2.64.0 release notes to highlight recent additions to the Managed API

---

sdks/python/apache_beam/ml/inference/base.py

These should match https://github.com/apache/beam/blob/c51d6d3100983f0b868efd9d4aeb89006b749a98/sdks/python/apache_beam/ml/inference/base.py#L156 …

Fix pre/postprocess type hints

---

sdks/python/apache_beam/yaml/yaml_io.py
sdks/python/apache_beam/yaml/yaml_io_test.py

Add a STRING format to PubSub reading that interpretes the payload as utf-8 encoded.

---

.test-infra/metrics/sync/github/github_runs_prefetcher/code/main.py

Consider workflow flaky if the 5 last runs were failed

---

sdks/python/apache_beam/examples/snippets/snippets.py
sdks/python/apache_beam/examples/snippets/snippets_test.py

added test_accessing_valueprovider_info_after_run

---

sdks/java/io/kafka/build.gradle

Fixes: [#34314](https://github.com/apache/beam/issues/34314)
Successful run example: https://github.com/akashorabek/beam/actions/runs/13891705322 …

Fix Precommit SQL

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOInitializer.java

Add option to disable Kafka metrics

---

sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/providers/SqsReadConfiguration.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/providers/SqsReadSchemaTransformProvider.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/providers/package-info.java
sdks/java/io/amazon-web-services2/src/test/java/org/apache/beam/sdk/io/aws2/sqs/providers/SqsReadSchemaTransformProviderTest.java

This change creates a schema transform provider exposing the SQS read functionality implemented in the Java SDK to other SDK languages.
Other languages wrappers will be added in a separate PR. …

Enable xlang access for SQS read functionality

---

sdks/python/apache_beam/typehints/opcodes.py
sdks/python/apache_beam/typehints/trivial_inference_test.py

Handle numeric promotion, sequence multiplication, and fix division for Python 3.11+. …

More precise binary operation inference.

---

CHANGES.md

update CHANGES with Read bugs/improvements

---

CHANGES.md

Add changes.md message for Trigger support in Prism.
A part of #31438 .
----------------------- …

[#31438] Add changes.md message for Trigger support in Prism.

---

sdks/python/apache_beam/yaml/yaml_provider.py

This fixes https://github.com/apache/beam/issues/34343
Turns out `urllib.parse.urlparse(None, '').scheme` returns an empty *bytes* object(?!). When base is None, there is no base-relative joining we need to do, so we return the path directly. 
GitHub Actions …

Fix relative path yaml provider error when no base provided.

---

.test-infra/tools/stale_k8s_workload_cleaner.sh

Fixes: [#33435](https://github.com/apache/beam/issues/33435)
Successful run example: https://github.com/akashorabek/beam/actions/runs/13944853806 …

Remove finalizers from sdb-cluster before deleting singlestoreio namespaces

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/BeamKafkaTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/KafkaTableProvider.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/KafkaTableProviderTest.java

BeamSQL's Create Table Statement does not support consumer properties. This PR aims to add that support on KafkaTableProvider for all KafkaTable …

Kafta Table consumer properties feature for beamSQL

---

CHANGES.md

Manually update CHANGES.md on master by adding a new section for the next release …

update the changes.md by adding 2.65.0

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/StreamingDataflowWorker.java

ipv6 networking is an implementation detail and may change at anytime in the future so removing the check
R: @scwhittle  …

remove private ipv6 check

---

release/src/main/scripts/set_version.sh

Fix version on the master

---

release/src/main/scripts/set_version.sh

Fixes problem seen/attempted to be fixed by https://github.com/apache/beam/pull/34371
I tried this locally with the expected input set and it ran correctly …

Perform correct release version validation

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedSource.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/WatchForKafkaTopicPartitions.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java

If a specified topic or partition do not exist in a kafka cluster, the pipeline should fail before submission. There are some caveats to this, such as whether or not the cluster is reachable, so we only fail in the case where the cluster is reachable but the specified partitions or topics are not present. …

Fail Fast if Resources Do Not Exist in Kafka Cluster

---

website/www/site/content/en/documentation/sdks/python-pipeline-dependencies.md

Mention __init__.py, which is customary for packages.

---

CONTRIBUTING.md
contributor-docs/code-change-guide.md

* Move java 8 to 11
* Fix a few markdown formatting issues …

Update CONTRIBUTING.md to point to code-change-guide

---

release/src/main/scripts/set_version.sh

CP: Perform correct release version validation (#34378)

---

.github/workflows/build_release_candidate.yml

Relies on https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow#defining-prerequisite-jobs
Since we have if conditions for these defined, they should still run even if only one job is triggered
GitHub …

Enforce ordering to avoid svn conflicts

---

sdks/python/build.gradle

Update build.gradle (#34401)

---

sdks/python/apache_beam/yaml/yaml_provider.py

This will allow other users to replace the default sql provider used by 'Join' and 'Combine-sql'. …

Factor out a get_default_sql_provider() function.

---

sdks/python/apache_beam/yaml/yaml_provider.py

Follow up to https://github.com/apache/beam/pull/34404/files#r2010875137 …

Add warning comment so that folks don't change this

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/PubsubSink.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/PubsubSinkTest.java

[Dataflow Streaming] Improve exception handling in PubsubSink to rest stream to prevent precondition exception on reuse

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GetWorkTimingInfosTracker.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GetWorkTimingInfosTrackerTest.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcWindmillServerTest.java

We want to track the GetWorkTimings even when we don't proxy the calls through the dispatcher.
R: @scwhittle 
[![Build …

track GetWork from WindmillWorker to UserWorker in proxyless path

---

website/www/site/content/en/documentation/programming-guide.md

Corrects the python reference in the programming guide for section "4.2.4.3. Combining a PCollection into a single value".
Currently it's the below that shows the average instead of the sum:
and with this PR it now shows the right global sum reference:
GitHub …

Fix programming guide python reference for combining pcollection into a single value

---

sdks/java/io/kafka/build.gradle
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetrics.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaSinkMetricsTest.java

Remove dependency of core-runners in kafka:io …

Remove dependency of core-runners in kafka:io

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java

Correcting array truncation logic to satisfy schema ARRAY(vector_length=>128) …

correcting array truncation logic (resolves #34276)

---

sdks/python/apache_beam/io/tfrecordio.py

Replaces snappy with google-crc32c to fix the issue #34226

adding google-crc32c

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

ran ``` python3 scripts/tools/bomupgrader.py 26.57.0```
logs - 
```
INFO:root:-----Read BeamModulePlugin-----
INFO:root:-----check dependency defs in BeamModulePlugin-----
INFO:root:-----prepare build.gradle for example project-----
INFO:root:-----resolve dependency-----
INFO:root:-----Update BeamModulePlugin-----
INFO:root:Changed com.google.api:gax: 2.62.0 -> 2.63.1
INFO:root:Changed com.google.cloud:google-cloud-spanner: 6.88.0 -> 6.89.0
INFO:root:Unchanged: io.grpc:grpc-netty:1.70.0
INFO:root:Unchanged: io.netty:netty-transport:4.1.110.Final
INFO:root:Changed com.google.protobuf:protobuf-java: 4.29.0 -> 4.29.4
INFO:root:Unchanged: org.apache.arrow:arrow-memory-core:15.0.2
INFO:root:Changed com.google.apis:google-api-services-bigquery: v2-rev20250216-2.0.0 -> v2-rev20250313-2.0.0 …
```

upgraded gcp-bom to 26.57.0

---

CHANGES.md
website/www/site/content/en/blog/beam-2.63.0.md

There is a protobuf bug which causes back-compat issues with clients using older versions of protobuf to generate protos. This calls it out …

Add known protobuf issue

---

.github/workflows/beam_PreCommit_Java.yml
.github/workflows/beam_PreCommit_Java_GCP_IO_Direct.yml

[beam_PreCommit_Java (Run Java PreCommit)](https://github.com/apache/beam/actions/runs/14080638329/job/39439417418?pr=34420)
and [beam_PreCommit_Java_GCP_IO_Direct (Run Java_GCP_IO_Direct PreCommit)](https://github.com/apache/beam/actions/runs/14080638332/job/39432602293?pr=34420#logs) are exceeding now 2hr and are cancelled. Extending to 180 for both.  …

extend timeout for beam_PreCommit_Java_GCP_IO_Direct and beam_PreCommit_Java actions

---

sdks/python/apache_beam/yaml/yaml_provider.py

Avoid hard dependency on clonevirtualenv.

---

runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto

Confirmed that this field is coming across, so I am exposing it to the legacy worker. This PR is a zero-risk early piece that enables later adding an "isDrain" bit to timer callbacks. …

Expose drain_mode in windmill proto

---

.github/workflows/run_rc_validation_python_mobile_gaming.yml

added run_rc_validation_python_mobile_gaming.yml

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.63.0.md
website/www/site/content/en/blog/beam-2.64.0.md
website/www/site/content/en/get-started/downloads.md

Added blog post for 2.64.0

---

.github/workflows/run_rc_validation_java_quickstart.yml

Added a new RC validation workflow for Java quickstart

---

contributor-docs/code-change-guide.md
sdks/go/README.md

Adds instructions regarding building the Go SDK harness container for Dataflow

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/DataflowOutputCounter.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/IntrinsicMapTaskExecutorFactoryTest.java

[Dataflow] Remove unused PhysicalElementCount Counter

---

.github/REVIEWERS.yml
.github/autolabeler.yml

The goal here is to better round robin reviews based on current expertise/engagement. Notable changes:
- Added claude to Python rotation and removed Damon from rotations
- Removed IO routing and consolidated most reviewers into Java. All IO labels also are either Java/Python/Go, so we can let that label handle finding a reviewer
- Reduced scope of build label so random non-build PRs don't get routed that way …

Update reviewers to more accurately match current state of repo

---

contributor-docs/discussion-docs/2025.md

Updated the discussion doc up to Beam 2.64.0

---

CHANGES.md
website/www/site/content/en/blog/beam-2.64.0.md

minor doc updates

---

.github/workflows/republish_released_docker_containers.yml

Updated the republished workflow to 2.64.0

---

runners/google-cloud-dataflow-java/worker/windmill/src/main/proto/windmill.proto

plumb grpc flow control settings via UserWorkerRunnerV1Settings for dynamic update of these values from Windmill/Dataflow
follow up PR will consume the flow control settings w/ appropriate defaults. …

plumb grpc flow control settings via UserWorkerRunnerV1Settings

---

contributor-docs/release-guide.md

We haven't generally done these in the past, and they are not very high value at this point. I think we should just do this at milestones. …

Remove social media pieces from release guide

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcUtil.java

handle empty string
YAML implementation passes default driver_jars: '' which is causing NPE in JDBCUtil.
[![Build …

JDBCIO - handle empty driverjars argument

---

.github/workflows/cut_release_branch.yml
release/src/main/scripts/set_version.sh

Add rc00 tag

---

.github/autolabeler.yml

It looks like this was always matching and wasn't functioning as a real negation, so too much was getting tagged build. Example pr - https://github.com/apache/beam/pull/34517 got tagged build but doesn't have any relevant build changes …

Remove build label exclusion and just use workflows

---

.github/actions/setup-k8s-access/action.yml
.github/workflows/beam_PostCommit_Java_SingleStoreIO_IT.yml

Fixes #30523
Successful run: https://github.com/Amar3tto/beam/actions/runs/14227255238/job/39869619571 …

Fix PostCommit Java SingleStoreIO IT job

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

Issue warnings when dataSourceConfiguration and dataSourceProviderFn are set

---

sdks/python/apache_beam/io/gcp/big_query_query_to_table_it_test.py
sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py
sdks/python/apache_beam/io/gcp/bigquery_write_it_test.py
sdks/python/apache_beam/io/gcp/gcsio_integration_test.py
sdks/python/apache_beam/ml/gcp/recommendations_ai.py

Addresses: [#30513](https://github.com/apache/beam/issues/30513)
Addresses the main frequently occurring flaky tests in the PostCommit Python workflow.
Successful job example: https://github.com/akashorabek/beam/actions/runs/14228735266 …

Fix postcommit python flaky tests

---

contributor-docs/release-guide.md

updated the release guide

---

sdks/python/apache_beam/io/textio.py
sdks/python/apache_beam/io/textio_test.py

https://github.com/apache/beam/pull/34364 reverted the PR. …

Fix the error for directory separator

---

CHANGES.md

added the Beam 3.0.0 highlights to the release template

---

sdks/python/apache_beam/yaml/main.py
sdks/python/apache_beam/yaml/main_test.py
sdks/python/apache_beam/yaml/yaml_testing.py
sdks/python/apache_beam/yaml/yaml_testing_test.py
sdks/python/apache_beam/yaml/yaml_transform.py
sdks/python/apache_beam/yaml/yaml_utils.py
sdks/python/apache_beam/yaml/yaml_utils_test.py
website/www/site/content/en/documentation/sdks/yaml-udf.md

The apache_beam.yaml.main module now takes a --test and --test_suite option to run tests, --fix_tests to update them as the pipeline evolves, and --create_test to automatically generate a regression test of the pipeline by sampling the inputs and asserting the observed outputs.
This builds on top of https://github.com/apache/beam/pull/34513
To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STAT …

Add the ability to fix and automatically create yaml pipeline tests.

---

sdks/python/apache_beam/internal/cloudpickle_pickler.py

Found an edge-case where system.modules changes during iteration causing an error during unpickling. …

Copy sys.module.items() in case it changes during iteration.

---

website/www/site/layouts/partials/section-menu/en/sdks.html

Add a link to the Beam yaml examples.

---

sdks/python/apache_beam/typehints/native_type_compatibility_test.py
sdks/python/apache_beam/typehints/typehints.py
sdks/python/apache_beam/typehints/typehints_test.py

Handles re.Pattern and re.Match type checking, replacing the `typing` variants that always treated these types as `Any`. 
Fixes #20489  …

[#20489] Add support for re.Pattern and re.Match type checking

---

.github/workflows/run_rc_validation_python_mobile_gaming.yml
scripts/tools/validate_table.sh

use the script when validating the BQ table

---

.github/workflows/beam_Publish_Beam_SDK_Snapshots.yml

Addresses #32161 
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build …

Activate service account for Publish Beam SDK Snapshots workflow

---

runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkJobInvoker.java
runners/java-job-service/src/main/java/org/apache/beam/runners/jobsubmission/JobInvoker.java

Fixes [#31418](https://github.com/apache/beam/issues/31418)
Reverts [#33713](https://github.com/apache/beam/pull/33713)
Successful job example: https://github.com/akashorabek/beam/actions/runs/14447873693 …

Fix The PostCommit XVR Flink job

---

sdks/python/apache_beam/examples/streaming_wordcount_it_test.py
sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py
sdks/python/apache_beam/io/gcp/bigquery_write_it_test.py
sdks/python/apache_beam/io/gcp/gcsio_integration_test.py

Addresses [#30513](https://github.com/apache/beam/issues/30513)
Successful run example: https://github.com/akashorabek/beam/actions/runs/14459000914 …

Fix new flaky postcommit python tests

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarness.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/streaming/harness/WindmillStreamSender.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/streaming/harness/FanOutStreamingEngineWorkerHarnessTest.java

Addresses: [#34171](https://github.com/apache/beam/issues/34171)
Successful run example: https://github.com/akashorabek/beam/actions/runs/14375428917 …

Fix FanOutStreamingEngineWorkerHarnessTest - testOnNewWorkerMetadata_redistributesBudget

---

sdks/python/apache_beam/examples/cookbook/bigtableio_it_test.py
sdks/python/apache_beam/examples/online_clustering.py
sdks/python/apache_beam/io/gcp/bigtableio_it_test.py
sdks/python/apache_beam/metrics/cells.py
sdks/python/apache_beam/runners/dataflow/internal/apiclient.py
sdks/python/apache_beam/transforms/enrichment_handlers/bigtable_it_test.py

I was seeing noise about this in our tests... …

Avoid use of deprecated datetime.utcnow().

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt

Back port virtualenv-clone to 2.64 Python SDK container

---

.github/workflows/run_rc_validation_python_yaml.yml
contributor-docs/release-guide.md

Added run_rc_validation_python_yaml to validate the Beam YAML RC

---

sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai.py

fix the doc

---

learning/tour-of-beam/learning-content/core-transforms/map/group-by-key/description.md

Move Java snipped to the Java block, and remove a redundant line. …

Tour of Beam: update GroupByKey example

---

sdks/python/apache_beam/internal/cloudpickle_pickler_test.py
sdks/python/apache_beam/internal/module_test.py

Add some more cloudpickle tests to demonstrate behavior. …

Add some more cloudpickle tests.

---

website/www/site/content/en/documentation/runtime/environments.md

Updated the container doc

---

sdks/python/apache_beam/yaml/pipeline.schema.yaml

Add schema definition for yaml test specs.

---

scripts/ci/pr-bot/package-lock.json
scripts/ci/pr-bot/package.json

Revert "Bump @octokit/request, @actions/github and @octokit/rest in /scripts/ci/pr-bot"

---

sdks/java/expansion-service/src/main/java/org/apache/beam/sdk/expansion/service/ExpansionService.java

Instead, print usage when invoking expansion service without parameter  …

Fix IndexOutOfBoundsException invoking expansion service

---

sdks/python/apache_beam/runners/portability/fn_api_runner/translations.py

Though this coder is identital to the normal iterable coder when not state backing is provided, some SDKs refuse to instantiate these coders outside of this context. …

Only declare state backed iterables on code channel.

---

sdks/python/apache_beam/runners/portability/job_server.py

The previously registered SIGINT handler had an incorrect signature according to the signal module documentation:
https://docs.python.org/3/library/signal.html#signal.signal
> The handler is called with two arguments: the signal number and the current stack frame (None or a frame object; for a description of frame objects,
This PR updates the handler to the correct signature. It now gracefully stops the server and ensures the original handler is called for proper application exit. This is important especially in a Colab environment, because the kernel will send out SIGINT when the stop button of a cell is pressed.

Fix SIGINT handler for StopOnExitJobServer

---

sdks/python/apache_beam/ml/rag/enrichment/bigquery_vector_search.py
sdks/python/apache_beam/ml/rag/enrichment/bigquery_vector_search_it_test.py

Add option to create metedata filter with function.

---

.github/workflows/beam_PostCommit_Java_ValidatesRunner_Flink_Java8.yml

Fixes: [#32949](https://github.com/apache/beam/issues/32949)
PostCommit Java ValidatesRunner Flink and PostCommit Java ValidatesRunner Flink Java8 were running at the same time, causing flakiness …

Fix The PostCommit Java ValidatesRunner Flink Java8 job

---

examples/notebooks/beam-ml/bigquery_vector_ingestion_and_search.ipynb

BigQuery embeddings colab

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy

workaround: https://github.com/apache/beam/issues/32603#issuecomment-2836370541 …

pin pip==25.0.1

---

website/www/site/content/en/blog/apache-beam-flink-and-kubernetes-part2.md
website/www/site/content/en/blog/apache-beam-flink-and-kubernetes.md

There was a typo under name I fixed the typo.

Fixing Typo on Blog Post

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanSource.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskReader.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/ScanTaskSource.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergIOReadTest.java

[IcebergIO] Fetch source schema directly from the table

---

sdks/python/apache_beam/yaml/standard_io.yaml

Adjusting the version since this went in before the 2.65.0 branch cut.
This fixes https://github.com/apache/beam/issues/34767. …

Adjusting the YAML Kafka Managed I/O compat version

---

CHANGES.md

Update CHANGES.md after 2.64 release cut

---

sdks/python/apache_beam/typehints/trivial_inference.py

Replace an old JIRA-style issue reference with the correct GitHub Issue link (this issue never existed on JIRA anyway) …

Fix issue link in trivial_inference.py

---

sdks/python/apache_beam/io/gcp/bigquery_file_loads.py

Add name to BQ File Loads lambda to ensure changes are update compatible

---

sdks/python/apache_beam/io/gcp/gcsio.py
sdks/python/apache_beam/io/gcp/gcsio_test.py

Fixes https://github.com/apache/beam/issues/34834 …

use batch delete for GCS IO

---

.github/workflows/beam_PostCommit_Java_Nexmark_Dataflow_V2.yml

Fix #34822
Tested on https://github.com/apache/beam/actions/runs/14804050036/job/41569043036
confirm jobs now run with Dataflow runner v2 …

Fix Nexmark Dataflow V2 use runner v2

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java

Modify the assert to accept any instance of AvroCoder, including subclasses. This allows the class to read messages that were written as GenericRecords, which are encoded using the AvroGenericCoder. …

Change Assert to Check instanceof AvroCoder

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java

Cherry-picks https://github.com/apache/beam/pull/34843 to the 2.65 release branch. …

Modify the assert to accept any instance of AvroCoder, including subclasses

---

scripts/ci/issue-report/package-lock.json
scripts/ci/issue-report/package.json

Reverts apache/beam#34567
Fixes #34855

Revert "Bump @octokit/request and @octokit/rest in /scripts/ci/issue-report"

---

.github/workflows/tour_of_beam_backend_integration.yml
learning/tour-of-beam/backend/integration_tests/emulators/firebase/Dockerfile

Fixes: [#34817](https://github.com/apache/beam/issues/34817)
Upgraded `node` version to `20`, since new `firebase-tools` release doesn't support node 18 anymore.
Successful run example: https://github.com/akashorabek/beam/actions/runs/14834992512
GitHub Actions …

Fix Tour of Beam Go Integration tests

---

scripts/ci/pr-bot/findPrsNeedingAttention.ts

This label will be helpful for finding PRs which need help …

Add label when PR gets reassigned

---

sdks/python/apache_beam/coders/coders.py
sdks/python/apache_beam/coders/coders_test_common.py
sdks/python/apache_beam/coders/typecoders.py
sdks/python/apache_beam/coders/typecoders_test.py

Encode paneinfo with PaneInfoCoder.
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels …

Encode paneinfo with PaneInfoCoder. (#34824)

---

scripts/ci/pr-bot/findPrsNeedingAttention.ts

Fix pr-bot workflows

---

scripts/ci/pr-bot/shared/commentStrings.ts

Reorder the opt-out of review comment from:
```
Assigning reviewers. If you would like to opt out of this review, comment assign to next reviewer:
R: @claudevdm for label python.
R: @Abacn for label java.
Available commands:
```
to:
```
Assigning reviewers:
R: @claudevdm for label python.
R: @Abacn for label java.
Note: If you would like to opt out of this review, comment `assign to next reviewer`
Available commands:
``` …

reorder opt-out review comment

---

sdks/python/apache_beam/ml/rag/embeddings/vertex_ai_test.py
sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai_test.py

Tests failing because trying to use deprecated model. …

Replace deprecated model version.

---

examples/notebooks/beam-ml/anomaly_detection/anomaly_detection_iforest.ipynb

For now, in our colab, we are using the RC of 2.65.0, since some of the features/improvements are new in the coming 2.65.0  
We will switch to the final, stable 2.65.0 version in our notebook as soon as it's officially out.
colab link:
https://colab.sandbox.google.com/github/shunping/beam/blob/anomaly-detection-notebook-2/examples/notebooks/beam-ml/anomaly_detection/anomaly_detection_iforest.ipynb

[AnomalyDetection] Add a notebook for using iforest for anomaly detection

---

examples/notebooks/beam-ml/anomaly_detection/anomaly_detection_iforest.ipynb

- Changed how environment variables are set. 
- Added links to open notebook in colab and github.
- Restructure the sections and sub-sections.
- Reset execution counts
colab preview:
https://colab.sandbox.google.com/github/shunping/beam/blob/anomaly-detection-notebook-3/examples/notebooks/beam-ml/anomaly_detection/anomaly_detection_iforest.ipynb

[AnomalyDetection] Update notebook.

---

sdks/python/apache_beam/coders/typecoders_test.py

The typecoders_test.py file wasn't covered by the reformatted linting done with the yapf upgrade, this fixes the issue. …

Fix typecoders_test.py formatting

---

examples/notebooks/beam-ml/alloydb_product_catalog_embeddings.ipynb
examples/notebooks/beam-ml/bigquery_enrichment_transform.ipynb
examples/notebooks/beam-ml/gemma_2_sentiment_and_summarization.ipynb
examples/notebooks/beam-ml/run_inference_vllm.ipynb

Some automated tooling assumes that it can execute cells if they don't have outputs (this is used to import notebooks in other contexts/test them). This fixes some notebooks which fail this process by adding dummy outputs …

Add empty outputs to notebooks which can't run without help

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/MetricsPusher.java
runners/extensions-java/metrics/src/main/java/org/apache/beam/runners/extensions/metrics/MetricsGraphiteSink.java
runners/extensions-java/metrics/src/main/java/org/apache/beam/runners/extensions/metrics/MetricsHttpSink.java

I just happened to be talking to someone about possibly working with these and I wanted to get them into pristine shape before we start. …

Remove type suppressions from MetricsPusher and MetricsSink

---

sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergWriteSchemaTransformProvider.java
website/www/site/content/en/documentation/io/managed-io.md

To highlight dynamic destinations

Update Iceberg table field documentation 

---

CHANGES.md

Add cloudpickle default to changes.md.

---

sdks/python/apache_beam/io/gcp/bigquery_tools.py

Revert "Correcting regex for _PROJECT_PATTERN for bigquery table name (resolv…"

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_read_internal.py

[Python] Added the validate support for ReadAllFromBigQuery

---

runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/util/BoundedQueueExecutorTest.java

Fix the following flake, the thread may not have terminated yet. By using join we enforce that it does terminate but avoid the race.
```
testScheduleWorkWhenExceedMaximumBytesOutstanding[useFairMonitor = true] (org.apache.beam.runners.dataflow.worker.util.BoundedQueueExecutorTest) failed
runners/google-cloud-dataflow-java/worker/build/test-results/test/TEST-org.apache.beam.runners.dataflow.worker.util.BoundedQueueExecutorTest.xml [took 1s]
java.lang.AssertionError: expected:<TERMINATED> but was:<RUNNABLE>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.apache.beam.runners.dataflow.worker.util.BoundedQueueExecutorTest.testScheduleWorkWhenExce …
```

Fix flaky BoundedQueueExecutor test

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.65.0.md
website/www/site/content/en/get-started/downloads.md

Update Beam website to release 2.65.0

---

sdks/python/apache_beam/transforms/resources.py
sdks/python/apache_beam/transforms/resources_test.py

Prevent ValueError when passing resource_hints in StandardOptions

---

sdks/python/tox.ini

Fixes: [#30799](https://github.com/apache/beam/issues/30799)
Fixes: [#31285](https://github.com/apache/beam/issues/31285)
Successful The PostCommit Python Dependency job example: https://github.com/akashorabek/beam/actions/runs/14977198589
Successful PreCommit Python ML tests with ML deps installed job example: https://github.com/akashorabek/beam/actions/runs/14976785049 …

Specify pip version for ML and Transformers tests

---

runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/SimpleMonitoringInfoBuilder.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/BeamFnDataReadRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/BeamFnDataWriteRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/CombineRunners.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

Just fixing some broken windows. Mostly adding explicit error checking to places where we just let invalid values slip through API boundaries. Re-enabling nullness checking for files I touched in prior PR. …

Fix minor issues in various PTransformRunner classes

---

examples/notebooks/beam-ml/alloydb_product_catalog_embeddings.ipynb
examples/notebooks/beam-ml/bigquery_vector_ingestion_and_search.ipynb

Add empty outputs.

---

sdks/python/apache_beam/yaml/generate_yaml_docs.py

Resolves #34770 
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?even …

Fix for emojis rendering issue for yaml examples (resolves #34770)

---

examples/notebooks/beam-ml/anomaly_detection/anomaly_detection_iforest.ipynb
examples/notebooks/beam-ml/anomaly_detection/anomaly_detection_zscore.ipynb

Fix empty outputs.

---

sdks/python/apache_beam/typehints/opcodes.py
sdks/python/apache_beam/typehints/trivial_inference.py

Updates the trivial inference cpython emulation/state machine to support Python 3.13 changes (new opcodes and changes to previous ones.) This is necessary to unblock Python 3.13 support. 
Part of #34869 …

Update trivial inference for Python 3.13

---

sdks/python/apache_beam/typehints/trivial_inference.py

fix linting

---

sdks/python/setup.py

Correct the upper bound definition to make it strict.
See: https://cwiki.apache.org/confluence/display/BEAM/Dependency+management+guidelines+for+Beam+Python+SDK+maintainers#DependencymanagementguidelinesforBeamPythonSDKmaintainers-Howtoaddanewdependency? for reasons. …

Use a strict upper bound.

---

sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptions.java

check the audit key exists before adding it

---

CHANGES.md

My change in Coder https://github.com/apache/beam/pull/33626 has introduced breaking change leading to Coder serial version to change. This mostly affects Coders extending CustomCoder and Coder.
GitHub …

Add 2.63 breaking incompatibility to CHANGES.md

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/options/pipeline_options_test.py

Fix gcs audit custom entries

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/SplittablePairWithRestrictionDoFnRunner.java
sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/FnApiStateAccessor.java

This builds on #34883 by moving shared initialization to `FnApiStateAccessor`. …

Share FnApiStateAccessor initialization across ParDo runners in Java SDK harness

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Direct.json
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java
sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/IcebergUtilsTest.java
sdks/python/apache_beam/transforms/managed_iceberg_it_test.py

[IcebergIO] Fix Iceberg list conversion

---

runners/spark/src/test/java/org/apache/beam/runners/spark/translation/streaming/ResumeFromCheckpointStreamingTest.java

To mitigate #34946, ignoring this test. …

Ignore result of flaky ResumeFromCheckpointStreamingTest.testWithResume

---

.github/workflows/beam_PostCommit_Java_Examples_Dataflow_V2.yml

I overlooked the testJavaVersion and java17Home settings in #34925. …

[Gradle] Patch testJavaVersion and java17Home for Dataflow runner v2 distroless integration test

---

.github/workflows/beam_PreCommit_Java_Examples_Dataflow_Java21.yml
build.gradle.kts

Move Java Example distroless Dataflow to Java21 precommit

---

.github/workflows/build_release_candidate.yml

Fixes https://github.com/apache/beam/issues/34694 …

use java 11 for yaml docs

---

contributor-docs/release-guide.md

Release documents fix post 2.65.0 release

---

sdks/python/setup.py

Updates the `google-apitools` dependency to the latest version for future Python 3.13 support. Leaves the previous versioning alone for old Python versions, as that seems to have broken some of the ML testing that leans on older beam versions
Part of #34869  …

Update google-apitools to 0.5.32

---

sdks/python/apache_beam/typehints/typehints.py

The check for `AnyTypeConstraint` types happening before type normalization could create situations where an `AnyTypeConstraint` was created during normalization and then have `_consistent_with_check` called on it, which is not implemented for that type constraint class. This avoids that potential issue by checking for `Any` afterwards; if an `Any` constraint is passed into the normalization function it will be returned unchanged, so the cases caught by the old code are still covered. …

Slide AnyTypeConstraint check after type normalization

---

examples/notebooks/beam-ml/alloydb_product_catalog_embeddings.ipynb

Remove newline outputs.

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/container/license_scripts/dep_urls_java.yaml

Upgrade to GCP-BOM 26.60.0

---

examples/notebooks/documentation/transforms/python/io/RequestResponseIO.ipynb
website/www/site/content/en/documentation/io/built-in/webapis.md

(#30422)
Took the Java example for the RequestResponseIO transform as reference to
* update the website with python example and documentation
* add a jupyter notebook with the runnable example …

Update website documentation and add notebook example for python sdk RRIO

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java

fixes https://github.com/apache/beam/issues/31422
Based on https://github.com/apache/beam/issues/31422#issuecomment-2159010658, try to fix this by making `closed` volatile. …

fix the IllegalStateException in STORAGE_WRITE_API

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java

60 000 ms is 1 minute, not 10 minutes …

Update comment about timeouts in BigtableIO

---

.github/REVIEWERS.yml
.github/workflows/stale.yml

added the stale issue checks

---

examples/notebooks/beam-ml/anomaly_detection/anomaly_detection_iforest.ipynb

Switch to use the official 2.65.0 in this notebook.

Some minor fixes after beam 2.65.0 was released.

---

sdks/python/apache_beam/io/gcp/bigquery.py
sdks/python/apache_beam/io/gcp/bigquery_test.py

Resolves #35019 
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow%3A%22Bui …

Passing max_retries in WriteToBigquery (resolves #35019)

---

contributor-docs/code-change-guide.md

Clarify dataflow worker jar path

---

sdks/go/pkg/beam/runners/prism/internal/jobservices/artifact.go
sdks/go/pkg/beam/runners/prism/internal/jobservices/server.go

Fixes #34316
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheels.yml/badge.svg?event=sc …

fix prism runner race condition

---

runners/google-cloud-dataflow-java/build.gradle

Update dataflow containers

---

sdks/java/core/src/main/java/org/apache/beam/sdk/values/PCollectionViews.java

[Java] Explicitly handle singleton iterators instead of using helper and catching exceptions which may be from fetching the iterable.

---

website/www/site/content/en/case-studies/akvelon.md

- update text with missed word …

[Website] update akvelon case study text

---

.github/workflows/beam_PostCommit_Yaml_Xlang_Direct.yml

I had left the runs on for the new postcommit workflow set to latest, when there is no machine set up for that remotely.  Changing to the normal 20.04 version. …

[YAML]: postcommit IT - change to ubuntu-20.04

---

.github/trigger_files/beam_PostCommit_Java_Jpms_Dataflow_Java11.json
sdks/java/testing/jpms-tests/build.gradle

This test failed due to stale deps on the SDK harness container. Adjusting it to stage the jar. …

Use staged SDK harness & Dataflow worker jar in JPMS tests

---

sdks/python/apache_beam/yaml/yaml_provider.py
sdks/python/apache_beam/yaml/yaml_specifiable.py
sdks/python/apache_beam/yaml/yaml_specifiable_test.py

Also add support on callable in spec.

[YAML] Add a spec provider for transforms taking specifiable arguments

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

Fix null check when fetching driverJars from value provider

---

sdks/python/apache_beam/runners/portability/fn_api_runner/fn_runner_test.py
sdks/python/apache_beam/runners/portability/portable_runner_test.py

Fixes #30657, Fixes #30645
Successful runs: https://github.com/apache/beam/actions/runs/15534860777, https://github.com/apache/beam/actions/runs/15534858636 …

Fix PostCommit Python ValidatesRunner Samza / Spark jobs

---

.github/workflows/beam_PostCommit_Yaml_Xlang_Direct.yml

Seeing disk space issue [here](https://github.com/apache/beam/actions/runs/15619378606/job/44000086195), so lets try adding a free disk space step.
Might fix this as well - https://github.com/apache/beam/issues/35198.
If not, we will rollback to self hosted runner and maybe disable kafka test.  Oracle test should be fine now. …

[yaml]: add free disk space step for post commit yaml workflow

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/status/BeamFnStatusClient.java

Currently failing Java PreCommit …

Suppress Findbugs

---

.github/workflows/beam_PreCommit_Java_Solace_IO_Direct.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/auth/GoogleADCIdTokenProvider.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/GetKinesisRecordsResult.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisIO.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/KinesisPartitioner.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/kinesis/ShardRecordsIterator.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3ReadableSeekableByteChannel.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/s3/S3WritableByteChannel.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsIO.java
sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/sqs/SqsUnboundedReader.java
sdks/java/io/hadoop-common/src/main/java/org/apache/beam/sdk/io/hadoop/SerializableConfiguration.java
sdks/java/io/hadoop-format/src/main/java/org/apache/beam/sdk/io/hadoop/format/HadoopFormatIO.java
sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFn.java

**Changes:**
- Updated **Ubuntu** version for PreCommit Java Solace IO Direct
- Updated **Spotbugs** version (also needed for Java SolaceIO)
- Fixed **Spotbugs** issues found by new version for:
- Hadoop IO
- Amazon-Web-Services2 IO
- Pulsar IO
GitHub Actions …

Fix PreCommit Java Solace IO Direct job

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/status/BeamFnStatusClient.java

[Release-2.66] cherry-pick #35274 into release branch

---

.test-infra/mock-apis/build.gradle
examples/java/src/main/java/org/apache/beam/examples/KafkaStreaming.java
examples/java/src/main/java/org/apache/beam/examples/complete/TrafficRoutes.java
examples/java/src/main/java/org/apache/beam/examples/complete/datatokenization/utils/SchemasUtils.java
examples/java/src/main/java/org/apache/beam/examples/cookbook/TriggerExample.java
examples/java/src/main/java/org/apache/beam/examples/subprocess/configuration/SubProcessConfiguration.java
examples/kotlin/src/main/java/org/apache/beam/examples/kotlin/cookbook/TriggerExample.kt
it/common/src/main/java/org/apache/beam/it/common/utils/ResourceManagerUtils.java
runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/ExecutionStateSampler.java
runners/flink/src/main/java/org/apache/beam/runners/flink/metrics/FileReporter.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPTransformMatchers.java
runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java
runners/samza/src/main/java/org/apache/beam/runners/samza/container/ContainerCfgLoader.java
sdks/java/build-tools/src/main/resources/beam/spotbugs-filter.xml
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/CoderProviders.java
sdks/java/core/src/main/java/org/apache/beam/sdk/coders/DefaultCoder.java
sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/resourcehints/ResourceHints.java
sdks/java/extensions/ml/src/main/java/org/apache/beam/sdk/extensions/ml/AnnotateImages.java
sdks/java/io/debezium/build.gradle
sdks/java/io/debezium/src/main/java/org/apache/beam/io/debezium/KafkaSourceConsumerFn.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java
sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaExactlyOnceSink.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOUtils.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java
sdks/java/io/snowflake/src/main/java/org/apache/beam/sdk/io/snowflake/KeyPairUtils.java
sdks/java/io/synthetic/src/main/java/org/apache/beam/sdk/io/synthetic/SyntheticOptions.java
sdks/java/io/synthetic/src/main/java/org/apache/beam/sdk/io/synthetic/SyntheticStep.java
sdks/java/testing/jpms-tests/build.gradle
sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/NexmarkConfiguration.java

Fix Spotbugs

---

sdks/python/apache_beam/examples/snippets/transforms/elementwise/pardo_dofn_methods.py

Playground tests are running against latest released beam and this change assumed that tests will run against the current dev version - https://github.com/apache/beam/actions/runs/15573291125/workflow#L75 - temporary fix until the next release
GitHub Actions …

Unbreak Playground CI nightly suite

---

website/www/site/content/en/blog/beam-college-2025-anomaflow.md
website/www/site/data/authors.yml

This blog post shares my experience building Anomaflow, an Apache Beam-based anomaly detection pipeline, during the 2025 Beam College Hackathon. I placed 3rd in the competition and wanted to share my learnings and tips with the community.

Blog: My Experience at Beam College 2025 (3rd Place Hackathon Winner)

---

.github/trigger_files/beam_PostCommit_SQL.json
sdks/java/extensions/sql/src/main/codegen/config.fmpp
sdks/java/extensions/sql/src/main/codegen/includes/parserImpls.ftl
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/parser/SqlUseCatalog.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlCliTest.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/PubsubToBigqueryIT.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/PubsubToIcebergIT.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergReadWriteIT.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTableProviderTest.java

Cherrypicking #35314

---

.github/trigger_files/beam_CloudML_Benchmarks_Dataflow.json
.github/workflows/beam_CloudML_Benchmarks_Dataflow.yml

This will allow us to run these as actions runs …

Allow running TFT benchmarks from pr

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java
sdks/python/apache_beam/io/kafka.py

Add dynamic read support to KafkaIO in Python SDK

---

sdks/python/apache_beam/io/gcp/bigquery.py

added timeout for Direct_Read with Bigquery IO

---

sdks/python/apache_beam/transforms/async_dofn.py
sdks/python/apache_beam/transforms/async_dofn_test.py

Adds Async Dofns and their tests to BEAM.
Meant to be used in cases where processing is long and we don't want to block the GetWork/CommitWork streams waiting for the processing to finish synchronously.  Instead we buffer the item into state, add it to a queue, and commit the result when the item is finished using state and timers.
Takes a standard Dofn as input and does the dofns work asynchronously. …

Add Async Dofn and Test to BEAM

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Updates Dataflow Python container

---

.github/trigger_files/beam_PostCommit_SQL.json
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/parser/SqlCreateExternalTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/TableProvider.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergCatalog.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTableProvider.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/store/InMemoryMetaStore.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/PubsubToIcebergIT.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergReadWriteIT.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/iceberg/IcebergTableProviderTest.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergCatalogConfig.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergTableCreateConfig.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/PartitionUtils.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java
sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/TableAlreadyExistsException.java

Cherrypick #35341

---

it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/pubsub/PubsubIOLT.java

Fixes: #35194
Successful run example: https://github.com/akashorabek/beam/actions/runs/15690375458 …

Fix PubsubIOLT

---

examples/java/src/main/java/org/apache/beam/examples/complete/datatokenization/utils/SchemasUtils.java
examples/java/src/main/java/org/apache/beam/examples/subprocess/SubProcessPipelineOptions.java
examples/java/src/main/java/org/apache/beam/examples/subprocess/configuration/SubProcessConfiguration.java
examples/kotlin/src/main/java/org/apache/beam/examples/kotlin/cookbook/TriggerExample.kt
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaExactlyOnceSink.java
sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIOUtils.java
sdks/java/io/synthetic/src/main/java/org/apache/beam/sdk/io/synthetic/SyntheticStep.java

Part of #35312
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wh …

Fix suppressed Spotbugs issues

---

sdks/python/apache_beam/options/pipeline_options.py
sdks/python/apache_beam/runners/portability/sdk_container_builder.py
sdks/python/apache_beam/transforms/environments.py

Context: https://lists.apache.org/thread/rrpdj3b32cz8qhr23x82q9fbg0rn8crr …

Disable dependency logging in local envs

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ExecutionStateSampler.java

Fix data race ExecutionStateSampler.java:491 in ExecutionStateImpl.reset()

---

sdks/python/apache_beam/coders/coders_test_common.py

This is to prepare a test that would if standard cloudpickle replaced dill in pickling "special types" [1]
[1] https://github.com/apache/beam/blob/6ac5009dbfdfb32f558d90c8824e7e3ade04d618/sdks/python/apache_beam/coders/coder_impl.py#L529
https://github.com/apache/beam/issues/21298 …

Add cross-process determinism check for DeterministicFastPrimitivesCoder.

---

sdks/python/apache_beam/ml/rag/embeddings/vertex_ai.py
sdks/python/apache_beam/ml/transforms/embeddings/vertex_ai.py

For some reason, this recently broke linting - https://github.com/apache/beam/actions/runs/15922468937/job/44912189610
The complaints are mostly valid though. …

Fix vertex linting

---

sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java

These logs can't be controlled with SLF4J threshold levels and seem to serve no purpose in this class. I considered changing these to `LOG.trace(...)` calls, but I don't see the use for that if the histogram implementation is thoroughly tested.
GitHub Actions …

Remove stdout prints from HistogramData

---

it/common/src/main/java/org/apache/beam/it/common/PipelineLauncher.java
it/common/src/main/java/org/apache/beam/it/common/PipelineOperator.java
it/common/src/test/java/org/apache/beam/it/common/PipelineOperatorTest.java
it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DirectRunnerClient.java

ForceCancel should be much faster to stop a streaming job. …

added waitForConditionAndForceCancel

---

sdks/python/apache_beam/coders/coders_test_common.py

Internal tests use hermetic python that does not have sys.executable. Skip this test internally. …

Skip test if no python interpreter.

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.66.0.md
website/www/site/content/en/get-started/downloads.md
website/www/site/data/authors.yml

Update Beam website to release 2.66.0

---

.github/workflows/republish_released_docker_containers.yml

Update Republish Released Docker Images

---

.github/trigger_files/beam_PostCommit_Yaml_Xlang_Direct.json
sdks/python/apache_beam/yaml/integration_tests.py

fixes #35198
The failure is caused by the recent testcontainers upgrade.
See https://github.com/apache/beam/issues/35198#issuecomment-3027810930 for more details.

Fix yaml postcommit test failure

---

sdks/java/io/rabbitmq/src/main/java/org/apache/beam/sdk/io/rabbitmq/RabbitMqIO.java

Fixes https://github.com/apache/beam/issues/35082 …

RabbitMqIO doesn't handle closed channels

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/action/QueryChangeStreamAction.java

Previously, https://github.com/apache/beam/pull/34967 set query end timestamp to  now + 2mins. This is required for change stream APIs. However this violates  the checkDone logic and causes issues https://screenshot.googleplex.com/5nqt7kNYWNfAv8t.
After the fix, the issue is gone https://screenshot.googleplex.com/6dFwQw7VPAsTy8j

fix endtimestamp issue

---

contributor-docs/release-guide.md

Added some manual steps for the Yaml release doc since we haven't figure out how to fix https://github.com/apache/beam/issues/34694 . …

added the manual check for the Yaml release doc

---

.github/workflows/beam_PostCommit_Go_VR_Samza.yml
.github/workflows/beam_PostCommit_Python_ValidatesRunner_Samza.yml
.github/workflows/beam_PostCommit_XVR_Samza.yml
buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/samza/job-server/build.gradle
sdks/go/test/build.gradle
sdks/go/test/run_validatesrunner_tests.sh
sdks/python/scripts/run_job_server.sh
sdks/python/tox.ini

* Honor testJavaVersion property in toxTask
* Honor testJavaVersion property in Go Validation Runner Task
* Honor testJavaVersion property in XVR Samza task
After this PR, one can upgrade gradle plugins to versions that dropped Java8 support, e.g. redo #35324 , upgrade Gradle shadow plugin etc  …

Move remaining workflow to Java11

---

sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java

reconnect when publishMessage in JMS fails

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/BeamKafkaCSVTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/BeamKafkaTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/KafkaTableProvider.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/NestedPayloadKafkaTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/PayloadSerializerKafkaTable.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/kafka/KafkaTableProviderTest.java
website/www/site/content/en/documentation/dsls/sql/extensions/create-external-table.md

This change introduces watermark generation strategies for the BeamSQL's Kafka Table. Users can now define watermark.type and watermark.delay in TBLPROPERTIES to enable event-time processing and better handle out-of-order data in streaming pipelines.
GitHub …

Add watermark strategy for BeamSQL Kafka tables

---

sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datagen/AdvancingTimestampFn.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datagen/DataGeneratorPTransform.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datagen/DataGeneratorRowFn.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datagen/DataGeneratorTable.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datagen/DataGeneratorTableProvider.java
sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/datagen/package-info.java
sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/meta/provider/datagen/DataGeneratorTableProviderTest.java
website/www/site/content/en/documentation/dsls/sql/extensions/create-external-table.md

BeamSQL does not have Data Generator to test some basic functions. I created a Datagen Table that allows for creating tables based on in-memory data generation. This is useful for developing and testing queries locally without requiring access to external systems. The DataGen table is built-in; no additional dependencies are required.
Tables can be either bounded (generating a fixed number of rows) or unbounded (generating a stream of rows at a specific rate). The table provides fine-grained controls to customize the generated values for each field. …

BeamSQL Datagen Table Provider

---

sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOMetadata.java

Fixes https://github.com/apache/beam/issues/35401 …

added the job id for spanner IO

---

sdks/python/apache_beam/coders/proto2_coder_test_messages_pb2.py
sdks/python/apache_beam/examples/snippets/transforms/aggregation/groupby_test.py
sdks/python/apache_beam/io/gcp/experimental/spannerio_test.py
sdks/python/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py
sdks/python/apache_beam/io/requestresponse_test.py
sdks/python/apache_beam/ml/anomaly/detectors/pyod_adapter_test.py
sdks/python/apache_beam/ml/rag/chunking/langchain_test.py
sdks/python/apache_beam/ml/transforms/embeddings/huggingface_test.py
sdks/python/apache_beam/runners/dataflow/internal/clients/dataflow/dataflow_v1b3_client.py
sdks/python/apache_beam/runners/direct/direct_runner.py
sdks/python/apache_beam/transforms/enrichment_handlers/bigtable_it_test.py
sdks/python/apache_beam/transforms/enrichment_handlers/vertex_ai_feature_store_it_test.py

https://github.com/apache/beam/pull/34612 seems to be causing some tests to fail. I don't think we need a full revert, but we can go back to the fnapi runner as the default to get things to green while investigating.
As part of this, I modified some of the test changes I made so that they're portable (relying on the exception type showing up in the error string doesn't work on the fnapi runner where those exceptions are actually thrown at the top level)
See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job- …

Temporarily move back to fnapi runner as default

---

sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProvider.java
sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaReadSchemaTransformProviderTest.java

These changes will add support for the Managed Schema Registry solution provided by Google. It will determine if the Schema Registry URL is a Google SR link and apply some specific configs for the platform. It is backwards compatible as the old code path is the default code path for a normal SR link. …

Extend Schema Registry Support on Managed Kafka I/O to Google's Managed Schema Registry Solution

---

sdks/python/apache_beam/io/gcp/bigquery.py

Distinguishing bigquery logging failures severities

---

sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/catalog/IcebergCatalogBaseIT.java

Fixes #31931
Successful run: https://github.com/apache/beam/actions/runs/16437026965 …

Fix IcebergIO Integration Tests job

---

.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Dataflow.json
sdks/python/setup.py

This currently requires tox to be installed at runtime in all settings since this is not part of our container. Really we just shouldn't be requiring this at all since this is only a problem in test environments.
Marking as release blocking since it is a perf regression (and an EOU problem)
Cherry-pick of https://github.com/apache/beam/pull/35679 …

Cherrypick: Remove tox dependency

---

examples/notebooks/beam-ml/cloudsql_postgres_product_catalog_embeddings.ipynb
examples/notebooks/beam-mlcloudsql_postgres_product_catalog_embeddings.ipynb

Cloudsql pg colab

---

sdks/python/apache_beam/yaml/main.py

Fixes https://github.com/apache/beam/issues/35720 …

YAML Test CLI Flag Fix

---

examples/java/src/main/java/org/apache/beam/examples/cookbook/IcebergRestCatalogCDCExample.java
examples/java/src/main/java/org/apache/beam/examples/cookbook/IcebergRestCatalogStreamingWriteExample.java

Adding Example for CDC with Iceberg Rest Catalog. Sample run for the pipeline is attached below 
screenshot capturing both write and CDC pipelines working together
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tes …

Add Example for Iceberg REST Catalog CDC

---

sdks/python/apache_beam/examples/inference/gemini_text_classification.py
sdks/python/apache_beam/io/debezium.py

Fixes #30513
Successful tests: https://github.com/apache/beam/actions/runs/16547689442/job/46814158621 …

Fix PostCommit Python job

---

sdks/python/apache_beam/examples/inference/gemini_text_classification.py
sdks/python/apache_beam/io/debezium.py

[Cherrypick] Fix PostCommit Python job (#35709)

---

sdks/python/apache_beam/ml/transforms/base.py
sdks/python/apache_beam/yaml/yaml_ml.py
sdks/python/apache_beam/yaml/yaml_ml_test.py
sdks/python/setup.py

Reverts #35715 
Fixes #34739 ([run](https://github.com/apache/beam/actions/runs/16654659022)), Fixes #31006 ([run](https://github.com/apache/beam/actions/runs/16654633082)), Fixes #32603 ([run](https://github.com/apache/beam/actions/runs/16654618467))
GitHub …

Revert #35715 YAML and Python ML

---

buildSrc/src/main/groovy/org/apache/beam/gradle/Repositories.groovy

mitigate #35762
The repo has been sunset: https://central.sonatype.org/news/20250326_ossrh_sunset/ and causing intermittent build failure …

Remove OSSRH Sonatype from list of repos

---

sdks/python/apache_beam/ml/transforms/base.py
sdks/python/apache_beam/yaml/yaml_ml.py
sdks/python/apache_beam/yaml/yaml_ml_test.py
sdks/python/setup.py

#35693
I think the previously added import of 'tensorflow-text' in the Round 1 PR was causing issues with pyarrow and nptype. …

[Yaml] - fix ml embeddings issue round2

---

sdks/python/apache_beam/yaml/examples/transforms/ml/taxi_fare/streaming_taxifare_prediction.yaml

Fixes #31418
Fixes #30602
Fixes #30601
Fixes #30517
Successful workflow (Flink): https://github.com/A1K28/beam/actions/runs/16682909834
Successful workflow (Samza): https://github.com/A1K28/beam/actions/runs/16682918253
Successful workflow (Spark3): https://github.com/A1K28/beam/actions/runs/16682927799
Successful workflow (DirectRunner): https://github.com/A1K28/beam/actions/runs/16682929064 …

Fix ValueError affecting XVR tests

---

sdks/python/scripts/run_pytest.sh

fix: sdks/python/scripts/run_pytest.sh had a problem with Windows slashes.
successful run: https://github.com/A1K28/beam/actions/runs/16733691278
fixes #30528 …

fix windows slashes for dask (#30528)

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/CachingFactory.java
sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FromRowUsingCreator.java

Switch to double-checking locking for lazy initialization to address a race condition on initialization. 
[![Build …

Fix race conditions in apache.beam.sdks.schemas

---

sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go
sdks/go/pkg/beam/runners/prism/internal/stage.go
sdks/go/pkg/beam/runners/prism/internal/worker/bundle.go

Fix a split bundle bug when using timers in stateful dofn

---

sdks/go/pkg/beam/options/jobopts/options.go

Fix go linting issues in options.go …

Fix options.go flag comments

---

examples/java/build.gradle
examples/java/src/main/java/org/apache/beam/examples/cookbook/IcebergBatchWriteExample.java

Adding Example for Batch Write with Iceberg BigQuery Metastore. Sample run for the pipeline is attached below
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3 …

Metastore example

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/ChannelCache.java
runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/stubs/ChannelCacheTest.java

The previous logic only used the default before any config update was issued. However we always update the config, so this never used the default.  Fixed by changing default handling to be based upon empty proto instead of null.
The added unit test fails with the previous logic. …

[Dataflow Java Streaming] Fix defaulted flow control settings for grpc stream.

---

.github/workflows/beam_PreCommit_Java_Kafka_IO_Direct.yml

Enable parallel for KafkaIO precommit …

Re-enable parallel for KafkaIO precommit

---

sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcIO.java

Fix JdbcIO.read log spam when autocommit disabled

---

sdks/java/javadoc/overview.html
sdks/python/apache_beam/ml/anomaly/transforms.py
website/www/site/content/en/get-started/downloads.md

Fix API doc index page broken format and link

---

sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java

Slide the construction and returned split into the synchronized block in trySplitForElementAndRestriction
[![Build …

Fix race condition in FnApiDoFnRunner.java

---

examples/notebooks/beam-ml/cloudsql_mysql_product_catalog_embeddings.ipynb

Cloudsql MySQL embeddings colab.

---

runners/google-cloud-dataflow-java/build.gradle
sdks/python/apache_beam/runners/dataflow/internal/names.py

Bump DF image tags
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/buil …

Bump DF Java Python container tags

---

.github/workflows/republish_released_docker_containers.yml

Update Republish Released Docker Containers

---

playground/backend/containers/router/Dockerfile

Fix Deploy-Update-Playground-environment-stg Cloud Build trigger

---

sdks/python/apache_beam/io/gcp/bigquery_test.py

This test has been a bit flaky and it may be because Prism doesn't always handle mocking well (because mocking isn't fully portable) …

Pin a mocking test to DirectRunner

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcCommitWorkStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcDispatcherClient.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/client/grpc/GrpcGetWorkerMetadataStream.java
runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/work/processing/StreamingWorkScheduler.java

[Dataflow Java Streaming] Reduce log spam for direct path mode and improve status page.

---

sdks/python/container/Dockerfile

Ensurepip is packaged with old wheels of setuptools and pip. This can cause issues with vulnerability tools; this fixes the problem by upgrading those wheels and manually removing the bad wheels.
Trying this here - https://github.com/apache/beam/actions/runs/17051864149 …

Update ensurepip to avoid vulnerabilities in wheels

---

sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java
sdks/java/io/file-based-io-tests/src/test/java/org/apache/beam/sdk/io/text/TextIOIT.java

Fixes https://github.com/apache/beam/issues/33330 …

Controlling reshuffle in `FileIO.MatchAll`

---

sdks/go/test/integration/integration.go

Fixes #34989
Successful run: https://github.com/apache/beam/actions/runs/17092124680 …

Fix PostCommit Go VR Samza job

---

CHANGES.md
release/build.gradle.kts
runners/samza/src/main/java/org/apache/beam/runners/samza/SamzaRunner.java
runners/twister2/src/main/java/org/apache/beam/runners/twister2/Twister2Runner.java
website/www/site/content/en/documentation/runners/nemo.md
website/www/site/content/en/documentation/runners/samza.md
website/www/site/content/en/documentation/runners/twister2.md
website/www/site/content/en/roadmap/nemo-runner.md
website/www/site/content/en/roadmap/samza-runner.md
website/www/site/content/en/roadmap/twister2-runner.md

* Deprecate Samza runner (#35448)
* Deprecate Twister2 runner (#35905)
* Remove twister2 runner test from validation task and consolidate validation task
* Note nomi runner as retired in website
GitHub …

Runner support status for Beam 3

---

runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java

Fixes #31914 by adding stream.toByteStringAndReset() before each encode call in WindmillSink$WindmillStreamWriter.add to clear residual data, preventing IllegalStateException. …

[Java]Fix IllegalStateException in WindmillSink by Clearing Stream Before Encoding (#31914)

---

.github/workflows/beam_StressTests_Java_KafkaIO.yml

Fix StressTests Java KafkaIO job

---

sdks/python/apache_beam/runners/interactive/pipeline_instrument_test.py

Fix an incorrect indentation in an import that breaks the python linting check. …

Fix linting breakage in pipeline_instrument_test.py

---

sdks/python/tox.ini

Fixes #31285
Successful run: https://github.com/apache/beam/actions/runs/17317800076 …

Fix PreCommit Python ML tests with ML deps installed job

---

examples/yaml/README.md
sdks/python/apache_beam/yaml/examples/transforms/ml/sentiment_analysis/README.md
sdks/python/apache_beam/yaml/examples/transforms/ml/sentiment_analysis/streaming_sentiment_analysis.yaml
sdks/python/apache_beam/yaml/examples/transforms/ml/taxi_fare/README.md
sdks/python/apache_beam/yaml/examples/transforms/ml/taxi_fare/custom_nyc_taxifare_model_deployment.ipynb
sdks/python/apache_beam/yaml/examples/transforms/ml/taxi_fare/streaming_taxifare_prediction.yaml

Part of the larger effort https://github.com/apache/beam/issues/35068 to add more YAML example pipelines.
Update some YAML example pipelines for user accessibility and visibility. …

YAML example suite update

---

CHANGES.md

Fix: Correctly assign feature (https://github.com/apache/beam/pull/35453) to the next release and fixing format.  …

Fix: Correctly assign feature to release

---

sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/core_test.py

Right now, user state and timers will error out if you try to access them from process in a DoFn with with_exception_handling. This PR allows state support, but opt-in only since it is potentially unsafe.
Part of https://github.com/apache/beam/issues/35976
GitHub …

Allow stateful exception handling

---

examples/notebooks/beam-ml/data_preprocessing/huggingface_text_embeddings.ipynb

Update notebook to use embedding gemma

---

sdks/python/apache_beam/transforms/core.py
sdks/python/apache_beam/transforms/core_test.py

CP: #36044 
[![Build python source distribution and wheels](https://github.com/apache/beam/actions/workflows/build_wheel …

fix(Partition): support numpy integer types in partition validation 

---

sdks/python/apache_beam/yaml/examples/README.md
sdks/python/apache_beam/yaml/examples/transforms/ml/fraud_detection/fraud_detection_mlops_beam_yaml_sdk.ipynb

YAML example suite minor updates
Part of the larger effort https://github.com/apache/beam/issues/35068 …

YAML example suite minor updates

---

sdks/java/io/mqtt/src/main/java/org/apache/beam/sdk/io/mqtt/MqttIO.java
sdks/java/io/mqtt/src/test/java/org/apache/beam/sdk/io/mqtt/MqttIOTest.java

Fix MqttIO read checkpoint logic

---

sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/GrowableOffsetRangeTracker.java

Use unsigned integer math to calculate differences between range start, consumed and estimated end positions. The difference between two values does not exceed the maximum value of unsigned longs so BigDecimal isn't strictly necessary here. For high volume consumption in KafkaIO this reduces CPU time spent in RestrictionTracker.getProgress by ~30x. …

[GrowableOffsetRangeTracker] Use UnsignedLong instead of BigDecimal to calculate progress

---

sdks/python/test-suites/portable/common.gradle

Cherrypick #36098

---

sdks/python/apache_beam/yaml/examples/transforms/jinja/import/README.md
sdks/python/apache_beam/yaml/examples/transforms/jinja/include/README.md

#35909 - found a few minor errors with the pipeline calls …

[YAML] - update readme to correct pipeline calls

---

buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
runners/google-cloud-dataflow-java/worker/build.gradle
sdks/java/extensions/sql/hcatalog/build.gradle

This cherrypicks #36106 to the 2.67.0 postrelease branch, where it should be automatically updating the containers. …

[2.67.0 postrelease] Fix CVE-2025-48734, CVE-2024-13009 (#36106)

---

sdks/python/apache_beam/examples/snippets/transforms/elementwise/enrichment_test.py

this test is flaky with this error:
```
=================================== FAILURES ===================================
_____________ EnrichmentTest.test_enrichment_with_vertex_ai_legacy _____________
[gw1] linux -- Python 3.9.22 /runner/_work/beam/beam/sdks/python/test-suites/tox/py39/build/srcs/sdks/python/target/.tox-py39-cloud/py39-cloud/bin/python
self = <apache_beam.examples.snippets.transforms.elementwise.enrichment_test.EnrichmentTest testMethod=test_enrichment_with_vertex_ai_legacy>
mock_stdout = <_io.StringIO object at 0x78825a2ccf70>
def test_enrichment_with_vertex_ai_legacy(self, mock_stdout):
enrichment_with_vertex_ai_legacy()
output = mock_stdout.getvalue().splitlines()
expected = validate_enrichment_with_vertex_ai_legacy()
self.maxDiff = None
>     self.assertEqual(output, …
```

Sort output before comparison in enrichment test

---

.github/trigger_files/IO_Iceberg_Integration_Tests.json
.github/trigger_files/IO_Iceberg_Managed_Integration_Tests_Dataflow.json
.github/trigger_files/beam_PostCommit_Python_Xlang_IO_Direct.json
sdks/java/io/iceberg/build.gradle

To handle [CVE-2025-47436](https://orc.apache.org/security/CVE-2025-47436/)

[IcebergIO] pin ORC 1.9.6

---

sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/HarnessMonitoringInfosInstructionHandlerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/control/ProcessBundleHandlerTest.java
sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/MultimapUserStateTest.java

There is no guarantee on the order keys are returned. Also fixes a couple warnings from other FnApi tests.
[![Build …

Changes multimap state keys() tests to not care about order. 

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Bump python SDK harness to beam-master-20250917

---

sdks/go/pkg/beam/core/runtime/harness/harness.go
sdks/go/pkg/beam/core/runtime/harness/harness_test.go

Only report timeout duration parsing error during harness start.

---

sdks/python/apache_beam/yaml/yaml_io.py
sdks/python/apache_beam/yaml/yaml_io_test.py

Fixes https://github.com/apache/beam/issues/36039 …

Add support for PROTO format in YAML Pub/Sub transform

---

CHANGES.md
website/www/site/config.toml
website/www/site/content/en/blog/beam-2.68.0.md
website/www/site/content/en/get-started/downloads.md

Update Beam website to release 2.68.0

---

.github/workflows/code_completion_plugin_tests.yml

Allow manually running code_completion_plugin_tests.yml

---

model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/external_transforms.proto
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/providers/ReadFromSqlServerSchemaTransformProvider.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/providers/SqlServerSchemaTransformTranslation.java
sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/providers/WriteToSqlServerSchemaTransformProvider.java
sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/providers/SqlServerSchemaTransformTranslationTest.java
sdks/java/managed/src/main/java/org/apache/beam/sdk/managed/Managed.java
sdks/python/apache_beam/transforms/managed.py

Managed JDBCIO (Part 3) - SqlServer
Similar to #36034 and #36045

Support managed jdbc io (SQLServer) 

---

CHANGES.md

Fix changes whitespace

---

sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/logicaltypes/OneOfType.java
sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/logicaltypes/LogicalTypesTest.java

Allow nullable subfields for `OneOfType` to fix YAML python integration test failure caused by #35150. …

Fix broken PreCommit YAML Xlang Direct 

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Update container image to newly released version
https://pantheon.corp.google.com/artifacts/docker/cloud-dataflow/us/gcr.io/v1beta3%2Fbeam_python3.12_sdk/sha256:54ada041c8826261d4c1a34542803324f7b2d58930c077ef5ac22b0f410ebc5f
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)](https:/ …

Update python SDK container image

---

.github/workflows/beam_PreCommit_Python_Dill.yml

Adds a dill test workflow that installs the apache-beal[dill] extra and runs dill tests. …

Add dill test workflow

---

.github/workflows/beam_PreCommit_Python_Dill.yml

Remove workflow_run.

---

sdks/python/container/py310/base_image_requirements.txt
sdks/python/container/py311/base_image_requirements.txt
sdks/python/container/py312/base_image_requirements.txt
sdks/python/container/py313/base_image_requirements.txt
sdks/python/container/py39/base_image_requirements.txt

Update Beam container deps. 
google-cloud-secret-manager==2.24.0 is an apache beam 'extra' dependency, and pip check doesn't detect that it wasn't installed in https://github.com/apache/beam/blob/340d420c2d315a4cb9ec419606356a109b867d3d/sdks/python/container/Dockerfile#L75C1-L76C1
Full dependency upgrade to be done with the GHA job that was recently fixed: https://github.com/apache/beam/issues/30518 …

Add google-cloud-secret-managager to beam python container deps

---

playground/backend/containers/java/Dockerfile
playground/infrastructure/ci_cd.py

Fix sql example in playground

---

sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoBeamConverter.java
sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtobufUtil.java

An error level errorprone finding when readObject used in non-private method.
https://errorprone.info/bugpattern/BanSerializableRead
blocked internal code import …

Fix errorprone move serialization to private method

---

sdks/python/apache_beam/runners/dataflow/internal/names.py

Verified Google Cloud Secret Manager added to dependency
https://pantheon.corp.google.com/artifacts/docker/cloud-dataflow/us/gcr.io/v1beta3%2Fbeam_python3.10_sdk/sha256:e461e84d52839a7d5882d78d8a4a4b2cb89078c5c2dafefce6f34063f8bd323f
[![Python tests](https://github.com/apache/beam/actions/workflows/python_tests.yml/badge.svg?event=schedule&&?branch=master)] …

Update Python SDK container

---

sdks/python/apache_beam/internal/metrics/cells.py
sdks/python/apache_beam/internal/metrics/metric_test.py
sdks/python/apache_beam/metrics/execution.py
sdks/python/apache_beam/metrics/metric.py
sdks/python/apache_beam/metrics/monitoring_infos.py
sdks/python/apache_beam/metrics/monitoring_infos_test.py
sdks/python/apache_beam/runners/direct/direct_metrics.py
sdks/python/apache_beam/utils/histogram.py

Resolves #36267
Implement the Histogram metric for the python SDK.
I'm going to do the actual moving of all histogram related stuff from `internal/metric.py` to the public `metric.py` in a separate PR to make this PR easier to review. …

Implement histogram user metric for python SDK

---

sdks/python/apache_beam/programming_guide_test.py

We missed this in https://github.com/apache/beam/pull/36334 …

Add back missing licenses

---

infra/iam/users.yml

This PR adds Ibrahim’s user access configuration to users.yml …

Add ibrahim user access

---

sdks/java/io/components/src/main/java/org/apache/beam/sdk/io/components/throttling/ThrottlingSignaler.java

Adds a class for the worker to signal to the runner that a remote call is being throttled. This abstracts the current counter method away from the user such that it can be replaced in the future. 
Java version of #35984 …

Add ThrottlingSignaler class to the Java SDK

---

infra/iam/users.yml

Add permissions for storage

---

sdks/python/apache_beam/transforms/core.py

This previously worked since the superclass accepts a label …

Allow passing label through GBK
